### ISSUE TITLE
weapon training order

### ISSUE THREAD

**Issue by clapplegate** [rpherbig/dr-scripts#1]
when all combat skills are 0/34 offhand is selected before a skill that trains using a main hand weapon resulting in its combat maneuver failing

**Comment by rcuhljr** [comment]
Good find, the guy who added combat maneuvers isn't the guy who uses offhand weapons.

**Comment by rpherbig** [comment]
I don't think this has anything to do with charged maneuvers. The charged maneuvers logic just determines which attack action to fput. Charged maneuvers are always executed before standard attacks though.

Looking over the code, I what is happening is that you wield the offhand weapon, then swap (line 422-ish) and end up with an empty right hand.

**Comment by rpherbig** [comment]
@clapplegate I realized my response may have been taken wrong. I don't want you to think I was being negative - we really appreciate you filing this.

Nice catch :)
