### ISSUE TITLE
Add support for sad people without zills

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#100]

**Comment by rpherbig** [comment]
This seems similar to the case in which someone has marked Forging for training but hits one of the NYI cases. A more "permanent" (where "permanent" is defined as the current execution of the script) version of #72?

In this case, should we remove the skill from the training list?

**Comment by rpherbig** [comment]
@rcuhljr Any objections to me removing Performance from the skill list when the character has no zills?

**Comment by rcuhljr** [comment]
That's a fine stopgap for now, while you're there make appraise go straight to the art appraisals

**Comment by rpherbig** [comment]
From rank 1? I thought assessing was faster in the beginning...

**Comment by rcuhljr** [comment]
Go straight to art appraisal if you don't have zills.
