### ISSUE TITLE
Dependency install failing(?) on fresh lich.

### ISSUE THREAD

**Issue by Zhennlash** [rpherbig/dr-scripts#1014]
Heya. Lich has been configured (linux). All default scripts have been ;trust(ed).
Dependency was downloaded, ;trust(ed), and ran (install).

 The following is returned during install, after some successful autostart stuff.

> Finished install!
> --- Lich: error: $SAFE=2 to 4 are obsolete
> 	lich.rbw:2533:in `block (3 levels) in <class:Script>'
> 	lich.rbw:2533:in `block (2 levels) in <class:Script>'
> >
> [dependency: Update found for dependency.lic]
> [dependency: Restarting Dependency in 2 seconds...]
> --- Lich: error: $SAFE=2 to 4 are obsolete
> 	lich.rbw:2533:in `block (3 levels) in <class:Script>'
> 	lich.rbw:2533:in `block (2 levels) in <class:Script>'
> >
> --- Lich: dependency active.
> --- Lich: error: $SAFE=2 to 4 are obsolete
> 	lich.rbw:2533:in `block (3 levels) in <class:Script>'
> 	lich.rbw:2533:in `block (2 levels) in <class:Script>'

Note I'm seeing these "block" messages all over when running scripts, and still must manually ;trust scripts added by Dependency.

Any thoughts? =(

**Comment by rpherbig** [comment]
Can you `;list trusted` and paste the output here?

**Comment by Zhennlash** [comment]
Sure thing;

> >;list trusted
> --- Lich: trusted scripts: repository, lnet, narost, alias, autostart, favs, go2, infomon, lnet, mapmap, narost, repository, settings, vars, dependency

**Comment by rpherbig** [comment]
That looks ok.

Can you open a command prompt and tell me what `ruby -v` outputs?

**Comment by rpherbig** [comment]
Or `;e echo RUBY_VERSION` would also work

**Comment by Zhennlash** [comment]
> ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

and 

> >;e echo RUBY_VERSION
> --- Lich: exec1 active.
> [exec1: 2.3.1]

Respectively.

Here is a curated list of installed gems as well;

> gtk2 (3.0.7)
> sqlite3 (1.3.12)
> rest-builder (0.9.1)
> rest-core (4.0.0)
> rest-firebase (1.1.0)

**Comment by rpherbig** [comment]
That would be the problem. Lich requires Ruby 2.0.0 to work:
```
>;e echo RUBY_VERSION
--- Lich: exec1 active.
[exec1: 2.0.0]
--- Lich: exec1 has exited.
```

**Comment by Zhennlash** [comment]
D'oh!

Thanks a lot. =)
