### ISSUE TITLE
Foging - unable to forge light throwing axe

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1023]
[forge]>pound light throwing axe on anvil with my hammer
I could not find what you were referring to.
>
[forge: *** ERROR TRYING TO CRAFT, EXITING ***]

On the iron anvil you see a light unfinished steel throwing axe.

NEEDS ADJUST FOR "LIGHT"

>pound throwing axe on anvil with my hammer
Sparks fly into the air as you transfer the axe back and forth between the forge fires and the anvil, alternating heating with vigorous hammering of the metal.  With expert precision the metal takes shape without any faults.
Roundtime: 15 sec.

**Comment by rpherbig** [comment]
I made one of these last night, so I know it is possible

What arguments did you pass to forge?

**Comment by Aurayn** [comment]
I tried:
;forge weaponsmithing 1 "throwing axe" steel "throwing axe"
;forge weaponsmithing 1 "light throwing axe" steel "light throwing axe"

**Comment by rpherbig** [comment]
Try ;smith steel "throwing axe"

**Comment by Aurayn** [comment]
with no chapter numbers?
