### ISSUE TITLE
;bescort failure - Lich: 'escort' tried to stop 'scholarship', but it isn't running!

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1024]
More \ continued issues with ;bescort from NTR to guardians

See bolded below, very odd

[go2]>ne

You run northeast.
[Northern Trade Road, Wooded Valley]
You come upon a small clearing in the heavy woods that allows a view of the sky.  A faint path can be made out that wanders into the trees, but it fades off before you can wonder about where it might lead.  There is an unnerving quiet here, even the wind seems to have died.  You feel a stranger in this wild place, perhaps an unwelcome stranger.  You also see a faded roadsign.
Also here: Deatly.
Obvious paths: northeast, southwest.

Room Number: 1176

[go2]>go path

[Wilderness, Overgrown Path]
A faint trail fades to nothing more than a thin break in the undergrowth, but seems to faintly curve east to southwest.  An occasional rustle from areas unseen is a soft reminder that the solitude of the area is only an illusion.  
Obvious paths: none.

Room Number: 8010

--- Lich: escort active.

[escort]>look

[Wilderness, Overgrown Path]
A faint trail fades to nothing more than a thin break in the undergrowth, but seems to faintly curve east to southwest.  An occasional rustle from areas unseen is a soft reminder that the solitude of the area is only an illusion.  
Obvious paths: none.

Room Number: 8010

[escort]>search

You search around for a moment.
Roundtime: 2 sec.
You find a faint path and faint traces of an animal trail.

[escort]>go trail

The trail closes in behind you.
[Wilderness, Overgrown Path]

[escort]>look

Tangled underbrush creates a thick lattice here.  The barest motion sends thin branches biting into skin.  Tiny tufts of fur snagged on undergrowth show that two-legged creatures aren't the only ones caught by surprise.  
Obvious paths: north.

Room Number: 8011

[Wilderness, Overgrown Path]
Tangled underbrush creates a thick lattice here.  The barest motion sends thin branches biting into skin.  Tiny tufts of fur snagged on undergrowth show that two-legged creatures aren't the only ones caught by surprise.  
Obvious paths: north.

Room Number: 8011

[escort]>search

You search around for a moment.
Roundtime: 2 sec.
You find very faint traces of an animal trail.

[escort]>go trail

The trail closes in behind you.
[Wilderness, Overgrown Path]
Reaching up from a low thicket, slender branches arc high overhead, shutting out most of the sky.  Prickly shoots from the undergrowth thrust forth in all directions.  
Obvious paths: north.

Room Number: 8012

[escort]>look

[Wilderness, Overgrown Path]
Reaching up from a low thicket, slender branches arc high overhead, shutting out most of the sky.  Prickly shoots from the undergrowth thrust forth in all directions.  
Obvious paths: north.

Room Number: 8012

[escort]>search

Your feet are still soaked.
You search around for a moment.
Roundtime: 2 sec.
You find a faint animal trail.

[escort]>go trail

The trail closes in behind you.

[escort]>look

[Wilderness, Dry Streambed]
A lively brook once bubbled through the narrow gully, but time and drought have left only this cracked streambed as a reminder.  You also see a weathered signpost and an animal trail.
Obvious paths: none.

Room Number: 7958

[escort]>search

[Wilderness, Dry Streambed]
A lively brook once bubbled through the narrow gully, but time and drought have left only this cracked streambed as a reminder.  You also see a weathered signpost and an animal trail.
Obvious paths: none.

Room Number: 7958

You search around for a moment.
Roundtime: 2 sec.
You find some faint animal tracks and a bare spot that leads southeast into the deep wilderness.

[escort]>go spot

[Wilderness]
Scraggly trees grow close together, poking up through the wild, arching brush.  Toward the southeast, the woods and undergrowth thicken into a dark, tangled mass, making travel confusing at best.  
Obvious paths: east, south, northwest.
Blazed trails:  none.

[escort]>look

Room Number: 7957

[Wilderness]
Scraggly trees grow close together, poking up through the wild, arching brush.  Toward the southeast, the woods and undergrowth thicken into a dark, tangled mass, making travel confusing at best.  
Obvious paths: east, south, northwest.
Blazed trails:  none.

Room Number: 7957

**--- Lich: 'escort' tried to stop 'scholarship', but it isn't running!

--- Lich: escort has exited.

[go2]>**

[go2: move: no recognized response in 30 seconds.  giving up.]

[go2: restarting script...]

[go2: ETA: 0:00:06 (17 rooms to move through)]

[go2]>

[go2: move: no recognized response in 30 seconds.  giving up.]

[go2: restarting script...]

**Comment by rcuhljr** [comment]
I fixed the 7957 thing already. Someone deleted the northwest move out of that room in the map.
