### ISSUE TITLE
Support multiple castings of CF

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#1026]
You can cast CF more than once if your thanatology allows it. Each multiple of ~70 ranks (something like that. elanthipedia has the details) nets you an extra cast. My question would be: should we just look at thana ranks and set the value or let it be user-specified?

**Comment by rpherbig** [comment]
If it is a static game mechanic, I'd use Thanatology ranks (similar to what we do for Arcana and cambrinth).

**Comment by jandersson** [comment]
Makes sense. Here's the elanthipedia page for reference: https://elanthipedia.play.net/Consume_Flesh
