### ISSUE TITLE
Training-manager should find a room with NPCs in it

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#103]
Instead of finding an empty room, it should search for a room with NPCs in it.

To avoid matching familiars and the like, we should provide a list of target NPCs (i.e. 'bear') that we can match against DRRoom.npcs.

Implementation-wise, I'm thinking we might change our hunting_info array to a hash:
`
@reavers = { 'npcs' => ['reaver', 'hound'], 'rooms' => [1850, 1851, 1852, 1856, 1848, 1849] }
`

**Comment by rpherbig** [comment]
And then the predicate arg to find_empty_room? would be:
`
proc { DRRoom.npcs.count > 0 && DRRoom.npcs.all? { |npc| npcs.include? npc } }
`

**Comment by rpherbig** [comment]
Per @rcuhljr , the big issue here is avoiding rooms that stealth PCs are hunting in.

**Comment by rpherbig** [comment]
@rcuhljr Would it be sufficient for training-manager to monitor for either 1) "jumps out of the shadows" messages; or 2) see if another PC stays in the room for more than a few seconds?

**Comment by rcuhljr** [comment]
possibly? but the logic doesn't exist and it needs to. and it should only check after arriving in the room for a window, someone sneaking in later and talking to us shouldn't make us leave.
