### ISSUE TITLE
The battle of Holy oil vs Flask of oil in the Forging Ring

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#1035]
When training both Theurgy and Forging in Crossing-Training.....

The forging script usually grabs my holy oil, pours the entire contents on to the completed work order item...and then it doesn't know what to do with itself.

In the past, I've kept my holy oil in a closed container....but now that I've added Theurgy to Crossing-training that is not an option.

Would it be possible for the forging script to specifically identify and use a flask of oil (instead of holy oil)?

Or if not possible, maybe designate a specific container for said oil?

Thanks!

Gabellia

**Comment by rcuhljr** [comment]
Ok, should have a workaround in place. Add this to your yaml.

```crafting_items_in_container:
- oil```

and make sure you have a a `crafting_container` set up as well.
