### ISSUE TITLE
;moonwatch does not work during moon rises/sets

### ISSUE THREAD

**Issue by reithir** [rpherbig/dr-scripts#1036]
After Katamba and Yavash set, got some strange output from moonwatch, and it's not figuring out when moons are up or down. At this moment moonwatch is showing this:

[k]-(-42) [y]-(-48) [x]+(61)

Weird double negative number and it's counting up and instead of down.

**Comment by rpherbig** [comment]
@rcuhljr Any ideas on this one?

**Comment by reithir** [comment]
Thanks for looking into this Robert and Robert. :) Let me know if you need my help debugging, I'm around all weekend.

**Comment by rcuhljr** [comment]
It's not an issue with them setting, it's an issue with the connection to the moonwatch db dying after it's been open for a long time. I haven't found a way to successfully kill and restart the connection yet short of restarting SF.

**Comment by rpherbig** [comment]
If we can't recover, can we at least detect the problem and notify the user
they need to restart SF?

**Comment by reithir** [comment]
That's a bummer, but a warning system would be nice if the root cause can't be fixed. Restarting SF isn't the end of the world, but it would put a damper on using ;learn. ;-)

**Comment by reithir** [comment]
It went by quickly and I didn't capture it but I saw a message today that said something like ";dependency is restarting the connection to the ;moonwatch server", was this a change you guys made? I've had a lot of meetings today but it looks like ;moonwatch has been working well as far as I've seen today, but I haven't been watching it all that much. What's going on here, anything?

**Comment by rcuhljr** [comment]
Should be fixed.
