### ISSUE TITLE
ALCHEMY - wont choose anything BUT Neck Potion

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1039]
Which is a problem as Neck Potion doesn't work:  SEE ALCHEMY - Neck Potion not working #987

I had bypassed this for a week or so by changing the base-recipies to:

- name: a neck potion
  noun: potion
  volume: 1
  type: remedies
  **work_order: false**
  chapter: 4
  container: bowl
  herb1: riolur
  herb1_stock: 8

I then commented out this entire section - same issue
I then deleted this entire section - same issue
I then renamed the base-crafting.yaml from profile - same issue

each test dependency was closed and that instance of SF was relaunched
for the final test I closed all instances of SF and deleted all local base-recipies - same issue

Maybe just fixing SEE ALCHEMY - Neck Potion not working #987 to UNTIE the stick versus GETting it might be simplest?

**Comment by Dartellum** [comment]
This still a symptom for you? If not, could you close this issue?
