### ISSUE TITLE
Athletics: Specify a 'climb practice' target similar to how hunting zones are done

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#1043]
Currently the athletics training utilizes two methods: running a circuit around crossing as well as climb practice around the Shard undergondola. I would argue that it would diversify training if we could have a list of climbing targets, similar to base-hunting, which we do climb practice on for athletics training. The climbing circuit is nice because it is lazy but it is difficult to design one that is efficient. 

I'd like to suggest an idea for training athletics where we specify an athletics_zone, just like hunting_zone, and we go there and do `climb practice thing`. It would be up to the user to decide if this is an appropriate spot for their skills.

**Comment by jayRyan24** [comment]
Have you started groundwork on this yet? I'd let to set it up ASAP for places like Shard and Hib. Would like to spend this weekend on it actually, we can collaborate.

**Comment by jayRyan24** [comment]
Could very well work like hunting does, A file Base-athletics.yaml, and the personal yaml could have something like:

athletics_training:
- :room: under_gondola
  args:
  - ladder

**Comment by jandersson** [comment]
https://github.com/rpherbig/dr-scripts/pull/1090

**Comment by jandersson** [comment]
Ive got something like that in place in the above pull request, let me know what you think. Would appreciate it.
