### ISSUE TITLE
Combat Trainer: Offhand Thrown Weapon Problems

### ISSUE THREAD

**Issue by ndriskell** [rpherbig/dr-scripts#1044]
Hello, I am new to this so excuse my ignorance. How do you set up an offhand weapon to be thrown in your .yaml profile? Right now I have it so my bola is thrown from the offhand, but nothing is in my main hand, so I have no weapon to Parry with. Here is my .yaml profile relating to the matter:

weapon_training:
  Brawling: ''
  Small Edged: short sword
  Small Blunt: bola
  Offhand Weapon: bola
  Light Thrown: bola

offhand_thrown: Light Thrown

I do not see how to tell it to place a weapon in my main hand when throwing my bola. 

Thanks.

**Comment by rcuhljr** [comment]
If you want to parry while using thrown, you'll want to equip a parry stick. If you don't want to parry, see my response to your stances post.

**Comment by ndriskell** [comment]
My goal was to hold my sword in my right hand and my bola in my left, throwing the bola. The bola does go to my left hand and is thrown from it, but my right hand is empty. If this is by design that is fine, I was just wondering if that was possible. Thanks.

**Comment by rcuhljr** [comment]
Not currently supported, mainly because two weapons makes skinning and looting more complicated.

**Comment by ndriskell** [comment]
Ah ok, thanks.
