### ISSUE TITLE
Combat Trainer: Stances

### ISSUE THREAD

**Issue by ndriskell** [rpherbig/dr-scripts#1045]
Hello, how do stances work in a .yaml profile? Is it possible to set numeric values for evasion, parry, and shield? 

It seems for me my stances are changed at random, often with many of the points not being used. I have the following lines in my .yaml profile:

stances:
  Small Edged:
  - Evasion
  - Parry Ability
  - Shield Usage

  Small Blunt:
  - Evasion
  - Shield Usage
  - Parry Ability

  Light Thrown:
  - Evasion
  - Shield Usage
  - Parry Ability

  Brawling:
  - Evasion
  - Shield Usage

stance_override:

They seem to do nothing and it all appears random. For example, when using light thrown evasion is often turned off. I just may be ignorant on how it works. Thanks.

**Comment by ndriskell** [comment]
I figured out the problem, it was ignorance. 

You cannot have spaces between the stances. Below is my stances section which is now working:

stances:
  Offhand Weapon:
  - Evasion
  - Shield Usage
  - Parry Ability
  Small Edged:
  - Parry Ability
  - Evasion
  - Shield Usage
  Light Thrown:
  - Evasion
  - Shield Usage
  - Parry Ability
  Brawling:
  - Evasion
  - Shield Usage
  - Parry Ability
  Small Blunt:
  - Parry Ability
  - Evasion
  - Shield Usage

Notice how there are no spaces between anything. I assume this is because it is an array. I have closed this thread.

**Comment by rcuhljr** [comment]
You'll want to highlight your sample yaml in the future and select insert code formatting option so that it doesn't turn them into markdown, makes it hard to read as YAML.

**Comment by ndriskell** [comment]
Thanks for the info, I did not know.
