### ISSUE TITLE
Add support for chest harness "You slip" messaging.

### ISSUE THREAD

**Issue by jayRyan24** [rpherbig/dr-scripts#1049]
Add support for the messaging "You slip <weapon>" to Equipment Manager".

**Comment by rpherbig** [comment]
I thought this was done in 5be0418 to fix #1033. Have you restarted
dependency lately?

**Comment by jayRyan24** [comment]
I did, but for some reason I hadn't gotten an update for this. I'm not really sure what the issue is, but I completely wiped my lich and started over picking this up. I went to merge my changes, and uh, it was done. I thought you guys just did it that quickly.
