### ISSUE TITLE
crossing-setup should allow configurable mana costs for magic training.

### ISSUE THREAD

**Issue by hwoo79** [rpherbig/dr-scripts#105]
Would like to be able to configure it to cast a set amount of mana below the DISCERN cap.  This would help prevent backfiring, which leads to nerve damage.

**Comment by rpherbig** [comment]
I could see a few different approaches here:
* I think the simple fix is to allow a 'mana' attr on a spell definition which overrides the stored discern value
* A more complicated solution could be to detect a backfire and scale down the stored discern value
* A different approach would be to implement a bool 'cautious spellcasting' mode which takes some % off of the stored discern value

@hwoo79 I've not encountered much backfiring, so I'm not sure which one best solves your problem. What are your thoughts?

**Comment by hwoo79** [comment]
whatever is going to require the least amount of fiddling from the end user.  I think the 'cautious' mode would work.

**Comment by rpherbig** [comment]
Sounds good. Do you have a particular % in mind? In other words, roughly how cautious would you want it to be?

**Comment by hwoo79** [comment]
I'd say 5% with at least 1 mana below the discern amount would be a safe start.

might take more casts, but it's cautious for a reason.
