### ISSUE TITLE
Add support for Barbarian Meditate Research

### ISSUE THREAD

**Issue by jayRyan24** [rpherbig/dr-scripts#1050]
Add support for the 3.1 Magic change to Barbarians for Meditate Research. This facilitates training abilities without having to toggle them on and off during combat.

**Comment by rpherbig** [comment]
When I experimented with that, it was awful. Something like one mind state
per 3 to 5 meditates. Are you seeing better results?

**Comment by jayRyan24** [comment]
I'm staying locked in Warding without using a Warding skill. I'm running them and all of them are locked. Typically you must stop using abilities and then restart them to gain the exp pulse form them, this alleviates the need for it.

**Comment by rpherbig** [comment]
My barb just runs one ability for each skill and they stay locked (no need to stop and restart them). But there's no harm in using research meditate if it works better for you.

**Comment by jayRyan24** [comment]
I only use this with Warding. I can't get Warding to move at all by running Swan. Everics mentioned the way to train abilities due to how they work with only giving exp for the first initial minute, and that you must restart them. I run Earthquake and about 5 other Augmentations, so those stay rather high and full. Running Swan or turtle fails me, they don't train. Jhien mentioned Meditate Research and it made a huge difference. Warding is now constantly locked.
