### ISSUE TITLE
Missing combat messaging when fighting flying creatures

### ISSUE THREAD

**Issue by cynesis** [rpherbig/dr-scripts#1051]
>[combat-trainer]>weave
>You come out of hiding.
>A silver-tipped mature forest gryphon is flying too high for you to attack.

Results in 15 second pause then debug messaging.

**Comment by cynesis** [comment]
>1079: bput(%w(weave bob circle).sample, 'roundtime', 'There is nothing else', 'Face what', 'You must be closer', 'You must be standing', 'Strangely, you don\'t feel like fighting right now') unless game_state.npcs.empty?
  bput(%w(weave bob circle).sample, 'roundtime', 'There is nothing else', 'Face what', 'You must be closer', 'You must be standing', 'Strangely, you don\'t feel like fighting right now', 'is flying too high for you to attack') unless game_state.npcs.empty?

>1450: attempt = bput("maneuver #{action}", 'You brace your', 'balanced and', 'Taking a full step back', 'You take a step back', 'You lower your shoulders', 'You angle to the side and ', 'rest a bit longer', 'You square up your feet')
  attempt = bput("maneuver #{action}", 'You brace your', 'balanced and', 'Taking a full step back', 'You take a step back', 'You lower your shoulders', 'You angle to the side and ', 'rest a bit longer', 'You square up your feet', 'You must be standing to perform that maneuver')

Although a fix_standing call before line 1450 might handle this one better. Added messaging couldn't hurt.

**Comment by swhalengold** [comment]
This is still happening.

[combat-trainer]>attack
>
A silver-tipped mature forest gryphon is flying too high for you to attack. 

15 seconds later....

[combat-trainer: checked against [/Wouldn't it be better if you used a melee weapon?/i, /Face What?/i, /Roundtime/i, /You aren't close enough to attack/i, /It would help if you were closer/i, /There is nothing else to face!/i, /You must be hidden/i]]
[combat-trainer: for command attack]
