### ISSUE TITLE
hunting-buddy and crossing-trainer running simultaneously and conflicting.

### ISSUE THREAD

**Issue by arkrail** [rpherbig/dr-scripts#1054]
I've been having multiple instance of hunting-buddy and crossing-trainer being run simultaneously by training-manager, causing me to die to things like box picking naked in hunting grounds, or removing my armor to repair gear in front of 4 dire bears.  I'm attaching log snippets of what I can find of the errors starting, let me know if you need more of the logs.

Kalravion:
sell-loot]>deposit all

The clerk slides a small metal box across the counter into which you drop all your Kronars.  She counts them carefully and records the deposit in her ledger.

[drinfomon]>balance

[sell-loot]>withdraw 3 silver

The clerk pages through her ledger.  "Kalravion, it looks like your current balance is 1100 platinum, 6 gold, 9 silver, 9 bronze, and 9 copper Kronars."

[sell-loot]>check balance

The clerk counts out 3 silver Kronars and hands them over, making a notation in her ledger.

--- Lich: sell-loot has exited.

--- Lich: crossing-training active.

The clerk pages through her ledger.  "Kalravion, it looks like your current balance is 1100 platinum, 6 gold, 6 silver, 9 bronze, and 9 copper Kronars."
Summoning Lord Torgro just arrived.

--- Lich: hunting-buddy active.

Ticklypuff:

[hunting-buddy: ***STATUS*** stopping due to time]

You cup your hand before thrusting your palm up and out in a slapping motion at a dire bear!
Angry hissing accompanies green-hued liquid spraying forth from your palm to form a viridian glob that quickly leaps towards a dire bear.
The glob completely covers its back with stinging fumes as it flies on by.
Roundtime: 1 sec.
You feel fully rested.
You feel fully attuned to the mana streams again.

[combat-trainer]>hunt

You take note of all the tracks in the area, so that you can hunt anything nearby down.

To the east, northeast, north, down:
  1)   a blood wolf
  2)   a blood wolf

Roundtime: 8 sec.
* With pathetic timing, a dire bear slices wide at you.  You turn aside some of the claw with a polished steel parry stick.  
[You're nimbly balanced and in better position.]
* Ineptly, a dire bear saunters forward, its jaws wide open in menacing fashion at you.  You dodge, ducking casually.  
[You're nimbly balanced and in strong position.]
A dire bear appears less distracted.

[combat-trainer]>hide

* Awkwardly, a dire bear swipes with powerful and sharp claws at you.  You turn aside some of the claw with a polished steel parry stick.  
[You're nimbly balanced and have slight advantage.]
You melt into the background, convinced that your attempt to hide went unobserved.
Roundtime: 3 sec.
You feel fully attuned to the mana streams again.

[combat-trainer]>attack

You bob suddenly, lowering yourself into a smaller target.
[You're nimbly balanced and in good position.]
Roundtime: 4 sec.
A dire bear stands up on its hind legs and sniffs inquisitively at the air.

[combat-trainer]>pre pv 2

You trace a hasty sigil in the air, shaping the pattern of the Petrifying Visions spell.

[combat-trainer]>circle

You come out of hiding.
You hesitate and change your mind, circle back awkwardly.  The dire bear easily out maneuvers you.
[You're nimbly balanced with no advantage.]
Roundtime: 3 sec.
* With pathetic timing, a dire bear swipes with powerful and sharp claws at you.  You deflect some of the claw with a polished steel parry stick.  
[You're nimbly balanced and have slight advantage.]

[combat-trainer]>hide

You melt into the background, convinced that your attempt to hide went unobserved.
Roundtime: 3 sec.

[combat-trainer]>attack

You leap out of hiding and ambush a dire bear, completely surprising it.
< Attacking gracefully, you punch your brass knuckle at a dire bear.  A dire bear attempts to evade, stepping partially into the shot.  The knuckle lands a solid hit (4/23) to the bear's left arm.
[You're nimbly balanced with no advantage.]
[Roundtime 2 sec.]
* As if fumbling muscle flab were natural, a dire bear swipes with powerful and sharp claws at you.  You beat off some of the claw with a polished steel parry stick.  
[You're nimbly balanced and have slight advantage.]

[combat-trainer]>hide

You melt into the background, convinced that your attempt to hide went unobserved.
Roundtime: 3 sec.
You feel fully prepared to cast your spell.
You feel fully rested.
You feel fully attuned to the mana streams again.

[combat-trainer]>stalk

You are convinced that your stalking went unobserved.
You move into position to stalk a dire bear when it moves.
Roundtime: 2 sec.

[combat-trainer]>attack

You leap out of hiding and ambush a dire bear, gaining a slight advantage.
< Moving fluidly, you punch your brass knuckle at a dire bear.  A dire bear fails to evade, pivoting toward safety but still partially within harm's reach.  The knuckle lands a solid hit (4/23) to the bear's chest.
[You're solidly balanced with no advantage.]
[Roundtime 2 sec.]
You feel fully rested.

[combat-trainer]>cast

You gesture at a dire bear.
You whisper several words of arcane power, attempting to twist a dire bear's mind with primal terror.
Your malefic assault overtakes a dire bear, petrifying it to the spot!
Roundtime: 2 sec.
* In a weak and directionless display of aggression, a dire bear saunters forward, its jaws wide open in menacing fashion at you.  You repulse some of the teeth with a polished steel parry stick.  
[You're solidly balanced and opponent has slight advantage.]

[combat-trainer]>perc

You reach out with your senses and see pale (7/21) streams of black Necromantic mana oozing through the area.
Letting your senses extend further, you feel there is immensely more mana to the northwest, and around the same mana to the east.
You sense the Rite of Contrition spell upon you, which will last until you fail to provide 6 mana for it.
You sense the Manifest Force spell surrounding you, which will last for eight roisaen or until it has endured six more blows.
You sense the Obfuscation spell upon you, which will last for about eight roisaen.
Roundtime: 7 sec.

[combat-trainer]>hide

* Apparently without direction or thought, a dire bear saunters forward, its jaws wide open in menacing fashion at you.  You turn aside some of the teeth with a polished steel parry stick.  
[You're solidly balanced with no advantage.]
You melt into the background, convinced that your attempt to hide went unobserved.
Roundtime: 3 sec.
The dire bear no longer seems petrified.

[combat-trainer]>attack

...wait 1 seconds.

[combat-trainer]>attack

You leap out of hiding and ambush a dire bear, startling it.
< Moving fluidly, you punch your brass knuckle at a dire bear.  A dire bear fails to evade, avoiding most of the blow.  The knuckle lands a solid hit (4/23) to the bear's left leg.
[You're solidly balanced with no advantage.]
[Roundtime 2 sec.]
You feel fully rested.
* Moving in like a timid schoolboy, a dire bear swipes with powerful and sharp claws at you.  You beat off some of the claw with a polished steel parry stick.  
[You're solidly balanced with opponent in good position.]
* Ineptly, a dire bear swipes with powerful and sharp claws at you.  You evade, leaping aside.  
[You're solidly balanced with no advantage.]

[combat-trainer]>tar ACS 2

You trace a hasty sigil in the air, shaping the pattern of the Acid Splash spell.
You begin to weave mana lines into a target pattern around a dire bear.
A dire bear wheels around quickly and drops to all fours.

[combat-trainer]>charge my armband 1

You harness a small amount of energy and attempt to channel it into your cambrinth armband.
You are able to channel all the energy into the armband.
The cambrinth armband absorbs all of the energy.
Roundtime: 2 sec.
* Ineptly, a dire bear swipes with powerful and sharp claws at you.  You counter some of the claw with a polished steel parry stick.  
[You're solidly balanced and in better position.]

[combat-trainer]>invoke my armband 

The cambrinth armband pulses with Arcane energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.
Roundtime: 1 sec.
You feel fully attuned to the mana streams again.

[combat-trainer]>weave

You weave back and forth in a dance-like motion, drawing your opponent's attention away from the fight.
[You're nimbly balanced and in good position.]
Roundtime: 4 sec.
Your formation of a targeting pattern around a dire bear has completed.
Your cambrinth armband thrums softly as it discharges all its power to maintain your spell.

[combat-trainer]>hide

You melt into the background, convinced that your attempt to hide went unobserved.
Roundtime: 3 sec.
A dire bear stands up on its hind legs and sniffs inquisitively at the air.
A dire bear stands up on its hind legs and sniffs inquisitively at the air.

[combat-trainer]>attack

You bob suddenly, lowering yourself into a smaller target.
[You're nimbly balanced and in very strong position.]
Roundtime: 4 sec.
You feel fully rested.
You feel fully attuned to the mana streams again.
A dire bear lumbers in.
A dire bear stands up on its hind legs and sniffs inquisitively at the air.

[combat-trainer]>cast

You reveal yourself.
You cup your hand before thrusting your palm up and out in a slapping motion at a dire bear!
Angry hissing accompanies green-hued liquid spraying forth from your palm to form a viridian glob that quickly leaps towards a dire bear.
As the glob races by its left leg, several drops fly off and sizzle while burning pits into the flesh.
The dire bear is lightly stunned!
Roundtime: 1 sec.
You feel fully attuned to the mana streams again.

[combat-trainer]>hunt

* Apparently without direction or thought, a dire bear slices wide at you.  You evade, managing to get out of the way with a minimum of effort.  
[You're nimbly balanced and in very strong position.]
You take note of all the tracks in the area, so that you can hunt anything nearby down.

To the east, northeast, north, north:
  1)   a blood wolf

To the east, northeast, north, down:
  2)   a blood wolf

Roundtime: 8 sec.
A dire bear appears less distracted.
You've gained a new rank in your overall defensive maneuvering.
The dire bear begins to advance on you!
The dire bear is still a distance away from you and is closing steadily.

[combat-trainer]>hide

You melt into the background, convinced that your attempt to hide went unobserved.
Roundtime: 3 sec.
You feel fully attuned to the mana streams again.

[combat-trainer]>attack

A dire bear stands up on its hind legs and sniffs inquisitively at the air.
You leap out of hiding and ambush a dire bear, catching it off guard.
< Moving in gracefully, you punch your brass knuckle at a dire bear.  A dire bear attempts to evade, not quite escaping the blast.  The knuckle lands a hard hit (5/23) that bruises the left forearm.
[You're nimbly balanced and in good position.]
[Roundtime 2 sec.]

[combat-trainer]>stance set 100 0 82

Setting your Evasion stance to 100%, your Parry stance to 0%, and your Shield stance to 82%.  You have 0 stance points left.
The dire bear closes to pole weapon range on you!

[combat-trainer]>pre pv 2

You feel fully rested.
You trace a hasty sigil in the air, shaping the pattern of the Petrifying Visions spell.

[combat-trainer]>circle

You fake a dire bear, first moving one way and then another, leaving it off balance.
[You're nimbly balanced and in superior position.]
Roundtime: 3 sec.
The dire bear closes to melee range on you!
* Moving inexpertly, a dire bear swipes with powerful and sharp claws at you.  You barely block with a small gryphon-pelt shield sealed with protective wax.  
[You're nimbly balanced and opponent has slight advantage.]

[combat-trainer]>attack

* Moving in like a timid schoolboy, a dire bear swipes with powerful and sharp claws at you.  You partially block with a small gryphon-pelt shield sealed with protective wax.  
[You're nimbly balanced and in strong position.]
< With grace, you punch your brass knuckle at a dire bear.  A dire bear fails to evade, avoiding most of the blow.  The knuckle lands a hard hit (5/23) that deeply bruises the right bicep, lightly stunning it.
[You're adeptly balanced and in dominating position.]
[Roundtime 2 sec.]
You feel fully rested.
You feel fully attuned to the mana streams again.
Dako'gi Gamila just arrived.

[combat-trainer]>get my cutlass

You get a steel cutlass from inside your shoulder tote.

[combat-trainer]>stance set 100 82 0

A dire bear lumbers in.
A dire bear lumbers in.
The dire bear begins to advance on Gamila.
The dire bear begins to advance on you!
The dire bear is still a distance away from you and is closing steadily.
* Inexpertly, a dire bear saunters forward, its jaws wide open in menacing fashion at you.  You dodge, stepping aside in the nick of time.  
[You're nimbly balanced and opponent has slight advantage.]
Dako'gi Gamila strides northwest.
Setting your Evasion stance to 100%, your Parry stance to 82%, and your Shield stance to 0%.  You have 0 stance points left.

[combat-trainer]>app bear quick

You are certain that the dire bear is in extremely bad shape.
The dire bear has more than a few relatively minor wounds.
You are confident that it is about as strong as you are.
You are confident that it is somewhat less agile than you are.
You wonder if it is quite a bit less disciplined than you are.
You are confident that it is rather less quick to react than you are.
You wonder if it is apparently as conditioned as you are.
You weren't able to observe long enough to even guess at its offensive skill.
Taking stock of its defensive abilities, and attacking with a steel cutlass, you wonder if the dire bear is something that you'd kill quickly.

[Roundtime: 3 seconds]
* In a weak and directionless display of aggression, a dire bear swipes with powerful and sharp claws at you.  You slap away some of the claw with a steel cutlass.  
[You're nimbly balanced and in good position.]
You feel fully prepared to cast your spell.

[combat-trainer]>attack

< You draw a steel cutlass at a dire bear.  A dire bear evades, barely managing to get out of the way.  
[You're winded, adeptly balanced and overwhelming opponent.]
[Roundtime 3 sec.]
* Trying poorly, a dire bear saunters forward, its jaws wide open in menacing fashion at you.  You slap away little of the teeth with a steel cutlass.  
[You're winded, adeptly balanced and have slight advantage.]
The dire bear closes to pole weapon range on you!
Appearing to have lost sight of its target, a dire bear stops advancing.
* With weak timing, a dire bear swipes with powerful and sharp claws at you.  You dodge, ducking in the nick of time.  
[You're winded, adeptly balanced and in very strong position.]

[combat-trainer]>cast

* Looking as if this were a bad idea, a dire bear swipes with powerful and sharp claws at you.  You repulse some of the claw with a steel cutlass.  
[You're adeptly balanced and in dominating position.]
You gesture at a dire bear.
You whisper several words of arcane power, attempting to twist a dire bear's mind with primal terror.
Your malefic assault overtakes a dire bear, petrifying it to the spot!
Roundtime: 2 sec.
The dire bear closes to melee range on you!
A dire bear saunters northwest.

[combat-trainer]>attack

* Moving inexpertly, a dire bear slices wide at you.  You counter little of the teeth with a steel cutlass.  
[You're adeptly balanced and in good position.]
< Attacking gracefully, you slice a steel cutlass at a dire bear.  A dire bear fails to evade, avoiding only some of the blow.  The cutlass lands a hard hit (5/23) that wounds it deeply across the upper left arm, lightly stunning it.
[You're nimbly balanced and overwhelming opponent.]
[Roundtime 4 sec.]
* Moving inexpertly, a dire bear swipes with powerful and sharp claws at you.  You evade, barely leaning out of harm's reach.  
[You're nimbly balanced and have slight advantage.]
* As if effort and skill were a bad thing, a dire bear swipes with powerful and sharp claws at you.  You evade, barely stepping to one side.  
[You're nimbly balanced and in good position.]

[combat-trainer]>tar ACS 2

You trace a hasty sigil in the air, shaping the pattern of the Acid Splash spell.
You begin to weave mana lines into a target pattern around a dire bear.
You feel fully attuned to the mana streams again.
The dire bear no longer seems petrified.
* With inexpert timing, a dire bear saunters forward, its jaws wide open in menacing fashion at you.  You evade, barely twisting out of a tight spot.  
[You're nimbly balanced and have slight advantage.]
* Trying inexpertly, a dire bear swipes with powerful and sharp claws at you.  You repulse little of the claw with a steel cutlass.  
[You're nimbly balanced and opponent has slight advantage.]
* As if effort and skill were a bad thing, a dire bear swipes with powerful and sharp claws at you.  You dodge, barely twisting out of harm's reach.  

[combat-trainer]>charge my armband 1

[You're nimbly balanced and in better position.]
You harness a small amount of energy and attempt to channel it into your cambrinth armband.
You are able to channel all the energy into the armband.
The cambrinth armband absorbs all of the energy.
Roundtime: 2 sec.

[combat-trainer]>invoke my armband 

The cambrinth armband pulses with Arcane energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.
Roundtime: 1 sec.
* Inexpertly, a dire bear charges with surprising speed at you.  You dodge, just managing to get out of a tight spot.  
[You're nimbly balanced and have slight advantage.]
* Tentatively, a dire bear swipes with powerful and sharp claws at you.  You dodge, leaning to one side.  
[You're nimbly balanced and in excellent position.]

[combat-trainer]>circle

You fake a dire bear, first moving one way and then another, leaving it off balance.
[You're adeptly balanced and overwhelming opponent.]
Roundtime: 4 sec.
Your formation of a targeting pattern around a dire bear has completed.
* Tentatively, a dire bear swipes with powerful and sharp claws at you.  You beat off some of the claw with a steel cutlass.  
[You're adeptly balanced and have slight advantage.]
* Apparently without direction or thought, a dire bear slices wide at you.  You dodge, barely leaning out of harm's reach.  
[You're adeptly balanced and in very strong position.]

[combat-trainer]>attack

< Moving fluidly, you slice a steel cutlass at a dire bear.  A dire bear attempts to dodge, mainly avoiding the blow.  The cutlass lands a strong hit (6/23) that splinters bones and nearly severs the left arm.
A dire bear growls one last time and collapses.
[You're adeptly balanced]
[Roundtime 4 sec.]
You feel fully attuned to the mana streams again.
* Trying inexpertly, a dire bear charges with surprising speed at you.  You evade, stepping aside in the nick of time.  
[You're nimbly balanced and have slight advantage.]
* Moving weakly, a dire bear slices wide at you.  You dodge, barely twisting out of a tight spot.  
[You're nimbly balanced with no advantage.]
* Apparently without direction or thought, a dire bear swipes with powerful and sharp claws at you.  You dodge, managing to get out of the way with a minimum of effort.  
[You're nimbly balanced and in very strong position.]
Your cambrinth armband thrums softly as it discharges all its power to maintain your spell.
You feel fully rested.

[combat-trainer]>cast

* Awkwardly, a dire bear slices wide at you.  You counter some of the teeth with a steel cutlass.  
[You're nimbly balanced and in strong position.]
* Moving inexpertly, a dire bear swipes with powerful and sharp claws at you.  You knock aside little of the claw with a steel cutlass.  
[You're nimbly balanced and have slight advantage.]
Your target pattern dissipates because the dire bear is dead, but the main spell remains intact.

[combat-trainer]>release spell

You let your concentration lapse and feel the spell's energies dissipate.

[combat-trainer]>health

Your body feels at full strength.
Your spirit feels full of life.
You have no significant injuries. 

[combat-trainer]>perform preserve on bear

You bend over the bear's corpse to make one long, continuous cut with your ritual knife that just barely pierces into it.  Unseen energies seep into the creature's fluids, suspending the corpse in unnatural stasis for a time.
Roundtime: 4 sec.
You feel fully attuned to the mana streams again.
* As if effort and skill were a bad thing, a dire bear charges with surprising speed at you.  You counter some of the body with a steel cutlass.  
[You're nimbly balanced and in excellent position.]
A dire bear stops and sniffs the air.

[combat-trainer]>perform harvest on bear

You bend over the bear's corpse to make a few quick, precise motions with your ritual knife, focusing your thanatological insight intently in order to prepare it for harvesting.  You then plunge your knife efficiently into the corpse and carve out an average piece of fetish material.
Roundtime: 4 sec.
* Moving inexpertly, a dire bear swipes with powerful and sharp claws at you.  You dodge, barely managing to get out of the way.  
[You're nimbly balanced and in better position.]
* Apparently without direction or thought, a dire bear charges wide at you.  You dodge, leaping aside.  
[You're nimbly balanced and in good position.]

[combat-trainer]>drop material

Having no further use for an average chunk of bear material, you discard it.  The material quickly degrades into uselessness.

[combat-trainer]>loot

You search the dire bear.
You find nothing of interest.
* Apparently without direction or thought, a dire bear saunters forward, its jaws wide open in menacing fashion at you.  You dodge, stepping clear of danger.  
[You're nimbly balanced with no advantage.]
A dire bear rots away into nothingness.

[combat-trainer]>tar ACS 2

* Ineptly, a dire bear swipes with powerful and sharp claws at you.  You evade, stepping aside.  
[You're nimbly balanced with no advantage.]
You trace a hasty sigil in the air, shaping the pattern of the Acid Splash spell.
You turn to face a dire bear.
You begin to weave mana lines into a target pattern around a dire bear.
* As if effort and skill were a bad thing, a dire bear swipes with powerful and sharp claws at you.  You evade, moving out of the way.  
[You're nimbly balanced with no advantage.]
* Apparently without direction or thought, a dire bear saunters forward, its jaws wide open in menacing fashion at you.  You turn aside most of the teeth with a steel cutlass.  
[You're nimbly balanced and in strong position.]
You feel fully attuned to the mana streams again.

[combat-trainer]>charge my armband 1

You harness a small amount of energy and attempt to channel it into your cambrinth armband.
You are able to channel all the energy into the armband.
The cambrinth armband absorbs all of the energy.
Roundtime: 2 sec.
* Apparently without direction or thought, a dire bear slices wide at you.  You repulse some of the teeth with a steel cutlass.  
[You're solidly balanced and opponent has slight advantage.]
* Apparently without direction or thought, a dire bear swipes with powerful and sharp claws at you.  You beat off some of the claw with a steel cutlass.  
[You're solidly balanced and opponent has slight advantage.]
* Apparently without direction or thought, a dire bear saunters forward, its jaws wide open in menacing fashion at you.  You dodge, jumping to one side.  
[You're solidly balanced and have slight advantage.]
You feel fully attuned to the mana streams again.
Your formation of a targeting pattern around a dire bear has completed.

[combat-trainer]>invoke my armband 

The cambrinth armband pulses with Arcane energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.
Roundtime: 1 sec.
* As if effort and skill were a bad thing, a dire bear swipes with powerful and sharp claws at you.  You dodge, stepping aside.  
[You're solidly balanced with opponent in better position.]
* Moving in like a timid schoolboy, a dire bear saunters forward, its jaws wide open in menacing fashion at you.  You dodge, moving out of the way.  
[You're solidly balanced and in better position.]
* Awkwardly, a dire bear swipes with powerful and sharp claws at you.  You dodge, moving out of the way.  
[You're solidly balanced with opponent in better position.]

[combat-trainer]>cast

You cup your hand before thrusting your palm up and out in a slapping motion at a dire bear!
Your cambrinth armband emits a loud *snap* as it discharges all its power to aid your spell.
Angry hissing accompanies green-hued liquid spraying forth from your palm to form a viridian glob that quickly leaps towards a dire bear.
The glob coats its abdomen with an irritating mist as it hurtles on past.
Roundtime: 1 sec.
* In a weak and directionless display of aggression, a dire bear charges with surprising speed at you.  You beat off some of the body with a steel cutlass.  
[You're solidly balanced and have slight advantage.]
* Apparently without direction or thought, a dire bear swipes with powerful and sharp claws at you.  You dodge, ducking casually.  
[You're solidly balanced and have slight advantage.]

[combat-trainer]>release ROC

The Rite of Contrition matrix loses cohesion, leaving your aura naked.

[combat-trainer]>retreat

You retreat back to pole range.

[combat-trainer]>retreat

The dire bear begins to advance on you!
The dire bear advances from nearby and is closing steadily.
You retreat from combat.

[combat-trainer]>stow my cutlass

You put your cutlass in your shoulder tote.

--- Lich: combat-trainer has exited.

[hunting-buddy]>retreat

You are already as far away as you can get!
The dire bear closes to pole weapon range on you!
The dire bear begins to advance on you!
The dire bear is still a distance away from you and is closing steadily.
The dire bear begins to advance on you!
The dire bear is still a distance away from you and is closing steadily.

[hunting-buddy]>release ROC

Release what?
[Check RELEASE HELP for more information.]

--- Lich: go2 active.

[go2: ETA: 0:00:36 (168 rooms to move through)]

[go2]>east

You are engaged to a dire bear at pole weapon range!

[go2]>retreat

You feel fully attuned to the mana streams again.

[go2]>retreat

You retreat from combat.

[go2]>east

You are already as far away as you can get!

[go2: move: failed]

You go east.
[Rocky Outcrop]
Little light penetrates this narrow gap between the two mounds of the outcropping.  Grey rock soars toward the sky to the north and south, with a deep, treacherous looking crevasse in between to the immediate south of the trail.  A few sickly ferns grow in gaps and chinks in the rock, and a scrubby bush with poisonous looking berries clings to one side of the slope.  
Obvious paths: northeast, west.

[go2: restarting script...]

[go2: error: your current room was not found in the map database]

--- Lich: go2 has exited.

[hunting-buddy: Failed to navigate to room 8926, attempting again]

[hunting-buddy: In an unknown room, manually attempting to navigate to 8926]

[hunting-buddy: failed to find a matching room]

[hunting-buddy]>inv combat

All of your combat:

  a lelori forester's stonebow
  some lumium ring gloves
  a lumium ring balaclava
  a polished steel parry stick
  a quilted silk hauberk sealed with protective wax
  a small gryphon-pelt shield sealed with protective wax
  some silver-chased elbow spikes
  some brass knuckles
[Type INVENTORY HELP for more options]

--- Lich: hunting-buddy has exited.

--- Lich: safe-room active.

[safe-room]>health

Your body feels at full strength.
Your spirit feels full of life.
You have no significant injuries. 

[safe-room: ***STATUS*** No wounds, skipping healing]

--- Lich: safe-room has exited.

--- Lich: crossing-repair active.

[crossing-repair]>inv combat

All of your combat:

  a lelori forester's stonebow
  some lumium ring gloves
  a lumium ring balaclava
  a polished steel parry stick
  a quilted silk hauberk sealed with protective wax
  a small gryphon-pelt shield sealed with protective wax
  some silver-chased elbow spikes
  some brass knuckles
[Type INVENTORY HELP for more options]

[crossing-repair]>wealth kronars

  3 silver Kronars (300 copper Kronars).
A dire bear saunters in, swinging its head from side to side.

[crossing-repair: In an unknown room, manually attempting to navigate to 1900]

[crossing-repair: failed to find a matching room]

[crossing-repair]>withdraw 9 gold

You must be at a bank teller's window to withdraw money.
A dire bear saunters in, swinging its head from side to side.
The dire bear begins to advance on you!
The dire bear is still a distance away from you and is closing steadily.
The dire bear begins to advance on you!
The dire bear is still a distance away from you and is closing steadily.

[crossing-repair: *** No match was found after 15 seconds, dumping info]

[crossing-repair: messages seen length: 8]

[crossing-repair: message: You must be at a bank teller's window to withdraw money.]

[crossing-repair: message: A dire bear saunters in, swinging its head from side to side.]

[crossing-repair: message: Manifest Force  (5 roisaen)]

[crossing-repair: message: Obfuscation  (5 roisaen)]

[crossing-repair: message: The dire bear begins to advance on you!]

[crossing-repair: message: The dire bear is still a distance away from you and is closing steadily.]

[crossing-repair: message: The dire bear begins to advance on you!]

[crossing-repair: message: The dire bear is still a distance away from you and is closing steadily.]

[crossing-repair: checked against [/The clerk counts/i, /The clerk tells/i]]

[crossing-repair: In an unknown room, manually attempting to navigate to 19093]

[crossing-repair: failed to find a matching room]

The dire bear closes to pole weapon range on you!

[crossing-repair]>remove my ring.balaclava

You take a lumium ring balaclava off your head.
Roundtime: 1 sec.
The dire bear closes to pole weapon range on you!
The dire bear closes to melee range on you!
* Apparently without direction or thought, a dire bear swipes with powerful and sharp claws at you.  You dodge, stepping aside.  
[You're solidly balanced and opponent has slight advantage.]

[crossing-repair]>give my ring.balaclava to Catrox

What is it you're trying to give?
The dire bear closes to melee range on you!
* Apparently without direction or thought, a dire bear charges with surprising speed at you.  You turn aside some of the body with a polished steel parry stick.  
[You're solidly balanced and opponent has slight advantage.]
* Ineptly, a dire bear saunters forward, its jaws wide open in menacing fashion at you.  You counter some of the teeth with a polished steel parry stick.  
[You're solidly balanced and have slight advantage.]
* Awkwardly, a dire bear saunters forward, its jaws wide open in menacing fashion at you.  You evade, stepping clear of danger.  
[You're solidly balanced and have slight advantage.]
* Apparently without direction or thought, a dire bear swipes with powerful and sharp claws at you.  You repulse some of the claw with a polished steel parry stick.  
[You're solidly balanced with no advantage.]

**Comment by rpherbig** [comment]
This should be fixed by @rcuhljr  in c41219c1b47e3e5f40e6d929b7480522789a28b2
