### ISSUE TITLE
Missing crossing-training backfire match.

### ISSUE THREAD

**Issue by Zhennlash** [rpherbig/dr-scripts#1057]
Occurs during magic training (Util|Aug);

> [crossing-training: *** No match was found after 15 seconds, dumping info]                                                                                 
> [crossing-training: messages seen length: 20]                                                                                                                                                                                            
> [crossing-training: message: You reveal yourself.]                                                                                                         
> [crossing-training: message: Your cambrinth armband emits a loud *snap* as it discharges all its power to aid your spell.]
> [crossing-training: message: Your spell barely backfires.]

**Comment by rpherbig** [comment]
Could you post a bit more of the log?

**Comment by Zhennlash** [comment]
Oddly, I haven't been able to reproduce this one. I'm going to go ahead and close this until I find something logged.

My apologies.
