### ISSUE TITLE
;astrology should have buffs available similar to lockpick_buffs

### ISSUE THREAD

**Issue by reithir** [rpherbig/dr-scripts#1063]
like lockpicking, it should check whether you have the relevant buff up before starting the astrology routine, and casting if it necessary; hello piercing gaze!

**Comment by rcuhljr** [comment]
`astrology_buffs` is already supported. look at Crannach, Mooselurk, or Paeriluno for examples.

**Comment by reithir** [comment]
Oops, my mistake. That's great, thank you!!

**Comment by reithir** [comment]
I just put this into my yaml file, it looks like it casts the astrology_buff spells every time astrology runs whether the spells are already up or not; doesn't lockpick_buff only cast when the spell is needed? Doesn't it make sense to only cast the spell if it's not up?

**Comment by rpherbig** [comment]
Lock picking behaves the same way.

We decided to always recast because your previous cast could have been weak
from being used in training, etc.

I'm open to changing it if you feel strongly about this...

**Comment by reithir** [comment]
Ooh I gotcha, that makes sense. Yeah for my present alt I'm working on (~40th circle moonie), he doesn't use symbiosis casting for training so all of his casts are full power, so this wasn't an issue for me; it would just save a little time to not have to recast unless it were necessary, but it's probably not a big deal. I probably don't feel strongly enough to really advocate for this to be changed. thanks for the info!
