### ISSUE TITLE
Resonance Request

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1064]
Now that we have Ignite casting on whatever is in the right hand can we do the same for Resonance?

**Comment by rpherbig** [comment]
We already have a template for this with Ignite and Rutilor's Edge, it should be easy to add Resonance. That said, we should take this opportunity to see if there is some refactoring we can do.

**Comment by rpherbig** [comment]
@Aurayn This should be working, but I don't have a character with the spell. Can you test it and let me know if there are any problems?

**Comment by Aurayn** [comment]
Doesnt seem to be working as yet

You are holding a steel cinquedea in your right hand.


>
[combat-trainer]>pre Resonance 15
>
You trace a careful sigil in the air, shaping the pattern of the Resonance spell.
>
[combat-trainer]>remove my cambrinth-link choker
You remove a cambrinth-link choker dangling a malachite cameo from around your neck.
>
[combat-trainer]>charge my cambrinth-link choker 11
You harness a small amount of energy and attempt to channel it into your cambrinth-link choker.
You are able to channel all the energy into the choker.
The cambrinth-link choker absorbs all of the energy.
Roundtime: 3 sec.
>
A giant black leucro wakes up.
>
A giant black leucro wakes up.
>
A giant black leucro wakes up.
>
The black leucro climbs to its feet.
>
The black leucro leaps to its feet.
>
Remedi holds out his arms, then brings them down evenly.
A giant black leucro wobbles slightly, then collapses into sleep.
A giant black leucro wobbles slightly, then collapses into sleep.
A giant black leucro wobbles slightly, then collapses into sleep.
A giant black leucro wobbles slightly, then collapses into sleep.
>
You feel sufficiently recovered to use your concussive scream again.
>
The black leucro growls in a low, rythmic breathing as it sleeps.
>
The black leucro growls in a low, rythmic breathing as it sleeps.
>
[combat-trainer]>wear my cambrinth-link choker
You hang a cambrinth-link choker dangling a malachite cameo around your neck.
>
[combat-trainer]>remove my cambrinth-link choker
You remove a cambrinth-link choker dangling a malachite cameo from around your neck.
>
The black leucro growls in a low, rythmic breathing as it sleeps.
>
[combat-trainer]>invoke my cambrinth-link choker 
Your link to the cambrinth-link choker is intact.
Roundtime: 1 sec.
>
[combat-trainer]>wear my cambrinth-link choker
The black leucro growls in a low, rythmic breathing as it sleeps.
>
You hang a cambrinth-link choker dangling a malachite cameo around your neck.
>
[combat-trainer]>circle
Remedi assumes a tense stance, concentrating on something.
>
You fake a giant black leucro, first moving one way and then another, leaving it off balance.
[You're nimbly balanced and overwhelming opponent.]
Roundtime: 4 sec.
>
Your cambrinth-link choker thrums softly as it discharges as much power as necessary, leaving a moderate amount left for future use.
>
Remedi's blighted gold bracelet flares with radiant light, and he looks more at ease than before.
>
[combat-trainer]>attack
< You thrust a steel cinquedea at a giant black leucro and waste any advantage you had.  A giant black leucro evades, just stepping out of harm's way.  
[You're nimbly balanced and overwhelming opponent.]
[Roundtime 6 sec.]
>
The black leucro growls in a low, rythmic breathing as it sleeps.
>
The black leucro growls in a low, rythmic breathing as it sleeps.
>
You feel fully attuned to the mana streams again.
>
Katamba sets, slowly dropping below the horizon.
>
You've gained a new rank in your ability to parry.
>
The black leucro stands back up.
>
* Ineptly, a giant black leucro pounces, its mouth curled back in a savage snarl at you.  You repulse some of the teeth with a steel cinquedea.  
[You're nimbly balanced and overwhelming your opponent.]
>
The black leucro growls in a low, rythmic breathing as it sleeps.
>
[combat-trainer]>hide
The black leucro discovers you, ruining your hiding place!
Roundtime: 5 sec.
>
A giant black leucro wakes up.
>
A giant black leucro wakes up.
>
A giant black leucro wakes up.
>
You feel fully prepared to cast your spell.
>
Remedi holds out his arms, then brings them down evenly.
A giant black leucro wobbles slightly, then collapses into sleep.
A giant black leucro wobbles slightly, then collapses into sleep.
A giant black leucro wobbles slightly, then collapses into sleep.
A giant black leucro wobbles slightly, then collapses into sleep.
>
You feel fully rested.
>
[combat-trainer]>attack
The black leucro growls in a low, rythmic breathing as it sleeps.
>
The black leucro growls in a low, rythmic breathing as it sleeps.
>
The black leucro growls in a low, rythmic breathing as it sleeps.
>
< Moving fluidly, you draw a steel cinquedea at a giant black leucro.  A giant black leucro fails to dodge, taking the full blow.  The cinquedea lands a heavy strike (7/23) that nicks the leucro's left forearm.
[You're winded, adeptly balanced and overwhelming opponent.]
[Roundtime 5 sec.]
>
Remedi assumes a tense stance, concentrating on something.
>
Your cambrinth-link choker thrums softly as it discharges as much power as necessary, leaving a moderate amount left for future use.
The skipping, sparkling rhythm of Caress of the Sun flows from your lips, enticing the air around you to shed moisture and to warm as if under a summer sun.
>
The black leucro growls in a low, rythmic breathing as it sleeps.
>
**[combat-trainer]>cast my** 
You can't cast that at yourself!
>
[combat-trainer]>release spell
You let your concentration lapse and feel the spell's energies dissipate.
>
[combat-trainer]>hunt
You take note of all the tracks in the area, so that you can hunt anything nearby down.

**Comment by rpherbig** [comment]
In Slack, @Aurayn reported that this worked for his scimitar.
