### ISSUE TITLE
Add "exit" if Killed

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#1066]
I've had on a few occassions died without realizing, most recently by a box i shouldn't have been picking.  Is it possible to create a mechanism that would identify if you've been dead for a certain period of time and then automatically exits you from the game to prevent further memory loss or departing after long enough.

If one isn't afk, then perhaps they could disable the exit feature?

**Comment by rpherbig** [comment]
The `afk` script will (among other things) detect if you are dead. In that case it will wait 3 minutes, `depart items`, and then exit the game. Is that what you are looking for?

**Comment by wscherer420** [comment]
Didn't know about that feature.  That's great, but i think i'd prefer to not depart at all, just exit, and allow me to decide how to handle it when i log back in.  Is that possible with the afk script?

**Comment by wscherer420** [comment]
How does this work if you are a Necromancer with no favors.  Would it still try to depart item?  Would it successfully depart but leave my items in a grave?  Or would it fail and then exit the game?

**Comment by wscherer420** [comment]
Nevermind, got help from some Lichers about customized the Depart on Death in my YAML.  Looks like this takes care of my concerns.  Thank you!
