### ISSUE TITLE
;sew doesn't seem to be using my outfitting belt properly

### ISSUE THREAD

**Issue by reithir** [rpherbig/dr-scripts#1077]
I think I have my yaml set up properly, but when I try to make a piece with ;sew, it tries to "get <tool>" instead of untie <tool> from outfit belt.

**Comment by rcuhljr** [comment]
Can you submit your yaml?

**Comment by reithir** [comment]
#########################################
##########  Hunting Settings    #########
#########################################

training_manager_hunting_priority: true
training_manager_priority_skills:
- Bow
- Large Edged

hunting_file_list:
- setup
#- backtrain

hunting_info:
- :zone: young_wyverns
  args:
  - d1
  - setup
  stop_on:
  - Bow
  - Large Edged

hunting_buddies:

#########################################
###########  Gear Settings    ###########
#########################################

gear_sets:
  standard:
  - targe
  - parry stick
  - padded hood
  - padded mask
  - padded gloves
  - padded shirt
  - padded pants
  naked: []

#########################################
#########  Combat - General    ##########
#########################################

stances:
  Bow:
  - Evasion
  - Shield Usage
  - Parry Ability
  Crossbow:
  - Evasion
  - Shield Usage
  - Parry Ability
  Light Thrown:
  - Evasion
  - Shield Usage
  - Parry Ability

skinning:
  skin: true
  arrange_all: true
  arrange_count: 1
  tie_bundle: true

#########################################
#########  Combat - Offense    ##########
#########################################

dual_load: true
use_stealth_attacks: true

weapon_training:
  Large Edged: broadsword
  Bow: battle longbow

offensive_spells:
- skill: Debilitation
  name: Swarm
  abbrev: swarm
  mana: 12
  expire: The bugs finally cease swarming
  harmless: true

#########################################
#########  Combat - Defense    ##########
#########################################

buff_spells:
  Instinct:
    abbrev: inst
    recast: 2
    mana: 10
    symbiosis: false
    cambrinth:
    - 20
    - 20
  See the Wind:
    abbrev: stw
    recast: 2
    mana: 10
    symbiosis: false
    cambrinth:
    - 20
    - 20
  Senses of the Tiger:
    abbrev: sott
    recast: 2
    mana: 10
    symbiosis: false
    cambrinth:
    - 20
    - 20
  Hands of Lirisa:
    abbrev: hol
    recast: 2
    mana: 10
    symbiosis: false
    cambrinth:
    - 20
    - 20
  Oath of the Firstborn:
    abbrev: oath
    recast: 2
    mana: 15
    symbiosis: false
    cambrinth:
    - 15
    - 15

#########################################
#########  Combat - Training    #########
#########################################

training_abilities:
  Hunt: 80
  Perc: 120
  Stealth: 60
  App: 60
  Tactics: 30

combat_spell_training:
  Utility:
    abbrev: bes
    cyclic: true
    mana: 15
  Augmentation:
    abbrev: bes
    cyclic: true
    mana: 15
  Warding:
    abbrev: ey
    mana: 10
    symbiosis: true
    cambrinth:
    - 20

#########################################
########  Non-Combat Settings    ########
#########################################

crossing_training:
- Locksmithing
- Engineering

#- Mechanical Lore
#- Appraisal
#- Outdoorsmanship
#- Outfitting
#- Athletics
#- Scouting
#- Attunement
#- Augmentation
#- Utility
#- Warding



#########################################
##########  Spell Training    ###########
#########################################

cast_only_to_train: true
symbiosis_learning_threshold: 3
prep_scaling_factor: 0.95
dedicated_camb_use: spell
cambrinth: armband
cambrinth_cap: 50
stored_cambrinth: false

cyclic_cycle_skills:
- Augmentation
- Utility

training_spells:
  Augmentation:
  Utility:
  Warding:
    abbrev: ey
    symbiosis: true

cyclic_training_spells:
  Augmentation:
    abbrev: BES
    cyclic: true
  Utility:
    abbrev: BES
    cyclic: true
  Warding:

#########################################
#######$###  Misc Settings    ###########
#########################################

hometown: Crossing
favor_god: Everild
favor_goal: 10
listen: true

#########################################
###########  Loot Training    ###########
#########################################

storage_containers:
- duffel bag
- rucksack

gem_pouch_adjective: gem
spare_gem_pouch_container: cloak
loot_subtractions:
loot_additions:

#########################################
#########  Lockpick Settings    #########
#########################################

use_lockpick_ring: true
lockpick_container: case
lockpick_type: stout
harvest_traps: true
picking_box_source: duffel bag
picking_box_storage: rucksack
lockpick_buffs:
  spells:
    - abbrev: hol
      mana: 15
      cambrinth:
      - 25
      - 25

#########################################
##########  Mining Settings    ##########
#########################################

mining_skip_populated: true
mine_implement: shovel
mine_use_packet: true
mining_buddy_vein_list:
- Silver
- Gold
- Platinum
- Lumium
- Darkstone
- Damite
- Kertig
- Haralun
- Glaes
- Animite

#########################################
#########  Crafting Settings    #########
#########################################

crafting_container: haversack
workorder_diff: hard

train_workorders:
- Shaping

work_order_disciplines:
- Shaping

workorder_recipes:
  shaping:
  - shortbow
  - bow
  - longbow

shaping_tools:
- carving knife
- shaper
- drawknife
- rasp

outfiting_tools:
- sewing needles
- scissors
- yardstick
- scraper
- awl

engineering_belt:
  name: carpenter belt
  items:
    - carving knife
    - shaper
    - drawknife
    - rasp
    - saw

outfiting_belt:
  name: outfit belt
  items:
    - sewing needles
    - scissors
    - yardstick
    - awl
    - knitting needles

#########################################
###########  Gear Listings    ###########
#########################################

gear:
- :name: targe
  :is_leather: true
  :hinders_lockpicking: true
  :is_worn: true
  :swappable: false
- :name: stick
  :adjective: parry
  :is_leather: false
  :hinders_lockpicking: false
  :is_worn: true
  :swappable: false
- :name: balaclava
  :adjective: ring
  :is_leather: false
  :hinders_lockpicking: true
  :is_worn: true
- :name: lorica
  :adjective: scale
  :is_leather: false
  :hinders_lockpicking: false
  :is_worn: true
- :name: sleeves
  :adjective: ring
  :is_leather: false
  :hinders_lockpicking: true
  :is_worn: true
- :name: greaves
  :adjective: light
  :is_leather: false
  :hinders_lockpicking: false
  :is_worn: true
- :name: hood
  :adjective: padded
  :is_leather: true
  :hinders_lockpicking: true
  :is_worn: true
- :name: mask
  :adjective: padded
  :is_leather: true
  :hinders_lockpicking: true
  :is_worn: true
- :name: gloves
  :adjective: padded
  :is_leather: true
  :hinders_lockpicking: true
  :is_worn: true
- :name: shirt
  :adjective: padded
  :is_leather: true
  :hinders_lockpicking: false
  :is_worn: true
- :name: pants
  :adjective: padded
  :is_leather: true
  :hinders_lockpicking: false
  :is_worn: true
- :name: knuckles
  :adjective: steel
  :is_leather: false
  :hinders_lockpicking: true
  :is_worn: true
  :swappable: false
- :name: spikes
  :adjective: elbow
  :is_leather: false
  :hinders_lockpicking: true
  :is_worn: true
  :swappable: false
- :name: spikes
  :adjective: knee
  :is_leather: false
  :hinders_lockpicking: true
  :is_worn: true
  :swappable: false
- :name: footwraps
  :adjective: steel
  :is_leather: false
  :hinders_lockpicking: true
  :is_worn: true
  :swappable: false
- :name: longbow
  :adjective: battle
  :is_leather: true
  :is_worn: false
  :swappable: false
  :wield: true
- :name: broadsword
  :is_leather: false
  :is_worn: false
  :swappable: false
  :wield: true
- :name: club
  :adjective: throwing
  :is_leather: false
  :is_worn: false
  :swappable: false
  :wield: true
- :name: hammer
  :adjective: throwing
  :is_leather: false
  :is_worn: false
  :swappable: false
  :wield: true
- :name: sword
  :adjective: bastard
  :is_leather: false
  :is_worn: false
  :swappable: true
  :wield: true
- :name: nightstick
  :is_leather: false
  :is_worn: false
  :swappable: false
  :wield: true
- :name: scimitar
  :is_leather: false
  :is_worn: false
  :swappable: false
  :wield: true
- :name: crossbow
  :is_leather: true
  :is_worn: false
  :swappable: false
  :wield: true

**Comment by reithir** [comment]
Yikes, that formatted kinda janky. All the bullet dots are actually dashes, and the spacing formatting is correct in my yaml. Sorry about that; let me know if there is a better way to post it

**Comment by rpherbig** [comment]
Try putting three back ticks ` before and after the block of YAML

**Comment by reithir** [comment]
```#########################################
##########  Hunting Settings    #########
#########################################

training_manager_hunting_priority: true
training_manager_priority_skills:
- Bow
- Large Edged

hunting_file_list:
- setup
#- backtrain

hunting_info:
- :zone: young_wyverns
  args:
  - d1
  - setup
  stop_on:
  - Bow
  - Large Edged

hunting_buddies:

#########################################
###########  Gear Settings    ###########
#########################################

gear_sets:
  standard:
  - targe
  - parry stick
  - padded hood
  - padded mask
  - padded gloves
  - padded shirt
  - padded pants
  naked: []

#########################################
#########  Combat - General    ##########
#########################################

stances:
  Bow:
  - Evasion
  - Shield Usage
  - Parry Ability
  Crossbow:
  - Evasion
  - Shield Usage
  - Parry Ability
  Light Thrown:
  - Evasion
  - Shield Usage
  - Parry Ability

skinning:
  skin: true
  arrange_all: true
  arrange_count: 1
  tie_bundle: true

#########################################
#########  Combat - Offense    ##########
#########################################

dual_load: true
use_stealth_attacks: true

weapon_training:
  Large Edged: broadsword
  Bow: battle longbow

offensive_spells:
- skill: Debilitation
  name: Swarm
  abbrev: swarm
  mana: 12
  expire: The bugs finally cease swarming
  harmless: true

#########################################
#########  Combat - Defense    ##########
#########################################

buff_spells:
  Instinct:
    abbrev: inst
    recast: 2
    mana: 10
    symbiosis: false
    cambrinth:
    - 20
    - 20
  See the Wind:
    abbrev: stw
    recast: 2
    mana: 10
    symbiosis: false
    cambrinth:
    - 20
    - 20
  Senses of the Tiger:
    abbrev: sott
    recast: 2
    mana: 10
    symbiosis: false
    cambrinth:
    - 20
    - 20
  Hands of Lirisa:
    abbrev: hol
    recast: 2
    mana: 10
    symbiosis: false
    cambrinth:
    - 20
    - 20
  Oath of the Firstborn:
    abbrev: oath
    recast: 2
    mana: 15
    symbiosis: false
    cambrinth:
    - 15
    - 15

#########################################
#########  Combat - Training    #########
#########################################

training_abilities:
  Hunt: 80
  Perc: 120
  Stealth: 60
  App: 60
  Tactics: 30

combat_spell_training:
  Utility:
    abbrev: bes
    cyclic: true
    mana: 15
  Augmentation:
    abbrev: bes
    cyclic: true
    mana: 15
  Warding:
    abbrev: ey
    mana: 10
    symbiosis: true
    cambrinth:
    - 20

#########################################
########  Non-Combat Settings    ########
#########################################

crossing_training:
- Locksmithing
- Engineering

#- Mechanical Lore
#- Appraisal
#- Outdoorsmanship
#- Outfitting
#- Athletics
#- Scouting
#- Attunement
#- Augmentation
#- Utility
#- Warding



#########################################
##########  Spell Training    ###########
#########################################

cast_only_to_train: true
symbiosis_learning_threshold: 3
prep_scaling_factor: 0.95
dedicated_camb_use: spell
cambrinth: armband
cambrinth_cap: 50
stored_cambrinth: false

cyclic_cycle_skills:
- Augmentation
- Utility

training_spells:
  Augmentation:
  Utility:
  Warding:
    abbrev: ey
    symbiosis: true

cyclic_training_spells:
  Augmentation:
    abbrev: BES
    cyclic: true
  Utility:
    abbrev: BES
    cyclic: true
  Warding:

#########################################
#######$###  Misc Settings    ###########
#########################################

hometown: Crossing
favor_god: Everild
favor_goal: 10
listen: true

#########################################
###########  Loot Training    ###########
#########################################

storage_containers:
- duffel bag
- rucksack

gem_pouch_adjective: gem
spare_gem_pouch_container: cloak
loot_subtractions:
loot_additions:

#########################################
#########  Lockpick Settings    #########
#########################################

use_lockpick_ring: true
lockpick_container: case
lockpick_type: stout
harvest_traps: true
picking_box_source: duffel bag
picking_box_storage: rucksack
lockpick_buffs:
  spells:
    - abbrev: hol
      mana: 15
      cambrinth:
      - 25
      - 25

#########################################
##########  Mining Settings    ##########
#########################################

mining_skip_populated: true
mine_implement: shovel
mine_use_packet: true
mining_buddy_vein_list:
- Silver
- Gold
- Platinum
- Lumium
- Darkstone
- Damite
- Kertig
- Haralun
- Glaes
- Animite

#########################################
#########  Crafting Settings    #########
#########################################

crafting_container: haversack
workorder_diff: hard

train_workorders:
- Shaping

work_order_disciplines:
- Shaping

workorder_recipes:
  shaping:
  - shortbow
  - bow
  - longbow

shaping_tools:
- carving knife
- shaper
- drawknife
- rasp

outfiting_tools:
- sewing needles
- scissors
- yardstick
- scraper
- awl

engineering_belt:
  name: carpenter belt
  items:
    - carving knife
    - shaper
    - drawknife
    - rasp
    - saw

outfiting_belt:
  name: outfit belt
  items:
    - sewing needles
    - scissors
    - yardstick
    - awl
    - knitting needles

#########################################
###########  Gear Listings    ###########
#########################################

gear:
- :name: targe
  :is_leather: true
  :hinders_lockpicking: true
  :is_worn: true
  :swappable: false
- :name: stick
  :adjective: parry
  :is_leather: false
  :hinders_lockpicking: false
  :is_worn: true
  :swappable: false
- :name: balaclava
  :adjective: ring
  :is_leather: false
  :hinders_lockpicking: true
  :is_worn: true
- :name: lorica
  :adjective: scale
  :is_leather: false
  :hinders_lockpicking: false
  :is_worn: true
- :name: sleeves
  :adjective: ring
  :is_leather: false
  :hinders_lockpicking: true
  :is_worn: true
- :name: greaves
  :adjective: light
  :is_leather: false
  :hinders_lockpicking: false
  :is_worn: true
- :name: hood
  :adjective: padded
  :is_leather: true
  :hinders_lockpicking: true
  :is_worn: true
- :name: mask
  :adjective: padded
  :is_leather: true
  :hinders_lockpicking: true
  :is_worn: true
- :name: gloves
  :adjective: padded
  :is_leather: true
  :hinders_lockpicking: true
  :is_worn: true
- :name: shirt
  :adjective: padded
  :is_leather: true
  :hinders_lockpicking: false
  :is_worn: true
- :name: pants
  :adjective: padded
  :is_leather: true
  :hinders_lockpicking: false
  :is_worn: true
- :name: knuckles
  :adjective: steel
  :is_leather: false
  :hinders_lockpicking: true
  :is_worn: true
  :swappable: false
- :name: spikes
  :adjective: elbow
  :is_leather: false
  :hinders_lockpicking: true
  :is_worn: true
  :swappable: false
- :name: spikes
  :adjective: knee
  :is_leather: false
  :hinders_lockpicking: true
  :is_worn: true
  :swappable: false
- :name: footwraps
  :adjective: steel
  :is_leather: false
  :hinders_lockpicking: true
  :is_worn: true
  :swappable: false
- :name: longbow
  :adjective: battle
  :is_leather: true
  :is_worn: false
  :swappable: false
  :wield: true
- :name: broadsword
  :is_leather: false
  :is_worn: false
  :swappable: false
  :wield: true
- :name: club
  :adjective: throwing
  :is_leather: false
  :is_worn: false
  :swappable: false
  :wield: true
- :name: hammer
  :adjective: throwing
  :is_leather: false
  :is_worn: false
  :swappable: false
  :wield: true
- :name: sword
  :adjective: bastard
  :is_leather: false
  :is_worn: false
  :swappable: true
  :wield: true
- :name: nightstick
  :is_leather: false
  :is_worn: false
  :swappable: false
  :wield: true
- :name: scimitar
  :is_leather: false
  :is_worn: false
  :swappable: false
  :wield: true
- :name: crossbow
  :is_leather: true
  :is_worn: false
  :swappable: false
  :wield: true
```

**Comment by reithir** [comment]
thanks, that's better

**Comment by rcuhljr** [comment]
`outfiting_belt:` `outfiting_tools:`  Note you only have one T in both of those.

**Comment by reithir** [comment]
Argh, oops. Of course I misspelled it. Thank you!
