### ISSUE TITLE
BARD - training stalls casting cyclics in Crossing-tr

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1078]
[Lindale_Crossing_Stop.txt](https://github.com/rpherbig/dr-scripts/files/614409/Lindale_Crossing_Stop.txt)
[Lindale_Phoenix(1).txt](https://github.com/rpherbig/dr-scripts/files/614408/Lindale_Phoenix.1.txt)

YAML here   http://pastebin.com/Srav57PN

**Comment by rpherbig** [comment]
I added a missing message in e8bc1cdb69e4f95a0f83c78d67147386b8e44389

There is also a problem in the YAML: Warding is in `crossing_training` but no spell is defined for it. Does `;validate` show an error?

**Comment by Aurayn** [comment]
>;validate
--- Lich: validate active.
[validate: Checking 33 different potential errors]
[validate: All done!]
--- Lich: validate has exited.

**Comment by rpherbig** [comment]
I'll write a validator for that tonight.

Does everything work if you remove Warding?

**Comment by Aurayn** [comment]
great news guys this is working!  i know because afterr hunting  it went back into Crossing and i got. 25 plat fine fir not releasing DALU. 

can someone check that?
