### ISSUE TITLE
Listening as a Trader

### ISSUE THREAD

**Issue by drjunkie** [rpherbig/dr-scripts#1082]
Right now I walk in to a room with someone teaching (like Xaji) and assess teach. I see that he's teaching TM and start listening.

The game gives me the message "You're not sure what use the Targeted Magic skill could ever be to you, but you don't see any harm in listening to Xaji."

Crossing train then inputs >stop listening

I would like to get the scholarship at least from listening, and i have listen: true in my YAML.

Could we make it not >stop listening as a trader?

**Comment by rpherbig** [comment]
I think the best short-term fix is to enable magic classes for traders by default.

#979 is a good long-term fix.
