### ISSUE TITLE
Constant Errors with Combat-Trainer

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#1089]
http://pastebin.com/fHRPmqCj  - Log
http://pastebin.com/2f7EWtv1 - ;e help
http://pastebin.com/gYxztC7V - my YAML file

This actually happens with my other characters too.  Combat-trainer will not launch.  I try to kill depend, and restart, and usually that does it, but often enough i have to kill dependency multiple times.  Ocassionally i've resulted to exiting the game and relaunching it to troubleshoot the issue.  Not sure what the deal is. 

--- Lich: combat-trainer active.
 
--- Lich: error: wrong number of arguments (1 for 0)
    combat-trainer:1512:in `initialize'
    combat-trainer:1512:in `new'
 
--- Lich: combat-trainer has exited.

**Comment by rcuhljr** [comment]
Ok a couple of things need sorted out. Firstly it looks like you have a couple of our scripts in ;autostart other than dependency. This may well be causing problems, remove them from there and add them using step six [here](https://github.com/rpherbig/dr-scripts/wiki/First-Time-Setup). Also your yaml files should be named with an uppercase M, but that just screws up ;e help_me apparently. After the next time you restart your client do a new ;e help_me as I want to make sure you're still getting dependency updates. Did you turn on developer mode at some point and start updating scripts manually?

**Comment by wscherer420** [comment]
How can i tell which scripts are "yours" versus not?  Not sure which to remove.  Also i made the M uppercase on my files but now i receive the following error when i do ;e help

>;e help
--- Lich: exec1 active.
--- Exception: undefined local variable or method `help' for main:Object
exec1:1:in `_script'
--- Lich: exec1 has exited.


CURRENT SCRIPTS IN AUTOSTART BELOW
--- Global autostart scripts: alias, lnet, repository (args: download-updates), tending, dependency, textsubs, roomnumbers, skill-recorder

--- Mistified's autostart scripts: tending, roomnumbers, textsubs

**Comment by wscherer420** [comment]
I removed tending, roomnumbers, and textsubs from the autostart and added them to the ;e autostart.  I did another ;e help_me. 

http://pastebin.com/psrjaB36

**Comment by rcuhljr** [comment]
>How can i tell which scripts are "yours" versus not?

Anything from this github repository is ours. You want to remove textsubs, roomnumbers, and skill-recorder. Remove the last of them and see if you're still getting these errors. If so maybe reinstall dependency. The only thing I can think of is some of your scripts are being locked by your OS so that dependency can't replace them with the latest version.

**Comment by rcuhljr** [comment]
I may have found and fixed part of your error. Let me know if this problem resolves itself.

**Comment by wscherer420** [comment]
So far everything is working good.  The only things i did was current the uppercase issue on my YAML files, and then remove the autostart scripts and added them on the lich autostart.  That took care of the issues i was experiencing.  I am still having an issue with my Necro not dropping material from corpses he harvests, but that may be a separate issue?

**Comment by rcuhljr** [comment]
It is, our necro players are hunting down that problem. Sorry for the issues!

**Comment by wscherer420** [comment]
No worries! I appreciate the support, couldn't do a 10th of what i'm doing without you guys.
