### ISSUE TITLE
Missing messaging for combat maneuvers versus flying creatures

### ISSUE THREAD

**Issue by cynesis** [rpherbig/dr-scripts#1091]
>[combat-trainer]>maneuver powershot
>You must be standing to perform that maneuver.

>[combat-trainer: checked against [/You brace your/i, /balanced and/i, /Taking a full step back/i, /You take a step back/i, /You lower your shoulders/i, /You angle to the side and /i, /rest a bit longer/i, /You square up your feet/i]]

**Comment by rpherbig** [comment]
This seems like an odd timing thing. SafetyProcess should make you stand pretty soon after something knocks you over.

**Comment by cynesis** [comment]
Certainly an odd timing maneuver. Below is a log of the most recent event (i.e., this issue). Note that the charged maneuver command is executed, _and then_ I am knocked prone. It looks to be occurring during this particular point in the code:

>    attempt = bput("maneuver #{action}", 'You brace your', 'balanced and', 'Taking a full step back', 'You take a step back', 'You lower your shoulders', 'You angle to the side and ', 'rest a bit longer', 'You square up your feet')
>    return if attempt == 'rest a bit longer'
>
>    # Maneuvers have extra non-RT delays
>    pause 7
>    waitrt?

So, adding the standing message to the bput() resolves the issue if you are _already prone_ when the command executes, but not if you fall during that lengthy but necessary pause.



> [combat-trainer: action count: 0 vs 10]
> 
> [combat-trainer: skill exp: 32 vs 34]
> 
> [combat-trainer: ***Fatigue: 100***]
> 
> [combat-trainer: ***Target: 85***]
> 
> [combat-trainer: ***Ready to use charged maneuver: powershot***]
> 
> [combat-trainer]>maneuver powershot
> 
> > 
> * A young forest gryphon rakes a set of large, sharp claws at you.  You barely block with a small gryphon-pelt shield sealed with protective wax.  
> [You're slightly off balance with opponent dominating.]
> > 
> A silver-tipped mature forest gryphon rears itself on its haunches and flaps its wings.  Heavy gusts of wind buffet and swirl around you.
> Failing to leap in time, you get twisted about in the winds, losing your balance and falling to the ground!
> 
> P> 
> * A young forest gryphon rakes a set of large, sharp claws at you.  You evade, ducking in the nick of time.  
> [You're very badly balanced with opponent in strong position.]
> P> 
> You must be standing to perform that maneuver.
> P> 
> P> 
> P> 
> You feel fully prepared to cast your spell.
> P> 
> P> 
> P> 
> P> 
> P> 
> * With strength, a young forest gryphon rakes a set of large, sharp claws at you.  You fail to dodge.  
> The claw lands a skimming (0/23) strike to your chest.
> [You're very badly balanced with opponent overwhelming you.]
> P> 
> The air around you solidifies into a dull yellow haze and intercepts the attack with a shower of coruscating light.
> * Moving fluidly, a young forest gryphon rakes a set of large, sharp claws at you.  You fail to dodge.  
> The claw lands a light hit (1/23) to your right leg.
> [You're bruised, very badly balanced with opponent in excellent position.]
> P> 
> P> 
> P> 
> P> 
> The air around you solidifies into a dull yellow haze and throws off bright waves of light as it resists the attack.
> * Moving in gracefully, a silver-tipped mature forest gryphon rakes a set of large, sharp claws at you.  You fail to block with a small gryphon-pelt shield sealed with protective wax.  
> The claw lands a light hit (1/23) to your right leg.
> [You're bruised, very badly balanced with opponent dominating.]
> P> 
> P> 
> The air around you solidifies into a dull yellow haze and throws off shimmering light in the wake of the attack.
> * With great skill, a young forest gryphon rakes a set of large, sharp claws at you.  You barely fail to block with small shield.  
> The claw lands a light hit (1/23) to your left arm.
> [You're bruised, very badly balanced with opponent overwhelming you.]
> P> 
> The air around you solidifies into a dull yellow haze, buckling and losing much of its mass under the force of the attack.
> * Moving in gracefully, a young forest gryphon rakes a set of large, sharp claws at you.  You barely fail to block with small shield.  
> The claw lands a light hit (1/23) to your right leg.
> [You're bruised, very badly balanced with opponent in very strong position.]
> P> 
> [DRPrime]-DR:Byd: "I use thievery to train stealth on my bard"
> 
> P> ,chat Yeah. Empath reqs (and Traders to a lesser extent) are ridiculous.
> 
> [combat-trainer: *** No match was found after 15 seconds, dumping info]
> 
> [combat-trainer: messages seen length: 26]
> 
> [combat-trainer: message: * A young forest gryphon rakes a set of large, sharp claws at you.  You barely block with a small gryphon-pelt shield sealed with protective wax.  ]
> 
> [combat-trainer: message: [You're slightly off balance with opponent dominating.]]
> 
> [combat-trainer: message: A silver-tipped mature forest gryphon rears itself on its haunches and flaps its wings.  Heavy gusts of wind buffet and swirl around you.]
> 
> [combat-trainer: message: Failing to leap in time, you get twisted about in the winds, losing your balance and falling to the ground!]
> 
> [combat-trainer: message: * A young forest gryphon rakes a set of large, sharp claws at you.  You evade, ducking in the nick of time.  ]
> 
> [combat-trainer: message: [You're very badly balanced with opponent in strong position.]]
> 
> [combat-trainer: message: You must be standing to perform that maneuver.]
> 
> [combat-trainer: message: You feel fully prepared to cast your spell.]
> 
> [combat-trainer: message:  * Miss Wendelle arrives, looking forward to another day of fun!]
> 
> [combat-trainer: message: * With strength, a young forest gryphon rakes a set of large, sharp claws at you.  You fail to dodge.  The claw lands a skimming strike to your chest.]
> 
> [combat-trainer: message: [You're very badly balanced with opponent overwhelming you.]]
> 
> [combat-trainer: message: The air around you solidifies into a dull yellow haze and intercepts the attack with a shower of coruscating light.]
> 
> [combat-trainer: message: * Moving fluidly, a young forest gryphon rakes a set of large, sharp claws at you.  You fail to dodge.  The claw lands a light hit to your right leg.]
> 
> [combat-trainer: message: [You're bruised, very badly balanced with opponent in excellent position.]]
> 
> [combat-trainer: message: Manifest Force  (11 roisaen)]
> 
> [combat-trainer: message: Obfuscation  (16 roisaen)]
> 
> [combat-trainer: message: The air around you solidifies into a dull yellow haze and throws off bright waves of light as it resists the attack.]
> 
> [combat-trainer: message: * Moving in gracefully, a silver-tipped mature forest gryphon rakes a set of large, sharp claws at you.  You fail to block with a small gryphon-pelt shield sealed with protective wax.  The claw lands a light hit to your right leg.]
> 
> [combat-trainer: message: [You're bruised, very badly balanced with opponent dominating.]]
> 
> [combat-trainer: message: The air around you solidifies into a dull yellow haze and throws off shimmering light in the wake of the attack.]
> 
> [combat-trainer: message: * With great skill, a young forest gryphon rakes a set of large, sharp claws at you.  You barely fail to block with small shield.  The claw lands a light hit to your left arm.]
> 
> [combat-trainer: message: [You're bruised, very badly balanced with opponent overwhelming you.]]
> 
> [combat-trainer: message: The air around you solidifies into a dull yellow haze, buckling and losing much of its mass under the force of the attack.]
> 
> [combat-trainer: message: * Moving in gracefully, a young forest gryphon rakes a set of large, sharp claws at you.  You barely fail to block with small shield.  The claw lands a light hit to your right leg.]
> 
> [combat-trainer: message: [You're bruised, very badly balanced with opponent in very strong position.]]
> 
> [combat-trainer: message: [DRPrime]-DR:Byd: "I use thievery to train stealth on my bard"]
> 
> [combat-trainer: checked against [/You brace your/i, /balanced and/i, /Taking a full step back/i, /You take a step back/i, /You lower your shoulders/i, /You angle to the side and /i, /rest a bit longer/i, /You square up your feet/i]]
> 
> [DRPrime]-You: "Yeah. Empath reqs (and Traders to a lesser extent) are ridiculous."
> P> 
> P> 
> A silver-tipped mature forest gryphon rears itself on its haunches and flaps its wings.  Heavy gusts of wind buffet and swirl around you.
> Because you are already lying down you are unaffected.
> P> stand
> You stand back up.
