### ISSUE TITLE
Adding further Sorcery Support

### ISSUE THREAD

**Issue by drboldwin** [rpherbig/dr-scripts#1095]
Not sure there is an issue for this yet (searched some key words and didn't see anything) so apologize if there is.

But want to start a discussion about adding symbiosis support to sorcery casting.  Currently it is very mana consuming to cast sorcery for training purposes without it (I'm casting in the 40-50 range just to learn) but when I swapped over the casting logic to work similar to how regular spells train in crossing-training and therefore support symbiosis I saw a marked improvement in both training time and mana consumption.

So I'm thinking we start listing sorcery similar to how we list other spells

```
Sorcery:
  abbrev: shadows
  symbiosis: true
```

and the push it through the standard casting logic we already use in crossing-training.  We could likely just copy that code into common-arcana, or even move all casting logic code into that area and simply call it from crossing-training.  (just another idea)

**Comment by rpherbig** [comment]
This should be working

**Comment by rpherbig** [comment]
Sorry, hit send too soon. Sorcery should use symbiosis if it is set, but
will not automatically adjust mana up and down. Is that what you are
suggesting?

**Comment by drboldwin** [comment]
yeah - smart sorcery like we have smart magic training
