### ISSUE TITLE
Harvest Ritual Issue - Not dropping Material

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#1099]
http://pastebin.com/TtYu8Kcq

I heard you guys are working on this.  Posted my Log of it in case it helps.  Looks like the drop material gets caught up in roundtime?

**Comment by wscherer420** [comment]
also, it also seems to only happen when i'm using my shortbow.

**Comment by rpherbig** [comment]
ee8022668dd1b38fcd82dbbc4127ba4e0f05ee2f should help us debug this...

**Comment by jandersson** [comment]
Would expanding `@rituals['failure']` with `*@rituals['failure']` help as an input to bput? I don't see a difference when i test it out, but i also cant recreate the issue.

**Comment by rpherbig** [comment]
You should not need to flatten (see `pick.lic`).

**Comment by jandersson** [comment]
OK cool. I'm noticing that in this log and the log jhien posted, the player gets attacked right after they input the command

**Comment by jandersson** [comment]
I think the players may be loading old data from profiles/base-spells.yaml instead of data/base-spells.yaml
The old data in profiles/ doesn't have entries for failure messages or constructs so `@rituals['failures']` is nil and bput matches on the empty string. 

I asked Jhien to delete/rename this old file and he hasn't had the issue since

**Comment by wscherer420** [comment]
I do still have my base-spells file in my profile folder.  However, i deleted all the base named files in my profile folder and it cause an entire array of issues for me.  I could create a log of the events that occur after deleted those files.  But perhaps that's not the proper procedure for transitioning from base in profile to base in data?

**Comment by rpherbig** [comment]
base.yaml and base-empty.yaml should both stay in profiles. The rest can be deleted.

**Comment by jandersson** [comment]
If you rename them to something like `old-base-X.bak`, then you can delete them when you're sure nothings broken.

**Comment by wscherer420** [comment]
Here is the log of what occurs when i delete all files except the base and base-empty.  at the bottom of the log is where the error occurs.  http://pastebin.com/kxx8sMyV

**Comment by wscherer420** [comment]
So i deleted all files except base, base-empty, and base-items from my profile folder.  I kept base items because my Necro was getting the same error message as my Cleric in the above pastebin link regarding gem nouns.  My Necro is no longer hanging onto the material.  But not sure why i need to keep the base-items file for it to work.

**Comment by wscherer420** [comment]
Ok so I visited the data folder file list on Github and realized I, for whatever reason, was missing a bunch of the scripts that should have been in there.  I've since made sure my data folder matches what's on the github site and it looks like it has cured my issues.  I'll keep posted if there is anything else, but for now i think you guys figured it out. Thanks again for all the support.
