### ISSUE TITLE
Forging - sipar and shield needs editing

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1101]
When running the below commands:
;forge armorsmithing 4 "metal round sipar " lumium sipar
;forge armorsmithing 4 "metal target shield" lumium shield

there are two asemblies required: 

(1) finished metal shield handle
(1) finished long leather cord

the commands are wrong after the first of each assemblies and the script stalls. Please see below: 

http://pastebin.com/gF4drtTY

**Comment by rcuhljr** [comment]
I don't think this issue is actually closed? Shields don't work like the rest of armor for assembly and that needs fixed.
