### ISSUE TITLE
Issue with cycle_armors.

### ISSUE THREAD

**Issue by jayRyan24** [rpherbig/dr-scripts#1110]
cycle_armors isn't handling unlisted items correctly. It doesn't see my quilted pants when it checks, it then just gets my chain greaves and tries to wear them. 

Adding:
```
Light Armor:
- quilted pants
```

fixes the issue.

http://pastebin.com/fHnVLBdz

**Comment by rcuhljr** [comment]
Yeah, if you don't want to wear the quilted pants at all in that hunting spot don't list them in your gear_set standard.
