### ISSUE TITLE
Necromancer Consume ritual being overwritten by dissect

### ISSUE THREAD

**Issue by cynesis** [rpherbig/dr-scripts#1127]
```
[combat-trainer]>health

Your body feels slightly battered.
Your spirit feels full of life.
You have some minor abrasions to the neck, a severely swollen and deeply bruised right arm compounded by deep cuts across the right arm, some minor abrasions to the left arm, minor swelling and bruising around the right leg compounded by cuts and bruises about the right leg, some minor abrasions to the left leg, some tiny scratches to the left hand, some minor abrasions to the chest, some tiny scratches to the abdomen.

Bleeding
            Area       Rate              
\-----------------------------------------
       right arm       (tended)
   inside r. arm       slight

!> 
[combat-trainer: Severity to Wounds: {1=>["neck", "left arm", "left leg", "chest"], 4=>["right arm"], 5=>["right arm"], 3=>["right leg"], 2=>["left hand", "abdomen"]}]

[combat-trainer: Attempting necromancer ritual consume on gryphon]

[combat-trainer: Attempting necromancer ritual preserve on gryphon]

[combat-trainer]>perform preserve on gryphon

You bend over the gryphon's corpse to make one long, continuous cut with your ritual knife that just barely pierces into it.  Unseen energies seep into the creature's fluids, suspending the corpse in unnatural stasis for a time.
Roundtime: 4 sec.
!R> 
[combat-trainer: Unseen energies seep into the creature's fluids, suspending the corpse in unnatural stasis for a time]

[combat-trainer: Detected preserve or dissect messaging]

[combat-trainer: Last ritual performed: preserve]

[hunting-buddy: ***STATUS*** 18 minutes of hunting remaining or waiting on Targeted Magic, Thanatology, Skinning, Stealth]

[combat-trainer]>perform consume on gryphon

!> 
A torrent of sizzling, bile-green acid sprays outward from you!
!> 
[combat-trainer: ]

[combat-trainer: Last ritual performed: preserve]

[combat-trainer: Attempting necromancer ritual dissect on gryphon]

[combat-trainer]>perform dissect on gryphon

You kneel over the young forest gryphon's corpse and make a few quick, precise cuts with your ritual knife.  Your cuts follow the vital lines of the corpse, causing its residual life force to bubble forth, ready for draining.
Roundtime: 4 sec.
!R> 
[combat-trainer: a few quick, precise cuts with your ritual knife]

[combat-trainer: Detected consume messaging]

[combat-trainer: Last ritual performed: dissect]
```

**Comment by rpherbig** [comment]
I don't see what caused the consume to fail... it didn't say you were stuck in RT. Was a message filtered out?

**Comment by cynesis** [comment]
It's hard to tell, but it issues a preserve ritual, which sets last ritual to preserve. Then, it issues a consume ritual, followed immediately by a dissect ritual. The consume ritual, being the first command, executes and the dissect ritual command hits an RT wait. However, Lich still thinks dissect is the last ritual. See here:

[combat-trainer: Last ritual performed: preserve]
[combat-trainer]>perform consume on gryphon

> There's the consume ritual command

[combat-trainer: Last ritual performed: preserve]

[combat-trainer: Attempting necromancer ritual dissect on gryphon]

[combat-trainer]>perform dissect on gryphon

> There's the dissect ritual command

You kneel over the young forest gryphon's corpse and make a few quick, precise cuts with your ritual knife. Your cuts follow the vital lines of the corpse, causing its residual life force to bubble forth, ready for draining.
Roundtime: 4 sec.

> But that's a consume ritual

!R>
[combat-trainer: a few quick, precise cuts with your ritual knife]

[combat-trainer: Detected consume messaging]

[combat-trainer: Last ritual performed: dissect]

> So combat trainer thinks dissect was the last ritual, despite detecting the consume messaging.

**Comment by rpherbig** [comment]
Oh, I see what you're saying. That is strange, I wonder if @jandersson came across something like that when he was debugging rituals...

**Comment by jandersson** [comment]
it looks like youre using the old data file in the profiles folder

```
[combat-trainer]>perform consume on gryphon

!> 
A torrent of sizzling, bile-green acid sprays outward from you!
!> 
[combat-trainer: ]
```

That empty line from combat trainer is the string it matched on when it performed the ritual. Since `@ritual['construct']` and `@ritual['failure']` is missing from that file, it matches on anything

**Comment by jandersson** [comment]
To fix, delete `profiles/base-spells.yaml`

**Comment by cynesis** [comment]
Issue resolved.
