### ISSUE TITLE
casting spells QoL for combat-trainer

### ISSUE THREAD

**Issue by izawwlgood** [rpherbig/dr-scripts#1132]
It'd be nice if the logic for spellcasting could be adjusted to INVOKE [cambrinth] just before casting the spell, instead of immediately after prepping/charging.  This would save the need to pick up the Dedicated Cambrinth feat. 

Currently it looks like INVOKE occurs right after a CHARGE action, and the CAST waits for full prep (or whatever is designated).

**Comment by rcuhljr** [comment]
Should be in place.
