### ISSUE TITLE
crossing-training: shard hometown + athletics at gondola area

### ISSUE THREAD

**Issue by caseysinger** [rpherbig/dr-scripts#1134]
hometown: Shard
safe_room: 2801 (right outside of shard north gate)
Athletics:  635

When training athletics, it takes me all the way up to the north side of the segoltha before AND after training athletics.
Room Number: 1894, I see this on Line 707 in crossing-training.  

Edit: I said gondola, I meant Segoltha

**Comment by rcuhljr** [comment]
Fixed hopefully, let me know if it doesn't work.

**Comment by caseysinger** [comment]
Tested and confirmed good.  Thanks all.
