### ISSUE TITLE
Forge: Push tub issue

### ISSUE THREAD

**Issue by jayRyan24** [rpherbig/dr-scripts#1142]
**Push tub** doesn't work with people using Tub as a start of their name...

http://pastebin.com/aVf4tB9J

**Comment by rpherbig** [comment]
Did you check if `push first tub` works?

**Comment by jayRyan24** [comment]
I didn't, I requested Tubba to try it out, but I think he missed it and didn't. I'll touch base with him/Kekahuna and see if it works. If so, I'll patch it in.

**Comment by Kekahunadr** [comment]
ok sorry i missed all this 
if i put PUSH S TUB it work
so im guessing that is PUSH SLAC TUB

**Comment by Kekahunadr** [comment]
>tap slac tub
>
You tap a slack tub filled with water.

**Comment by Kekahunadr** [comment]
[forge]>push tub
>
You twitch.
>push slack tub
Gusts of hot steam billow from the tub as you submerse the scorching hot tall mug.

The worked metal looks to be in need of some oil to preserve and protect it.
Roundtime: 18 sec.

**Comment by Kekahunadr** [comment]
there thats better
