### ISSUE TITLE
ALCHEMY - Limb Potion not working

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1148]
Maybe I am misunderstanding the system, but FORAGED and crushed yelith doesnt work ???

```
>;remedy remedies 4 "limb potion" yelith water "coal nugget" mortar potion
--- Lich: remedy active.
[remedy]>get remed book
You get a book of master remedy instructions from inside your backpack.
>
[remedy]>turn my book to chapter 4
You turn your book to chapter 4, entitled "Internal Wound Remedies".
>
[remedy]>read my book
              -=    Chapter 4 : Internal Wound Remedies    =-

 Page 1: a head potion                           Page 10: some chest tonic
 Page 2: a chest potion                          Page 11: some abdominal tonic
 Page 3: an abdomen potion                       Page 12: some neck tonic
 Page 4: a neck potion                           Page 13: some eye tonic
 Page 5: an eye potion                           Page 14: some back tonic
 Page 6: a back potion                           Page 15: some limb tonic
 Page 7: a limb potion                           Page 16: some skin tonic
 Page 8: a skin potion                           
 Page 9: some head tonic                         
>
[remedy]>turn my book to page 7
You turn your book to page 7, instructions for crafting a limb potion.
>
[remedy]>study my book
You scan the limb potion instructions with a glance and comprehend all but several minor details in the text.
You now feel ready to begin the crafting process.
Roundtime: 8 sec.
>
[remedy]>put my book in my bag
You put your book in your duffel bag.
>
[remedy]>untie my mortar from my alchemist's belt
You remove an iron mortar from your alchemist's belt.
>
[remedy]>get my yelith
You get some crushed yelith from inside your backpack.
>
[remedy]>put yelith in my mortar
You put your yelith in your iron mortar.
>
[remedy]>put my yelith in my bag
What were you referring to?
>
[remedy]>untie my mortar from my alchemist's belt
Untie what?
>
[remedy]>get my yelith
You get some crushed yelith from inside your iron mortar.
>
[remedy]>put yelith in my mortar
You put your yelith in your iron mortar.
>
[remedy]>put my yelith in my bag
What were you referring to?
>
[remedy]>untie my pestle from my alchemist's belt
You remove an iron pestle from your alchemist's belt.
>
[remedy]>crush my yelith with my pestle
**You stop, realizing that type of plant requires a cooking pot and mixing stick.**
```

**Comment by Aurayn** [comment]
EUREKA looks like it needs to be told to use the BOWL


You get a book of master remedy instructions from inside your duffel bag.
>study book
You scan the limb potion instructions with a glance and comprehend all but several minor details in the text.
You now feel ready to begin the crafting process.
Roundtime: 5 sec.
>stow book
You put your book in your backpack.
>get mix stick
You get a grooved covellite mixing stick with a tempered finish from inside your backpack.
>mix bowl with sti
With wide strokes you mix an unfinished yelith potion with your stick.  Peering at the solution reveals it is mixing correctly.

Upon completion you see some particulate clouding up the mixture.
Roundtime: 15 sec.

You need another splash of water to continue crafting an unfinished yelith potion.  You believe you can pour or put it into the bowl, pot or cauldron and continue mixing the unfinished brew inside.

[Ingredients can be added by putting them with the unfinished item and continuing to craft.]
>

**Comment by rpherbig** [comment]
FYI @Dartellum

**Comment by Dartellum** [comment]
Limb potion is set to false in base recipes and to use a bowl:
- name: a limb potion
  noun: potion
  volume: 1
  type: remedies
  work_order: false
  chapter: 4
  container: bowl
  herb1: yelith
  herb1_stock:

**Comment by Aurayn** [comment]
This wasnt work orders it was using ;remedy remedies 3 "limb salve" jadice water "coal nugget" mortar salve

does mortar need to be bowl maybe?

**Comment by Dartellum** [comment]
Yes, change mortar to bowl. Also, for purchased or dried herbs requiring 
crushing first then put into the bowl, the script is not setup to do 
that, yet. You would the herb prepared first before launching the 
script. Maybe over the Holiday I can look into that.

-- 
Regards,
Dr. Walter Wesley "Wes" Snyder V
484-300-4833 (h)
484-431-3355 (m)
484-302-7006 (f)
