### ISSUE TITLE
;Scroll-Search addition request

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1152]
request to have **treasure chest** added to the options searchable in container:    The container to search.

;scroll-search search "treasure chest"
--- Lich: scroll-search active.
[scroll-search]>stow right
You put your chest in your journey pack.
>
[scroll-search]>remove my treasure chest
Remove what?

 
its trying to remove it
only looks for wearables and stows if it is in your hand

**Comment by Aurayn** [comment]
anyone able to look at this?

the *remove* is killing me

**Comment by rcuhljr** [comment]
Should be fixed.
