### ISSUE TITLE
Add You easily strap to combat-trainer for new baldric.

### ISSUE THREAD

**Issue by Dartellum** [rpherbig/dr-scripts#1160]
```
[combat-trainer]>stow right
You easily strap your stone broadsword to a cloth-of-gold baldric clasped with an onyx scorpion.
>
The air around you shimmers with a weak yellow light that quickly disperses.
>
You shiver involuntarily as a cold breeze rushes through a small airy fissure.
>
[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 4]
[combat-trainer: message: You easily strap your stone broadsword to a cloth-of-gold baldric clasped with an onyx scorpion.]
[combat-trainer: message: The air around you shimmers with a weak yellow light that quickly disperses.]
[combat-trainer: message: You shiver involuntarily as a cold breeze rushes through a small airy fissure.]
[combat-trainer: message: [DRPrime]-DR:Jhien: "does afk prevent logout?"]
[combat-trainer: checked against [/You put/i, /The braided (.+) is too long/, /is too long/i]]
```

**Comment by rpherbig** [comment]
Related to #1074, but that was equipmanager. This one looks like `empty_hands` in common.

**Comment by Dartellum** [comment]
[combat-trainer]>stow my staff
You easily strap your steel staff to a cloth-of-gold baldric clasped with an onyx scorpion.
>
* Apparently without direction or thought, a sabre-toothed warcat slices wide at you.  You partially block with a crimson-scale targe with fitted seams.
[You're adeptly balanced and in dominating position.]
>
* Trying weakly, a red bear orc reiver sweeps low at you.  You barely block with a crimson-scale targe with fitted seams.  
[You're adeptly balanced and in better position.]
>
* Apparently without direction or thought, a red bear orc reiver feints low at you.  You dodge, jumping to one side.
[You're adeptly balanced and opponent has slight advantage.]
>
* Trying inexpertly, a red bear orc reiver chops a rusty steel battle-axe at you.  You barely block with a crimson-scale targe with fitted seams.
[You're adeptly balanced and in good position.]
>
A sabre-toothed warcat gestures at you.
Vibrant orange flames seem to flicker in the sabre-toothed warcat's yellow eyes, capturing your attention with a mesmerising stare.
You feel a calm wash over you, but you think about blood and gore for a moment and it goes away.
>
* Trying inexpertly, a red bear orc reiver sweeps low at you.  You barely block with a crimson-scale targe with fitted seams.
[You're nimbly balanced and opponent has slight advantage.]
>
* As if fumbling muscle flab were natural, a sabre-toothed warcat lashes out with large, velvet-padded claws extended at you.  You partially block with a crimson-scale targe with fitted seams.
[You're nimbly balanced and in good position.]
>
* Trying inexpertly, a red bear orc reiver slices a rusty steel battle-axe at you.  You barely block with a crimson-scale targe with fitted seams.
[You're nimbly balanced and opponent has slight advantage.]
>
Divine Hammer Rakkor just arrived.
>
Divine Hammer Rakkor went through the village gate.
>
The orc reiver moves into a position to parry.
>
The sabre-toothed warcat stalks out of the area.
>
A gusty but warm breeze continues to swirl around you.
>
You feel fully prepared to cast your spell.
>
The strong smell of ozone accompanies a bolt discharging through a sabre-toothed warcat.
The strong smell of ozone accompanies a bolt discharging through a red bear orc reiver.
The strong smell of ozone accompanies a bolt discharging through a red bear orc reiver.
The strong smell of ozone accompanies a bolt discharging through a red bear orc reiver.
>
* Attacking inexpertly, a red bear orc reiver slices a rusty steel battle-axe at you.  You barely block with a crimson-scale targe with fitted seams.
[You're adeptly balanced and have slight advantage.]
>
* Moving inexpertly, a sabre-toothed warcat lashes out with large, velvet-padded claws extended at you.  You evade, just stepping out of harm's way.
[You're adeptly balanced and in superior position.]
>
* Trying weakly, a red bear orc reiver chops a rusty steel battle-axe at you.  You barely block with a crimson-scale targe with fitted seams.
[You're adeptly balanced with no advantage.]
>
[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 41]
[combat-trainer: message: You easily strap your steel staff to a cloth-of-gold baldric clasped with an onyx scorpion.]
[combat-trainer: message: * Apparently without direction or thought, a sabre-toothed warcat slices wide at you.  You partially block with a crimson-scale targe with fitted seams.  ]
[combat-trainer: message: [You're adeptly balanced and in dominating position.]]
[combat-trainer: message: * Trying weakly, a red bear orc reiver sweeps low at you.  You barely block with a crimson-scale targe with fitted seams.  ]
[combat-trainer: message: [You're adeptly balanced and in better position.]]
[combat-trainer: message: * Apparently without direction or thought, a red bear orc reiver feints low at you.  You dodge, jumping to one side.  ]
[combat-trainer: message: [You're adeptly balanced and opponent has slight advantage.]]
[combat-trainer: message: * Trying inexpertly, a red bear orc reiver chops a rusty steel battle-axe at you.  You barely block with a crimson-scale targe with fitted seams.  ]
[combat-trainer: message: [You're adeptly balanced and in good position.]]
[combat-trainer: message: Manifest Force  (22 roisaen)]
[combat-trainer: message: Y'ntrel Sechra  (1 roisan)]
[combat-trainer: message: Sure Footing  (31 roisaen)]
[combat-trainer: message: Ignite  (11 roisaen)]
[combat-trainer: message: Ethereal Shield  (3 roisaen)]
[combat-trainer: message: Electrostatic Eddy  (Indefinite)]
[combat-trainer: message: Swirling Winds  (30 roisaen)]
[combat-trainer: message: Mantle of Flame  (1 roisan)]
[combat-trainer: message: Substratum  (29 roisaen)]
[combat-trainer: message: A sabre-toothed warcat gestures at you.]
[combat-trainer: message: Vibrant orange flames seem to flicker in the sabre-toothed warcat's yellow eyes, capturing your attention with a mesmerising stare.]
[combat-trainer: message: You feel a calm wash over you, but you think about blood and gore for a moment and it goes away.]
[combat-trainer: message: * Trying inexpertly, a red bear orc reiver sweeps low at you.  You barely block with a crimson-scale targe with fitted seams.  ]
[combat-trainer: message: [You're nimbly balanced and opponent has slight advantage.]]
[combat-trainer: message: * As if fumbling muscle flab were natural, a sabre-toothed warcat lashes out with large, velvet-padded claws extended at you.  You partially block with a crimson-scale targe with fitted seams.  ]
[combat-trainer: message: [You're nimbly balanced and in good position.]]
[combat-trainer: message: * Trying inexpertly, a red bear orc reiver slices a rusty steel battle-axe at you.  You barely block with a crimson-scale targe with fitted seams.  ]
[combat-trainer: message: [You're nimbly balanced and opponent has slight advantage.]]
[combat-trainer: message: Divine Hammer Rakkor just arrived.]
[combat-trainer: message: Divine Hammer Rakkor went through the village gate.]
[combat-trainer: message: The orc reiver moves into a position to parry.]
[combat-trainer: message: The sabre-toothed warcat stalks out of the area.]
[combat-trainer: message: A gusty but warm breeze continues to swirl around you.]
[combat-trainer: message: You feel fully prepared to cast your spell.]
[combat-trainer: message: The strong smell of ozone accompanies a bolt discharging through a sabre-toothed warcat.]
[combat-trainer: message: The strong smell of ozone accompanies a bolt discharging through a red bear orc reiver.]
[combat-trainer: message: The strong smell of ozone accompanies a bolt discharging through a red bear orc reiver.]
[combat-trainer: message: The strong smell of ozone accompanies a bolt discharging through a red bear orc reiver.]
[combat-trainer: message: * Attacking inexpertly, a red bear orc reiver slices a rusty steel battle-axe at you.  You barely block with a crimson-scale targe with fitted seams.  ]
[combat-trainer: message: [You're adeptly balanced and have slight advantage.]]
[combat-trainer: message: * Moving inexpertly, a sabre-toothed warcat lashes out with large, velvet-padded claws extended at you.  You evade, just stepping out of harm's way.  ]
[combat-trainer: message: [You're adeptly balanced and in superior position.]]
[combat-trainer: checked against [/You put/i]]
[combat-trainer]>cast

**Comment by Dartellum** [comment]
[combat-trainer]>stow right
You easily strap your stone broadsword to a cloth-of-gold baldric clasped with an onyx scorpion.
>
[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 5]
[combat-trainer: message: You easily strap your stone broadsword to a cloth-of-gold baldric clasped with an onyx scorpion.]
[combat-trainer: message: Manifest Force  (26 roisaen)]
[combat-trainer: message: Swirling Winds  (28 roisaen)]
[combat-trainer: message: Y'ntrel Sechra  (21 roisaen)]
[combat-trainer: message: Ethereal Shield  (Fading)]
[combat-trainer: checked against [/You put/i, /The braided (.+) is too long/, /is too long/i]]

**Comment by Dartellum** [comment]
Any word on fixing this? I can dig into it, if I have time.

**Comment by rpherbig** [comment]
I have not looked into it.

**Comment by Dartellum** [comment]
I think I found it. Common-arcana. Testing now.

Regards,
Dr. Walter Wesley "Wes" Snyder V
484-300-4833 (h)
484-431-3355 (m)

**Comment by Dartellum** [comment]
I just submitted a PR for it.

Regards,
Dr. Walter Wesley "Wes" Snyder V
484-300-4833 (h)
484-431-3355 (m)

On Thu, Sep 7, 2017 at 12:14 PM, Dr. Wes Snyder V <dr.wes.snyder.v@gmail.com
