### ISSUE TITLE
Crossing-training waits to lock Appraisal when Scholarship is trained

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#1161]
https://github.com/rpherbig/dr-scripts/commit/5ed9c1686036dc84ef2ff9e4f1e7fc4910ad35b4#commitcomment-20198752 notes that the `study-art` script will train Appraisal until locked, even if crossing-training was trying to train Scholarship.

**Comment by rpherbig** [comment]
A change should probably be made to `new-character` to conditionally not buy the book

**Comment by rcuhljr** [comment]
I planned on leaving new character as is, they might travel somewhere else and the book is dirt cheap. Fixed the root issue.
