### ISSUE TITLE
Exp tracker from genie

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#117]
Tack earned percent/ranks of experience.

**Comment by rpherbig** [comment]
Is there a genie script to convert or is this something new?

**Comment by rcuhljr** [comment]
It'd be new, it's a plugin over there. It's not anything major you just snapshot exp rank/percent on login and then update exp messages with a little subtext of ranks gained.

**Comment by rcuhljr** [comment]
22494456e0ab1e7ada2c0cf454a6c97e3b61548a
