### ISSUE TITLE
Forge trashing someone else's items on anvil.

### ISSUE THREAD

**Issue by drjunkie** [rpherbig/dr-scripts#1173]
While running forge, I ran around due to no empty rooms, I then got a work order, went into a room where someone already was and trashed his stuff off of the anvil. This starts about line 700. I included me running frantically from room to room above that.

http://pastebin.com/RMk46mY3

**Comment by rpherbig** [comment]
Strange... the code checks that no PCs are in the room. We'll have to look into why it didn't pick up on Cainec who was clearly in the room...

```
--- Lich: go2 active.
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>go eastern arch
[Forging Society, Smithy]
This eastern chamber of the smithy is equipped like the others, with a forge and anvil for heating and tempering the castings from the foundry.  From time to time, the din of hammers pounding on the heated blanks rings out from the anvils in the other rooms.  You also see a grindstone, an arch, a pile of fuel and a large waste bucket.
Also here: Warlord Cainec.
Obvious exits: none.
Room Number: 8909
>
[go2: travel time: 0:00:00]
--- Lich: go2 has exited.
[smith]>look on anvil
On the iron anvil you see an unfinished bronze flat pestle.
>
[smith]>clean anvil
You drag the waste bucket close and prepare to clean off the anvil.
 
[Do you really want to clean off the anvil?  Clean it one more time to destroy the contents.]
>
[smith]>clean anvil
You stop working and clean off the anvil's surface, discarding an unfinished bronze flat pestle into the waste bucket.
Roundtime: 2 sec.
```

**Comment by drjunkie** [comment]
I would assume it checks Also here:

I don't know if his title would cause it to think that he's an NPC?

**Comment by rpherbig** [comment]
On another note, `find_anvil` and `find_grindstone` should probably not tap the item in their current room (since tap is different logic than what is actually used in, e.g. `clean_anvil?`). Instead they should rotate the array of expected rooms similar to how `find` does it:
```
    start_index = @rooms.index(Room.current.id) || 0
    search(@rooms.rotate(start_index)) unless found?

**Comment by rcuhljr** [comment]
Tap provides support for custom forging items created via wands and unlisted forging rooms.

**Comment by rpherbig** [comment]
@drjunkie  Did you download drinfomon from ;repos instead of using the one that comes with dependency?

**Comment by drjunkie** [comment]
I hadn't started a log on that character, but I did have drinfomon started twice, and killed one of them.

**Comment by rcuhljr** [comment]
Are you on the lich fork? if so go find a room with one other person in it and see what happens when you `;en echo DRRoom.pcs`

**Comment by rpherbig** [comment]
@drjunkie Have you had a chance to try this?
