### ISSUE TITLE
go2 geting stuck in rossmans

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#1174]
Go2 can't get through this room in training manager.  What other info can I provide to help fix this?

[go2: error: failed to find a path between your current room (19191) and destination room (8694)]

I think #1111 is referencing the same issue.

**Comment by mwest152** [comment]
This is a really old issue, I'm pretty sure it still exists but seems to only effect genie users.

**Comment by Sarvatt** [comment]
this should be fixed now, it was updated to use moves instead of multiple fputs which tripped up genie
