### ISSUE TITLE
Issue with Engineering!

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#1175]
http://pastebin.com/STs5KbFp

Not sure what the issue is.  I don't have any experience with Engineering without the script, so i'm not sure where the error is occuring.

[shape]>scrape my lumber with my drawknife
You cannot figure out how to do that.  Perhaps finding suitable ingredients and studying some instructions would help.

**Comment by b-Y-d** [comment]
You need to buy a new instruction book, you've outgrown your current one. The script is breaking because you're trying to do a recipe that's not in the apprentice shaping book. 

You need **a book of journeyman shaping instructions**.

**Comment by wscherer420** [comment]
Thanks!
