### ISSUE TITLE
;bescort getting stuck at Leucs

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1179]
Also here: Bloodwraith Inkin, Pious Pidulz who is emanating a bright holy aura and Shentai.
Obvious paths: northeast, southwest.
Room Number: 1176

**Comment by rpherbig** [comment]
Do you have a log of getting stuck?

I checked Inkin's log by cross-referencing room 1176 with Pidulz being in the room, and only ever saw him moving through the room - he never appeared to be stuck.

**Comment by Aurayn** [comment]
[Shentai(17).txt](https://github.com/rpherbig/dr-scripts/files/666203/Shentai.17.txt)

**Comment by rpherbig** [comment]
Somehow you have a version of bescort that had a typo in it, which was only live for 13 minutes before a fix was pushed :)

Restarting dependency should fix this.

**Comment by Aurayn** [comment]
Hmmmm.. restarted the PC and dependency. When launching ;training from 1033 ;bescort stil ltakes me to room 1176 and goes no further but does start my combatscript there.

[Shentai(18).txt](https://github.com/rpherbig/dr-scripts/files/666381/Shentai.18.txt)

**Comment by rpherbig** [comment]
Do you have a `base-hunting.yaml` in your `scripts/profiles/` directory?

**Comment by Aurayn** [comment]
I do.... though I thought I had deleted that for a fix from a previous issue when it went to scripts folder.... deleting it again
