### ISSUE TITLE
Combat Appraise looks to Fams first

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1184]
[combat-trainer]>app leopard quick
A sleek leopard is YOUR familiar, Aurayn!
The sleek leopard appears to be in good condition.

**Comment by rpherbig** [comment]
Do you have this setting?
```
ignored_npcs:
- leopard
```

**Comment by Aurayn** [comment]
I do not...can I set that for all my fams?

**Comment by rpherbig** [comment]
Yes. It will ignore those nouns for the purposes of checking empty rooms, training abilities, etc.

**Comment by Aurayn** [comment]
:)  <-- that's for you
