### ISSUE TITLE
Someone broke maps on the NTR and it's taking everyone into resussies

### ISSUE THREAD

**Issue by caseysinger** [rpherbig/dr-scripts#1190]
I believe someone mis-mapped a room in the COPSE and GO2 is trying to route through there.  

As a temporary fix, I changed the timeto to over 9000 so that go2 would choose the NTR route instead.

;e Map.list[1201].timeto={"1200"=>0.2, "1202"=>0.2, "6132"=>9000.2}

**Comment by rcuhljr** [comment]
Fixed for now, someone needs to map the resus hunting area properly.
