### ISSUE TITLE
jail-buddy wish

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#1192]
If this is an easy thing to do....would it be possible to rub one's gweth after emptying their sack when arrested?

Thanks!

~Gab

**Comment by drboldwin** [comment]
I've asked about this before - I think the trouble is you get arrested so much people will start breaking their gweths from activating them too many times.

**Comment by drgabellia** [comment]
Could it be set up to give the option, then?  gwethrub: true  ?
