### ISSUE TITLE
Base-Hunting.yaml update to add new hunting ground

### ISSUE THREAD

**Issue by Vaprak** [rpherbig/dr-scripts#1193]
Looking to add orc raiders in rossmans, there are 2 different difficulties of them. I submitted a pull request but here are the rooms in case i did it wrong

+  # https://elanthipedia.play.net/Orc_raider 365-450
 +  orc_raiders:
 +  - 8704
 +  - 8705
 +  - 8706
 +  - 8707
 +  - 8708
 +  - 8709
 +  orc_raiders2:
 +  - 8710
 +  - 8711
 +  - 8712
 +  - 8713
 +  - 8714
 +  - 8715
 +  - 8716
 +  - 8717
 +  - 8718

**Comment by rpherbig** [comment]
Merged in 19107ef7702347e63cc09482efa2a34557487fc6
