### ISSUE TITLE
Fix oxford commas issues

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#12]

**Comment by rpherbig** [comment]
@rcuhljr Can you elaborate on what issues you were seeing?

**Comment by rcuhljr** [comment]
I think I've fixed it? the list_to_thing methods where returning empty items "" since it would double split on `and,`. I haven't run into it in awhile.

**Comment by rcuhljr** [comment]
Closing until someone can reproduce an actual problem.
