### ISSUE TITLE
If your storage container is closed when crossing-training starts, it will send it into a loop.

### ISSUE THREAD

**Issue by hwoo79** [rpherbig/dr-scripts#120]
Script isn't confirming storage of items, then attemps to forage and braid vines with gloves still in hand.

**Comment by rpherbig** [comment]
Can you provide some in-game text?

**Comment by hwoo79** [comment]
this occurs ad infinum after the exp all/info checks, if you have something in your hands and your STOW container is closed.

>
[crossing-training]>stow right
But that's closed.
>
[crossing-training]>stow right
But that's closed.
>
[crossing-training]>stow right
But that's closed.
>

**Comment by rpherbig** [comment]
Would it be fair to assume this is the same container as in #129? @hwoo79 @rcuhljr

**Comment by rcuhljr** [comment]
we can get a list of all containers in equipmanager easily enough. We could just have an open all, close all (that ignores gem pouches)

**Comment by hwoo79** [comment]
that seems kind of "hacky" I think this lends more toward having a character variable list that the other scripts can call.  I know I keep my tools in my main pack but would like my ingot waste to go into a bag.  others may want belt support further down the road.

**Comment by rpherbig** [comment]
This might be affected by #174. We should retest after that is merged.

**Comment by rcuhljr** [comment]
d90fa12 If we can think of a more useful implementation that's not burdensome to enter for the user we can add it is a new lower priority issue. @rpherbig do we want an issue to check what containers are closed before trying to open to prevent spam of commands?

**Comment by rpherbig** [comment]
What do you think about using 'inv container'?
