### ISSUE TITLE
SUMMONING Elemental weapons stopped working

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1200]
[combat-trainer: Unable to summon weapons as a unknown]
[combat-trainer]>turn my 
Turn what?

[Mistrya(29).txt](https://github.com/rpherbig/dr-scripts/files/671859/Mistrya.29.txt)

[Mistrya-setup.txt](https://github.com/rpherbig/dr-scripts/files/671860/Mistrya-setup.txt)

**Comment by jayRyan24** [comment]
This is trying to dertermine if you are a moon mage, warrior mage, or not. 

 ```
 def summon_weapon(moon = nil, element = nil, ingot = nil, skill = nil)
    if DRStats.moon_mage?
      unless moon
        echo "Couldn't find any moons to cast moonblade with"
        return
      end
      fput('get moon')
    elsif DRStats.warrior_mage?
      get_ingot(ingot, true)
      case DRC.bput("summon weapon #{element} #{skill}", 'You lack the elemental charge', 'you draw out')
      when 'You lack the elemental charge'
        summon_admittance
        summon_weapon(moon, element, nil, skill)
      end
      stow_ingot(ingot)
    else
      echo "Unable to summon weapons as a #{DRStats.guild}"
    end
    pause 1
    waitrt?
    DRC.fix_standing
  end
```

This last line "else" is saying that your class is "unknown". You need to restart this setup and let it get your data again. Some reason it's not working. Also, you were holding a stone scimitar in your hand when the script started up. It then stowed it. I would always break those weapons before manually starting them up, or you'll summon two weapons and have an extra, and if by chance your sheath doesn't support the length/weight of the weapon, you'll end up with a bunch of issues.

**Comment by Aurayn** [comment]
How do I 'restart the setup'?
