### ISSUE TITLE
Add lockpicks to PICK script

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#1204]
So the PICK script works if the lockpicks found in crossings are found at the locksmiths with other provinces.  Can you add the Shard lockpicks to the list of recognized lockpicks?  If someone decides to move to new town, they'll need to establish a new lockpick ring, as they won't be able to add these to their crossings lockpicks.  But that's not a big deal, gotta do things manually once and awhile!

 stout iron lockpick - 270 dokora
 bronze lockpick - 451 d
 slim ivory lockpick - 1443 d
 slim copper lockpick - 2706 d
 quality copper lockpick - 10824 d
 slim diamondique lockpick - 27060 d

**Comment by wscherer420** [comment]
added costs of each

**Comment by jandersson** [comment]
Need to map the lockpick shop (and the procedure to get in)

**Comment by wscherer420** [comment]
Its actually already done for shard.  When your hometown is set to Shard, and you run pick, it runs you all the way into the locksmiths room, through the bard guild (executing the puzzle to get through).

**Comment by wscherer420** [comment]
was about to post a log of it for you, but its night and the shop is closed.  Might need some logic to handle night time i guess.

**Comment by jandersson** [comment]
Excellent! Either i did that and forgot or someone got to it :D

**Comment by wscherer420** [comment]
FYI it looks like the locksmith location in shard was removed from the base-town file.  Room 9817

**Comment by wscherer420** [comment]
In case you need need to see the messaging through the transaction.

P>buy stout iron lockpick

Kilam says, "I'll give that to you for 270 dokoras."
P>offer 270

Kilam hands over your purchase.
P>put lockpick on my lockpick ring
You put a stout iron lockpick on your lockpick ring.

**Comment by rpherbig** [comment]
@wscherer420 I think I got those two fixed, please retest and let me know if you still have any problems.

**Comment by wscherer420** [comment]
Everything worked great except the ending..Not sure if it matters though as go2 can navigate out of that room no problem.  You are also laying down when you get into the room as the two gor'togs throw you there.  

[pick]>put my lockpick on my lockpick ring
You put a stout iron lockpick on your lockpick ring.
P>
[pick]>out
You can't go there.
P>
[pick: move: failed]
--- Lich: pick has exited.

P>;go2 bank
--- Lich: go2 active.
[go2: ETA: 0:00:01 (9 rooms to move through)]
[go2]>stand
You stand back up.
>
[go2]>go  trapdoor
