### ISSUE TITLE
Bleeding as a Necromancer

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#1205]
Saw another post about adding bleeding severity. This would be especially helpful for Necromancers as we don't get healed by autopaths, we actually need to hunt to heal.

Option 1: Bleeding severity could help because we would continue hunting and hopefully heal.

Option 2: I've never had an issue getting healed by Dokt, even while SO'd. Maybe others have, but not me.  One risk would be going to the bank to withdraw funds prior.  Perhaps removing the withdraw funds part of safe-room for Necros and permit us to see Dokt and just have a debt increase.

Option 3: When bleeding triggers the need to heal, perhaps shoot a Necromancer to a designated hunting zone (of a weaker critter that maybe we designate), where we could kill and heal ourselves easier.

**Comment by izawwlgood** [comment]
There is already support for DEVO/CF

stop_hunting_if_bleeding: false
necromancer_healing:
  Devour:
    abbrev: devo
    mana: 20
    cambrinth:
    - 10

thanatology:
  ritual_type: harvest
  heal: true

**Comment by wscherer420** [comment]
ah ok, didn't know about that.  That will ought to work.
