### ISSUE TITLE
Stealing script bin turn in going too fast, leaving items in bag

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#1208]
```
[steal]>get butter cheese from my backpack

[steal]>put butter cheese in bin

You get a wax-covered butter cheese from inside your black backpack.
> 
A bored-looking Human boy nods toward you as your butter cheese falls into the azurite bin.
A bored-looking Human boy says, "Nice work, Giulietta."
> 
[steal]>get butter cheese from my backpack

[steal]>put butter cheese in bin

You get a wax-covered butter cheese from inside your black backpack.
> 
A bored-looking Human boy nods toward you as your butter cheese falls into the azurite bin.
A bored-looking Human boy says, "Nice work, Giulietta."
> 
[steal]>get butter cheese from my backpack

[steal]>put butter cheese in bin

You get a wax-covered butter cheese from inside your black backpack.
> 
A bored-looking Human boy nods toward you as your butter cheese falls into the azurite bin.
A bored-looking Human boy says, "Nice work, Giulietta."
> 
[steal]>get basin from my backpack

[steal]>put basin in bin

[steal]>get basin from my backpack

[steal]>put basin in bin

Sorry, you may only type ahead 1 command.
Sorry, you may only type ahead 1 command.
> 
[steal]>get basin from my backpack

[steal]>put basin in bin

Sorry, you may only type ahead 1 command.
> 
Sorry, you may only type ahead 1 command.
> 
[steal]>get doublet from my backpack

[steal]>put doublet in bin

You get a basin from inside your black backpack.
> 
A bored-looking Human boy nods toward you as your basin falls into the azurite bin.
A bored-looking Human boy says, "Nice work, Giulietta."
> 
You get a doublet from inside your black backpack.
> 
A bored-looking Human boy nods toward you as your doublet falls into the azurite bin.
A bored-looking Human boy says, "Nice work, Giulietta
```

**Comment by mwest152** [comment]
Could be a genie thing, but still happening pretty much every bin:

[steal]>get kit refill from my backpack

[steal]>put kit refill in bin

> 
[steal]>get kit refill from my backpack

[steal]>put kit refill in bin

Sorry, you may only type ahead 1 command.
Sorry, you may only type ahead 1 command.
> 
You get a repair kit refill from inside your black backpack.
> 
A bored-looking Human boy nods toward you as your kit refill falls into the azurite bin.
A bored-looking Human boy says, "Nice work, Giulietta."
> 
[steal]>get kit refill from my backpack

[steal]>put kit refill in bin

You get a repair kit refill from inside your black backpack.
> 
A bored-looking Human boy nods toward you as your kit refill falls into the azurite bin.
A bored-looking Human boy says, "Nice work, Giulietta."
> 
[steal]>get kit refill from my backpack

[steal]>put kit refill in bin

You get a repair kit refill from inside your black backpack.
> 
A bored-looking Human boy nods toward you as your kit refill falls into the azurite bin.
A bored-looking Human boy says, "Nice work, Giulietta."
> 
[steal]>get butter cheese from my backpack

[steal]>put butter cheese in bin

[steal]>get butter cheese from my backpack

[steal]>put butter cheese in bin

Sorry, you may only type ahead 1 command.
> 
Sorry, you may only type ahead 1 command.
> 
You get a wax-covered butter cheese from inside your black backpack.
> 
A bored-looking Human boy nods toward you as your butter cheese falls into the azurite bin.
A bored-looking Human boy says, "Nice work, Giulietta."
>

**Comment by rcuhljr** [comment]
Don't bump the delay just make a slow bin option or something that uses bput.

**Comment by rpherbig** [comment]
In testing now
