### ISSUE TITLE
Hib repair not working for Metal

### ISSUE THREAD

**Issue by jayRyan24** [rpherbig/dr-scripts#1209]
Hib repair not working for metal gear. 

Pull Request = #1210

**Comment by jayRyan24** [comment]
The problem is the repair_info array is not being filled with both sets of hash data when it's being filled.

**Comment by jayRyan24** [comment]
I fixed this locally by doing the following. It is a fix, but doesn't actually "fix" the issue. I am not necessarily sure what the cause is, I just know the symptom and a way to fix it. I went ahead and uploaded my changes to get it working, I know Luestyin also moved here, but I'd really like to figure out why the code in the above comment works for Crossing and not Hib. 

```
  def setup
    @equipment_manager = EquipmentManager.new
    @equipment_manager.wear_equipment_set?('standard')

    settings = get_settings
    @repair_withdrawal_amount = settings.repair_withdrawal_amount
    hometown = get_data('town')[settings.hometown]

    ensure_copper_on_hand(@repair_withdrawal_amount, settings.hometown)

    @repair_info_leather = {
      hometown['leather_repair'] => @equipment_manager.items.select(&:leather)
    }

    @repair_info_metal = {
      hometown['metal_repair'] => @equipment_manager.items.reject(&:leather)
    }
  end
```
```

  def initialize
    setup

    @repair_info_metal.each do |repairer, items|
      echo "Repairing at #{repairer}" if UserVars.crossing_repair_debug
      repair_at(repairer['name'], repairer['id'], items)
    end

    @repair_info_leather.each do |repairer, items|
      echo "Repairing at #{repairer}" if UserVars.crossing_repair_debug
      repair_at(repairer['name'], repairer['id'], items)
    end

    @repair_info_leather.to_a.reverse.each do |repairer, _items|
      while tickets_left?(repairer)
      end
    end

    @repair_info_metal.to_a.reverse.each do |repairer, _items|
      while tickets_left?(repairer)
      end
    end
  end
```

**Comment by rpherbig** [comment]
It looks like the root cause of this is that the metal repairer and leather repairer are the same person in Hib. The hash assignment syntax we're using only 'keeps' the last assignment in that case.

**Comment by rpherbig** [comment]
You can merge two hashes with something like this: `h = {'a' => ['b']}.merge({'a' => ['c']}){|k, old, new| old + new}`

**Comment by jayRyan24** [comment]
So, I did some type of check because this is what I thought the issue was. I changed the roomnumber and the name of the repairer and it didn't fix the problem. I think in hindsight I was changing the dr-scripts one and not the scripts one...
