### ISSUE TITLE
Learned.lic

### ISSUE THREAD

**Issue by drboldwin** [rpherbig/dr-scripts#1214]
Could we add a bit to this that tracks each individual's skill time that is being learned?  So we can see what skills are clearing more often and adjust accordingly?

EXAMPLE

Targeted Magic   2.36 (22.9 Hours)
Tactics       0.81 (12.32 Hours)

**Comment by skyleronken** [comment]
so you want to track total hours that a skill has been absorbing experience in the area, or do you want to know how many hours per rank?

**Comment by rpherbig** [comment]
@drboldwin Does PR #1477 (now merged) address this?
