### ISSUE TITLE
Moonblade in Combat-trainer.lic

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#1218]
With TKS in offensive spells, moonblade casts automatically, not exactly sure the details on how it works.  It goes for a 1 second pause snap cast, which with 500 utility i still fail most of the time.  I don't usually risk messing with the code but I changed the pause to 2 seconds and it fixed it.  Not sure if that's something someone wants to make permanent.  Or if there is a better solution.

    fput('pre moonblade')
    pause 2
    fput("cast #{UserVars.moons['visible'].first}")
    fput('break moonblade')

**Comment by rpherbig** [comment]
I think we should pause according to the `prep_time` attribute of the Moonblade spell in their settings

**Comment by mwest152** [comment]
This prep of moonblade is actually done because TKS is in my offensive spells.  I actually don't have moonblade anywhere in my YAML.

**Comment by wscherer420** [comment]
What about if you are using TKS as a scroll spell.  Is there a way to shut down the prep moonblade?  Cause i don't have that spell as another guild.

**Comment by jandersson** [comment]
One solution is to set `tk_ammo` to something and the script will skip checking for moonblade slivers.
