### ISSUE TITLE
Add research support for crossing-training

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#122]
It'd be nice if the empath could lock attunement while healbotting.

**Comment by rcuhljr** [comment]
sub section finishing:
However, there is still more to learn before you arrive at a breakthrough
Done: 
Breakthrough

**Comment by rpherbig** [comment]
When would you want research to be worked? As part of the normal training rotation? Only while in idle mode? Or something else?

**Comment by rpherbig** [comment]
I see research.lic and researcher.lic in the lich repo. These look like good starting points.

**Comment by rcuhljr** [comment]
Yeah, we should make it an external script to crossing training so others can use it.

**Comment by rpherbig** [comment]
@rcuhljr Ok to close this, or did you want to do some more with research?
