### ISSUE TITLE
Go2 undergondola hang ups

### ISSUE THREAD

**Issue by izawwlgood** [rpherbig/dr-scripts#1225]
You approach the branch, but the steepness is intimidating.
Roundtime: 2 sec.

Did not attempt again (had to input manually). Room 19459 if thats relevant

**Comment by izawwlgood** [comment]
And ths - 

Room Number: 19472
>
[go2]>climb ledge
You make your way up the ledge.  Partway up, you make the mistake of looking down.  Struck by vertigo, you cling to the ledge for a few moments, then slowly climb back down.
Roundtime: 2 sec.
>
>climb led
You approach the ledge, but the steepness is intimidating.
Roundtime: 2 sec.

**Comment by rpherbig** [comment]
Moved to rcuhljr/dr-lich#9

**Comment by izawwlgood** [comment]
Room Number: 19459
>
[go2]>climb niche
Trying to judge the climb, you peer over the edge.  A wave of dizziness hits you, and you back away from the niche.
Roundtime: 4 sec.

Hung up, restarted after 30s

**Comment by rpherbig** [comment]
I fixed a whole bunch of move failures. Make sure you're on `4.7.23f` and let me know if you still have any problems.
