### ISSUE TITLE
Buff BEFORE hunting?

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#1229]
How hard would it be to set it up so that one buffs BEFORE entering the hunting area?

~Gab

**Comment by rpherbig** [comment]
Search Torgro YAML for 'prehunt'. There are two parts, a room and a set of
buffs.

Is that what you are looking for?

**Comment by drgabellia** [comment]
That is exactly what I needed.  Thank you!

**Comment by drgabellia** [comment]
Okay...prebuff works fine.....however.  What about multiple hunting areas?  As an example, I hunt Sky giants, but I also backtrain in leucros - and use different prebuff spells.  Would it be difficult to set up individual prebuff rooms and spell sets for each hunting area?

**Comment by jayRyan24** [comment]
It's not that it's difficult, it's that it's completely different. This was an initial setup, the goal is to have different buffs for different hunts.

**Comment by rpherbig** [comment]
@drgabellia @jayRyan24 Take a look at what @adamgoerdt just added. He has some examples here: http://pastebin.com/UfHhhWcv
