### ISSUE TITLE
Adding spells to OM Orb causing scroll

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#1241]
I can successfully add spells to my OM orb via cast: touch orb.

However, it causes a bit of scroll.  I think the string "You successfully weave the Shield of Light spell into the receptive aura of the orb, and feel the energies seeping down into the magic of its core!" needs to be added to the script so that it recognizes a successful cast.  Log below.
Thanks!
~Gab

--- Lich: 'escort' tried to stop 'scholarship', but it isn't running!
--- Lich: escort has exited.
[go2: travel time: 0:03:47]
--- Lich: go2 has exited.
--- Lich: buff active.
[buff]>prepare benediction 35
That won't affect your current attunement very much.
You begin chanting a prayer to invoke the Benediction spell.
>
[buff]>charge my armband 25
>
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
[buff]>charge my armband 25
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
Your body is still soaked.
>
[buff]>invoke my armband spell
The armband pulses with Holy energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.  By directing your focus, you ensure that mana is drawn only when spells are cast.
Roundtime: 1 sec.
>
You feel fully attuned to the mana streams again.
>
[buff]>touch orb
You feel fully prepared to cast your spell.
>
You reach up with open palms and cradle the floating rainbow orb, allowing its light to ripple over your entire body.  You sense a tugging sensation from the center of the orb, pulling at your consciousness.
Roundtime: 3 sec.
You sense the rainbow orb attempting to absorb the spell in your mind.  You successfully weave the Benediction spell into the receptive aura of the orb, and feel the energies seeping down into the magic of its core!

Your armband emits a loud *snap* as it discharges all its power to aid your spell.
You suddenly feel more limber, your reflexes charged with a great energy.
Suddenly your muscles flood with energy, singing with a strong vigor.
A surge of great energy tingles through every nerve in your body, leaving you feeling more dexterous.
>
You feel fully rested.
>
You feel fully attuned to the mana streams again.
>
[buff: *** No match was found after 15 seconds, dumping info]
[buff: messages seen length: 21]
[buff: message: You feel fully prepared to cast your spell.]
[buff: message: You reach up with open palms and cradle the floating rainbow orb, allowing its light to ripple over your entire body.  You sense a tugging sensation from the center of the orb, pulling at your consciousness.]
[buff: message: Roundtime: 3 sec.]
[buff: message: You sense the rainbow orb attempting to absorb the spell in your mind.  You successfully weave the Benediction spell into the receptive aura of the orb, and feel the energies seeping down into the magic of its core!]
[buff: message: Your armband emits a loud *snap* as it discharges all its power to aid your spell.]
[buff: message: You suddenly feel more limber, your reflexes charged with a great energy.]
[buff: message: Suddenly your muscles flood with energy, singing with a strong vigor.]
[buff: message: A surge of great energy tingles through every nerve in your body, leaving you feeling more dexterous.]
[buff: message: Osrel Meraud  (94%)]
[buff: message: Glythtide's Gift  (OM)]
[buff: message: Murrula's Flames  (OM)]
[buff: message: Persistence of Mana  (OM)]
[buff: message: Benediction  (OM)]
[buff: message: You feel fully rested.]
[buff: message: Osrel Meraud  (94%)]
[buff: message: Glythtide's Gift  (OM)]
[buff: message: Murrula's Flames  (OM)]
[buff: message: Persistence of Mana  (OM)]
[buff: message: Benediction  (OM)]
[buff: message: [DRPrime]-DR:Pidulz: "Love me some Xaji"]
[buff: message: You feel fully attuned to the mana streams again.]
[buff: checked against [/^You gesture/i, /A soft silver glow envelops/i, /You reach with both/i, /You listen intently to the air/i, /You close your eyes/i, /You close yours eyes/i, /Your target pattern dissipates/i, /You make a holy gesture/i, /You raise your left hand skyward/i, /Flickering shadows tear away/i, /You sense a Malediction/i, /You release an accompaniment/i, /You roll your hands in an elliptical pattern/i, /You cup your hand/i, /You raise your right hand skyward/i, /You flicker your malevolent desires towards/i, /You clench your hands into fists and grit your teeth/i, /You make a sweeping gesture with your arm/i, /You wave your hand/i, /Tendrils of flame dart along your hand/i, /Invisible strands of air twist/i, /The flames dancing along your fingertips/i, /^You can't cast that at yourself/i, /^You need to specify a body part to consume/i, /You breathe deeply, centering your energies/i, /You strike your heel against the ground/i, /You clasp your hands together/i, /With a wave of your hand/i, /Your words fill you with an unflagging sense of resolve and purpose/i, /A renewed sense of purpose fills you/i, /You make a ruthless lashing gesture/i, /You clench your fist and mutter a whispered/i, /You call forth the dark will of the divine/i, /^Your heart skips a beat/i, /You whisper the final word of your spell/i, /You reach one hand toward the earth/i, /^You rebuke a/i, /You clap (you|your) hands/i, /You are pulled through your unstable Moongate/i, /You thrust your/i, /Your mind races/i, /You draw forth a pulse of/i, /You reach with your fist toward the ground/i, /You raise your hand/i, /A crackling mantle of blazing orange-yellow flames/i]]
Hargeff climbs onto a rope and begins to make his way across.
>
[buff]>prepare MAPP 35
That won't affect your current attunement very much.
You begin chanting a prayer to invoke the Major Physical Protection spell.
>
[buff]>charge my armband 25
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
[buff]>charge my armband 25
>
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
[buff]>invoke my armband spell
The armband pulses with Holy energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.  By directing your focus, you ensure that mana is drawn only when spells are cast.
Roundtime: 1 sec.
>
You feel fully attuned to the mana streams again.
>
[buff]>cast
>
You feel fully prepared to cast your spell.
>
You gesture.
Your armband emits a loud *snap* as it discharges all its power to aid your spell.
A bright silver nimbus roars up around you as streaks of steel-blue light descend in a convex field.
A sense of calm focus takes hold as the luminous pattern washes over you.  You feel much more able to avoid attacks with your energized joints.
>
[buff]>prepare Centering 35
That won't affect your current attunement very much.
You begin chanting a prayer to invoke the Centering spell.
>
[buff]>charge my armband 25
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
[buff]>charge my armband 25
You feel fully rested.
>
The ropes sway in the wind, making Hargeff wrap his arm more tightly around it as he continues to try to cross.
>
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
Hargeff shuffles along a rope leading north.
>
[buff]>invoke my armband spell
The armband pulses with Holy energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.  By directing your focus, you ensure that mana is drawn only when spells are cast.
Roundtime: 1 sec.
>
The rainbow orb of light hovering near you pulses, as if alive.
>
[buff]>cast
You feel fully prepared to cast your spell.
>
You gesture.
Your armband emits a loud *snap* as it discharges all its power to aid your spell.
The ceaseless ebb and flow of your spirit palpably quiets, granting you an enhanced grounding in your body.
>
[buff]>prepare sol 35
That won't affect your current attunement very much.
You begin chanting a prayer to invoke the Shield of Light spell.
>
[buff]>charge my armband 25
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
[buff]>charge my armband 25
>
You feel fully rested.
>
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
[buff]>invoke my armband spell
The armband pulses with Holy energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.  By directing your focus, you ensure that mana is drawn only when spells are cast.
Roundtime: 1 sec.
>
Hargeff shuffles along a rope leading north.
>
You feel fully prepared to cast your spell.
>
[buff]>touch orb
You reach up with open palms and cradle the floating rainbow orb, allowing its light to ripple over your entire body.  You sense a tugging sensation from the center of the orb, pulling at your consciousness.
Roundtime: 3 sec.
You sense the rainbow orb attempting to absorb the spell in your mind.  You successfully weave the Shield of Light spell into the receptive aura of the orb, and feel the energies seeping down into the magic of its core!

Your armband emits a loud *snap* as it discharges all its power to aid your spell.
A fiery blaze covers your shield arm like a vambrace of solid sunlight.
>
You feel fully rested.
>
[buff: *** No match was found after 15 seconds, dumping info]
[buff: messages seen length: 22]
[buff: message: You reach up with open palms and cradle the floating rainbow orb, allowing its light to ripple over your entire body.  You sense a tugging sensation from the center of the orb, pulling at your consciousness.]
[buff: message: Roundtime: 3 sec.]
[buff: message: You sense the rainbow orb attempting to absorb the spell in your mind.  You successfully weave the Shield of Light spell into the receptive aura of the orb, and feel the energies seeping down into the magic of its core!]
[buff: message: Your armband emits a loud *snap* as it discharges all its power to aid your spell.]
[buff: message: A fiery blaze covers your shield arm like a vambrace of solid sunlight.]
[buff: message: Osrel Meraud  (92%)]
[buff: message: Glythtide's Gift  (OM)]
[buff: message: Murrula's Flames  (OM)]
[buff: message: Major Physical Protection  (35 roisaen)]
[buff: message: Centering  (36 roisaen)]
[buff: message: Persistence of Mana  (OM)]
[buff: message: Benediction  (OM)]
[buff: message: Shield of Light  (OM)]
[buff: message: You feel fully rested.]
[buff: message: Osrel Meraud  (92%)]
[buff: message: Glythtide's Gift  (OM)]
[buff: message: Murrula's Flames  (OM)]
[buff: message: Major Physical Protection  (35 roisaen)]
[buff: message: Centering  (36 roisaen)]
[buff: message: Persistence of Mana  (OM)]
[buff: message: Benediction  (OM)]
[buff: message: Shield of Light  (OM)]
[buff: checked against [/^You gesture/i, /A soft silver glow envelops/i, /You reach with both/i, /You listen intently to the air/i, /You close your eyes/i, /You close yours eyes/i, /Your target pattern dissipates/i, /You make a holy gesture/i, /You raise your left hand skyward/i, /Flickering shadows tear away/i, /You sense a Malediction/i, /You release an accompaniment/i, /You roll your hands in an elliptical pattern/i, /You cup your hand/i, /You raise your right hand skyward/i, /You flicker your malevolent desires towards/i, /You clench your hands into fists and grit your teeth/i, /You make a sweeping gesture with your arm/i, /You wave your hand/i, /Tendrils of flame dart along your hand/i, /Invisible strands of air twist/i, /The flames dancing along your fingertips/i, /^You can't cast that at yourself/i, /^You need to specify a body part to consume/i, /You breathe deeply, centering your energies/i, /You strike your heel against the ground/i, /You clasp your hands together/i, /With a wave of your hand/i, /Your words fill you with an unflagging sense of resolve and purpose/i, /A renewed sense of purpose fills you/i, /You make a ruthless lashing gesture/i, /You clench your fist and mutter a whispered/i, /You call forth the dark will of the divine/i, /^Your heart skips a beat/i, /You whisper the final word of your spell/i, /You reach one hand toward the earth/i, /^You rebuke a/i, /You clap (you|your) hands/i, /You are pulled through your unstable Moongate/i, /You thrust your/i, /Your mind races/i, /You draw forth a pulse of/i, /You reach with your fist toward the ground/i, /You raise your hand/i, /A crackling mantle of blazing orange-yellow flames/i]]
[buff]>prepare mpp 35
That won't affect your current attunement very much.
You begin chanting a prayer to invoke the Minor Physical Protection spell.
>
[buff]>charge my armband 25
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
[buff]>charge my armband 25
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
[buff]>invoke my armband spell
The armband pulses with Holy energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.  By directing your focus, you ensure that mana is drawn only when spells are cast.
Roundtime: 1 sec.
>
Hargeff shuffles along a rope leading north, finally arriving on this side.
>
[buff]>touch orb
You reach up with open palms and cradle the floating rainbow orb, allowing its light to ripple over your entire body.  You sense a tugging sensation from the center of the orb, pulling at your consciousness.
Roundtime: 3 sec.
You sense the rainbow orb attempting to absorb the spell in your mind.  You successfully weave the Minor Physical Protection spell into the receptive aura of the orb, and feel the energies seeping down into the magic of its core!

Your armband emits a loud *snap* as it discharges all its power to aid your spell.
You are bathed in a soft silver glow for a moment.
>
You feel fully rested.
>
[buff: *** No match was found after 15 seconds, dumping info]
[buff: messages seen length: 25]
[buff: message: You reach up with open palms and cradle the floating rainbow orb, allowing its light to ripple over your entire body.  You sense a tugging sensation from the center of the orb, pulling at your consciousness.]
[buff: message: Roundtime: 3 sec.]
[buff: message: You sense the rainbow orb attempting to absorb the spell in your mind.  You successfully weave the Minor Physical Protection spell into the receptive aura of the orb, and feel the energies seeping down into the magic of its core!]
[buff: message: Your armband emits a loud *snap* as it discharges all its power to aid your spell.]
[buff: message: You are bathed in a soft silver glow for a moment.]
[buff: message: Osrel Meraud  (92%)]
[buff: message: Glythtide's Gift  (OM)]
[buff: message: Murrula's Flames  (OM)]
[buff: message: Minor Physical Protection  (OM)]
[buff: message: Major Physical Protection  (35 roisaen)]
[buff: message: Centering  (35 roisaen)]
[buff: message: Persistence of Mana  (OM)]
[buff: message: Benediction  (OM)]
[buff: message: Shield of Light  (OM)]
[buff: message: [General][Juulman] "where can i meet ya truix?"]
[buff: message: You feel fully rested.]
[buff: message: Osrel Meraud  (90%)]
[buff: message: Glythtide's Gift  (OM)]
[buff: message: Murrula's Flames  (OM)]
[buff: message: Minor Physical Protection  (OM)]
[buff: message: Major Physical Protection  (35 roisaen)]
[buff: message: Centering  (35 roisaen)]
[buff: message: Persistence of Mana  (OM)]
[buff: message: Benediction  (OM)]
[buff: message: Shield of Light  (OM)]
[buff: checked against [/^You gesture/i, /A soft silver glow envelops/i, /You reach with both/i, /You listen intently to the air/i, /You close your eyes/i, /You close yours eyes/i, /Your target pattern dissipates/i, /You make a holy gesture/i, /You raise your left hand skyward/i, /Flickering shadows tear away/i, /You sense a Malediction/i, /You release an accompaniment/i, /You roll your hands in an elliptical pattern/i, /You cup your hand/i, /You raise your right hand skyward/i, /You flicker your malevolent desires towards/i, /You clench your hands into fists and grit your teeth/i, /You make a sweeping gesture with your arm/i, /You wave your hand/i, /Tendrils of flame dart along your hand/i, /Invisible strands of air twist/i, /The flames dancing along your fingertips/i, /^You can't cast that at yourself/i, /^You need to specify a body part to consume/i, /You breathe deeply, centering your energies/i, /You strike your heel against the ground/i, /You clasp your hands together/i, /With a wave of your hand/i, /Your words fill you with an unflagging sense of resolve and purpose/i, /A renewed sense of purpose fills you/i, /You make a ruthless lashing gesture/i, /You clench your fist and mutter a whispered/i, /You call forth the dark will of the divine/i, /^Your heart skips a beat/i, /You whisper the final word of your spell/i, /You reach one hand toward the earth/i, /^You rebuke a/i, /You clap (you|your) hands/i, /You are pulled through your unstable Moongate/i, /You thrust your/i, /Your mind races/i, /You draw forth a pulse of/i, /You reach with your fist toward the ground/i, /You raise your hand/i, /A crackling mantle of blazing orange-yellow flames/i]]
--- Lich: buff has exited.
>
--- Lich: go2 active.
[go2: ETA: 0:00:02 (3 rooms to move through)]
[go2]>search ravine
You search around, closely examining a deep ravine.  Nodding in satisfaction, you find a series of shallow cracks!
>
[go2]>climb crack
[Mistwood Forest, In a Ravine]
Narrow cracks in the ravine wall offer an escape from the shadows of the canyon, though to judge by the amount of rubble littering the rocky floor, "treacherous" is probably the kindest way to describe the climb.  
Obvious paths: east, south, west.
Room Number: 10064

**Comment by ohbeanz** [comment]
Cast message missing. Can pop this in real quick.
