### ISSUE TITLE
SHARD climbing addition

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1244]
Reequest shard_wall be added perm

skill 140-?

practice_options:
  # https://elanthipedia.play.net/Climbing_and_Swimming_list
  # Shard Undergondola - Deep Pit by Latami  (202 - ?)
  undergondola_pit:
      id:  9609
      target: pit
  # Shard Undergondola - Branch to Undergondola (530 - 1000+)
  undergondola_branch:
      id:  2245
      target: branch
  shard_wall:
      id:  2517
      target: wall

**Comment by jandersson** [comment]
This can be closed
