### ISSUE TITLE
Nomad Xaji

### ISSUE THREAD

**Issue by richardhertzog** [rpherbig/dr-scripts#1246]
In light of the recent issues we've seen at the Oasis, and the previous ones at the Campfire, I would like to propose we use the ;lnet locate feature to find Xaji and keep him nomadic. This would at least deter issues.

**Comment by rpherbig** [comment]
What recent issues have you seen?

**Comment by rpherbig** [comment]
Related, it would be easy enough to split lichbot into two scripts, one that is responsible for items (which could hang out with bankbot, or even be merged into bankbot), and one that is responsible for buffs and composting.

**Comment by Dartellum** [comment]
Given this issue is 3 years old, is it still valid?

**Comment by MahtraDR** [comment]
@rpherbig Can we close this? Years without updates...
