### ISSUE TITLE
:Combat-trainer not dropping fragments after tending

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1253]
**_Also doesn't swap hands for summoned elemental weapon see below_**

[combat-trainer]>attack
>
< Moving with powerful grace, you kick your steel-toed footwrap at a cave troll.  A cave troll fails to evade, moving almost completely out of harm's reach.  The footwrap lands a good strike (3/23) to the troll's neck.
[You're adeptly balanced and opponent has slight advantage.]
[Roundtime 3 sec.]
>
You feel an agonizing pain from the jagged stone fragment lodged in your left leg.
>
A cave troll gestures at you.
A cave troll stomps the ground heavily with its massive foot as it completes its incantation!
A small stone rock rips itself free of the earth, then splits into two jagged shards and hurtles toward you!
You block the first shard with your small shield.
You manage to get out of the way of the final shard!
>
You feel fully attuned to the mana streams again.
>
[combat-trainer]>tend my left leg
>
The cave troll moves into a position to dodge.
>
* Moving in like a timid schoolboy, a cave troll bashes a war hammer at you.  You dodge, leaning to one side.  
[You're bruised, nimbly balanced with opponent in very strong position.]
>
The cave troll moves into a position to dodge.
>
**You foolishly remove the jagged stone fragment from your leg tearing the flesh and horribly aggravating the wound!
Roundtime: 20 seconds.**
>
You feel fully prepared to cast your spell.
>
The air around you solidifies into a dull yellow haze and throws off bright waves of light as it resists the attack.
* Moving fluidly, a cave troll feints high at you.  You fail to dodge, mainly avoiding the blow.  The hammer lands a light hit (1/23) to your chest.
[You're bruised, nimbly balanced with opponent in very strong position.]
>
A cave troll gestures at you.
A cave troll stomps the ground heavily with its massive foot as it completes its incantation!
A small stone rock rips itself free of the earth, then splits into two jagged shards and hurtles toward you!
You manage to get out of the way of the first shard!
You block the final shard with your small shield.
>
You feel fully rested.
>
The air around you solidifies into a dull yellow haze and throws off shimmering light in the wake of the attack.
* Fluidly, a cave troll sweeps low at you.  You attempt to dodge, only slightly avoiding the blow.  The hammer lands a light hit (1/23) to your right arm.
[You're bruised, nimbly balanced with opponent in good position.]
>
The air around you solidifies into a dull yellow haze, buckling and losing much of its mass under the force of the attack.
* With grace, a cave troll bashes a war hammer at you.  You fail to dodge, stepping partially into the shot.  The hammer lands a good hit (2/23) to your left arm.
[You're bruised, nimbly balanced with opponent in very strong position.]
>
A cave troll gestures at you.
A cave troll stomps the ground heavily with its massive foot as it completes its incantation!
A small stone rock rips itself free of the earth, then splits into two jagged shards and hurtles toward you!
You manage to get out of the way of the first shard!
You block the final shard with your small shield.
>
The air around you solidifies into a dull yellow haze, losing most of its mass under the force of the attack.
* Moving fluidly, a cave troll bashes a war hammer at you.  You attempt to evade, only slightly avoiding the blow.  The hammer lands a light hit (1/23) to your right arm.
[You're hurt, nimbly balanced with opponent in superior position.]
>
A cave troll gestures at you.
A cave troll stomps the ground heavily with its massive foot as it completes its incantation!
A small stone rock rips itself free of the earth, then splits into two jagged shards and hurtles toward you!
You manage to get out of the way of the first shard!
You block the final shard with your small shield.
>
The air around you solidifies into a dull yellow haze, collapsing under the force of the attack in a silent cascade of glassy fragments that vanish before reaching the ground.
* Moving with powerful grace, a cave troll sweeps low at you.  You fail to dodge, avoiding only some of the blow.  The hammer lands a solid hit (4/23) to your right leg.
[You're hurt, nimbly balanced with opponent in very strong position.]
>
* A cave troll swings a war hammer at you.  You evade, barely twisting out of harm's reach.  
[You're hurt, nimbly balanced with opponent in better position.]
>
* Moving in gracefully, a cave troll sidesteps and bashes at you.  You fail to dodge, stepping partially into the shot.  The hammer lands a good hit (2/23) to your chest.
[You're battered, nimbly balanced with opponent in good position.]
>
* With grace, a cave troll sidesteps and bashes at you.  You attempt to dodge, stepping partly into the blow.  The hammer lands a good strike (3/23) to your abdomen.
[You're battered, nimbly balanced with opponent in very strong position.]
>
The cave troll moves into a position to dodge.
>
[combat-trainer]>invoke my armband 
The cambrinth armband pulses with Elemental energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.
Roundtime: 1 sec.
>
[combat-trainer]>cast
You gesture.
Your cambrinth armband emits a loud *snap* as it discharges all its power to aid your spell.
A delicate pleasant breeze begins to stir.
>
**[combat-trainer]>attack
Wouldn't it be better if you used a melee weapon?**
>
You feel fully rested.
You feel fully attuned to the mana streams again.
>
* Moving in gracefully, a cave troll swings a war hammer at you.  You attempt to evade, only partially avoiding the impact.  The hammer lands a light hit (1/23) to your right arm.
[You're battered, nimbly balanced with opponent in good position.]
>
* Moving in gracefully, a cave troll feints high at you.  You attempt to evade, not quite escaping the blast.  The hammer lands a light hit (1/23) to your chest.
[You're battered, nimbly balanced with opponent in excellent position.]
>
A cave troll gestures at you.
A cave troll stomps the ground heavily with its massive foot as it completes its incantation!
A small stone rock rips itself free of the earth, then splits into two jagged shards and hurtles toward you!
You manage to get out of the way of the first shard!
You block the final shard with your small shield.
>
[combat-trainer]>retreat
You retreat back to pole range.
>
[combat-trainer]>retreat
You retreat from combat.
>
[combat-trainer]>pre MAF 5
You trace a geometric sigil in the air, shaping the pattern of the Manifest Force spell.
>
[combat-trainer]>charge my armband 15
>
The cave troll begins to advance on you!
The cave troll is still a distance away from you and is closing steadily.
>
You harness a moderate amount of energy and attempt to channel it into your cambrinth armband.
You are able to channel all the energy into the armband.
The cambrinth armband absorbs all of the energy.
Roundtime: 3 sec.
>
You shiver involuntarily as a cold breeze rushes through a small airy fissure.
>
[combat-trainer]>invoke my armband 
A cave troll gestures at you.
A cave troll stomps the ground heavily with its massive foot as it completes its incantation!
A small stone rock rips itself free of the earth, then splits into two jagged shards and hurtles toward you!
You block the first shard with your small shield.
You manage to get out of the way of the final shard!
>
A cave troll gestures at you.
A cave troll stomps the ground heavily with its massive foot as it completes its incantation!
A small stone rock rips itself free of the earth, then splits into two jagged shards and hurtles toward you!
You block the first shard with your small shield.
You manage to get out of the way of the final shard!
>
[hunting-buddy: ***STATUS*** 37 minutes of hunting remaining or waiting on Large Edged, Heavy Thrown, Light Thrown, Brawling, Small Edged, Polearms]
The cambrinth armband pulses with Elemental energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.
Roundtime: 1 sec.
>
[combat-trainer]>cast
>
The cave troll begins to advance on you!
The cave troll is still a distance away from you and is closing steadily.
>
The cave troll begins to advance on you!
The cave troll is still a distance away from you and is closing steadily.
>
You gesture.
Your cambrinth armband emits a loud *snap* as it discharges all its power to aid your spell.
The air around you shimmers with a dull yellow haze.  The scintillating light writhes and twists, abruptly coalescing into a translucent field before blinking out of sight.
>
**[combat-trainer]>attack
Wouldn't it be better if you used a melee weapon?**
>
The cave troll closes to pole weapon range on you!
>
[combat-trainer]>retreat
You retreat from combat.
>
[combat-trainer]>pre rm 20
You trace a geometric sigil in the air, shaping the pattern of the Rising Mists spell.
>
[combat-trainer]>attack
Wouldn't it be better if you used a melee weapon?
>
You feel fully rested.
You feel fully attuned to the mana streams again.
>
[combat-trainer]>attack
Wouldn't it be better if you used a melee weapon?
>
A delicate pleasant breeze continues to swirl around you.
>
[combat-trainer]>attack
The cave troll closes to pole weapon range on you!
>
Wouldn't it be better if you used a melee weapon?
>
[combat-trainer]>retreat
You retreat from combat.
>
[combat-trainer]>attack
Wouldn't it be better if you used a melee weapon?
>
The cave troll closes to pole weapon range on you!
>
The cave troll closes to pole weapon range on you!
>
[combat-trainer]>retreat
You retreat from combat.
>
[combat-trainer]>attack
Wouldn't it be better if you used a melee weapon?
>
The cave troll closes to pole weapon range on you!
>
[combat-trainer]>retreat
You retreat from combat.
>
[combat-trainer]>attack
Wouldn't it be better if you used a melee weapon?
>
[combat-trainer]>attack
The cave troll closes to pole weapon range on you!
>
The cave troll closes to pole weapon range on you!
>
Wouldn't it be better if you used a melee weapon?
>
[combat-trainer]>retreat
You retreat from combat.
>
[combat-trainer]>attack
Wouldn't it be better if you used a melee weapon?
>
The cave troll closes to pole weapon range on you!
>
A cave troll gestures at you.
A cave troll stomps the ground heavily with its massive foot as it completes its incantation!
A small stone rock rips itself free of the earth, then splits into two jagged shards and hurtles toward you!
You block the first shard with your small shield.
You block the final shard with your small shield.
>
[combat-trainer]>retreat
You retreat from combat.
>
[combat-trainer]>attack
You can not slam with a jagged stone fragment!
>
The cave troll closes to pole weapon range on you!
>
The cave troll closes to pole weapon range on you!
>
[combat-trainer]>perc
You reach out with your senses and see brilliant (17/21) streams of roiling Elemental mana coursing through the area.
Letting your senses extend further, you feel there is shimmering (9/21) mana to the southwest, and pale (7/21) mana to the north.
You sense the Tailwind spell upon you, which will last for about fourteen roisaen.
You sense the Y'ntrel Sechra spell upon you, which will last for about one roisan.
You sense the Manifest Force spell surrounding you, which will last for seventeen roisaen or until it has endured six more blows.
You sense the Swirling Winds spell upon you, which will last for about fourteen roisaen.
You sense the Sure Footing spell upon you, which will last for about twelve roisaen.
You are preparing the Rising Mists spell at twenty mana.
You sense the Zephyr spell in the area, which will last for about three roisaen.
You sense an Ethereal Fissure spell matrix infusing the available mana streams with a large amount of extra elemental energy.
The Ethereal Fissure should last for approximately fifteen roisaen.
Roundtime: 3 sec.
>
The cave troll closes to pole weapon range on you!
>
[combat-trainer]>attack
Wouldn't it be better if you used a melee weapon?
>
The cave troll closes to melee range on you!
>
The cave troll closes to melee range on you!
>
A cave troll gestures at you.
A cave troll stomps the ground heavily with its massive foot as it completes its incantation!
A small stone rock rips itself free of the earth, then splits into two jagged shards and hurtles toward you!
You manage to get out of the way of the first shard!
You block the final shard with your small shield.
>
A cave troll gestures at you.
A cave troll stomps the ground heavily with its massive foot as it completes its incantation!
A small stone rock rips itself free of the earth, then splits into two jagged shards and hurtles toward you!
[combat-trainer]>attack
You block the first shard with your small shield.
You manage to get out of the way of the final shard!
>
Wouldn't it be better if you used a melee weapon?
>
[combat-trainer]>attack
Wouldn't it be better if you used a melee weapon?
>
A delicate pleasant breeze continues to swirl around you.
>
The cave troll closes to melee range on you!
>
The cave troll moves into a position to dodge.
>
The air around you solidifies into a dull yellow haze and intercepts the attack with a shower of coruscating light.
* Moving in gracefully, a cave troll bashes a war hammer at you.  You fail to evade, only slightly avoiding the blow.  The hammer lands a good strike (3/23) to your right arm.
[You're hurt, nimbly balanced with opponent in strong position.]
>
[combat-trainer]>attack
Wouldn't it be better if you used a melee weapon?
>
[combat-trainer]>attack
Wouldn't it be better if you used a melee weapon?
>
[combat-trainer]>attack
Wouldn't it be better if you used a melee weapon?
>
The air around you solidifies into a dull yellow haze and throws off bright waves of light as it resists the attack.
* Moving fluidly, a cave troll bashes a war hammer at you.  You fail to dodge, only slightly avoiding the blow.  The hammer lands a good hit (2/23) to your neck.
[You're battered, nimbly balanced with opponent in superior position.]
>
A cave troll gestures at you.
A cave troll stomps the ground heavily with its massive foot as it completes its incantation!
A small stone rock rips itself free of the earth, then splits into two jagged shards and hurtles toward you!
You manage to get out of the way of the first shard!
You block the final shard with your small shield.
>
[combat-trainer]>attack
Wouldn't it be better if you used a melee weapon?
>
You feel fully prepared to cast your spell.
>
**[combat-trainer]>summon weapon icy Light Thrown**
The air around you solidifies into a dull yellow haze and throws off shimmering light in the wake of the attack.
* Moving in gracefully, a cave troll sidesteps and bashes at you.  You fail to dodge, only slightly avoiding the blow.  The hammer lands a light hit (1/23) to your chest.
[You're battered, nimbly balanced and opponent has slight advantage.]
>
The air around you solidifies into a dull yellow haze, buckling and losing much of its mass under the force of the attack.
* Fluidly, a cave troll swings a war hammer at you.  You fail to dodge, only slightly avoiding the blow.  The hammer lands a light hit (1/23) to your chest.
[You're battered, nimbly balanced with opponent in better position.]
>
**Closing your eyes, you grunt briefly in effort as you sense a small aqueous ethereal fissure open in front of you.  Thrusting your hand through, you draw out an icy bola.  As you open your eyes, the fissure closes.
Roundtime: 1 sec.**
>
**_[combat-trainer]>turn my fragment
>
You attempt to turn a jagged stone fragment, but that doesn't seem to do much._**
>
* A cave troll sweeps low at you.  You dodge, barely stepping to one side.  
[You're battered, nimbly balanced with opponent in strong position.]
>
The crashing boom of thunder rolls through the mouth of a small airy fissure.
>
The air around you solidifies into a dull yellow haze, losing most of its mass under the force of the attack.
* Moving in gracefully, a cave troll swings a war hammer at you.  You attempt to dodge, avoiding only some of the blow.  The hammer lands a light hit (1/23) to your abdomen.
[You're battered, nimbly balanced with opponent in strong position.]
>
The cave troll moves into a position to dodge.
>
A delicate pleasant breeze continues to swirl around you.
>
* A cave troll bashes a war hammer at you.  You dodge, just stepping out of harm's way.  
[You're battered, nimbly balanced with opponent in very strong position.]
>
A cave troll glances at you and grins viciously.
>
A cave troll gestures at you.
A cave troll stomps the ground heavily with its massive foot as it completes its incantation!
A small stone rock rips itself free of the earth, then splits into two jagged shards and hurtles toward you!
You manage to get out of the way of the first shard!
The air around you solidifies into a dull yellow haze, collapsing under the force of the attack in a silent cascade of glassy fragments that vanish before reaching the ground.
The final shard is partially blocked as it glances off your small shield.
The final shard bounces off your neck, leaving you completely unfazed.
>
The cave troll moves into a position to dodge.
>
[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 28]
[combat-trainer: message: You attempt to turn a jagged stone fragment, but that doesn't seem to do much.]
[combat-trainer: message: * A cave troll sweeps low at you.  You dodge, barely stepping to one side.  ]
[combat-trainer: message: [You're battered, nimbly balanced with opponent in strong position.]]
[combat-trainer: message: The crashing boom of thunder rolls through the mouth of a small airy fissure.]
[combat-trainer: message: The air around you solidifies into a dull yellow haze, losing most of its mass under the force of the attack.]
[combat-trainer: message: * Moving in gracefully, a cave troll swings a war hammer at you.  You attempt to dodge, avoiding only some of the blow.  The hammer lands a light hit to your abdomen.]
[combat-trainer: message: [You're battered, nimbly balanced with opponent in strong position.]]
[combat-trainer: message: The cave troll moves into a position to dodge.]
[combat-trainer: message: [DRPrime]-DR:Sylvari: "oh he's got SLS in here nice!"]
[combat-trainer: message: Tailwind  (14 roisaen)]
[combat-trainer: message: Y'ntrel Sechra  (1 roisan)]
[combat-trainer: message: Manifest Force  (16 roisaen)]
[combat-trainer: message: Swirling Winds  (13 roisaen)]
[combat-trainer: message: Sure Footing  (12 roisaen)]
[combat-trainer: message: A delicate pleasant breeze continues to swirl around you.]
[combat-trainer: message: * A cave troll bashes a war hammer at you.  You dodge, just stepping out of harm's way.  ]
[combat-trainer: message: [You're battered, nimbly balanced with opponent in very strong position.]]
[combat-trainer: message: A cave troll glances at you and grins viciously.]
[combat-trainer: message: A cave troll gestures at you.]
[combat-trainer: message: A cave troll stomps the ground heavily with its massive foot as it completes its incantation!]
[combat-trainer: message: A small stone rock rips itself free of the earth, then splits into two jagged shards and hurtles toward you!]
[combat-trainer: message: You manage to get out of the way of the first shard!]
[combat-trainer: message: The air around you solidifies into a dull yellow haze, collapsing under the force of the attack in a silent cascade of glassy fragments that vanish before reaching the ground.]
[combat-trainer: message: The final shard is partially blocked as it glances off your small shield.]
[combat-trainer: message: The final shard bounces off your neck, leaving you completely unfazed.]
[combat-trainer: message: [DRPrime]-DR:Fuss: "crannach is basically wehre i got 99% of my YAML from"]
[combat-trainer: message: The cave troll moves into a position to dodge.]
[combat-trainer: message: [DRPrime]-DR:Sylvari: "didnt think that was suported"]
[combat-trainer: checked against [/You lack the elemental charge/i, /You reach out/i]]
>
**[combat-trainer]>pull my fragment**
>
* Moving in gracefully, a cave troll feints high at you.  You fail to evade, avoiding most of the blow.  The hammer lands a solid hit (4/23) that bruises the right hamstring.
[You're beat up, nimbly balanced with opponent in excellent position.]
>
A cave troll gestures at you.
A cave troll stomps the ground heavily with its massive foot as it completes its incantation!
A small stone rock rips itself free of the earth, then splits into two jagged shards and hurtles toward you!
You block the first shard with your small shield.
You block the final shard with your small shield.
>
**I'm afraid that you can't pull that.**

**Comment by rpherbig** [comment]
cbf5397ca3ff857853d9cdd963e33ccbe4a254ba
