### ISSUE TITLE
crossing-training hometown settings for buying yarn

### ISSUE THREAD

**Issue by cpryor6** [rpherbig/dr-scripts#1256]
Found this issue when buying yarn for knitting , crossing_trainer on line 952 seems to be root cause

**Comment by cpryor6** [comment]
Datapoint:  if in Haven or Shard, money is withdrawn from local bank, then a run to crossing is made, buying yarn fails due to wrong currency, then it runs to safe room and drops my needles!

[sew]>put my book in my backpack
You put your book in your hitman's backpack.
>
[sew]>get my knitting needle
You get some polished glaes knitting needles from inside your hitman's backpack.
>
[sew]>get my wool yarn
What were you referring to?
>
[sew: You seem to be missing: wool yarn]
--- Lich: sew has exited.
[crossing-training]>get my wool yarn
What were you referring to?
>
[crossing-training]>drop my yarn
What were you referring to?
>
[crossing-training]>drop my knitting needles
You drop some polished glaes knitting needles.

**Comment by cpryor6** [comment]
the issue is actually with crossing_trainer on line 952

**Comment by Dartellum** [comment]
I believe I fixed this this. Please let me know if it is working for you now.
