### ISSUE TITLE
Pause research to permit training alternate skills

### ISSUE THREAD

**Issue by skyleronken** [rpherbig/dr-scripts#1260]
I suggest the implementation of a flag that permits us to pause research when the event_loop attempts to train a non-research friendly skill. Once that skill is finished, simply resume the current research.

**Comment by BinuDR** [comment]
Pausing research causes you to lose progress over time.  Is this a feature people would want?  Researching is usually a less than optimal way to train as it is, losing progress on top of that wouldn't be helpful.

**Comment by MahtraDR** [comment]
@rpherbig I'd say we close this. ;research takes just a few minutes to run when you die.
