### ISSUE TITLE
Status-monitor and custom messaging

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#1268]
Would it be possible to add custom messaging if quitting via the status-monitor script?  I'm suggesting the option, if possible, to add our own custom messaging so that we all don't have the same messaging.

As always, thank you for everything you guys do!

~Gab

**Comment by Dartellum** [comment]
Are you asking if we can add custom messages to the Hmm? Yes? Ok? currently in status-monitor? This something you still wanting now the request is 3 years old?

**Comment by MahtraDR** [comment]
@rpherbig Can we close this? Years without updates.
