### ISSUE TITLE
Error after item assembly with forge.

### ISSUE THREAD

**Issue by hwoo79** [rpherbig/dr-scripts#127]
[forge]>assemble my knife with my hilt
You slide the knife over the tang of your hilt and tighten the pommel to secure it.
>
--- Lich: error: undefined method `find_empty_room?' for #<Scripting::Forge:0xe4cf5d0>
	forge:153:in `grind_item'
	forge:148:in `slack'
--- Lich: forge has exited.

**Comment by rpherbig** [comment]
There is a new version of common that fixes this. Please download it and
rerun common to overwrite any stale method definition and retry this craft.

**Comment by rpherbig** [comment]
After discussion in #128, it's because of an out-of-date version of the forge script.
