### ISSUE TITLE
Fix ignite in combat-trainer

### ISSUE THREAD

**Issue by skyleronken** [rpherbig/dr-scripts#1272]
Ignite no longer needs to be released from weapon to weapon. It should be able to be tracked like any other buff now. It just takes a moment for the effect to return to the new weapon.

**Comment by rpherbig** [comment]
Is that for all weapons, or only elemental (summoned) weapons?

**Comment by skyleronken** [comment]
I have only tested it on normal weapons. You cannot recast ignite **before** its expired unless you 'release ignite', but that is not required to have the effect transfer to new weapons. This would mean that the configs would really only accept -1 as the recast time.

**Comment by rpherbig** [comment]
Neat, this must be new. Was there an announcement or anything?

I get to remove so much code that was a workaround to the old behavior :)

**Comment by skyleronken** [comment]
Not new that I know of. I had been doing it this way in my previous genie scripts.

**Comment by skyleronken** [comment]
tested this more. Not really helpful in training. Closing issue.
