### ISSUE TITLE
Alarm/TextString Alert

### ISSUE THREAD

**Issue by izawwlgood** [rpherbig/dr-scripts#1276]
It'd be nice to have the ability to send certain text strings to other windows. For example, spells fading, locates, bandages unwrapping, that sort of thing. So I propose a script, say, AlertMe, that lets you set some textstrings, say 'begin bleeding again', and sends the entire string to a window of your choosing, thoughts, or familiar, or OOC, etc.

I envision this being useful for setting alerts or alarms, specifically in the event of, say, someone locating, or advancing on you while youre hunting, so it doesnt get lost in the scroll.

**Comment by vtcifer** [comment]
@izawwlgood a framework for this is part of #5091.  

Scripts can make use of it once it's tested and committed.

**Comment by MahtraDR** [comment]
Closing this. We have the ability to do this today with triggers, and DRC.log_window.
