### ISSUE TITLE
add quench messaging to forge.lic

### ISSUE THREAD

**Issue by hwoo79** [rpherbig/dr-scripts#128]
line 123 and 124 need to be changed to:

    case bput("turn #{@item} on anvil with my tongs", 'ready for cooling in the slack tub', 'ready for a quench hardening in the slack tub', 'Roundtime')
    when 'ready for cooling in the slack tub', 'ready for a quench hardening in the slack tub'

respectively for additional quench messaging.

**Comment by rpherbig** [comment]
This was added to forge at the same time I fixed #126. Can you double check that you have the latest forge script?

**Comment by hwoo79** [comment]
I don't, but it's because I customized the holding container.  I will find a 'backpack' and add it to dependency

**Comment by rpherbig** [comment]
You can also modify the '@bag' value on line 35 (though be careful, as that change would get overwritten when a new version of forge is released).
