### ISSUE TITLE
red brocket deer room numbers

### ISSUE THREAD

**Issue by richardhertzog** [rpherbig/dr-scripts#1291]
Someone requested they be added to base-hunting but as I was exploring the area I noticed despite the fact every room is different a lot of them have the same room numbers.

young_red_brocket_deer:
- 10655
- 10656
- 10656
- 10657

red_brocket_deer:
- 10657
- 10656
- 10656 
- 10655

elder_red_brocket_deer:
- 10655
- 10656
- 10656
- 10657

**Comment by rpherbig** [comment]
Does that just mean every room has a mixed spawn, or different rooms are returning the same ID?

**Comment by richardhertzog** [comment]
Different rooms are returning the same idea. It's a 3 tier hunting area so
that could bite someone pretty hard if they tried it!

**Comment by jayRyan24** [comment]
This area needs a bescort I think.

**Comment by izawwlgood** [comment]
Late to the party here - the middle two rooms of each of the three tiers are identical, which makes it obnoxious as hell to go2 around.

**Comment by vtcifer** [comment]
Should be closed by #3992
