### ISSUE TITLE
Lay Ward requires moons to be out to cast as an empath.

### ISSUE THREAD

**Issue by arkrail** [rpherbig/dr-scripts#1292]
[buff: No moon available to cast lw]
[buff: Couldn't find any moons to cast lw with]

**Comment by rpherbig** [comment]
Lay Ward shouldn't require a moon. Do you by chance have `moon: true` in the LW spell definition?

**Comment by arkrail** [comment]
I did....and have no idea how that made it into my empaths yaml.  Thanks!
