### ISSUE TITLE
Maintain spells or buffs for lockpicking

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#13]

**Comment by rcuhljr** [comment]
Quick fix in place.

**Comment by rpherbig** [comment]
@rcuhljr is referring to 50f7792fb4bfe0208a05652e2076d5f72b2848a5.

Are there any plans for a larger-scale change? I don't think there are too many locksmithing buffs... While barbarians have one, I don't plan on getting it.

**Comment by rpherbig** [comment]
The short-term fix looks like it's working well enough that no one is asking for something larger-scale.
