### ISSUE TITLE
Support training for all crafting skills

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#130]
Forge.lic currently handles blacksmithing and weaponsmithing, but needs support for armorsmithing (search for 'NOT YET IMPLEMENTED'). Smelt.lic handles smelting.

We still need to support Engineering, Outfitting, Alchemy (and eventually Enchanting once it is released). A good starting point would probably be: https://elanthipedia.play.net/mediawiki/index.php/Category:Crafting_scripts

**Comment by hwoo79** [comment]
Another resource for this could be the mastercraft script from Genie.  It has 9 dependencies and also uses a global variable system.

http://www.genieclient.com/bulletin/topic/4855-download-utilitymastercraft/

**Comment by rpherbig** [comment]
Thanks for the link!

**Comment by hwoo79** [comment]
I can grab it if you can't. I know you used to have to have a key (paid for genie) to have forums access

**Comment by rpherbig** [comment]
I do not have forum access, but @rcuhljr might.

**Comment by rcuhljr** [comment]
Uploaded to the samples folder

**Comment by rpherbig** [comment]
We will want to make sure to address the issue in #136 in each of the other crafting skills' scripts.

**Comment by rpherbig** [comment]
@rcuhljr @kamarcum Think we can call this one done?

**Comment by rpherbig** [comment]
Alchemy is covered in #481.
