### ISSUE TITLE
ENGINEERING - sharpened drawknife is not getting materials to complete

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1300]
You need another finished short wooden pole to continue crafting an unfinished sharpened bronze drawknife.  You believe you can assemble the two ingredients together once you acquire them.

--- Lich: forge active.
[forge]>get my blacksmithing book
You get a book of journeyman blacksmithing instructions from inside your duffel bag.
>
[forge]>turn my book to chapter 3
You turn your book to chapter 3, entitled "Engineering Tools".
>
[forge]>read my book
              -=    Chapter 3 : Engineering Tools    =-

 Page 1: some short metal chisels                Page 14: some curved metal pliers
 Page 2: a short metal drawknife                 Page 15: a metal curved bone saw
 Page 3: some long metal chisels                 Page 16: a metal curved wood saw
 Page 4: some square metal rifflers              Page 17: a sturdy metal drawknife
 Page 5: a thin metal rasp                       Page 18: a rough metal wood shaper
 Page 6: a metal straight bone saw               Page 19: some reinforced chisels
 Page 7: a metal straight wood saw               Page 20: some curved metal rifflers
 Page 8: a long metal drawknife                  Page 21: a textured metal rasp
 Page 9: some squat metal rifflers               Page 22: some rough metal pliers
 Page 10: some plain metal pliers                Page 23: a metal slender bone saw
 Page 11: a flat metal shaper                    Page 24: a metal slender wood saw
 Page 12: some sturdy metal chisels              Page 25: a sharpened metal drawknife
 Page 13: a coarse metal rasp                    
>
[forge]>turn my book to page 25
You turn your book to page 25, instructions for crafting a sharpened metal drawknife.
>
[forge]>study my book
You review the sharpened drawknife instructions and quickly realize the design is far beyond your abilities.
You now feel ready to begin the crafting process.
Roundtime: 6 sec.
>
Summoning Lord Torgro came through an arch.
>
[forge]>put my book in my bag
You put your book in your duffel bag.
>
Summoning Lord Torgro went through an arch.
>
[forge]>get my bronze ingot
You get a bronze ingot from inside your hunting pack.
>
[forge]>put my ingot on anvil
You put your ingot on the iron anvil.
>
[forge]>untie my hammer from my forger belt
You remove a polished forging hammer crafted from engraved icesteel from your forger's belt.
>
[forge]>untie my tongs from my forger belt
You remove some polished tongs crafted from engraved icesteel from your forger's belt.
>
[forge]>pound ingot on anvil with my hammer
You scoop up the drawknife with your tongs and heat it over the flames of the forge.  Once the metal is glowing hot you place it back upon the anvil and hammer it steadily with your hammer.  Blow after blow rings out without any problems at all.

As you complete working the fire dies down and needs more fuel.
Roundtime: 16 sec.
>
[forge]>tie my tongs to my forger belt
You attach some polished tongs crafted from engraved icesteel to your forger's belt.
>
[forge]>untie my shovel from my forger belt
You remove a tapered steel shovel from your forger's belt.
>
[forge]>push fuel with my shovel
Gripping the shovel tightly, you slam it deep into the pile of fuel and give it a hard kick.  Straining, you remove the shovel with a mound of coal atop and toss it onto the fire.
Roundtime: 16 sec.
>
[forge]>tie my shovel to my forger belt
...wait 1 seconds.
>
[forge]>tie my shovel to my forger belt
You attach a tapered steel shovel to your forger's belt.
>
[forge]>untie my tongs from my forger belt
You remove some polished tongs crafted from engraved icesteel from your forger's belt.
>
[forge]>pound drawknife on anvil with my hammer
Following solid heating in the forge, you carefully fold the glowing red metal back onto itself and hammer it until both ends are fused.  Almost all of the rapid pounds find their mark.
Roundtime: 20 sec.
>
[forge]>pound drawknife on anvil with my hammer
You scoop up the drawknife with your tongs and heat it over the flames of the forge.  Once the metal is glowing hot you place it back upon the anvil and hammer it steadily with your hammer.  Your experience as a blacksmith is beginning to show in the finished work.

As you finish the fire flickers and is unable to consume its fuel.
Roundtime: 16 sec.
>
[forge]>tie my hammer to my forger belt
You attach a polished forging hammer crafted from engraved icesteel to your forger's belt.
>
[forge]>untie my bellows from my forger belt
You remove a wyvern leather bellows with handles of engraved icesteel from your forger's belt.
>
[forge]>push my bellows
You force copious amounts of air into the hot coals by pumping the bellows.
Roundtime: 17 sec.
>
Tekronn came through an arch.
>
Tekronn went through an arch.
>
[forge]>tie my bellows to my forger belt
You attach a wyvern leather bellows with handles of engraved icesteel to your forger's belt.
>
[forge]>untie my hammer from my forger belt
You remove a polished forging hammer crafted from engraved icesteel from your forger's belt.
>
[forge]>pound drawknife on anvil with my hammer
After using the tongs to warm the drawknife over the forge fire, you place it down upon the anvil and make some adjustments to its shape with carefully timed hammer taps.  Your experience as a blacksmith is beginning to show in the finished work.
Roundtime: 14 sec.
>
Your feet are finally dry.
>
[forge]>pound drawknife on anvil with my hammer
After using the tongs to warm the drawknife over the forge fire, you place it down upon the anvil and make some adjustments to its shape with carefully timed hammer taps.  Your experience as a blacksmith is beginning to show in the finished work.
Roundtime: 19 sec.
>
[forge]>pound drawknife on anvil with my hammer
You scoop up the drawknife with your tongs and heat it over the flames of the forge.  Once the metal is glowing hot you place it back upon the anvil and hammer it steadily with your hammer.  Your experience as a blacksmith is beginning to show in the finished work.
Roundtime: 16 sec.
>
[forge]>pound drawknife on anvil with my hammer
Following solid heating in the forge, you carefully fold the glowing red metal back onto itself and hammer it until both ends are fused.  Almost all of the rapid pounds find their mark.
Roundtime: 11 sec.
>
[forge]>pound drawknife on anvil with my hammer
You scoop up the drawknife with your tongs and heat it over the flames of the forge.  Once the metal is glowing hot you place it back upon the anvil and hammer it steadily with your hammer.  The hammering very nearly meets your expectations.

You notice the drawknife would benefit from some soft reworking.
Roundtime: 16 sec.
>
[forge]>turn drawknife on anvil with my tongs
You hold the drawknife steady on the horn of the anvil with your tongs.  Then you tap it lightly with your hammer to add a curve along the metal's surface.

The metal now appears ready for cooling in the slack tub.
Roundtime: 16 sec.
>
[forge]>tie my hammer to my forger belt
You attach a polished forging hammer crafted from engraved icesteel to your forger's belt.
>
[forge]>tie my tongs to my forger belt
You attach some polished tongs crafted from engraved icesteel to your forger's belt.
>
[forge]>push tub
Gusts of hot steam billow from the tub as you submerse the scorching hot sharpened drawknife.

The worked metal looks to be in need of some oil to preserve and protect it.
Roundtime: 16 sec.

You need another finished short wooden pole to continue crafting an unfinished sharpened bronze drawknife.  You believe you can assemble the two ingredients together once you acquire them.

[Ingredients can be added by using ASSEMBLE Ingredient1 WITH Ingredient2]
>
[forge]>get drawknife from anvil
You get an unfinished sharpened bronze drawknife from atop an iron anvil.
>
[forge]>get my short.pole
What were you referring to?
>
[forge]>assemble my drawknife with my short.pole
What were you referring to?
>
[forge: *** No match was found after 15 seconds, dumping info]
[forge: messages seen length: 3]
[forge: message: What were you referring to?]
[forge: message: [DRPrime]-DR:Etreu: "They should not be the same container. but it shouldn't cause a loop."]
[forge: message: [DRPrime]-DR:Etreu: "it will just cause you to miss boxes."]
[forge: checked against [/affix it securely in place/i, /and tighten the pommel to secure it/i, /carefully mark where it will attach when you continue crafting/i]]
[forge]>get my oil
You get a flask of oil from inside your duffel bag.
>
[forge]>pour my oil on my drawknife

You need another finished short wooden pole to continue crafting an unfinished sharpened bronze drawknife.  You believe you can assemble the two ingredients together once you acquire them.

[Ingredients can be added by using ASSEMBLE Ingredient1 WITH Ingredient2]

[forge]>get drawknife from anvil
You get an unfinished sharpened bronze drawknife from atop an iron anvil.
>
[forge]>get my short.pole
What were you referring to?
>
[forge]>assemble my drawknife with my short.pole
What were you referring to?
>
[forge: *** No match was found after 15 seconds, dumping info]
[forge: messages seen length: 3]
[forge: message: What were you referring to?]
[forge: message: [DRPrime]-DR:Etreu: "They should not be the same container. but it shouldn't cause a loop."]
[forge: message: [DRPrime]-DR:Etreu: "it will just cause you to miss boxes."]
[forge: checked against [/affix it securely in place/i, /and tighten the pommel to secure it/i, /carefully mark where it will attach when you continue crafting/i]]
[forge]>get my oil
You get a flask of oil from inside your duffel bag.
>
[forge]>pour my oil on my drawknife

You need another finished short wooden pole to continue crafting an unfinished sharpened bronze drawknife.  You believe you can assemble the two ingredients together once you acquire them.

[Ingredients can be added by using ASSEMBLE Ingredient1 WITH Ingredient2]
>
[forge: *** No match was found after 15 seconds, dumping info]
[forge: messages seen length: 2]
[forge: message: You need another finished short wooden pole to continue crafting an unfinished sharpened bronze drawknife.  You believe you can assemble the two ingredients together once you acquire them.]
[forge: message: [Ingredients can be added by using ASSEMBLE Ingredient1 WITH Ingredient2]]
[forge: checked against [/Roundtime/i, /Applying the final touches/i, /You can't pour/i]]
[forge]>put my oil in my bag
You put your oil in your duffel bag.
>
[forge]>get my stamp
You get a basic silversteel stamp from inside your duffel bag.
>
[forge]>mark my drawknife with my stamp
You cannot figure out how to do that.
>
[forge]>put my stamp in my bag
You put your stamp in your duffel bag.
>
--- Lich: forge has exited.
[workorders]>get my forging logbook
You get a forging work order logbook from inside your hunting pack.
>
[workorders]>bundle my drawknife with my logbook
Only completed items can be bundled with the work order.
>
[workorders: *** No match was found after 15 seconds, dumping info]
[workorders: messages seen length: 1]
[workorders: message: Only completed items can be bundled with the work order.]
[workorders: checked against [/You notate the/i, /This work order has expired/i, /The work order requires items of a higher quality/i, /That's not going to work/i]]
[workorders]>stow right
You put your drawknife in your hunting pack.
>
[workorders]>stow left
You put your logbook in your hunting pack.
>
--- Lich: go2 active.
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>go arch

**Comment by arkrail** [comment]
Forging is doing similar things, but I thought it might have been Shard related. #1298
