### ISSUE TITLE
Fix Pick so that it doesn't attempt teleport boxes when the moon isn't up.

### ISSUE THREAD

**Issue by ohbeanz** [rpherbig/dr-scripts#1310]
Because you can die. All the time.

**Comment by rcuhljr** [comment]
Make sure to make this optional.

**Comment by MahtraDR** [comment]
@rpherbig How do you feel about closing this, given today we can
```
pick:
  trap_blacklist:
  - teleport
```
I understand the nuance difference of the request, but as a no-effort solution for a 4yo solution, trap_blacklist seems reasonable to me.
