### ISSUE TITLE
workorders: Add support for Su Helmas adjustable crafting tools

### ISSUE THREAD

**Issue by skyleronken** [rpherbig/dr-scripts#1322]
Su Helmas introduced a crafting tool that is adjustable between tongs and a shovel. It would be nice to have support for adjustable tools since this is likely to become a new trend.

**Comment by jandersson** [comment]
I just got one of these as well. I wonder if its worth revisiting the 'transforming item' code in EquipManager?

**Comment by Dartellum** [comment]
I had tried to get this working before when I had one. I finally gave up. I still have the adjustable tongs.

**Comment by Dartellum** [comment]
I could look into this again, if you think I should. Otherwise, I suggest closing this issue as it is 3 years old now.

**Comment by MahtraDR** [comment]
@rpherbig Close, as per Dart's comment from 2020?
