### ISSUE TITLE
common: ordinal numbers from 13 to 11

### ISSUE THREAD

**Issue by shadee01** [rpherbig/dr-scripts#1329]
Ordinal numbers should be changed in common to remove twelfth and thirteenth.

> rumm ret
You rummage through a black velvet reticule and see an emerald ring, a sapphire ring, a copper ring, an oravir ring, a covellite ring, an opal ring, a bronze ring, a pearl ring, a jade ring, a diamond ring, a coral ring, a bloodstone ring, an amethyst ring and an agate ring.
> tap first ring in ret
You tap an emerald ring inside your reticule.
> tap fifth ring in ret
You tap a covellite ring inside your reticule.
> tap tenth ring in ret
You tap a diamond ring inside your reticule.
> tap eleventh ring in ret
You tap a coral ring inside your reticule.
> tap twelfth ring in ret
You tap a coral ring inside your reticule.
> tap thirteenth ring in ret
You tap a coral ring inside your reticule.
> tap fourteenth ring in ret
You tap a coral ring inside your reticule.

**Comment by jandersson** [comment]
Closed by 1090a03f5021e6656b51046e84ec13b7071d7881
