### ISSUE TITLE
Convert theurgy to pure ruby

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#133]

**Comment by rpherbig** [comment]
@rcuhljr Can we close this with 2385120d6a8e7135a6d987b23d9e65342b3af7ba and 9f6392dda1bbacfd62ed96d2c5209e0cf72f24d2 or is there more work to be done?

**Comment by rcuhljr** [comment]
I want to make the sword and water holder variables, as well as 'do you have commune tasmine'

**Comment by rcuhljr** [comment]
1f48eccf7d2fd0399cc9986379390427836d80f0
