### ISSUE TITLE
Request setting for choosing NPC healer without setting up hometown

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#1337]
Currently hunting storm bulls in Leth....hate running back to Crossings to wait in line at Dokt's for healing.  Would it be possible add a NPC healer choice to my yaml without changing my hometown?  (I don't want/need Leth as my hometown)

Thank  you.

~Gab

**Comment by BinuDR** [comment]
The setting `force_healer_town` deals with this.

This issue can be closed. @rpherbig .  If I don't need to @ you to close issues, please let me know.
