### ISSUE TITLE
Predict Event in astrology

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#1347]
Predicting events is another thing to do in astrology training. Currently it predicts skill pools which its filled from an observation and then predicts weather. We could insert predict event somewhere in there. 

Note: I wouldn't mind tackling this after I get my current PR completed

**Comment by mwest152** [comment]
Not sure the timer, but perc moons also moves me multiple mind states with 500+ astrology.  Same type of usage as predict weather for possible in combat integration and an additional thing for the astrology script.  At 530 or whatever I have in astro, predicting events actually wont even move me 1 mind state.  I think someone mentioned maybe below 400-450 it is good.   It is pretty quick to do however at least at night.

**Comment by jandersson** [comment]
`perc moons` moves astrology? I had no idea. I'll look at adding it after RtR and predict event is done.

**Comment by jandersson** [comment]
Would you mind making an issue for that? Something like 'Integrate perc moon to astrology and use in combat-trainer'
