### ISSUE TITLE
Integrate Read the Ripples (RtR) with astrology script

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#1349]
RtR should be a non-lethal method for locking astrology, so It should probably be prioritized over ways walking which is lethal.

I will grab this on my Moonmage and program it into `astrology` if no one gets to it before :]

**Comment by Aurayn** [comment]
RTR SF SCRIPT : TITLE RTR - http://pastebin.com/m3Wr5auH
RTR SF - POST CAST SCRIPT : TITLE RTR+ - http://pastebin.com/UUrNAuuj

This work out as I was too injured to use my telescope. I healed mid predictions but lost several minutes. Even so the messages are the same. 
RTR LOG WHEN INJURED: -  http://pastebin.com/6ZWqKunF

**Comment by jandersson** [comment]
Thank you sir!

**Comment by Aurayn** [comment]
Right back atcha
