### ISSUE TITLE
Request - EOTB released when hunt is done

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1352]
Got kicked out of hunting due to bleeding and it was still up
Hunt finished timer and it was still up

Thanks!

**Comment by jandersson** [comment]
What did having invisiblity mess up? I ask because it might be more helpful to release invisibility in that script where its needed

**Comment by Aurayn** [comment]
Couldn't be healed by Dokt
Couldn't get weapons fixed
Couldn't do banking

**Comment by rpherbig** [comment]
Can you get a log of these?

**Comment by jandersson** [comment]
To add on, I got stuck during forging training due to having invisibility up. There's a `release_invisibility` method in common that might be good to run. It should already be doing it at the bank.

**Comment by Aurayn** [comment]
yessir i will try and get those today for you.

**Comment by jandersson** [comment]
It looks like repair already handles release invisibility. Ill add a PR to catch the banking and some other inviso related issues i noticed
