### ISSUE TITLE
forging.lic needs to handle multiple discipline logbooks

### ISSUE THREAD

**Issue by hwoo79** [rpherbig/dr-scripts#136]
line 180 probably needs to be 'forging logbook' instead of 'logbook' in case of other disciplines logbooks present

**Comment by rpherbig** [comment]
I don't have a logbook. Have you tested that 'get my forging logbook' works?

**Comment by hwoo79** [comment]
Yes, it does work. Same with get my engineering logbook. I'm assuming the same on alchemy logbook, but I don't do alchemy. 

Next time e can fork it and p
