### ISSUE TITLE
Mechanical Lore Statue

### ISSUE THREAD

**Issue by Sephroc** [rpherbig/dr-scripts#1370]
When braiding it just drops the rope instead of putting it in the statue. Was told to put in an issue in here to get the statue in the Crossing Empath Guild added. Thanks!

**Comment by rpherbig** [comment]
Huh, I thought I did that in #1279 (fd06bd8b29674faa64179e13585a8a29748a8b2f).

Can you go to the room with the statue and tell me what `;en echo DRRoom.room_objs` returns?

**Comment by Sephroc** [comment]
>;en echo DRRoom.room_objs
--- Lich: exec1 active.
[exec1: ["pile of rocks", "braided bundling rope", "braided bundling rope",
"grass", "an embroidery needle", "large fiery fissure", "braided bundling
rope", "pile of rocks", "braided bundling rope", "sunstone runestone marked
with a symbol for Compost", "silver tea cart with several things on it",
"large vela'tohr plant", "marble statue of an elegant Elven woman carrying
a shallow basin in her arms", "an Empath renown scroll", "shallow stone
stairs", "junk"]]
--- Lich: exec1 has exited.

**Comment by rpherbig** [comment]
Well... it's definitely there (`marble statue of an elegant Elven woman carrying
a shallow basin in her arms`). I'll have to check if the regex catches that when I have more time.

**Comment by skyleronken** [comment]
en echo DRRoom.room_objs.map { |long_name| DRC.get_noun(long_name) }

--- Lich: exec1 active.

[exec1: ["chips", "chips", "cart", "plant", "arms", "scroll", "stairs"]]


You can see that it picks up "arms" not "statue"

**Comment by rcuhljr** [comment]
put a workable hotfix in place.
