### ISSUE TITLE
base-shrines movement failure

### ISSUE THREAD

**Issue by tulanegator** [rpherbig/dr-scripts#1371]
I'm a new Cleric. When I run the theurgy.lic script it results in an error because movement fails in Kaerna Village when I go up from this room:

[A Dark Tunnel]
There is a strong light leaking in from a hole above you, and weaker lantern light to the east.  Roots stick out from the wood-braced dirt walls, the glittering minerals in the earth catching what little light there is and reflecting it back.  
Obvious exits: east, up.

to this room:

[Near Kaerna Village, A Dirt Path]
Here a dirt path leads to a dark grove of trees.  A tree stump, its trunk featuring a sizable hole and the base covered with odd carvings that would appear to be symbols, stands where the trail terminates.  
Obvious paths: none.
Roundtime: 10 seconds.

When I get to the second room, A Dirt Path, the script tries to move "go path" then "go pool" but I'm usually lying on my back (and in a 10 second RT) when I get up to the dirt path. I've paused the script and manually completed the next steps, but then on my way down the stump (from the Dirt Path room to the Dark Tunnel) the same thing happens. I end up kneeling or lying down in the Dark Tunnel and the movement script fails. I think I've narrowed the issue to the following section of the base-shrines file:

  - location: Damaris' altar near Kaerna
    start_room: 1164
    path_in:
    - go shack
    - go hole
    - west
    - up
    - go path
    push: altar
    path_out:
    - go path
    - go stump
    - east
    - go hole
    - out

It does not wait or check for standing while going "up" or "go stump." Unfortunately I'm not sure how to fix it.

**Comment by rpherbig** [comment]
Try `;e use_lich_fork` then restarting your front end.

**Comment by tulanegator** [comment]
Thank you that worked. I fell through the stump and got the following:

[theurgy]>go stump
You take a deep breath, say a brief prayer, and then climb into a tree stump.

Near the bottom, one of the roots you are holding onto suddenly gives way, and you fall a few feet before landing firmly on your bottom, shaken, but intact.

[A Dark Tunnel]
There is a strong light leaking in from a hole above you, and weaker lantern light to the east.  Roots stick out from the wood-braced dirt walls, the glittering minerals in the earth catching what little light there is and reflecting it back.  
Obvious exits: east, up.
Roundtime: 10 seconds.
>
[theurgy]>east
You can't do that while sitting!
>
[theurgy]>stand
You stand back up.
[theurgy]>east
>
You go east.
[A Dark Tunnel]
Were it not for some lanterns that someone has hung from the ceiling of this burrow, you wouldn't be able to see a thing.  The total silence that pervades this underground tunnel isn't helping much, either.  What little you do see of the architecture is expertly made, possibly even Dwarven in construction.  You also see a dark hole.
Obvious exits: west.
