### ISSUE TITLE
Mapping Moths

### ISSUE THREAD

**Issue by izawwlgood** [rpherbig/dr-scripts#1382]
Could someone get this area mapped?

**Comment by mwest152** [comment]
I've mapped this, I could make a map image and update narost, but it's a little dangerous for me.  I'll try to get this added to base-hunting a little later.  

room numbers:
12036
12037
12038
12039
12040
12041
12042
12065
12066
12067
12068
12069
12070
12071

**Comment by mwest152** [comment]
Submitted pull request to add to base-hunting.
