### ISSUE TITLE
Casting moonblade at non existent moon

### ISSUE THREAD

**Issue by Missah** [rpherbig/dr-scripts#1385]
Combat yaml is attempting to cast moonblade at a moon that is not out.  It continues to cast over and over and over.  Can this be fixed, please?
Thank you.

```
[combat-trainer]>pre moonblade

Since you're not feeding enough power into the spell pattern to make it coherent, you quickly work your way to the minimum required.
You raise your arms skyward, chanting the equation of the Moonblade spell.

[combat-trainer]>cast yavash

You gesture.
Yavash is on the wrong side of Elanthia and is not visible.

[combat-trainer]>break moonblade

You must hold the black moonblade to do that.
```

**Comment by rpherbig** [comment]
@rcuhljr Was the moonwatch bot down for a bit?

**Comment by BinuDR** [comment]
This seems to be handled.  It uses the common-arcana method `check_moonwatch` to check if moonwatch is running, and if it's not it will start it and wait for the uservar to be populated with data.
@rpherbig
