### ISSUE TITLE
steal script crashes on NPC stealing (GLITCH)

### ISSUE THREAD

**Issue by brycole** [rpherbig/dr-scripts#1391]
The steal script is currently crashing when stealing from the "beggar" npc using Genie + Lich. It is a repeatable bug. I could not replicate manually.

Output is:

hide
You hide
Roundtime
steal beggar <crash before output>

I initially thought it may be related to command queing and swapped out FPUT for BPUT but the crash still happened.

![steal](https://cloud.githubusercontent.com/assets/19298910/23248728/c8ab7d72-f955-11e6-9267-025b3b8ab340.JPG)

**Comment by rpherbig** [comment]
If you set `npc_stealing_attempt_count: 0` that will prevent stealing from the beggar (a short term fix).

I don't have Genie so I can't test why this is happening. @rcuhljr Do you have Genie?

**Comment by intangibles** [comment]
I reviewed the lich debug logs during the time frame and nothing popped out.  I also don't see any genie related logs that I could use to debug.

I could probably run XML logs during the process if you think that would help.

**Comment by MahtraDR** [comment]
@rpherbig Close? Lich's open source now, if this comes up again, we can look at it then?
