### ISSUE TITLE
Steal script shouldn't drop items until full hands or leaving shop

### ISSUE THREAD

**Issue by brycole** [rpherbig/dr-scripts#1398]
Steal is currently dropping an item after every steal, instead of dropping when hands are full or when shop is over.  This is causing double hide RT.  

```
> [steal]>steal pick in catalog
> 
> You feel fully attuned to the mana streams again.
> H> 
> Moving stealthily, you manage to grab a carved pick right from underneath the apprentice's very nose.
> You learned quite badly from this nearly trivial theft.
> Roundtime: 5 sec.
> H> 
> [steal]>drop my pick
> 
> You come out of hiding.
> You think better of leaving this evidence out where anyone can see it, and stuff it somewhere out of sight.
> You drop a carved pick.
> 
> > 
> [steal]>hide
> 
> You blend in with your surroundings, but cannot shake the feeling that you drew attention to yourself.
> Roundtime: 5 sec.
> 
> HR> 
> [steal]>steal pick in catalog
> 
> Moving stealthily, you manage to grab a carved pick right from underneath the apprentice's very nose.
> You learned quite badly from this nearly trivial theft.
> Roundtime: 5 sec.
> 
```

**Comment by skyleronken** [comment]
Not sure about this. I train hiding while stealing. i guess if I were ML then I wouldn't want the additional hide attempts...

**Comment by intangibles** [comment]
122 stealth
77 thievery

Stealth training is fairly negligible and may even be on a timer. I stole "acceptable" items 12 times and did not move a single mindstate.   I drained from 3/34 to 2/34 and was not getting any exp from stealing until 20-30 seconds later.

Beginning: 
thievery 0/34
stealth 3/34

ending
thievery 30/34
stealth 6/34

**Comment by mwest152** [comment]
What is your stealth ranks to thievery ranks though?  I believe they would need to be in the same range to learn stealth from acceptable items.

**Comment by skyleronken** [comment]
They are on par

**Comment by intangibles** [comment]
I'm not confident that hiding twice grants extra EXP. When i was testing it appeared to be on a timer.  Can you confirm you see learning from both hide/steal attempts?

**Comment by BinuDR** [comment]
Does anyone still use steal since burgle was released?

**Comment by KatoakDR** [comment]
> Does anyone still use steal since burgle was released?

Yep because it’s fun to rob stores :)

For training I rely on burgle script but I do run steal script every once in and a while.

**Comment by BinuDR** [comment]
@rpherbig I'd say go ahead and close this.  With burgle and `hide_to_steal: false`, I don't think there's any need for it anymore.
