### ISSUE TITLE
configurable exec command from , to  ;  (GLITCH)

### ISSUE THREAD

**Issue by brycole** [rpherbig/dr-scripts#1401]
Is it possible we can have the option of changing the execution command in GLITCH?

Right now its a COMMA, because genie uses SEMICOLON as a separator.  However, the separator can be changed via "#config separatorchar §" in genie which will allows the use of semicolon via lich.   ( I changed to that symbol to avoid conflicts.)

I made the change in GLITCH to ; but lich.rbw kept being overridden.  I tried to set it read only but this broke several other scripts so swapped back to using comma.

I've had the ; seperator changed for about a week now and the only issue ive noticed is that the Exp Window plugin in genie uses ;. But not a big deal.

Thanks!

**Comment by skyleronken** [comment]
Is this really such an issue? Ive been using the comma instead of semicolon for a while. I have not seen it limit my Lich functionality in any way. Is this more of a convenience thing for copy and paste? If so, I recommend closing this ticket.

**Comment by intangibles** [comment]
If you are swapping back and forth between Genie and Stormfront then yes, it can be quite annoying. You also need semicolons to be able to paste code in chat when discussing single line items executions.

Genie has a way to change the separator character and the lich change is relatively minor. 

Further, convenience is a perfectly reasonable reason to make a coding change.

**Comment by skyleronken** [comment]
Those of us using glitch have become accustomed. I switch between Profanity and Genie and do sometimes mix it up, but a switch like this may negatively impact genie aliases. 

Is the necessary Genie modification documented well? Could cause an issue for new Lichers. 

Is there a way to make it a configuration or environment variable rather than a static change? That would be considered coding/engineering best practices.

**Comment by intangibles** [comment]
I definitely understand that you can become accustomed to it.  But I think we should also be looking at it from a new player prospective.  This raises the barrier for use of GLITCH that may turn people away. We should do everything we can to make a seamless transaction.

Your question RE: aliases is a good question too. Luckily all of genie aliases can be edited via a text file. If players wanted to switch to the new separator, they could. If not, they can leave it the same.

And can absolutely be changed on the fly via environment variable. I imagine it can be folded into the glitch fork toggle for initial start up, and changed later.

It's a 1 line change in litch.rbw. Or a couple lines if it gets swapped to an environment variable.

$clean_lich_char = $frontend == 'genie' ? ',' : ';'

**Comment by MahtraDR** [comment]
Is this still an issue for people?

**Comment by MahtraDR** [comment]
@rpherbig close this? Genie's open source now. Folks can fix this kind of thing for themselves.
