### ISSUE TITLE
;WEAVE - augmentation Request

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1402]
have ;Weave check the loom and remove any thread already on it

**Comment by rpherbig** [comment]
Can you get a log of the commands used, success, and failure?

**Comment by Aurayn** [comment]
my goof up is the same messagig as when someone leaves a spool of thread on does this work?


[go2: travel time: 0:00:01]

--- Lich: go2 has exited.

[weave-cloth]>get my thread

You get some cotton thread from inside your duffel bag.

[weave-cloth]>put my thread on loom

You load a hefty loom with all of some cotton thread.

[weave-cloth]>get my thread

You get some fine silk thread from inside your hunting pack.

[weave-cloth]>put my thread on loom

You have difficulty stringing the loom due to the differing thread material.  A loom capable of more intricate weaves is necessary to handle such exotic cloth creation.

[weave-cloth]>drop thread

You drop some fine silk thread.

[weave-cloth]>weave loom

The loom needs to have 2 sections of thread, length 10 yards or more placed on it before cloth weaving can begin.  You think you can STUDY it to learn more.

[weave-cloth: *** No match was found after 15 seconds, dumping info]

[weave-cloth: messages seen length: 2]

[weave-cloth: message: The loom needs to have 2 sections of thread, length 10 yards or more placed on it before cloth weaving can begin.  You think you can STUDY it to learn more.]

[weave-cloth: message: [Trade] Your mind hears Aayveia thinking, "kinda like you and those oh so lovely spectacles"]

[weave-cloth: checked against [/dust and debris/i, /unravel/i, /bunch/i, /needs pushing together/i, /need pushing together/i, /roundtime/i]]

[weave-cloth]>weave loom

The loom needs to have 2 sections of thread, length 10 yards or more placed on it before cloth weaving can begin.  You think you can STUDY it to learn more.

[weave-cloth: *** No match was found after 15 seconds, dumping info]

[weave-cloth: messages seen length: 2]

[weave-cloth: message: The loom needs to have 2 sections of thread, length 10 yards or more placed on it before cloth weaving can begin.  You think you can STUDY it to learn more.]

[weave-cloth: message: [Trade] Your mind hears Sepharus thinking, "They're only temporary"]

[weave-cloth: checked against [/dust and debris/i, /unravel/i, /bunch/i, /needs pushing together/i, /need pushing together/i, /roundtime/i]]


[weave-cloth]>weave loom

The loom needs to have 2 sections of thread, length 10 yards or more placed on it before cloth weaving can begin.  You think you can STUDY it to learn more.
>stow thr
You pick up some fine silk thread.
You put your thread in your hunting pack.
>look on loo
You see the loom is loaded with some cotton thread.

[weave-cloth: *** No match was found after 15 seconds, dumping info]

[weave-cloth: messages seen length: 4]

[weave-cloth: message: The loom needs to have 2 sections of thread, length 10 yards or more placed on it before cloth weaving can begin.  You think you can STUDY it to learn more.]

[weave-cloth: message: You pick up some fine silk thread.]

[weave-cloth: message: You put your thread in your hunting pack.]

[weave-cloth: message: You see the loom is loaded with some cotton thread.]

[weave-cloth: checked against [/dust and debris/i, /unravel/i, /bunch/i, /needs pushing together/i, /need pushing together/i, /roundtime/i]]

[weave-cloth]>weave loom

The loom needs to have 2 sections of thread, length 10 yards or more placed on it before cloth weaving can begin.  You think you can STUDY it to learn more.
>study look
Study what?
>study loom
  You think it possible to PUT refined thread onto the loom and then WEAVE the loom to begin weaving a yard of cloth.  The primary cloth types are created by loading threads of the same material for both the warp and weft.

  This appears to be a simple type of loom.  More advanced looms can also be ADJUSTed to produce various weave patterns and loaded with dissimilar thread and metallic threads to produce more exotic types of fabric.

  Once weaving has begun, you may need to CLEAN, TURN, or PUSH the loom to handle any problems that arise during the process.


[weave-cloth: *** No match was found after 15 seconds, dumping info]

[weave-cloth: messages seen length: 7]

[weave-cloth: message: The loom needs to have 2 sections of thread, length 10 yards or more placed on it before cloth weaving can begin.  You think you can STUDY it to learn more.]

[weave-cloth: message: Study what?]

[weave-cloth: message:   You think it possible to PUT refined thread onto the loom and then WEAVE the loom to begin weaving a yard of cloth.  The primary cloth types are created by loading threads of the same material for both the warp and weft.]

[weave-cloth: message:   This appears to be a simple type of loom.  More advanced looms can also be ADJUSTed to produce various weave patterns and loaded with dissimilar thread and metallic threads to produce more exotic types of fabric.]

[weave-cloth: message:   Once weaving has begun, you may need to CLEAN, TURN, or PUSH the loom to handle any problems that arise during the process.]

[weave-cloth: message: [Trade] Your mind hears Aayveia thinking, "I hope so."]

[weave-cloth: message: [DRPrime]-DR:Kesmgurr: "Exactly"]

[weave-cloth: checked against [/dust and debris/i, /unravel/i, /bunch/i, /needs pushing together/i, /need pushing together/i, /roundtime/i]]

[weave-cloth]>weave loom

The loom needs to have 2 sections of thread, length 10 yards or more placed on it before cloth weaving can begin.  You think you can STUDY it to learn more.

[weave-cloth: *** No match was found after 15 seconds, dumping info]

[weave-cloth: messages seen length: 3]

[weave-cloth: message: The loom needs to have 2 sections of thread, length 10 yards or more placed on it before cloth weaving can begin.  You think you can STUDY it to learn more.]

[weave-cloth: message: [DRPrime]-DR:Zharen: "weeks, you know what I was thinking the other day? Clerics need some love"]

[weave-cloth: message: [DRPrime]-DR:Kesmgurr: "Even stranger, there is not lnet"]

[weave-cloth: checked against [/dust and debris/i, /unravel/i, /bunch/i, /needs pushing together/i, /need pushing together/i, /roundtime/i]]

[weave-cloth]>weave loom

The loom needs to have 2 sections of thread, length 10 yards or more placed on it before cloth weaving can begin.  You think you can STUDY it to learn more.
>get thre from loo
You get some cotton thread from inside a hefty loom.

[weave-cloth: *** No match was found after 15 seconds, dumping info]

[weave-cloth: messages seen length: 4]

[weave-cloth: message: [DRPrime]-DR:Aidrial: "Together - We Are Legion."]

[weave-cloth: message: The loom needs to have 2 sections of thread, length 10 yards or more placed on it before cloth weaving can begin.  You think you can STUDY it to learn more.]

[weave-cloth: message: You get some cotton thread from inside a hefty loom.]

[weave-cloth: message: [DRPrime]-DR:Phanuel: "Clerics really should be able to put more buffs into their orb."]

[weave-cloth: checked against [/dust and debris/i, /unravel/i, /bunch/i, /needs pushing together/i, /need pushing together/i, /roundtime/i]]

>drop loo
>look in my pack
But you aren't holding that.

[weave-cloth]>stow my cloth

In the hunting pack you see some fine silk thread, some fine silk thread, a cloth silk deed, a flat yardstick, a pointed awl, some fine silk cloth, some large cloth padding, some large cloth padding, an indigo gem pouch, an indigo gem pouch, an indigo gem pouch, a crown, a crown, a crown, a crown, a steel ingot, a cleaning cloth, a padded mantle, some large cloth padding, a rugged lavender backpack, some small cloth padding, some small cloth padding, some small cloth padding, a deed register, a steel ingot, a steel ingot, a steel ingot, a burgundy wood stylus, a deed packet, a lumium ingot, some fine titanese cloth, some wool yarn, some wool yarn, a glowing Kertigen orb, some wool yarn, a basic stamp, a milky celadon verdant heart, some wool yarn, some borax flux, some steel mechanisms, some wool yarn, some wool yarn, a linen black knapsack, a clay tablet, a fine scroll, a yellowed scroll, a curved hide scraper, some wood glue, some bleaching solution, a leather strip box, a hilt box, a small padding roll, a small backing roll, a large backing roll, a large padding roll, a short cord bundle, a hilt box, some ribbed sewing needles, some wool yarn, some wool yarn, some wool yarn, some wool yarn, some tinker's tools, some metal clamps, some wood stain, some wool yarn, some wool yarn, some long chisels, some sealing wax, a cerulean razor, a haversack, some wool yarn, some braided vines, some braided vines, some balsa lumber, a green gem pouch, a deed packet, a ingot gold deed, a ingot platinum deed, a ingot iron deed and an elegant folio.

--- Lich: weave-cloth has exited.

Stow what?  Type 'STOW HELP' for details.
>drop thr
You drop some cotton thread.
>;weave

--- Lich: weave-cloth active.

[weave-cloth]>get my thread

You get some fine silk thread from inside your hunting pack.

[weave-cloth]>put my thread on loom

You load a hefty loom with all of some fine silk thread.

[weave-cloth]>get my thread

You get some fine silk thread from inside your hunting pack.

[weave-cloth]>put my thread on loom

You load a hefty loom with all of some fine silk thread.

[weave-cloth]>weave loom

With a pull of the beam, you swap heddles securing the warp threads on the loom.  The loom's shuttle zips across the shed of warp threads and the weft battens together evenly along the edge.

Several weft threads bunch together from a tight turn in the fabric.
Roundtime: 12 sec.

[weave-cloth]>turn loom

With a slight turn you adjust the position of the loom's heddles, perfectly aligning the warp threads before weaving further.
Roundtime: 12 sec.

[weave-cloth]>weave loom

With a pull of the beam, you swap heddles securing the warp threads on the loom.  The loom's shuttle zips across the shed of warp threads and the weft battens together evenly along the edge.

One side of the partially-woven cloth is uneven, and needs pushing together.
Roundtime: 11 sec.

[weave-cloth]>push loom

You turn the loom's cloth roller while releasing slack on the warp threads, repositioning the partially-woven cloth with room to spare.
Roundtime: 13 sec.

[weave-cloth]>weave loom

You beat the cloth with the loom's reed and then exchange positions of the warp thread.  You pass the shuttle back and forth across the loom, your skill showing in the exceptional quality weave produced along the cloth's edge.
Roundtime: 4 sec.

[weave-cloth]>weave loom

With a pull of the beam, you swap heddles securing the warp threads on the loom.  You pass the shuttle back and forth across the loom, your skill showing in the exceptional quality weave produced along the cloth's edge.
Roundtime: 13 sec.

[weave-cloth]>weave loom

You shift the loom's beam and swap the raised heddles with the lowered ones.  After adjusting the loom's harnesses, you rapidly feed the shuttle across the warp threads, press it together with the reed and take up the cloth along a roller.

The thread upon the shuttle is bunching up from excessive tension.
Roundtime: 11 sec.

[weave-cloth]>turn loom

You perfectly adjust the tension along the loom's heddles and form a straighter shed of threads for picking the shuttle across.
Roundtime: 8 sec.

[weave-cloth]>weave loom

You shift the loom's beam and swap the raised heddles with the lowered ones.  After adjusting the loom's harnesses, you rapidly feed the shuttle across the warp threads, press it together with the reed and take up the cloth along a roller.

The cloth threads begin to unravel along the fell and need pushing together.
Roundtime: 8 sec.

[weave-cloth]>push loom

You turn the loom's cloth roller while releasing slack on the warp threads, repositioning the partially-woven cloth with room to spare.
Roundtime: 9 sec.

[weave-cloth]>weave loom

With a pull of the beam, you swap heddles securing the warp threads on the loom.  Pick after pick the shuttle passes effortlessly through the warp threads, forcing you to pause only for minor adjustments and taking up the cloth.
Roundtime: 11 sec.

[weave-cloth]>weave loom

You shift the loom's beam and swap the raised heddles with the lowered ones.  After adjusting the loom's harnesses, you rapidly feed the shuttle across the warp threads, press it together with the reed and take up the cloth along a roller.

The cloth threads begin to unravel along the fell and need pushing together.
Roundtime: 11 sec.

[weave-cloth]>push loom

You turn the loom's cloth roller while releasing slack on the warp threads, repositioning the partially-woven cloth with room to spare.
Roundtime: 6 sec.
You snip off the bolt of fabric and are left with some fine silk cloth.

[weave-cloth]>stow my cloth

You put your cloth in your hunting pack.

--- Lich: weave-cloth has exited.

>count cloth
You count out 39 yards of material there.
>..sew

**Comment by Aurayn** [comment]
Any thoughts on this? Was thinking we could do the same as forging where it removes ingots folks leave on the anvils..... they do the same with cloth

**Comment by rpherbig** [comment]
It seems like a fine idea. I don't think anyone is actively working on it.

**Comment by BinuDR** [comment]
Created a PR for this.

https://github.com/rpherbig/dr-scripts/pull/4498
