### ISSUE TITLE
Shard Forging Work Orders

### ISSUE THREAD

**Issue by drjunkie** [rpherbig/dr-scripts#1403]
When receiving a workorder for 2 superior quality sturdy metal drawknives, it doesn't grab the short poles required to assemble them. Following is my log:

[workorders]>get my forging logbook
You get a forging work order logbook from inside your aqua backpack.
>
[workorders]>ask Serric for challenging blacksmithing work
Serric shuffles through some notes and says, "Alright, this is an order for a sturdy metal drawknife. I need 2 of superior quality, made from any material and due in 65 roisaen.  Please complete the items, bundle them with your logbook and then give me the logbook to complete this order.  Good luck!"

You seem to recall this item being somewhere in chapter 3 of the instruction book.
>
[workorders]>put my logbook in my backpack
>
You put your logbook in your aqua backpack.
>
[workorders]>wealth dokoras
  4 gold and 10 silver Dokoras (5,000 copper Dokoras).
>
--- Lich: go2 active.
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>southeast
You go southeast.
[Forging Society, Supply Stand]
Enormous piles of ore flanked by glistening ingots dwarf the crafters making purchases here.  Rope as thick as a Gor'Tog's waist hang from a trio of massive pulleys used to rearrange crates around the area.  You also see a large sign.
Obvious exits: southwest, northwest.
Room Number: 4434
>
[go2: travel time: 0:00:00]
--- Lich: go2 has exited.
[workorders]>order 11
The attendant says, "You can purchase a huge bronze ingot for 405 Dokoras.  Just order it again and we'll see it done!"
>
[workorders]>order 11
The attendant takes some coins from you and hands you a huge bronze ingot.
>
[workorders]>stow left
You put your ingot in your aqua backpack.
>
[smith]>wealth dokoras
  4 gold, 5 silver, 9 bronze, and 5 copper Dokoras (4,595 copper Dokoras).
>
[smith]>inv search flask of oil
You rummage about your person, looking for something...

  Your oil is in a rugged aqua backpack.

Roundtime:  4 secs

[Type INVENTORY HELP for more options]
>
[smith]>tap anvil
I could not find what you were referring to.
>
--- Lich: go2 active.
[go2: ETA: 0:00:00 (3 rooms to move through)]
[go2]>southwest
You go southwest.
[Forging Society, East Hall]
This long corridor lined with soot-stained carpet reverberates with the whine of grinding steel.  Workers hurry back and forth to resupply at the stand to the northeast.  You also see an oak door.
Obvious exits: northeast, west.
Room Number: 4432
>
[go2]>go door
[Forging Society, Crucible]
A central cavity splits the ceiling and metal tubing funnels smoke away from the glowing fire.  A granite crucible scarred with use rests atop a forked beam next to the fire.  Black scrapes along the ground lead over to a circular pile of fuel in the corner.  You also see an ingot cutter, an oak door and a large waste bucket.
Obvious exits: north.
Room Number: 9617
[go2]>north
>
You go north.
[Forging Society, Forge]
Blocks of carved basalt form an octagonal forge surrounding shallow pits containing piles of fuel.  A steel anvil butts up against, and peeks over the heavily chipped blocks.  An assortment of metal molds and attachments for the anvil hang from the wall.  You also see a grindstone and a large waste bucket.
Also here: Outfitting Guru Maci.
Obvious exits: south.
Room Number: 9618
>
[go2: travel time: 0:00:00]
--- Lich: go2 has exited.
--- Lich: go2 active.
[go2: ETA: 0:00:01 (6 rooms to move through)]
[go2]>south
You go south.
[Forging Society, Crucible]
A central cavity splits the ceiling and metal tubing funnels smoke away from the glowing fire.  A granite crucible scarred with use rests atop a forked beam next to the fire.  Black scrapes along the ground lead over to a circular pile of fuel in the corner.  You also see an ingot cutter, an oak door and a large waste bucket.
Obvious exits: north.
Room Number: 9617
>
[go2]>go door
[Forging Society, East Hall]
This long corridor lined with soot-stained carpet reverberates with the whine of grinding steel.  Workers hurry back and forth to resupply at the stand to the northeast.  You also see an oak door.
Obvious exits: northeast, west.
Room Number: 4432
>
[go2]>northeast
You go northeast.
[Forging Society, Supply Stand]
Enormous piles of ore flanked by glistening ingots dwarf the crafters making purchases here.  Rope as thick as a Gor'Tog's waist hang from a trio of massive pulleys used to rearrange crates around the area.  You also see a large sign.
Obvious exits: southwest, northwest.
Room Number: 4434
>
[go2]>northwest
You go northwest.
[Forging Society, East Hall]
A pair of water barrels awaits use if the forge fires should get out of control.  A thin film of white dust coats the floor and walls, likely caused from the continuous passage of heavy sleds bearing supplies to and from the forges.  You also see Forging Society Master Serric and a hickory door.
Obvious exits: southeast, west.
Room Number: 4435
>
[go2]>go door
[Forging Society, Crucible]
Crinkled patches of metal stain the dolomite floor.  The splattering becomes more numerous and expands to form concentric circles near the room's center, where a large granite crucible hangs over a large fire.  You also see an ingot cutter, a pile of fuel, a large waste bucket and a hickory door.
Obvious exits: south.
Room Number: 9615
>
[go2]>south
You go south.
[Forging Society, Forge]
An octagonal forge situated in the room's center emits a ruddy glow illuminating the basalt blocks framing it.  In the corner, a large grindstone casts a gigantic shadow upon the wall, and wisps of steam rise up from the recently used slack tub and anvil.  You also see a pile of fuel and a large waste bucket.
Obvious exits: north.
Room Number: 9616
>
[go2: travel time: 0:00:02]
--- Lich: go2 has exited.
[smith]>look on anvil
The anvil's surface looks clean and ready for forging.
>
--- Lich: forge active.
[forge]>get my blacksmithing book
>
You get a book of journeyman blacksmithing instructions from inside your aqua backpack.
>
[forge]>turn my book to chapter 3
You turn your book to chapter 3, entitled "Engineering Tools".
>
[forge]>read my book
              -=    Chapter 3 : Engineering Tools    =-

 Page 1: a short metal drawknife                 Page 14: a metal curved wood saw
 Page 2: some short metal chisels                Page 15: a metal curved bone saw
 Page 3: a long metal drawknife                  Page 16: some curved metal pliers
 Page 4: a metal straight wood saw               Page 17: a coarse metal rasp
 Page 5: a metal straight bone saw               Page 18: some sturdy metal chisels
 Page 6: a thin metal rasp                       Page 19: some curved metal rifflers
 Page 7: some square metal rifflers              Page 20: some reinforced chisels
 Page 8: some long metal chisels                 Page 21: a sharpened metal drawknife
 Page 9: a flat metal shaper                     Page 22: a metal slender wood saw
 Page 10: some plain metal pliers                Page 23: a metal slender bone saw
 Page 11: some squat metal rifflers              Page 24: some rough metal pliers
 Page 12: a rough metal wood shaper              Page 25: a textured metal rasp
 Page 13: a sturdy metal drawknife               
>
[forge]>turn my book to page 13
You turn your book to page 13, instructions for crafting a sturdy metal drawknife.
>
[forge]>study my book
You review the sturdy drawknife instructions and confidently discern most of the design's minutiae.
You now feel ready to begin the crafting process.
Roundtime: 7 sec.
>
[forge]>put my book in my backpack
You put your book in your aqua backpack.
>
[forge]>get my bronze ingot
You get a bronze ingot from inside your aqua backpack.
>
[forge]>put my ingot on anvil
You put your ingot on the iron anvil.
>
[forge]>get my ball-peen hammer
You get a steel ball-peen hammer from inside your aqua backpack.
>
[forge]>get my tongs
You get some covellite box-jaw tongs from inside your aqua backpack.
>
[forge]>pound ingot on anvil with my hammer
Sparks fly into the air as you transfer the drawknife back and forth between the forge fires and the anvil, alternating heating with vigorous hammering of the metal.  The work proceeds as planned and you avoid introducing any defects.
Roundtime: 14 sec.
>
[forge]>pound drawknife on anvil with my hammer
Following solid heating in the forge, you carefully fold the glowing red metal back onto itself and hammer it until both ends are fused.  With expert precision the metal takes shape without any faults.

As you finish the fire flickers and is unable to consume its fuel.
Roundtime: 12 sec.
>
[forge]>put my ball-peen hammer in my backpack
...wait 1 seconds.
>
[forge]>put my ball-peen hammer in my backpack
You put your hammer in your aqua backpack.
>
[forge]>get my bellows
You get a leather bellows from inside your aqua backpack.
>
[forge]>push my bellows
You stoke the fire with strong pumps of your bellows.
Roundtime: 27 sec.
>
[forge]>put my bellows in my backpack
You put your bellows in your aqua backpack.
>
[forge]>get my ball-peen hammer
You get a steel ball-peen hammer from inside your aqua backpack.
>
[forge]>pound drawknife on anvil with my hammer
After using the tongs to warm the drawknife over the forge fire, you place it down upon the anvil and make some adjustments to its shape with carefully timed hammer taps.  The forging proceeds exceptionally well and free of mistakes.
Roundtime: 15 sec.
>
[forge]>pound drawknife on anvil with my hammer
Sparks fly into the air as you transfer the drawknife back and forth between the forge fires and the anvil, alternating heating with vigorous hammering of the metal.  The forging proceeds exceptionally well and free of mistakes.
Roundtime: 12 sec.
>
[forge]>pound drawknife on anvil with my hammer
After using the tongs to warm the drawknife over the forge fire, you place it down upon the anvil and make some adjustments to its shape with carefully timed hammer taps.  The forging proceeds exceptionally well and free of mistakes.

The drawknife could use some straightening along the horn of the anvil.
Roundtime: 12 sec.
>
[forge]>turn drawknife on anvil with my tongs
...wait 1 seconds.
>
[forge]>turn drawknife on anvil with my tongs
You angle the drawknife downward along the anvil's horn with your tongs, and then gently tap it with your hammer.
Roundtime: 16 sec.
>
[forge]>pound drawknife on anvil with my hammer
You scoop up the drawknife with your tongs and heat it over the flames of the forge.  Once the metal is glowing hot you place it back upon the anvil and hammer it steadily with your hammer.  Blow after blow rings out without any problems at all.
Roundtime: 25 sec.
>
[forge]>pound drawknife on anvil with my hammer
You scoop up the drawknife with your tongs and heat it over the flames of the forge.  Once the metal is glowing hot you place it back upon the anvil and hammer it steadily with your hammer.  The forging proceeds exceptionally well and free of mistakes.
Roundtime: 14 sec.
>
[forge]>pound drawknife on anvil with my hammer
Following solid heating in the forge, you carefully fold the glowing red metal back onto itself and hammer it until both ends are fused.  The work proceeds as planned and you avoid introducing any defects.

The metal now appears ready for cooling in the slack tub.
Roundtime: 12 sec.
>
[forge]>put my ball-peen hammer in my backpack
You put your hammer in your aqua backpack.
>
[forge]>put my tongs in my backpack
You put your tongs in your aqua backpack.
>
[forge]>push tub
An explosive blast of steam erupts from your sturdy drawknife as it hits the cool water of the slack tub!

The worked metal looks to be in need of some oil to preserve and protect it.
Roundtime: 12 sec.

You need another finished short wooden pole to continue crafting an unfinished sturdy bronze drawknife.  You believe you can assemble the two ingredients together once you acquire them.

[Ingredients can be added by using ASSEMBLE Ingredient1 WITH Ingredient2]
>
[forge]>get drawknife from anvil
You get an unfinished sturdy bronze drawknife from atop an iron anvil.
>
[forge]>get my short.pole
What were you referring to?
>
[forge]>assemble my drawknife with my short.pole
What were you referring to?
>
[forge: *** No match was found after 15 seconds, dumping info]
[forge: messages seen length: 1]
[forge: message: What were you referring to?]
[forge: checked against [/affix it securely in place/i, /and tighten the pommel to secure it/i, /carefully mark where it will attach when you continue crafting/i]]
[forge]>get my oil
You get a flask of oil from inside your aqua backpack.
>
[forge]>pour my oil on my drawknife

You need another finished short wooden pole to continue crafting an unfinished sturdy bronze drawknife.  You believe you can assemble the two ingredients together once you acquire them.

[Ingredients can be added by using ASSEMBLE Ingredient1 WITH Ingredient2]
>
[forge: *** No match was found after 15 seconds, dumping info]
[forge: messages seen length: 2]
[forge: message: You need another finished short wooden pole to continue crafting an unfinished sturdy bronze drawknife.  You believe you can assemble the two ingredients together once you acquire them.]
[forge: message: [Ingredients can be added by using ASSEMBLE Ingredient1 WITH Ingredient2]]
[forge: checked against [/Roundtime/i, /Applying the final touches/i, /You can't pour/i]]
[forge]>put my oil in my backpack
You put your oil in your aqua backpack.
>
--- Lich: forge has exited.
>
[workorders]>get my forging logbook
You get a forging work order logbook from inside your aqua backpack.
>
[workorders]>bundle my drawknife with my logbook
Only completed items can be bundled with the work order.
>
[workorders: *** No match was found after 15 seconds, dumping info]
[workorders: messages seen length: 1]
[workorders: message: Only completed items can be bundled with the work order.]
[workorders: checked against [/You notate the/i, /This work order has expired/i, /The work order requires items of a higher quality/i, /That's not going to work/i]]
[workorders]>stow right
You put your drawknife in your aqua backpack.
>
[workorders]>stow left
You put your logbook in your aqua backpack.
>
--- Lich: go2 active.
[go2: ETA: 0:00:00 (3 rooms to move through)]
[go2]>north
You go north.
[Forging Society, Crucible]
Crinkled patches of metal stain the dolomite floor.  The splattering becomes more numerous and expands to form concentric circles near the room's center, where a large granite crucible hangs over a large fire.  You also see an ingot cutter, a pile of fuel, a large waste bucket and a hickory door.
Obvious exits: south.
Room Number: 9615
>
[go2]>go door
[Forging Society, East Hall]
A pair of water barrels awaits use if the forge fires should get out of control.  A thin film of white dust coats the floor and walls, likely caused from the continuous passage of heavy sleds bearing supplies to and from the forges.  You also see Forging Society Master Serric and a hickory door.
Obvious exits: southeast, west.
Room Number: 4435
[go2]>southeast
>
Serric folds his arms across his chest and says, "Hey you.  Are you smart and strong?  Ask me about careers or hobbies should you be interested in learning more about them."
>
You go southeast.
[Forging Society, Supply Stand]
Enormous piles of ore flanked by glistening ingots dwarf the crafters making purchases here.  Rope as thick as a Gor'Tog's waist hang from a trio of massive pulleys used to rearrange crates around the area.  You also see a large sign.
Obvious exits: southwest, northwest.
Room Number: 4434
>
[go2: travel time: 0:00:01]
--- Lich: go2 has exited.
[workorders]>order 11
The attendant says, "You can purchase a huge bronze ingot for 405 Dokoras.  Just order it again and we'll see it done!"
>
[workorders]>order 11
The attendant takes some coins from you and hands you a huge bronze ingot.
>
[workorders]>stow left
You put your ingot in your aqua backpack.
>
[smith]>wealth dokoras
  4 gold, 18 bronze, and 10 copper Dokoras (4,190 copper Dokoras).
>
[smith]>inv search flask of oil
You rummage about your person, looking for something...

  Your oil is in a rugged aqua backpack.

Roundtime:  4 secs

[Type INVENTORY HELP for more options]
>
[smith]>tap anvil
...wait 1 seconds.
>
[smith]>tap anvil
I could not find what you were referring to.
>
--- Lich: go2 active.
[go2: ETA: 0:00:00 (3 rooms to move through)]
[go2]>southwest
You go southwest.
[Forging Society, East Hall]
This long corridor lined with soot-stained carpet reverberates with the whine of grinding steel.  Workers hurry back and forth to resupply at the stand to the northeast.  You also see an oak door.
Obvious exits: northeast, west.
Room Number: 4432
>
[go2]>go door
[Forging Society, Crucible]
A central cavity splits the ceiling and metal tubing funnels smoke away from the glowing fire.  A granite crucible scarred with use rests atop a forked beam next to the fire.  Black scrapes along the ground lead over to a circular pile of fuel in the corner.  You also see an ingot cutter, an oak door and a large waste bucket.
Obvious exits: north.
Room Number: 9617
>
[go2]>north
You go north.
[Forging Society, Forge]
Blocks of carved basalt form an octagonal forge surrounding shallow pits containing piles of fuel.  A steel anvil butts up against, and peeks over the heavily chipped blocks.  An assortment of metal molds and attachments for the anvil hang from the wall.  You also see a grindstone and a large waste bucket.
Also here: Outfitting Guru Maci.
Obvious exits: south.
Room Number: 9618
>
[go2: travel time: 0:00:01]
--- Lich: go2 has exited.
--- Lich: go2 active.
[go2: ETA: 0:00:01 (6 rooms to move through)]
[go2]>south
You go south.
[Forging Society, Crucible]
A central cavity splits the ceiling and metal tubing funnels smoke away from the glowing fire.  A granite crucible scarred with use rests atop a forked beam next to the fire.  Black scrapes along the ground lead over to a circular pile of fuel in the corner.  You also see an ingot cutter, an oak door and a large waste bucket.
Obvious exits: north.
Room Number: 9617
>
[go2]>go door
[Forging Society, East Hall]
This long corridor lined with soot-stained carpet reverberates with the whine of grinding steel.  Workers hurry back and forth to resupply at the stand to the northeast.  You also see an oak door.
Obvious exits: northeast, west.
Room Number: 4432
>
[go2]>northeast
You go northeast.
[Forging Society, Supply Stand]
Enormous piles of ore flanked by glistening ingots dwarf the crafters making purchases here.  Rope as thick as a Gor'Tog's waist hang from a trio of massive pulleys used to rearrange crates around the area.  You also see a large sign.
Obvious exits: southwest, northwest.
Room Number: 4434
>
[go2]>northwest
You go northwest.
[Forging Society, East Hall]
A pair of water barrels awaits use if the forge fires should get out of control.  A thin film of white dust coats the floor and walls, likely caused from the continuous passage of heavy sleds bearing supplies to and from the forges.  You also see Forging Society Master Serric and a hickory door.
Obvious exits: southeast, west.
Room Number: 4435
>
[go2]>go door
>
[Forging Society, Crucible]
Crinkled patches of metal stain the dolomite floor.  The splattering becomes more numerous and expands to form concentric circles near the room's center, where a large granite crucible hangs over a large fire.  You also see an ingot cutter, a pile of fuel, a large waste bucket and a hickory door.
Obvious exits: south.
Room Number: 9615
>
[go2]>south
You go south.
[Forging Society, Forge]
An octagonal forge situated in the room's center emits a ruddy glow illuminating the basalt blocks framing it.  In the corner, a large grindstone casts a gigantic shadow upon the wall, and wisps of steam rise up from the recently used slack tub and anvil.  You also see a pile of fuel and a large waste bucket.
Obvious exits: north.
Room Number: 9616
>
[go2: travel time: 0:00:02]
--- Lich: go2 has exited.
[smith]>look on anvil
The anvil's surface looks clean and ready for forging.
>
--- Lich: forge active.
[forge]>get my blacksmithing book
You get a book of journeyman blacksmithing instructions from inside your aqua backpack.
>
[forge]>turn my book to chapter 3
You turn your book to chapter 3, entitled "Engineering Tools".
>
[forge]>read my book
              -=    Chapter 3 : Engineering Tools    =-

 Page 1: a short metal drawknife                 Page 14: a metal curved wood saw
 Page 2: some short metal chisels                Page 15: a metal curved bone saw
 Page 3: a long metal drawknife                  Page 16: some curved metal pliers
 Page 4: a metal straight wood saw               Page 17: a coarse metal rasp
 Page 5: a metal straight bone saw               Page 18: some sturdy metal chisels
 Page 6: a thin metal rasp                       Page 19: some curved metal rifflers
 Page 7: some square metal rifflers              Page 20: some reinforced chisels
 Page 8: some long metal chisels                 Page 21: a sharpened metal drawknife
 Page 9: a flat metal shaper                     Page 22: a metal slender wood saw
 Page 10: some plain metal pliers                Page 23: a metal slender bone saw
 Page 11: some squat metal rifflers              Page 24: some rough metal pliers
 Page 12: a rough metal wood shaper              Page 25: a textured metal rasp
 Page 13: a sturdy metal drawknife               
>
[forge]>turn my book to page 13
You turn your book to page 13, instructions for crafting a sturdy metal drawknife.
>
[forge]>study my book
You review the sturdy drawknife instructions and confidently discern most of the design's minutiae.
You now feel ready to begin the crafting process.
Roundtime: 10 sec.
>
[forge]>put my book in my backpack
You put your book in your aqua backpack.
>
[forge]>get my bronze ingot
You get a bronze ingot from inside your aqua backpack.
>
[forge]>put my ingot on anvil
You put your ingot on the iron anvil.
>
[forge]>get my ball-peen hammer
You get a steel ball-peen hammer from inside your aqua backpack.
>
[forge]>get my tongs
You get some covellite box-jaw tongs from inside your aqua backpack.
>
[forge]>pound ingot on anvil with my hammer
Following solid heating in the forge, you carefully fold the glowing red metal back onto itself and hammer it until both ends are fused.  With expert precision the metal takes shape without any faults.
Roundtime: 19 sec.
>
[forge]>pound drawknife on anvil with my hammer
Following solid heating in the forge, you carefully fold the glowing red metal back onto itself and hammer it until both ends are fused.  The work proceeds as planned and you avoid introducing any defects.

As you complete working the fire dies down and needs more fuel.
Roundtime: 19 sec.
>
[forge]>put my tongs in my backpack
You put your tongs in your aqua backpack.
>
[forge]>get my shovel
You get a steel wide shovel with a tempered finish from inside your aqua backpack.
>
[forge]>push fuel with my shovel
Sweat dripping from your face, you heap pile after pile of coal atop the fire with your shovel.  Satisfied, you lean on the shovel and wipe off your brow.
Roundtime: 12 sec.
>
[forge]>put my shovel in my backpack
You put your shovel in your aqua backpack.
>
[forge]>get my tongs
You get some covellite box-jaw tongs from inside your aqua backpack.
>
[forge]>pound drawknife on anvil with my hammer
You scoop up the drawknife with your tongs and heat it over the flames of the forge.  Once the metal is glowing hot you place it back upon the anvil and hammer it steadily with your hammer.  The work proceeds as planned and you avoid introducing any defects.

As you complete working the fire dies down and needs more fuel.
Roundtime: 18 sec.
>
[forge]>put my tongs in my backpack
You put your tongs in your aqua backpack.
>
[forge]>get my shovel
You get a steel wide shovel with a tempered finish from inside your aqua backpack.
>
[forge]>push fuel with my shovel
With wide sweeps of the shovel you scatter fuel evenly across the fire.  Then, for good measure you shovel out the spent ash into the nearby waste bucket.
Roundtime: 16 sec.
>
[forge]>put my shovel in my backpack
You put your shovel in your aqua backpack.
>
[forge]>get my tongs
You get some covellite box-jaw tongs from inside your aqua backpack.
>
[forge]>pound drawknife on anvil with my hammer
Sparks fly into the air as you transfer the drawknife back and forth between the forge fires and the anvil, alternating heating with vigorous hammering of the metal.  The forging proceeds exceptionally well and free of mistakes.

You notice the drawknife would benefit from some soft reworking.
Roundtime: 14 sec.
>
The bucket burbles suddenly as its contents begin to dissolve....

After a moment, it seems to calm down.
>
[forge]>turn drawknife on anvil with my tongs
You angle the drawknife downward along the anvil's horn with your tongs, and then gently tap it with your hammer.
Roundtime: 16 sec.
>
[forge]>pound drawknife on anvil with my hammer
Following solid heating in the forge, you carefully fold the glowing red metal back onto itself and hammer it until both ends are fused.  The work proceeds as planned and you avoid introducing any defects.
Roundtime: 16 sec.
>
[forge]>pound drawknife on anvil with my hammer
...wait 1 seconds.
>
[forge]>pound drawknife on anvil with my hammer
Following solid heating in the forge, you carefully fold the glowing red metal back onto itself and hammer it until both ends are fused.  The forging proceeds exceptionally well and free of mistakes.
Roundtime: 14 sec.
>
[forge]>pound drawknife on anvil with my hammer
You scoop up the drawknife with your tongs and heat it over the flames of the forge.  Once the metal is glowing hot you place it back upon the anvil and hammer it steadily with your hammer.  The forging proceeds exceptionally well and free of mistakes.

The metal now appears ready for cooling in the slack tub.
Roundtime: 27 sec.
>
[forge]>put my ball-peen hammer in my backpack
You put your hammer in your aqua backpack.
>
[forge]>put my tongs in my backpack
You put your tongs in your aqua backpack.
>
[forge]>push tub
An explosive blast of steam erupts from your sturdy drawknife as it hits the cool water of the slack tub!

The worked metal looks to be in need of some oil to preserve and protect it.
Roundtime: 27 sec.

You need another finished short wooden pole to continue crafting an unfinished sturdy bronze drawknife.  You believe you can assemble the two ingredients together once you acquire them.

[Ingredients can be added by using ASSEMBLE Ingredient1 WITH Ingredient2]
>code so forging work orders in shard don't grab the short poles for drawknives  D:
>
[forge]>get drawknife from anvil
You get an unfinished sturdy bronze drawknife from atop an iron anvil.
>
[forge]>get my short.pole
What were you referring to?
>
[forge]>assemble my drawknife with my short.pole
What were you referring to?
>;k forge
--- Lich: forge has exited.

**Comment by rpherbig** [comment]
Hmm, that's strange. The recipe has a short pole listed. Have you restarted dependency (including logging out/in) in a while?

**Comment by adamgoerdt** [comment]
Also, check your profiles folder and see if there's a base-crafting.yaml file there.  Delete it if it's there

**Comment by jandersson** [comment]
Closed by #2819
