### ISSUE TITLE
Add "mob long description" variable to DRInfomon

### ISSUE THREAD

**Issue by brycole** [rpherbig/dr-scripts#1410]
-Add variable parse mob long descriptions.  Current variable only parses in noun.  DRRoom.npcs
-Secondary objective - add creature adjective to YAML for target priority  #1168 

This will be needed for mob target priority when hunting and mobs have the same noun.  
e.g. dire bear and silver-backed bear.

Right now you can only check "bear" where both bears have a secondary adjective. e.g. "dire" or "silver.

**Comment by MahtraDR** [comment]
@rpherbig Looks like we can closed, as the attached PR is closed?
