### ISSUE TITLE
S'sgui Malchata - Night Time Room Numbers need adding

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#1411]
This critter was recently added.  But didn't notice the rooms changed at night.  So we need to add the following room numbers...

11001
11002
11003
11010
11017
11018
12127
12132
12128
12129

Also, Remove 10996 - nothing spawns in this room.

ORIGINAL POST BELOW:

S'sgui malchata - https://elanthipedia.play.net/S%27sugi_malchata

Rank 500-700 according to the hunting ladder.

Roomnumbers:

10995
10996
10997
10998
11000

**Comment by intangibles** [comment]
@intangibles

I'm in the process of merging these rooms but gotta wait for day/night cycle again.

**Comment by MahtraDR** [comment]
@wscherer420 Is this still a thing? I can add these if they are.

**Comment by MahtraDR** [comment]
@rpherbig Close?
