### ISSUE TITLE
Shield DESCRIPTION ADDITION

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1416]
[combat-trainer]>cast
You gesture.
Your cambrinth armband emits a loud *snap* as it discharges all its power to aid your spell.
Your latent Shield of Light spell dissipates.
A fiery blaze covers your shield arm like a vambrace of solid sunlight.
>
[combat-trainer]>wear shield
Wear what?
(You can also WEAR LEFT or WEAR RIGHT)
>
You feel fully rested.
>
*[combat-trainer: *** No match was found after 15 seconds, dumping info]*

**Comment by rpherbig** [comment]
Could you elaborate on this? The issue title says `sleep description addition`, but the problem appears to be a failed match on `wear shield`.

My guess is that since Shield of Light went to your arm after casting, you don't actually need to `wear shield`.

**Comment by Aurayn** [comment]
ye should have said Shield...... it needs to get  added to base spells is my understanding

**Comment by rpherbig** [comment]
That is not part of base spells, you probably have 'wear shield' in your
YAML

**Comment by rpherbig** [comment]
@Aurayn Any update on this?

**Comment by Aurayn** [comment]
ooops sorry just seeing this, yes you have to WEAR SHIELD after the cast. I put it in my orb like my other clerics, so its a non issue for me now. We can close this if you like.
