### ISSUE TITLE
Crafting belts, need more categories

### ISSUE THREAD

**Issue by brycole** [rpherbig/dr-scripts#1420]
I use a carpenters belt for shaping and an engineering belt for carving, but cannot put both belts under engineering. Instead I have to edit the YAML to swap belts when I'm doing carving/shaping.

Solution would be to break engineering belt into separate categories.

-carving_belt
-shaping_belt
-engineering_belt

etc.

**Comment by MahtraDR** [comment]
Closing this. It's a bit awkward to close after so much time has passed, but having polled users on Discord, I couldn't find one who'd use this functionality today...
