### ISSUE TITLE
Picking Script - should pick quick when locksmith is locked

### ISSUE THREAD

**Issue by brycole** [rpherbig/dr-scripts#1421]
Picks doesn't change picking speed when locksmithing is mindlocked.

Ideally one would pick "blind" when getting exp and then if a lock is easy enough, pick quick instead.  
Or, add in some option to speed pick when clearing boxes w/o exp as a goal.

**Comment by wstampley** [comment]
With picking only granting xp on success, I think this can be closed (as spamming pick blind just wastes time). @rpherbig
