### ISSUE TITLE
Allow crossing-training workorders to use Carving

### ISSUE THREAD

**Issue by intangibles** [rpherbig/dr-scripts#1423]
When I activate workorders via crossing training, there is an error in asking for jobs.

> [workorders]>ask Talia for challenging shaping work
> Talia shuffles through some notes and says, "Alright, this is an order for a footman's bow. I need 4 of superior quality, made from any material and due in 245 roisaen.  Please complete the items, bundle them with your logbook and then give me the logbook to complete this order.  Good luck!"
> You seem to recall this item being somewhere in chapter 4 of the instruction book.

When I activate workorders manually via
;workorders carving. it works as normal

> [workorders]>ask Talia for challenging carving work
> Talia shuffles through some notes and says, "Alright, this is an order for an articulated stone belt. I need 2 of superior quality, made from any material and due in 95 roisaen.  Please complete the items, bundle them with your logbook and then give me the logbook to complete this order.  Good luck!"
> You seem to recall this item being somewhere in chapter 4 of the instruction book.

**My YAML**
```
train_workorders:
  - carving
work_order_disciplines:
  - carving
carving_workorder_material_type: bone
workorder_min_items: 1
workorder_max_items: 10
workorder_recipes:
  carving:
  - a bone crown
```

**Comment by rpherbig** [comment]
`;crossing-training` will only train Engineering (workorders) with Shaping.

**Comment by rpherbig** [comment]
Does `;validate` report anything?

**Comment by intangibles** [comment]
Well, if ;crossing-training is somehow hardcoded to use shaping then I guess then this would turn into a feature request,  ";workorders carving" uses the YAML i have listed above just fine.

**Comment by rpherbig** [comment]
If I recall correctly (and @rcuhljr might know more), you run out of good Carving recipes with which to train at some point, whereas Shaping is easy to train at any rank.

**Comment by intangibles** [comment]
I'm fairly certain bone is the absolute best.   It's far lighter then wood and you can buy it from the store.  
Deer 60 workability - 3.3 stone per deer bone
Wolf 55 workability - 3 stone per deer bone

It also doesn't require any additions or extra items.

Plus you can bring a bunch of bones with you on your person and not need to be at the engineering hall.   Lumber not so much. It's a lot heavier.  

10 balsa lumber - 600 stone

a <bone> crown	Master	09- Intricate	Decorative Bone Carving	3 pieces	
a <bone> comb	Master	10- Difficult	Decorative Bone Carving	2 pieces	
a <bone> haircomb	Master	11- Very Difficult	Decorative Bone Carving	3 pieces

**Comment by skyleronken** [comment]
I recommend closing this and either creating a new ticket or just leave workorders to use shaping as the means for training engineering.
