### ISSUE TITLE
Astrology.lic with cyclic

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#1426]
When running astrology script, there is no check to make sure cyclic was actually released before being astral plane walk section which will cause the script to hang when it attempts to moongate.

--- Lich: bescort active.

[bescort]>recall heavens grazhir

You know the names of:
  Asharshpar'i
  Dinegavren
  Mintais
  Rolagi
  Dor'na'torna
  Marendin
  Tamigen
  Taniendar
  Erekinzil
  Tabelrem
  Auilusi
  Besoge
  Vellano
Roundtime: 2 sec.
R> 
[bescort]>release SOV

**...wait 2 seconds.**
R> 
You feel fully rested.
R> 
[bescort]>prepare mg 5

That won't affect your current attunement very much.

You raise your head skyward, chanting the equation of the Moongate spell.

**Comment by jandersson** [comment]
I think this might be fixable by changing `release_cyclics` to use `bput` instead of `fput`. Is the release messaging always the same?

**Comment by jandersson** [comment]
Actually im pretty sure SLS and SOV have different release messages... so maybe bput won't be such a great solution.

**Comment by mwest152** [comment]
Not sure what you do to make it try again if it gets a ...wait or type ahead warning.   But I assume that's all that would be needed.

**Comment by jandersson** [comment]
I believe `bput` does this
