### ISSUE TITLE
;combat-trainer not using spare gem pouches, ;sell-loot doesn't sell full pouches

### ISSUE THREAD

**Issue by reithir** [rpherbig/dr-scripts#1437]
Sorry, this issue has sort of two related issues:

1) ;combat-trainer correctly removes a full pouch, stores it in the storage container and pulls a new gem pouch from "spare_gem_pouch_container" but doesn't run a new "store gem <gem_pouch_adjective> pouch" so it just starts storing the gems in my default storage container.

2) ;sell-loot doesn't check for or pull full gem pouches from the storage container, just the one you're wearing so you have to run sell-loot several times.

Are 1 and 2 working as they should be? It seems a little illogical to me, any chance these could be changed? Or if I'm doing something wrong, let me know? thanks!

**Comment by skyleronken** [comment]
1) your issue has to do with the adjective f the gem pouch you define in your yaml, and the gem pouch you ask for from the gem merchant. Make sure they match and get rid of any that don't meet that.

2) assuming these are untied pouches, right?

**Comment by reithir** [comment]
Thanks Skyler. I only ever set "gem_pouch_adjective", is there another gem pouch setting? All of the pouches I have on my person are "gem" pouches "gem_pouch_adjective: gem". This problem seems to happen while hunting, it's not an interaction with a gem merchant, although I didn't realize it tries to ask for a new one, I just have a bunch on me. I can get rid of them if that will help though.

And yes, untied pouches, just the way ;combat-trainer leaves them.

**Comment by skyleronken** [comment]
There isnt a different setting. the gem_pouch_adjective is something like "dark", "red", etc. 

Then, when you get the gem pouch from the NPC, you need to say "ask <NPC> for dark gem pouch"

If you ask for a different pouch than is set in your yaml adjective, then you will have the issues you are experieincing.

**Comment by reithir** [comment]
Ahh interesting, I was using that setting incorrectly all this time then, my gem pouches can be addressed as "gem pouch" so that's the adjective I used, but that obviously doesn't work. I'll change it to "dark" and store all my gem pouches and see how that goes. I vaguely remember I had trouble asking for certain color pouches from some appraisers, do you know anything about it? I'll have to test out and see. Thanks!

**Comment by skyleronken** [comment]
i think we can close this issue
