### ISSUE TITLE
Graceful exit command

### ISSUE THREAD

**Issue by Onbusi** [rpherbig/dr-scripts#1438]
I would like a "graceful exit" to be added.  A command that will finish what it is currently doing (crossing-repair/workorders/athletics/etc.) and then exit the training-manager.  This way you can exit or stop training-manager without stopping in the middle of getting your items repaired or halfway through a workorder, or have to wait until your hunt is over to exit, etc.

I've seen a trading script that did this when I ran Genie, before starting a new section of the script it would check a variable, if it was 0 it would move to the next section, if it was 1, it would go and feed and stable your carriage then stop.  When you were ready to exit you just changed the variable by inputting a command var set stop 1 or something similar.

**Comment by MahtraDR** [comment]
@Onbusi Are you able to test this? See linked commit above, copying the code used in t2 into training-manager

**Comment by Kiriawen** [comment]
@MahtraDR I know that there are still folks out there who use Training-manager but it is getting a bit long in the tooth.  I know most folks who I interact with on Discord are using T2 or are just running scripts as one offs.  

As T2 does have this behaviour for the vast majority of situations I would say this one is safe to close.

**Comment by MahtraDR** [comment]
I'm torn on closing this, because it's also an easy first issue for someone who wants to work on it. The code from t2 would fit here almost as is.

**Comment by MahtraDR** [comment]
Closing as stale, and nobody's stepped up.
