### ISSUE TITLE
;pick <qty>

### ISSUE THREAD

**Issue by Onbusi** [rpherbig/dr-scripts#1439]
I like to do - pick in my before and after hunt, but if I put stop_lockpicking_on_mindlock: true I will fill up my packs and leave boxes on the ground after <6hrs.  If I put it to false, I will only run ;pick after I get back from the hunt because it will use up all the boxes.  I'd like pick to either be able to specify a quantity of boxes to be picked or if it could locally override the mindlock variable, either way would work for what I'm trying to accomplish.

**Comment by MahtraDR** [comment]
@Onbusi would you still use this today?

**Comment by Onbusi** [comment]
I don't have an active account right now. I still think it is good
programming to have this in there, so the user could stop and start the
script with another script. My idea was to use it with a timer to log off
after a certain amount t of play time.

**Comment by MahtraDR** [comment]
Fair enough. In theory it's not too hard. I'll look into this.

**Comment by Kiriawen** [comment]
@MahtraDR Bump.  it's been 12 months.

**Comment by MahtraDR** [comment]
Closing as no others have expressed interest since.
