### ISSUE TITLE
combat-trainer setting stance to 0 80 100 while using bow

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#144]
Below are my combat-setup stances and a log of the issue happening(see second STANCE SET)
The default ranged stances are still in place(all evasion shield)

    CombatVars.stances = {
      'Brawling' => %w(evasion shield),
      'Small Edged' => %w(evasion shield),
      'Twohanded Edged' => %w(evasion parry),
      'Heavy Thrown' => %w(evasion parry),
      'Polearms' => %w(evasion shield),
      'Staves' => %w(evasion shield),
      'Offhand Weapon' => %w(evasion parry),
      'Light Thrown' => %w(evasion parry),
      'Small Blunt' => %w(evasion shield)
    }

[combat-setup]>get allarh
You pick up the allarh lying at your feet.
>
[combat-setup]>stow my allarh
You put your allarh in your leather baldric.
>
[combat-setup]>get my first bow
You get a Nisha short bow from inside your leather baldric.
>
[combat-setup]>stance set 80 0 100
Setting your Evasion stance to 80%, your Parry stance to 0%, and your Shield stance to 100%.  You have 0 stance points left.
>
[combat-setup]>load
Your cougar-hide targe makes the task more difficult.
You reach into your baldric to load the Nisha short bow with a boar-tusk arrow.
Roundtime 3 sec.
>
The wild boar closes to melee range on you!
>
* As if effort and skill were a bad thing, a wild boar charges wide at you.  You evade, leaping aside.  
[You're winded, nimbly balanced and in better position.]
>
* With pathetic timing, a wood troll feints to the side at you.  You partially block with a reinforced cougar-hide targe.  
[You're winded, nimbly balanced and have slight advantage.]
>
[combat-setup]>stance set 0 80 100
Setting your Evasion stance to 0%, your Parry stance to 80%, and your Shield stance to 100%.  You have 0 stance points left.
>
[combat-setup]>maneuver powershot
You square up your feet and arch your back while searching for an engaged enemy to target.
>
A musk hog hisses viciously and lunges at you!
* A musk hog claws, swiping with its hooves at you.  You barely block with a reinforced cougar-hide targe.  
[You're winded, nimbly balanced and in better position.]
>
With a loud twang, you let fly your arrow!

Your errant arrow results in nothing more than a soft thud against a wood troll's .
The boar-tusk arrow lands nearby!
>
* With the speed and temerity of a swooping falcon, a wild boar charges at you.  You fail to block with a reinforced cougar-hide targe.  The body lands a light hit (1/23) to your left hand.
[You're bruised, winded, nimbly balanced with no advantage.]
>
* Driving in with naturally fluid movements, a wood troll bashes a war club at you.  You fail to block with a reinforced cougar-hide targe.  The club lands a light hit (1/23) to your chest.
[You're bruised, winded, nimbly balanced and opponent has slight advantage.]
>
[combat-setup]>stow arrow
You pick up a boar-tusk arrow.
You put your arrow in your leather baldric.
>
[combat-setup]>load
Your cougar-hide targe makes the task more difficult.
You reach into your baldric to load the Nisha short bow with a boar-tusk arrow.
Roundtime 3 sec.
>
A musk hog hisses viciously and lunges at you!
* Moving well, a musk hog claws, swiping with its hooves at you.  You barely fail to block with cougar-hide targe.  The claw lands a light hit (1/23) to your chest.
[You're bruised, winded, nimbly balanced and in better position.]
>
* With the speed and temerity of a swooping falcon, a wild boar charges at you.  You fail to block with a reinforced cougar-hide targe.  The body lands a glancing (0/23) blow to your right leg.
[You're bruised, winded, nimbly balanced with opponent in good position.]
>
You begin to target a wood troll.
>
[combat-setup]>bob
You bob suddenly, lowering yourself into a smaller target.
[You're bruised, winded, nimbly balanced and have slight advantage.]
Roundtime: 4 sec.
>
The wood troll moves into a position to parry.
>
A musk hog hisses viciously and lunges at you!
* A musk hog leaps, bellowing wildly, its teeth bared in rage at you.  You barely block with a reinforced cougar-hide targe.  
[You're bruised, winded, nimbly balanced and in better position.]
>
[combat-setup]>hide
You melt into the background, convinced that your attempt to hide went unobserved.
Roundtime: 6 sec.
>
The wild boar searches around for a moment.
>
The wood troll searches around for a moment.
>
A musk hog sniffs at the air, its nose twitching nervously.
>
[combat-setup]>shoot
You come out of hiding.
Your attempt is slightly hindered by your cougar-hide targe.
< Moving in gracefully, you fire a boar-tusk arrow at a wood troll.  A wood troll fails to evade.  The arrow lands a heavy strike (7/23) to the troll's right arm.

The boar-tusk arrow lodges itself shallowly into the wood troll!
[You're bruised, winded, nimbly balanced and in better position.]
[Roundtime 1 sec.]
>
[combat-setup]>load
Your cougar-hide targe makes the task more difficult.
You reach into your baldric to load the Nisha short bow with your last boar-tusk arrow.
Roundtime 3 sec.
>
[combat-setup]>aim
You begin to target a wood troll.
>
[combat-setup]>bob
You bob suddenly, lowering yourself into a smaller target.
[You're bruised, nimbly balanced and in very strong position.]
Roundtime: 4 sec.
>
You are unable to maintain your focus on the shadows around you, and your knowledge of better hiding places subsides.
>
* A wild boar bites at you.  You barely block with a reinforced cougar-hide targe.  
[You're bruised, nimbly balanced and have slight advantage.]
>
[combat-setup]>hide
You melt into the background, convinced that your attempt to hide went unobserved.
Roundtime: 6 sec.
>
A musk hog sniffs at the air, its nose twitching nervously.
>
Your concentration fails, and you feel your body perceptibly slow.
>
The wild boar searches around for a moment.
>
The wood troll searches around for a moment.
>
[combat-setup]>shoot
>
You come out of hiding.
Your attempt is slightly hindered by your cougar-hide targe.
< Moving fluidly, you fire a boar-tusk arrow at a wood troll.  A wood troll fails to evade.  The arrow lands a hard hit (5/23) that painfully mashes several toes of the left foot.

The boar-tusk arrow lodges itself shallowly into the wood troll!
[You're bruised, nimbly balanced and in good position.]
[Roundtime 1 sec.]
>
[combat-setup]>stow my bow
You put your bow in your leather baldric.
>
[combat-setup]>get my first fan
You get a steel thin-bladed fan from inside your leather baldric.
>
[combat-setup]>stance set 100 0 80
Setting your Evasion stance to 100%, your Parry stance to 0%, and your Shield stance to 80%.  You have 0 stance points left.
>
[combat-setup]>maneuver twirl
>
You take a step back and set your fan into a twirling motion.
>
You angle the twirling fan down upon a wood troll!

Your errant fan results in nothing more than a soft thud against a wood troll's .

[You're bruised, nimbly balanced and in good position.]
Roundtime: 8 sec.
>
A musk hog hisses viciously and lunges at you!
* Apparently without direction or thought, a musk hog claws, swiping with its hooves at you.  You block with a reinforced cougar-hide targe.  
[You're bruised, nimbly balanced and in very strong position.]
>
* As if fumbling muscle flab were natural, a wild boar bites at you.  You dodge, stepping clear of danger.  
[You're nimbly balanced with no advantage.]
>
The wood troll moves into a position to dodge.

**Comment by rpherbig** [comment]
Note that the syntax you have for CombatVars.stances is OVERWRITING, not APPENDING to the hash. My theory here is that the defaults are being overriden, meaning the script will use whatever stance is best for training.

To append, the syntax you want in your character-specific method is:
```
CombatVars.stances['Brawling'] = %w(evasion shield)
...
CombatVars.stances['Small Blunt'] = %w(evasion shield)
```

Give that a try and let me know how it goes.

**Comment by rpherbig** [comment]
@OdnaZvezda have you had a change to try this out?

**Comment by OdnaZvezda** [comment]
Yes, it's working now with skill specific stances.  I'll go ahead and close this
