### ISSUE TITLE
Before and After - Performance not working

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1441]
[hunting-buddy: ***STATUS*** EXECUTE performance]
[hunting-buddy: *** Failed to find performance ***]
[hunting-buddy: *** Please report this to Etreu, Sheltim, or

**Comment by rpherbig** [comment]
Do you have a script named performance?

**Comment by Aurayn** [comment]
Nope

**Comment by rpherbig** [comment]
That's your problem. It's trying to find a script with that name.
