### ISSUE TITLE
Kill Counter

### ISSUE THREAD

**Issue by izawwlgood** [rpherbig/dr-scripts#1444]
I envision something that when activated simply scores the number of times the script enters LOOT. It can store this as a variable that can be recalled. If it can include a time stamp, ossim. 

Something like ;kill-counter start
Let it run for 20m
;kill-counter stop
;kill-counter list

**You killed 4 billion critters! 
**Started 4:00
**Finished 4:20

If the timestamp cant be added, that's also fine.

**Comment by skyleronken** [comment]
it would be easier to put this into combat-trainer or even hunting-buddy. Any specific reason why you want this to be a standalone?

**Comment by izawwlgood** [comment]
I suppose I'd prefer combat-trainer then - i'd want to be able to start up a routine in a given area, and just let it run for x minutes, and then see how many kills occurred in that period of time. I'm not sure how well that would play with hunting-buddy? Presumably fine so long as the counter reset was just something you activated manually?

So, no, no reason for it to be a standalone!

**Comment by skyleronken** [comment]
decided to do it like a monitor instead of what we discussed. This will be cleaner since it will exist outside of any existing scripts and be easier to reference without it getting stuck in the scroll.

**Comment by izawwlgood** [comment]
Mechanically I suppose something like ;scroll-list might be good too - you run it, it counts the number of times you output LOOT, and then you can do something like ;killcounter count and it spits out a number at you, or, ;killcounter reset and it sets the counter back to zero.

Is this ready for testing>

**Comment by skyleronken** [comment]
I can do that, but I think lets wait a few weeks to see what folks want to do. I may expand it to track additional hunting related data. Its good to go right now.
