### ISSUE TITLE
Genie Room Numbers

### ISSUE THREAD

**Issue by MidnightCat77** [rpherbig/dr-scripts#1445]
I would love to see a feature where you can see Genie room numbers in addition to Lich room numbers.

**Comment by skyleronken** [comment]
Honestly, doesn't sound like a Lich thing to me. You can modify your genie windows to display the genie room number.

**Comment by MidnightCat77** [comment]
Oh, I don't have Genie. I meant as a Lich user, since a good portion of the population use Genie still.

**Comment by skyleronken** [comment]
i dont really see the point in this. Why would you need Genie room numbers if you don't use Genie?

**Comment by MidnightCat77** [comment]
Okay, for instance. I have a friend named Bob. Bob has Genie. I want to hang out with Bob and I am currently in a wooded area away from a city. I can't tell Bob what room number I'm in since I have Lich and he doesn't since he has Genie room numbers.

**Comment by MahtraDR** [comment]
@rpherbig Close? Genie's open source now. Someone can create this functionality if they really want to, but this is years old now.
