### ISSUE TITLE
Skinning not reactivating after 'cannot be skinned' (combat trainer)

### ISSUE THREAD

**Issue by brycole** [rpherbig/dr-scripts#1446]
Skinning turns off when hunting young ogres, but does not turn back on when using a -back file for rock trolls.

[combat-trainer]>arrange for skin
The ogre cannot be skinned, so you can't arrange it either.
[combat-trainer]>loot

```
Lines 426-429
      when 'cannot be skinned'
        game_state.unskinnable(mob_noun)
        break
      when 'That creature cannot'
```

It technically shouldn't be turning it off for rock trolls since trolls are a different mob noun, but unsure why.

```
  def arrange_mob(mob_noun, game_state)
    return unless @skin
    return unless @arrange_count > 0
    return unless game_state.skinnable?(mob_noun)
    return if game_state.casting_consume || game_state.prepare_consume

```

My work around will be to disable skinning in YAML and renable in the back file.  But something doesn't seem to be working right here.

Thanks!

**Comment by MahtraDR** [comment]
@rpherbig Can close this. The checks today are much more robust than they were in 2017.
