### ISSUE TITLE
Shaping and other crafts in ;crossing-training

### ISSUE THREAD

**Issue by reithir** [rpherbig/dr-scripts#1449]
I've just started using the shaping option for my ;crossing-training routine and I feel like every time the skill gets a little bit below 34/34, it immediately grabs another workorder and then makes two or three bows, and most of that time of course is spent when the skill is back locked. Is this by design, or is there a setting I can wait to tell ;crossing-training to wait until I'm down to like 5/34 before going to grab another workorder (similar logic to going back to hunt maybe)? I just feel like I spend a lot of my town training time grinding on work orders and wasting time and materials when my engineering skill is already locked. Any ideas, or anyone else notice this?

**Comment by rcuhljr** [comment]
Honestly it sounds like you're letting crossing-training too long? That would only occur if you had all your other skills at like 25+ already in crossing training since it always picks the lowest. If you still want a work around for this you can just set a longer exp timer on Engineering in your yaml so it won't try to train shaping again too often.

**Comment by reithir** [comment]
Ah understood, thanks for the advice. I checked my yaml again and it looks like I just don't have enough stuff, maybe I should just add more things to give crossing-training more things to do. That's good to know it always moves on to the lowest field experience thing. I'll tinker, probably no need to try to do a workaround, just need to balance what my yaml does. thanks!

**Comment by skyleronken** [comment]
@reithir does this still need an issue or was it a configuration thing?

**Comment by reithir** [comment]
hi skyler, I got it figured out, it was mostly configuration thing on my part. I think it's good to go, thanks for discussing. issue can be closed!
