### ISSUE TITLE
Add assess_teach and check_listening to common

### ISSUE THREAD

**Issue by brycole** [rpherbig/dr-scripts#1450]
I think it would be a good idea to assess_teach and check_listening methods to common (or some form of them). I pulled them from crossing-training and stripped some stuff out to make them work in a before: script.

It should allow a bit more leverage for other scripts and anyone who is creating a training method outside crossing-training.

```
 def assess_teach
    case DRC.bput('assess teach', 'is teaching a class', 'No one seems to be teaching', 'You are teaching a class')
    when 'No one seems to be teaching', 'You are teaching a class'
      waitrt?
      return {}
    end
    results = reget(20, 'is teaching a class')
    waitrt?

    results.each_with_object({}) do |line, hash|
      line.match(/(.*) is teaching a class on (.*) which is still open to new students/) do |match|
        teacher = match[1]
        skill = match[2]
        # Some classes match the first format, some have additional text in the 'skill' string that needs to be filtered
        skill.match(/.* \(compared to what you already know\) (.*)/) { |m| skill = m[1] }
        hash[teacher] = skill
      end
    end
  end


  def check_listening
    return if DRRoom.pcs.empty?
    classes = assess_teach
    @last_teacher = classes
                    .reject { |t, s| t.nil? || s.nil? }
                    .sort_by { |_t, s| [DRSkill.getxp(s), DRSkill.getrank(s)] }
                    .find { |t, _s| DRC.listen?(t) }
                    .first

    @listen_timer = @last_teacher ? nil : Time.now
  end

```

**Comment by skyleronken** [comment]
@intangibles trying making a fork, branch, and test against dependent scripts. If it works fine, submit it as a PR and lets get it committed!

**Comment by intangibles** [comment]
Will do! I don't quite know how to fork or branch yet, bit of a learning curve still with GIT still.

**Comment by jandersson** [comment]
Just as an update, `assess_teach` was moved to `common`. But `check_listening` is still in `crossing-training`

**Comment by MahtraDR** [comment]
@asechrest Would you be keen on this one?

**Comment by MahtraDR** [comment]
I initially started looking into adding check_listening and have since decided against it. This issue is five years old now and we couldn't think of a good use case for this today. 

Closing.
