### ISSUE TITLE
Stealing Issue

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#1455]
There is an issue with pelt potion, and pelt lotion from Dirge, Tromlyn's Tannery.  Basically any drop or stow command needs to be done twice, not sure why.  

ROOM: 19475
  id: '341'
  item: pelt potion
  id: '342'
  item: lotion

I can skip these locally, but either these should be removed, or a fix put in.  I was thinking maybe something similar to whatever we do to drop instruments that take 2 commands to drop.  Here is a log of what it looks like.  If you try to put it in your pack a second time, or drop it, it will work.  

```
[steal]>put my pelt potion in my backpack

You come out of hiding.
Something appears different about the lotion, perhaps try doing that again.
```

**Comment by rpherbig** [comment]
Does it keep the item in hand when you get that message?

**Comment by mwest152** [comment]
It does keep the item in hand.

**Comment by Kiriawen** [comment]
@MahtraDR No idea if this is still an issue or not.  I'm not aware of anyone who still utilizes the steal script and I know that updates for that script are virtually none at this point.  

My suggestion would be for the person with the issue to utilize the Burgle script for training purposes and we can call this one closed.

**Comment by MahtraDR** [comment]
Agreeing with @Kiriawen here. I don't know anyone using the stealing script today. We all use burgle to train. Closing.
