### ISSUE TITLE
support gathering

### ISSUE THREAD

**Issue by hwoo79** [rpherbig/dr-scripts#146]
need a script for gathering (mining,logging)

**Comment by hwoo79** [comment]
Talked with Torgro earlier today about mining; he asked for a log if I had a chance.  Here is an example of clearing out a node with some danger abatement.

[mining-log.txt](https://github.com/rpherbig/dr-scripts/files/96654/mining-log.txt)

**Comment by rpherbig** [comment]
That log implies you already have a mining script (named `mine`? and another called `danger`?). Is that something you'd be willing to add to the repo?

**Comment by rpherbig** [comment]
Mining is in a functional, but not ideal place. `Mine.lic` needs to be replaced (partial work is in `mine2.lic`).

Also, `mining-buddy` should have the bput/reget logic replaced with Flags.
