### ISSUE TITLE
Theurgy Script Pool Bug

### ISSUE THREAD

**Issue by Sephroc** [rpherbig/dr-scripts#1465]
Whenever you look while in the dark pool while taking a ritual bath it makes you go out. Which sucks cause if you haven't had to your vision yet you dont get the boost to your devotion.

>l
>
[A Dark Grove, A Deep Pool]
The sand below your feet is soft as silk and as black as the night about you.  The waters are colder than death, causing you to shake violently.  A deep stillness enfolds the obsidian waters, which seem to close about your body like enveloping folds of the thickest onyx velvet.  
Also here: Treasure Seeker Embrace.
Obvious paths: out.
>
[theurgy]>out
The infusion of herbs and water drip off you as you exit the pool.
You go out.
[Near Kaerna Village, A Dark Grove]
Around you grow trees in a circle so even and perfect they warrant suspicion.  In the center of the grove is a deep pool, its surface smooth and glassy, undisturbed by the wind.  Peering into it, it takes you a moment to realize that your face is not reflected in the pool and another to realize that neither are the trees.  In fact, the only thing that can be seen are stars -- thousands and thousands of endless stars, some of which you know you have never seen in the sky above you.  You also see a black obsidian altar with a rough obsidian bowl on it and a dirt path.
Obvious paths: none.
Room Number: 11690
>
[theurgy]>remove badge
You take off a pilgrim's badge.
>

**Comment by Sephroc** [comment]
Also in the script it makes a TON of holy oil for some reason, not sure why this is. I'm loaded up for a months worth of Theurgy on just that haha

**Comment by MahtraDR** [comment]
This doesn't happen amymore. I just tested on mine (I have weeks worth of logs showing this not happening too)
