### ISSUE TITLE
Rituals not being used in combat-trainer if Thanatology is locked

### ISSUE THREAD

**Issue by Morzain** [rpherbig/dr-scripts#1476]
The dissect ritual trains first aid as well as thanatology.
The harvest ritual trains skinning as well as thanatology.

Ideally combat-trainer would keep using rituals until the both skills are locked (or have options for deciding this). Currently I have it setup to stop combat  when first-aid is locked but this never happens as it stops using rituals once Thanatology is locked.

**Comment by intangibles** [comment]
I pushed some changes which cover this issue. See pull request #1563.
