### ISSUE TITLE
Harvest material storage is missing 'flawless'

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#1478]
#1462 added the ability to store high-quality harvested material.

@izawwlgood notes that 'flawless' is missing:

```
[combat-trainer]>rummage /C material my back
You rummage through a sturdy black backpack looking for something similar to "material" but there is nothing in there like that.

[combat-trainer]>glance left
You glance down to see a flawless chunk of bull material in your left hand.

[combat-trainer]>drop material
Having no further use for a flawless chunk of bull material, you discard it. The material quickly degrades into uselessness.
```

As well, the 'glance' is unncessary since the harvest action reports the quality of the material:
```
combat-trainer]>perform harvest on bull
You bend over the bull's corpse to make a few quick, precise motions with your ritual knife, focusing your thanatological insight intently in order to prepare it for harvesting. You then plunge your knife efficiently into the corpse and carve out a flawless piece of fetish material.
Roundtime: 4 sec.
```

**Comment by FluxBorn** [comment]
the logic for completing the perform was wired separately, so I didn't bother to rewrite the whole method to avoid using glance.

`result = bput(perform_message, @rituals['preserve'], @rituals['dissect'], @rituals['harvest'], @rituals['consume'], @rituals['construct'], @rituals['failures'])`

But I will add flawless.

**Comment by FluxBorn** [comment]
It was brought up to me that the logic should be modified to always try to make sure the character has the set amount of material on them if harvest store is set to true. And that this would supersede the currently YAML set thanatology method until it was full, then switch back to using the YAML set thanatology. IE user could be set to use Dissect as their preferred Thanatology, but on killing a target if they have Delete repeated word store set to true, it would check their bag and see if they were full on material. If full, it would perform Dissect as usual, if not full it would harvest.

**Comment by jandersson** [comment]
Did #1618 fix this?

**Comment by izawwlgood** [comment]
Yes!

On Jun 1, 2017 8:51 AM, "Jonas Andersson" <notifications@github.com> wrote:

Did #1618 <https://github.com/rpherbig/dr-scripts/pull/1618> fix this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rpherbig/dr-scripts/issues/1478#issuecomment-305483815>,
or mute the thread
