### ISSUE TITLE
Request for Bundles to work like gem pouches

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1485]
Ie so that the bundles remove themselves at the 200 count and start a new one. Maybe we dont need a separate storage container as it's rope vs bundle?

Also keep ropes in default container for swapping so the script doesn't run you back to crossing after every bundle is filled.

**Comment by Aurayn** [comment]
Any updates or shall I close this?

**Comment by rpherbig** [comment]
I don't think anyone is actively working on this

**Comment by MahtraDR** [comment]
@rpherbig close?
