### ISSUE TITLE
Added messaging for ammo lodged in player

### ISSUE THREAD

**Issue by izawwlgood** [rpherbig/dr-scripts#1486]
"You feel a slight pain from the crossbow bolt lodged in your chest."
Shallow lodge.

I feel, but cannot be certain, that I have also seen the messaging "You feel a twinge..." or "slight twinge"? I believe I have also seen "sharp pain" and "You wince in pain..."

I suppose it may be useful to do some lodged tests and see what diversity of messaging there is.

**Comment by jandersson** [comment]
Does #1625 fix this?

**Comment by izawwlgood** [comment]
Appears to have - i haven't had any issues with lodged stuff since!

**Comment by rpherbig** [comment]
See #1625
