### ISSUE TITLE
Can we get a duskruin rat catching script?

### ISSUE THREAD

**Issue by Caledric** [rpherbig/dr-scripts#1489]
https://github.com/rpherbig/dr-scripts/blob/master/samples/duskruin-labyrinth.cmd

Is a good script written for genie... we could use one for lich.

**Comment by jandersson** [comment]
You can close this Caledric. Though please make new issues to make the rat catcher better :]

**Comment by rpherbig** [comment]
See `dusk-labyrinth.lic`
