### ISSUE TITLE
crossing-train doesn't check for Outdoorsmasnhip mind-lock

### ISSUE THREAD

**Issue by Lazasar** [rpherbig/dr-scripts#1492]
I am collecting and kicking rocks, even when at 33

**Comment by jandersson** [comment]
Is perception in your training set?

**Comment by Lazasar** [comment]
# Non-combat settings
crossing_training:
- Summoning
- Appraisal
- Athletics
- Perception
- Attunement
- Scholarship
- Outdoorsmanship

**Comment by skyleronken** [comment]
collecting is used to perception as well. 

`
    when 'Perception'
      train_outdoorsmanship
`

If you REALLY wanted it to be separate you could add juggling or something, but training perception in combat (via Hunt)  is more effective and very easy. 

This issue can be closed.
