### ISSUE TITLE
Support a TM Focus in combat-trainer

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#1497]
Needs to be held in your hand and invoked (once) to start using. Once you attack with a weapon it deactivates. Once you stow it deactivates. You can still do `shove`, `weave`, `circle`, and the like.

It behaves like a weapon, so I wonder if listing it as a training weapon and adding an attribute to the `gear` listings would be the most appropriate. According to a GM post, these items have durability and are repaired like metal weapons too.

**Comment by izawwlgood** [comment]
I think this will also be a useful setting for people who want to not waste RT on TM/Debil only routines. For example, hold a parrying weapon, weave/shove/circle, and solely focus on their TM/Debil.
