### ISSUE TITLE
Remedy - Doesn't understand Red Flowers

### ISSUE THREAD

**Issue by m-burroughs** [rpherbig/dr-scripts#1499]
I worked on an elaborate fix to get `Red Flowers` to work inside of `;workorders`
I will work on similar logic to fix a problem with the wording inside of `;remedies` next.
See below log for context.

```
[remedy]>get remed book
You get a book of master remedy instructions from inside your red-leucro haversack.
[remedy]>turn my book to chapter 2
You turn your book to chapter 2, entitled "Simple Remedies".
[remedy]>read my book
              -=    Chapter 2 : Simple Remedies    =-

 Page 1: some blister cream                      Page 7: some mouth wash
 Page 2: some itch salve                         Page 8: some eye wash
 Page 3: some moisturizing ointment              Page 9: some hangover potion
 Page 4: some wart salve                         Page 10: some refreshment elixir
 Page 5: some stomach tonic                      Page 11: some vigor poultices
 Page 6: some lip balm                           
[remedy]>turn my book to page 6
You turn your book to page 6, instructions for crafting some lip balm.
[remedy]>study my book
You scan the lip balm instructions with a glance and comprehend all but several minor details in the text.
You now feel ready to begin the crafting process.
Roundtime: 4 sec.
Malikor closes his eyes and grows still.
[remedy]>put my book in my haversack
You put your book in your red-leucro haversack.
[remedy]>untie my mortar from my alchemist belt
Vieira roots around the area for a moment.
You remove a deep mahogany mortar with an herb garden carved around the base from your alchemist's belt.
[remedy]>get my red flower
What were you referring to?
[remedy: You seem to be missing: red flower]
--- Lich: remedy has exited.
[workorders]>get my alchemy logbook
```

**Comment by Lazasar** [comment]
--- Lich: remedy active.
[remedy]>get remed book
>
You get a book of apprentice remedy instructions from inside your traveler's pack.
>
[remedy]>turn my book to chapter 2
You turn your book to chapter 2, entitled "Simple Remedies".
>
[remedy]>read my book
              -=    Chapter 2 : Simple Remedies    =-

 Page 1: some blister cream                      Page 4: some wart salve
 Page 2: some itch salve                         Page 5: some stomach tonic
 Page 3: some moisturizing ointment              
>
[remedy]>turn my book to page 1
>
You turn your book to page 1, instructions for crafting some blister cream.
>
[remedy]>study my book
You scan the blister cream instructions with a glance and confidently discern most of the design's minutiae.
You now feel ready to begin the crafting process.
Roundtime: 5 sec.
R>
[remedy]>put my book in my pack
You put your book in your traveler's pack.
>
[remedy]>get my mortar from my pack
>
You get a green stone mortar from inside your traveler's pack.
>
[remedy]>get my red flowers
You get some dried red flowers from inside your stone mortar.
>
[remedy]>put red flowers in my mortar
You put your flowers in your stone mortar.
>
[remedy]>put my red flowers in my pack
What were you referring to?
>
[remedy]>get my mortar from my pack
What were you referring to?
>
[remedy: You seem to be missing: mortar]
--- Lich: remedy has exited.
>
[workorders]>get my alchemy logbook
You get an alchemy work order logbook from inside your traveler's pack.
>
[workorders]>bun my cream with logbook
That's not going to work.  Type BUNDLE HELP for details.
>
[workorders: *** No match was found after 15 seconds, dumping info]

**Comment by rpherbig** [comment]
Closing in favor of #1681
