### ISSUE TITLE
Investigate tags for DR maps.

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#150]
[DRPrime]-GSIV:Tillmen: "interesting_tags = [ "alchemist", "consignment", "bank", "furrier", "gemshop", "herbalist", "locksmith", "pawnshop", "town", "advguard", "advguild", "advpickup", "armorshop", "bakery", "bardguild", "boutique", "chronomage", "clericguild", "empathguild", "forge", "general store", "npccleric", "npchealer", "movers", "smokeshop", "sorcererguild", "warriorguild", "weaponshop", "wizardguild", "advguard2", "clericshop", "fletcher", "rangerguild", "sunfist", "voln", "exchange", "inn", "exchange" ]"
[DRPrime]-GSIV:Tillmen: "If anyone wants to create a separate DR list of tags, I can stick an if/else in go2 to use it."

**Comment by rpherbig** [comment]
Does he just need a list of names, it also room IDs?
