### ISSUE TITLE
goat agility course script needs conversion

### ISSUE THREAD

**Issue by Caledric** [rpherbig/dr-scripts#1507]
I don't know how to write lich scripts yet so I wrote an SF script to do the goat agility course... if someone could convert it to lichie goodness that would be great.  I know there are only a few days left in duskruin, but some folks could benefit from this.

http://pastebin.com/M65VFRt0

**Comment by jandersson** [comment]
I have a few tokens/slips left. I'll give it a go and upload the result for anyone else to tinker with!

**Comment by MahtraDR** [comment]
Closing because it's super stale. If someone wants to pick up the idea, they are welcome to.
