### ISSUE TITLE
Allow pre-hunt charging elemental-charge

### ISSUE THREAD

**Issue by Lazasar** [rpherbig/dr-scripts#1511]
It would be cool if there was a way to SUMMON ADMITTANCE to max charge before heading off to hunt.

**Comment by rpherbig** [comment]
You could make a custom script and use the before hunt setting to call it. The admittance logic itself is already defined in `common-arcana` (method `summon_admittance`).

**Comment by rpherbig** [comment]
@Lazasar Have you had a chance to try this out?

**Comment by Lazasar** [comment]
Hey! yes, I have and in the process found a flaw in the summon_admittance function in common_summing. I would love to have access to the project so I can submit a change myself, but wasn't able to create a branch ... do you guys work off the master or do i just need to permissions?

**Comment by rpherbig** [comment]
The recommended workflow is for you to create a fork, make your changes there, and then submit a pull request.

**Comment by rpherbig** [comment]
Let me know if I can help :)
