### ISSUE TITLE
Please add to astrology script...

### ISSUE THREAD

**Issue by Missah** [rpherbig/dr-scripts#1515]
the following happened over and over and over....

[astrology]>peer telescope
Clouds obscure the sky where the Brigantine should appear.
>
[astrology: *** No match was found after 15 seconds, dumping info]
[astrology: messages seen length: 4]
[astrology: message: Clouds obscure the sky where the Brigantine should appear.]
[astrology: message: [Trade][Zaherli] "That sounds very suspicious."]
[astrology: message: Aura Sight  (7 roisaen)]
[astrology: message:  * Guerilla Ebmarah joins the adventure.]
[astrology: checked against [/You peer aimlessly through your telescope/i, /You see nothing regarding the future/i, /Roundtime/i]]
[astrology]>stow telescope
You put your telescope in your leather pack.
>
[astrology]>get telescope
You get an ivory telescope inlaid with a ruby-eyed golden dragon from inside your leather pack.
>
[astrology]>center telescope on Brigantine
You put your eye to the ivory telescope and attempt to center on the constellation of the Brigantine.
>
[astrology]>peer telescope
Clouds obscure the sky where the Brigantine should appear.
>
[astrology: *** No match was found after 15 seconds, dumping info]
[astrology: messages seen length: 3]
[astrology: message: Clouds obscure the sky where the Brigantine should appear.]
[astrology: message: Aura Sight  (7 roisaen)]
[astrology: message: Aura Sight  (7 roisaen)]
[astrology: checked against [/You peer aimlessly through your telescope/i, /You see nothing regarding the future/i, /Roundtime/i]]
[astrology]>stow telescope
You put your telescope in your leather pack.

**Comment by jandersson** [comment]
Looks like an issue due to not having piercing gaze up... I can put in a check for that message and have it skip to the next constellation

**Comment by Missah** [comment]
PG backfired for some reason, so wasn't up.  Possible to add that for when it happens on the rare occasions?

**Comment by rpherbig** [comment]
Closing in favor of #1614
