### ISSUE TITLE
if I have repair tickets from other crafting societies, I go into an infinite loop

### ISSUE THREAD

**Issue by Lazasar** [rpherbig/dr-scripts#1527]
[workorders]>get my clerk ticket
You get a clerk repair ticket from inside your traveler's pack.
>
[workorders]>look at my ticket
Looking at the clerk ticket you see it is for a grey stone pestle.  You recall that your pestle should be ready by now.

Written at the bottom you see Alchemy Society, Tool Shop, Zoluren.
>
[workorders]>give clerk
You realize that ticket isn't for this repair shop, and your goods are not here.
>
[workorders]>put my clerk ticket in my pack
You put your ticket in your traveler's pack.
>
[workorders]>get my clerk ticket
You get a clerk repair ticket from inside your traveler's pack.
>
[workorders]>look at my ticket
Looking at the clerk ticket you see it is for a grey stone pestle.  You recall that your pestle should be ready by now.

Written at the bottom you see Alchemy Society, Tool Shop, Zoluren.
>
[workorders]>give clerk
You realize that ticket isn't for this repair shop, and your goods are not here.
>
[workorders]>put my clerk ticket in my pack
You put your ticket in your traveler's pack.
>
[workorders]>get my clerk ticket
You get a clerk repair ticket from inside your traveler's pack.
>
[workorders]>look at my ticket
Looking at the clerk ticket you see it is for a grey stone pestle.  You recall that your pestle should be ready by now.

Written at the bottom you see Alchemy Society, Tool Shop, Zoluren.
>
[workorders]>give clerk
>
You realize that ticket isn't for this repair shop, and your goods are not here.
>
[workorders]>put my clerk ticket in my pack
You put your ticket in your traveler's pack.
>
[workorders]>get my clerk ticket
You get a clerk repair ticket from inside your traveler's pack.
>

**Comment by MahtraDR** [comment]
Closing. Sometime since this was opened workoders was updated to match the type of ticket to the type of clerk.
