### ISSUE TITLE
Crossing-Training F2P Scouting

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#1529]
Since hitting 600 scouting, my f2p ranger has been getting stuck somewhere in Xing training.  Maybe if the script would stop running if it tries to go to a zone where you don't have a pass to go?  I've had a therengia pass for a while, I think the issue now is it wants to go to Illithi.  Athletics actually has the same issue at the Gondola branch.

**Comment by rcuhljr** [comment]
You can define custom trails to run and athletics climbs to use, you'll probably want to use those. Although honestly hunt in combat should keep your scouting mostly locked.

**Comment by rpherbig** [comment]
The scouting setting is called `trail_override`. The athletics settings are `swimming_target` or `climbing_target`.

**Comment by mwest152** [comment]
Ah thats cool, I disabled scouting for now, I'll keep an eye on it.  I'm familiar with the swimming/climbing targets and where to find the settings for that.  How does the trail_override work?

**Comment by rcuhljr** [comment]
just provide a list of room numbers with trail heads you want to take in order.

**Comment by mwest152** [comment]
perfect thanks!
