### ISSUE TITLE
Theurgy script doesn't take into account falling on move UP to room 11688

### ISSUE THREAD

**Issue by Lazasar** [rpherbig/dr-scripts#1531]
[theurgy]>west
You go west.
[A Dark Tunnel]
There is a strong light leaking in from a hole above you, and weaker lantern light to the east.  Roots stick out from the wood-braced dirt walls, the glittering minerals in the earth catching what little light there is and reflecting it back.  
Obvious exits: east, up.
Room Number: 11688
>
[theurgy]>up
You take a deep breath, say a brief prayer, and climb up.

There is a moment of desperate scrambling and cursing as one of the roots tries to give way, and then you are up and out....

[Near Kaerna Village, A Dirt Path]
Here a dirt path leads to a dark grove of trees.  A tree stump, its trunk featuring a sizable hole and the base covered with odd carvings that would appear to be symbols, stands where the trail terminates.  
Obvious paths: none.
Roundtime: 10 seconds.
Room Number: 11689
>
[theurgy]>go path
You must be standing to do that.
>
[theurgy: move: no recognized response in 30 seconds.  giving up.]
[theurgy]>go pool
What were you referring to?
>
[theurgy: move: failed]
[theurgy]>get sage from my rucksack
You get a bag of sage from inside your leather rucksack.
>
[theurgy]>rub sage
You rub a bag of sage.
>
[theurgy]>get lavender from my rucksack
You get a bag of lavender from inside your leather rucksack.
>
[theurgy]>rub lavender
You rub a bag of lavender.
>
You feel fully prepared to seek assistance from the Immortals once again.
>
You've gained a new rank in your knowledge of mechanical lore.

**Comment by rcuhljr** [comment]
Are you on the lich fork? Pretty sure this is fixed over there.

**Comment by Lazasar** [comment]
Forgive my ignorance, but how do I get that? I would have assumed dependency would download any updates

**Comment by rcuhljr** [comment]
It's not an update, it's a different version of lich tailored to DR. `;e use_lich_fork`

**Comment by rpherbig** [comment]
We need to make that the default

**Comment by BastionWT** [comment]
Maybe related. I *am* on the Lich Fork, but have a similar issue.

[theurgy]>up

You go west.
[A Dark Tunnel]
There is a strong light leaking in from a hole above you, and weaker lantern light to the east.  Roots stick out from the wood-braced dirt walls, the glittering minerals in the earth catching what little light there is and reflecting it back.  
Obvious exits: east, up.

Room Number: 11688


[theurgy]>go path

You take a deep breath, say a brief prayer, and then climb up the tunnel.

There are a few tense moments as you scramble up through the darkness, but you manage to get a good grip of the roots and start to work your way slowly, but carefully, out....

[Near Kaerna Village, A Dirt Path]
Here a dirt path leads to a dark grove of trees.  A tree stump, its trunk featuring a sizable hole and the base covered with odd carvings that would appear to be symbols, stands where the trail terminates.  
Obvious paths: none.
Roundtime: 5 seconds.

Room Number: 11689

...wait 5 seconds.

[theurgy]>get Taffelberries from my rucksack

You get some sugar-dipped taffelberries from inside your rucksack.

[theurgy]>commune truffenyi

You pour your faith and devotion into a plea to Truffenyi, some sugar-dipped taffelberries held aloft in your hands.
A faint voice murmurs in your head, ~ "You are heard, my child." ~

An aromatic white smoke begins to waft off of your offering.  The tendrils fan out in a jumble of twining, weaving movements until they bring about the distinct semblance of a ban-minahle tree.  Just as its smoky roots finish wrapping your hands, the entirety of the arboreal image is blown away, leaving a glowing Tamsine orb on your palm.

The power of Truffenyi has answered your prayer.

[theurgy]>drop orb

You drop a glowing Tamsine orb.

[theurgy]>go pool

What were you referring to?

[theurgy: move: failed]

[theurgy]>get sage from my rucksack

You get a bag of sage from inside your rucksack.

[theurgy]>rub sage

You rub a bag of sage.

[theurgy]>get lavender from my rucksack

You get a bag of lavender from inside your rucksack.

[theurgy]>rub lavender

You rub a bag of lavender.
The Tamsine orb glows faintly.
You feel fully prepared to seek assistance from the Immortals once again.
The Tamsine orb glows faintly.
You are still rather wet, but drying off nicely.
The Tamsine orb begins to pulse.
The Tamsine orb starts pulsing rapidly.
The Tamsine orb shatters.
Your feet are finally dry.
You sense your connection to the area you consecrated earlier fade away.
With a sigh of relief, Gratio clambers out of the stump.
Father Gratio wandered down a dirt path.
Father Gratio wandered up a dirt path.

Gratio steps into a hole in a tree stump and vanishes into the darkness.
Streamers of white clouds form a gentle carpet for the sun as it mounts its throne high in the noontime sky.
You've gained a new rank in your knowledge of utility magic.
The sky becomes completely overcast.
Xibar slowly rises above the horizon.
With a sigh of relief, Cleripatra clambers out of the stump.
Cleripatra wandered down a dirt path.
Cleripatra wandered up a dirt path.

Cleripatra steps into a hole in a tree stump and vanishes into the darkness.
The clouds part slightly, revealing bits of open sky.
Katamba sets, slowly dropping below the horizon.
The clouds break up somewhat, leaving only a few left in the sky.
With a sigh of relief, Arcara clambers out of the stump.
Arcara wandered down a dirt path.
More clouds move in above, almost obscuring the sky completely.
Arcara wandered up a dirt path.

Arcara steps into a hole in a tree stump and vanishes.

You hear the sounds of someone scrambling madly about, followed by a *BUMP*.
Dancing from one cloud to another, the sun wends its way towards evening.
You've gained a new rank in maneuvering in chain armor.
You've gained a new rank in your ability to evade.
The clouds break up somewhat, leaving only a few left in the sky.
A few scattered clouds reflect the warm glow of the sun as it descends towards its rest.
>stow
You put your sage in your rucksack.
>stow left
You put your lavender in your rucksack.

I hung there for 4+ hours (however long it takes to completely empty your pools).

**Comment by BastionWT** [comment]
Still an issue for me. Might be related to mapdb changes while in there.

**Comment by BastionWT** [comment]
[go2]>go gate

[Northern Trade Road, Kaerna Outskirts]
The wooden wall surrounding the tiny waystop of Kaerna is a visible line drawn between the plains and hamlet.  Thick grasses and shrubs growing against the protective barrier seem intent upon reclaiming the village's side-by-side buildings for the prairie.  Off to one side stands an abandoned militia shack, a silent casualty to the ongoing war between civilization and nature.  You also see a weathered wooden sign and the town gate.
Obvious paths: northwest.

Room Number: 1164


[go2: travel time: 0:00:02]

--- Lich: go2 has exited.

[theurgy]>go shack

[The Militia Shack, Inside]
Not much is left of this building except mice and a few ratty blankets.  It seems well and truly abandoned, of no significant notice whatsoever.  
Obvious exits: out.

Room Number: 1134

The air around you shimmers with a weak yellow light that quickly disperses.

[theurgy]>go hole


[theurgy: move: no recognized response after 30 lines.  giving up.]


[theurgy]>west

[A Dark Tunnel]
Were it not for some lanterns that someone has hung from the ceiling of this burrow, you wouldn't be able to see a thing.  The total silence that pervades this underground tunnel isn't helping much, either.  What little you do see of the architecture is expertly made, possibly even Dwarven in construction.  You also see a dark hole.
Obvious exits: west.

Room Number: 11687


[theurgy]>up

You go west.
[A Dark Tunnel]
There is a strong light leaking in from a hole above you, and weaker lantern light to the east.  Roots stick out from the wood-braced dirt walls, the glittering minerals in the earth catching what little light there is and reflecting it back.  
Obvious exits: east, up.

Room Number: 11688

[theurgy]>go path

You take a deep breath, say a brief prayer, and then climb up the tunnel.

There are a few tense moments as you scramble up through the darkness, but you manage to get a good grip of the roots and start to work your way slowly, but carefully, out....

[Near Kaerna Village, A Dirt Path]
Here a dirt path leads to a dark grove of trees.  A tree stump, its trunk featuring a sizable hole and the base covered with odd carvings that would appear to be symbols, stands where the trail terminates.  
Obvious paths: none.
Roundtime: 5 seconds.

Room Number: 11689

...wait 4 seconds.

What were you referring to?

[theurgy: move: failed]

[theurgy]>get sage from my rucksack

You get a bag of sage from inside your rucksack.

[theurgy]>rub sage

You rub a bag of sage.

[theurgy]>get lavender from my rucksack

You get a bag of lavender from inside your rucksack.

[theurgy]>rub lavender

You rub a bag of lavender.
You are still rather wet, but drying off nicely.
You feel the divinity seep from your bones as the previous blessing of Chadatru wanes.
The clouds part slightly, revealing a few twinkling stars.
The field of silver-blue light dissipates from around you.  The sense of calm focus leaves you, and your joints feel strangely stiffer than before.
Your body is mostly dry now.
The soft silver glow fades from around you.
A gentle sound mimicking the patter of a summer shower meets your ears as the a brilliant orb of rippling cerulean light floating near you shears apart in luminous waves, reforming seconds later into a more solid sphere.
Your latent Shield of Light spell dissipates.
Xibar sets, slowly dropping below the horizon.
Your spirit grows colder as its enhanced vigor begins to wane.
Your spirit feels less protected as the lucent sphere fades from around you.
The sense of spiritual centering leaves you.
The glowing aura fades from around you.
A brilliant orb of rippling cerulean light spins slowly through the air, orbiting your body like a miniature, luminous moon.
Your body is finally dry.
The soft white glow fades from around you.
You've gained a new rank in using large edged weapons.
The last of the stars disappear behind a thick bank of clouds.
With a sigh of relief, Gratio clambers out of the stump.
Father Gratio wandered down a dirt path.
Yavash slowly rises above the horizon.
Father Gratio wandered up a dirt path.

Gratio steps into a hole in a tree stump and vanishes into the darkness.
The cerulean orb floats serenely in the air, just above your head.
The cerulean orb hovering near you suddenly dips behind your left shoulder, circling timidly behind your back.
The cerulean orb of light hovering near you pulsates, as if ebbing and flowing with its own internal tide.
The clouds part slightly, revealing a few twinkling stars.
Ripples of gleaming cerulean light exude from the orb hovering near you, causing your skin to take on the texture and color of a babbling brook.
Various tones and shades of blue wash over the cerulean orb floating near you, illuminating the surroundings in the full scale of rich, oceanic hues.
With a sigh of relief, Alquem clambers out of the stump.
Alquem wandered down a dirt path.
Alquem wandered up a dirt path.

And then hours later, just to check:
>;repos download-mapdb

--- Lich: repository active.

[repository: map database is up-to-date]

[repository: done]

**Comment by asechrest** [comment]
@rpherbig @MahtraDR 

With no additional comments since 2017 and a glance at the code wherein it retries on failure, I say we close this.
