### ISSUE TITLE
combat-trainer doesn't deal well with running out of ammo

### ISSUE THREAD

**Issue by Lazasar** [rpherbig/dr-scripts#1532]
Ideally, it should put away the weapon and move on to a new one, instead, it just keeps trying to load/aim/shoot.

**Comment by wscherer420** [comment]
I've had this happen as well.  I'd be happy if it just skipped that weapon during training somehow.  I can buy more ammo later myself.

**Comment by MahtraDR** [comment]
Closing. combat-trainer just shuts off the ranged skill when you run out of ammo today.
