### ISSUE TITLE
cast message missing from base-spells

### ISSUE THREAD

**Issue by tulanegator** [rpherbig/dr-scripts#1533]
The Sanyu Lyba cast message is not in base-spells. The messaging is:

You open your arms in a hieratic gesture of summoning.

Could someone point me to a walk through or tutorial describing how I can contribute this code to lich? I've been learning some ruby, exploring lich, and I'm writing my first script. I'd like to start helping where possible but I've never used git.

**Comment by rpherbig** [comment]
Merged in 1c79ac0e4776d6c3580e5906cd50822767409abd
