### ISSUE TITLE
Pick.lic & common-items.lic - Shard lockpick refilling breaks go2 at night.

### ISSUE THREAD

**Issue by brycole** [rpherbig/dr-scripts#1537]
Shard lockpicking refill breaks at night.  This could either be a go2 fix or a pick fix?

> > 
> You feel fully attuned to the mana streams again.
> > 
> --- Lich: 'go2' has been stopped by pick.
> 
> --- Lich: go2 has exited.
> 
> --- Lich: go2 active.
> 
> [go2: ETA: 0:00:00 (2 rooms to move through)]
> 
> [go2]>go blue shop
> 
> The shop appears to be closed, but you catch the attention of a night attendant inside, and he says, "I'm sorry, I can only allow citizens in at night."
>   He pauses, then quietly says, "Just for you,
>  I'd look the other way for 1,200 Dokoras."
> [GO again to bribe the night attendant to let you inside.]
> > 
> > 
> You feel fully attuned to the mana streams again.
> > 
> You feel fully attuned to the mana streams again.
> > 
> [go2: move: no recognized response in 30 seconds.  giving up.]
> 
> The night attendant has lost intrest in you.
> > 
> [go2: restarting script...]
> 
> [go2: ETA: 0:00:00 (2 rooms to move through)]
> 

This is the code inside common-items.lic.
 ```  
def refill_lockpick_container(lockpick_type, hometown, container, count)
    room = get_data('town')[hometown]['locksmithing']['id']

    if room.nil?
      echo '***No locksmith location found for current Hometown! Skipping refilling!***'
      return
    end

    count.times do
      buy_item(room, "#{lockpick_type} lockpick")
      DRC.bput("put my lockpick on my lockpick #{container}", 'You put')
    end
    # Be polite to Thieves, who need the room to be empty
    DRC.fix_standing
    move('out')
  end

  def stow_hands
    stow_hand('right') if DRC.right_hand
    stow_hand('left') if DRC.left_hand
  end

  def stow_hand(hand)
    braid_regex = /The braided (.+) is too long/
    result = DRC.bput("stow #{hand}", 'You put', braid_regex, 'is too long')
    dispose_trash(DRC.get_noun(Regexp.last_match(1))) if braid_regex.match(result)
  end


def buy_item(room, item)
    DRCT.walk_to(room)

    case DRC.bput("buy #{item}", /prepared to offer it to you for (.*) kronars/, /Let me but ask the humble sum of (.*) coins/, /for a mere (.*) kronars/, /I can let that go for...(.*) kronars/, /That'll cost you (.*) lirums/, 'You decide to purchase', 'Buy what', /I'll give that to you for (.*) dokoras/)
    when /prepared to offer it to you for (.*) kronars/
      amount = Regexp.last_match(1)
    when /Let me but ask the humble sum of (.*) coins/
      amount = Regexp.last_match(1)
    when /for a mere (.*) kronars/
      amount = Regexp.last_match(1)
    when /I can let that go for...(.*) kronars/
      amount = Regexp.last_match(1)
    when /That'll cost you (.*) lirums/
      amount = Regexp.last_match(1)
    when /I'll give that to you for (.*) dokoras/
      amount = Regexp.last_match(1)
    end

    fput("offer #{amount}") if amount
  end
```

**Comment by intangibles** [comment]
I'm thinking if there is any nighttime variables we can leverage from a different part of the code, this could be an easy fix.

**Comment by wscherer420** [comment]
or just add an extra 1200 tot he amount withdrawn when your hometown is set to shard?  I think that would fix it too.

**Comment by intangibles** [comment]
The 1200 would definitely work.  Go2 has it nicely integrated.  I stopped having problems once I hunted a create with coins because i always had enough to get inside.

**Comment by MahtraDR** [comment]
This doesn't happen anymore. The script just offers 999999 for school lockpick and buys at the lowest price. 

@rpherbig can close.
