### ISSUE TITLE
Blacksmithing uses other oils

### ISSUE THREAD

**Issue by Lazasar** [rpherbig/dr-scripts#1540]
As a cleric, I have other oils in my inventory, and even if I make sure to use separate containers for theurgy and crafting, the woodorder script does a generic "get my oil" and not a "get my oil from my <crafting container>", so the wrong oil gets used, sometimes.

**Comment by rpherbig** [comment]
If it grabs the wrong oil, it *should* put it back and try `get [ordinal] oil` until it finds one that works. Is that what you are seeing?

**Comment by rcuhljr** [comment]
That's not how blacksmithing oil works. (or any of the crafting items).

You need to set up 
```
crafting_container: blah
crafting_items_in_container:
- something
- else
```

and store your forging oil in a different container then your holy oil.
