### ISSUE TITLE
Astrology script won't get bones from container

### ISSUE THREAD

**Issue by Missah** [rpherbig/dr-scripts#1541]
Set up yaml this way:

have_divination_bones: true
divination_bones_storage: pack
#container: pack
#tied: false

and tried this way:

have_divination_bones: true
divination_bones_storage: pack
container: pack
tied: false

and even tried this way, like Crann has it set up, but yaml wouldn't validate:

have_divination_bones: true
divination_bones_storage: pack
  container: pack
  tied: false

I also tried adding the adjective (leather) to my storage pack.

With everyone of these setups, I get the following:

[astrology]>get bones from my 
Please rephrase that command.
>
[astrology: *** No match was found after 15 seconds, dumping info]
[astrology: messages seen length: 5]
[astrology: message: Please rephrase that command.]
[astrology: message: Piercing Gaze  (10 roisaen)]
[astrology: message: Aura Sight  (9 roisaen)]
[astrology: message: Piercing Gaze  (10 roisaen)]
[astrology: message: Aura Sight  (9 roisaen)]
[astrology: checked against [/divination bones/i, /you get/i]]
[astrology]>roll my bones
You'll need to be holding the divination bones to do that.
>
You feel you have sufficiently pondered your latest observation.
>
[astrology: *** No match was found after 15 seconds, dumping info]
[astrology: messages seen length: 5]
[astrology: message: You'll need to be holding the divination bones to do that.]
[astrology: message: Piercing Gaze  (10 roisaen)]
[astrology: message: Aura Sight  (9 roisaen)]
[astrology: message: You feel you have sufficiently pondered your latest observation.]
[astrology: message:  * Drifter Druidal Greybeard joins the adventure.]
[astrology: checked against [/roundtime/i]]
[astrology]>put bones in my 
What were you referring to?
>
[astrology: *** No match was found after 15 seconds, dumping info]
[astrology: messages seen length: 6]
[astrology: message: What were you referring to?]
[astrology: message: Piercing Gaze  (9 roisaen)]
[astrology: message: Aura Sight  (9 roisaen)]
[astrology: message:  * Acquirer Hammerfist has woken up in search of new ale!]
[astrology: message: Piercing Gaze  (9 roisaen)]
[astrology: message: Aura Sight  (9 roisaen)]
[astrology: checked against [/divination bones/i, /you put/i]]
[astrology]>stand
You stand back up.
>
[astrology]>align Lore
You focus internally and align yourself for a prediction on a random lore skill.
Roundtime: 2 sec.
>
[astrology]>get bones from my 
Please rephrase that command.
>;k astrol
--- Lich: astrology has exited.

**Comment by jandersson** [comment]
I think you have an error in your config

**Comment by Missah** [comment]
I've looked/checked everything I can think of checking, here is my yaml:

https://pastebin.com/MvxVZYKB

**Comment by jandersson** [comment]
```
have_divination_bones: true
divination_bones_storage: leather pack
container: leather pack
tied: false
```
`divination_bones_storage` is making a list of sorts. You need to add two spaces before `divination_bones_storage:` and `tied:` to push them into the list. Everything should work then

e.g.
```
divination_bones_storage:
  container: leather pack
  tied: false
```
reference: https://github.com/jandersson/dr-scripts/blob/master/profiles/Crannach-setup.yaml#L245

**Comment by jandersson** [comment]
I've updated my response after a bit of an editing frenzy, but the above shouuuuld fix your issue!

**Comment by Missah** [comment]
That fixed it, thank you so much.  I hate myself when I do stupid things - I just didn't see it.  Really appreciate you looking into it so quickly!

**Comment by jandersson** [comment]
Happy to help!
