### ISSUE TITLE
Forging accepting workorders for item over 5 volumes

### ISSUE THREAD

**Issue by tulanegator** [rpherbig/dr-scripts#1551]
The bronze ingot purchased in the forge is 5 volumes. The workorders script is accepting workorders for a tapered mixing stick that takes 6 volumes of metal. This sends the script into a tailspin that ultimately locks it in a loop. The error starts when you try to pound after studying the tapered mixing stick recipe and then is exaggerated when workorders doesn't know how to tie a hammer and tongs to a forger belt:

[forge]>pound ingot on anvil with my hammer
You need a larger volume of metal to continue crafting.
>
[forge: ***You need a larger ingot to forge this item.***]
--- Lich: forge has exited.
[workorders]>get my forging logbook
You need a free hand to pick that up.

Ultimately the hammer and tongs are stowed, rather than tied, and when it attempts to continue crafting it loops searching for the hammer and tongs. I'm happy to help prepare a fix but I'm not sure where to start. The easiest way would be to prevent workorders from accepting 6 volume recipes. The tapered mixing stick is properly in base-recipes as 6 volumes:

- name: a tapered mixing stick
  noun: stick
  volume: 6
  type: blacksmithing
  work_order: true
  chapter: 5

If anyone can provide guidance on how to fix this I'll work on implementing it.

**Comment by rcuhljr** [comment]
Fixed.
