### ISSUE TITLE
Add outfitting/tailoring to workorders/crossing-trainer

### ISSUE THREAD

**Issue by jonathan-stricker** [rpherbig/dr-scripts#1565]
Started playing the ranger again and it would be nice to be able make non-knitted tailoring items to train outfitting and do tailoring work orders. My tailoring is 700 so I never get offered knitted items, the hardest one is more like the 400-500 range. What can I do to help implement?

thanks!
Reithir

**Comment by rpherbig** [comment]
I thought there were knitted items beyond 700. Do you have techniques that are skewing your workorder selection away from knitted goods?

**Comment by reithir** [comment]
The most difficult knitting pattern is a knitted blanket, a tier 7 (challenging) pattern, which according to the elanthipedia crafting table requires 550 ranks without techs and 368 with. With 700 ranks asking for a work order basically never results in this one.

**Comment by MahtraDR** [comment]
Closing as this support exists today.
