### ISSUE TITLE
Go2 Error with Fatigue

### ISSUE THREAD

**Issue by Sephroc** [rpherbig/dr-scripts#1569]
In Aesry, Go2 does not work properly because of fatigue issues. It'd be nice to have a fatigue check and for it to wait till you have enough fatigue to work

**Comment by NBSL** [comment]
Try this edit and let me know if it works. Only tested it in the Segoltha tunnels.  I don't have access to Aesery on a F2P account I don't believe.

Only change is I added 
`wait_while { stamina < 75 }`
after 
`wait_while { muckled? }` line 963
[go2.lic.zip](https://github.com/rpherbig/dr-scripts/files/949460/go2.lic.zip)

**Comment by Sephroc** [comment]
It works, but the issue that comes is time. Its set pretty high, so even when running across town is gonna do 1 step at a time and wait a coons age till it climbs the next step. If you have about 30 stamina you can make all the climbs. Is there a way for it to just wait a bit after it fails then retry in 10 secs or so?
Appreciate all the help you do for lich
-Sephroc

**Comment by NBSL** [comment]
Hey Seph,

Try this go version.
I moved the stamina check out of the generic section of the each loop and moved it into the the section that handles ruby procs. I also changed it to wait_until stamina > 29. Go still breaks quite often for me when traveling up and down the climbables, usually trying to move to another room before the climb has triggered.
[go2.lic.zip](https://github.com/rpherbig/dr-scripts/files/957085/go2.lic.zip)

**Comment by Sephroc** [comment]
Alright will do. Although for the go2 that you did give me, it works perfectly. I haven't had any hangs up. Not sure if that would be easier than remapping the whole island, but I will start doing that. When I see places like that.

**Comment by NBSL** [comment]
The issue with the go2 method is that it would be hardcoded to 30 fatigue for everything. That means all the paths that only require 5, or climbing down the stairs south of the furrier that requires 10, would still wait for 30.

Both methods have about the same travel time though with my 14 second climb times.

I'll leave it up to @rcuhljr and @rpherbig  on which method they would prefer being used.

**Comment by MahtraDR** [comment]
Closing, looks abandoned, although a good idea.
