### ISSUE TITLE
base-hunting.yaml Added in hunts

### ISSUE THREAD

**Issue by Sephroc** [rpherbig/dr-scripts#1572]
Added in Nipoh Oshu 3 tiers of it, Nightweaver Unyns, and Nightreaver Unyn

  # https://elanthipedia.play.net/Nipoh_oshu_(1) 150-240 Aesry
  # Need Light Source
  nipoh_oshu1:
  - 12487
  - 12483
  - 12484
  # https://elanthipedia.play.net/Nipoh_oshu_(2) 170-290 Aesry
  # Need Light Source
  nipoh_oshu2:
  - 12497
  - 12495
  - 12494
  - 12493
  - 12499
  - 12498
  # https://elanthipedia.play.net/Nipoh_oshu_(3) 240-350 Aesry
  # Need Light Source
  nipoh_oshu3:
  - 12490
  - 12489
  - 12488
  - 12491
  - 12492

  # https://elanthipedia.play.net/Nightweaver_unyn 100-188 Aesry
  # Need Light Source
  nightweaver_unyn:
  - 12474
  - 12480
  - 12481
  - 12501
  - 12506
  # https://elanthipedia.play.net/Nightreaver_unyn 180-225 Aesry
  # Need Light Source
  nightreaver_unyn:
  - 12518
  - 12536
  - 12513
  - 12505
  - 12519

**Comment by MahtraDR** [comment]
Are these still valid?

**Comment by rpherbig** [comment]
@Sephroc

**Comment by MahtraDR** [comment]
@rpherbig Sorry I missed this one. It's 4 years old, and nobody else has piped in. Close?
