### ISSUE TITLE
;shape gets confused by "Mysari" in the room

### ISSUE THREAD

**Issue by jonathan-stricker** [rpherbig/dr-scripts#1578]
I was doing some shaping at the ranger guild and someone named Mysari was there, and every time shape tried to rub my product with my rasp, it kept rubbing Mysari instead. The syntax on our end looks fine, it's just a weird thing with DR and the rub verb, it tries to rub someone named "My" instead of treating it as the actual word "my". Here's a quick log clipping, I'm not sure how we can fix:

shape: *** No match was found after 15 seconds, dumping info]
[shape: messages seen length: 15]
[shape: message: You rub Mysari in a friendly fashion.]
[shape: message: Andreasis begins to fiddle with a sturdy brass coffer.]
[shape: message: Andreasis looks up from the brass coffer with a satisfied grin.]
[shape: message: Romsca continues to braid his vines.]
[shape: message: Trevinder just arrived.]
[shape: message: Reithir rubs Mysari gently, massaging his muscles.]
[shape: message: Trevinder runs south.]
[shape: message: Romsca continues to braid his vines.]
[shape: message: As the day wanes, the sun begins its long trudge towards its home and the sweet comfort of night.]
[shape: message: Celok smashes his foot into a pile of rocks.  It suddenly explodes, scattering bits and pieces of debris in every direction.]
[shape: message: Celok roots around the area for a moment.]
[shape: message: Celok forages around the area for a while and manages to collect a pile of rocks.]
[shape: message: Evissam concentrates intently on his technique as he continues to play a quiet dirge on his copper zills.]
[shape: message: Water is quickly puddling on the ground nearby, but two spots in the shape of feet or shoes remain strangely dry.]
[shape: message: Andreasis stares intently at the brass coffer for a few moments before shaking her head at her obvious failure to find something.]
[shape: checked against [/a wood shaper is needed/i, /ready for shaping with a wood shaper/i, /carved with a carving knife/i, /further carving with a knife/i, /continued knife carving/i, /rubbed out with a rasp/i, /A cluster of small knots/i, /Applying the final touches/i, /That tool does not seem suitable for that task./i, /while it is inside of something/i, /Glue should now be applied/i, /glue to fasten it/i, /ready to be clamped/i, /pushed with clamps/i, /pushing it with clamps/i, /Some wood stain/i, /You fumble around but/i, /ASSEMBLE Ingredient1/i]]
[shape]>rub my buckle with my rasp
>
You rub Mysari in a friendly fashion.

**Comment by rpherbig** [comment]
We need to hunt down and delete every character whose name starts with `My` or `In`.

**Comment by reithir** [comment]
Seconded.

**Comment by MahtraDR** [comment]
@rpherbig Close? We can't fix parser issues, alas. This is really annoying. Conceivably we could add a common to look for other PCs in a room, and pause || exit if their names start with "my" or "in"  but that feels really heavy handed to me, as this is a bit of an edge case.
