### ISSUE TITLE
Statusmonitor configurable time check

### ISSUE THREAD

**Issue by ghost** [rpherbig/dr-scripts#1582]
Could we add a time check parameter to statusmonitor?, If you remain in a room for longer than a configurable amount of time it send a status monitor message?

This will help for those occasional cases where ;go2, ;hunting-buddy, crafting, etc... gets stuck in a loop or just gives up and leaves you lingering in the room "forever."

**Comment by MahtraDR** [comment]
This is a very old issue, with no follow up since. Would be happy to revisit this topic as fresh when if it comes up again.
