### ISSUE TITLE
Check wounds fails when poisoned

### ISSUE THREAD

**Issue by reithir** [rpherbig/dr-scripts#1584]
Strange error I just noticed, training-manager just finished hunting and it checked me for wounds and was...mistaken:

```
--- Lich: hunting-buddy has exited.
--- Lich: safe-room active.
>
[safe-room]>health
Your body feels at full strength.
Your spirit feels full of life.
You have some tiny scratches to the neck, minor swelling and bruising around the left arm compounded by cuts and bruises about the left arm, minor swelling and bruising around the right leg compounded by cuts and bruises about the right leg, minor swelling and bruising around the left leg compounded by cuts and bruises about the left leg, some minor abrasions to the left hand, some tiny scratches to the chest, some tiny scratches to the abdomen, some tiny scratches to the back, some minor abrasions to the right eye.
You have a mildly poisoned right leg.
>
[safe-room: ***STATUS*** No wounds, skipping healing]
--- Lich: safe-room has exited.
```

It then ran to get my gear repaired and continue on with training-manager. Soooo what's up with that?

**Comment by intangibles** [comment]
It has to do with the poison bugging out the wound check.  There are a couple other instances of wounds not being recognized as well. We should probably start collecting them.

The missings wounds I believe are mostly related to lockpicking traps.

**Comment by rpherbig** [comment]
While we should fix the wounds that aren't recognized, there might also be an argument for `safe-room` to skip the threshold check if you are bleeding or poisoned...

**Comment by jandersson** [comment]
`common-healing::check_wounds` needs to be updated to handle the line with poison

**Comment by jandersson** [comment]
The title for this could be more descriptive so it shows up in search, something like "Check wounds fails when poisoned"
