### ISSUE TITLE
equipmanager.lic option to stop sort auto head

### ISSUE THREAD

**Issue by Thires** [rpherbig/dr-scripts#1585]
Since inventory no longer shifts, would it be possible to add an option to disable this?

**Comment by mwcarew** [comment]
I'd second this or at least make it optional with a YAML variable.

**Comment by Thires** [comment]
I give up trying to figure out how to pull a request. I am sure it is simple and I am just missing it.

**Comment by rpherbig** [comment]
This was fixed a while ago - I guess we forgot to close the issue. The setting is `sort_auto_head: false`.
