### ISSUE TITLE
combat-trainer not picking up bolts if one is lodged in you

### ISSUE THREAD

**Issue by mwineland587** [rpherbig/dr-scripts#1589]
[combat-trainer]>stow bolt

That crossbow bolt needs to be tended to be removed.
>he
>

Your body feels slightly battered.
Your spirit feels full of life.
You have some tiny scratches to the chest, some minor abrasions to the abdomen.

You have a crossbow bolt lodged shallowly into your chest.
>
[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 37]
[combat-trainer: message: * As if effort and skill were a bad thing, a silver-backed bear slices wide at you.  You dodge.  ]
[combat-trainer: message: [You're bruised, solidly balanced and in very strong position.]]
[combat-trainer: message: * As if fumbling muscle flab were natural, a dire bear swipes with powerful and sharp claws at you.  You dodge, managing to get out of the way with a minimum of effort.  ]
[combat-trainer: message: [You're bruised, solidly balanced with opponent in better position.]]
[combat-trainer: message: That crossbow bolt needs to be tended to be removed.]
[combat-trainer: message: * Moving in like a timid schoolboy, a dire bear swipes with powerful and sharp claws at you.  You dodge, leaning just out of harm's reach.  ]
[combat-trainer: message: [You're bruised, solidly balanced with no advantage.]]
[combat-trainer: message: The flame opals adorning the triquetra symbol of your blighted gold bracelet flare with radiance, a sense of peace and restfulness spreading through you to ease your mental fatigue.]
[combat-trainer: message: Rite of Grace  (Indefinite)]
[combat-trainer: message: Obfuscation  (2 roisaen)]
[combat-trainer: message: Philosopher's Preservation  (13 roisaen)]
[combat-trainer: message: Manifest Force  (27 roisaen)]
[combat-trainer: message: Ease Burden  (2 roisaen)]
[combat-trainer: message: A dire bear saunters down.]
[combat-trainer: message: * Awkwardly, a dire bear saunters forward, its jaws wide open in menacing fashion at you.  You dodge, twisting to one side.  ]
[combat-trainer: message: [You're bruised, solidly balanced with no advantage.]]
[combat-trainer: message: You think you have your best shot possible now.]
[combat-trainer: message: Your concentration slips for a moment, and your spell is lost.]
[combat-trainer: message: * Awkwardly, a silver-backed bear swipes with powerful and sharp claws at you.  You evade.  ]
[combat-trainer: message: [You're bruised, solidly balanced and in strong position.]]
[combat-trainer: message: * Ineptly, a dire bear saunters forward, its jaws wide open in menacing fashion at you.  You dodge, leaning just out of harm's reach.  ]
[combat-trainer: message: [You're bruised, solidly balanced and opponent has slight advantage.]]
[combat-trainer: message: * Apparently without direction or thought, a dire bear saunters forward, its jaws wide open in menacing fashion at you.  You dodge, managing to get out of the way with a minimum of effort.  ]
[combat-trainer: message: [You're bruised, solidly balanced with opponent in strong position.]]
[combat-trainer: message: * Apparently without direction or thought, a dire bear slices wide at you.  You dodge, stepping out of harm's way.  ]
[combat-trainer: message: [You're bruised, solidly balanced and opponent has slight advantage.]]
[combat-trainer: message: Your body feels slightly battered.]
[combat-trainer: message: Your spirit feels full of life.]
[combat-trainer: message: You have some tiny scratches to the chest, some minor abrasions to the abdomen.]
[combat-trainer: message: You have a crossbow bolt lodged shallowly into your chest.]
[combat-trainer: message: Rite of Grace  (Indefinite)]
[combat-trainer: message: Obfuscation  (2 roisaen)]
[combat-trainer: message: Philosopher's Preservation  (13 roisaen)]
[combat-trainer: message: Manifest Force  (26 roisaen)]
[combat-trainer: message: Ease Burden  (2 roisaen)]
[combat-trainer: message: * Ineptly, a dire bear saunters forward, its jaws wide open in menacing fashion at you.  You dodge, leaping aside.  ]
[combat-trainer: message: [You're bruised, solidly balanced with no advantage.]]
[combat-trainer: checked against [/You pick up/i, /You get/i, /You need a free hand/i, /There isn't any more room/i, /You just can't/i, /push you over the item limit/i, /You stop as you realize the .* is not yours/i, /Stow what/i, /already in your inventory/i, /The .* is not designed to carry anything/i]]
>;pause
--- Lich: combat-trainer paused.
>

>tend my chest
You skillfully remove the crossbow bolt from your chest leaving the wound no worse than it was before.
Roundtime: 5 seconds.

**Comment by izawwlgood** [comment]
FYI this has been resolved but requires you not use the same ammo as what is lodging.

**Comment by MahtraDR** [comment]
@rpherbig taking @izawwlgood's comment at face value, can close. (I also can't replicate this at all today)
