### ISSUE TITLE
RDC StringProc Update to use wait_while

### ISSUE THREAD

**Issue by brycole** [rpherbig/dr-scripts#1595]
```
[exec1: @id=7633
@image="Therengia, 33, Road to Theren.gif"
@climate=nil
@title=["[[Jantspyre River, South Bank]]"]
@check_location=nil
@timeto={"7634"=>0.2, "7647"=>0.2, "7651"=>0.2}
@location=nil
@tags=["rock"]
@wayto={"7634"=>"southwest", "7647"=>"go bank", "7651"=>StringProc.new("echo 'YOU CAN CREATE A SCRIPT NAMED UDC TO TAKE ALL ARMOR OFF' start_script ('udc') wait_while{ running?('udc') } move 'go bank'fput 'e' pause waitrt? fput 'ne' pause waitrt? fput 'ne' pause waitrt? fput 'e'  pause waitrt? echo 'YOU CAN CREATE A SCRIPT NAMED RDC TO PUT ALL ARMOR ON' start_script ('rdc')")}
@paths=["Obvious paths: southwest."]
@image_coords=[376, 89, 391, 104]
@terrain=nil
@description=["The forest gives way to the banks of a swift-flowing river.  No bridge crosses the water, and the far bank is too steep to clamber out."]]

```
Can anyone update the RDC string proc to the same syntax as UDC? RDC currently goes wild trying to put gear on while go2 is running.

start_script ('udc') wait_while{ running?('udc') <-- current code
start_script ('rdc')  <-- current code

Thanks!  (I can't currently update stringprocs due to using Genie. or something bizzarre like that.)

**Comment by intangibles** [comment]
Quick work around until this can get updated.

custom_require.call(%w(equipmanager))

pause_script('go2')
 
gearset='standard'
if variable[1] != nil
  gearset = variable[1]
end
 
settings = get_settings
equipment_manager = EquipmentManager.new(settings)
equipment_manager.wear_equipment_set?(gearset)

unpause_script('go2')

**Comment by MahtraDR** [comment]
Closing as it's too old, and I can't figure out what it's about today. Happy to treat a new issue as fresh.
