### ISSUE TITLE
Combat trainer unable to find new weapon skill

### ISSUE THREAD

**Issue by NBSL** [rpherbig/dr-scripts#1602]
The error only happens in one of my training yamls. 
Debugging it, the furthest I got is determine_next_to_train doesn't return a new_weapon_skill.

The issue fixes itself after combat-trainer exits and is reran.

Combat trainer errors with 
`Lich: error: can't convert NilClass to String (NilClass#to_str gives NilClass)
	combat-trainer:2115:in 'include?'
	combat-trainer:2115:in 'backstab?'
Lich: combat-trainer has exited.`

Yaml in question:
[url](https://pastebin.com/RntnSgx3)

**Comment by rcuhljr** [comment]
Run ;e help_me and submit that pastebin, the yaml you linked doesn't compile and the issue may relate to settings pulled in from you main -setup file.

**Comment by NBSL** [comment]
https://pastebin.com/t5rEkk0i

**Comment by rcuhljr** [comment]
Is this the skinning file that's causing problems? You can add `debug` to the list of args for that file to dump more info from the hunt that breaks.

**Comment by mwest152** [comment]
I think there was a note when I first made my YAML that backstab and ambush aren't supposed to be used at the same time.  Not actually sure what "ambush" does since there is use_stealth_ attacks, or ambush stun in training-abilities.   Unrelated, but I notice you have prowess under training_abilities rather than buffs.  Was curious why.

**Comment by NBSL** [comment]
Thank you @rcuhljr I'll try running the debug and see if I get anything new.

@mwest152 Simple answer is, originally I was using Inkin's yaml as an example when I started a few weeks back. So most of my thief and combat settings come directly from his setup.

**Comment by rpherbig** [comment]
I never had any trouble on Inkin using both.

**Comment by NBSL** [comment]
Latest yaml: [https://pastebin.com/rmDZ26te](url)
Intial state output: [https://pastebin.com/vDdkv7qE](url)

[hunting-buddy: ***STATUS*** 59 minutes of hunting remaining or waiting on Small Edged, Brawling, Backstab]
[combat-trainer]>ambush stun

You aren't close enough to attack.
You begin to stealthily advance on a snowbeast.
A snowbeast snarls and howls at a shadow.
A granite gargoyle grumbles and stomps about, looking for something.
A granite gargoyle grumbles and stomps about, looking for something.

[combat-trainer]>stow my throwing.spike

You come out of hiding.
You put your spike in your kidskin baldric.

[combat-trainer: failed to match a weapon for :]
[combat-trainer: ***Fatigue: 100***]
[combat-trainer: ***Target: 85***]
--- Lich: error: can't convert NilClass to String (NilClass#to_str gives NilClass)
	combat-trainer:2115:in `include?'
	combat-trainer:2115:in `backstab?'
--- Lich: combat-trainer has exited.

**Comment by NBSL** [comment]
A bit more info. I threw a couple echo checks into the combat-trainer and it appears that when game_state.weapon_training is passed as a parameter to determine_next_to_training, it comes through as empty.

[combat-trainer: action count: 0 vs 15]
[combat-trainer: skill exp: 0 vs -1]
[combat-trainer: new skill needed for training]
[combat-trainer: Gamestate.weapon_training: {"Small Edged"=>"rapier", "Brawling"=>""}]
[combat-trainer: Parameter weapon_training: {}]
[combat-trainer: checking weapons as nil!=Small Edged]

My current solution is to add
`weapon_training = game_state.weapon_training if weapon_training.empty?`
to line 94 of combat-training

I haven't figured out why, nor have I tested that bandaid long term, but for the last half hour it's been working.

**Comment by rpherbig** [comment]
I have a theory that what is happening is in your setup file you have `r4` set. When retreating, combat-trainer tries to swap to a ranged weapon. But in that hunt, you have no ranged weapons defined.

To test this theory, could you add an echo around line 48 to confirm that the `determine_next_to_train(game_state, game_state.retreat_weapons, false)` case is being taken?

**Comment by NBSL** [comment]
You were correct. I completely overlooked that I added that to my yaml earlier. Thank you

**Comment by rpherbig** [comment]
@NBSL I added a validator that should detect this case, could you give it a try?

**Comment by NBSL** [comment]
This is the output I get:

;validate
--- Lich: validate active.
Validating settings for 5 settings files
Checking 40 different potential errors in file Uidin-setup.yaml
Checking 40 different potential errors in file Uidin-ranged.yaml
Checking 40 different potential errors in file Uidin-thrown.yaml
Checking 40 different potential errors in file Uidin-skinning.yaml
Checking 40 different potential errors in file Uidin-kill.yaml
WARNINGS:0 ERRORS:2
All done!
--- Lich: validate has exited.
