### ISSUE TITLE
Remedy hangs when duplicate mortar is on the ground / in trash receptacle 

### ISSUE THREAD

**Issue by thejko** [rpherbig/dr-scripts#1604]
[remedy]>put water in mortar

You put your water in the stone mortar which is inside a waste bin.

Probably just need to specify MY mortar, not sure if this issue occurs when adding other items to mortar.

**Comment by rpherbig** [comment]
@thejko Are you comfortable editing the script to use `my mortar` and testing it out?

**Comment by thejko** [comment]
Picking up some test mortars and giving it a shot - found a few instances where the script didn't specify `my mortar` when adding water or alcohol and changed them.

**Comment by thejko** [comment]
Ran through a few different items without a hitch, I'll send a pull request.
