### ISSUE TITLE
Missing messaging for Snipe

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#1607]
Missing messaging for snipe on a failed hide.  I think with poach it just fires if you are not in hiding, figure snipe should do the same.

[combat-trainer]>snipe

H> 
The young wyvern searches around for a moment.
A young wyvern has spotted you!
The young wyvern discovers you, ruining your hiding place!

> 
* Awkwardly, a young wyvern lunges foward and snaps its fangs at you.  You dodge, stepping out of harm's way.  
[You're solidly balanced with no advantage.]
> 
How can you snipe if you are not hidden?

[combat-trainer: *** No match was found after 15 seconds, dumping info]

[combat-trainer: messages seen length: 31]

[combat-trainer: message: ...wait 1 seconds.]

**Comment by rpherbig** [comment]
@mwest152 Give that a whirl and let me know if you still have any problems. You will need to restart dependency to get the updated script.
