### ISSUE TITLE
safe_room is not necro safe

### ISSUE THREAD

**Issue by Morzain** [rpherbig/dr-scripts#1612]
I had 1 minor scratch and it said 1 exceeded threshhold of 0 so it sent me to the autopuff in riverhaven and got me arrested.

I have since set saferoom_health_threshold to 1000 so hopefully it never happens again to me, but I've heard reports of other people experiencing this as well.

**Comment by rpherbig** [comment]
There is a check to avoid auto empath if a necro. Apparently it did not
detect you are a necro.

Was drinfomon running?

**Comment by rcuhljr** [comment]
Make sure you didn't trust drinfomon, nor safe-room

**Comment by Morzain** [comment]
drinfomon was running, and I do not believe either of those are trusted. is there a way to check?

**Comment by rpherbig** [comment]
`;list trusted`

Also, could you run `;en echo DRStats.necromancer?` for us?

**Comment by intangibles** [comment]
There definitely has to be a non safe-room related issue going on.  Safe-room has ran an ungodly amount of times (10,000+?) on my necromancer, for 50+ circles of training.  I've never once had it bug out and run to an auto-healer.

**Comment by Morzain** [comment]
HR>;list trusted
--- Lich: trusted scripts: repository, lnet, narost, lnet, dependency, status-monitor, status-mon, narost, wiz_to_lich, narost2

Apparently some things are listed twice ^^^

Not sure the correct syntax:

HR>;en echo DRStats.necromancer?
--- Lich: could not find script 'en' in directory C:/Users/Morzain/Desktop/lich/scripts
HR>

R>;e echo DRStats.necromancer?
--- Lich: exec1 active.
--- Exception: uninitialized constant DRStats
exec1:1:in `_script'
--- Lich: exec1 has exited.

**Comment by Morzain** [comment]
I had also gone 50 circles without seeing this happen until that day. Maybe it was just a weird glitch, I had never seen it happen before. No idea, just if it was a new bug I wanted to be sure to mention it.

**Comment by rpherbig** [comment]
The failure of `;en` implies you aren't using the lich fork. Could you run `;e use_lich_fork` and then restart dependency after it updates lich?

**Comment by Morzain** [comment]
isn't that fork for genie support? I've been using SF. just want to make sure I understand but here you go:

--- Lich: dependency, drinfomon
>;en echo DRStats.necromancer?
--- Lich: exec1 active.
[exec1: true]

I ran ;learn first as after a fresh restart only dependency was running. In any event I guess we can probably just close this and if it happens again I'll run this command to see if it thinks I'm not a necro at the time?

**Comment by rpherbig** [comment]
That fork is for DR lich users, it contains a number of fixes that don't affect GS.
