### ISSUE TITLE
Bug around aiming with a ranged weapon

### ISSUE THREAD

**Issue by ghost** [rpherbig/dr-scripts#1615]
This one was complicated. Steps to reproduce:

Aim with a ranged weapon (crossbow)
Creature dies before ready to shoot
Swap weapons to another ranged weapon
Aim with second ranged weapon
You're already aiming
Combat trainer hangs and will never end the hunt, because it isn't expecting to already be aiming

https://pastebin.com/5Ss1NYz2

**Comment by rpherbig** [comment]
Huh, that's quite the specific set of circumstances...

**Comment by jayRyan24** [comment]
Not seen that in a year. I guess we can add on a weapon swap that if the weapon is a ranged weapon, just fput 'stop aim' or whatever it is?

**Comment by BastionWT** [comment]
Yeah. I have my alts raising up things like bow, crossbow, and sling (among other things). I'd occasionally come back to them with basically clear field EXP because they'd sat for hours waiting in the above condition. Only thing I needed to do to get them moving again was AIM.

**Comment by jayRyan24** [comment]
Definitely weird. I've run about 7 chars with all weapons and never experienced this once. I'm talking thousands and thousands of ranks. My barb has 610 slings, 650 crossbows, and 700 bow alone. My other chars are in the 300-500's. 

I wonder if it's a setup thing, though I can't imagine that. Regardless, @rpherbig testing a fix all night.

**Comment by BastionWT** [comment]
Not fixed. :)

https://pastebin.com/49zWVPGr

**Comment by rpherbig** [comment]
Ah... my fix only runs if you are changing weapon skills. We'll need to move that code to handle your case in which it picks the same skill again.

**Comment by BastionWT** [comment]
On my necro as well:
https://pastebin.com/QbuEX8eL

**Comment by BastionWT** [comment]
Also on my bard. :)
https://pastebin.com/ZEm6Xx1d

**Comment by BastionWT** [comment]
Still occurring, unfortunately. Always on slings. Never any aimed weapon besides slings.

**Comment by BastionWT** [comment]
[combat-trainer]>poach
A dire bear has spotted you!
The dire bear discovers you, ruining your hiding place!
>
* Apparently without direction or thought, a dire bear charges with surprising speed at you.  You block with a small gryphon-pelt shield sealed with protective wax.
[You're adeptly balanced and in dominating position.]
>
How can you poach if you are not hidden?
>
[combat-trainer]>load
Your leather sling is already loaded with a small rock.
>
[combat-trainer]>aim
You are already targetting that!
>
[combat-trainer]>

May be a partial cause to the issues as well. Sat there, not doing anything afterward.

**Comment by MahtraDR** [comment]
@rpherbig  What do you think? Worth pursuing 5 years on? I'm inclined to close, since it has had no follow up since.
