### ISSUE TITLE
Quicken the Earth cast message

### ISSUE THREAD

**Issue by Sephroc** [rpherbig/dr-scripts#1617]
Quicken the earth isn't added into cast messages

[combat-trainer]>cast
Your cambrinth armband emits a loud *snap* as it discharges all its power to aid your spell.
Disregarding the pain, you grind the dirt brutally into the palm of your hand, blood and soil forming a viscous paste.

The gritty colloid smearing your skin sears with flaring heat!  Just as the smell of burning flesh begins to assault your senses, a vermillion cloud billows forth from your grasp.  You clench your fist and the swirling torrent of particles responds, coalescing into a Halfling-sized construct of sodden loam.
 
Abruptly the exterior of the being solidifies into a rocky shell, trapping a smattering of liquid on the outside.  The viscous fluid runs labyrinthine trails down the front of the creature before being reabsorbed by its skin.  Its head mechanically snaps up and it immediately scans the area for targets.
Roundtime: 1 sec.

[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 40]
[combat-trainer: message: Your cambrinth armband emits a loud *snap* as it discharges all its power to aid your spell.]
[combat-trainer: message: Disregarding the pain, you grind the dirt brutally into the palm of your hand, blood and soil forming a viscous paste.]
[combat-trainer: message: The gritty colloid smearing your skin sears with flaring heat!  Just as the smell of burning flesh begins to assault your senses, a vermillion cloud billows forth from your grasp.  You clench your fist and the swirling torrent of particles responds, coalescing into a Halfling-sized construct of sodden loam.]
[combat-trainer: message: Abruptly the exterior of the being solidifies into a rocky shell, trapping a smattering of liquid on the outside.  The viscous fluid runs labyrinthine trails down the front of the creature before being reabsorbed by its skin.  Its head mechanically snaps up and it immediately scans the area for targets.]
[combat-trainer: message: Quicken the Earth  (17 roisaen)]

**Comment by jayRyan24** [comment]
So, is this spell already working? Does it auto attack? I'm going to implement support for this pet and am wondering if it is actually needed then? Seems like it already works. We just need to add the messaging and such.

**Comment by jayRyan24** [comment]
How are you getting it to perform the ritual and get the dirt?

**Comment by Sephroc** [comment]
No i have to manually do that myself with before actions, but its not fail
proof doing that because of the factor if you fail to retreat or cant
forage the area.

**Comment by Sephroc** [comment]
Quicken the Earth:
    abbrev: QE
    recast: 1
    mana: 10
    cambrinth:
    - 6
    before:
    - message: retreat
      matches: You retreat back to pole
    - message: retreat
      matches: You retreat from combat 
    - message: forage dirt
      matches: You manage
    - message: perform cut
      matches: You draw

**Comment by intangibles** [comment]
He's just saying it needs a cast_messages to base-spells.
