### ISSUE TITLE
Stealing necklace in dirge causes error

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#1619]
Not sure what this error is for, but for some reason I get an error when my script steals this item.  Then not stowing it hangs my script, also also doesn't bin the stuff I stole to this point.  I'm going to add it to the do not steal list for now, but no clue myself on how to fix it.  Pasted the item from base-stealing and the log of what happened.

- exceptionally_max: 577
  exceptionally_min: 477
  id: '340'
  item: golden necklace
  item_in: on counter
  pawnable: false
  province: zoluren
  room: 19476
  rather_max: 696
  rather_min: 653
  very_max: 589
  very_min: 586

H> 
[steal]>steal golden necklace on counter

Moving stealthily, you manage to grab a simple golden necklace right from underneath a sales clerk's very nose.
You learned acceptably from this theft.
Roundtime: 5 sec.

HR> 
--- Lich: error: comparison of Fixnum with nil failed
	steal:285:in `<='
	steal:285:in `update_target'

--- Lich: steal has exited.

**Comment by mwest152** [comment]
I thought maybe it was that necklace, because it happened twice, but just happened again with another item:

Moving stealthily, you manage to grab a portable stove right from underneath the merchant Berolt's very nose.
You learned somewhat poorly from this simple theft.
Roundtime: 5 sec.

HR> 
--- Lich: error: comparison of Fixnum with nil failed
	steal:285:in `<='
	steal:285:in `update_target'

--- Lich: steal has exited.

**Comment by rcuhljr** [comment]
I pushed something that should fix this, although I can't see how you were getting into that state based on your stealing yaml.
