### ISSUE TITLE
;Bescort isn't going across the gondola properly

### ISSUE THREAD

**Issue by reithir** [rpherbig/dr-scripts#1626]
Sometimes it works fine, but other times it does the following and I'm not sure why:

[go2: ESCORT REQUIRED DOWNLOAD IT FROM THE REPO]
--- Lich: escort active.
[escort]>look
[Obsidian Pass, Platform]
Like an aerie forgotten in the wilderness, the platform remains despite being abandoned by its creators.  While rickety and creaking uneasily, it appears to have held up well.  Two side-by-side granite beams rise up from the edge of the ridge, around which have been wound the lengths of rope used by the gondola that provides transport over the great chasm.  You also see a granite plaque, a weathered wooden gondola and the ridge.
Obvious paths: none.
Room Number: 2249
>
--- Lich: could not find script 'scholarship' in directory C:/Users/jonathan/Documents/lich/scripts
[escort]>go gondola
[Gondola, Cab North]
Worn down to a dusky grey color, the proud wood once cut and fitted to compose this gondola creaks with age and disrepair, but appears to be steady.  Seats have been lifesculpted up from the floor and melded into the sides.  Weak light streams in through the yellow-tinted windows, eating away patiently at what little color remains in the tiny, musty chamber.  You also see a plump field piglet.
Also here: Menace Kekahuna.
Obvious exits: south, out.
>
You feel fully rested.
>
The door swings shut of its own accord, and the gondola pushes off.
>
The ridge to the north begins to slowly draw away as the cab moves south.
>
The platform vanishes against the ridgeline.
>
The cab nears the center of the chasm, swinging in the breeze.
>
The gondola arrives at the center of the chasm, and keeps heading south.
>
The cab continues away from the center of the chasm.
>
The cab trundles on along as the ropes overhead creak and moan.
>
The cab trundles on along as the ropes overhead creak and moan.
>
The cab swings in a mountain wind over the chasm.
>
The ropes creak as the gondola continues south.
>
With a soft bump, the gondola comes to a stop at its destination.
>
The gondola creaks as a wind pushes it back and forth.
>
The door swings shut of its own accord, and the gondola pushes off.
>
The ridge to the south begins to slowly draw away as the cab moves north.
>l
[Gondola, Cab North]
Worn down to a dusky grey color, the proud wood once cut and fitted to compose this gondola creaks with age and disrepair, but appears to be steady.  Seats have been lifesculpted up from the floor and melded into the sides.  Weak light streams in through the yellow-tinted windows, eating away patiently at what little color remains in the tiny, musty chamber.  You also see a plump field piglet.
Obvious exits: south.

So it boarded the gondola but then it didn't go to the other room and wait for the bump at destination and then it didn't get off; this happened once while I ran for a few hours and if it happens the character just sits there indefinitely. Let me know if you need any more info

**Comment by reithir** [comment]
ah hah, I found some additional info, I just saw it happen, here's the log:

[go2]>go gondola
There is no wooden gondola here.  You'll have to wait for it to come back around.
>
[go2: waiting for the gondola...]
>
The gondola swings closer to the platform.
>

The gondola stops on the platform and the door silently swings open.

>
[go2]>go gondola
[Gondola, Cab North]
Worn down to a dusky grey color, the proud wood once cut and fitted to compose this gondola creaks with age and disrepair, but appears to be steady.  Seats have been lifesculpted up from the floor and melded into the sides.  Weak light streams in through the yellow-tinted windows, eating away patiently at what little color remains in the tiny, musty chamber.  
Obvious exits: south, out.
>
[go2]>south
You go south.
[Gondola, Cab South]
Dark brown stains have worked their way into the wooden floor and seats of this small cab, griming up the windows so that the light comes in as a ruddy, dirty color.  The faintest trace of some sweetly-sick metallic scent lingers here, just barely detectable, but inescapable.  The fresh mountain air tries to push through the sour smell, but the stench remains.  
Obvious exits: north.
>
The gondola creaks as a wind pushes it back and forth.
>
The door swings shut of its own accord, and the gondola pushes off.
>
The ridge to the north begins to slowly draw away as the cab moves south.
>
The platform vanishes against the ridgeline.
>
The cab nears the center of the chasm, swinging in the breeze.
>
The gondola arrives at the center of the chasm, and keeps heading south.
>
--- Lich: 'go2' has been stopped by hunting-buddy.
--- Lich: go2 has exited.
--- Lich: go2 active.
[go2: error: your current room was not found in the map database]
--- Lich: go2 has exited.
[hunting-buddy: Failed to navigate to room 9676, attempting again]
[hunting-buddy: In an unknown room, manually attempting to navigate to 9676]
[hunting-buddy: failed to find a matching room]
The cab continues away from the center of the chasm.
>


So hunting-buddy killed go2 and then it couldn't start again because the gondola room isn't mapped. What's going on here, why does hunting-buddy think it's lost?

**Comment by jandersson** [comment]
The gondola runs on `escort` currently, I think the issue you're experiencing is a shortcoming of that Wizard script. Adding the gondola to `bescort` is definitely on the todo list though

**Comment by jandersson** [comment]
I noticed there isn't an issue for that, so i made one. You can close this in favor of:
https://github.com/rpherbig/dr-scripts/issues/1636

Feel free to comment there to get it some more attention!

**Comment by rpherbig** [comment]
#1636
