### ISSUE TITLE
TM using cambrinth causes double charge on creature death and subsequent next cast

### ISSUE THREAD

**Issue by brycole** [rpherbig/dr-scripts#1632]
This is is a fairly easy work around to this, by simply not using cambrinth with TM spells.  But I figured it would be best to document anyways.

When you Prep/Target TM, Charge Camb, then the creature you are facing dies (for whatever reason),  you release the spell and Prep/Target/Charge all over again.  This second cast has mana in the cambrinth from the first cast and the second cast and can cause backfires if you are casting near your TM spell cap.

It happened frequently enough that I would blow my nerves, but only because I was constantly killing things from USOL and constructs.  This would stack on top of casting buff spells near cap and it turned into a sort of cascade.  Once I identified the issue I just took cambrinth away from TM spells.  But it took awhile to figure out why i was slowly destroying my nerves.

**Comment by rpherbig** [comment]
Is there a way to release mana from a cambrinth?

**Comment by intangibles** [comment]
I don't think so.  There is some round-out-ways that could potentially work but have other drawbacks.

This lets you specify how much mana to draw from your cambrinth.  This would actually be a fantastic solution but it breaks invoke cambrinth spell/cyclic, so a cyclic would steal all your mana.  Example below.

> > charge my mana 20
> You harness a moderate amount of energy and attempt to channel it into your cambrinth manacle.
> You are able to channel all the energy into the manacle.
> The cambrinth manacle absorbs all of the energy.
> Roundtime: 4 sec.
> R> invoke my mana 10
> The cambrinth manacle pulses with Arcane energy.  You reach for its center and forge a magical link to it, attempting to ready 10 mana streams for your use.  You manage to attune yourself exactly as you intended to.
> Roundtime: 1 sec.
> R> 
> Your cambrinth manacle thrums softly as it discharges some of its power to maintain your spell.
> > 
> Your cambrinth manacle thrums softly as it discharges all its power to maintain your spell.
> 

What I've done in the past is used my easiest spell I know and do quick snapcasts to clear the mana. Mileage can vary here depending on spells available and skill, so may not be the best solution.

**Comment by MahtraDR** [comment]
@rpherbig can close. 

This is not an issue if you set invoke cambrinth exact or whatever the setting is called. It'll never invoke more than what you set the spell to use.

**Comment by MahtraDR** [comment]
The exact setting today is  called ```cambrinth_invoke_exact_amount``` and defaults to false.
