### ISSUE TITLE
Add defensive stance option to combat-trainer.

### ISSUE THREAD

**Issue by brycole** [rpherbig/dr-scripts#1635]
So the idea here is that you can go full defensive stance in an area you just want to train defenses, and it would still swap between parry/shield.

Shield stance would be "stance set 100 100 0 0"
Parry parry would be "stance set 100 0 100 0"

I dont really see any specific functionality for this currently unless you created 2 separate YAMLS with stance_override.

**Comment by MahtraDR** [comment]
@rpherbig can close. Addressed reasonably well in https://github.com/rpherbig/dr-scripts/pull/5277
