### ISSUE TITLE
Thief + offhand weapon + small edged = backstab

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#164]
If not by default, maybe by user setting?  backstab_offhand_se

Potential issues if using a medium edge that weighs over 30+ stones

**Comment by rcuhljr** [comment]
can you backstab offhanded? I hadn't tried it.

**Comment by OdnaZvezda** [comment]
Yes.  Backstab left with a suitable small/medium edge

**Comment by rpherbig** [comment]
Marking this as 'must have' since we have a user requesting it. @OdnaZvezda would you agree, or is this a nice to have?

**Comment by OdnaZvezda** [comment]
I would say it's a must have.  Much of my offhand training was done while backstabbing.

**Comment by OdnaZvezda** [comment]
I apologize for my lack of github knowledge(pull requests/code submissions), but I have a working solution(tested with thief and non-thief characters).   This solution would require users to know whether they have a suitable backstabbing offhand weapon in their setup.yaml.  Likewise, a small/medium edged weapon over 30 stones isn't suitable for mainhand backstabbing so I'm not sure this case is much different.

http://pastebin.com/a4KW61yW

**Comment by rpherbig** [comment]
I'll run this overnight to test.

**Comment by OdnaZvezda** [comment]
I noticed this morning that offhand attacks were just doing "attack"

This should fix that
http://pastebin.com/GQAGudqs
