### ISSUE TITLE
Combat-trainer hanging

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#1640]
Combat trainer has been hanging specifically on my barb only.  Happened like 3 times in the past few days, coincidentally maybe since adding whirlwind, but was able to log the problem this most recent time.  When I stowed my spike the script restarted and got the spike out again:

[combat-trainer]>berserk tornado

But you are already enraged with that berserk.
> 
[combat-trainer]>roar everild

The fury of Everild's Rage burns in your soul, and your roar is filled with that fury.  Rage intimidates, and fear weakens.  Foes shall fall before you, weakened and humiliated by the expression of your strength.
A warklin mauler appears less confident in its ability to defend itself.
Roundtime: 2 sec.
R> 
R> 
* As if effort and skill were a bad thing, an armored warklin snaps its mandibles at you.  You dodge, with a practiced hand.  
[You're incredibly balanced and overwhelming your opponent.]
R> 
[combat-trainer]>jab

< Moving with indomitable grace, you jab a glaes bastard sword at a warklin mauler.  A warklin mauler attempts to dodge, only partially avoiding the impact.  
The sword lands a light hit (1/23) to the mauler's left leg.
[You're incredibly balanced and overwhelming opponent.]
[Roundtime 2 sec.]
R> 
R> 
R> 
[combat-trainer]>stance set 0 100 87

Setting your Evasion stance to 0%, your Parry stance to 100%, and your Shield stance to 87%.  You have 0 stance points left.
> 
[combat-trainer]>jab

< Moving with indomitable grace, you jab a glaes bastard sword at a warklin mauler.  A warklin mauler attempts to dodge, only partially avoiding the impact.  
The sword lands a light hit (1/23) to the mauler's chest.
[You're incredibly balanced and overwhelming opponent.]
[Roundtime 2 sec.]
R> 
R> 
R> 
[DRPrime]-DR:Ivalde: "Oh fair"

* Apparently without direction or thought, a warklin mauler rears back and slashes its impaler at you.  You partially block with a metal target shield.  
[You're incredibly balanced and in dominating position.]
R> 
* Moving in like a timid schoolboy, a warklin mauler slices wide at you.  You block with a metal target shield.  
[You're incredibly balanced and overwhelming your opponent.]
R> 
* As if effort and skill were a bad thing, a warklin mauler rears back and slashes its impaler at you.  You partially block with a metal target shield.  
[You're incredibly balanced and in dominating position.]
R> 
[combat-trainer]>jab

< Moving as a single sinuous force, you jab a glaes bastard sword at a warklin mauler.  A warklin mauler fails to evade, avoiding only some of the blow.  
The sword lands a light hit (1/23) to the mauler's right leg.
[You're incredibly balanced and overwhelming opponent.]
[Roundtime 2 sec.]
R> 
R> 
R> 
* Looking as if this were a bad idea, an armored warklin lunges with its razorlike mandibles at you.  You knock aside some of the mandibles with a glaes bastard sword.  
[You're incredibly balanced and overwhelming your opponent.]
R> 
[combat-trainer]>jab

< Moving with the precision of a mongoose, you jab a glaes bastard sword at a warklin mauler.  A warklin mauler fails to evade, only partially avoiding the impact.  
The sword lands a good hit (2/23) to the mauler's left arm.
[You're incredibly balanced and overwhelming opponent.]
[Roundtime 2 sec.]
R> 
R> 
[combat-trainer]>tie my bastard.sword to straps

You attach a glaes bastard sword to your reinforced straps.
> 
[combat-trainer]>get my throwing.spike

You get a throwing spike from inside your spidersilk backpack.
> 
> 
> 
> 
[combat-trainer]>swap my spike

A warklin mauler drones a low-pitched humming cadence.
> 
* Apparently without direction or thought, a warklin mauler rears back and slashes its impaler at you.  You block with a metal target shield.  
[You're incredibly balanced and overwhelming your opponent.]
> 
* Moving in like a timid schoolboy, a warklin mauler rears back and slashes its impaler at you.  You partially block with a metal target shield.  
[You're incredibly balanced and overwhelming your opponent.]
> 
You turn your spike easily in your hands and end with it in position to be used as a light thrown and light blunt weapon.
> 
[combat-trainer]>get my throwing.spike

You are already holding that.
> 
> 
> 
> 
* As if effort and skill were a bad thing, an armored warklin lashes its scythe-bladed foreleg at you.  You beat off some of the foreleg with a throwing spike.  
[You're incredibly balanced and overwhelming your opponent.]
> 
> 
> 
> 
* Moving in like a timid schoolboy, a warklin mauler screams a strange battle-cry and stabs its impaler at you.  You block with a metal target shield.  
[You're incredibly balanced and overwhelming your opponent.]
> 
* Moving in like a timid schoolboy, a warklin mauler twists its torso wildly, thrusting its impalers at you.  You slap away some of the impaler with a throwing spike.  
[You're incredibly balanced and in dominating position.]
> 
> 
> 
* Looking as if this were a bad idea, an armored warklin lunges with its razorlike mandibles at you.  You partially block with a metal target shield.  
[You're incredibly balanced and overwhelming your opponent.]
> 
* Awkwardly, a warklin mauler screams a strange battle-cry and stabs its impaler at you.  You partially block with a metal target shield.  
[You're incredibly balanced and overwhelming your opponent.]
> 
> 
> 
> 
> 
> 
* Looking as if this were a bad idea, a warklin mauler twists its torso wildly, thrusting its impalers at you.  You partially block with a metal target shield.  
[You're incredibly balanced and overwhelming your opponent.]
> 
A warklin mauler drones a low-pitched humming cadence.
> 
> 
* Moving well, an armored warklin snaps its mandibles at you.  You badly fail to block with a throwing spike.  
The mandibles lands a brushing (0/23) hit to your chest.
[You're incredibly balanced and overwhelming your opponent.]
> 
* Tentatively, a warklin mauler screams a strange battle-cry and stabs its impaler at you.  You slap away some of the impaler with a throwing spike.  
[You're incredibly balanced and overwhelming your opponent.]
> 
> 
> 
> 
* Moving in like a timid schoolboy, a warklin mauler screams a strange battle-cry and stabs its impaler at you.  You block with a metal target shield.  
[You're adeptly balanced and overwhelming your opponent.]
> 
[DRPrime]-DR:Flyntt: "WM wouldn't get Nexus because that is the same as their mana booster."

> 
> 
* As if effort and skill were a bad thing, an armored warklin lunges with its razorlike mandibles at you.  You knock aside some of the mandibles with a throwing spike.  
[You're adeptly balanced and in very strong position.]

> 
[hunting-buddy: ***STATUS*** 52 minutes of hunting remaining or waiting on Polearms]

**Comment by elBlanquito** [comment]
Same thing happened to me last night, but I was too tired to report it (sorry!), and just turned on crossing-train instead. meow.

**Comment by rcuhljr** [comment]
You're not trying to use the spike with WW are you?

**Comment by mwest152** [comment]
it is my small blunt and small edge for whirlwind.  Should i use something else?

**Comment by rcuhljr** [comment]
WW doesn't currently work with swappables.

**Comment by mwest152** [comment]
Ah good to know, need to replace everything :p.  My set is the Cidemon special.
