### ISSUE TITLE
"Special" ironwood tree in 1514 is breaking chop-wood/forestry-buddy

### ISSUE THREAD

**Issue by jonathan-stricker** [rpherbig/dr-scripts#1641]
R>l
[Dense Forest]
Ancient ferns grow in abundance here, flourishing on the rich, dark forest floor shaded by lofty satinwood trees.  Their graceful fronds quiver and sway, moved by light breezes.  You also see a cougar, an ancient ironwood tree, a cougar and a cougar.
Obvious paths: east, southeast, south.
Room Number: 1514
R>
R>;chop-wood
--- Lich: chop-wood active.
R>
[chop-wood]>stow right
You put your axe in your hunter's rucksack.
>
[chop-wood]>get my axe
You get a steel battle axe from inside your hunter's rucksack.
>
[chop-wood]>chop tree
>
With wide arcs you smash your battle axe into the trunk looming before you.
Roundtime: 6 sec.
R>
[chop-wood]>get my packet
You get a packet of deed claim forms from inside your hunter's rucksack.
>
[chop-wood]>push Ironwood tree with my packet
That does not look like something that can be deeded.
>

**Comment by MahtraDR** [comment]
Closing. Nobody's complained in 4 years...
