### ISSUE TITLE
combat-trainer error when using Carrion Call spell

### ISSUE THREAD

**Issue by VorareDR** [rpherbig/dr-scripts#1644]
Getting error dump below after each cast of carrion call.  My guess is it has to do with the custom gesture messaging not being in the match logic.

**You lift your right hand, forming your claws into the shape of a vulture's talons.**
Your cambrinth pivuh emits a loud *snap* as it discharges all its power to aid your spell.
With the deep, hissing growl of a hungry vulture, cascading streams of deep purple energy come into being, swirling menacingly around the shadow mage!
The streams of energy rake against an Adan'f shadow mage's abdomen, leaving severe gashes behind.  In an accelerated process of decay, all flesh and sinew drop or evaporate from the exposed bone, leaving only bone behind!
The shadow mage is knocked completely senseless!
Roundtime: 1 sec.

[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 33]
[combat-trainer: message: An Adan'f shadow mage gestures at you.]
[combat-trainer: message: A noose of darkest shadows forms in an Adan'f shadow mage's hands.  With a flick of its wrist, it sends it flying at you!]
[combat-trainer: message: The noose misses completely!]
[combat-trainer: message: You lift your right hand, forming your claws into the shape of a vulture's talons.]
[combat-trainer: message: Your cambrinth pivuh emits a loud *snap* as it discharges all its power to aid your spell.]
[combat-trainer: message: With the deep, hissing growl of a hungry vulture, cascading streams of deep purple energy come into being, swirling menacingly around the shadow mage!]
[combat-trainer: message: The streams of energy rake against an Adan'f shadow mage's abdomen, leaving severe gashes behind.  In an accelerated process of decay, all flesh and sinew drop or evaporate from the exposed bone, leaving only bone behind!]
[combat-trainer: message: The shadow mage is knocked completely senseless!]
[combat-trainer: message: Roundtime: 1 sec.]
[combat-trainer: message: You feel fully rested.]
[combat-trainer: message: You feel fully attuned to the mana streams again.]
[combat-trainer: message: The shadow mage sways on its feet, its staff held loosely in its hand.]
[combat-trainer: message:           SKILL: Rank/Percent towards next rank/Amount learning/Mindstate fraction]
[combat-trainer: message:          Sorcery:    163 48.96% very engaged  (23/34)]
[combat-trainer: message: Time Development Points: 151  Favors: 0  Deaths: 32  Departs: 5]
[combat-trainer: message: Overall state of mind: clear]
[combat-trainer: message: EXP HELP for more information]
[combat-trainer: message: The blood warrior roars in challenge, "Adan'f lusss!  Adan'f lusss!"]
[combat-trainer: message: The blood warrior moves into a position to dodge.]
[combat-trainer: message: An Adan'f shadow mage gestures at you.]
[combat-trainer: message: A noose of darkest shadows forms in an Adan'f shadow mage's hands.  With a flick of its wrist, it sends it flying at you!]
[combat-trainer: message: The noose glances off your round sipar.]
[combat-trainer: message: The noose barely touches your chest, leaving a paper-thin cut.]
[combat-trainer: message: * Awkwardly, an Adan'f shadow mage sidesteps and bashes at you.  You evade.  ]
[combat-trainer: message: [You're bruised, nimbly balanced with opponent in better position.]]
[combat-trainer: message: * Moving in like a timid schoolboy, an Adan'f blood warrior bashes a srhhtel hammer at you.  You block solidly with a round sipar.  ]
[combat-trainer: message: [You're bruised, nimbly balanced and in good position.]]
[combat-trainer: message: Your body feels slightly battered.]
[combat-trainer: message: Your spirit feels full of life.]
[combat-trainer: message: You have no significant injuries. ]
[combat-trainer: message: The shadow mage sways on its feet, its staff held loosely in its hand.]
[combat-trainer: message: * In a weak and directionless display of aggression, an Adan'f shadow mage slices a glowing skull-tipped staff at you.  You dodge.  ]
[combat-trainer: message: [You're bruised, nimbly balanced with opponent in strong position.]]
[combat-trainer: checked against [/^Your spell backfires/i, /Your spell barely backfires/i, /You strain, but are too mentally fatigued/i, /^You gesture/i, /A soft silver glow envelops/i, /You listen intently to the air/i, /You close (your|yours) eyes/i, /Your target pattern dissipates/i, /You make a .* gesture/i, /You raise your (left|right) hand skyward/i, /Flickering shadows tear away/i, /You sense a Malediction/i, /You release an accompaniment/i, /You roll your hands in an elliptical pattern/i, /You (cup|wave|raise) your hand/i, /You flicker your malevolent desires towards/i, /You clench your hands into fists and grit your teeth/i, /Tendrils of flame dart along your hand/i, /Invisible strands of air twist/i, /The flames dancing along your fingertips/i, /^You can't cast that at yourself/i, /^You need to specify a body part to consume/i, /You breathe deeply, centering your energies/i, /You strike your heel against the ground/i, /You clasp your hands together/i, /With a wave of your hand/i, /Your words fill you with an unflagging sense of resolve and purpose/i, /A renewed sense of purpose fills you/i, /You clench your fist and mutter a whispered/i, /You call forth the dark will of the divine/i, /^Your heart skips a beat/i, /You whisper the final word of your spell/i, /^You rebuke a/i, /You clap (you|your) hands/i, /You are pulled through your unstable Moongate/i, /You thrust your/i, /Your mind races/i, /You draw forth a pulse of/i, /A crackling mantle of blazing orange-yellow flames/i, /You speak a few words of righteousness/i, /You give sudden voice/i, /You hold out your arms/i, /^With a slight flick, you point one of your fingers/i, /^You reach (out|up with|with your|one hand|with both)/i, /You place your hands on your temples/i, /Using your left hand, you channel the spell's energies and gesture/i, /You steeple your fingers together/i, /You successfully weave the .* spell into the receptive aura of the orb/i, /The energy contained in your ritual flutters away impotently as it seeks the open skies/i, /At the ritual's peak, your prophetic connection blooms a thousand-fold/i, /Traces of your prior ritual still linger about you/i, /You swipe your fingertips/i, /^Your spirit lashes out/i, /You open your arms in a hieratic gesture/i, /^A (white|silver) static/i, /^A (glowing amber|crimson) mist/i, /^Disregarding the pain, you grind the dirt brutally into the palm of your hand/i]]

**Comment by rcuhljr** [comment]
90% no cast message, 10% carrion call being a terrible spell :) pushed a fix.

**Comment by VorareDR** [comment]
killed and restarted dependency and i'm still getting the same error.  checked my data directory and i see the update to base-spells.yaml
