### ISSUE TITLE
High Social Outrage Global Settings and High Social Outrage Allowable Town Tasks

### ISSUE THREAD

**Issue by brycole** [rpherbig/dr-scripts#1645]
Hiya!

I want to compile a list of all town functions that are or are not affected by high social outrage.

Not:
Repairing (might want to test more repair locations just in case)
Withdrawing Money 

YES:
Exchanging Money
Depositing Money

Please add any town functions that you think may or may not be triggered by social outrage.

I'm also thinking about the best way to add.  I was thinking a YAML setting initially but a $global might be better with an event flag to set.

@jandersson

**Comment by Morzain** [comment]
YES:
buying lockpicks
buying anything probably
using vaults

Not:
Selling gems
Selling bundles
training stats
paying debt.

**Comment by jandersson** [comment]
Can't use an empath

**Comment by izawwlgood** [comment]
Afaik dependency will prevent you from going to autopuffs so long as it recognizes you're a necro. 

Similarly if you set sell gems and bundles to false that solves that. So really it's just crossing repair and banking that need to be addressed?

**Comment by jandersson** [comment]
It does, though if you run to the empath with high SO as a non-necro, empaths still want you to go to jail

**Comment by jandersson** [comment]
Though to be fair the above situation was me being an idiot and setting my sorcery training to a town room.

**Comment by intangibles** [comment]
Well, there are plenty of reasons why you might have SO due to non-idiot situations.  :)  Like necros Fighting in Town or being accused by people.

**Comment by jandersson** [comment]
Agreed, but i think me setting `high_social_outrage=true` since I was being forgetful. Thats another issue though; how to check social outrage.

**Comment by intangibles** [comment]
Yeah, I was thinking about this too.  We could do a $global variable with a trigger/flag on the common SO messages (burn him, etc) and have that set the high_social_outrage variable (or YAML setting.) We also could do a justice check (perhaps as part of a non-SO task like withdrawal) to confirm social_outrage.

**Comment by jandersson** [comment]
Brainstorming, but I'd add the `justice` to command to initialization of drinfomon and record that as your SO status. If the events script exists (for Flag class), add a flag for that `burn em!` messaging [if the user doesn't have dependency installed the events script wont exist]. Use a method in drinfomon to update your SO status based on this flag.

**Comment by izawwlgood** [comment]
This is kind of an issue of what the user sets. If they try and train
sorcery in justice, that's on them I suppose. Presenting the only setting
that I feel needs additional control would be depositing coin.

Afk has a setting for number of arrest, which should help prevent getting
in spirals. It would be nice to have a setting that prevents some town
services too, but I would not want this automated. For example, all my
necro does in town is deposit coin. Storing pouches and bundles is also a
solution for avoiding these town services.

**Comment by MahtraDR** [comment]
Closing this. We have a lot of issues to work on today, and this has had zero additional interest in four years.
