### ISSUE TITLE
;validate shows no problems with YAML & Parser shows it good to go, but it's terminating mid-combat with this exception!

### ISSUE THREAD

**Issue by elBlanquito** [rpherbig/dr-scripts#1647]
[combat-trainer]>hide
You melt into the background, convinced that your attempt to hide went unobserved.
Roundtime: 4 sec.
The fire maiden searches around for a moment.
The fire maiden searches around for a moment.
[combat-trainer]>attack
...wait 1 seconds.
[combat-trainer]>attack
You leap out of hiding and ambush a fire maiden, completely surprising it.
< You thrust a steel throwing spike at a fire maiden.  A fire maiden knocks aside little of the spike with a scorched greatsword.  
[You're solidly balanced with no advantage.]
[Roundtime 5 sec.]
--- Lich: error: comparison of Fixnum with Array failed
	combat-trainer:960:in `<='
	combat-trainer:960:in `block in check_buffs'
--- Lich: combat-trainer has exited.
* Tentatively, a fire maiden feints low at you.  You evade, with a practiced hand.  
[You're solidly balanced with no advantage.]

**Comment by elBlanquito** [comment]
Is it because :adjective: throwing is stored in Array but there is no match? What does this error mean?  error: comparison of Fixnum with Array failed
combat-trainer:960:in <=' combat-trainer:960:inblock in check_buffs'

**Comment by rcuhljr** [comment]
Submit your setup yaml, it looks like there's something messed up with your buffs, most likely you have bad data around a recast: setting in one of your buff spells.

**Comment by elBlanquito** [comment]
priority_skills_lower_limit: 0
training_manager_hunting_priority: true
training_manager_priority_skills:
- Targeted Magic
- Small Edged
- Staves
- Large Edged
- Debilitation
- Shield Usage

hunting_info:
- :zone: fire_sprites1
  :duration: 25
  args:
  - d1
  stop_on:
  - Debilitation
  - Shield Usage

weapon_training:
  Targeted Magic: ''
  Small Edged: throwing spike
  Large Edged: abassi 
  #Light Thrown: bola
  Staves: cane
  
  
dance_skill: Small Edged

exp_timers:
  #Stealth: 300
  First Aid: 360
  Attunement: 130
  Astrology: 210
  #Thievery: 600

# Gear settings
gear:
# - :adjective: example
#   :name: gear
#   :is_leather: true
#   :hinders_lockpicking: false
#   :is_worn: true
- :adjective: coarse
  :name: cowl
  :is_leather: true
  :hinders_lockpicking: true
  :is_worn: true
- :adjective: 
  :name: shield
  :is_leather: true
  :hinders_lockpicking: true
  :is_worn: true
- :adjective: coarse 
  :name: gloves
  :is_leather: true
  :hinders_lockpicking: true
  :is_worn: true
- :adjective: 
  :name: leathers
  :is_leather: true
  :hinders_lockpicking: true
  :is_worn: true
- :adjective: parry
  :name: stick
  :is_leather: false
  :hinders_lockpicking: true
  :is_worn: true
- :adjective:
  :name: knuckles
  :is_leather: false
  :hinders_lockpicking: true
  :is_worn: true
- :adjective: elbow
  :name: spikes
  :is_leather: false
  :hinders_lockpicking: false
  :is_worn: true
- :adjective: 
  :name: sabre
  :is_leather: false
  :hinders_lockpicking: false
  :is_worn: false
- :adjective: 
  :name: abassi
  :is_leather: false
  :hinders_lockpicking: false
  :is_worn: false
- :adjective: 
  :name: cane
  :is_leather: false
  :hinders_lockpicking: false
  :is_worn: true
- :adjective: 
  :name: bola
  :is_leather: false
  :hinders_lockpicking: false
  :is_worn: false
- :adjective: throwing
  :name: spike
  :is_leather: false
  :hinders_lockpicking: false
  :is_worn: false
  :swappable: true

gear_sets:
  standard:
  - coarse cowl
  - coarse gloves
  - leathers
  - parry stick
  - knuckles
  - elbow spikes
  - cane
  - shield
  
  stealing:
  - parry stick
  
offensive_spells:
- skill: Targeted Magic
  name: Dinazen Olkar
  abbrev: do
  cast_only_to_train: false
  mana: 3
  cambrinth:
  - 3
- skill: Debilitation
  name: Calm
  target_enemy:
  abbrev: calm
  mana: 1
  cambrinth:
  - 1
  
use_stealth_attacks: true
have_telescope: true
#tk_ammo: dart

buff_spells:
  Shadows:
    abbrev: shadows
    mana: 29
    recast: 1
    cambrinth:
    - 5
    harmless: true
  Seer's Sense:
    abbrev: seer
    mana: 20
    recast: 1
    harmless: true
    cambrinth: 
    - 5
  Clear Vision:
    abbrev: CV
    recast: 
    - 1
    mana: 30
    cambrinth:
    - 5
    harmless: true
  Courage:
    abbrev: Courage
    recast: 1
    mana: 8
    cambrinth:
    - 2
    harmless: true
  Tenebrous Sense:
    abbrev: TS
    recast: 1
    mana: 20
    cambrinth:
    - 5
    harmless: true  
  Aura Sight:
    abbrev: aus
    recast: 1
    mana: 15
    cambrinth:
    - 10
    harmless: true
  Piercing Gaze:
    abbrev: PG
    recast: 1
    mana: 20
    cambrinth:
    - 5
    harmless: true
  Cage of Light:
    abbrev: COL
    recast: 1
    mana: 7
    cambrinth:
    - 5
    harmless: true

charged_maneuvers:
  Brawling: palmstrike
  Bow: powershot
  Slings: powershot
  Small Edged: cleave
  Large Edged: cleave
  Twohanded Edged: cleave
  Small Blunt: crash
  Large Blunt: crash
  Twohanded Blunt: crash
  Staves: twirl
  Polearms: impale

training_abilities:
  Hunt: 80
  PercMana: 240
  Stealth: 60
  Astro: 300
  App Quick: 60
  Tactics: 30
  Collect: 120
  Perc: 123
  Analyze: 121
  Ambush Stun: 35
  Recall: 600


#cyclic_training_spells:
 # Utility:
  #  abbrev: RF
   # cyclic: true
#cyclic_cycle_skills:
#- Utility

fatigue_regen_threshold: 85
fatigue_regen_action: bob

prep_scaling_factor: 0.71
listen: true

skinning:
  skin: true
  arrange_all: false
  arrange_count: 0
  tie_bundle: true

crossing_training:
- Outdoorsmanship
- Augmentation
- Astrology
- Appraisal
- Utility
- Mechanical Lore
- Warding
- Athletics
- Perception
- Attunement
- Scholarship
- Outdoorsmanship
- First Aid
#- Locksmithing

cambrinth: brooch
cambrinth_cap: 5
held_cambrinth: false
stored_cambrinth: false
safe_room: 851
favor_goal: 75
favor_god: Meraud

#hometown: Shard
hometown: Crossing
#hometown: Therenborough

gem_pouch_adjective: black
spare_gem_pouch_container: rucksack
sell_loot_pouch: true

sell_loot_bundle: true

storage_containers:
- rucksack

hand_armor: coarse gloves

sell_loot_pouch: false

training_spells:
  Augmentation:
    abbrev: seer
    symbiosis: false
  Warding:
    abbrev: COL
    symbiosis: false
  Utility:
    abbrev: pg
    symbiosis: false

hide_to_steal: true
bin_stolen: false
stealing_bag: rucksack

lockpick_type: stout
harvest_traps: false

loot_bodies: true


loot_additions:
#scroll types
- scroll
- papyrus roll
- parchment
- hhr'lav'geluhh bark
- clay tablet
- wax tablet
- faded vellum
- papyrus roll
- seishaka leaf
#nuggets
- gold nugget
- platinum nugget
- lumium nugget
- ninium nugget
#- electrum nugget
- muracite nugget
- darkstone nugget
- damite nugget
- kertig nugget
- haralun nugget
- glaes nugget
- animite nugget
#- covellite nugget
#- oravir nugget
#other bullshit
- package
- gold ring
- kirmhiro draught
- signet ring
- witch ball
- satin pillow
- license
- writ
- permit
- pass
- profile
- seastars
- pendant
- jasper
- heliodor
- tasialm
- seastar
- pulzones
- quadrello


loot_subtractions:
- coffer
- strongbox
- chest
- caddy
- trunk
- casket
- skippet
- crate
- box
- card
- arrow
- rock
- rocks
- arrows

dump_junk: true

aim_fillers:
  Crossbow:
  - circle
#  - weave
#  - bob
  Bow:
  - circle
  - weave
  - bob
  Slings:
  - circle
  - weave
  - bob

# RESEARCH
use_research: false
#research_skills:
# - Elemental Magic
# - Arcana
# - Utility
# - Augmentation
# - Warding

# LOCKPICKING
picking_box_source: rucksack
picking_box_storage: rucksack
harvest_traps: false
picking_pet_box_source: rucksack
lockpick_type: stout
lockpick_dismantle: fire
stop_pick_on_mindlock: true

astrology_buffs:            
  spells:                   
    - abbrev: pg            
      mana: 12              
      cambrinth:            
      - 5
    - abbrev: aus           
      mana: 15            
      cambrinth:            
      - 5
#    - abbrev: dc           
#      mana: 550             
#      focus: abacus        
#      worn_focus: false      
#    - abbrev: rtr          
#      mana: 550            
#      focus: abacus        
#      worn_focus: false   

textbook: false
#textbook_type: treatise
mine_for_outdoorsmanship: false
braid_item: grass


#Moon Mage Enchanting Notes
# https://pastebin.com/ddQiUL2W

**Comment by rcuhljr** [comment]
```
  Clear Vision:
    abbrev: CV
    recast: 
    - 1
    mana: 30
```

There ya go, that's not a valid entry for recast.

**Comment by elBlanquito** [comment]
Wow! Thank you very much--I appreciate the fresh eyes. I'm surprised ;validate didn't cite that as an error.
