### ISSUE TITLE
Pray Pilgrim Badge during hunting for Paladins

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#1650]
Paladins lose Soul strength as time passes if no soul boosting actions are done.  It would be great if we could put Pray Badge on a timer so that our characters could keep our Soul level maxed out.  According to Elanthipedia (https://elanthipedia.play.net/Soul_system), the timer for soul boost on praying to a pilgrim badge is 31 minutes.  So perhaps it could just be done before or after the TRAINING-MANAGER runs the Tithe script.  It can also be done during combat while holding a weapon in the other hand if that's easier.    

Below is how the text looks on it:

R>tap pilgrim badge
You tap a pilgrim's badge that you are wearing.

R>remove badge
You take off a pilgrim's badge.

R>pray badge
You think upon the immortals, and the holy places built in their honor by mortals who have heard them speak, or seen the power of their beings.
As you feel your connection to them grow, you sense the eyes of the gods upon you.
Roundtime: 10 sec.
A warm, soothing sensation washes over your soul.
You feel a strengthening of your faith and bolstering of your soul.

R>wear badge
You put on a pilgrim's badge.

**Comment by rpherbig** [comment]
We've got `pray badge` logic in `theurgy`, so it shouldn't be hard to extract.

That said, we already support tithing which can keep a paladin at max soul state. Is there a big gain to be had by implementing this?

**Comment by BastionWT** [comment]
Yes please!

**Comment by wscherer420** [comment]
Thought i had replied to your question about already having the Tithe option.  It is my experience that Tithe runs you all the way back to crossings to execute.  So if you live in any other hometown it would be cumbersome to run all the way to crossings.  The pray badge option could be done anywhere and could technically replace the need for Tithe.  I've turned off Tithe because after hunting near Shard or Hib, it would run me all the way to crossings.  It's been awhile since i last tried Tithe, so not sure if its been adjusted at all to accommodate Tithe boxes in other towns (that is if Tithe boxes exist in other towns?)

**Comment by wscherer420** [comment]
Just trying to bump this request :)

**Comment by jayRyan24** [comment]
This was completed with: #2331
