### ISSUE TITLE
UTILITY added to be used with before: 

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1651]
[hunting-buddy: ***STATUS*** EXECUTE Utility]
[hunting-buddy: *** Failed to find a script named 'Utility' ***]
[hunting-buddy: *** Please report this to Etreu, Sheltim, or https://github.com/rpherbig/dr-scripts/issues  ***]
--- Lich: could not find script 'Utility' in directory C:/LICH/scripts

Was for my moonie, but also any guild would be nice

**Comment by rpherbig** [comment]
@Aurayn Do you have a script named `Utility.lic`?

**Comment by Aurayn** [comment]
Negative

**Comment by jandersson** [comment]
are you running `before` or `after` arguments with utility?

**Comment by Aurayn** [comment]
was trying both

**Comment by intangibles** [comment]
@Aurayn 

before: and after: are for custom scripts.

You have to a script called "utility.lic" and put into your script folder.

--- Lich: could not find script 'Utility' in directory C:/LICH/scripts

**Comment by jandersson** [comment]
Yea it seems like you want to train Utility magic? however that's part of the `crossing-trainer` script

**Comment by Aurayn** [comment]
yes I want to force train it before and after hunting independent of crossing-tr

**Comment by intangibles** [comment]
@Aurayn 

Right. So you want someone to make you a Utility Script independent of crossing-trainer.   This is probably not going to happen within dependency.  I'd advise making your own.  Or, I'd suggest exploring the options available within dependency.  I'm fairly confident there is already an option to do whatever it is you want done with Utility magic.

There are already several ways built into dependency scripts to train utility. You can use crossing-training or you can use combat-trainer (combat_spell_training.)   Combat is also the preferred choice for many people to train magic.  You can also take advantage of the cyclic options too if you have a cyclic utility.

**Comment by Aurayn** [comment]
yep sounds like I am out of luck there... ok thanks.

**Comment by rpherbig** [comment]
It shouldn't be too hard to make your own utility trainer if you're willing to tinker a bit. I realize you're not a coder, but this would be a good time to experiment :) There are lots of coders on LNet that could help answer questions.

`Common-arcana` has the helper functions you need, so it would be a matter of chaining them together:

- prepare?(abbrev, mana)
- find_charge_invoke_stow(cambrinth, stored_cambrinth, cambrinth_cap, dedicated_camb_use, charges)
- cast?()
