### ISSUE TITLE
`loot_bodies: false` prevents ending a hunt

### ISSUE THREAD

**Issue by Traik404** [rpherbig/dr-scripts#1653]
At cave trolls, hunting buddy quits fine after 15 minutes.
At Germishdin, it keeps fighting forever.

At first I thought it was forever trying to kill the last mob before leaving, but the logs show it killing multiple germishdin and still never trying to retreat.

Yaml: https://pastebin.com/XqacEqQQ
Logs: https://pastebin.com/hsvgcvav

**Comment by rcuhljr** [comment]
Looks like setting `loot_bodies: false` disables skinning and looting, and prevents it from ever noticing that mobs have died.

**Comment by Traik404** [comment]
Thanks!

**Comment by Traik404** [comment]
Any way to have it register dead monsters besides looting?

**Comment by rcuhljr** [comment]
No, but that seems like a bug we should probably find a fix for.

**Comment by Traik404** [comment]
I turned looting on and it fixed it, you were correct!

**Comment by jayRyan24** [comment]
Can you rename this issue to something more appropriate as it is definitely a bug. 

Thanks!

**Comment by rpherbig** [comment]
@Traik404 #1884 was just merged which introduces a new setting, `skip_last_kill`, which should fix with this.

**Comment by MahtraDR** [comment]
@rpherbig Close?
