### ISSUE TITLE
Bescort - Blue belly crocs near riverhaven

### ISSUE THREAD

**Issue by tdbrown1985** [rpherbig/dr-scripts#1658]
When attempting to leave crocs bescort does "go reed" in the room I'm hunting in but then only attempts to move south after that. While moving south, it does not attempt to 'go reed' ever again and continues in an endless loop of going south.

**Comment by tulanegator** [comment]
Is this a constant problem or did it correct after restarting lich?

**Comment by tdbrown1985** [comment]
Corrected after restarting

**Comment by jandersson** [comment]
Don't forget to close the issue if its no longer occurring

**Comment by BastionWT** [comment]
BTW, this "broke" for me days ago.

I had "reeds" on my character, a stolen item that hadn't been binned. Broke in the same manner as the above, just in case that happens to be your issue as well.
