### ISSUE TITLE
Some startup errors

### ISSUE THREAD

**Issue by reithir** [rpherbig/dr-scripts#1659]
the log commanded me to file an issue, so I am. ;) Just restarted my toon and was this stuff came up:

[You are standing up.]
>
--- Lich: lnet has exited.
--- Lich: dependency active.
--- Lich: alias service started
[repository: map database is up-to-date]
[repository: done]
[repository: scripts are up-to-date]
--- Lich: repository has exited.
[bootstrap: *** Failed to find a script named 'spell-monitor' ***]
[bootstrap: *** Please report this to Etreu, Sheltim, or https://github.com/rpherbig/dr-scripts/issues  ***]
[bootstrap: *** Failed to find a script named 'roomnames' ***]
[bootstrap: *** Please report this to Etreu, Sheltim, or https://github.com/rpherbig/dr-scripts/issues  ***]
[bootstrap: *** Failed to find a script named 'roomname' ***]
[bootstrap: *** Please report this to Etreu, Sheltim, or https://github.com/rpherbig/dr-scripts/issues  ***]

**Comment by rpherbig** [comment]
I think you have some typos in your autostart list.

There is no `spell-monitor`, it is `spellmonitor` (note the lack of a dash). There is no `roomnames` or `roomname`, but there is a `roomnumbers`.

**Comment by reithir** [comment]
Oh yes, duh. When it told me it couldn't find that script I assumed it just didn't add it, I clear out my bad tries. Sorry. ;-)
