### ISSUE TITLE
Add flags/yaml settings to set materials for ;workorders

### ISSUE THREAD

**Issue by jonathan-stricker** [rpherbig/dr-scripts#1661]
instead of the default of buying bronze for blacksmithing or balsa for shaping, it would be nice to have a global YAML setting to choose what metal/wood/stone/whatever to buy (including what number it is in the order list). If left blank it can run the way it runs now but you can set it to something else; that way if someone wanted a harder or more expensive material they could just set it.

Just wanted to see if anyone wanted to tackle this, I'm going to start learning some ruby to try to help out with development, but if anyone wants to put this together in the short run I'd be grateful. :)

**Comment by MahtraDR** [comment]
Closing this, because today we can choose recipes for workorders, which in turn dictates materials.
