### ISSUE TITLE
attunement powerwalking my moonie

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#1666]
On my moon mage attunement script used to just perc and perc self, or whatever it was that was on separate timers.  Now it is trying to powerwalk and giving me match errors.  Not sure when this started, probably really recently.

--- Lich: go2 has exited.

[attunement]>perc

> 
Yavash is dominant, while Katamba and Xibar's influences are moderate.
Perception and Enlightened Geometry spells are favored.
You sense the Shadows spell upon you, which will last for about thirty roisaen.
You sense the Manifest Force spell surrounding you, which will last for twenty-nine roisaen or until it has endured six more blows.
You sense the Shadowling spell upon you, which will last for about sixty-four roisaen.
You sense the Seer's Sense spell upon you, which will last for about twenty roisaen.
Roundtime: 3 sec.
R> 
[attunement: *** No match was found after 15 seconds, dumping info]

[attunement: messages seen length: 15]

[attunement: message: Yavash is dominant, while Katamba and Xibar's influences are moderate.]

[attunement: message: Perception and Enlightened Geometry spells are favored.]

[attunement: message: Shadows  (30 roisaen)]

[attunement: message: Manifest Force  (29 roisaen)]

[attunement: message: Shadowling  (64 roisaen)]

[attunement: message: Seer's Sense  (20 roisaen)]

[attunement: message: You sense the Shadows spell upon you, which will last for about thirty roisaen.]

[attunement: message: You sense the Manifest Force spell surrounding you, which will last for twenty-nine roisaen or until it has endured six more blows.]

[attunement: message: You sense the Shadowling spell upon you, which will last for about sixty-four roisaen.]

[attunement: message: You sense the Seer's Sense spell upon you, which will last for about twenty roisaen.]

[attunement: message: Roundtime: 3 sec.]

[attunement: message: Shadows  (30 roisaen)]

[attunement: message: Manifest Force  (29 roisaen)]

[attunement: message: Shadowling  (63 roisaen)]

[attunement: message: Seer's Sense  (20 roisaen)]

[attunement: checked against [/You reach out/i]]

--- Lich: go2 active.

[go2: ETA: 0:00:00 (1 rooms to move through)]

[go2]>east

You meander east.

**Comment by jandersson** [comment]
Type `info` in game and see if it still does it. It may have 'forgotten' that you were an MM.

**Comment by jandersson** [comment]
Are you still experiencing this?

**Comment by mwest152** [comment]
I actually had taken attunement out and replaced it with a simple script,
since Moonie attunement is pretty basic.  I'll test it out later today.

**Comment by mwest152** [comment]
issue fixed or resolved itself
