### ISSUE TITLE
Experimental Narost build with better map organization and other features

### ISSUE THREAD

**Issue by dewiniaid** [rpherbig/dr-scripts#1667]
Raelok said I should post an issue over here.

I'm working on an fork of Narost (current working name xnarost) that organizes the map menu better.  (Future plans include an extended right-click menu when you click on a room to allow it to call arbitrary scripts with the room number included -- e.g. for integration with ;wander and other such scripts).

Sample of the map organization: http://i.imgur.com/ottkilJ.png

I'm crowdsourcing GS4 map data on a Google Docs spreadsheet which feeds into the script.  It occured to me that this might be useful for DR players, so I'm inviting contributions.

Here's a copy (renamed for DR, but it's still currently GS4 data): https://docs.google.com/spreadsheets/d/1dmeUUd9xCwKu758WGLHJktCmGtcgBVVsfeLLTJD2Y1c/edit#gid=0

If someone wants to take the mantle on building a spreadsheet for DR, I'll try to integrate it into a future release.

Logic on the current menu generation:
* Submenus are generated for each unique category name.  Map names in the submenus use the Short Name
* Two other submenus are created: an All Maps menu (which contains all maps listed by longname)  and an Uncategorized Maps menu (which contains all maps that have 0 categories).
* If there's a reference to a map the script doesn't know about, it's treated as if it's shortname and longname match the partial filename (the "map-location" of "map-location-123456.png") and it has no categories.

**Comment by intangibles** [comment]
@rpherbig 
@rcuhljr 

This looks awesome.

**Comment by dewiniaid** [comment]
Fixed the spreadsheet permissions -- they didn't copy from the GS4 when when I duplicated the spreadsheet.

It should be viewable now.

**Comment by rcuhljr** [comment]
What's the plan for integrating this data into Narost? adding it into the script directly, storing it in the mapdb, or something else?

Not volunteering myself currently, but I could definitely see where this would be a desired feature in DR.

**Comment by MahtraDR** [comment]
@dewiniaid Did this go anywhere?

**Comment by MahtraDR** [comment]
@rpherbig close? Seems dead.
