### ISSUE TITLE
Crossing-Trainer Broken Magic Training

### ISSUE THREAD

**Issue by babblezen** [rpherbig/dr-scripts#1668]
Currently, Crossing-Trainer utilizes a timer based methodology to train magic. This is a flawed approach. The most viable method to train magic is repetitive casting. Can we have a mindstate goal function for the yaml or something similar? Otherwise it does not train magic effectively at all.

**Comment by rcuhljr** [comment]
There's not any real timer, there's just a priority system. If your magics are the lowest skills it will just stand there casting until they're not (or you tank your attunement in which case it will go do something else for a bit).

Honestly I'm not sure how many people are still even training magics in crossing-training in favor of using the combat_spell_training system. This issue might be better generalized to just add an optional mind_state threshold for crossing-trainer similar to combat_trainer for people who want less rotation between skill selection.

**Comment by babblezen** [comment]
It won't stand there casting. I've left only magic within the priority list and it will casts 3-4 times then idle after cycling through them with full attunement. Yeah, I could use combat trainer but this guy is an alt that I really have no desire to throw into combat. If it becomes necessary, sure, I'll do that.

**Comment by rcuhljr** [comment]
Maybe check that you didn't set exp_timers for the magic fields accidentally? I just turned on the magics for my empath and starting at no exp it's chain cast while sitting still up to 20/34 in each before I turned it off with no pauses.

**Comment by BastionWT** [comment]
That @rcuhljr describes is what happens on my characters.
