### ISSUE TITLE
Pick ignoring box difficulty

### ISSUE THREAD

**Issue by Jimbo541** [rpherbig/dr-scripts#1669]
I've been having a recurring issue, where pick will ignore the box difficulty on boxes with a reaper trap.

It always continues to attempt to disarm, even if too hard. But just for reaper boxes.

**Comment by rpherbig** [comment]
@jeitzen1012 Could you post a log?

**Comment by jeitzen1012** [comment]
Here is where it grabs box and keep going.

Only does it with reaper boxes.


--- Lich: attunement has exited.

--- Lich: pick active.

[pick]>open my bag

That is already open.
> 
[pick]>open my bag

That is already open.
> 
[pick]>rummage /B my bag

You rummage through a stained green duffel bag looking for boxes and see a copper-edged wooden chest, a mildewy oaken chest, a poorly made pine skippet, a poorly made iron chest, a worm-eaten pine box, a worm-eaten deobar chest and a deeply gouged brass strongbox.
> 
[pick]>inv combat

> 
All of your combat:

  some tarnished chain gloves edged in a seven-pointed star motif
  a quilted titanese hood sealed with protective wax
  a light lumium plate mask
  a steel spear
  a mistwood Nisha shortbow
  a quilted fine titanese hauberk sealed with protective wax
  an azure-scale targe with a reinforced design
  an iron-banded parry stick with brown leather straps
[Type INVENTORY HELP for more options]
> 
[pick]>remove my chain.gloves

> 
You pull off some tarnished chain gloves edged in a seven-pointed star motif from your hands.
> 
[pick]>stow my chain.gloves

You put your gloves in your traveler's pack.
> 
[pick]>remove my plate.mask

You remove a light lumium plate mask from your nose.
> 
[pick]>stow my plate.mask

You put your mask in your traveler's pack.
> 
[pick]>remove my targe

You loosen the straps securing your targe and remove it.
> 
[pick]>stow my targe

You put your targe in your traveler's pack.
> 
[pick]>sit

You sit down.

s> 
[pick]>get my chest from my bag

You get a copper-edged wooden chest from inside your duffel bag.
s> 
s> 
[pick]>disarm my chest identify

Somebody has already located and identified the current trap on the wooden chest...

A crust-covered black scarab of some unidentifiable substance clings to the wooden chest by six tiny legs, all of which are firmly imbedded into the wood and look like it may be tough to dig them out.
Prayer would be a good start for any attempt of yours at disarming the wooden chest.

s> 
[pick]>disarm my chest careful

s> 
You carefully work at disarming the chest.
You work with the trap for a while but are unable to make any progress.
You get the distinct feeling your manipulation caused something to shift inside the trap mechanism.  This is not likely to be a good thing.
Roundtime: 15 sec.

**Comment by rpherbig** [comment]
Do you have `lockpick_ignore_difficulty` set to `true`?

**Comment by jeitzen1012** [comment]
No, it only happens on reaper boxes.

**Comment by rpherbig** [comment]
Closed in #5001
