### ISSUE TITLE
Picking blind instead of quick on easy traps

### ISSUE THREAD

**Issue by joeblow7314** [rpherbig/dr-scripts#1672]
;pick uses pick blind instead of pick quick, on "aged grandmother" level locks.
[pick blind log.txt](https://github.com/rpherbig/dr-scripts/files/1034694/pick.blind.log.txt)
[Ymerejv-setup.txt](https://github.com/rpherbig/dr-scripts/files/1034696/Ymerejv-setup.txt)

**Comment by FluxBorn** [comment]
This is currently the list for how locks are gauged I believe, and it seems like its a little off to me.

  pick_careful:
  - lock has the edge on you, but you've got a good shot at
  - You have some chance of being able to
  - odds are against you
  - would be a longshot
  - You have an amazingly minimal chance

  pick_quick:
  - trivially constructed piece of junk barely worth your time
  - will be a simple matter for you to unlock
  - should not take long with your skills
  - You think this lock is precisely at your skill level
  - with only minor troubles

  pick_blind:
  - trivially constructed gadget which you can take down any time
  - An aged grandmother could
  - you could do it blindfolded
  - You really don't have any chance
  - Prayer would be a good start for any
  - You could just jump off a cliff and save
  - You probably have the same shot as a snowball
  - A pitiful snowball encased in the Flames


the five items under pick_blind seem like they should be under careful? Can someone verify this?

**Comment by izawwlgood** [comment]
Personally, I would prefer if ALL pick attempts that weren't careful, were BLIND. I tend to go through my boxes really fast.

**Comment by rcuhljr** [comment]
I've added a `pick_blind: false` to the base yaml, if set true will always pick blind until mindlocked, then resort to normal pick speeds.
