### ISSUE TITLE
Add Shard Ranger guild rooms to go2

### ISSUE THREAD

**Issue by aslerjack** [rpherbig/dr-scripts#1680]
Was wondering if someone could add the two rooms in the Shard Ranger guild as locations that can be reached with the go2 script? I can get to Room Number: 6272 but then need to "go underbrush" for the [Shattered Oak, Ranger Guild] room and then 'West" to get to the [Shattered Oak, Work Area] room. Neither of these rooms have a room number.

Not a big deal if it can't be done, just would like to use the "work area" room as a training spot.

thanks,
Jack

**Comment by NBSL** [comment]
If you follow this guide: [Lich Mapping Reference](https://elanthipedia.play.net/Lich_mapping_reference#To_Get_Started), you can use ;addroom to add the rooms yourself.

You might have to run the checkout command as ;repos checkout-mapdb --password=YOURPASSWORD

Then run the command like this:
`;addroom "go underbrush, west, east, go underbrush" manual` to add unmapped rooms.

The second go underbrush is whatever the exit is to get back to room 6272

Once you run that, you can do ;repos uploadmapdb --password=PASSWORD_USED_WITH_CHECKOUT

Remember the password you set, as it's used for updating the mapdb and uploading scripts.

**Comment by aslerjack** [comment]
Thank you, I will give it a shot tonight.

Jack

**Comment by aslerjack** [comment]
Worked like a charm, thanks again for the help.
Jack
