### ISSUE TITLE
Add the ability to enter simple commands to statusmon in slack and have output in-game

### ISSUE THREAD

**Issue by ghost** [rpherbig/dr-scripts#1684]
(Maybe not with statusmon)

It would be great to have the ability to respond to simple items in-game via slack. Accept a trade. Speak a line. Point up. Etc...

Since there are potentially multiple DR accounts tied to a single Slack account, perhaps the message sent to Statusmon (or another means) could be:

Bastion point up
or
Bastion say Thanks!

[Character name] [action]

Thanks for your consideration.

**Comment by MahtraDR** [comment]
Is this still an issue today? I don't know anyone who uses slack with DR...

**Comment by MahtraDR** [comment]
This is a very old issue, with no follow up since. Would be happy to revisit this topic as fresh when if it comes up again.
