### ISSUE TITLE
Add sanowret crystal usage to combat-trainer

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#1689]
This would let the user train arcana via `gaze` or `exhale` crystal during combat. Both actions incur no RT.

**Comment by jandersson** [comment]
Counter part to #701 for town-training

**Comment by skyleronken** [comment]
Jonas, are you doing this or need it done?

**Comment by jandersson** [comment]
I'm not doing it - I think thieves and barbarians might appreciate it

**Comment by rcuhljr** [comment]
I'm not super sure this needs to exist here, stand alone scripts seem really good for the crystals since they share no resources other than concentration.

**Comment by jandersson** [comment]
Makes sense!
