### ISSUE TITLE
Shops for Stealing to add

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#1696]
Forging and Engineering societies have items to steal and are on Crossing Justice

Knife Clan has 2 shops, 1 of which will teach to quite high levels and justice as far as I can tell is not running for knife clan

8776: forging society
8864: engineering society
6206: [Knife Clan, Tobb's Smithy]
6213: [Knife Clan, Bukor's Leatherworks]

Here is my most recent version of base-stealing in regard to the new shops and a couple items I sampled.

- room: 8776
  province: zoluren
  item: leather strips
  item_in: in crate
  pawnable: false
  id: '403'
  acceptable_min: 741
  acceptable_max: 741
- room: 8776
  province: zoluren
  item: shield boss
  item_in: in crate
  pawnable: false
  id: '404'
  trivial_min: 741
  trivial_max: 1750
- room: 8776
  province: zoluren
  item: backing
  item_in: in crate
  pawnable: false
  id: '405'
  trivial_min: 741
  trivial_max: 1750
- room: 8776
  province: zoluren
  item: oak haft
  item_in: in crate
  pawnable: false
  id: '406'
  trivial_min: 741
  trivial_max: 1750
- room: 8864
  province: zoluren
  item: leather strips
  item_in: in crate
  pawnable: false
  id: '407'
  acceptable_min: 741
  acceptable_max: 741
- room: 8864
  province: zoluren
  item: lenses
  item_in: in crate
  pawnable: false
  id: '408'
  poorly_min: 741
  poorly_max: 741
- room: 8864
  province: zoluren
  item: bone backer
  item_in: in crate
  pawnable: false
  id: '409'
  trivial_min: 741
  trivial_max: 1750
- room: 6206
  province: zoluren
  item: sunblade
  item_in: on desk
  pawnable: false
  id: '410'
  trivial_min: 741
  trivial_max: 1750
- room: 6206
  province: zoluren
  item: stiletto
  item_in: on desk
  pawnable: false
  id: '411'
  trivial_min: 741
  trivial_max: 1750
- room: 6213
  province: zoluren
  item: reinforced coat
  item_in: on table
  pawnable: false
  id: '412'
  exceptionally_min: 741
  exceptionally_max: 741
- room: 6213
  province: zoluren
  item: leather jerkin
  item_in: on table
  pawnable: false
  id: '413'
  acceptable_min: 741
  acceptable_max: 741

**Comment by rpherbig** [comment]
@rcuhljr Since you have a high level Thief, could you check these out?

**Comment by mwest152** [comment]
@rcuhljr had a chance to check these out?  Adding these 3 shops is literally the difference between 20 mindstates and 34 for me in a stealing run.   Confirmed there is no justice for tiger clan and knife clan.  Though we already have the tiger shops in.

**Comment by rcuhljr** [comment]
I have not, can we not just use the steal script to record and submit these new items to the repo?

**Comment by mwest152** [comment]
Stealing existing items will update the numbers, but pretty sure adding new items, or maybe just new shops requires extra effort.  Which is probably smart, because someone could  add a shop on an island randomly and jack things up pretty good.

**Comment by mwest152** [comment]
I've run through each of these 3 shops and used the steal script to add the items.  They will show up on base-stealing, and then disappear a little later.

HR> 
[dependency: submittingNEW:420:{"room"=>6213, "province"=>"zoluren", "item"=>"jerkin", "item_in"=>"on table", "pawnable"=>false, "id"=>"420", "acceptable_min"=>749, "acceptable_max"=>749}]


- room: 8776
  province: zoluren
  item: strip
  item_in: in crate
  pawnable: false
  id: '418'
  acceptable_min: 749
  acceptable_max: 749
- room: 8864
  province: zoluren
  item: strip
  item_in: in crate
  pawnable: false
  id: '419'
  acceptable_min: 749
  acceptable_max: 749
- room: 6213
  province: zoluren
  item: jerkin
  item_in: on table
  pawnable: false
  id: '420'
  acceptable_min: 749
  acceptable_max: 749

**Comment by rpherbig** [comment]
`base-stealing` is an auto-updated file, so the local changes are probably being overwritten. They'll still be stored in firebase which means the data isn't lost, it just needs @rcuhljr or myself to pull it into `base-stealing`.

**Comment by rcuhljr** [comment]
Added the latest things from the base and added an optional guilds: tag to data for restricted rooms. If we're motivated it may make sense to move that restricted list elsewhere.

**Comment by rpherbig** [comment]
5a959709cc478ac5998af9af8cd36c7dd7cf695c and 8df21d7753483ea926bd193e67defe74c425eca2

**Comment by rpherbig** [comment]
Is the guild restriction always per-room, or can it be per-item?

**Comment by mwest152** [comment]
I don't know of any guild restricted items, just rooms.  The current system of skipping it like it was closed seems to work ok.

**Comment by rpherbig** [comment]
In that case we could move the restriction info to its own mapping of room -> boolean (i.e. it does not have to be part of the item info). But that doesn't seem essential right now...

**Comment by rcuhljr** [comment]
Agreed, it would be nice to denormalize that data a bit, but it wasn't essential.
