### ISSUE TITLE
Stop the pick script as soon as mindlock is reached

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#17]
Only if UserVars.stop_on_mindlock is true, of course.

We're leaving exp on the table by continuing to disarm/pick while mindlocked.

**Comment by kamarcum** [comment]
Is https://github.com/rpherbig/dr-scripts/blob/master/pick.lic#L54-L56 good enough to close this?

**Comment by rpherbig** [comment]
Maybe. But you're potentially losing nearly an entire box worth of exp if you lock just after starting the box. Maybe we should lower the threshold to 30-32?

**Comment by rcuhljr** [comment]
dropping the threadhold to 30ish makes sense and seems easiest.
