### ISSUE TITLE
workorders.lic

### ISSUE THREAD

**Issue by Redheadmoonie** [rpherbig/dr-scripts#1709]
All the cloth stuff in base-recipes is set to workorder: false. Please change them to workorder: true. Thanks

**Comment by rcuhljr** [comment]
Probably open for discussion whether we want to enable this since knitting is the preferred way for most people to train. People can use overrides to select recipes currently if they diverge ala https://gist.github.com/rcuhljr/f2be7c688bf425afa7996955badf81bd but open to discussion.
