### ISSUE TITLE
tie/untie ritual support

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#1712]
Using staff tied to pack for ritual focus need to tie/untie

**Comment by xtremenerdrage** [comment]
Did below and it will untie invoke etc but when it goes to tie     _DRC.bput("tie my #{focus} to my #{tied}", 'You attach')_   it will just put [buff]>tie my staff
Tie what?


 find_focus(spell['focus'], spell['worn_focus'], spell['tied_focus'])    and        stow_focus(spell['focus'], spell['worn_focus'], spell['tied_focus'])
and     def find_focus(focus, worn, tied)

def stow_focus(focus, worn, tied)
    return unless focus

    if worn
      DRC.bput("wear my #{focus}", 'You attach', 'You slide', 'You are already wearing', 'You hang', 'You sling', 'You put', 'You place')
    elsif tied
      bput("tie my #{focus} to my #{tied}", 'You attach')
    else
      DRC.bput("stow my #{focus}", 'You put')
    end
  end
and it drops the to my apparently and I get
[buff]>tie my staff
Tie what?
if worn
      DRC.bput("wear my #{focus}", 'You attach', 'You slide', 'You are already wearing', 'You hang', 'You sling', 'You put', 'You place')
    elsif tied
      DRC.bput("tie my #{focus} to my #{tied}", 'You attach')
    else
      DRC.bput("stow my #{focus}", 'You put')
    end
  end

**Comment by rpherbig** [comment]
@rcuhljr did acb0ca1bbd38cb04e57d135dc33fe4adb1b4986d fix this?

**Comment by rcuhljr** [comment]
Hopefully? I don't have much for ritual casters.
