### ISSUE TITLE
boar clan

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#1713]
Changed Hib's tannery and repair to boar clan and left the rest hib in case your closer to boar

Boar Clan:
  currency: dokoras
  leather_repair:
    id: 12174
    name: Tuzra
  metal_repair:
    id: 12174
    name: Tuzra
  deposit:
    id: 8883
  exchange:
    id: 8884
  gemshop:
    id: 8899
    name: rasiya
  tannery:
    id: 12173
    name: Gudthar
  npc_empath:
    id: 8881
  locksmithing:
    id:
  theurgy_supplies:
    id:
  debt_office:
    id: 11696
  guard_house:
    id: 11697

**Comment by rpherbig** [comment]
Those seem to match the current values for Boar Clan. What needs changed for this issue?

**Comment by jayRyan24** [comment]
What if you're hunting to the south or east of hib, you're going to have to run all the way back up to boar clan to repair, bypassing hib?

**Comment by xtremenerdrage** [comment]
Yeah I wasn't thinking and didn't see the boar clan location

**Comment by MahtraDR** [comment]
Can we close this, or is there anything pending here?
