### ISSUE TITLE
Appraise 'pouches' should appraise worn pouch

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#1715]
Right now it only looks for full pouches in your `full_pouch_container` and ignores the (partially full) one you are wearing.

**Comment by rpherbig** [comment]
I'm not sure if this should be in addition to, or independent of, appraising full ones in your container.

**Comment by jandersson** [comment]
Ah thats a good idea. Is there a way to specifically target something you are wearing? i guess `appraise my #{gem_pouch_adjective} pouch` ?

**Comment by rpherbig** [comment]
I'm not sure without some testing. Theoretically, your full pouches would have the same adjective.
