### ISSUE TITLE
premie_wicked_burrow mining area

### ISSUE THREAD

**Issue by BardWyrrd** [rpherbig/dr-scripts#1728]
Request to add the premium mining area in wicked burrow to base-mining.
  premie_wicked_burrow:
  - 10000
  - 10001
  - 10002
  - 10003
  - 10004
  - 10005
  - 10006
  - 10007

**Comment by Sarvatt** [comment]
sent a pull request for it at https://github.com/rpherbig/dr-scripts/pull/1729
