### ISSUE TITLE
YAML setting for ammunition check/restock

### ISSUE THREAD

**Issue by ghost** [rpherbig/dr-scripts#1742]
It would be nice if, after selling loot or another similar timing, the routines could check YAML settings to make sure you have the appropriate amounts of ammunition.

ammo_storage: quiver
arrow_type: cougar-claw arrow
arrow_min: 15
bolt_type: bolt
bolt_min: 20
rock_type: shard
rock_min: 5

Would help with the buddy hunting, and in general ammo usage.

**Comment by BastionWT** [comment]
Same thing for tk_ammo, btw. We already specify the type, we should also then specify the amount and have it check for that as the minimum before beginning a hunt/during sell loot/sometime.

**Comment by wscherer420** [comment]
This would be kinda cool. But sounds difficult because of the type of ammo, stores that sell them, and province you're hunting in.

**Comment by mwest152** [comment]
actually doesn't seem that crazy.   inspired me to write a before combat script that will check my inventory for bolts, and daggers for my tk_ammo.  My ruby skills are really bad, or I'd help on this one.

**Comment by MahtraDR** [comment]
@rpherbig can close. This is what restock.lic does
