### ISSUE TITLE
New wield/sheath

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#1745]
[combat-trainer: checked against [/Sheathing/i, /You sheathe/i, /You .* unload/i, /close the fan/i, /You secure your/i, /You slip/i, /You hang/i, /You strap/i]]
combat-trainer]>sheath my sterak.axe

**You easily strap your sterak axe to a shimmering faeweave baldric with cambrinth buckles.**
can we have You easily strap added to the sheath check

**Comment by jayRyan24** [comment]
Is there not a new wield as well?

**Comment by xtremenerdrage** [comment]
When running debug it has those checks above but this Baldric verbs you EASILY strap, just need that check added to sheath
