### ISSUE TITLE
empath link list

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#1747]
Either a smart setting for empaths to be able to link specific names when hunting 

empath_links:
  - Zook
it will link check for current links - if Zook isn't matched it will
touch zook
link zook persistent
link zook hodierna

Bonus to this - if you want to run your other toons to where your empath hunts it basically becomes a healbot
or

ability to set multiple lines in buff_nonspells:

buff_nonspells:
  touch zook; link zook pers; link zook hod: 60

**Comment by MahtraDR** [comment]
@rpherbig can close. this is possible today with multi, or possible then (and now) by creating an alias with newlines between arguments like this:

```
taq => touch \? \r link \? pers \r link \? hod
taq: 60``
