### ISSUE TITLE
jail-buddy should check bankbot if not enough coin in bank

### ISSUE THREAD

**Issue by skyleronken** [rpherbig/dr-scripts#1750]
If bankbot is configured, jail-buddy should check bankbot for coin to pay off debts to get equipment back.

**Comment by skyleronken** [comment]
Looking at the code, the change is needed in common-money's function for withdrawing coin.

**Comment by jayRyan24** [comment]
This should probably work by instead of not having enough coin, simply check if the bankbot is being used. This should be the first check, if not, check bank. If it is there and there aren't enough funds, check bank.

**Comment by MahtraDR** [comment]
Closing as per https://github.com/rpherbig/dr-scripts/issues/1909#issuecomment-1032112683
