### ISSUE TITLE
Engineering work orders

### ISSUE THREAD

**Issue by mwcarew** [rpherbig/dr-scripts#1757]
Getting an error when making pendants for engineering. Shape.lic isn't getting finished short leather cords or some such.

https://pastebin.com/xJXU5rvh

**Comment by mwcarew** [comment]
This is with shaping work orders in the YAML and 111 Engineering. Done in Crossing.

**Comment by BastionWT** [comment]
Also broken for me, same issue. This started happening in the last 2 days. Pendants recipe is not working.

**Comment by adamgoerdt** [comment]
Updated recipe in PR 1759 should resolve this

**Comment by rpherbig** [comment]
@leustyin I think the problem is that `wood pendant` isn't in `base-recipes`.
