### ISSUE TITLE
no ammo and tkt

### ISSUE THREAD

**Issue by Missah** [rpherbig/dr-scripts#1771]
[combat-trainer]>cast
The rock guardian closes to pole weapon range on you!
>
You gesture at a rock guardian.
Your cambrinth armband emits a loud *snap* as it discharges all its power to aid your spell.
There is nothing here that can be thrown, so the spell fails.
Roundtime: 1 sec.

sometimes tk_ammo will disappear from room - in rock guardians, for example, a low fog comes in and everything on the ground disappears.

Can something be added to combat so that when "There is nothing here that can be thrown" shows up, it will grab more ammo from container and drop it?

Thank you.

**Comment by mwest152** [comment]
I've had good luck with small weapons.  While not fool proof, daggers have worked well for me.  They disappear on occasion, but never really investigated why.  I usually just keep a few daggers on me at a time.  I think I'll end scripts early and just forget to pick it up, or death is the only time I really lose them.  I've tried stuff like rocks, and the janitor eats em up fast.

**Comment by rcuhljr** [comment]
I'll be fixing this at some point, just need to get around to it.

**Comment by rcuhljr** [comment]
Oops forgot this guy, if combat-trainer sees the message it will attempt to drop more `tk_ammo`.
