### ISSUE TITLE
Astrology Prediction Tool Support

### ISSUE THREAD

**Issue by nando248** [rpherbig/dr-scripts#1772]
add support for Celestial Charts, Mirrors, Decks, etc... for Moon Mage predictions. Currently, bones are the only supported tools using:
have_divination_bones: false
divination_bones_storage:
  container:
  tied:

**Comment by nando248** [comment]
just checking back on this, is there any way I could get support for Celestial Charts? especially now that destiny cipher has been tweaked.

**Comment by jandersson** [comment]
Working on it!

**Comment by MahtraDR** [comment]
@rpherbig We can close this one too. This was added sometime between then, and now.
