### ISSUE TITLE
Scholarship

### ISSUE THREAD

**Issue by Redheadmoonie** [rpherbig/dr-scripts#1773]
--- Lich: astrology has exited.
[hunting-buddy: ***STATUS*** EXECUTE Scholarship]
[hunting-buddy: *** Failed to find a script named 'Scholarship' ***]
[hunting-buddy: *** Please report this to Etreu, Sheltim, or https://github.com/rpherbig/dr-scripts/issues  ***]
--- Lich: could not find script 'Scholarship' in directory G:/lich/scripts
[hunting-buddy: ***STATUS*** EXECUTE Athletics]
--- Lich: athletics active.

**Comment by jandersson** [comment]
Is this in an `before:` or `after:`? You're seeing the error because scholarship.lic doesn't exist. Its not a script we have on here either.

**Comment by Redheadmoonie** [comment]
Yes, it was set as a before. I've since removed it
