### ISSUE TITLE
glaives seem to be an issue with combat-trainer

### ISSUE THREAD

**Issue by blaylosw** [rpherbig/dr-scripts#1774]
combat trainer is having issues with a glaive. it swaps back and forth and never attacks.  Keeps looking to match

 [combat-trainer: checked against [/ short staff /i, /\bglaive\b.*(heavy edged|two-handed edged|heavy blunt|two-handed blunt|light edged|medium edged|light blunt|medium blunt|light thrown|short staff)/i]]

**Comment by rpherbig** [comment]
Could you post more of the log?

**Comment by blaylosw** [comment]
[combat-trainer]>wield my glaive
You draw out your steel glaive from the burlap baldric, gripping it firmly in your right hand and balancing with your left.
>
[combat-trainer]>swap my glaive
You switch your glaive so that you can use it as a halberd weapon.
>
* In a weak and directionless display of aggression, a cougar pounces, snarling with its fangs bared in rage at you.  You evade.  
[You're solidly balanced with no advantage.]
>
The brocket deer begins to advance on you!
The brocket deer advances from nearby and is closing steadily.
>
* In a weak and directionless display of aggression, a cougar slices wide at you.  You evade.  
[You're solidly balanced and in good position.]
>
The brocket deer closes to melee range on you!
>
The brocket deer begins to advance on you!
The brocket deer advances from nearby and is closing steadily.
>
The brocket deer closes to melee range on you!
>
[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 21]
[combat-trainer: message: You switch your glaive so that you can use it as a halberd weapon.]
[combat-trainer: message: * In a weak and directionless display of aggression, a cougar pounces, snarling with its fangs bared in rage at you.  You evade.  ]
[combat-trainer: message: [You're solidly balanced with no advantage.]]
[combat-trainer: message:  Khri Avoidance  (3 roisaen)]
[combat-trainer: message:  Khri Darken  (10 roisaen)]
[combat-trainer: message:  Khri Dampen  (1 roisan)]
[combat-trainer: message:  Khri Hasten  (8 roisaen)]
[combat-trainer: message:  Khri Strike  (3 roisaen)]
[combat-trainer: message: The brocket deer begins to advance on you!]
[combat-trainer: message: The brocket deer advances from nearby and is closing steadily.]
[combat-trainer: message: * In a weak and directionless display of aggression, a cougar slices wide at you.  You evade.  ]
[combat-trainer: message: [You're solidly balanced and in good position.]]
[combat-trainer: message: The brocket deer closes to melee range on you!]
[combat-trainer: message: The brocket deer begins to advance on you!]
[combat-trainer: message: The brocket deer advances from nearby and is closing steadily.]
[combat-trainer: message: The brocket deer closes to melee range on you!]
[combat-trainer: message:  Khri Avoidance  (3 roisaen)]
[combat-trainer: message:  Khri Darken  (9 roisaen)]
[combat-trainer: message:  Khri Dampen  (1 roisan)]
[combat-trainer: message:  Khri Hasten  (8 roisaen)]
[combat-trainer: message:  Khri Strike  (3 roisaen)]
[combat-trainer: checked against [/ short staff /i, /\bglaive\b.*(heavy edged|two-handed edged|heavy blunt|two-handed blunt|light edged|medium edged|light blunt|medium blunt|light thrown|short staff)/i]]
[combat-trainer]>swap my glaive
You switch your glaive so that you can use it as a quarter staff weapon.
>
* Awkwardly, a cougar swipes with deadly claws extended at you.  You dodge.  
[You're solidly balanced and in superior position.]
>
* Trying inexpertly, an elder red brocket deer kicks out its hooves at you.  You evade, barely stepping to one side.  
[You're solidly balanced with no advantage.]
>
* Awkwardly, an elder red brocket deer kicks out its hooves at you.  You partially block with a small gryphon-pelt shield sealed with protective wax.  
[You're solidly balanced and have slight advantage.]
>
* Ineptly, a cougar slices wide at you.  You block solidly with a small gryphon-pelt shield sealed with protective wax.  
[You're solidly balanced and in excellent position.]
>
* Moving inexpertly, an elder red brocket deer bares its large teeth and bites at you.  You dodge, barely stepping to one side.  
[You're solidly balanced with no advantage.]
>
[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 16]
[combat-trainer: message: You switch your glaive so that you can use it as a quarter staff weapon.]
[combat-trainer: message: * Awkwardly, a cougar swipes with deadly claws extended at you.  You dodge.  ]
[combat-trainer: message: [You're solidly balanced and in superior position.]]
[combat-trainer: message: * Trying inexpertly, an elder red brocket deer kicks out its hooves at you.  You evade, barely stepping to one side.  ]
[combat-trainer: message: [You're solidly balanced with no advantage.]]
[combat-trainer: message:  Khri Avoidance  (3 roisaen)]
[combat-trainer: message:  Khri Darken  (9 roisaen)]
[combat-trainer: message:  Khri Dampen  (1 roisan)]
[combat-trainer: message:  Khri Hasten  (8 roisaen)]
[combat-trainer: message:  Khri Strike  (3 roisaen)]
[combat-trainer: message: * Awkwardly, an elder red brocket deer kicks out its hooves at you.  You partially block with a small gryphon-pelt shield sealed with protective wax.  ]
[combat-trainer: message: [You're solidly balanced and have slight advantage.]]
[combat-trainer: message: * Ineptly, a cougar slices wide at you.  You block solidly with a small gryphon-pelt shield sealed with protective wax.  ]
[combat-trainer: message: [You're solidly balanced and in excellent position.]]
[combat-trainer: message: * Moving inexpertly, an elder red brocket deer bares its large teeth and bites at you.  You dodge, barely stepping to one side.  ]
[combat-trainer: message: [You're solidly balanced with no advantage.]]
[combat-trainer: checked against [/ short staff /i, /\bglaive\b.*(heavy edged|two-handed edged|heavy blunt|two-handed blunt|light edged|medium edged|light blunt|medium blunt|light thrown|short staff)/i]]
[combat-trainer]>swap my glaive
>
* Trying weakly, an elder red brocket deer kicks out its hooves at you.  You barely block with a small gryphon-pelt shield sealed with protective wax.  
[You're solidly balanced with opponent in good position.]
>
You switch your glaive so that you can use it as a halberd weapon.
>
* Moving inexpertly, an elder red brocket deer kicks out its hooves at you.  You dodge, ducking in the nick of time.  
[You're solidly balanced with no advantage.]
>
* As if effort and skill were a bad thing, a cougar swipes with deadly claws extended at you.  You block solidly with a small gryphon-pelt shield sealed with protective wax.  
[You're solidly balanced and in good position.]

**Comment by rpherbig** [comment]
@blaylosw I think this change will fix it. Let me know if you have any problems.

**Comment by blaylosw** [comment]
chat do I have to load anything?

**Comment by rpherbig** [comment]
Restart `dependency`
