### ISSUE TITLE
Significant bug in ;remedy

### ISSUE THREAD

**Issue by jonathan-stricker** [rpherbig/dr-scripts#1776]
During the remedy creation process, when it's interrupted by needing to add more reagents/water/whatever, the script will always resume the process with crushing with a pestle following the addition of the new material, even when another step is required. See example below where the script crushes with pestle following the addition of the coal even when the output said it needed skimming with a sieve. This oversight impacts the quality and if it happens a couple of times during creation it can make the quality too low for work orders. Thanks.

[remedy]>analyze my cream
You analyze the blister cream and learn more about its construction.
When crafting is complete this will be a type of basic wound remedy.
A thick froth coats the mixture.  To avoid having this affect the preparation you should push the cream with a sieve to skim off the material.
From the progress so far, it looks like the cream is of outstanding (11/12) quality.
Roundtime: 6 sec.
>
[remedy]>tie my grooved pestle to my alchemist belt
You attach a steel grooved pestle to your alchemist's belt.
>
[remedy]>untie my sieve from my alchemist belt
You remove a trapezoidal darkstone wire sieve from your alchemist's belt.
>
[remedy]>push my cream with my sieve

You need another catalyst material to continue crafting some unfinished blister cream.  You believe you can just pour or put it inside the mortar and continue crushing the unfinished remedy inside.

[Ingredients can be added by putting them with the unfinished item and continuing to craft.]
>
[remedy]>tie my wire sieve to my alchemist belt
You attach a trapezoidal darkstone wire sieve to your alchemist's belt.
>
[remedy]>get my coal nugget
You get a massive coal nugget from inside your yellow haversack.
>
[remedy]>put my coal nugget in my mortar
You vigorously rub the nugget alongside the mortar to scrape some shavings into the mixture.
>
[remedy]>put my coal nugget in my haversack
You put your nugget in your yellow haversack.
>
[remedy]>untie my pestle from my alchemist belt
You remove a steel grooved pestle from your alchemist's belt.
>
[remedy]>crush my cream with my pestle
With short strokes you crush some unfinished blister cream with your pestle.  You struggle to properly remove the used plant pieces in a timely manner.
Roundtime: 16 sec.
>

**Comment by jandersson** [comment]
Closed by #3642
