### ISSUE TITLE
Add support for manipulate_only_to_train flag RE: empathy

### ISSUE THREAD

**Issue by ghost** [rpherbig/dr-scripts#1778]
My empath is currently one of those causing problems with spawn mechanics and manipulate. I don't have a game-side solution, but we can limit the impact by adding a new flag that empaths can set regarding their manipulating.

manipulate_only_to_train: true
Similar to cast_only_to_train: true, if true the empath will only attempt to manipulate when they're below 30/34 or whatever in Empathy. If above that number, no manipulating.

manipulate_only_to_train: false
The default setting, and would behave as it does right now. Sometime you want to be manipulating creatures even when locked. Safety, faster killing of other mobs, etc...

My empath will often be at 34/34 Empathy for half of his hunt, waiting for evasion and stealth to also lock. If I'm NOT manipulating for half the hunt, I'll suck in fewer mobs, which will result in fewer dead rooms. Also nice for me as that's 20 seconds every few minutes that I could be training something else.

**Comment by MahtraDR** [comment]
@rpherbig this was resolved by https://github.com/rpherbig/dr-scripts/pull/2587
