### ISSUE TITLE
combat trainer - necro rituals and skinning

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#178]
Necro rituals dissect and preserve allow the corpse to be skinned as well.  Corpses can't be skinned after harvest.

**Comment by rpherbig** [comment]
@hwoo79 Are you up for fixing this one? :)

**Comment by hwoo79** [comment]
Sure thing!

In testing, I found that dissect will not allow skinning.  I believe this is a difference between DR Prime and DR The Fallen.  I'm assuming this to be a bug in The Fallen.

**Comment by rpherbig** [comment]
df4f8144d3535b84268174598319e27c46b938e7
