### ISSUE TITLE
IZ support for offensive_spells

### ISSUE THREAD

**Issue by BastionWT** [rpherbig/dr-scripts#1783]
Cast:
>cast
You gesture.
Your empathic shock makes the spell slightly more pliable.
Monstrous feelings of cold-bloodedness uncoil from within, taking root in places where your empathy has receded.  Their physical echoes are concentrated most in your hands, and you immediately recognize the onset of an abnormal arthritis.

Touch Messages (there look to be 7 of these):
>touch goblin
Honing the essence of pain on your fingertips, you reach out to touch a striped origami goblin.

You insouciantly swing a backhand at a striped origami goblin.

You lean forward, your arm outstretched at a white origami mouse for a touch.

Feeling implacable, you lunge with an extended hand toward a white origami mouse.

You stab your curled ashen fingers at a black origami grasshopper.

You extend a pain-laden hand toward a striped origami grasshopper.

You reach out toward a striped origami grasshopper with the back of your hand in a gesture of false sympathy.

**Comment by rpherbig** [comment]
Is `touch` occurring as part of a script? I'm not sure where to add those messages.

**Comment by BastionWT** [comment]
Touch is the command to "attack" with IZ.
