### ISSUE TITLE
Astrology needs a stun check

### ISSUE THREAD

**Issue by Redheadmoonie** [rpherbig/dr-scripts#1784]
Astrology needs a stun check to prevent this from happening:
[astrology]>predict future
You look inside yourself in an attempt to see beyond the now.
After a few moments, the mists of time begin to part.

Suddenly your mind receives a numbing jolt as visions of a bat-winged skull overwhelm your mind.
Roundtime: 10 sec.
The world around you returns to its mundane appearance.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You are still stunned.
[astrology]>stand
You stand back up.
[astrology]>predict state all

**Comment by mwest152** [comment]
this could probably use a fix, but as a side note, using a divination tool I think prevents ever being stunned by a bad prediction.

**Comment by rpherbig** [comment]
Huh, `astrology.lic` has a stun check right there: https://github.com/rpherbig/dr-scripts/blob/master/astrology.lic#L267-L271

I'm not sure why it isn't working. I assume `stunned?` returned false...

**Comment by rcuhljr** [comment]
Stunned doesn't work right in DR versus GS4. GS4 gives numeric stunned time remaining values.

**Comment by Redheadmoonie** [comment]
with the duration being 0.5 it just rapid fire spams stand over and over
