### ISSUE TITLE
New feature: Spreadsheet support for bags?

### ISSUE THREAD

**Issue by elBlanquito** [rpherbig/dr-scripts#1789]
Would it be possible to add support for outputting the contents of a bag into a spreadsheet (excel or .ods format) ?

**Comment by rpherbig** [comment]
Are you envisioning the output of, say, `inv list`? Or something more complicated? I'm trying to understand what this would do differently than copy/paste from your front end into Excel/OOCalc

**Comment by elBlanquito** [comment]
Oh, it'd be so useful to have a function to call that would generate a list in excel, in a column, where each item (broken up in commas as in rummage bag, or dashes with inventory list). Don't need anything complicated done with the data, it's just rife with formatting errors when i copy and paste directly from the terminal into .odf and requires manual attention to clean up each paste.

Just something simple to output the inventory of a bag, into a list, where each item has it's own cell in a column is what I had in mind. Is something like this doable? Am I making sense? Do you think this would be useful to others besides just myself?

**Comment by jandersson** [comment]
Is `inv list` what you are asking for?

**Comment by elBlanquito** [comment]
I apologize.  It seems that copying+pasting the results of INV LIST is definitely clean enough for my purposes! Sorry for bothering you! Thank you very much Jonas and Robert!sheath

**Comment by jandersson** [comment]
Cheers Blanquito, there are definitely libraries for what you want to do!
