### ISSUE TITLE
Crossing-Trainer stops teaching and begins teaching the same skill

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#1790]
I'm not sure if it is intentional, but it is strange. Crossing-trainer will stop teaching a skill, then attempt to teach all the people in the room the same skill. This seems to happen on a timer or when cycling skills.

**Comment by mwest152** [comment]
Yeah I think that is if you only have 1 class to teach listed.  It would be cycling between classes.

**Comment by rpherbig** [comment]
It wouldn't be hard to add `@settings.classes_to_teach.size > 1` to `check_teaching` in `crossing-training`.
