### ISSUE TITLE
Knitting needles dropped when starting crossing-training

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#1792]
Figured out why ive randomly lost knitting needles a few times I think.

Did a little investigating, assuming because needle in in trash_nouns: in base-items
-------------
[buff]>cast

You gesture.
Rutilant sparks of light encircle you, bathing you in a warm glow as your body begins to tingle with energy.

> 
--- Lich: buff has exited.

> 
[crossing-training]>drop my knitting needles

You drop some polished steel knitting needles.
----------------
adding to outfitting tools: or loot_additions: didnt seem to work

**Comment by rpherbig** [comment]
@rcuhljr Is this related to 193d7e6f86c7d136ed41180efd70bc259410f2ab?

**Comment by rcuhljr** [comment]
No, as long as the needles are set up properly in `gear:` it will override this behavior.

**Comment by rpherbig** [comment]
In `gear` only? I.e. will `knitting_tools` also work? https://github.com/rpherbig/dr-scripts/blob/master/profiles/base.yaml#L255-L256

**Comment by rcuhljr** [comment]
Only gear that I'm aware of.

**Comment by Sarvatt** [comment]
This has happened to me a ton, only adding it to gear fixed it

**Comment by Sarvatt** [comment]
would anyone be averse to adding needles to lootables while keeping needle in junk to avoid this situation?
