### ISSUE TITLE
Shaping getting stuck in lag

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#1798]
Just got stuck with lumber at my feet and unable to move while doing a shaping workorder, looks to be lag related?

[shape]>put my iron drawknife in my rucksack
...wait 1 seconds.
...wait 1 seconds.
[shape]>put my iron drawknife in my rucksack
You put your drawknife in your nightsilk rucksack.
[shape]>put my iron drawknife in my rucksack
[shape]>get my shaper
What were you referring to?
[shape: You seem to be missing: shaper]
You get a wood shaper from inside your nightsilk rucksack.
--- Lich: shape has exited.
[crossing-training]>get my lumber
You need a free hand to pick that up.

**Comment by rpherbig** [comment]
Check if you have a Rangu ticket for the shaper

**Comment by Sarvatt** [comment]
no ticket, I had the shaper it just thought the extra put my iron drawknife in my rucksack after it was already put away was a failure getting the shaper and gave up

**Comment by Sarvatt** [comment]
[shape]>scrape my lumber with my drawknife
You carefully separate out the excess material and place it at your feet.
You select a high quality piece of lumber and brace your foot against it.  A layer at a time you scrape into the wood, flattening it into the desired shape.  Peering at the clean cuts inspires confidence for continued shaping.
Shaping with a wood shaper is needed to further smooth the material's surface.
Roundtime: 21 sec.
Vadok begins to lecture you on the proper usage of the Locksmithing skill.
[smartlisten: Checking if I should listen to a class on Locksmithing]
To learn from him, you must LISTEN TO Vadok.
[smartlisten: Attempting to listen to Vadok]
  (LISTEN HELP for more options)
Treylis continues to braid his vines.
Vadok stops playing his song.
Vadok begins a masterful concerto on his copper zills with only the slightest hint of difficulty.
[Trade] Your mind hears Tyx thinking, "yall comeion"
Sentoki puts his book in his backpack.
Sentoki gets a sharpened steel drawknife from inside his backpack.
Sentoki gets some maple lumber from inside his backpack.
Skein of Shadows  (1 roisan)
Manifest Force  (7 roisaen)
Treylis continues to braid his vines.
Gakse puts his drawknife in his tinker's pack.
Gakse gets a wood shaper from inside his tinker's pack.
Treylis continues to braid his vines.
Veleren gestures.
Four items rapidly decompose.
Treylis continues to braid his vines.
Skein of Shadows  (1 roisan)
Manifest Force  (6 roisaen)
Sentoki puts his drawknife in his backpack.
Sentoki gets a steel jagged wood shaper from inside his backpack.
Rakkor continues to play a quiet serenade on his copper zills, pausing only a little through a difficult section.
Treylis roots around the area for a moment.
Treylis forages around the area for a while until he finds a vine.
[smartlisten]>listen to Vadok 
[shape]>put my iron drawknife in my rucksack
...wait 1 seconds.
...wait 1 seconds.
[shape]>put my iron drawknife in my rucksack
[smartlisten]>listen to Vadok 
You put your drawknife in your nightsilk rucksack.
You begin to listen to Vadok teach the Locksmithing skill.
Gakse puts his shaper in his tinker's pack.
Gakse gets a steel carving knife from inside his tinker's pack.
[shape]>put my iron drawknife in my rucksack
[smartlisten]>listen to Vadok 
[shape]>get my shaper
[DRPrime]-DR:Mitkiahn: "732"
What were you referring to?
You are already listening to someone.  You may wish to STOP LISTENING.
[shape: You seem to be missing: shaper]
You get a wood shaper from inside your nightsilk rucksack.
--- Lich: shape has exited.
[crossing-training]>get my lumber
You need a free hand to pick that up.
Treylis continues to braid his vines.
Skein of Shadows  (1 roisan)
Manifest Force  (6 roisaen)
[DRPrime]-DR:Mitkiahn: "He's hiding"
Vadok smiles at you.
[DRPrime]-DR:Raelok: "i break about 10 per day"
Treylis continues to braid his vines.
Sentoki puts his shaper in his backpack.
Sentoki gets a steel jagged wood shaper from inside his backpack.
Treylis continues to braid his vines.
Vadok seems to relax as he continues to play a masterful concerto on his copper zills.
Skein of Shadows  (1 roisan)
Manifest Force  (6 roisaen)
Treylis continues to braid his vines.
Gakse puts his knife in his tinker's pack.
Gakse gets a wood shaper from inside his tinker's pack.
[crossing-training: *** No match was found after 15 seconds, dumping info]
[crossing-training: messages seen length: 17]
[crossing-training: message: You need a free hand to pick that up.]
[crossing-training: message: Treylis continues to braid his vines.]
[crossing-training: message: Skein of Shadows  (1 roisan)]
[crossing-training: message: Manifest Force  (6 roisaen)]
[crossing-training: message: [DRPrime]-DR:Mitkiahn: "He's hiding"]
[crossing-training: message: Vadok smiles at you.]
[crossing-training: message: [DRPrime]-DR:Raelok: "i break about 10 per day"]
[crossing-training: message: Treylis continues to braid his vines.]
[crossing-training: message: Sentoki puts his shaper in his backpack.]
[crossing-training: message: Sentoki gets a steel jagged wood shaper from inside his backpack.]
[crossing-training: message: Treylis continues to braid his vines.]
[crossing-training: message: Vadok seems to relax as he continues to play a masterful concerto on his copper zills.]
[crossing-training: message: Skein of Shadows  (1 roisan)]
[crossing-training: message: Manifest Force  (6 roisaen)]
[crossing-training: message: Treylis continues to braid his vines.]
[crossing-training: message: Gakse puts his knife in his tinker's pack.]
[crossing-training: message: Gakse gets a wood shaper from inside his tinker's pack.]
[crossing-training: checked against [/You get some/i, /You pick up/i]]
[crossing-training]>drop my lumber
But you aren't holding that.
Treylis continues to braid his vines.
 * Zoluren's Herald Navesi Daerthon joins the adventure.
[DRPrime]-DR:Raelok: "no idea how many boxes that is"
Treylis continues to braid his vines.
Sentoki puts his shaper in his backpack.
Sentoki gets a tapered steel rasp from inside his backpack.
[DRPrime]-DR:Etreu: "well give the stouts a go, might save you some coin at least."
Skein of Shadows  (1 roisan)
Manifest Force  (6 roisaen)
[DRPrime]-DR:Giulietta: "you gonna gank him?"
Treylis continues to braid his vines.
Rakkor concentrates intently on his technique as he continues to play a quiet serenade on his copper zills.
Treylis continues to braid his vines.
[crossing-training: *** No match was found after 15 seconds, dumping info]
[crossing-training: messages seen length: 14]
[crossing-training: message: But you aren't holding that.]
[crossing-training: message: Treylis continues to braid his vines.]
[crossing-training: message:  * Zoluren's Herald Navesi Daerthon joins the adventure.]
[crossing-training: message: [DRPrime]-DR:Raelok: "no idea how many boxes that is"]
[crossing-training: message: Treylis continues to braid his vines.]
[crossing-training: message: Sentoki puts his shaper in his backpack.]
[crossing-training: message: Sentoki gets a tapered steel rasp from inside his backpack.]
[crossing-training: message: [DRPrime]-DR:Etreu: "well give the stouts a go, might save you some coin at least."]
[crossing-training: message: Skein of Shadows  (1 roisan)]
[crossing-training: message: Manifest Force  (6 roisaen)]
[crossing-training: message: [DRPrime]-DR:Giulietta: "you gonna gank him?"]
[crossing-training: message: Treylis continues to braid his vines.]
[crossing-training: message: Rakkor concentrates intently on his technique as he continues to play a quiet serenade on his copper zills.]
[crossing-training: message: Treylis continues to braid his vines.]
[crossing-training: checked against [/You drop/i, /What were you/i]]
--- Lich: crossing-training has exited.
--- Lich: hunting-buddy active.

**Comment by MahtraDR** [comment]
This doesn't happen today with common-item predicates.
