### ISSUE TITLE
Support training high rank Athletics

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#18]
Hold something in hands during Athletics training if above a certain rank.

**Comment by rcuhljr** [comment]
Definitely slowing down at 400 athletics. I may try holding items to see if it helps, or just have them swim the segoltha.

**Comment by kamarcum** [comment]
@rcuhljr Did swimming work out? Should this be marked resolved?

**Comment by rcuhljr** [comment]
It seems decent enough now with swimming.
