### ISSUE TITLE
base-recipes.yaml has a dupe on metal flasks

### ISSUE THREAD

**Issue by hennii** [rpherbig/dr-scripts#1801]
```
- name: a small metal flask
  noun: flask
  volume: 5
  type: blacksmithing
  work_order: true
  chapter: 6
```
Is the correct one, and this is the dupe:
```
- name: a metal flask
  noun: flask
  volume: 5
  type: blacksmithing
  work_order: true
  chapter: 6
```

**Comment by rpherbig** [comment]
According to https://elanthipedia.play.net/Blacksmithing_products both of those exist (as well as `a large metal flask` which we don't appear to have in `base-recipes`). Is this causing a problem for you?

**Comment by Sarvatt** [comment]
See https://github.com/rpherbig/dr-scripts/pull/1743 - you just hit the gap where you need a journeyman book

**Comment by hennii** [comment]
@Sarvatt Ah, thank you for clarifying!
