### ISSUE TITLE
Can't turn in work orders while invisible

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#1803]
I know its generally understood training doesnt play nice with invisibility, but SOV is a pretty nice utility trainer and its only seeming to hang in this one spot turning in a workorder.  Was hoping its an easy fix.  I was going to write a simple trigger script or something in the meantime.

[workorders]>give log to Jakke

You can't do that while you're invisible.
I> 
[workorders]>give log to Jakke

You can't do that while you're invisible.
I> 
[workorders]>give log to Jakke

Side note, Sanowret kinda goes crazy if ur invisible too.

**Comment by jandersson** [comment]
In common, there is a method called `release_invisiblity` which will drop all invisiblity spells that are active.
