### ISSUE TITLE
Sanowret-crystal goes crazy while invisible

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#1804]
Not sure if there is a tag to suspend it while invisible or something, or if I should just work around it.

[sanowret-crystal]>unhide

[sanowret-crystal]>exhale sanowret crystal

Doing that would give away your hiding place.  It'd be more practical to just come out in the open first.
I> 
But you are not hidden!
I> 
Doing that would give away your hiding place.  It'd be more practical to just come out in the open first.
I> 
[sanowret-crystal]>unhide

[sanowret-crystal]>exhale sanowret crystal

But you are not hidden!
I> 
[sanowret-crystal]>unhide

[sanowret-crystal]>exhale sanowret crystal

Doing that would give away your hiding place.  It'd be more practical to just come out in the open first.
I>

**Comment by jandersson** [comment]
It should use the `release_invisibility` method we have. I'm not sure a passive script should be unhiding/releasing spells though.

**Comment by MahtraDR** [comment]
@rpherbig Can close this. sanowret-crystal.lic today has a check for, and returns if invisible, or hidden.

line 44

```
    return if hiding? || invisible?
```
