### ISSUE TITLE
If you are both on a ferry and going to the same hunting zone it will see each other over and over and not hunt anywhere

### ISSUE THREAD

**Issue by sprode** [rpherbig/dr-scripts#1807]
I'm not sure what this needs to be fixed but I just experienced it.   I broke the loop manually, but if neither were attentive, this could go on forever theoretically

**Comment by elBlanquito** [comment]
Hahah this is an awesome bug!

**Comment by elBlanquito** [comment]
Maybe, force buddy hunt or have a timer after a fail that is RNG seeded with a wide enough range so that it will eventually create a disparity in time offset and fix itself?

**Comment by KatoakDR** [comment]
> have a timer after a fail that is RNG seeded with a wide enough range so that it will eventually create a disparity in time offset and fix itself?

Yep, and that's what was implemented in https://github.com/rpherbig/dr-scripts/pull/4419

https://github.com/rpherbig/dr-scripts/blob/567483a6bd76c4f8b82800f8b04fe846b63ebed0/common-travel.lic#L304
