### ISSUE TITLE
Timer Class

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#1809]
Timers seem pretty ubiquitous in the script logic. Any thoughts about creating a Timer class in the Events script? It would standardize their creation and usage. 

```ruby
Timer.create('bacon-time', 60) # Creates countdown timer called bacon-time for 60 seconds
Timer['bacon-time'].timeleft # => 45
Timer['bacon-time'].duration # => 15
Timer['bacon-time'].expired? # => False
Timer.create('my_script') # Creates a stopwatch timer called 'my_script'
Timer['my_script'].reset # Resets 'my_script' timer
```

We can consolidate all the existing countdown timers like `dump_junk` using this and also allow for users to create stopwatch timers to time things like how long a script has been running.

**Comment by jandersson** [comment]
I was looking at this for inspiration: http://www.rubydoc.info/github/rubyworks/facets/Timer

**Comment by rpherbig** [comment]
Seems reasonable to me
