### ISSUE TITLE
Missing Astrology Messaging

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#1810]
Certain wounds I guess prevent using a telescope, not really sure which.  

> heal

Your body feels at full strength.
Your spirit feels full of life.
You have some minor abrasions to the right arm, some minor abrasions to the left arm, some minor abrasions to the right hand, some minor abrasions to the chest.
You have no significant injuries. 

You get a gloomwood telescope inlaid with silver from inside your grey pack.
s> 
[astrology]>center telescope on Dawgolesh

The pain is too much.
You are unable to hold the gloomwood telescope steady, and give up.
Roundtime: 5 seconds.

sR> 
Karhhsh's cambrinth armband emits a loud *snap*.

s> 
You feel fully attuned to the mana streams again.

s> 
[astrology: *** No match was found after 15 seconds, dumping info]

[astrology: messages seen length: 14]

[astrology: message: The pain is too much.]

[astrology: message: You are unable to hold the gloomwood telescope steady, and give up.]

[astrology: message: Roundtime: 5 seconds.]

[astrology: message: Read the Ripples  (5 roisaen)]

[astrology: message: Clear Vision  (28 roisaen)]

[astrology: message: Aura Sight  (29 roisaen)]

[astrology: message: Protection from Evil  (20 roisaen)]

[astrology: message: Destiny Cipher  (80 roisaen)]

[astrology: message: Piercing Gaze  (28 roisaen)]

[astrology: message: Karhhsh's cambrinth armband emits a loud *snap*.]

[astrology: message:  * Deflector Cerrano Da'Bigsnozaroo joins the adventure.]

[astrology: message: Karhhsh roots around the area for a moment.]

[astrology: message: Karhhsh forages around the area for a while and manages to collect a pile of rocks.]

[astrology: message: You feel fully attuned to the mana streams again.]

[astrology: checked against [/You put your eye/i, /open it to make any use of it/i]]

[astrology]>peer telescope

The pain is too much.
You are unable to hold the gloomwood telescope steady, and give up.
Roundtime: 5 seconds.
sR> 
[astrology]>stow telescope

You put your telescope in your grey pack.

**Comment by jandersson** [comment]
This messaging can trigger a safe-room healing run. Being too injured to play the zills in crossing-trainer is an example.
