### ISSUE TITLE
smart listen type ahead issue with Pick

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#1812]
So this weird instance actually came up 3 times in the exact same way since I moved my safe-room to a spot where I can catch a class.  For some reason some messaging gets ignored and I grab a second pet box which hangs the pick script.

--- Lich: go2 has exited.

> listen to Riphik
listen to Riphik

Riphik begins to lecture you on the proper usage of the Life Magic skill.
To learn from him, you must LISTEN TO Riphik.
  (LISTEN HELP for more options)
> 
[smartlisten: Checking if I should listen to a class on Life Magic]

[smartlisten: Attempting to listen to Riphik]

[smartlisten]>listen to Riphik 

You begin to listen to Riphik teach the Life Magic skill.
> 
You are already listening to someone.  You may wish to STOP LISTENING.
> 
[smartlisten]>stop listening

You feel fully rested.
> 
[hunting-buddy: ***STATUS*** EXECUTE pick]

--- Lich: pick active.

You are already listening to someone.  You may wish to STOP LISTENING.
> 
You stop listening to Riphik.
> 
[pick]>open my haversack

> 
That is already open.
> 
[pick]>open my backpack

That is already open.
> 
[pick]>open my carpetbag

> 
[pick]>rummage /B my haversack

That is already open.
> 
You rummage through an elongated black haversack looking for boxes but there is nothing in there like that.
> 
[pick]>rummage /B my carpetbag

You rummage through a charming tapestry carpetbag patterned with sprawling cabbage roses looking for boxes and see a misshaped pine trunk, a sturdy driftwood trunk, a moldy wooden trunk, a crust-covered mahogany skippet, a mud-stained copper box, a poorly made brass trunk, a mud-stained copper box, a salt-stained copper casket, a dull copper casket, a reinforced pine casket, a sturdy steel skippet, a mildewy driftwood skippet, a mildewy pine skippet, a plain steel skippet, a crust-covered mahogany crate, a poorly made brass crate, a poorly made iron crate and a corroded copper crate.
> 
Riphik begins to lecture you on the proper usage of the Life Magic skill.
listen to Riphik
listen to Riphik
To learn from him, you must LISTEN TO Riphik.
  (LISTEN HELP for more options)
> 
[pick]>get my trunk from my carpetbag

[smartlisten: Checking if I should listen to a class on Life Magic]

[smartlisten: Attempting to listen to Riphik]

[smartlisten]>listen to Riphik 

Sorry, you may only type ahead 1 command.
Sorry, you may only type ahead 1 command.
> 
You get a misshaped pine trunk from inside your tapestry carpetbag.
> 
You begin to listen to Riphik teach the Life Magic skill.
> 
[smartlisten]>listen to Riphik 

[pick]>get my trunk from my carpetbag

You are already listening to someone.  You may wish to STOP LISTENING.
> 
You get a sturdy driftwood trunk from inside your tapestry carpetbag.
> 
The twisted steel buckle of your thighband pulses with a soft light for a moment, and you feel more focused.
> 
[smartlisten]>listen to Riphik 

[smartlisten]>stop listening

[pick]>get my trunk from my carpetbag

[pick]>disarm my trunk identify

Sorry, you may only type ahead 1 command.
Sorry, you may only type ahead 1 command.
> 
You are already listening to someone.  You may wish to STOP LISTENING.
> 
You stop listening to Riphik.
> 
You notice Riphik attempting to conceal his spell preparations.
Riphik assumes a meditative stance, concentrating on something.
> 
[smartlisten]>stop listening

[pick]>disarm my trunk identify

But you aren't listening to anyone.
> 
You notice a sphere with some type of lacing around it.  It seems a small portion of the trap has been removed.
Roundtime: 3 sec.

R> 
[smartlisten]>stop listening

[pick]>disarm my trunk identify

...wait 2 seconds.
R> 
...wait 2 seconds.
R> 
[pick]>disarm my trunk careful

You notice a sphere with some type of lacing around it.  It seems a small portion of the trap has been removed.
Roundtime: 3 sec.

R> 
[pick]>pick my trunk blind

> 
If you're going to use a lockpick from the lockpick ring you'd better have an empty hand first.

**Comment by Sarvatt** [comment]
This is exactly what happened to me with shaping in https://github.com/rpherbig/dr-scripts/issues/1812, I had just edited out the teaching line

**Comment by rpherbig** [comment]
Do you maybe have smart listen running twice? It's odd that it tried to
listen twice. Check ;list

**Comment by mwest152** [comment]
smartlisten only running once, but i do have also in my YAML listen: true

**Comment by Sarvatt** [comment]
I put a more complete log of it happening in shaping in https://github.com/rpherbig/dr-scripts/issues/1798, its the same thing though, listening twice while doing other things

**Comment by mwest152** [comment]
Because i had smart listen up, i didnt notice genie had a built in trigger on this too.  Though I think the 1 listen out of smart listen was still hanging shaping.
