### ISSUE TITLE
Airship support

### ISSUE THREAD

**Issue by elBlanquito** [rpherbig/dr-scripts#1820]
Suggestions for Shard to Aesry Airship solutions? Will just a string proc do it?

**Comment by jandersson** [comment]
Probably - StringProcs are kind of a pain to write though. I personally like writing it in bescort because its easier to update later and you can write it out cleanly in a text editor rather than pack it all into a single line.

**Comment by rcuhljr** [comment]
bescort support for airship added, just needs hooked into go2.

**Comment by rpherbig** [comment]
Could someone hook up the sand barge at the same time? see #1566 (afa77cdd25ff1e76d762ee1c2c2ca5acd38eb0b0)

**Comment by elBlanquito** [comment]
Great work guys. Thank you so much!
