### ISSUE TITLE
Blank Line Feeds during weapon_training with Targeted Magic: ''

### ISSUE THREAD

**Issue by brycole** [rpherbig/dr-scripts#1822]
Hey all,

If combat training is currently on "Targeted Magic: ''" under weapon_training: settings, and you are casting a spell, combat-trainer sends blank line feeds.

This turns into a bigger issue if you are using combat_spell_training: with 3 spells because it seems to take priority over weapon_training:. I believe there is some sort of cooldown for combat_spell_training but it may be non-existent if you are cycling through 3 spells.

This is probably working as intended but maybe combat-trainer should have a secondary skill for TM if you are casting a spell? 

This behavior can be fixed by removing TM From weapon_training and/or disabling combat_spell_training.

Thanks!

**Comment by MahtraDR** [comment]
Closing. Too old an issue to pursue today. Can treat new issues as fresh.
