### ISSUE TITLE
light_source: support ideas?

### ISSUE THREAD

**Issue by elBlanquito** [rpherbig/dr-scripts#1823]
What would be the most effective way to implement light_source support?

gaethzen_item: 

is there any way to do it for Non-Magic Users that is maximally inclusive? Or is it the case that lighting conditions aren't mission critical in any meaningful sense? Will not having a light source cause anything to fail?

**Comment by elBlanquito** [comment]
Well I can confirm that mining in a dark area without a light source is a no-go, so sea_caves might be un-mine-able until I figure out a work around.

**Comment by rcuhljr** [comment]
Request general slot magical lights next pay fest >.>

**Comment by elBlanquito** [comment]
I was considering figuring out a basic algorithm for held gaethzen (lowering it at feet) and torches for NMU or when nerves are so shot that gaetzhen is not  an option.

If I look at what's going on and put together an algorithm with pseudo-code based on matches, would anyone be willing to coach me on coding that up (not asking for hand-holding, just to give an outline and direct to resources when needing guidance?)

**Comment by elBlanquito** [comment]
Nah, i'm going to work on this!  I think i'm going to stick strictly gaethzen at first to keep it simple, sorry NMU.

**Comment by elBlanquito** [comment]
Upon reflection, just writing a simple script to run as a before: action with one's own guild-specific lighting ability is, in my opinion, the best way to go about this. Therefore, unless there is some pressing need for this in the future, I'm going to lay this to rest and continue working on something that others want and can appreciably benefit from!
