### ISSUE TITLE
Sand Barge Support

### ISSUE THREAD

**Issue by elBlanquito** [rpherbig/dr-scripts#1831]
Would someone who is capable be willing to add ;bescort support for the Sand Barge in Muspar'i?

I'd love to watch you or see a log, if possible and you are so willing, to get an idea how it is done.

**Comment by rpherbig** [comment]
This should already be supported (`;bescort sandbarge hvaral oasis` for example). Can you give that a try and let us know how it goes?

**Comment by elBlanquito** [comment]
omg, I apologize, when i ;bescort help I didn't see it listed last night. Sorry for wasting your time. Definitely had a breakthrough learning syntax last night and am working through a few minor but functional commits! 
Sorry to waste your time!

**Comment by jandersson** [comment]
The script exists, but im not sure if its been hooked into go2 yet.
