### ISSUE TITLE
Muspar'i Shard Support + (sand barge hooks?)

### ISSUE THREAD

**Issue by cafeTechne** [rpherbig/dr-scripts#1835]
Someone (Willower) asked if I could put up a bug report requesting support for astral pathways to Muspar'i. 

In addition, i closed out the ticket yesterday before reading Jonas' comment that he wasn't sure if bescort was hooked into go2 for Muspar'i. 

Please advise on how I may support this task. Thank you!

**Comment by jandersson** [comment]
`;bescort ways muspari` will take you to muspari via AP

**Comment by elBlanquito** [comment]
I'll let her know, are the hooks good to go Jonas? If so, I'll close this out. If not, I can learn what I need to learn to make that happen if you can point me in the right direction!

**Comment by jandersson** [comment]
Take a look at https://github.com/rpherbig/dr-scripts/pull/1566 there's a couple of stringprocs in there you could test.

**Comment by elBlanquito** [comment]
Outstanding! Thank you very much! This is great!

**Comment by rpherbig** [comment]
The stringproc example in #1566 only has `start_location`. You'll need to change it to add an `end_location`.

**Comment by Redheadmoonie** [comment]
The Muspar'i shard location on the Muspar'i side isn't included in bescort. Can go to there, but try returning and it errors out

**Comment by jandersson** [comment]
Finally got around to doing this. Sandbarge is hooked in to the mapdb now. You can go ahead and close this.
