### ISSUE TITLE
Circlecheck requirements are off for Moon mages - "You're ready to circle!"

### ISSUE THREAD

**Issue by tdbrown1985** [rpherbig/dr-scripts#1840]
>ask kss about cir

"Well, Walper," the guildleader says, "You have some work to do before you can advance to circle 52 in our order.

Regarding your survival knowledge, you should work on 5th Survival (Locksmithing).

Once you've accomplished that, come see me again."
>
Kssarh drops a book on a table and mutters a few choice words at Kryeus.
>;circlecheck
--- Lich: circlecheck active.
Your next level will award: 151 TDPs
***You're ready to circle!***
You have enough 5th Survival (Locksmithing) for circle 51 and need 1 (84) ranks for circle 52

**Comment by rcuhljr** [comment]
I'm not seeing the problem? If you haven't hit info since the last time you circled it still thinks you're ready to circle because it thinks you're 50 or lower. As you can see below it points out that you're not ready for circle 52 because you need lockpicking, like the guild leader said.

**Comment by tdbrown1985** [comment]
The problem was it was saying I was ready to circle when I wasn’t, however, after typing info and rechecking ;circlecheck it no longer says that so apparently that was the problem. I didn’t know info would reset it. Thanks
