### ISSUE TITLE
;buff set names should be case insensitive

### ISSUE THREAD

**Issue by brycole** [rpherbig/dr-scripts#1841]
You cannot use a skill name or any part of the skill name in a waggle set.
```
  Warding:
    Manifest Force:
      abbrev: maf
      recast: 99999
      mana: 5
      cambrinth:
      - 5
      - 5
      - 5
      - 4

> ,buff Warding

--- Lich: buff active.

--- Lich: buff has exited.

> ,buff 1Warding

--- Lich: buff active.

--- Lich: buff has exited.

> 
```

**Comment by rpherbig** [comment]
I think the issue is actually capitalization. Try naming it `warding` (all lower case).

**Comment by intangibles** [comment]
Great, that worked.

I had tried that (and like 50 other variations) but something else must have been blocking it when i was trying lower case.  

Thank you!

**Comment by rpherbig** [comment]
Overcome by #1850

**Comment by MahtraDR** [comment]
@rpherbig Close this one too?
