### ISSUE TITLE
Base prep_scaling_factor: is set way to high even for primary magics

### ISSUE THREAD

**Issue by Maledar** [rpherbig/dr-scripts#1847]
We've constantly had to tell people that are backfiring low-mid levels that to change their prep_scaling_factor: 0.85 most consensus is that .85 or .80 is fine but .98 is causing too many backfiring, leading to no learning and more healing

**Comment by Sarvatt** [comment]
This issue has come up from people a lot on lichnet, I ran into it myself as a ranger. 98% is way too high and I can't reliably cast in crossing-training at that without killing my nerves which makes it even harder to cast at 98% and it's a downward spiral from there. a more sane default like 85 or 90% would be appreciated.

**Comment by MahtraDR** [comment]
@rpherbig This can be closed. The current default is .85
