### ISSUE TITLE
Elanthipedia Dependency Documentation

### ISSUE THREAD

**Issue by intangibles** [rpherbig/dr-scripts#1848]
Hi All,

I think we need to come up with a better system for documenting dependency variables in Elanthipedia. Tons of stuff is missing.  I just introduced a new player who has been going through the YAML and he has painstakingly made it apparent that lots of stuff has not been documented.

Perhaps we shouldn't close any PRs until an item has been documented? Is there any better way to track this? Thoughts?

@rcuhljr @rpherbig

**Comment by jandersson** [comment]
The number of sample profiles is kind of overwhelming too. They have examples of setting usage, but its not clear which one you should check for what settings.

**Comment by intangibles** [comment]
@jandersson 

Great idea.

An example of this is... I was also trying to explain hunting files and back files, the order of loading YAMLs from base, setup, hunting files, etc etc, and that's not something that can really be explained in a "variable setting."

My friend is an old warmie who returned and I know Qetu's backfile has a great setup, but sending him there was a horrible idea.  Sounds like Qetu needs to write a guide for his YAML :).  Maybe we can put this type of thing in comments in profiles that are hosted in Git?

**Comment by rpherbig** [comment]
Are these helpful? (there are some others, I just linked to a few)

https://github.com/rpherbig/dr-scripts/wiki/Introduction-to-Character-Settings

https://github.com/rpherbig/dr-scripts/wiki/YAMLs-and-You-pt-1:-Basic-YAML-Information

https://github.com/rpherbig/dr-scripts/wiki/YAMLs-and-You-pt-2:-Creating-Your-Own-YAML

**Comment by intangibles** [comment]
@rpherbig 

Yes! those are great.  I just poked around seeing how a new player would navigate to those and it wasn't exactly apparent.  I think maybe we should add a single page that lists all the new player guides in hyperlinks and toss that page up in ,links script.

Like... a new player shouldn't end up here

https://elanthipedia.play.net/Lich_script_repository

Before the other links.

**Comment by jandersson** [comment]
Does something like this make sense? https://github.com/rpherbig/dr-scripts/wiki/DR-Scripts-Tutorials

**Comment by intangibles** [comment]
Yeah, this is a great start.  I think we should have a paper trail from dependency installation as well.

Also, I dont know anything about wiki editing but maybe having a bullet point of links that is similar to the blue links on the far right.
