### ISSUE TITLE
Kill Scripts when Sent to the Junk Yard

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#1854]
Once and awhile i end up at the junk yard.  It would be cool if training-manager recognized the room and killed all the scripts, leaving you in afk mode.  Just seems cleaner and maybe safer.

**Comment by rpherbig** [comment]
So far we've been handling this on a case-by-case basis, so an individual script can know how to recover.

For example: https://github.com/rpherbig/dr-scripts/blob/master/steal.lic#L238-L245

Which scripts have been sending you to the Junk Yard?

**Comment by wscherer420** [comment]
It usually occurs for me during combat-trainer.  Just over hunting.  I pack all my gems into my pack instead of a gem pouch.  I prefer to just fill pouch with pack rather than swap pouches and run ;sell.  So i'll get overloaded with gems from hunting.  

Because ;sell only sells items from the pouch you're wearing right?  It doesn't check other pouches for gems and sell those as well?

**Comment by MahtraDR** [comment]
Closing. Not enough data, and four+ years old. We can treat new reports as fresh.
