### ISSUE TITLE
loot_specials: not working

### ISSUE THREAD

**Issue by brycole** [rpherbig/dr-scripts#1856]
This is my YAML currently.  For some reason it's not using loot_specials.

```
loot_specials:
- name: kyanite stones
  bag: bag
- name: jadeite stones
  bag: bag
```

```
> [combat-trainer]>loot
> 
> You search the s'sugi malchata.
> The malchata was carrying some kyanite stones, 7 copper coins, 8 bronze coins, and 6 silver coins!
> 
> > 
> [combat-trainer]>stow copper coins
> 
> You pick up 7 copper Dokoras.
> 
> > 
> [combat-trainer]>stow bronze coins
> 
> You pick up 8 bronze Dokoras.
> 
> > 
> [combat-trainer]>stow silver coins
> 
> [combat-trainer]>stow stones
> 
> You pick up some kyanite stones.
> You open your pouch and put the kyanite stones inside, closing it once more.
```

thanks!

**Comment by rpherbig** [comment]
> [combat-trainer]>stow stones

I'm pretty sure this means `combat-trainer` is checking for 'stones', i.e. the noun only, without adjectives. Can you try removing the adjective from your `loot_specials`?

**Comment by rcuhljr** [comment]
Currently you'd need to have the same name in your lootables list as in the loot special, so you'd probably need to subtraction stones, and addition kyanite/jadeite. It's probably  possible to rework the loot logic to pass in both the full item name, and it's loot noun/adj.

**Comment by intangibles** [comment]
Okay, I've added the loot stuff in, will report back if it works.

I also checked Etreus and Chunos YAML profiles for the kyanite examples first, so imagine it's not working for them either? Unless I've got something else borked on my end.

**Comment by rcuhljr** [comment]
It doesn't work for Etreu, I just assumed I'd deleted the setting already because they weren't showing up in my bag anymore.

**Comment by intangibles** [comment]
Ahh! Okay, i'll report back, but might be awhile.

**Comment by mwest152** [comment]
i pulled some out of a chest and properly stored them in my duffel bag the other day.  I just assumed they weren't dropping very often.

**Comment by MahtraDR** [comment]
Can't reproduce this today. We can treat new reports as fresh.
