### ISSUE TITLE
braid.lic - standalone mechlore script

### ISSUE THREAD

**Issue by Missah** [rpherbig/dr-scripts#1857]
Any chance that someone could tweek the braid.lic script?

Currently it doesn't remove hand items (gloves, etc).

Also, disposing of the rope is a little wonky as well.

I'm hoping that if this is an easy fix, someone can take a few minutes to fix it?

Thanks!

**Comment by rpherbig** [comment]
`braid.lic` isn't one of our scripts, so I'd prefer us not take/copy over someone else's script. We could break out the mech lore logic in `crossing-training` though.

**Comment by rpherbig** [comment]
@Missah does `crossing-training` do what you need? It looks easy enough to move to a standalone script, I just want to make sure it'll meet your needs.

**Comment by Missah** [comment]
Yes.  The mechlore part of crossing-training trains me.  If you could move that to a standalone, that would be perfect.

**Comment by rpherbig** [comment]
If you have a few minutes, could you restart dependency (which will download the new script) and give `;mech-lore` a try?

**Comment by Sarvatt** [comment]
>;mech-lore
--- Lich: mech-lore active.
[drinfomon]><snip stats here>
>
--- Lich: error: uninitialized constant Scripting::MechLore::EquipmentManager
	mech-lore:13:in `initialize'
	mech-lore:79:in `new'
--- Lich: mech-lore has exited.


Adding equipmanager to this line seems to work though

custom_require.call(%w[common common-items drinfomon equipmanager])

**Comment by Missah** [comment]
You must of fixed it....works great!!  Thank you so much!

**Comment by Sarvatt** [comment]
oh, it worked for you? wonder why it errored for me, it's still failing every startup. indeed thanks for the script though!

**Comment by rpherbig** [comment]
I pushed the fix, you may need to restart dependency to get it
