### ISSUE TITLE
zills with injuries

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#187]
You cannot play the copper zills in your current physical condition

**Comment by rpherbig** [comment]
Is there a log to go with this?

What is the desired behavior? Just add another option to `bput("play #{UserVars.song}", ...)`?

**Comment by rcuhljr** [comment]
Probably just add another option, that's the exact message above. I mean we could set an injured flag to true and have crossing training go to the empath if that flag is set to true. We could also detect when head injuries are preventing cambrinth usage.
