### ISSUE TITLE
add arg option for refilling lockpicks in pick

### ISSUE THREAD

**Issue by fireballx777** [rpherbig/dr-scripts#1883]
It would be nice if `pick.lic` had an option to run with an arg to override the `skip_lockpick_ring_refill` setting.  This might be a niche case, but I like to run `pick` in `after` for certain hunts, and depending on what I'm hunting, I sometimes do and sometimes don't want it to run back to town to refill locks.

**Comment by rcuhljr** [comment]
It's already supported in that you just make a yaml file with that setting to false and call it as an argument to pick.
