### ISSUE TITLE
missing messaging combat-trainer

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#1899]
[combat-trainer]>sheath my sling

A s'sugi malchata plunges one of its clawed hands into the sand, clucking and chattering wildly.  The sand about your feet begins to swirl until it rises up around you, holding you fast in place!
Roundtime: 1 sec.
[You're solidly balanced with no advantage.]

R> 
...wait 1 seconds.
R> 
[combat-trainer]>sheath my sling

You don't seem to be able to move to do that.

> 
[combat-trainer: *** No match was found after 15 seconds, dumping info]

[combat-trainer: messages seen length: 41]

**Comment by rpherbig** [comment]
What's the right way to recover? Pause for a second and try again?

**Comment by mwest152** [comment]
yeah sorry, kinda like being stunned.
