### ISSUE TITLE
Add 'proxy' (transfer-on-every-deposit) to bankbot

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#1909]
This would be similar to how `transfer` (a one-time action) currently works, but automatically whenever a deposit is made.

For the help content:
```
      "  (proxy) set [character name] - all deposits you make will now be directed to the account of [character name]. This overwrites any previous proxy. [Character name] must already have an account with bankbot.",
      "  (proxy) (list|clear) - list or clear your deposit proxy.",
```

**Comment by MahtraDR** [comment]
@rpherbig The comments are in the file, but I don't see the function. I'll leave it open, because it's yours. :)

**Comment by rpherbig** [comment]
Bankbot is basically dead due to a change in Simu's policy. People could still run it, I guess, but it's no longer approved and money will be confiscated.

**Comment by MahtraDR** [comment]
Thanks for that note. I'll close out all the bankbot issues now.
