### ISSUE TITLE
Fix how bankbot communicates to the user

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#1910]
Right now, bankbot _mostly_ replies via the same channel that was used. For example, if you whisper `balance`, it should whisper the result back (or use LNet if `balance` came from LNet).

There are still some inconsistencies in a few places (from when bankbot _only_ supported whispers). I _think_ I've marked them all with TODOs.

**Comment by MahtraDR** [comment]
Closing as per https://github.com/rpherbig/dr-scripts/issues/1909#issuecomment-1032112683
