### ISSUE TITLE
train_with_moon: true

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1916]
Request for an option to ONLY run ;hunting (stand alone or with :crossing-training) when a moon is out.

Basically no hunting if no moons, or hunting with moons

**Comment by mwest152** [comment]
You would really not want to hunt if there is no moons?  Sometimes it can be like hours.

**Comment by MahtraDR** [comment]
@Aurayn Is this still an issue for you?

**Comment by MahtraDR** [comment]
@KatoakDR this might go well with your idea for moons-training

**Comment by KatoakDR** [comment]
Thanks, @MahtraDR 

Seems this was resolved per https://github.com/rpherbig/dr-scripts/pull/3772 in hunting-buddy

And will more generically be supported by https://github.com/rpherbig/dr-scripts/pull/5410 in T2
