### ISSUE TITLE
Blowgun and dart support

### ISSUE THREAD

**Issue by thatgirl0820** [rpherbig/dr-scripts#1925]
Is there any way using a blowgun and the blowgun darts could be added so they are supported for hunting? I believe blowguns are considered brawling. Thanks!

**Comment by rpherbig** [comment]
Could you post a log here of getting your blowgun, loading it, a few attacks, and stowing it? If anyone works on this we will need the in-game messaging.

**Comment by thatgirl0820** [comment]
Here's what I have from one cougar kill. Let me know if you need more...

The cougar begins to advance on you!
The cougar is still a distance away from you and is closing steadily.
>hold blow
You remove a purpleheart blowgun engraved with twisting vines from your belt.
>

>load blowg
You reach into your quiver to load the purpleheart blowgun with a blowgun dart.
Roundtime 2 sec.
>

>aim coug
You begin to target a cougar.

You think you have your best shot possible now.
>shoot
< Moving with indomitable grace, you fire a blowgun dart at a cougar.  A cougar fails to dodge, taking the full blow.  The dart lands a massive strike that lightly bruises the cougar's side with an attack which fails to pierce the skin, lightly stunning it.

The blowgun dart lodges itself shallowly into the cougar!
[You're solidly balanced and in good position.]
[Roundtime 1 sec.]
>
You feel fully rested.
>load blowg
You reach into your quiver to load the purpleheart blowgun with a blowgun dart.
Roundtime 2 sec.
>aim coug
>
You begin to target a cougar.
>

You think you have your best shot possible now.
>shoot
< Moving as a single sinuous force, you fire a blowgun dart at a cougar.  A cougar fails to dodge, mis-stepping and blundering into the blow.  The dart lands a vicious strike that cuts the lumbar region just enough to bleed a little, stunning it.

The blowgun dart lodges itself shallowly into the cougar!
[You're solidly balanced and in good position.]
[Roundtime 1 sec.]
>load blowg
You reach into your quiver to load the purpleheart blowgun with a blowgun dart.
Roundtime 2 sec.

>aim coug
You begin to target a cougar.

You think you have your best shot possible now.

>shoot
< Driving in like the overwhelming force of a hurricane, you fire a blowgun dart at a cougar.  A cougar attempts to dodge, moving directly into the blow.  The dart lands a massive strike that drives the blowgun dart deep into the ribcage to savage the lungs.

The blowgun dart lodges itself deeply into the cougar!
The cougar falls to the ground and lies still.
[You're solidly balanced]
[Roundtime 1 sec.]
>

>tap blow
You tap a purpleheart blowgun engraved with twisting vines that you are holding.

>wear blowg
You attach a purpleheart blowgun engraved with twisting vines to your belt.


You search the cougar.
Lodged into it was a blowgun dart, a blowgun dart, and a blowgun dart.
You find nothing of interest.
>

>get dart
You pick up a blowgun dart.
>stow dart
You put your dart in your thigh quiver.

>get dart
You pick up a blowgun dart.
>stow dart
You put your dart in your thigh quiver.
>get dart
>stow dart
You pick up a blowgun dart.
>
You put your dart in your thigh quiver.
>get dart
You get some blowgun darts from inside your thigh quiver.
>stow dart
You put your darts in your thigh quiver.
>
>hold blowg
You remove a purpleheart blowgun engraved with twisting vines from your belt.
>
>stow blowg
You put your blowgun in your suede haversack.

>get blowg
You get a purpleheart blowgun engraved with twisting vines from inside your suede haversack.

>wear blowg
>
You attach a purpleheart blowgun engraved with twisting vines to your belt.

**Comment by rpherbig** [comment]
Note to anyone that picks this up: the `offhand_thrown` setting might be a pattern we could follow, but it doesn't include any logic for loading.

**Comment by rpherbig** [comment]
Done in #2092 (1c418096935f3e1417296cc225163b5738f51727)

Thanks @Ry7n !
