### ISSUE TITLE
;Sew broken

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#1930]
It is putting the cloth back in a container for some reason.....

https://pastebin.com/sPtUkyuB

[sew]>order 6

The attendant says, "You can purchase 100 yards of cotton thread for 777 Lirums.  Just order it again and we'll see it done!"

[sew]>order 6

The attendant takes some coins from you and hands you 100 yards of cotton thread.

[sew]>put my cotton thread in my duffel bag

You put your thread in your duffel bag.

[sew]>get my tailoring book

You get a book of master tailoring instructions from inside your duffel bag.

[sew]>turn my book to chapter 2

You turn your book to chapter 2, entitled "Cloth Decorative Wear".

[sew]>read my book

              -=    Chapter 2 : Cloth Decorative Wear    =-

 Page 1: some cloth socks                        Page 29: a sleeveless cloth shirt
 Page 2: some cloth ankle socks                  Page 30: a cloth shirt
 Page 3: a cloth armband                         Page 31: a cloth cloak
 Page 4: some cloth fingerless gloves            Page 32: a cloth dress hat
 Page 5: a cloth ankleband                       Page 33: a cloth top hat
 Page 6: a cloth eyepatch                        Page 34: some baggy cloth pants
 Page 7: some cloth knee socks                   Page 35: a cloth dress
 Page 8: some pleated cloth gloves               Page 36: a knee-length cloth dress
 Page 9: some elbow-length gloves                Page 37: a front-laced cloth dress
 Page 10: a cloth headband                       Page 38: a billowing cloth shirt
 Page 11: a cloth belt                           Page 39: a baggy cloth shirt
 Page 12: a cloth scarf                          Page 40: a cloth tunic
 Page 13: some elegant cloth gloves              Page 41: some cloth robes
 Page 14: some cloth slippers                    Page 42: some cloth dress pants
 Page 15: some cloth field shoes                 Page 43: a floor-length cloth dress
 Page 16: a cloth hat                            Page 44: a cloth gown
 Page 17: a cloth dunce hat                      Page 45: a cloth dress shirt
 Page 18: a segmented cloth belt                 Page 46: a short-sleeved tunic
 Page 19: a cloth dress belt                     Page 47: a formal cloth tunic
 Page 20: a cloth commoner's cloak               Page 48: a cloth tabard
 Page 21: a cloth head scarf                     Page 49: a hooded cloth cloak
 Page 22: a cloth veil                           Page 50: a cloth cape
 Page 23: a floppy cloth hat                     Page 51: some hooded cloth robes
 Page 24: a double-wrapped belt                  Page 52: a deeply-hooded cloak
 Page 25: some cloth pants                       Page 53: a cloth mage's robe
 Page 26: a cloth skirt                          Page 54: some flowing cloth robes
 Page 27: a cloth kilt                           Page 55: a cloth shaman's robe
 Page 28: a cloth sash                           

[sew]>turn my book to page 53

You turn your book to page 53, instructions for crafting a cloth mage's robe.

[sew]>study my book

You scan the mage's robe instructions with a glance and quickly realize the design is far beyond your abilities.
You now feel ready to begin the crafting process.
Roundtime: 8 sec.

[sew]>put my book in my duffel bag

You put your book in your duffel bag.

[sew]>get my cloth

You get some burlap cloth from inside your hunting pack.

*[sew]>put my burlap cloth in my duffel bag

You put your cloth in your duffel bag.*

[sew]>get my scissors

You get some razor sharp scissors crafted from animite from inside your duffel bag.

[sew]>cut my cloth with my scissors

You must be holding the burlap cloth to do that.

**Comment by jandersson** [comment]
Did you have something in your hands?

**Comment by jandersson** [comment]
Looking at line 181 in sew.lic.. `stow_item(left_hand) if checkleft` which it does right before you get the scissors

**Comment by Aurayn** [comment]
I cant tell from my log

**Comment by Aurayn** [comment]
Let me make sure my hands are empty and manually run it

**Comment by Aurayn** [comment]
So manual run confirming nothing in hands works fine. A loud hmmmmmmmmm fills the room.

**Comment by jandersson** [comment]
That sounds good. You could try putting something in your right hand and starting the sew script and see if you can recreate the issue.

**Comment by jandersson** [comment]
For what its worth, ive been training outfitting with sew the past few days without hitting this

**Comment by Aurayn** [comment]
nope same issue..... lemme see about posting the log.. nope too bag Jonas I will slack it to you

**Comment by jandersson** [comment]
```
[sew]>push my robe with my needles

With expert precision you wind your needle back and forth over the robe, stopping only every so often to straighten the fabric.

Two layers of the fabric won't cooperate and could use some pins to align them.
Roundtime: 32 sec.
The melody of Lindale's song turns to a more sonorous theme, dancing in a stately cadence that allows certain words to linger on the air.
Lindale begins a quiet concerto on his copper zills with only the slightest hint of difficulty.
Blackwater gets a corroded brass coffer from inside his haversack.
Blackwater looks up from the brass coffer with a satisfied grin.
Crannach puts his telescope in his hunting pack.
Crannach gets an ivory telescope inlaid with a ruby-eyed golden dragon from inside his hunting pack.
Crannach stops playing his song.
Crannach puts his eye to an ivory telescope inlaid with a ruby-eyed golden dragon.
Anshelm stumbles only slightly as he continues to play a hymn on his copper zills.
Blackwater puts his coffer in his carryall.
Blackwater gets a poorly made steel crate from inside his haversack.
Blackwater looks up from the steel crate with a satisfied grin.
The gentle rain patters down on the surface of Lindale's copper zills.
Lindale stops playing his song.
Lindale wandered down a small footpath.
Crannach puts his telescope in his hunting pack.
Crannach gets an ivory telescope inlaid with a ruby-eyed golden dragon from inside his hunting pack.
Crannach puts his eye to an ivory telescope inlaid with a ruby-eyed golden dragon.
The air around Anshelm shimmers with a weak yellow light that quickly disperses.
Blackwater begins to fiddle with a poorly made steel crate.
Blackwater looks up from the steel crate with a satisfied grin.
Treylis stops practicing his climbing skills.
Treylis finishes playing a halting aria on his copper zills.

[sew]>put my sewing needles in my duffel bag

You put your needles in your duffel bag.

[sew]>get my pins

What were you referring to?

[sew: You seem to be missing: pins]

--- Lich: sew has exited.

--- Lich: sew active.

[sew]>tap my cotton thread

You tap some cotton thread inside your duffel bag.

[sew]>get my tailoring book

You get a book of master tailoring instructions from inside your duffel bag.

[sew]>turn my book to chapter 2

You turn your book to chapter 2, entitled "Cloth Decorative Wear".

[sew]>read my book

              -=    Chapter 2 : Cloth Decorative Wear    =-

 Page 1: some cloth socks                        Page 29: a sleeveless cloth shirt
 Page 2: some cloth ankle socks                  Page 30: a cloth shirt
 Page 3: a cloth armband                         Page 31: a cloth cloak
 Page 4: some cloth fingerless gloves            Page 32: a cloth dress hat
 Page 5: a cloth ankleband                       Page 33: a cloth top hat
 Page 6: a cloth eyepatch                        Page 34: some baggy cloth pants
 Page 7: some cloth knee socks                   Page 35: a cloth dress
 Page 8: some pleated cloth gloves               Page 36: a knee-length cloth dress
 Page 9: some elbow-length gloves                Page 37: a front-laced cloth dress
 Page 10: a cloth headband                       Page 38: a billowing cloth shirt
 Page 11: a cloth belt                           Page 39: a baggy cloth shirt
 Page 12: a cloth scarf                          Page 40: a cloth tunic
 Page 13: some elegant cloth gloves              Page 41: some cloth robes
 Page 14: some cloth slippers                    Page 42: some cloth dress pants
 Page 15: some cloth field shoes                 Page 43: a floor-length cloth dress
 Page 16: a cloth hat                            Page 44: a cloth gown
 Page 17: a cloth dunce hat                      Page 45: a cloth dress shirt
 Page 18: a segmented cloth belt                 Page 46: a short-sleeved tunic
 Page 19: a cloth dress belt                     Page 47: a formal cloth tunic
 Page 20: a cloth commoner's cloak               Page 48: a cloth tabard
 Page 21: a cloth head scarf                     Page 49: a hooded cloth cloak
 Page 22: a cloth veil                           Page 50: a cloth cape
 Page 23: a floppy cloth hat                     Page 51: some hooded cloth robes
 Page 24: a double-wrapped belt                  Page 52: a deeply-hooded cloak
 Page 25: some cloth pants                       Page 53: a cloth mage's robe
 Page 26: a cloth skirt                          Page 54: some flowing cloth robes
 Page 27: a cloth kilt                           Page 55: a cloth shaman's robe
 Page 28: a cloth sash                           


[sew]>turn my book to page 53

You turn your book to page 53, instructions for crafting a cloth mage's robe.

[sew]>study my book

You scan the mage's robe instructions with a glance and quickly realize the design is far beyond your abilities.
You now feel ready to begin the crafting process.
Roundtime: 4 sec.
Crannach puts his telescope in his hunting pack.
Crannach gets an ivory telescope inlaid with a ruby-eyed golden dragon from inside his hunting pack.
Crannach puts his eye to an ivory telescope inlaid with a ruby-eyed golden dragon.

[sew]>put my book in my duffel bag

You put your book in your duffel bag.
Blackwater looks up from the steel crate with a satisfied grin.

[sew]>get my cloth

Anshelm continues to perform his unextraordinary hymn on his copper zills.
You get some burlap cloth from inside your duffel bag.

[sew]>put my burlap cloth in my duffel bag

You put your cloth in your duffel bag.

[sew]>get my scissors

You get some razor sharp scissors crafted from animite from inside your duffel bag.

[sew]>cut my cloth with my scissors

You must be holding the burlap cloth to do that.
```
It looks like the script doesn't know how to buy pins or the recipe could be wrong.. but i pasted the relevant part of the log here. The script couldn't find pins, leaving you with an unfinished item in your hands then started up `;sew` again without stowing or trashing it.

**Comment by jandersson** [comment]
Looking at base-recipes.yaml, the recipe seems to be missing the pins

**Comment by Aurayn** [comment]
you buy them like you would other ingredients

**Comment by Aurayn** [comment]
oil, glue, stain etc

**Comment by jandersson** [comment]
The script should buy the pins if you run out of them. It looks like it won't buy them if you never had any.

**Comment by jandersson** [comment]
Try buying some yourself, then it should be fine

**Comment by Aurayn** [comment]
will do
