### ISSUE TITLE
Bescort bug with people trying to swim Faldesu river with under 200 atheltics

### ISSUE THREAD

**Issue by Maledar** [rpherbig/dr-scripts#1931]
Seems like a simple fix... these are the lines that need to be changed..but I'm lost on how to do a PR

Line 490 on Bescort
from
    if UserVars.athletics >= 140
to
    if UserVars.athletics >= 200

**Comment by rcuhljr** [comment]
You can make the swim as low as 120, we don't really have a good way to deal highly variable athletics checks.

**Comment by Maledar** [comment]
Encountered people with no burden and 180 athletics not being able to...

Also personally encountered my cleric, with no burden and 111 atheltics, and bescort tried to make him swim the river.. so it might be more than just the one line

**Comment by rcuhljr** [comment]
Are you running the skill-recorder script?

**Comment by rcuhljr** [comment]
Also there's stat weighting to make swims, hence the high athletics variability.

**Comment by Maledar** [comment]
Gotcha....a lot more complicated then thought hmm.. ok yes skill-recorder was running

**Comment by MahtraDR** [comment]
@rpherbig is close this unless we get more input for it. The default that exists now hasn't yielded a complaint in at least 4 years.
