### ISSUE TITLE
Opt for casting on the dominant moon when using moonblade

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#1938]
Moonblade casts on a visible moon, but it may not be the dominant moon. Casting on dominant moons results in an upgrade on the weapon. 

Dominant moons could be tracked by moonwatch. It could also be a check by the user before casting, resulting in some roundtime. I'm debating if this should be a setting or it should be the default behaviour.

**Comment by Redheadmoonie** [comment]
would be nice if this was the default, though most of us use moonblade for slivers more than as an actual weapon.

**Comment by jandersson** [comment]
Yea I've only been using moonblade for slivers, so haven't looked into this.
