### ISSUE TITLE
Retreat Threshold not reliable

### ISSUE THREAD

**Issue by jbrock24** [rpherbig/dr-scripts#1940]
Using Retreat Threshold doesn't always work. Sometimes it retreats and then others it never retreats. It definitely sees it correctly as per the combat-trainer start up. r0 should always retreat based on the code.

```
  def update_room_npcs
    @dancing = npcs.length <= @dance_threshold || npcs.empty?
    @retreating = @retreat_threshold && npcs.length >= @retreat_threshold
  end
```
Example of issue.
https://pastebin.com/dZpvwffF

**Comment by jayRyan24** [comment]
It appears to be an issue with SpellProcess not being aware of the `game_state.retreating?` condition. Probably SpellProcess needs to use the above setting to determine to retreat and then SafetyProcess' keep_away.

**Comment by jayRyan24** [comment]
I came to this conclusion while watching it not retreat at the beginning of a hunt (during buffing) and then retreating once that was done. Then, during the hunt later, it stopped retreating while it reapplied buffs. This is why it appeared to work sporadically.

**Comment by MahtraDR** [comment]
Is this still an issue today? The code looks unchanged, but I also can't reproduce the issue.

**Comment by MahtraDR** [comment]
Closing as stale.
