### ISSUE TITLE
go2 necromancer perform entry failure

### ISSUE THREAD

**Issue by VorareDR** [rpherbig/dr-scripts#1941]
Would it be possible to add a check to go2 when it attempts to >perform entry for the line 'You think it unwise while something is engaged in battle with you.'?  if it could then retreat, move a room and retry the entry command instead of failing it would avoid the issue captured below.

[go2]>n
You run north.
[Foot of Wyvern Mountain, Steep Trail]
Wyvern Mountain towers high rises in the sky above, with a thundering waterfall cascading down its front.  Several smaller peaks rise around the mountain cap like dragon's teeth, framing its snowy top.  Massive boulders frame the narrow winding trail, which slopes steeply upward and appears to have been recently cleared of rubble.  You also see a juvenile wyvern, a rocky path and a juvenile wyvern.
Obvious paths: south.
Room Number: 19183
>
You feel fully rested.
>
[go2]>perform entry
The juvenile wyvern begins to advance on you!
The juvenile wyvern is still a distance away from you and is closing steadily.
>
The juvenile wyvern begins to advance on you!
The juvenile wyvern is still a distance away from you and is closing steadily.
>
[go2: travel time: 0:00:09]
--- Lich: go2 has exited.
You think it unwise while something is engaged in battle with you.

**Comment by VorareDR** [comment]
OR, other thought, you can walk into that guildhall from the temple.  so an alternative solution would be for go2 to take you in the manual way instead of using >perform entry, which would avoid potential failure in a juv wyvern infested room entirely.

**Comment by jandersson** [comment]
I'm thinking that if perform entry isn't necessary then the entire 20sec roundtime can be skipped in favor of running through wyverns. Thoughts?

**Comment by VorareDR** [comment]
I think removing the perform entry is the best option.  Skip the RT entirely and no risk of the perform failing when advanced.  

Room Number: 9660 is the entry point in the temple in wyverns.  From there it's >go wall and you're inside.

**Comment by jandersson** [comment]
ill remove the perform entry if the way to Kaluto is fully mapped (I remember mapping the path through the illusory wall a year ago). Any idea if it still is mapped?

**Comment by jandersson** [comment]
I'll do it next time i circle otherwise

**Comment by VorareDR** [comment]
There's an issue with starting go2 in Room Number: 9652.  Otherwise I think it's all mapped.  I've been using go2 from all over the shard and surrounding areas to room 9650 without issue.

[Underground Passage]
Slender wavy lines have been carved into the ceiling in a meandering pattern, encircling golden disks from which hang a series of red paper lanterns.  The carvings become more complex as they radiate outward, incorporating alchemical symbols and jagged geometric glyphs.  Set into one of the walls, a curving osage door looms, its frame nearly as tall as the passage itself.  
Obvious exits: east, west.
Room Number: 9652
>;go2 wyv
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (9652) and destination room (19181)]

**Comment by jandersson** [comment]
Done - You can close this. The perform entry mapping is still there, but it turns out that the mapping to the guild wasn't complete. After completing it, `;go2` choose the path through wyverns even with the `perform entry` path still in place, because its a lot faster.

**Comment by VorareDR** [comment]
Nice and thank you for taking care of the missing mapping.

**Comment by jandersson** [comment]
No problem. Youll want to do `;repository download mapdb` and `;e Map.reload` if you haven't restarted in a while
