### ISSUE TITLE
Execute Scripts in different Hometowns

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#1942]
Would it be possible to add the ability to execute a script outside your normal hometown, and have it work in the town you're in (or want), rather than run you all the way back to your hometown.  

For example.  Current hometown is Shard.  I travel often to Crossings.  It would be great if i could do ":sell-loot crossings" or ";crossing-repair crossings" and have the script work in that town. 

Or I'm battle an invasion in Theren and need to run to get healed.  I could do ";safe-room theren" and run quickly to the autopath.  

Thoughts?

**Comment by MahtraDR** [comment]
https://github.com/rpherbig/dr-scripts/pull/5254 Should close this. @rpherbig I don't know how to link issues, apologies.

**Comment by rpherbig** [comment]
Fixed in #5254
