### ISSUE TITLE
retreat in go2 doesn't check for type-ahead lines

### ISSUE THREAD

**Issue by PatricCampbell** [rpherbig/dr-scripts#1944]
When using go2, it will attempt to retreat in certain rooms but it puts both retreat commands and the direction to move all at once which breaks the script if you don't have extra type-ahead lines. An example is here:

```
[go2]>retre
 retre
 go path

Sorry, you may only type ahead 1 command.
> 
You are already as far away as you can get!
> 
You are already as far away as you can get!
> 
[go2]>retre
 retre
 go path

You feel fully attuned to the mana streams again.
> 
Sorry, you may only type ahead 1 command.
> 
You are already as far away as you can get!
> 
You are already as far away as you can get!
> 
[go2]>south

You can't go there.
> 
[go2: move: failed]

[go2: restarting script...]

[go2: ETA: 0:00:46 (53 rooms to move through)]
```

**Comment by jandersson** [comment]
This is near Shard right? I recall seeing this in the map data. This is specific to the way the room is mapping to move down the path. You could likely remap that particular `wayto` to just `move go path` instead of using the stringproc it has.

**Comment by Sarvatt** [comment]
what room is it?

**Comment by Sarvatt** [comment]
fixed this up by making stringprocs that use waitrt? in them in wyverns

**Comment by rpherbig** [comment]
@PatricCampbell can you test this and let us know if it works now?

**Comment by MahtraDR** [comment]
Closing as we don't control the mapdb, and it's over 4 years old with no response.
