### ISSUE TITLE
Not sure if issue? Using cambrinth in offensive_spells double charging on creature death

### ISSUE THREAD

**Issue by Maledar** [rpherbig/dr-scripts#1953]
Maybe I shouldn't be using cambrinth in my offensive spells? But I've noticed as a Moon mage, if I'm targeting something, (dire bear) charge, and then swing my blade and kill it, I will release the spell BUT I will charge the exact same amount, so basically trying to cast a spell at double the intended amount

**Comment by Sarvatt** [comment]
there's no real way around it besides not using cambrinth for offensive spells, release cambrinth only breaks the link, it wont discharge the mana in it afaik.

**Comment by rcuhljr** [comment]
Generally speaking there's no reason to ever use cambrinth on offensive spells, so finding a work around wasn't high priority.

**Comment by jayRyan24** [comment]
@Maledar The logic behind this is that Debils and TM spells all train fine at min prep or near min prep, this is especially true for spells like Fireball and FOU which have large AOE's build in. The other caveat to this would be the using of Debils and TM spells for Sorcery training, which would need more and more mana to make the successful cast actually train.

**Comment by MahtraDR** [comment]
@rpherbig Can close this. ```# invoke a specific cambrinth amount -- useful for traders with Avtalia Array
cambrinth_invoke_exact_amount: false
``` resolves this problem. it may charge twice, but it'll invoke only the correct amount.
