### ISSUE TITLE
textsubs IF number

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#1954]
Genie has a trigger that shows inner fire for barbs as a number - this is the trigger below
Could we have textsubs added for that for barbs?

#trigger {^(*-/**-+)$} {#var fire_level 80;#var fire_subtract {#eval {count("$1", "-")}};#math fire_level subtract $fire_subtract;#echo IF Level: ($fire_level/80)}

#trigger {^(-|-+)$} {#var fire_level 80;#var fire_subtract {#eval {count("$1", "-")}};#math fire_level subtract $fire_subtract;#echo IF Level: ($fire_level/80)}

#trigger {^(**-/**-+)$} {#var fire_level 80;#var fire_subtract {#eval {count("$1", "-")}};#math fire_level subtract $fire_subtract;#echo IF Level: ($fire_level/80)}

**Comment by rpherbig** [comment]
It looks like we already have IF levels in: https://github.com/rpherbig/dr-scripts/blob/master/textsubs.lic#L890-L903

Is it not working?

**Comment by jayRyan24** [comment]
It works with `meditate flame`.  I am wondering if maybe he is talking about `meditate power`, which shows the stars?

**Comment by MahtraDR** [comment]
No info in over 4 years. Closing.
