### ISSUE TITLE
Rank Cap for Undergondola Pit

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#1969]
Just FYI

You begin to practice your climbing skills.
This climb is no challenge at all, so you stop practicing.

climbing_target: undergondola_pit
Athletics:    483 00.48% clear          (0/34)
Agility 100

**Comment by Sarvatt** [comment]
Are you forcing it to use that climbing_target? Don't do that? :)

**Comment by wscherer420** [comment]
Yeah i changed it already to the branch so that it keeps training.  I just remember seeing somewhere the rank range for the pit, but the top level rank was listed as unknown.  So wanted to communicate where it capped out for me in case it would be helpful to others.
