### ISSUE TITLE
combat-trainer doesn't parse atik'ets correctly.

### ISSUE THREAD

**Issue by hwoo79** [rpherbig/dr-scripts#200]
a red-gold scaled atik'et

single quote screws it up.

[combat-setup]>perform dissect on et

**Comment by rpherbig** [comment]
Try `atik\'et` in your settings

**Comment by hwoo79** [comment]
Sorry for sounding dumb, but where in my settings would I put it?

**Comment by rpherbig** [comment]
Oh, I think I misunderstood. `atik'et` is the name of a mob?

**Comment by hwoo79** [comment]
Yes, it's the name of the mob.

**Comment by rpherbig** [comment]
This feels like a bug in `drinfomon`, since we are just pulling the mob noun from `DRRoom.dead_npcs`. There's a bunch of regexes in that part of `drinfomon` that @rcuhljr might be more familiar with.

**Comment by hwoo79** [comment]
Yeah, just glancing at `drinfomon` it looks like it might have to do with the `find_dead_npcs` method and how it strips out the name.

**Comment by rcuhljr** [comment]
Should be fixed in 5f3ca3e3ad1892996215d141fa205c25aaeee934
