### ISSUE TITLE
Repair items with forging/outfitting when possible

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#205]
What are the requisite items for each method? Skill/rank requirement?

**Comment by rpherbig** [comment]
Some techniques are needed to improve your repair capability (see https://elanthipedia.play.net/mediawiki/index.php/Weaponsmithing_techniques, https://elanthipedia.play.net/mediawiki/index.php/Armorsmithing_techniques, https://elanthipedia.play.net/mediawiki/index.php/Blacksmithing_techniques).

It should be around 100 forging you can start repairing. The techniques decrease time taken, increase amount repaired, and allow you to repair below a certain condition threshold.

Repairing metal items requires a brush and oil, both consumables. It should only take a minute or so per item, which may be better than the NPC (who can parallelize repairs).

**Comment by rcuhljr** [comment]
Deferring
