### ISSUE TITLE
Hunting Priority - ;training-manager true/false

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#2055]
It would be really cool if the Hunting-Priority could be set when activating ;training-manager.

;training-manager (refers to the YAML file)
;training-manager true (overrides whatever YAML says and runs as if hunting priority is true)
;training-manager false (overrides YAML and runs as if hunting priority is false)

**Comment by jayRyan24** [comment]
Hard to see a use for this when you can just change it in the yaml. Also, what if a person doesn't have `training_manager_priority_skills` listed, how would that be handled?

**Comment by wscherer420** [comment]
well changing a YAML is how its done, but isn't it a little cumbersome to open your YAML, change the text, save, and maybe restart depend and then launch?  Would be cool if it could be done in the moment.  And regarding not having skills listed, i suppose it would be handled the same.  How does it handle it now if no skills are listed?

**Comment by rcuhljr** [comment]
You don't need to restart dependency for yaml changes to be picked up. How frequently is this setting being changed? I can't recall switching it more then once or twice over two years on ~6 characters.

**Comment by jayRyan24** [comment]
This seems really unneeded.

**Comment by wscherer420** [comment]
No biggie.   I personally switch my priority frequently depending on what i feel like doing.  But yeah if its too niche then lets close.
