### ISSUE TITLE
,sew missing messaging

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#2059]
I looked at the script, the messaging actually appears to be there, not sure why my script has been hanging.

sew]>get my tailoring book

You get a book of apprentice tailoring instructions from inside your tailor's kit.
> 
[sew]>turn my book to chapter 5

The book is already turned to chapter 5, entitled "Knitted Clothing".
> 
[sew: *** No match was found after 15 seconds, dumping info]

**Comment by mwest152** [comment]
[sew: checked against [/Page \d+.*some knitted hose/i]]

[sew]>read my book

> 
              -=    Chapter 5 : Knitted Clothing    =-

 Page 1: a knitted napkin                        Page 10: a knitted scarf
 Page 2: a knitted armband                       Page 11: some knitted slippers
 Page 3: some knitted socks                      Page 12: a knitted skirt
 Page 4: a knitted ankleband                     Page 13: a knitted shirt
 Page 5: a knitted headband                      Page 14: some knitted gloves
 Page 6: some knitted mittens                    Page 15: some knitted legwarmers
 Page 7: a knitted hood                          Page 16: a knitted towel
 Page 8: some knitted booties                    
 Page 9: a knitted hat                           


> 

> 
[sew: *** No match was found after 15 seconds, dumping info]

[sew]>turn my book to page 

Which page do you wish to turn the a book of apprentice tailoring instructions to?
> 
[sew: *** No match was found after 15 seconds, dumping info]

[sew]>study my book

You quickly flip through the book and determine it is a collection of instructions for the tailoring crafting Discipline in the Outfitting crafting society.

Upon further perusal, it appears you can TURN the BOOK to the FOREWORD, and read a short primer on how crafting of this type is performed.  You may also TURN the BOOK to INDEX, and read it for a list of chapters.  Then, you can TURN the BOOK to CHAPTER # and read it for a list of instructions on each page.  Finally, you can TURN the BOOK to a PAGE # in that chapter, and read it for detailed information on what is required for the crafting process.

Once you have turned to the page you wish to craft, you may STUDY the BOOK to begin the crafting process.

With some complex books, it is possible to TURN the BOOK to [discipline name] to select a different set of templates.

[sew: *** No match was found after 15 seconds, dumping info]

[sew: messages seen length: 34]

**Comment by Sarvatt** [comment]
There are no hose on that page in your book, did you just hit 175 ranks with an apprentice book maybe?

**Comment by mwest152** [comment]
that was it.  Thanks!
