### ISSUE TITLE
combat-trainer box looting issue

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#2062]
Not sure why I'm running into this, could be barb specific, but i keep getting hung with a box and my box bag being full.  Only noticed on my barb, but thats my only guy regularly filling his box bag.
```
[combat-trainer]>stow my throwing.hammer

You put your hammer in your spidersilk backpack.
> 
[combat-trainer]>get my throwing.hammer

You get a steel throwing hammer from inside your spidersilk backpack.
> 
[combat-trainer]>loot goods

You search the Xala'shar magus.
The magus was carrying a crust-covered wooden chest!

> 
[combat-trainer]>stow my throwing.hammer

You put your hammer in your spidersilk backpack.
> 
[combat-trainer]>stow chest

You pick up a crust-covered wooden chest.
There isn't any more room in the haversack for that.

[combat-trainer]>get my throwing.hammer

The corpse of a hulking Xala'shar magus slowly melts away into a greenish-black pool of ooze, laced with fractured bones and several stray teeth.

> 
A hulking Xala'shar magus flexes its heavily-bandaged fingers with a low groan and softly mutters, "The price one pays to attain true power."
> 
You need a free hand to pick that up.
> 
[hunting-buddy: ***STATUS*** 22 minutes of hunting remaining or waiting on Polearms]

[combat-trainer: *** No match was found after 15 seconds, dumping info]

**Comment by mwest152** [comment]
**more complete log by request**

-------------

You put your hammer in your spidersilk backpack.
> 
[combat-trainer]>get my throwing.hammer

You get a steel throwing hammer from inside your spidersilk backpack.
> 
[combat-trainer]>loot goods

You search the Xala'shar magus.
The magus was carrying a crust-covered wooden chest!

> 
[combat-trainer]>stow my throwing.hammer

You put your hammer in your spidersilk backpack.
> 
[combat-trainer]>stow chest

You pick up a crust-covered wooden chest.
There isn't any more room in the haversack for that.

> 
> 
> 
> 
> 
[combat-trainer]>get my throwing.hammer

The corpse of a hulking Xala'shar magus slowly melts away into a greenish-black pool of ooze, laced with fractured bones and several stray teeth.

> 
A hulking Xala'shar magus flexes its heavily-bandaged fingers with a low groan and softly mutters, "The price one pays to attain true power."
> 
You need a free hand to pick that up.
> 
A hulking Xala'shar magus glowers darkly at you.
Flickering shadows tear away from the Xala'shar magus's fingertips, shuddering through the air toward you!
Unable to overcome your fortitude, the shadowy tendrils are sent roiling back toward the Xala'shar magus!  They coalesce rapidly around it in a constricting cage.
> 
> 
> 
[hunting-buddy: ***STATUS*** 22 minutes of hunting remaining or waiting on Polearms]

* As if fumbling muscle flab were natural, a hulking Xala'shar magus sidesteps and bashes at you.  You evade, stepping aside.  
[You're nimbly balanced with opponent in very strong position.]
> 
* Trying inexpertly, a hulking Xala'shar thrall lunges a rusted dagger at you.  You repulse little of the dagger with a steel nightstick.  
[You're nimbly balanced with opponent in better position.]
> 
You feel fully rested.

> 
> 
> 
> 
* Awkwardly, a hulking Xala'shar magus slices a gnarled white oak staff with deeply carved markings at you.  You dodge, leaping aside.  
[You're nimbly balanced with opponent in very strong position.]
> 
A hulking Xala'shar magus spreads its arms and begins chanting in an ancient tongue, it robes thrashing about wildly as if surrounded in an ethereal wind.
* Apparently without direction or thought, a hulking Xala'shar magus slices a gnarled white oak staff with deeply carved markings at you.  You beat off some of the staff with a steel nightstick.  
[You're nimbly balanced with opponent in very strong position.]
> 
* Trying inexpertly, a hulking Xala'shar thrall thrusts a rusted dagger at you.  You counter little of the dagger with a steel nightstick.  
[You're nimbly balanced with opponent in strong position.]
> 
[DRPrime]-DR:Giulietta: "7 for 9!"

> 
> 
> 
> 
The swirling confines of malevolent darkness wane from about a hulking Xala'shar magus.
> 
[combat-trainer: *** No match was found after 15 seconds, dumping info]

[combat-trainer: messages seen length: 30]

[combat-trainer: message: The swirling confines of malevolent darkness wane from about a hulking Xala'shar magus.]

[combat-trainer: message:  Tornado (1 roisaen)]

[combat-trainer: message:  Panther (60 roisaen)]

[combat-trainer: message:  Monkey (79 roisaen)]

[combat-trainer: message:  Piranha (79 roisaen)]

[combat-trainer: message:  Python (77 roisaen)]

[combat-trainer: message: [DRPrime]-DR:Giulietta: "7 for 9!"]

[combat-trainer: message: [You're nimbly balanced with opponent in strong position.]]

[combat-trainer: message: * Trying inexpertly, a hulking Xala'shar thrall thrusts a rusted dagger at you.  You counter little of the dagger with a steel nightstick.  ]

[combat-trainer: message: [You're nimbly balanced with opponent in very strong position.]]

[combat-trainer: message: * Apparently without direction or thought, a hulking Xala'shar magus slices a gnarled white oak staff with deeply carved markings at you.  You beat off some of the staff with a steel nightstick.  ]

[combat-trainer: message: A hulking Xala'shar magus spreads its arms and begins chanting in an ancient tongue, it robes thrashing about wildly as if surrounded in an ethereal wind.]

[combat-trainer: message: [You're nimbly balanced with opponent in very strong position.]]

[combat-trainer: message: * Awkwardly, a hulking Xala'shar magus slices a gnarled white oak staff with deeply carved markings at you.  You dodge, leaping aside.  ]

[combat-trainer: message: You feel fully rested.]

[combat-trainer: message: [You're nimbly balanced with opponent in better position.]]

[combat-trainer: message: * Trying inexpertly, a hulking Xala'shar thrall lunges a rusted dagger at you.  You repulse little of the dagger with a steel nightstick.  ]

[combat-trainer: message: [You're nimbly balanced with opponent in very strong position.]]

[combat-trainer: message: * As if fumbling muscle flab were natural, a hulking Xala'shar magus sidesteps and bashes at you.  You evade, stepping aside.  ]

[combat-trainer: message:  Tornado (1 roisaen)]

[combat-trainer: message:  Panther (60 roisaen)]

[combat-trainer: message:  Monkey (79 roisaen)]

[combat-trainer: message:  Piranha (80 roisaen)]

[combat-trainer: message:  Python (77 roisaen)]

[combat-trainer: message: Unable to overcome your fortitude, the shadowy tendrils are sent roiling back toward the Xala'shar magus!  They coalesce rapidly around it in a constricting cage.]

[combat-trainer: message: Flickering shadows tear away from the Xala'shar magus's fingertips, shuddering through the air toward you!]

[combat-trainer: message: A hulking Xala'shar magus glowers darkly at you.]

[combat-trainer: message: You need a free hand to pick that up.]

[combat-trainer: message: A hulking Xala'shar magus flexes its heavily-bandaged fingers with a low groan and softly mutters, "The price one pays to attain true power."]

[combat-trainer: message: The corpse of a hulking Xala'shar magus slowly melts away into a greenish-black pool of ooze, laced with fractured bones and several stray teeth.]

[combat-trainer: checked against [/^You .*(?i-mx:throwing.*\bhammer)/, /^You get.*hammer/i, /^What were you referring/i, /But that is already/i, /You are already/i]]

[combat-trainer: for command get my throwing.hammer]

**Comment by Sarvatt** [comment]
https://github.com/rpherbig/dr-scripts/blob/master/combat-trainer.lic#L384

**Comment by mwest152** [comment]
Fixed.
