### ISSUE TITLE
sew does not take the material into account for cloth

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#2065]
it hardcodes "get my cloth" and such in places, which can grab chamois cloths instead of crafting material.

**Comment by mwest152** [comment]
--- Lich: sew active.

[sew]>tap my cotton thread

> 
You tap some cotton thread inside your duffel bag.
> 
[sew]>get my tailoring book

You get a book of master tailoring instructions from inside your duffel bag.
> 
[sew]>turn my book to chapter 4

You turn your book to chapter 4, entitled "Cloth Armor".
> 
[sew]>read my book

              -=    Chapter 4 : Cloth Armor    =-

 Page 1: a quilted cloth mask                    Page 24: some insulated cloth pants
 Page 2: a quilted cloth aventail                Page 25: an insulated cloth hood
 Page 3: a padded cloth mask                     Page 26: a quilted cloth tabard
 Page 4: a padded cloth aventail                 Page 27: a padded cloth mantle
 Page 5: a quilted cloth cap                     Page 28: a padded cloth vest
 Page 6: some quilted cloth gloves               Page 29: an insulated cloth tasset
 Page 7: some quilted cloth pants                Page 30: some padded cloth sleeves
 Page 8: an insulated cloth mask                 Page 31: some insulated cloth vambraces
 Page 9: an insulated cloth aventail             Page 32: a padded cloth tabard
 Page 10: a padded cloth cap                     Page 33: a quilted cloth shirt
 Page 11: some padded cloth gloves               Page 34: a quilted cloth robe
 Page 12: a quilted cloth hood                   Page 35: an insulated cloth mantle
 Page 13: a quilted cloth tasset                 Page 36: an insulated cloth vest
 Page 14: some quilted cloth vambraces           Page 37: some insulated cloth sleeves
 Page 15: some padded cloth pants                Page 38: an insulated cloth tabard
 Page 16: an insulated cloth cap                 Page 39: a padded cloth shirt
 Page 17: some insulated cloth gloves            Page 40: a quilted cloth hauberk
 Page 18: a padded cloth hood                    Page 41: a padded cloth robe
 Page 19: a quilted cloth mantle                 Page 42: an insulated cloth shirt
 Page 20: a quilted cloth vest                   Page 43: a padded cloth hauberk
 Page 21: a padded cloth tasset                  Page 44: an insulated cloth robe
 Page 22: some quilted cloth sleeves             Page 45: an insulated cloth hauberk
 Page 23: some padded cloth vambraces            

> 
[sew]>turn my book to page 45

You turn your book to page 45, instructions for crafting an insulated cloth hauberk.
> 
[sew]>study my book

You scan the insulated hauberk instructions with a glance and confidently discern most of the design's minutiae. (3/5)
You now feel ready to begin the crafting process.
Roundtime: 7 sec.
R> 
You feel fully attuned to the mana streams again.
R> 
[sew]>put my book in my duffel bag

You put your book in your duffel bag.
> 
[sew]>get my cloth

You get a chamois cloth from inside your silk backpack.
> 
[sew]>get my scissors

You get some iron scissors from inside your silk backpack.
> 
[sew]>cut my cloth with my scissors

You have no idea how to craft an insulated cloth hauberk from this.

**Comment by jandersson** [comment]
@mwest152 - can you add three backtics (the ` key left of the 1 key) above and below your logs? It formats it to be easier to read :)

**Comment by xtremenerdrage** [comment]
Also having this issue
