### ISSUE TITLE
favor.lic missing messaging

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#2077]
```
> ,training-manager

--- Lich: training-manager active.

[training-manager]>favor

You currently have 11 favors with the gods.
Your most recent favor was granted by Damaris.
> 
[training-manager]>tap Damaris orb

The orb is delicate.  Tapping it is not advised.
> 
[training-manager]>rub my Damaris orb

You sense that this Damaris orb is not deemed worthy to hold your required sacrifice.  Perhaps another would work at this time?

> ,ka

--- Lich: training-manager has exited.

**Comment by rpherbig** [comment]
What causes that message to occur? What should we do if we encounter it?

**Comment by jandersson** [comment]
I think this happens when you get two favor orbs, causing the old one to stop working. Correct me if I'm wrong.

**Comment by mwest152** [comment]
I think if you get 3 orbs it happens or if you get someone else's orb maybe.  I just dropped it.  It was my only orb at the time not sure where I got it.

**Comment by Sarvatt** [comment]
yeah it happens with multiples, dropping it is the only thing you can do

**Comment by MahtraDR** [comment]
@rpherbig I am going through issues for favor.lic and saw this. I think we can close it. It's a known issue, and the effort involved isn't worth it, given how nobody has responded/added to this since 2017.
