### ISSUE TITLE
Reoccurring login errors causing major issues in combat/crossing-training

### ISSUE THREAD

**Issue by Missah** [rpherbig/dr-scripts#2103]
I have 3 accounts...these errors happen several times each week.  Hopefully someone can tell me what I need to do to fix it.  Thank you!

Acct #1 gets this login error:
[repository: scripts are up-to-date]
--- Lich: repository has exited.
--- Lich: could not find script 'scriptname' in directory C:/Users/Rose/Documents/lich/scripts
--- Lich: sanowret-crystal active.

Which is turn causes this error:

>;crossing-training

--- Lich: crossing-training active.

--- Lich: error: wrong number of arguments (1 for 0)
	crossing-training:53:in `initialize'
	crossing-training:53:in `new'

--- Lich: crossing-training has exited.

Login errors for accts #2 and #3:

--- Lich: equipmanager active.

--- Lich: error: uninitialized constant Scripting::EquipmentManager::DRC
	equipmanager:8:in `<class:EquipmentManager>'
	equipmanager:7:in `script'

--- Lich: equipmanager has exited.

Which results in this error:

[hunting-buddy: ***STATUS*** beginning hunt '["d0"]' for '45' minutes]
--- Lich: combat-trainer active.
--- Lich: error: wrong number of arguments (1 for 0)
	combat-trainer:2064:in `initialize'
	combat-trainer:2064:in `new'
--- Lich: combat-trainer has exited.
>

**Comment by rpherbig** [comment]
This feels like a problem with your autostarts. Could you post the output of `;autostart list` and `;e echo list_autostarts`?

**Comment by Missah** [comment]
My pleasure!  Hope it's that simple, info below:

Acct #1:
>;autostart list

--- Global autostart scripts: alias, lnet, repository (args: download-updates), dependency, dr-autovote

--- Annari's autostart scripts: (none)

>;e echo list_autostarts
--- Lich: exec1 active.
[exec1: ["scriptname", "sanowret-crystal", "drinfomon", "events", "equipmanager", "common", "common-money", "common-travel", "common-summoning", "common-crafting", "textsubs", "roomnumbers", "smartlisten", "afk", "spellmonitor", "moonwatch", "listen", "keepalive", "jail-buddy"]]
--- Lich: exec1 has exited.
>

Acct #2:
>;autostart list

--- Global autostart scripts: alias, lnet, repository (args: download-updates), dependency, dr-autovote

--- Missah's autostart scripts: (none)

>;e echo list_autostarts
--- Lich: exec1 active.
[exec1: ["sanowret-crystal", "drinfomon", "events", "equipmanager", "common", "common-money", "common-travel", "common-summoning", "common-crafting", "textsubs", "roomnumbers", "smartlisten", "afk", "spellmonitor", "moonwatch", "listen", "keepalive", "jail-buddy"]]
--- Lich: exec1 has exited.

Acct #3
>;autostart list

--- Global autostart scripts: alias, lnet, repository (args: download-updates), dependency, dr-autovote

--- Gabellia's autostart scripts: (none)

>;e echo list_autostarts
--- Lich: exec1 active.
[exec1: ["sanowret-crystal", "drinfomon", "events", "equipmanager", "common", "common-money", "common-travel", "common-summoning", "common-crafting", "textsubs", "roomnumbers", "smartlisten", "afk", "spellmonitor", "moonwatch", "listen", "keepalive", "jail-buddy"]]
--- Lich: exec1 has exited.

**Comment by rpherbig** [comment]
Yep, 'scriptname' shouldn't be in your autostarts.Try `;e stop_autostart('scriptname')` on Acct #1.

**Comment by Missah** [comment]
>;e stop_autostart('scriptname')
--- Lich: exec1 active.
--- Lich: exec1 has exited.

repeated command several times, including logging in/out with same results.  Suggestions?

>;e echo list_autostarts
--- Lich: exec1 active.
[exec1: ["scriptname", "sanowret-crystal", "drinfomon", "events", "equipmanager", "common", "common-money", "common-travel", "common-summoning", "common-crafting", "textsubs", "roomnumbers", "smartlisten", "afk", "spellmonitor", "moonwatch", "listen", "keepalive", "jail-buddy"]]
--- Lich: exec1 has exited.

**Comment by rpherbig** [comment]
What does this output? `;e echo UserVars.autostart_scripts.include?('scriptname')`

**Comment by rcuhljr** [comment]
Lich isn't always super motivated about saving changes to user vars, you might try running `;e UserVars.save()` after the stop autostart. We should probably add that to `stop_autostart` if it helps and we could use a helper method on the manager to let it know to update autostart scripts list if you change a non global autostart without restarting dependency.

**Comment by Missah** [comment]
Still getting login issues:
--- Lich: equipmanager active.
--- Lich: error: uninitialized constant Scripting::EquipmentManager::DRCI
	equipmanager:9:in `<class:EquipmentManager>'
	equipmanager:7:in `script'
--- Lich: equipmanager has exited.

See this when trying to run ;astrology:
>;astrol
--- Lich: astrology active.
--- Lich: error: private method `empty_hands' called for #<Scripting::EquipmentManager:0xc1252c8>
	astrology:50:in `do_buffs'
	astrology:38:in `initialize'
--- Lich: astrology has exited.

Hope that helps to track down this bug.

**Comment by jandersson** [comment]
What are your trusted scripts? Can you paste the output from `;lt`

**Comment by Missah** [comment]
Holy crap...why is dependency listed 4 times?  Is that normal?

>;lt
--- Lich: trusted scripts: repository, lnet, narost, dependency, lnet2, status-monitor, slackbot, dependency, dependency, dependency, dependency, status-monitor, slackbot, dependency, status-monitor, listen, keepalive, keepalive, slackbot, dr-autovote, dr-autovote,

**Comment by jandersson** [comment]
That seems strange. `;distrust dependency` until it doesn't show up, then `;trust dependency`.

**Comment by jandersson** [comment]
You can probably distrust lnet2 as well (and remove from any autostarts)

**Comment by jandersson** [comment]
This is what I have for reference:
```
R>;lt
--- Lich: trusted scripts: repository, lnet, narost, dependency, slackbot, status-monitor, dr-autovote
```

**Comment by Missah** [comment]
>;lt
--- Lich: trusted scripts: repository, lnet, narost, dependency, dr-autovote, slackbot, status-monitor

So my question becomes....how did all those duplicates appear? Last script I would of trusted was dr-autovote...and that was a while ago.

**Comment by jandersson** [comment]
Do you have lich in a shared dropbox folder with multiple machines using it?

**Comment by Missah** [comment]
No, do not have lich in a shared dropbox folder and only use lich on one puter.  The issue hasn't been constant.  Usually only happens a few times a week, and relogging a few times would usually make it go away.

**Comment by rcuhljr** [comment]
The multi trust thing is normal for lich, it doesn't really pay attention to how many times something is trusted as long as it's at least once.

**Comment by Missah** [comment]
Sorry missed your autostart request:

>;e echo list_autostarts
--- Lich: exec1 active.
[exec1: ["sanowret-crystal", "drinfomon", "events", "equipmanager", "common", "common-money", "common-travel", "common-summoning", "common-crafting", "textsubs", "roomnumbers", "smartlisten", "afk", "spellmonitor", "moonwatch", "listen", "keepalive", "jail-buddy"]]
--- Lich: exec1 has exited.

>;autostart list

--- Global autostart scripts: alias, lnet, repository (args: download-updates), dependency, dr-autovote

--- Missah's autostart scripts: (none)

**Comment by Sarvatt** [comment]
;e stop_autostart(['events', 'equipmanager', 'common', 'common-money', 'common-travel', 'common-summoning', 'common-crafting', 'spellmonitor', 'listen', 'keepalive'])

**Comment by Missah** [comment]
okay....and then what?

**Comment by Missah** [comment]
I've done as you have suggested.  As the problem is an intermittent one, I won't know if it's gone away or not until I have logged in several times.  Thank you so much for your help!

**Comment by Missah** [comment]
Still getting error  :(

--- Lich: sanowret-crystal active.
[drinfomon]>exp all
--- Lich: equipmanager active.

>
--- Lich: error: uninitialized constant Scripting::EquipmentManager::DRC
	equipmanager:8:in `<class:EquipmentManager>'
	equipmanager:7:in `script'
--- Lich: equipmanager has exited.
[drinfomon]>info

**Comment by MahtraDR** [comment]
@rpherbig We can close this.
