### ISSUE TITLE
Worn TM Foci Issues with Crossing-Repair & Combat

### ISSUE THREAD

**Issue by Missah** [rpherbig/dr-scripts#2118]
My brand new shiny altered TM foci is worn.  I have it listed under gear:  and flagged as worn.  It works great with TM foci.  However.....

After the hunt when crossing-repair kicks in it is STOWED because it's not a repairable item.  Hence, when the next hunt starts TM foci doesn't work....because it is now trying to REMOVE a stowed item.

I tried adding it under my standard gear set, but then the issue was at the beginning of each hunt it tried to GET the foci, which it couldn't because item is WORN.

Please add some sort of flag to prevent it from trying to get repaired.

Thank you!

**Comment by rpherbig** [comment]
Huh, it looks like it should try and wear it...

Could you hold the item and tell me what `;e echo DRC.right_hand` outputs?

With it still in your right hand, could you then `;e EquipmentManager.new.return_held_gear` and tell me what happens?

**Comment by Missah** [comment]
>glance right
You glance down to see a pale tyrium toe-ring displaying a delicate amaranth Eu's promise crystal in your right hand.

>;e echo DRC.right_hand
--- Lich: exec1 active.
--- Exception: uninitialized constant DRC
exec1:1:in `_script'
--- Lich: exec1 has exited.

>glance right
You glance down to see a pale tyrium toe-ring displaying a delicate amaranth Eu's promise crystal in your right hand.

>;e EquipmentManager.new.return_held_gear
--- Lich: exec1 active.
--- Exception: uninitialized constant EquipmentManager
exec1:1:in `_script'
--- Lich: exec1 has exited.

**Comment by jandersson** [comment]
use `;en echo DRC.right_hand` and `;en EquipmentManager.new.return_held_gear` (note the 'n' in `;en`)

**Comment by Missah** [comment]
>;en echo DRC.right_hand
--- Lich: exec1 active.
[exec1: tyrium toe-ring]
--- Lich: exec1 has exited.


>;en EquipmentManager.new.return_held_gear
--- Lich: exec1 active.
[exec1]>stow my toe-ring
You put your toe-ring in your hitman's backpack.
>
--- Lich: exec1 has exited.

**Comment by rpherbig** [comment]
Thanks @jandersson 😄 

@Missah could you post the gear part of your YAML that includes the focus?

**Comment by Missah** [comment]
- :name: toe-ring
  :is_worn: true

**Comment by rpherbig** [comment]
#2630
