### ISSUE TITLE
clean-lumber failing

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#2119]
>;clean-lumber help
--- Lich: clean-lumber active.
--- Lich: error: clean-lumber:37: formal argument cannot be an instance variable
  def process_size(args, size, @bag)
                                   ^
    C:/Users/Jerry/Documents/Lich/lich/lich.rbw:2546:in `eval'
    C:/Users/Jerry/Documents/Lich/lich/lich.rbw:2546:in `block (3 levels) in <class:Script>'
--- Lich: clean-lumber has exited.

**Comment by Dartellum** [comment]
So we need to use tool_storage instead of @bag but need @bag for the tool belt stuff.
