### ISSUE TITLE
Afk script did not catch afk check

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#212]
This was spammed a few hundred (ok, maybe a few dozen?) times:
```
from inside your backpack. then ceases movement. solidly against the left foot! ... are you aware of this message if so then say something right now.  lands nearby! begins to advance on you! crumbles to dust.
```

**Comment by rpherbig** [comment]
@rcuhljr Does status monitor catch this now?

**Comment by rcuhljr** [comment]
It certainly should, basically we're just waiting until we get checked again? I'm voting we close this for now, I've made some major status monitor overhauls.

**Comment by rpherbig** [comment]
Sounds good
