### ISSUE TITLE
;go2 goes down the Jantspyre when unable

### ISSUE THREAD

**Issue by jonathan-stricker** [rpherbig/dr-scripts#2144]
One of my toons tried to travel from Haven to Rossman and despite 107 in athletics, go2 tried to take him down the Jantspyre; even after I stripped off all his armor he still wasn't remotely able to swim it. Shouldn't it be skill checking and take the barge instead? If so what's the cap, and can it be lowered? Thanks.

**Comment by MahtraDR** [comment]
Closing as we don't control the mapdb where this info is stored...
