### ISSUE TITLE
People using lnet to spoof peoples name, password saving not changing it.

### ISSUE THREAD

**Issue by Maledar** [rpherbig/dr-scripts#2164]
Aside from saving password what other resolution is there to people stop acting like assholes and making jokes about rape and stupid shit?

**Comment by Maledar** [comment]
To be clear, I did ;lnet password=whastever and someone still took over my lnet chat kicked me off and someone was talking like they were me

**Comment by rpherbig** [comment]
Unfortunately, all things LNet are out of our control. We've got emails out to Tillmen requesting some assistance (and mod privileges).

**Comment by Sarvatt** [comment]
this can be closed
