### ISSUE TITLE
handling of weapons not stored in default containers.

### ISSUE THREAD

**Issue by hwoo79** [rpherbig/dr-scripts#217]
combat-trainer uses `'get` and `stow` for weapon handling.  It's my opinion that it should use `wield` and `sheath` to handle weapons.  I have a default sheath for melee weapons set using the `store` command but my container is full so I keep one melee weapon in my pack.  So when the script uses `get` it works fine, but `stow` will return an error of `that is too heavy to go in there` or whatever the messaging is.

Using `wield` and `sheath` will return the weapon to the container that it came from.  I might be an edge case, but I don't think so.  Also, this method would be preferable to assigning a `storage_location:` for every gear item.

**Comment by rpherbig** [comment]
@hwoo79 Is this a problem you are currently experiencing?

**Comment by hwoo79** [comment]
Yes and no.  I was having the problem because my melee storage container defined by STOW was too full weight wise.  the verbs `WIELD` and `SHEATH` will pull the weapon from whatever container it's in then put it back.  

I fixed my problem by getting a lighter HT/Pike.  So this issue will come back for me when I get enough strength to go up weight in weapons.

**Comment by rcuhljr** [comment]
wield/sheath support added through gear flag `:wield: true`

**Comment by rpherbig** [comment]
5621818f8c462585c35183dd533bbe92d71162d3
