### ISSUE TITLE
Fix up timeto's on scouting rooms

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#2176]
note: this is not dr-scripts related but I'm making an issue about it so I remember to come back and fix it.

timeto's on ranger trails are vastly undertimed, making people take longer paths.

this one from the riverhaven ferry to swamp trolls in lang takes a little over 5 minutes at 500 skill but has 160 seconds as it's timeto. A longer timeto would make it take the quicker route over the rope bridge. I'm suspecting because someone with a massive amount of ranks added the initial ones :)
@timeto={"3574"=>0.2, "3575"=>0.2, "3572"=>0.2, "1377"=>StringProc.new("if UserVars.scouting && UserVars.scouting > 200 then 160.0 else nil end")}

I'd like to time the ones listed on the mapdb with a more moderate 500 ranks and update them all, maybe halfway between the 500 rank times and the current ones. Hopefully in one go since they are stringprocs.

**Comment by MahtraDR** [comment]
Closing, as we don't control the mapdb at all, plus it's over four years old.
