### ISSUE TITLE
Sew not returning to outfitting_room:

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#2193]
When you run out of thread it runs your to the society to refill, but then continues working in the society rather than running back to your outfitting room.

**Comment by rpherbig** [comment]
Maybe https://github.com/rpherbig/dr-scripts/blob/master/sew.lic#L82 is the culprit?

**Comment by MahtraDR** [comment]
Closing as very stale. Happy to revisit if it still exists today.
