### ISSUE TITLE
forging - Crafting page numbers differ between Prime and TF

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#220]
May apply to other crafts as well.

====== Apprentice blacksmithing book TF=======
read book
              -=    Chapter 6 : Forged Item Design    =-

 Page 1: a slender metal rod                     Page 9: a back scratcher
 Page 2: a shallow metal cup                     Page 10: a metal bolt box
 Page 3: a metal horseshoe                       Page 11: a metal origami case
 Page 4: a soft metal keyblank                   Page 12: a metal lockpick case
 Page 5: a short metal mug                       Page 13: a metal ankle band
 Page 6: a tall metal mug                        Page 14: a small metal flask
 Page 7: a large metal horseshoe                 
 Page 8: some metal barbells               

====== Apprentice blacksmithing book Prime=======
>read book
              -=    Chapter 6 : Forged Item Design    =-

 Page 1: a shallow metal cup                     Page 9: a large metal horseshoe
 Page 2: a slender metal rod                     Page 10: a small metal flask
 Page 3: a tall metal mug                        Page 11: a metal ankle band
 Page 4: a short metal mug                       Page 12: a metal lockpick case
 Page 5: a soft metal keyblank                   Page 13: a metal origami case
 Page 6: a metal horseshoe                       Page 14: a metal bolt box
 Page 7: a back scratcher                        
 Page 8: some metal barbells

**Comment by rpherbig** [comment]
We should do this just so things don't break on Prime when the server reboots (e.g. today).

**Comment by rcuhljr** [comment]
0bce5a7
