### ISSUE TITLE
;theurgy - holy oil puchasing - shard

### ISSUE THREAD

**Issue by NSGregory** [rpherbig/dr-scripts#2203]
When the character is out of holy oil, they go to buy more.  The vendor requires two "buy oil" commands, but the script seems to expect to receive oil from the vendor after a single "buy oil."

This has been observed only in shard... the only place i've tried it.

**Comment by Cloverleaf** [comment]
Actually ordering a second time doesn't get the item either.  I think it needs an offer 90.

**Comment by MahtraDR** [comment]
@rpherbig Can close. This isn't an issue with the script.
