### ISSUE TITLE
Crossing-repair should use CONTACT FIX for Thieves

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#221]
I don't recall what circle I got the ability at, was between 30-35 if I recall.  Notes and usage are in the pastebin.  If there's more you need from me, let me know.

http://pastebin.com/7LPp40jU

**Comment by rpherbig** [comment]
According to one user: "So I was writing support for thief Contact Fix into crossing-repair when I realized that due to RTs and coin: Contact Fix is both slower and more expensive. At least for the Crossing area. project abandoned"
