### ISSUE TITLE
Requesting Advanced Option for Performance

### ISSUE THREAD

**Issue by RohkDR** [rpherbig/dr-scripts#2215]
Kind of straightforward... Having high perfomance and lich doesnt work as far as ive found. Id appreciate the time and effort to add an option to get a higher end instrument ( IE: brass shawn ) hold it, and play it until performance is sufficient, then stow and continue to next bit in crossing training. Again, I have no clue the process, nor difficulty of this happening but willing to help in anyway if someone is able. 
Thank you in advance.

**Comment by rpherbig** [comment]
https://github.com/rpherbig/dr-scripts/blob/master/crossing-training.lic#L1050 is where `crossing-training` will play zills to train Performance. You might be able to use that as a guide if you're interested in making it (or some new code) play other instruments.

**Comment by BhaalgornDR** [comment]
Ill give it a shot, though I know nothing of ruby. Im use to chopping things together for genie.. maybe itll pay off.

**Comment by MahtraDR** [comment]
@rpherbig We can close this. I just noticed performance has this functionality already today.
