### ISSUE TITLE
Circle Check is now just reporting TDP's

### ISSUE THREAD

**Issue by invisioblack** [rpherbig/dr-scripts#2229]
;circlecheck
--- Lich: circlecheck active.
Your next level will award: 166 TDPs
J>
--- Lich: circlecheck has exited.

;circlecheck next
--- Lich: circlecheck active.
Your next level will award: 166 TDPs
--- Lich: circlecheck has exited.

I logged out and back in and it stopped working.  I don't know what the issue is.

**Comment by rpherbig** [comment]
If you type `;la`, is `drinfomon` running?

**Comment by Sarvatt** [comment]
drinfomon didn't record your skills for some reason, did you log in dead?

**Comment by invisioblack** [comment]
--- Lich: dependency, drinfomon, skill-recorder, spellmonitor, roomnumbers, lnet

But learned is still working.
--- Lich: learned active.
J>
 Mechanical Lore    0.67  (0.36/hr, 8.68/day)   Scholarship      0.34  (0.18/hr, 4.40/day)
      Arcana        0.3   (0.16/hr, 3.89/day) Outdoorsmanship    0.18  (0.10/hr, 2.33/day)
    Summoning       0.16  (0.09/hr, 2.07/day)    Perception      0.14  (0.08/hr, 1.81/day)
    Athletics       0.12  (0.06/hr, 1.55/day)   Shield Usage     0.1   (0.05/hr, 1.30/day)
     Brawling       0.09  (0.05/hr, 1.17/day)   Light Armor      0.09  (0.05/hr, 1.17/day)
  Targeted Magic    0.07  (0.04/hr, 0.91/day)     Evasion        0.05  (0.03/hr, 0.65/day)
     Utility        0.05  (0.03/hr, 0.65/day) Elemental Magic    0.04  (0.02/hr, 0.52/day)
    Defending       0.04  (0.02/hr, 0.52/day)    Attunement      0.01  (0.01/hr, 0.13/day)
   TOTAL RANKS: 2.45  HOURLY: 1.32  DAILY: 31.78
   TOTAL TDPS: 2.41  DAILY: 31.21
   Learning For: 1.9 hours
--- Lich: learned has exited.

I did not log in dead.

**Comment by invisioblack** [comment]
Is a timing issue with my login - can fix by altering timing.

**Comment by jandersson** [comment]
The issue with logging in dead is fixed
