### ISSUE TITLE
go2 getting stuck in mistwood forest

### ISSUE THREAD

**Issue by fireballx777** [rpherbig/dr-scripts#2233]
go2 is getting stuck when attempting to move through mistwood forest to get to reivers.  Even with typeahead set to 0 or 1, it will attempt four move commands in a row after entering the thicket (from 7666 to 19100).  This will often get stuck due to using too many typeaheads, and be unable to restart as it doesn't recognize a path in the in-between rooms.

**Comment by Sarvatt** [comment]
genie or frostbite I'm guessing? They don't like a string of stringprocs.

[exec1: @id=7666
@image="Therengia, 34, Mistwood Forest.gif"
@climate=nil
@title=["[[Mistwood Forest, Narrow Trail]]"]
@check_location=nil
@timeto={"7661"=>0.2, "8694"=>0.2, "8644"=>1.0, "19100"=>0.2}
@location=nil
@tags=["grass", "georin grass", "hulnik grass", "rock"]
@wayto={"7661"=>"southwest", "8694"=>StringProc.new("fput 'go thicket\n e\n ne\n nw\n n'; fput 'go gate'"), "8644"=>StringProc.new("fput 'go thicket'; fput 'east'; fput 'southwest'; fput 'south'; fput 'northeast'; fput 'go gap'"), "19100"=>"go thicket"}
@paths=["Obvious paths: southwest."]
@image_coords=[292, 439, 308, 457]
@terrain=nil
@description=["The road wends its way back and forth through the trees.  Little more than a dirt track bordered by curseweed and other thorny shrubs, its rutted surface is shadowed by overhanging branches.  The silence is broken from time to time by low growls or the chirping of unseen birds."]]

**Comment by jandersson** [comment]
Those should be move commands, not fputs

**Comment by fireballx777** [comment]
Yes, frostbite.

**Comment by Sarvatt** [comment]
probably should leave this open until it's fixed

**Comment by fireballx777** [comment]
I fixed the mapping to the reiver area (8694) from a series of naked directions to move commands.  It wasn't the fputs that was causing the issue.

**Comment by jandersson** [comment]
`fput 'go thicket\n e\n ne\n nw\n n';` That looks an fput sending 5 movement commands at once
