### ISSUE TITLE
Issue status-monitor on login

### ISSUE THREAD

**Issue by DryIce41** [rpherbig/dr-scripts#2238]
Can you all please help me with this? I'm especially interested in why status-monitor is crashing. 
TIA
Using Genie.
Upon login I get this: 

--- Lich: go2 has exited.

--- Lich: error: undefined local variable or method `custom_require' for #<Scripting:0x352c2d8>
	common:56:in `script'
	/users/jkgeda/documents/lich/lich.rbw:2546:in `eval'

--- Lich: autolisten active.

--- Lich: circlemonitor active.

--- Lich: error: undefined local variable or method `custom_require' for main:Object
	circlemonitor:7:in `_script'
	/users/jkgeda/documents/lich/lich.rbw:2502:in `eval'

--- Lich: circlemonitor has exited.

--- Lich: roomnumbers active.

--- Lich: moonwatch active.

--- Lich: error: undefined local variable or method `custom_require' for main:Object
	moonwatch:5:in `_script'
	/users/jkgeda/documents/lich/lich.rbw:2502:in `eval'

--- Lich: moonwatch has exited.

--- Lich: status-monitor active.

--- Lich: error: undefined method `parse_args' for main:Object
	status-monitor:14:in `_script'
	/users/jkgeda/documents/lich/lich.rbw:2502:in `eval'

--- Lich: status-monitor has exited.

**Comment by rpherbig** [comment]
That generally happens when `dependency` is not running. Can you `;la` and check?

**Comment by DryIce41** [comment]
Dependecy is running. 
--- Lich: dependency, drinfomon, spellmonitor, autolisten, textsubs, roomnumbers, moonwatch, status-monitor, training-manager, events, hunting-buddy, combat-trainer, lnet

**Comment by rcuhljr** [comment]
What's in your `;autostart list`?

**Comment by DryIce41** [comment]
--- Global autostart scripts: alias, lnet, repository (args: download-updates), dependency, go2, drinfomon, common, spellmonitor, autolisten, circlemonitor, textsubs, roomnumbers

--- Yiel's autostart scripts: moonwatch, status-monitor, common

**Comment by rcuhljr** [comment]
Yeah there's your problem, don't autostart any of our scripts other than dependency through `;autostart`, use `;e autostart()` instead.

**Comment by DryIce41** [comment]
Can you help me understand the difference please? And the syntax for ;e autostart?

**Comment by Sarvatt** [comment]
the bottom of https://github.com/rpherbig/dr-scripts/wiki/First-Time-Setup explains it, remove circlemonitor textsubs roomnumbers spellmonitor drinfomon autolisten common and go2 via ;autostart remove, then run ;e autostart(['textsubs', 'roomnumbers', 'autolisten']).

**Comment by Sarvatt** [comment]
you're in genie so replace ; with , of course

**Comment by DryIce41** [comment]
Perfect fix. Thankyou all!
