### ISSUE TITLE
add appraisal to combat

### ISSUE THREAD

**Issue by hwoo79** [rpherbig/dr-scripts#224]
Can keep appraisal moving in combat by throwing in a APPRAISE mob_noun QUICK.  This results in a 3 second RT.

For reference, I believe, the cooldown timer is 60 seconds.

**Comment by rpherbig** [comment]
Appraising in combat is already supported. I can't check the setting name right now, but search Torgro-setup.yaml for either `app` or `appraise`.

**Comment by hwoo79** [comment]
Of course it does!  I'm behind the times.
