### ISSUE TITLE
Commonize crossing-trainer::cast_spell

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#2243]
It looks like all the logic in crossing-trainer can be moved to DRCA.cast_spell.

**Comment by jandersson** [comment]
The two things left that I can see are: commonize the auto mana logic and handle composting.

One thing ive been wondering about casting compost is how to handle the `walk_to @settings.compost_room` line. I would think that should not be commonized and maybe crossing-trainer should handle that before the spell is cast? But im curious to hear any other thoughts.

**Comment by MahtraDR** [comment]
This is fully in commons today...
