### ISSUE TITLE
go2 can't get to blood vines

### ISSUE THREAD

**Issue by NSGregory** [rpherbig/dr-scripts#2248]
produced by: ;go2 4213
error: can't find a path to there (sic)

Issue appears related to the fact that none of the rooms in the Pilgrim's Trail Section near hib (and hib cleric guild) have room numbers?  

Which is odd because you can go2 past that region easily.  Indeed, that's the current work around to get to blood vines, go2 past then have a before and after script to get you into known territory.

**Comment by Tarhish** [comment]
I realize this is an old issue, but I saw the problem and remapped bloodvines.  I also changed their hunting area in base-hunting.  Hunted in that zone off and on for a couple months, so I believe this issue can be closed.
