### ISSUE TITLE
Breaking moonblades

### ISSUE THREAD

**Issue by DryIce41** [rpherbig/dr-scripts#2249]
Hello all. You were very helpful last time.

I'm having an issue now where I have summoned weapons set up. The moonblades work really well until combat-trainer breaks them into slivers. 
I can't figure out why it's doing this as I do not have tks or tkt set up in my yaml. If I set up TKT or TKS, combat trainer breaks the moonbldae much more regularly.  And will immediately if I release slivers.

I'm not good enough with the code in combat-trainer to see the issue. But can we set a variable up to not break the moonblade if we don't want it to? Or does that already exist. 

Also, if I force moonblade to recast by putting a "expire" match in, it doesn't reshape it to the correct size. 

My Yaml is messy excuse me.  Been a work in progress. 
https://pastebin.com/paqnCTn6

**Comment by DryIce41** [comment]
It seems to be working with this current yaml. I'll continue to run it an see what happens.

**Comment by DryIce41** [comment]
This issue seems to continue.  Does IoE have any reason to call for breaking the moonblade?

**Comment by jandersson** [comment]
What is IoE?

**Comment by rpherbig** [comment]
Could you `;e echo DRStats.moon_mage?` and tell us what it says?

**Comment by DryIce41** [comment]
Invocation of energy.  I'll post that tomorrow.  Home for the holidays.  Thank you for your attention!  Merry Christmas

**Comment by jandersson** [comment]
Merry christmas :) Do you mean invocation of the spheres? If so, that spell doesn't require moons to cast.

**Comment by jandersson** [comment]
This page offers details on how to cast IOTS: https://github.com/rpherbig/dr-scripts/wiki/Moon-Mage-Tutorials

**Comment by DryIce41** [comment]
,e echo DRstats.moon_mage yielded this:

--- Lich: exec1 active.

--- Exception: uninitialized constant DRstats

exec1:1:in `_script'

--- Lich: exec1 has exited.

**Comment by DryIce41** [comment]
And you're right about IOTS.  But from further testing, it doesn't seem to make a difference on whether combat-trainer breaks the moonblade or not

**Comment by Sarvatt** [comment]
that should be ,en echo DRStats.moon_mage?

**Comment by DryIce41** [comment]
Same result  :(

**Comment by rpherbig** [comment]
That implies `drinfomon` isn't running

**Comment by DryIce41** [comment]
I tried it again after a fresh restart

,en echo DRstats.moon_mage
--- Lich: exec1 active.
--- Exception: uninitialized constant Scripting::DRstats
exec1:1:in `script'
--- Lich: exec1 has exited.

> ,list

--- Lich: dependency, drinfomon, spellmonitor, moonwatch, status-monitor, afk, textsubs

> ,e echo DRstats.moon_mage
--- Lich: exec1 active.
--- Exception: uninitialized constant DRstats
exec1:1:in `_script'
--- Lich: exec1 has exited.

**Comment by jandersson** [comment]
Try `DRStats` instead of `DRstats` (case matters here)

**Comment by jandersson** [comment]
Also the method is `moon_mage?`. A question mark at the end of a method name means it returns true or false (The More You Know.gif) 

So `,en echo DRStats.moon_mage?` on my trader:
```
>;en echo DRStats.moon_mage?  
--- Lich: exec1 active.       
[exec1: false]                
--- Lich: exec1 has exited.
```

**Comment by DryIce41** [comment]
,en echo DRStats.moon_mage?

--- Lich: exec1 active.

[exec1: true]

--- Lich: exec1 has exited.

**Comment by DryIce41** [comment]
Thanks I wasn't putting the ? at the end lol  Don't know why i assumed that wasn't important

**Comment by jandersson** [comment]
Did it get worked out?

**Comment by DryIce41** [comment]
I think so.. but I have no idea how
