### ISSUE TITLE
Create pet boxes to a cap

### ISSUE THREAD

**Issue by EOughourli** [rpherbig/dr-scripts#2255]
I'd love an option in `pick.lic` to create pet boxes up to a cap, rather than a defined number of new boxes.  You can currently do ;pick pets x and it will attempt to disarm and save x number of boxes, but this is indifferent to the number of pet boxes you already have.  What would be nice is an option to do, maybe, ;pick pets cap x, and it will bring you up to x _total_ pet boxes in your `picking_pet_box_source`, inclusive of ones you already have.

**Comment by wscherer420** [comment]
it would be great if Pick always kept your pet box count up.  Rather than manually needing to run pet box.

**Comment by wstampley** [comment]
@rpherbig - Since pet boxes don't teach anymore, we can probably close this issue.
