### ISSUE TITLE
arrest with fine causes problems with crossing-training

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#226]
The script recovers on it's own if you have enough money on you to pay the fine or if you are put in the stocks.  Your gear gets returned to you right away.  Otherwise you have to pay your fine, return to the guard house and get your sack from the desk.  There could be things in the sack you're given if you had something in your hands at the time of the arrest.  Getting the items from the sack and stowing them isn't necessarily the best option, but it's probably better than being arrested with something in your hands that you need to continue training.

Can be potentially expensive with Forging training.  It gets stuck on forging and cycles through buying an ingot and trying to forge.  It dumps the ingot in the bucket and goes to the bank for more money.   Otherwise it's just a nuisance

A log of the arrest and fine
http://pastebin.com/zMBMv4F2

And of paying the fine/recovering the gear
http://pastebin.com/xtYAGuwh

**Comment by rpherbig** [comment]
`jail-buddy` should take care of this
