### ISSUE TITLE
Stealth Attack Override

### ISSUE THREAD

**Issue by izawwlgood** [rpherbig/dr-scripts#2262]
Survival primes will see a very significant bonus to hit from stealth, and accordingly, may want to train weapons via uphunting a bit more, and always using ambush/poach. I propose a flag, 'stealth_attack_always: true/false' that when set to true, has combat_trainer ignore Stealth field XP at 34/34, and simply ALWAYS uses stealth attacks/poaches/hides before casting vivi.

I'm not sure a good way of handling this, either always considering Stealth field XP < 34/34, or adding an or conditional to the use_stealth_attack check, but I think this would be useful for anyone who stealths.

**Comment by MahtraDR** [comment]
Closing this. We have a lot of issues to work on today, and this has had zero additional interest in four years.
