### ISSUE TITLE
Spellmonitor still broken for me 

### ISSUE THREAD

**Issue by DryIce41** [rpherbig/dr-scripts#2267]
>;spellmonitor
--- Lich: error: uninitialized constant DRStats
	spellmonitor:50:in `_script'
	C:/Users/JKGeda/Documents/lich/lich.rbw:2512:in `eval'
>;list
--- Lich: dependency, drinfomon, moonwatch, status-monitor, afk, textsubs, roomnumbers

I get this error on login and when I try to start spell monitor manually.  Any thoughts?

If I ;repos download spellmonitor  I get the old version of spellmonitor. Which will start but obviously doesn't work

**Comment by rpherbig** [comment]
Can you `;list trusted` and report back the output?

**Comment by DryIce41** [comment]
;list trusted
--- Lich: trusted scripts: repository, narost, narost, circlemonitor, spellmonitor, dr-autovote, slackbot, slackbot, lnet, status-monitor, dependency

**Comment by DryIce41** [comment]
I just untrusted all but dependency and it now seems to be working...

**Comment by rpherbig** [comment]
Untrusting spellmonitor was the fix. When it was trusted, it couldn't access the untrusted `drinfomon`.

**Comment by DryIce41** [comment]
Thank you!  Now I tried too many fixes before this and broke my setup to use Genie lol.  Messed up Ruby I think.  But that's another problem. Thank you much!
