### ISSUE TITLE
Jail-buddy assumes you get arrested in your hometown

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#2273]
Hometown is shard, got arrested in crossing.  Jail buddy paid my shard debt and went to the shard jail to retrieve items

**Comment by Sarvatt** [comment]
how do you envision it wokring? I could see checking the current room and go to the jail in the province that room is in after getting arrested. maybe start tracking jailer_room or something in base-towns to compare it to?

**Comment by jandersson** [comment]
Some brainstorming:

Check wealth while in jail. Parse your debt. Check wealth after being sentenced, the one that increases is the one you need to pay. 

The room you were arrested in is stored, so we can operate on tags for finding the jail. After being released.

If pay-debt doesn't take arguments for which provincial debt to pay, it should be updated to do that.

**Comment by jandersson** [comment]
Hopefully you dont get your tax bill while in jail. that could be some crazy corner case

**Comment by jayRyan24** [comment]
Can you parse your current location after you are freed? So, you are in jail in Shard, you do a ;reget #, parse it looking for the city, and then base your pay-debt and retrieval on that?

```
reget 20

reget.each
  if =~ /[(Shard,|Crossing|etc./i
    city = city name
    break
  end
 
wait_for_script_to_complete('pay-debt', city)
etc..
```

**Comment by MahtraDR** [comment]
Closing this. Hasn't been worked on since, and no requests since. If someone wants to submit, they can.
