### ISSUE TITLE
Moonblade woes

### ISSUE THREAD

**Issue by DryIce41** [rpherbig/dr-scripts#2307]
I'll lose my moonblade during a hunt for a number of reasons and combat trainer doesn't recognize to recast it. Can somebody help? I thought to put in and "expire" setting in the spell but I'll need to match multiple conditions.  The following is the messaging when I lose the spell:

- above your head and focus on disrupting its matrix in a spectacular manner  (messaging for when you break a moonblade which combat trainer occasionally does)
 
- Your moonblade dissipates into the shadows from whence it came. (messaging for when a katamba moon blade expires.)

- Your moonblade is consumed (messaging for when a yavash or xibar moonblade expires.  May need moonstaff equivelents)

**Comment by jandersson** [comment]
Have you looked at mooselurks YAML? He hunted primarily with moonweapons

**Comment by jayRyan24** [comment]
https://github.com/rpherbig/dr-scripts/blob/master/profiles/Mooselurk-setup.yaml

**Comment by jayRyan24** [comment]
Sorry, never used a moonblade except for shards for Tk ammo. :(

**Comment by DryIce41** [comment]
i have looked at it.  ill simplify my yaml and try it... i think theres a clause during ritual spells to break summoned weapons

**Comment by jandersson** [comment]
Can you paste the output from the game when it does that?

**Comment by DryIce41** [comment]
sure
[combat-trainer]>cast
You raise your hand in an imaginary toast to Glythtide.
As the spell dabs at the spirit realm, your mind falters into a fuzzy hallucination.  You feel a haze slip over you, like you have just been drinking too much wine.  A flock of flying books surrounds you, circling your head so that they are just out of your reach.  One of them flutters up to you and bops you on the nose!  Reeling from the impact, you see it settle itself in your lap like a housecat, opening itself to page 595.  You stare into the book, feeling wiser than before.

Emotional pain and exhaustion lingers in your mind, even after you regain rational control.
> 
[combat-trainer]>jab
> 
< Trying inexpertly, you jab a heavy black moonblade at a red bear orc bandit.  A red bear orc bandit dodges, stepping aside in the nick of time.  
[You're bruised, adeptly balanced and in good position.]
[Roundtime 2 sec.]
R> 
The orc bandit moves into a position to parry.
R> 
* With poor timing, a long-fanged warcat lashes out with large, velvet-padded claws extended at you.  You slap away little of the claw with a heavy black moonblade.  
[You're bruised, adeptly balanced and have slight advantage.]
R> 
* Moving weakly, a red bear orc bandit slices wide at you.  You evade, stepping aside in the nick of time.  
[You're bruised, adeptly balanced and in better position.]
R> 
[combat-trainer]>break my moonblade

You thrust your black moonblade above your head and focus on disrupting its matrix in a spectacular manner.
With a careful touch, you pick apart the right structures from the matrix, weakening its physical integrity without disrupting the power of the spell.
The black moonblade cracks down its length and then explodes into a cloud of black slivers!
The slivers drift about for a moment, then begin to orbit your head.
[combat-trainer]>get my telescope
You get a simple oak telescope from inside your oilcloth rucksack.
[combat-trainer]>center telescope on Verena
You put your eye to the oak telescope and attempt to center on the planet Verena.
Your search for the planet Verena turns up fruitless.
[combat-trainer]>center telescope on Estrilda
You put your eye to the oak telescope and attempt to center on the planet Estrilda.
Your search for the planet Estrilda turns up fruitless.
[combat-trainer]>center telescope on Durgaulda

**Comment by rpherbig** [comment]
In combat-trainer:
```
  def cast_ritual(data, game_state)
    if summoned = game_state.summoned_info(game_state.weapon_skill)
      break_summoned_weapon(game_state.weapon_name)
```

**Comment by DryIce41** [comment]
Yup. I saw that too. but I'm not familiar enough with the language yet to change it.  I also need combat-trainer to recast the moonblade when it expires.  It doesn't do that currently  And if it does (if I force it to) it doesn't shape it to the correct size.

**Comment by jandersson** [comment]
I would think that breaking is only needed for Warrior Mages, whereas moonmages can wear the weapon.

**Comment by Rhayle** [comment]
Has anyone worked on this? I am having the same problem. and was thinking of trying to tackle it

**Comment by DryIce41** [comment]
I don't think so.  I quit hunting with moonblades.  Im unfamiliar with Ruby code and have a newborn so I haven't made time for this in my life.  It'd be great if you tried it

**Comment by Rhayle** [comment]
ok. I will try to work on that. Be patient though, I'm still learning ruby.

**Comment by MahtraDR** [comment]
@rpherbig We can close this.
