### ISSUE TITLE
crossing-training workorders for non traders

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#232]
Creating this at the request of @rcuhljr 

Workorders function on non-traders, however, no other skills get trained due to the lack of Trading skill.

**Comment by rcuhljr** [comment]
http://pastebin.com/PyrNAptR
http://pastebin.com/KX8bq3dz

**Comment by rcuhljr** [comment]
e59eb3ecf1ec719ff6b0afa9f5c704fcba06d98c
