### ISSUE TITLE
workorders hang if items are bundled with logbook

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#235]
This happens when trying to get new work orders after the script is killed or interrupted via disconnect etc.

You go west.
[Engineering Society, Crafting Supplies - 8865]
Expertly fitted grey marble slabs frame the lower half of the shop's alabaster walls.  Shadows dance at the light produced by carefully arranged copper torch holders about the room.  This area sells a variety of supplies to eager crafters and offers some shelter from the loud noises of productivity emanating from the east.  You also see Engineering Society Mistress Talia Volmogen, an elegantly carved mistwood door leading outside and a large sign.
Obvious exits: north, east, west.

[go2: travel time: 0:00:00]

--- Lich: go2 has exited.

[workorders]>get my engineering logbook

You get an engineering work order logbook from inside your rucksack.

[workorders]>ask Talia for challenging Shaping work

You realize you have items bundled with the logbook, and should untie them before getting a new work order.

[workorders: *** No match was found after 15 seconds, dumping info]

[workorders: messages seen length: 4]

[workorders: message: You realize you have items bundled with the logbook, and should untie them before getting a new work order.]

[workorders: message: Eillie's Cry  (62 roisaen)]

[workorders: message: Redeemer's Pride  (18 roisaen)]

[workorders: message: Gauge Flow  (49 roisaen)]

[workorders: checked against [/^To whom/i, /order for .* I need \d+ of .* quality/i]]

[workorders]>ask Talia for challenging Shaping work

You realize you have items bundled with the logbook, and should untie them before getting a new work order.

[workorders: *** No match was found after 15 seconds, dumping info]

[workorders: messages seen length: 7]

[workorders: message: You realize you have items bundled with the logbook, and should untie them before getting a new work order.]

[workorders: message: Eillie's Cry  (62 roisaen)]

[workorders: message: Redeemer's Pride  (18 roisaen)]

[workorders: message: Gauge Flow  (48 roisaen)]

[workorders: message: Eillie's Cry  (62 roisaen)]

[workorders: message: Redeemer's Pride  (18 roisaen)]

[workorders: message: Gauge Flow  (48 roisaen)]

[workorders: checked against [/^To whom/i, /order for .* I need \d+ of .* quality/i]]

[workorders]>ask Talia for challenging Shaping work

You realize you have items bundled with the logbook, and should untie them before getting a new work order.

[workorders: *** No match was found after 15 seconds, dumping info]

[workorders: messages seen length: 4]

[workorders: message: You realize you have items bundled with the logbook, and should untie them before getting a new work order.]

[workorders: message: Eillie's Cry  (62 roisaen)]

[workorders: message: Redeemer's Pride  (18 roisaen)]

[workorders: message: Gauge Flow  (48 roisaen)]

[workorders: checked against [/^To whom/i, /order for .* I need \d+ of .* quality/i]]

[workorders]>ask Talia for challenging Shaping work

You realize you have items bundled with the logbook, and should untie them before getting a new work order.
Talia casually explains, "Please ask me about careers or hobbies if you are interested in learning more about them."

[workorders: *** No match was found after 15 seconds, dumping info]

[workorders: messages seen length: 8]

[workorders: message: You realize you have items bundled with the logbook, and should untie them before getting a new work order.]

[workorders: message: Eillie's Cry  (61 roisaen)]

[workorders: message: Redeemer's Pride  (18 roisaen)]

[workorders: message: Gauge Flow  (48 roisaen)]

[workorders: message: Talia casually explains, "Please ask me about careers or hobbies if you are interested in learning more about them."]

[workorders: message: Eillie's Cry  (61 roisaen)]

[workorders: message: Redeemer's Pride  (18 roisaen)]

[workorders: message: Gauge Flow  (48 roisaen)]

[workorders: checked against [/^To whom/i, /order for .* I need \d+ of .* quality/i]]

**Comment by rcuhljr** [comment]
d410e6fd9be048d65c4aa8fc53f7dac21b25ff0b  Let us know if this doesn't fix it.
