### ISSUE TITLE
Todo List for Risen

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#2366]
The purpose of this issue is to create a discussion around the 'nice-to-haves' regarding the upcoming necromancer feature 'Risen' and how that will integrate with dr-scripts.. When they are released we can break this into individual tasks/issues to be tackled and close this.

It would be nice to 
* store the recipes for risen in base/data-necromancer.yaml
* have a script track the contents of your locker, similar to `;vaults` and `;banks`
* have combat-trainer support butchering
* have a script for stitching them together from parts stored in the locker. (named ;makemans)
* have combat trainer support 'combat risen' summoning and buffing/debuffing

**Comment by MahtraDR** [comment]
After consultation with my resident Necro class expert, I'm closing this out as no longer relevant today. 

Would be happy to revisit as a fresh issue whenif it comes up again.
