### ISSUE TITLE
validate should check if sell_loot_money_on_hand is valid

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#2371]
sell_loot_money_on_hand: 1000 will fail because it does a keep_coppers_bank = parse(keep_money_by_currency.split(' ')) expecting the right format (which would be 1 gold or 10 silver), but it is not obvious what the formatting should be.

**Comment by jandersson** [comment]
What is the correct format?

**Comment by rpherbig** [comment]
`sell_loot_money_on_hand: [amount as integer] [currency as string]`

**Comment by jandersson** [comment]
Sorry to be a pain, but is that `3000 kronars` or `3000 bronze`?

**Comment by Sarvatt** [comment]
copper bronze silver gold platinum, it reduces it to the least amount of coins, sell_loot_money_on_hand: 3000 bronze would withdraw 3 platinum

**Comment by jandersson** [comment]
This is resolved

**Comment by rpherbig** [comment]
#2388
