### ISSUE TITLE
Finish writing mine2.lic (to replace mine.lic and danger.lic)

### ISSUE THREAD

**Issue by hwoo79** [rpherbig/dr-scripts#238]
[mine]>stow
 get my packet
You put your shovel in your traveler's pack.
>
You get a large packet of deed claim forms from inside your tool bag.
>
[mine]>push nugget with packet
 stow left

You push the nugget to the side and tear off a claim notice from your packet.  After affixing the form securely to the nugget, you record it on a deed for your records.
The deed packet appears out of deeds, so you toss it away!
>
Stow what?  Type 'STOW HELP' for details.
>

[mine]>stow
 get my packet
>
You put your shovel in your traveler's pack.
>
What were you referring to?

**Comment by rpherbig** [comment]
This should be part of the rewrite of `danger` and `mine` (see `mine2.lic`).
