### ISSUE TITLE
Use yaml to select text subs

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#2396]
Text subs is starting to get pretty bloated, people should be able to opt in/out of subsections of subs to use through their yaml.

    text_subs:
      item_app: true
      damage: true
      combat_app: false
      mana_levels: true

**Comment by rpherbig** [comment]
Has this been requested by users?

**Comment by rcuhljr** [comment]
Just me.

**Comment by MahtraDR** [comment]
Closing this out as stale today. I'd love for users to be able to define their own textsubs, which is what I originally this was. Also... mana levels, combat appraisal, damage, and item appraisals are all displayed in the game stream today. We can clean up textsubs quite a bit.
