### ISSUE TITLE
Room missing near 2092 - old cranks road and Storm bulls

### ISSUE THREAD

**Issue by Missah** [rpherbig/dr-scripts#2402]
Go2 is stopping because of missing room:

[Old Crank's Road, Forest]
Leaves littering the surface of the damp road await their final fate:  being slowly ground into the mud, then decaying into the earth to create another layer of rich, dark loam.  Sloping downward to the southwest, this section of road is a long, gentle bend following a curve from the northwest.  
Obvious paths: southwest, northwest.

Room Number: 2092

[go2]>west

You easily navigate the mud and move forward...
Roundtime:  3 seconds.
...wait 3 seconds.
--- error: server_thread: Missing end tag for '' (got "component")
Line: 1
Position: 33
Last 80 unconsumed characters:
[Old Crank's Road, Forest]
Light filtering through the branches casts a hazy, warm glow to all it touches, from the snake-like moss roped around the trees to the new shoots of vegetation pushing up through the moist soil at the edge of the road.  Staggered puddles of water fill the deep wheel gashes slashed into the trail.  As each wagon passes, the puddle configuration changes, as the waters mingle and advance down slope toward the marshland.  
Obvious paths: northeast, south.
...wait 3 seconds.

[go2]>west

...wait 3 seconds.
...wait 3 seconds.
...wait 3 seconds.

[go2: restarting script...]

[go2: error: your current room was not found in the map database]

--- Lich: go2 has exited.

**Comment by Sarvatt** [comment]
Hopefully this fixes it, it looks like its 2176 and I added the description to the right room number.

--- Lich: exec1 active.
[exec1: @id=2176
@image="zoluren-111-road_to_ilaya_taipa-1377281955.png"
@climate=nil
@title=["[[Old Crank's Road, Forest]]"]
@check_location=nil
@timeto={"2092"=>0.2, "2177"=>0.2}
@location=nil
@tags=[]
@wayto={"2092"=>"northeast", "2177"=>"south"}
@paths=["Obvious paths: northeast, south."]
@image_coords=[258, 345, 272, 359]
@terrain=nil
@description=["The wind filtering through the branches sings a soft evening lullaby, accompanied by the creak of limbs and gentle percussion of the snake-like moss thumping the trees.  Staggered puddles of water fill the deep wheel gashes slashed into the trail.  As each wagon passes, the puddle configuration changes, and the waters mingle and advance down slope toward the marshland.", "Light filtering through the branches casts a hazy, warm glow to all it touches, from the snake-like moss roped around the trees to the new shoots of vegetation pushing up through the moist soil at the edge of the road. Staggered puddles of water fill the deep wheel gashes slashed into the trail. As each wagon passes, the puddle configuration changes, as the waters mingle and advance down slope toward the marshland."]]
--- Lich: exec1 has exited.

**Comment by Missah** [comment]
Thanks!  I'll let you know if it happens again.

**Comment by Missah** [comment]
Haven't had any further issues in more than a week.  I think we can close this?
