### ISSUE TITLE
Jailbuddy breaks when using bankbot

### ISSUE THREAD

**Issue by Maledar** [rpherbig/dr-scripts#2433]
Small hiccup I found when using a bankbot, when you're arrested with jailbuddy, during the paydebt it breaks when withdrawing the money

**Comment by Dartellum** [comment]
Please provide a log so I can see. Pay-debt.lic has the proper settings for it to work. Are you using a custom script?

**Comment by Maledar** [comment]
Finally got a log of the incident

You aren't wearing anything special.
[Type INVENTORY HELP for more options]
>
--- Lich: 'go2' has been stopped by pay-debt.
--- Lich: go2 has exited.
--- Lich: go2 active.
[go2: you're already here...]
--- Lich: go2 has exited.
[pay-debt]>whisper Bankbot withdraw 10000 kronars
You whisper to Bankbot, "withdraw 10000 kronars"
>
Bankbot offers you a tip of 10,000 Kronars.  Type ACCEPT TIP, to accept it or DECLINE TIP to refuse it.
>
[pay-debt]>accept tip
You accept Bankbot's tip and slip it away.
>
[pay-debt]>whisper Bankbot withdraw 3000 kronars
Bankbot whispers, "Your balance is: 8,084,807 Kronars,  Lirums,  Dokoras."
>
You whisper to Bankbot, "withdraw 3000 kronars"
>
Bankbot offers you a tip of 3,000 Kronars.  Type ACCEPT TIP, to accept it or DECLINE TIP to refuse it.
>
[pay-debt]>accept tip
You accept Bankbot's tip and slip it away.
>
[pay-debt]>whisper Bankbot withdraw 90 kronars
>
You whisper to Bankbot, "withdraw 90 kronars"
>
Bankbot whispers, "Your balance is: 8,081,807 Kronars,  Lirums,  Dokoras."
>
Bankbot offers you a tip of 90 Kronars.  Type ACCEPT TIP, to accept it or DECLINE TIP to refuse it.
>
[pay-debt]>accept tip
You accept Bankbot's tip and slip it away.
>
[pay-debt]>whisper Bankbot withdraw 6 kronars
You whisper to Bankbot, "withdraw 6 kronars"
>
Bankbot whispers, "Your balance is: 8,081,717 Kronars,  Lirums,  Dokoras."
>
Telarann just arrived.
>
Telarann runs out.
>
[pay-debt: *** No match was found after 15 seconds, dumping info]
[pay-debt: messages seen length: 10]
[pay-debt: message: Psychic Shield  (16 roisaen)]
[pay-debt: message: Seer's Sense  (8 roisaen)]
[pay-debt: message: Bless  (5 roisaen)]
[pay-debt: message: Destiny Cipher  (35 roisaen)]
[pay-debt: message: Telarann runs out.]
[pay-debt: message: Telarann just arrived.]
[pay-debt: message: Bankbot whispers, "Your balance is: 8081717 Kronars,  Lirums,  Dokoras."]
[pay-debt: message: Bankbot whispers, "Your balance is: 8081717 Kronars,  Lirums,  Dokoras."]
[pay-debt: message: You whisper to Bankbot, "withdraw 6 kronars"]
[pay-debt: message: You whisper to Bankbot, "withdraw 6 kronars"]
[pay-debt: checked against [/offers you/i, /Whisper what to who?/i]]
[pay-debt: for command whisper Bankbot withdraw 6 kronars]
[pay-debt: ***STATUS*** Insufficient funds to pay your debt]
[pay-debt: ]
--- Lich: pay-debt has exited.
[jail-buddy: ***STATUS*** Failed to pay debt and retrieve items]
[jail-buddy:]
--- Lich: jail-buddy has exited.

**Comment by Maledar** [comment]
And no not using any custom script just got picked up by guards running to train something

**Comment by Maledar** [comment]
This is bankbots side, I only deleted ledger info

Maledar whispers, "withdraw 10000 kronars"                                                                                                                                                                                                                                               |
[bankbot]>tip Maledar 10000 Kronars                                                                                                                                                                                                                                                      |
You offer Maledar a tip of 10,000 Kronars.  Type CANCEL TIP to withdraw the offer.                                                                                                                                                                                                       |
>                                                                                                                                                                                                                                                                                      |
Maledar accepts your tip and slips it away with a smile.                                                                                                                                                                                                                                 |
>                                                                                                                                                                                                                                                                                      |
[bankbot: Logging: Maledar, withdrawal, 10000, Kronars, succeeded]                                                                                                                                                                                                                       |
          |
[bankbot]>whisper Maledar Your balance is: 8084807 Kronars,  Lirums,  Dokoras.                                                                                                                                                                                                           |
You whisper to Maledar, "Your balance is: 8,084,807 Kronars,  Lirums,  Dokoras."                                                                                                                                                                                                         |
>                                                                                                                                                                                                                                                                                      |
Maledar whispers, "withdraw 3000 kronars"                                                                                                                                                                                                                                                |
[bankbot]>tip Maledar 3000 Kronars                                                                                                                                                                                                                                                       |
You offer Maledar a tip of 3,000 Kronars.  Type CANCEL TIP to withdraw the offer.                                                                                                                                                                                                        |
>                                                                                                                                                                                                                                                                                      |
Maledar accepts your tip and slips it away with a smile.                                                                                                                                                                                                                                 |
>                                                                                                                                                                                                                                                                                      |
[bankbot: Logging: Maledar, withdrawal, 3000, Kronars, succeeded]                                                                                                                                                                                                                        |
          |
[bankbot]>whisper Maledar Your balance is: 8081807 Kronars,  Lirums,  Dokoras.                                                                                                                                                                                                           |
Maledar whispers, "withdraw 90 kronars"                                                                                                                                                                                                                                                  |
>                                                                                                                                                                                                                                                                                      |
You whisper to Maledar, "Your balance is: 8,081,807 Kronars,  Lirums,  Dokoras."                                                                                                                                                                                                         |
[bankbot]>tip Maledar 90 Kronars                                                                                                                                                                                                                                                         |
You offer Maledar a tip of 90 Kronars.  Type CANCEL TIP to withdraw the offer.                                                                                                                                                                                                           |
>                                                                                                                                                                                                                                                                                      |
Maledar accepts your tip and slips it away with a smile.                                                                                                                                                                                                                                 |
>                                                                                                                                                                                                                                                                                      |
Maledar whispers, "withdraw 6 kronars"                                                                                                                                                                                                                                                   |
>                                                                                                                                                                                                                                                                                      |
[bankbot: Logging: Maledar, withdrawal, 90, Kronars, succeeded]
         |
[bankbot]>whisper Maledar Your balance is: 8081717 Kronars,  Lirums,  Dokoras.                                                                                                                                                                                                           |
You whisper to Maledar, "Your balance is: 8,081,717 Kronars,  Lirums,  Dokoras."                                                                                                                                                                                                         |
>                                                                                                                                                                                                                                                                                      |
Telarann just arrived.

**Comment by Dartellum** [comment]
Looks working to me all up to the last withdraw. Was your bankbot in roundtime?

**Comment by Maledar** [comment]
Nope he didn't get any error message or anything wasn't doing any commands

**Comment by Dartellum** [comment]
The last whisper just disappeared into the ether it looks like.

**Comment by Dartellum** [comment]
I think a pause may correct this.

**Comment by Maledar** [comment]
Not a bad idea but it has to do with taking money from bankbot with all denominations I believe because it broke in the same manner when doing a workorder

**Comment by Dartellum** [comment]
My guys use my bankbot and grab the money. I have 5 characters using him. Once in a while I see one of the asks do not take but my guy asks again. Also, if it goes through without kronars at the end it will fail.

**Comment by MahtraDR** [comment]
Closing this. Not seen any reports since 2018. We can treat new reports as fresh.
