### ISSUE TITLE
Stalking while hunting follows critter into occupied room

### ISSUE THREAD

**Issue by Missah** [rpherbig/dr-scripts#2436]
Hunting Warklins in room #1.....followed a Warklin into room #2 which was occupied......any way to avoid this?   Log below:

I was hunting in room #7272.

[combat-trainer]>engage

You are already advancing on a warklin mauler.
A warklin mauler appears less distracted.
You notice Missah attempting to conceal her spell preparations.
Missah raises her arms skyward, chanting.
An armored warklin slices wide at Missah.  
You hear a warklin mauler breathing slowly.
A warklin mauler carefully picks its way east.
An armored warklin carefully picks its way north.

[hunting-buddy: ***STATUS*** 9 minutes of hunting remaining or waiting on Stealth]

Missah is engulfed in a ripple of light and shadow, and vanishes, only to reappear some distance away!
The warklin mauler begins to advance on Missah.
The warklin mauler begins to advance on Missah.
Missah reveals a moderate weakness in a warklin mauler's defense.

[combat-trainer]>cast

You have lost sight of your target, so you stop advancing.

You move along to follow your mark.

[Abandoned Mine, Tunnel]
The passageway levels off here allowing you to slow down and catch your breath.  The guiding light is even scarcer causing the occasional stumble, stubbed toe and silent curse.  You also see a warklin mauler, a warklin mauler, an armored warklin, an armored warklin and an armored warklin.
Also here: Doom's Whisper Buluc.
Obvious exits: west, up.

Room Number: 7273

A chorus of trilling mews heralds the arrival of a mischievous snow white kitten with taffelberry-stained paws.
A warklin mauler twists its torso wildly, thrusting its impalers at Buluc.  
You turn to face a warklin mauler.
You reveal yourself.
You gesture at a warklin mauler.
Slippery as an eel, a spiritual tendril creeps into its soul, engendering a powerful sense of indecisiveness.  The warklin mauler begins to mope around obliviously.
It drops to its knees before you.
Roundtime: 2 sec.
You feel fully rested.
You feel fully attuned to the mana streams again.
An armored warklin lunges with its razorlike mandibles at Buluc.  
An armored warklin lashes its scythe-bladed foreleg at Buluc.  
Buluc draws a balanced bar mace at an armored warklin.  The mace lands a strong hit (6/23) that rips the top layer of skin from its chest and exposes underlying muscle, stunning it!  

[combat-trainer]>hide

You blend in with your surroundings, but cannot shake the feeling that you drew attention to yourself.
Roundtime: 3 sec.
An armored warklin wobbles precariously, eyes filmed over slightly.
Buluc traces a careful sigil in the air.

[combat-trainer]>attack

A warklin mauler rears back and slashes its impaler at Buluc.  
You aren't close enough to attack.
You begin to stealthily advance on a warklin mauler.

[combat-trainer]>engage

You are already advancing on a warklin mauler.

**Comment by Sarvatt** [comment]
dont_stalk: true if you don't want to follow mobs to other rooms like that

**Comment by jandersson** [comment]
I can add in a stop stalk command after you successfully stalk

**Comment by Sarvatt** [comment]
if you stop stalk does attacking reset the stalk timer though? that is a really good idea

**Comment by jandersson** [comment]
I dont know

**Comment by Missah** [comment]
In the meantime, I'll add dont_stalk: true to my yaml.  Wasn't aware of that setting.  Thanks!
