### ISSUE TITLE
Meditate Contemplation stands too soon when used in ;buff <waggle set>

### ISSUE THREAD

**Issue by joeblow7314** [rpherbig/dr-scripts#2440]
The RT doesn't actually last as long as you need to remain seated to get the meditation to take effect, so the ;buff script ends up standing too soon.

Verbiage to wait for is either "The flame dance about you and fuel an enhanced defensive capability!" or more generically "You feel a jolt as your vision snaps shut." (the latter would probably be useful for all meditations)

Log of what happens:
"[buff]>med contemplation
You must be sitting to properly reinforce your physical resistance.
>
[buff]>sit
You sit down.
s>
[buff]>med contemplation
You begin to meditate upon the chakrel amulet, your inner fire swelling as you center your mind, body, and spirit.
Roundtime: 9 sec.
sR>
Gazing into the flame, you contemplate a myriad of protective strategies.
sR>
Closer, closer the flames leap as you complete the martial analysis.
sR>
[buff]>stand
s>
You stand back up.
>
Standing has disrupted your focus, leaving you vulnerable to physical harm."

**Comment by MahtraDR** [comment]
Closing as this issue was resolved between then and now sometime. Can't reproduce today.
