### ISSUE TITLE
workorders - shaping - does not recover on failed shaping

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#245]
Log in pastebin.  This could potentially happen in any craft.

Possible solution, ANALYZE the item being crafted after sending an error to the game window to determine which tool to use next.

Workorder is for a toe ring.  Shape starts crafting a toe ring, but reports an error after no messages received in 15 seconds, seems to ignore the first message and proceeds to shape again, then the error loop begins.

http://pastebin.com/X3maSAnJ

**Comment by rcuhljr** [comment]
This is an unrelated to crafting bug we haven't tracked down. I think it may lie in Lich itself. Sometimes the buffer for a script just gets screwed up and our bput never sees messages even when they occur. Restarting fixes it but it's been sufficiently rare.

**Comment by OdnaZvezda** [comment]
Noted.  But when shape sees the following, it could take some corrective measures.

[shape]>rub my ring with my rasp
 
That tool does not seem suitable for that task.

**Comment by rcuhljr** [comment]
If you get me the analyze messaging for the various tools I'll add in some recovery options.

**Comment by OdnaZvezda** [comment]
blacksmithing http://pastebin.com/XC58CLxs
tailoring http://pastebin.com/q4WJtEsi
shaping http://pastebin.com/xG076hqr

**Comment by rpherbig** [comment]
@rcuhljr @OdnaZvezda  Is this done?
