### ISSUE TITLE
Gate of souls entry bescort needed

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#2450]
This will open up a lot of f2p hunting areas. There are 2 parts to wander through, the entrance needs you to wander and has mobs around 120-170 ranks in it, you exit the maze to move further in by finding a temple you can go through that opens up 2 tiers of atik'et mobs, then finally another wandering maze in the south part that has firecats and atik'et mobs that train around 280-425 ranks.

https://elanthipedia.play.net/RanikMap14a

**Comment by jayRyan24** [comment]
I love this area from the Ushnish quests. Is all of this mapped?

**Comment by jandersson** [comment]
Only the maze areas are unmapped

**Comment by Sarvatt** [comment]
Fixed by https://github.com/rpherbig/dr-scripts/commit/17670ebb3c56c8e62f71d54d58ad0475449e647f
