### ISSUE TITLE
Shaping is giving an error every time it completes a workorder

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#2458]
read log is giving this message

You open your logbook and sort through its contents.
This logbook is tracking a work order requiring you to craft a wood belt buckle.  This work order appears to be complete.  Now give it to a crafting trainer within the next 68 roisaen to receive payment. 

but it's getting hung up for a bit checking how many more items you must bundle

```
[workorders: checked against [/You must bundle and deliver \d+ more/i]]
[workorders: for command read my log]

**Comment by Dartellum** [comment]
I fixed this, I believe. Works on my guy as intended.
