### ISSUE TITLE
workorders - 2 issues (carving knife stowed in weapon container & lumber at feet)

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#247]
http://pastebin.com/URTysJ4F

Issue 1 - I logged in at home after leaving crossing-training running at work.  I was mid shaping and after finishing the work order manually, I STOWed my carving knife(bad me I know).  Being a weapon, it put the knife in my weapon container and was unable to find it later.  Would it suffice for the script to "get my <crafting tool>" rather than "get my <crafting tool> from my <container>"?   I don't carry more than one of any crafting tool around with me(or weapon with a crafting tool name, I'm looking at you throwing hammer.  Now I use a hhr'ata).  I can't speak for others.

Issue 2 - Shape.lic stopped after not finding a carving knife.  My characters hands were full and there was lumber at her feet.   Issue 2 might not have happened if not for Issue 1 and Issue 2 may be a good thing in this case.  If the script had been free to continue, more wood would have been bought, partially crafted and ultimately wasted, resulting in a loss of money.

**Comment by rcuhljr** [comment]
get my carving knife is probably a good switch. I'll look at making the change.

**Comment by rcuhljr** [comment]
2ec306a
