### ISSUE TITLE
Super random restock issue feeling about something and not seeing what you're looking for 

### ISSUE THREAD

**Issue by Maledar** [rpherbig/dr-scripts#2488]
[hunting-buddy]>tap my bundle
I could not find what you were referring to.
>
[hunting-buddy]>tap my bundling rope
You tap a braided bundling rope inside your leather backpack.
>
--- Lich: restock active.
[restock]>open my carryall
That is already open.
>
[restock]>open my greatsword sheath
You are confident that your refractive field has fully oscillated, concealing you once again.
>
[restock]>open my backpack
That is already open.
>
That is already open.
>
[restock]>count my first boar-tusk arrows
You count some boar-tusk arrows in the quiver and see there are thirty-nine left.
>
[restock]>count my second boar-tusk arrows
I could not find what you were referring to.
>
[restock]>tap my wide-bladed dagger
You tap a wide-bladed dagger inside your leather backpack.
>
[restock]>rummage /C dagger IN MY leather backpack
You feel about a weathered dark brown leather backpack with a torn strap.
>
You feel fully rested.
>
[restock: *** No match was found after 15 seconds, dumping info]
[restock: messages seen length: 16]
[restock: message: Seer's Sense  (25 roisaen)]
[restock: message: Psychic Shield  (29 roisaen)]
[restock: message: Refractive Field  (20 roisaen)]
[restock: message: Shadows  (26 roisaen)]
[restock: message: Clear Vision  (27 roisaen)]
[restock: message: Bless  (20 roisaen)]
[restock: message: [DRPrime]-DR:Absidian: "I pulled off the durn gweth. I kept getting my thinking and my chatting confused and wound up feeling stupid. No worries chuno. It takes a lot to offend me. just let me fart first and well get along fine."]
[restock: message: [DRPrime]-You: "I'm so confused"]
[restock: message: Seer's Sense  (25 roisaen)]
[restock: message: Psychic Shield  (29 roisaen)]
[restock: message: Refractive Field  (20 roisaen)]
[restock: message: Shadows  (27 roisaen)]
[restock: message: Clear Vision  (27 roisaen)]
[restock: message: Bless  (20 roisaen)]
[restock: message: You feel fully rested.]
[restock: message: You feel about a weathered dark brown leather backpack with a torn strap.]
[restock: checked against [/^You rummage .*/i]]
[restock: for command rummage /C dagger IN MY leather backpack]
[restock]>wealth kronars

**Comment by Sarvatt** [comment]
so it needs a release_invisibility

**Comment by Maledar** [comment]
I'm pretty certain I wasn't in RF

**Comment by Maledar** [comment]
I wasn't because I had just finished a sewing workorder

**Comment by Sarvatt** [comment]
it shows you in RF, restock needs to release invisibility before rummaging

**Comment by MahtraDR** [comment]
I can't reproduce this today.
