### ISSUE TITLE
workorders - crafted item quality lower than required by work order

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#252]
[sew]>cast my needles
You add a row of double stitches to the booties and cast it off from your knitting needles.
Roundtime: 21 sec.
Applying the final touches, you complete working on some knitted wool booties.
>
[sew]>stow my needles
You put your needles in your rucksack.
>
[sew]>get my outfitting logbook
You get an outfitting work order logbook from inside your rucksack.
>
[sew]>bundle my booties with my logbook
The work order requires items of a higher quality, so you decide against bundling that.
>
[sew: *** No match was found after 15 seconds, dumping info]
[sew: messages seen length: 1]
[sew: message: The work order requires items of a higher quality, so you decide against bundling that.]
[sew: checked against [/You notate the/i, /This work order has expired/i]]
[sew]>put my outfitting logbook in my rucksack
You put your logbook in your rucksack.
>
--- Lich: sew has exited.
--- Lich: sew active.
[sew]>get my tailoring book
You get a book of apprentice tailoring instructions from inside your rucksack.
>

**Comment by rcuhljr** [comment]
a666bf7

**Comment by OdnaZvezda** [comment]
if /requires items of/ =~ bput("bundle my #{@item}

@item should be @noun
