### ISSUE TITLE
Finally solve the cross versioning problem.

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#2526]
Dumping conversation here to keep my current best brainstorm of a way to solve this problem permanently.

>Out of curiosity why don't we add a version variable to the top of the common files and when inserting features require common_file_version >= version on new features?

>Noise and cumbersome mostly, and it only solves a subsection of the problem since it only catches new functionality requirements when the most common occurrence we have is in the opposite direction, new common files will break when used with older main files.  If someone really wanted to tackle the problem you should snapshot the hashes from git on dependency start up, and check each file hash before loading it in bootstrap, if it's changed refetch the old version you require from github and load that into memory. That would keep a running instance dependency always using it's version of scripts preventing cross instance collisions.

**Comment by MahtraDR** [comment]
We have versioning on some critical scripts, but on balance, I don't think we're missing anything on commons without versions today. Closing as stale.
