### ISSUE TITLE
ssl error and dependency quitting

### ISSUE THREAD

**Issue by Manterre** [rpherbig/dr-scripts#2542]
I am getting the following error with lich

--- Lich: error: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version
    C:/Ruby200/lib/ruby/2.0.0/net/http.rb:918:in `connect'
    C:/Ruby200/lib/ruby/2.0.0/net/http.rb:918:in `block in connect'
then it kills dependency

**Comment by rcuhljr** [comment]
Can you `;e echo "#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL}"`

**Comment by Sarvatt** [comment]
yeah you need to update that past 2.0.0-p594 to connect to github now

**Comment by Sarvatt** [comment]
did that fix it?

**Comment by MahtraDR** [comment]
@rpherbig This can be closed.
