### ISSUE TITLE
;pick bugging picking through non disarmed boxes

### ISSUE THREAD

**Issue by Maledar** [rpherbig/dr-scripts#2552]
Encountered by our good friend Majorly I'm posting his log, it looks like it picked up Vunes braiding as a successful disarm? Not sure but he ended up taking a bolt to the face 

[DRPrime]-DR:Maj: "Bad thing it, when it does that, it doesnt check for injury either since it thinks it passed the disarm phase"
[DRPrime]-DR:Maj: "A simple addition to check for However, a reinforced ironwood box is not fully disarmed, making any chance of picking it unlikely.... would work

[pick]>disarm my box quick

You quickly work at disarming the box.
You work with the trap for a while but are unable to make any progress.
You get the distinct feeling your manipulation caused something to shift inside the trap mechanism.  This is not likely to be a good thing.
Roundtime: 1 sec.

[pick]>disarm my box careful

...wait 1 seconds.
Vune continues to braid his vines.

[pick]>pick my box ident

You can unlock the ironwood box with only minor troubles.
However, a reinforced ironwood box is not fully disarmed, making any chance of picking it unlikely.
Roundtime: 1 sec.

[pick]>pick my box quick

You deftly remove a lockpick from the lockpick ring and begin to work at quickly picking open the box.
You realize very quickly that this was a very bad idea...
Just as your ears register the sound of a sharp snap, a crossbow bolt flies out the front of the box right into your body!
A crossbow bolt lodges lightly in your head.
You realize that despite this mishap, the box still has more to torment you with.
You return your lockpick to the lockpick ring.
Roundtime: 1 sec.

[pick]>open my box

It is locked.

[pick]>dismantle my box thump

You must first disarm the ironwood box before you attempt to dismantle it.
Vune roots around the area for a moment.
Vune forages around the area for a while until he finds a vine.
Vune continues to braid his vines.
Vune continues to braid his vines

**Comment by rcuhljr** [comment]
The vine braiding is unrelated, I think there's a race condition with lag spikes here where we see 'Unable to make any progress', fire off the next bput, and the next bput sees the previous commands RT which came after the retry message as success for it's most recent command. 

Adding a pause (less ideal) or a `waitfor('Roundtime')` before this [line](https://github.com/rpherbig/dr-scripts/blob/master/pick.lic#L416) should fix the problem but you'll want to test it a bit if you know anyone who blows up locks regularly.

**Comment by KatoakDR** [comment]
Same issue as #4316

This issue was fixed by:
* https://github.com/rpherbig/dr-scripts/pull/4799

Thank you

@rpherbig this may be closed
