### ISSUE TITLE
hunting-buddy  EXECUTing pick in combat

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#2553]
[hunting-buddy: ***STATUS*** EXECUTE pick]

[combat-trainer]>retreat

You retreat from combat.

[combat-trainer]>release EE

Release what?
[Check RELEASE HELP for more information.]

--- Lich: combat-trainer has exited.

[hunting-buddy]>retreat

A hulking Xala'shar magus glowers darkly at you.
You feel a wash of heat as a spell shatters against your ward.
A hulking Xala'shar magus glowers darkly at you.
You feel a wash of heat as a spell shatters against your ward.
You are already as far away as you can get!

[hunting-buddy]>release EE

Release what?
[Check RELEASE HELP for more information.]

[hunting-buddy: ***STATUS*** EXECUTE pick]

--- Lich: pick active.

A hulking Xala'shar magus spreads its arms and begins chanting in an ancient tongue, it robes thrashing about wildly as if surrounded in an ethereal wind.
The Xala'shar magus begins to advance on you!
The Xala'shar magus is still a distance away from you and is closing steadily.
A hulking Xala'shar magus spreads its arms and begins chanting in an ancient tongue, it robes thrashing about wildly as if surrounded in an ethereal wind.
The Xala'shar magus begins to advance on you!
The Xala'shar magus is still a distance away from you and is closing steadily.

[pick]>open my duffel bag

What were you referring to?

[pick]>open my backpack

That is already open.

[pick]>open my carry

That is already open.

[pick]>rummage /B my duffel bag

I don't know what you are referring to.

[pick]>rummage /B my carry

You rummage through a multi-strapped carryall looking for boxes and see a reinforced mahogany casket, a plain copper chest, a plain copper crate, a misshaped ironwood skippet and a rusty iron chest.

[pick]>get my casket from my carry

You get a reinforced mahogany casket from inside your multi-strapped carryall.

[pick]>disarm my casket identify

You notice a small hole in the side of the casket and the remnants of some type of powder.
Roundtime: 3 sec.
The Xala'shar thrall begins to advance on you!
The Xala'shar thrall is still a distance away from you and is closing steadily.
A hulking Xala'shar magus shudders beneath its voluminous robes, a scabbed hand pulling tightly at the fabric draped over its shoulders.

[pick]>disarm my casket careful

**Comment by Aurayn** [comment]
before:
  - release_cyclic 
  after:
  **- safe-room force**   <-----
  - go2 1051
  - release_cyclic 
  - buff aec   
  - summon-admitt 
  - summon-pathway
  - athletics
  - pick
  - buff etf
  - buff

**Comment by wstampley** [comment]
@rpherbig - This is a configuration issue, not a code one, and should be able to be closed.
