### ISSUE TITLE
TM Foci doesn't get reapplied when having to tie bundle

### ISSUE THREAD

**Issue by halprind** [rpherbig/dr-scripts#2556]
mentioned in discord:
> I noticed that if you have a TM foci invoked while needing to tie a bundle. That you will stow, lose the enchantment, tie bun and wear it, then get foci back out and not invoke it again.

**Comment by rpherbig** [comment]
We probably should make a more generic 'get rid of my weapon, do something, get it back' function somewhere. Parts of that logic are implemented in a few different places in `combat-trainer`...

**Comment by MahtraDR** [comment]
Closing as stale. We have several functions today that lower, then retrieve items in hand after performing an action. None of them would cover this use case, the TM focus would have to be re-invoked if it leaves the hands. Not a lot of clamour for this in the intervening 5 years.
