### ISSUE TITLE
Beckon the Naga missing prep_type: prepare in base-spells update

### ISSUE THREAD

**Issue by Maledar** [rpherbig/dr-scripts#2567]
https://pastebin.com/SMDWgTSS

Can't target Beckon the Naga, I see it has Heavy: true which it is but its just breaking

*updated title I've had trouble updating my fork to the current github apologies I did some custom editing and now omg Idk what I did lol*

**Comment by Maledar** [comment]
In the same token...cast messaging is missing I've had some trouble learning how to sync my fork back to the current github so I'll leave the cast messaging here, I'm also unsure how to list it because it seems to change with the mob

The air between you and the rock guardian distorts as if being viewed in a curved mirror.  A shimmering lesser naga lurches into visibility, tatters of pastel colors wrapped around its serpentine length like a second skin.  A sublime, sibilant melody fills the area.             |
Roundtime: 2 sec.

https://pastebin.com/jekzjNE7

**Comment by swatjester** [comment]
Any update here?

**Comment by Tarhish** [comment]
Is this `Your mind latches onto something moving just under the surface of the air` messaging that's common to all the casts?

**Comment by MahtraDR** [comment]
https://github.com/rpherbig/dr-scripts/pull/5269 should close this. @rpherbig
