### ISSUE TITLE
String proc help

### ISSUE THREAD

**Issue by Manterre** [rpherbig/dr-scripts#2573]
I was wanting to add the Shard Thief guild to the mapdb, but I believe it will need a string proc to enter it.  You need to knock, and say the password and then enter the door.  The string proc I think should work is
;e Room.current.wayto[''] = StringProc.new(“fput('knock'); fput("say hannawend"); move 'go door'”) 

but I think we need a yaml setting to pull up password and then I am not sure how to have the string proc pull the password.

**Comment by MahtraDR** [comment]
@rpherbig Can close this one.
