### ISSUE TITLE
when bolt on ground. combat-trainer tries to stow bolt instead of tend wound

### ISSUE THREAD

**Issue by halprind** [rpherbig/dr-scripts#2597]
> [combat-trainer: message: [You're solidly balanced with opponent dominating.]]
> [combat-trainer: message: * A Dragon Priest assassin chops a silver q'zhalata dagger at you.  You dodge.  ]
> [combat-trainer: message: That crossbow bolt needs to be tended to be removed.]
> [combat-trainer: checked against [/You pick up/i, /You get/i, /You need a free hand/i, /There isn't any more room/i, /You just can't/i, /push you over the item limit/i, /You stop as you realize the .* is not yours/i, /Stow what/i, /already in your inventory/i, /The .* is not designed to carry anything/i]]
> [combat-trainer: for command stow bolt]

**Comment by wstampley** [comment]
@KatoakDR - Didn't you recently fix this?
