### ISSUE TITLE
Rename .yml files to .yaml

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#2604]
Dependency on start up can scan for `.yml` files and rename them to `.yaml`

**Comment by rpherbig** [comment]
@rcuhljr did you tell him to file this issue?

**Comment by jandersson** [comment]
`>.>`
`<.<`

**Comment by jandersson** [comment]
¯\_(ツ)_/¯

**Comment by rcuhljr** [comment]
I swapped the name order since I was making an off the cuff suggestion, clearly the renaming should go the other way.

**Comment by rcuhljr** [comment]
No wait I had the order right, why was this closed?

**Comment by jandersson** [comment]
I thought there was a lack of interest - I suppose I should have asked first

**Comment by jandersson** [comment]
Should dependency handle this automatically or would it be better to have something like the validate script prompt you if you want to rename the files.

**Comment by rcuhljr** [comment]
validate printing a warning on any miss named files is probably a fine start. I don't know about the interest level but it's an improvement that should be made at some point, no reason not to have an issue tracking it.

**Comment by MahtraDR** [comment]
@rpherbig Sometime in the last 3 years, yaml became the default. Shall we close this?
