### ISSUE TITLE
Use secondary (backup) weapons if moon not available for moonblade

### ISSUE THREAD

**Issue by ghost** [rpherbig/dr-scripts#2613]
There exists functionality for the summoning and shaping of moonblades already. I can add the right summoned weapons verbiage to my YAML and begin hunting with them. However...then the moons go down. Uh oh, stuck unable to fight with weapons. The key piece that is missing right now, is having the conditional check.

- Are there summoned moonblade weapons setup in the YAML?
- Are there moons out?
- Yay! Cast and use moonblades.
- Moonblade poofed (expited), cast another one!

All of the above is already covered. What we also then need is:

- Uh oh, moons went away!
- Default to backup weapon training setup in the YAML
- Train with normal weapons
- Moon rises
- Swap back to summoned weapons.

User Story:
As a moonmage I would like to draw out my bastard sword when moons aren't out, sheath it and cast moonblade when they are out. When the moons go back down, I draw my bastard sword again.

**Comment by BastionWT** [comment]
Would still love for this to happen, if possible.

**Comment by MahtraDR** [comment]
@KatoakDR This seems like something you'd enjoy :)

**Comment by MahtraDR** [comment]
Since we can now define hunts with and without moons, this is redundant.
