### ISSUE TITLE
Weaponized IZ support

### ISSUE THREAD

**Issue by ghost** [rpherbig/dr-scripts#2624]
Right now IZ (Empath cyclic) is supported...kinda. Having it setup in your YAML will successfully cast the spell, but nothing else then happens. This is because touch <target> is required to actively deal damage to creatures. This could be accomplished with buff_nonspells: touch: 30, except it requires `<target>`.

Use case: I'd like to be able to cast IZ (can currently), and then on a frequent basis touch the target that I am currently facing (can't currently). This takes mana (the cyclic cost is consumed each touch), so only doing so when mana is above threshold values.

cast
```
You gesture.
Your empathic shock makes the spell slightly more pliable.
Monstrous feelings of cold-bloodedness uncoil from within, taking root in places where your empathy has receded. Their physical echoes are concentrated most in your hands, and you immediately recognize the onset of an abnormal arthritis.
```

Touch Messages (there look to be 7 of these):

touch goblin
```
Honing the essence of pain on your fingertips, you reach out to touch a striped origami goblin.

You insouciantly swing a backhand at a striped origami goblin.

You lean forward, your arm outstretched at a white origami mouse for a touch.

Feeling implacable, you lunge with an extended hand toward a white origami mouse.

You stab your curled ashen fingers at a black origami grasshopper.

You extend a pain-laden hand toward a striped origami grasshopper.

You reach out toward a striped origami grasshopper with the back of your hand in a gesture of false sympathy.
```

**Comment by BastionWT** [comment]
Would still love this, if possible.

**Comment by rpherbig** [comment]
Is the purpose of this simply doing damage, or training a skill?

**Comment by BastionWT** [comment]
Training TM as the primary intent, @rpherbig. Also dealing damage.

**Comment by rpherbig** [comment]
If the goal is training TM, someone could (fairly) easily add a new `training_abilities` that touches if your TM isn't mindlocked.

**Comment by BastionWT** [comment]
Specifically it would have to touch the correct type of creature. TOUCH doesn't work. TOUCH GOBLIN does.

**Comment by MahtraDR** [comment]
@rpherbig can close this. 

```yaml
attack_overrides:
  Empathy: touch```

```yaml
weapon_training:
  Empathy: ''
```

```yaml
  iz: &iz
    Icutu Zaharenela:
      prep: prepare
      mana: 15
      recast: 1
      cyclic: true```

**Comment by MahtraDR** [comment]
I'll also write a brief wiki article on this if we don't have one.
