### ISSUE TITLE
Theurgy in Hib

### ISSUE THREAD

**Issue by tulanegator** [rpherbig/dr-scripts#2641]
Noticed two issues running theurgy with hometown Hib. I may look into fixing these later but I'm at work and want to document them...

**First Issue**

> [theurgy]>count my first oil in my thigh pouch
> There's only one part left of the holy oil.
> >
> [theurgy: *** No match was found after 15 seconds, dumping info]
> [theurgy: messages seen length: 8]
> [theurgy: message: Persistence of Mana  (OM)]
> [theurgy: message: Benediction  (OM)]
> [theurgy: message: Glythtide's Gift  (OM)]
> [theurgy: message: Major Physical Protection  (OM)]
> [theurgy: message: Murrula's Flames  (OM)]
> [theurgy: message: Osrel Meraud  (97%)]
> [theurgy: message:  * Hodierna's Fist Kaelie has joined the adventure after escaping another!]
> [theurgy: message: There's only one part left of the holy oil.]
> [theurgy: checked against [/I could not find what you were referring to./i, /tell you much of anything./i, /and see there (?:is|are) (.+) left\./, /There (?:is|are) (?:only )?(.+) parts? left/]]
> [theurgy: for command count my first oil in my thigh pouch]
> [theurgy]>count my second oil in my thigh pouch
> >
> I could not find what you were referring to.

**Second Issue**

> [New Lamps for Gold]
> Hibarnhvidar's lamp and lantern shop is either cozy or cramped, depending on one's outlook.  Three or four customers would crowd this tiny establishment, but almost all of the wares are within arm's length, except for the flammable stuff.  That sits behind a high counter out of reach of the public.  You also see a box with brass lamps in it, a sturdy counter with a few things on it, a shelf for bronze lamps with a few things on it and a wicker chest full of bottles of lamp oil.
> Obvious exits: out.
> Room Number: 11609
> >
> [go2: travel time: 0:00:01]
> --- Lich: go2 has exited.
> [theurgy]>buy oil
> That oil is not for sale.
> (If you're trying to buy another one, you may need to be more specific, as in BUY GLEAMING SHORTSWORD ON TABLE.)
> [theurgy: *** No match was found after 15 seconds, dumping info]
> [theurgy: messages seen length: 30]
> [theurgy: message: Persistence of Mana  (OM)]
> [theurgy: message: Benediction  (OM)]
> [theurgy: message: Glythtide's Gift  (OM)]
> [theurgy: message: Major Physical Protection  (OM)]
> [theurgy: message: Murrula's Flames  (OM)]
> [theurgy: message: Osrel Meraud  (97%)]
> [theurgy: message: (If you're trying to buy another one, you may need to be more specific, as in BUY GLEAMING SHORTSWORD ON TABLE.)]
> [theurgy: message: That oil is not for sale.]
> [theurgy: checked against [/prepared to offer it to you for (.*) (?:kronar|lirum|dokora)s?/, /Let me but ask the humble sum of (.*) coins/, /for a (?:mere )?(.*) (?:kronar|lirum|dokora)s?/, /I can let that go for...(.*) (?:kronar|lirum|dokora)s?/, /cost you (?:just )?(.*) (?:kronar|lirum|dokora)s?/, /it may be yours for just (.*) (?:kronar|lirum|dokora)s?/, /I'll give that to you for (.*) (?:kronar|lirum|dokora)s?/, /I ask that you give (.*) copper (?:kronar|lirum|dokora)s?/, /it'll be (.*) (?:kronar|lirum|dokora)s?/, /the price of (.*) coins? is all I ask/, /tis only (.*) (?:kronar|lirum|dokora)s?/, /That will be (.*) copper (?:kronar|lirum|dokora)s? please/, /to you for (.*) (?:kronar|lirum|dokora)s?/, /You decide to purchase/i, /Buy what/i]]
> [theurgy: for command buy oil]
> [theurgy]>research status
> You're not researching anything!
> >
> [theurgy]>release mana
> You aren't harnessing any mana.
> >
> [theurgy]>prep bless 1
> You begin chanting a psalm to invoke the Bless spell.
> >
> [theurgy]>cast my oil
> You gesture at a flask of oil.
> A brilliant silver glow surrounds a flask of oil for a few moments, but nothing else seems to happen.
> >
> [theurgy]>get oil from my thigh pouch
> You get a bottle of holy oil from inside your thigh pouch.
> >
> [theurgy]>combine oil with oil
> >
> You must be holding both substances to combine them.  For more information, see HELP VERB COMBINE.
> >
> [theurgy]>put oil in my thigh pouch
> You put your oil in your thigh pouch.

The purchase works when you "order oil in chest"

**Comment by MahtraDR** [comment]
@rpherbig This looks resolved by the attached commit from 2018.
