### ISSUE TITLE
Outfitting assistance - rucksacks

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#2643]
;sew stow sewing 3 "cloth rucksack" rucksack silk only makes the page 23 small cloth rucksack. I can't get it to make page 26. Some assistance to automate making Page 26 rucksacks please with straps?

Page 23: a small cloth rucksack                  
Page 26: a cloth rucksack

**Comment by jandersson** [comment]
try typing the whole thing out, `a cloth rucksack`

**Comment by Aurayn** [comment]
God call
