### ISSUE TITLE
PROTECT COIN for sell_loot_money_on_hand:

### ISSUE THREAD

**Issue by Traik404** [rpherbig/dr-scripts#2647]
When running a training-manager that takes a ferry with regularity, the sell_loot_money_on_hand: line works perfectly to keep ferry money on hand.

As the bank stop is right after the hunt and 10-30 minutes before the next hunt, I worry about the ferry money being stolen as I stack rocks and read books.

Ideally whatever it is you withdraw from the bank would be appended onto a protect coin command.

  PROTECT COIN [#] [TYPE] [KRONAR|LIRUM|DOKORA]
    PROTECT COIN 3 GOLD DOKORAS
    PROTECT COIN 1 PLATINUM KRONARS
    PROTECT COIN 1 SIL LIR

**Comment by Sarvatt** [comment]
how many coins can you protect?

**Comment by Sarvatt** [comment]
and what happens if you try to protect more than you can? Asking because it might need a lot more logic to determine this, or it might just protect the max you can if you try to protect more.

**Comment by Traik404** [comment]
>protect coin 8 silver kronar
You can't protect that many coins!
>protect coin 7 silver kronar
You don't have that many silver Kronars!

It is more for paladins than non I believe.

**Comment by jayRyan24** [comment]
Is this really an issue?

**Comment by Traik404** [comment]
No, it's a suggestion.

**Comment by MahtraDR** [comment]
Closing as wontfix.
