### ISSUE TITLE
Track if a character is f2p or not.

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#2653]
I was thinking this could be done at login with drinfomon, something like doing an inv check and matching /[13]00 items/ or teach open and matching You don't have access to teaching classes because you don't have a subscription. The inv check might be preferred because it's actually useful info to have spammed at login.

A few uses would be automatically using the xala climb_practice target if you are f2p instead of being sent to undergondola at 540 ranks, and not taking the trails to other provinces in ;scouting

**Comment by KatoakDR** [comment]
`drinfomon` now identifies your account subscription in `UserVars.subscription`, thanks
