### ISSUE TITLE
Dropped items on disconnect/disarm/lag/etc

### ISSUE THREAD

**Issue by Traik404** [rpherbig/dr-scripts#2663]
You retreat from combat.
>
You notice a haon-hafted hunting spear adorned with parrot feathers at your feet, and do not wish to leave it behind.

If the string between You notice a -- and --at your feet, and do not wish to leave it behind., matches an item in your yaml, can you pick it up and stow it?

**Comment by wstampley** [comment]
The `;afk` script will pick up items when you attempt to leave them behind, and many people run it as an autostart. @rpherbig - this can probably be closed.
