### ISSUE TITLE
healme should pause certain crossing-training scripts

### ISSUE THREAD

**Issue by Traik404** [rpherbig/dr-scripts#2664]
Please have healme pause crossing-training scripts like mech-lore, first-aid (reading), outdoorsman rock kicking, etc. 

Also please let healme always keep Heal up now (the new one that works like regenerate) as it spot heals with HW/HS. The string for Heal fading should be 'You feel the warmth in your flesh gradually subside.'

**Comment by MahtraDR** [comment]
Closing as stale. We don't recommend folks use crossing trainer anymore.
