### ISSUE TITLE
sew - yarn still in right hand after buying/combining

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#267]
It seems yarn might have a cap of around 300 yards?   When the yarn was counted, there were 103 yards, the script then bought 100 yards and combined them twice.  When the knitting started, the needles were in my left hand and there was yarn still in my right hand.   Simple solution might be to "stow my yarn" twice.

http://pastebin.com/tve89pJT

**Comment by rcuhljr** [comment]
timing issue, fix pushed, need a better long term fix using bput
