### ISSUE TITLE
Add magic training support during crafting.

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#2690]
It would be nice to train magic in the background while crafting, but I'm not sure how to hook it in in a generic way since it would have to be duplicated across so many scripts. Any ideas?

**Comment by BinuDR** [comment]
I used to do magical research during forging.  180 seconds worth of it, started right after studying the book.

**Comment by Sarvatt** [comment]
the framework for this is set up and it will be pushed in a few days once common-arcana propagates
