### ISSUE TITLE
Crossing-Repair is missing a check for sell_loot_skip_bank

### ISSUE THREAD

**Issue by Zhennlash** [rpherbig/dr-scripts#2698]
https://github.com/rpherbig/dr-scripts/commit/de510cd128f6d04495b64c8fd47448604829460f#diff-0a4314f98139de0f9661f6ec8be1e6e1

This edit enabled deposit functionality regardless of sell_loot_skip_bank. This is problematic for those with social outrage.

**Comment by rpherbig** [comment]
@jandersson
