### ISSUE TITLE
Frivolous/fun: Siegery leveling 

### ISSUE THREAD

**Issue by ghost** [rpherbig/dr-scripts#2699]
Siegery is a fun game that requires luck and leveled up pieces to win consistently. While we can't do anything about the former, Lich is great at scripting easy, repeatable scenarios over and over again to achieve great results.

Use case: I'd like to sit my alt in a room with someone else's alt in a room and ;siegery. The script will set up the game from our individual kits (yaml for kit pieces), play the game to its conclusion, repair the kit pieces at the end, and repeat.

**Comment by rpherbig** [comment]
If you've got a log of a game being played, that will help in case someone is interested but does not have a siegery kit of their own.

**Comment by MahtraDR** [comment]
No follow up since. Closing.
