### ISSUE TITLE
Handle wield failure due to a dropped weapon

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#27]
I'm not sure *how* my bastard sword ended up on the ground, but it did...

Relevant text:
```You find it difficult to wield the sword, as it is lying at your feet!```

**Comment by rcuhljr** [comment]
[Private]-DRF:Aeoa: "I see the issue on github about dropped weapons, I've been having the same thing happen to me with a steel scimitar, the message I saw when I dropped it was [combat-setup: out of room, failed to store scimitar]"
[Private]-DRF:Aeoa: "then I dropped it"

More info.

**Comment by OdnaZvezda** [comment]
Here's a log of it happening.

You think you have your best shot possible now.
>
[combat-setup]>shoot
Your attempt is slightly hindered by your cougar-hide targe.
< Moving like a striking snake, you fire a boar-tusk arrow at a sand sprite.  A sand sprite attempts to evade, stepping partially into the shot.  The arrow lands an extremely heavy hit (9/23) that scratches the right bicep (But another battle scar for the sprite's collection!).

The boar-tusk arrow lodges itself shallowly into the sand sprite!
[You're adeptly balanced and overwhelming opponent.]
[Roundtime 1 sec.]
[combat-setup]>stow my bow
>
You feel fully rested.
>
* Attacking weakly, a sand sprite lunges a coral knife at you.  You dodge, just stepping out of harm's way.  
[You're adeptly balanced and have slight advantage.]
>
You put your bow in your black bag.
>
[combat-setup]>get my first scimitar
You get a steel scimitar from inside your black bag.
>
[combat-setup]>swap
You move a steel scimitar to your left hand.
>
[combat-setup: out of room, failed to store scimitar]
[combat-setup]>drop my scimitar
>
A sand sprite suddenly dances gracefully into view, moving around in a dizzying pattern.
>
A sand sprite gestures at you.
>
[combat-setup: out of room, failed to store ]
[combat-setup]>attack left
You drop a steel scimitar.
>
< Driving in like the irresistable force of a cyclone, you claw your fingers at a sand sprite.  A sand sprite attempts to dodge, not quite escaping the blast.  The fingers lands a good strike (3/23) that scratches it in a slash from behind, lightly stunning it.
[You're adeptly balanced and in dominating position.]
[Roundtime 2 sec.]
>
[combat-setup]>attack left
< Moving with incredible power and control, you punch your brass knuckle at a sand sprite.  A sand sprite fails to parry with a coral knife.  The knuckle lands a strong hit (6/23) that buckles the left knee for a moment with a painful frontal blow.
[You're incredibly balanced and overwhelming opponent.]
[Roundtime 2 sec.]
>
* Trying poorly, a sand sprite thrusts a coral knife at you.  You barely block with a reinforced cougar-hide targe.  
[You're adeptly balanced and opponent has slight advantage.]
>
A sand sprite gestures at you.
>
[combat-setup]>attack left
< You punch your brass knuckle at a sand sprite.  A sand sprite knocks aside little of the knuckle with a coral knife.  
[You're adeptly balanced and overwhelming opponent.]
[Roundtime 2 sec.]
>
[combat-setup]>attack left
< Driving in like an adept combatant, you gouge your fingers at a sand sprite.  A sand sprite badly fails to parry with a coral knife.  The fingers lands a good strike (3/23) that stabs the fleshy portion of the right arm.
[You're adeptly balanced and overwhelming opponent.]
[Roundtime 1 sec.]

**Comment by rcuhljr** [comment]
da3e5c280631c0b5d43149726c29b5cabaf0ff67 hoping this fixes it. Need to test.

**Comment by OdnaZvezda** [comment]
After the fix, I was able to force the drop with a bow in my right hand, moving it to my left.  Bows don't normally change hands for combat purposes though.  


[combat-setup]>shoot

Your attempt is slightly hindered by your cougar-hide targe.
< Driving in with naturally fluid movements, you fire a boar-tusk arrow at a sand sprite.  A sand sprite fails to evade, stepping partially into the shot.  The arrow lands a massive strike (11/23) that completely severs the sprite's left hamstring.

The boar-tusk arrow lodges itself deeply into the sand sprite!
A sand sprite slowly falls to the ground, moaning in despair, shuddering in pain before taking her last breath.
[You're adeptly balanced]
[Roundtime 1 sec.]
>swap
...wait 1 seconds.
>swap
>swap
You move a Nisha short bow to your left hand.
>swap
You move a Nisha short bow to your right hand.

[combat-setup]>skin

You move a Nisha short bow to your left hand.
The sprite cannot be skinned.
The sand sprite moves into a position to dodge.
* Trying inexpertly, a sand sprite feints to the side at you.  You barely block with a reinforced cougar-hide targe.  
[You're adeptly balanced and in better position.]

[combat-setup]>drop my bow


[combat-setup]>loot

You drop a Nisha short bow.
You search the sand sprite.
Lodged into it was a boar-tusk arrow and a boar-tusk arrow.
The sprite was carrying 1 copper coin, 5 bronze coins, and 1 silver coin!
You feel fully rested.
A sand sprite decays away.
* Trying weakly, a sand sprite thrusts a coral knife at you.  You evade, just stepping out of harm's way.  
[You're adeptly balanced with no advantage.]

[combat-setup]>stow arrow

You pick up a boar-tusk arrow.
You put your arrow in your black bag.

[combat-setup]>stow arrow

You pick up a boar-tusk arrow.
You put your arrow in your black bag.

[combat-setup]>stow coin

You pick up 1 silver Lirum.

**Comment by OdnaZvezda** [comment]
A swap test after the fix with my scimitar did not cause me to drop it.   I'll keep watching though.

[combat-setup]>backstab
>
A sand sprite scans the area for a moment, looking for something.
>
[combat-setup]>hide
Your scimitar is a little awkward, but usable.
You slip out of concealment and backstab a sand sprite!
< Driving in like an unbeatable force, you thrust a steel scimitar at a sand sprite.  A sand sprite fails to evade, only partially avoiding the impact.  The scimitar lands a heavy strike (7/23) that stabs deeply into the scalp, knocking it completely senseless.
[You're solidly balanced and in very strong position.]
[Roundtime 4 sec.]
>
...wait 4 seconds.
>
The sand sprite moves into a position to dodge.
>
[combat-setup]>attack
< Driving in with naturally fluid movements, you jab a steel scimitar at a sand sprite.  A sand sprite badly fails to parry with a coral knife.  The scimitar lands a light hit (1/23) to the sprite's chest.
A sand sprite slowly falls to the ground, moaning in despair, shuddering in pain before taking her last breath.
[You're nimbly balanced]
[Roundtime 2 sec.]
>
[combat-setup]>stow my scimitar
...wait 2 seconds.
>
The sand sprite moves into a position to dodge.
>swap
...wait 1 seconds.
>swap
You move a steel scimitar to your left hand.
>
[combat-setup]>stow my scimitar
* Inexpertly, a sand sprite feints low at you.  You slap away little of the knife with a polished steel parry stick.  
[You're nimbly balanced with opponent in strong position.]
>
You put your scimitar in your black bag.
>
[combat-setup]>stow my scimitar
[combat-setup]>get my first hammer
Stow what?  Type 'STOW HELP' for details.
>
You get a steel throwing hammer from inside your black bag.
>
[combat-setup]>loot
You search the sand sprite.
Lodged into it was a boar-tusk arrow and a boar-tusk arrow.
The sprite was carrying 1 copper coin, 5 bronze coins, and 1 silver coin!
>
* Moving weakly, a sand sprite feints high at you.  You dodge, barely twisting out of a tight spot.  
[You're nimbly balanced and opponent has slight advantage.]
>
* Moving poorly, a sand sprite thrusts a coral knife at you.  You evade, barely stepping to one side.  
[You're nimbly balanced with opponent in strong position.]
>
You feel fully rested.
>
The sand sprite begins to advance on you!
The sand sprite advances from nearby and is closing steadily.
>
A sand sprite gestures at you.
>
A sand sprite decays away.
>
[combat-setup]>stow arrow
You pick up a boar-tusk arrow.
You put your arrow in your black bag.
>
[combat-setup]>stow arrow
You pick up a boar-tusk arrow.
You put your arrow in your black bag.
>
[combat-setup]>stow coin
You pick up 1 silver Lirum.
>
[combat-setup]>stow coin
You pick up 5 bronze Lirums.
>
[combat-setup]>stow coin
You pick up 1 copper Lirum.
>
The sand sprite closes to melee range on you!
>
A sand sprite gestures at you.
>
* Moving poorly, a sand sprite jabs a coral knife at you.  You counter little of the knife with a steel throwing hammer.  
[You're nimbly balanced with opponent in superior position.]
>

**Comment by rcuhljr** [comment]
The bow was a skinning drop, I'll fix that as well.

**Comment by rcuhljr** [comment]
Reminder to self: Fix this by adding a skinning results array to base.yaml
hide pelt hair skin tail bone etc. so that users can add in custom skin items if they're hunting something weird.

**Comment by rpherbig** [comment]
@rcuhljr What's the status of this?

**Comment by rcuhljr** [comment]
Oh. I think my first pass fixed about 95% of the problems, but I still want to add skinning results to a base.yaml file and only drop items after skinning that are part of that array I think. Is breaking due to keeping a skinned item in hand worse then possibly dropping something that isn't a skin?

**Comment by rpherbig** [comment]
I'd consider dropping a non-skinning item the worse outcome. It's likely your weapon, which is bad news all around.

**Comment by rpherbig** [comment]
@rcuhljr Is it safe to close this?

**Comment by rpherbig** [comment]
Closing this in favor of #692
