### ISSUE TITLE
Support Reverse Putrefaction (RPU) 

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#2705]
Arisen Zombies can be buffed with the Reverse Putrefaction spell. The expiration message is `An arisen kobold zombie's motions slow, the effects of rigor mortis becoming more evident.`

Casting is `cast offense` or `cast defense`

**Comment by jandersson** [comment]
#2708

**Comment by rpherbig** [comment]
Fixed in 9c991b7672f6ac95288ab705228dc29d02eed94b (merge of #2708)
