### ISSUE TITLE
go2 issue when trying to hunt Shard Frostweavers

### ISSUE THREAD

**Issue by Amala777** [rpherbig/dr-scripts#2711]
I tried adding Shard Frostweavers to hunting base but go2 gets stuck in the first room. It is a premie area.

It is not a dark area or area that is day/night. Just a premie hunting spot. Can someone fix the mapping? It only goes to 

  #https://elanthipedia.play.net/Frostweaver                             180-260
  #snowbeast also attack here ***PREMIUM ONLY ***
  shard_frostweaver:
  - 9633
  - 9632
  - 9628
  - 9629
  - 9630
  - 9631
  - 9620 

[Dragon's Spine, Steps of Sorrow]
Crystallized rocks and frost-covered foliage glitter like diamonds in the snow, reflecting light from a thousand facets.  The brisk wind brings with it a faint pungent odor, quickly gone with its next breath of frosty air.
You also see some carved stone steps.
Obvious paths: east.

Room Number: 2913

> 
Mapped exits: climb steps

[go2]>n

> 
You can't go there.
> 
[go2: move: failed]

[go2: restarting script...]

[go2: ETA: 0:00:01 (5 rooms to move through)]

[go2]>go stone step

You whisper a command word as you step toward the stone steps.  The curtain of magic that shimmers over the entry parts, allowing you to pass through.

[Dragon's Spine, Path]
Stone steps provide entrance and exit for an icy paradise.  A faint pathway follows a ledge, snaking by caverns on one side and a steep drop-off on the other, with everything sparkling from a pristine coating of snow.
You also see a snowbeast, a frostweaver that is surrounded by a shimmering shield, a frostweaver that is surrounded by a shimmering shield and a frostweaver that is surrounded by a shimmering shield.
Obvious paths: north.

Room Number: 2913

takes me back and forth to room 2913.

**Comment by jandersson** [comment]
Its fixed, you'll want to run `;repository download-mapdb` then run `;e Map.reload` to refresh your current Map. Logging out and back in also works.

**Comment by Amala777** [comment]
thank you!!!!
