### ISSUE TITLE
workorders - shape - not enough material to start crafting

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#272]
The script completed 2 of 3 for a work order before this happened.

http://pastebin.com/JCBN09hL

**Comment by rcuhljr** [comment]
Ah, the new recipes you added are the first ones that three of them can't be crafted out of one piece of lumber, hadn't added the restock logic yet. I'll get on this.

**Comment by rpherbig** [comment]
@rcuhljr Was this fixed?

**Comment by rcuhljr** [comment]
No.

**Comment by rcuhljr** [comment]
Actually that's a lie, I finished this.
