### ISSUE TITLE
Script errors for hunting-buddy and circlecheck.

### ISSUE THREAD

**Issue by Volkak** [rpherbig/dr-scripts#2743]
Hello, i am having some error when I attempt to run hunting-buddy and circlecheck. The errors are as follows.

>--- Lich: hunting-buddy active.
--- Lich: equipmanager active.
--- Lich: equipmanager has exited.
--- Lich: error: uninitialized constant HuntingBuddy::DRC
	hunting-buddy:8:in `<class:HuntingBuddy>'
	hunting-buddy:7:in `_script'
--- Lich: hunting-buddy has exited.

>--- Lich: circlecheck active.
--- Lich: error: uninitialized constant DRStats
	circlecheck:499:in `main'
	circlecheck:626:in `_script'
--- Lich: circlecheck has exited.

Any help is greatly appreciated,

**Comment by Sarvatt** [comment]
you most likely trusted something you shouldnt have, what does ;list
trusted say?

**Comment by Volkak** [comment]
my ;list says:

>--- Lich: dependency, narost, roomnumbers
