### ISSUE TITLE
Smartlisten autostarts without populating listen_skills array

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#2749]
With smartlisten in dependency autostart, it seems to start up sometimes without populating the listen_skills array. Restarting the script fixes the problem. There might be some issue with reading from a yaml during the autostart process.

I added an echo to show if the skill is in `listen_skills` seen below:
```
Razzerfrazzer begins to lecture you on the proper usage of the Engineering skill.
To learn from him, you must LISTEN TO Razzerfrazzer.
  (LISTEN HELP for more options)
sR>
[smartlisten: Checking if I should listen to a class on Engineering]
[smartlisten: listen_skills.include?(Engineering)=false]
```

**Comment by jandersson** [comment]
For good measure, troubleshooting - Here are my autostarts:

```
R>;autostart list
--- Global autostart scripts: alias, lnet, repository (args: download-updates), dependency

--- Crannach's autostart scripts: (none)
>;e echo list_autostarts
--- Lich: exec1 active.
[exec1: ["afk", "roomnumbers", "smartlisten", "dr-autovote", "textsubs", "play", "sanowret-crystal", "status-monitor", "craft-track", "moonwatch", "jail-buddy"]]
```

**Comment by MahtraDR** [comment]
@KatoakDR is this related to our dependency collision? I think it is. If it is, this can be closed.

**Comment by KatoakDR** [comment]
> @KatoakDR is this related to our dependency collision? I think it is. If it is, this can be closed.

Agree
