### ISSUE TITLE
fix bescort moving to geni area

### ISSUE THREAD

**Issue by hwoo79** [rpherbig/dr-scripts#275]
paths in geni/leucro area don't show up unless you're a Ranger with scouting.  Currently, bescort will not move to geni if they exits aren't seen, throwing an error of `train your perception!` 

bescort should move to geni even if the exits aren't seen in the room.

**Comment by rcuhljr** [comment]
Hopefully corrected. 62105eb8864494abb9bad95d15696bf36c2fd147
