### ISSUE TITLE
Shaping and Sewing don't require work rooms

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#276]
Shaping and sewing don't need to use the work rooms, we should support doing them about town. Sewing should be a low traffic area due to cutting of fabric (which we don't support yet) dropping it to the ground.

**Comment by rpherbig** [comment]
We're seeing some of our characters getting hung up waiting on other characters to clear the work rooms.

Escalating this to the v3 milestone.

**Comment by rpherbig** [comment]
I think the `engineering_room` setting addresses this for shaping. I don't think tailoring has been fixed.
