### ISSUE TITLE
Check teaching when training alchemy or engineering in crossing-training

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#2760]
This is a user requested feature

Check teaching is already done before outfitting training, but not for alchemy or engineering. We could teach people when returning to our training room.

**Comment by Sarvatt** [comment]
it only teaches or listens if you use the local methods to craft, not workorders, and there is nothing set up for alchemy that way. I submitted a PR for engineering though.

**Comment by jandersson** [comment]
Sounds good, I'll split this into two issues for each discipline thenOn Jun 15, 2018 21:37, Robert Hooker <notifications@github.com> wrote:it only teaches or listens if you use the local methods to craft, not workorders, and there is nothing set up for alchemy that way. I submitted a PR for engineering though.
