### ISSUE TITLE
Support fletching

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#2761]
This is user requested.

Create a script that crafts arrows and bolts. 

I have been working on this. One thing I noticed is that the current `shape.lic` script does not support this area of crafting very well. The messaging is more like lockpicking where you get a success message and a following message saying that you should use a carving knife. So I think it is more straightforward to write something from scratch rather than working around how shape.lic is currently set up.

**Comment by MahtraDR** [comment]
Resolved by #5846
