### ISSUE TITLE
swappable fans

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#277]
a steel thin-bladed fan
>study fan
Studying your fan carefully, you're sure you could do the following things with it:
   OPEN, CLOSE, FLIRT, KISS, DANCE, WAVE.

Note: OPEN will swap the thin-bladed fan to make it an edged weapon, CLOSE will change it to blunt the razor-sharp ends.

>open fan
With a practiced flick of your wrist, you snap open your thin-bladed fan to expose the sharpened steel edges at the end of the blades.
You fiercely switch your grip so that your fan can be used as a light edged weapon.
>close fan
With a practiced flick of your wrist, you snap your thin-bladed fan closed, savoring the weight of the weapon in your fist.
You switch your fan so that you can use it as a short staff weapon.

**Comment by rcuhljr** [comment]
Need the message for trying to close/open while it's already in that state.
