### ISSUE TITLE
crossing-training stealing no longer moving on after finding closed shops

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#279]
Stealing used to move on to the next shop after a couple attempts.

You go northeast.
[Arthe Dale, Glaysker Lane - 1080]
As you pause for a moment on the cobblestoned lane, your eye is caught by the entrance to a squat stone building with a blue awning.  A dazzling silver sword has been securely mounted to the arched entryway above a small engraved plaque.  
[go2]>go shop
Obvious paths: northeast, southwest.
>
[Assuming you mean an arched entryway.]

The door is locked up tightly for the night.
>
[go2: move: no recognized response in 30 seconds.  giving up.]
[go2: restarting script...]
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>go shop
[Assuming you mean an arched entryway.]

The door is locked up tightly for the night.
>
[go2: move: no recognized response in 30 seconds.  giving up.]
[go2: restarting script...]
>
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>go shop
[Assuming you mean an arched entryway.]

The door is locked up tightly for the night.
>
--- Lich: 'go2' has been stopped by crossing-training.
--- Lich: go2 has exited.
[crossing-training]>retreat
You are already as far away as you can get!
>
--- Lich: go2 active.
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>go shop
[Assuming you mean an arched entryway.]

The door is locked up tightly for the night.
>
[go2: move: no recognized response in 30 seconds.  giving up.]
[go2: restarting script...]
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>go shop
[Assuming you mean an arched entryway.]

The door is locked up tightly for the night.
>
[go2: move: no recognized response in 30 seconds.  giving up.]
[go2: restarting script...]
>
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>go shop
[Assuming you mean an arched entryway.]

The door is locked up tightly for the night.
>
--- Lich: 'go2' has been stopped by crossing-training.
--- Lich: go2 has exited.
>
[crossing-training]>retreat
You are already as far away as you can get!
>
--- Lich: go2 active.
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>go shop
[Assuming you mean an arched entryway.]

The door is locked up tightly for the night.
>
[go2: move: no recognized response in 30 seconds.  giving up.]
[go2: restarting script...]
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>go shop
[Assuming you mean an arched entryway.]

The door is locked up tightly for the night.
>
[go2: move: no recognized response in 30 seconds.  giving up.]
[go2: restarting script...]
>
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>go shop
[Assuming you mean an arched entryway.]

The door is locked up tightly for the night.
>
--- Lich: 'go2' has been stopped by crossing-training.
--- Lich: go2 has exited.
[crossing-training]>retreat
You are already as far away as you can get!
>
--- Lich: go2 active.
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>go shop
[Assuming you mean an arched entryway.]

The door is locked up tightly for the night.
>time
It has been 419 years, 70 days since the Victory of Lanival the Redeemer.
It is the 2nd month of Ka'len the Sea Drake in the year of the Crystal Snow Hare.
It is currently spring and it is evening.
You think it's 3 roisaen after the Anlas of Revelfae.
>
[go2: move: no recognized response in 30 seconds.  giving up.]
[go2: restarting script...]
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>go shop
[Assuming you mean an arched entryway.]

The door is locked up tightly for the night.
>
[go2: move: no recognized response in 30 seconds.  giving up.]
[go2: restarting script...]
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>go shop
[Assuming you mean an arched entryway.]

The door is locked up tightly for the night.
>
--- Lich: 'go2' has been stopped by crossing-training.
--- Lich: go2 has exited.
[crossing-training]>retreat
You are already as far away as you can get!
>
--- Lich: go2 active.
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>go shop
[Assuming you mean an arched entryway.]

The door is locked up tightly for the night.
>

**Comment by rcuhljr** [comment]
I put in a fix, it's kind of a problem in that go2 is restarting itself instead of quitting. I pushed in a fix.
