### ISSUE TITLE
go2 list seems to be broken

### ISSUE THREAD

**Issue by kgargano** [rpherbig/dr-scripts#2790]
> ,go2 list

--- Lich: go2 active.

--- Lich: error: comparison of Array with Array failed
	go2:316:in `sort'
	go2:316:in `script'

--- Lich: go2 has exited.

**Comment by jandersson** [comment]
Any chance you added a target that wasn't a number? go2 is not very good at error checking when adding a custom location, ive broken this myself by adding nil.

**Comment by kgargano** [comment]
I will check.  Where is the data stored? I don't see it in vars list

**Comment by Sarvatt** [comment]
its stored in data/lich.db3, you can delete that to "fix" it but you will lose all settings stored in it like autostarts and saved go2 stuff. if you can't remember what the last custom target you added was so that you can delete it that may be your only option.

**Comment by kgargano** [comment]
What format is db3? I could write a small script to retrieve the values...

**Comment by jandersson** [comment]
It's an sqlite3 database. Write some SQL or dig through it with a database management toolOn Jun 24, 2018 15:05, Keith Gargano <notifications@github.com> wrote:What format is db3? I could write a small script to retrieve the values...

**Comment by kgargano** [comment]
Ah . it unfortunately stores the data as a blob.  I'll just delete it and
start over
