### ISSUE TITLE
Rub verb intercepted by parser

### ISSUE THREAD

**Issue by kgargano** [rpherbig/dr-scripts#2802]
https://github.com/rpherbig/dr-scripts/blob/911fb115a5199fda62a8a66917dddc385c70dfe7/shape.lic#L124

rub my hairpin with my rasp

You rub My[blahblah].

change  it to 

scrape my {item} with my rasp and it'll avoid the parser issue.

**Comment by Sarvatt** [comment]
this can be closed, fixed by https://github.com/rpherbig/dr-scripts/commit/ec1cd6eae1bbbc2c877ab46500ed59170eeec1bd
