### ISSUE TITLE
Training-Manager (or BUFF/Attunement) tries to harness mana in the empath room and gets stuck

### ISSUE THREAD

**Issue by Tyrranny** [rpherbig/dr-scripts#2820]
It gets in an endless loop alot in Dokt's room, because it cannot harness mana in there. See copied text below.

[safe-room]>stand
You stand back up.
>
--- Lich: safe-room has exited.
[hunting-buddy: ***STATUS*** EXECUTE attunement]
--- Lich: attunement active.
[attunement]>harness 10
**Something in the area is interfering with your attempt to harness.**
>
[attunement: *** No match was found after 15 seconds, dumping info]
[attunement: messages seen length: 19]
[attunement: message: Major Physical Protection  (3 roisaen)]
[attunement: message: Manifest Force  (9 roisaen)]
[attunement: message: Persistence of Mana  (OM)]
[attunement: message: Osrel Meraud  (88%)]
[attunement: message: Bless  (1 roisan)]
[attunement: message: Auspice  (21 roisaen)]
[attunement: message: Minor Physical Protection  (19 roisaen)]
[attunement: message: Centering  (10 roisaen)]
[attunement: message: Sanctify Pattern  (16 roisaen)]
[attunement: message: Major Physical Protection  (3 roisaen)]
[attunement: message: Manifest Force  (9 roisaen)]
[attunement: message: Persistence of Mana  (OM)]
[attunement: message: Osrel Meraud  (88%)]
[attunement: message: Bless  (1 roisan)]
[attunement: message: Auspice  (21 roisaen)]
[attunement: message: Minor Physical Protection  (19 roisaen)]
[attunement: message: Centering  (10 roisaen)]
[attunement: message: Sanctify Pattern  (16 roisaen)]
[attunement: message: Something in the area is interfering with your attempt to harness.]
[attunement: checked against [/You tap into/i, /Strain though you may/i]]
[attunement: for command harness 10]
[attunement]>infuse om 10
You have no harnessed mana to infuse.
>
[attunement]>harness 10
**Something in the area is interfering with your attempt to harness.**

**Comment by MahtraDR** [comment]
Closing as wontfix.
