### ISSUE TITLE
Workorders should support repairing outfitting tools that aren't beltworn

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#2821]
I noticed that `;workorders tailoring repair` will only repair knitting tools or anything under `outfitting_belt`...
We should add in a setting for `outfitting_tools` so these can be repaired:

```yaml
outfitting_tools:   
- knitting needles  
- sewing needles    
- awl               
- scissors          
- stamp             
- hide scraper      
- slickstone        
- yardstick         
```

**Comment by Sarvatt** [comment]
oh good call, I just ran into this problem also
