### ISSUE TITLE
backstab range check no longer valid, results in error if not in melee

### ISSUE THREAD

**Issue by BastionWT** [rpherbig/dr-scripts#2848]
[combat-trainer]>backstab
Your blade is a little awkward, but usable.
It would help if you were closer to the Xala'shar thrall.
>
Appearing to have lost sight of its target, a hulking Xala'shar thrall stops advancing.
>
A hulking Xala'shar thrall's battered corpse slowly sinks into the ground with a barely audible hiss, leaving a sparse pile of possessions in its wake.
>
The Xala'shar thrall searches around for a moment.
A hulking Xala'shar thrall has spotted you!
The Xala'shar thrall discovers you, ruining your hiding place!
>
You feel like your powerful presence has gotten the better of a hulking Xala'shar thrall.
You feel like your powerful presence has gotten the better of a hulking Xala'shar magus.
You feel like your powerful presence has gotten the better of a hulking Xala'shar thrall.
>
The Xala'shar thrall begins to advance on you!
The Xala'shar thrall advances from nearby and is closing steadily.
>
The Xala'shar magus closes to pole weapon range on you!
>
A hulking Xala'shar thrall strolls into view with a nervous gait, scanning the area with wide eyes.
>
The Xala'shar thrall closes to melee range on you!
>
[hunting-buddy: ***STATUS*** 22 minutes of hunting remaining or waiting on Stealth, Backstab]
A hulking Xala'shar magus appears confused.
>
The Xala'shar thrall begins to advance on you!
The Xala'shar thrall is still a distance away from you and is closing steadily.
>
The Xala'shar magus closes to melee range on you!
>
Focusing on the dark well at your core, you feel yourself become submerged in the rise and spill of silence.
>
Appearing to have lost sight of its target, a hulking Xala'shar thrall stops advancing.
>
The Xala'shar thrall searches around for a moment.
A hulking Xala'shar thrall has spotted you!
The Xala'shar thrall discovers you, ruining your hiding place!
>
[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 180]
[combat-trainer: message: The Xala'shar thrall discovers you, ruining your hiding place!]
[combat-trainer: message: A hulking Xala'shar thrall has spotted you!]
[combat-trainer: message: The Xala'shar thrall searches around for a moment.]
[combat-trainer: message: Appearing to have lost sight of its target, a hulking Xala'shar thrall stops advancing.]
[combat-trainer: message:  Khri Elusion  (25 roisaen)]
[combat-trainer: message:  Khri Guile  (3 roisaen)]
[combat-trainer: message:  Khri Strike  (25 roisaen)]
[combat-trainer: message:  Khri Prowess  (3 roisaen)]
[combat-trainer: message:  Khri Darken  (30 roisaen)]
[combat-trainer: message:  Khri Silence  (10 roisaen)]
[combat-trainer: message:  Khri Avoidance  (25 roisaen)]
[combat-trainer: message:  Khri Plunder  (26 roisaen)]
[combat-trainer: message: Focusing on the dark well at your core, you feel yourself become submerged in the rise and spill of silence.]
[combat-trainer: message: The Xala'shar magus closes to melee range on you!]
[combat-trainer: message: The Xala'shar thrall is still a distance away from you and is closing steadily.]
[combat-trainer: message: The Xala'shar thrall begins to advance on you!]
[combat-trainer: message: A hulking Xala'shar magus appears confused.]
[combat-trainer: message: The Xala'shar thrall closes to melee range on you!]
[combat-trainer: message: A hulking Xala'shar thrall strolls into view with a nervous gait, scanning the area with wide eyes.]
[combat-trainer: message: The Xala'shar magus closes to pole weapon range on you!]
[combat-trainer: message:  Khri Elusion  (25 roisaen)]
[combat-trainer: message:  Khri Guile  (3 roisaen)]
[combat-trainer: message:  Khri Strike  (25 roisaen)]
[combat-trainer: message:  Khri Prowess  (3 roisaen)]
[combat-trainer: message:  Khri Darken  (31 roisaen)]
[combat-trainer: message:  Khri Silence  (11 roisaen)]
[combat-trainer: message:  Khri Avoidance  (25 roisaen)]
[combat-trainer: message:  Khri Plunder  (26 roisaen)]
[combat-trainer: message: The Xala'shar thrall advances from nearby and is closing steadily.]
[combat-trainer: message: The Xala'shar thrall begins to advance on you!]
[combat-trainer: message: You feel like your powerful presence has gotten the better of a hulking Xala'shar thrall.]
[combat-trainer: message: You feel like your powerful presence has gotten the better of a hulking Xala'shar magus.]
[combat-trainer: message: You feel like your powerful presence has gotten the better of a hulking Xala'shar thrall.]
[combat-trainer: message:     None]
[combat-trainer: message: Staff On Duty:]
[combat-trainer: message: Active Mentors: 1]
[combat-trainer: message: Online Players: 539]
[combat-trainer: message: Raptorr           Odemis            Pfanston          ]
[combat-trainer: message: Lila              Coeur             Dhalinar          Khaytaiths]
[combat-trainer: message: Urlo              Viqtiln           Wuxit             Kaeta]
[combat-trainer: message: Yaheh             Tikis             Mlos              Oqus]
[combat-trainer: message: Dewrabl           Felicini          Glavt             Silenzio]
[combat-trainer: message: Majicor           Crobin            Nylhhsha          Mairon]
[combat-trainer: message: Askanda           Jondac            Pormethius        Zurial]
[combat-trainer: message: Riftal            Yukionna          Toefurr           Hitchock]
[combat-trainer: message: Asterid           Flawgic           Syphaer           Snowpanther]
[combat-trainer: message: Halius            Mistrya           Lumens            Keladra]
[combat-trainer: message: Fjalar            Zoi               Ikrin             Elucidator]
[combat-trainer: message: Vieira            Perune            Elanterar         Zevenz]
[combat-trainer: message: Douken            Ydian             Salmonies         Onrown]
[combat-trainer: message: Geriscus          Clairsten         Zerang            Vrallux]
[combat-trainer: message: Daawnn            Vladmirr          Reverence         Kyura]
[combat-trainer: message: Aloriana          Xixist            Shohanna          Lilliana]
[combat-trainer: message: Dsai              Aerthes           Simas             Vyraen]
[combat-trainer: message: Maltaiche         Aiuti             Madishaed         Zucco]
[combat-trainer: message: Elvault           Pazmoa            Exoduss           Adeleena]
[combat-trainer: message: Muleie            Mulder            Brennarose        Elfverhan]
[combat-trainer: message: Myzt              Blucifer          Tirost            Kimeryn]
[combat-trainer: message: Wilhellm          Garsteaode        Kalevah           Geezarcia]
[combat-trainer: message: Heartsfyre        Shughai           Cayra             Nohrin]
[combat-trainer: message: Avareyna          Sepharus          Noopin            Evro]
[combat-trainer: message: Liftar            Merrila           Acronyx           Devish]
[combat-trainer: message: Tamarina          Rzin              Deshane           Ilwyn]
[combat-trainer: message: Hoshino           Bejah             Vykanthiss        Slaz]
[combat-trainer: message: Maghoon           Gniloi            Vyrric            Juravial]
[combat-trainer: message: Aylay             Kacutt            Aharilyn          Ataelos]
[combat-trainer: message: Ambaldo           Kingdok           Teopalpe          Sazerdag]
[combat-trainer: message: Pseeif            Roggyrle          Vitiosus          Kammae]
[combat-trainer: message: Thomoson          Khohan            Oogamooga         Cidolf]
[combat-trainer: message: Zakutin           Nulak             Micvein           Telghazal]
[combat-trainer: message: Aluren            Noct              Syival            Pormithius]
[combat-trainer: message: Phavyn            Mistified         Whagone           Italshan]
[combat-trainer: message: Thife             Blackwater        Wenwick           Alzbar]
[combat-trainer: message: Cuttlefish        Sarvatt           Tyx               Safe]
[combat-trainer: message: Drefg             Imvenko           Mithandres        Scaley]
[combat-trainer: message: Fahijeck          Tvann             Arki              Lysalfa]
[combat-trainer: message: Euph              Ulgrim            Navoah            Inkin]
[combat-trainer: message: Kargarth          Shidu             Dakre             Yraggahh]
[combat-trainer: message: Gily              Serature          Mondmorder        Atee]
[combat-trainer: message: Rajiruji          Daevin            Annakinksy        Kaldean]
[combat-trainer: message: Jaged             Shigalyev         Anrelle           Gooseberry]
[combat-trainer: message: Grimmjowl         Bukuma            Nolbert           Zesoma]
[combat-trainer: message: Vune              Elyssari          Hiidie            Gratio]
[combat-trainer: message: Zhaeun            Rkull             Acharak           Irithwynn]
[combat-trainer: message: Aszen             Kehema            Seldaren          Aedarin]
[combat-trainer: message: Yoldin            Lokard            Ysei              Ruven]
[combat-trainer: message: Calise            Zehira            Xif               Zinsbog]
[combat-trainer: message: Eriin             Slobbidetr        Bithalia          Djordje]
[combat-trainer: message: Myddnite          Ronicoregest      Zeqwery           Rogure]
[combat-trainer: message: Kenpatchi         Mirdon            Karthor           Zharx]
[combat-trainer: message: Kalleis           Trexi             Nefarious         Galrim]
[combat-trainer: message: Lostos            Everics           Benceman          Yvela]
[combat-trainer: message: Tebaud            Missah            Rekon             Gabellia]
[combat-trainer: message: Adamaxis          Gorteous          Annari            Rikkon]
[combat-trainer: message: Sophrona          Enlar             Nymri             Lnedrich]
[combat-trainer: message: Melomina          Kaltoran          Jacwyn            Vadok]
[combat-trainer: message: Alenwi            Dchoo             Fidon             Gendrearic]
[combat-trainer: message: Schase            Dondaldinho       Icotrop           Askyia]
[combat-trainer: message: Astridattar       Schimmelpeninck   Khoba             Jonrakk]
[combat-trainer: message: Danait            Vhurtz            Berney            Tuchie]
[combat-trainer: message: Mircha            Isaias            Lindale           Japhrimel]
[combat-trainer: message: Kyver             Kasrakin          Agalea            Reshvor]
[combat-trainer: message: Ossam             Taak              Coane             Landee]
[combat-trainer: message: Vallier           Baldrak           Woldo             Frenton]
[combat-trainer: message: Lashansa          Meigs             Plix              Mikian]
[combat-trainer: message: Latagi            Ziuorjorp         Aningan           Kurtus]
[combat-trainer: message: Zerzio            Fizox             Margerie          Carlae]
[combat-trainer: message: Zharen            Rhystal           Grarr             Flastae]
[combat-trainer: message: Ardwinn           Impulse           Maintain          Estrala]
[combat-trainer: message: Idania            Bizi              Itto              Parned]
[combat-trainer: message: Zeeve             Erixx             Natarian          Yuoree]
[combat-trainer: message: Jadrax            Vaebrek           Rhadyn            Cattii]
[combat-trainer: message: Thaulos           Telutci           Matamoras         Gram]
[combat-trainer: message: Namirah           Nazrael           Thorn             Shandos]
[combat-trainer: message: Aervyn            Chuno             Buuwl             Aristokrat]
[combat-trainer: message: Remigius          Deylen            Serakk            Mazrian]
[combat-trainer: message: Morpheosis        Baelgrum          Laanis            Etry]
[combat-trainer: message: Inoo              Elphierose        Atanamir          Nasrid]
[combat-trainer: message: Nekhebett         Charlize          Orphne            Jorenn]
[combat-trainer: message: Rayyoln           Tirsten           Kehlbins          Arck]
[combat-trainer: message: Shinikaze         Voranos           Ithilis           Gigondas]
[combat-trainer: message: Yudai             Anotsu            Aerbax            Marddl]
[combat-trainer: message: Erindar           Nsar              Chummy            Theophilus]
[combat-trainer: message: Falein            Hirun             Rensau            Caraleene]
[combat-trainer: message: Keriss            Falconhoof        Saraesh           Etoyaloma]
[combat-trainer: message: Blaytox           Dyago             Moza              Dansky]
[combat-trainer: message: Aumaru            Rastal            Jezzail           Rhamer]
[combat-trainer: message: Kithylan          Hoger             Frankhee          Aoirc]
[combat-trainer: message: Solclaim          Zensanium         Klurn             Maizze]
[combat-trainer: message: Erreth            Ambrosya          Antarus           Gallendale]
[combat-trainer: message: Mahalae           Martel            Frostrune         Curufin]
[combat-trainer: message: Suntori           Drenzile          Banner            Henil]
[combat-trainer: message: Mikirali          Khaelyn           Bezar             Kelneth]
[combat-trainer: message: Tolerated         Mespher           Belazeru          Yndass]
[combat-trainer: message: Schriel           Etal              Eitheus           Ajaxrin]
[combat-trainer: message: Revelator         Heji              Zavemgag          Valsynia]
[combat-trainer: message: Erzul             Zizzek            Leustyin          Twiddlethumbs]
[combat-trainer: message: Szoengi           Hhshikath         Shaeun            Ledia]
[combat-trainer: message: Samech            Mouintain         Rigek             Ophinicus]
[combat-trainer: message: Neurine           Linal             Collain           Abee]
[combat-trainer: message: Aarroneous        Leontiogair       Herodo            Arihana]
[combat-trainer: message: Treahead          Dartellum         Deimeter          Booba]
[combat-trainer: message: Anshelm           Haruhiko          Viansome          Penethol]
[combat-trainer: message: Kyenchiro         Elnoer            Christus          Qiyan]
[combat-trainer: message: Eridu             Schieffelin       Moriora           Kvatos]
[combat-trainer: message: Eathsus           Onock             Binu              Eyndalron]
[combat-trainer: message: Ashalf            Bhaalgorn         Stonemoe          Myeople]
[combat-trainer: message: Ceindrech         Veleren           Serafine          Hotoke]
[combat-trainer: message: Lorwryn           Nogri             Gavius            Zsijn]
[combat-trainer: message: Relenva           Rhakim            Hodoor            Alucios]
[combat-trainer: message: Sylanvei          Prestley          Divy              Zoci]
[combat-trainer: message: Darkrum           Sustain           Brahmer           Wocmok]
[combat-trainer: message: Kuklin            Shikkan           Yggrald           Xargrave]
[combat-trainer: message: Koujia            Samyl             Ashev             Akris]
[combat-trainer: message: Constantinne      Travic            Nanakii           Kaileine]
[combat-trainer: message: Contact           Crannach          Akikado           Dijkstra]
[combat-trainer: message: Shagium           Ylzung            Jasnah            Rakkor]
[combat-trainer: message: Vaerek            Tekumseh          Dafi              Drachefeuer]
[combat-trainer: message: Andgrim           Woodsey           Miralor           Malciss]
[combat-trainer: message: Nysper            Ecksdee           Galaphyrae        Boobear]
[combat-trainer: message: Vagon             Samantaka         Siul              Soeadu]
[combat-trainer: message: Valorna           Shigar            Taanaa            Joolie]
[combat-trainer: message: Winaugusconey     Hitz              Alagos            Kwadie]
[combat-trainer: message: Valgrind          Rerutsa           Vinarterta        Bitrad]
[combat-trainer: message: Hecte             Blackmuse         Psilocybe         Berimeg]
[combat-trainer: message: Balaraj           Aaoskar           Quintessence      Melx]
[combat-trainer: message: Khaen             Birani            Wrecked           Blackro]
[combat-trainer: message: Morgann           Podfol            Treylis           Lyzalian]
[combat-trainer: message: Pazohn            Jeffe             Holeyiates        Ssarek]
[combat-trainer: message: Sereze            Nodor             Bayric            Myrsha]
[combat-trainer: message: Hessan            Waydren           Zenary            Crucis]
[combat-trainer: message: Maci              Evoldo            Msaia             Pucktin]
[combat-trainer: message: Brave Adventurers Questing:]
[combat-trainer: message: The Xala'shar thrall discovers you, ruining your hiding place!]
[combat-trainer: message: A hulking Xala'shar thrall has spotted you!]
[combat-trainer: message: The Xala'shar thrall searches around for a moment.]
[combat-trainer: message: A hulking Xala'shar thrall's battered corpse slowly sinks into the ground with a barely audible hiss, leaving a sparse pile of possessions in its wake.]
[combat-trainer: message: Appearing to have lost sight of its target, a hulking Xala'shar thrall stops advancing.]
[combat-trainer: message: It would help if you were closer to the Xala'shar thrall.]
[combat-trainer: message: Your blade is a little awkward, but usable.]
[combat-trainer: checked against [/Wouldn't it be better if you used a melee weapon?/i, /Face What?/i, /Roundtime/i, /You aren't close enough to attack/i]]
[combat-trainer: for command backstab]
[combat-trainer]>hide
You melt into the background, convinced that your attempt to hide went unobserved.
Roundtime: 2 sec.

**Comment by rpherbig** [comment]
I think this was fixed in 46619692b6726d6047765794c2c097184a07fcad

You may need to log out and back in to get the updated version of `combat-trainer`
