### ISSUE TITLE
sell-loot make keep_amount/keep_type customizable

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#287]
This issue ties into https://github.com/rpherbig/dr-scripts/issues/221

When crossing-training wasn't calling sell-loot after a work order, it worked for my thief because I always had sufficient coin on me to pay my fines if I got arrested

**Comment by rpherbig** [comment]
Sell-loot takes args of how much to keep (e.g. `;sell-loot 3 plat`). This works when called by itself, but `crossing-training` does not pass along any args. Is that what you are asking for?

**Comment by OdnaZvezda** [comment]
Yes
