### ISSUE TITLE
first-aid and performance

### ISSUE THREAD

**Issue by tulanegator** [rpherbig/dr-scripts#2878]
[hunting-buddy: ***STATUS*** EXECUTE first-aid]
--- Lich: first-aid active.
[first-aid]>get my textbook
--- Lich: performance active.
[performance]>play gavotte
You get a weathered textbook with a tattered cover from inside your carrying bag.
>
Your zills's dirtiness may affect your performance.
You begin a quiet gavotte on your copper zills with only the slightest hint of difficulty.
>
[performance]>stop play
[first-aid]>open my textbook
You stop playing your song.
>
That is already open!
>
[performance]>remove my zills
[first-aid]>turn my textbook to Westanuryn
You slide a pair of copper zills off your finger.
>
You turn to the section on Westanuryn physiology.
>
[performance]>get my chamois cloth
[first-aid]>study my textbook
You need a free hand to pick that up.
>
You begin studying the Westanuryn chart, gradually absorbing the knowledge contained within.
Roundtime: 20 seconds.
>
[performance: *** No match was found after 15 seconds, dumping info]
[performance: messages seen length: 3]
[performance: message: Roundtime: 20 seconds.]
[performance: message: You begin studying the Westanuryn chart, gradually absorbing the knowledge contained within.]
[performance: message: You need a free hand to pick that up.]
[performance: checked against [/You get/i]]
[performance: for command get my chamois cloth]
[performance]>wipe my zills with my chamois cloth
You need to be holding the cloth in order to wipe your copper zills.
>
[first-aid]>turn my textbook to Crab
>
You turn to the section on Crab physiology.
>
[first-aid]>study my textbook
You begin studying the Crab chart, gradually absorbing the knowledge contained within.
Roundtime: 20 seconds.
>
[performance]>wring my chamois cloth
[first-aid]>turn my textbook to Silverfish
You should be holding that first.
>
You turn to the section on Silverfish physiology.
>
[first-aid]>study my textbook
You begin studying the Silverfish chart, gradually absorbing the knowledge contained within.
Roundtime: 20 seconds.
>
[performance: *** No match was found after 15 seconds, dumping info]
[performance: messages seen length: 4]
[performance: message: Roundtime: 20 seconds.]
[performance: message: You begin studying the Silverfish chart, gradually absorbing the knowledge contained within.]
[performance: message: You turn to the section on Silverfish physiology.]
[performance: message: You should be holding that first.]
[performance: checked against [/You wring a dry/i, /You wring out/i]]
[performance: for command wring my chamois cloth]
>
[performance]>wring my chamois cloth
You should be holding that first.

**Comment by rpherbig** [comment]
@Sarvatt is this related to #2874 ?
