### ISSUE TITLE
hoarfrost white sanowret crystal added to database

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#2887]
You put on a hoarfrost white sanowret crystal.   --- Lich: sanowret-crystal active.  [sanowret-crystal]>tap my sanowret crystal   I could not find what you were referring to.   [sanowret-crystal: Sanowret crystal not found.]   --- Lich: sanowret-crystal has exited."

**Comment by Sarvatt** [comment]
those need to be interacted with as white crystal instead of sano crystal

**Comment by jandersson** [comment]
Wondering a couple of things
could we get rid of the tap and not break anything?
is the exhale command it does good enough to detect if you have a crystal?

**Comment by xtremenerdrage** [comment]
just adding that hoarfrost still doesn't work - as mentioned they are "white crystal"

**Comment by MahtraDR** [comment]
Closing. We have `sanowret_adjective` today.
