### ISSUE TITLE
backstab/new blindside fails when you lose hiding

### ISSUE THREAD

**Issue by Setvers** [rpherbig/dr-scripts#2897]
[combat-trainer]>hide
You melt into the background, convinced that your attempt to hide went unobserved.
HR>
A cougar sniffs inquisitively at the air.
HR>
[combat-trainer]>backstab
HR>
A wood troll has spotted you!
>
[combat-trainer]>backstab
You must be hidden to blindside.
>
[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 15]
[combat-trainer: message:  Khri Focus  (13 roisaen)]
[combat-trainer: message: You must be hidden to blindside.]
[combat-trainer: message: A wood troll has spotted you!]
[combat-trainer: for command backstab]

**Comment by tulanegator** [comment]
It appears this was fixed in commit #2904
