### ISSUE TITLE
Allow for defined choices to use when predicting the future in ;astrology

### ISSUE THREAD

**Issue by ghost** [rpherbig/dr-scripts#2905]
>exp mods
The following skills are currently under the influence of a modifier:
+241 Attunement
--171 Targeted Magic
+190 Perception
--10 Thievery
+70 First Aid
+97 Forging
+190 Astrology

Yikes, that -TM. Right now ;astrology finishes by seeing which of your prediction pools can be used, aligning to that skill pool, and predicting. Examples are shown below.

Moon Mages can, instead of aligning to a skill pool (i.e. Magic), align to a particular skill itself. Rather than choosing one skill at random within that pool, you will then predict the future on the chosen specific skill.

This will prevent the sometimes very negative predictions from negatively impacting your normal hunting. Rather than get a big minus to TM, I'd prefer a big minus to...Arcana. Rather than get a big minus to Evasion, I'd prefer a big minus to Outdoorsmanship. Etc...

I've made the necessary changes to astrology (my copy is named astrology2 to avoid being overwritten). It requires a section in the YAML for astrology_prediction_skills, with one line item per skillset you're wanting to specifically predict for. i.e. 

```
astrology_prediction_skills:
  magic: Arcana
  lore: Scholarship
  offense: Bow
  defense: Parry
  survival: Outdoorsmanship
```
I'm recommending adding the following section to base.yaml for those people that don't want to use the override:

```
astrology_prediction_skills:
  magic: magic
  lore: lore
  offense: offense
  defense: defense
  survival: survival
```

Astrology2.lic located here: https://pastebin.com/aftpft8e. The changes to the script are minimal. 5 additional variables at the top, and then making use of those variables in the def predict_all(pools) section.

**Example generic astrology:**

> [astrology]>predict state all
> You consider your recent observations:
> You have a potent understanding of the celestial influences over magic (67-77%).
> You have an insightful understanding of the celestial influences over lore (78-88%).
> You have a complete understanding of the celestial influences over offensive combat (100%).
> You have a complete understanding of the celestial influences over defensive combat (100%).
> You have a potent understanding of the celestial influences over survival (67-77%).
> You have no understanding of the celestial influences over future events (0%).
> Roundtime: 13 sec.
> 
> [astrology]>align lore
> You focus internally and align yourself for a prediction on a random lore skill.
> Roundtime: 2 sec.
> >
> [astrology]>predict future
> You look inside yourself in an attempt to see beyond the now.
> After a few moments, the mists of time begin to part.
> The unity of your mind brings an additional vibrancy to these visions.
> You see an earthquake devastate a small village.
> People are fleeing in every direction.
> You see an endless sea of crystal-blue water.
> A man stands in darkness alongside a forge.
> A sudden feeling of warmth pervades your soul.
> Roundtime: 10 sec.
> 
> [astrology]>align magic
> You focus internally and align yourself for a prediction on a random magic skill.
> Roundtime: 2 sec.
> >
> [astrology]>predict future
> You look inside yourself in an attempt to see beyond the now.
> After a few moments, the mists of time begin to part.
> The unity of your mind brings an additional vibrancy to these visions.
> You see a fire raging through a pine forest.
> You see a celestial display of the planets in orbit.
> A woman stands in darkness trailed by a tiny frosty sphere.
> A shiver runs through your spine.
> Roundtime: 10 sec.
> 
> [astrology]>align survival
> You focus internally and align yourself for a prediction on a random survival skill.
> Roundtime: 2 sec.
> >
> Veleren attaches a thin iron rasp to his carpenter's belt.
> >
> [astrology]>predict future
> You look inside yourself in an attempt to see beyond the now.
> After a few moments, the mists of time begin to part.
> The unity of your mind brings an additional vibr
> 
> ancy to these visions.
> You see a grossly bloated sun.
> It has grown many times its normal size.
> The sky is filled with its eerie, red light.
> You see an ancient mountain, worn by the sands of time.
> A woman stands in darkness with blood dripping from her wounds.
> A sudden feeling of warmth pervades your soul.
> Roundtime: 10 sec.

**Example astrology2:**

> [astrology2]>cast
> You gesture.
> Your cambrinth armband emits a loud *snap* as it discharges all its power to aid your spell.
> Your color vision blossoms with new depth.  The vibrant hues resolve into incredibly defined auras that dance around everything you see.
> >
> You consider your recent observations:
> You have no understanding of the celestial influences over magic (0%).
> You have no understanding of the celestial influences over lore (0%).
> You have a significant understanding of the celestial influences over offensive combat (56-66%).
> You have a complete understanding of the celestial influences over defensive combat (100%).
> You have no understanding of the celestial influences over survival (0%).
> You have no understanding of the celestial influences over future events (0%).
> Roundtime: 16 sec.
> >
> You feel fully rested.
> >
> [astrology2]>align Bow
> >
> You focus internally and align yourself for a prediction on Bows.
> Roundtime: 2 seconds.
> >
> [astrology2]>predict future
> You look inside yourself in an attempt to see beyond the now.
> After a few moments, the mists of time begin to part.
> The unity of your mind brings an additional vibrancy to these visions.
> You see a firestorm erupt above your head.
> Waves of heat wash over you, making you gasp for breath.
> You see a ghost, haunting the place of its death.
> A man stands in darkness armed with a bow and arrow.
> A sudden feeling of warmth pervades your soul.
> You are certain that your experience helped avoid a darker fate.
> Roundtime: 10 sec.
> >
> [astrology2]>align Parry
> You focus internally and align yourself for a prediction on Parry Ability.
> Roundtime: 2 seconds.
> >
> [astrology2]>predict future
> You look inside yourself in an attempt to see beyond the now.
> After a few moments, the mists of time begin to part.
> The unity of your mind brings an additional vibrancy to these visions.
> You see Grazhir cracking open in one sharp movement.
> The World Dragon emerges, roaring soundlessly.
> It moves to sear Katamba to a lifeless black.
> You see an ancient mountain, worn by the sands of time.
> A woman stands in darkness holding a parry stick.
> A sudden feeling of warmth pervades your soul.
> Roundtime: 10 sec.
> >
> [astrology2]>predict analyze
> Your masterful awareness brings the webs of fate to life as a dynamic overlay on reality.  A handful of images flutter in and out of view and you pick out the following:
>  
> A vivid cerulean (good polarity) spellbook that slowly reshapes itself into a cowering figure.  It hangs in the air a moment before fading from sight.
>  
> A vivid sky blue (good polarity) shield that disappears and is replaced by two crossed swords.  It hangs in the air a moment before fading from sight.  A Human man stands in the background, watching.
>  
> A vivid sapphire (good polarity) tome that shifts into an open book.  It hangs in the air a moment before fading from sight.  A Human man stands in the background, watching.
>  
> A vivid aquamarine (good polarity) moonblade that disappears and is replaced by a bow and arrow.  It hangs in the air a moment before fading from sight.
>  
> A vivid azure (good polarity) tree that slowly reshapes itself into an acrobat.  It hangs in the air a moment before fading from sight.  A Human man stands in the background, watching.
>  
> Roundtime: 7 sec.
> >
> --- Lich: astrology2 has exited.

**Comment by MahtraDR** [comment]
This has been pending for over 3 years now. No interest has been shown on this since it was opened, so closing as stale. Would happily consider a new request as fresh.
