### ISSUE TITLE
getting a combat-trainer error

### ISSUE THREAD

**Issue by s1ckpuppy** [rpherbig/dr-scripts#2906]
>;combat
--- Lich: combat-trainer active.
--- Lich: error: combat-trainer:3282: syntax error, unexpected end-of-input, expecting keyword_end
	C:/Users/nick/Downloads/lich-4.6.37/lich/lich.rbw:2542:in `eval'
	C:/Users/nick/Downloads/lich-4.6.37/lich/lich.rbw:2542:in `block (3 levels) in <class:Script>'
--- Lich: combat-trainer has exited.

**Comment by Sarvatt** [comment]
fixed by https://github.com/rpherbig/dr-scripts/pull/2907
