### ISSUE TITLE
New performance bug

### ISSUE THREAD

**Issue by Maledar** [rpherbig/dr-scripts#2919]
https://pastebin.com/RwjyiSfs

It paused but I ended up with the compendium in hand so I couldn't clean the zills

**Comment by rpherbig** [comment]
@sarvatt

**Comment by Sarvatt** [comment]
sorry, this one is different, the zills got dirty in the middle of reading which isn't handled and needs to be fixed.

**Comment by Sarvatt** [comment]
Fixed by https://github.com/rpherbig/dr-scripts/commit/20330449599d720fda4f6e01477e853c4159af6f

**Comment by rpherbig** [comment]
@Maledar can you retest this?

**Comment by Maledar** [comment]
Across like 7 people that only happened to me once... and hasn't re-happened again so be a bit hard to retest but I will try

**Comment by Sarvatt** [comment]
yeah it's a hard condition to hit, your zills have to get dirty in the middle of running first-aid. I'm 100% sure this is fixed though, first-aid always ignores cleaning zills now and i've tested that.
