### ISSUE TITLE
add options for use_research

### ISSUE THREAD

**Issue by hwoo79** [rpherbig/dr-scripts#292]
would like to be able to set use_research to only use it for a specific skill, say warding, and then use the training spells for the others.

**Comment by rpherbig** [comment]
@rcuhljr I'm thinking we'd want to add a new setting, `crossing_training_research_skills`, that is an array of skill names (similar to `crossing_training`). We can check if `use_research` is true first, then fall-back to `crossing_training_research_skills`. Thoughts?

**Comment by hwoo79** [comment]
sounds perfect!

**Comment by rcuhljr** [comment]
Closing since this is now supported.
