### ISSUE TITLE
steal.lic path to 12835 prevents script from running in Shard

### ISSUE THREAD

**Issue by cpryor6** [rpherbig/dr-scripts#2948]
path to 12835 breaks in steal.lic when leaving Fayrin's rest:

[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (2852) and destination room (12835)]
--- Lich: go2 has exited.
[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (2852) and destination room (12835)]
--- Lich: go2 has exited.
out
[Telgi Mod'Sunhin, Enescu's Herbs]
The sagging shelves of this hut are lined with dingy, filth-caked bottles filled with things of indeterminate color, size and shape.  Dust balls skid along the splintered floor dizzily.  A sputtering fire in a small brazier lends just enough light to the room to make any sensible person wish for complete darkness.  You also see a chopping table, the herbalist Enescu and an overturned straw basket with an herbal catalog on it.
Obvious exits: out.
Room Number: 2852
>
[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (2852) and destination room (12835)]
--- Lich: go2 has exited.
You go out.
[Telgi Mod'Sunhin, Platform]
This is a creaking platform that rises twenty feet above the forest floor.  The view is much the same as below, except for a small treehouse that stands before you.  Its roof is a crazy quilt of tattered cloth, rotted shingles, branches and vines.  The walls are dark and splintered, and smoke occasionally seeps out from the cracks.  You also see a narrow staircase.
Obvious paths: none.
Room Number: 2853
>
[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (2853) and destination room (12835)]
--- Lich: go2 has exited.
[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (2853) and destination room (12835)]
--- Lich: go2 has exited.
[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (2853) and destination room (12835)]
--- Lich: go2 has exited.
[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (2853) and destination room (12835)]
--- Lich: go2 has exited.
[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (2853) and destination room (12835)]
--- Lich: go2 has exited.
[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
go stai
[go2: error: failed to find a path between your current room (2853) and destination room (12835)]
--- Lich: go2 has exited.
[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (2853) and destination room (12835)]
--- Lich: go2 has exited.
You will have to climb that.
>
[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (2853) and destination room (12835)]
--- Lich: go2 has exited.
[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (2853) and destination room (12835)]
--- Lich: go2 has exited.
[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (2853) and destination room (12835)]
--- Lich: go2 has exited.
cli stai
[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (2853) and destination room (12835)]
--- Lich: go2 has exited.
[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (2853) and destination room (12835)]
--- Lich: go2 has exited.
[Fayrin's Rest, Telgi Mod'Sunhin]
The road winds with easy grace through a lightly wooded clearing.  A large burrow of Halflings snuggles against a cedar to the north, fitted with a series of curtained windows and filtered vents.  To the other side of the Telgi is an ancient oak, gnarled with age and disease.
Obvious paths: northeast, west.
Room Number: 2838
>
[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (2838) and destination room (12835)]
--- Lich: go2 has exited.
[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (2838) and destination room (12835)]
--- Lich: go2 has exited.
[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (2838) and destination room (12835)]
--- Lich: go2 has exited.
[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (2838) and destination room (12835)]
--- Lich: go2 has exited.
[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (2838) and destination room (12835)]
--- Lich: go2 has exited.
w
[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (2838) and destination room (12835)]
--- Lich: go2 has exited.
[steal: Failed to navigate to room 12835, attempting again]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (2838) and destination room (12835)]
--- Lich: go2 has exited.
You go west.
[Fayrin's Rest, Telgi Mod'Sunhin]
Massive oaks extend a silver-grey canopy of leaves that fades quickly into inkblack darkness from here to the east, north and south.  The air shimmers and whispers softly, sibilantly, of long growth and and gradual decay.  A few slender cedars and elms mark the beginning of a denser forest to the west, one marked by greater undergrowth and steeper rises.  You also see a small, faintly glowing obelisk.
Obvious paths: east, southwest.
Room Number: 2837
>

**Comment by aruthas** [comment]
Should be fixed.  Any and all test appreciated

**Comment by cpryor6** [comment]
This was indeed fixed!  Thank you!
