### ISSUE TITLE
Not leaving combat when too injured to get a weapon

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#2952]
Ended up with severe paralysis from backfiring too much, and got stuck with this until I died

[combat-trainer: message: Your wounds hinder your ability to do that.]
[combat-trainer: checked against [/^You .*(?i-mx:forest.*\bcrossbow)/, /^You remove.*crossbow/i, /^.*you untie your .*(?i-mx:forest.*\bcrossbow)
  from it./, /^What were you referring/i, /^Untie what/i, /^You are a little too busy/i]]
[combat-trainer: for command untie my forest.crossbow]

**Comment by rpherbig** [comment]
Duplicate of #3640
