### ISSUE TITLE
Request: blindside support for two categories of weapons

### ISSUE THREAD

**Issue by CunningRunt** [rpherbig/dr-scripts#2962]
Would anyone mind integrating blindside/backstab support for both edges and blunts?

**Comment by Sarvatt** [comment]
he's looking to train both weapon types in backstab: at the same time instead of one or the other, does that work?

**Comment by CunningRunt** [comment]
Do you mean simultaneously?  I'd like to apply it to both edges and blunts at once, e.g.:

backstab:
- Small Edged
- Small Blunt

**Comment by Tarhish** [comment]
On my thief if I have small blunt and small edged in my backstab and in my weapon training it will swap between them as each one needs training and keep the stabs happening as needed, yeah.  It looks like

backstab: 
  - Small Edged
  - Small Blunt

**Comment by Tarhish** [comment]
Oh, I've been using it this way for so long I didn't realize that wasn't how it looked in the sample.  combat-trainer just has a backstab.include(weapon_skill), so if you add more lines to the yaml it just checks to see if it includes the weapon skill you're using.  I haven't had any problems with this.

**Comment by rpherbig** [comment]
Do you know if backstab works with a swappable weapon?

**Comment by Tarhish** [comment]
I'd be willing to test it, but I don't have a swappable weapon I'm capable of backstabbing with.  I'll look around for a throwing spike or something unless someone is better-equipped than me and has one ready.

**Comment by MahtraDR** [comment]
This has been pending for over 3 years now. None of the current active developers has any interest in this, so closing it out. Would happily consider a new request as fresh.
