### ISSUE TITLE
Oil for Forging and Theurgy do not mix

### ISSUE THREAD

**Issue by edmondsd** [rpherbig/dr-scripts#2966]
When performing a forging workorder, it will execute "get oil" rather than "get oil from _crafting container_", therefore grabs my holy oil in my _<theurgy_supply_container>_. The holy oil is then stowed in my general container and Theurgy doesn't find it. So, I buy excess holy oil. Effectively, I end up buy alot of holy oil. Could we set it to default to grab the oil for forging from the _<crafting container>_ and put back to there? Or whatever works best.

**Comment by Sarvatt** [comment]
set crafting_items_in_container: haversack or whatever in your yaml to keep components in there.

**Comment by edmondsd** [comment]
[forge]>push slack tub
An explosive blast of steam erupts from your back scratcher as it hits the cool water of the slack tub!

The worked metal looks to be in need of some oil to preserve and protect it.
Roundtime: 25 sec.
>
[forge]>get scratcher from anvil
You get an unfinished bronze back scratcher from atop an iron anvil.
>
[forge]>get my oil
You get a bottle of holy oil from inside your hide satchel.
>
[forge]>pour my oil on my scratcher
You can't fill that with the holy oil.
>
Your latent Shield of Light spell dissipates.
>
[forge: *** No match was found after 15 seconds, dumping info]
[forge: messages seen length: 13]
[forge: message: Your latent Shield of Light spell dissipates.]
[forge: message: Centering  (7 roisaen)]
[forge: message: Auspice  (5 roisaen)]
[forge: message: Glythtide's Gift  (1 roisan)]
[forge: message: Bless  (7 roisaen)]
[forge: message: Osrel Meraud  (90%)]
[forge: message: Shield of Light  (Fading)]
[forge: message: Murrula's Flames  (OM)]
[forge: message: Major Physical Protection  (3 roisaen)]
[forge: message: Minor Physical Protection  (3 roisaen)]
[forge: message: Protection from Evil  (7 roisaen)]
[forge: message: Persistence of Mana  (OM)]
[forge: message: You can't fill that with the holy oil.]
[forge: checked against [/Roundtime/i, /Applying the final touches/i, /You can't pour/i, /You pour all of/i]]
[forge: for command pour my oil on my scratcher]
[forge]>put my oil in my pack
You put your oil in your leather pack.
>
[forge]>get my second oil
You get a flask of oil from inside your leather pack.
>
[forge]>pour my oil on my scratcher
You unwrap the cloth surrounding the oil, and use it to rub grime and grit off your back scratcher.  Then, you pour a small amount on the metal and work it in.
Roundtime: 12 sec.
Applying the final touches, you complete working on a bronze back scratcher.

**Comment by edmondsd** [comment]
Fix:
crafting_items_in_container:
- oil
