### ISSUE TITLE
Social Outrage and ;pick for shard

### ISSUE THREAD

**Issue by halprind** [rpherbig/dr-scripts#2971]
> [go2]>offer 99990000000
> Malik laughs and says, "I can't take bribes with Lyle around."
> He mutters something under his breath.
>
>[go2]>offer 99990000000
>[status-monitor: ]
>Malik laughs and says, "I can't take bribes with Lyle around." 
>He mutters something under his breath.``

> As you speak up to use the facilities, the clerk scowls at you.  "We don't serve necromancers or sorcerers here.  Leave, now, before I call the guards."

**Comment by Sarvatt** [comment]
I mean, you should know if you need to move hometowns temporarily, what else could we do about it? :D

**Comment by halprind** [comment]
@Sarvatt stop spamming it and kill the script maybe for one.

**Comment by MahtraDR** [comment]
Closing this. We have a lot of issues to work on today, and this has had zero additional interest in 3+ years.
