### ISSUE TITLE
Updates for Ratha base-data, jail-buddy matching, and Trader Regalia spell messaging

### ISSUE THREAD

**Issue by Tarhish** [rpherbig/dr-scripts#2985]
**First:**  Forge Mistress Grimbly of the Rathan Forging Society visits rooms: 
- 11100
- 10762
during her tours of the society building, which aren't currently in base-crafting.

**Second:** base-towns missing some guild-leader data for Ratha
WM GL Tyrsan is in 12687
Thief GL Dwillig s in 13577
Bard GL Lileyew is in 12692
Barb GL Anhh'shre is in 12670

**Third:**
Trader Spell Regalia currently doesn't have cast messaging in base-spells and will hang for a moment on cast.

Cast Success: You cup your palms skyward to bask in an emergent cascade of starlight, feeling cold white radiance cleave to your silhouette as it flows from your aura.
Cast Fail is already in base-spells due to lack of starlight or moonlight.

**Fourth:**  Jail-Buddy doesn't currently recognize the high guard manhandling you in Ratha.  The log looks like this

The high guard scans the area with a watchful eye.
The guard stares in your direction for a long moment, then charges straight for you!  You are unable to evade the onslaught, trapped by the guard.

With deft actions, the guard binds your hands behind your back, and marches you off.
The guard brings you to the jail, where several companions aid to hold you down and strip you of all your possessions.  They are placed in a sack under the watchful eye of the jail warden, and then you are ushered to a cell, the door opened just long enough for you to be shoved inside.
[Ratha, Jail]
A loose scattering of straw cannot conceal the stinking remains of rotten refuse.  By the look of the yellow substance that also stains the floor, someone was not able to handle the smell.  
Obvious exits: none.

Please let me know if I can help with this or if I should split these up/get more information.

**Comment by Sarvatt** [comment]
Thanks for all the info! have PR's for all for fixes in now
