### ISSUE TITLE
Pick script unlocked a box that was not disarmed, triggering the trap

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#30]
The relevant log:

>
[pick: disarm(casket, normal)]
[pick]>disarm my casket normal
You begin work at disarming the casket.
You work with the trap for a while but are unable to make any progress.
You get the distinct feeling your manipulation caused something to shift inside the trap mechanism.  This is not likely to be a good thing.
Roundtime: 9 sec.
>
[pick: disarm(casket, careful)]
[pick]>disarm my casket careful
>
You carefully work at disarming the casket.
You work with the trap for a while but are unable to make any progress.
Roundtime: 12 sec.
>
[pick]>disarm my casket analyze
You've already analyzed this trap in preparation for harvesting, there's no need to do so again.
>
[pick]>disarm my casket harvest
The remnants of this casket's previous trap have already been completely harvested.
>
[pick]>disarm my casket analyze
You've already analyzed this trap in preparation for harvesting, there's no need to do so again.
>
[pick]>disarm my casket harvest
The remnants of this casket's previous trap have already been completely harvested.
>
[pick]>pick my casket ident
The lock is a trivially constructed piece of junk barely worth your time.
However, a misshaped pine casket is not fully disarmed, making any chance of picking it unlikely.
Roundtime: 5 sec.
>
[pick]>pick my casket quick
You deftly remove a lockpick from the lockpick ring and begin to work at quickly picking open the casket.
You realize very quickly that this was a very bad idea...
You attempt to pull the annoying grinning face from the casket and clumsily shred the fatty bladder behind it in the process.
>
A black cloud of ash and soot explodes out of the bladder on the pine casket, and you suddenly feel horribly transformed.
You realize that despite this mishap, the casket still has more to torment you with.
You return your lockpick to the lockpick ring.
Roundtime: 6 sec.

**Comment by rcuhljr** [comment]
Fixed. https://github.com/rpherbig/dr-scripts/commit/f4ac78f705082ee34f21c86865f09be83e183bbe
