### ISSUE TITLE
combat-trainer getting stuck loading and aiming bows

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#3022]
deleted

**Comment by Sarvatt** [comment]
it takes some time to trigger but once it's broken it'll forever be broken in that hunt unless it seems like.

**Comment by Sarvatt** [comment]
scratch that, hit the bug again with that change.

**Comment by xtremenerdrage** [comment]
I've noticed this alot, it does seem to only happen with a hunting buddy

**Comment by xtremenerdrage** [comment]
Wouldn't it have to do with the line that makes the game_state false if a mob died?

  def attack_aimed(charged_maneuver, game_state)
    game_state.selected_maneuver = charged_maneuver unless game_state.loaded
    **_game_state.loaded = false if game_state.mob_died && !(game_state.casting_consume || game_state.prepare_consume)_**
    game_state.clear_aim_queue if Flags['ct-ranged-ready']

**Comment by Sarvatt** [comment]
This seems to happen right after an armor swap happens from looking at the logs.

**Comment by xtremenerdrage** [comment]
I actually haven't noticed the stuck loading issue in a long time

**Comment by Sarvatt** [comment]
didn't you start using bandaid.lic as a during:?

**Comment by xtremenerdrage** [comment]
Oh I haven't been hunting with people lately, that's probably why I haven't noticed it

**Comment by Sarvatt** [comment]
it seems that if something happens on a timer in say trainerprocess it wont actually get passed along to the game if it's currently doing work in initialize (aka armor swapping or warhorns), I don't know why though.
