### ISSUE TITLE
workorder/shaping is not buying the correct materials on making a pendant

### ISSUE THREAD

**Issue by aruthas** [rpherbig/dr-scripts#3035]
Shaping is getting hung up because it is not buying the correct materials.
[issue.txt](https://github.com/rpherbig/dr-scripts/files/2266336/issue.txt)

**Comment by Sarvatt** [comment]
on it, i see a few problems here

**Comment by aruthas** [comment]
your up early 👍

**Comment by Sarvatt** [comment]
I don't get how noone noticed this before :)
