### ISSUE TITLE
feature request: support swapping crafting belts

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#3051]
if outfitting_belt: is defined for instance we could inv waist, and remove whatever is worn to put the defined belt on at the start of the script

**Comment by Maledar** [comment]
My only suggestion for f2p using a fascionesta liscense, this will remove their extra belt. So maybe, tag a belt being worn:  so it doesn't have to remove it? can just pull from inventory

**Comment by MahtraDR** [comment]
Closing this as a clone of https://github.com/rpherbig/dr-scripts/issues/1692
