### ISSUE TITLE
Locket recipe breaking in workorders

### ISSUE THREAD

**Issue by Maledar** [rpherbig/dr-scripts#3054]
Something going wrong that I end up not holding the strap and assembling it..I will try to catch the full issue but its happened across 2 characters and yes I know a fix was put in and I restarted since

**Comment by Sarvatt** [comment]
a log would be much appreciated

**Comment by Maledar** [comment]
https://pastebin.com/XspBjW32

I just recreated it. Mind you it did buy the first cord earlier, so I do have it for the first one. But even now as I completed it (The log is the 2nd locket being made) I don't have another cord but still it doesn't seem to even try to assemble the cord
