### ISSUE TITLE
Looking at how to add observations and predictions to combat-trainer for moonies

### ISSUE THREAD

**Issue by aruthas** [rpherbig/dr-scripts#3056]
[combat-trainerastro.txt](https://github.com/rpherbig/dr-scripts/files/2279901/combat-trainerastro.txt)
Needs refined and looked over by someone who is better at coding.

**Comment by MahtraDR** [comment]
This has been pending for over 3 years now. No interest has been shown on this since it was opened, so closing as stale. Would happily consider a new request as fresh.
