### ISSUE TITLE
Athletics pausing at around 400 ranks on jumble rocks log attached

### ISSUE THREAD

**Issue by Maledar** [rpherbig/dr-scripts#3060]
It's happened twice now, log below

https://pastebin.com/r8cGR5gZ

I'm pretty sure its this messaging stopping it

This climb is too difficult, so you stop practicing. 

It'll just stop after that not exit or restart

**Comment by Sarvatt** [comment]
you went there be ause you had athleticism up which faded when you got
there, need to add 10% to the ranks i guess

**Comment by Sarvatt** [comment]
the min ranks for this specific climb was heavily tested

**Comment by Maledar** [comment]
Happened again....this time I had no buff and it went to climb anyway

https://pastebin.com/u2ULQqXH

414 athletics

**Comment by Sarvatt** [comment]
skill-recorder updates every 30 seconds

**Comment by Sarvatt** [comment]
you had the buff within the 30 second of it starting to climb, im not sure i'm comfortable raising the limit any higher because the next lowest climb stops teaching at 425

**Comment by Sarvatt** [comment]
for you personally to have this stop and fix yourself, remove your athletics buff from any spell training
