### ISSUE TITLE
Consider requiring all common method references to be fully qualified

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#3069]
As a codebase that is constantly in flux and with new contributors I think the code would be more readable if we qualified all references to common methods with their script abbreviation..

e.g.
instead of `retreat` we use `DRCT.retreat` then it is immediately clear to the reader that this is from the DRCT module

Readability may also contribute to _more_ contributors if they can understand the scripts they are reading and want to change. Even as a frequent editor, I find myself asking "Where is this defined?"

**Comment by rpherbig** [comment]
I'm ok with this. I think you're right that it might help new contributors.

**Comment by MahtraDR** [comment]
@rpherbig can we close this as we're enforcing this going forward already?
