### ISSUE TITLE
base-hunting entry dark_spirits is totally wack

### ISSUE THREAD

**Issue by Zhennlash** [rpherbig/dr-scripts#3085]
>   dark_spirits:
>   - 8499
>   - 8497
>   - 8498
>   - 8500

The first three rooms lead to dragon priests, the fourth leads to the city of Theren (lol).

A confirmed room for dark spirits seems to be 13704. None of the items in the array are accurate.

**Comment by Glimmereyes** [comment]
Might need to be moved into escort_zone.  If memory serves, between the darkness and the identical room descriptions the map does not handle the area well.
