### ISSUE TITLE
[FIXED] Smite (paladin ability) doesn't work in combat-train

### ISSUE THREAD

**Issue by igroglaz** [rpherbig/dr-scripts#3092]
---
training_abilities:
  Smite: 20
---
doesn't work

---
training_abilities:
  Conviction: 20
---

also doesn't work :(

**Comment by igroglaz** [comment]
nope, it's problem with ruby. now I can't start the game.

**Comment by tulanegator** [comment]
You need to have two spaces before "Smite". Ex:

training_abilities:
  Smite: 80

**Comment by BastionWT** [comment]
```
training_abilities:
  Smite: 61
```

That works fine for me. Make sure to set the value to greater than 60, Tangar, as that is how often you get free Smites.

**Comment by igroglaz** [comment]
I put 61, still doesn't work :(

**Comment by igroglaz** [comment]
I've updated my YAML, but it doesn't help:
https://0bin.net/paste/rWumrdgeZ+P3rGlp#yRjCvJkPaEtHn02dwLJ9rkhvz6hnIJKLkBcFmKHyjzB

1) my character constantly RUN away if there are more then 2 rats 
2) char do not apply Smite..

PLEASE HELP!

**Comment by igroglaz** [comment]
also I still have this error: " --- error: XMLParser.tag_start: comparison of Fixnum with nil failed  "  


I've wrote about it there ( https://github.com/rpherbig/dr-scripts/issues/3088 ), but nobody knows where it comes from, so I put it in 'ignore'

**Comment by igroglaz** [comment]
combat log where I run away all the time:
https://0bin.net/paste/ozMl8L+muZZHYzV8#3yk1UcWvwj80lhB-QhC+cnbkDgchCONEXIlXp3Tkg0w

**Comment by rpherbig** [comment]
Is your character using any other `training_abilities` like Perc or Hunt?

**Comment by rpherbig** [comment]
What is the name of your character and the name of your YAML file?

**Comment by igroglaz** [comment]
1) no, char doesn't use any training_abilities
2) character name: Igroglaz
Igroglaz-setup.yaml
It certanly reads YAML file cause when I changed equipment - Lich reacts on it and wear/wield according gear.

**Comment by igroglaz** [comment]
I tried to use Frostbites client, but still got the same error there too:
--- error: XMLParser.tag_start: comparison of Fixnum with nil failed

**Comment by igroglaz** [comment]
Ok! I fixed this error: --- error: XMLParser.tag_start: comparison of Fixnum with nil failed (ticket closed)

But my character continue to run away from fights and do not use Smite! :DDD Please help!!

**Comment by igroglaz** [comment]
log from the game: https://0bin.net/paste/oBcJk1KlKD+OQ51I#plcpBWgD3L0uX61tNzodtrDlT0p9QgAlrsfAZI0zpKs

**Comment by igroglaz** [comment]
With the help of Sarvatt we figured out source of problem:

>;e echo health
--- Lich: exec1 active.
[exec1: ]
--- Lich: exec1 has exited.

Sarvatt: "so yeah lich isn't parsing the xml simu is sending right, it thinks you have no health

What to do with it?

**Comment by igroglaz** [comment]
My latest setup (fixed fork version): https://pastebin.com/gtBxgqXj

...it keeping RUNNING away :(

**Comment by igroglaz** [comment]
I'm going to delete all simu and ruby programms from PC.. also clean regesrty.. would tell about results

**Comment by igroglaz** [comment]
Nothing worked. I cleaned everything from old clients.

Also I found that this error:
 " --- error: XMLParser.tag_start: comparison of Fixnum with nil failed "
still there. I didn't fixed it, it was just hidded in highlights.

For now I quit playing DR till this problem would be solved somehow.

**Comment by igroglaz** [comment]
I tried all. Different versions of Ruby, google all kinds of websites about Ruby.. Nothing help.

**Comment by rpherbig** [comment]
Have you been able to get DR working _without_ lich?

**Comment by igroglaz** [comment]
yep, SF worked perfectly. also I tried Frostbite, lich worked there too, but had the same error.

**Comment by igroglaz** [comment]
Theres are incredible guys at http://forum.gsplayers.com/showthread.php?117073-DragonRealms-error-XMLParser-tag_start-comparison-of-Fixnum-with-nil-failed ! They found an issue - the only thing which I needed to do:

> If you right-click the mana bar and choose NONE for the TEXT it gives errors. That's the issue. Change it back to FULL.

It fixed the issue completely!

YAHOO!

**Comment by rpherbig** [comment]
I'm so glad you got this resolved!

And especially thank you for closing the loop and letting us know what the problem was.

**Comment by MahtraDR** [comment]
@rpherbig Can close this one.
