### ISSUE TITLE
walkingastro breaks on wounds 

### ISSUE THREAD

**Issue by Maledar** [rpherbig/dr-scripts#3101]
https://pastebin.com/PPMha2Rk

The pain is too much.
You are unable to hold the flamewood telescope steady, and give up.
Roundtime: 5 seconds.

**Comment by BastionWT** [comment]
I'll take this one.

**Comment by Maledar** [comment]
New issue of using during athletics

**Comment by MahtraDR** [comment]
@rpherbig can close. Resolved as above.
