### ISSUE TITLE
Bastard swords & Raekhlo breaks weapon changes in Combat Training

### ISSUE THREAD

**Issue by Beyonddisbelief** [rpherbig/dr-scripts#3103]
When the character is specifically using a swappable weapon with Raekhlo, it can cause weapon switching to fail and have the hunt go indefinitely in the two-handed variant.

Raekhlo's are hard coded to accepted only one-handed weapons. If the script tries to sheathe without swapping the weapon back to one hand, it will claim that the weapon is too large to fit in the Raekhlo. 

Need a method to force it to always swap back to one-handed before sheathing, without breaking other swappable weapons that work differently (such as staves).

Sampel Messaging:
FAILURE: (Two-handed mode)
>shea sword in rae
You realize that your raekhlo is too small to hold that.

SUCCESS: (One-handed mode)
>shea sword in rae
You hang your sparkling blue sword from your raekhlo.  It rattles against the dark azure scimitar hanging from your raekhlo, and you adjust them.

>swap sword
You fiercely switch your grip so that your sword can be used as a heavy edged weapon.
>swap sword
You switch your sword so that you can use it as a two-handed edged weapon.

IIRC "fiercely switch" verbiage for bastard swords changes based on your skill and my not be something one would want to match when swapping.

**Comment by Beyonddisbelief** [comment]
If there's no perfect universal solution, I think it may be easier to fix it for raekhlos specifically and worry about other special sheathes separately.

I imagine that its more likely people have bazillion different swappable weapons to worry about than uncommon sheathes - this is assuming the messaging  is static for raehklos "You realize that your raekhlo is too small to hold that." but I don't know for sure as I don't own other exotic swappable weapons.

**Comment by Sarvatt** [comment]
the swapping messages are already handled fine in equipmanager, i added the "too small to hold that" message to the stow/sheath handling and made it swap your weapon then stow/sheath again if its seen

**Comment by Beyonddisbelief** [comment]
Thanks Sarvant, FYI the new equipmanager seems to be working. I'm not entirely sure why i was having trouble with weapon switching entirely but everything seems to be working normally after i restarted thigns a few times"

**Comment by Sarvatt** [comment]
the new equiipmanager is what i'm trying to push to everyone, it wont hurt them, no need to close this
