### ISSUE TITLE
jailbuddy needs to start killing craft/workorders for forging

### ISSUE THREAD

**Issue by Maledar** [rpherbig/dr-scripts#3106]
Log here

https://pastebin.com/V391Z2g8

This has happened to me a couple of times, and other lichers. 

Best case scenario, you're in a loop like the log. 

Worst case scenario, someone else is already on the forge, error trying to craft and then you dump crafting gear into waste bucket. I've a few tools and someone else lost a unique hammer this way

**Comment by Maledar** [comment]
https://pastebin.com/daxKHpsf

Again, jail-buddy takes another hammer

**Comment by MahtraDR** [comment]
Today, jailbuddy pauses everything when it starts. it does its jail-buddy business, and only then unpauses stuff. I can't see this happening, but we can revisit whenif it does.
