### ISSUE TITLE
Astrology Diviniation Bones - Container not recognized

### ISSUE THREAD

**Issue by Beyonddisbelief** [rpherbig/dr-scripts#3108]
Issues:
1) "container" variable not recognized and comes out blank.
 "get bones from my"
2) Script should specify "divination" as the adjective to prevent issues with variety of other bones (instruments, skin parts, etc.)

- Setup:
have_divination_bones: true
divination_bones_container: rucksack

- Inventory:
R>tap my bones
You'll need to be holding the divination bones to do that.

R>sort bones
All items in an oilcloth rucksack that match your "bones" are now at the top of the container.

R>l in ruck
In the oilcloth rucksack you see some steed divination bones,

- Log:
[astrology]>predict state all
>
You consider your recent observations:
You have a feeble understanding of the celestial influences over magic.
You have no understanding of the celestial influences over lore.
You have no understanding of the celestial influences over offensive combat.
You have a fledgling understanding of the celestial influences over defensive combat.
You have a weak understanding of the celestial influences over survival.
You have no understanding of the celestial influences over future events.
Roundtime: 16 sec.
R>
R>
A scavenger troll strolls in, looks you squarely in the eye and says, "Me thinks I likes this lead rope."  Suddenly, in a blur of motion, it grabs all the junk strewn throughout the area and bolts.
R>
Schyse just arrived.
R>
A long-tailed white rat scurries into the room.
R>
Schyse climbed up a town wall.
R>
[astrology]>align magic
You focus internally and align yourself for a prediction on a random magic skill.
Roundtime: 2 sec.
R>
[astrology]>get bones from my 
Sticky Fingers Etal just arrived.
>
Please rephrase that command.
>
Sticky Fingers Etal climbed up a town wall.
>
A long-tailed white rat scurries off.
>
You've gained a new rank in your knowledge of astrology.
>
Thraena just arrived.
>
Thraena starts to climb up a town wall, but finds it too difficult.
>
[astrology: *** No match was found after 5 seconds, dumping info]
[astrology: messages seen length: 10]
[astrology: message: Thraena starts to climb up a town wall, but finds it too difficult.]
[astrology: message: Thraena just arrived.]
[astrology: message: You've gained a new rank in your knowledge of astrology.]
[astrology: message: Cage of Light  (5 roisaen)]
[astrology: message: Seer's Sense  (6 roisaen)]
[astrology: message:  * Outdoorsman Tssaa Darkeyed joins the adventure.]
[astrology: message: A long-tailed white rat scurries off.]
[astrology: message: Sticky Fingers Etal climbed up a town wall.]
[astrology: message: Please rephrase that command.]
[astrology: message: Sticky Fingers Etal just arrived.]
[astrology: checked against [/divination bones/i, /you get/i]]
[astrology: for command get bones from my ]
[astrology]>roll my bones
You'll need to be holding the divination bones to do that.
>

**Comment by aruthas** [comment]
did you set up the yaml with divination_bones_storage: ?

**Comment by Beyonddisbelief** [comment]
I just tried both
divination_bones_storage: rucksack
and 
divination_bones_container: rucksack

Same result.

**Comment by aruthas** [comment]
Ok there is more to it

**Comment by aruthas** [comment]
Did u look at crannichs yaml?

**Comment by Beyonddisbelief** [comment]
Thanks for the tip. The way it is declared is different from most containers are declared.

**Comment by Beyonddisbelief** [comment]
Still would be nice to have "divination"  adjective added to avoid confusing with animal bones and musical instrument bones, though.
