### ISSUE TITLE
Astrology not casting Piercing Gaze when using Telescope

### ISSUE THREAD

**Issue by Beyonddisbelief** [rpherbig/dr-scripts#3113]
--- Lich: go2 has exited.
[crossing-training]>assess teach
You assess the teaching environment...

No one seems to be teaching.
Roundtime:  5 seconds.
R>
--- Lich: astrology active.
[astrology]>observe sky
You scan the sky from horizon to horizon.
It is completely overcast.

The following heavenly bodies are visible:
Clouds obscure the sky where the mid-afternoon sun should appear.
Clouds obscure the sky where the planet Verena should appear.
Clouds obscure the sky where the planet Estrilda should appear.
Clouds obscure the sky where the planet Durgaulda should appear.
Clouds obscure the sky where the planet Penhetia should appear.
Clouds obscure the sky where the planet Szeldia should appear.
Katamba is below the horizon.
Xibar is below the horizon.
Yavash is below the horizon.
Roundtime: 5 sec.
R>
You notice Tuulhisakna attempting to conceal his spell preparations.
Tuulhisakna bows his head and chants a prayer.
You decipher the telltale signs of the Centering spell.
R>
**[astrology]>get telescope
You get a simple mahogany telescope from inside your blue robe.
>
[astrology]>center telescope on Szeldia
You put your eye to the mahogany telescope and attempt to center on the planet Szeldia.
>
[astrology]>peer telescope
Clouds obscure the sky where the planet Szeldia should appear.
>
[astrology: *** No match was found after 15 seconds, dumping info]
[astrology: messages seen length: 1]**
[astrology: message: Clouds obscure the sky where the planet Szeldia should appear.]
[astrology: checked against [/You peer aimlessly through your telescope/i, /open it to make any use of it/i, /You see nothing regarding the future/i, /The pain is too much/i, /Roundtime/i]]
[astrology: for command peer telescope]
[astrology]>stow right
You put your telescope in your blue robe.
>
[astrology]>get telescope
You get a simple mahogany telescope from inside your blue robe.
>
[astrology]>center telescope on Szeldia
You put your eye to the mahogany telescope and attempt to center on the planet Szeldia.
>
[astrology]>peer telescope
Clouds obscure the sky where the planet Szeldia should appear.
>
Tuulhisakna gestures.
Tuulhisakna's cambrinth armband emits a loud *snap*.
Tuulhisakna's cambrinth torque emits a loud *snap*.
Tuulhisakna's face grows stoic, his body steady and vigilant.
>
Tuulhisakna begins a quiet battle song on his copper zills with only the slightest hint of difficulty.
>
Valgrind just arrived.
>
Valgrind climbed up a town wall.
>
Tuulhisakna troops southwest.
>
[astrology: *** No match was found after 15 seconds, dumping info]
[astrology: messages seen length: 9]
[astrology: message: Tuulhisakna troops southwest.]
[astrology: message: Valgrind climbed up a town wall.]
[astrology: message: Valgrind just arrived.]
[astrology: message: Tuulhisakna begins a quiet battle song on his copper zills with only the slightest hint of difficulty.]
[astrology: message: Tuulhisakna's face grows stoic, his body steady and vigilant.]
[astrology: message: Tuulhisakna's cambrinth torque emits a loud *snap*.]
[astrology: message: Tuulhisakna's cambrinth armband emits a loud *snap*.]
[astrology: message: Tuulhisakna gestures.]
[astrology: message: Clouds obscure the sky where the planet Szeldia should appear.]
[astrology: checked against [/You peer aimlessly through your telescope/i, /open it to make any use of it/i, /You see nothing regarding the future/i, /The pain is too much/i, /Roundtime/i]]
[astrology: for command peer telescope]
[astrology]>stow right
You put your telescope in your blue robe.
>
[astrology]>get telescope
You get a simple mahogany telescope from inside your blue robe.
>
[astrology]>center telescope on Szeldia
You put your eye to the mahogany telescope and attempt to center on the planet Szeldia.
>
**[astrology]>peer telescope
Clouds obscure the sky where the planet Szeldia should appear.
>
Shadow Fighter Myddnite just arrived.
>
Shadow Fighter Myddnite climbed up a town wall.
>
[astrology: *** No match was found after 15 seconds, dumping info]**
[astrology: messages seen length: 3]
[astrology: message: Shadow Fighter Myddnite climbed up a town wall.]
[astrology: message: Shadow Fighter Myddnite just arrived.]
[astrology: message: Clouds obscure the sky where the planet Szeldia should appear.]
[astrology: checked against [/You peer aimlessly through your telescope/i, /open it to make any use of it/i, /You see nothing regarding the future/i, /The pain is too much/i, /Roundtime/i]]
[astrology: for command peer telescope]
[astrology]>stow right
You put your telescope in your blue robe.
>
[astrology]>get telescope
You get a simple mahogany telescope from inside your blue robe.
>
[astrology]>center telescope on Szeldia
You put your eye to the mahogany telescope and attempt to center on the planet Szeldia.
>
**[astrology]>peer telescope
Clouds obscure the sky where the planet Szeldia should appear.
[astrology: *** No match was found after 15 seconds, dumping info]**
[astrology: messages seen length: 1]
[astrology: message: Clouds obscure the sky where the planet Szeldia should appear.]
[astrology: checked against [/You peer aimlessly through your telescope/i, /open it to make any use of it/i, /You see nothing regarding the future/i, /The pain is too much/i, /Roundtime/i]]
[astrology: for command peer telescope]
[astrology]>stow right

**Comment by MahtraDR** [comment]
astrology.lic uses the astrology waggle. If you want PG whilst using the script, it needs to be in the waggle, with appropriate recast: timers so you always have it up.

@rpherbig This can be closed, I think.
