### ISSUE TITLE
Ruby 2.0 dl and install missing GlobalSignRootCA

### ISSUE THREAD

**Issue by Catalax** [rpherbig/dr-scripts#3114]
Got this error during Ruby install: 

WARNING:  Unable to pull data from 'https://rubygems.org/': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/specs.4.8.gz)
WARNING:  Unable to pull data from 'https://rubygems.org/': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/specs.4.8.gz)

Troubleshot accdng to instructions here: https://elanthipedia.play.net/Lich_scripting_engine

But my problem is that the GlobalSignRootCA.pem file I'm supposed to go find following the instrux is just not there: 

![image](https://user-images.githubusercontent.com/42918159/44960780-18a71f80-aecb-11e8-8dcd-2a86b23d93e4.png)

Tried to google around a little to find a workaround but everything I find (as recent as about five days ago) tells me that any version of Ruby other than 2.0 is not going to work with Lich for DR purposes- but I can't dl 2.0 with the CA I need  so is there a workaround?

**Comment by Sarvatt** [comment]
you need the newest release of 2.0 specifically, 
https://dl.bintray.com/oneclick/rubyinstaller/rubyinstaller-2.0.0-p648.exe

**Comment by Catalax** [comment]
Sorry, I should have specified I did have 2.0.0-p648 instead of referring to it as '2.0', but....

Resolved. 

I’ll post what worked for me here, the process and the misunderstandings I had. (at the risk of appearing like I’ve never used a computer before but hey, maybe someone else looking for an answer hasn’t) that led to problems in case anyone else ends up here with the same question. 

The video here: https://www.youtube.com/watch?v=Ty-seLTJSi4 was a good source and following it got me almost all the way to where I needed to be. What the video doesn’t go into is any errors that might be encountered during setup. 

You can see the error I got while installing Lich in the original post above. The troubleshooting instructions I went through are here: 

https://elanthipedia.play.net/Lich_scripting_engine

under the Solving RubyGems error, and these instructions also got me- almost- to where I needed to be but there were a couple of misunderstandings of instructions as written for someone who doesn’t work regularly with this sort of thing. 

First, when you get to the section of instructions that this screenshot (below) of the troubleshooting section, it caused some confusion on my part. My rubygems\ssl_certs folder didn’t look like that; the GlobalSignRootCA.pem was missing from mine. I was under the impression from looking at this screenshot that my folder was supposed to have the .pem, leading me to believe I had a whole ‘nother problem that this troubleshoot didn’t cover. So I spent too much time googling around trying to identify that whole ‘nother issue that didn’t exist. Don’t do that. If your folder is missing GlobalSignRootCA.pem then you’re still on the right track.
 
![image](https://user-images.githubusercontent.com/42918159/44962007-113e4100-aee0-11e8-8e2a-867db523fff7.png)

But… if your issue is the same as mine… Your folder DOES NOT look like the screen above and that’s okay for now; it’s not supposed to if you’re here reading this because you have the same issue I did.

So… because your folder is missing GlobalSignRootCA.pem, we need to put it there. The next section of the troubleshoot caused me a little confusion as well. There’s a link here (in the green circle)
 
![image](https://user-images.githubusercontent.com/42918159/44962073-e4d6f480-aee0-11e8-91af-6da8c60f30bd.png)

that leads to some weird ftml looking junk that I haven’t seen since like 2002, eliciting a ‘well that can’t be right’ reaction because I understood ‘obtain’ in the instructions to mean ‘download’, and it’s not. So if you get here:
![image](https://user-images.githubusercontent.com/42918159/44962066-de487d00-aee0-11e8-9104-c755f146cc24.png)

 
you’re still on the right track but the confusion (for me) wasn’t quite over with probably in part because of the frustration of the last couple of hours of failure and dead ends that had built up by this point.
 
So, ‘obtain’ does not mean ‘download’, so go ahead and right-click on the jumble of hieroglyphics that link led you to, and Save As…, as instructed in the troubleshooting section at elanthipedia that we’ve been referencing. But, be aware that just saving that above code as ‘all files’ in your notepad is not enough because even with using the ‘all files’ dropdown, you’ll still default to saving it as a .txt file 

so do this: 
![image](https://user-images.githubusercontent.com/42918159/44962099-15b72980-aee1-11e8-9a35-2f93625c1127.png)
(or go here https://sslguru.com/knowledgebase.php?action=displayarticle&id=224 to read the same info)
 
The troubleshooting section just says ‘Make sure it's saved as a .pem file, not a .txt file.”, but doesn’t tell you anything about how to defeat notepad and windows, as determined to make you save it as a .txt file-even if you do use the All Files dropdown- as Siri is to keep you on highways and toll roads when you’re asking for directions ten minutes up the road. 

What I ended up doing to avoid the 'default-to-.txt file' issue was to open up the inevitable GlobalSignRootCA.pem.(that was really a .txt) in notepad, and Save As-> in the rubygems>ssl_certs folder, and click (single-click) on an existing license and retype the correct filename in the File Name dialog box, and this went the long way ‘round to get past the pesky default .txt save. 

So I hope I didn’t actually -add- any confusion to the issue. There were just a couple of points in the instructions about fixing the error that I didn’t catch on to at first (through fourth) go but I finally worked it out with some trial and (mostly) error and I hope to spare someone else who might be a layman or casual computer guy with this same problem any of the issues that I had understanding what was really going on.

**Comment by rcuhljr** [comment]
>So… because your folder is missing GlobalSignRootCA.pem, we need to put it there. The next section of the troubleshoot caused me a little confusion as well. There’s a link here (in the green circle)

I think that's a side effect of moving it to elanthipedia. The original walkthrough was here https://github.com/rpherbig/dr-scripts/wiki/Solving-RubyGems-Error where you can see that it's a large link. What the instructions are trying to get across is that you right click on the link and select `save as` and save that as a .pem file, it avoids the problems of copy and pasting the contents manually and having to figure out how to get a text editor to save the file correctly. 

Someone should get on clarifying the issues you had with the instructions, making it more explicit is never a bad idea.

**Comment by MahtraDR** [comment]
@rpherbig Happily we can close this...
