### ISSUE TITLE
Idled out of the game while in combat

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#312]
I killed the last mob in the room. Training abilities are used while there are no mobs, which _should_ keep us from idling out.

However, as combat-trainer rotated through training abilities, it ended up selecting appraise, which can't be used unless there are mobs. It never moved on to perc or hunt, hence idling out of the game.

**Comment by rcuhljr** [comment]
Look at the recent changes I made to afk.lic and see if we can close this.

**Comment by rpherbig** [comment]
We could, but I think there is still room to improve the logic. Rather than
get stuck on appraising while the room is empty, it should perceive when
the cooldown is up, etc.

Thoughts?

**Comment by rcuhljr** [comment]
Sure, although I'm not sure why it would get stuck, it should go on cooldown when it's selected allowing another skill to be used.
