### ISSUE TITLE
mine & workorders should use :tie_to: setting if crafting tools are part of gear:

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#313]
Crafting tools are heavy, toolbelts make them weightless.

>untie shov
You remove a haralun wide shovel from your forger's belt.
>put shov on count
You put your wide shovel on the counter.

Naissura hefts the wide shovel and puts it on the medium balance scale.  She patiently adds small sacks of stones on the other side till the beam becomes exactly level.

Naissura squints at the balance beam needle and says, "The shovel weighs about sixty stones," and puts the shovel on the counter.

You pay Naissura and take your shovel off the counter.

>l on belt
On the forger's belt you see a stirring rod, some curved tongs, a leather bellows and a cross-peen hammer.
>rem belt
You remove a rugged forger's belt wrapped with fraying grey bourde from around your waist.
>put belt on count
You put your forger's belt on the counter.

Naissura puts the forger's belt on the small balance scale and adds small stones one by one until the beam becomes exactly level.

Naissura squints at the balance beam needle and says, "The belt weighs about five stones," and puts the belt on the counter.

You pay Naissura and take your belt off the counter.

>wear belt
You put a rugged forger's belt wrapped with fraying grey bourde around your waist.
>tie shov to belt
You attach a haralun wide shovel to your forger's belt.
>rem belt
You remove a rugged forger's belt wrapped with fraying grey bourde from around your waist.
>put belt on count
You put your forger's belt on the counter.

Naissura puts the forger's belt on the small balance scale and adds small stones one by one until the beam becomes exactly level.

Naissura squints at the balance beam needle and says, "The belt weighs about five stones," and puts the belt on the counter.

You pay Naissura and take your belt off the counter.

>wear belt
You put a rugged forger's belt wrapped with fraying grey bourde around your waist.
>

- :name: shovel
  :adjective: wide
  :is_leather: false
  :hinders_lockpicking: 
  :is_worn: false
  :swappable: false
  :tie_to: forger's belt
- :name: tongs
  :adjective: curved
  :is_leather: false
  :hinders_lockpicking: 
  :is_worn: false
  :swappable: false
  :tie_to: forger's belt
- :name: rod
  :adjective: stirring
  :is_leather: true
  :hinders_lockpicking: 
  :is_worn: false
  :swappable: false
  :tie_to: forger's belt
- :name: hammer
  :adjective: cross-peen
  :is_leather: false
  :hinders_lockpicking: 
  :is_worn: false
  :swappable: false
  :tie_to: forger's belt
- :name: bellows
  :adjective: leather
  :is_leather: true
  :hinders_lockpicking: 
  :is_worn: false
  :swappable: false
  :tie_to: forger's belt

**Comment by rpherbig** [comment]
@rcuhljr has identified some technical difficulties making the crafting scripts use the `:tie_to:` logic, so he introduced some new settings (forging_belt, engineering_belt, outfitting_belt).

@OdnaZvezda Are these new settings working for you?

**Comment by OdnaZvezda** [comment]
I haven't logged in in close to a week.  Those settings were working last I checked(my bard was doing mostly crafting with belts for outfitting and forging)
