### ISSUE TITLE
Add Thief Glance Support for Pick

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#3135]
I don't think identification teaches, and my thief can actually end up stuck for a good amount of time trying to ID a pet box for example over and over.  The glance ability for thieves doesn't even have an RT.

What info and or messaging would be needed to be gathered to implement this?  I am pretty sure the ID messaging is actually different that standard ID.

**Comment by rpherbig** [comment]
Closed in #5001
