### ISSUE TITLE
Murrula's Flame cast not in database

### ISSUE THREAD

**Issue by andvho** [rpherbig/dr-scripts#3136]
The messaging for successfully casting Murrula's Flame is not being caught. 
The message is:

You raise your palms and face to the heavens, whispering a quiet prayer to Murrula.
The mental strain of this pattern is considerably eased by your ritual focus.

A warm sensation of security floods your bones as the faint outline of a spectral bird roars into visibility, folding its fiery wings around you.  Their flames whorl around you protectively in a wordless promise to stave off Urrem'tier's grasp if your faith remains strong.  Soon the bird's presence fades visibly, although you still feel its warmth surrounding you.

**Comment by Sarvatt** [comment]
any idea what causes it to change messages? MF should be in an orb always which works, last time I fixed this I added - ^Wisps of spectral flame whorl.*$ to base-spells because that was in the persons message but not in yours.

**Comment by Sarvatt** [comment]
https://github.com/rpherbig/dr-scripts/issues/2965 was the last issue

**Comment by andvho** [comment]
I'm not casting it in the orb because it seems to take up 3 slots. It does
work fine if casting into the orb.

**Comment by MahtraDR** [comment]
@rpherbig this works today. can close.
