### ISSUE TITLE
workorders - shadowling trap sprung earlier, can't ask for workorder

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#314]
If the timer from the trap has worn off, all you have to do is say something normally and your voice will return to normal

[pick]>disarm my chest careful

You carefully work at disarming the chest.
With the precision and grace of a skilled craftsman, you grab the black crystal near the lock of the chest and toss it aside.

As the crystal hits the ground, what can only be described as "liquid shadows" begin to pour from it!  With a sudden motion, they envelop you totally.  You try to scream but no sound is heard.  After a moment the shadows are gone and everything seems to be back to normal.
Roundtime: 15 sec.

[pick: ]

[pick: ]

[pick: **SPRUNG TRAP**]

--- Lich: apick has exited.

==========================
~~~ Later that day
==========================

[workorders]>ask Yalda for challenging Blacksmithing work

You want to ask about shadowlings, but don't.
Yalda whistles a quiet melody as she walks into the room.

[workorders: *** No match was found after 15 seconds, dumping info]

[workorders: messages seen length: 2]

[workorders: message: You want to ask about shadowlings, but don't.]

[workorders: message: Yalda whistles a quiet melody as she walks into the room.]

[workorders: checked against [/^To whom/i, /order for .* I need \d+ of .* quality/i, /You realize you have items bundled with the logbook/i]]

[workorders]>ask Yalda for challenging Blacksmithing work

You want to ask about shadowlings, but don't.
>l
[Forging Society, Foundry - 8773]
Waves of heat, blasting with an almost tangible force, roll from the flames of a brick-lined firepit.  Over the firepit, a blackened granite crucible hangs by stout chains from an oak beam high overhead.  Near the crucible's spout stand stone molds of different shapes, with a pile of fuel within easy reach.  Similar crucibles hang to the north and south.  You also see Forging Society Mistress Yalda, a pile of fuel, a large waste bucket and an ingot cutter.
Obvious exits: north, east, south, west.

[workorders: *** No match was found after 15 seconds, dumping info]

[workorders: messages seen length: 4]

[workorders: message: You want to ask about shadowlings, but don't.]

[workorders: message: [Forging Society, Foundry]]

[workorders: message: Waves of heat, blasting with an almost tangible force, roll from the flames of a brick-lined firepit.  Over the firepit, a blackened granite crucible hangs by stout chains from an oak beam high overhead.  Near the crucible's spout stand stone molds of different shapes, with a pile of fuel within easy reach.  Similar crucibles hang to the north and south.  You also see Forging Society Mistress Yalda, a pile of fuel, a large waste bucket and an ingot cutter.]

[workorders: message: Obvious exits: north, east, south, west.]

[workorders: checked against [/^To whom/i, /order for .* I need \d+ of .* quality/i, /You realize you have items bundled with the logbook/i]]

[workorders]>ask Yalda for challenging Blacksmithing work

You want to ask about shadowlings, but don't.
>;k work
Yalda pulls her notepad and quill from her apron and jots down some notes with a soft sigh.
>'what

You feel your voice return to normal.

You say, "What."
>ask yald for challenging black work
Yalda shuffles through some notes and says, "Alright, this is an order for a shallow metal cup. I need 4 of superior quality, made from any material and due in 105 roisaen.  Please complete the items, bundle them with your logbook and then give me the logbook to complete this order.  Good luck!"

**Comment by rpherbig** [comment]
This might be better handled as part of pick... Some trap recovery logic?

**Comment by OdnaZvezda** [comment]
Maybe, I don't know what other scripts ask NPC's for things, so this may pop up somewhere else.  Workorders will hang if you're still talking like a shadowling though.  Something should be in place to prevent that at the very least.

Pick exits after a trap is sprung(at least when run manually).  I don't know if there is a message that lets you know when the effect of the trap has worn off.  I believe it can be removed with Uncurse, but that isn't always an option.

When I get another trap like this, I can get more messaging when I try to talk while the effect is on and watch for the effect to end.

The time between the trap being sprung and doing the workorder was a couple hours(not a whole lot of chat in TF).

**Comment by rpherbig** [comment]
I think we need to just add this to the 'ask X for Y' logic in workorders...l

**Comment by rcuhljr** [comment]
Added to work orders for now. If you catch the message for that trap being set off start a new issue and we can try and speak after the trap pops just to get the timer going.
