### ISSUE TITLE
Update moonwatch to perceive planets 

### ISSUE THREAD

**Issue by e-volusian** [rpherbig/dr-scripts#3151]
Opening this ticket per discussion with Atanamir, Heji, Gooseberry, Msaia, Rieum, Dankmar on lnet

Wondering about the possibility of adding inner and outer planets to moonwatch ?

Since *observe sky* only shows "inner" planets apparently; for outer planets, must *perceive* each one individually to know what's in the sky.

**Comment by MahtraDR** [comment]
This has been pending for over 3 years now. No interest has been shown on this since it was opened, so closing as stale. Would happily consider a new request as fresh.
