### ISSUE TITLE
Athletics.lic difficulty issue

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#3154]
right at 600 Athletics ranks, my thief is getting hung up with RTs running through Xalas and taking massive bleeders.  I think the threshold needs to be taking up a few ranks.  Probably just barely failing, like 2 seconds RT and falling on my ass.

**Comment by jandersson** [comment]
How do you feel about a setting that you could adjust yourself? I was thinking a minimum rank requirement that you can adjust yourself.

**Comment by mwest152** [comment]
I kinda like keeping things as automated and efficient as possible, but I
imagine someone might have a use for an override setting of some sort.

**Comment by jandersson** [comment]
Override was what I had in mind. I don't have any issues against just upping the rank requirement though. In some cases rank requirements are really approximate and what worked for the developer.

**Comment by BinuDR** [comment]
We had talked about adding a setting to use the undergondola instead if people wanted that.

When I added xalas there was a discussion on where to set the lower limit for using it, I don't remember if we ever got enough data to adjust it fully.  Either that or your stats are lower than the people who tested with similar ranks.  Strength and agility bot help climbing.

**Comment by BinuDR** [comment]
It looks like we added optional args to athletics.lic for this:

>{ name: 'undergondola', regex: /^un.*/i, optional: true, description: 'Climb branch etc undergondola' }
{ name: 'xalas', regex: /^xala.*/i, optional: true, description: 'Climb xalas in zoluren in instead of undergondola' }

**Comment by MahtraDR** [comment]
@rpherbig can close, there are options in place to fix this already.
