### ISSUE TITLE
shape.lic has not option to stamp item

### ISSUE THREAD

**Issue by BL4CKM4GICK** [rpherbig/dr-scripts#3166]
Is this able to be corrected. Cheers.

**Comment by BL4CKM4GICK** [comment]
Awesome!

**Comment by Sarvatt** [comment]
workorders.lic does the stamping though?

**Comment by Sarvatt** [comment]
you're not going to force stamping or anything like that right? it's a waste of time for one-off items since you dont learn from it, workorders has a toggle to enable stamping things

**Comment by Tarhish** [comment]
I don't think it's workorders that does that, but ;forge.  It checks settings.mark_crafted_goods and pulls out your stamp, then marks it if and only if that's true.  I took the steps from that, but changed the fputs into bputs and get_item/stow_items.  So now, upon finishing it does:

```
  def stamp
    return unless @stamp
    get_item('stamp')
    bput("mark my #{@noun} with my stamp", 'carefully hammer the stamp', 'You cannot figure out how to do that')
    pause
    waitrt?
    stow_item('stamp')
  end
```

Where @stamp is only true if mark_crafted_goods.  This is called upon finishing a product.

**Comment by Sarvatt** [comment]
oh you're right, sorry about that! shape really doesn't have stamping support after all this time? wow.

**Comment by Tarhish** [comment]
So my ;tinker script does all the ;shape stuff and also does enhancements -- laminating, lightening, and cable-backing.  So this issue grew a bit into adding stamping and moving over that stuff.  I think it's working, but I don't have all those techniques so Barder's helping cover the last tests.
