### ISSUE TITLE
clean-lumber.lic isn't correctly checking if you are using a wood saw

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#3167]
just had someone report on lnet that it was trying to use a bone saw even though there is a check for wood/woodcutting saw in the script.

**Comment by Tarhish** [comment]
In sheer coincidence I just saw one of the problems Maltaiche was talking about at the same time -- some of the fputs can fail to trigger right and everything piles up and collapses and end up trying to cut a deed or combine lumber and a branch.

**Comment by MahtraDR** [comment]
Closing as stale.
