### ISSUE TITLE
Hunt_only_with_moons

### ISSUE THREAD

**Issue by Saxblue42** [rpherbig/dr-scripts#3169]
Hey guys, absolutely love lich, great work, revived the game for me. Anyway, a thought I had for moon mages is a command that would allow only going into combat trainer when a moon was up. This would allow exclusive use of moon weapons and slivers for TKT/TKS, which would be awesome. 
Thanks for all the hard work.

**Comment by drgabellia** [comment]
This is a GREAT idea!  Would it be hard to code?  Seems like just a check to hunting_buddy to see if a moon was up would work?  Just hoping.......

**Comment by MahtraDR** [comment]
@rpherbig can close this. Katoak added this to t2 in https://github.com/rpherbig/dr-scripts/pull/5410
