### ISSUE TITLE
Request: Mobs/Players in room Window

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#3176]
A window we could start that would show what mobs and/or players were in the room with us. Perhaps even 2 different scripts, one for players and one for mobs.
It's nice to be able to see who/what is in the room at a glance.

**Comment by xtremenerdrage** [comment]
I was thinking just an external window like moonwatch would be pretty nice. I dont know the details on SF vs Profanity vs Genie with those types of windows

**Comment by MahtraDR** [comment]
@xtremenerdrage This is really a thing for your FE, as Sarvatt suggested back in 2018.

@rpherbig Close?
