### ISSUE TITLE
Releasing spell when barbarian

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#3185]
```
[DRPrime]-DR:Quack: "anyone know how to remove from ;crossing-training the   
  part where it keeps trying to RELEASE SPELL?  i'm a 6th circle barb, and i 
  have no use for that" [17:42]           
[DRPrime]-You: "When does it try to release spell?" [17:46]                                   
[DRPrime]-DR:Quack: "Crannach, after kicking the pile of rocks it does RELEASE
  SPELL and RELEASE MANA" [17:47]                                                                            
```
The outdoorsmanship script might be the script this user is referring to

**Comment by Glimmereyes** [comment]
From what I can tell, it currently checks if the Crafting_Training_Spells variable exists, which is defined in Base.yaml.  That causes the check to always pass a True and the script to always perform the Magic_Cleanup section.  It also appears to hit the Magic_Routine sections, but that fails silently.

Changing "return unless @training_spells" to "return if @training_spells.empty?" appears to fix this, but this change would affect all the crafting scripts as well as Outdoorsmanship.lic so would prefer someone more knowledgeable double checks for unintended consequences.
