### ISSUE TITLE
Box Looting when bag full causing timeout.

### ISSUE THREAD

**Issue by lbacker88** [rpherbig/dr-scripts#3198]
So this appears to be related to whirlwind.  After completing a kill, it attempts to switch to the whirlwind weapons, then goes to search the dead mob.  When it finds a box  it stows the left handed weapon, attempts to loot the box, but doesn't drop it when it the bag is full.  It then times out attempting to redraw the left handed weapon.  See Below.

[combat-trainer]>draw
< Moving with amazing force and guile, you draw a steel karambit at a red bear orc raider.  A red bear orc raider barely fails to parry with a pitted steel broadsword.  The karambit lands a vicious strike that crunches bone and rips flesh so that the right leg is left hanging by a few bloody sinews.
Utilizing flawless combat expertise you execute an agile attack combination.
The orc raider looks down with a faintly surprised expression before collapsing upon the ground.
[You're adeptly balanced]
[Roundtime 2 sec.]
[combat-trainer]>stow my karambit
You put your karambit in your kidskin baldric.
>
[combat-trainer]>get my nightstick
You get a steel nightstick with a tempered finish from inside your kidskin baldric.
>
[combat-trainer]>get my bola
>
You get a steel bola from inside your kidskin baldric.
>
[combat-trainer]>stow my bola
You put your bola in your kidskin baldric.
>
[combat-trainer]>get my bola
You get a steel bola from inside your kidskin baldric.
>
[combat-trainer]>loot
You search the orc raider.
The raider was carrying a dull iron skippet!
>
[combat-trainer]>stow my bola
You put your bola in your kidskin baldric.
>
[combat-trainer]>stow skippet
The orc raider decays away, leaving behind only a foul stench.
>
You pick up a dull iron skippet.
You just can't get the iron skippet to fit in the duffel bag, no matter how you arrange it.
>
[combat-trainer]>get my bola
You need a free hand to pick that up.
>
[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 1]
[combat-trainer: message: You need a free hand to pick that up.]
[combat-trainer: checked against [/^You .*(?i-mx:\bbola)/, /^You get.*bola/i, /^What were you referring/i, /But that is already/i, /You are already/i]]
[combat-trainer: for command get my bola]
>
You feel fully rested.
>
Blood pumping loudly, you whip about in a tumultuous fury.

**Comment by Tarhish** [comment]
It's always something with barbarians that I can't easily test, but there looks like this could be because Flags['container-full'] only has the 'isn't any more room for that' message and doesn't trigger on  'You just can't get the iron skippet to fit in the duffel bag, no matter how you arrange it.'  If it had seen the former it would have dropped the box in stow_loot and marked that skippet as something it shouldn't try to loot anymore.

That seem right to anyone else?

**Comment by MahtraDR** [comment]
No longer happens today.
