### ISSUE TITLE
New lockpicking items

### ISSUE THREAD

**Issue by RohkDR** [rpherbig/dr-scripts#3199]
New items added to the corn maze this year allows them to be locked, then picked to practice locksmithing essentially. Was wondering if there would be a way to add this into ;pick or would a separate script be more efficient?

**Comment by BL4CKM4GICK** [comment]
Would like to second this possibility.

**Comment by dakre18** [comment]
Sarvatt suggested he would do it, if someone bought him a box to use. I'm sure he would still love one as a gift ;) lol

**Comment by Sarvatt** [comment]
already got one, just need free time

**Comment by DRWafflesworth** [comment]
Please

**Comment by wstampley** [comment]
This is handled by the current version of `;locksmithing`, so this issue can be closed - @rpherbig
