### ISSUE TITLE
A climbing message not being recognized

### ISSUE THREAD

**Issue by theodore-s-beers** [rpherbig/dr-scripts#3202]
This is in room 1642. The script doesn't pick up this message, then it eventually restarts. So, I wouldn't call it broken, but it wastes a lot of time (thirty seconds per occurrence). The text is as follows:

"You make your way up the tree. Partway up, you make the mistake of looking down. Struck by vertigo, you cling to the tree for a few moments, then slowly climb back down."

I'll also attach a screenshot. Thanks for all of your work on these scripts!

![climbing](https://user-images.githubusercontent.com/32523293/48307147-7cbe1380-e50c-11e8-85f5-9ae5c53e5f72.png)

**Comment by theodore-s-beers** [comment]
Sorry, at first I thought this was part of a training script, but I realized it's go2 trying to reach a certain location. I'm still not sure why it immediately tries climbing again after every other failure message, but doesn't pick up on this one.

**Comment by rpherbig** [comment]
It looks like lich should already be handling this case.

Can you `;e echo LICH_VERSION` and let me know what it outputs?

**Comment by Sarvatt** [comment]
you want to ;e use_lich_fork as per https://github.com/rpherbig/dr-scripts/wiki/First-Time-Setup to fix this to be clearer
