### ISSUE TITLE
Combat-Trainer not recognizing when the arrow is fired.

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#3239]
Check the Log.  

Basically it appears after shooting a critter with my bow it doesn't seem to recognize that the event occurred and times out.

https://pastebin.com/UWsARpYj

**Comment by Sarvatt** [comment]
For now to work around it, you can use an arrow with an adjective instead of just "an arrow", restock will restock them.

**Comment by wscherer420** [comment]
after i loot the creature i'm picking up all the arrows.  That isn't the problem.  It is just that when i FIRE the arrow it times out, like combat-trainer didn't recognize i shot the arrow so the 15 second timer hits.  Ya know what i mean?

**Comment by Sarvatt** [comment]
yeah I do, its because it's assuming you are using a foobar arrow instead of "an arrow"

**Comment by wscherer420** [comment]
ok gotcha. just that with restock in Shard there aren't any color options for arrows

**Comment by wscherer420** [comment]
Roger that.  Thank you
