### ISSUE TITLE
[Crossing-Training] Performance stamina check possibly missing a message?

### ISSUE THREAD

**Issue by TheOnlyTick** [rpherbig/dr-scripts#3272]
[crossing-training]>play polka

You can't muster the strength to perform.
> 
[crossing-training: *** No match was found after 15 seconds, dumping info]

[crossing-training: messages seen length: 3]

[crossing-training: message: Seer's Sense  (Fading)]

[crossing-training: message: Shadows  (19 roisaen)]

[crossing-training: message: You can't muster the strength to perform.]

[crossing-training: checked against [/dirtiness may affect your performance/i, /slightest hint of difficulty/i, /You begin a/i, /You struggle to begin/i, /You're already playing a song/i, /You effortlessly begin/i, /You begin some/i, /You cannot play/i, /Play on what instrument/i, /now isn't the best time to be playing/i, /Perhaps you should find somewhere drier before trying to play/i]]

[crossing-training: for command play polka]

**Comment by rpherbig** [comment]
It looks like `performance.lic` was updated to handle this in 37bcdf08c6cc90c83d02d9f20bf6c9e951a5d8a6 but [crossing-training](https://github.com/rpherbig/dr-scripts/blob/master/crossing-training.lic#L775) was not.

**Comment by Sarvatt** [comment]
submitted a fix, we need to make crossing-training use athletics.lic more and gut this :)
