### ISSUE TITLE
mef branch script

### ISSUE THREAD

**Issue by BL4CKM4GICK** [rpherbig/dr-scripts#3284]

**Comment by BL4CKM4GICK** [comment]
Does anyone have a mef branch script for running 2 branches. I looked around and couldn't see one.

**Comment by CunningRunt** [comment]
Would also be interested in an elegant solution that deconflicts hands/roundtime

**Comment by MahtraDR** [comment]
@rpherbig Can close this. It's what wand_watcher does today.
