### ISSUE TITLE
Issues with ;theurgy

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#3288]

**Comment by drgabellia** [comment]
There are three issues that happened with ;theurgy when I ran it this morning:

#1 It doesn't use GG to make a drink to create the orb for Truffenyi's commune. (It buys taffelberries, instead)
#2 It doesn't do the Tamsine commune (I vaguely remember that after theurgy2 was changed, it DID do Tamsine's commune, but it did it too soon, and thus no theurgy was learned)
#3 It didn't tithe

My setup for whitelist:

theurgy_whitelist:
- tithe
- refectory
- sirese_seed
- pray_badge

theurgy_exp_threshold: 33
theurgy_bead_carving_tool: ritual knife
theurgy_use_prayer_mat: false
theurgy_prayer_mat_room:

*******************

***For ease in reading this log, non-relevent text has been edited out

>;theurgy

--- Lich: theurgy active.

[theurgy]>spells

You recall the spells you have learned from your training. ***edited, just need to see that Gab has GG

In the chapter entitled "Divine Intervention", you have notes on the Aesrela Everild [ae], Heavenly Fires [hf], Resurrection [rezz], Glythtide's Gift [gg], Murrula's Flames [mf], and Fire of Ushnish [fou] spells.

[theurgy]>spells

[theurgy]>rummage /C taffelberries IN MY carryall

You recall the spells you have learned from your training. ***edited, just need to see that Gab has GG

In the chapter entitled "Divine Intervention", you have notes on the Aesrela Everild [ae], Heavenly Fires [hf], Resurrection [rezz], Glythtide's Gift [gg], Murrula's Flames [mf], and Fire of Ushnish [fou] spells.

[theurgy]>count my first oil in my carryall

There are twenty-one parts left of the holy oil.

[theurgy]>count my second oil in my carryall

I could not find what you were referring to.

[theurgy]>pray Glythtide

With a mirthful laugh, you offer up a thankful prayer to Glythtide for his many blessings.

You sense that you are as pure of spirit as you can be, and you are ready for whatever rituals might face you.

You feel that your gods have smiled upon you for your attempts to please them.
[Praying for 6 sec.]

[theurgy]>wealth kronars

  7 gold, 18 bronze, and 11 copper Kronars (7,191 copper Kronars).

[theurgy]>tap my holy water in my chalice

You tap some holy water inside a chalice.

--- Lich: go2 active.  ***edited no need to see the travel rooms

[go2: ETA: 0:00:04 (21 rooms to move through)]

[go2: travel time: 0:00:02]

--- Lich: go2 has exited.

[theurgy]>order 14

Skalliweg gives you a happy grin and puts some sugar-dipped taffelberries on the bar.  You pay him 15 copper kronars for it.

[theurgy]>get taffelberries

You get some sugar-dipped taffelberries from atop a sleek polished bar.

[theurgy]>put taffelberries in my carryall

You put your taffelberries in your multi-strapped carryall.

--- Lich: go2 active.

[go2: ETA: 0:00:00 (4 rooms to move through)] ***edited no need to see travel rooms

--- Lich: go2 has exited.

[theurgy]>forage dirt

You manage to find some dirt.
Roundtime: 4 sec.
A chorus of trilling mews heralds the arrival of a mischievous snow white kitten with taffelberry-stained paws.

[theurgy]>get chalice from my carryall

You get a chalice from inside your multi-strapped carryall.

[theurgy]>commune eluned

You grind some dirt in your fist, allowing the particles to slowly trickle out over your chalice.  The grains seem to melt into water, which overflow from your chalice.  Some of the dirt bypasses the chalice, trickling down in a circle on the ground, a small pool of crytal clear water forming in the center.

[theurgy]>put chalice in my carryall

You feel fully prepared to seek assistance from the Immortals once again.
You put your chalice in your multi-strapped carryall.

[theurgy]>rummage /C taffelberries IN MY carryall

You rummage through a multi-strapped carryall looking for something similar to "taffelberries" and see some sugar-dipped taffelberries.

[theurgy]>tap my taffelberries in my carryall

You tap some sugar-dipped taffelberries inside your multi-strapped carryall.

[theurgy]>get taffelberries from my carryall

You get some sugar-dipped taffelberries from inside your multi-strapped carryall.

[theurgy]>commune truffenyi

You pour your faith and devotion into a plea to Truffenyi, some sugar-dipped taffelberries held aloft in your hands.
A faint voice murmurs in your head, ~ "You are heard, my child." ~

An aromatic white smoke begins to waft off of your offering.  The tendrils fan out in a jumble of twining, weaving movements until they bring about the distinct semblance of an aganylosh'a tree.  Just as its smoky roots finish wrapping your hands, the entirety of the arboreal image is blown away, leaving a glowing Tamsine orb on your palm.

The power of Truffenyi has answered your prayer.

[theurgy]>drop orb

You drop a glowing Tamsine orb.

--- Lich: go2 active.

[go2: ETA: 0:00:03 (17 rooms to move through)] ***edited, no need to see travel rooms

--- Lich: go2 has exited.

[theurgy]>meditate

You bow your head and contemplate your day, the hours before you and those behind, and ready yourself for what lies ahead.

You sense that you are as pure of spirit as you can be, and you are ready for whatever rituals might face you.

You feel that your gods have smiled upon you for your attempts to please them.
Roundtime: 7 sec

[theurgy]>tap my holy water in my chalice

You tap some holy water inside a chalice.

--- Lich: go2 active. ***Edited, no need to see travel rooms

[go2: ETA: 0:00:09 (48 rooms to move through)]

[go2: travel time: 0:00:00]

--- Lich: go2 has exited.

[theurgy]>plant seed

You carefully dig a hole and cover your seed gently.

[theurgy]>get chalice from my carryall

You get a chalice from inside your multi-strapped carryall.

[theurgy]>sprinkle chalice on room

You sprinkle some holy water over the spot where the seed is planted.

You sense that you are as pure of spirit as you can be, and you are ready for whatever rituals might face you.

You feel that your gods have smiled upon you for your attempts to please them.

[theurgy]>put chalice in my carryall

You put your chalice in your multi-strapped carryall.

[theurgy]>remove pilgrim badge

You take off a round mistwood pilgrim's badge edged with a heavy bezel of anlora-avtoma.

[theurgy]>pray pilgrim badge

You think upon the immortals, and the holy places built in their honor by mortals who have heard them speak, or seen the power of their beings.
As you feel your connection to them grow, you sense the eyes of the gods upon you.
Roundtime: 10 sec.

You sense that you are as pure of spirit as you can be, and you are ready for whatever rituals might face you.

You feel that your gods have smiled upon you for your attempts to please them.
A mischievous snow white kitten with taffelberry-stained paws suddenly streaks into the room, pitching headfirst into the ground.

[theurgy]>wear pilgrim badge

You put on a round mistwood pilgrim's badge edged with a heavy bezel of anlora-avtoma.

[theurgy]>commune

After a moment, you see a crystal-clear vision of your god who speaks slowly and deliberately, "Your unwavering faith and devotion pleases me greatly, Gabellia.  Go forth, and continue your works and you shall only attain a greater level of purity." (15/16)

--- Lich: theurgy has exited.

Theurgy:   1143 99.24% cogitating    (24/34)
Please note, if Tasmine's commune was used, Theurgy would be 34/34

**Comment by MahtraDR** [comment]
from running just ```;theurgy``` certainly Tamsine runs.

```
2021-12-18 16:21:52 +1300:[theurgy]>commune tamsine
2021-12-18 16:21:52 +1300:You feel warmth spread throughout your body, making the very ends of your hair tingle.  A vibrant blue nimbus encloses you before fading away.
2021-12-18 16:21:52 +1300:[theurgy]>put my chalice in my backpack
2021-12-18 16:21:53 +1300:You put your chalice in your blue backpack.
2021-12-18 16:21:53 +1300:[theurgy]>remove pilgrim badge
2021-12-18 16:21:53 +1300:You take off a pilgrim's badge.
2021-12-18 16:21:53 +1300:[theurgy]>pray pilgrim badge
```

I'm getting Truffenyi's this weekend, will test GG casting, the code certainly thinks it should cast GG if the cleric has it. I'll dig in.

In 7 weeks of running theurgy multiple times a day, it has never tithed. I do have tithe set in my yaml, so I'll look into that as well. I'll copy your theurgy settings and try. 

I do realize this is a 3yo issue :)

**Comment by MahtraDR** [comment]
note theurgy.lic already uses GG to make wine for Truffenyi's commune, and uses Tamsine's commune. I only fixed tithing, and bead carving with the above.
