### ISSUE TITLE
hangs when attacking flying

### ISSUE THREAD

**Issue by swhalengold** [rpherbig/dr-scripts#3302]
at line 2445
      bput(command, 'Wouldn\'t it be better if you used a melee weapon?', 'Face What?', 'Roundtime', "You aren't close enough to attack", 'It would help if you were closer', 'There is nothing else to face!', 'You must be hidden')

Suggest changing it to this
      bput(command, 'Wouldn\'t it be better if you used a melee weapon?', 'Face What?', 'Roundtime', "You aren't close enough to attack", 'It would help if you were closer', 'There is nothing else to face!', 'You must be hidden', 'flying too high for you to attack.')

Because when hunting mature griffins the following happens;

[combat-trainer]>attack

A silver-tipped mature forest gryphon is flying too high for you to attack.

15 seconds later....

[combat-trainer: checked against [/Wouldn't it be better if you used a melee weapon?/i, /Face What?/i, /Roundtime/i, /You aren't close enough to attack/i, /It would help if you were closer/i, /There is nothing else to face!/i, /You must be hidden/i]]
[combat-trainer: for command attack]

**Comment by Sarvatt** [comment]
whats the message when they land?

**Comment by Sarvatt** [comment]
I'm thinking about something like this

```diff --git a/combat-trainer.lic b/combat-trainer.lic
index 3707ddcb..7c9da327 100644
--- a/combat-trainer.lic
+++ b/combat-trainer.lic
@@ -2442,12 +2442,18 @@ class AttackProcess
         end
       end

-      bput(command, 'Wouldn\'t it be better if you used a melee weapon?', 'Face What?', 'Roundtime', "You aren't close enough to attack", 'It would help if you were closer', 'There is nothing else to face!', 'You must be hidden')
+      bput(command, 'Wouldn\'t it be better if you used a melee weapon?', 'Face What?', 'Roundtime', "You aren't close enough to attack", 'It would help if you were closer', 'There is nothing else to face!', 'You must be hidden', 'flying too high for you to attack')
     end

     pause
     waitrt?

+    if reget(5, 'flying too high for you to attack')
+      waitfor('landing on the ground message')
+    end
+
     if reget(5, 'You can\'t backstab that')
       if game_state.npcs.uniq.length == 1
         game_state.unstabbable(game_state.npcs.first)

**Comment by swhalengold** [comment]
The landing message is this;

A silver-tipped mature forest gryphon flares its wings as it lands with an ungraceful **THUD**.

**Comment by rpherbig** [comment]
How long does it take them to land?

If it's really short (a few seconds), `waitfor` is probably ok. If it's anything longer, I think we should consider the attack 'done' (but not increment the attack counter). That way we keep trying other things, like training abilities, while waiting for the mob to land.

**Comment by swhalengold** [comment]
Seems to me they tend to always land within about 7 seconds, or the next time it attacks.

**Comment by Sarvatt** [comment]
Would this work?

```diff --git a/combat-trainer.lic b/combat-trainer.lic
index 0e8b8347..c2cec06e 100644
--- a/combat-trainer.lic
+++ b/combat-trainer.lic
@@ -2441,12 +2441,19 @@ class AttackProcess
         end
       end

-      bput(command, 'Wouldn\'t it be better if you used a melee weapon?', 'Face What?', 'Roundtime', "You aren't close enough to attack", 'It would help if you were closer', 'There is nothing else to face!', 'You must be hidden')
+      bput(command, 'Wouldn\'t it be better if you used a melee weapon?', 'Face What?', 'Roundtime', "You aren't close enough to attack", 'It would help if you were closer', 'There is nothing else to face!', 'You must be hidden', 'flying too high for you to attack')
     end

     pause
     waitrt?

+    if reget(5, 'flying too high for you to attack')
+      case bput('face next', 'There is nothing', 'You turn to face')
+      when 'There is nothing'
+        pause 5
+      end
+    end
+
     if reget(5, 'You can\'t backstab that')
       if game_state.npcs.uniq.length == 1
         game_state.unstabbable(game_state.npcs.first)```

**Comment by Sarvatt** [comment]
or am I going down the wrong path? engaging another mob if one is flying and retrying, or pausing 5 seconds (number pulled out of my ass) if there is only 1 mob and it's flying before retrying?

**Comment by swhalengold** [comment]
That looks good to me.  100%.  im in combat now so ill paste it into mine and test it
