### ISSUE TITLE
barb analyze support

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#3312]
I wrote this up without hashes, if anyone has the chance could they take a look at how to change accuracy/balance/damage/flame into a hash table? 

line 2926
    @barb_accuracy = settings.barb_accuracy
    echo("  @barb_accuracy: #{@barb_accuracy}") if $debug_mode_ct

    @barb_damage = settings.barb_damage
    echo("  @barb_damage: #{@barb_damage}") if $debug_mode_ct

    @barb_balance = settings.barb_balance
    echo("  @barb_balance: #{@barb_balance}") if $debug_mode_ct

    @barb_flame = settings.barb_flame
    echo("  @barb_flame: #{@barb_flame}") if $debug_mode_ct

line 3375

  def set_barb_balance_flag
    Flags.reset('ct-balance-ready')
  end

line 3380
  def melee_attack_verb
    if currently_whirlwinding
      determine_whirlwind_action
    elsif attack_override
      attack_override
    elsif @use_weak_attacks
      brawling? ? 'gouge' : 'jab'
    elsif @use_barb_combos && !offhand? && !brawling? && (@barb_accuracy || @barb_balance || @barb_damage || @barb_flame)
      update_analyze_array_combo(false) if @analyze_combo_array.empty?
      @analyze_combo_array.empty? ? 'attack' : @analyze_combo_array.shift
    elsif @use_barb_combos && !offhand? && !brawling? && !(@barb_accuracy || @barb_balance || @barb_damage || @barb_flame)
      update_analyze_array(false) if @analyze_combo_array.empty?
      @analyze_combo_array.empty? ? 'attack' : @analyze_combo_array.shift
    else
      'attack'
    end
  end

line 3475

  def update_analyze_array_combo
    ret = false
    if Flags["ct-accuracy-ready"] && @barb_accuracy
      perform_analyze?('accuracy', 50)
      ret = true
    end
    if Flags["ct-damage-ready"] && @barb_damage
      perform_analyze?('damage', 125)
      ret = true
    end
    if Flags["ct-balance-ready"] && @barb_balance
      perform_analyze?('balance', 600)
      ret = true
    end
    if @barb_flame
      perform_analyze?('flame', 0)
      ret = true
    end
    return ret
  end

line 3532

Flags.delete('ct-balance-ready')

barb_accuracy: true
barb_damage: true
barb_balance: true

**Comment by MahtraDR** [comment]
Barb analyze support was added sometime between when this issue was opened, and today. Closing.
