### ISSUE TITLE
Clean-Leather vs Clean-Lumber

### ISSUE THREAD

**Issue by Glimmereyes** [rpherbig/dr-scripts#3313]
Is there a particular reason that these two scripts have different orders for their variables?

;clean-lumber type source storage 
;clean-leather source noun [storage]

**Comment by rpherbig** [comment]
Probably not

**Comment by asechrest** [comment]
I'm working on clean-leather now. I _could_ make the arg order consistent, but that may be a breaking change for anyone who automates the script call with the existing arg order.

Thoughts? If just leave it, we can close this.

**Comment by asechrest** [comment]
Let's close this. I'd like to retain the arg order so that we don't break automated calls to it.

**Comment by MahtraDR** [comment]
Closing as per @asechrest's comment.
