### ISSUE TITLE
Trabe Chalice recasting before it expires

### ISSUE THREAD

**Issue by Tarhish** [rpherbig/dr-scripts#3314]
I mean to look at this myself at some point, but first I have to confront the pain of regexes in spellmonitor.

Combat-trainer and buff get sort of uncertain about whether or not Trabe Chalice is up or not.  In general, it'll try to recast Trabe Chalice one extra time during each cast's duration, which fails since the spell can't be overwritten without higher mana.  

It doesn't get stuck recasting it, it just tries once.  For example, if I prebuff TRC then when combat trainer starts up it'll try buffing Trabe Chalice, fail, then move on.  It won't try again until it fades.  I'm guessing it's something weird with the way it presents in ActiveSpells.

```
Trabe Chalice  (intact, 8 roisaen)
Trabe Chalice  (intact, 1 roisan)
```

**Comment by jandersson** [comment]
TRC was a source of pain for me as well. It might be worth having spellmonitor strip everything after the first comma (plus the whitespace) to get it reading as a regular spell.

**Comment by Sarvatt** [comment]
does the spell ever show if its not intact?

**Comment by jandersson** [comment]
Yea, it has various stages of breakage

**Comment by Tarhish** [comment]
Yeah, it's got descriptions like cracked, shattered, smashed, all the way
down.  It couldn't give a percentage, Noooooo.



On Jan 8, 2019 3:35 PM, "Robert Hooker" <notifications@github.com> wrote:

does the spell ever show if its not intact?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rpherbig/dr-scripts/issues/3314#issuecomment-452442344>,
or mute the thread

**Comment by Sarvatt** [comment]
ok took Cran's suggestion and ignored everything before the comma inside the parenthesis

**Comment by Sarvatt** [comment]
ok no, i think i found the real problem here, there is something else wrong.. spellmonitor does catch it fine as long as its the first spell in activespells, everything but the active spell gets added to the next active spell, what I pushed doesn't do anything different.

https://rubular.com/r/OIIbeY5Y4HoA7i

**Comment by Tarhish** [comment]
Ahah, so that might be the answer to the mystery.  I couldn't explain on the surface of it why it wouldn't see TRC, cast it and fail, but then not cast it again.  Maybe that reset it to first position, which made it happy?

I'll have to see if that makes sense once I get home or if I'm just talking crap.

**Comment by Tarhish** [comment]
There were rare times when it would cast a second time in the fight.  That could have happened when another buff displaced it from position one. I don't often hunt for longer than fifteen minutes at a time, so I could imagine that being a rare occurrence.

**Comment by Tarhish** [comment]
Some fiddling and investigation while working on starlight stuff revealed that this was caused by me fiddling with an expire: message.  It wasn't supposed to be used the way I used it.  So forget this issue.  Instead I'm going to look at the neatest way to stop TRC from recasting while 'fading'

**Comment by Tarhish** [comment]
I don't think this is a problem -- I was just using it incorrectly
