### ISSUE TITLE
Bescort will pause/hang trying to get into red_gold atiket

### ISSUE THREAD

**Issue by Maledar** [rpherbig/dr-scripts#3320]
https://pastebin.com/CfmnsbK6

For some reason just stops pushing, maybe we can add something to restart the process if it matches the stop pushing?

**Comment by Glimmereyes** [comment]
It's already matching for "You stop pushing" and should be restarting the push section.   I could remove the anchors in case that's causing some strange issue if no one else spots a problem.

Did it catch properly when it attempted to go through the blocked tunnel?

**Comment by Maledar** [comment]
Doesn't seem to catch properly, its a very random hang sometimes I go through sometimes I don't.  This is a log of what happens when I don't. And ;status-monitor seems to catch something but I have to manually push the boulder then retreat/kneel to get in


https://pastebin.com/SM7xXY8Q

**Comment by MahtraDR** [comment]
Closing this as stale, and can't reproduce today.
