### ISSUE TITLE
include Body Elixir in Alchemy Work Orders

### ISSUE THREAD

**Issue by dakre18** [rpherbig/dr-scripts#3325]
I have checked, Body Elixirs can be made with store bought ojhenik, and works with the scripts if work_order: is changed to true and herb1_stock: is changed to 12.

**Comment by Tarhish** [comment]
Do you happen to know if a 'body draught' could be added this way as well? It looks like that only needs ojhenik too, but I don't have anyone who does alchemy.

**Comment by rpherbig** [comment]
Fixed in b22745f
