### ISSUE TITLE
crafting recipes beyond abilities should be skipped

### ISSUE THREAD

**Issue by dakre18** [rpherbig/dr-scripts#3326]
After studying the book, recipes should be skipped and go back for another work order/recipe from the following messages:

> You review the body elixir instructions and quickly realize the design is far beyond your abilities.

> You scan the general draught instructions with a glance and quickly realize the design is far beyond your abilities.

tested with alchemy, forging, outfitting, and engineering. each book tested uses the same 2 lines above, and those recipes are nearly impossible to complete for work orders.

**Comment by dakre18** [comment]
after thinking about this a bit more, i think this should be a true/false setting.
ignore work order diff = true, then you would still try, even if you cannot make it.
if it's false, to prevent an infinite loop, either remove it from training, or put a warning to reduce difficulty if you cannot complete the work order.

**Comment by jandersson** [comment]
How can this issue be recreated? I ask because I don't think I've run into it before.

**Comment by jandersson** [comment]
You can configure your workorder difficulty as a setting on the craft level.  You'll ignore the difficulty in any case, you make it, its shit and you cant bundle it to your workorder log.

**Comment by dakre18** [comment]
it's mostly when you try to do hard work orders if i remember correctly, and it sees a work order for an item i don't have techniques for and is set to true in the base-recipes.yaml. Then it spends time trying to work a work order it'll never finish, since the recipe is beyond my abilities.

I had it set to hard, so i could earn more from the work orders, using the techniques i know.

**Comment by MahtraDR** [comment]
Closing this. In the intervening time since this was opened... the general wisdom became to always buy master books. That's just how it goes today.
