### ISSUE TITLE
combat-trainer.lic - include release cambrinth with release spell/mana

### ISSUE THREAD

**Issue by daedelis** [rpherbig/dr-scripts#3336]
combat-trainer.lic - instances of bput 'release spell'/'release mana' should include bput 'release #{@cambrinth}' to minimize probability of future backfire

**Comment by daedelis** [comment]
combat-trainer.lic - ignite does not need to be release/recast if interim weapon change action list is strictly shape|turn (summoned weapons)

**Comment by Sarvatt** [comment]
release only breaks the link, it doesn't remove the mana from the cambrinth. you want to use cambrinth_invoke_exact_amount: true if you are worried about using extra mana

**Comment by daedelis** [comment]
Worried about the next spell using any cambrinth at all, if it otherwise isn't configured to do so.

**Comment by MahtraDR** [comment]
Today we have `cambrinth_invoke_exact_amount` which makes this moot. Closing as no longer relevant.
