### ISSUE TITLE
NOT an issue...Just a change?

### ISSUE THREAD

**Issue by Kyasix** [rpherbig/dr-scripts#3341]
I was having trouble with workorders being skipped, since my hometown was set to langenfirth and no forge is in the area.  I solved this problem by splitting hometown: into hometown: and crafttown: in my yaml and modifying a copy or workorders.lic and smith.lic to read crafttown instead of hometown from yaml.  (i call the modified workorders.lic from a before: ) works like a charm, i can keep my training manager doing its thing in lang or theren and choose what town i want it to run to for crafting.  I can show the changes i made if anyone is interested.

**Comment by Sarvatt** [comment]
look at how leth deriel is set up for a way to do this, add an anchor to riverhaven and make the crafting stuff for langenfirth use that anchor

**Comment by Tarhish** [comment]
We'd also want to copy in the part data so there's a Langenfirth entry for each of those sections on the bottom -- and just use the Riverhaven room numbers.  Basically just copying each haven entry and renaming it Langenfirth
