### ISSUE TITLE
Dependency Install failure

### ISSUE THREAD

**Issue by Uerne** [rpherbig/dr-scripts#3355]
I looked up the problem and tried this fix https://github.com/rpherbig/dr-scripts/wiki/Solving-RubyGems-Error. 

Didn't do anything though. Here's my return message on the ;dependency install command. 

- Lich: dependency active.
Removing lich autostarts for existing scripts...
--- Lich: error: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version
	C:/Ruby200/lib/ruby/2.0.0/net/http.rb:917:in `connect'
	C:/Ruby200/lib/ruby/2.0.0/net/http.rb:917:in `block in connect'
--- Lich: dependency has exited.

Any help would be appreciated.

**Comment by Sarvatt** [comment]
You need to use a newer ruby 2.0 release

**Comment by Sarvatt** [comment]
https://dl.bintray.com/oneclick/rubyinstaller/rubyinstaller-2.0.0-p648.exe

**Comment by Uerne** [comment]
Thank you. I just installed ruby from an old download. I'll give it a shot

**Comment by Uerne** [comment]
That did the trick, thank you
