### ISSUE TITLE
Athletics STILL breaks, even with performance_pause: 5

### ISSUE THREAD

**Issue by proctophage** [rpherbig/dr-scripts#3368]
https://pastebin.com/WrWwLCTe

I'm not lagging, the scripts are just weaved together very poorly.

**Comment by Sarvatt** [comment]
up the delay more or offer an alternative way to fix it

**Comment by jandersson** [comment]
It looks like the delay is not the issue

**Comment by proctophage** [comment]
The delay is not the issue. It's the way performance is called and stopped by athletics, study-art, and first-aid.

This happened with performance_pause: 10 in my yaml, and I was not lagging at all. 
https://pastebin.com/eLAVSfnh

It happens most often when transitioning to or from scripts that call performance. It tries to study statue, sees a line from performance, and immediately tries to study the next thing. Study art then stops performance and exits, and athletics starts. Athletics calls performance and then does nothing forever.

**Comment by proctophage** [comment]
Since I know this will never be fixed, the workaround I've got for this issue is to put a go2 immediately following athletics before starting any other script. This ensures that roundtime will be completed and performance will cleanup properly before starting any new script.
