### ISSUE TITLE
wishlist: add an option to turn in tools to the clerk for workorders

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#3382]
it can just call the clerk-tools script if an option is set.

**Comment by MahtraDR** [comment]
Closing as won'tfix. The way t2 works, it's very simple to just call clerk-tools before and after.

![image](https://user-images.githubusercontent.com/93822896/213828110-61deee58-ee7c-4a28-9eb9-32f5359aaec7.png)
