### ISSUE TITLE
app pouch: appraises wrong pouch in combat

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#3389]
Love the new app pouch setting for combat, however it appraises Gab's tart pouch instead of her gem pouch.  (Her tart pouch defaults to the first pouch every time her gear is sorted)  

You retreat from combat.

[combat-trainer]>app my pouch quick

The tart pouch is incredibly pliant.
It appears that the tart pouch can be worn attached to a belt.
You are certain that the tart pouch weighs exactly 2 stones.
The tart pouch looks to be custom-made.
You are certain that the tart pouch is worth exactly nothing.
The tart pouch looks to bear your familiar marks of registration.
Roundtime: 5 seconds.
The Xala'shar slayer closes to pole weapon range on you!
The Xala'shar slayer closes to pole weapon range on you!
The Xala'shar archimage begins to advance on you!
The Xala'shar archimage is still a distance away from you and is closing steadily.

You feel fully attuned to the mana streams again.
A hulking Xala'shar archimage briskly sweeps west with a malicious laugh, a fisted hand held at the small of its back.
The Xala'shar slayer closes to melee range on you!
The Xala'shar slayer closes to melee range on you!
The Xala'shar archimage begins to advance on you!
The Xala'shar archimage is still a distance away from you and is closing steadily.
The serpent earcuff coils, sensing your danger.  Tiny fangs suddenly puncture your flesh, but the expected pain doesn't come.  Instead, soothing warmth radiates outward from the bite, leaving you feeling a little better than before.
Your formation of a targeting pattern around a hulking Xala'shar archimage has completed.
The Xala'shar archimage closes to pole weapon range on you!
* A hulking Xala'shar archimage sidesteps and bashes at you.  You dodge.  
[You're bruised, mighty, nimbly balanced and in good position.]
* A hulking Xala'shar slayer slices a double-bladed broadsword with a tattered cloth-wrapped hilt at you.  You barely block with a diamondwood shield reinforced with silversteel spikes.  
[You're bruised, mighty, nimbly balanced and have slight advantage.]
* A hulking Xala'shar slayer sweeps low at you.  You barely block with a diamondwood shield reinforced with silversteel spikes.  
[You're bruised, mighty, nimbly balanced and in better position.]
A cage of shadowy tendrils coalesces around a hulking Xala'shar slayer.
The Xala'shar archimage closes to melee range on you!
You feel fully attuned to the mana streams again.
The Xala'shar archimage closes to pole weapon range on you!

[combat-trainer: *** No match was found after 15 seconds, dumping info]

[combat-trainer: messages seen length: 63]

[combat-trainer: message: The Xala'shar archimage closes to pole weapon range on you!]

[combat-trainer: message: You feel fully attuned to the mana streams again.]

[combat-trainer: message: The Xala'shar archimage closes to melee range on you!]

[combat-trainer: message: A cage of shadowy tendrils coalesces around a hulking Xala'shar slayer.]

[combat-trainer: message: Soul Shield  (30 roisaen)]

[combat-trainer: message: Persistence of Mana  (OM)]

[combat-trainer: message: Glythtide's Gift  (OM)]

[combat-trainer: message: Auspice  (OM)]

[combat-trainer: message: Murrula's Flames  (OM)]

[combat-trainer: message: Benediction  (OM)]

[combat-trainer: message: Major Physical Protection  (21 roisaen)]

[combat-trainer: message: Shield of Light  (OM)]

[combat-trainer: message: Bless  (OM)]

[combat-trainer: message: Hydra Hex  (Indefinite)]

[combat-trainer: message: Osrel Meraud  (89%)]

[combat-trainer: message: Centering  (20 roisaen)]

[combat-trainer: message: Gauge Flow  (19 roisaen)]

[combat-trainer: message: Protection from Evil  (23 roisaen)]

[combat-trainer: message: Minor Physical Protection  (21 roisaen)]

[combat-trainer: message: Righteous Wrath  (23 roisaen)]

[combat-trainer: message: [You're bruised, mighty, nimbly balanced and in better position.]]

[combat-trainer: message: * A hulking Xala'shar slayer sweeps low at you.  You barely block with a diamondwood shield reinforced with silversteel spikes.  ]

[combat-trainer: message: [You're bruised, mighty, nimbly balanced and have slight advantage.]]

[combat-trainer: message: * A hulking Xala'shar slayer slices a double-bladed broadsword with a tattered cloth-wrapped hilt at you.  You barely block with a diamondwood shield reinforced with silversteel spikes.  ]

[combat-trainer: message: [You're bruised, mighty, nimbly balanced and in good position.]]

[combat-trainer: message: * A hulking Xala'shar archimage sidesteps and bashes at you.  You dodge.  ]

[combat-trainer: message: The Xala'shar archimage closes to pole weapon range on you!]

[combat-trainer: message: Your formation of a targeting pattern around a hulking Xala'shar archimage has completed.]

[combat-trainer: message: The serpent earcuff coils, sensing your danger.  Tiny fangs suddenly puncture your flesh, but the expected pain doesn't come.  Instead, soothing warmth radiates outward from the bite, leaving you feeling a little better than before.]

[combat-trainer: message: The Xala'shar archimage is still a distance away from you and is closing steadily.]

[combat-trainer: message: The Xala'shar archimage begins to advance on you!]

[combat-trainer: message: The Xala'shar slayer closes to melee range on you!]

[combat-trainer: message: The Xala'shar slayer closes to melee range on you!]

[combat-trainer: message: A hulking Xala'shar archimage briskly sweeps west with a malicious laugh, a fisted hand held at the small of its back.]

[combat-trainer: message: Soul Shield  (30 roisaen)]

[combat-trainer: message: Persistence of Mana  (OM)]

[combat-trainer: message: Glythtide's Gift  (OM)]

[combat-trainer: message: Auspice  (OM)]

[combat-trainer: message: Murrula's Flames  (OM)]

[combat-trainer: message: Benediction  (OM)]

[combat-trainer: message: Major Physical Protection  (21 roisaen)]

[combat-trainer: message: Shield of Light  (OM)]

[combat-trainer: message: Bless  (OM)]

[combat-trainer: message: Hydra Hex  (Indefinite)]

[combat-trainer: message: Osrel Meraud  (91%)]

[combat-trainer: message: Centering  (21 roisaen)]

[combat-trainer: message: Gauge Flow  (19 roisaen)]

[combat-trainer: message: Protection from Evil  (23 roisaen)]

[combat-trainer: message: Minor Physical Protection  (22 roisaen)]

[combat-trainer: message: Righteous Wrath  (24 roisaen)]

[combat-trainer: message: You feel fully attuned to the mana streams again.]

[combat-trainer: message: [DRPrime]-DR:Uerne: "NP"]

[combat-trainer: message: The Xala'shar archimage is still a distance away from you and is closing steadily.]

[combat-trainer: message: The Xala'shar archimage begins to advance on you!]

[combat-trainer: message: The Xala'shar slayer closes to pole weapon range on you!]

[combat-trainer: message: The Xala'shar slayer closes to pole weapon range on you!]

[combat-trainer: message: Roundtime: 5 seconds.]

[combat-trainer: message: The tart pouch looks to bear your familiar marks of registration.]

[combat-trainer: message: You are certain that the tart pouch is worth exactly nothing.]

[combat-trainer: message: The tart pouch looks to be custom-made.]

[combat-trainer: message: You are certain that the tart pouch weighs exactly 2 stones.]

[combat-trainer: message: It appears that the tart pouch can be worn attached to a belt.]

[combat-trainer: message: The tart pouch is incredibly pliant.]

[combat-trainer: checked against [/You sort/i, /Appraise what/i, /You cannot appraise/i]]

[combat-trainer: for command app my pouch quick]

**Comment by drgabellia** [comment]
I'm closing this issue.  With sort_auto_head option I can always leave my gem pouch in the #1 position for appraisal, it's an easy workaround.

**Comment by Sarvatt** [comment]
this is an easy fix, no need to close it. i'm submitting a fix now.
