### ISSUE TITLE
;repository download dependency.lic failing

### ISSUE THREAD

**Issue by robbintt** [rpherbig/dr-scripts#3396]
I've set this up on a linux machine and connected a custom python client doing normal client stuff. 

lich is currently living in `/root/clones/lich/` and being run as root -- it's a single purpose machine, probably will be dockerized eventually...

`pylanthia.py`, the client, is running as a user.

I'm running into a strange issue:

```
> ;repository download dependency.lic
--- Lich: repository active.
[repository: error: file not found]
--- Lich: repository has exited.
```

**Comment by robbintt** [comment]
I tried re-extracting the lich zip and got the same thing.

https://lichproject.org/download/lich-4.6.49.zip

**Comment by Sarvatt** [comment]
you're running a client as a user in a root owned directory it can't write to?

**Comment by robbintt** [comment]
i tested running the client as root and it didn't have any effect.

I also think the lich process would be the one writing to the lich scripts directory, and the error doesn't reflect that (although the error is pretty low information).

**Comment by robbintt** [comment]
Manually specifying that helps some detection stuff, for example `links` works.

However, the original info in this ticket is still the same.

Maybe it is an authentication issue against the lich servers?

Do you know how lich goes about authenticating and pulling down new data?

I can say for certain that lich.rbw gets replaced every time I run it. I comment out the line that pulls in the the gtk gem, around line 600, and it gets uncommented whenever I run lich.

**Comment by robbintt** [comment]
Interestingly, `dependency.lic` is not in `;repository list`
```
                      file   game    size          last update          author    DLs    rating
---------------------------   ----   -----   ------------------   -------------   ----   -------
            add-map-tag.lic     dr    0.9k   2014-12-21 11:35pm          nobody     31
             allpurpose.lic     dr    8.4k   2014-12-21 11:35pm          nobody     57
                 alpick.lic     dr    6.4k   2014-12-21 11:35pm          nobody     15
              appraisal.lic     dr    0.4k   2014-12-21 11:36pm          nobody     87
                  astro.Cmd     dr    2.3k   2014-12-21 11:36pm          nobody     28
             attunement.lic     dr    0.3k   2014-12-21 11:36pm          nobody     66
              autocount.lic     dr    0.5k   2014-12-21 11:36pm          nobody      8
             autoinvoke.lic     dr    0.2k   2014-12-21 11:37pm          nobody      8                                           autoinvoke.txt     dr    0.2k   2014-12-21 11:37pm          nobody      3
               autopick.lic     dr    2.8k   2014-12-21 11:37pm          nobody     28
              brikhouse.lic     dr    4.8k   2014-12-21 11:37pm          nobody      6
                collect.lic     dr    0.6k   2014-12-21 11:37pm          nobody     93                                  combatspellpractice.lic     dr    1.9k   2014-12-21 11:37pm          nobody     52
            commodities.lic     dr    7.2k   2014-12-21 11:41pm          nobody     12
          companionwalk.lic     dr    0.8k   2014-12-21 11:41pm          nobody      7
                  count.lic     dr    2.3k   2014-12-21 11:41pm          nobody      5                                                court.lic     dr    1.2k   2014-12-21 11:41pm          nobody     12
                 danger.lic     dr    0.7k   2014-12-21 11:41pm          nobody     29
              drinfomon.lic     dr   22.7k   2016-03-08 10:41am          nobody    314
            echo-stream.lic     dr    0.4k   2014-12-21 11:41pm          nobody      9
               enchante.lic     dr    0.6k   2014-12-21 11:41pm          nobody     19
               favorhug.lic     dr    2.3k   2014-12-21 11:41pm          nobody     26
                 favors.lic     dr    3.3k   2014-12-21 11:41pm          nobody    125
                  GmSoy.lic     dr   12.1k   2014-12-21 11:41pm          nobody     17
              healother.lic     dr    1.8k   2014-12-21 11:41pm          nobody     40
               healself.lic     dr    2.9k   2014-12-21 11:41pm          nobody     59
               herbheal.lic     dr    3.8k   2014-12-21 11:41pm          nobody     59
                 hummer.lic     dr    3.5k   2014-12-21 11:41pm          nobody     12
```

**Comment by rcuhljr** [comment]
Odd, Someone else can upload a new version of dependency if they want. Maybe because I haven't logged into lich in so long it poofed since it was under my control? Someone could have deleted it if I lost authorship as well. I mean downloading it via dependency is identical to just downloading it from git, it's just simpler for most users and reduces the risk of naming the file incorrectly or messing up line endings or a myriad of other copy and paste errors that can arise.

**Comment by robbintt** [comment]
I manually added `dependency.lic` to the scripts directory and ran it. I think I am nearly 100% up and running now. I will have to revise my install process until it is reproducible and have some rough edges around the lich update process and the `require gtk` GTK dependency.

**Comment by jandersson** [comment]
Its in `;repository` still. It looks like theres still some filtering going on there on your end. Look at the dates and authors (assuming thats the full list). Another thought is to wget it from github (`wget https://raw.githubusercontent.com/rpherbig/dr-scripts/master/dependency.lic`)

**Comment by robbintt** [comment]
@jandersson putting it there manually seems to have worked. i might be totally fixed now, or not.

**Comment by jandersson** [comment]
Got it, wasn't sure if you were trying to automate this. Though i suppose once dependency runs itll update.
