### ISSUE TITLE
Could someone add a single line to combat for TM foci....getting quite a bit of scroll

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#3397]
I'm a pest, sorry guys.  But when I wear my TM foci I get a TON of scroll.  (I have it listed in my gear, but that doesn't seem to make a difference) Just need to have a single line added............somewhere.....to stop the scroll:  (or if there is somewhere I can add this line, please point me in the right direction)

[combat-trainer]>wear my toe-ring
>
You put a pale tyrium toe-ring displaying a delicate amaranth Eu's promise crystal onto your feet.
>
The searing lights fade from around a lava drake.
>
The drake grows fully molten, melting into the ground for a few moments before emerging a few feet away.
>
* A lava drake darts forward and slashes at you.  You dodge.  
[You're mighty, adeptly balanced and overwhelming your opponent.]
>
* A lava drake darts forward and slashes at you.  You barely block with a diamondwood shield reinforced with silversteel spikes.  
[You're mighty, adeptly balanced and in strong position.]
>
* A lava drake lashes at you.  You evade.  
[You're mighty, adeptly balanced and in superior position.]
>
A lava drake appears less distracted.
>
A lava drake rears back and opens its fiery maw, unleashing a gout of scorching air and dust directly into your eyes!
The cloud of dirt sailing towards your face takes you completely by surprise.
Dust flies into your eyes and clumps up, seriously hindering your vision!
>
The clumps of dirt stinging your eyes cause your vision to go spotty and black!
Roundtime: 3 sec.
>
You feel fully attuned to the mana streams again.
>
* A lava drake lashes at you.  You barely block with a diamondwood shield reinforced with silversteel spikes.  
[You're mighty, adeptly balanced and in very strong position.]
>
* A lava drake swipes at you.  You partially block with a diamondwood shield reinforced with silversteel spikes.  
[You're mighty, adeptly balanced and in superior position.]
>
A cage of shadowy tendrils coalesces around a lava drake.
A cage of shadowy tendrils coalesces around a lava drake.
>
* A lava drake lunges forward and swings at you.  You evade.  
[You're mighty, adeptly balanced and overwhelming your opponent.]
>
[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 58]
[combat-trainer: message: Soul Shield  (24 roisaen)]
[combat-trainer: message: Major Physical Protection  (34 roisaen)]
[combat-trainer: message: Centering  (33 roisaen)]
[combat-trainer: message: Protection from Evil  (36 roisaen)]
[combat-trainer: message: Benediction  (OM)]
[combat-trainer: message: Shield of Light  (OM)]
[combat-trainer: message: Persistence of Mana  (OM)]
[combat-trainer: message: Righteous Wrath  (34 roisaen)]
[combat-trainer: message: Glythtide's Gift  (OM)]
[combat-trainer: message: Auspice  (OM)]
[combat-trainer: message: Murrula's Flames  (OM)]
[combat-trainer: message: Bless  (OM)]
[combat-trainer: message: Gauge Flow  (71 roisaen)]
[combat-trainer: message: Hydra Hex  (Indefinite)]
[combat-trainer: message: Minor Physical Protection  (34 roisaen)]
[combat-trainer: message: Osrel Meraud  (93%)]
[combat-trainer: message: [You're mighty, adeptly balanced and overwhelming your opponent.]]
[combat-trainer: message: * A lava drake lunges forward and swings at you.  You evade.  ]
[combat-trainer: message: A cage of shadowy tendrils coalesces around a lava drake.]
[combat-trainer: message: A cage of shadowy tendrils coalesces around a lava drake.]
[combat-trainer: message: [You're mighty, adeptly balanced and in superior position.]]
[combat-trainer: message: * A lava drake swipes at you.  You partially block with a diamondwood shield reinforced with silversteel spikes.  ]
[combat-trainer: message: [You're mighty, adeptly balanced and in very strong position.]]
[combat-trainer: message: * A lava drake lashes at you.  You barely block with a diamondwood shield reinforced with silversteel spikes.  ]
[combat-trainer: message: You feel fully attuned to the mana streams again.]
[combat-trainer: message: Roundtime: 3 sec.]
[combat-trainer: message: The clumps of dirt stinging your eyes cause your vision to go spotty and black!]
[combat-trainer: message: Dust flies into your eyes and clumps up, seriously hindering your vision!]
[combat-trainer: message: The cloud of dirt sailing towards your face takes you completely by surprise.]
[combat-trainer: message: A lava drake rears back and opens its fiery maw, unleashing a gout of scorching air and dust directly into your eyes!]
[combat-trainer: message: [Trade][Deimeter] "looking to trade resources (tyrium, haledroth) for a fire shard tattoo from HotRF, send me a thought."]
[combat-trainer: message: A lava drake appears less distracted.]
[combat-trainer: message: [You're mighty, adeptly balanced and in superior position.]]
[combat-trainer: message: * A lava drake lashes at you.  You evade.  ]
[combat-trainer: message: [You're mighty, adeptly balanced and in strong position.]]
[combat-trainer: message: * A lava drake darts forward and slashes at you.  You barely block with a diamondwood shield reinforced with silversteel spikes.  ]
[combat-trainer: message: Soul Shield  (24 roisaen)]
[combat-trainer: message: Major Physical Protection  (34 roisaen)]
[combat-trainer: message: Centering  (33 roisaen)]
[combat-trainer: message: Protection from Evil  (36 roisaen)]
[combat-trainer: message: Benediction  (OM)]
[combat-trainer: message: Shield of Light  (OM)]
[combat-trainer: message: Persistence of Mana  (OM)]
[combat-trainer: message: Righteous Wrath  (35 roisaen)]
[combat-trainer: message: Glythtide's Gift  (OM)]
[combat-trainer: message: Auspice  (OM)]
[combat-trainer: message: Murrula's Flames  (OM)]
[combat-trainer: message: Bless  (OM)]
[combat-trainer: message: Gauge Flow  (72 roisaen)]
[combat-trainer: message: Hydra Hex  (Indefinite)]
[combat-trainer: message: Minor Physical Protection  (34 roisaen)]
[combat-trainer: message: Osrel Meraud  (93%)]
[combat-trainer: message:  * Mystic Blade Theodrid Rindarios joins the adventure.]
[combat-trainer: message: [You're mighty, adeptly balanced and overwhelming your opponent.]]
[combat-trainer: message: * A lava drake darts forward and slashes at you.  You dodge.  ]
[combat-trainer: message: The drake grows fully molten, melting into the ground for a few moments before emerging a few feet away.]
[combat-trainer: message: The searing lights fade from around a lava drake.]
[combat-trainer: message: You put a pale tyrium toe-ring displaying a delicate amaranth Eu's promise crystal onto your feet.]
[combat-trainer: checked against [/You sling/i, /You attach/i, /You .* unload/i, /You slide/i, /You place/i, /close the fan/i, /You hang/i, /You spin/i, /You strap/i, /You carefully loop/i, /You don't seem to be able to move/i]]
[combat-trainer: for command wear my toe-ring]
[combat-trainer]>wield my sickle

**Comment by Tarhish** [comment]
That's a good looking ring to serve as a focus.  I'm pretty sure the PR I just opened fixes the line that's causing the problem -- equip manager hasn't had anyone with a worn weapon that wears with a 'You put' message before, and since combat trainer treats foci as weapons you got to be the first to find that out :-)
