### ISSUE TITLE
Combat-trainer requires common to run first

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#34]
If you run common first (or have it autostart) then combat-trainer will run.

Output from a clean Lich run:
>;combat-trainer
--- Lich: combat-trainer active.
--- Lich: error: uninitialized constant Scripting::SetupProcess::DRC
 combat-trainer:20:in `<class:SetupProcess>'
 combat-trainer:19:in `script'
--- Lich: combat-trainer has exited.

**Comment by rpherbig** [comment]
I'm not sure that running common manually will fix this. I just tried it (on a clean run of StormFront/Lich) and got this:

>;common
--- Lich: error: undefined class/module Scripting::Item
C:/Users/Robert/Desktop/lich/lich.rbw:2292:in `load'
C:/Users/Robert/Desktop/lich/lich.rbw:2292:in `block (2 levels) in <module:Vars>'
C:/Users/Robert/Desktop/lich/lich.rbw:2282:in `synchronize'

**Comment by rcuhljr** [comment]
Pretty sure this is a non issue. Can you reproduce any real problems now?

**Comment by rpherbig** [comment]
It's still kind of a problem. Common isn't autostarted by default, and the error message is completely unintuitive to anyone that isn't us.
