### ISSUE TITLE
Allow storage of crafting tools

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#341]
Part 1, allow storage of tools in the crafting hall 10 item storage system.

Part 2, allow storage of tools in vaults?

**Comment by jayRyan24** [comment]
I think the idea of using the vault is good. - Chuno

**Comment by Ilfarian** [comment]
I see this is already an open item, so I don't want to duplicate it, just bump it.

Vaults wouldn't help us FTP folk (though may be superior for subscribers), but I third the tool storage at the crafting hall suggestion!
