### ISSUE TITLE
Textbook Reading during Combat to Train First Aid

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#3423]
Any chance we can get this done?  Would be awesome!

**Comment by MahtraDR** [comment]
This is a very old issue, with no follow up since. Would be happy to revisit this topic as fresh when if it comes up again.

**Comment by MahtraDR** [comment]
Note also that today we have dissect to train FA in combat. Beats reading a book! :)

**Comment by rpherbig** [comment]
Nothing beats hands-on (or is it _hands-in_?) experience
