### ISSUE TITLE
Barbarian Ability Support need for....

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#3424]
Tried adding my abilities to my YAML and most aren't supported.  Got this message on each:

Barb ability 'Everild' not yet supported. Please make an issue on Github

- Everild
- Buffalo 
- Flame
- Power

**Comment by rpherbig** [comment]
For anyone interested in picking this up, you can add entries here: https://github.com/rpherbig/dr-scripts/blob/bb98adbace693692e4a9e386b20dff1e19c75774/data/base-spells.yaml#L243-L247

**Comment by Tarhish** [comment]
I'd be willing to add these, but without a barbarian I don't know the usage or have the ability to test it.

@wscherer420 , if you have the messages and syntax for those abilities then that would make this easy.

**Comment by wscherer420** [comment]
Not sure if this is what you need.  Not very good at being a Barbarian.  See below @Tarhish 

roar everild
The fury of Everild's Rage burns in your soul, and your roar is filled with that fury.  Rage intimidates, and fear weakens.  Foes shall fall before you, weakened and humiliated by the expression of your strength.
A giant thicket viper appears less confident in its ability to defend itself.
Roundtime: 2 sec.
roar everild
The fury of Everild's Rage burns in your soul, and your roar is filled with that fury.  Rage intimidates, and fear weakens.  Foes shall fall before you, weakened and humiliated by the expression of your strength.
A giant thicket viper resists the roar's efforts to further debilitate its confidence.
Roundtime: 2 sec.


form buffalo
Lurching forward, you reposition your burden and mimic the steady movements of the Buffalo.
Roundtime: 2 sec.
The powerful gait of the Buffalo form leaves your mind and burden hampers your movements once again.

**Comment by Tarhish** [comment]
Like rpherbig said they'd look like
```
Buffalo:
  type: form
  start_command: form buffalo
  activated_message: Lurching forward, you reposition your burden and mimic
  expired_message: finish practicing the Form of the Buffalo  (?????)
```
We'd need the expiry messages too, since I'm just guessing. Though if you're at all interested in working on the codebase we could help you put it in there.

**Comment by MahtraDR** [comment]
This looks to have been resolved by https://github.com/rpherbig/dr-scripts/commit/cb528629a721292b4d9d7f15e05c2712961eec52#diff-18443e09d277ccd7f885eaf0b9fbdcad81101750fe3ed962d52a7b82a60bb99a
