### ISSUE TITLE
Smelt-deed - Will attempt to smelt anything

### ISSUE THREAD

**Issue by mtruitt** [rpherbig/dr-scripts#3433]
Most likely should have a check against stone lumber etc. I just tested and confirmed it tried to smelt a bunch of soapstone.

**Comment by Sarvatt** [comment]
honestly, that is just user error. dont do that?

**Comment by mtruitt** [comment]
Actually, just doing smelt-deed did that. Per its own documentation

smelt-deeds
combines deeds of like metals to save inventory space

Well aware it would be user error if I had done smelt-deed soapstone

**Comment by rpherbig** [comment]
An easy change would be to make the `material` arg non-optional: https://github.com/rpherbig/dr-scripts/blob/master/smelt-deeds.lic#L15

Does anyone ever call this script without that arg?

**Comment by rcuhljr** [comment]
I used to call it without arguments after every mining run. I kept all other deeds in my book and didn't gather wood at the time.

**Comment by rcuhljr** [comment]
Seems like just adding in a list of known metals might be a decent fix and it will only combine down metal deeds.
