### ISSUE TITLE
add a way to override athletics hometown.

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#3434]
just marking this so I see it in the future, we should be able to override athletics hometowns so people can actually use hib. swim_liirewsag is busted and people can easily get back and forth to shard fast, it might be worth just skipping p5 athletics entirely if someone has ice skates or something like that.

**Comment by Sarvatt** [comment]
well, that would suck for a f2p only in hib with a p5 visa. hmm.

**Comment by MahtraDR** [comment]
@rpherbig athletics accepts targets today. I'd close this, as wontfix.
