### ISSUE TITLE
shadowling multi-casting during combat

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#3450]
Shadowling appears to be casting multiple times during combat (This does not happen when buffing before combat)  Logs below.  (Removed all the combat text, not relevant)  It usually casts 3 continuous times before it finally stops.

Thanks for looking!
~Gab

[combat-trainer]>prep shadowling 15

You make a careless gesture as you chant the words for the Shadowling spell.
You feel fully rested.
You feel fully attuned to the mana streams again.

[combat-trainer]>charge my watersilk bag 35

You harness a large amount of energy and attempt to channel it into your watersilk bag.
You are able to channel all the energy into the bag.
The watersilk bag absorbs all of the energy.
Roundtime: 4 sec.

[combat-trainer]>charge my watersilk bag 25
  
You harness a moderate amount of energy and attempt to channel it into your watersilk bag.
You are able to channel all the energy into the bag.
The watersilk bag absorbs all of the energy.
Roundtime: 3 sec.

[combat-trainer]>charge my watersilk bag 25

You harness a moderate amount of energy and attempt to channel it into your watersilk bag.
You are able to channel all the energy into the bag.
The watersilk bag absorbs all of the energy.
Roundtime: 3 sec.

[combat-trainer]>invoke my watersilk bag  spell

The watersilk bag pulses with Lunar energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.  By directing your focus, you ensure that mana is drawn only when spells are cast.
Roundtime: 1 sec.

[combat-trainer]>release shadowling

That would be a neat trick.  Try finding a shadowling first.

[combat-trainer]>cast

You gesture.
Your watersilk bag emits a loud *snap* as it discharges all its power to aid your spell.
Coagulated shadows pool into existence swiftly shaping into the diminutive form of a shadowling.

[combat-trainer]>invoke shadowling

You gesture, adjusting the pattern that binds the shadowling to this plane.  Invisible forces rapidly disperse the creature's corporeal form as you merge its component shadows into your own.
Roundtime: 3 sec.

[combat-trainer]>prep shadowling 15

You make a careless gesture as you chant the words for the Shadowling spell.

[combat-trainer]>charge my watersilk bag 35

You harness a large amount of energy and attempt to channel it into your watersilk bag.
You are able to channel all the energy into the bag.
The watersilk bag absorbs all of the energy.
Roundtime: 4 sec.

Your shadow babbles, "Beebo!"

[combat-trainer]>charge my watersilk bag 25

You harness a moderate amount of energy and attempt to channel it into your watersilk bag.
You are able to channel all the energy into the bag.
The watersilk bag absorbs all of the energy.
Roundtime: 3 sec.

[combat-trainer]>charge my watersilk bag 25

You harness a moderate amount of energy and attempt to channel it into your watersilk bag.
You are able to channel all the energy into the bag.
The watersilk bag absorbs all of the energy.
Roundtime: 3 sec.

You feel fully prepared to cast your spell.

[combat-trainer]>invoke my watersilk bag  spell

The watersilk bag pulses with Lunar energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.  By directing your focus, you ensure that mana is drawn only when spells are cast.
Roundtime: 1 sec.

[combat-trainer]>release shadowling

A faint growl echoes from the depths of your shadow as the shadowling bound to it returns to whence it came.

[combat-trainer]>cast

You gesture.
Your watersilk bag emits a loud *snap* as it discharges all its power to aid your spell.
Coagulated shadows pool into existence swiftly shaping into the diminutive form of a shadowling.

[combat-trainer]>invoke shadowling

You gesture, adjusting the pattern that binds the shadowling to this plane.  Invisible forces rapidly disperse the creature's corporeal form as you merge its component shadows into your own.
Roundtime: 3 sec.

[combat-trainer]>prep shadowling 15

[combat-trainer]>charge my watersilk bag 35

[combat-trainer]>charge my watersilk bag 25

You harness a moderate amount of energy and attempt to channel it into your watersilk bag.
You are able to channel all the energy into the bag.
The watersilk bag absorbs all of the energy.
Roundtime: 3 sec.
[combat-trainer]>charge my watersilk bag 25

You harness a moderate amount of energy and attempt to channel it into your watersilk bag.
You are able to channel all the energy into the bag.

The watersilk bag absorbs all of the energy.
Roundtime: 3 sec.

You feel fully prepared to cast your spell.

[combat-trainer]>invoke my watersilk bag  spell

The watersilk bag pulses with Lunar energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.  By directing your focus, you ensure that mana is drawn only when spells are cast.
Roundtime: 1 sec.

[combat-trainer]>release shadowling

A faint growl echoes from the depths of your shadow as the shadowling bound to it returns to whence it came.
Shentai leaps from hiding and ambushes a storm bull!

[combat-trainer]>cast

You gesture.
Your watersilk bag emits a loud *snap* as it discharges all its power to aid your spell.
Coagulated shadows pool into existence swiftly shaping into the diminutive form of a shadowling.

[combat-trainer]>invoke shadowling

You gesture, adjusting the pattern that binds the shadowling to this plane.  Invisible forces rapidly disperse the creature's corporeal form as you merge its component shadows into your own.
Roundtime: 3 sec.

**Comment by MahtraDR** [comment]
@rpherbig can close this.
