### ISSUE TITLE
glove check

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#3454]
please add /You slip/i to the list in equipmanager - line 213

[weararmor: message: You slip some damite mail gloves onto your hands.]

[weararmor: checked against [/You sling/i, /You attach/i, /You .* unload/i, /You slide/i, /You place/i, /close the fan/i, /You hang/i, /You spin/i, /You strap/i, /You put/i, /You carefully loop/i, /You don't seem to be able to move/i]]

[weararmor: for command wear my mail.gloves]

in equipmanager

    todo.all? do |held_item|
      if info = worn_items.find { |item| item.short_regex =~ held_item }
        stow_helper("wear my #{info.short_name}", info.short_name, 'You sling', 'You attach', 'You .* unload', 'You strap', 'You slide', 'You work your way into', 'You spin', '^You ', 'You carefully loop', 'slide effortlessly onto your')
        true

**Comment by Sarvatt** [comment]
how did you hit that in return_held_gear?

**Comment by Sarvatt** [comment]
i'll add it but i'm curious

**Comment by Sarvatt** [comment]
only thing i can think of is you killed your scripts while either outdoors or combat-trainer were swapping hand armor?

**Comment by Sarvatt** [comment]
nothing wrong with adding more checks, i'm just curious

**Comment by xtremenerdrage** [comment]
Honestly I'm not sure, I was checking different gloves for what I wanted to wear and added some mail gloves into my yaml then combat trainer gave me an error, went out of combat and tested with weararmor and got the same message.
