### ISSUE TITLE
Join Hunting Buddies

### ISSUE THREAD

**Issue by DRBoxBoss** [rpherbig/dr-scripts#3456]
Would it be possible to have a setting that would allow folks to join hunting buddies upon arrival and leave/disband group upon leaving?

Thank You,

**Comment by Sarvatt** [comment]
it's easily possible, no paladin has implemented it yet :D  i was thinking about adding it for egg usage to spawn champ mobs at one point

**Comment by DRBoxBoss** [comment]
If it is possible and doesn't cause too much of an issue, the ability to group up and hunt with hunting buddies while sharing/benefiting from group buffs/wards would be awesome. Thank You!

**Comment by MahtraDR** [comment]
We had a chat between the active devs at this time, and we've decided against pursuing this.

It would require significant changes to various scripts to deal with avoids, on/before joins, on death, etc... This issue is over two years old, and hasn't had any interest since. Closing.
