### ISSUE TITLE
;astrology, ;walkingastro telescope use on sun pointing at character (Sunyun) instead of Sun

### ISSUE THREAD

**Issue by Bedonder** [rpherbig/dr-scripts#3460]
When either script runs with my character named Sunyun it tries to “center telescope on sun” it tries to look at me (“You peer into the wrong end of a simple mahogany telescope”.) Both “center telescope on sun in sky” and “center telescope on sun in heavens” do not work.

I assisted and the GM had me try "center telescope on elanthian sun" and that worked. Can the script be changed to add "elanthian" before sun?

**Comment by Bedonder** [comment]
It may be that only ;walkingastro has the problem. It is night ingame and I can't test.

**Comment by Sarvatt** [comment]
does look like its just walkingastro. thanks for the heads up!

**Comment by Tarhish** [comment]
This was the answer all along?  Incredible.

There's also a center('sun') in combat-trainer.  Mind getting that one at the same time?

**Comment by Sarvatt** [comment]
done, makes me wonder if there is a workaround for heart or heaven :)

**Comment by Bedonder** [comment]
Thanks! From the GM: Ynami whispers, "In terms of objects, you cannot add "in sky" or "in heavens" it only cares about the object after "CENTER TELESCOPE ON"."
Not sure if this helps.

**Comment by Sarvatt** [comment]
yeah i was wondering if you could center telescope on elanthian heavens

**Comment by Sarvatt** [comment]
to fix people whos names start with heart or heaven :)

**Comment by Bedonder** [comment]
It works! you guys are the best! 
I had made a SF script that would waitfor the error message and then put "center telescope on elanthian sun" and loop. Your solution is much better:)

**Comment by Sarvatt** [comment]
if you ever run into a problem and you know the fix but dont know how to fix it in ruby, just submit it here. that was silly easy and you pointed out a way to work around a lot of issues because you assisted and they told you.

**Comment by Tarhish** [comment]
Yeah, this one bugged us for a while

**Comment by Bedonder** [comment]
;walkingastro is fixed but I just had the issue with running ;astrology:(

**Comment by Sarvatt** [comment]
at least you didn't name yourself some variation of My, they really should block names that break their parser that way

**Comment by Sarvatt** [comment]
so yeah base-constellations is going to need to be updated to use elanthian sun for this person if anyone is up for it

**Comment by Sarvatt** [comment]
can you reopen the issue?

**Comment by Sarvatt** [comment]
or file a new one with the astrology problem
