### ISSUE TITLE
combat-trainer should treat combat_training_spells listed as sorcery, as sorcery

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#3467]
If you list
```
combat_training_spells:
  Sorcery:
    abbrev: ic
```
This will not be treated as sorcery because the spell merge will fail. Spells listed under the Sorcery header shouldn't be dependent on spell merge.

**Comment by CunningRunt** [comment]
Agreed, this is relatively serious since it can cause you to lose held items.

**Comment by wscherer420** [comment]
any progress on this?

**Comment by jandersson** [comment]
No progress, but its on my todo list.

**Comment by MahtraDR** [comment]
This can be achieved today by setting the skill for the spell as Sorcery in your own yaml.

```
  Sorcery: &ecry
    abbrev: ecry
    symbiosis: true
    mana: 1
    skill: Sorcery
```

**Comment by jandersson** [comment]
Nice!
