### ISSUE TITLE
combat-trainer "forgets" weapon noun when game gets laggy

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#347]
http://pastebin.com/pBVTUfm5

Line 15: get my club
lag hits
Line 54: lob command issued on club that has not been picked up yet
does not pick up club until line 86, lobs club at line 177
Line 188: get my <noun missing>

Sometime after this, I untied my bastard sword from it's strap and combat proceeded without any other weapon switching through the night.  The club was still at my feet.

**Comment by rpherbig** [comment]
It looks like the `attack_thrown` code uses `checkright` to determine what item to pick up (see https://github.com/rpherbig/dr-scripts/blob/master/combat-trainer.lic#L882). Unfortunately, `checkright` is unreliable, especially in very low or very high lag situations.

I think we should try using `game_state['weapon_name']` instead and see if that is more reliable.
