### ISSUE TITLE
Workorders - shaping weak character

### ISSUE THREAD

**Issue by Rigged123** [rpherbig/dr-scripts#3470]
> 
[workorders]>tap my deed

An attendant arrives, takes your deed and motions to two burly workers.  The workers carefully load a small alabaster rock onto a sled, and drag it over in front of you.

> 
[workorders]>get alabaster rock

You are not strong enough to pick that up!
> 
[workorders: *** No match was found after 15 seconds, dumping info]

**Comment by Tarhish** [comment]
I'm thinking about what we should do with this.  My first instinct is that if you can't pick up the rock/lumber/whatever then it should stop and do the crafting in that room, and not try to move elsewhere, but otherwise continue as normal

**Comment by Rigged123** [comment]
That would work for me.
