### ISSUE TITLE
Safe-room necro healing

### ISSUE THREAD

**Issue by Jimbo541** [rpherbig/dr-scripts#3472]
If poisoned safe-room will wait till poison clears to end, even if you are already fully healed. 

This can cause you to wait for quite some time, while taking no damage from the poison.

**Comment by Tarhish** [comment]
What's the ideal behavior here?  I haven't scripted much with necros, but I'm trying to think of a reliable way to distinguish between 'this poison isn't going to hurt me at all' and 'this poison could kill a younger necro if they just end safe-room prematurely'.

**Comment by Jimbo541** [comment]
As a class, necros can just skip the poison check I'd say and move on.

That is my personal thought on it. Not sure what everyone else feels.

**Comment by Jimbo541** [comment]
Young Necros heal at empaths. Then they use CF, which is combat only healing, when Empaths are no longer an option. Once skilled devour can be cast successfully. So maybe a setting to skip poison check, so you can do it when you are big enough.

**Comment by MahtraDR** [comment]
@rpherbig Can close this one.
