### ISSUE TITLE
Dependency Connection

### ISSUE THREAD

**Issue by Uerne** [rpherbig/dr-scripts#3474]
I run on a satellite connection. Dependency seems to be trying to connect to something and fails every once in a while due to the ping involved with satellite internet. 

I've been starting and restarting the game client and dependency for the last few hours with no luck. 
>tm
--- Lich: training-manager active.
[training-manager]>favor

You currently have 31 favors with the gods.
Your most recent favor was granted by Meraud.

>favor
>

You currently have 31 favors with the gods.
Your most recent favor was granted by Meraud.
>
[training-manager: *** No match was found after 15 seconds, dumping info]
[training-manager: messages seen length: 0]
[training-manager: checked against [/You currently have \d+/i, /You are not currently/i]]
[training-manager: for command favor]
[training-manager]>tap my Meraud orb

;combat Doesn't work either.

Is there a way to run everything without it being dependent on an external connection?

**Comment by Sarvatt** [comment]
are you auto starting traininng manager? if so, stop :)

**Comment by Uerne** [comment]
Someone asked if I was running TM as an autostart. I am not. Here's what I get at the start of the client

[You are standing up.]
>
--- Lich: alias service started
--- Lich: lnet active.
--- Lich: repository active.
--- Lich: dependency active.
>
--- Lich: sanowret-crystal active.
--- Lich: error: undefined local variable or method `custom_require' for #<Scripting:0x434cc58>
	sanowret-crystal:5:in `script'
	F:/Games/lich/lich/lich.rbw:2553:in `eval'
--- Lich: sanowret-crystal has exited.


and here are my autostarts


--- Global autostart scripts: alias, lnet, repository (args: download-updates), dependency

--- Uerne's autostart scripts: sanowret-crystal

**Comment by Uerne** [comment]
--- Lich: error: buffer error
	C:/Ruby200/lib/ruby/2.0.0/net/http/response.rb:357:in `finish'
	C:/Ruby200/lib/ruby/2.0.0/net/http/response.rb:357:in `finish'
--- Lich: dependency has exited.

This is what looks like the main problem.

**Comment by Uerne** [comment]
Going on day three with zero use out of anything dependency related. Been using it for two months now and it's completely lost functionality. It'll work for a few hours in the middle of the day and then during peak hours it just stops. 

I'll give ANY information you need. Just looking for any idea of why this is happening

**Comment by Uerne** [comment]
And I have 2 alts, neither of which is experiencing this problem often.

**Comment by Tarhish** [comment]
So the sanowret issue is probably because it's in ;autostart.  It's starting up at the same time as dependency and failing to get the custom_requires that it needs loaded in time. If you do 
```
;autostart remove sanowret-crystal
;e autostart('sanowret-crystal', false)
```

Then it should only start sano once dependency is fully loaded.  The rest of it, though, I'm not sure of.  If dependency were totally broken those scripts should have just hung at startup, and not tried a bunch of stuff first.  That buffer error doesn't ring a bell.

**Comment by Uerne** [comment]
I removed Sanowret from my autostart list this morning but it didn't have any impact. Go2 is even breaking down now. Not just the bescort service but any time I hit an rt or an action, it stops.

**Comment by Uerne** [comment]
I removed Sanowret from my autostart list this morning but it didn't have any impact. Go2 is even breaking down now. Not just the bescort service but any time I hit an rt or an action, it stops. 

No one has given me a straight answer yet on dependency being networked. Is dependency trying to connect to something and failing because of my satellite ping? Because that's never going to change. 

If it's a problem I can deal with I'll keep niggling at it but connectivity is insurmountable.

**Comment by Uerne** [comment]
I removed Sanowret from my autostart list this morning but it didn't have any impact. Go2 is even breaking down now. Not just the bescort service but any time I hit an rt or an action, it stops. 

No one has given me a straight answer yet on dependency being networked. Is dependency trying to connect to something and failing because of my satellite ping? Because that's never going to change. 

If it's a problem I can deal with I'll keep niggling at it but connectivity is insurmountable.

**Comment by Tarhish** [comment]
Yeah, dependency checks out with github here every time it starts up, among several other things like submitting thieving data, but that shouldn't be a problem.  Can you post what you see if you... start up, kill dependency (if it's running) and then run ;dependency again?

**Comment by rcuhljr** [comment]
We'll probably need a log of what happens when you log into the game fresh like Tarhish pointed out.  

>Go2 is even breaking down now. Not just the bescort service but any time I hit an rt or an action, it stops.

That sounds like there may be other problems here as well. I think I edited the forked version of lich to bail out in case the pet problems ever cropped up again, but do you have any pets or weird atmospheric toys out? This sounds a lot like the great pet crashes of 2017.  I'm not seeing the bail out code so maybe that didn't happen?

The next time you get this weird crashing behavior, try running `;e echo $strip_xml_multiline`

**Comment by Uerne** [comment]
I've been logged on for almost 12 hours. Everything worked until about 6pm mountain. Then it just fails. There's no log-off or whatever. It was working and then it doesn't. 

During workorders it's just keeps trying to find a match for 'ask yalda for challenging work' It'll do that till doomsday, and before you ask it's the 15 second 'no match found' bohicky. 
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[workorders]>ask Yalda for challenging blacksmithing work
Yalda shuffles through some notes and says, "Alright, this is an order for a diagonal-peen hammer. I need 2 of superior quality, made from any material and due in 55 roisaen.  Please complete the items, bundle them with your logbook and then give me the logbook to complete this order.  Good luck!"

You seem to recall this item being somewhere in chapter 2 of the instruction book.
>
[workorders: *** No match was found after 15 seconds, dumping info]
[workorders: messages seen length: 0]
[workorders: checked against [/^To whom/i, /order for .* I need \d+ /i, /order for .* I need \d+ stacks \(5 uses each\) of .* quality/i, /You realize you have items bundled with the logbook/i, /You want to ask about shadowlings/i]]
[workorders: for command ask Yalda for challenging blacksmithing work]
[workorders]>ask Yalda for challenging blacksmithing work

It'll do that forever. And I haven't logged off at any point.

**Comment by Tarhish** [comment]
So this is interesting, but I do want to be clear -- this does not appear to be related to dependency trying to talk out to a server and failing during gameplay.  It probably IS related to your connection though. 

So what interests me is the 'messages seen length: 0'  If we're in common's bput then it should log every line it gets from 'get', but it didn't see anything.  So is lich Script.current.gets just... not seeing what DR's sending?

```
  def bput(message, *matches)
    waitrt?
    log = []
    matches.flatten!
    matches.map! { |item| item.is_a?(Regexp) ? item : /#{item}/i }
    clear
    put message
    timer = Time.now
    while (response = get?) || (Time.now - timer < 15)

      if response.nil?
        pause 0.1
        next
      end

      log += [response]

      case response
      when /(?:\.\.\.wait |Wait |\.\.\. wait )([0-9]+)/
        pause(Regexp.last_match(1).to_i - 0.9)
        waitrt?
        put message
        timer = Time.now
        next
      when /Sorry, you may only type ahead/
        pause 1
        put message
        timer = Time.now
        next
      when /^You are a bit too busy performing to do that/, /You should stop playing before you do that/
        put 'stop play'
        put message
        timer = Time.now
        next
      when /would give away your hiding place/
        release_invisibility
        put 'unhide'
        put message
        timer = Time.now
        next
      when /^You are still stunned/, /^You can't do that while entangled in a web/
        pause 0.5
        put message
        timer = Time.now
        next
      end

      matches.each do |match|
        if (result = response.match(match))
          return result.to_a.first
        end
      end
    end
    echo '*** No match was found after 15 seconds, dumping info'
    echo "messages seen length: #{log.length}"
    log.reverse.each { |logged_response| echo "message: #{logged_response}" }
    echo "checked against #{matches}"
    echo "for command #{message}"
    ''
  end
```

**Comment by KatoakDR** [comment]
I used @Tarhish's [workaround](https://github.com/rpherbig/dr-scripts/issues/3474#issuecomment-471380987) to `;e autostart('sanowret-crystal', false)`

However, scripts I autostart that way _do not appear_ in the `;autostart list` output and `;autostart remove <script>` doesn't work either because it doesn't think there are any autostart scripts.

However, when I connect to Lich, all the scripts that were configured via `;e autostart('<script>', false)` still run.

How can I remove these scripts from autostart? Thanks

**Comment by rcuhljr** [comment]
`;e autostart` and `;autostart` have nothing to do with each other and ;autostart should generally be avoided. `;e stop_autostart('namegoeshere')` removes an autostart script, `;e list_autostarts` shows the scripts in your autostart currently.

**Comment by rcuhljr** [comment]
Or see section 10 in the setup instructions for more accurate info. https://github.com/rpherbig/dr-scripts/wiki/First-Time-Setup

**Comment by MahtraDR** [comment]
@rpherbig This can be closed.
