### ISSUE TITLE
Workorders - engineering with someone in your group

### ISSUE THREAD

**Issue by Rigged123** [rpherbig/dr-scripts#3475]
I'm usually dragging around a teaching buddy, but it will get into a skipping loop with trying to find an empty room if someone is in your group. You can see the below room was empty besides me and my party.

Room Number: 8867

[go2]>go birch door

> 
Mapped exits: go birch door, go oak door, go maple door

[Engineering Society, Workshop]
Tall alabaster walls encompass rows of tables covered with unfinished stone pieces.  A massive iron gate and a large chain hanging from a system of pulleys and winches dominate the north end of the room.  Attendants stand at the ready to collect and store crafters' furniture that would otherwise be too large to carry.
You also see an unfinished serpentine stout stirring rod, a pile of fuel, a gear press, an assortment of communal crafting tools, a table saw, Attendant Dalehphina, a birch door and a large waste bucket.
Obvious exits: none.
Rigged followed.

Room Number: 9058

--- Lich: go2 has exited.

[workorders: ***Failed to find an empty room, pausing***]

**Comment by Tarhish** [comment]
Based on everything I'm seeing there's already a check that excludes group members in the common methods for finding an empty room.  So... I guess I don't understand why it didn't work here.  I'll try it with an alt and see what it's thinking here.

**Comment by Rigged123** [comment]
Is it the unfinished stirring rod someone left?

**Comment by MahtraDR** [comment]
Closing as wontfix.
