### ISSUE TITLE
workorders - shaping loops on failed material purchase

### ISSUE THREAD

**Issue by dakre18** [rpherbig/dr-scripts#3478]
While workorders is training engineering/shaping, when it has to go back to purchase more lumber, it gets stuck in a loop if you do not have enough money on hand.

Workorders finishes multiple items (finished 3 out of 5), so when it detects the lack of lumber, it goes to buy more lumber and gets stuck in a loop. For reference, i'll put the workorder info before the loop.

`[workorders]>ask Talia for challenging shaping work
Talia shuffles through some notes and says, "Alright, this is an order for a wood bo staff. I need 5 of superior quality, made from any material and due in 230 roisaen.  Please complete the items, bundle them with your logbook and then give me the logbook to complete this order.  Good luck!"`

Edit: forgot to put, each wood bo staff uses 8 pieces of wood.

The loop says this:

`[workorders]>order 10
The attendant shrugs and says, "Ugh, you don't have enough coins to purchase 5 pieces of maple lumber!"
[workorders]>combine
You must be holding both substances to combine them.  For more information, see HELP VERB COMBINE.
[workorders]>count my maple lumber
I could not find what you were referring to.`

This repeats constantly, until i pause the script to pull more money out of the bank.

**Comment by MahtraDR** [comment]
Doesn't happen anymore.
