### ISSUE TITLE
Combat-Trainer Personlizing

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#348]
Greetings, I've gone through the Tekronn-Setup.yaml file and personalized it .  Renamed it to myself (Mistified) and then worked on the content inside.  Unfortunately i'm not familiar with this at all and just looked at the existing content as placeholders and changed them for the items i'm wearing.  

The script is working decently when i run it in combat.  But it is drawing weapons that don't have a high enough ranking for the "Hunting Zone (rock guardians)" that i'm in.  Is there a way to pick which weapons would be drawn in a particular hunting zone?

**Comment by OdnaZvezda** [comment]
It sounds like this is the section you want to edit.  The skills/weapons here don't need to be all the weapons you have.  But the ones you use primarily.   You can create a Mistified-back.yaml with just a weapon_training: section for back training other weapons and then when you want to back train, call it with ;combat-trainer back

weapon_training:
  Brawling: ''
  Twohanded Edged: bastard sword
  Large Edged: bastard sword
  Large Blunt: throwing hammer
  Heavy Thrown: throwing hammer
  Crossbow: light crossbow

**Comment by rpherbig** [comment]
Welcome to the repo, @wscherer420 !

@OdnaZvezda is correct, `weapon_training` is what you want to modify. That is a list of skills (and their weapons) to train.

By way of explanation, the scripts load in `base.yaml` first, then `CharacterName-setup.yaml`, then yaml files for each argument you pass to `combat-trainer`. For example, `;combat-trainer back` has an argument of `back` and would load `back.yaml` after the other two files. For any settings that are in multiple files, the last value to be loaded wins (e.g. the value in `back.yaml` in this case).

**Comment by wscherer420** [comment]
In the Weapon_training section, am i subject to the amount of existing weapon training lines presented there?  Brawling, twohanded edge, large edge, large blunt, heavy thrown, crossbow = 6.  Can i just remove lines and or add lines to increase and decrease the amount of weapons i want to train?

I only have 3 weapons that would be able to train in rock guardians.  But i have about 9 that i'm backtraining.  So in the back file i can add all nine of those weapons?

**Comment by wscherer420** [comment]
Also, this is what i'd adjust my primary weapons training to be in rock guardians (zone 1)

weapon_training:
  Brawling: ''
  Large Edged: black broadsword
  Large Blunt: ukabi
  Small Edge: throwing dagger
  Small Blunt: War Hammer.

Do i need to make any adjustments in the top section of the setup file, area might be called "training priority" i believe?  It lists several weapon categories that i'm not using as well.  What role does this area play?

:training_manager_hunting_priority: true
:training_manager_priority_skills:
- Polearms
- Small Edged
- Small Blunt
- Light Thrown
- Twohanded Blunt
- Staves
- Offhand Weapon
hunting_info:
- :zone: rock guardians
  args:
  - back
  stop_on:
  - Polearms
  - Small Edged
  - Small Blunt
  - Light Thrown
  - Twohanded Blunt
  - Staves
  - Offhand Weapon
- :zone: giant thicket vipers
  args:
  stop_on:
  # - Plate Armor
  # - Chain Armor
  # - Brigandine
  # - Light Armor
  # - Shield Usage
  - Brawling
  - Large Edged
  - Twohanded Edged
  - Large Blunt
  - Heavy Thrown
  - Crossbow
  # - Targeted Magic
  # - Debilitation

**Comment by rpherbig** [comment]
You can modify `weapon_training` to have as many or as few weapons as you like.

If `training_manager_hunting_priority` is true, then `training-manager` will prioritize combat skills. False, it will prioritize noncombats.

`training_manager_priority_skills` is a list of skills that will trigger stopping noncombat (i.e. town) training and run off to do combat. Remove ones that are not applicable.

`stop_on` us a list of skills that will trigger stopping combat training.

In the example above, `training-manager` will train in rock guardians until seven skills are around 32 (Polearms, etc), then go to thicket vipers until six skills are around 32 (Brawling, etc), then go back to town to train noncombats. It will remain in town until any of seven skills are under around 6 (Polearms, etc).

**Comment by wscherer420** [comment]
SUPER HELPFUL!  Thank you so much.  I'm work on it and see how it goes, might have a few more questions...thanks again.
