### ISSUE TITLE
Holy Weapon Charging via Icon 

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#3483]
It would be great if we could add holy weapon charging to Training-Manager.  Perhaps could be done when the Paladin is conducting the soul boosting script while doing crossing-training.  

______________________________

>get my icon
You get a silver Rutilor icon framed in blade-shaped filigree from inside your traveler's pack.

>clean my icon
You carefully wipe off the dust from your Rutilor icon.
Roundtime: 10 seconds

>clean my icon
You turn the Rutilor icon before lightly rubbing your palm over it.
Roundtime: 15 seconds

>clean my icon
You inspect your Rutilor icon from all angles, making sure it is completely clean and polished.
Roundtime: 20 seconds

>clean my icon
The icon is spotless.  No need to clean it right now.

>hug my icon
You drop to your knees and hold the Rutilor icon closely, feeling a sense of purity in your heart.
Roundtime: 20 seconds

>focus my icon
Unaware of what is going on around you, you raise the icon high above your head and feel a sense of serenity in your being.
Roundtime: 20 seconds

>pray my icon
You breathe out respectful praise to the gods as the Rutilor icon glows for a moment.
You feel ready to recharge your holy weapon.

>get my axe
You get a tyrium sterak axe with a tempered blade from inside your weapon harness.
>glyph renew axe
Your weapon must be in your right hand.
>swap
You move a silver Rutilor icon framed in blade-shaped filigree to your left hand.
You move a tyrium sterak axe with a tempered blade to your right hand.

>stow icon
You put your icon in your traveler's pack.
>glyph renew axe
You trace the Glyph of Renew upon your sterak axe causing it to glow intensely white.

>glyph renew axe
You are not properly prepared to use this glyph.

>look at my axe
Your axe is blinding you with holy power.

**** Other Messages

>Clean my icon right after completing the ritual:  
>You just performed the ritual not too long ago.  It's best to wait a bit before trying again.

>Hugging the icon without cleaning it:
>hug my icon
You need to clean the icon first.

>Tapping my icon
>tap rutilor icon
You tap a silver Rutilor icon framed in blade-shaped filigree that you are holding.

**Comment by MahtraDR** [comment]
Closing as not something likely to be added to crossing-training.
