### ISSUE TITLE
bank withdraw fails and gets stuck in a loop

### ISSUE THREAD

**Issue by dakre18** [rpherbig/dr-scripts#3487]
I'm pretty sure getting caught stealing caused this message due to social outrage, but when it's too high and sell-loot or crossing-training goes to withdraw gold from the bank, this message comes up and the withdraw doesn't happen.

`[crossing-training]>withdraw 2 gold`
`The clerk glares at you.  "I don't know what you think you're doing Dakre, but I don't like it much."`

**Comment by BinuDR** [comment]
That's not social outrage, that's for withdrawing too many times in a row.

```>with 5 gold
The clerk counts out 5 gold Kronars and hands them over, making a notation in her ledger.
>with 5 gold
The clerk counts out 5 gold Kronars and hands them over, making a notation in her ledger.
>with 5 gold
The clerk counts out 5 gold Kronars and hands them over, making a notation in her ledger.
>with 5 gold
The clerk counts out 5 gold Kronars and hands them over, making a notation in her ledger.
>with 5 gold
The clerk counts out 5 gold Kronars and hands them over, making a notation in her ledger.
>with 5 gold
The clerk glares at you.  "I don't know what you think you're doing Binu, but I don't like it much."```

**Comment by dakre18** [comment]
Oh i see, i thought it was SO, since i had gotten caught not too long before that. and i go to the bank, try to withdraw and that happened. i may have missed a withdrawal happen before that, but i didn't realize it was from too many times in a row. i honestly don't think i tried that many times.

I guess that changes the issue a bit, since lich just walks out to do whatever, comes back to withdraw again and i was stuck in a loop honestly. i'll keep an eye on it again, but i would think the fix is just to pause for a few seconds and try to withdraw again.

the only thing i can think that happens every time i got that message, is i ran into the teller, deposited all coin, and tried to withdraw that 2 gold so quickly due to the script. not sure if that's the problem, but that's what i remember.

**Comment by dakre18** [comment]
i changed the title to make more sense, but i still do not know how to duplicate the loop. the simplest solution would be to recognize it failed and try to withdraw again. i'll leave that to the devs to decide though, since more than 1 script seems to make a bank run.

**Comment by Tarhish** [comment]
I actually ran into this on my own in ;trade.  I had it depositing after doing a work order then a  caravan_coins_on_hand value that made it withdraw 5 more times,  I adjusted my values to hit that less often, but yeah I'll look at the common methods in a little while.  Should be easy enough.

**Comment by MahtraDR** [comment]
@BinuDR Is this still an issue today?

**Comment by asechrest** [comment]
This has been addressed previously in `DRCM.get_money-from_bank` and the case statement for money withdrawal now pauses when we get this feedback: https://github.com/rpherbig/dr-scripts/blob/27fffc9580c5f99d1eb623e5ab5fe13ea496f84d/common-money.lic#L206

Closing as completed.
