### ISSUE TITLE
Steal.lic -- Crossbow bolts combine? and then time out.

### ISSUE THREAD

**Issue by ServerFailure** [rpherbig/dr-scripts#3496]
You get some crossbow bolts from inside your hunting pack.
>
[steal]>put crossbow bolts in bin
A bored-looking Human boy nods toward you as your crossbow bolts falls into the azurite bin.
A bored-looking Human boy says, "Nice work, You."
>
[steal]>get crossbow bolts from my pack
What were you referring to?
>
[steal: *** No match was found after 15 seconds, dumping info]
[steal: messages seen length: 1]
[steal: message: What were you referring to?]
[steal: checked against [/You get/i]]
[steal: for command get crossbow bolts from my pack]
[steal]>put crossbow bolts in bin

**Comment by MahtraDR** [comment]
Closing. Since burgling was introduced, folks don't use this script. If this comes up in a modern context, we can revisit.
