### ISSUE TITLE
Improve logic when bleeding

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#35]
When bleeding is detected, turn on the tendme script then retreat to a set saferoom.

Experiment with the ordering of retreat, tendme, retreat, walk_to due to roundtime.

**Comment by rpherbig** [comment]
The current behavior is pretty awful (run `tendme` and then retreat until the bleeder goes away). This logic breaks especially when you have an internal bleeder you can't tend. And if you got a bleeder from the mobs you're fighting, it's more likely you'll get another before yours goes away.

In practice this seems to mean you retreat, tend, and keep retreating until `afk` logs you out.

I'm not sure if it's related, but when I saw this happen last night `combat-trainer` did not stop when sent the stop signal by `hunting-buddy`.

**Comment by rcuhljr** [comment]
Is this resolved but just staying in combat after tending even with a bleeder?

**Comment by rpherbig** [comment]
Does combat-trainer keep fighting after tending?
