### ISSUE TITLE
consider training outdoorsmanship through combat-trainer

### ISSUE THREAD

**Issue by hwoo79** [rpherbig/dr-scripts#350]
maybe have `outdoorsmanship` on a timer similar to `perception` and `attunement` and have it retreat and collect <something> every so often to keep outdoorsmanship moving in combat.

**Comment by rpherbig** [comment]
Hmm, would that require a way to know if your current hunting room supports
collecting? Does what can be collected vary by room?

**Comment by hwoo79** [comment]
Supposedly a `FORAGE LIST` is in the works for Rangers, but nothing now without just experimenting.  Maybe there could be a `collect_item:` setting under the hunting parameters that could set it for rooms,  as a rule of thumb, it's rocks for outside rooms.  the easiest item would be best as all items scale with skill (collect just collects more of the item)
