### ISSUE TITLE
combat-trainer doesn't recognize Phoenix Pyre while under Will of Winter

### ISSUE THREAD

**Issue by swatjester** [rpherbig/dr-scripts#3511]
Combat-trainer script doesn't recognize the change in messaging when Phoenix Pyre is affected by Will of Winter. As such, you get a massive amount of error scroll afterwards and it stalls for 15 seconds.

**Comment by Sarvatt** [comment]
can you paste what the message you see is? it should be handled.

**Comment by swatjester** [comment]
[combat-trainer]>release DALU

A few fleeting, soporific notes tarry in the air before your lullaby slowly dies down like the night receding at Anduwen.
> 
[combat-trainer]>prepare PYRE 7

> 
You feel fully rested.

> 
An arthelun cabalist gestures at you.
Flickering embers drift from an arthelun cabalist's fingertips, cascading to the ground where they land in a rough circle.  Suddenly a pillar of white-hot flame bursts from the embers toward the ceiling!  Stepping out of the column of flame, a majestic fiery lion shakes its burning mane, snarls, and springs toward you!

The lion suddenly yowls and shies away from you.
The fiery lion shakes its glowing mane, then vanishes in a swirl of flames.
> 
Wrapped in winter you begin to chant the Phoenix's Pyre, filling it with your frigid will.  Your chant begins low, each word crackling from your lips, and as your voice grows you begin to thread Fire in opposition to the Water.  The air about you quickly agitates, causing it to warm almost painfully as snowflakes rapidly flutter around you and die.
> 
[combat-trainer]>hunt

You take note of all the tracks in the area, so that you can hunt anything nearby down.

To the north:
  1)   an immense dirt construct
  2)   a charred husk
  3)   an arthelun cabalist
  4)   an arthelun cabalist
  5)   an arthelun cabalist
  6)   an arthelun cabalist
  7)   an arthelun cabalist
  8)   an arthelun cabalist

To the south:
  9)   an arthelun cabalist
  10)   an arthelun cabalist
  11)   an arthelun cabalist
  12)   an arthelun cabalist

To the southwest:
  13)   Natarian
  14)   an arthelun cabalist

Roundtime: 8 sec.
R> 
The arthelun cabalist moves into a position to dodge.
R> 
Teardrops of flame ignite the air about an arthelun cabalist.  An arcane whisper pierces your mind, "BURN, MORTAL!"

* An arthelun cabalist chops a longsword crafted from pure flame at you.  You fend off some of the longsword with a balanced bar mace.  
[You're winded, nimbly balanced with opponent in good position.]
R> 
* An arthelun cabalist sidesteps and bashes at you.  You turn aside some of the longsword with a balanced bar mace.  
[You're winded, nimbly balanced with opponent in very strong position.]
R> 
An arthelun cabalist gestures.
R> 
[hunting-buddy: ***STATUS*** 80 minutes of hunting remaining or waiting on Small Edged, Chain Armor, Polearms, Plate Armor, Parry Ability, Brawling, Evasion, Shield Usage, Tactics]

The arthelun cabalist moves into a position to dodge.
> 
[combat-trainer]>attack

< You draw a balanced bar mace at an arthelun cabalist.  An arthelun cabalist blocks with a blazing shield.  
[You're winded, nimbly balanced with opponent in better position.]
[Roundtime 3 sec.]
R> 
You circle lightly on the balls of your feet, singing proudly in a clear voice.
R> 
* An arthelun cabalist sweeps low at you.  You barely block with a small shield.  
[You're winded, nimbly balanced and opponent has slight advantage.]
R> 
You feel fully prepared to cast your spell.
> 
An arthelun cabalist appears less distracted.
> 
[combat-trainer]>cast

* An arthelun cabalist feints high at you.  You fend off some of the longsword with a balanced bar mace.  
[You're winded, nimbly balanced with opponent in strong position.]
> 
You release a duet of elemental fire and water into your chanting, intensifying the callous syllables.

Roundtime: 3 sec.
R> 
With barely a pause for breath, you neatly segue to the verse of the Phoenix's Pyre.  Your skin warms tangibly as you bite off each of the words with a fierceness that seems to incite the very air around you to anger as a conflux of flame and frost is born about you.
The admixture of flames and frost lands an awesome strike (12/23) to an arthelun cabalist's neck!
The arthelun cabalist is knocked completely senseless!
The admixture of flames and frost lands a powerful strike (10/23) to an arthelun cabalist's left eye!
The arthelun cabalist is knocked completely senseless!
The admixture of flames and frost lands a good strike (3/23) to an arthelun cabalist's abdomen!

R> 
An arthelun cabalist's eyes smolder as tiny flames rupture from her skin.

* An arthelun cabalist feints high at you.  You block with a small shield.  
[You're winded, nimbly balanced and in strong position.]
> 
You feel fully attuned to the mana streams again.

> 
A driblet of drool escapes an arthelun cabalist mouth, hissing softly as it splatters amidst the roaring flames.
> 
* An arthelun cabalist sidesteps and bashes at you.  You slap away most of the longsword with a balanced bar mace.  
[You're winded, nimbly balanced and opponent has slight advantage.]
> 
A driblet of drool escapes an arthelun cabalist mouth, hissing softly as it splatters amidst the roaring flames.
> 
[combat-trainer: *** No match was found after 15 seconds, dumping info]

[combat-trainer: messages seen length: 36]

[combat-trainer: message: A driblet of drool escapes an arthelun cabalist mouth, hissing softly as it splatters amidst the roaring flames.]

[combat-trainer: message: [You're winded, nimbly balanced and opponent has slight advantage.]]

[combat-trainer: message: * An arthelun cabalist sidesteps and bashes at you.  You slap away most of the longsword with a balanced bar mace.  ]

[combat-trainer: message: Phoenix's Pyre  (Indefinite)]

[combat-trainer: message: Eillie's Cry  (27 roisaen)]

[combat-trainer: message: Will of Winter  (21 roisaen)]

[combat-trainer: message: Rage of the Clans  (3 roisaen)]

[combat-trainer: message: Aura of Tongues  (4 roisaen)]

[combat-trainer: message: Naming of Tears  (5 roisaen)]

[combat-trainer: message: Redeemer's Pride  (5 roisaen)]

[combat-trainer: message: Harmony  (25 roisaen)]

[combat-trainer: message: Drums of the Snake  (28 roisaen)]

[combat-trainer: message: A driblet of drool escapes an arthelun cabalist mouth, hissing softly as it splatters amidst the roaring flames.]

[combat-trainer: message: You feel fully attuned to the mana streams again.]

[combat-trainer: message: [You're winded, nimbly balanced and in strong position.]]

[combat-trainer: message: * An arthelun cabalist feints high at you.  You block with a small shield.  ]

[combat-trainer: message: An arthelun cabalist's eyes smolder as tiny flames rupture from her skin.]

[combat-trainer: message: The admixture of flames and frost lands a good strike (3/23) to an arthelun cabalist's abdomen!]

[combat-trainer: message: The arthelun cabalist is knocked completely senseless!]

[combat-trainer: message: The admixture of flames and frost lands a powerful strike (10/23) to an arthelun cabalist's left eye!]

[combat-trainer: message: The arthelun cabalist is knocked completely senseless!]

[combat-trainer: message: The admixture of flames and frost lands an awesome strike (12/23) to an arthelun cabalist's neck!]

[combat-trainer: message: With barely a pause for breath, you neatly segue to the verse of the Phoenix's Pyre.  Your skin warms tangibly as you bite off each of the words with a fierceness that seems to incite the very air around you to anger as a conflux of flame and frost is born about you.]

[combat-trainer: message: Roundtime: 3 sec.]

[combat-trainer: message: Phoenix's Pyre  (Indefinite)]

[combat-trainer: message: Eillie's Cry  (27 roisaen)]

[combat-trainer: message: Will of Winter  (21 roisaen)]

[combat-trainer: message: Rage of the Clans  (3 roisaen)]

[combat-trainer: message: Aura of Tongues  (4 roisaen)]

[combat-trainer: message: Naming of Tears  (5 roisaen)]

[combat-trainer: message: Redeemer's Pride  (5 roisaen)]

[combat-trainer: message: Harmony  (25 roisaen)]

[combat-trainer: message: Drums of the Snake  (28 roisaen)]

[combat-trainer: message: You release a duet of elemental fire and water into your chanting, intensifying the callous syllables.]

[combat-trainer: message: [You're winded, nimbly balanced with opponent in strong position.]]

[combat-trainer: message: * An arthelun cabalist feints high at you.  You fend off some of the longsword with a balanced bar mace.  ]

[combat-trainer: checked against [/^Your spell .*backfires/i, /You strain, but are too mentally fatigued/i, /^You gesture/i, /A soft silver glow envelops/i, /You listen intently to the air/i, /You close (your|yours) eyes/i, /Your target pattern dissipates/i, /You make a .* gesture/i, /You raise your (left|right) hand skyward/i, /Flickering shadows tear away/i, /You sense a Malediction/i, /You release an accompaniment/i, /You roll your hands in an elliptical pattern/i, /You (cup|wave|raise) your hand/i, /You flicker your malevolent desires towards/i, /You clench your hands into fists and grit your teeth/i, /Tendrils of flame dart along your hand/i, /Invisible strands of air twist/i, /The flames dancing along your fingertips/i, /^You can't cast that at yourself/i, /^You need to specify a body part to consume/i, /You breathe deeply, centering your energies/i, /You strike your heel against the ground/i, /You clasp your hands together/i, /With a wave of your hand/i, /Your words fill you with an unflagging sense of resolve and purpose/i, /A renewed sense of purpose fills you/i, /You clench your fist and mutter a whispered/i, /You call forth the dark will of the divine/i, /^Your heart skips a beat/i, /You whisper the final word of your spell/i, /^You rebuke a/i, /You clap (you|your) hands/i, /You are pulled through your unstable Moongate/i, /You thrust your/i, /Your mind races/i, /You draw forth a pulse of/i, /A crackling mantle of blazing orange-yellow flames/i, /You speak a few words of righteousness/i, /You give sudden voice/i, /You hold out your arms/i, /^With a slight flick, you point one of your fingers/i, /^You reach (out|up with|with your|one hand|with both)/i, /You place your hands on your temples/i, /Using your left hand, you channel the spell's energies and gesture/i, /You steeple your fingers together/i, /You successfully weave the .* spell into the receptive aura of the orb/i, /The energy contained in your ritual flutters away impotently as it seeks the open skies/i, /At the ritual's peak, your prophetic connection blooms a thousand-fold/i, /Traces of your prior ritual still linger about you/i, /You swipe your fingertips/i, /^Your spirit lashes out/i, /You open your arms in a hieratic gesture/i, /^A (white|silver) static/i, /^A (glowing amber|crimson) mist/i, /^Disregarding the pain, you grind the dirt brutally into the palm of your hand/i, /^You lift your right hand/i, /You roar and draw your arms back/i, /You attempt to quiet your mind/i, /Your fingerbones phosphoresce hylomorphic blue/i, /you immediately recognize the onset of an abnormal arthritis/i, /You point a crooked finger at/i, /Mentally steeling yourself in preparation for the unnatural action/i, /Currently lacking the skill/i, /^You mold/i, /You gaze towards the sky above seeking the strongest flows of Air/i, /Having located a suitably abundant flow of Air, you inhale sharply filling yourself with the tranquil element/i, /You gaze upward seeking the strongest flows of Air/i, /^You drop briefly to one knee as you firmly press your palms into the ground/i, /^You gaze about your surroundings to locate the strongest lines of Aether/i, /You relax your eyes in order to focus on the trace amounts of Fire that warm you and the world around you/i, /^There isn't enough starlight or moonlight for this spell/i, /^You don't have a spell prepared!$/i, /You begin to target/i, /^Wisps of spectral flame whorl.*$/i, /^You cup your palms skyward to bask in.*$/i, /^Incited by the spell, your starlight aura/i, /^Cupping your palms skyward, you bask in a cascade.*$/i]]

[combat-trainer: for command cast]
