### ISSUE TITLE
combat-trainer doesn't support auto-returning weapons

### ISSUE THREAD

**Issue by swatjester** [rpherbig/dr-scripts#3512]
Combat trainer doesn't really handle auto-returning weapons. My phalanx spear automatically returns to my hand after I throw it, without having to be bonded and INVOKEd.  This causes problems with the script. You can kind of work around it by bonding your spear anyway, in which case it will uselessly attempt to INVOKE (usually well after the spear auto returns). This causes additional problems. For instance using training-manager, after cycling my main hunting zone, then my backtrain, then town stuff, when it returns to my main hunting zone, the INVOKEs will all be broken after the repair cycle, and  INVOKE will call the wrong item if you have multiple thrown invoked weapons. This can cause additional bugs down the line (for instance, if it invokes a weapon out of certain types of containers, that weapon becomes unable to be wielded.) It seems to be exacerbated by a combination of using an auto-returning weapon and maybe also after you repair. 

< You lob a jagged shark bone phalanx spear at a fuligin umbral moth.  A fuligin umbral moth fails to block with its uncanny wings.  
The spear lands a strong hit (6/23) that scratches it in a slash from behind, lightly stunning it.

The phalanx spear spins back towards you, returning safely to your outstretched hand.
[You're winded, nimbly balanced and in dominating position.]
[Roundtime 2 sec.]

**Comment by Tarhish** [comment]
Mind posting the whole log of what it does in combat-trainer, from the attack, to hanging after it throws?  I think I know what I'd do to fix it, but I can't be sure I'm in the right place without seeing where it breaks, and I don't want to change the wrong thing.

**Comment by Sarvatt** [comment]
there is only one auction item in the game that does this so we really need the logs if you want it fixed.

**Comment by swatjester** [comment]
On further examination, I still encounter this issue even without this spear in my script at all. So I think the auto-returning part is just a red herring. 
@Tarhish --  I doubt a log would help, but to your point there's not abberrant messaging.  I don't have one handy at the moment but the order of operations of what happens is (First loop of the script) -- you throw the spear, with the messaging as indicated above; I've got that spear perma-bonded as well, so it has :bound: true in the YAML, so it then moves to INVOKE as normal, but as the spear is already in hand, there's just "You have no bonds to invoke" and it all functions as normal.  On the second loop of the script, it will eventually invoke the wrong item as described above, which will cause you to end up with both hands full; the error is simply that you have something in your other hand when you take some action (the exact error and message will depend on whether it's a melee or ranged action you're trying to take.) 

But as noted, I've taken the spear entirely out of the YAML and still encounter the issue. It seems to me like it's something to do with maybe the stored variable somewhere for what bond is invoked isn't initializing properly when you cycle through a number of bonded weapons, and it becomes "off by 1" so to speak. If so, that would probably be on Simu's end, not Lich. 

But seems like there could be a potential work around that at the start of combat trainer, if you have any weapons set to :bound: true; then every time you begin hunting, it cycles INVOKE and STOW/SHEATHE until it gets the "You have no bonds to invoke" messaging *before* it starts hunting.

**Comment by mtruitt** [comment]
I've seen this issue with repairing weapons. After you repair, you have to sit and invoke through them all and re-stow. Its 100% on Simu.

**Comment by MahtraDR** [comment]
@rpherbig I think we can close this. It's not a lich issue.
