### ISSUE TITLE
Khri fright not recognized

### ISSUE THREAD

**Issue by halprind** [rpherbig/dr-scripts#3522]
"After a deep breath, your meditation bears fruit and you feel much more frightening"

**Comment by halprind** [comment]
probably just needs to be added to cast_messages: under base-spells.yaml

**Comment by halprind** [comment]
adding "- After a deep breath" to my khri_preps: to see if that solves it

**Comment by Tarhish** [comment]
Did that work out for you?  I would expect it to, but wanted to check.

**Comment by halprind** [comment]
added it to khri_preps seemed to of worked.

**Comment by rpherbig** [comment]
Closed in 8f885a702541a82c7486cab0de2359d456b812de
