### ISSUE TITLE
Don't sit a repair npc while waiting

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#3530]
It would be useful to move from a repair npcs instead of waiting out tickets so you don't get stolen from. It's a very easy target stealing from people waiting. Hiding could even be an option.

**Comment by thejko** [comment]
Perhaps something that requires you to remove armor can run while repairing? Thievery, mechanical lore, etc?

**Comment by rpherbig** [comment]
Maybe run to your safe room and wait there?

**Comment by Sarvatt** [comment]
the script is weird though and relies on the checking ticket status every 30 seconds, never got around to breaking that up
