### ISSUE TITLE
Alchemy getting stuck in Shard....

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#3543]
See below:  Appears the check against didn't look for "you vigorously".  Might be more to it than that though..  

[remedy]>put dried flowers in my mortar
>
You vigorously rub the flowers alongside the mortar to scrape some shavings into the mixture.
>
[remedy: *** No match was found after 15 seconds, dumping info]
[remedy: messages seen length: 7]
[remedy: message: Manifest Force  (30 roisaen)]
[remedy: message: Researcher's Insight  (23 roisaen)]
[remedy: message: Gauge Flow  (84 roisaen)]
[remedy: message: Manifest Force  (30 roisaen)]
[remedy: message: Researcher's Insight  (23 roisaen)]
[remedy: message: Gauge Flow  (84 roisaen)]
[remedy: message: You vigorously rub the flowers alongside the mortar to scrape some shavings into the mixture.]
[remedy: checked against [/You put/i, /already has something/i, /can only hold/i, /You realize the/i]]
[remedy: for command put dried flowers in my mortar]
[remedy]>untie my pestle from my alchemist belt
You fumble with the ties, quickly realizing that you need a free hand.
>
[remedy: *** No match was found after 15 seconds, dumping info]
[remedy: messages seen length: 4]
[remedy: message: Manifest Force  (30 roisaen)]
[remedy: message: Researcher's Insight  (22 roisaen)]
[remedy: message: Gauge Flow  (83 roisaen)]
[remedy: message: You fumble with the ties, quickly realizing that you need a free hand.]
[remedy: checked against [/You (remove|untie)/i, /Untie what/i]]
[remedy: for command untie my pestle from my alchemist belt]
[remedy]>get my pestle
You should untie the iron pestle from the alchemist's belt first.
>
[remedy: *** No match was found after 15 seconds, dumping info]
[remedy: messages seen length: 7]
[remedy: message: Manifest Force  (29 roisaen)]
[remedy: message: Researcher's Insight  (22 roisaen)]
[remedy: message: Gauge Flow  (83 roisaen)]
[remedy: message: Manifest Force  (30 roisaen)]
[remedy: message: Researcher's Insight  (22 roisaen)]
[remedy: message: Gauge Flow  (83 roisaen)]
[remedy: message: You should untie the iron pestle from the alchemist's belt first.]
[remedy: checked against [/^You get/i, /^You are already/i, /^What do you/i, /^What were you/i, /You pick up/i, /can't quite lift it/i]]
[remedy: for command get my pestle]
[remedy]>crush my dried flowers with my pestle
You need to be holding the pestle first.
>
[remedy]>put my dried flowers in my backpack
You put your flowers in your backpack.
>
[remedy]>untie my pestle from my alchemist belt
You untie an iron pestle from the straps of your alchemist's belt.
>
[remedy]>crush my ointment with my pestle
Crush what?
>
[remedy: *** No match was found after 15 seconds, dumping info]
[remedy: messages seen length: 4]
[remedy: message: Manifest Force  (29 roisaen)]
[remedy: message: Researcher's Insight  (22 roisaen)]
[remedy: message: Gauge Flow  (83 roisaen)]
[remedy: message: Crush what?]
[remedy: checked against [/You need another splash of water/i, /You need another splash of alcohol/i, /You toss the/i, /Upon completion you see some particulate clouding up the mixture./i, /You need another prepared herb/i, /begins to transition colors/i, /You need another catalyst material/i, /Once finished you notice clumps of material/i, /With wide strokes you mix/i, /Applying the final touches/i, /That tool does not seem suitable for that task./i, /You vigorously rub/i, /Patiently you wait a few moments and then proceed/i, /Interesting thought really... but no./i, /You need to be holding the pestle first./i, /The mortar can only hold 25 pieces of material./i, /You spin your/i, /You slowly filter/i, /To avoid a problem/i, /Roundtime:/i]]
[remedy: for command crush my ointment with my pestle]
[remedy]>crush my ointment with my pestle
Crush what?
>

**Comment by Tarhish** [comment]
Yeah, it looks like the problem might have been triggered by something that happened earlier, right before the start of the log.

```
[remedy: message: You fumble with the ties, quickly realizing that you need a free hand.]
[remedy: checked against [/You (remove|untie)/i, /Untie what/i]]
```
Somehow your character ended up with your hands full in the middle of crafting.  Can you grab a bit more of the log?

**Comment by Tarhish** [comment]
Never mind, I think I was wrong.  Teach me to read these on my phone.  I'll look at it closer.

**Comment by Tarhish** [comment]
Yep, here it is
```
    case bput("put #{@herb1} in my #{@container}", 'You put', 'already has something', 'can only hold', 'You realize the')
    when 'You put', 'can only hold'
      stow_item(@herb1) # Added for when the herb is larger than 25 pieces
    when 'already has something', 'You realize the'
      bput("tilt my #{@container}", 'You grab')
      bput("tilt my #{@container}", 'You grab', 'Roundtime')
      bput("put #{@herb1} in my #{@container}", 'You put')
      stow_item(@herb1) # Added for when the herb is larger than 25 pieces
    end
```
After that it goes to get your pestle.  It doesn't realize that's one of the messages that means it has bits of herb leftover.  We can fix that.

**Comment by wscherer420** [comment]
Hey noticed i haven't been getting hung up doing Alchemy lately.  Am i same to assume it was fixed and we should close the item?

**Comment by wscherer420** [comment]
Actually nevermind.  It still hangs up.  Same spot.

**Comment by Tarhish** [comment]
Yep, sorry -- someone else was doing a much larger remedies change that would also have touched this, but it turned out to need more testing.  Just a moment, because I think this is a simple adjustment.
