### ISSUE TITLE
Arranging & Skinning in combat-trainer

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#3544]
The combat-trainer script keeps wanting to do "arrange all for [type]" or just "skin" by itself.

That doesn't work.  It needs to be "arrange dead for type" or "skin dead" else you get "You don't know how to do that." and "Skin what?".

**Comment by Sarvatt** [comment]
it works fine, why is it not working for you? can you tap all?

**Comment by Sarvatt** [comment]
it works fine and has for years, figuring out why arrange all isn't working for you with the DR parser is the problem. Does your name start with all or was someone named all in the room?

**Comment by Sarvatt** [comment]
I use an allarh which does interfere with loot all but its never interfered with arranging

**Comment by Sarvatt** [comment]
the problem is more likely you turned on arrange all but you don't have the crafting technique to do it?

**Comment by Kaesken** [comment]
Nobody is in the room with me and my name does not start with all, no.
There's a crafting technique?
I ended up just going into the combat-trainer script and changing it to "dead" instead.  I'll have to look into the technique.  I typically don't bother with the crafting system nor the techniques.

**Comment by Sarvatt** [comment]
you have arrange_all: true set in your skinning: section in your yaml forcing it to arrange all

**Comment by Sarvatt** [comment]
https://elanthipedia.play.net/Arrange_command

**Comment by Sarvatt** [comment]
arrange all does 5 arranges in one command

**Comment by Kaesken** [comment]
I can arrange all, no problem, but it has to be worded "arrange dead all".
But I'll definitely look into those techniques, thank you.  :)

**Comment by Sarvatt** [comment]
noone else has that problem so yeah look into why you hit it :) most likely the DR parser is just chopping off all from your command there and you aren't doing it.

**Comment by Kaesken** [comment]
Hah, well I ended up just opening the combat-trainer script and just editing it myself on my end, lol
So now it's working.
Still learning of all this!  It's definitely very interesting.  Imma close this since it's been solved.  Again, thank you!

**Comment by Kaesken** [comment]
Just so you know, I did try to go get the crafting technique as mentioned above but it's not offered to me due to lack of skill.  Is there any way to disable the built-in scripts from auto-updating? I tried to disable it in the repository settings but I still have to extract my edited 'combat-manager' because every time I log in, Lich edits it back to the original file.

**Comment by jandersson** [comment]
There's not much we can do based on the information youve given.

**Comment by jandersson** [comment]
Can you post a link to a log of when it happens? and a link to your config/yaml file? That would help tremendously

**Comment by Kaesken** [comment]
Well "skin" by itself is now working rather than asking me "Skin what?" all the time.
"arrange all for all" gives me this:
"You don't know how to do that."
Which I understand to go get a technique to be able to use that, HOWEVER, without the technique, I can type "arrange DEAD for all" and it'll arrange it *without* the technique which is what I'm not getting some folks to understand.

I don't believe it's a yaml issue at all.

**Comment by Kaesken** [comment]
So maybe set combat-trainer to check your outfitting skill and if you're below 25 ranks, use "arrange DEAD for all" but if you're above 25 ranks, use the "arrange ALL for all"?

**Comment by Sarvatt** [comment]
you arent doing an arrange all unless you have the techniques, just arrange
all off in your yaml until you get the 50 engineering or outfitting to
learn arrange all and set arrange_count higher than 1...

**Comment by Sarvatt** [comment]
you’re juat doing the standard 1 arrange

**Comment by Kaesken** [comment]
Outfitting:      3 98.75% clear          (0/34)

Therefore, I don't have the ability to get the technique.

> arrange all for all
You don't know how to do that.
> arrange dead for all
Are you trying to arrange for a skin, part or bone?
> arrange dead all

> 
You begin to arrange the serpent's corpse in a manner that, while making the process of obtaining a part more difficult, guarantees a greater reward.
Roundtime: 2 sec.
> arrange dead all

You continue arranging the serpent's corpse in a manner that, while making the process of obtaining a part more difficult, guarantees a greater reward.
Roundtime: 2 sec.
> arrange dead all

You continue arranging the serpent's corpse in a manner that, while making the process of obtaining a part more difficult, guarantees a greater reward.
Roundtime: 2 sec.
> arrange dead all

You continue arranging the serpent's corpse in a manner that, while making the process of obtaining a part more difficult, guarantees a greater reward.
Roundtime: 2 sec.
R> arrange dead all

You complete arranging the serpent's corpse in a manner that, while making the process of obtaining a part more difficult, guarantees a greater reward.
Roundtime: 2 sec.
> skin

Moving with impressive skill and grace, you effortlessly retrieve a perfect fang from the Endrus serpent.
You carefully fit a jagged wooden fang into your bundle.
Roundtime: 2 sec.

**Comment by Kaesken** [comment]
Explain that then?

**Comment by Tarhish** [comment]
So here it is in combat-trainer:
```
@arrange_all = skinning['arrange_all'] || false
arrange_message = @arrange_all ? "arrange all for #{type}" : "arrange for #{type}"
```
In other words, the only reason it'd do ARRANGE ALL FOR WHATEVER is if you have skinning set to arrange_all in your yaml.  It doesn't do that unless you tell it to.  

Similarly, this:
```
skinning:
  skin: true
  arrange_all: false
  arrange_count: 0
  tie_bundle: false
I'd advise searching

**Comment by Sarvatt** [comment]
arrange all has a higher RT than a normal arrange which is the part  you are not getting, it combines 5 arranges into one arrange action with lesser RT

>arrange all
You complete arranging the wyvern's corpse in a manner that, while making the process of obtaining a part more difficult, guarantees a greater reward. 
Roundtime: 5 sec.

**Comment by Sarvatt** [comment]
arrange dead for all is doing nothing but a normal arrange because the dragonrealms game parser is just reducing it to "arrange"

**Comment by Kaesken** [comment]
So if I put 'arrange: false' it'll do "arrange dead all" instead for the script or not do arrange at all?  Because I DO want to arrange.  I just CANNOT with the phrase "arrange all for all" it HAS to be "arrange DEAD all"

**Comment by Sarvatt** [comment]
```
skinning:
  skin: true
  arrange_all: false
  arrange_count: 1 (or up to 4)
  tie_bundle: false```

**Comment by Sarvatt** [comment]
that will just arrange 1 time, or however many you set in arrange_count:, arrange all does all of the possible arrange actions in one action so you dont have to do the 2 second arranges multiple times to learn more

**Comment by Kaesken** [comment]
Ok, thank you!

**Comment by Sarvatt** [comment]
no worries, its worth getting that technique though for massively increased learning though! 50 outfitting or engineering to get a technique slot isnt more than a few days throwing a craft outfitting in a before or something. you only need knitting needles. the bone and skin ones both let you arrange all anything.
