### ISSUE TITLE
Cam we add and appraisal focus option

### ISSUE THREAD

**Issue by Angel-DR** [rpherbig/dr-scripts#3553]
Hi guys, 

Can we please add appraisal focus?

It works really quick to lock appraisal (appraise focus defense), but also to boost a skill of choice i.e.: parry before battle. 

https://elanthipedia.play.net/Appraisal_skill#Appraise_focus

Thank you for your time and consideration. 

~Angel

**Comment by jandersson** [comment]
I'll take a look at it, this doesn't look to hard to integrate into the appraisal script (famous last words).

**Comment by Angel-DR** [comment]
Thank you!

**Comment by Angel-DR** [comment]
Thank you!!!

Angel
