### ISSUE TITLE
New Almanacs

### ISSUE THREAD

**Issue by DRBoxBoss** [rpherbig/dr-scripts#3559]
Greetings folks,

I have acquired one of the new almanacs and am excited to use it. According to a very knowledgeable person, I was told that you were able to use the almanac to keep 3 primary, 5 secondary, or 6 tertiary skills. Ideally having a set of variables to cycle through (maybe 3?) would be super.

The current almanac script doesn't work as each time that you go to study the new almanac you have to TURN TO SKILL (e.g. forging, astrology, athletics, etc). It works on a 10 min timer much like the original almanac. Let me know how I can assist with creating this script if you're willing to take it on. Thanks!

**Comment by Sarvatt** [comment]
basically he just wants to keep 3 5 or 6 skills moving from one skillset always and is asking for almanac to rotate through a list of skills.

**Comment by Sarvatt** [comment]
I’m on this, adding a yaml option to define what skills you want to train and pick the lowest mindstate one when the timer is up.

**Comment by DRBoxBoss** [comment]
Just wanted to say thank you for digging into this question and taking the time to make updates to accommodate the new almanac. Thanks again!
