### ISSUE TITLE
Armor hindrance textsubs are wrong

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#3562]
According to https://elanthipedia.play.net/Hindrance we are applying the shield textsub numbers to normal armor, which only has 8 hinderances instead of 15.

The shield list

Order | Hindrance
-- | --
0 | no
1 | insignificant
2 | trivial
3 | light
4 | minor
5 | fair
6 | mild
7 | moderate
8 | noticeable
9 | high
10 | significant
11 | great
12 | extreme
13 | debilitating
14 | overwhelming
15 | insane

The armor list

Order | Hindrance
-- | --
0 | no
1 | insignificant
2 | light
3 | fair
4 | moderate
5 | high
6 | great
7 | overwhelming
8 | insane

**Comment by Sarvatt** [comment]
I am getting this on a pair of gauntlets for example
You feel certain that some steel plate gauntlets etched with faint stars appear to impose light (3/15) maneuvering hindrance and light (3/15) stealth hindrance, offering:

instead of 2/2 hinderances it should be.

**Comment by rpherbig** [comment]
That article was only updated in February of this year. Do we trust this data?

**Comment by rpherbig** [comment]
https://elanthipedia.play.net/index.php?title=Hindrance&type=revision&diff=500475&oldid=488444

**Comment by Sarvatt** [comment]
armor has never had the middle tier hinderances like trivial mild minor, etc. i trust it.

**Comment by MahtraDR** [comment]
Closing this. We don't textsub hindrances anymore, since the game exposes that info natively.
