### ISSUE TITLE
Connectivity

### ISSUE THREAD

**Issue by Greydok** [rpherbig/dr-scripts#3565]
Is there a way to disable dependency's connectivity? It has been struggling to connect to something for a while and is not working during slow internet days. 

Why does it require a strong connection? All of the scripts and information are stored locally. Is it gathering player information? I am not attempting to be inflammatory. It works well when it works.

**Comment by Tarhish** [comment]
Could you elaborate a bit? Dependency doesn't need to constantly talk out except maybe for querying moonwatch, but that'd just fail to sync moons, not make everything else fail.

What's breaking for you? What messages are you seeing? What's actually not working?

**Comment by Tarhish** [comment]
To be clear, I'm curious because you're not the first person to get this impression.  It's making me wonder if something in some particular script is failing in a way that is causing confusion.

**Comment by jandersson** [comment]
I have ran into a case where dependency crashes due to a connection issue, I'm not sure if that is what @Greydok is referring to, but that is my guess.

**Comment by rcuhljr** [comment]
Stealing calls out to upload new stealing data. Moon related data synchs. Those are the only two I'm thinking of if you're not connect to slack.

**Comment by jayRyan24** [comment]
`Is it gathering player information?` is actually an inflammatory statement considering it's completely open source and everyone can read every bit of code in the system. It's like saying "i'm not racist but <insert racist remark>".

**Comment by jayRyan24** [comment]
The only connection issues I've experienced is 

A) when reading/writing to the stream, but that's the connection between the system and the game over the port, not with my local dependency and some offshoot dependency server which everyone connects to. 

B) Connecting to the lnet server, but this is separate from Dependency, `Lich != Dependency`.

**Comment by MahtraDR** [comment]
We do see issues with dependency connection sometimes, when github's cdns barf. 

Given this is 2 years old, and without updates. I'll close it for now. If this comes up again, we can see about following it up.
