### ISSUE TITLE
Combat will stall if right hand too injured to hold weapon

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#3575]
If right hand is too injured to hold a weapon, combat stalls and character just stands there until bleed out.  Would it be possible if hand is too injured to stop the hunt and go to healer?

[combat-trainer]>wield my finivire.slingshot

Your right hand is too injured to draw the finivire slingshot!
A cage of shadowy tendrils coalesces around a hulking Xala'shar magus.
A cage of shadowy tendrils coalesces around a hulking Xala'shar thrall.
* A hulking Xala'shar thrall thrusts a rusted dagger at you.  You deflect some of the dagger with a cerulean sprite-bone parry stick tangled in withered vines.  
[You're hurt, mighty, nimbly balanced with opponent in superior position.]
A hulking Xala'shar thrall strolls into view with a nervous gait, scanning the area with wide eyes.
A hulking Xala'shar magus chuckles softly and whispers, "Your incessant whispering amuses me, slave."
* A hulking Xala'shar thrall thrusts a rusted dagger at you.  You block with a diamondwood shield reinforced with silversteel spikes.  
[You're hurt, mighty, nimbly balanced and in very strong position.]
* A hulking Xala'shar magus slices a gnarled white oak staff with deeply carved markings at you.  You evade.  
[You're hurt, mighty, nimbly balanced with opponent in superior position.]
You feel fully attuned to the mana streams again.
The Xala'shar thrall moves into a position to parry.
* A hulking Xala'shar thrall jabs a rusted dagger at you.  You block with a diamondwood shield reinforced with silversteel spikes.  
[You're hurt, mighty, nimbly balanced and in strong position.]
* A hulking Xala'shar magus thrusts a gnarled white oak staff with deeply carved markings at you.  You partially block with a diamondwood shield reinforced with silversteel spikes.  
[You're hurt, mighty, nimbly balanced with opponent in good position.]
* A hulking Xala'shar thrall feints low at you.  You fend off most of the dagger with a cerulean sprite-bone parry stick tangled in withered vines.  
[You're hurt, mighty, nimbly balanced with opponent in very strong position.]

[combat-trainer: *** No match was found after 15 seconds, dumping info]

[combat-trainer: messages seen length: 49]

[combat-trainer: message: [You're hurt, mighty, nimbly balanced with opponent in very strong position.]]

[combat-trainer: message: * A hulking Xala'shar thrall feints low at you.  You fend off most of the dagger with a cerulean sprite-bone parry stick tangled in withered vines.  ]

[combat-trainer: message: [You're hurt, mighty, nimbly balanced with opponent in good position.]]

[combat-trainer: message: * A hulking Xala'shar magus thrusts a gnarled white oak staff with deeply carved markings at you.  You partially block with a diamondwood shield reinforced with silversteel spikes.  ]

[combat-trainer: message: [You're hurt, mighty, nimbly balanced and in strong position.]]

[combat-trainer: message: * A hulking Xala'shar thrall jabs a rusted dagger at you.  You block with a diamondwood shield reinforced with silversteel spikes.  ]

[combat-trainer: message: Centering  (24 roisaen)]

[combat-trainer: message: Minor Physical Protection  (24 roisaen)]

[combat-trainer: message: Soul Shield  (37 roisaen)]

[combat-trainer: message: Platinum Hands of Kertigen  (11 roisaen)]

[combat-trainer: message: Persistence of Mana  (OM)]

[combat-trainer: message: Osrel Meraud  (86%)]

[combat-trainer: message: Glythtide's Gift  (OM)]

[combat-trainer: message: Murrula's Flames  (OM)]

[combat-trainer: message: Bless  (OM)]

[combat-trainer: message: Auspice  (OM)]

[combat-trainer: message: Benediction  (OM)]

[combat-trainer: message: Shield of Light  (OM)]

[combat-trainer: message: Hydra Hex  (Indefinite)]

The swirling confines of malevolent darkness wane from about a hulking Xala'shar thrall.

[combat-trainer: message: Divine Radiance  (16 roisaen)]

[combat-trainer: message: Major Physical Protection  (25 roisaen)]

[combat-trainer: message: The Xala'shar thrall moves into a position to parry.]

[combat-trainer: message: You feel fully attuned to the mana streams again.]

[combat-trainer: message: [You're hurt, mighty, nimbly balanced with opponent in superior position.]]

A cage of shadowy tendrils coalesces around a hulking Xala'shar thrall.

[combat-trainer: message: * A hulking Xala'shar magus slices a gnarled white oak staff with deeply carved markings at you.  You evade.  ]

[combat-trainer: message: [You're hurt, mighty, nimbly balanced and in very strong position.]]

[combat-trainer: message: * A hulking Xala'shar thrall thrusts a rusted dagger at you.  You block with a diamondwood shield reinforced with silversteel spikes.  ]

[combat-trainer: message: A hulking Xala'shar magus chuckles softly and whispers, "Your incessant whispering amuses me, slave."]

[combat-trainer: message: A hulking Xala'shar thrall strolls into view with a nervous gait, scanning the area with wide eyes.]

[combat-trainer: message: [You're hurt, mighty, nimbly balanced with opponent in superior position.]]

[combat-trainer: message: * A hulking Xala'shar thrall thrusts a rusted dagger at you.  You deflect some of the dagger with a cerulean sprite-bone parry stick tangled in withered vines.  ]

[combat-trainer: message: Centering  (24 roisaen)]

[combat-trainer: message: Minor Physical Protection  (24 roisaen)]

[combat-trainer: message: Soul Shield  (38 roisaen)]

[combat-trainer: message: Platinum Hands of Kertigen  (11 roisaen)]

[combat-trainer: message: Persistence of Mana  (OM)]

[combat-trainer: message: Osrel Meraud  (86%)]

[combat-trainer: message: Glythtide's Gift  (OM)]

[combat-trainer: message: Murrula's Flames  (OM)]

[combat-trainer: message: Bless  (OM)]

[combat-trainer: message: Auspice  (OM)]

[combat-trainer: message: Benediction  (OM)]

[combat-trainer: message: Shield of Light  (OM)]

[combat-trainer: message: Hydra Hex  (Indefinite)]

[combat-trainer: message: Divine Radiance  (17 roisaen)]

[combat-trainer: message: Major Physical Protection  (25 roisaen)]

[combat-trainer: message: A cage of shadowy tendrils coalesces around a hulking Xala'shar thrall.]

[combat-trainer: message: A cage of shadowy tendrils coalesces around a hulking Xala'shar magus.]

[combat-trainer: message: Your right hand is too injured to draw the finivire slingshot!]

[combat-trainer: checked against [/You draw/i, /You deftly remove/i, /You slip/i, /Wield what/i, /With a flick of your wrist you stealthily unsheathe/i]]

[combat-trainer: for command wield my finivire.slingshot]

[tendme]>heal

A mischievous snow white kitten with taffelberry-stained paws hisses at a hulking Xala'shar thrall and rasps a tiny gutteral yowl.
A hulking Xala'shar magus glowers darkly at you.
Flickering shadows tear away from the Xala'shar magus's fingertips, shuddering through the air toward you!
The shadows rapidly dissipate as they draw near you.

Your body feels somewhat battered.
Your spirit feels full of life.
You have some minor abrasions to the neck, some tiny scratches to the left arm, some tiny scratches to the right leg, some minor abrasions to the left leg, an ugly stump for a right hand, some tiny scratches to the chest, some tiny scratches to the abdomen, some minor abrasions to the back, some minor abrasions to the right eye.

Bleeding
            Area       Rate              
-----------------------------------------
      right hand       very bad

**Comment by Sarvatt** [comment]
stop_hunting_if_bleeding: true is the default setting, did you override that anywhere?

**Comment by drgabellia** [comment]
Gah....I was totally unaware of this setting.  I will add it to my yaml ASAP and will close this thread.  Thanks, Sarv for your quick response - really appreciate all that you do.

**Comment by Sarvatt** [comment]
It's the default setting though, should be working now unless you set it to false in a yaml?

**Comment by rcuhljr** [comment]
That's a hunting-buddy setting I thought, if someone is using T2 or combat-trainer manually it's not going to kick in.
