### ISSUE TITLE
exclude thieves/barbs from sanowret_no_use_scripts

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#3579]
The spells are blacklisted here because magic users want to avoid tanking concentration too much which isn't a problem for these two, we could make sanowret.lic ignore that setting based on the guild.

**Comment by simiydr** [comment]
Thieves should not be excluded from this, as khri are concentration-based abilities and having sanowret run during combat would be quite... unfortunate.

**Comment by Sarvatt** [comment]
they are specifically the ones that have complained ever since I made this change! :D

**Comment by Sarvatt** [comment]
i'm sure all the ones complaining are decked out in concentration regen items I guess

**Comment by Sarvatt** [comment]
closing this, there is no consensus and it just needs commenting in base.yaml to explain the situation.
