### ISSUE TITLE
Simplify script download process

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#358]
From @rcuhljr : we should just switch to downloading all of our scripts on initial install. Anything existing with the same name gets backed up to a text file. This solves all of our blocking issues and removes the cumbersome get_script  business.

**Comment by rcuhljr** [comment]
Probably relevant to this change? make base.yaml a tracked and dowloaded resource.

**Comment by rpherbig** [comment]
Make sure to update https://github.com/rpherbig/dr-scripts/wiki/Setup-Process

**Comment by rcuhljr** [comment]
Think we can close this?

**Comment by rpherbig** [comment]
Have you tested on a fresh install?

**Comment by rpherbig** [comment]
I just ran through a fresh install and it worked perfectly.
