### ISSUE TITLE
Swappable Weapons + Nerve Damage

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#3588]
Okay, so I've decreased my health threshold so my character will visit Dokt's more often but wasn't sure if you guys would like to know that if nerves are badly damaged, you can't swap weapons (which makes sense, lol).  In case someone wanted to include a stop hunt to go to Dokt on a message such as this because it snags the script and won't do anything else at all:

> swap my sword
Will alone cannot conquer the paralysis that has wracked your body.

**Comment by Sarvatt** [comment]
another message that happens with severe paralysis and breaks combat https://github.com/rpherbig/dr-scripts/issues/2952

**Comment by Kaesken** [comment]
Ahh, didn't see that else I woulda added it there, my bad!  Thank you.  :)
I had my health threshold set to 70 but nerves tend to get fried faster than my health gets before it triggers Dokts, lol  I just didn't want to keep going to Dokt with a couple minor abrasions, y'know?  XD
Especially with those long lines here lately.  @-@

**Comment by Sarvatt** [comment]
severe paralysis of the entire body and no other wounds is only a 7, you may want to figure out why you're backfiring too much. is auto mana doing it in combat_training_spells maybe? that's the usual cause, and there is a feat you can get to help

**Comment by Kaesken** [comment]
Ahh, yes I am using auto mana so I don't have to continuously have to change it all the time.

**Comment by Sarvatt** [comment]
may want to grab Cautious Casting asap, that should stop any injuries
