### ISSUE TITLE
locksmithing.lic allow more than one lockbox

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#3590]
Would it be possible to update lockbox to support multiple of the same lockbox (I have 3 of the training boxes)

**Comment by mtruitt** [comment]
As a work around. I just made a copy of the script and updated it to get third. This allowed me to also toggle them without additional code. and I just run it as a before/after as lockbox2

**Comment by MahtraDR** [comment]
@mikejcook could you grab this one? I'm thinking introduce a setting for number of lockboxes, and add ordinal if greater than 1.

**Comment by mikejcook** [comment]
@MahtraDR  Sure thing. Interesting - it looks like we actually have two scripts in the repo. There's locksmithing and lockbox. Lockbox ONLY works with daily trainers, while locksmithing works with dailies, burgle lockboxes, and calls pick, as well.

Glancing over locksmithing, there are a couple things that can be cleaned up in it, beyond adding support for multiple training boxes, but it's generally in a better state than lockbox is/was.

It feels like it might make sense to drop lockbox altogether. This definitely replicates all of its functionality. That will break any existing scripts, but having both of these seems problematic. Thoughts?

**Comment by MahtraDR** [comment]
Sounds good to me to drop lockbox.lic from the repo and have this functionality in locksmithing.lic

**Comment by MahtraDR** [comment]
@mikejcook sorry, I was on my phone. I think we should drop lockbox.lic. I see that trade.lic is the only script that calls, so we'll need to change that one script. It looks like we might be able to simply point trade.lic at locksmithing.lic instead and that'll be there.

**Comment by MahtraDR** [comment]
Did not mean to close. Apologies.

**Comment by MahtraDR** [comment]
@urbaj-dr Have you tested locksmithing.lic in trade.lic as a replacement to lockbox.lic by chance? If not, could you?
