### ISSUE TITLE
Forge: shovel and bellows doesn't work if crucible isn't empty

### ISSUE THREAD

**Issue by dakre18** [rpherbig/dr-scripts#3591]
When forging, i found if the crucible isn't empty, you cannot use your bellows or shovel. It's a DR bug that the GM specifically said the parser stops at the crucible if anything is in it, which is why it wasn't working with the bellows or shovel. It would help if the script could empty the crucible OR give a warning to empty the crucible if it isn't empty.

While the script is running, it will ignore the bellows and continue to craft with that mistake, but the shovel will break the script, running into an infinite loop. The message that appears is "You cannot figure out how to do that.  Perhaps finding suitable ingredients and studying some instructions would help."

**Comment by rpherbig** [comment]
> When forging

Were you using `smelt.lic`?

**Comment by dakre18** [comment]
No, i was using workorders blacksmithing. In this case, the particular forge i was using had ingots left in the crucible for some reason, and was causing me to sit in an infinite loop until i figured out what was causing it.

**Comment by Tarhish** [comment]
Can I get a clarification?  If workorders decides it needs to smelt, it stuffs some ingots in the crucible then starts ;smelt.  ;smelt works with things in the crucible already, since that's its intended use.  So at what point did things screw up?  Did ;smelt fail to stir the crucible?

**Comment by dakre18** [comment]
the problem is not when using smelt.lic, it's when trying to forge on an anvil with a crucible in the room.

there's one room in The Crossing forge if you need to test, but if you have something in the crucible while forging, you cannot use your bellows or shovel because of a DR Parser bug.

**Comment by BinuDR** [comment]
What room number?

**Comment by dakre18** [comment]
Also if it matters, forge summoning wands include crucibles.

**Comment by MahtraDR** [comment]
Resolved by https://github.com/rpherbig/dr-scripts/pull/6009
