### ISSUE TITLE
workorders - expired workorder is not handled

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#362]
You go east.
[Forging Society, Tool Store - 8776]
Masters and journeyman of the forging craft find a home in this room purchasing tools and ingredients.  Loud thumps and groaning accompany the loading and unloading of goods from storage.  You also see Forging Society Mistress Yalda, a steel crate, a large sign, a sturdy low counter with a small placard on it and a clerk.
Obvious exits: north, south, west.
>
[go2: travel time: 0:00:00]
--- Lich: go2 has exited.
[workorders]>give log to Yalda
Apparently the work order time limit has expired.  You should untie any items bundled with it and then ask Yalda for another.
>
[workorders: *** No match was found after 15 seconds, dumping info]
[workorders: messages seen length: 1]
[workorders: message: Apparently the work order time limit has expired.  You should untie any items bundled with it and then ask Yalda for another.]
[workorders: checked against [/You hand/i, /You can/i]]
[workorders]>retreat
You are already as far away as you can get!
>
--- Lich: go2 active.
[go2: ETA: 0:00:00 (2 rooms to move through)]
[go2]>west
You go west.
[Forging Society, Lobby and Maker's Mark Ordering - 8772]
A chamber with stone walls and a lofty, vaulted ceiling links the rooms of the forge.  Its high arches help to subdue the clangor, letting it rise and echo in the space overhead.  Waves of heat and flickering reddish light from the foundries to the west strive with the scream of the grindstones to the east and the pounding din of metal on metal from the smithies to the south.  You also see a large sign, an armorsmithing chart hanging from the wall, a weaponsmithing chart hanging from the wall and a blacksmithing chart hanging from the wall.
Obvious exits: north, east, south, west.
>
[go2]>north
You go north.
[Forging Society, Book Store - 8771]
Freshly chiseled granite walls surround an area where forgers can quickly resupply.  A passageway covered by a leather flap pierces the wall to the south, and from the passage resound the clangs of an anvil chorus.  A simple wooden door leads back outside.  You also see a prestige board and a large sign.
Obvious exits: south.
>
[go2: travel time: 0:00:00]
--- Lich: go2 has exited.
--- Lich: go2 active.
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>south
You go south.
[Forging Society, Lobby and Maker's Mark Ordering - 8772]
A chamber with stone walls and a lofty, vaulted ceiling links the rooms of the forge.  Its high arches help to subdue the clangor, letting it rise and echo in the space overhead.  Waves of heat and flickering reddish light from the foundries to the west strive with the scream of the grindstones to the east and the pounding din of metal on metal from the smithies to the south.  You also see a large sign, an armorsmithing chart hanging from the wall, a weaponsmithing chart hanging from the wall and a blacksmithing chart hanging from the wall.
Obvious exits: north, east, south, west.
>
[go2: travel time: 0:00:00]
--- Lich: go2 has exited.
--- Lich: go2 active.
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>south
You go south.
[Forging Society, Supplies - 8775]
A chamber with stone walls and a lofty, vaulted ceiling links the rooms of the forge.  Its high arches help to subdue the clangor, letting it rise and echo in the space overhead.  Waves of heat and flickering reddish light from the foundries to the west strive with the scream of the grindstones to the east and the pounding din of metal on metal from the smithies to the south.  You also see a large sign, a central arch, a western arch and an eastern arch.
Obvious exits: north.
>
[go2: travel time: 0:00:00]
--- Lich: go2 has exited.
--- Lich: go2 active.
[go2: ETA: 0:00:00 (2 rooms to move through)]
[go2]>north
You go north.
[Forging Society, Lobby and Maker's Mark Ordering - 8772]
A chamber with stone walls and a lofty, vaulted ceiling links the rooms of the forge.  Its high arches help to subdue the clangor, letting it rise and echo in the space overhead.  Waves of heat and flickering reddish light from the foundries to the west strive with the scream of the grindstones to the east and the pounding din of metal on metal from the smithies to the south.  You also see a large sign, an armorsmithing chart hanging from the wall, a weaponsmithing chart hanging from the wall and a blacksmithing chart hanging from the wall.
Obvious exits: north, east, south, west.
>
[go2]>east
You go east.
[Forging Society, Tool Store - 8776]
Masters and journeyman of the forging craft find a home in this room purchasing tools and ingredients.  Loud thumps and groaning accompany the loading and unloading of goods from storage.  You also see Forging Society Mistress Yalda, a steel crate, a large sign, a sturdy low counter with a small placard on it and a clerk.
Obvious exits: north, south, west.
>
[go2: travel time: 0:00:00]
--- Lich: go2 has exited.
[workorders]>give log to Yalda
Apparently the work order time limit has expired.  You should untie any items bundled with it and then ask Yalda for another.

**Comment by rcuhljr** [comment]
Fixed hopefully.
