### ISSUE TITLE
Combat-Trainer failing when starting

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#3622]
At least one other person experiencing the same issue.  Basically it is failing to check everything from the start.  It can't find the stance check, orb check, then finally it pulls out my shortbow, loads it, and keeps trying to load it forever, doesn't progress past that because it doesn't realize the shortbow is already loaded, so keeps trying to load.  

https://pastebin.com/7zpFkW2x

**Comment by Sarvatt** [comment]
you're going to need to paste the contents of Yourname-sheld.yaml, that's where the problem is.

**Comment by Sarvatt** [comment]
that's what ;combat shield runs.

**Comment by wscherer420** [comment]
https://pastebin.com/wJ7K5YK0

**Comment by wscherer420** [comment]
Tried logging out and didn't fix it.  Here is the log.  Combat-trainer is failing on all my files.  -Shield, -Stealth, -Primary

**Comment by wscherer420** [comment]
So it appears the issue isn't isolated to ;combat-trainer.  I'm having issues with ;go2 as well.  Same thing, just not reading checks at all.  See attached.  https://pastebin.com/Ay4vueZF

**Comment by wscherer420** [comment]
Fixed itself somehow i guess.  No longer having the issue.  Thank you!
