### ISSUE TITLE
 add SPELL, FIELD to ;researcher

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#3628]
Please  add SPELL, FIELD to ;researcher under skills option. 

 ;researcher <skill>
  skill        What skill or type of research do you want to do? [attunement, augmentation, fundamental, symbiosis, utility, warding]

 ;researcher symbiosis <sym_type>
  symbiosis    Do symbiosis research?
  sym_type     Which symbiosis do you want to research? [activate, avoid, cast, discern, endure, examine, explore, harness, harvest, heal, impress, learn, perform, remember, resolve, spell, spring, strengthen, watch]

**Comment by drgabellia** [comment]
Love this script!  Any chance there could be an addition where it pauses other scripts that are running?  When I infuse my OM orb, for example, it interrupts the research and it costs me some time.  
[om]>infuse om 50

Are you sure you want to do that?  You'll interrupt your research!
[Enter your command again if you want to.]

[om: *** No match was found after 15 seconds, dumping info]

[om: messages seen length: 34]

(removed a bunch of misc msg)

[om: message: Are you sure you want to do that?  You'll interrupt your research!]

[om: checked against [/having reached its full capacity/i, /a sense of fullness/i, /Something in the area is interfering with your attempt to harness/i, /as if it hungers for more/i, /Your infusion fails completely/i, /You don't have enough harnessed mana to infuse that much/i, /You have no harnessed/i]]

[om: for command infuse om 50]

[om]>infuse om 50

You lose your focus on your research project.  <-- this

**Comment by jandersson** [comment]
Glad to hear you like it. I'll need to submit this to the repo first. I'll add the field as part of the submission.

**Comment by Aurayn** [comment]
field and spell if you please

**Comment by Aurayn** [comment]
Bumping this?

**Comment by jandersson** [comment]
Wasn't a script added for researching?

**Comment by Aurayn** [comment]
I have no idea where this is at at the moment. As far as I can tell ;researcher doesn't incorporate FIELD and SPELL yet.


>;researcher help
--- Lich: researcher active.

  ;researcher 

  ;researcher <skill>
   skill        What skill or type of research do you want to do? [attunement, augmentation, fundamental, symbiosis, utility, warding]

  ;researcher symbiosis <sym_type>
   symbiosis    Do symbiosis research? 
   sym_type     Which symbiosis do you want to research? [activate, avoid, cast, discern, endure, examine, explore, harness, harvest, heal, impress, learn, perform, remember, resolve, spell, spring, strengthen, watch]
--- Lich: researcher has exited.

**Comment by Aurayn** [comment]
>;researcher symbiosis spell
>
--- Lich: researcher active.
You feel as if a predator is watching you from the shadows.
>
Etry refreshes your memory and continues to train you in the Athletics skill.
> 
[researcher]>research status
You're not researching anything!
>
[researcher: researching=true]
[researcher: researching=false]
[researcher: Using waggle set settings]
[researcher: waggle data: {"Gauge Flow"=>{"skill"=>"Utility", "mana"=>5, "abbrev"=>"gaf", "mana_type"=>"ap", "cambrinth"=>[25, 25, 25, 20]}}]
[researcher]>release mana
You aren't harnessing any mana.
>
[invasion-watch: Watching for invasions in the following rooms: [820, 1034, 1051, 1230, 7301, 6163]]
[sleep65: 6163]
[sleep65: Leaving after 65 minutes]
[sleep65: 3900]
>
[researcher]>prep gaf 5
You raise your arms skyward, chanting the equation of the Gauge Flow spell.
>
[researcher]>harness 25
You tap into the mana from twenty-five of the surrounding streams and attempt to keep it channeling in a stream around you.
Roundtime: 2 sec.
>
[researcher]>harness 25
>
You tap into the mana from twenty-five of the surrounding streams and add it to the appreciable amount already streaming around you.
Roundtime: 2 sec.
>
[researcher]>harness 25
You tap into the mana from twenty-five of the surrounding streams and add it to the vast amount already streaming around you.
Roundtime: 2 sec.
>
[researcher]>harness 20
...wait 2 seconds.
>
[researcher]>harness 20
You tap into the mana from twenty of the surrounding streams and add it to the extreme amount already streaming around you.
Roundtime: 2 sec.
>
You feel fully prepared to cast your spell.
>
[researcher]>cast
You gesture.
You contribute your harnessed streams to increase the pattern's potential.
A distracting flurry of cold white mana momentarily blinds you.  As your eyes adjust, you notice local fluctuations in mana are being represented by white graphs and sigils in the corners of your sight.
>
[researcher]>research symbiosis spell 300
Please specify a valid symbiosis to research.

**Comment by jandersson** [comment]
Is there a script for researching?

**Comment by jandersson** [comment]
Hi folks, this isn't a script in the repository unfortunately. I don't have plans to update the one in the lich repo due to time. 

If this is still a wanted script, I think making an issue for it would be a good start so it can be tracked.
