### ISSUE TITLE
go2.lic needs merging

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#3632]
updated upstream https://github.com/matt-lowe/Lich/commits/master/scripts/go2.lic

**Comment by MahtraDR** [comment]
@rpherbig Do we want this? I can submit. Or close?

**Comment by rpherbig** [comment]
I think it would be prudent to at least do a diff and see if there are any changes we need to pull in

**Comment by MahtraDR** [comment]
I need to learn better git. It must be possible to go commit by commit. In the mean time, I have a diff here https://github.com/rpherbig/dr-scripts/compare/master...MahtraDR:creating_a_branch_to_compare_upstream_go2_against_ours?expand=1

**Comment by MahtraDR** [comment]
Actually, it's not many at all.

Starting here https://github.com/matt-lowe/Lich/commits/master/scripts/go2.lic

We have the DR-specific commit already. The others are all GS-specific, I think. They're all very small commits, with some rapid version bumping in between. I don't think we should rebase, or need any of those commits...

**Comment by rpherbig** [comment]
Thank you for doing the investigation
