### ISSUE TITLE
small cord part missing from "some metal hand claws" in base-recipes.yaml

### ISSUE THREAD

**Issue by SekmehtDR** [rpherbig/dr-scripts#3633]
- name: some metal hand claws
  noun: claws
  volume: 4
  type: weaponsmithing
  work_order: true
  chapter: 8
  part:
  - short cord

(Short Cord is missing and needs the part added, drives me nuts when this file updates).

**Comment by Sarvatt** [comment]
you shouldn't be doing weaponsmithing in ;workorders no matter what you have techs in, but I submittted a fix.

**Comment by Sarvatt** [comment]
forge assumes you can use society ingots, aka 5 volumes at a time.

**Comment by SekmehtDR** [comment]
Ah right in I didn’t even know because handclaws are 4 volumes lol
