### ISSUE TITLE
TENDing needed in Clay Soldiers

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#3636]
Auto tending is not initiating/working to remove clay fragments:

A grey clay fragment flies directly at you!  You raise your shield to block the clay shard.
[You're bruised, nimbly balanced with opponent in superior position.]
A grey clay fragment flies directly at you!  You raise your shield to block the clay shard.
[You're bruised, nimbly balanced with opponent in superior position.]
A grey clay fragment flies directly at you!  You raise your shield to block the clay shard.
[You're bruised, nimbly balanced with opponent in superior position.]
A grey clay fragment flies directly at you!  It lodges shallowly in your left arm!
[You're bruised, nimbly balanced with opponent in superior position.]

Your body feels at full strength.
Your spirit feels full of life.
You are slightly fatigued.
You have some moderately deep cuts about the left arm.
Bleeding
            Area             Rate              
-----------------------------------------
            left arm       slight
You have a grey clay fragment lodged firmly into your left arm.

**Comment by jandersson** [comment]
We should see if there's any existing 'check for lodged' functionality in combat-trainer and update it to include this. If it doesn't exist, maybe we can add a flag to detect the `It lodges shallowly in your left arm!` message and use `tendme.lic`'s logic to remove it.

**Comment by MahtraDR** [comment]
This is in tendme today.
