### ISSUE TITLE
Stealing script

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#3638]
I can't get the stealing script to work.  It was working in the beginning but after each of my chars hit 40 ranks of thievery, it suddenly would do this:
[hunting-buddy: ***STATUS*** EXECUTE steal]

--- Lich: steal active.

[steal: ***NO VALID TARGETS FOUND***]

--- Lich: steal has exited.

I have this set:
# Stealing Settings
stealing_bag: rucksack
hide_to_steal: true
bin_stolen: true
stealing_towns:
  - Crossing
  - Arthe Dale
  - Kaerna Village
  - Tiger Clan
  - Knife Clan
  - Dirge
stealing_buffs:
  khri:
   - Plunder

**Comment by Sarvatt** [comment]
it tracks everything you steal on a 1 hour timer, if that timer isn't up it wont teach you skill so it wont steal it. it'll open up in 20-30 more ranks.

**Comment by Kaesken** [comment]
But I've been stuck at 41 ranks for the past 3 days...

**Comment by Kaesken** [comment]
My warmage has 35 ranks of thievery so it trained her to 10/34 but the others are about 40 and 41 and it's stays at 0/34 and keeps skipping it.

**Comment by Kaesken** [comment]
I deleted the variable as a friend suggested and it executed the script but it only trained it to 2/34 before quitting even with my EXP timer variable.  :(

**Comment by rpherbig** [comment]
One thing that might help is if you could modify `steal.lic` and add a line of code between lines 55 and 56 (the middle line with the `echo`):
```ruby
    targets = find_targets(args.item, args.container)
    echo "@stealing_options: #{@stealing_options}"
    npcs = settings.npc_stealing_attempt_count > 0 ? find_npcs : []
```

**Comment by Sarvatt** [comment]
setting npc_stealing_attempt_count: 2 may help also so you get a few extra steal attempts. deleting the variable doesn't help, the items literally wont teach you more than once an hour. there is an in game timer for learning from the same steal.

**Comment by Kaesken** [comment]
Well, I did something similar to that.  I made a 2nd copy of it and named it steal2 and removed all the timers and cooldowns from it and the variable setting at the top and then I put the low skill count to 10 but keptthe difficulty skill count at 1 and it has been locking thievery now!

Thanks for your help, hun.  :)
I'll go ahead and close this.  ^-^
