### ISSUE TITLE
swapping weapons with a hurt hand breaks combat trainer

### ISSUE THREAD

**Issue by proctophage** [rpherbig/dr-scripts#3640]
https://pastebin.com/U47Ueaxi

**Comment by Arkluras** [comment]
How is your right hand being injured? Sorcery backlash?

**Comment by proctophage** [comment]
No. It just had a slight bleeder.

**Comment by Arkluras** [comment]
Interesting. That definitely needs to be handled then.

**Comment by jayRyan24** [comment]
Sounds like you're too injured to hunt then? I could handle this by going through the swap routine and if you are too injured, just removing that skillset from training, but this will lopside your weapons. Is this really the best fix, or should you leave combat if bleeding to go get healed? I'll be honest, I don't hunt places that can injury me to this point. It could be that you're hunting too long and the small nicks are adding up, you're hunting too high, or you're encumbered?

**Comment by jayRyan24** [comment]
I don't personally think this is something that should be handled, but I could definitely do it. @rpherbig @jandersson @Sarvatt @dr-leustyin may have different opinions and better ones though, I could be thinking too small.

**Comment by proctophage** [comment]
I have it set to stop hunting when bleeding. The zoluren hunting ladder is very unforgiving trying to make the next step up. You either don't get past 1/34 at certain places, or you hunt things that can give you bleeders within a half hour of hunting them. Not encumbered. Using the full suite of buffs available to me. Decent crafted gear in full repair. TDPs all spent. This is just what you have to deal with as a F2P. Is it too much to ask to just put something in to exit the hunting routine entirely and go get healed when this occurs?

**Comment by jandersson** [comment]
Ive had this problem and only hacked out a solution, just to get me going again. A fix/hack/bandaid is better than the current fail loop IMO.

**Comment by jayRyan24** [comment]
OK, so my idea is to just remove the skill from the trainer if this message is received. What do you guys think? :D It's already something we do in some instances, and shouldn't be that difficult. What is your hack @jandersson ?

**Comment by jayRyan24** [comment]
Remove skill and say `"WOUNDED, CANNOT SWAP WEAPON, REMOVING SKILL FROM TRAINING!"`

**Comment by jandersson** [comment]
My repository is a mess right now, but let me see if i can find it.

**Comment by jayRyan24** [comment]
> Is it too much to ask to just put something in to exit the hunting routine entirely and go get healed when this occurs?

Not too much of a task, but code bloat is a thing. We are already righteously abounding with it though, so there's that. This is why I brought in other's opinions.

**Comment by jayRyan24** [comment]
Of course swapping the weapon is handled in equipment manager, making this not as easy as "all I gotta do is"... lovely.

**Comment by jayRyan24** [comment]
I'll just make the method return a boolean.

**Comment by jandersson** [comment]
No worries about code bloat with this failure here. I cannot find the change I made but and I am convinced it wont be helpful, if you want to me to dig for it let me know. I would opt for ending the hunt. You can no longer train what you've decided to train plus Its the easy solution. 

I would say removing it from the training list is a solution, but consider that the hunt might be targeted at that skill.

**Comment by jayRyan24** [comment]
How is the hunt not ended if he is bleeding?

**Comment by Tarhish** [comment]
I don't know if this is what happened, but my read on the logic is that if skip_last_kill is false (as default), and the hunt times out before you start bleeding, clean_up_step will become 'kill' and at that point you'll stay in the hunt until the mob you're fighting dies, even if you start bleeding from that point on.

I think this came up recently -- it's kind of an odd coincidence.  I couldn't say without more of the log, but you'd see the hunt out of time messaging.

**Comment by jandersson** [comment]
> How is the hunt not ended if he is bleeding and he doesn't have end hunting while bleeding false?
I hope the hunt is ended if so. Is that not whats happening?

**Comment by jayRyan24** [comment]
Yeah, but he's saying a slight bleeder is not allowing him to swap, but he says that `stop_hunting_if_bleeding: true` is set. Why isn't it ending the hunt then?

**Comment by Tarhish** [comment]
To clarify what I was posing as a question:
```
    case @clean_up_step
    when nil
      @clean_up_step = if @stop_on_bleeding && bleeding?
                         'clear_magic'
                       elsif @skip_last_kill
                         'clear_magic'
                       else
                         'kill'
                       end
    when 'kill'
      @clean_up_step = 'clear_magic'
    when 'clear_magic'
      @clean_up_step = 'dismiss_pet'
    when 'dismiss_pet'
      @clean_up_step = 'stow'
    when 'stow'
      @clean_up_step = 'done'
    end
```

When the hunt is just going along, clean_up_step is nil so if you're bleeding this sees that and starts ending the hunt.  But once time runs out on the hunt, it becomes 'kill', and it won't check to see if you're bleeding anymore.  It'll only move on from 'kill' once def execute in LootProcess hits:

```
    if (game_state.mob_died || game_state.npcs.empty?) && game_state.finish_killing?
      15.times do
        break unless Flags['using-corpse']
        break if DRRoom.dead_npcs.empty?
        pause
      end
      stow_lootables(game_state)
      echo('LootProcess::clean_up') if $debug_mode_ct
      game_state.next_clean_up_step
    end
```

IE, that mob ded.  There's enough shenanigans with the various processes touching this that I'm not certain, but I think that's right.

**Comment by jandersson** [comment]
oh yea i see - i think getting stalled

**Comment by jayRyan24** [comment]
Sorry didn't even see your comments T. If that's what's happening, OK. This is such a one off. Is this the scenario the OP was having? @proctophage

**Comment by Tarhish** [comment]
Ugh, there's so much involved in this.

I think def start_combat in the CombatTrainer class stops looking for new stop events once it starts cleaning up.

```
      next unless @stop && !@game_state.cleaning_up?
      @game_state.next_clean_up_step
      @game_state.stop_weak_attacks
      @game_state.stop_analyze_combo
```
This is, I think, when it gets the stop signal from hunting buddy.  Then next_clean_up_step does

```
def next_clean_up_step
    echo("  Changing from clean up step #{@clean_up_step}") if $debug_mode_ct
    case @clean_up_step
    when nil
      @clean_up_step = if @stop_on_bleeding && bleeding?
                         'clear_magic'
                       elsif @skip_last_kill
                         'clear_magic'
                       else
                         'kill'
                       end
    when 'kill'
      @clean_up_step = 'clear_magic'
    when 'clear_magic'
      @clean_up_step = 'dismiss_pet'
    when 'dismiss_pet'
      @clean_up_step = 'stow'
    when 'stow'
      @clean_up_step = 'done'
    end
  end
```
So if combat-trainer gets the @stop signal from hunting-buddy to end the hunt due to skills, time, etc. it stops going into next_clean_up_step, so it won't catch a new bleeder.

**Comment by proctophage** [comment]
Did this ever get fixed?

**Comment by Ry7n** [comment]
#3741 #3338 #2952 #1664 All seem like duplicates of this issue.

**Comment by rpherbig** [comment]
Worth noting here, though not required to be fixed as part of closing this if it turns out to be a different fix:
```
[combat-trainer]>swap my riste

* Looking as if this were a bad idea, an Endrus serpent bites at you.  You partially block with a metal target shield.  
[You're solidly balanced and opponent has slight advantage.]
> 
Will alone cannot conquer the paralysis that has wracked your body.
> 
[combat-trainer: *** No match was found after 15 seconds, dumping info]

[combat-trainer: messages seen length: 21]
> ,ka
```
