### ISSUE TITLE
workorder remedies

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#3647]
I'm not sure if I'm doing this wrong or not?
Here's my YAML settings:
train_workorders:
- Remedies
crafting_container: duffel bag
alchemy_belt:
  name: grass toolstrap
  items:
  - iron mortar
  - iron pestle
  - large jar
  - mixing stick
  - wire sieve
train_workorders: true
craft_max_mindstate: 31

> [workorders]>get my alchemy logbook
> 
> You get an alchemy work order logbook from inside your duffel bag.
> > 
> [workorders]>ask Lanshado for challenging remedies work
> 
> Lanshado shuffles through some notes and says, "Alright, this is an order for some limb salve. I need 5 stacks (5 uses each) of superior quality, made from any material and due in 180 roisaen.  Please complete the items, bundle them with your logbook and then give me the logbook to complete this order.  Good luck!"
> 
> You seem to recall this item being somewhere in chapter 3 of the instruction book.
> > 
> > 
> [workorders]>ask Lanshado for challenging remedies work
> 
> > 
> Lanshado shuffles through some notes and says, "Alright, this is an order for some skin salve. I need 3 stacks (5 uses each) of superior quality, made from any material and due in 110 roisaen.  Please complete the items, bundle them with your logbook and then give me the logbook to complete this order.  Good luck!"
> 
> You seem to recall this item being somewhere in chapter 3 of the instruction book.
> > 
> [workorders]>ask Lanshado for challenging remedies work
> 
> Lanshado shuffles through some notes and says, "Alright, this is an order for an eye potion. I need 2 stacks (5 uses each) of superior quality, made from any material and due in 75 roisaen.  Please complete the items, bundle them with your logbook and then give me the logbook to complete this order.  Good luck!"
> 
> You seem to recall this item being somewhere in chapter 4 of the instruction book.
> > 
> [workorders]>put my logbook in my duffel bag
> 
> You put your logbook in your duffel bag.
> > 
> [workorders]>wealth kronars
> 
>   3 platinum Kronars (30000 copper Kronars).
> > 
> [workorders]>get coal nugget from my duffel bag
> 
> You get a massive coal nugget from inside your duffel bag.
> > 
> [workorders]>app my coal nugget
> 
> The coal nugget is made with metal.
> 
> You are certain the coal nugget would work well as an alchemical catalyst.
> 
> You are certain the coal nugget has a volume of 10.
> You are confident that the coal nugget might weigh a few stones.
> You are certain that the coal nugget is worth exactly 87 Kronars.
> Roundtime: 8 seconds.
> R> 
> R> 
> > 
> [workorders]>put my coal nugget in my duffel bag
> 
> You put your nugget in your duffel bag.
> > 
> [workorders]>get second coal nugget from my duffel bag
> 
> What were you referring to?
> > 
> [workorders]>get water from my duffel bag
> 
> You get some water from inside your duffel bag.
> > 
> [workorders]>count my water
> 
> There are ten parts left of the water.
> > 
> [workorders]>put my water in my duffel bag
> 
> You put your water in your duffel bag.
> > 
> [workorders]>get water from duffel bag
> 
> You get some water from inside your duffel bag.
> > 
> [workorders]>get water from duffel bag
> 
> What were you referring to?
> > 
> [workorders]>put my water in my duffel bag
> 
> You put your water in your duffel bag.
> > 
> [workorders]>tap first aevaes in my duffel bag
> 
> > 
> I could not find what you were referring to.
> > 
> --- Lich: go2 active.
> 
> [go2: ETA: 0:00:00 (1 rooms to move through)]
> 
> [go2]>south
> 
> You limp south.
> 
> [Alchemy Society, Supplies]
> A pungent odor combines with the powder-filled air to make breathing here more difficult.  Racks of spices, herbs, plants and other materials line the walls as attendants scurry about helping customers.  Pewter trays in each corner hold burning incense sticks.  Despite the size and large amount of smoke wafting from each stick, it is nearly impossible to detect even a hint of their scent.
> You also see a dry press, a large sign and a plant grinder.
> Obvious exits: north, south.
> 
> > 
> [go2: travel time: 0:00:00]
> 
> --- Lich: go2 has exited.
> 
> [workorders]>order 10
> 
> The attendant says, "You can purchase (25 pieces) crushed aevaes for 537 Kronars.  Just order it again and we'll see it done!"
> > 
> [workorders]>order 10
> 
> The attendant takes some coins from you and hands you (25 pieces) crushed aevaes.
> 
> > 
> [workorders]>put my crushed aevaes in my duffel bag
> 
> You put your aevaes in your duffel bag.
> > 
> [workorders]>order 10
> 
> The attendant says, "You can purchase (25 pieces) crushed aevaes for 537 Kronars.  Just order it again and we'll see it done!"
> > 
> [workorders]>order 10
> 
> The attendant takes some coins from you and hands you (25 pieces) crushed aevaes.
> 
> > 
> [workorders]>put my crushed aevaes in my duffel bag
> 
> You put your aevaes in your duffel bag.
> > 
> --- Lich: remedy active.
> 
> --- Lich: buff active.
> 
> --- Lich: buff has exited.
> 
> [remedy]>get remed book
> 
> You get a book of apprentice remedy instructions from inside your duffel bag.
> > 
> > 
> > 
> [remedy]>turn my book to chapter 4
> 
> The book is already turned to chapter 4, entitled "Internal Wound Remedies".
> > 
> [remedy]>read my book
> 
>               -=    Chapter 4 : Internal Wound Remedies    =-
> 
>  Page 1: a neck potion                           Page 4: a head potion
>  Page 2: an abdomen potion                       
>  Page 3: a chest potion                          
> 
> > 
> > 
> You begin to lose focus on your cambrinth tailband.
> > 
> [remedy: *** No match was found after 15 seconds, dumping info]
> 
> [remedy: messages seen length: 7]
> 
> [remedy: message: You begin to lose focus on your cambrinth tailband.]
> 
> [remedy: message: Refresh  (15 roisaen)]
> 
> [remedy: message: Iron Constitution  (14 roisaen)]
> 
> [remedy: message:  Page 3: a chest potion                          ]
> 
> [remedy: message:  Page 2: an abdomen potion                       ]
> 
> [remedy: message:  Page 1: a neck potion                           Page 4: a head potion]
> 
> [remedy: message:               -=    Chapter 4 : Internal Wound Remedies    =-]
> 
> [remedy: checked against [/Page \d+.*an eye potion/i]]
> 
> [remedy: for command read my book]
> 
> [remedy]>turn my book to page 
> 
> Which page do you wish to turn the a book of apprentice remedy instructions to?
> > 
> Some of the faces on your bowtie bump into one another but quickly correct course to rejoin the others.
> > 
> > 
> > 
> > 
> > 
> [remedy: *** No match was found after 15 seconds, dumping info]
> 
> [remedy: messages seen length: 6]
> 
> [remedy: message: Refresh  (14 roisaen)]
> 
> [remedy: message: Iron Constitution  (13 roisaen)]
> 
> [remedy: message: Refresh  (14 roisaen)]
> 
> [remedy: message: Iron Constitution  (14 roisaen)]
> 
> [remedy: message: Some of the faces on your bowtie bump into one another but quickly correct course to rejoin the others.]
> 
> [remedy: message: Which page do you wish to turn the a book of apprentice remedy instructions to?]
> 
> [remedy: checked against [/You turn your/i, /The book is already/i]]
> 
> [remedy: for command turn my book to page ]
> 
> [remedy]>study my book
> 
> You quickly flip through the book and determine it is a collection of instructions for the remedies crafting Discipline in the Alchemy crafting society.
> 
> Upon further perusal, it appears you can TURN the BOOK to the FOREWORD, and read a short primer on how crafting of this type is performed.  You may also TURN the BOOK to INDEX, and read it for a list of chapters.  Then, you can TURN the BOOK to CHAPTER # and read it for a list of instructions on each page.  Finally, you can TURN the BOOK to a PAGE # in that chapter, and read it for detailed information on what is required for the crafting process.
> 
> Once you have turned to the page you wish to craft, you may STUDY the BOOK to begin the crafting process.
> > 
> > 
> > 
> > 
> [remedy: *** No match was found after 15 seconds, dumping info]
> 
> [remedy: messages seen length: 5]
> 
> [remedy: message: Refresh  (14 roisaen)]
> 
> [remedy: message: Iron Constitution  (13 roisaen)]
> 
> [remedy: message: Once you have turned to the page you wish to craft, you may STUDY the BOOK to begin the crafting process.]
> 
> [remedy: message: Upon further perusal, it appears you can TURN the BOOK to the FOREWORD, and read a short primer on how crafting of this type is performed.  You may also TURN the BOOK to INDEX, and read it for a list of chapters.  Then, you can TURN the BOOK to CHAPTER # and read it for a list of instructions on each page.  Finally, you can TURN the BOOK to a PAGE # in that chapter, and read it for detailed information on what is required for the crafting process.]
> 
> [remedy: message: You quickly flip through the book and determine it is a collection of instructions for the remedies crafting Discipline in the Alchemy crafting society.]
> 
> [remedy: checked against [/Roundtime/i]]
> 
> [remedy: for command study my book]
> 
> [remedy]>put my book in my duffel bag
> 
> You put your book in your duffel bag.
> > 
> [remedy]>get my bowl
> 
> You get a large metal bowl from inside your wyvern skull.
> > 
> [remedy]>get my aevaes
> 
> You get some crushed aevaes from inside your duffel bag.
> > 
> [remedy]>put aevaes in my bowl
> 
> You put your aevaes in your large bowl.
> > 
> [remedy]>put my aevaes in my duffel bag
> 
> What were you referring to?
> > 
> [remedy]>untie my mixing stick from my grass toolstrap
> 
> You untie a metal mixing stick from the straps of your grass toolstrap.
> > 
> [remedy]>mix my bowl with my mixing stick
> 
> You cannot figure out how to do that.  Perhaps finding suitable ingredients and studying some instructions would help.

**Comment by Sarvatt** [comment]
you outleveled the apprentice book most likely, 175 skill?

**Comment by Kaesken** [comment]
Doh.... I didn't think about that!  That's what I get for converting 198 mech into Alchemy (now 217) without knowing anything about crafting.  I'll upgrade the book.  Thank you!  You're a guru, Sarvatt, lol

**Comment by Kaesken** [comment]
Okay, now it's taking out the logbook, asking for the orders, goes off to buy a coal nugget and returns to the supply room at Alchemy Society and tries to buy "order 1" which is 10 splashes of water but gets stuck there because she didn't stow the logbook or coal nugget and gets hung up right there.

**Comment by Kaesken** [comment]
Oh, nvm, I see the issue.  I forgot to un-commented her craft container setting.  XD

**Comment by Kaesken** [comment]
Ok, reopening because I caught another one....  It's during the repairing at Alchemy Society, Tool Shop.
It'll snag all my tools but it'll do an extra:

>get my clerk ticket
What were you referring to?


Then it does nothing.

**Comment by Sarvatt** [comment]
that is a different bug, you probably have the wrong tools set up in another craft

**Comment by dakre18** [comment]
if it repaired all your tools, then that looks normal. when it's getting tickets, it returns all tickets until it can't find anymore tickets.

**Comment by Kaesken** [comment]
A'ight, thanks.  Sorry for the long delay, I had forgot I had reopened this.  Closed it so it doesn't take up space.  :)
