### ISSUE TITLE
Alchemy - Riverhaven - Not all NPC rooms listed

### ISSUE THREAD

**Issue by SekmehtDR** [rpherbig/dr-scripts#3648]
Carmifex sometimes travels into rooms that are not listed in the NPC rooms section. 19038 and 19039 should be listed. Otherwise, the workorder script will constantly loop until that NPC is available. Starting Line 787 in base-crafting.yaml

Riverhaven: &theren_remedies
    npc: Carmifex
    npc_last_name: Carmifex
    npc-rooms:
    **- 19038
    - 19039**
    - 19041
    - 19055
    - 19043
    - 19059
    - 19045
    - 19047
    - 19049
    - 19051
    - 19053

**Comment by jayRyan24** [comment]
@SekmehtDR Can you close this Issue? Thanks!

**Comment by jandersson** [comment]
Closed by #3761
