### ISSUE TITLE
why oh whyo would I want to DROP my almanac?

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#3649]
While hunting...this happened:
[almanac]>get my almanac

You get a hefty omnibus almanac with a sturdy indurium cover from inside your leather pack.

[almanac]>study my almanac

You set about studying your omnibus almanac intently.  You believe you've learned something significant about Brigandine!
Roundtime: 10 seconds
You feel fully prepared to cast your spell.
* Ineptly, a storm bull lowers its horns and charges with a loud bellow at you.  You block with a small gryphon-pelt shield sealed with protective wax.  
[You're nimbly balanced and in good position.]
* Moving in like a timid schoolboy, a storm bull pounds at you.  You fend off most of the fist with a kertig throwing spike.  
[You're nimbly balanced and in superior position.]
A storm bull drums its silvery hooves upon the ground.
You feel a wash of heat as a spell shatters against your ward.
A storm bull drums its silvery hooves upon the ground.
You feel a wash of heat as a spell shatters against your ward.
* As if effort and skill were a bad thing, a storm bull pounds at you.  You dodge, twisting easily away from the blow.  
[You're nimbly balanced and in strong position.]
Raising its head, a storm bull gives a challenging bellow.

* Tentatively, a storm bull lowers its horns and charges with a loud bellow at you.  You dodge, twisting easily away from the blow.  
[You're nimbly balanced and in very strong position.]

[almanac]>stow my almanac

You put your almanac in your leather pack.

--- Lich: sanowret-crystal unpaused.

--- Lich: walkingastro unpaused.

--- Lich: t2 unpaused.

--- Lich: hunting-buddy unpaused.

--- Lich: combat-trainer unpaused.

[combat-trainer]>drop my omnibus almanac  <--- Why would I want to do this?

What were you referring to?

**Comment by Tarhish** [comment]
So combat trainer is on the almanac no use scripts list by default because it does a lot of hand swapping and dropping. Same with crafting scripts.

If you want to use it in combat add Almanac: 60 to your training_abilities

I guess the question was why it was running in combat in the first place.  Does your almanac no use scripts list in your yaml have almanac on it?

**Comment by drgabellia** [comment]
Interesting....I had just commented out almanac: 60 in training abilities because I didn't want her training it for one of her hunting yamls.
This is her no_use setup:
almanac_no_use_scripts:
- athletics
- sew
- carve
- forge
- remedy
- shape
- enchant
- craft

**Comment by Tarhish** [comment]
Yeah, it might be best to copy the version from base.yaml then add any custom crafting or other handsy scripts into that.  Everything on that list could be annoying if the almanac script triggers at the wrong time -- I don't think it'll actually drop anything valuable for real (except steal -- I could see that dropping something), but it might enter the command after it's left your hand.

Best not to leave it to chance :-\

**Comment by drgabellia** [comment]
I shall do that, thanks for the input!

**Comment by jayRyan24** [comment]
@drgabellia Is this figured out? Can this be closed?

**Comment by drgabellia** [comment]
yep...this can be closed.  I added all the info from the base yaml as suggested.  Thanks for the help!
