### ISSUE TITLE
Combat-trainer should halt if wearing equipment fails

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#365]
Per @rcuhljr, the intention is that combat trainer stops if `wear_equipment_set?` fails.

Right now, all it does is:
`EquipmentManager.instance.wear_equipment_set?(settings.worn_items) if settings.worn_items`

**Comment by rcuhljr** [comment]
I'm open to discussion regarding if this is the correct behavior. We need to be careful that training manager and hunting buddy handle these bubbled up failures properly and don't just leave you standing there until you die.
