### ISSUE TITLE
Toad Form for Barbarians

### ISSUE THREAD

**Issue by khrispyb** [rpherbig/dr-scripts#3656]
Is there a way to add Toad Form for Barbarians? Thanks

**Comment by rpherbig** [comment]
You could submit a PR that updates base-spells. See: https://github.com/rpherbig/dr-scripts/blob/master/data/base-spells.yaml#L208

Or if you could post the activate and expire messages that would help someone else add it.

**Comment by khrispyb** [comment]
I’ve never submitted a PR, sort of new here.  What do I do exactly?

**Comment by khrispyb** [comment]
here is the activate/expire:
Start: All sense of heat and cold is lost as your body slips into the resilient Form of the Toad!
Stop: You feel your inner fire cool as you finish practicing the Form of the Toad.
