### ISSUE TITLE
workorders tailoring issue 

### ISSUE THREAD

**Issue by khrispyb** [rpherbig/dr-scripts#3658]
am getting the below error 

> ,workorders tailoring

[workorders]>get my outfitting logbook

You get an outfitting work order logbook from inside your cylindrical pannier.
> 
[workorders]>ask Jakke for challenging tailoring work

> 
Jakke shuffles through some notes and says, "Alright, this is an order for a coarse leather mask. I need 2 of superior quality, made from any leather and due in 75 roisaen.  Please complete the items, bundle them with your logbook and then give me the logbook to complete this order.  Good luck!"

You seem to recall this item being somewhere in chapter 9 of the instruction book.
> 
[workorders]>put my logbook in my pannier

You put your logbook in your cylindrical pannier.
> 
[workorders: UNKNOWN CHAPTER FOR TAILORING ITEM {"name"=>"a coarse leather mask", "noun"=>"mask", "volume"=>3, "type"=>"tailoring", "work_order"=>true, "chapter"=>9, "part"=>["small padding"]}]

in base-recipes.yaml the mask entry looks valid and is set as follows:

- name: a rugged leather mask
  noun: mask
  volume: 3
  type: tailoring
  work_order: true
  chapter: 9
  part:
  - small padding

am I doing something wrong here?

**Comment by khrispyb** [comment]
btw it is not isolated to only the mask, got it again for another item:

**Comment by rpherbig** [comment]
Your workorder was for a _coarse_ mask, you quoted the base-recipes entry for a _rugged_ mask.

Here is the entry for [a coarse leather mask](https://github.com/rpherbig/dr-scripts/blob/master/data/base-recipes.yaml#L2683):
```yaml
- name: a coarse leather mask
  noun: mask
  volume: 3
  type: tailoring
  work_order: false
  chapter: 9
  part:
  - small padding
```

Note `work_order: false`. I wouldn't have expected workorders to accept it... maybe someone else can dig into that a bit more, I've got to run.

**Comment by khrispyb** [comment]
You're right, my mistake, but it is the same and was set to true.

- name: a coarse leather mask
  noun: mask
  volume: 3
  type: tailoring
  work_order: true
  chapter: 9
  part:
  - small padding

same for the gloves:

- name: some thick gloves
  noun: gloves
  volume: 5
  type: tailoring
  work_order: true
  chapter: 9
  part:
  - small padding
