### ISSUE TITLE
workorders - expired workorder round 2

### ISSUE THREAD

**Issue by OdnaZvezda** [rpherbig/dr-scripts#366]
Found the root of the problem.   Crafted items were too low quality for the workorder requirement and were dropped rather than bundled with the workorder.  

First, workorders only creates as many items as the workorder calls for, then tries to give the logbook to the society craftmaster. http://pastebin.com/8uYSwQT6

https://github.com/rpherbig/dr-scripts/issues/362 was happening as a result of the above.

Better knitting needles should fix this for the character in question.

**Comment by rcuhljr** [comment]
Yeah it's kind of a known issue that if you're tanking items it won't work. I haven't gone through and done the leg work to deal with failures although I think I I could add in some logic pretty cleanly.

**Comment by OdnaZvezda** [comment]
I don't know that dealing with failures is necessary.  If you don't have the skill to consistently craft the items at the quality needed, it's reasonable to assume that you'd run out of time while crafting replacements.  Workorders could possibly echo a message to the effect that the crafted items were too low quality for the logbook and return control to crossing-training
