### ISSUE TITLE
base.yaml - Add Clamps to shaping tools

### ISSUE THREAD

**Issue by dakre18** [rpherbig/dr-scripts#3660]
Shaping uses clamps as a tool, but it doesn't get repaired after a workorder if it's not on the list of shaping tools.

**Comment by Sarvatt** [comment]
so add it to your tools if you craft something that uses them?

**Comment by Sarvatt** [comment]
it’s only bows afaik

**Comment by Sarvatt** [comment]
adding it to the default tool list is a NAK from me, only people who either take bow techs or are over 500ish skill need it.

**Comment by dakre18** [comment]
true it's not hard, it's just not obvious and is a simple change. i didn't check if it was only bows, but shaping does use clamps.

**Comment by jandersson** [comment]
What happens in the workorder flow if I dont have a clamp and this is on the list?

**Comment by jandersson** [comment]
If it doesn't have any major drawbacks, like breaking scripts, I dont see a big problem with adding it. Is it something you can look into @dakre18 ?

**Comment by Tarhish** [comment]
Before it would have broken scripts during repairs when workorders tried to find clamps and you didn't have any on you.  After that semi-recent change workorders will continue without breaking everything even if you're missing a tool during repair, but it might BEEP at you and echo an error.  

I think it would function, but we'd get a lot of people all of a sudden asking why workorders is complaining it can't find clamps.  When I did that change I was still thinking you shouldn't have a tool on your list that you don't have in your inventory.

**Comment by dakre18** [comment]
So without the clamp on the list, shape.lic will still use the tool, and it never gets repaired after the workorder.lic is done.

With the clamp on the list, after workorder.lic is done, it will try to get the clamps, and then just dings with an error saying "[workorders: You seem to be missing: clamps]" and continues getting the ticket from Rangu.

**Comment by Sarvatt** [comment]
> Before, it would have broken scripts during repairs when workorders tried to find clamps and you didn't have any on you. After that semi-recent change workorders will continue without breaking everything even if you're missing a tool during repair, but it might BEEP at you and echo an error.
> 
> I think it would function, but we'd get a lot of people all of a sudden asking why workorders is complaining it can't find clamps. When I did that change I was still thinking you shouldn't have a tool on your list that you don't have in your inventory.

thanks for fixing that, that’s specifically why i was against adding it and didnt realize you fixed that.

**Comment by jayRyan24** [comment]
Can this be closed? @Sarvatt @dakre18 @Tarhish

**Comment by dakre18** [comment]
from the discussion, clamps would need added still, since it can be used in shaping recipes. Sarvatt was just worried it would break the script, but changes were made to prevent that.

But it's up to yall to add it or not. If yall decide it isn't needed, we can just close it. From my recollection, clamps are only used in the bow recipes in shaping.

**Comment by Tarhish** [comment]
Yeah, I was busy around this time and was too lazy to make the change, but once I broke my ankle and started healing I had forgotten about it.  Sarvatt was right, but nowadays I don't see any real reason we couldn't add it in.  Either way, people should have clamps around, since it's gonna start throwing them at bow recipes eventually.
