### ISSUE TITLE
Yrisa Healer Fang Cove Join List

### ISSUE THREAD

**Issue by khrispyb** [rpherbig/dr-scripts#3663]
Using safe-room in Fang Cove doesn't add you to the list for healing - is there something I can add to "JOIN LIST" when in 8393 with Yrisa?  Otherwise you just sort of lie there and I think she keeps your vitality up but doesn't heal.

Thanks

**Comment by khrispyb** [comment]
nice you guys rock

**Comment by jandersson** [comment]
Closed by #3760
