### ISSUE TITLE
Combat-trainer.lic 

### ISSUE THREAD

**Issue by mtruitt** [rpherbig/dr-scripts#3666]
Change needs to be rolled back.

--- Lich: error: wrong number of arguments (given 2, expected 1)
	equipmanager:155:in `wield_weapon_offhand'
	combat-trainer:3261:in `wield_offhand_weapon'

**Comment by Sarvatt** [comment]
log out and back in all characters to pick up the changes. or ;kill dependency then ;dependency

**Comment by BinuDR** [comment]
Not it doesn't.  Log out and back in

**Comment by BinuDR** [comment]
Oops, Sarvatt beat me to it.

**Comment by mtruitt** [comment]
So yes, it still is a problem for anyone that was logged in prior to the change.

**Comment by BinuDR** [comment]
We update the code base frequently to make bug fixes and add features fairly often.

If something stops working all of a sudden, try logging out and back in or ask on lnet.

**Comment by mtruitt** [comment]
More than a few people had commented about it on lnet.

**Comment by BinuDR** [comment]
And I wasn't logged in most of the day.  Other people answered though.
