### ISSUE TITLE
Safe Room: Spams stand when unconscious

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#3668]
The safe room script spams `fixstanding` if you are unconscious. 
```
[safe-room]>stand          
You're unconscious!        
[safe-room]>stand          
You're unconscious!        
[safe-room]>stand          
You're unconscious!        
[safe-room]>stand          
You're unconscious!        
[safe-room]>stand          
You're unconscious!        
[safe-room]>stand          
You're unconscious!        
[safe-room]>stand          
You're unconscious!        
[safe-room]>stand          
You're unconscious!        
[safe-room]>stand          
You're unconscious!        
[safe-room]>stand          
You're unconscious!        
[safe-room]>stand          
!UP>                       
You're unconscious!        
[safe-room]>stand          
You're unconscious!        
[safe-room]>stand          
You're unconscious!        
[safe-room]>stand          
You're unconscious!        
[safe-room]>stand          
You're unconscious!        
[safe-room]>stand          
You're unconscious!        
[safe-room]>stand          
You're unconscious!        
[safe-room]>stand          
You're unconscious!        
[safe-room]>stand          
You're unconscious!        
[safe-room]>stand
You're unconscious!        
[safe-room]>stand          
You're unconscious!        
[safe-room]>stand          
You're unconscious!        
[safe-room]>stand          
You're unconscious!        
[safe-room]>stand          
```

Unconsciousness state should be captured by either lich or drinfomon, lets do a `until !unconscious` loop before doing `fixstanding`.

_edited_
## Suggestion
Look into using `sleeping?` or `checksleeping` in either `fixstanding` or safe-room

**Comment by jandersson** [comment]
Its in the statusprompt as `U`

e.g. 

`UP!>stand`

**Comment by jandersson** [comment]
If its not in there - might be a good idea to add it. I would opt for `disabled?` instead since `unconscious?` is easy for me to misspell.

**Comment by Sarvatt** [comment]
just adding a pause 1 to the loop in https://github.com/rpherbig/dr-scripts/blob/master/common.lic#L263-L268 would probably be good enough and fix it from spamming as fast as possible in other cases also?

**Comment by Sarvatt** [comment]
dunno if I like relying on the statusprompt, I dont use it and doubt I'm the only one.

**Comment by jandersson** [comment]
I believe you still get the data from it with it off. That's a hunch though

**Comment by Sarvatt** [comment]
does unconcious set off the stunned indicator by any chance in the xml?

**Comment by jandersson** [comment]
I dont think so because stunned is its own indicator in statusprompt. But I'm not logging the fake xml data at the moment. Another hunch D:

**Comment by jandersson** [comment]
I can start logging it though. Researching `spell` has a pretty good chance of doing this, plus a good head bleeder and paralysis. What are you thinking if it does set it off?

**Comment by Sarvatt** [comment]
no need to, was just wondering if you get an indicator in your client. was thinking it could check for when you've got <indicator id='IconSTUNNED'> up but that's too much for a common file :D I'd be a fan of just adding a pause 1 to tthe loop though, it'd fix other situations of it spamming full speed like 
```
You don't seem to be able to move to do that

**Comment by jandersson** [comment]
Ah ok. So I think the statusprompt indicator `U` is just a symbol that shows up based on the data your client gets, like all the other indicators.

**Comment by jandersson** [comment]
Any attempt at a fix would close this in my book. `pause 1` or `until !knockedout?`

**Comment by jandersson** [comment]
I'll turn on the background data logging for a day, that should be enough to see whats happening. Research `spell` does this as often.

**Comment by jandersson** [comment]
Its already built into lich, LostRanger said just do `sleeping?` or `checksleeping` that is analagous with the `U` sent to statusprompt

**Comment by MahtraDR** [comment]
Closing this. It's not a lich issue if the xml isn't updating fast enough.
