### ISSUE TITLE
Testing: Bput timeout test fails often

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#3669]
The test for bput timing out in our tests is a common point of failure in our CI. We've had a few pull requests get marked as failed due to it. Its usually off by a fraction of a second.

We could increase the threshold on it. But i was wondering, what does it tell us when it fails? If the response is 'lets increase the threshold', it seems to me we haven't really defined a good point for this to fail and inform us of anything useful. I think we should either remove the test or skip it.

**Comment by rcuhljr** [comment]
I think we don't care enough about the value the wait is enough to need the precision it has, might as well bump it to a 5 or 10 second threshold.

**Comment by jandersson** [comment]
That makes sense, so its a bput sanity check then. I can make a commit that ups it to 5.

**Comment by jandersson** [comment]
Closed by #3723
