### ISSUE TITLE
Balloon to m'riss

### ISSUE THREAD

**Issue by RohkDR** [rpherbig/dr-scripts#3678]
--- Lich: go2 active.

[go2: ETA: 0:15:07 (38 rooms to move through)]

--- Lich: error: (eval):1: syntax error, unexpected ',', expecting ')'
start_script ('bescort', ['balloon', 'mriss']) wait_...
                        ^
(eval):1: syntax error, unexpected ',', expecting end-of-input
..._script ('bescort', ['balloon', 'mriss']) wait_while{ runni...
...                               ^
	lich.rbw:1234:in `eval'
	lich.rbw:1234:in `block in call'

--- Lich: go2 has exited.

Using go2, encountered this at the Lang tree

**Comment by jandersson** [comment]
Do you have the room number handy? I think the room might need a fix

**Comment by RohkDR** [comment]
Room Number: 8793

**Comment by jandersson** [comment]
Got it. The room is issuing a command with syntax problems.

Its sending `start_script ('bescort', ['balloon', 'mriss']); wait_while{ running?('bescort')` which has a left brace in the wait_while

**Comment by jandersson** [comment]
Fixed. You can either re login on all your characters or have one of them run `;e repos download-mapdb` then have any other characters run `;e Map.reload`

**Comment by Hazado** [comment]
issue can be closed.
