### ISSUE TITLE
checkfavor error

### ISSUE THREAD

**Issue by Angel-DR** [rpherbig/dr-scripts#3681]
Hi guys,

I received a message today, just following directions =) 

[t2: ***STATUS*** EXECUTE checkfavor]

[t2: *** Failed to find a script named 'checkfavor' ***]

[t2: *** Please report this to Etreu, Sheltim, or https://github.com/rpherbig/dr-scripts/issues  ***]

**Comment by BinuDR** [comment]
It sounds like you are trying to use checkfavor in your training_list when you don't have the script.

**Comment by Angel-DR** [comment]
Thank you.

I never saw that error before though. I wonder if somehow it got moved.

I'll check it out. I only reported because it said to.

I should have checked first. But didn't know that's what it meant, but now
I know to check.

Thanks Binu!!

Angel

**Comment by MahtraDR** [comment]
@rpherbig can close
