### ISSUE TITLE
Combat logger/parser

### ISSUE THREAD

**Issue by izawwlgood** [rpherbig/dr-scripts#369]
I want more data from my weapons/buffs. So, I propose a script that runs and with a few set parameters (which weapons you'll be using, maybe some others). Then, as you attack, it scores the strength of the attack (https://elanthipedia.play.net/mediawiki/index.php/Damage), and displays avg dps, avg roundtime. I'm thinking the output could look like 

Weapon   Avg RT Avg DPS
Scimitar       2.5s        6
Broadsword 4.3s        8

Such a thing would be useful for judging the efficacy of buffs or comparing weapons. With a bit of tweaking, it might also be useful for logging 'number of casts to kill' for TM spells. It'd also be nice if it could be amended to include Guardian Spirit attacks, for Empaths.

**Comment by rcuhljr** [comment]
Definitely doable, would we want to snapshot certain information along with each recorded hit such as ranks in the weapon skill? We could track spell buffs but things like barbarian roars and thief khri's is a little trickier with having to monitor start and stop messaging.

**Comment by izawwlgood** [comment]
There are a few options I think - one would be to separately parse results when buffs are up (check for a designated set of buffs?), and display them separately, but it might be obnoxious to parse WHICH buffs are up. Instead, maybe just have a 'buffed' and 'non-buffed'? My Barb for example has Dragon/Eagle, Bear, Tsunami, and Wildfire as offensive buffs. Trying to factor in barb roars and thief ambushes would be a nightmare.

**Comment by izawwlgood** [comment]
Very cool. Early thoughts/feedback -

1. Ranged weapons need to be tracked by listing the ammo, not the weapon (e.g., 'arrow' not 'shortbow'), as the combat messaging reflects the ammo. Ranged weapons also spit out wonky avg data, since the time to fire is always 1, but not sure anything can be or should be done about that. I only use full aims, so maybe just default the time to whatever the full aim time is (8s? 10s?)

2. I'm not sure how it's grabbing the information, but not all combat messages involve the name of the weapon. For example, if you SLAM with a blunt weapon - 

< You slam a mace haft at a s'sugi malchata.  A s'sugi malchata fails to evade.  **The haft** lands a solid hit (4/23) to the malchata's chest.

compared to:

< You draw a flanged haralun mace at a s'sugi malchata.  A s'sugi malchata fails to evade.  **The mace** lands a strong hit (6/23) to the malchata's right arm.

If you're grabbing the 'The mace', then a slam won't return the weapon used. 

3. Charged maneuvers might not be functioning properly. Not sure the best way to parse them in, as there's an obvious charge up period, and then a ~5s RT. Here's example messaging - 

Making an agile leap, you lash out in an attempt to cleave a zombie stomper in half!

Your marauder blade lands a powerful strike (10/23) to a zombie stomper's head!
With expert skill you end the attack and maneuver into a better position.

[You're bruised, winded, nimbly balanced with opponent in good position.]
Roundtime: 5 sec.

4. Some AoE abilities use standard messaging, for example, whirl - 

With a quick two step motion you ready your glaive, holding it at shoulder level before launching into a turn that renders you as nothing more than a shade of dissolution.

Your glaive lands a solid hit (4/23) to a zombie stomper's right leg!

Your glaive lands a hard hit (5/23) to a zombie stomper's left leg!

Your glaive lands a strong hit (6/23) to a zombie stomper's chest!
A zombie stomper falls belly-up and grunts its last grunt.

[You're nimbly balanced]
Roundtime: 4 sec.

And I think some cyclic TM. Might be cool to include them, though not sure how to parse between pulses on the cyclics. Maybe just have it set to report 'avg damage per pulse'? 


All in all this is fantastic though, I'm really impressed and excited to play around with it!

**Comment by izawwlgood** [comment]
Messaging for PYRE - 

The flames land a solid hit (4/23) to a swamp troll's right leg!

Messaging for Rimefang - 

An icy blade circling you lands a good strike (3/23) to a beisswurm's back!


Seems like you could just add 'flames' or 'blade circling' as a weapon type in these cases.

**Comment by rpherbig** [comment]
@rcuhljr @izawwlgood Is `skill-recorder.lic` good enough to close this?

**Comment by rcuhljr** [comment]
skill-recorder isn't at all related to this, thanks for confusing everyone :)

**Comment by rpherbig** [comment]
@rcuhljr @izawwlgood Is `performance-monitor.lic` good enough to close this?

**Comment by rcuhljr** [comment]
If you close this issue spin up a new one with the user feedback from this issue in it.

**Comment by rpherbig** [comment]
I'll let you manage this one.

**Comment by izawwlgood** [comment]
It works great as it stands for some weapons, but could still use some updates!
