### ISSUE TITLE
Remedy script

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#3692]
Forgot I had wounds when I started the training-manager so when she got to the alchemy society, she got stuck in a nonstop loop.  Course I stopped it so I can heal but wasn't sure if you guys wanted to know or not.

[remedy]>untie my pestle from my grass toolstrap

Your wounds hinder your ability to do that.
> 
Your body is still soaked.
> 
[remedy: *** No match was found after 15 seconds, dumping info]

[remedy: messages seen length: 2]

[remedy: message: Your body is still soaked.]

[remedy: message: Your wounds hinder your ability to do that.]

[remedy: checked against [/You (remove|untie)/i, /Untie what/i]]

[remedy: for command untie my pestle from my grass toolstrap]

[remedy]>get my pestle

[remedy: *** No match was found after 15 seconds, dumping info]

[remedy: messages seen length: 2]

[remedy: message: Some of the faces on your bowtie bump into one another but quickly correct course to rejoin the others.]

[remedy: message: You should untie the iron pestle from the grass toolstrap first.]

[remedy: checked against [/^You get/i, /^You are already/i, /^What do you/i, /^What were you/i, /You pick up/i, /can't quite lift it/i]]

[remedy: for command get my pestle]

[remedy]>crush my red flowers with my pestle

You need to be holding the pestle first.
> 
[remedy]>untie my pestle from my grass toolstrap

Your wounds hinder your ability to do that.

**Comment by dakre18** [comment]
i'll take a look at it. looks like a simple fix, and i've got some other minor changes i could make as well.

**Comment by Dartellum** [comment]
Looks like a catch is required and then exit - or force safe-room run.

**Comment by dakre18** [comment]
yeah, i work slow. motivation is in short supply with me, but i've got some other changes i'm working on. little fixes mainly to improve the remedy script.

**Comment by Dartellum** [comment]
@dakre18 Slow is good. After I wrote remedy.lic and then added to workorders, I was burnt out. I am glad you are updating it. :) I can, maybe, look at adding a catch for this situation this weekend. I will let you know.

**Comment by Dartellum** [comment]
Do we want to pause the script while seeking healing? Or, just exit and seek healing?

**Comment by Dartellum** [comment]
I believe this wound cover it, in common-crafting under def get_crafting_item()...

    elseif DRC.bput("untie my #{name} from my #{belt['name']}", 'You (remove|untie)', 'Untie what', 'Your wounds hinder your ability to do that.') =~ /Your wounds hinder your ability to do that./
        craft_room = Room.current.id
        wait_for_script_to_complete('safe-room', ['force'])
        get_crafting_item(name, bag, bag_items, belt)
      end

I will wound my guy some and test.

**Comment by Dartellum** [comment]
elsif DRC.bput("untie my #{name} from my #{belt['name']}", 'You (remove|untie)', 'Untie what', 'Your wounds hinder your ability to do that.') =~ /Your wounds hinder your ability to do that./
        craft_room = Room.current.id
        wait_for_script_to_complete('safe-room', ['force'])
        DRCT.walk_to(craft_room)
        get_crafting_item(name, bag, bag_items, belt)
      end

That fixed it for my person. The only challenge left to test is if the room you were in was an anvil or other room needed for the crafting and what happens when you return to an occupied room.

**Comment by rpherbig** [comment]
Closed in #3790
