### ISSUE TITLE
Riverhaven's Alchemy Society + go2

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#3693]
So apparently Riverhaven's alchemy society used to be just plain "Alchemy Society" and now it's "Riverhaven Alchemy Society".  The go2 can get me in there but using go2 to get out, I keep getting:

--- Lich: go2 active.

[go2: error: your current room was not found in the map database]

--- Lich: go2 has exited.

--
Edit; definitely busts the entire thing if you have set to workorders and hometown is Riverhaven

[workorders: In an unknown room, manually attempting to navigate to 19041]

[workorders: failed to find a matching room]

[workorders: In an unknown room, manually attempting to navigate to 19055]

[workorders: failed to find a matching room]

[workorders: In an unknown room, manually attempting to navigate to 19043]

[workorders: failed to find a matching room]

[workorders: In an unknown room, manually attempting to navigate to 19059]

[workorders: failed to find a matching room]

[workorders: In an unknown room, manually attempting to navigate to 19045]

[workorders: failed to find a matching room]

[workorders: In an unknown room, manually attempting to navigate to 19047]

**Comment by dakre18** [comment]
i noticed this same issue, only in TF, in multiple society buildings in The Crossing.

**Comment by Kaesken** [comment]
I haven't experienced it in Crossing.  Just Riverhaven since they added the town name into the societies title which is probably what's causing the go2 issue.  I already fixed my Genie's maps for the change but I don't know how to do the same for Lich's go2.

**Comment by Tarhish** [comment]
I believe I fixed the Haven Alchemy and Engineering societies now, but keep an eye out for more.  I'm glad they have the town names in the society buildings now but boy that change made it weird.

**Comment by Hazado** [comment]
Fixed Fang Cove earlier today

**Comment by Kaesken** [comment]
Yeah, same here but I don't think they have Crossing's alchemy society with the town name in it.  Probably why they changed Riverhaven's due to both buildings having the same ID name.  I'll keep an eye out for anymore!

**Comment by Kazmous** [comment]
Engineering seems to work now with the following potential small exception if you don't have an engineering_room: set . After ordering the materials, it just immediately gives [workorders: ***Failed to find an empty room, stopping the search***] and starts crafting in the resource depot room (ID 9110).

Enchanting and Outfitting still seems to be broke (starting ;craft outside the society doesn't move into the society to order materials, just starts inputting the ordering wherever you currently are,  and starting ;go2 from inside the society trying to get outside indicates "[go2: error: your current room was not found in the map database]" and kills ;go2   ---- however, you can use ;go2 enchanting / outfitting to get into the societies...)
