### ISSUE TITLE
Appraisal.lic

### ISSUE THREAD

**Issue by Windamere** [rpherbig/dr-scripts#3696]
Appraisal.lic needs a Catch after line 50 in notepad++ that catches if the pouch is closed, open the pouch then attempt line 50 again. 

Appraising closed pouches doesn't work, at least until a certain skill.

**Comment by Windamere** [comment]
https://pastebin.com/LVvPvx0y Thief with 21 appraisal can't appraise closed pouches until APP: 80

**Comment by Hazado** [comment]
Issue can be closed.
