### ISSUE TITLE
TM Focus doesn't re-invoke after stowing for telescope/ritual focus/etc

### ISSUE THREAD

**Issue by jgmast** [rpherbig/dr-scripts#3702]
I've been using a TM focus and when first getting into combat the combat-trainer script will invoke it correctly. My moon mage will occasionally swap to telescope to train astrology in combat and after doing that it will stow the telescope and wield the TM focus (animite sphere) but it won't invoke it.
Same issue when holding a ritual focus when rebuffing.
I thought this worked at one point so it might be a regression (or maybe I just didn't notice before).

**Comment by MahtraDR** [comment]
@rpherbig Can close this. Doesn't happen today.
