### ISSUE TITLE
Craft.lic enchanting - adding challenging(<= 550) and complicated(<= 700) 

### ISSUE THREAD

**Issue by Bedonder** [rpherbig/dr-scripts#3729]
Not sure what the protocol is for this
at line 193 I have edited/added the following on a copy of craft.lic on my system.
------
    elsif rank <= 550 # Tier 7 - Challenging
	  # Buy a abolition and induction sigils and runestone
      ensure_copper_on_hand(4000, @settings)
      order_item(crafting_data['artificing'][@hometown]['stock-room'], 2)
      order_item(crafting_data['artificing'][@hometown]['stock-room'], 1)
      stow_hands
      buy_item(crafting_data['artificing'][@hometown]['stock-room'], 'runestone')
      stow_hands
      wait_for_script_to_complete('enchant', [6, 'gauge flow runestone', 'runestone'])
      dispose_trash('runestone')
    elsif rank <= 700 # Tier 8 - Complicated
	  # Buy a rarefaction and induction sigils and runestone
      ensure_copper_on_hand(4000, @settings)
      order_item(crafting_data['artificing'][@hometown]['stock-room'], 5)
      order_item(crafting_data['artificing'][@hometown]['stock-room'], 1)
      stow_hands
      buy_item(crafting_data['artificing'][@hometown]['stock-room'], 'runestone')
      stow_hands
      wait_for_script_to_complete('enchant', [6, 'dispel runestone', 'runestone'])
      dispose_trash('runestone')
-----
I have tested the Tier 7 on my MM (436 ranks in enchanting) and it works.
the Tier 8 I have purchased store bought sigils and rune and it works for me using ;enchant 6 "dispel runestone" rune

let me know if you need anything else.

**Comment by rpherbig** [comment]
Thank you @Bedonder !
