### ISSUE TITLE
Add support for lockbox picking in combat

### ISSUE THREAD

**Issue by DRWafflesworth** [rpherbig/dr-scripts#3733]
Since locksmith trainers are becoming more common, could we add support for them in combat with retreating being optional?

**Comment by Dartellum** [comment]
Already support this:
training_abilities:
  Locks: 200

**Comment by jandersson** [comment]
wrt retreating, is it possible to pick a box at melee? Why should it be optional if not?

**Comment by Dartellum** [comment]
Cannot pick at melee. Message is too busy to do that.

**Comment by MahtraDR** [comment]
Closing as a duplicate of https://github.com/rpherbig/dr-scripts/issues/3733 purely because that one has a lot more info/context, so makes more sense to me that we keep that one.
