### ISSUE TITLE
athletics breaks when climb prac is too difficult

### ISSUE THREAD

**Issue by proctophage** [rpherbig/dr-scripts#3735]
https://pastebin.com/3J1vj3iQ

Dunno how this happened honestly. I've been doing this boulder for quite some time and for some reason this time I didn't have enough skill and it broke the script in a way it could not recover from. I don't have any athletics buffs. I don't know if it was debuffed, but how would athletics even be debuffed? Either way... can something be added here to exit and do the next climb step down instead of it breaking? The line to look for would be:
This climb is too difficult, so you stop practicing.

**Comment by BinuDR** [comment]
Did you depart recently?

Check EXP MODS and see if you have a negative mod to athletics.

**Comment by proctophage** [comment]
No, didn't depart recently. I don't see any buffs or debuffs to athletics in exp mods. Like I said idk how I could have debuffed athletics since epedia says nothing debuffs it.

**Comment by Sarvatt** [comment]
a bad prediction maybe?
