### ISSUE TITLE
Make combat-trainer compatible with bonded throwing weapons.

### ISSUE THREAD

**Issue by hwoo79** [rpherbig/dr-scripts#375]
This would be supported via hurl/invoke.

Would also need a yaml setting for the weapon to set as bonded.

**Comment by rpherbig** [comment]
Do you have a log?

**Comment by hwoo79** [comment]
```
> hurl

< Fluidly, you hurl a light haralun throwing axe at an Elven lowlife.  An Elven lowlife attempts to evade, avoiding most of the blow.  
The axe lands a very heavy hit (8/23) that etches a light cut into the right side of the chest.

The throwing axe lodges itself shallowly into the lowlife!
[You're solidly balanced and in superior position.]
[Roundtime 3 sec.]

R> 
The lowlife reels about wildly, trying to regain control.
R> 
The ruffian reels about wildly, trying to regain control.
R> invoke

A light haralun throwing axe suddenly leaps from an Elven lowlife and flies toward you!  You catch the axe easily in your right hand.
Roundtime: 1 sec.

R> hurl
> 
< With grace, you hurl a light haralun throwing axe at an Elven lowlife.  An Elven lowlife attempts to evade, mainly avoiding the blow.  
The axe lands an extremely heavy hit (9/23) that exposes bone along the entire left arm and spatters blood everywhere.

The throwing axe lodges itself deeply into the lowlife!
invoke
[You're solidly balanced and in superior position.]
[Roundtime 3 sec.]

R> 
R> 
R> 
R> invoke

A light haralun throwing axe suddenly leaps from an Elven lowlife and flies toward you!  You catch the axe easily in your right hand.
Roundtime: 1 sec.
```

**Comment by rpherbig** [comment]
What's the advantage over the current lob/get? More damage from hurl?

**Comment by hwoo79** [comment]
Yes, a lot more damage from hurl.

**Comment by hwoo79** [comment]
>invoke
A light haralun throwing axe suddenly leaps from a giant black leucro and flies toward you!  You catch the axe easily in your right hand.
Roundtime: 1 sec.

**Comment by rpherbig** [comment]
I think we'd want to add one `combat-trainer` setting (`throw_action`) and one Item attribute (`bonded`). I'm currently in [the middle of a refactor](https://github.com/rpherbig/dr-scripts/pull/379) that should make this quite a bit easier.

**Comment by rcuhljr** [comment]
This setting kind of needs to be weapon specific since you may not have all your weapons bonded, could we just have a 'bonded weapon skills' list and if it's bonded use hurl/invoke?

**Comment by rpherbig** [comment]
Good point. Will ponder.

**Comment by rpherbig** [comment]
I agree that we can just key off of the bonded status to use hurl/invoke vs lob/get.

I still think `bonded` is a property of the Item class.

**Comment by rcuhljr** [comment]
reasonable, but we'll need to start keeping the item object and passing it around in game_state probably.
