### ISSUE TITLE
Tokka Decks and ;astrology

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#3764]
Now that Tokka Decks actually work....any chance they can be added to ;astrology?

~Gab

**Comment by jayRyan24** [comment]
Wow, that seems super complicated (looking at it on Epedia). Is this really needed with how easy it is to train using RTR post circle 50?

**Comment by MahtraDR** [comment]
Closing. This isn't likely to ever be implemented unless someone truly is passionate for it..
