### ISSUE TITLE
cleaning_cloth in Crossing-training

### ISSUE THREAD

**Issue by RyanEOD** [rpherbig/dr-scripts#3765]
I have my worn_instrument: set to cowbell, I also tried just setting my instrument: to it as well. With a cleaning cloth set, it keeps trying to remove my zills and clean them, when my cowbell needs cleaning. I'm assuming it isn't looking for the variable when trying to clean - 

Looks like the problem is here - 

  def clean_zills
    cloth = @settings.cleaning_cloth

    case bput("get my #{cloth}", 'You get', 'What were you')
    when 'What were you'
      echo('You have no chamois cloth, removing Performance from training')
      @settings.crossing_training.delete('Performance')
      return
    end

    bput('remove my zills', 'You slide')

    loop do
      case bput("wipe my zills with my #{cloth}", 'Roundtime', 'not in need of drying', 'You should be sitting up')
      when 'not in need of drying'
        break
      when 'You should be sitting up'
        fix_standing
        next
      end
      pause 1
      waitrt?

      until /you wring a dry/i =~ bput("wring my #{cloth}", 'You wring a dry', 'You wring out')
        pause 1
        waitrt?
      end
    end

    until /not in need of cleaning/i =~ bput("clean my zills with my #{cloth}", 'Roundtime', 'not in need of cleaning')
      pause 1
      waitrt?
    end

    bput('wear my zills', 'You slide')
    bput("stow my #{cloth}", 'You put')
  end
end

**Comment by Tarhish** [comment]
Thanks for pointing this out.  I see crossing training doing its own thing, so I might as well move everything over to the common method.

**Comment by Tarhish** [comment]
I think I've got the changes worked out -- I'm just going to test them until dirt is achieved.
