### ISSUE TITLE
Jail-buddy/Pay-debt

### ISSUE THREAD

**Issue by blackheart217** [rpherbig/dr-scripts#3766]
Was arrested in Shard, hometown set to Hib.  

Jail buddy active, found guilty.  

pay-debt began, found debts to both Illithi and Forfedhdar.   It took me all the way down to Hib, where it withdrew the amount for the shard debt, went to Hib justice office and paid the shard amount, then timed out.

Guessing its a hometown issue? but also had debts to both places.

**Comment by jayRyan24** [comment]
@blackheart217 Can you close this issue, it seems that @Hazado fixed it already.

**Comment by blackheart217** [comment]
Sure thing
