### ISSUE TITLE
Premium toggle in YAML?

### ISSUE THREAD

**Issue by RyanEOD** [rpherbig/dr-scripts#3768]
Now that the Fang Cove portals are in the go2 mapping, can we do a premium toggle? Setting "force_healer_town: Fang Cove" in my yaml is still taking the mammoth even though I have a variable set in Genie for "premium = true". I believe it should use the portals but for some reason it doesn't believe I'm premie. Setting this in the YAML would be pretty easy. Thoughts?

**Comment by Hazado** [comment]
This should be fixed in the latest update to drinfomon.lic
Should be automatically set now.

**Comment by rpherbig** [comment]
Fixed in #3769
