### ISSUE TITLE
Mining-buddy skips the room it should mine and mining the next

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#377]
No log, but @rcuhljr says it's an issue of bput not waiting on the last line returned from mining.

**Comment by EMSwanson** [comment]
Here are a couple messages that give prospect information. I'll post more as I get them.

You see evidence of mineral deposits and are certain a substantial quantity remains to be found.
This area is composed of metamorphic rock layers.

[mining-buddy]>prospect
You see evidence of mineral deposits and are certain a good quantity remains to be found.
This area is composed of metamorphic rock layers.

[mining-buddy]>prospect
You see evidence of mineral deposits and are certain a decent quantity remains to be found.
This area is composed of metamorphic rock layers.

You carefully scan the area and look for ways to excavate additional material.  Your analysis has revealed no additional resources to be unearthed here.

[mine]>prospect
You see evidence of mineral deposits and are certain a scattering of resources remains to be found.
This area is composed of sedimentary rock layers.

**Comment by rcuhljr** [comment]
Should be working for low skills.
