### ISSUE TITLE
Oshu base-hunting

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#3774]
So I took the roomnumbers of each of the area in Oshu and dunno if you guys are interested in this or not, but here's what I snagged. I also noticed upon my grabbing the roomnumbers that there are duplicate numbers in here.

  nipoh_oshu1:
  - 12483
  - 12487
  - 12937
  - 12936
  - 12484
  - 12936
  - 12937
  nipoh_oshu2:
  - 12482
  - 12494
  - 12495
  - 12496
  - 12493
  - 12498
  - 12499
  nipoh_oshu3:
  - 12488
  - 12489
  - 12936
  - 12937
  - 12490
  - 12491
  - 12492

Numbers I found duplicates of:
12937
12936

**Comment by Dartellum** [comment]
PR created but need some clarity.
  
# https://elanthipedia.play.net/nipoh_oshu                             240-350
  nipoh_oshu1:
  - 12483
  - 12487
  - 12937
  - 12936
  - 12484
  nipoh_oshu2:
  - 12482
  - 12494
  - 12495
  - 12496
  - 12493
  - 12498
  - 12499
 nipoh_oshu3:
  - 12488
  - 12489
  #- 12936 Belong here on in nipoh_oshu1?
  #- 12937 Belong here on in nipoh_oshu1?
  - 12490
  - 12491
  - 12492  
  #- 12497 This part of the area?

**Comment by Kaesken** [comment]
Next time I'm out on Aesry I can try to use the Ranik's maps to circle which rooms show the duplicate numbers.  Dunno why I didn't think of that at the time, lol
