### ISSUE TITLE
Enchanting Crashing

### ISSUE THREAD

**Issue by khrispyb** [rpherbig/dr-scripts#3784]
craft enchanting was working fine a few days ago, all of a sudden (changed nothing in my yaml) am getting the following issue (after below log, just gets all jacked up with hands and not having anything to craft and spins for hours):

--- Lich: enchant active.

[enchant]>get my artificing book

You get a book of apprentice artificing instructions from inside your carryall.
> 
[enchant]>turn my book to chapter 2

You turn your book to chapter 2, entitled "Utility and Fluff Artificing".
> 
[enchant]>read my book

              -=    Chapter 2 : Utility and Fluff Artificing    =-

 Page 1: a radiant trinket                       Page 7: simple devourer
 Page 2: a celestial beacon                      Page 8: a wind trinket
 Page 3: a cambrinth retuner                     Page 9: Garden's Vision
 Page 4: a flash trinket                         Page 10: an earth trinket
 Page 5: a mana trinket                          
 Page 6: Eluned's Scry                           

> 
[enchant: *** No match was found after 15 seconds, dumping info]

[enchant: messages seen length: 7]

[enchant: message:  Page 6: Eluned's Scry                           ]

[enchant: message:  Page 5: a mana trinket                          ]

[enchant: message:  Page 4: a flash trinket                         Page 10: an earth trinket]

[enchant: message:  Page 3: a cambrinth retuner                     Page 9: Garden's Vision]

[enchant: message:  Page 2: a celestial beacon                      Page 8: a wind trinket]

[enchant: message:  Page 1: a radiant trinket                       Page 7: simple devourer]

[enchant: message:               -=    Chapter 2 : Utility and Fluff Artificing    =-]

[enchant: checked against [/Page \d+: earth trinket/i]]

[enchant: for command read my book]

[enchant]>turn my book to page 

Which page do you wish to turn the a book of apprentice artificing instructions to?
> 
[enchant: *** No match was found after 15 seconds, dumping info]

[enchant: messages seen length: 1]

[enchant: message: Which page do you wish to turn the a book of apprentice artificing instructions to?]

[enchant: checked against [/You turn your/i, /The book is already/i]]

[enchant: for command turn my book to page ]

[enchant]>study my artificing book

You quickly flip through the book and determine it is a collection of instructions for the artificing crafting Discipline in the Enchanting crafting society.

Upon further perusal, it appears you can TURN the BOOK to the FOREWORD, and read a short primer on how crafting of this type is performed.  You may also TURN the BOOK to INDEX, and read it for a list of chapters.  Then, you can TURN the BOOK to CHAPTER # and read it for a list of instructions on each page.  Finally, you can TURN the BOOK to a PAGE # in that chapter, and read it for detailed information on what is required for the crafting process.

Once you have turned to the page you wish to craft, you may STUDY the BOOK to begin the crafting process.
> 
[enchant: *** No match was found after 15 seconds, dumping info]

[enchant: messages seen length: 3]

[enchant: message: Once you have turned to the page you wish to craft, you may STUDY the BOOK to begin the crafting process.]

[enchant: message: Upon further perusal, it appears you can TURN the BOOK to the FOREWORD, and read a short primer on how crafting of this type is performed.  You may also TURN the BOOK to INDEX, and read it for a list of chapters.  Then, you can TURN the BOOK to CHAPTER # and read it for a list of instructions on each page.  Finally, you can TURN the BOOK to a PAGE # in that chapter, and read it for detailed information on what is required for the crafting process.]

[enchant: message: You quickly flip through the book and determine it is a collection of instructions for the artificing crafting Discipline in the Enchanting crafting society.]

[enchant: checked against [/You scan/i, /You review/i]]

[enchant: for command study my artificing book]

[enchant]>put my artificing book in my carryall

You put your book in your carryall.
> 
[enchant]>untie my brazier from my enchanter's toolbelt

You untie a tin brazier from the straps of your enchanter's toolbelt.
> 
[enchant]>get my totem from my carryall

You get a plain bone totem from inside your carryall.
> 
[enchant]>put my totem on brazier

You glance down at the smoking brazier and reconsider if you wish to begin enchanting.

[Putting an item on the brazier begins the enchanting process.  This process can enhance the item, or cause serious damage to it and the enchanter.  Put your item onto the brazier again in the next 30 seconds, to proceed.  You've been warned!]
> 
[enchant]>put my totem on brazier

You must first clean off the brazier.
> 
[enchant]>clean brazier

The brazier is not currently lit, and so you feel it is safe to collect anything atop it.
> 
[enchant]>put my bone totem in my carryall

You put your totem in your carryall.
> 
[enchant]>look on brazier

On the brazier you see a bone totem.
> 
[enchant]>get my totem

You get a plain bone totem from atop your brazier.
> 
[enchant]>put my totem in my carryall

You put your totem in your carryall.
> 
[enchant]>get my totem from my carryall

> 
You get a plain bone totem from inside your carryall.
> 
[enchant]>put my totem on brazier

You glance down at the smoking brazier and reconsider if you wish to begin enchanting.

[Putting an item on the brazier begins the enchanting process.  This process can enhance the item, or cause serious damage to it and the enchanter.  Put your item onto the brazier again in the next 30 seconds, to proceed.  You've been warned!]
> 
[enchant]>put my totem on brazier

You must first study instructions regarding the enchantment you wish to begin, prior to placing the item to be enchanted on the brazier.
You put your totem on your brazier.

**Comment by Hazado** [comment]
due to a change in common-crafting.lic this issue happened.
PR #3781 is in to fix this issue.
