### ISSUE TITLE
enchant.lic issue /w craft.lic - after runestone created, change to get MY runestone after completion

### ISSUE THREAD

**Issue by SekmehtDR** [rpherbig/dr-scripts#3797]
In shard, when enchant runs starting with craft.lic it finishes the crafting no problem. But when the script gets ready to finish it tries to "get runestone" defaulting for what is at your feet. Well when this happens, it tries to get the runestone from the shop and the script hangs and repeats.

> You pick up the fount lying at your feet.
> > 
> [enchant]>put my fragile fount in my pack
> 
> You put your fount in your traveler's pack.
> > 
> [enchant]>get runestone
> 
> A sales clerk rushes over to help you.
> 
> The sales clerk smiles and says, "The price on a basic basalt runestone is 135 Dokoras.  You can BUY the item if you like."
> > 

The line above, if it can be changed to get **my** runestone that would fix this syntax/location issue. Thanks!

**Comment by SekmehtDR** [comment]
One thing I found was in craft.lic, walk_to (@training_room) is missing for items 550 and 700 ranks in difficulty. this should be there to walk away from the room with supplies (and training_rooms being added to the setup yaml). Still wouldn't hurt ot include the "get MY runestone" in there too.

>     elsif rank <= 550 # Tier 7 - Challenging
>       # Buy a abolition and induction sigils and runestone
>       ensure_copper_on_hand(4000, @settings)
>       order_item(crafting_data['artificing'][@hometown]['stock-room'], 2)
>       order_item(crafting_data['artificing'][@hometown]['stock-room'], 1)
>       stow_hands
>       buy_item(crafting_data['artificing'][@hometown]['stock-room'], 'runestone')
>       stow_hands
**>       walk_to(@training_room)**
>       wait_for_script_to_complete('enchant', [6, 'gauge flow runestone', 'runestone'])
>       dispose_trash('runestone')

**Comment by SekmehtDR** [comment]
I think the issue in enchant.lic is on line 235 in def cleanup...

> bput("get #{@item}", "You", "What")

Needs to be changed to

> bput("get my #{@item}", "You", "What")

**Comment by SekmehtDR** [comment]
After making these changes everything works perfect for me, hopefully this isn't clear as mud and helps you guys out! Thanks for all you do.

**Comment by Dartellum** [comment]
Added walk_to for tier 7 and 8. That should fix this.
