### ISSUE TITLE
sew.lic - seal, lighten, and reinforce fails to find page

### ISSUE THREAD

**Issue by dakre18** [rpherbig/dr-scripts#3803]
After checking the script, it appears to be the colons in the page name for seal, lighten, and reinforce cause a Regex match problem. I removed the colon and they worked fine.

With the colons, it turns to chapter 1 in the tailor book (i use a master book), then times out and never finds the page.

**Comment by Hazado** [comment]
could you post that page please? it will help witb fixing the regex
