### ISSUE TITLE
New shaping workorder update is hanging when buying glue

### ISSUE THREAD

**Issue by nro2** [rpherbig/dr-scripts#3807]
New update causing shaping/workorders to mess up when buying glue.  Counts two, goes to buy more with the 2 still in hand, and never handles the 2 volume.  Ends up with full hands trying to buy more glue repeatedly.   400 line or so text file of the error attached.

**Comment by Dartellum** [comment]
Working on a fix.

**Comment by Dartellum** [comment]
See PR 3808 for the fix.

**Comment by rpherbig** [comment]
Fixed in c075abb5a9496b4df3f9a9cf63ee57019b143ac3 from PR #3808
