### ISSUE TITLE
go2 "go foot" needs to be specified

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#3810]
May want to specify "footpath" instead of "foot" because while wearing "footwraps", it gets confused.  Room number: 19467

[Dark Woodlands, Rugged Trail]
Silverwood trees line the hard-packed rocky path, casting long pockets of shadow across the brush.  Red and black berries, in various stages of ripeness, dangle invitingly across the trail from the myriad of chokecherry bushes stealthily hidden in the brown grass.
You also see a moss-covered footpath.
Obvious paths: north, south.

> 
Mapped exits: go moss-covered footpath

[go2]>go foot

You can't do that.

**Comment by Sarvatt** [comment]
you know you can do that yourself right?

**Comment by Sarvatt** [comment]
just change it to go moss footpath

**Comment by Kaesken** [comment]
How?  I looked into the go2 file and can't find it and there isn't any info on do it.

**Comment by Sarvatt** [comment]
hopefully someone playing the game still sees this, its a mapping issue nohing to do with drscripts

**Comment by Kaesken** [comment]
Mkay then how am I to do this myself if it's got  nothing to do with drscripts?  I'm sorry but you're coming off as rude and I don't know why.  I'm only trying to be helpful with finding bugs, glitches and issues.

**Comment by Kaesken** [comment]
After reading 3 different pages of epedia, I finally figured it out.  No idea why that was so difficult to explain....

;automap
go footpath
;stop

Boom, fixed.

**Comment by rpherbig** [comment]
Thank you for fixing the map @Kaesken !

**Comment by Kaesken** [comment]
You're welcome @rpherbig .  Helf helped me step by step since the way I found was just a temp fix for only my end.  Pretty simple now that I know the 2 commands to do it.
