### ISSUE TITLE
Combat Trainer Suggestion for Empaths

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#3815]
Since a few construct areas as we get older have regular creatures mixed in, I'd like to suggest maybe an additional features that if you're an empath, PERCEIVE the creature to check if it's living, undead or a construct prior to determining a mode of attack.

Perceive for living:
You sense a life essence enlivening the gryphon.

Perceive for undead:
A twisted and abused life essence animates the fiend, even though it should be inert.  A subtle ripple of pain dances across your senses at this encounter with the undead.

Perceive for construct:
Though somehow animate, this construct lacks any life essence.

**Comment by Ry7n** [comment]
This is a great idea, although these values shouldn't need to be pulled dynamically, as they would be constant for all of the NPCs with the same adjective/noun combo. Instead, it might make sense to add a new `base-creatures.yaml` that includes the creature type, and adjust attacks accordingly.

**Comment by Kaesken** [comment]
That actually sounds like a wonderful idea.  I hope it gets implemented because my Empath is so far behind on her weapons compared to her defenses and especially her magics it's sad, lol

**Comment by Kaesken** [comment]
@Ry7n ; Tho not sure if it'll be implemented.  I was just given word by a character named "Gooseberry" that he's informed the dev team here to ignore my issues and requests.  No idea why.  I'm just trying to be supportive and helpful.  lol

**Comment by Sarvatt** [comment]
Gooseberry is me. anyway weirdo, this is only useful for very low level isn’t it? would this be used past gargs?

**Comment by Kaesken** [comment]
Not sure if you'd see my discord so I'll post it here and in public, as well to show that I'm not trying to be this "entitled asshole" you're trying to claim I am.
Okay, first of all, I do apologize if I come across as what you called an entitled asshole, I really didn't mean to.  I only post on github trying to be helpful and supportive.  I don't know what your beef is.  You could have just came to me like a mature adult and told me you had an issue with how I worded things, we could have talked and hashed things out and I would have explained to you I didn't mean to sound that way and apologized to you up front but you didn't.  You instantly went into the insults and rudeness.  Now, I'm still trying to learn how not to come across asshole-ish via text online, even my therapist is trying to help me but no amount of "training" seems to be helping because in my mind, I don't see myself being an asshole.  But thing I've learned is that text via online isn't always what it seems.  It may seem one way to one person who's in a good mood and a totally different way to someone in a bad mood.

Now, back to subject...  the younger construct areas for Empaths have just those types of creatures.  Orgami, endrus serpents, etc. However, granite gargoyle have other living creatures the spawn with them.  I tried going to the clay soldiers, however, unfortunately their lodged object (I forget what it was) messes with the script and kills it due to it being an item that dissolves upon touch and when trying to drop what you tended, it says that you're not holding it even tho you are holding one.  I haven't got to the black marble gargoyles quite yet.  Tho my magics should be strong enough I can try to jump to them but that's a pretty large leap to avoid constructs areas that don't spawn other living/undead creatures (if I dont have absolution up at the time).  I've not checked the undead areas, however.

**Comment by Hiinky** [comment]
FWIW granite gargoyle is the the last hunting ground you'll come across that has mixed creatures and it can easily be bypassed with undead kobolds and eidolon steeds in Shard.  This is most likely the reason its never been built in.  Also, the Simu mechanic that makes you automatically face your next target is the biggest hurdle.  Other than granite gargs, a simple "- construct" or "- undead" arg is plenty to hunt safely.  I can say that I do like the idea of being able to read in the undead/construct status from base-hunting.

I've sent in several Simu BUG reports on clay solders.  Its super annoying and no one but an empath really ever wants to hunt there despite being in a great skill range.  In a pinch you can EMPTY left/right to drop the fragments.  When I hunted up there a put a sound alarm on the "you can't drop that" message so I knew to fix it asap.  Other than the buggy fragments, ;tendme does pretty good at keeping you fragment-free

**Comment by Kaesken** [comment]
@Hiinky ; That's a great idea on the alarm for the time being.  I'll have to add that in.
