### ISSUE TITLE
Alchemy Workorders Hangup

### ISSUE THREAD

**Issue by khrispyb** [rpherbig/dr-scripts#3820]
Was working fine a few days ago, but am now getting a weird sequence where it puts stuff away (mortar) then tries to work with it.  I think this hangup has cause lich to crash and boot me more than a few times over the past few days - see below.  Thanks!

[remedy]>crush my cream with my pestle

With short strokes you crush some unfinished blister cream with your pestle.  Peering at the mixture reveals an even distribution of materials.

Upon completion you see some particulate clouding up the mixture.
Roundtime: 20 sec.

You need another prepared herb to continue crafting some unfinished blister cream.  You believe you can just pour or put it inside the mortar and continue crushing the unfinished remedy inside.

[Ingredients can be added by putting them with the unfinished item and continuing to craft.]
R> 
[remedy]>put my iron mortar in my carryall

You put your mortar in your carryall.
> 
[remedy]>tap nemoih in carryall

You tap some dried nemoih inside your carryall.
> 
[remedy]>get my nemoih from my carryall

You get some dried nemoih from inside your carryall.
> 
[remedy]>put my nemoih in my mortar

You vigorously rub the nemoih alongside the mortar to scrape some shavings into the mixture.
> 
[remedy]>put my dried nemoih in my carryall

You put your nemoih in your carryall.
> 
[remedy]>get my pestle

You are already holding that.
> 
[remedy]>get my sieve

You get a metal sieve from inside your carryall.
> 
[remedy]>push my cream with my sieve

Push what?

**Comment by Hazado** [comment]
Its strange that your mortar is in your left hand

**Comment by khrispyb** [comment]
Yeah, I'll try to get a longer log for you, but it's getting tangled somewhere.
