### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by khrispyb** [rpherbig/dr-scripts#3824]
Over the past week or two, I've had at least 3-4 crashes per day at random points through my training, no consistent place.  Not sure what it is or if this is helpful, but I'm pasting the most recent below in case it is something that others are experiencing:

You gesture.
You twist the mana streams of your Clear Vision spell in a chaotic motion, inciting them into unpredictable patterns.
You feel more aware of your environment.

> 
[buff]>release mana

> 
You feel fully attuned to the mana streams again.
> 
[buff: *** No match was found after 15 seconds, dumping info]

[buff: messages seen length: 5]

[buff: message: Shadows  (9 roisaen)]

[buff: message: Gauge Flow  (14 roisaen)]

[buff: message: Clear Vision  (10 roisaen)]

[buff: message: Piercing Gaze  (70 roisaen)]

[buff: message: You feel fully attuned to the mana streams again.]

[buff: checked against [/You release all/i, /You aren't harnessing any mana/i]]

[buff: for command release mana]

[buff]>prep symb

--- error: server_thread: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. @ io_fillbuf - fd:4

**Comment by khrispyb** [comment]
Tried to update lich to fix constant disconnect issue - now can't even connect after updating.  Would really appreciate some help.  Thanks

--- Lich: repository active.

[repository: downloading Lich 4.6.54...]

[repository: Lich has been updated to version 4.6.54.]

[repository: Changes will take effect next time you start Lich.]

[repository: map database is up-to-date]

[repository: done]

[repository: scripts are up-to-date]

--- Lich: repository has exited.


exit

--- Lich: dependency has exited.

--- Lich: skill-recorder has exited.

--- Lich: roomnumbers has exited.

--- Lich: moonwatch has exited.

--- Lich: afk has exited.

--- Lich: lnet has exited.

[09:48] Connection closed.
[09:48] Connected to eaccess.play.net.
[09:48] Connection closed.
[09:48] Connect failed. (ConnectionRefused)
[09:48] Connected to eaccess.play.net.
[09:48] Connection closed.
[09:48] Connect failed. (ConnectionRefused)
[09:49] Connected to eaccess.play.net.
[09:49] Connection closed.
[09:49] Connect failed. (ConnectionRefused)

**Comment by rpherbig** [comment]
That version number doesn't look like the lich fork. Can someone check on
that for me?

@sarvatt @janderson

**Comment by khrispyb** [comment]
Tried to reinstall lich from the lich project, site to no avail. can't log in to lich at all from any FE, same unable to connect issue. May need a TeamViewer assist or something as I'm at a loss, will tip handsomely to undo whatever I did here...thanks :/

**Comment by bmcneff** [comment]
First step, let's see what we're dealing with.  What's your OS? Are you using windows10 64bit, or something else? If you are, it simplifies things a bit, there's an [automated installer](http://bit.ly/Win10-Lich-Installer) which makes life easier and gives us a solid base from which to start.  If not, things get a bit more complex.

**Comment by khrispyb** [comment]
Windows 10 64 Bit is what I'm running.

So I've narrowed it down to a hosts file issue (lich now connects through stormfront) - had to delete a line for DR in the hosts file.  It still isn't working though because, since editing the hosts file, it now thinks the hosts file is a .txt file even though I save as "all files" - any ideas?

**Comment by bmcneff** [comment]
Follow this to enable file extensions:
https://www.thewindowsclub.com/show-file-extensions-in-windows

Follow this to learn how to edit your hosts file:
https://support.rackspace.com/how-to/modify-your-hosts-file/

When you edit it this time, delete the .txt file extension and save the file.

**Comment by khrispyb** [comment]
Yep, that totally worked.  Huge thank you.
