### ISSUE TITLE
combat-trainer picking up tk_ammo

### ISSUE THREAD

**Issue by Akhorishaan** [rpherbig/dr-scripts#3825]
Been poking at it a bit, but can't figure it out.  It will drop the designated tk_ammo on the ground, then pick it back up again before casting, then it has nothing to throw so it drops some ammo again, then picks it right back up.  Not using a ranged weapon at all, just using the bolts as tks ammo.

[combat-trainer]>get my crossbow bolts

You get some crossbow bolts from inside your backpack.

> 
[combat-trainer]>drop crossbow bolts

You drop some crossbow bolts.

> 
[combat-trainer]>target tks 15

You raise your hands skyward, chanting the equation of the Telekinetic Storm spell.
You begin to weave mana lines into a targeting pattern centered around yourself that is designed to strike the avenues of attack around you.

> 
[combat-trainer]>stow bolts

You pick up some crossbow bolts.
You put your bolts in your backpack.

**Comment by Tarhish** [comment]
I can answer this one.  bolt and bolts are standard entries in the lootable list, ie. it will always try to pick them off the ground when it sees them.  You'll want to either make a 
```
loot_subtractions:
- bolt
- bolts
```
entry to tell it not to pick up bolts willy nilly (don't do this if you use bolts as ammo for a crossbow) or choose a different tk_ammo.

**Comment by Hiinky** [comment]
You can set restock  to buy tk_ammo such as shaving razors or cheap weapons that can be easily replaced if lost.  It Crossing it will default to a kris or you can set a custom item.

restock:
  tk_ammo:
    quantity: 2  
    hometown: Crossing
    name: yellow razor
    room: 8265
    price: 312
    size: 1
    stackable: false

**Comment by jayRyan24** [comment]
@Akhorishaan As they said, you will need to A) remove bolts/arrows from your loot tables when hunting with TKT/TKS, or you can use one of the other types of ammo from the base files that already exist. Please close this issue. Thank you!
