### ISSUE TITLE
check_discern error

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#3832]
[combat-trainer]>attack

< You gouge your fingers at a baby forest gryphon.  A baby forest gryphon dodges, barely managing to get out of the way.  
[You're bruised, adeptly balanced and in superior position.]
[Roundtime 1 sec.]
R> 
[combat-trainer]>stance set 83 100 0

> 
Setting your Evasion stance to 83%, your Parry stance to 100%, and your Shield stance to 0%.  You have 0 stance points left.
> 
--- Lich: error: comparison of Float with nil failed
	common-arcana:498:in `>'
	common-arcana:498:in `check_discern'

--- Lich: combat-trainer has exited.

**Comment by Tarhish** [comment]
Huh.  Line 498 is
```
elsif discern_data.empty? || discern_data['time_stamp'].nil? || Time.now - discern_data['time_stamp'] > settings.check_discern_timer_in_hours * 60 * 60 || !discern_data['more'].nil?
```
Since there's already an earlier check for discern_data['time_stamp'].nil? I suppose settings.check_discern_timer_in_hours must be nil somehow.

I wasn't even aware you could adjust this until now, but I suppose you can.  Long shot, but you don't have that setting in your setup yaml, do you?

**Comment by Kaesken** [comment]
No idea.  I took it straight from the github.  I don't have check_discern_timer_in_hours at all.  I only have use_auto_mana

**Comment by Kaesken** [comment]
Thankfully I have the old version of my combat-trainer on my other laptop so I can convert it back.

**Comment by Kaesken** [comment]
Ok, so I think I got it.  I'm in dev mode so I was manually making certain changes by uploading them into my scripts folders.  I must have made an oppsie somewhere so this was 100% my fault.
I zipped a copy of my lich folder, took myself off dev mode, updated and no errors.

Sorry about that.   Thank you for the assistance @Tarhish
