### ISSUE TITLE
Appraisal.lic Appraise focus with OM running

### ISSUE THREAD

**Issue by Windamere** [rpherbig/dr-scripts#3836]
Hit a snag with the new update Appraise focus

Needs a catch for running scripts like OM that interfere with research.

@no_use_scripts = settings.appraisal_no_use_scripts
(probably needs a yaml addition as well)

return if @no_use_scripts.any? { |name| Script.running?(name)

Things like zills, summoning, outdoors, and athletics shouldn't affect it, but any magic skills or locksmithing causes it to break..

**Comment by jayRyan24** [comment]
This pauses and waits for the script to finish. Are you running those other scripts during this?

**Comment by jayRyan24** [comment]
What you're asking for will only not run the appraisal if those things aren't running, but if they are run while appraisal is running, it will still break it. Every script would have to be changed to avoid running while appraisal is running.

**Comment by drgabellia** [comment]
I'm the one that prompted this.....I have a script that runs in the background that keeps my OM orb full via harnessing when it drops to a certain threshold.  If it harnesses during appraisal focus it stops the focus.  I was looking for a way to either pause or stop my harness script during ;appraisal focus.

**Comment by rcuhljr** [comment]
It's probably easier to change the background script to just not execute while appraisal is running. The sanowret crystal script should be a good example of this.

**Comment by drgabellia** [comment]
I would be happy to amend my script to not execute while appraisal is running.  Unfortunately, even after looking at the sanowret crystal script I do not know how to do this.

**Comment by Tarhish** [comment]
I could take a look, but for an OM maintaining script it _might_ be just adding an `unless Script.running?('appraisal')` at the end of whatever line is actually doing the harnessing.

Like, `focus_orb(blahblah) unless Script.running?('appraisal')`

**Comment by Sarvatt** [comment]
share it on discord, i'm sure a bunch of us will help. it's not a script in dr-scripts so its not really an issue here to be honest.

**Comment by Tarhish** [comment]
She ran it by me just a little bit earlier, and it turns out some enterprising soul had already added a no_use_almanac list += an array of a couple other scripts, so in the end it was even easier.  I just plopped it onto the end of the array.  I have a feeling this script has been passed around a few times. 😄

**Comment by drgabellia** [comment]
More than a few, I think!  Thank you again for your help, Tarhish.  It's working great!

**Comment by jayRyan24** [comment]
@Windamere Can you close this please? Thanks!
