### ISSUE TITLE
go2 unable to navigate from Asharshpar'i

### ISSUE THREAD

**Issue by Akhorishaan** [rpherbig/dr-scripts#3844]
[Telpengi'hhs Sara'a, Embalming Chamber]
Grime of ages untold sullies the walls, the dankness and layered soot blanketing everything until the room appears like something from a demented painter's twisted nightmare vision, or a place where the souls of the deceased rage for eternity.  Thick with filth, the details of the ceiling and walls are obscured, sharpening the contrast of the silvery-white shard of stone inset into the ornate pedestal that rests in the center of the chamber.  
Obvious exits: south.

Room Number: 9999

[go2: error: failed to find a path between your current room (9999) and destination room (####)] (inside oshu manor)

Was wondering if go2 could be tweaked to know how to navigate out of the embalming rooms in Oshu, all you have to do is go to the room right to the east of the door and turn the sconce, then the door opens.

For reference, door is in 9996 and TURNable sconce is in 9998

**Comment by MahtraDR** [comment]
Closing this as we don't control the mapdb.
