### ISSUE TITLE
Equipmentmanager.lic

### ISSUE THREAD

**Issue by mrsaletzkus** [rpherbig/dr-scripts#3846]
it doesn't untie items from a rucksack ... the wording for it is untie <item name> from my rucksack... it ties the items no problem but will not untie them ... I have tie_on: set to rucksack

**Comment by Sarvatt** [comment]
its tie_to: also keep in mind rucksack ties have a limited number of uses

**Comment by mrsaletzkus** [comment]
thats how I have it and thats not working ... no I didn't know there was limited uses thanks for letting me know

**Comment by Sarvatt** [comment]
what are you tying?

**Comment by mrsaletzkus** [comment]
a spear and a quaterstaff

**Comment by jayRyan24** [comment]
Can you provide a log of what's happening.

**Comment by MahtraDR** [comment]
@mrsaletzkus Is this still an issue?

**Comment by MahtraDR** [comment]
@rpherbig Can close this. No updates in a long time, no longs.
