### ISSUE TITLE
Almanac breaks workorders when doing artificing

### ISSUE THREAD

**Issue by nro2** [rpherbig/dr-scripts#3855]
This has happened twice to me in the past two days.  The script stows my burin to pull out the almanac, studies the almanac and doesn't get the burin back out.

https://pastebin.com/jTTB2M8f

**Comment by aruthas** [comment]
Make sure to add it to the almanac_no_use_scripts.

**Comment by nro2** [comment]
Thanks, actually did this last night and forgot to close this!

**Comment by Sarvatt** [comment]
fixing it for everyone in https://github.com/rpherbig/dr-scripts/pull/3877
