### ISSUE TITLE
forge.lic - lighten fails to find page

### ISSUE THREAD

**Issue by dakre18** [rpherbig/dr-scripts#3857]
with the changes to finding recipes, ;forge lighten <noun> no longer works by just finding "lightening" in the armor book. It fails to match anything, and in turn continues the script without starting the process.

I changed the script to find "metal armor lightening" and it worked just fine. This only applies to armor, so nothing else needed changed.

similar to issue #3803 and fix applied in #3804 

****************

[forge]>get my armorsmithing book
You get a book of master armorsmithing instructions from inside your hunting pack.

[forge]>turn my book to chapter 5
You turn your book to chapter 5, entitled "Armor Enhancements".

[forge]>read my book

              -=    Chapter 5 : Armor Enhancements    =-

 Page 1: metal armor lightening                  Page 4: metal armor reinforcing
 Page 2: metal armor tempering                   Page 5: rare-metal armor tempering
 Page 3: metal armor repair                      

[forge: *** No match was found after 15 seconds, dumping info]
[forge: message:  Page 3: metal armor repair                      ]
[forge: message:  Page 2: metal armor tempering                   Page 5: rare-metal armor tempering]
[forge: message:  Page 1: metal armor lightening                  Page 4: metal armor reinforcing]
[forge: message:               -=    Chapter 5 : Armor Enhancements    =-]
[forge: checked against [/Page \d+:\s(?:some|a|an)?\s*lightening/i]]
[forge: for command read my book]
[forge]>turn my book to page 
Which page do you wish to turn the a book of master armorsmithing instructions to?

[forge: *** No match was found after 15 seconds, dumping info]
[forge: message: Which page do you wish to turn the a book of master armorsmithing instructions to?]
[forge: checked against [/You turn your/i, /The book is already/i]]
[forge: for command turn my book to page ]
[forge]>study my book
You quickly flip through the book and determine it is a collection of instructions for the armorsmithing crafting Discipline in the Forging crafting society.

Upon further perusal, it appears you can TURN the BOOK to the FOREWORD, and read a short primer on how crafting of this type is performed.  You may also TURN the BOOK to INDEX, and read it for a list of chapters.  Then, you can TURN the BOOK to CHAPTER # and read it for a list of instructions on each page.  Finally, you can TURN the BOOK to a PAGE # in that chapter, and read it for detailed information on what is required for the crafting process.

Once you have turned to the page you wish to craft, you may STUDY the BOOK to begin the crafting process.

**Comment by MahtraDR** [comment]
forge.lic has been completely rewritten since. Closing as stale.
