### ISSUE TITLE
Astrology isn't working right.

### ISSUE THREAD

**Issue by nro2** [rpherbig/dr-scripts#3867]
Starting today, when training astrology, my moon mage is centering his telescope on Dawgolesh and peering, over and over and over.  Used to only train with RTR, now it isn't using it at all.

**Comment by nro2** [comment]
https://pastebin.com/mdCxwrhq

**Comment by nro2** [comment]
Also, when stowing bones:

[astrology]>put bones in my {"container"=>"haversack", "tied"=>false}

**Comment by jayRyan24** [comment]
The peer_telescope issue:

The issue is:

```
      result = DRCMM.peer_telescope
      case result
      when /The pain is too much/
        get_healed
        return observe_routine(body)
      when /open it/
```

it's wanting the return `/open it/` and getting `/open it to make any use of it/`

I will also push the fix for the bones. Thanks for helping and making the issue.

**Comment by mtruitt** [comment]
This needs to be reopened. I just pulled and tested and still the same issue.
