### ISSUE TITLE
Enchant.lic - imbue isn't recast when it backfires

### ISSUE THREAD

**Issue by dakre18** [rpherbig/dr-scripts#3869]
While enchanting, my first imbue spell backfired, and it didn't attempt to recast it. Might want to make sure it does on the second cast as well, since it will not finish the enchantment without successfully casting imbue.

I do have 'use_harness_when_arcana_locked: true` set, so it charges my cambrinth as well as harnesses mana, but it should still cast it at 100 mana (as i'm trying to do).

************

[enchant]>prep imbue 25
You trace a careful sigil in the air, shaping the pattern of the Imbue spell.

[enchant]>charge my watersilk bag 25
You harness a moderate amount of energy and attempt to channel it into your watersilk bag.
You are able to channel all the energy into the bag.
The watersilk bag absorbs all of the energy.
Roundtime: 3 sec.

[enchant]>charge my watersilk bag 25
...wait 1 seconds.

[enchant]>charge my watersilk bag 25
You harness a moderate amount of energy and attempt to channel it into your watersilk bag.
You are able to channel all the energy into the bag.
The watersilk bag absorbs all of the energy.
Roundtime: 3 sec.

[enchant]>charge my watersilk bag 25
...wait 1 seconds.

[enchant]>charge my watersilk bag 25
You harness a moderate amount of energy and attempt to channel it into your watersilk bag.
You are able to channel all the energy into the bag.
The watersilk bag absorbs all of the energy.
Roundtime: 3 sec.

[enchant]>invoke my watersilk bag 75
You feel fully prepared to cast your spell.

The watersilk bag pulses with Elemental energy.  You reach for its center and forge a magical link to it, attempting to ready 75 energy lines for your use.  Your efforts are mostly successful, but you accidentally attune yourself to 76 of the lines.
Roundtime: 1 sec.

[enchant]>harness 25
You tap into the mana from twenty-five of the surrounding streams and attempt to keep it channeling in a stream around you.
Roundtime: 2 sec.

[enchant]>harness 25
You tap into the mana from twenty-five of the surrounding streams and add it to the appreciable amount already streaming around you.
Roundtime: 2 sec.

[enchant]>harness 25
...wait 1 seconds.

[enchant]>harness 25
You tap into the mana from twenty-five of the surrounding streams and add it to the vast amount already streaming around you.
Roundtime: 2 sec.

You sense a tiny amount of mana slip away from you.

[enchant]>cast basic runestone on brazier
You gesture at a basic basalt runestone.
You contribute your harnessed streams to increase the pattern's potential.
Your watersilk bag emits a loud *snap* as it discharges as much power as necessary, leaving a great amount left for future use.
Your spell barely backfires.

[enchant]>untie my burin from my enchanter toolbelt
You untie a polished moabi burin set with a fey-bone handle from the straps of your enchanter's toolbelt.

[enchant]>scribe basic runestone on brazier with my burin
That tool does not seem suitable for that task.

**Comment by MahtraDR** [comment]
This is addressed by #6452 but note if it's wildly wrong, it'll just get stuck retrying, so some user due diligence is required to ensure your settings work...
