### ISSUE TITLE
disconnects

### ISSUE THREAD

**Issue by khrispyb** [rpherbig/dr-scripts#3882]
Not sure where to put this, but I'm getting this error about 3 times a day.  Anything I can do on my end?

[lnet: An existing connection was forcibly closed by the remote host. - SSL_connect]

lnet:117:in `connect'
lnet:117:in `connect'

[lnet: closed stream]

C:/Ruby24-x64/lib/ruby/2.4.0/openssl/buffering.rb:57:in `sysread'
C:/Ruby24-x64/lib/ruby/2.4.0/openssl/buffering.rb:57:in `fill_rbuff'

[lnet: connection lost]

[lnet: waiting 280 seconds before trying to reconnect...]

--- error: server_thread: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. @ io_fillbuf - fd:4

**Comment by khrispyb** [comment]
this is the other message I'm getting:

--- error: server_thread: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. @ io_fillbuf - fd:4 
[dependency: error in moonwatch #<Errno::ECONNRESET: An existing connection was forcibly closed by the remote host. - SSL_connect>]

I should note I live in mexico city so maybe this has something to do with my IP?  I'm trying through a U.S.-based VPN to see if that changes anything...

**Comment by rcuhljr** [comment]
I think this is just a side effect of some unreliable network connection between you and some of the various hosts (lnet's chat server, firebase for moonwatch data). If it's not crashing you or causing inconvenience I think you'll basically just need to ignore it if the VPN doesn't change anything.

**Comment by khrispyb** [comment]
Ah that's unfortunate.  It kicks me off DR altogether every time.  The VPN
didn't change anything unfortunately.

**Comment by rcuhljr** [comment]
You might try talking to your ISP?  I'd be surprised if you don't see any similar connection issues for other long running requests (other games, some less resilient streaming services).

**Comment by khrispyb** [comment]
Not having any other issues so I don't think it's an ISP thing.  Guess I just have to live with it?
