### ISSUE TITLE
Workorders

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#3892]
My apologies if this was already mentioned but I have workorders set to before hunting and if I don't have any coins on me when I start training-manager, it goes straight to workorders without withdrawing any coins but continues to try order things.

[go2: travel time: 0:00:05]

--- Lich: go2 has exited.

[workorders]>order 3

The attendant shrugs and says, "Ugh, you don't have enough coins to purchase an intricate congruence sigil-scroll!"
> 
[workorders]>order 3

The attendant shrugs and says, "Ugh, you don't have enough coins to purchase an intricate congruence sigil-scroll!"
> 
[workorders]>buy sphere

The clerk says, "That will be 150 Kronars."
You realize you don't have that much.
> 
[workorders: *** No match was found after 15 seconds, dumping info]

[workorders: messages seen length: 3]

[workorders: message: [DRPrime]-DR:Kidrick: "they're just common enough to not be too expensive to replace"]

[workorders: message: You realize you don't have that much.]

[workorders: message: The clerk says, "That will be 150 Kronars."]

[workorders: checked against [/prepared to offer it to you for (.*) (?:kronar|lirum|dokora)s?/, /Let me but ask the humble sum of (.*) coins/, /for a (?:mere )?(.*) (?:kronar|lirum|dokora)s?/, /I can let that go for...(.*) (?:kronar|lirum|dokora)s?/, /cost you (?:just )?(.*) (?:kronar|lirum|dokora)s?/, /it may be yours for just (.*) (?:kronar|lirum|dokora)s?/, /I'll give that to you for (.*) (?:kronar|lirum|dokora)s?/, /I ask that you give (.*) copper (?:kronar|lirum|dokora)s?/, /it'll be (.*) (?:kronar|lirum|dokora)s?/, /the price of (.*) coins? is all I ask/, /tis only (.*) (?:kronar|lirum|dokora)s?/, /That will be (.*) copper (?:kronar|lirum|dokora)s? please/, /to you for (.*) (?:kronar|lirum|dokora)s?/, /I ask (.*) copper (?:kronar|lirum|dokora)s or if you would prefer/, /Cost you just (.*) (?:kronar|lirum|dokora)s?, okie dokie\?/i, /It will cost just (.*) (?:kronar|lirum|dokora)s?/i, /I would suggest (.*) (?:kronar|lirum|dokora)s?/i, /You decide to purchase/i, /Buy what/i]]

[workorders: for command buy sphere]

[workorders]>put my sphere in my traveling bag

What were you referring to?
> 
[workorders]>buy sphere

The clerk says, "That will be 150 Kronars."
You realize you don't have that much.
> ,ka

--- Lich: 'hunting-buddy' has been stopped by training-manager.

--- Lich: training-manager has exited.

> 
--- Lich: hunting-buddy has exited.

> weal

Wealth:
  No Kronars.
  No Lirums.
  No Dokoras.

**Comment by Sarvatt** [comment]
do you have workorder_cash_on_hand: empty in your yaml or something? it defaults to 20000 aka 2 plats for enchanting and grabs it before it crafts, it may be in an invalid format in your yaml if you changed it.

**Comment by Sarvatt** [comment]
or someone is stealing from you

**Comment by Kaesken** [comment]
It's quite possible she was stolen from but honestly this particular character, I haven't logged her on in a couple weeks, I wouldn't be able to tell you if she had any coin on her or not but when starting the training-manager, it never checked to see if she had coins.  However, I went ahead and added the workorder_cash_on_hand: 500 (I figure that's probably good enough since this particular account is f2p and I don't always have 2 plats in her bank).  I'll try to remember to check her balance before I start training-manager.

**Comment by Sarvatt** [comment]
it defaults to 20000 because it needs it, 5 silver isn't enough for more than one craft tops

**Comment by Kaesken** [comment]
A'ight, I'll put it back at 2pk.  I understand Simu adding a bank cap but 10?  I wish they'd do like 50 or 100 at the very least since the economy 1k is becoming chump change now.

Thanks, hun.

**Comment by Kaesken** [comment]
Okay so I figured out why it's always hanging.  Because F2P can only keep 10 plat at a time in the bank and we don't get money for completed workorders so once she uses up all her coins in the craft (and she doesn't hunt enough to keep 2 plats regularly), that's why workorders keep hanging.
