### ISSUE TITLE
LSU key + Jail Buddy/Pay Debt

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#3893]
Joined the Locksmith Union and apparently the keys stay worn on you even in jail, lol
So when the script tries to retrieve my sack, it can't cause of the key.  I went ahead and removed the key but jay asked me to post this.

```
[pay-debt]>get Damiza sack

You'll need to not be wearing anything to retrieve your items properly.  If you still want to retrieve your sack while wearing items, please attempt to get it again in the next ten seconds.
> 
> 
A soft midnight black kitten marches into the area on tiny paws, tail held proudly in the air.

> 
> 
[pay-debt: *** No match was found after 15 seconds, dumping info]

> inv
You are wearing a gleaming animite key.

[Type INVENTORY HELP for more options]
> 
> ,ka
```

**Comment by rpherbig** [comment]
How do you resolve this - `get sack` again? Do you then have to re-wear all of your gear?

**Comment by Kaesken** [comment]
Oh, doh, sorry forgot to mention that part.

I have to remove the key then get the sack to retrieve my stuff.
