### ISSUE TITLE
bescort breaks on the west side of the tunnel in gate of souls 

### ISSUE THREAD

**Issue by proctophage** [rpherbig/dr-scripts#3896]
https://pastebin.com/di4r8DC6

This happens both entering and exiting gate of souls. Bescort will hang in this room and never complete, either failing to see the tunnel there and go into it, or failing to catch that it has successfully exited the tunnel and exit to hand control back to hunting-buddy. The result is that training-manager will hang forever in this room.

**Comment by Sarvatt** [comment]
are you using genie?

**Comment by proctophage** [comment]
Genie, why?

**Comment by Sarvatt** [comment]
fput movements break genie, its useful to know to dig in to it

**Comment by Kaesken** [comment]
I use genie but never had that issue when Damiza was hunting in that area.  I'm not sure what's different about mine, though.

**Comment by proctophage** [comment]
is there a workaround or something else I could do?

**Comment by proctophage** [comment]
It's a static travel time through the tunnel, right? Would it work to just have a pause here once it enters the tunnel long enough to get through it?

**Comment by proctophage** [comment]
https://pastebin.com/cgRZ0FwP
This happens in StormFront too, in the same room. So it's definitely not just a genie issue. This was from the most recent version of bescort today.

**Comment by proctophage** [comment]
I think this may be caused by a race condition. It goes to stand before the room description is loaded, so it seems like it waits forever because it doesn't know what room I'm in when trying to navigate after exiting the tunnel. I put a pause after the waitfor the looks for the line heralding your exit, so it has time to load the room description before moving on. The problem seems intermittent, so I'll let it run for a while before I make a pull request with that pause and close the issue.

**Comment by proctophage** [comment]
Nope. Doesn't work. Can someone please help?

**Comment by Tarhish** [comment]
I think I figured it out.  I'll submit a change

**Comment by proctophage** [comment]
That makes a lot of sense. It works. I could kiss you, Tashish.

**Comment by Tarhish** [comment]
I think this can be closed now?
