### ISSUE TITLE
wishlist: list both lich and dependency autostarts in ;help_me

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#3898]

**Comment by MahtraDR** [comment]
@asechrest This is a neat idea you might find interesting.

**Comment by asechrest** [comment]
I'll look at this next.

I also had a thought of moving the `help_me` functionality out of dependency and into a standalone script. Posed that to the original Lich devs and waiting to see if there is a downside I'm not thinking of.

**Comment by MahtraDR** [comment]
Closing as we now have help_me.lic dedicated. Due to lich framework issues, including the output of another script is tricky... and we haven't been able to get the autostarts listed.
