### ISSUE TITLE
Sling ammo from chipper weapons breaks combat-trainer

### ISSUE THREAD

**Issue by BardWyrrd** [rpherbig/dr-scripts#3900]
Sling ammo (in this case, cupcake crumbs) that come from chipper weapon activation, fail to match when combat-trainer shoots them from a sling.

< You fire a cupcake crumb at a yellow-bristled gremlin.  A yellow-bristled gremlin fails to evade.  The crumb flashes with a brilliant silver light and lands a demolishing hit (15/23) that pierces through the shoulder of the right arm and forces it and the arm to separate in a painful bloody display.
That would have stuck if there was anything left to stick to!
The cupcake crumb falls to the ground!
A yellow-bristled gremlin curses before sprawling to the ground, dead.
The swirling confines of malevolent darkness wane from about a yellow-bristled gremlin.
[You're adeptly balanced]
[Roundtime 1 sec.]

[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 36]
[combat-trainer: message: [You're nimbly balanced and in excellent position.]]
[combat-trainer: message: * A yellow-bristled gremlin feints low at you.  You dodge.  ]
[combat-trainer: message: You manage to deflect the final blast with your gold-on-niniam targe!]
[combat-trainer: message: You manage to get out of the way of the first arcing blast of electricity!]
[combat-trainer: message: Two blasts of electricity arc from it to you!]
[combat-trainer: message: A yellow-bristled gremlin gestures rudely at you.]
[combat-trainer: message: [You're nimbly balanced and in superior position.]]
[combat-trainer: message: * A yellow-bristled gremlin charges at you.  You evade.  ]
[combat-trainer: message: You feel fully attuned to the mana streams again.]
[combat-trainer: message: [You're nimbly balanced and in good position.]]
[combat-trainer: message: * A yellow-bristled gremlin bashes a chipped cudgel at you.  You evade.  ]
[combat-trainer: message: The yellow-bristled gremlin closes to melee range on you!]
[combat-trainer: message: Hydra Hex  (Indefinite)]
[combat-trainer: message: Shield of Light  (OM)]
[combat-trainer: message: Bless  (11 roisaen)]
[combat-trainer: message: Persistence of Mana  (OM)]
[combat-trainer: message: Major Physical Protection  (OM)]
[combat-trainer: message: Protection from Evil  (12 roisaen)]
[combat-trainer: message: Minor Physical Protection  (OM)]
[combat-trainer: message: Benediction  (OM)]
[combat-trainer: message: Osrel Meraud  (87%)]
[combat-trainer: message: Centering  (34 roisaen)]
[combat-trainer: message: A cage of shadowy tendrils coalesces around a yellow-bristled gremlin.]
[combat-trainer: message: A cage of shadowy tendrils coalesces around a yellow-bristled gremlin.]
[combat-trainer: message: The yellow-bristled gremlin closes to pole weapon range on you!]
[combat-trainer: message: You feel fully rested.]
[combat-trainer: message: Your formation of a targeting pattern around a yellow-bristled gremlin has completed.]
[combat-trainer: message: The swirling confines of malevolent darkness wane from about a yellow-bristled gremlin.]
[combat-trainer: message: [Roundtime 1 sec.]]
[combat-trainer: message: [You're nimbly balanced and overwhelming opponent.]]
[combat-trainer: message: The cupcake crumb lodges itself shallowly into the yellow-bristled gremlin!]
[combat-trainer: message: < You fire a cupcake crumb at a yellow-bristled gremlin.  A yellow-bristled gremlin attempts to evade.  The crumb flashes with a brilliant silver light and lands a powerful strike that punches a hole through the skin on its side, lightly stunning it.]
[combat-trainer: message: The second gremlin manages to pry its attacker loose and, snarling loudly, delivers a mighty kick that sends the gremlin flying through the air!  Both regain their feet with surprising quickness, eyeing each other warily.]
[combat-trainer: message: A yellow-bristled gremlin suddenly launches itself at a yellow-bristled gremlin, attempting to wrest a chipped cudgel from its grasp.  The two gremlins tumble to the ground where they wrestle ferociously, biting and clawing at each other.]
[combat-trainer: message: A yellow-bristled gremlin begins to wave its arms in a magical fashion, focusing on you!]
[combat-trainer: message: You feel fully attuned to the mana streams again.]
[combat-trainer: checked against [/isn't loaded/i, /There is nothing/i, /But your/i, /you (fire|poach|snipe) an? (?:.*\s)?(arrows?|bolt|shard|rock|sphere|clump|coral|fist|holder|lump|patella|pellet|pulzone|quadrello|quill|stone|stopper|verretto).* at/i, /I could not find/i, /with no effect and falls to the ground/i, /Face what/i, /How can you (poach|snipe)/i, /you don't feel like fighting right now/i, /That weapon must be in your right hand to fire/i]]
[combat-trainer: for command shoot]

**Comment by MahtraDR** [comment]
This is include today already.
