### ISSUE TITLE
theurgy error when doing research

### ISSUE THREAD

**Issue by Bedonder** [rpherbig/dr-scripts#3904]
When I run crossing-training I get the following error;

[theurgy]>buy oil

You decide to purchase the oil, and pay the alchemist Chizili 125 Kronars.
The alchemist Chizili hands you your oil.

[theurgy]>research status

You believe that you're 11% complete with a portion of research about Utility Patterns Research.  You estimate that you will complete it a few minutes from now.

--- Lich: error: undefined local variable or method `find_current_project' for #<TheurgyActions:0x0000000007a9a928>
Did you mean?  find_pcs_prone
	theurgy:923:in `complete_or_interrupt_research'
	theurgy:353:in `buy_single_supply'

--- Lich: theurgy has exited.

I have Theurgy and magic research in crossing-training. It the script keeps going but I end up with a sack full of unused oil.

**Comment by rpherbig** [comment]
It looks like the `find_current_project` array is not defined. I combed through the history and can't find where it was ever defined. I don't see how this ever worked in `theurgy`.

That said, the fix looks straightforward. I think both instances of `find_current_project` should be replaced with `project_match`. Could you give that a try and see if it works?

**Comment by Bedonder** [comment]
That did the trick. It works when you replace that. It cancels research and then makes holy oil.
Thanks.
