### ISSUE TITLE
Repair Suggestion

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#3908]
Is there any way that the repair script can do the repair all option rather than individual items?  We're leaving us more vulnerable to folks stealing our coin with us just standing there waiting on our stuff or we get stolen from before we can get all our stuff repaired.

The command works everywhere as far as I know but it's "ask [repair shop owner] for repair all" and it will take ALL worn armor plus 1 weapon in your right hand.  Of course the rest of our weapons will have to be given individually but maybe the repair all for worn gear would make it less opportunity to steal all our coins while we're standing there handing everything one by one.

**Comment by rpherbig** [comment]
We've discussed it before - for example, #399. There's no harm in supporting `repair all`, but no one has taken the time to implement it. It's definitely more complicated than the current logic and I'm not sure it would fix the real problem: stealing.

We could consider something like #3530 - finding something else to do while waiting on repairs.

**Comment by Kaesken** [comment]
Ahh, yeah, I think maybe doing the crossing_training or crafting while the repairs would be a good idea.  I'm going to go ahead and close this since it's been mentioned elsewhere.  I'll try to skim better. lol

I'm still learning the language but maybe I can help once I do.  I'm also wanting to try to implement the Prydaen gods in favors.lic.  That's already going to be tricky as hell tho lol
