### ISSUE TITLE
Bescort Ways Death

### ISSUE THREAD

**Issue by khrispyb** [rpherbig/dr-scripts#3909]
Straight up went the wrong way and killed me...

You sense a constant flow of Lunar energy around you, twisting and weaving itself into a constantly moving web.  You reach out into the maze and attempt to orient yourself toward the only two landmarks you can sense.
You believe the center of the microcosm is to the northwest.
You believe the end of the conduit lies northeast.
Roundtime: 7 sec.
R> 
One of the beams of light twists suddenly, bringing the burning ribbon of energy into your path!
You effortlessly maintain your place among the shifting streams of mana.
R> 
[bescort]>northwest

You move across the unreal landscape, navigating by the streams of Lunar energy.

[Astral Plane, Grey Expanse]
You can see nothing but grey light in every direction.  The light is composed of a single soft color, lacking any sense of depth or texture.  You cannot feel any ground below you and it is impossible to tell where the landscape ends and the horizon begins, or if such a distinction is even drawn here.
Obvious exits: none.

**Comment by khrispyb** [comment]
So I think bescort needs to re-perceive here, right?

**Comment by rpherbig** [comment]
@jandersson any ideas?

**Comment by rcuhljr** [comment]
There's a chance to expanse on any movement I thought, I don't think `One of the beams of light twists suddenly, bringing the burning ribbon of energy into your path!` is a ways shift message but someone would need to loiter in the ways chain perceiving before and after that message to be sure.

**Comment by khrispyb** [comment]
I'll experiment with it if I see that message again, thanks - we can close
this out then

**Comment by jandersson** [comment]
That should just be flavor text. The key thing to track is your balance which is based on your harnessed mana. Its my experience that expanse is random, like rcuhljr said. Once youre in there there's also a very small chance of escaping.
