### ISSUE TITLE
Make a rossman's landing/haven training options

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#391]
(12:40:54 PM) Zook: climb, bank, tannery, gem shop, safe room, auto empath
(12:40:57 PM) Zook: any others I need to get?
(12:57:53 PM) Zook: Athletics #jant river
7651
7650
7649
7648
7647
7633

Bank #Riverhaven teller
7953 
Tannery #Riverhaven tanner
7956
Gem Shop #Riverhaven gem shop
7955
Safe Room #Rossmans Courtyard

Auth Empath #Riverhaven empath
8720

(1:00:24 PM) Zook: safe room 7695 i forgot to put that
(1:01:37 PM) Zook: tanner update for rossmans is 770
(1:01:40 PM) Zook: 7702

**Comment by rpherbig** [comment]
Does `go2` work between all of those?

**Comment by rpherbig** [comment]
What about repair facilities?

**Comment by rpherbig** [comment]
And crafting facilities?

**Comment by xtremenerdrage** [comment]
safe room 7695 tanner in rossmans 7702 haven repair shop 8737 
Crafting facilities are in haven but not sure about an appraisal place, by this time you should be using quick app in combat though

**Comment by rcuhljr** [comment]
I think this may be a lower priority since he's training in Fang cove now I believe.
