### ISSUE TITLE
Devotion draining for f2ps running Theurgy constantly in CT

### ISSUE THREAD

**Issue by Maledar** [rpherbig/dr-scripts#3918]
So I seem to encounter this problem with f2ps clerics with the drain being so slow and CT running constantly running Theurgy pretty much drains your devotions. 

If there's a way we could toggle the communes off? I've been using this one in a before/after 25 minute hunt and brought my devotion back up from 2/16 to 13/16 in one night

**Comment by Maledar** [comment]
https://pastebin.com/fftq47FY

**Comment by MahtraDR** [comment]
@rpherbig Can close this one too. This isn't an issue today.
