### ISSUE TITLE
[athletics] Breaks when you are too injured to play instrument

### ISSUE THREAD

**Issue by kara-ryli** [rpherbig/dr-scripts#3919]
When you're attempting athletics but are too injured to play your zills, athletics invokes ;safe-room which creates two instances of ;go2, which causes a bunch of movement failures.

Log attached.

[athletics.log](https://github.com/rpherbig/dr-scripts/files/3668035/athletics.log)

**Comment by Sarvatt** [comment]
walt_to should probably kill go2 at the start, its the cause of it

**Comment by MahtraDR** [comment]
This is a very old issue now. Closing. Would be happy to revisit this request as fresh if it comes up again.
