### ISSUE TITLE
Stance lower or off

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#392]
Option to set stance inside of .yaml or even turn off setting stances so we can set manually.

**Comment by rpherbig** [comment]
@xtremenerdrage You can force a stance for a given weapon skill via the `stances` setting. Is that what you are looking for?

**Comment by xtremenerdrage** [comment]
correct me if i'm wrong, that sets maxed out stances. Would it be possible to have an option to set a custom stance ie. 80 20 80 - my example would be gremlins, using mostly evasion and shield to defend but keeping 20 in parry so it still receives exp

**Comment by rcuhljr** [comment]
Possible fix in place, waiting on user testing.

**Comment by xtremenerdrage** [comment]
No issues running last night
