### ISSUE TITLE
workorder turn in script for ;crafted stuff

### ISSUE THREAD

**Issue by izawwlgood** [rpherbig/dr-scripts#3921]
With the caravan route update, I find my backpack is getting full of blankets and chokers I'm making along the way. This is neat! However, it's annoying to have to manually spam the society masters for a WO that'll take what I want.
I propose a workorder turn in script that has the following functionality, in order of awesomeness - 
1. ;turnin tailoring "knitted blanket" - will head to the nearest Outfitting society and find the master and spam ASK [master] FOR [DIFFICULTY] TAILORING WORK until `knitted blanket` comes up, and then it'll bundle up as many blankets as it takes to fill the WO and GIVE [master].
2. Will check my backpack for indicated items (knitted blanket, or balsa choker or whatever), and if there are >5 of them in the container, it'll run to the nearest appropriate society and do the above.

**Comment by Tarhish** [comment]
I think this can be closed now?

**Comment by izawwlgood** [comment]
As far as I know this hasn't been added? I'm using a sf script that does
this

**Comment by Tarhish** [comment]
I made ;trade do this as a part of closing out, and I thought you were using that.  Do you have something else that was generating large quantities of crafted goods you needed this for, or was ;trade not behaving?

**Comment by izawwlgood** [comment]
I didn't realize trade closeup was doing this. Can we manually set the
items to look for?

**Comment by Tarhish** [comment]
Yeah, or rather, it would be more accurate to say if you manually set the items to make then it'll automatically turn them in throughout the run, whenever you stop at a society with more than 4 of that item competed. Check out the trader tutorial on the wiki and I put in an example.

**Comment by izawwlgood** [comment]
Gotcha thanks! Yeah good to close!
