### ISSUE TITLE
Sigil Location Crowd Sourcing

### ISSUE THREAD

**Issue by GreyhallowDR** [rpherbig/dr-scripts#3937]
Has the idea been floated to crowd source mapping sigil locations with Lich? I'm assuming there is a way to have scripts report back info to a central database right?

**Comment by rpherbig** [comment]
Yes, that's how stealing works today. W could do something similar for
sigils.

**Comment by GreyhallowDR** [comment]
exactly, something like base-stealing.yaml file

**Comment by Sarvatt** [comment]
i think E would need to create a new db on firebase for it, is there enough bandwidth for that? we were hitting the free limits but not sure how it is after disabling the trader shop tracking

**Comment by Sarvatt** [comment]
the base stealing yaml file is manually populated from the db on firebase that gets updated in real time. steal.lic updates the data. it would take someone who cares a lot of work to do this, just a heads up it wont be easy if you want to implement it :)

**Comment by rpherbig** [comment]
I'm pretty sure I can make the new fire base data store if someone wanted
to run with this.

**Comment by MahtraDR** [comment]
Closing as resolved by #5562
