### ISSUE TITLE
Playing instruments during study-art

### ISSUE THREAD

**Issue by LuckyThiefDR** [rpherbig/dr-scripts#3941]
I think ;performance should run during this script, but it looks like a condition on line 26 prevents it while crossing-training is running.

**Comment by jayRyan24** [comment]
So it doesn't hinder the study when it's running? Like can you play and instrument while studying? They don't interfere? If not, I don't think this is an issue at all and can easily be removed. A log of it working together would be good.

**Comment by MahtraDR** [comment]
@rpherbig We can close this, study-art calls performance today.
