### ISSUE TITLE
Boomerangs / Return thrown items

### ISSUE THREAD

**Issue by Maledar** [rpherbig/dr-scripts#3948]
Is there an easy way to add the match that it already is in your hand? Or is there a reason it was left like this? Or should I just not use a boomerang? 

It'll come back in the hand, try to pick it up then pause for a few seconds because it doesn't recognize the command of it already being in your hand, pastebin below. 

https://pastebin.com/z8pkFgeC

**Comment by MahtraDR** [comment]
Hi, sorry for the delay here.

If it works like bound weapons, you can try using `:bound: true` in your gear sets, and that should work. This issue is quite old now though, so closing it out for now. Happy to revisit this issue as fresh if it's still happening today.
