### ISSUE TITLE
Log out when a construct attacks

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#395]
I'm envisioning `crossing-training` or `afk` logging out when a construct is identified in the room.

We may also want to investigate getting ahold of long names to match glass construct, not any construct.

**Comment by rcuhljr** [comment]
I'd suggest beeping and giving a 10-15 second loud warning to kill afk if you don't want to exit, some may be dragging people out of construct rooms etc. also, don't exit if there's not still a construct in the room at the end of the timer.

**Comment by rpherbig** [comment]
Is this a duplicate of #327?

**Comment by rcuhljr** [comment]
the could probably be combined down.
