### ISSUE TITLE
;combat-trainer and ;healme conflict over empath_healing

### ISSUE THREAD

**Issue by kara-ryli** [rpherbig/dr-scripts#3950]
This ones's tricky, and without an obvious solution, so please bear with me; I'm happy to help fix this with some thoughtful direction. Basically:

**empath_healing**
```
empath_healing:
  VH:
  - 10
  HW:
  - 10
  HS:
  - 10
  HEAL:
  - 20
```

`;healme`,  will use these settings to spam the `HEAL` spell on you repeatedly to self-heal unless you specify a bleeder you want to keep. Using heal is a bit more time efficient way to self heal. As an aside, `empath_healing` doesn't support configurable prep time, which could really juice `;healme`'s speed.

`combat-trainer` will use these settings to spam the `HEAL` spell on you if you have _any_ wounds and don't have FOC:

```rb
echo('Healing') if $debug_mode_ct
if @wounds.any?
  if @empath_spells['FOC']
    data = { 'abbrev' => 'foc', 'mana' => @empath_spells['FOC'].first, 'cambrinth' => @empath_spells['FOC'][1..-1] }
  elsif @empath_spells['HEAL']
    data = { 'abbrev' => 'heal', 'mana' => @empath_spells['HEAL'].first, 'cambrinth' => @empath_spells['HEAL'][1..-1] }
  end
  @wounds = {}
  prepare_spell(data, game_state, true) if data
end
```

...this is problematic because it both clobbers vitality healing (which, in my current situation, is more of a problem than minor scratches) and drains mana pretty hard.

So ideally I'd like to have HEAL not in my `empath_healing` for `;combat;`, but  in it for `;healme`. There are two workarounds:

* Use a waggle set for `;healme` instead
* Override `empath_healing` in hunting YAML files

Both of these work at the moment, but the former has some discoverability challenges and the latter requires double management of mana values.

So I'd like to help make this a little cleaner; solutions could be:

* Leave as-is
* Change the heal logic of `;combat`
* Remove empath_healing from `;healme`
* A fourth thing?

Curious on opinions.

**Comment by Tarhish** [comment]
I don't really like the idea of changing settings at this point unless it keeps the old ones valid for the time being.  Still, I think there's at least two things to do here. Adjust combat-trainer and later adjust healme, which definitely isn't perfect at low circles.

Currently combat-trainer will cast VH if Regeneration is active and vit is low, but it doesn't do the same if HEAL is up.  That should change.

Second, it shouldn't spam HEAL if HEAL is already running.  Both of these are easy to change.

As for healme, I got started a long time back with making it so ;healme would keep HEAL up and continue to cast HW and HS while avoiding places that HEAL had cleared up.  It was tricky, but I might be able to make a better go of it later

**Comment by MahtraDR** [comment]
Closing as wontfix. This hasn't come up as in issue in years...
