### ISSUE TITLE
setting up Buff upkeep during mining

### ISSUE THREAD

**Issue by aemenash** [rpherbig/dr-scripts#3955]
Would there be a way to have mining manager or mining buddy set up to use mining buffs and upkeep the buffs during mining? buffs like wolf scent spell or even a line to use the trader speculate luck ability as cooldown permits?

**Comment by rpherbig** [comment]
It shouldn't be hard to have one of the mining scripts call `buff` and look for a spell set.

**Comment by aemenash** [comment]
I’m really really new to DR and Lich but thought it would be a cool thing, I have NO idea how easy or hard it would be to get that sort of thing added in or not but thought the idea worth posting to the geniuses that are making these scripts lol 😊

Sent from Mail for Windows 10

**Comment by rpherbig** [comment]
Huh, it looks like this may have already been done in #2672

Have you tried adding a buff set called `mining`?

**Comment by Tarhish** [comment]
There's a nuance to it and I forgot about the fact I wanted to fix this.  The mining waggle is called when you start mining, but only at the start of the process.  Buffs wear off as you move room to room, especially when you might spend 15 minutes in one of them.

I was annoyed by this back when I needed the buff to mine successfully, but I didn't do much updating then, and forgot about it.  I can make a change for this.

**Comment by rpherbig** [comment]
Fixed in #3958
