### ISSUE TITLE
AEG and MOF support

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#396]
AEG and MOF support for buffs would be awesome

**Comment by rpherbig** [comment]
I took a look at this and see a few problems:

- You must have both hands free to `invoke jar` (the ritual focus for AEG, which my WM has). That means you'd have to break your summoned weapon, then resummon it after casting.
- Even if you did empty your hands, when you invoke the focus there is a 20 second roundtime. That's hefty even by summoned weapon standards. Even if you retreat before invoking, mobs are going to engage with you and get in some hits.
- (Assuming you don't have the non-consumed focus and feat) `combat-trainer` doesn't have a good way to make sure you have a focus.

**Comment by xtremenerdrage** [comment]
It's 20 seconds of rt, I agree, at this point it doesn't make any sense to add it in. 
Maybe if Simu changes the rt or adds something to make it feasable in combat we'll be able to add something, If the rt was even down to 15 seconds we could probably use it.

Let's hope Simu makes these usable without leaving combat 
Thanks

**Comment by xtremenerdrage** [comment]
I mean I guess technically if you had shield and evasion and AEG/MOF DID NOT drop it could potentially be useable, what do you think?

**Comment by rpherbig** [comment]
I think this should wait until we have a pre-combat preparation room (see #167).

**Comment by xtremenerdrage** [comment]
I tested this in combat with it currently ON and this worked.
you can have your weapon out, get jar, prep aeg, stow weapon, invoke jar, get weapon, RELEASE AEG, cast and it will effectively have aeg on the entire time.

**Comment by xtremenerdrage** [comment]
I would probably use it like this where the spell never actually falls off, to be safe I would have it recast anywhere from 1-4 rois maybe?

**Comment by rcuhljr** [comment]
I'm going to add ritual support in combat anyways for empaths, so it's going to happen at some point. We waste more time with appraisal then 20 second (which is only like 12~ seconds of combat time after retreating). I'm not that worried about implementing this.

**Comment by rcuhljr** [comment]
added
