### ISSUE TITLE
Sigilscholarship loop

### ISSUE THREAD

**Issue by khrispyb** [rpherbig/dr-scripts#3964]
Hi 
Running sigilscholarship and it gets stuck in Shard/SteelClaw Clan and loops endlessly...  see below

[Steelclaw Clan, Jainder's Walk]
Massive ironwood timbers creak as the cobblestoned street gives way to the broad wooden ramp leading up to the Lamentine bridge.  Swallows, their nests safely tucked up under the bridge supports, dart gracefully hither and fro around the beams and out across the walls to the rich farm lands and dinner.  
Obvious paths: south.

> 
[go2: travel time: 0:00:19]

--- Lich: go2 has exited.

> 
[sigilscholarship: Failed to navigate to room 2880, attempting again]

[sigilscholarship: In an unknown room, manually attempting to navigate to 2880]

[sigilscholarship: failed to find a matching room]

[sigilscholarship]>perceive sigil

You clear your mind and begin searching the area for subtle lights and shadows hiding mathematical secrets of a deeper order.
Roundtime: 6 sec.
R> 
R> 
[sigilscholarship]>perceive sigil

[DRPrime]-DR:Gigondas: "Was he sent by the High Command?"
You close your eyes and turn to a random direction.  Quickly opening them, you hunt for previously-hidden details in the area.
In your mind's eye you see the definition of an abolition sigil before you.
Roundtime: 10 sec.
R> 
R> 
R> 
[sigilscholarship]>perceive sigil

> 
Left and right you crane your head to observe the intricacies of your surroundings.
Roundtime: 8 sec.
R> 
R> 
[sigilscholarship]>perceive sigil

Left and right you crane your head to observe the intricacies of your surroundings.
Roundtime: 9 sec.
R> 
[DRPrime]-DR:Critter: "okay, the stones stay pressed for 2 minutes"

R> 
[sigilscholarship]>perceive sigil

Left and right you crane your head to observe the intricacies of your surroundings.
Roundtime: 8 sec.
R> 
R> 
R> 
[DRPrime]-DR:Critter: "timing is key here then lol"

R> 
R> 
[DRPrime]-DR:Kalinandra: "so press like at the moment they go down and you might make it"

[sigilscholarship]>perceive sigil

Back and forth you walk through the area while taking note of its more unique aspects.
Roundtime: 10 sec.
R> 
R> 
R> 
[sigilscholarship]>perceive sigil

Back and forth you walk through the area while taking note of its more unique aspects.
Roundtime: 9 sec.
R> 
R> 
R> 
R> 
R> 
[sigilscholarship]>perceive sigil

Left and right you crane your head to observe the intricacies of your surroundings.
Roundtime: 8 sec.
R> 
R> 
R> 
R> 
[sigilscholarship]>perceive sigil

Whorls of dust upon the ground catch your eye.  You get closer to study them in more detail.
Subtleties in the surroundings reveal themselves as the origins of a metamorphosis sigil.
Roundtime: 9 sec.
R> 
[sigilscholarship: In an unknown room, manually attempting to navigate to 2841]

[sigilscholarship: failed to find a matching room]

R> 
Your Psychic Shield wears off.
R> 
R> 
[sigilscholarship]>perceive sigil

You recall having already identified the metamorphosis secondary sigil in this area.  However, it seems likely the sigil's quality and precision could be improved.
Roundtime: 10 sec.
R> 
[sigilscholarship: In an unknown room, manually attempting to navigate to 2856]

[sigilscholarship: failed to find a matching room]

R> 
R> 
[sigilscholarship]>perceive sigil

You recall having already identified the metamorphosis secondary sigil in this area.  However, it seems likely the sigil's quality and precision could be improved.
Roundtime: 9 sec.
R> 
[sigilscholarship: In an unknown room, manually attempting to navigate to 2805]

[sigilscholarship: failed to find a matching room]

R> 
R> 
R> 
[sigilscholarship]>perceive sigil

You recall having already identified the metamorphosis secondary sigil in this area.  However, it seems likely the sigil's quality and precision could be improved.
Roundtime: 10 sec.
R> 
[sigilscholarship: In an unknown room, manually attempting to navigate to 2817]

[sigilscholarship: failed to find a matching room]

R> 
R> 
[sigilscholarship]>perceive sigil

You recall having already identified the metamorphosis secondary sigil in this area.  However, it seems likely the sigil's quality and precision could be improved.
Roundtime: 10 sec.
R> 
[sigilscholarship: In an unknown room, manually attempting to navigate to 2803]

[sigilscholarship: failed to find a matching room]

**Comment by MahtraDR** [comment]
Closing this. We don't have this script in our repo.
