### ISSUE TITLE
safe-room.lic & Fang Cove

### ISSUE THREAD

**Issue by cfrisby77** [rpherbig/dr-scripts#3966]
Update safe-room.lic  line 45 to:

      Flags.add('healthy', 'do anything more for you now', 'Dokt waves a large hand at you', 'Dokt gives you a quick glance', 'go have yourself a birthday party', 'you are well', 'have other patients', 'you look fine and healthy', 'A little rest and exercise', 'There is nothing I can do for you', 'Up and out', 'What are you doing lying there with the wounded', 'Come along.  Leave room for the others.', "I think you don't really need healing")

**Comment by cfrisby77** [comment]
Added 'I can't do anything more for you now',  to   Flags.add('healthy' section and testing

**Comment by rpherbig** [comment]
Closed in #3971
