### ISSUE TITLE
Combat-Trainer verb issue

### ISSUE THREAD

**Issue by darkxion** [rpherbig/dr-scripts#3974]
Combat-Manager does that 15 second hang whenever I take a throwing dagger or knife out of, or put back into, my bandolier. Is there a way I can add the proper verb to the script?

[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 8]
[combat-trainer: message: [You're solidly balanced with opponent in strong position.]]
[combat-trainer: message: The throwing dagger slides easily out of the blue bandolier.  Strangely, the bandolier doesn't seem any less full.]
[combat-trainer: checked against [/^You .*(?i-mx:throwing.*\bdagger)/, /^You get.*dagger/i, /^What were you referring/i, /But that is already/i, /You are already/i]]
[combat-trainer: for command get my throwing.dagger]

This is the info from stowing or getting dagger.
The throwing dagger slides easily out of the blue bandolier.  Strangely, the bandolier doesn't seem any less full.

The throwing dagger slides easily into the blue bandolier.  Strangely, the bandolier doesn't seem any fuller.

**Comment by Tarhish** [comment]
Yeah, this is equipmanager being a little too specific with its verbs.  Do you happen to have the other error message for when it tries to stow the dagger and hangs?

**Comment by darkxion** [comment]
Yep!

[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 27]
[combat-trainer: message: [You're solidly balanced with opponent in good position.]]
[combat-trainer: message: * Moving inexpertly, an Endrus serpent bites at you.  You barely block with a lumium round sipar.  ]
[combat-trainer: message: [You're solidly balanced and opponent has slight advantage.]]
[combat-trainer: message: * Inexpertly, an Endrus serpent bites at you.  You barely block with a lumium round sipar.  ]
[combat-trainer: message: [You're solidly balanced with opponent in better position.]]
[combat-trainer: message: * Moving with great skill, an Endrus serpent bites at you.  You barely fail to block with round sipar.  The teeth lands a grazing strike to your left hand.]
[combat-trainer: message: An Endrus serpent slithers in.]
[combat-trainer: message: [You're solidly balanced and opponent has slight advantage.]]
[combat-trainer: message: * Trying inexpertly, an Endrus serpent bites at you.  You barely block with a lumium round sipar.  ]
[combat-trainer: message: [You're solidly balanced and opponent has slight advantage.]]
[combat-trainer: message: * With amateurish style, an Endrus serpent slices wide at you.  You slap away little of the teeth with an iron-banded parry stick with brown leather straps.  ]
[combat-trainer: message: Your feet are still soaked.]
[combat-trainer: message: [You're solidly balanced with no advantage.]]
[combat-trainer: message: * Attacking poorly, an Endrus serpent bites at you.  You barely block with a lumium round sipar.  ]
[combat-trainer: message: You feel fully rested.]
[combat-trainer: message: [You're solidly balanced with no advantage.]]
[combat-trainer: message: * With inept movements, an Endrus serpent bites at you.  You slap away little of the teeth with an iron-banded parry stick with brown leather straps.  ]
[combat-trainer: message: [You're solidly balanced with no advantage.]]
[combat-trainer: message: * With poor timing, an Endrus serpent bites at you.  You repulse little of the teeth with an iron-banded parry stick with brown leather straps.  ]
[combat-trainer: message: [You're solidly balanced and opponent has slight advantage.]]
[combat-trainer: message: * Moving poorly, an Endrus serpent slices wide at you.  You barely block with a lumium round sipar.  ]
[combat-trainer: message: The throwing dagger slides easily into the blue bandolier.  Strangely, the bandolier doesn't seem any fuller.]
[combat-trainer: checked against [/You put .*dagger/i, /You .* unload/i, /close the fan/i, /You easily strap/i, /You don't seem to be able to move/i, /You secure/i, /is too small to hold that/i, /You hang/i]]
[combat-trainer: for command stow my throwing.dagger]

**Comment by darkxion** [comment]
Now that I know which script - equipmanager - controls that, I'll try to adjust it. Shouldn't be too difficult.

**Comment by Tarhish** [comment]
My guess, (though I can't tell without a copy of that bandolier) is that we'd need to adjust 

`matches: [/^(You|The) .*#{item.short_regex}/, "^You get.*#{item.name}", '^What were you referring', 'But that is already', 'You are already'],`

in the stowed: section

and for stowing the daggers the final else in stow_weapon should be

```
    else
      stow_helper("stow my #{weapon.short_name}", weapon.short_name, "(You|The) .*#{weapon.name}", 'You .* unload', 'close the fan', 'You easily strap', "You don't seem to be able to move", 'You secure', 'is too small to hold that', 'You hang')
    end
```

Personally, I think any message that begins with You or The and has the name of the weapon in it is fine for a bput accept message.  You would have to try it and see if it solves your problem, or if you've already got a different solution that works too. :-)

**Comment by darkxion** [comment]
tap
You tap a midnight blue bandolier embroidered in black with the stalking panther of Damaris that you are wearing.

appraise
There is a soft shimmer around the blue bandolier, as if the very fabric were woven with magic.

The blue bandolier is a container.

**Comment by Tarhish** [comment]
If you want to try it with those changes, I have them here

https://raw.githubusercontent.com/Tarhish/dr-scripts/equip-dagger/equipmanager.lic

You'd have to replace the file, ;kill dependency, ;dependency, then start up combat-trainer to see if it behaves correctly.

**Comment by darkxion** [comment]
Didn't work, but I think I have a general idea of what you mean. I'll fiddle with it! Thanks so much!

Do you know if there is a way to make combat-trainer stow my ammo that lands on the ground after firing? It always tries to "stow my quadrello" but it's on the ground so the script can't find what I'm referring to.

**Comment by Tarhish** [comment]
So it's possible, based on what I'm hearing, that if you have wield: true set for that dagger, then sheath it in the bandolier, that it will start getting seen as normal.

**Comment by darkxion** [comment]
That fixed the hang when wielding it, but not when sheathing it. I'm OK with that, one less hang is great. Thanks! So much to learn, it seems. haha

**Comment by darkxion** [comment]
OK, so, I know why changes to equipmanager.lic don't work. Every time that I log in, it reverts back to the stock file. Is there a way to turn that off?

**Comment by Sarvatt** [comment]
;e toggle_developer_mode but you have to do it on all characters

**Comment by darkxion** [comment]
That worked, thanks!

**Comment by Tarhish** [comment]
I'm more than willing to help get a fix into the live drscripts, but it's 100% a messaging problem.   I can't guess how to fix it without seeing what the new messages are.

**Comment by darkxion** [comment]
Using these messages from "get my dagger", and "stow my dagger", I edited the script and it's working now without hangs. I don't know if there are other relevant messages, as I'm very new at this, but these are what I used.
The throwing dagger slides easily out of the blue bandolier. Strangely, the bandolier doesn't seem any less full.
The throwing dagger slides easily into the blue bandolier. Strangely, the bandolier doesn't seem any fuller.
This part-
      stowed: {
        verb: 'get',
        matches: [/^You .*#{item.short_regex}/, "^You get.*#{item.name}", 'slides easily out', '^What were you referring', 'But that is already', 'You are already'],
        failures: ['You get', /But that is already/],
        failure_recovery: proc { |noun| bput("stow my #{noun}", 'You put', 'slides easily into ', 'But that is already in') },
        exhausted: ['What were you referring']

and this part-
      stow_helper("sheath my #{weapon.short_name}", weapon.short_name, 'Sheathing', 'You sheathe', 'You .* unload', 'close the fan', 'You secure your', 'You slip', 'You hang', 'You strap', "You don't seem to be able to move", 'You easily strap', 'is too small to hold that', 'slides easily into',  'With a flick of your wrist you stealthily sheathe')
    elsif weapon.worn
      stow_helper("wear my #{weapon.short_name}", weapon.short_name, 'You sling', 'You attach', 'You .* unload', 'You slide', 'You place', 'close the fan', 'You hang', 'You spin', 'You strap', 'You put', 'You carefully loop', "You don't seem to be able to move")
    elsif !weapon.tie_to.nil?
      stow_helper("tie my #{weapon.short_name} to #{weapon.tie_to}", weapon.short_name, 'You attach', 'close the fan', 'you tie', 'You are a little too busy', "You don't seem to be able to move")
    elsif weapon.transforms_to
      stow_helper("#{weapon.transform_verb} my #{weapon.short_name}", weapon.short_name, weapon.transform_text)
      stow_weapon(weapon.transforms_to)
    else
      stow_helper("stow my #{weapon.short_name}", weapon.short_name, "You put .*#{weapon.name}", 'You .* unload', 'close the fan', 'You easily strap', "You don't seem to be able to move", 'You secure', 'is too small to hold that', 'slides easily into', 'You hang')
    end
  end

**Comment by Tarhish** [comment]
Awesome, and yeah, that would do it.  While we're here, though, what does it look like when you SHEATH into it?  Since you mentioned WIELD works fine, might as well add that in for WIELDING to and from it?

**Comment by darkxion** [comment]
sheath dagger
The throwing dagger slides easily into the blue bandolier.  Strangely, the bandolier doesn't seem any fuller.

Wield is the only one that looks different from what i've seen, but I think that is already in the script.

wield dagger
You draw out your throwing dagger from the blue bandolier, gripping it firmly in your right hand

**Comment by Tarhish** [comment]
Thanks :-)  I think that's everything we could use.

**Comment by Tarhish** [comment]
I made a couple tiny changes to make the messaging less like to trip on something unintended.  Let me know if it somehow breaks it for you and I'll move it back towards what you had.
