### ISSUE TITLE
Crossing-repair doesn't repair gear if one has debt

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#3977]
I did some training and forgot to pay my debt.  Then I noticed that crossing-repair does not go back to bank to obtain more coin if needed for repair. 

[crossing-repair]>withdraw 1 platinum

The clerk counts out 1 platinum Kronars and hands them over, making a notation in her ledger.
A burly Gor'Tog taps you on the shoulder and says, "Gabellia D'emibenit, roight?  I'm Barg, from da Debt Collector's Office.  I tink y'have sometin' I been sent t' collect."
With a resigned sigh, you hand your coins to the collector.  "Dis ain't all da debt, but dis is enough for now.  You still owe 89,237 Kronars dough - don't forget."  The collector grins and steps aside.
--- Lich: performance active.

--- Lich: go2 active.

--- Lich: 'textsubs' has been stopped by go2.

[go2: ETA: 0:00:11 (59 rooms to move through)]

[go2]>out

You wander out.
[First Provincial Bank, Lobby]
Marble tiled floors covered with heavy rugs and walls of polished jasper that gleam a cool blue mark this bank as solid and secure (and expensive).  An official money-changing booth is to one side and a row of tellers windows faces you.  Several guards, armed and armored, stand ready for trouble of any sort.  Near the tellers stands a table of fine wood for those who need to do some writing.  You also see a money-changer's booth, a bucket of viscous gloop and the tellers' windows.
Obvious exits: out.

****Walk to Randals

[Randal's Leather Repair, Work Room]
Mounds of leather and hides find themselves stacked in almost every corner of this small work area.  Wooden boxes of metal rings, studs and rivets claim the remaining space, prompting Randal to use two rolls of padding as a make-shift seat because there is no further room for them.  Behind a wood counter Randal sits smiling to himself as he works on a leather breastplate.  A large hide tacked to the wall has something written on it.  You also see a large waste bucket.
Obvious exits: west.

Room Number: 1544

[go2: travel time: 0:00:09]

You feel fully rested.

--- Lich: go2 has exited.

[crossing-repair]>remove my parry.stick

You loosen the straps securing your parry stick and remove it.

[crossing-repair]>give my parry.stick to Randal

Randal looks over the stick and says, "That will cost 50,160 Kronars to repair.  Just give it to me again if you want, and I'll have it ready in 10 roisaen."

[crossing-repair]>give Randal

Randal smiles at you and says, "You will need more coin if I am to be repairing that!"

[crossing-repair]>wear my parry.stick

You strap the parry stick along your right forearm, settling it into a comfortable position.

[crossing-repair]>remove my notched.sleeves

You remove some notched wood drake-bone sleeves from your arms.

[crossing-repair]>give my notched.sleeves to Randal

Randal looks over the sleeves and says, "That will cost 54 Kronars to repair.  Just give it to me again if you want, and I'll have it ready in 1 roisaen."
You continue playing on your thin-edged zills.

[crossing-repair]>give Randal

Randal smiles at you and says, "You will need more coin if I am to be repairing that!"

[crossing-repair]>wear my notched.sleeves

You attach some notched wood drake-bone sleeves to your arms.

*******Walked to Catrox's

[Catrox's Forge, Entryway]
The forge of Catrox the Dwarf is known throughout the lands.  Here mundane metal is transformed into tools, and weapons, damaged armor and shields are made whole again.  This entryway is covered by a tin roof, with no walls, in the hope of letting some air into the smoky, noisy and sweltering compound.  The ringing of metal on metal, the sputtering of cinders and slag, the hissing of steel meeting water, all are audible from within.  You also see Repairman Catrox, a large sign, a sooty swinging door and a large waste bucket.
Obvious exits: out.

Room Number: 19093

[go2: travel time: 0:00:08]

--- Lich: go2 has exited.

A chorus of trilling mews heralds the arrival of a mischievous snow white kitten with taffelberry-stained paws.

[crossing-repair]>remove my ring.cap

You take a damite ring cap off your head.

[crossing-repair]>give my ring.cap to Catrox

You continue to focus on conquering a quiet sonata as the complex rhythm wafts from your thin-edged zills.
Catrox looks over the cap and says, "That will cost 267 Kronars to repair.  Just give it to me again if you want, and I'll have it ready in 1 roisaen."

[crossing-repair]>give Catrox

An argument over who is touching whom carries in from the back room.  Catrox cups his head in work worn hands and sighs, "I need a vacation."
Catrox mutters, "You will need more coin if I am to be repairing that!"

[crossing-repair]>wear my ring.cap

You put a damite ring cap on your head.

[crossing-repair]>remove my ring.mask

You remove a damite ring mask from your nose.

[crossing-repair]>give my ring.mask to Catrox

Catrox looks over the mask and says, "That will cost 125 Kronars to repair.  Just give it to me again if you want, and I'll have it ready in 1 roisaen."

[crossing-repair]>give Catrox

Catrox mutters, "You will need more coin if I am to be repairing that!"

***No gear was repaired, went back to bank

[Provincial Bank, Teller]
A neat row of barred windows faces you along a marble counter.  Several patrons are already busy but there seems to be one window available.  The clerk smiles at you and beckons you over.  You also see a freshly painted sign.
Obvious exits: out.

Room Number: 1900

[go2: travel time: 0:00:00]

--- Lich: go2 has exited.

[crossing-repair]>wealth

Debt:
  You owe 8 platinum, 9 gold, 2 silver, 3 bronze, and 7 copper Kronars to the Principality of Zoluren. (89237 copper Kronars)

Wealth:
  No Kronars.
  No Lirums.
  No Dokoras.

[crossing-repair]>deposit all

You don't have any Kronars to deposit.

[crossing-repair]>withdraw 3 silver

The clerk counts out 3 silver Kronars and hands them over, making a notation in her ledger.
A burly Gor'Tog taps you on the shoulder and says, "Gabellia D'emibenit, roight?  I'm Barg, from da Debt Collector's Office.  I tink y'have sometin' I been sent t' collect."
With a resigned sigh, you hand your coins to the collector.  "Dis ain't all da debt, but dis is enough for now.  You still owe 88,937 Kronars dough - don't forget."  The collector grins and steps aside.

[crossing-repair]>get my Catrox ticket

What were you referring to?

[crossing-repair]>get my Randal ticket

What were you referring to?

--- Lich: 'performance' has been stopped by crossing-repair.

[performance]>stop play

--- Lich: crossing-repair has exited.

**Comment by Tarhish** [comment]
I'm trying to think what the best way to solve this would be, since this problem keeps rearing its head.  I see 3 options.  Have ensure_copper_on_hand run a flag to look for a debt collector, and run it again if the flag trips, just run ensure_copper_on_hand again anytime it withdraws money, which would be most reliable, but add another wealth check for everyone every time it runs.  Or something weird, like having sell-loot pay off your debt in-province if the debt office is nearby.

**Comment by MahtraDR** [comment]
Closing as this hasn't been a problem reported since.
