### ISSUE TITLE
Mining buddy pickaxe vs shovel

### ISSUE THREAD

**Issue by DryIce41** [rpherbig/dr-scripts#3989]
Would it be possible and simple to set up a way to use a pickaxe when clearing rooms with veins that are not in your keep list, but a shovel when the vein is? This will make clearing rooms via mining buddy to go faster and reset spawns.

**Comment by MahtraDR** [comment]
@Raykyn55 whatcha think?

**Comment by MahtraDR** [comment]
Closing as very stale. Happy to revisit if it still exists today.
