### ISSUE TITLE
Alternate skinning options

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#4]
Skin only for skill, not loot

**Comment by hwoo79** [comment]
Please add arranging for items other than skin.

ARRANGE
ARRANGE <creature>
ARRANGE FOR <part/skin/bone/organ>
ARRANGE ALL (requires Leather Tanning Expertise or Basic Bone Collecting)

**Comment by rpherbig** [comment]
@hwoo79  'arrange all' is currently supported by setting CombatVars.skinning['arrange_all'] = true (it defaults to false in baseline_setup).

**Comment by hwoo79** [comment]
I knew that, I was just pasting all the options from elanthipedia.play.net

**Comment by rcuhljr** [comment]
7c6bc2fe75e44f10137e6b66ea6d0ff1d7a0e953
