### ISSUE TITLE
Clean up documentation

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#40]
see title

**Comment by rpherbig** [comment]
Combat-trainer and Combat-setup could both use some attention too.

**Comment by rpherbig** [comment]
And the README needs an overhaul

**Comment by rcuhljr** [comment]
Rename combat scripts.

**Comment by rpherbig** [comment]
We clearly need some documentation on how to get started/set up.

**Comment by rpherbig** [comment]
A specific issue our first user has encountered: using short names, not descriptions, in UserVars.weapon_training

**Comment by rpherbig** [comment]
I think I'll be ok with closing this once we document the attributes used in spell definitions.
