### ISSUE TITLE
Failed to find a match in combat followed by a server thread error.

### ISSUE THREAD

**Issue by EMSwanson** [rpherbig/dr-scripts#400]
This has happened to me a number of times. I'll keep track and post more detail next time it happens.

[combat-trainer]>attack
< Moving fluidly, you swing a pine-handled sledgehammer at a wind hound.  A wind hound fails to evade, avoiding only some of the blow.  The sledgehammer lands a strong hit to the hound's right eye, lightly stunning it.
[You're winded, adeptly balanced and overwhelming opponent.]
[Roundtime 8 sec.]
>
The faenrae reaver moves into a position to parry.
>
* Tentatively, a faenrae reaver chops wide at you.  You turn aside some of the axe with a pine-handled sledgehammer.  
[You're winded, nimbly balanced with opponent in good position.]
>
[combat-trainer]>app hound careful
[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 0]
[combat-trainer: checked against [/Taking stock of/i, /It's dead/i, /You can't determine anything about this creature./i, /I could not find/i, /You cannot appraise that/i, /roundtime/i, /^Perhaps that/i]]
[combat-trainer]>maneuver crash
--- error: server_thread: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
--- Lich: roomnumbers has exited.
--- Lich: hunting-buddy has exited.
--- Lich: combat-trainer has exited.
--- Lich: lnet has exited.

**Comment by rcuhljr** [comment]
Are you having network issues? That looks like Stormfront dropped the connection through to DR.

**Comment by xtremenerdrage** [comment]
I think this is the issue related to pigs 
Can you try putting your pig away and see if the issue still persists?

**Comment by rpherbig** [comment]
@rcuhljr Do we have an ETA from Tillmen on an update to Lich?

**Comment by rcuhljr** [comment]
I haven't caught him online yet.

**Comment by EMSwanson** [comment]
Ok, yes, thank you! I now know why other things were occasionally dropping as well.
