### ISSUE TITLE
Alchemy Support for Clerk-Tools?

### ISSUE THREAD

**Issue by khrispyb** [rpherbig/dr-scripts#4003]
Wondering if there is a reason it is not supported or if there are plans to add it?

Thanks!

**Comment by aemenash** [comment]
Indeed was wondering this myself, is there a mechanical issue or was alchemy and enchanting just not a thing when clerk-tools went live? I too would like to know.

adding my voice to KhrispyB's

**Comment by rpherbig** [comment]
> Indeed was wondering this myself, is there a mechanical issue or was alchemy and enchanting just not a thing when clerk-tools went live?

Probably the latter. `clerk-tools.lic` supports an alchemy belt so it shouldn't be hard to add

> if there are plans to add it

I suggest asking around in LNet if anyone is working on it. Most likely not.

**Comment by Tarhish** [comment]
I can look at it later today - it should be really easy to add.

**Comment by Tarhish** [comment]
I think this issue can be closed now, if you get back to it.

**Comment by khrispyb** [comment]
Hey, thanks for adding alchemy - saw outfitting was up too but it only stores knitting needles not other tools that are needed to run ;workorders tailoring (scissors, sewing needles, yardstick etc)

**Comment by Tarhish** [comment]
By default outfitting_tools: only has - knitting needle in it, since most people start with just knitting.

You'll want to make your own
```
outfitting_tools:
- sewing needle
- yardstick
- scissors
- knitting needle
- awl
```
etc entry for all the tools you're using in your crafting, and then clerk-tools will store and retrieve them.

**Comment by khrispyb** [comment]
awesome thanks
