### ISSUE TITLE
wishlist: add a validate error for cornmaze_container being a string instead of an array

### ISSUE THREAD

**Issue by Sarvatt** [rpherbig/dr-scripts#4007]
someone broke it within a few minutes setting cornmaze_container: carryall.

**Comment by MahtraDR** [comment]
@rpherbig Sorry, I thought my commit being merged would resolve this issue. Can be closed. Is there a way to have a merge auto-close open issues?

**Comment by rpherbig** [comment]
> Is there a way to have a merge auto-close open issues?

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

For example, "Fixes #4007" in the commit message
