### ISSUE TITLE
add burden to textsubs

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#401]
Can we have textsubs added to burden? 1/12 is none etc, I have pasted the burdens below in order

None
Light Burden
Somewhat Burdened
Burdened
Heavy Burden
Very Heavy Burden
Overburdened
Very Overburdened
Extremely Overburdened
Tottering Under Burden
Are you even able to move?
It's amazing you aren't squashed!

**Comment by rpherbig** [comment]
Is the `info` command the only way to see your burden?

**Comment by rcuhljr** [comment]
and `encumbrance` command. They are long enough to let us safely replace None if we tie it to the Encumbrance label.

**Comment by rpherbig** [comment]
@rcuhljr @xtremenerdrage Would we want 'None' to be 0/11 or 1/12?

For example, damage starts at 'no damage' which is '0/27'.

**Comment by xtremenerdrage** [comment]
both places it always says Encumbrance: before the amount if that helps

**Comment by xtremenerdrage** [comment]
Oh I misread, that's a good point I guess None would be 0/11 since I think most people read none as 0

**Comment by rcuhljr** [comment]
I'd say 0/11 as well.
