### ISSUE TITLE
;steal in crossing/leth doesn't drop a couple items

### ISSUE THREAD

**Issue by blackheart217** [rpherbig/dr-scripts#4017]
[The True Bard D'Or, Fine Instruments]
steal case of silver in catalog => silver flute case: 
https://pastebin.com/MGFZfzrF

[Demiciil's Armory]
steal small vest in catalog => heavy leather vest
https://pastebin.com/8G2M2iT5

Ends up stowing the items when the drop command fails, stacking burden.

**Comment by blackheart217** [comment]
Also occurring in a few non-zoluren locations

"red felt hawking pouch" in [Zaldi Taipa, Falconer's Chadir Room Number: 13720
[steal]>steal fourth pouch, on rack
attempts to "drop my fourth pouch,"

"heavy leather vest" in  [Demiciil's Armory] Room Number: 10039
[steal]>steal small vest in catalog
attempts to "drop my small vest"

"fitted gown" in [Meek's Stitchery]  Room Number: 13996
[steal]>steal fitted gown lists
attempts to "drop my fitted gown"; which for some reason even despite the correct adjective, still fails.

**Comment by mtruitt** [comment]
[steal]>steal wide-brimmed hat in catalog

Moving stealthily, you manage to grab a wide-brimmed hat right from underneath the merchant Rufus's very nose.
You learned rather well from this difficult theft.
Roundtime: 5 sec.

[steal]>drop my wide-brimmed hat

You come out of hiding.
What were you referring to?

**Comment by mtruitt** [comment]
[steal]>steal case of silver in catalog

Moving stealthily, you manage to grab a silver flute case right from underneath the apprentice's very nose.
You learned acceptably from this theft.
Roundtime: 5 sec.

**Comment by mtruitt** [comment]
HR> steal silver case

Moving stealthily, you manage to grab a silver flute case right from underneath the apprentice's very nose.
You learned acceptably from this theft.
Roundtime: 5 sec.

HR> drop case

You come out of hiding.
