### ISSUE TITLE
Better low rank Alchemy training (without doing work orders)

### ISSUE THREAD

**Issue by n1neb4ll** [rpherbig/dr-scripts#4019]
Alchemy can be trained up to at least 50 ranks (I've heard 100) by just foraging for blue flowers and crushing them in a mortar. No need to do work orders. Not only is it much faster than doing work orders, it is free, which is significant for F2P players that cannot make money back from work orders.

**Comment by n1neb4ll** [comment]
This is a quick and dirty trainer I wrote up. someone that is a better programmer than I may consider including this or something similar in alchemy.

`=begin
  Goes to Warmie Guild and forages flowers, then crushes them until mindlocked
=end

custom_require.call(%w[common common-items common-travel common-crafting events drinfomon])

class Flowers
  include DRC
  include DRCT
  include DRCI
  include DRCC

  def initialize
    arg_definitions = [
      [
        { name: 'mindstates', regex: /\d+/, optional: true, description: 'Number of mindstates or collection attempts to perform before exiting. Defaults to 3' },
        { name: 'collect_item', regex: /\w+/i, optional: true, description: 'Item to collect. Will use forage_item if not set' }
      ]
    ]
    args = parse_args(arg_definitions)
    @settings = get_settings
    @performance_pause = @settings.performance_pause
    @bag = @settings.crafting_container
    @belt = @settings.alchemy_belt
    @mortar = 'mortar'
    @pestle = 'pestle'
    @targetxp = 4
    @targetxp = args.mindstates.to_i if args.mindstates
    
    start_exp = DRSkill.getxp('Alchemy')
    @end_exp = [start_exp + 15, 29].min
	
    low_level_alchemy
  end


  def low_level_alchemy

	if (DRSkill.getxp('Alchemy') >= @end_exp)
		echo '*** QUITTING DUE TO MINDSTATE ***'
		exit
	end
	
    attempt = 0 # Failsafe counter to prevent an infinite loop if this is no longer moving alchemy
    while (DRSkill.getxp('Alchemy') < @end_exp) && (attempt < @targetxp)
		walk_to(984)               # can update this in the future for any blue flower foraging room
		check_mort_and_pes         # we need to make sure that we have both and that the pestle is not INSIDE our mortar (this will prevent us from putting flowers in)
    	forage?('blue flower')     # find us a fresh blue flower
    	crush_herb 				   # crush it up
    	stow_crafting_item(@pestle, @bag, @belt)  # put our pestle away so we have a free hand
    	clean_mortar			   # we don't need the crushed up flower now, so let's toss it.
    	stow_crafting_item(@mortar,@bag, @belt)			   # all done, let's put our pestle away as well.
		
		attempt += 1
		if (attempt >= @targetxp)
			echo '*** QUITTING DUE TO EXCEEDING MAXIMUM TRIES ***'
			exit
		end
		if (DRSkill.getxp('Alchemy') >= @end_exp)
			echo '*** QUITTING DUE TO MINDSTATE ***'
			exit
		end
	end
   end


	def check_mort_and_pes
		# first we clear our hands, and then we get our mortar and pestle.
		# we need to make sure that the pestle is not inside the mortar
		# otherwise, we cannot put our flowers in our mortar
		
		stow_hands 			# clear our hands
		
		case bput('get my mortar', 'You get a', 'What were you referring to?')
		when 'What were you referring to?'
			echo '*** ERROR, COULD NOT FIND MORTAR. IS IT IN A CLOSED BAG? ***'
			exit
		end
		
		
		clean_mortar
		
		# now that we've cleared out our mortar of flowers, let's make sure
		# our pestle isn't in there either, and make sure we have a pestle
		case bput('get my pestle', 'You get a', 'What were you referring to?')
		when 'What were you referring to?'
			echo '*** ERROR, COULD NOT FIND PESTLE. IS IT IN A CLOSED BAG? ***'
			exit
		end		
		
		# Put them away for now.
		stow_hands
	end
	
	def clean_mortar
	
		# let's check to make sure there are no flowers in our mortar right now
		# we are assuming you aren't using your mortar for anything else at this time
		# if you are using this script, so only check for the flower
		case bput('get flower from mortar', 'You get', 'What were you referring to?')
		when 'You get'
			dispose_trash('flower')
		end
		
	end

  def crush_herb

	# we know that we have a mortar and pestle already, so just grab them.
	# no need to handle not having one. likewise, we know that we have 
	# found a flower already, so drop it in and grab your pestle.
    bput('get my mortar', 'You get')
    bput('put my flower in my mortar', 'You put')
    bput('get my pestle', 'You get')

	# now we crush until we're done!
	loop do
		case bput('crush blue flowers in my mortar with my pestle', 'Utilizing short strokes', 'You intently', 'Back and forth', 'Bit by Bit', 'You complete')
		when 'You complete'
        break
        end
    end
  end
  
end




Flowers.new
`

**Comment by dakre18** [comment]
i think this could be possible, and would be beneficial for doing workorders with ingredients that cannot be bought. It would require gathering herb data around each town, since different herbs are located in different areas. Then making a script to forage those herbs and prepare them. Herbs require different outdoorsmanship skill depending on day and night, and some are not available in specific seasons. 

Optionally, i think it would help to have options for traveling out of town for herbs not available nearby, or at least a list of towns willing to travel to. So the biggest hurdle would be gathering data, since it would be simple to forage/collect herbs and prepare them by crushing or drying (may need an option to use wayerd device too?).
