### ISSUE TITLE
Workorders logic error in checking for lumber quantities for shaping

### ISSUE THREAD

**Issue by n1neb4ll** [rpherbig/dr-scripts#4020]
When using workorders to do shaping work orders, there is a logic problem near the top of the shape_items function (line 302). I believe the problem is with 

`if items_per_stock.zero? || (count % items_per_stock).zero?` 

It will check on first run, and if there is enough lumber, it will continue. However, on subsequent runs if there is not enough lumber to complete the work order, it won't catch it, and ends up either a) telling you you have no lumber and quitting (it should be going to buy more lumber according to the rest of the function) or b) shape.lic gets stuck in a loop saying you do not have enough lumber( not receiving expected output, and won't go buy more). Logic to buy more lumber is in workorders.lic.

Need to either fix the logic in workorders.lic, or add a safeguard in shape.lic to go buy more lumber if it gets the message you do not have enough lumber.

**Comment by Tarhish** [comment]
I _think_ that part is working fine, as it does count how much it should have, how many items it should make, and count increments as it moves through the crafting process.

I _have_ noticed this happen if our listed volume is off by 1 on a recipe, though.  It'll mostly work, but with certain volume combinations it'll buy what it think is enough, but run out partway through.  I'll keep looking at the script, but do you know what shaping recipe it was you were working on?

**Comment by n1neb4ll** [comment]
Sorry for the late reply. I believe it was the wooden bracelet.

**Comment by Tarhish** [comment]
Yeah, sorry for the delay here too -- lots of event stuff and family stuff going on.  I'll look at this again.

**Comment by dakre18** [comment]
It does help to post a log of what happens, but it should be throwing away any lumber that was leftover before buying more. If that happens, it should always have enough lumber. At least until an update to handle buying in bulk first, and stop making extra trips to the shop :)

**Comment by MahtraDR** [comment]
Workorders has been completely rewritten since this was an issue. Closing.
