### ISSUE TITLE
Alchemy and large bowls

### ISSUE THREAD

**Issue by DryIce41** [rpherbig/dr-scripts#4027]
Remedies is leaving off the adjective assigned in my yaml for getting my alchemy_tool: - large bowl

Instead it grabs the first bowl in my inventory, which is my sandstone divination bowl. 

Any way to fix that to pull the adjective from my yaml?

I did try: 
alchemy_tools:
- large bowl
- large.bowl
- "large bowl"

but not all at once.  Tap my large bowl does work.

**Comment by Tarhish** [comment]
Okay, so I don't use the remedy script a lot, and it could use some love from someone who does, but from my look at it what I see is it changes the container that's needed based on the recipe, and when it's 'bowl' it's hardcoded in as part of workorders.  If you ran ;remedy with "large bowl" as your container arg then it should be fine, and it uses your -large bowl when repairing, but workorders just goes with bowl.  

There are a couple ways someone who uses this might be able to fix that, but for now what you should be able to do is keep your divination bowl outside of your crafting_container.

**Comment by DryIce41** [comment]
I appreciate you looking into this.
I do keep my sandstone bowls and large bowls in separate containers with the large bowl in the crafting_container:

**Comment by Tarhish** [comment]
This should work for you as long as you have `- large bowl` in your alchemy tools:.  I was able to pull mine up, so give it a shot.

**Comment by DryIce41** [comment]
Thank you for working on it! 

I got this error:
You put your ojhenik in your leather haversack.
>
--- Lich: remedy active.
--- Lich: error: remedy:62: syntax error, unexpected ')', expecting '}'
/#{args.container}/ =~ tool  ) } || args.container 
                              ^
remedy:63: syntax error, unexpected ')', expecting '}'
d { |tool| /pestle/ =~ tool  ) } || 'pestle'
                              ^
	C:/Users/JKGeda/lich/lich.rbw:2522:in `eval'
	C:/Users/JKGeda/lich/lich.rbw:2522:in `block (2 levels) in <class:Script>'
--- Lich: remedy has exited.
>
[workorders]>get my alchemy logbook
