### ISSUE TITLE
combat-trainer ammo request

### ISSUE THREAD

**Issue by TegCross** [rpherbig/dr-scripts#4045]
Could you please add 'scale' to the ammo from my chipper weapon or possibly add a new yaml variable for chipper ammo?

Thank you very much! Happy Thanksgiving!

**Comment by Hiinky** [comment]
Add to new up pull request.  Should go live in a day or so once the request is reviewed and committed.

**Comment by TegCross** [comment]
You rock! Thank you much!

**Comment by rpherbig** [comment]
Done in #4047
