### ISSUE TITLE
polite safe-room.lic "May I have a Heal?"

### ISSUE THREAD

**Issue by DRLimes** [rpherbig/dr-scripts#4050]
Propose a change to safe-room.lic line 210

fput("whisper #{empath} May I have a Heal?")

**Comment by Sarvatt** [comment]
This will break all the existing healer scripts in use afaik

**Comment by DRLimes** [comment]
> This will break all the existing healer scripts in use afaik

hmm its never easy is it..

**Comment by rpherbig** [comment]
If you convince our empaths to upload their scripts here, then it'd be easy to keep it in sync...

**Comment by MahtraDR** [comment]
I'm closing this. As nice as I think this is, I don't want to create a situation where folks miss out on healing because of a change we make here. Another way of looking at it... it's all scripted actions. Politeness doesn't factor. :)
