### ISSUE TITLE
fam keeps getting app'd

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#406]
Familiar keeps getting appraised in combat
(bear)

**Comment by xtremenerdrage** [comment]
a russet bear

**Comment by rpherbig** [comment]
I think this is a duplicate of #57

**Comment by rpherbig** [comment]
From @rcuhljr : Add noun list of ignored npc's so combat trainer doesn't count familiars, pets, and other stuff as enemies

**Comment by rcuhljr** [comment]
ground work in place, drinfomon should be better at picking out the nouns of stupidly named npcs like yellow and gold banded lizard with sparkly hair.

**Comment by rcuhljr** [comment]
Fixed, add npc nouns to ignored_npcs:

```
ignored_npcs:
 - Brokk
 - bear
```
