### ISSUE TITLE
Suggestion on research in crossing-training.lic

### ISSUE THREAD

**Issue by dakre18** [rpherbig/dr-scripts#4069]
I was looking at how crossing-training.lic uses magical research, and i see it will use fundamental, stream, utility, warding, and augmentation.

If it's doable, it would be helpful to add a check, if arcana is over 1000 AND utility, warding, and augmentation are all 3 on the training list, it would use SPELL for each of those 3 skills. The only thing that would need added is a check prior to checking for individual skills.

It would still work the same, so it would research SPELL up to 3 times, depending on mindstate. Otherwise, it will research the individual skills listed, if the user doesn't have the arcana or doesn't want to train one of the 3 skills (for whatever reason).

Also, it doesn't look like research checks for a waggle_set, which would be a nice addition to check for a 'gaf' waggle_set. If it already does, i may have missed it.

**Comment by MahtraDR** [comment]
Closing as wontfix.
