### ISSUE TITLE
mining

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#407]
--- Lich: go2 active.
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>south
You go south.
[Abandoned Mine, Tunnel - 7266]
A ghastly sight confronts you entering this portion of the mine.  Poised to attack, battle axe in one hand, shield in the other, stands a dwarf frozen in all of his glory.  What he was about to fight or defend himself from or what left him in this sorry state, can only be the subject of conjecture.  You also see a beisswurm.
Obvious exits: north, northeast, south.
>
[go2: travel time: 0:00:00]
--- Lich: go2 has exited.
[mining-buddy]>prospect
You see evidence of mineral deposits and are certain a good quantity (3/5) remains to be found.
This area is composed of metamorphic rock layers.
Studying the geology, you are certain that continued mining will be quite safe.
You are certain that travertine can be mined here.
Miners stand ready to trade resources in for deeds.  Just PUSH any mined up stone or metal, and they'll take care of the rest.
Roundtime: 8 sec.
>
[mining-buddy]>retreat
You are already as far away as you can get!
>
--- Lich: go2 active.
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>south
A beisswurm slithers in.
>
The beisswurm begins to advance on you!
The beisswurm advances from nearby and is closing steadily.
>
You can't do that while engaged!
>
[go2: move: failed]
[go2: restarting script...]
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>south
You can't do that while engaged!
>
[go2: move: failed]
[go2: restarting script...]
[go2]>combatant
Please rephrase that command.
>
The beisswurm closes to melee range on you!
>
The beisswurm begins to advance on you!
The beisswurm advances from nearby and is closing steadily.

**Comment by rcuhljr** [comment]
Yeah it's a known issue with go2's behavior. I've got an email out to tillmen with a fix for it, we're waiting to see if he'll make the change.

**Comment by rcuhljr** [comment]
Actually it looks like this should be fixed in the latest version, testing.

**Comment by rcuhljr** [comment]
Ok there was a bug in tillmen's fix, I've sent him some corrections.
