### ISSUE TITLE
Go2 infinite loops trying to leave rossman gryphons when engaged

### ISSUE THREAD

**Issue by proctophage** [rpherbig/dr-scripts#4070]
here's the loop
https://pastebin.com/sfmhJ8B9

Cancelled go2 and restarted it, and it fails briefly, then after the script times out it's able to get out
https://pastebin.com/P5vNkjxG

Doesn't always happen, but when it does it can't ever escape and loops forever. Seems to only happen when engaged in room 8625

**Comment by Tarhish** [comment]
I made a change to the map to fix this problem last week and it seems to have stuck.

**Comment by proctophage** [comment]
Thanks! I'll close the issue then.
