### ISSUE TITLE
tendme hangs forever when stopping combat due to bleeding

### ISSUE THREAD

**Issue by proctophage** [rpherbig/dr-scripts#4071]
https://pastebin.com/16u3CFmw

dunno what happened here, but it never gave control back to combat-trainer
nearly died there because it never saw whatever it was looking for to end tendme

**Comment by MahtraDR** [comment]
@proctophage I realize it's been awhile... is this still an issue you see by chance?

**Comment by KatoakDR** [comment]
`tendme` and how combat-trainer calls the script have changed to address issues like this. I imagine this is now resolved. If this is still happening, please comment on the issue with a game log and steps to reproduce. Thanks!
