### ISSUE TITLE
Revise how the lootables list is handled

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#408]
Some recent commits have affected the list of lootables:

- a52348a29367ad22ef750dd4f75547ff90954daa added a gem
- ff4bd5c0ef1922900600d8fa7ae9ef4552ecb798 added some scrolls
- b82749b19bff2f8f90cc663e759ae033fa447451 made it necessary to add plurals (e.g. coins)

Since only base.yaml was updated, these changes were not picked up by anyone that overrides the lootables setting. This is fairly common because the lootables list in base.yaml does not include boxes, which many people want.

I propose we instead define some more granular lootables in base.yaml (`lootable_scrolls`, `lootable_gems`, `lootable_boxes`, etc.) and the `lootables` setting then becomes a list of which types to loot. We can then freely update the noun list as needed.

**Comment by rcuhljr** [comment]
loot_additions and loot_subtractions is my suggestion. I don't underestimate peoples desires to loot certain one off items and I don't want someone changing their own loot preference to break them off of our base updates.
