### ISSUE TITLE
multi cambrinth support in combat trainer

### ISSUE THREAD

**Issue by aemenash** [rpherbig/dr-scripts#4083]
I've noticed that combat-trainer does not recognize my second camb item for buff upkeep, prebuffing it works great but once in combat i only get half strength buffs when it comes time to recast, and yes i understand some folks are oh no you dont want to spend those seconds charging extra cambs, but i figure what is 30 seconds downtime when i get at least an extra ten mins before i need to rebuff again. any chance that combat trainer could be tweaked relatively easily to recognize the cambrinth_items: list?

**Comment by Tarhish** [comment]
The bad news is it's not terribly easy to add this in -- ct uses some creative and entirely separate code to weave charging and invoking into stabbing and slashing, and it's complicated enough that testing it would be difficult to be sure it wasn't going to break things for everyone else.

It is possible though, especially after working with cambrinth recently.  If someone else doesn't get to it first I might, later down the line.

**Comment by aemenash** [comment]
Ok thanks at least for taking a look at the issue, I have sort of managed a bit of an interim workaround, using buff_spells: list and manually setting the mana prep higher and maxing the two charges allowed on the camb armband, crap kicks my mana bar but at least my buffs are closer to ¾ power and duration.

Sent from Mail for Windows 10

**Comment by MahtraDR** [comment]
@rpherbig It's not really a RFE, I'd say close?
