### ISSUE TITLE
workorders.lic - issue with tied clamps

### ISSUE THREAD

**Issue by dakre18** [rpherbig/dr-scripts#4085]
A section in workorders.lic isn't designed for tied clamps.

>case bput('get my clamps', 'What were', 'You get')
when 'What were'
__order_item(info['tool-room'], info['clamps-number'])
end
stow_tool('clamps')

If my clamps are tied, it fails to match any message, and then tries to tie them when it stows the item. This is what happens:

>[workorders]>get my clamps
You should untie the muracite clamps from the braided toolstrap first.
[workorders: *** No match was found after 15 seconds, dumping info]
[workorders: message: You should untie the muracite clamps from the braided toolstrap first.]
[workorders: checked against [/What were/i, /You get/i]]
[workorders: for command get my clamps]

>[workorders]>tie my clamps to my braided toolstrap
You must be holding the muracite clamps to tie to the toolstrap.
[workorders: *** No match was found after 15 seconds, dumping info]
[workorders: message: You must be holding the muracite clamps to tie to the toolstrap.]
[workorders: checked against [/you attach/i]]
[workorders: for command tie my clamps to my braided toolstrap]

Other than using get_crafting_item to handle tied or stowed items, other checks are possible too, such as tapping the clamps.

**Comment by Dartellum** [comment]
I can work on this, possibly this weekend.

**Comment by Dartellum** [comment]
Could you change the case line to case bput('tap my clamps', 'What were', 'You tap')? I do not think I have the noun to tie clamps to my belt so I can only test tapping in my container. I believe this should fix it.

**Comment by dakre18** [comment]
Yes, tapping works, like i mentioned. This is how the output looks like:

>You tap some muracite clamps with Elven gold jaws atop your braided toolstrap.

I wasn't sure if tapping was enough for this section or not, but it works in almost every case i've seen.

**Comment by Dartellum** [comment]
I will test some more and then merge.

**Comment by MahtraDR** [comment]
Fixed by https://github.com/rpherbig/dr-scripts/pull/5868
