### ISSUE TITLE
Remedies Workorders issue

### ISSUE THREAD

**Issue by khrispyb** [rpherbig/dr-scripts#4088]
Getting this error and really cannot figure out what the problem is.  I have the following tools listed:
 
alchemy_tools:
- alabaster mortar
- sieve
- pestle
- mixing stick
- alabaster bowl

[remedy]>put my book in my shadows
You put your book in your encompassing shadows.
>
[remedy]>get my alabaster mortar
You get a polished blue alabaster mortar wrapped in supple leather from inside your encompassing shadows.
>
[remedy]>lower alabaster mortar ground
You lower the mortar and place it on the ground at your feet.
>
[remedy]>tap jadice in shadows
You tap some dried jadice inside your encompassing shadows.
>
[remedy]>get my jadice from my shadows
You get some dried jadice from inside your encompassing shadows.
>
[remedy]>count my jadice
You count out 25 pieces of material there.
>
[remedy]>combine my jadice
You must be holding both substances to combine them.  For more information, see HELP VERB COMBINE.
>
[remedy]>put jadice in my alabaster mortar
You put your jadice in your alabaster mortar.
>
[remedy]>put my jadice in my shadows
What were you referring to?
>
[remedy]>get my alabaster mortar
>
You pick up the mortar lying at your feet.
>
[remedy]>get my mixing stick
You get a mixing stick fashioned from a petrified chicken leg from inside your encompassing shadows.
>
[remedy]>mix my alabaster mortar with my mixing stick
That might work if you first put it inside a bowl, pot or cauldron.
>
[remedy: *** No match was found after 15 seconds, dumping info]
[remedy: messages seen length: 3]
[remedy: message: Shadowling  (1 roisan)]
[remedy: message: Shadowling  (1 roisan)]
[remedy: message: That might work if you first put it inside a bowl, pot or cauldron.]
[remedy: checked against [/Applying the final touches/i, /Interesting thought really... but no./i, /you just can't mix/i, /Try as you might/i, /Roundtime:/i]]
[remedy: for command mix my alabaster mortar with my mixing stick]
[remedy]>mix my alabaster mortar with my mixing stick
That might work if you first put it inside a bowl, pot or cauldron.

**Comment by Tarhish** [comment]
I see the problem.  Give me a moment and I'll write up a fix.

**Comment by Tarhish** [comment]
Sorry about that.  In the meantime, if you change your tool entry from 'alabaster mortar' to just 'mortar' it should work.
