### ISSUE TITLE
attunement (streams) research

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#409]
option to add attunement (streams) research
also, can you specify which researches you want it to do?

**Comment by rpherbig** [comment]
Granular research options is covered in #292.

As for attunement research, I noticed that there are two types (https://elanthipedia.play.net/mediawiki/index.php/Magical_Research) based on your rank. We should consider handling both.

**Comment by rcuhljr** [comment]
The second one has a backlash chance, I wasn't planning on implementing it.

**Comment by xtremenerdrage** [comment]
Yea the second one EVEN at my rank will still backlash and leave a huge stun/bleeder... its pretty annoying

**Comment by rcuhljr** [comment]
Should be working now. In addition to the previous research settings you you'll need to fill out research_skills: in your yaml. See Selanas-setup.yaml for an example.
