### ISSUE TITLE
add toads to base

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#410]
add toads to base 
50266 #order is wm attunement
50267

**Comment by rpherbig** [comment]
Could you elaborate on "order is wm attunement"? I don't understand the comment.

Are there more rooms in the hunting zone than those two? If so, could you find the full list of room numbers?

The easiest way to do that is to have two aliases:
   cb => ;e $temp = []
   rec => ;e echo $temp << Room.current.id

Run `cb` first to start with a clean slate. Then walk through the zone running `rec` in each room. This will output the room list each time, so all you have to do is copy the output after running `rec` in the last room.

**Comment by rcuhljr** [comment]
he meant the rooms are ordered based on the current WM mana levels.

**Comment by rpherbig** [comment]
Those levels fluctuate over time right?

**Comment by rcuhljr** [comment]
Yes.

**Comment by rcuhljr** [comment]
added the two rooms for now.

**Comment by xtremenerdrage** [comment]
This can be closed

**Comment by rpherbig** [comment]
f738b3c3fb552d2e0b7de279383178fa92437f0a
