### ISSUE TITLE
Crossing Wir Dinego

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#4104]
I got the room numbers for the wir dinego's in Crossings if you guys like to add it to the data.

```
  # https://elanthipedia.play.net/Wir_dinego                             300-400
  wir_dinego_crossing:
  - 7376
  - 7377
  - 7378
  - 7379
  - 7381
  - 7395
  - 7394
  - 7393
  - 7392
  - 7391
  - 7390
  - 7389
  - 7388
  - 7387
  - 7386
  - 7385
  - 7384
  - 7383
  - 7382
  - 7380
```

**Comment by MahtraDR** [comment]
@Kaesken Are these still valid?

**Comment by MahtraDR** [comment]
@rpherbig Close? or wait another week? Given it's two years old, and nobody else has asked, and @Kaesken hasn't responded... I figure it doesn't make sense to add yet another zone for us to maintain. I would be happy to add for an active request, note.
