### ISSUE TITLE
mine.lic - doesn't recognized when pinned by rockslide

### ISSUE THREAD

**Issue by GreyhallowDR** [rpherbig/dr-scripts#4111]
script doesn't recognize when you're pinned down. Takes around 60 seconds to get out with the final messaging. 
> You finally manage to clear away enough rubble to lever yourself free.

Script doesn't fail, but it would be a step towards accuracy and maybe prompt a health check?

https://pastebin.com/LS3YP0EY

**Comment by MahtraDR** [comment]
Resolved by #5840
