### ISSUE TITLE
Heal-remedies genich stem

### ISSUE THREAD

**Issue by DryIce41** [rpherbig/dr-scripts#4114]
When using crossing bought herbs, heal-remedies will attempt to eat the genich stem, gets notification that you should inhale it instead but skips genich stem. 

If anybody could help with that I'd appreciate it.

**Comment by DryIce41** [comment]
And nevermind, it apparently works out of combat.  I'll check it again in combat to ensure it is working. Maybe I got lost in the scroll.

**Comment by Hiinky** [comment]
If you find one or the other isn't working, let me know.  I only edited it in one place last time so may have missed a reference somewhere.

**Comment by DryIce41** [comment]
[heal-remedy]>health
Your body feels slightly battered.
Your spirit feels full of life.
HEAD          -Fresh Internal-     -*- [XXX_____]
CHEST         -Fresh External-     -*- [X_______]
CHEST         -Scars External-     -*- [X_______]

[You're bruised, nimbly balanced and in dominating position.]

[heal-remedy]>eat my nemoih root
You eat a portion of a nemoih root.
 
[heal-remedy]>drink my blocil potion
You drink a portion of some blocil potion.

[heal-remedy]>eat my plovik leaf
You eat a portion of a plovik leaf.
That was the last of your plovik leaf.

[heal-remedy]>drink my ithor potion
You drink a portion of an ithor potion.
That was the last of your ithor potion.

[heal-remedy]>drink my qun pollen
You drink a portion of some qun pollen.

[heal-remedy]>eat my hulij elixir
You eat a portion of some hulij elixir.
That was the last of your hulij elixir.

[heal-remedy]>eat my genich stem
You'd be better off trying to inhale a genich stem.

[heal-remedy]>eat my ojhenik potion
You eat a portion of some ojhenik potion.
That was the last of your ojhenik potion.

[combat-trainer]>load
