### ISSUE TITLE
force_healer_town settings causes debt to accumulate 

### ISSUE THREAD

**Issue by vtcifer** [rpherbig/dr-scripts#4120]
This is because safe_room still withdraws funds from your hometown bank, which unless healer town is the same currency as hometown, means you're not getting the right coin for that healer.

Digging into it, I think it would need updates to ensure_copper_on_hand, to pass hometown instead of settings to it, but that has a knock on effect to withdraw_exact_amount, since that uses more than just hometown from settings.  I'm not sure if there is a more elegant solution right now.  

Additionally, if ensure_copper_on_hand could be updated this way, it would make it possible for things like force_crafting_town (since premie portals are open all the time, would make it easier to do work orders in hometown that don't have a crafting society).

**Comment by jandersson** [comment]
From what youre describing, it sounds like `ensure_copper_on_hand` should take an optional argument for a town to withdraw from, cascading down to additional helper methods if necessary.

**Comment by vtcifer** [comment]
> From what youre describing, it sounds like `ensure_copper_on_hand` should take an optional argument for a town to withdraw from, cascading down to additional helper methods if necessary.

This was an excellent idea, and I've got it mostly working thanks to this suggestion.  Only concern now is I slowly withdraw money from the bank of the force_healer_town to my regular home town. The fix for that would be to deposit back again, if force_healer_town is set, but I'm not sure if that's good/desired behavior, as it might catch more than just what we withdrew.  

Thoughts?

**Comment by jandersson** [comment]
I think things may be getting a bit messy in the money handling logic, but I would try to make force_healer_town and the arg you pass to ensure_copper_on_hand be the same.

**Comment by vtcifer** [comment]
Closed by #4135
