### ISSUE TITLE
retreat stealth training ability

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#4124]
Could someone copy stealth from training_abilities and make a copy that's RStealth - it would simply retreat twice before hiding.

training_abilities:
  Stealth: 100
  RStealth: 100 
 
Could be used for stealth training or when changing hunting areas and stealth hasn't caught up.

**Comment by MahtraDR** [comment]
Resolved by https://github.com/rpherbig/dr-scripts/pull/4126
