### ISSUE TITLE
pick.lic error with barbarian meditation buff

### ISSUE THREAD

**Issue by Bedonder** [rpherbig/dr-scripts#4132]
I am getting an error in pick.lic when using a barbarian meditation in the pick: waggle_sets:

--- Lich: error: undefined local variable or method `fix_standing' for Scripting::DRCA:Module

Here are my relevant yaml settings;

waggle_sets:
  default:
  - Python
  - Piranha
  - Turtle
  - Dragon
  - Monkey
  pick:
  - Focus

meditation_pause_timer: 10

--------------------
log
--------------------
[pick]>sit

You are already sitting.

[pick]>med focus

You begin to meditate upon the chakrel amulet, your inner fire swelling as you center your mind, body, and spirit.
Roundtime: 11 sec.
Peering into the flame, you visualize the difficult feats you wish to perform.
You draw the flames close and bring forth an image of the complex task of disabling locks and traps.
The deep understanding of locks and traps provided by your Focus meditation slips away from your mind.
The flame surrounds you and infuses you with deep insight into the workings of locks and traps!
You feel a jolt as your vision snaps shut.
The spikes of your wristcuff flicker and you feel more battle-ready.

--- Lich: error: undefined local variable or method `fix_standing' for Scripting::DRCA:Module
	common-arcana:78:in `block in start_barb_abilities'
	common-arcana:74:in `each'

--- Lich: pick has exited.

**Comment by rpherbig** [comment]
@Bedonder give it another try, let me know if it still breaks

**Comment by Bedonder** [comment]
All good! Thanks for the quick fix!
