### ISSUE TITLE
steal.lic - the item selection process can lead to very bad inefficiencies in travel

### ISSUE THREAD

**Issue by vtcifer** [rpherbig/dr-scripts#4138]
At my current ranks, with a hometown of shard, and setting stealing towns as below, steal will start in crossing, go to shard, go back to crossing, go back to shard, go to leth on the first time it's run.  

Either after item selection in find_all_targets, the targets should be sorted based on order in stealing town, or find_all_targets should be run multiple times each for town.  I'm not sure which would be better.

**Character/settings:**
Guild: Thief
Thievery: 485
```yaml
stealing_towns:
 - Shard
 - Leth Deriel
 - Crossing
```

**Comment by vtcifer** [comment]
I tried getting targets to sort based on town, but I have no idea why `targets.sort_by!{ |id | }` works, but `targets.sort_by!{ |town | }` doesn't.

**Comment by Tarhish** [comment]
The `targets.select { |id|` thing is more like 'take the data that's in the first level of 'targets' and call it variable id.  So targets.sort_by! { |town| } is actually the same as targets.sort_by! { |id| } except it names the variable differently.

That said, given stealing options, I think that     `@stealing_options.sort_by { |data| data['town'] }` should work?

**Comment by vtcifer** [comment]
After digging and staring a lot, it's because targets isn't what I thought it was, it's a triple-index array (that I'm still not sure how it's being used/why it's setup the way it is), but later on I was able to figure out that per_room_targets.values is the final list, and is an array as opposed to a triple indexed array of hashes.  Much easier to sort.  

Or even better use a for each and select to allow the yaml to pick the order.  Working on this now.

**Comment by vtcifer** [comment]
Some quick testing and it's 

```ruby
@stealing_towns.each do |current_town|
  targets.select { |target| target['town'] == current_town }
  .each { |target| steal(target)}
end
```
instead of 

```ruby
targets.each { |target| steal(target) }
```

I'll run with this for a while but I think that's it. 😊
