### ISSUE TITLE
Sell-Loot issue with Fang Cove Changes

### ISSUE THREAD

**Issue by cfrisby77** [rpherbig/dr-scripts#4140]
also found a couple issues with sell-loot in fang cove. 
1. gem selling is not going to the correct room. It is trying to sell in room 8305, inside the hut is: 8386 
2. it is trying to sell to Wicket but he is not there, it is now "a Halfling gembuyer" (This may change by time of day) 
3. Gorund's Furs also has a new attendant: "a youthful attendant" It did sell the bundle but also threw an error.
 [sell-loot-custom]>sell my bundle
You hold up your lumpy bundle for the youthful attendant to buy.
A youthful attendant takes the bundle and hands you 28 Dokoras in exchange.
Youthful attendant says, "And there's your rope back again."
>
The grid of thin lines slides away from your thoughts.
>
You notice as a spotted leopard slinks into the room.
>
[sell-loot-custom: *** No match was found after 15 seconds, dumping info]
[sell-loot-custom: messages seen length: 6]
[sell-loot-custom: message: You notice as a spotted leopard slinks into the room.]
[sell-loot-custom: message: The grid of thin lines slides away from your thoughts.]
[sell-loot-custom: message: Substratum  (Fading)]
[sell-loot-custom: message: Youthful attendant says, "And there's your rope back again."]
[sell-loot-custom: message: A youthful attendant takes the bundle and hands you 28 Dokoras in exchange.]
[sell-loot-custom: message: You hold up your lumpy bundle for the youthful attendant to buy.]
[sell-loot-custom: checked against [/ponders over the bundle/i, /sorts through it/i, /gives it a close inspection/i]]
[sell-loot-custom: for command sell my bundle]
[sell-loot-custom]>stow rope
You put your rope in your journey pack.

**Comment by rpherbig** [comment]
I fixed the room # and `sell-loot` message.

Could you do more investigation into Wicket before we make that change?

**Comment by cfrisby77** [comment]
Gemsmith Wickett and Furrier Gorund Are there during the Day.

You ask Wickett to buy a small flax-colored pearl.
Gemsmith Wickett carefully studies the flax-colored pearl, then hands you 424 Dokoras.

You hold up your bundle for Gorund to buy.
Gorund takes your bundle and gives it a close inspection.  With an uninterested grunt, he hands you 72 Dokoras.
Furrier Gorund says, "And there's your rope back again."

**Comment by cfrisby77** [comment]
So it looks like being in the correct room fixes the issue. The room will still accept  **Wickett** if he is not in the room.

>
[sell-loot-custom]>get my bloodstone from my gem pouch
You get a small green bloodstone from inside your gem pouch.
>
[sell-loot-custom]>sell my bloodstone to Wickett
You ask the Halfling gembuyer to buy a small green bloodstone.
A Halfling gembuyer carefully studies your green bloodstone, then hands you 247 Dokoras.
