### ISSUE TITLE
common-arcana fails to find barbarian buffs

### ISSUE THREAD

**Issue by minor-fixes-only** [rpherbig/dr-scripts#4145]
For barbarians:
`echo DRSpells.active_spells` 

returns {nil=>1000}
For all other guilds, this command lists their current spells or khri that are active.
This results in combat-trainer.lic repeatedly apply certain buffs.
It also prevents DRCA.start_barb_abilities  recognizing which buffs are up and will attempt to use abilities already in action.

Basically, there's no way for a barbarian to know what buffs they have going unless they flag start and stop messages, which doesn't seem to work all the time.

**Comment by minor-fixes-only** [comment]
Following up on this as it's still an active issue with severe implications.  This is currently draining inner fire to the point that a barbarian cannot use any buffs.

**Comment by rpherbig** [comment]
Do you have Power and/or Powermonger?

**Comment by minor-fixes-only** [comment]
Yes both.

**Comment by MahtraDR** [comment]
@minor-fixes-only still an issue? I don't see this with my barb today.

**Comment by MahtraDR** [comment]
@rpherbig Can close this. Not an issue today.
