### ISSUE TITLE
Clan justice items shouldn't be under main city headings

### ISSUE THREAD

**Issue by vtcifer** [rpherbig/dr-scripts#4146]
Given the way that clan justice works (and now that it's turned back on), any shop that falls under clan justice should probably be under it's own city, and not under a normal city (see: Fayrin's Rest being included with Shard).

I'm not sure if there are any other places that are clan justice 'hidden' under a main city for stealing.

**Comment by MahtraDR** [comment]
Closing as it's an old issue, with no additional interest shown since.
