### ISSUE TITLE
different types of lockpick rings

### ISSUE THREAD

**Issue by GreyhallowDR** [rpherbig/dr-scripts#4151]
I have a key from Droughtman's and ,pick doesn't play nicely with it.

Can the code be reworked to  remove the "lockpick" adjective and provide for using a custom adjective in yaml?

[pick]>app my lockpick key 

Appraise what?  Type APPRAISE HELP for more information.

[pick: *** No match was found after 15 seconds, dumping info]

[pick: messages seen length: 5]

[pick: message: Platinum Hands of Kertigen  (10 roisaen)]

[pick: message: A glowering Shadow Servant trudges off, following its master.]

[pick: message: Platinum Hands of Kertigen  (10 roisaen)]

[pick: message: Appraise what?  Type APPRAISE HELP for more information.]

[pick: message: (ASK <Fatimi> TO APPRAISE <> to get a sales price.)]

[pick: checked against [/and it appears to be full/i, /and it might hold an additional \d+/i, /\d+ lockpicks would probably fit/i]]

[pick: for command app my lockpick key]

--- Lich: pick has exited.

> tap my key
You tap a golden key with an elaborately sculpted "D" that you are wearing.
> app my gold key

(ASK <Fatimi> TO APPRAISE <key> to get a sales price.)

The golden key is made with metal.
The golden key looks to be holding 47 lockpicks and it might hold an additional 3.
It appears that the golden key can be worn attached to a belt.
You are certain that the golden key weighs exactly 14 stones.
You are certain that the golden key is worth exactly 4,510 Dokoras, 6,250 Kronars, or 5,000 Lirums.
Roundtime: 8 seconds.

**Comment by vtcifer** [comment]
Also would help since some of the new loot from BNE are tool cases.

**Comment by BinuDR** [comment]
This should address it.
https://github.com/rpherbig/dr-scripts/pull/4152

**Comment by rpherbig** [comment]
Closed in #4152
