### ISSUE TITLE
Burgle script + Steal Script in Shard

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#4172]
Could we get a trigger for the burgle.lic to stop when this message is seen:
```
Footsteps nearby make you wonder if you're pushing your luck.
```

I get caught every time after this message.

Edit;
Also on a side note, stealing in Shard at night time produces this:
```
[go2]>go blue shop

The shop appears to be closed, but you catch the attention of a night attendant inside, and he says, "I'm sorry, I can only allow citizens in at night."
  He pauses, then quietly says, "Just for you,
 I'd look the other way for 1200 Dokoras."
[GO again to bribe the night attendant to let you inside.]
> 
A chorus of trilling mews heralds the arrival of a soft midnight black kitten.

> 
Your body below the waist is dripping with water.  Pools of it are forming all around you.
> 
[go2: move: no recognized response in 30 seconds.  giving up.]

[go2: restarting script...]

[go2: ETA: 0:00:00 (1 rooms to move through)]

[go2]>go blue shop

The attendant says, "Fine.  1201 Dokoras, please."
You realize you don't have enough.  The attendant looks at your pitiful bribe and closes the door without another word.
> 
The night attendant has lost intrest in you.
> 
[go2: move: no recognized response in 30 seconds.  giving up.]

[go2: restarting script...]

> 
[go2: ETA: 0:00:00 (1 rooms to move through)]

[go2]>go blue shop

The shop appears to be closed, but you catch the attention of a night attendant inside, and he says, "I'm sorry, I can only allow citizens in at night."
  He pauses, then quietly says, "Just for you,
 I'd look the other way for 1200 Dokoras."
[GO again to bribe the night attendant to let you inside.]
```

**Comment by Kaesken** [comment]
Scratch the burgle section.  Someone's looking into it!  Thank you, all!

**Comment by BinuDR** [comment]
The default is to get out asap as soon as the footsteps are heard.
From epedia:

safe_mode: true                           # stop searching and try to get out as quickly as possible when hearing footsteps.  Default: true

**Comment by BinuDR** [comment]
For the stealing in shard at night issue, you either need to make sure you have enough dokoras on you  to bribe them, or you need to be a citizen of Ilithi so they let you in without a bribe.

**Comment by Kaesken** [comment]
Yeah that's what Kalindara was telling me but after I showed her my log, it wasn't triggering the flag so I think she's looking into it.

**Comment by vtcifer** [comment]
> Could we get a trigger for the burgle.lic to stop when this message is seen:
> 
> ```
> Footsteps nearby make you wonder if you're pushing your luck.
> ```
> 
> I get caught every time after this message.

AFAIK, It's already setup to do this as best as can be done. 
Due to how RT works with bput, if it's already in the bput for searching/movement/etc when that message hits, it will still perform that action.  Immediate after that it will get out.

**Comment by Kaesken** [comment]
Okies, thanks guys!
