### ISSUE TITLE
;burgle - unable to drop item 

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#4178]
You rummage around the tiny desk, until you find a gaethzen Eluned's glory blossom with a short Elven silver stem.  It looks valuable, so you decide to take it.
Roundtime: 10 sec.

[burgle]>drop my s blossom
What were you referring to?
>
[burgle]>drop my s blossom
What were you referring to?
>
[burgle]>drop my s blossom
>
What were you referring to?

This continued until I manually stopped ;burgle.

~Gab

**Comment by vtcifer** [comment]
Pending fixes in PR #4170 should resolve this.

**Comment by drgabellia** [comment]
Thank you!
