### ISSUE TITLE
People dragging when at NPC healers

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#4187]
I see in safe-room where there's a flag for when someone drags you out of the room but it never triggered when Slagamemnon dragged one of my guys out.  I've turned my drag avoids on but is there a special way to get the flags to trigger returning to the safe-room if dragged out of the room?

**Comment by rpherbig** [comment]
Can you post a log?

**Comment by Kaesken** [comment]
Ah  yeah sorry, it happened on a character I don't have log recording on but I can see if I can catch one of my guys going there and drag them myself.

**Comment by Dartellum** [comment]
Can we close this issue?

**Comment by Kaesken** [comment]
Oops, sorry.  I totally forgot about this.  Closing!
