### ISSUE TITLE
Updated post text in INVENTORY - need equipmanager fix pushed.

### ISSUE THREAD

**Issue by Stormsocks** [rpherbig/dr-scripts#4188]
Currently have this starting at line 106 in equipmanager:

  def get_combat_items
    bput('inv combat', 'Type INVENTORY HELP for more options')
    snapshot = reget(40)
    if snapshot.grep(/All of your combat|You aren't wearing anything like that/).any? &&
       snapshot.grep(/Type INVENTORY HELP/).any?
      snapshot
        .map(&:strip)
        .reverse
        .take_while { |item| !['All of your combat:', "You aren't wearing anything like that."].include?(item) }
        .drop_while { |item| item != '[Type INVENTORY HELP for more options]' }
        .drop(1)
        .reverse
    else
      get_combat_items
    end
  end

It is hanging up because they changed the post text to "Use INVENTORY HELP"

Looks like it needs to be changed in three places - lines 107, 110 and 115.

**Comment by Stormsocks** [comment]
Looks like the same issue occurs in common-arcana at lines 259, 261 and 266.

**Comment by rpherbig** [comment]
@Stormsocks thanks for submitting this. Let us know if you see any more.

**Comment by vmw-connors** [comment]
I was about to open an MR @rpherbig  - yours is incomplete. There is a period in this line:

`-        .drop_while { |item| item != '[Type INVENTORY HELP for more options]' }`
`+        .drop_while { |item| item != '[Use INVENTORY HELP for more options.]' }`

**Comment by rpherbig** [comment]
Thank you @vmw-connors !
