### ISSUE TITLE
leaving Shard Thief guild

### ISSUE THREAD

**Issue by GreyhallowDR** [rpherbig/dr-scripts#4190]
For some reason this happens every time crossing-training leaves the thief guild after binning BnE items. When I run go2 manually from the guild it leaves just fine but something is different otherwise.

It's like the script isn't recognizing the room move/id. It gets stuck in a loop trying to go OUT 

https://pastebin.com/e6RfSxr7

**Comment by MahtraDR** [comment]
@GreyhallowDR Are you still seeing this? I just tried on my thief, and don't see this myself.

**Comment by MahtraDR** [comment]
@rpherbig this can be closed.
