### ISSUE TITLE
Problems during mapdb update for Shard Cleric Guild portals

### ISSUE THREAD

**Issue by vtcifer** [rpherbig/dr-scripts#4194]
I tried updating the mapdb last night for the Shard Cleric guildleader, so that both portals could be used.  This worked fine for me in both non-cleric and cleric testing, but broke this morning for some users.  For some reason, they were getting errors with the stringproc I put in to timeto for those portals to return nil if they're not a Cleric: `"13737"=>StringProc.new("DRStats.guild == 'Cleric' ? 0.2 : nil")` .  A user in lnet, and another user in discord reported that this failed:
```
,e echo("#{DRStats.guild}")
--- Lich: exec1 active.
--- Exception: uninitialized constant DRStats
exec1:1:in `_script'
--- Lich: exec1 has exited.
```

Both had drinfomon running, but could not access the DRStats class.  I get the following executing the same line:

```
,e echo("#{DRStats.guild}")
--- Lich: exec1 active.
[exec1: Cleric]
--- Lich: exec1 has exited.
```

**Comment by Tarhish** [comment]
So, I pulled up the map xml.  The only other place that uses DRStats in a stringproc is room 14351, which has:

```
@timeto={"14352"=>0.2, "12208"=>StringProc.new("Scripting::DRStats.circle >= 30 ? 0.2 : nil rescue nil")}
```

I'm wondering if this would work better.

**Comment by vtcifer** [comment]
Forgot to mention, I had them try that too, using :: to resolve to Scripting class from Lich itself, but got pretty much the same error.  
Since I can't reproduce, I really have no idea what's going on.  If anyone else has the same behavior (error when trying to directly reference guild method from DRStats), I'd be willing to create a map to share, but this broke the hell out of go2 for someone in Haven, and I really rather not break the map again.

**Comment by jandersson** [comment]
If i understand the problem correctly: There is no guarantee that a user of go2 has drinfomon running. What youre seeing is errors from users without drinfomon, so DRStats does not exist. My suggestion is to include a check in your StringProc for drinfomon (`script_running?` i think), and do business as usual, else you should do whatever is reasonable for a user without DRStats.

**Comment by vtcifer** [comment]
I thought that might be it as well, but did confirm at least one of the people having problems already had drinfomon running, so I didn't think it was that.

**Comment by jandersson** [comment]
🤔 It could be that they have an old version of ruby where the concept of `;trust` still exists. I believe this was why the skillrecorder script was made.

Go2 is trusted
DRStats is untrusted
So go2 cannot access DRStats... but it can access UserVars which is what skillrecorder writes your athletics skills, to for example

**Comment by jandersson** [comment]
I would honestly just suggest they upgrade ruby if this is the case... otherwise you or someone has to write some weird logic that writes to UserVars

**Comment by Tarhish** [comment]
That was it, I remember now. There was a problem where drinfomon was running but other scripts couldn't read it. It was if someone had trusted drinfomon

**Comment by vtcifer** [comment]
I'll give that a shot, I have a list of those who were having problems and I'll see if any of the are able to confirm ruby version.  

> DRStats is untrusted

DRStats, or drinfomon?

**Comment by jandersson** [comment]
Both, the drinfomon script implements the DRStats class, unless thats been changed.

**Comment by jandersson** [comment]
> DRStats, or drinfomon?

Yes ;)

drinfomon.lic should be implementing the DRStats class, unless thats been changed.

**Comment by vtcifer** [comment]
Still looking at this, just otherwise occupied.  

It's interesting that DRstats is in the mapdb already:
```Scripting::DRStats.circle >= 30 ? 0.2 : nil rescue nil;```
I assume the rescue nil is there to solve the "Oh crap, there's an error" part.  And since I think it's really only to get into a dead end, in an already low traffic area (Thieve's guild, master's den), problems don't crop up with path finding that much.

I'll try to look at updates to skillrecorder, and reaching out to those I know had issues in the past to test before doing any push to mapdb/pr.

**Comment by vtcifer** [comment]
Officially not supporting ruby versions lower than 2.5.5 (#5048) means these kinds of StringProcs can be safely added back in (once the mapdb is unlocked again).
