### ISSUE TITLE
Trade Update - Breaking Change in Shard

### ISSUE THREAD

**Issue by mtruitt** [rpherbig/dr-scripts#4197]
Now when trying to run Trade in Shard it now runs me to horse clan then endless loops. 

[trade]>RETURN CARAVAN

Please rephrase that command.
> 
| Going to find your caravan in the last-seen or nearest stable.

[trade: You're already here...]

[trade]>RETURN CARAVAN

Please rephrase that command.
> 
| Going to find your caravan in the last-seen or nearest stable.

[trade: You're already here...]

[trade]>RETURN CARAVAN

Please rephrase that command.
> 
| Going to find your caravan in the last-seen or nearest stable.

[trade: You're already here...]

[trade]>RETURN CARAVAN

Please rephrase that command.
> 
| Going to find your caravan in the last-seen or nearest stable.

[trade: You're already here...]

[trade]>RETURN CARAVAN

> 
Please rephrase that command.
> 
| Going to find your caravan in the last-seen or nearest stable.

[trade: You're already here...]

[trade]>RETURN CARAVAN

,k trade

**Comment by Tarhish** [comment]
I'll look at that.  I bet there's something wrong with the tagging for stables in that area.  But, from testing, the only reason it should be looking at stables is if you a.) have trade_use_stables: true set, or b.) you try to RENT a caravan and the clerk says you already have one checked out.

I suspect that it's the latter, maybe the caravan got lost and was auto-stabled, but just from looking at that log I can't tell.  If that's true and the horse-clan stable room is wrong, then this is what would happen.  Immediate workaround is to find which stable your caravan went to manually, then RETURN it, and restart the script.

If that's not what's happening then something else is wrong.

**Comment by Tarhish** [comment]
A couple other places are tagged as stables in the map atm, the royal mews and horse clan as examples.  I've done a review and tagged all the caravan stables as something different, so a quick change will stop it from visiting those, but if there's something else going wrong then I'd like to roll that up at the same time.

**Comment by Sarvatt** [comment]
that was me, I tagged stables where you can buy horses with stables before any of the trader stuff :)

**Comment by mtruitt** [comment]
I can confirm I did not have a caravan rented. I actually make sure I return it everyday just because I know it can get hung up like that sometimes.

**Comment by Tarhish** [comment]
Sarvatt!  Always glad to see you foiling my plans! 😄 

I'll disambiguate the map entries from the horsey people, since that's a good idea, but I still can't make it break like that in Theren or Zoluren.  I'll run down to shard and see if there's some unusual messaging from the clerks in that area.

**Comment by Tarhish** [comment]
```

[trade]>recall caravan
You don't recall having a caravan.
>
[trade: Response: You don't recall having a caravan.]
[trade: No caravan found]
--- Lich: go2 active.
[go2: ETA: 0:00:01 (6 rooms to move through)]

--- Lich: go2 has exited.
[trade]>rent caravan
The clerk nods and says, "All right, that's a 288 Dokoras fee for a rental...."

You count out your 288 Dokoras and pay the clerk, who sends his assistant out to get your transportation together.

>
--- Lich: go2 active.
--- Lich: go2 has exited.
[trade]>recall caravan
You seem to recall that you left your horse-drawn caravan right behind you.
>
[trade: Response: You seem to recall that you left your horse-drawn caravan right behind you]
[trade]>tell horse-drawn caravan to go faster
You tell your driver to speed up the pace, but he looks at you and says, "But your horse-drawn caravan is going as fast as it can go already!"
```

That's what I get down in Shard with trade_use_stable: false (default settings), which is what I assume is what you were talking about.  I will go ahead and adjust the map tags, but it wouldn't have mattered since it never tries to go to the stables.  If you get a log of this starting up let me know, because the only way I can reproduce it is to let my caravan idle out and while logged off and then try to start up in Shard.  After the next change it won't try to go to Horse Clan in that case, and just head to the nearest caravan stable.

**Comment by mtruitt** [comment]
It was actually getting hung up clearing out the storage box and then I would log after closeup but will go ahead and close this issue.
