### ISSUE TITLE
Low RT disarm identifies can cause pick to think that the disarm was succesful

### ISSUE THREAD

**Issue by vtcifer** [rpherbig/dr-scripts#4198]
Only thing I  can think of that happened here is that the Roundtime output somehow got picked up in disarm_speed, so that it thought it was disarmed.  

```
You get a sturdy iron crate from inside your haversack.
> 
[pick]>disarm my crate identify
> 
Looking closely into the keyhole, you spy what appears to be a pulsating ball with some sort of metal lacing around it.  The lacing runs to meet a coin sized piece of metal near the keyhole itself.
The iron crate's trap is a trivially constructed gadget which you can take down any time.
Roundtime: 1 sec.
[pick]>disarm my crate quick
R> 
...wait 1 seconds.
R> 
[pick]>disarm my crate analyze
Nothing on this crate has been disarmed, what could you possibly analyze?
> 
```

The ...wait should have been picked up by bput to trigger a redo, but wasn't for some reason, and matched against something else.  Since the only things that get passed to the bput are the failed disarm messages (not present), and the retry message (not present), and 'Roundtime', I think that it was the Roundtime text from the previous disarm ID.  

Looks to be maybe the same issue as #2552, which never had a fix?

**Comment by KatoakDR** [comment]
Same issue as #4316

This issue was fixed by:
* https://github.com/rpherbig/dr-scripts/pull/4799

Thank you

@rpherbig this may be closed
