### ISSUE TITLE
;trade confused by contract case

### ISSUE THREAD

**Issue by GreyhallowDR** [rpherbig/dr-scripts#4201]
When the script rummages your contract container it gets fooled by a contract case and thinks that you have an outstanding contract. Script stalls when it taps for contract but doesn't find one.

Workaround: Don't have a contract case in your designated contract container.
Possible fix: add a comma after contract on line 777 

    DRC.list_to_array(text).select { |item| item.include?('contract,') }

Not sure if that introduces other problems down the line but it seems to be running fine for me so far.

EDIT: Yes, it totally introduces problems down the road.

**Comment by Tarhish** [comment]
I always stored mine in the pockets of my coat, so I don't think I would've noticed a contract-case related problem.  I think replacing that with
```
    DRC.list_to_array(text).reject { |item| item.include?('contract case') }
                                       .select { |item| item.include?('contract') }
```

might work?

**Comment by MahtraDR** [comment]
Closing as nobody is doing trader-specific coding today.
