### ISSUE TITLE
Fang Cove missing from Blacksmithing/Weaponsmithing

### ISSUE THREAD

**Issue by TegCross** [rpherbig/dr-scripts#4206]
I think I've gathered most of the required info, but please contact me if you need me to run back and get anything else.

Spaces weren't staying so attaching the variables as a separate txt file

**Comment by TegCross** [comment]
blacksmithing:
  Fang Cove:
    npc: Phahoe
    npc_last_name: Phahoe
    npc-rooms:
      - 14877
      - 9129
      - 9130
      - 9131
      - 9132
      - 9133
      - 9134
      - 9135
      - 9136
    anvils:
      - south of 14881 (not mapped)
      - south of 14882 (not mapped)
    crucibles:
      - 14881
      - 14882
    grindstones:
      - south of 14881 (not mapped)
      - south of 14882 (not mapped)
    logbook: forging
    pattern-book: blacksmithing
    finisher: oil
    finisher-full: flask of oil
    finisher-room: 14793
    finisher-number: 6
    repair-room: 9143
    repair-npc: clerk
    stock-volume: 5
    stock-room: 9132
    stock-number 11
    stock-name: bronze ingot
    trash-room: 14882
    idle-room: 9136
====================================
Not sure where these go, if anywhere
makers mark: 9133
book shop: 9134
supply depot: 9135 #packets
tool-room: 14793

**Comment by TegCross** [comment]
`blacksmithing:
  Fang Cove:
    npc: Phahoe
    npc_last_name: Phahoe
    npc-rooms:
      - 14877
      - 9129
      - 9130
      - 9131
      - 9132
      - 9133
      - 9134
      - 9135
      - 9136
    anvils:
      - south of 14881 (not mapped)
      - south of 14882 (not mapped)
    crucibles:
      - 14881
      - 14882
    grindstones:
      - south of 14881 (not mapped)
      - south of 14882 (not mapped)
    logbook: forging
    pattern-book: blacksmithing
    finisher: oil
    finisher-full: flask of oil
    finisher-room: 14793
    finisher-number: 6
    repair-room: 9143
    repair-npc: clerk
    stock-volume: 5
    stock-room: 9132
    stock-number 11
    stock-name: bronze ingot
    trash-room: 14882
    idle-room: 9136
====================================
Not sure where these go, if anywhere
makers mark: 9133
book shop: 9134
supply depot: 9135 #packets
tool-room: 14793




`

**Comment by Sarvatt** [comment]
like you said, it's missing because it's not mapped. It's very difficult to map it since they use duplicate rooms, you can't just automap it without breaking crossing

**Comment by TegCross** [comment]
Oh, understood. Thank you, Sarvatt.

**Comment by Sarvatt** [comment]
I mean if a premie is up to it it could be mapped with peer tags :)

**Comment by TegCross** [comment]
I'm back with the 

> I mean if a premie is up to it it could be mapped with peer tags :)

I joined back up with the 3 month special, so I'm willing to map them if you can point me to the instructions. I've admittedly never touched mapping for fear of borking up things for others.

**Comment by TegCross** [comment]
Tried getting some help on the discord with peer tags, they didn't seem to think it could be done. I trust you though, if you find time to walk a map-virgin through this I'm willing to help anyway I can.
