### ISSUE TITLE
Pay-debt not paying large debts and script ending before sack retrieval

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#4215]
With the advent of burgle, debts are larger now when arrested.  Snippets from log below show the issue.  The pay-debt script ended, but because debt was not paid and sack not retrieved....hunting buddy sent poor Gab to hunt naked, in which she promptly died.

********

[pay-debt: message: With a resigned sigh, you hand your coins to the collector.  "Dis ain't all da debt, but dis is enough for now.  You still owe 1405250 Kronars dough - don't forget."  The collector grins and steps aside.]

[pay-debt: message: A burly Gor'Tog taps you on the shoulder and says, "Gabellia D'emibenit, roight?  I'm Barg, from da Debt Collector's Office.  I tink y'have sometin' I been sent t' collect."]

[pay-debt: message: The clerk counts out 750 copper Kronars and hands them over, making a notation in her ledger.] 

Then off to jail to collect sack:

[pay-debt: message: You realize you won't be allowed to access your items until you've paid off your debt to society here.]

[pay-debt: checked against [/you reach for your sack/i]]

[pay-debt: for command get Gabellia sack]

--- Lich: pay-debt has exited.

**Comment by MahtraDR** [comment]
Closing as not relevant today, alas.
