### ISSUE TITLE
;trader encumbrance issues (too much grass in feedbag)

### ISSUE THREAD

**Issue by BL4CKM4GICK** [rpherbig/dr-scripts#4218]
My low level trader is having encumbrance issues with the amount of grass ;trader is putting in the feedbag. Can this be looked at for an easy solution where we can control the amount of grass being collected. Thanks!

**Comment by GreyhallowDR** [comment]
Agreed! The script maintains way too much grass. A nearly starving caravan doesn't need more than 5 or 6 pieces I think. Just keeping 3-5 in the feedbag should always work. Even if it doesn't get the caravan fully fed the first time, the next offering minutes later definitely will after its been filled again.

**Comment by MahtraDR** [comment]
Closing this as nobody is working on trader-specific scripts today.
