### ISSUE TITLE
Doesn't recoggnize new deadfall messaging

### ISSUE THREAD

**Issue by Sagadin** [rpherbig/dr-scripts#4219]
[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 23]
[combat-trainer: message: [You're nimbly balanced and in better position.]]
[combat-trainer: message: * With inept movements, a fledgling forest gryphon slices wide at you.  You barely block with a gargoyle-hide targe with a reinforced design.  ]
[combat-trainer: message: [You're nimbly balanced with opponent in better position.]]
[combat-trainer: message: * Moving inexpertly, a baby forest gryphon rakes a set of large, sharp claws at you.  You dodge, barely stepping to one side.  ]
[combat-trainer: message: [You're nimbly balanced and in excellent position.]]
[combat-trainer: message: * Tentatively, a baby forest gryphon slices wide at you.  You partially block with a gargoyle-hide targe with a reinforced design.  ]
[combat-trainer: message: [You're nimbly balanced and in good position.]]
[combat-trainer: message: * With pathetic timing, a fledgling forest gryphon rakes a set of large, sharp claws at you.  You evade, stepping out of harm's way.  ]
[combat-trainer: message: [You're nimbly balanced and in good position.]]
[combat-trainer: message: * Looking as if this were a bad idea, a baby forest gryphon rakes a set of large, sharp claws at you.  You dodge, leaning just out of harm's reach.  ]
[combat-trainer: message: Claws of the Cougar  (14 roisaen)]
[combat-trainer: message: See the Wind  (17 roisaen)]
[combat-trainer: message: Earth Meld  (17 roisaen)]
[combat-trainer: message: Instinct  (18 roisaen)]
[combat-trainer: message: Wisdom of the Pack  (13 roisaen)]
[combat-trainer: message: Senses of the Tiger  (18 roisaen)]
[combat-trainer: message: [You're nimbly balanced and in very strong position.]]
[combat-trainer: message: * Ineptly, a baby forest gryphon rakes a set of large, sharp claws at you.  You partially block with a gargoyle-hide targe with a reinforced design.  ]
[combat-trainer: message: [You're nimbly balanced and in strong position.]]
[combat-trainer: message: * Attacking inexpertly, a fledgling forest gryphon rakes a set of large, sharp claws at you.  You barely block with a gargoyle-hide targe with a reinforced design.  ]
[combat-trainer: message: A baby forest gryphon's bobbed tail twitches fitfully.]
[combat-trainer: message:  * Kaldreth was just struck down! ]
[combat-trainer: message: The limestone rock rapidly decays away.]
[combat-trainer: checked against [/You pick up/i, /You get/i, /You need a free hand/i, /There isn't any more room/i, /You just can't/i, /push you over the item limit/i, /You stop as you realize the .* is not yours/i, /Stow what/i, /already in your inventory/i, /The .* is not designed to carry anything/i]]
[combat-trainer: for command stow rock]

The rock "rapidly decays away" after being stowed.  Recreated issue in Dusk Ogre and Baby Gryphons.

**Comment by Sagadin** [comment]
Error with using deadfall in an area where rocks fall to stun targets rather than a branch or limb.  Can be short circuited by typing "stow what" after it attempts to stow the rock.

**Comment by vtcifer** [comment]
While this can be solved with loot_subtractions, the stow message should probably be updated to include the decay as a match to the bput.  It occurs with rock as you listed here, and coral (sand sprites).

I've tested with my own ranger, and there are a couple of lines in combat-trainer that need the string 'rapidly decays away' added to the bput match, but my local repo is not in a valid state to commit/PR.  

I'll try to get my repo fixed over the next weekend, and if no one use has updated by then, take care of it.

**Comment by asechrest** [comment]
Is this still an issue? I could perhaps look into it as a second PR since my main is a Ranger.

**Comment by asechrest** [comment]
> Is this still an issue? I could perhaps look into it as a second PR since my main is a Ranger.

Answering my own questions - combat-trainer appears to have the "rapidly decays away" messaging added to the Stow bputs. My bet is that this issue can be closed.
