### ISSUE TITLE
Pick using QUICK when it should be using Careful

### ISSUE THREAD

**Issue by Cerelum** [rpherbig/dr-scripts#4226]
Alright so I've noticed that when I use the ;pick command, it will most of the time work great.  However in some instances it will attempt to disarm box quick, and fail, sometimes up to twenty times in a row.  I most of the time just ;k pick, then do the disarm careful and get it in one or two attempts.

I think the pick script should realize that it's failed QUICK after a few tries (two or three) and then automatically move to CAREFUL.

**Comment by Cerelum** [comment]
Just to give some context.

`You can unlock the ironwood crate with only minor troubles.
Roundtime: 5 sec.
sR>
[pick]>pick my crate quick
You deftly remove a lockpick from the lockpick ring and begin to work at quickly picking open the crate.
You are unable to make any progress towards opening the lock.
You return your lockpick to the lockpick ring.
Roundtime: 5 sec.
sR>
[pick]>pick my crate quick
You deftly remove a lockpick from the lockpick ring and begin to work at quickly picking open the crate.
You are unable to make any progress towards opening the lock.
You return your lockpick to the lockpick ring.
Roundtime: 5 sec.
sR>
[pick]>pick my crate quick
s>
You deftly remove a lockpick from the lockpick ring and begin to work at quickly picking open the crate.
You are unable to make any progress towards opening the lock.
You return your lockpick to the lockpick ring.
Roundtime: 6 sec.
sR>
[pick]>pick my crate quick
s>
You deftly remove a lockpick from the lockpick ring and begin to work at quickly picking open the crate.
You are unable to make any progress towards opening the lock.
You return your lockpick to the lockpick ring.
Roundtime: 5 sec.
sR>
[pick]>pick my crate quick
You deftly remove a lockpick from the lockpick ring and begin to work at quickly picking open the crate.
You are unable to make any progress towards opening the lock.
You return your lockpick to the lockpick ring.
Roundtime: 5 sec.
sR>
[pick]>pick my crate quick
s>
You deftly remove a lockpick from the lockpick ring and begin to work at quickly picking open the crate.
You are unable to make any progress towards opening the lock.
You return your lockpick to the lockpick ring.
Roundtime: 7 sec.
sR>
[pick]>pick my crate quick
You deftly remove a lockpick from the lockpick ring and begin to work at quickly picking open the crate.
You are unable to make any progress towards opening the lock.
You return your lockpick to the lockpick ring.
Roundtime: 5 sec.
sR>
[pick]>pick my crate quick
You deftly remove a lockpick from the lockpick ring and begin to work at quickly picking open the crate.
You are unable to make any progress towards opening the lock.
You return your lockpick to the lockpick ring.
Roundtime: 7 sec.
sR>
[pick]>pick my crate quick
Wild Magic Valkena just arrived.
s>
You deftly remove a lockpick from the lockpick ring and begin to work at quickly picking open the crate.
With a soft click, you remove your lockpick and open and remove the lock.
You discover another lock protecting the ironwood crate's contents as soon as you remove this one.
You return your lockpick to the lockpick ring.
Roundtime: 7 sec.`

**Comment by rpherbig** [comment]
Closed in #5001
