### ISSUE TITLE
Trim down starter yamls, name them by class

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#423]
Lets stop using our active character yamls as seeds. Remove thorny things like crafting, gem pouches, paired down weapon and gear lists, etc.

**Comment by rpherbig** [comment]
Let's name them obvious things like `SampleBarbarian-setup.yaml`, that way they're colocated in the directory.

**Comment by rpherbig** [comment]
Broke out the rest of the classes into separate issues, this was getting too big.
