### ISSUE TITLE
;clerk-tools alchemy store in Shard

### ISSUE THREAD

**Issue by jamckee24** [rpherbig/dr-scripts#4235]
;clerk-tools alchemy store doesn't seem to work in Shard. It takes me to a repair room and won't let me store alchemy tools there.

**Comment by jamckee24** [comment]
Sorry I just realized I made this mistake. It's enchanting that has the problem, not alchemy.

**Comment by Dartellum** [comment]
Hello,
Which room is it taking you to?

**Comment by jamckee24** [comment]
It is taking me to :

[Waystation, Ylono's Repair]
Room Number: 19270

He obviously won't store enchanting gear. Only wants to fix stuff.

**Comment by Hiinky** [comment]
Its because there is no enchanting tool room.

**Comment by MahtraDR** [comment]
@rpherbig Can close this.
