### ISSUE TITLE
Carving Workorder in Shard - Alabaster Deed

### ISSUE THREAD

**Issue by jamckee24** [rpherbig/dr-scripts#4236]
;workorders carving in Shard gets hung up Alabaster deeds. After it buys them and stows them, when it goes to grab them later, it tries to "get alabaster deed", but I believe it's called a rock deed.

**Comment by MahtraDR** [comment]
@Raykyn55 Is this still an issue today, do you know? Should we close this? Thanks!

**Comment by Raykyn55** [comment]
> 

I *think* so, yes, this was one of the issues I addressed with the rewrite in #6274
