### ISSUE TITLE
Enchanting - Script gets stuck when a brazier is occupied

### ISSUE THREAD

**Issue by brewguyver** [rpherbig/dr-scripts#4251]
Script goes into a loop trying to write on brazier with burin if a brazier is not cleaned off. This probably occurs when someone else hits an issue or a failure point. The command to clean the brazier doesn't work if the brazier isn't lit ... instead it needs to be manually cleaned off of all items. Here's the message that starts the loop:

[Putting an item on the brazier begins the enchanting process.  This process can enhance the item, or cause serious damage to it and the enchanter.  Put your item onto the brazier again in the next 30 seconds, to proceed.  You've been warned!]
>
**[enchant]>put my bone totem on enchanter's brazier
You must first clean off the brazier.**
>
**[enchant]>clean enchanter's brazier
The brazier is not currently lit, and so you feel it is safe to collect anything atop it.**
>

**Comment by MahtraDR** [comment]
Closing as stale.
