### ISSUE TITLE
workorders enchant artificing fails to check crafting containers, repeatedly buys items as part of workorders as result

### ISSUE THREAD

**Issue by brewguyver** [rpherbig/dr-scripts#4255]
- Workorders artificing does not seem to be checking the following crafting_container: or crafting_items_in_container:
- If a workorder completion fails or gets stuck in a loop, the new purchased items - bone totems and sigil-scrolls specifically are not consumed
- Error occurs when there are already unfinished items on a brazier that is no longer in active use (has gone cold). This bug was reported in a separate issue earlier today (script needs to be updated to manually clear a cold brazier (message 1: You must first clean off the brazier. message 2: The brazier is not currently lit, and so you feel it is safe to collect anything atop it.)
- If workorders is run via command line (;workorders artificing), then the script gets stuck and has to receive manual intervention. However, if artificing run by hunting_buddy or crossing_training, the script treats the failure after message 2 as completion of the crafting set, quickly iterates through N number of "bundle with logbook" attempts, "completes," and then tries to do the workorders soon after
- The end result of the hunting_buddy / crossing_training issue is a backpack full of unused totems and sigil-scrolls

Fixing the container check logic would consume the extra materials and prevent buildup.

This may be resulting from the same "clean the brazier" problem reported earlier. That is because when workorders artificing fails to clean the brazier and breaks as part of crossing-training / training manager (see clean the brazier issue), it iterates through completing and trying to bundle each work order item and then "finishing" workorders / enchant scripts as if they were done core

**Comment by Dartellum** [comment]
Correct, those are not checked as the premise is to order and consume the items for the workorder. I could have the script check for existing sigils and components. However, this could cause other challenges if people are harvesting sigils and storing them in the crafting_container or crafting_items_in_container. The challenge is consuming the wrong sigils or components. 

I will play with the logic for purchasing this weekend.

As for the brazier in the Society, I can take a peek and see if I can tweak it.

**Comment by MahtraDR** [comment]
Closing as this has been fixed since.
