### ISSUE TITLE
Enchant issue with meditate fount

### ISSUE THREAD

**Issue by cfrisby77** [rpherbig/dr-scripts#4259]
[enchant]>meditate fount
You attempt to meditate, but have trouble concentrating.
>
[enchant: *** No match was found after 15 seconds, dumping info]
[enchant: messages seen length: 5]
[enchant: message: Gauge Flow  (14 roisaen)]
[enchant: message: Mantle of Flame  (6 roisaen)]
[enchant: message: Gauge Flow  (14 roisaen)]
[enchant: message: Mantle of Flame  (7 roisaen)]
[enchant: message: You attempt to meditate, but have trouble concentrating.]
[enchant: checked against [/Roundtime/i]]
[enchant: for command meditate fount]

[enchant]>meditate fount
You attempt to meditate, but have trouble concentrating.
>
A maid bustles in, wielding her dust cloth vigorously.  She empties a waste bin into her pail, taking the trash with her as she leaves.
>
[enchant: *** No match was found after 15 seconds, dumping info]
[enchant: messages seen length: 5]
[enchant: message: A maid bustles in, wielding her dust cloth vigorously.  She empties a waste bin into her pail, taking the trash with her as she leaves.]
[enchant: message:  * Loukhindal was just struck down! ]
[enchant: message: Gauge Flow  (12 roisaen)]
[enchant: message: Mantle of Flame  (4 roisaen)]
[enchant: message: You attempt to meditate, but have trouble concentrating.]
[enchant: checked against [/Roundtime/i]]
[enchant: for command meditate fount]

**Comment by Hiinky** [comment]
Do you have insight into why  you couldn't concentrate?
```
[enchant]>meditate fount
You attempt to meditate, but have trouble concentrating.
```
Was it wounds? Really lack of concentration?

**Comment by cfrisby77** [comment]
Not off hand. This occured at the crafting hall brazier. when i changed it back to use my own brazier, it worked fine. no woulds. did not check concentratoin.

**Comment by Hiinky** [comment]
Without more information on how/when/why it happened it's hard to recreate and fix.  If it happens again please try to capture your health and concentration levels.

**Comment by cfrisby77** [comment]
Ok tested it again and i think i found the issue. It looks like someone left a fount on the floor in the workroom. and it was trying to meditate on that one rather than the one in the brazier. is there a way to have the script make sure the room is clean.

**Comment by cfrisby77** [comment]
Might have it fixed. Testing it for a bit. will send pull request soon
