### ISSUE TITLE
You move over to ***** kill, a giant black leucro, and get ready to search it!

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#427]
When in a room with a buddy hunting, starting combat-trainer and come time to loot sometimes get

You move over to Persons name kill, a giant black leucro, and get ready to search it!
Not a huge issue as the script times out 15 seconds then starts back up, but would be awesome if it didnt.

**Comment by xtremenerdrage** [comment]
Also this

You stop as you realize the brass chest is not yours.

**Comment by xtremenerdrage** [comment]
Also please add a syntax for specific name to teach a skill if possible
Arrive at room and one of the yamls is set up to "teach * to name" 
the other can have auto listen on

**Comment by rcuhljr** [comment]
First pass in place, I think there's a similar not yours messaging for skinning, but I couldn't reproduce it with my alts. add friends to `hunting_buddies:` and report messaging that still needs corrected.
