### ISSUE TITLE
Moonwatch not updating "Sun" variable

### ISSUE THREAD

**Issue by KillashandreaDR** [rpherbig/dr-scripts#4277]
About 12pm PDT on 5/2, moonwatch appears to have broken.

"sun" variable is reading as {"day"=>true, "night"=>false, "timer"=>-630} and is not updating when the Sun sets/rises.

I have restarted dependency and moonwatch.  I have logged off/on.  I have deleted the "sun" variable.  None of that works.  moonwatch updates the variable back to the old negative timer (other than that the timer is getting larger and larger).

**Comment by rpherbig** [comment]
@rcuhljr @jandersson

**Comment by jandersson** [comment]
Noticing this as well. I was suspecting a moonbot not running, but after running my own for a few hours this still hasn't changed the negative timer.

**Comment by rcuhljr** [comment]
Oh I see the issue, should be fixed, start a new issue if it doesn't correct in a few hours (provided someone swaps a moonbot on).
