### ISSUE TITLE
Make "smith" style scripts for sew/shape/carve

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#428]
See #419 (https://github.com/rpherbig/dr-scripts/pull/419#discussion_r66292603). Do similar work for other crafting skills.

**Comment by ericmeek** [comment]
This is something I'd like to work on getting sorted and implemented while I work on lesser fixes. I'd like to get an idea in my head on what your vision of it was. From the way workorders-->smith-->forge is, I'm thinking this is what the rest should look like? Correct me if I'm wrong.

workorders-->smith-->forge (weaponsmithing/blacksmithing/armorsmithing)
workorders-->engineer-->craft (shaping/carving/tinkering)
workorders-->alchemy-->mix (remedies/reactancts/cooking)
workorders-->enchant-->whatever (whatever it's gonna be)

Or should the last scripts be divided? Smith calls a weaponsmith, blacksmith or armorsmith script. Engineer calls a shaping, carving, tinkering script, etc?

Or... should the division be in the "2nd level". Workorder calls a "shaping setup" script, then a shape script. Workorder calls a "carving setup" script then a carve script?

Understand what I mean?

**Comment by rpherbig** [comment]
I'm not sold on smith/forge being good names since I don't think it is intuitive what the difference is or when each should be called.

But I am in favor of workorders-->some helper-->crafting script. To paraphrase myself from another comment I can't find offhand, the crafting script only has to know the mechanics of crafting. The helper buys items (e.g. ingots and parts), finds a room, etc. This keeps the logic nicely contained. Smith and forge are a good model for this (except for #450, which is an example of something I want to avoid), even if I don't like their names.

I'm undecided on having one script per crafting skill vs one per crafting discipline. I kind of like the one-per-discipline approach to keep scripts as small and single-purpose as possible. My concern there would be code reuse/duplication, but I think we could make judicious use of the `common-*` files to manage that.

**Comment by ericmeek** [comment]
A thought on the script structure, not necessarily the names. 

workorders
	\_forgeprep
		\_smith
	\_engineerprep
		\_shape/carve
		\_tinker
		\_fletch
	\_alchemyprep
		\_mix
	\_outfitprep
		\_knit
		\_sew

stamp
temper
lighten
reinforce
repair
smelt
refine
hone
balance
spin
weave

**Comment by ericmeek** [comment]
A thought on the script structure, not necessarily the names. 

- workorders
    - forgeprep
        - smith
    - engineerprep
        - shape/carve
        - tinker
        - fletch
    - alchemyprep
        - mix
    - outfitprep
        - knit
        - sew

stamp
temper
lighten
reinforce
repair
smelt
refine
hone
balance
spin
weave

**Comment by rcuhljr** [comment]
One per discipline feels like overkill, smith has minimal code that's discipline specific, it feels like we'd duplicate the whole thing. I don't care what the naming convention is as long as the high level 'smith' equivalent makes sense and is easy to call on it's own.

**Comment by ericmeek** [comment]
Okay so I feel the ideas for workorder, low level and "enhancement" scripts are clear. Consensus on the prep level being discipline specific or not? I'm kind of leaning towards one script for all disciplines myself.
