### ISSUE TITLE
bootstrap error

### ISSUE THREAD

**Issue by khrispyb** [rpherbig/dr-scripts#4280]
Hi 

Tried to work this out but failed - any thoughts on what might be going on here?  This is a fresh install of lich - only scripts that dont pull from my yaml like go2 seem to be working, others give the below error.  Thanks!

[You are standing up.]
>
--- Lich: alias service started
--- Lich: lnet active.
--- Lich: repository active.
--- Lich: dependency active.
[repository: map database is up-to-date]

--- Welcome to LNet.  I think so, Brain, but why does a forklift have to be so big if all it does is lift forks?

[repository: done]
[repository: scripts are up-to-date]
--- Lich: repository has exited.
>
[dependency: latest version of lich fork already downloaded.]
;training-manager
--- Lich: training-manager active.
[bootstrap: *** Failed to find a script named '' ***]
[bootstrap: *** Please report this to Etreu, Sheltim, or https://github.com/rpherbig/dr-scripts/issues  ***]
--- Lich: error: uninitialized constant TrainingManager::DRC
Did you mean?  DRb
	training-manager:8:in `<class:TrainingManager>'
	training-manager:7:in `_script'
--- Lich: training-manager has exited.

**Comment by rpherbig** [comment]
Try running `;common` and then `;training-manager` again

**Comment by khrispyb** [comment]
>;common
[bootstrap: *** Failed to find a script named '' ***]
[bootstrap: *** Please report this to Etreu, Sheltim, or https://github.com/rpherbig/dr-scripts/issues ***]
>

**Comment by rpherbig** [comment]
Can you `;e UserVars.bootstrap_debug=true` and then try `;common`?

**Comment by khrispyb** [comment]
Hi, thanks - this is what came up:

>;e UserVars.bootstrap_debug=true
--- Lich: exec1 active.
--- Lich: exec1 has exited.
;common
CR - starting:["spellmonitor", "drinfomon"]
[bootstrap: ]
BS::
BS:Running
[bootstrap: *** Failed to find a script named '' ***]
[bootstrap: *** Please report this to Etreu, Sheltim, or https://github.com/rpherbig/dr-scripts/issues ***]
CR:done:["spellmonitor", "drinfomon"]
>;training-manager
--- Lich: training-manager active.
CR - starting:["common", "drinfomon", "common-travel"]
[bootstrap: ]
BS::
BS:Running
[bootstrap: *** Failed to find a script named '' ***]
[bootstrap: *** Please report this to Etreu, Sheltim, or https://github.com/rpherbig/dr-scripts/issues ***]
CR:done:["common", "drinfomon", "common-travel"]
--- Lich: error: uninitialized constant TrainingManager::DRCT
training-manager:9:in `<class:TrainingManager>'
training-manager:7:in `_script'
--- Lich: training-manager has exited.

**Comment by BinuDR** [comment]
Try this.
;repos download autostart.lic
log out, close your front end
log back in

**Comment by rcuhljr** [comment]
Could be a trust issue? Or they're running the wrong version of lich. You can see that dependency is calling `    bootstrapper = force_start_script('bootstrap', script_names)` with the two script names in question, however force_start_script isn't passing on those names to bootstrap successfully. So either their lich version is doing something wrong or [ArgParser](https://github.com/rpherbig/dr-scripts/blob/master/dependency.lic#L24) can't read their values for some reason for just this user.

**Comment by khrispyb** [comment]
>
--- Lich: alias service started
--- Lich: lnet active.
--- Lich: dependency active.
--- Lich: repository active.
>
[repository: downloading map database...]

--- Welcome to LNet. I think so, Brain, but this time you put the trousers on the chimp.
[dependency: latest version of lich fork already downloaded.]
[repository: deleting old map databases...]
[repository: loading map database...]
[repository: done]
[repository: scripts are up-to-date]
--- Lich: repository has exited.
;repos download autostart.lic
--- Lich: repository active.
[repository: downloading autostart.lic in 3 seconds... (;k repository to cancel)]
*************************IMPORTANT!*************************
Closing your front end does NOT necessarily drop
your character from the game! Type QUIT or EXIT!
*************************IMPORTANT!*************************
PvP has strict rules! See NEWS 5 15, NEWS 5 24, NEWS 5 25!
Scripting is ok, but you must be responsive! NEWS 5 17!
Vulgarity is not allowed in public! NEWS 5 7!
*************************IMPORTANT!*************************
 
Enjoy DragonRealms? Vote Today!
Visit Top Mud Sites! <http://www.topmudsites.com/vote-DragonRealms.html>
 
Login Tip:
Flee the authorities in Therengia, but cannot remember the details? RECALL knows!
Read More: RECALL WARRANT
[To disable these login tips, see HELP TIPS.]
>
[repository: done]
--- Lich: repository has exited.
* Log-on system converted 43% of your character's field experience into earned rank. *
>exit
--- Lich: dependency has exited.
--- Lich: lnet has exited.


*
* Disconnected from server. [7:11 pm]
*



--- Lich process exited with code 0

--- Open "/usr/local/Cellar/ruby/2.7.1_2/bin/ruby /Users/christopherbritton/lich/lich.rbw --dragonrealms --frostbite"
Connecting ...

--- Lich v4.12.1f is active. Type ;help for usage info.
Please wait for connection to game server.
Welcome to DragonRealms (R) v2.00
Copyright 2020 Simutronics Corp.
All Rights Reserved
 
----------------------------------------------------------------------------
Last login : Mon May 4 20:10:47 ET 2020
Logoff : Mon May 4 20:11:05 ET 2020
----------------------------------------------------------------------------
 
[Jademist River, Garden Path]
To the east the path leads to a small garden, hidden away amidst a small grove of fruit trees. To the west, the way leads back to the fury of the river and the main path.
Obvious paths: east, west.
 
[You are standing up.]
>
--- Lich: alias service started
--- Lich: lnet active.
--- Lich: repository active.
--- Lich: dependency active.
[repository: map database is up-to-date]
******************************************************

--- Welcome to LNet. I think so, Brain, but just how will we get the weasel to hold still?
*** Please check NEWS NEXT for unread NEWS items. ***
******************************************************
>
[repository: done]
>
[dependency: latest version of lich fork already downloaded.]
[repository: scripts are up-to-date]
--- Lich: repository has exited.
;training-manager
--- Lich: training-manager active.
[bootstrap: *** Failed to find a script named '' ***]
[bootstrap: *** Please report this to Etreu, Sheltim, or https://github.com/rpherbig/dr-scripts/issues ***]
--- Lich: error: uninitialized constant TrainingManager::DRC
Did you mean? DRb
training-manager:8:in `<class:TrainingManager>'
training-manager:7:in `_script'
--- Lich: training-manager has exited.

**Comment by BinuDR** [comment]
Give us the output of these two commands:
;autostart list
;e echo list_autostarts

**Comment by khrispyb** [comment]
>
--- Lich: alias service started
--- Lich: lnet active.
--- Lich: repository active.
--- Lich: dependency active.
[repository: map database is up-to-date]

--- Welcome to LNet. I think so, Brain! You draw the bath and I'll fetch the alka-seltzers and candles!
[repository: done]
[repository: scripts are up-to-date]
--- Lich: repository has exited.
[dependency: latest version of lich fork already downloaded.]
>;autostart list

--- Global autostart scripts: alias, lnet, repository (args: download-updates), dependency

--- autostart scripts: (none)
 
>;e echo list_autostarts
--- Lich: exec1 active.
[exec1: []]
--- Lich: exec1 has exited.
******************************************************
*** Please check NEWS NEXT for unread NEWS items. ***
******************************************************
>;e echo(list_autostarts)
--- Lich: exec1 active.
[exec1: []]
--- Lich: exec1 has exited.
>

**Comment by rcuhljr** [comment]
What operating system? Can you do an `;e help_me` and link the pastebin it puts in lnet here? Most of my next ideas would require some more intensive logging/debugging so someone who's still actively playing might want to field that one. I'd echo out `variable` at the top of bootstrap to make sure it's getting the arguments, if it's not then someone needs to inspect the version of lich.rb they're on.

**Comment by Hiinky** [comment]
He's on Mac.  Ruby 2.7.1.  Autostart will not work.  we reinstalled dependency but not lich itself.  Was referred to another Mac user and is currently working on those instructions.

**Comment by khrispyb** [comment]
Yep, macOS Catalina

**Comment by khrispyb** [comment]
Boiled down to a ruby version error. MacOS Catalina comes with 2.7.1 so I downgraded to 2.6.6 with these steps https://gswiki.play.net/Mac_Installation_-_Lich_(software) and help from Doug to run homebrew and clean up the other ruby version. Whew.  Thank for all the help.  Now just struggling to get Frostbite to run with lich if anyone has experience with that... thanks again
