### ISSUE TITLE
burgle.lic attempted to go window in the bedroom

### ISSUE THREAD

**Issue by cfrisby77** [rpherbig/dr-scripts#4285]
https://pastebin.com/uipwDqTg

Burgle got stuck after RT and tried to `go window` in the Bedroom.

**Comment by vtcifer** [comment]
I believe this is a race condition with move() from core lich.  #4393 should resolve this when finalized.

**Comment by Dartellum** [comment]
Was this resolved with PR 4393? Can we close this?

**Comment by cfrisby77** [comment]
I cannot recall, but i think so.
