### ISSUE TITLE
Grinding needs to deal with brush running out

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#429]
No text yet.

**Comment by rpherbig** [comment]
We could probably do a check like `workorders` does for carving (item: polish) where it gets discarded and a new one bought if the old had too few uses left. Do we know what that threshold would be?

**Comment by rcuhljr** [comment]
Threshold would probably have to be ~8 ish uses. I'd rather just backlog this until we can get a sample of it occurring.
