### ISSUE TITLE
;forge lighten mask -- not recognizing the output when it reads chapter 5.

### ISSUE THREAD

**Issue by Tyrranny** [rpherbig/dr-scripts#4293]
[forge]>read my book
              -=    Chapter 5 : Armor Enhancements    =-

 Page 1: metal armor lightening                  Page 4: metal armor repair
 Page 2: metal armor tempering                   Page 5: rare-metal armor tempering
 Page 3: metal armor reinforcing
>
[forge: ** No match was found after 15 seconds, dumping info]
[forge: messages seen length: 11]
[forge: message: Noumena  (3 roisaen)]
[forge: message: Membrach's Greed  (21 roisaen)]
[forge: message: Finesse  (9 roisaen)]
[forge: message: Platinum Hands of Kertigen  (6 roisaen)]
[forge: message: Trabe Chalice  (intact, 20 roisaen)]
[forge: message: [DRPrime]-DR:Hrpuff: "and then, if its one you can use. train up that skill pretty high then study that orb"]
[forge: message: [DRPrime]-DR:Velicar: "You see nothing unusual"]
[forge: message:  Page 3: metal armor reinforcing                 ]
[forge: message:  Page 2: metal armor tempering                   Page 5: rare-metal armor tempering]
[forge: message:  Page 1: metal armor lightening                  Page 4: metal armor repair]
[forge: message:               -=    Chapter 5 : Armor Enhancements    =-]
[forge: checked against [/Page \d+:\s(?:some|a|an)?\slightening/i]]
[forge: for command read my book]
[forge]>turn my book to page 
Which page do you wish to turn the a book of master armorsmithing instructions to?

I know that ;forge is calling another function for this I think anyway...
turn_to("page #{find_recipe(5, 'lightening')}")
That function apparently is not matching the reg ex to what my Master Armorsmithing Book shows.

If I am doing something wrong I am sorry but the command could not be any easier.

**Comment by rcuhljr** [comment]
Looks like no one tried to lighten anything in the 4 years it's existed. Fix pushed to master, restart dependency and it should work.

**Comment by Tyrranny** [comment]
Thank You :)
