### ISSUE TITLE
Request stow tk_ammo to be added to combat-trainer.lic in the before dying section

### ISSUE THREAD

**Issue by cfrisby77** [rpherbig/dr-scripts#4298]
It should be fput("stow #{@tk_ammo}")  but if falls outside the main script so it is not getting the settings. I tried a few things to make it work but it is still not getting the settings.

**Comment by Dartellum** [comment]
Hello,
Do you mean when you stop the script manually? I just have tk_ammo: razor and it picks up the razor when done. Razor is not in my loot_additions either.

**Comment by cfrisby77** [comment]
Yes, when you manually kill the script so in the "before_dying do" section.

**Comment by cfrisby77** [comment]
figured it out. going to submit pull request.
