### ISSUE TITLE
Smoke.lic has many errors

### ISSUE THREAD

**Issue by Tyrranny** [rpherbig/dr-scripts#4299]
I just started using this, but I see some glaring errors that lead me to believe maybe noone else is using it. Or perhaps things are race related and my Halfling gets them for another reason.

After lighting Cigar it sheathes <weapon> and looks for 'you put' only, but the text is 'you sheath'. I added this to my script and it works well now.
81 bput("sheath my #{@lighter_info['blade']}", 'You Sheath', 'You put')

MIssing a LOT of the exhale checks to confirm a successfull exhale. I have not added them all, but below is what I have found so far. you can see all messaging for every smoke image and Skill level at the Smoke Images Wiki page.
line 56 bput(output.to_s, 'You blow', 'You expel', 'You breathe out', 'You cast', 'You need to have inhaled')

**Comment by Tyrranny** [comment]
I will add more as I find them, I have editted my script6 several times, it keeps updating. I know I have done other edits, but forget them.

**Comment by Tyrranny** [comment]
Honestly the Exhale lingo should be thrown out, and just wait on roundtime... there are a lot of different messaging with regard to different images and skill levels.

**Comment by Tyrranny** [comment]
I just changed images and got another one...'You Exhale'
added tothe same line 56.
Unless you swap it to a waitrt type command.

**Comment by Hiinky** [comment]
Just my two cents.  This was intended to be a fluff script and is not likely to be updated quickly.  If you're willing to make the changes and upload them, they can be reviewed and merged.

**Comment by Tyrranny** [comment]
Can you tell me how to change the exhale line to just wait for roundtime instead of lookign for specific output?

**Comment by Tyrranny** [comment]
OK I have a new script with fixes, how do I upload it so you can update SMOKE.lic to work right?

**Comment by jandersson** [comment]
Click the pencil icon while viewing the script to edit it. Make your changes. After saving the changes, you'll get walked through making a pull request. Follow the steps and it should show up under this repo's pull requests.

**Comment by Tyrranny** [comment]
Thanks, I was able to do a pull request last week and get it updated. It's working great now for me.
