### ISSUE TITLE
Artificing....

### ISSUE THREAD

**Issue by Rob-PainTrain** [rpherbig/dr-scripts#4301]
Seems to not be matching the correct text when it picks up the scroll or something.

[enchant]>get my artificing book

You get a book of master artificing instructions from inside your hitman's backpack.
> 
[enchant]>turn my book to chapter 3

> 
You turn your book to chapter 3, entitled "Magical Foci".
> 
[enchant]>read my book

              -=    Chapter 3 : Magical Foci    =-

 Page 1: training ritual focus                   Page 11: advanced elemental ritual focus
 Page 2: a basic lunar ritual focus              Page 12: a destructive focus
 Page 3: basic elemental ritual focus            Page 13: advanced life ritual focus
 Page 4: basic life ritual focus                 Page 14: a fire focus
 Page 5: an accurate focus                       Page 15: advanced holy ritual focus
 Page 6: basic holy ritual focus                 Page 16: a frost focus
 Page 7: an efficient focus                      Page 17: advanced AP ritual focus

[enchant]>turn my book to page 6

 Page 8: advanced lunar ritual focus             Page 18: an electric focus
 Page 9: basic untuned ritual focus              Page 19: advanced untuned ritual focus
 Page 10: a lethal focus                         

> 
You turn your book to page 6, instructions for crafting basic holy ritual focus.
> 
[enchant]>study my artificing book

You scan the holy focus instructions with a glance and confidently discern most of the design's minutiae. (3/5)
You now feel ready to begin the crafting process.
Roundtime: 7 sec.
R> 
R> 
R> 
[enchant]>put my artificing book in my hitman backpack

> 
> 
You put your book in your hitman's backpack.
> 
[enchant]>get my brazier

You get an orichalcum brazier from inside your hitman's backpack.
> 
[enchant]>get my bone totem from my hitman backpack

You get a plain bone totem from inside your hitman's backpack.
> 
[enchant]>put my bone totem on brazier

You glance down at the smoking brazier and reconsider if you wish to begin enchanting.

[Putting an item on the brazier begins the enchanting process.  This process can enhance the item, or cause serious damage to it and the enchanter.  Put your item onto the brazier again in the next 30 seconds, to proceed.  You've been warned!]
> 
[enchant]>put my bone totem on brazier

With a flick, you pop open the brazier's lid.  Tiny motes briefly encircle the almond-shaped flame now burning within the brazier.  Carefully you place your totem atop the brazier.

Once finished you sense an imbue spell will be required to continue enchanting.
Roundtime: 8 sec.

You need another mana fount to continue crafting a plain bone totem.  WAVE a functional mana fount at the a plain bone totem to align the item with the fount's focusing properties.  Then continue the process with the casting of an imbue spell.
R> 
R> 
> 
[enchant]>tap my fount

You tap a fragile rough mana fount inside your hitman's backpack.
> 
[enchant]>get my fount

You get a fragile rough mana fount from inside your hitman's backpack.
> 
[enchant]>wave my fount at bone totem on brazier

You slowly wave the fount over and around the totem.  Motes of light rise up from the brazier and encircle your hand.  Satisfied the bonding is complete, you place the fount atop the totem.
> 
[enchant]>get my fey-bone rod

You get a fey-bone rod topped with a carved claw tightly clenching a polished sunstone from inside your hitman's backpack.
> 
[enchant]>wave fey-bone rod at bone totem on brazier

The spell is channeled through the fount hanging above, and down into the totem.  With expert precision you rapidly direct each stream into place around the totem.
Roundtime: 9 sec.

You need another abolition primary sigil to continue the enchanting process.  You believe you can STUDY the sigil and then TRACE it on the unfinished item to prepare it for continued scribing.

[Sigils can be added to the artifact to continue crafting.]

R> 
R> 
R> 
R> 
[enchant]>put my fey-bone rod in my hitman backpack

You put your rod in your hitman's backpack.
> 
[enchant]>get my abstract burin

You get a simple abstract burin from inside your hitman's backpack.
> 
[enchant]>put my abstract burin in my hitman backpack

You put your burin in your hitman's backpack.
> 
[enchant]>get abolition sigil

You pick up an intricate abolition sigil-scroll comprised of broad strokes.

> 
> 
[DRPrime]-DR:Highfire: "I um...giggitty?"

> 
> 
You feel a tickle as your millipede explores your ear.
> 
[enchant: *** No match was found after 15 seconds, dumping info]

[enchant: messages seen length: 6]

[enchant: message: You feel a tickle as your millipede explores your ear.]

[enchant: message: Nonchalance  (15 roisaen)]

[enchant: message: Noumena  (18 roisaen)]

[enchant: message: Turmar Illumination  (11 roisaen)]

[enchant: message: [DRPrime]-DR:Highfire: "I um...giggitty?"]

[enchant: message: You pick up an intricate abolition sigil-scroll comprised of broad strokes.]

[enchant: checked against [/You get/i]]

[enchant: for command get abolition sigil]

[enchant]>study my abolition sigil

You study the sigil-scroll and commit the design to memory.
Roundtime: 14 sec.
R> 
R> 
R> 
[enchant]>trace bone totem on brazier

Recalling the intricacies of the sigil, you trace its form over the totem with your finger and prepare to begin scribing it more permanently with a burin.
Roundtime: 2 sec.
R> 
[enchant]>get my abstract burin

You get a simple abstract burin from inside your hitman's backpack.
> 
[enchant]>scribe bone totem on brazier with my abstract burin

You lean in towards your totem and begin scribing marks along it with a simple abstract burin.  In and out you weave a decisive tapestry of patterns across the totem with your burin.

The totem's material struggles to accept the sigil scribing.
Roundtime: 21 sec.

You need another primary sigil to continue the enchanting process.  You believe you can STUDY the sigil and then TRACE it on the unfinished item to prepare it for continued scribing.

[Sigils can be added to the artifact to continue crafting.]
R> 
R> 
R> 
R> 
R> 
[enchant]>put my abstract burin in my hitman backpack

You put your burin in your hitman's backpack.
> 
[enchant]>get induction sigil

You pick up an intricate induction sigil-scroll comprised of broad strokes.

> 
> 
> 
[enchant: *** No match was found after 15 seconds, dumping info]

[enchant: messages seen length: 7]

[enchant: message: Nonchalance  (14 roisaen)]

[enchant: message: Noumena  (17 roisaen)]

[enchant: message: Turmar Illumination  (10 roisaen)]

[enchant: message: Nonchalance  (14 roisaen)]

[enchant: message: Noumena  (17 roisaen)]

[enchant: message: Turmar Illumination  (10 roisaen)]

[enchant: message: You pick up an intricate induction sigil-scroll comprised of broad strokes.]

[enchant: checked against [/You get/i]]

[enchant: for command get induction sigil]

[enchant]>study my induction sigil

You study the sigil-scroll and commit the design to memory.
Roundtime: 14 sec.
R> 
R> 
R> 
[enchant]>trace bone totem on brazier

Recalling the intricacies of the sigil, you trace its form over the totem with your finger and prepare to begin scribing it more permanently with a burin.
Roundtime: 1 sec.
R> 
[enchant]>get my abstract burin

You get a simple abstract burin from inside your hitman's backpack.
> 
[enchant]>focus bone totem on brazier

> 
You adjust the brazier's intensity and peer closely at the totem.  Deft adjustment to the brazier accurately reveals where further scribing should be made.
Roundtime: 18 sec.
R> 
R> 
R> 
R> 
[DRPrime]-DR:Zefkhyr: "Prereni are deer >.>"

[enchant]>scribe bone totem on brazier with my abstract burin

You lean in towards your totem and begin scribing marks along it with a simple abstract burin.  Through effortless control of the burin you capture the pattern in razor-sharp detail.
Roundtime: 17 sec.
R> 
R> 
R> 
You've gained a new rank in your knowledge of utility magic.
R> 
R> 
[enchant]>scribe bone totem on brazier with my abstract burin

You lean in towards your totem and begin scribing marks along it with a simple abstract burin.  Through effortless control of the burin you capture the pattern in razor-sharp detail.
Roundtime: 20 sec.
R> 
The clouds part slightly to reveal patches of blue sky.
R> 
R> 
[DRPrime]-DR:Barder: "Lycette are you on in any form, your order is done"

R> 
R> 
R> 
[enchant]>scribe bone totem on brazier with my abstract burin

You lean in towards your totem and begin scribing marks along it with a simple abstract burin.  In and out you weave a decisive tapestry of patterns across the totem with your burin.
Roundtime: 17 sec.
R> 
R> 
R> 
R> 
R> 
[enchant]>scribe bone totem on brazier with my abstract burin

You lean in towards your totem and begin scribing marks along it with a simple abstract burin.  With skilled flourishes of the burin you capture the sigil pattern's precision and complexity.

The traced sigil pattern blurs before your eyes, making it difficult to follow.
Roundtime: 20 sec.
R> 
[DRPrime]-DR:Highfire: "I've had them as pigs in my mind for....30 years"

R> 
R> 
You've gained a new rank in your practice as an alchemist.
R> 
R> 
R> 
[DRPrime]-DR:Highfire: "Oh god what is real anymore"

[DRPrime]-DR:Rivalae: "pretty sure they're deer and peccary are pig-types"

[enchant]>meditate fount on brazier

You lean in close to the fount, close your eyes and calmly meditate.  A melodic tone emitted by the fount guides the sharp sigil lines forming in your mind.
Roundtime: 13 sec.
R> 
R> 
R> 
R> 
> 
[enchant]>scribe bone totem on brazier with my abstract burin

You lean in towards your totem and begin scribing marks along it with a simple abstract burin.  With skilled flourishes of the burin you capture the sigil pattern's precision and complexity.
Roundtime: 17 sec.
R> exp lore all

Circle: 150
Showing Lore skills that you have skill in.

          SKILL: Rank/Percent towards next rank/Amount learning/Mindstate Fraction
         Forging:    201 65% clear          (0/34)     Engineering:    219 57% learning       (3/34)
      Outfitting:    237 79% scrutinizing  (17/34)         Alchemy:    231 03% ruminating     (8/34)
      Enchanting:    204 54% absorbing     (15/34)     Scholarship:    798 34% clear          (0/34)
 Mechanical Lore:    670 24% clear          (0/34)       Appraisal:    774 51% clear          (0/34)
     Performance:    117 45% clear          (0/34)         Tactics:    572 06% clear          (0/34)
         Trading:   1140 19% clear          (0/34)

Total Ranks Displayed: 5163
Lore Average: 469    Skills Included: 11.
Time Development Points: 2259  Favors: 30  Deaths: 23  Departs: 2
Rested EXP Stored: 3 hours  Usable This Cycle: 2:45 hours  Cycle Refreshes: 9:39 hours
Overall state of mind: clear
EXP HELP for more information

R> 
R> 
R> 
R> 
R> 
R> 
[enchant]>scribe bone totem on brazier with my abstract burin

You lean in towards your totem and begin scribing marks along it with a simple abstract burin.  In and out you weave a decisive tapestry of patterns across the totem with your burin.

The totem's material struggles to accept the sigil scribing.
Roundtime: 21 sec.
R> 
R> 
R> 
R> 
R> 
R> 
[enchant]>focus bone totem on brazier

...wait 1 second.
R> 
R> 
[enchant]>focus bone totem on brazier

You adjust the brazier's intensity and peer closely at the totem.  Added shadows provide perfect contrast to the totem's surface, revealing what was hidden.

Once finished you sense an imbue spell will be required to continue enchanting.
Roundtime: 15 sec.
R> 
R> 
R> 
[enchant]>put my abstract burin in my hitman backpack

You put your burin in your hitman's backpack.
> 
[enchant]>get my fey-bone rod

You get a fey-bone rod topped with a carved claw tightly clenching a polished sunstone from inside your hitman's backpack.
> 
[enchant]>wave fey-bone rod at bone totem on brazier

The spell is channeled through the fount hanging above, and down into the totem.  After focusing the streams into ordered groups you then direct them into exacting positions.
Roundtime: 13 sec.
The spell's energies settle upon the totem and seal off the streams of mana.  With the enchanting process completed, you believe it is safe to collect your things once more.
You collect the fount and place it at your feet.
You collect the totem and place it at your feet.

R> 
R> 
R> 
> 
[enchant]>put my fey-bone rod in my hitman backpack

> 
You put your rod in your hitman's backpack.
> 
[enchant]>get my abstract burin

You get a simple abstract burin from inside your hitman's backpack.
> 
[enchant]>put my brazier in my hitman backpack

You put your brazier in your hitman's backpack.
> 
[enchant]>put my abstract burin in my hitman backpack

You put your burin in your hitman's backpack.
> 
[enchant]>get my fount

You pick up the fount lying at your feet.
> 
[enchant]>put my fount in my hitman backpack

You put your fount in your hitman's backpack.
> 
[enchant]>get my bone totem

You pick up the totem lying at your feet.
> 
--- Lich: enchant has exited.

[workorders]>get my enchanting logbook

You get an enchanting work order logbook from inside your hitman's backpack.
> 
[workorders]>bundle my bone totem with my logbook

You notate the totem in the logbook then bundle it up for delivery.
> 
[workorders]>stow left

You put your logbook in your hitman's backpack.
> 
[workorders]>read my enchanting logbook

You open your logbook and sort through its contents.
This logbook is tracking a work order requiring you to craft basic holy ritual focus from any material.  You must bundle and deliver 2 more within the next 104 roisaen.

This logbook has been used to complete:
 0 Easy, 99 Challenging and 0 Hard Artificing work orders.
 0 Easy, 0 Challenging and 0 Hard Binding work orders.
 0 Easy, 0 Challenging and 0 Hard Invoking work orders.
> 
--- Lich: enchant active.

--- Lich: buff active.

--- Lich: buff has exited.

[enchant]>get my artificing book

You get a book of master artificing instructions from inside your hitman's backpack.
> 
[enchant]>turn my book to chapter 3

> 
You turn your book to chapter 3, entitled "Magical Foci".
> 
[enchant]>read my book

              -=    Chapter 3 : Magical Foci    =-

 Page 1: training ritual focus                   Page 11: advanced elemental ritual focus
 Page 2: a basic lunar ritual focus              Page 12: a destructive focus
 Page 3: basic elemental ritual focus            Page 13: advanced life ritual focus
 Page 4: basic life ritual focus                 Page 14: a fire focus
 Page 5: an accurate focus                       Page 15: advanced holy ritual focus
 Page 6: basic holy ritual focus                 Page 16: a frost focus
 Page 7: an efficient focus                      Page 17: advanced AP ritual focus
 Page 8: advanced lunar ritual focus             Page 18: an electric focus
 Page 9: basic untuned ritual focus              Page 19: advanced untuned ritual focus

[enchant]>turn my book to page 6

 Page 10: a lethal focus                         

> 
You turn your book to page 6, instructions for crafting basic holy ritual focus.
> 
[enchant]>study my artificing book

You scan the holy focus instructions with a glance and confidently discern most of the design's minutiae. (3/5)
You now feel ready to begin the crafting process.
Roundtime: 4 sec.
R> 
R> 
[enchant]>put my artificing book in my hitman backpack

> 
You put your book in your hitman's backpack.
> 
[enchant]>get my brazier

You get an orichalcum brazier from inside your hitman's backpack.
> 
[enchant]>get my bone totem from my hitman backpack

You get a plain bone totem from inside your hitman's backpack.
> 
[enchant]>put my bone totem on brazier

> 
You glance down at the smoking brazier and reconsider if you wish to begin enchanting.

[Putting an item on the brazier begins the enchanting process.  This process can enhance the item, or cause serious damage to it and the enchanter.  Put your item onto the brazier again in the next 30 seconds, to proceed.  You've been warned!]
> 
[enchant]>put my bone totem on brazier

With a flick, you pop open the brazier's lid.  Tiny motes briefly encircle the almond-shaped flame now burning within the brazier.  Carefully you place your totem atop the brazier.

Once finished you sense an imbue spell will be required to continue enchanting.
Roundtime: 18 sec.

You need another mana fount to continue crafting a plain bone totem.  WAVE a functional mana fount at the a plain bone totem to align the item with the fount's focusing properties.  Then continue the process with the casting of an imbue spell.
R> 
R> 
R> 
R> 
R> 
R> 
[enchant]>tap my fount

You tap a fragile rough mana fount inside your hitman's backpack.
> 
[enchant]>get my fount

You get a fragile rough mana fount from inside your hitman's backpack.
> 
[enchant]>wave my fount at bone totem on brazier

You slowly wave the fount over and around the totem.  Motes of light rise up from the brazier and encircle your hand.  Satisfied the bonding is complete, you place the fount atop the totem.
> 
[enchant]>get my fey-bone rod

You get a fey-bone rod topped with a carved claw tightly clenching a polished sunstone from inside your hitman's backpack.
> 
[enchant]>wave fey-bone rod at bone totem on brazier

The spell is channeled through the fount hanging above, and down into the totem.  After focusing the streams into ordered groups you then direct them into exacting positions.
Roundtime: 14 sec.

You need another abolition primary sigil to continue the enchanting process.  You believe you can STUDY the sigil and then TRACE it on the unfinished item to prepare it for continued scribing.

[Sigils can be added to the artifact to continue crafting.]

R> 
R> 
R> 
Your millipede industriously cleans its back, combing it clean with first one leg, then another.
R> 
R> 
R> 
[enchant]>put my fey-bone rod in my hitman backpack

You put your rod in your hitman's backpack.
> 
[enchant]>get my abstract burin

You get a simple abstract burin from inside your hitman's backpack.
> 
[enchant]>put my abstract burin in my hitman backpack

You put your burin in your hitman's backpack.
> 
[enchant]>get abolition sigil

You pick up an intricate abolition sigil-scroll comprised of broad strokes.

> 
> 
> 
> 
> 
> 
[enchant: *** No match was found after 15 seconds, dumping info]

[enchant: messages seen length: 8]

[enchant: message: Nonchalance  (9 roisaen)]

[enchant: message: Noumena  (13 roisaen)]

[enchant: message: Turmar Illumination  (6 roisaen)]

[enchant: message: Nonchalance  (9 roisaen)]

[enchant: message: Noumena  (13 roisaen)]

[enchant: message: Turmar Illumination  (6 roisaen)]

[enchant: message:  * Zombie Slayer Agorol joins the adventure.]

[enchant: message: You pick up an intricate abolition sigil-scroll comprised of broad strokes.]

[enchant: checked against [/You get/i]]

[enchant: for command get abolition sigil]

[enchant]>study my abolition sigil

You study the sigil-scroll and commit the design to memory.
Roundtime: 12 sec.
R> 
R> 
R> 
[enchant]>trace bone totem on brazier

Recalling the intricacies of the sigil, you trace its form over the totem with your finger and prepare to begin scribing it more permanently with a burin.
Roundtime: 1 sec.
R> 
[enchant]>get my abstract burin

You get a simple abstract burin from inside your hitman's backpack.
> 
[enchant]>scribe bone totem on brazier with my abstract burin

You lean in towards your totem and begin scribing marks along it with a simple abstract burin.  With skilled flourishes of the burin you capture the sigil pattern's precision and complexity.
Roundtime: 19 sec.

You need another primary sigil to continue the enchanting process.  You believe you can STUDY the sigil and then TRACE it on the unfinished item to prepare it for continued scribing.

[Sigils can be added to the artifact to continue crafting.]
R> 
R> 
R> 
R> 
R> 
[enchant]>put my abstract burin in my hitman backpack

You put your burin in your hitman's backpack.
> 
[enchant]>get induction sigil

You pick up an intricate induction sigil-scroll comprised of broad strokes.

> 
> 
> 
[enchant: *** No match was found after 15 seconds, dumping info]

[enchant: messages seen length: 4]

[enchant: message: Nonchalance  (9 roisaen)]

[enchant: message: Noumena  (12 roisaen)]

[enchant: message: Turmar Illumination  (5 roisaen)]

[enchant: message: You pick up an intricate induction sigil-scroll comprised of broad strokes.]

[enchant: checked against [/You get/i]]

[enchant: for command get induction sigil]

[enchant]>study my induction sigil

> 
You study the sigil-scroll and commit the design to memory.
Roundtime: 14 sec.
R> 
R> 
R> 
R> 
[enchant]>trace bone totem on brazier

**Comment by Dartellum** [comment]
Was this resolved? From the first part of the log it looks like the burin already had something on it. Did you move to your crafting room or trying to use the Society’s?

**Comment by MahtraDR** [comment]
Closing as addressed in the time since.
