### ISSUE TITLE
On new install, bootstrap failing other scripts, traced to either drinfomon.lic or common.lic

### ISSUE THREAD

**Issue by robbintt** [rpherbig/dr-scripts#4306]
I tested this on workorders, I also use `DRC` et al for a number of custom scripts that also are bombing on similar missing imports.
```
> ;workorders artificing
[bootstrap: *** Failed to find a script named '' ***]
[bootstrap: *** Please report this to Etreu, Sheltim, or https://github.com/rpherbig/dr-scripts/issues  ***]
--- Lich: error: uninitialized constant WorkOrders::DRCC
?workorders:10:in `&lt;class:WorkOrders>'
?workorders:8:in `_script'
```

**Comment by rpherbig** [comment]
This looks like #4280

@robbintt are you on a Mac?

**Comment by robbintt** [comment]
Yes, catalina but using a ruby docker base image in a custom client. Maybe I need to use a different ruby version in the docker env.

**Comment by rpherbig** [comment]
That seems likely. Let us know if that fixes it (or doesn't).

**Comment by robbintt** [comment]
Looks like I am on: `ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]`

I will try setting the ruby version in the other issue thread shortly.

**Comment by Hiinky** [comment]
I can confirm we had someone else recently with 2.7.1 on a Mac causing problems and downgrading fixed his issues.

**Comment by robbintt** [comment]
I can verify this was the issue, I switched to `ruby:2.6.6` and everything works.

https://hub.docker.com/_/ruby?tab=tags
