### ISSUE TITLE
base-lumber and go2 - room not navigable

### ISSUE THREAD

**Issue by Sagadin** [rpherbig/dr-scripts#4314]
Can we have room 2717 commented out or removed from base-lumber please?  Go2 is not able to move there and Kalinandara informs me that this particular go2 issue isn't one that can be fixed at this time.

**Comment by Sagadin** [comment]
Apparently this is not an issue if you have over 500 Athletics... not sure if there's a workaround for sub 500 athletics folks

**Comment by jandersson** [comment]
Is this the tree you can fall out of south of shard? If so it might be fixable by making the timeto to climb to tree artificially very high.

**Comment by Hiinky** [comment]
Its not only the the check. the rooms are missing movement tags and it randomly takes more than one cllimb to move from 2717 to 2718.  When the random extra climb appears, there is no movement tag and the description is another room entirely.

**Comment by jandersson** [comment]
Alright, sounds like the best bet is to comment it out then and maybe comment "under construction pending mapping improvement" or something like that
