### ISSUE TITLE
pick does not wait for disarm to be confirmed before moving on to pick

### ISSUE THREAD

**Issue by LuckyThiefDR** [rpherbig/dr-scripts#4316]
I've seen this happen 3 times in the same way. Pick will enter the disarm command and then immediately enter the pick identify command without waiting for feedback. If the disarm fails or there are additional traps, pick blows the trap by picking the lock.

---

[pick]>get my crate from my lootpouch
You get a sturdy mahogany crate from inside your cloth lootpouch.
>
[pick]>disarm my crate identify
>
You notice a tiny needle with a rust colored discoloration on its tip hidden next to the keyhole.
The mahogany crate's trap is a trivially constructed gadget which you can take down any time.
Roundtime: 1 sec.
[pick]>disarm my crate quick
>
[pick]>pick my crate ident
You quickly work at disarming the crate.
You work with the trap for a while but are unable to make any progress.
You get the distinct feeling your manipulation caused something to shift inside the trap mechanism.  This is not likely to be a good thing.
Roundtime: 1 sec.
>
...wait 1 seconds.
>
[pick]>pick my crate ident
>
The lock is a trivially constructed piece of junk barely worth your time.
However, a sturdy mahogany crate is not fully disarmed, making any chance of picking it unlikely.
Roundtime: 1 sec.
>
[pick]>pick my crate quick
>
You deftly remove a lockpick from the lockpick ring and begin to work at quickly picking open the crate.
You realize very quickly that this was a very bad idea...
With a barely audible click, a tiny needle near the crate's lock springs out and stabs you painfully in the finger.  Looking at the needle, you notice with horror the rust colored coating on the tip.
You are poisoned!
You return your lockpick to the lockpick ring.
Roundtime: 1 sec.

**Comment by rcuhljr** [comment]
Might be a race condition. Someone could rework pick to change sections like [this](https://github.com/rpherbig/dr-scripts/blob/master/pick.lic#L390-L391) to use flags to match the disarm difficulty and only match on roundtime for the bput, preventing a return on the first line of the disarm message which then fires off the next bput that matches on the roundtime from the previous message.

**Comment by LuckyThiefDR** [comment]
Got me again, here's another log of it:

---

You get a poorly made iron caddy from inside your cloth lootpouch.
>
[pick]>disarm my caddy identify
>
While inspecting the caddy patiently, you see what appears to be a small, swollen animal bladder recessed inside the keyhole.
This trap is a laughable matter, you could do it blindfolded!
Roundtime: 1 sec.
[pick]>disarm my caddy quick
>
[pick]>pick my caddy ident
You quickly work at disarming the caddy.
With a precise hand, you gently remove the string that holds the bladder shut from the locking mechanism, rendering it safe.
You believe that the caddy is not yet fully disarmed.
Roundtime: 1 sec.
>
The lock is a trivially constructed piece of junk barely worth your time.
However, a poorly made iron caddy is not fully disarmed, making any chance of picking it unlikely.
Roundtime: 1 sec.
>
[pick]>pick my caddy quick
>
[my-sanow]>gaze my sanowret crystal
You deftly remove a lockpick from the lockpick ring and begin to work at quickly picking open the caddy.
You realize very quickly that this was a very bad idea...
Moving with the grace of a pregnant goat, you carelessly flick at the piece of metal causing a lace to rupture the sphere.  Electricity leaps through the laces and focuses upon the iron disc before forming into a bolt of man-made lighting.  It strikes you in the chest and sends you airborne!
You return your lockpick to the lockpick ring.
Roundtime: 1 sec.

**Comment by LuckyThiefDR** [comment]
Here are my settings, in case it's relevant:

stop_pick_on_mindlock: false
pick_blind: false
skip_lockpick_ring_refill: true
lockpick_container: lockpick ring
lockpick_type: grandmaster
harvest_traps: false
picking_box_source: lootpouch

---
[pick]>get my chest from my lootpouch
You get a cracked driftwood chest from inside your cloth lootpouch.
>
[pick]>disarm my chest identify
>
You find a series of openings on the front of the chest concealing the points of several wickedly barbed crossbow bolts.
The driftwood chest's trap is a trivially constructed gadget which you can take down any time.
Roundtime: 1 sec.
[pick]>disarm my chest quick
>
[pick]>pick my chest ident
You quickly work at disarming the chest.
You work with the trap for a while but are unable to make any progress.
Roundtime: 1 sec.
>
This lock is a laughable matter, you could do it blindfolded!
However, a cracked driftwood chest is not fully disarmed, making any chance of picking it unlikely.
Roundtime: 1 sec.
>
[pick]>pick my chest blind
>
With a dramatic flourish, you pull out a strip of cloth and tie it around your head, covering your eyes.

You then deftly remove a lockpick from the lockpick ring and begin to work at somehow blindly picking open the chest.
You realize very quickly that this was a very bad idea...
Just as your ears register the sound of a sharp snap, a crossbow bolt flies out the front of the chest right into your body!
A crossbow bolt lodges lightly in your left leg.
You realize that despite this mishap, the chest still has more to torment you with.
You return your lockpick to the lockpick ring.
Roundtime: 4 sec.

**Comment by LuckyThiefDR** [comment]
Here's a new iteration of what looks like the same bug happening in a different part of the script (picking and opening without waiting for feedback):

---

[pick]>get my chest from my lootpouch
You get a mud-stained brass chest from inside your cloth lootpouch.
>
[pick]>disarm my chest identify
Right above the lock inside the keyhole, you see a tiny metal tube just poking out of a small wad of brown clay.
The brass chest's trap is a trivially constructed gadget which you can take down any time.
Roundtime: 1 sec.
>
[pick]>disarm my chest quick
You quickly work at disarming the chest.
With ever so much agility, you stick your fingernail into the tip of the clay and gently slide the tiny tube out of it and toss it aside.
Roundtime: 1 sec.
>
[pick]>pick my chest ident
>
This lock is a laughable matter, you could do it blindfolded!
Roundtime: 1 sec.
[pick]>pick my chest blind
>
[pick]>open my chest
>
With a dramatic flourish, you pull out a strip of cloth and tie it around your head, covering your eyes.

You then deftly remove a lockpick from the lockpick ring and begin to work at somehow blindly picking open the chest.
You are unable to make any progress towards opening the lock.
You return your lockpick to the lockpick ring.
Roundtime: 4 sec.
>
...wait 4 seconds.
>
[pick]>open my chest
It is locked.
>
[pick]>dismantle my chest 
You must first open the brass chest before you attempt to dismantle it.
>
[pick: *** No match was found after 15 seconds, dumping info]
[pick: messages seen length: 9]
[pick: message: Khri Focus  (9 roisaen)]
[pick: message: Khri Safe  (37 roisaen)]
[pick: message: Khri Hasten  (37 roisaen)]
[pick: message: Khri Sight  (37 roisaen)]
[pick: message: Khri Focus  (9 roisaen)]
[pick: message: Khri Safe  (37 roisaen)]
[pick: message: Khri Hasten  (37 roisaen)]
[pick: message: Khri Sight  (37 roisaen)]
[pick: message: You must first open the brass chest before you attempt to dismantle it.]
[pick: checked against [/repeat this request in the next 15 seconds/i, /Roundtime/i, /You must be holding the object you wish to dismantle/i]]
[pick: for command dismantle my chest ]
[pick]>get my trunk from my lootpouch
>
You get a dull steel trunk from inside your cloth lootpouch.

**Comment by LuckyThiefDR** [comment]
[pick]>disarm my chest identify
>
While inspecting the chest patiently, you see what appears to be a small, swollen animal bladder recessed inside the keyhole.
The driftwood chest's trap is a trivially constructed gadget which you can take down any time.
Roundtime: 1 sec.
[pick]>disarm my chest quick
>
[pick]>pick my chest ident
You quickly work at disarming the chest.
You work with the trap for a while but are unable to make any progress.
Roundtime: 1 sec.
>
The lock is a trivially constructed piece of junk barely worth your time.
However, a mud-stained driftwood chest is not fully disarmed, making any chance of picking it unlikely.
Roundtime: 1 sec.
[pick]>pick my chest quick
>
You deftly remove a lockpick from the lockpick ring and begin to work at quickly picking open the chest.
You realize very quickly that this was a very bad idea...
With a cautious hand, you attempt to undo the string tying the bladder to the locking mechanism only to be greeted with a loud "Poof" followed by a cloud of small particles that flow from the chest and drift through the air, gagging you!
You are diseased!
You return your lockpick to the lockpick ring.
Roundtime: 1 sec.

**Comment by KatoakDR** [comment]
This issue was fixed by:
* https://github.com/rpherbig/dr-scripts/pull/4799

Thank you

@rpherbig this may be closed
