### ISSUE TITLE
Workorders: Stuck on neverending loop

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#4319]
Seems to only happen with the red flowers that I've noticed.

https://pastebin.com/qACV7NBY

And it just keeps repeating "[remedy]>crush my red flowers with my pestle" over and over again.

**Comment by Kaesken** [comment]
So I added this to my script:
```
workorder_recipes:
  remedies:
    - a body draught
    - a face draught
    - some body ointment
    - some face ointment
    - a neck potion
    - a head potion
    - an abdomen potion
    - a chest potion
    - some neck salve
    - some back salve
    - some abdominal salve
    - some eye salve
    - some chest salve
    - some head salve
    - a neck potion
    - some abdominal tonic
    - an abdomen potion
    - some chest tonic
    - a chest potion
    - some head tonic
    - a head potion
    - some back tonic
    - a back potion
    - some eye tonic
    - an eye potion
    - some skin tonic
    - a skin potion
    - some limb tonic
    - a limb potion
    - some neck tonic
    - some abdominal ungent
    - some chest ungent
    - some head ungent
    - some back ungent
    - some eye ungent
    - some eye salve
    - some skin ungent
    - some skin salve
    - some limb ungent
    - some limb salve
    - some neck ungent
```
And now it's stuck at the ordering:  https://pastebin.com/SJ2WqDqL

**Comment by jandersson** [comment]
>Seems to only happen with the red flowers that I've noticed.
>
>https://pastebin.com/qACV7NBY
>
>And it just keeps repeating "[remedy]>crush my red flowers with my pestle" over and over again.

This looks like the remedy script is breaking somewhere. I dont think it's related to workorders.lic aside from the recipe it told remedy.lic to brew.  Do you remember what recipe it was? It might help

**Comment by Kaesken** [comment]
Sorry, got busy and I can't remember but I put my settings like this now:
```
craft_max_mindstate: 31
workorder_min_items: 3
workorder_max_items: 10
workorder_cash_on_hand: 20000
train_workorders:
# - Blacksmithing
# - Shaping
# - Tailoring
 - Remedies
workorder_diff:
  remedies: easy
```
And it works again but it's not going beyond 1/34 mindstate which is a bummer.  Anytime I put it above 'easy' it keeps going on a neverending loop of asking for workorders until it gives up and moves out of workorders.

**Comment by Dartellum** [comment]
Right, 500 times it loops asking. Did you obtain techniques? If so, that could cause you to not obtain certain workorders. Do you know what items you are asked to make when it does loop for challenging workorders? That would help. 

Also, I have a PR in for the override to work with non Society bought herbs; meaning you forage what you need.

**Comment by MahtraDR** [comment]
Workorders has been completely rewritten since this was an issue. Closing.
