### ISSUE TITLE
Issue with ;go2 in Misenseor abbey

### ISSUE THREAD

**Issue by jonathan-stricker** [rpherbig/dr-scripts#4322]
this issue just started this morning, bu go2 seems to have some sort of error when trying to navigate in the dark area of the abbey where resuscitants are. When I get to the first room, it walks into the second and then freezes into a loop, with the following error:

[go2]>go gate
What were you referring to?
>
[go2: move: failed]
[go2: restarting script...]
[go2: ETA: 0:00:18 (92 rooms to move through)]
[go2]>go gate
What were you referring to?
>
[go2: move: failed]
[go2: restarting script...]

This happens whether I call go2 manually, or if training-manager or hunting-buddy are trying to find a room in the resuscitants hunting area. This just started happening this morning, anyone make any edits to the map or go2? I'm running divine radiance in the area so it shouldn't be an issue of darkness.

**Comment by Sarvatt** [comment]
that area returns the dark room data in the xml even if you have a light source sometimes, resuscitants are a no go with lich unless moved to and from manual.

**Comment by jonathan-stricker** [comment]
Ahh okay downer, thanks @Sarvatt! I guess it was working yesterday because I ended up in that very first room by the gate, lich can navigate out of there but any other room and then it gets lost in the xml. okay I'll do that area manually, thanks!
