### ISSUE TITLE
problem rooms for go2, bescort - new rooms for base-mining

### ISSUE THREAD

**Issue by LuckyThiefDR** [rpherbig/dr-scripts#4328]
These rooms in the Riverhaven west wilds are water rooms and need to wait for roundtime:

8621
8620
8622
11096
8612
8611
8610
8609
15076
8614
8615
8616
8617
8618

---

There are additional mining rooms adjacent to dark_tunnels. They could be accessible by go2 if the above list of water rooms is fixed. Or, they could be made accessible by a bescort to connect 8575 to 8579 by kneeling, go passage, waiting to come out the other side, and standing.

  - 8579
  - 8576
  - 8577
  - 8578
  - 8584
  - 8586
  - 8587
  - 8588
  - 8583
  - 8582
  - 8581
  - 8585
  - 8580

---

These rooms in the Theren moat are water rooms and need to wait for roundtime:

6995
6996
6997
7003
7004

**Comment by jandersson** [comment]
>These rooms in the Riverhaven west wilds are water rooms and need to wait for roundtime

Don't really understand this. My understanding is that room transition roundtime should be handled by default. Can you post an log or describe whats going on?

**Comment by LuckyThiefDR** [comment]
Alright, here is a log showing the issues with the riverhaven west gate water area.

start: room #602
go2: room #8618

note: After these tests, I reduced typeahead from 5 to 3 and had the same problem, just with fewer failed move commands.

[Riverhaven West Wilds, Meadow]
A lone waxy-leafed bush covered with bright pink blossoms pokes above the tall meadow grass.  Exposed bush roots extend through the grass and out over a bare spot of ground that slopes down to a rocky creek bank to the north.  
Obvious paths: southwest, west.
Room Number: 602
>
Your body below the waist is dripping with water.  Pools of it are forming all around you.
>
--- Lich: go2 active.
[go2: ETA: 0:00:02 (12 rooms to move through)]
[go2]>southwest
You saunter southwest.
[Riverhaven West Wilds, Meadow]
The bleached half-buried skull of a large rat shows starkly against the dark soil of the meadow.  A patch of daisies grows around it as if planted in memoriam by a mourning rodent relative.  
Obvious paths: northeast, southwest, west, northwest.
Room Number: 600
>
[go2]>southwest
[go2]>go trail
[go2]>ne
[go2]>n
[go2]>n
You saunter southwest.
[Riverhaven West Wilds, Meadows]
[go2]>nw
To the east at the end of a somewhat muddy looking trail is a small stand of trees circling a small inland pond.  You also see a winding path.
Obvious paths: northeast, west, northwest.
Room Number: 591
>
[Sylvan Pond, Mud Flats]
[go2]>nw
Higher ground combined with runoff from the pond has created a muddy swamp.  Puddles of water intersperse with rivulets that travel to a deep depression beneath a hollow log.  You also see a muddy trail.
Obvious paths: northeast.
Room Number: 8623
>
You saunter northeast.
[Sylvan Pond, Mud Flats]
[go2]>northwest
The water of the pond seems to have backed up over land that was once dry.  Several toppled tree trunks are all that remain of the willows that grew here.  
Obvious paths: north, southwest, northwest.
Room Number: 8621
>
Roundtime: 1 sec.
You wade north, moving through the still water.
[Sylvan Glade, Pond]
Shaded by the branches of the willow trees, the pond water is comfortably cool and clean.  
Obvious paths: north, south, west.
[go2]>west
Room Number: 8622
>
...wait 1 seconds.
>
You can't swim in that direction.
>
You can't swim in that direction.
>
You can't swim in that direction.
>
Roundtime: 1 sec.
You wade west, moving through the still water.
[Sylvan Glade, Dam]
A jumbled pile of logs, brush and other forest debris forms a natural dam at the western end of the pond.  Extending out from the tangle is a half submerged willow tree trunk.  
Obvious paths: northeast, east, southeast.
[go2]>northwest
Room Number: 8620
>
You can't swim in that direction.
>
You feel fully rested.
>
[go2: restarting script...]
[go2: ETA: 0:00:01 (7 rooms to move through)]
[go2]>northeast
Roundtime: 1 sec.
You wade northeast, moving through the still water.
[Sylvan Glade, Lily Pads]
Free from the shadows of the trees to the east, the water sparkles in the light of the Elanthian stars.  
Obvious paths: south, southwest, northwest.
Room Number: 8620
>
[go2]>nw
[go2]>nw
[go2]>northwest
[go2]>west
[go2]>northwest
You feel fully rested.
>
Roundtime: 1 sec.
You wade northwest, moving through the still water.
[Sylvan Glade, Creek Inlet]
[go2]>west
Water from a deep creek rushes into a small inland pond.  
Obvious paths: southeast, west, northwest.
Room Number: 11096
>
...wait 1 seconds.
>
...wait 1 seconds.
>
...wait 1 seconds.
>
...wait 1 seconds.
>
Roundtime: 1 sec.
You wade west, moving against the light current at an angle.
[Riverhaven West Wilds, South Creek Bank]
To the east, the creek widens into a small, placid inland pond surrounded by a stand of delicately drooping willow trees. The stony bank of the creek rises to the south.  
Obvious paths: east, northwest.
Room Number: 8612
>
[go2: restarting script...]
[go2: ETA: 0:00:01 (6 rooms to move through)]
[go2]>east
Roundtime: 1 sec.
You wade east, moving with the light current.
[Sylvan Glade, Creek Inlet]
Water from a deep creek rushes into a small inland pond.  
Obvious paths: southeast, west, northwest.
Room Number: 11096
>
You feel fully rested.
>
[go2]>northwest
[go2]>northwest
[go2]>west
[go2]>northwest
[go2]>west
Roundtime: 1 sec.
You wade northwest, moving against the light current.
[Riverhaven West Wilds, North Creek Bank]
The creek bed dead ends here with the rise of a perpendicular cliff to the east.  
Obvious paths: southeast, northwest.
Room Number: 8614
>
...wait 1 seconds.
>
...wait 1 seconds.
>
...wait 1 seconds.
>
...wait 1 seconds.
>
[go2: restarting script...]
[go2: ETA: 0:00:00 (4 rooms to move through)]
[go2]>northwest
Roundtime: 1 sec.
You wade northwest, moving against the light current.
[Riverhaven West Wilds, North Creek Bank]
Rapidly-running water obscures the view of the creek bed, but dark shapes indicate the presence of rocks fairly close to the surface of the creek.  
Obvious paths: southeast, west.
Room Number: 8615
>
You feel fully rested.
>
[go2]>west
[go2]>northwest
[go2]>west
Roundtime: 1 sec.
You wade west, moving against the light current at an angle.
[Riverhaven West Wilds, North Creek Bank]
Movement other than the flow of the current can be seen beneath the somewhat turbulent water of the creek.  You also see a high bank.
Obvious paths: east, northwest.
Room Number: 8616
>
...wait 1 seconds.
>
...wait 1 seconds.
>
[go2: restarting script...]
[go2: ETA: 0:00:00 (2 rooms to move through)]
[go2]>northwest
Roundtime: 1 sec.
You wade northwest, moving against the light current at an angle.
[Riverhaven West Wilds, North Creek Bank]
Wet, algae-coated rocks rise at nearly perpendicular angles along both sides of the creek.  
Obvious paths: southeast, west.
Room Number: 8617
>
[go2]>west
You feel fully rested.
>
Roundtime: 1 sec.
You wade west, moving against the light current at an angle.
[Riverhaven West Wilds, North Creek Bank]
Water rushes swiftly over the rocky creek bed, dashing into submerged obstacles with liberal sprays of foam and white topped waves.  You also see a muddy bank.
Obvious paths: east.
Room Number: 8618
>
[go2: travel time: 0:00:34]
--- Lich: go2 has exited.

---

And this is the reverse, from 8618 to 602:

(I actually got through this time, earlier I was stuck in an endless loop in the first few rooms)

[Riverhaven West Wilds, North Creek Bank]
Water rushes swiftly over the rocky creek bed, dashing into submerged obstacles with liberal sprays of foam and white topped waves.  You also see a muddy bank.
Obvious paths: east.
Room Number: 8618
>
[go2: travel time: 0:00:34]
--- Lich: go2 has exited.
You feel fully rested.
>
You feel fully rested.
>;go 602
--- Lich: go2 active.
[go2: ETA: 0:00:02 (12 rooms to move through)]
[go2]>east
Roundtime: 1 sec.
You wade east, moving with the current.
[Riverhaven West Wilds, North Creek Bank]
Wet, algae-coated rocks rise at nearly perpendicular angles along both sides of the creek.  
Obvious paths: southeast, west.
Room Number: 8617
>
[go2]>southeast
[go2]>east
[go2]>southeast
[go2]>se
[go2]>se
Roundtime: 1 sec.
You wade southeast, moving with the light current.
[Riverhaven West Wilds, North Creek Bank]
Movement other than the flow of the current can be seen beneath the somewhat turbulent water of the creek.  You also see a high bank.
[go2]>s
Obvious paths: east, northwest.
Room Number: 8616
>
...wait 1 seconds.
>
...wait 1 seconds.
>
...wait 1 seconds.
>
...wait 1 seconds.
>
You can't swim in that direction.
>
You feel fully rested.
>
[go2: restarting script...]
[go2: ETA: 0:00:02 (10 rooms to move through)]
[go2]>east
Roundtime: 1 sec.
You wade east, moving with the light current.
[Riverhaven West Wilds, North Creek Bank]
[go2]>southeast
Rapidly-running water obscures the view of the creek bed, but dark shapes indicate the presence of rocks fairly close to the surface of the creek.  
Obvious paths: southeast, west.
[go2]>se
Room Number: 8615
[go2]>se
[go2]>s
>
[go2]>south
You feel fully rested.
>
Roundtime: 1 sec.
You wade southeast, moving with the light current.
[Riverhaven West Wilds, North Creek Bank]
[go2]>southwest
The creek bed dead ends here with the rise of a perpendicular cliff to the east.  
Obvious paths: southeast, northwest.
Room Number: 8614
>
...wait 1 seconds.
>
...wait 1 seconds.
>
...wait 1 seconds.
>
...wait 1 seconds.
>
You can't swim in that direction.
>
You feel fully rested.
>
[go2: restarting script...]
[go2: ETA: 0:00:01 (8 rooms to move through)]
[go2]>se
Roundtime: 1 sec.
You wade southeast, moving with the light current.
[Sylvan Glade, Creek Inlet]
Water from a deep creek rushes into a small inland pond.  
Obvious paths: southeast, west, northwest.
Room Number: 11096
>
[go2]>se
[go2]>s
[go2]>south
[go2]>southwest
[go2]>go trail
Roundtime: 1 sec.
You wade southeast, moving with the light current.
[Sylvan Glade, Lily Pads]
Free from the shadows of the trees to the east, the water sparkles in the light of the Elanthian stars.  
[go2]>northeast
Obvious paths: south, southwest, northwest.
Room Number: 8619
>
...wait 1 seconds.
>
...wait 1 seconds.
>
...wait 1 seconds.
>
...wait 1 seconds.
>
You can't swim in that direction.
>
You feel fully rested.
>
[go2: restarting script...]
[go2: ETA: 0:00:01 (6 rooms to move through)]
[go2]>s
Roundtime: 1 sec.
You wade south, moving through the still water.
[Sylvan Glade, Pond]
Shaded by the branches of the willow trees, the pond water is comfortably cool and clean.  
Obvious paths: north, south, west.
Room Number: 8622
>
[go2]>south
[go2]>southwest
[go2]>go trail
[go2]>northeast
[go2]>northeast
You feel fully rested.
>
Roundtime: 1 sec.
You wade south, moving through the still water.
[Sylvan Pond, Mud Flats]
The water of the pond seems to have backed up over land that was once dry.  Several toppled tree trunks are all that remain of the willows that grew here.  
Obvious paths: north, southwest, northwest.
Room Number: 8621
>
...wait 1 seconds.
>
...wait 1 seconds.
>
...wait 1 seconds.
>
...wait 1 seconds.
>
[go2: restarting script...]
[go2: ETA: 0:00:00 (4 rooms to move through)]
[go2]>southwest
Roundtime: 1 sec.
You wade southwest, moving through the still water.
[Sylvan Pond, Mud Flats]
Higher ground combined with runoff from the pond has created a muddy swamp.  Puddles of water intersperse with rivulets that travel to a deep depression beneath a hollow log.  You also see a muddy trail.
Obvious paths: northeast.
Room Number: 8623
>
[go2]>go trail
[go2]>northeast
[go2]>northeast
[Riverhaven West Wilds, Meadows]
To the east at the end of a somewhat muddy looking trail is a small stand of trees circling a small inland pond.  You also see a winding path.
Obvious paths: northeast, west, northwest.
Room Number: 591
>
You saunter northeast.
[Riverhaven West Wilds, Meadow]
The bleached half-buried skull of a large rat shows starkly against the dark soil of the meadow.  A patch of daisies grows around it as if planted in memoriam by a mourning rodent relative.  
Obvious paths: northeast, southwest, west, northwest.
Room Number: 600
>
You saunter northeast.
[Riverhaven West Wilds, Meadow]
A lone waxy-leafed bush covered with bright pink blossoms pokes above the tall meadow grass.  Exposed bush roots extend through the grass and out over a bare spot of ground that slopes down to a rocky creek bank to the north.  
Obvious paths: southwest, west.
Room Number: 602
>
[go2: travel time: 0:00:38]
--- Lich: go2 has exited.

**Comment by LuckyThiefDR** [comment]
This same issue appears for me regularly in the moat by Theren keep, and in the Thief 5th passage.

**Comment by jandersson** [comment]
Whats the error?

**Comment by jandersson** [comment]
The multiple commands sent is your typeahead, but it doesn't seem to be causing an issue from what I can read

**Comment by LuckyThiefDR** [comment]
My expectation/assumption was that go2 should automatically handle waiting for roundtime when necessary - as it does in most but not every area in my experience. I have no issues crossing major rivers and most water rooms. This time I was able to get through them, but in some sequences of movement commands it's possible to end up in a loop where you take one step forward and one step back repeatedly. If that's just a normal non-issue, then I guess I can deal with it.

---

All I'd ask then is that these additional rooms be added to the dark_tunnels mining room list:

8579
8576
8577
8578
8584
8586
8587
8588
8583
8582
8581
8585
8580

**Comment by jandersson** [comment]
> If that's just a normal non-issue, then I guess I can deal with it.

Its an issue for sure :) I am just trying to understand. 

Might be good cause for a new entry to bescort

**Comment by LuckyThiefDR** [comment]
What prompted me to open this issue happened while I was gathering that list of additional mining rooms. When exiting the area through that small river, I got stuck in what seemed to be an endless loop moving east and then west over and over. Here's how it works:

Say you have a sequence of movement commands through water rooms like this: east, southeast, east, northeast, east, south, west, go bank, south, south, ...

The first batch of commands goes through and you move 1 room east before hitting a wall of roundtime.

Then, the second batch of commands goes through but because you're in the wrong room, the only valid movement command is 'west'.

Now you're in an endless loop moving east and west forever.

**Comment by LuckyThiefDR** [comment]
Hold on a minute, I'm a dumbass. I recently started logging all my sessions so I went back and found the log of this happening.

---

[go2]>southeast

A steeply banked creek cuts across the meadow to the south.  
Obvious paths: northeast, east.

Room Number: 8589

[Riverhaven West Wilds, North Creek Bank]

[go2]>se

Water rushes swiftly over the rocky creek bed, dashing into submerged obstacles with liberal sprays of foam and white topped waves.  You also see a muddy bank.
Obvious paths: east.

Room Number: 8618

Roundtime: 1 sec.
You wade east, moving with the current.
[Riverhaven West Wilds, North Creek Bank]

[go2]>w

Wet, algae-coated rocks rise at nearly perpendicular angles along both sides of the creek.  
Obvious paths: southeast, west.

Room Number: 8617

...wait 1 seconds.
...wait 1 seconds.
>ex
Roundtime: 1 sec.
You wade southeast, moving with the light current.
[Riverhaven West Wilds, North Creek Bank]

[go2]>northwest

Movement other than the flow of the current can be seen beneath the somewhat turbulent water of the creek.  You also see a high bank.
Obvious paths: east, northwest.

Room Number: 8616

...wait 1 seconds.
...wait 1 seconds.

Roundtime: 1 sec.
You wade northwest, moving against the light current at an angle.
[Riverhaven West Wilds, North Creek Bank]

[go2]>west

Wet, algae-coated rocks rise at nearly perpendicular angles along both sides of the creek.  
Obvious paths: southeast, west.

Room Number: 8617

>sleep
>sleep
Roundtime: 1 sec.
You wade west, moving against the light current at an angle.
[Riverhaven West Wilds, North Creek Bank]

[go2]>northwest

Water rushes swiftly over the rocky creek bed, dashing into submerged obstacles with liberal sprays of foam and white topped waves.  You also see a muddy bank.
Obvious paths: east.

Room Number: 8618

You can't swim in that direction.

[go2: restarting script...]

[go2: ETA: 0:00:02 (12 rooms to move through)]

[go2]>east

Roundtime: 1 sec.
You wade east, moving with the current.
[Riverhaven West Wilds, North Creek Bank]
Wet, algae-coated rocks rise at nearly perpendicular angles along both sides of the creek.  
Obvious paths: southeast, west.

Room Number: 8617


[go2]>southeast

[go2]>east

[go2]>southeast

[go2]>se

[go2]>w

Roundtime: 1 sec.
You wade southeast, moving with the light current.
[Riverhaven West Wilds, North Creek Bank]
Movement other than the flow of the current can be seen beneath the somewhat turbulent water of the creek.  You also see a high bank.

[go2]>northwest

Obvious paths: east, northwest.

Room Number: 8616

...wait 1 seconds.
...wait 1 seconds.
...wait 1 seconds.
...wait 1 seconds.
Roundtime: 1 sec.
You wade northwest, moving against the light current at an angle.
[Riverhaven West Wilds, North Creek Bank]

[go2]>west

Wet, algae-coated rocks rise at nearly perpendicular angles along both sides of the creek.  
Obvious paths: southeast, west.

Room Number: 8617

Roundtime: 1 sec.
You wade west, moving against the light current at an angle.
[Riverhaven West Wilds, North Creek Bank]

[go2]>northwest

Water rushes swiftly over the rocky creek bed, dashing into submerged obstacles with liberal sprays of foam and white topped waves.  You also see a muddy bank.
Obvious paths: east.

Room Number: 8618

You feel fully rested.
You can't swim in that direction.

[go2: restarting script...]

[go2: ETA: 0:00:02 (12 rooms to move through)]

[go2]>east

Roundtime: 1 sec.
You wade east, moving with the current.
[Riverhaven West Wilds, North Creek Bank]
Wet, algae-coated rocks rise at nearly perpendicular angles along both sides of the creek.  
Obvious paths: southeast, west.

Room Number: 8617


[go2]>southeast

[go2]>east

[go2]>southeast

[go2]>se

[go2]>w

Roundtime: 1 sec.
You wade southeast, moving with the light current.
[Riverhaven West Wilds, North Creek Bank]

[go2]>northwest

Movement other than the flow of the current can be seen beneath the somewhat turbulent water of the creek.  You also see a high bank.
Obvious paths: east, northwest.

Room Number: 8616

...wait 1 seconds.
...wait 1 seconds.
...wait 1 seconds.
...wait 1 seconds.
Roundtime: 1 sec.
You wade northwest, moving against the light current at an angle.
[Riverhaven West Wilds, North Creek Bank]
Wet, algae-coated rocks rise at nearly perpendicular angles along both sides of the creek.  
Obvious paths: southeast, west.

Room Number: 8617


[go2]>west

You feel fully rested.

[DRPrime]-DR:Nituki: "Should be 12 o'clock on the city"
Roundtime: 1 sec.
You wade west, moving against the light current at an angle.
[Riverhaven West Wilds, North Creek Bank]

[go2]>northwest

Water rushes swiftly over the rocky creek bed, dashing into submerged obstacles with liberal sprays of foam and white topped waves.  You also see a muddy bank.
Obvious paths: east.

Room Number: 8618

You can't swim in that direction.

[DRPrime]-DR:Nituki: "top north"
[DRPrime]-DR:Gallifreius: "I'm in"
You feel fully rested.

[go2: restarting script...]

[go2: ETA: 0:00:02 (12 rooms to move through)]

[go2]>east

Roundtime: 1 sec.
You wade east, moving with the current.
[Riverhaven West Wilds, North Creek Bank]
Wet, algae-coated rocks rise at nearly perpendicular angles along both sides of the creek.  
Obvious paths: southeast, west.

Room Number: 8617


[go2]>southeast

[go2]>east

[go2]>southeast

[go2]>se

[go2]>w

[DRPrime]-DR:Gallifreius: "mission going smoothly"

Roundtime: 1 sec.
You wade southeast, moving with the light current.
[Riverhaven West Wilds, North Creek Bank]

[go2]>northwest

Movement other than the flow of the current can be seen beneath the somewhat turbulent water of the creek.  You also see a high bank.
Obvious paths: east, northwest.

Room Number: 8616

...wait 1 seconds.
...wait 1 seconds.
...wait 1 seconds.
...wait 1 seconds.
You feel fully rested.

[DRPrime]-DR:Nituki: "oh you don't have to tell me"
Roundtime: 1 sec.
You wade northwest, moving against the light current at an angle.
[Riverhaven West Wilds, North Creek Bank]
Wet, algae-coated rocks rise at nearly perpendicular angles along both sides of the creek.  

[go2]>west

Obvious paths: southeast, west.

Room Number: 8617

Roundtime: 1 sec.
You wade west, moving against the light current at an angle.
[Riverhaven West Wilds, North Creek Bank]
Water rushes swiftly over the rocky creek bed, dashing into submerged obstacles with liberal sprays of foam and white topped waves.  You also see a muddy bank.

[go2]>northwest

Obvious paths: east.

Room Number: 8618

You can't swim in that direction.

[DRPrime]-DR:Nituki: "Oh you mean the hair salon"
You feel fully rested.
[DRPrime]-DR:Damiza: "Looks like the top middle north Galli"

[go2: restarting script...]

[go2: ETA: 0:00:02 (12 rooms to move through)]

[go2]>east

Roundtime: 1 sec.
You wade east, moving with the current.
[Riverhaven West Wilds, North Creek Bank]
Wet, algae-coated rocks rise at nearly perpendicular angles along both sides of the creek.  
Obvious paths: southeast, west.

Room Number: 8617


[go2]>southeast

[go2]>east

[go2]>southeast

[go2]>se

[go2]>w

Roundtime: 1 sec.
You wade southeast, moving with the light current.
[Riverhaven West Wilds, North Creek Bank]

[go2]>northwest

Movement other than the flow of the current can be seen beneath the somewhat turbulent water of the creek.  You also see a high bank.
Obvious paths: east, northwest.

Room Number: 8616

...wait 1 seconds.
...wait 1 seconds.
...wait 1 seconds.
...wait 1 seconds.
Roundtime: 1 sec.
You wade northwest, moving against the light current at an angle.
[Riverhaven West Wilds, North Creek Bank]
Wet, algae-coated rocks rise at nearly perpendicular angles along both sides of the creek.  
Obvious paths: southeast, west.

Room Number: 8617


[go2]>west

Roundtime: 1 sec.
You wade west, moving against the light current at an angle.
[Riverhaven West Wilds, North Creek Bank]

[go2]>northwest

Water rushes swiftly over the rocky creek bed, dashing into submerged obstacles with liberal sprays of foam and white topped waves.  You also see a muddy bank.
Obvious paths: east.

Room Number: 8618

You feel fully rested.
You can't swim in that direction.

[go2: restarting script...]

[go2: ETA: 0:00:02 (12 rooms to move through)]

[go2]>east

Roundtime: 1 sec.
You wade east, moving with the current.
[Riverhaven West Wilds, North Creek Bank]
Wet, algae-coated rocks rise at nearly perpendicular angles along both sides of the creek.  
Obvious paths: southeast, west.

Room Number: 8617


[go2]>southeast

[go2]>east

[go2]>southeast

[go2]>se

[go2]>w

Roundtime: 1 sec.
You wade southeast, moving with the light current.
[Riverhaven West Wilds, North Creek Bank]
Movement other than the flow of the current can be seen beneath the somewhat turbulent water of the creek.  You also see a high bank.

[go2]>northwest

Obvious paths: east, northwest.

Room Number: 8616

...wait 1 seconds.
...wait 1 seconds.
...wait 1 seconds.
...wait 1 seconds.
Roundtime: 1 sec.
You wade northwest, moving against the light current at an angle.
[Riverhaven West Wilds, North Creek Bank]

[go2]>west

Wet, algae-coated rocks rise at nearly perpendicular angles along both sides of the creek.  
Obvious paths: southeast, west.

Room Number: 8617

Roundtime: 1 sec.
You wade west, moving against the light current at an angle.
[Riverhaven West Wilds, North Creek Bank]
Water rushes swiftly over the rocky creek bed, dashing into submerged obstacles with liberal sprays of foam and white topped waves.  You also see a muddy bank.
Obvious paths: east.

[go2]>northwest

Room Number: 8618

You feel fully rested.
You can't swim in that direction.

[go2: restarting script...]

[go2: ETA: 0:00:02 (12 rooms to move through)]

[go2]>east

Roundtime: 1 sec.
You wade east, moving with the current.
[Riverhaven West Wilds, North Creek Bank]
Wet, algae-coated rocks rise at nearly perpendicular angles along both sides of the creek.  
Obvious paths: southeast, west.

Room Number: 8617


[go2]>southeast

[go2]>east

[go2]>southeast

[go2]>se

[go2]>w

>LOOK
Roundtime: 1 sec.
You wade southeast, moving with the light current.
[Riverhaven West Wilds, North Creek Bank]

[go2]>northwest

Movement other than the flow of the current can be seen beneath the somewhat turbulent water of the creek.  You also see a high bank.
Obvious paths: east, northwest.

Room Number: 8616

...wait 1 seconds.
...wait 1 seconds.
...wait 1 seconds.
...wait 1 seconds.
[Riverhaven West Wilds, North Creek Bank]
Movement other than the flow of the current can be seen beneath the somewhat turbulent water of the creek.  You also see a high bank.
Obvious paths: east, northwest.

Room Number: 8616

Roundtime: 1 sec.
You wade northwest, moving against the light current at an angle.
[Riverhaven West Wilds, North Creek Bank]
Wet, algae-coated rocks rise at nearly perpendicular angles along both sides of the creek.  

[go2]>west

Obvious paths: southeast, west.

Room Number: 8617

Roundtime: 1 sec.
You wade west, moving against the light current at an angle.
[Riverhaven West Wilds, North Creek Bank]

[go2]>northwest

Water rushes swiftly over the rocky creek bed, dashing into submerged obstacles with liberal sprays of foam and white topped waves.  You also see a muddy bank.
Obvious paths: east.

Room Number: 8618

You feel fully rested.
You can't swim in that direction.

[DRPrime]-DR:Gallifreius: "wait I have really cool hair and I don't want to risk it going away D:"

[go2: restarting script...]

[go2: ETA: 0:00:02 (12 rooms to move through)]

[go2]>east

Roundtime: 1 sec.
You wade east, moving with the current.
[Riverhaven West Wilds, North Creek Bank]
Wet, algae-coated rocks rise at nearly perpendicular angles along both sides of the creek.  
Obvious paths: southeast, west.

Room Number: 8617


[go2]>southeast

[go2]>east

[go2]>southeast

[go2]>se

[go2]>w

Roundtime: 1 sec.
You wade southeast, moving with the light current.
[Riverhaven West Wilds, North Creek Bank]
Movement other than the flow of the current can be seen beneath the somewhat turbulent water of the creek.  You also see a high bank.

[go2]>northwest

Obvious paths: east, northwest.

Room Number: 8616

...wait 1 seconds.
...wait 1 seconds.
...wait 1 seconds.
...wait 1 seconds.
Roundtime: 1 sec.
You wade northwest, moving against the light current at an angle.
[Riverhaven West Wilds, North Creek Bank]

[go2]>west

Wet, algae-coated rocks rise at nearly perpendicular angles along both sides of the creek.  
Obvious paths: southeast, west.

Room Number: 8617

You feel fully rested.
Roundtime: 1 sec.
You wade west, moving against the light current at an angle.
[Riverhaven West Wilds, North Creek Bank]

[go2]>northwest

Water rushes swiftly over the rocky creek bed, dashing into submerged obstacles with liberal sprays of foam and white topped waves.  You also see a muddy bank.
Obvious paths: east.

Room Number: 8618

You can't swim in that direction.
>;kill all

--- Lich: mining-buddy has exited.

--- Lich: go2 has exited.

**Comment by jandersson** [comment]
Noticing some duplicate map ID's.  Assuming you're just trying to move through this area to get from A to B then yea i think a bescort entry is what could be a quick fix. Aside from bescort it may be possible to improve the mapping somehow (skeptical)?

**Comment by jandersson** [comment]
If im understanding right: what room numbers should bescort start taking over in? whats a and b?

**Comment by LuckyThiefDR** [comment]
On the northern end there are 3 possible entrances/exits at 8616, 8617, 8618.

On the southern end, you can enter/exit from 3 rooms which are 8621, 8612, and 15076.

**Comment by MahtraDR** [comment]
Is this still an issue today?

**Comment by jandersson** [comment]
Think it can be closed, i remember spending time looking into it to no avail. @LuckyThiefDR can re-open
