### ISSUE TITLE
combat-trainer weapon swap/off hand

### ISSUE THREAD

**Issue by Tweedum** [rpherbig/dr-scripts#4334]
Sometimes when the weapon change occurs my light thrown (boomerang) with end up in my off-hand causing a loop for a some time till its time to change weapons again. Its not every time. The log shows the correct order if stowing and getting the weapon, boomerang still ends  up in the off-hand once in a while for whatever reason. 

ex:
 
[combat-trainer]>jab

< You jab a ngalio at a Dragon Priest zealot.  A Dragon Priest zealot badly fails to block with a dark steel lata'oloh (medium edged weapon) with an curved oak hilt.  
The ngalio lands a light hit (1/23) (1/23) to the zealot's right arm.
Utilizing flawless combat expertise you execute an aggressive attack combination and fan the flames of your internal fire.
[You're nimbly balanced with opponent in good position.]
[Roundtime 2 sec.]
R> 
The Dragon Priest zealot moves into a position to parry.
R> 
[combat-trainer]>stow my ngalio

...wait 1 seconds.
R> 
[combat-trainer]>stow my ngalio

R> 
You feel fully rested.

R> 
...wait 1 seconds.
R> 
[combat-trainer]>stow my ngalio

You put your ngalio in your traveler's pack.
> 
[combat-trainer]>get my boomerang

You get a steel boomerang colored with red dye from inside your traveler's pack.
> 
[combat-trainer]>lob

What are you trying to lob?
> 
[combat-trainer]>get my boomerang

* A Dragon Priest zealot feints to the side at you.  You deflect some of the lata'oloh (medium edged weapon) with a calcified femur.  
[You're solidly balanced with opponent in superior position.]
> 

* A Dragon Priest zealot chops wide at you.  You dodge.  
[You're solidly balanced with opponent in very strong position.]
> 
You are already holding that.
> 
[combat-trainer]>lob

> 
> 
What are you trying to lob?
> 
[combat-trainer]>get my boomerang

You are already holding that.
> 
[combat-trainer]>lob

What are you trying to lob?
> 
[combat-trainer]>get my boomerang

You are already holding that.
> 
[combat-trainer]>lob

##########
Times passes
Into the next weapon
##########

> 
You are already holding that.
> 
[combat-trainer]>stow my boomerang

You put your boomerang in your traveler's pack.
> 
[combat-trainer]>get my claymore

You get a scrimshaw-handled claymore from inside your traveler's pack.
> 
[combat-trainer]>meditate research earthquake

**Comment by Hiinky** [comment]
Sadly this issue is specific to a boomerang.  The simu-side script that returns it to the hand that threw it seems to trigger any time it leaves your hand for any purpose - be it thrown or stowed.  The fastest and easiest fix would be to change weapons.

**Comment by Tweedum** [comment]
Thanks! That would explain why it "seems" random. I'll get a new weapon then.
