### ISSUE TITLE
Extract magic research logic from crossing-train to new script

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#4335]
Lets do researching as its own script.  Crossing-training has the logic necessary, it could be extracted into a standalone script. This will also add more options for the other two training managers t2 and coordinator.

**Comment by cfrisby77** [comment]
researcher.lic is available on repository

**Comment by MahtraDR** [comment]
@rpherbig Can close this, as pointed out by @cfrisby77 researcher.lic does this already.
