### ISSUE TITLE
Two artificing base-recipes errors

### ISSUE THREAD

**Issue by KillashandreaDR** [rpherbig/dr-scripts#4340]
artificing: -simple gwethdesuan...
it indicates "bone totem" which works up until finishing the enchantment, after which it becomes a "totem" (no adjective).  The workorder script them tries to pick up a "bone totem" and bundle it with the logbook, but instead it pulls a "bone totem" from your backpack.  In order to get it to work, you need to either drop the adjective from the enchant and workorder scripts only when picking up the item from your feet and when bundling with the logbook...or just remove "bone" from the base recipe.

artificing: -aura device...
it orders sigil #4 when it needs to order sigil #2.

**Comment by Dartellum** [comment]
I will work through this as I update all the recipes. I am getting closer to done. I will also work through each of these recipes to make sure the noun setting is correct. I see many nouns as bone totem but most are `workorders: false` so no one should encounter them doing workorders. :smile:

**Comment by Dartellum** [comment]
> artificing: -simple gwethdesuan...
> it indicates "bone totem" which works up until finishing the enchantment, after which it becomes a "totem" (no adjective). The workorder script them tries to pick up a "bone totem" and bundle it with the logbook, but instead it pulls a "bone totem" from your backpack. In order to get it to work, you need to either drop the adjective from the enchant and workorder scripts only when picking up the item from your feet and when bundling with the logbook...or just remove "bone" from the base recipe.
> 
> artificing: -aura device...
> it orders sigil #4 when it needs to order sigil #2.

@KillashandreaDR 
Did you mean `simple gwethsmasher` in chapter 2 or `a gwethdesuan` in chapter 5?

**Comment by KillashandreaDR** [comment]
Sorry been so long I don’t remember.  But since I wrote “simple” and based off of epedia and the components list, I am 99% sure I meant the smasher.

**Comment by Dartellum** [comment]
Okay fixed that one but it is set to false for workorders because one of the sigils, metamorphosis, is not store-bought. However, it will work for overrides now once the `base-recipes` PR is merged.

**Comment by Dartellum** [comment]
Fix for picking up the correct item. During testing, I had both ways, get my #{@item} and get #{@item}, retrieve the wrong item occasionally. This fix, https://github.com/rpherbig/dr-scripts/pull/5114, makes sure the item is picked up from the at feet location. Or, it did during my testing. I would like you to test it and report back. :smile:
