### ISSUE TITLE
go2 inv at feet not recognized

### ISSUE THREAD

**Issue by Tweedum** [rpherbig/dr-scripts#4345]
Anything in the atfeet slot loops go2.

--- Lich: go2 active.

--- Lich: 'textsubs' has been stopped by go2.

[go2: ETA: 0:00:24 (115 rooms to move through)]

[go2]>east

You notice a blunt-tipped arrows with lavender stripe at your feet, and do not wish to leave it behind.
> 
You sense your combat accuracy decrease as the battle shifts before you.
> 
[go2: move: no recognized response in 30 seconds.  giving up.]

[go2: restarting script...]

[go2: ETA: 0:00:24 (115 rooms to move through)]

[go2]>east

You notice a blunt-tipped arrows with lavender stripe at your feet, and do not wish to leave it behind.
> 

> 
[go2: move: no recognized response in 30 seconds.  giving up.]

[go2: restarting script...]

**Comment by Hiinky** [comment]
run ;afk  as an autostart.  the feet inventory handling is built in.  just set`health_threshold: 0` if you don't want to ever combat log.

**Comment by Hiinky** [comment]
;e autostart('afk')

**Comment by Hiinky** [comment]
Please update or close if this solved your concerns.

**Comment by Nuzack** [comment]
Please close this as I can not.
