### ISSUE TITLE
Still having issues with ;pick

### ISSUE THREAD

**Issue by LuckyThiefDR** [rpherbig/dr-scripts#4347]
My most recent download for the ;pick script was on 6/12 at ~7pm.

Here's the log from today - 
---
You get a moldy mahogany caddy from inside your cloth lootpouch.
>
[pick]>disarm my caddy identify
Careful probing of the mahogany caddy fails to reveal to you what type of trap protects it.
You get the distinct feeling your careless examination caused something to shift inside the trap mechanism.  This is not likely to be a good thing.
Roundtime: 1 sec.
>
[pick]>disarm my caddy identify
>
Careful probing of the mahogany caddy fails to reveal to you what type of trap protects it.
Roundtime: 1 sec.
>
[pick]>disarm my caddy identify
>
Careful probing of the mahogany caddy fails to reveal to you what type of trap protects it.
Roundtime: 1 sec.
[pick]>disarm my caddy identify
[pick]>disarm my caddy careful
>
Out of the corner of your eye, you notice a glint of razor sharp steel hidden within a suspicious looking seam on the caddy.
The mahogany caddy should not take long with your skills.
Roundtime: 2 sec.
>
...wait 2 seconds.
>
[pick]>pick my caddy ident
Careful probing of the mahogany caddy fails to teach you anything about the lock guarding it.
Roundtime: 1 sec.
>
[pick]>pick my caddy ident
Careful probing of the mahogany caddy fails to teach you anything about the lock guarding it.
Roundtime: 1 sec.
>
[pick]>pick my caddy ident
>
You can unlock the mahogany caddy with only minor troubles.
However, a moldy mahogany caddy is not fully disarmed, making any chance of picking it unlikely.
Roundtime: 1 sec.
[pick]>pick my caddy quick
>
You deftly remove a lockpick from the lockpick ring and begin to work at quickly picking open the caddy.
You realize very quickly that this was a very bad idea...
With a sinister swishing noise, a deadly sharp scythe blade whips out the front of the caddy, completely severing your right hand!  You watch with a sort of detatched horror as a fountain of blood arcs from the severed stump.

You realize that despite this mishap, the caddy still has more to torment you with.
You return your lockpick to the lockpick ring.
Roundtime: 1 sec.

**Comment by Hiinky** [comment]
This issue has not yet been addressed and was not part of recent updates.  Solution is still in the works.

**Comment by rpherbig** [comment]
Closed in #5001
