### ISSUE TITLE
Train should check your current tdps using the tdp command.

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#435]
http://pastebin.com/VacX8Fst

**Comment by rpherbig** [comment]
It looks like the root cause is `drinfomon` not refreshing your number of TDPs. Did `train` work after you ran info manually?

**Comment by rpherbig** [comment]
We'll need to update `drinfomon` to pick up the output of the `tdp` command:
```
>tdp
You have 117 TDPs.
```
