### ISSUE TITLE
bescort.lic Jolas

### ISSUE THREAD

**Issue by cfrisby77** [rpherbig/dr-scripts#4356]
Bescort currently does not support for the Jolas not being present at the Wharf / Dock.

it needs a "when /What were you referring to/" 

--------------------------------------------------------------------------------------------
**Mer'Kresh Match Information:**

The Jolas ties off to the Mer'Kresh docks!
>
A clerk enters and updates the slate board and yells out, "The sleek Jolas departing soon!"

**Hara'Jaal Match Information:**

The Jolas ties off to the Sumilo dock!
>
A clerk enters and updates the slate board and yells out, "The sleek Jolas departing soon!"
_________________________________________________________________________________________________

**LOG OF ISSUE:**

**Mer'Kresh Side**
look
[Wharf End, Mer'Kresh]
Through the gaps in the heavy wood planks, one can easily see the waters of Torbis Sanhalas lapping noisily at the pilings.  Although most of the surface of the wharf is covered by a wide assortment of boxes, barrels and shipping goods, there is little that would stop a dropped coin or trinket from vanishing through the slats and sinking into a watery grave.  You also see the Jolly Roger, the Nightblade's Claw, the Stranger Ranger, the Twilight's Journey, a slate board and an ebony slate.
Obvious paths: northwest.
Nearby in the water you see: the open ocean (distant), Mer'Kresh city (close), a few ships.
Room Number: 6542
>;bescor jolas harajaal
--- Lich: bescort active.
[bescort]>go Jolas
What were you referring to?
>
[bescort: *** No match was found after 15 seconds, dumping info]
[bescort: messages seen length: 2]
[bescort: message:  * Arcane Wraith Nairdyz joins the adventure.]
[bescort: message: What were you referring to?]
[bescort: checked against [/You climb/i]]
[bescort: for command go Jolas]

**Hara'Jaal Side**
>look
[Sumilo Dock]
The platform of the dock is wrapped around with a thick, spongy material that protects it from being damaged when ships pull up.  The dock planks are deeply scarred from the loading and unloading of cargo.  You also see a slate board and an ebony slate.
Obvious paths: north.
Nearby in the water you see: the open ocean (distant).
Room Number: 15253
>;bescort jolas merkresh
--- Lich: bescort active.
[bescort]>go Jolas
What were you referring to?
>
[bescort: *** No match was found after 15 seconds, dumping info]
[bescort: messages seen length: 1]
[bescort: message: What were you referring to?]
[bescort: checked against [/You climb/i]]
[bescort: for command go Jolas]

**Comment by Hiinky** [comment]
Handled on PR: Update Jolas #4359
