### ISSUE TITLE
Burgle not unpausing miscellaneous scripts when ending

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#4366]
Scripts paused before burgle:
--- Lich: burgle active.
--- Lich: sanowret-crystal paused.
--- Lich: mattune paused.
--- Lich: tap paused.
--- Lich: almanac paused.

Scripts unpaused after selling loot:
You sell your writing slate to Cormyn.

Cormyn takes your writing slate and gives it a quick but thorough examination.  After pausing for a moment, he hands you 4711 kronars for it.

--- Lich: crossing-training unpaused. < none of the other scripts unpaused (almanac, sanowret-crystal, etc)

--- Lich: burgle has exited.

**Comment by vtcifer** [comment]
Can you provide any further info.  I cannot reproduce.

**Comment by MahtraDR** [comment]
@rpherbig Can close. Can't reproduce, and no response in over a year.
