### ISSUE TITLE
base-hunting, suggested change to "dryads" room list

### ISSUE THREAD

**Issue by LuckyThiefDR** [rpherbig/dr-scripts#4367]
Useful part of the hunting ladder would be improved by dividing the 2 areas and including premium rooms.

---

  twisted_dryads:
  - 9766
  - 9767
  - 9772
  - 9774
  - 9773
  twisted_dryads_premium:
  - 15231
  - 15230
  - 15229
  dryad_priestess:
  - 9768
  - 9769
  - 9770
  - 9771

---

Also, this part if mapping is possible

  dryad_priestess_premium:
  - ?????
  - ?????
  - ?????

**Comment by Hiinky** [comment]
I'm looking at the premie rooms now but aren't the twisted dryads and priestess' the same range?  What feature makes one better/different from the other that separating them offers benefit?  I'm not very familiar with these two.

**Comment by Hiinky** [comment]
Addressed in PR: https://github.com/rpherbig/dr-scripts/pull/4377

**Comment by LuckyThiefDR** [comment]
Sorry for the late response - the priestesses are slightly easier at level
34, compared to the twisted dryad's 36. It was mainly relevant due to their
parrying, which made the priestesses viable at lower ranks.
