### ISSUE TITLE
safe-room with yrisa has pushstream issue

### ISSUE THREAD

**Issue by khrispyb** [rpherbig/dr-scripts#4368]
Hello

Using the safe-room with Yrisa in Fang Cove causes a massive slowdown (game keeps going with lich commands but the text crawls on my computer and rapidly catches up about 5-10 min later).  I usually see a pushstream type error at some point but not always.

I'm having this on multiple computers - any ideas what could be causing it?

**Comment by vtcifer** [comment]
If I had to guess, it's the busywait loop.  

It looks like when better (don't lie down) logic was put in for fang cove the pause in that loop was not put in specifically for fang cove.  I've seen the slow down, but not the pushstream error ever. I'll put a pause back in and see if the slow down gets any better.

**Comment by vtcifer** [comment]
Should be resolved with #4425.  Can you confirm and close if OK?

**Comment by khrispyb** [comment]
Works way better, still slows down a bit but not like before where it would barely move along at all. Thanks!
