### ISSUE TITLE
Add teaching to crossing-training

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#438]
From @xtremenerdrage:

> Also please add a syntax for specific name to teach a skill if possible
> Arrive at room and one of the yamls is set up to "teach \* to name" 
> the other can have auto listen on

**Comment by rpherbig** [comment]
Idle musings:
1. Support only teaching one skill? Or a list?
1. Support only teaching to one person? Or everyone in the room?
1. How do we handle skills that require movement? Skip them?

**Comment by wscherer420** [comment]
Yes teaching would be a great option.  Perhaps if it is set to on it would attempt to teach everyone in the room.  Lockpicking, First Aid don't require movement, correct?  If teaching then it could replace the current way scholarship is trained.  Maybe have teaching set on a timer (customizable?) or go until Mindlocked before the next skill training?
