### ISSUE TITLE
Add support for mana tuners in ;textsubs

### ISSUE THREAD

**Issue by Kaltair** [rpherbig/dr-scripts#4396]
;textsubs does not currently support mana tuners. I've written my own little script, but it is a bit janky and would probably be better suited for ;textsubs ... aaand I'm not super savvy with .lic scripts. Below is what I came up with ... over to the crowd on how best to integrate it without breaking anything.

Cheers!

TextSubs.add('Faint streams of cold, white mana chill your core.', 'Faint (1/21) streams of cold, white mana chill your core. (Lunar)')
TextSubs.add('Dim streams of cold, white mana chill your core.', 'Dim (2/21) streams of cold, white mana chill your core. (Lunar)')
TextSubs.add('Hazy streams of cold, white mana chill your core.', 'Hazy (3/21) streams of cold, white mana chill your core. (Lunar)')
TextSubs.add('Dull streams of cold, white mana chill your core.', 'Dull (4/21) streams of cold, white mana chill your core. (Lunar)')
TextSubs.add('Muted streams of cold, white mana chill your core.', 'Muted (5/21) streams of cold, white mana chill your core. (Lunar)')
TextSubs.add('Dusky streams of cold, white mana chill your core.', 'Dusky (6/21) streams of cold, white mana chill your core. (Lunar)')
TextSubs.add('Pale streams of cold, white mana chill your core.', 'Pale (7/21) streams of cold, white mana chill your core. (Lunar)')
TextSubs.add('Flickering streams of cold, white mana chill your core.', 'Flickering (8/21) streams of cold, white mana chill your core. (Lunar)')
TextSubs.add('Shimmering streams of cold, white mana chill your core.', 'Shimmering (9/21) streams of cold, white mana chill your core. (Lunar)')
TextSubs.add('Pulsating streams of cold, white mana chill your core.', 'Pulsating (10/21) streams of cold, white mana chill your core. (Lunar)')
TextSubs.add('Glowing streams of cold, white mana chill your core.', 'Glowing (11/21) streams of cold, white mana chill your core. (Lunar)')
TextSubs.add('Lambent streams of cold, white mana chill your core.', 'Lambent (12/21) streams of cold, white mana chill your core. (Lunar)')
TextSubs.add('Shining streams of cold, white mana chill your core.', 'Shining (13/21) streams of cold, white mana chill your core. (Lunar)')
TextSubs.add('Luminous streams of cold, white mana chill your core.', 'Luminous (14/21) streams of cold, white mana chill your core. (Lunar)')
TextSubs.add('Radiant streams of cold, white mana chill your core.', 'Radiant (15/21) streams of cold, white mana chill your core. (Lunar)')
TextSubs.add('Fulgent streams of cold, white mana chill your core.', 'Fulgent (16/21) streams of cold, white mana chill your core. (Lunar)')
TextSubs.add('Brilliant streams of cold, white mana chill your core.', 'Brilliant (17/21) streams of cold, white mana chill your core. (Lunar)')
TextSubs.add('Flaring streams of cold, white mana chill your core.', 'Flaring (18/21) streams of cold, white mana chill your core. (Lunar)')
TextSubs.add('Glaring streams of cold, white mana chill your core.', 'Glaring (19/21) streams of cold, white mana chill your core. (Lunar)')
TextSubs.add('Blazing streams of cold, white mana chill your core.', 'Blazing (20/21) streams of cold, white mana chill your core. (Lunar)')
TextSubs.add('Blinding streams of cold, white mana chill your core.', 'Blinding (21/21) streams of cold, white mana chill your core. (Lunar)')
TextSubs.add('Faint streams of fiery mana burn through your limbs.', 'Faint (1/21) streams of fiery mana burn through your limbs. (Elemental)')
TextSubs.add('Dim streams of fiery mana burn through your limbs.', 'Dim (2/21) streams of fiery mana burn through your limbs. (Elemental)')
TextSubs.add('Hazy streams of fiery mana burn through your limbs.', 'Hazy (3/21) streams of fiery mana burn through your limbs. (Elemental)')
TextSubs.add('Dull streams of fiery mana burn through your limbs.', 'Dull (4/21) streams of fiery mana burn through your limbs. (Elemental)')
TextSubs.add('Muted streams of fiery mana burn through your limbs.', 'Muted (5/21) streams of fiery mana burn through your limbs. (Elemental)')
TextSubs.add('Dusky streams of fiery mana burn through your limbs.', 'Dusky (6/21) streams of fiery mana burn through your limbs. (Elemental)')
TextSubs.add('Pale streams of fiery mana burn through your limbs.', 'Pale (7/21) streams of fiery mana burn through your limbs. (Elemental)')
TextSubs.add('Flickering streams of fiery mana burn through your limbs.', 'Flickering (8/21) streams of fiery mana burn through your limbs. (Elemental)')
TextSubs.add('Shimmering streams of fiery mana burn through your limbs.', 'Shimmering (9/21) streams of fiery mana burn through your limbs. (Elemental)')
TextSubs.add('Pulsating streams of fiery mana burn through your limbs.', 'Pulsating (10/21) streams of fiery mana burn through your limbs. (Elemental)')
TextSubs.add('Glowing streams of fiery mana burn through your limbs.', 'Glowing (11/21) streams of fiery mana burn through your limbs. (Elemental)')
TextSubs.add('Lambent streams of fiery mana burn through your limbs.', 'Lambent (12/21) streams of fiery mana burn through your limbs. (Elemental)')
TextSubs.add('Shining streams of fiery mana burn through your limbs.', 'Shining (13/21) streams of fiery mana burn through your limbs. (Elemental)')
TextSubs.add('Luminous streams of fiery mana burn through your limbs.', 'Luminous (14/21) sstreams of fiery mana burn through your limbs. (Elemental)')
TextSubs.add('Radiant streams of fiery mana burn through your limbs.', 'Radiant (15/21) streams of fiery mana burn through your limbs. (Elemental)')
TextSubs.add('Fulgent streams of fiery mana burn through your limbs.', 'Fulgent (16/21) streams of fiery mana burn through your limbs. (Elemental)')
TextSubs.add('Brilliant streams of fiery mana burn through your limbs.', 'Brilliant (17/21) streams of fiery mana burn through your limbs. (Elemental)')
TextSubs.add('Flaring streams of fiery mana burn through your limbs.', 'Flaring (18/21) streams of fiery mana burn through your limbs. (Elemental)')
TextSubs.add('Glaring streams of fiery mana burn through your limbs.', 'Glaring (19/21) streams of fiery mana burn through your limbs. (Elemental)')
TextSubs.add('Blazing streams of fiery mana burn through your limbs.', 'Blazing (20/21) streams of fiery mana burn through your limbs. (Elemental)')
TextSubs.add('Blinding streams of fiery mana burn through your limbs.', 'Blinding (21/21) streams of fiery mana burn through your limbs. (Elemental)')
TextSubs.add('Faint streams of bluish-white mana flow up your spine.', 'Faint (1/21) streams of bluish-white mana flow up your spine. (Life)')
TextSubs.add('Dim streams of bluish-white mana flow up your spine.', 'Dim (2/21) streams of bluish-white mana flow up your spine. (Life)')
TextSubs.add('Hazy streams of bluish-white mana flow up your spine.', 'Hazy (3/21) streams of bluish-white mana flow up your spine. (Life)')
TextSubs.add('Dull streams of bluish-white mana flow up your spine.', 'Dull (4/21) streams of bluish-white mana flow up your spine. (Life)')
TextSubs.add('Muted streams of bluish-white mana flow up your spine.', 'Muted (5/21) streams of bluish-white mana flow up your spine. (Life)')
TextSubs.add('Dusky streams of bluish-white mana flow up your spine.', 'Dusky (6/21) streams of bluish-white mana flow up your spine. (Life)')
TextSubs.add('Pale streams of bluish-white mana flow up your spine.', 'Pale (7/21) streams of bluish-white mana flow up your spine. (Life)')
TextSubs.add('Flickering streams of bluish-white mana flow up your spine.', 'Flickering (8/21) streams of bluish-white mana flow up your spine. (Life)')
TextSubs.add('Shimmering streams of bluish-white mana flow up your spine.', 'Shimmering (9/21) streams of bluish-white mana flow up your spine. (Life)')
TextSubs.add('Pulsating streams of bluish-white mana flow up your spine.', 'Pulsating (10/21) streams of bluish-white mana flow up your spine. (Life)')
TextSubs.add('Glowing streams of bluish-white mana flow up your spine.', 'Glowing (11/21) streams of bluish-white mana flow up your spine. (Life)')
TextSubs.add('Lambent streams of bluish-white mana flow up your spine.', 'Lambent (12/21) streams of bluish-white mana flow up your spine. (Life)')
TextSubs.add('Shining streams of bluish-white mana flow up your spine.', 'Shining (13/21) streams of bluish-white mana flow up your spine. (Life)')
TextSubs.add('Luminous streams of bluish-white mana flow up your spine.', 'Luminous (14/21) streams of bluish-white mana flow up your spine. (Life)')
TextSubs.add('Radiant streams of bluish-white mana flow up your spine.', 'Radiant (15/21) streams of bluish-white mana flow up your spine. (Life)')
TextSubs.add('Fulgent streams of bluish-white mana flow up your spine.', 'Fulgent (16/21) streams of bluish-white mana flow up your spine. (Life)')
TextSubs.add('Brilliant streams of bluish-white mana flow up your spine.', 'Brilliant (17/21) streams of bluish-white mana flow up your spine. (Life)')
TextSubs.add('Flaring streams of bluish-white mana flow up your spine.', 'Flaring (18/21) streams of bluish-white mana flow up your spine. (Life)')
TextSubs.add('Glaring streams of bluish-white mana flow up your spine.', 'Glaring (19/21) streams of bluish-white mana flow up your spine. (Life)')
TextSubs.add('Blazing streams of bluish-white mana flow up your spine.', 'Blazing (20/21) streams of bluish-white mana flow up your spine. (Life)')
TextSubs.add('Blinding streams of bluish-white mana flow up your spine.', 'Blinding (21/21) streams of bluish-white mana flow up your spine. (Life)')
TextSubs.add('Faint streams of golden mana echo through your body.', 'Faint (1/21) streams of golden mana echo through your body. (Holy)')
TextSubs.add('Dim streams of golden mana echo through your body.', 'Dim (2/21) streams of golden mana echo through your body. (Holy)')
TextSubs.add('Hazy streams of golden mana echo through your body.', 'Hazy (3/21) streams of golden mana echo through your body. (Holy)')
TextSubs.add('Dull streams of golden mana echo through your body.', 'Dull (4/21) streams of golden mana echo through your body. (Holy)')
TextSubs.add('Muted streams of golden mana echo through your body.', 'Muted (5/21) streams of golden mana echo through your body. (Holy)')
TextSubs.add('Dusky streams of golden mana echo through your body.', 'Dusky (6/21) streams of golden mana echo through your body. (Holy)')
TextSubs.add('Pale streams of golden mana echo through your body.', 'Pale (7/21) streams of golden mana echo through your body. (Holy)')
TextSubs.add('Flickering streams of golden mana echo through your body.', 'Flickering (8/21) streams of golden mana echo through your body. (Holy)')
TextSubs.add('Shimmering streams of golden mana echo through your body.', 'Shimmering (9/21) streams of golden mana echo through your body. (Holy)')
TextSubs.add('Pulsating streams of golden mana echo through your body.', 'Pulsating (10/21) streams of golden mana echo through your body. (Holy)')
TextSubs.add('Glowing streams of golden mana echo through your body.', 'Glowing (11/21) streams of golden mana echo through your body. (Holy)')
TextSubs.add('Lambent streams of golden mana echo through your body.', 'Lambent (12/21) streams of golden mana echo through your body. (Holy)')
TextSubs.add('Shining streams of golden mana echo through your body.', 'Shining (13/21) streams of golden mana echo through your body. (Holy)')
TextSubs.add('Luminous streams of golden mana echo through your body.', 'Luminous (14/21) streams of golden mana echo through your body. (Holy)')
TextSubs.add('Radiant streams of golden mana echo through your body.', 'Radiant (15/21) streams of golden mana echo through your body. (Holy)')
TextSubs.add('Fulgent streams of golden mana echo through your body.', 'Fulgent (16/21) streams of golden mana echo through your body. (Holy)')
TextSubs.add('Brilliant streams of golden mana echo through your body.', 'Brilliant (17/21) streams of golden mana echo through your body. (Holy)')
TextSubs.add('Flaring streams of golden mana echo through your body.', 'Flaring (18/21) streams of golden mana echo through your body. (Holy)')
TextSubs.add('Glaring streams of golden mana echo through your body.', 'Glaring (19/21) streams of golden mana echo through your body. (Holy)')
TextSubs.add('Blazing streams of golden mana echo through your body.', 'Blazing (20/21) streams of golden mana echo through your body. (Holy)')
TextSubs.add('Blinding streams of golden mana echo through your body.', 'Blinding (21/21) streams of golden mana echo through your body. (Holy)')

**Comment by Hiinky** [comment]
Address in PR: https://github.com/rpherbig/dr-scripts/pull/4459
Ready to close.
