### ISSUE TITLE
Combat trainer missing a match during foraging

### ISSUE THREAD

**Issue by phalanxo** [rpherbig/dr-scripts#4399]
>collect rock
As you rummage around, you notice a small, brown colored cloud rise up into the air.  Inhaling, you drop to the ground, and suddenly realize you feel quite light headed.
Roundtime: 6 sec.
P> 
[combat-trainer: *** No match was found after 15 seconds, dumping info]

[combat-trainer: messages seen length: 17]

[combat-trainer: message: The ship's rat closes to pole weapon range on you!]

[combat-trainer: message: The ship's rat closes to melee range on you!]

[combat-trainer: message: The ship's rat closes to melee range on you!]

[combat-trainer: message: Khri Focus  (6 roisaen)]

[combat-trainer: message: The ship's rat closes to pole weapon range on you!]

[combat-trainer: message: The ship's rat closes to pole weapon range on you!]

[combat-trainer: message: The ship's rat is still a distance away from you and is closing steadily.]

[combat-trainer: message: The ship's rat begins to advance on you!]

[combat-trainer: message: [DRPrime]-DR:Kalinandra: "they defintiely do uraazh, read wiki. :)"]

[combat-trainer: message: The ship's rat is still a distance away from you and is closing steadily.]

[combat-trainer: message: The ship's rat begins to advance on you!]

[combat-trainer: message: Khri Focus  (6 roisaen)]

[combat-trainer: message: Roundtime: 6 sec.]

[combat-trainer: message: As you rummage around, you notice a small, brown colored cloud rise up into the air.  Inhaling, you drop to the ground, and suddenly realize you feel quite light headed.]

[combat-trainer: message: The ship's rat is still a distance away from you and is closing steadily.]

[combat-trainer: message: The ship's rat begins to advance on you!]

[combat-trainer: message: You begin to advance on a ship's rat.]

[combat-trainer: checked against [/You manage to collect a pile/i, /The room is too cluttered/i, /believe you would probably have better luck trying to find a dragon/i, /if you had a bit more luck./i, /You cannot collect anything/i, /You forage around but are unable to find anything/i, /You wander around and poke your fingers/i, /You survey the area and realize that any collecting efforts would be futile/i, /You are sure you knew/i, /You begin to forage around,/i]]

[combat-trainer: for command collect rock]

[combat-trainer]>stand

Never seen this one before, but the regex isn't grabbing it.

**Comment by vtcifer** [comment]
Looks like someone may have been mining in the room?

**Comment by phalanxo** [comment]
Ahh, haven't seen that message before, probably cause I don't mine. Guess that would explain it..

**Comment by vtcifer** [comment]
Looked at this further, and it doesn't quite match mining strings exactly.  It may be quirk of the area you're in, where was this?

**Comment by phalanxo** [comment]
It was in shipyard rats in the crossing with very low outdoorsmanship skill.

**Comment by Hiinky** [comment]
Addressed in PR: https://github.com/rpherbig/dr-scripts/pull/4458
Can be closed.
