### ISSUE TITLE
Trade Check Ability issue

### ISSUE THREAD

**Issue by SugarGnar** [rpherbig/dr-scripts#4402]
--- Lich: error: comparison of Float with nil failed	trade:1491:in `='	trade:1491:in `check_ability?'
--- Lich: trade has exited.

**Comment by Hiinky** [comment]
Could you provide more detail?  This is most likely a yaml error but without more detail it's impossible to tell.  Was this at the start of the script?  Somewhere in the middle?  Could you paste your yaml settings for ;trade?

**Comment by asechrest** [comment]
@rpherbig Ok, to close, no response from OP, no current reports of the issue. Thanks.
