### ISSUE TITLE
dancing with offhand support

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#441]
I'm sure this is super low priority but I wanted let yall know.

When dancing with an offhand weapon

[combat-trainer]>feint
Wouldn't it be better if you used a melee weapon?

**Comment by rpherbig** [comment]
I suspect that is because feint is in `dance_actions` in base.yaml. Can you try overriding `dance_actions` in your character's setup yaml (similar to how you overrode `dance_skill`)?

**Comment by rpherbig** [comment]
@xtremenerdrage Did that fix it?

**Comment by xtremenerdrage** [comment]
Yes! please close
