### ISSUE TITLE
Detect common problems

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#445]
There are some common problems that we spend time fixing over and over. We should find an automated way to at least detect these problems, if not fix them (or suggest a fix to the user):

- [x] Spacing errors in YAML files (the error message would have to be very very specific)
- [x] A weapon skill that returns 0 ranks and 0 exp, 99% of the time that means the weapon skill is spelled wrong and they'll get stuck in combat forever
- [x] If you have something in weapon_training it should be a valid skill name

Check out this site, it corrects YAML spacing errors when it can. Can we hook into an API? http://www.yamllint.com/

Maybe `;dependency validate` ?

**Comment by rpherbig** [comment]
Another test: dance list contains 'feint' and dance skill is Offhand (see #441)

**Comment by rpherbig** [comment]
- Mispelled skills
- Skills in stop_on that aren't in weapon training
- Weapons in weapon training that aren't in gear
- Hunting zones without a stop on or duration

**Comment by rpherbig** [comment]
Duplicated sections (e.g. two `training_abilities` settings caused Chuno some problems)

**Comment by rcuhljr** [comment]
We can't really detect duplicate sections right now, we can only detect errors with the final one.

**Comment by rpherbig** [comment]
Which of the above have you implemented so far, @rcuhljr ?

**Comment by rcuhljr** [comment]
offhand feint, misspelled skills, read the tests and find out :)

**Comment by rpherbig** [comment]
14cebb9c27cbb24587710438d97ca2078780bb48

7ca3dbdc21f4ce940ddd72809f6979fbc67164fe

4b516de17e09e8ec6385221f855ea66833dfcde5

8f6c1fc22fe8aaf4a866588c14d9ff0c3a7cccf8

e098fd2da80327920791fa9d75e76935a0bc5c57

**Comment by rpherbig** [comment]
2a2cc434d4307ff4970cc1beadcca3c7c5b795d5
