### ISSUE TITLE
[maps] Request "Amusement Pier" in Crossing be mapped

### ISSUE THREAD

**Issue by KatoakDR** [rpherbig/dr-scripts#4452]
## Maps
* http://www.kythsjournal.com/maps/ZolMisc1.htm
* https://elanthipedia.play.net/RanikMap1c

## Cartographers
* [x] @KatoakDR maps the day/night time rooms and upload map-db
* [ ] @Hiinky adds graphical/clickable map of amusement pier

**Comment by KatoakDR** [comment]
I've uploaded the mappings of the Amusement Pier during the daytime. Some rooms are different at night, I'll upload those once Elanthia goes to sleep.

Because of the snafu I caused with a typo for the custom movement from room 899 into the pier, I'm tag-teaming with Kali who will make that more advanced change as well as providing the visual clickable map of the pier.

**Comment by KatoakDR** [comment]
I've uploaded the map updates for night time room descriptions in the Amusement Pier (there were just a few rooms).

Also added the transition from room 899 to the Amusement Pier via:
```
;e Room.current.wayto['15891'] = StringProc.new("fput 'go amusement pier'; fput 'south'")
;e Room.current.timeto['15891'] = 0.2
```

In discussion with Kali, when moving to the pier from room 899 via "go amusement pier" then the game response is non-standard and Lich doesn't know what room we are in. However, after manually moving to another room within the pier and the back, Lich correctly recognizes the room. The extra "You whisper..." sentence throws the XML parsing off.

```
>go amusement pier

You whisper a command word as you step toward the amusement pier.  The curtain of magic that shimmers over the entry parts, allowing you to pass through.

[Amusement Pier, Entrance]
Salty air drifts upon the wind causing bits of old paper to dance around half-full garbage bins, while sweepers go by cleaning up the day's refuse.  Various buildings and attractions are visible in the torchlight further down the wide wooden and metal pier.
You also see an elaborate gate with carved leaping animal shapes.
Obvious paths: southeast, south, southwest.
```

The solution we devised was to use a custom transition from room 899 (outside the pier) to a room inside the pier just past the first room.

`go2` and `get2` are still able to move the character to any of the mapped rooms within the pier, even to the first room in the pier. The side effect is that if you are in the Crossing then say run `;get2 15891` then your path will look like from room 899 to be "go amusement pier, south, north". It's negligible in time cost and allows us to bypass the XML problem when moving from 899 to 15891 in one movement.

**Comment by KatoakDR** [comment]
As of `map-1598252498.json` the Amusement Pier mappings and StringProc transition from 899 are approved and available.

**Comment by Hiinky** [comment]
Image added - issue can be closed.

**Comment by KatoakDR** [comment]
Thanks @Hiinky
