### ISSUE TITLE
Appraisal script bonus feature

### ISSUE THREAD

**Issue by GreyhallowDR** [rpherbig/dr-scripts#4456]
I managed to restock my full pouches with some empty ones. 

What if... when running the appraisal script, it will put empty pouches in the spare gem pouch container instead of back in the full gem pouch container. 

The gem pouch is a container, and can be opened and closed.
The gem pouch is moderately soft.
It appears that the gem pouch can be worn attached to a belt.
You are certain that the gem pouch weighs exactly 1 stone.
**There doesn't appear to be anything in** the gem pouch.
Roundtime: 3 seconds.

**Comment by jandersson** [comment]
Is the issue that the script puts empty gem pouches in the wrong container?

**Comment by vtcifer** [comment]
I think the first line indicates they themselves put empty pouches in their full pouch container?

**Comment by GreyhallowDR** [comment]
sorry, just realized you guys replied. There is no problem with the script as it. I was making a suggestion for an improvement. 
Have the script respond to empty pouches pulled and rather than put them back in the full_pouch_container it could divert them to the spare_pouch_container.
