### ISSUE TITLE
Dependency github communication deprecation

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#4478]
By early march of 2021 github will stop supporting our method of communicating with the dr-scripts repository for retrieval of scripts.

https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

We use this [here](https://github.com/rpherbig/dr-scripts/blob/master/dependency.lic#L451). It can be corrected by removing that and adding it as a header to the request.

```
request = Net::HTTP::Get.new(uri.request_uri)
request['Authorization'] = "token #{@git_token}"
```

Should do the trick, but should of course be tested and verified.

**Comment by rcuhljr** [comment]
Five month reminder :)

**Comment by rcuhljr** [comment]
Two month reminder before every single thing breaks.

**Comment by rcuhljr** [comment]
Once month reminder until everything breaks.

**Comment by rpherbig** [comment]
@jandersson @KatoakDR @BinuDR @jayRyan24 could one of you take a swing at this?

**Comment by jayRyan24** [comment]
Yeah I can.

**Comment by BinuDR** [comment]
@rcuhljr There's a 25th anniversary of DR event going on right now and it includes a free month resub code!  Come back for a month! :-)

https://www.play.net/dr/promo/reactivate/home.asp?offerCode=DRBACKAFTER6

**Comment by rcuhljr** [comment]
:ackbar:
