### ISSUE TITLE
HidePostStrings flag breaks safe-room waiting for others to finish

### ISSUE THREAD

**Issue by vtcifer** [rpherbig/dr-scripts#4529]
Setting HidePostStrings flag to on breaks safe-room waiting in the auto-paths:

OFF (Works):
Also here: Foo who is lying down.

ON(Doesn't work):
Also here: Foo (prone).

**Comment by MahtraDR** [comment]
What do you propose we do here? I've been thinking about this, and not sure there is much we can do if folks hide post strings...

**Comment by MahtraDR** [comment]
Note also I don't use the non-premium autopaths, so if this isn't an issue anymore, let me know. :)

**Comment by MahtraDR** [comment]
Closing as stale.
