### ISSUE TITLE
Workorders, Selecting your own ingot

### ISSUE THREAD

**Issue by MartyenDR** [rpherbig/dr-scripts#453]
so i talked with E about this, and he told me to arise an issue.

Thought this would be a neat addition to 'Workorders'. Selecting what type of ingot you made things out of, or selecting a premade ingot that may be more valuable.

just throwing this out there.

**Comment by rcuhljr** [comment]
```use_own_ingot_type: bronze
deed_own_ingot: false```

It will use an ingot of the given noun, if none exists it will try to find a deed of that noun and tap it. When done it will deed the ingot again if set to true.
