### ISSUE TITLE
tendme script suggestion

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#4531]
Was wondering that if you have tendme already running after your death, that maybe it'll do another health check for bleeders when you start to "bleed" again.

Messaging:
You feel a brief tingling sensation and then notice that you're bleeding.

**Comment by KatoakDR** [comment]
@Kaesken Curious, when you say "running after your death" do you mean that you want the `tendme` script to see if you're bleeding _while you're dead_ or after you've been resurrected? And if you've been resurrected, your concern is that you may not have been healed of your bleeders so you want `tendme` to take action to tend your wounds again?

**Comment by jandersson** [comment]
I think the question is does the script work after you've died and been brought back to life. Yes it does. If it doesn't, we need an issue for it!
