### ISSUE TITLE
Locksmithing.lic

### ISSUE THREAD

**Issue by DryIce41** [rpherbig/dr-scripts#4558]
The match table doesn't include "You detach"  Can that be added please"

You detach a thigh pouch with a lock in the shape of a corn kernel from your thigh.

[locksmithing: checked against [/You take/i, /Remove what/i, /You aren't wearing that/i, /You sling/i, /You remove/i]]

**Comment by rpherbig** [comment]
@DryIce41 it should be fixed, let me know if it's still breaking
