### ISSUE TITLE
Stealing updates

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#457]
"Possibly adjust trivial level for cravat in **19376** upwards, still difficult at 89", "Possibly adjust trivial level for cambrinth flake in **19152** upwards, still difficult at 89", "Possibly adjust trivial level for cloth in **19380** upwards, still difficult at 89"]]

**Comment by Aurayn** [comment]
[exec1: ["Adjust trivial level for oil in 19076 upwards, still exceptionally difficult at 86", "Adjust trivial level for oil in 19076 upwards, still exceptionally difficult at 90", "Adjust trivial level for ocarina in 19078 upwards, still exceptionally difficult at 90", "Adjust trivial level for hat in  upwards, still exceptionally difficult at 90", "Possibly adjust trivial level for cravat in 19376 upwards, still difficult at 89", "Possibly adjust trivial level for cambrinth flake in 19152 upwards, still difficult at 89", "Possibly adjust trivial level for cloth in 19380 upwards, still difficult at 89", "Possibly adjust trivial level for cravat in 19376 upwards, still difficult at 90"]]

**Comment by Aurayn** [comment]
>;e echo((UserVars.challenging_steal_log ||= [])+(UserVars.mid_steal_log ||= [])+(UserVars.trivial_steal_log ||= []))
--- Lich: exec1 active.
[exec1: ["Adjust trivial level for oil in 19076 upwards, still exceptionally difficult at 86", "Adjust trivial level for oil in 19076 upwards, still exceptionally difficult at 90", "Adjust trivial level for ocarina in 19078 upwards, still exceptionally difficult at 90", "Adjust trivial level for hat in  upwards, still exceptionally difficult at 90", "Adjust trivial level for oil in 19076 upwards, still exceptionally difficult at 90", "Adjust trivial level for ocarina in 19078 upwards, still exceptionally difficult at 90", "Adjust trivial level for hat in 19386 upwards, still exceptionally difficult at 90", "Possibly adjust trivial level for cravat in 19376 upwards, still difficult at 89", "Possibly adjust trivial level for cambrinth flake in 19152 upwards, still difficult at 89", "Possibly adjust trivial level for cloth in 19380 upwards, still difficult at 89", "Possibly adjust trivial level for cravat in 19376 upwards, still difficult at 90", "Possibly adjust trivial level for cravat in 19376 upwards, still difficult at 90", "Possibly adjust trivial level for shoes in 19388 upwards, still difficult at 90"]]
--- Lich: exec1 has exited.

**Comment by rcuhljr** [comment]
Updated.

**Comment by Aurayn** [comment]
Adjust trivial level for oil in 19076 upwards, still exceptionally difficult at 86
Adjust trivial level for oil in 19076 upwards, still exceptionally difficult at 90
Adjust trivial level for ocarina in 19078 upwards, still exceptionally difficult at 90
Adjust trivial level for hat in  upwards, still exceptionally difficult at 90
Adjust trivial level for oil in 19076 upwards, still exceptionally difficult at 90
Adjust trivial level for ocarina in 19078 upwards, still exceptionally difficult at 90
Adjust trivial level for hat in 19386 upwards, still exceptionally difficult at 90
Adjust trivial level for oil in 19076 upwards, still exceptionally difficult at 92
Adjust trivial level for vial in 19073 upwards, still IMPOSSIBLY difficult at 92
Adjust trivial level for high-button shoes in 19388 upwards, still IMPOSSIBLY difficult at 92
Adjust trivial level for signet ring in 4697 upwards, still IMPOSSIBLY difficult at 92
Adjust trivial level for rugged cowl in 19218 upwards, still IMPOSSIBLY difficult at 92
Possibly adjust trivial level for cravat in 19376 upwards, still difficult at 89
Possibly adjust trivial level for cambrinth flake in 19152 upwards, still difficult at 89
Possibly adjust trivial level for cloth in 19380 upwards, still difficult at 89
Possibly adjust trivial level for cravat in 19376 upwards, still difficult at 90
Possibly adjust trivial level for cravat in 19376 upwards, still difficult at 90
Possibly adjust trivial level for shoes in 19388 upwards, still difficult at 90
Possibly adjust trivial level for cambrinth flake in 19152 upwards, still difficult at 93

**Comment by Aurayn** [comment]
Adjust trivial level for cigarillo in 19385 upwards, still IMPOSSIBLY difficult at 93
Adjust trivial level for oil in 19076 upwards, still exceptionally difficult at 93
Adjust trivial level for vial in 19073 upwards, still IMPOSSIBLY difficult at 93
Adjust trivial level for high-button shoes in 19388 upwards, still IMPOSSIBLY difficult at 93
Adjust trivial level for signet ring in 4697 upwards, still IMPOSSIBLY difficult at 93
Adjust trivial level for rugged cowl in 7904 upwards, still IMPOSSIBLY difficult at 93
Possibly adjust trivial level for sling in 19237 upwards, still difficult at 93

**Comment by rcuhljr** [comment]
updated.

**Comment by rcuhljr** [comment]
[Private]-DR:Brevan: "Yeah I accidentally pasted the SF log instead of the pastbin link and got myself disconnected."
[Private]-DR:Brevan: "Recommend adding earrings to the list after stud, and rugged aventail after rugged mask."
[Private]-DR:Brevan: "That's what I put in for my own script because the next item in lich was a big jump."
[Private]-DR:Brevan: "Also recommend raising the difficulty of alcohol in the alchemy shop. I've been caught every run so far, even though it flags as acceptable."

**Comment by Aurayn** [comment]
PASTEBINnew pastetrends 
search...
 

Guest User
-
SHARE
TWEET

Untitled
 A GUEST   JUN 23RD, 2016   29   NEVER

rawdownloadcloneembedreportprint text 3.34 KB
Adjust trivial level for oil in 19076 upwards, still exceptionally difficult at 93
Adjust trivial level for vial in 19073 upwards, still IMPOSSIBLY difficult at 93
Adjust trivial level for high-button shoes in 19388 upwards, still IMPOSSIBLY difficult at 93
Adjust trivial level for signet ring in 4697 upwards, still IMPOSSIBLY difficult at 93
Adjust trivial level for rugged cowl in 7904 upwards, still IMPOSSIBLY difficult at 93
Adjust trivial level for feathered charm in 19377 upwards, still IMPOSSIBLY difficult at 93
Adjust trivial level for cigarillo in 19385 upwards, still IMPOSSIBLY difficult at 94
Adjust trivial level for vial in 19073 upwards, still IMPOSSIBLY difficult at 94
Adjust trivial level for vial in 19073 upwards, still IMPOSSIBLY difficult at 94
Adjust trivial level for high-button shoes in 19218 upwards, still IMPOSSIBLY difficult at 94
Adjust trivial level for signet ring in 4697 upwards, still IMPOSSIBLY difficult at 94
Adjust trivial level for rugged cowl in 7904 upwards, still IMPOSSIBLY difficult at 94
Adjust trivial level for feathered charm in 19377 upwards, still IMPOSSIBLY difficult at 94
Adjust trivial level for bobbin in 19379 upwards, still IMPOSSIBLY difficult at 94
Adjust trivial level for cigarillo in 19385 upwards, still IMPOSSIBLY difficult at 94
Adjust trivial level for vial in 19073 upwards, still IMPOSSIBLY difficult at 95
Adjust trivial level for high-button shoes in 19388 upwards, still IMPOSSIBLY difficult at 95
Adjust trivial level for signet ring in 4697 upwards, still IMPOSSIBLY difficult at 95
Adjust trivial level for rugged cowl in 7904 upwards, still IMPOSSIBLY difficult at 95
Adjust trivial level for feathered charm in 19377 upwards, still IMPOSSIBLY difficult at 95
Adjust trivial level for bobbin in 19379 upwards, still IMPOSSIBLY difficult at 95
Adjust trivial level for cigarillo in 19385 upwards, still IMPOSSIBLY difficult at 95
Adjust trivial level for feathered charm in 19377 upwards, still IMPOSSIBLY difficult at 95
Adjust trivial level for bobbin in 19379 upwards, still IMPOSSIBLY difficult at 95
Adjust trivial level for feathered charm in 19377 upwards, still IMPOSSIBLY difficult at 96
Adjust trivial level for bobbin in 19379 upwards, still IMPOSSIBLY difficult at 96
Adjust trivial level for feathered charm in 19377 upwards, still exceptionally difficult at 97
Adjust trivial level for bobbin in 19379 upwards, still exceptionally difficult at 97
Possibly adjust trivial level for cambrinth flake in 19152 upwards, still difficult at 93
Possibly adjust trivial level for oil in 19076 upwards, still difficult at 94
Possibly adjust trivial level for sling in 19237 upwards, still difficult at 94
Possibly adjust trivial level for oil in 19076 upwards, still difficult at 94
Possibly adjust trivial level for cambrinth flake in 19152 upwards, still difficult at 94
Possibly adjust trivial level for sling in 19237 upwards, still difficult at 94
Possibly adjust trivial level for oil in 19076 upwards, still difficult at 95
Possibly adjust trivial level for oil in 19076 upwards, still difficult at 95
Possibly adjust trivial level for oil in 19076 upwards, still difficult at 96
Possibly adjust trivial level for oil in 19076 upwards, still difficult at 97
Possibly adjust trivial level for oil in 19076 upwards, still difficult at 97
Low Learning level for herb bag in 8265 to 97
Low Learning level for herb bag in 8265 to 97
RAW Paste Data

Adjust trivial level for oil in 19076 upwards, still exceptionally difficult at 93
Adjust trivial level for vial in 19073 upwards, still IMPOSSIBLY difficult at 93
Adjust trivial level for high-button shoes in 19388 upwards, still IMPOSSIBLY difficult at 93
Adjust trivial level for signet ring in 4697 upwards, still IMPOSSIBLY difficult at 93
Adjust trivial level for rugged cowl in 7904 upwards, still IMPOSSIBLY difficult at 93
Adjust trivial level for feathered charm in 19377 upwards, still IMPOSSIBLY difficult at 93
Adjust trivial level for cigarillo in 19385 upwards, still IMPOSSIBLY difficult at 94
Adjust trivial level for vial in 19073 upwards, still IMPOSSIBLY difficult at 94
Adjust trivial level for vial in 19073 upwards, still IMPOSSIBLY difficult at 94
Adjust trivial level for high-button shoes in 19218 upwards, still IMPOSSIBLY difficult at 94
Adjust trivial level for signet ring in 4697 upwards, still IMPOSSIBLY difficult at 94
Adjust trivial level for rugged cowl in 7904 upwards, still IMPOSSIBLY difficult at 94
Adjust trivial level for feathered charm in 19377 upwards, still IMPOSSIBLY difficult at 94
Adjust trivial level for bobbin in 19379 upwards, still IMPOSSIBLY difficult at 94
Adjust trivial level for cigarillo in 19385 upwards, still IMPOSSIBLY difficult at 94
Adjust trivial level for vial in 19073 upwards, still IMPOSSIBLY difficult at 95
Adjust trivial level for high-button shoes in 19388 upwards, still IMPOSSIBLY difficult at 95
Adjust trivial level for signet ring in 4697 upwards, still IMPOSSIBLY difficult at 95
Adjust trivial level for rugged cowl in 7904 upwards, still IMPOSSIBLY difficult at 95
Adjust trivial level for feathered charm in 19377 upwards, still IMPOSSIBLY difficult at 95
Adjust trivial level for bobbin in 19379 upwards, still IMPOSSIBLY difficult at 95
Adjust trivial level for cigarillo in 19385 upwards, still IMPOSSIBLY difficult at 95
Adjust trivial level for feathered charm in 19377 upwards, still IMPOSSIBLY difficult at 95
Adjust trivial level for bobbin in 19379 upwards, still IMPOSSIBLY difficult at 95
Adjust trivial level for feathered charm in 19377 upwards, still IMPOSSIBLY difficult at 96
Adjust trivial level for bobbin in 19379 upwards, still IMPOSSIBLY difficult at 96
Adjust trivial level for feathered charm in 19377 upwards, still exceptionally difficult at 97
Adjust trivial level for bobbin in 19379 upwards, still exceptionally difficult at 97
Possibly adjust trivial level for cambrinth flake in 19152 upwards, still difficult at 93
Possibly adjust trivial level for oil in 19076 upwards, still difficult at 94
Possibly adjust trivial level for sling in 19237 upwards, still difficult at 94
Possibly adjust trivial level for oil in 19076 upwards, still difficult at 94
Possibly adjust trivial level for cambrinth flake in 19152 upwards, still difficult at 94
Possibly adjust trivial level for sling in 19237 upwards, still difficult at 94
Possibly adjust trivial level for oil in 19076 upwards, still difficult at 95
Possibly adjust trivial level for oil in 19076 upwards, still difficult at 95
Possibly adjust trivial level for oil in 19076 upwards, still difficult at 96
Possibly adjust trivial level for oil in 19076 upwards, still difficult at 97
Possibly adjust trivial level for oil in 19076 upwards, still difficult at 97
Low Learning level for herb bag in 8265 to 97
Low Learning level for herb bag in 8265 to 97
BitBucket - Backup your code in the cloud! Host unlimited private projects, for free. SIGN UP takes 10 seconds, and it's free!
                
create new paste  /  dealsnew!  /  api  /  trends  /  syntax languages  /  faq  /  tools  /  privacy  /  cookies  /  contact  /  dmca  /  advertise on pastebin  /  scraping  /  go  
Site design & logo © 2016 Pastebin; user contributions (pastes) licensed under cc by-sa 3.0 -- Dedicated Server Hosting by Steadfast

**Comment by rcuhljr** [comment]
The link to pastebin might be easier to put here :)  I'm going to build in automatic stealing difficulty updates so don't worry about posting updates for now.

**Comment by rcuhljr** [comment]
New stealing version is live, closing this, file a new issue for new issues :)
