### ISSUE TITLE
hunting_buddies

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#460]
It doesn't attempt to skin but then errors for not getting a skinning message, taps the bundle then times out when buddy skins his kill.

[combat-trainer]>tap bundle

[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 23]
[combat-trainer: message: You tap a tight bundle on the ground.]
[combat-trainer: message: Kargarth begins arranging the toad's corpse to increase the chance of a high quality prize.]
[combat-trainer: message: A red and black treehopper toad slaps fervently at Kargarth.  ]
[combat-trainer: message: Working deftly, Kargarth skillfully removes a toad gland from the remains of a red and black treehopper toad.]
[combat-trainer: message: A rainbow-hued treehopper toad slaps fervently at Kargarth.  ]
[combat-trainer: message: A vivid violet treehopper toad slaps fervently at Kargarth.  ]
[combat-trainer: message: Kargarth drops a poisonous toad gland.]
[combat-trainer: message: Kargarth bends over the toad's corpse briefly.]
[combat-trainer: message: The treehopper toad begins to advance on Kargarth.]
[combat-trainer: message: The treehopper toad slowly decays into little more than a shimmering puddle, which eventually evaporates into nothingness.]
[combat-trainer: message: Kargarth jabs a steel hanger at a rainbow-hued treehopper toad.  ]
[combat-trainer: message: Claws of the Cougar  (11 roisaen)]
[combat-trainer: message: See the Wind  (11 roisaen)]
[combat-trainer: message: Skein of Shadows  (23 roisaen)]
[combat-trainer: message: Sense of the Tiger  (29 roisaen)]
[combat-trainer: message: Hands of Lirisa  (10 roisaen)]
[combat-trainer: message: Instinct  (10 roisaen)]
[combat-trainer: message: A red and black treehopper toad slaps fervently at Kargarth.  ]
[combat-trainer: message: Kargarth slices a steel hanger at a rainbow-hued treehopper toad.  The hanger lands a good hit to its back!  ]
[combat-trainer: message: A rainbow-hued treehopper toad slaps fervently at Kargarth.  ]
[combat-trainer: message: A vivid violet treehopper toad slaps fervently at Kargarth.  ]
[combat-trainer: message: Kargarth slices a steel hanger at a rainbow-hued treehopper toad.  ]
[combat-trainer: message: You feel fully rested.]
[combat-trainer: checked against [/You tap a \w+ bundle that you are wearing/i, /I could not find what you were referring to/i]]
[combat-trainer]>skin
Skin what?

**Comment by rcuhljr** [comment]
adding a tap **my** bundle.

**Comment by rpherbig** [comment]
9e9546607600e490584293e5493c5f6a4a40c46d
