### ISSUE TITLE
New message needs matched for removing corn maze gloves

### ISSUE THREAD

**Issue by dakre18** [rpherbig/dr-scripts#4613]
The **heavy chain gloves bearing a blue-white phoenix** bought from the corn maze has a different removal message, that crossing-repair is not picking up. This may apply to other scripts that remove gloves.

`[crossing-repair]>remove my chain.gloves`
`Wiggling your fingers as mages do, you manage to loosen the chain gloves enough to pull them off.`

**Comment by KatoakDR** [comment]
@dakre18 Is there a special message when you wear the gloves, too?

**Comment by dakre18** [comment]
Yes. almost forgot that.

`[crossing-repair]>wear my chain.gloves`
`You tug on the chain gloves, flexing your hand as you pull them on for a snug fit.`

**Comment by Dartellum** [comment]
@KatoakDR you working on this?

**Comment by KatoakDR** [comment]
@Dartellum   It’s on my todo list today but haven’t started yet if you’re gunning for it

**Comment by Dartellum** [comment]
@KatoakDR it is on your list, go for it. :+1:

**Comment by KatoakDR** [comment]
On it!

**Comment by dakre18** [comment]
Found another in Appraisal:

> [appraisal]>remove my chain.gloves
> Wiggling your fingers as mages do, you manage to loosen the chain gloves enough to pull them off.
> [appraisal: *** No match was found after 15 seconds, dumping info]
> 
> [appraisal: message: Wiggling your fingers as mages do, you manage to loosen the chain gloves enough to pull them off.]
> [appraisal: checked against [/^You .*(?i-mx:\bchain.*\bgloves)/, /^You (get|sling|pull|work|loosen|slide|remove|yank).*gloves/, /Remove what/i, /You aren't wearing that/i, /slide themselves off of your/i]]
> [appraisal: for command remove my chain.gloves]

Not sure of any others, but without looking at the code, i don't know if it uses a common function or not.

**Comment by KatoakDR** [comment]
Thanks, the appraisal script uses the equipmanager script. We’re waiting on the PR to be approved and merged for the fix to go live.
