### ISSUE TITLE
base-picking error in disarm quick message list

### ISSUE THREAD

**Issue by LuckyThiefDR** [rpherbig/dr-scripts#4631]
On line 85 of my copy of base-picking, under the heading "disarm_quick:", there is this incorrect message:

  - This trap is a laughable matter, you could do it blindfolded!

The actual message in game reads:

  - This trap is a laughable matter -- you could do it blindfolded!

Due to the mismatch, the pick script defaults to using disarm careful instead of quick.  A simple fix that worked for me is to shorten the message to this:

  - This trap is a laughable matter

**Comment by KatoakDR** [comment]
Good catch, I believe it might be related to enabling TOGGLE APPRAISAL or recent phrasing changes otherwise unannounced. 

We’ll get a fix in soon, thanks
