### ISSUE TITLE
Magic Manager (Waggle from GS copy)

### ISSUE THREAD

**Issue by izawwlgood** [rpherbig/dr-scripts#464]
This is a screenshot of Waggle for GS - http://imgur.com/Yz3TVMD

I think something akin to this would be useful for DR. I imagine the user would have to enter 'Spells to Maintain', one by one, and enter parameters for each. For example, say I wanted to maintain OBF, I would enter OBF as the spell. Parameters would include 'how much mana to prep at', 'whether to use a cambrinth (which one [armband/anklet/etc], and how much [15])', and duration minimum to recast (i.e., if <5 rois or dropped entirely, recast). Spells could be entered in the order the script would check for, and recast them. I.e., maybe CH is a higher priority than BUE, so I would put CH first. With that in mind, it may also be useful to have 'move up' or 'move down' arrows for changing the order. This could also be useful for making sure cyclics don't drop for whatever reason!

Some toggles could be 'how much attunement to wait for before moving onto the next spell', whether or not the spell should be skipped if it backfires.

**Comment by rcuhljr** [comment]
First pass done, sample config [here](https://github.com/rpherbig/dr-scripts/blob/master/profiles/Selanas-setup.yaml#L200-L220). `;waggle` with no arguments uses the default list.

I'm gonna close this issue, I'd move your improvement ideas (adjustable attunement window, etc) to a new issue so we do lose track of them.
