### ISSUE TITLE
Combat Trainer - please add fragment (shell fragments) sling ammo (from fest games) 

### ISSUE THREAD

**Issue by TegCross** [rpherbig/dr-scripts#4645]
Please add 'fragment' to all relevant ammo places in Combat Trainer, specifically my issue arose from the 'shoot' command with my sling.

>The fragment lands a strong hit (6/23) to the bucca's right leg.

[combat-trainer: checked against [/isn't loaded/i, /There is nothing/i, /But your/i, /you (fire|poach|snipe) an? (?:.*\s)?(arrows?|bolt|shard|rock|sphere|clump|coral|fist|holder|lump|patella|pellet|pulzone|quadrello|quill|stone|stopper|verretto|crumb|spine|mantrap spike|tiny dragon|icicle|fang|scale|grey-black spike|bacon strip|page|naga|thorn).* at/i, /I could not find/i, /with no effect and falls to the ground/i, /Face what/i, /How can you (poach|snipe)/i, /you don't feel like fighting right now/i, /That weapon must be in your right hand to fire/i]]

[combat-trainer: for command shoot]

**Comment by KatoakDR** [comment]
Thanks for the report, @TegCross. Will take a look into it.
