### ISSUE TITLE
Combat-trainer - turn to face

### ISSUE THREAD

**Issue by TegCross** [rpherbig/dr-scripts#4649]
As shown in the log below, it appears there are several checks, but none for facing an opponent without a roundtime. This appeared to occur because I was too far away from the critter to hit it and was not facing it.

Forgive me if there is another issue open on this or I'm missing something, the only other somewhat related open issue was from 2018 and the notes all reference a barb using whirlwind with light attacks enabled.

[combat-trainer]>loot

I could not find what you were referring to.
> 
**[combat-trainer]>gouge**

You feel fully rested.

> 
**You turn to face a silver-backed bear.**
> 
Xanhand begins to advance on a silver-backed bear.
> 
Sserinth loads his competition shortbow with a boar-tusk arrow.
> 
The loud roaring of a raging inferno emanates from a tiny fiery fissure.
> 
A silver-backed bear rots away into nothingness.

> 
Sserinth appears to be aiming at a silver-backed bear with his competition shortbow.
> 
A silver-backed bear slumps wearily.
> 
The air around Sserinth crackles with more static electricity causing more random discharges!
Static electricity from the eddy around Sserinth discharges through a silver-backed bear, but it seems unaffected.
> 
Sserinth removes a cambrinth armband made of interlocking wildling spiders from his upper arm.
> 
Xanhand closes to pole weapon range on a silver-backed bear.
> 
Sserinth attaches a cambrinth armband made of interlocking wildling spiders to his upper arm.
> 
Sserinth gestures.
Sserinth's cambrinth armband emits a loud *snap*.
The air around Sserinth shimmers with a dull yellow haze.  The scintillating light writhes and twists, abruptly coalescing into a translucent field before blinking out of sight.
> 
Xanhand lands a hard hit (5/23) to the bear's abdomen.  
> 
Sserinth bobs, lowering himself into a smaller target.
> 
Sserinth traces a curving sigil in the air.
Sserinth begins to focus intently on a silver-backed bear.
> 
Sserinth bobs, lowering himself into a smaller target.
> 
[combat-trainer: *** No match was found after 15 seconds, dumping info]

[combat-trainer: messages seen length: 28]

[combat-trainer: message: Sserinth bobs, lowering himself into a smaller target.]

[combat-trainer: message: Sserinth begins to focus intently on a silver-backed bear.]

[combat-trainer: message: Sserinth traces a curving sigil in the air.]

[combat-trainer: message: Sserinth bobs, lowering himself into a smaller target.]

[combat-trainer: message: Xanhand lands a hard hit to the bear's abdomen.  ]

[combat-trainer: message: The air around Sserinth shimmers with a dull yellow haze.  The scintillating light writhes and twists, abruptly coalescing into a translucent field before blinking out of sight.]

[combat-trainer: message: Sserinth's cambrinth armband emits a loud *snap*.]

[combat-trainer: message: Sserinth gestures.]

[combat-trainer: message: Sserinth attaches a cambrinth armband made of interlocking wildling spiders to his upper arm.]

[combat-trainer: message: Xanhand closes to pole weapon range on a silver-backed bear.]

[combat-trainer: message: Persistence of Mana  (26 roisaen)]

[combat-trainer: message: Shield of Light  (12 roisaen)]

[combat-trainer: message: Bless  (18 roisaen)]

[combat-trainer: message: Sanctify Pattern  (2 roisaen)]

[combat-trainer: message: Minor Physical Protection  (25 roisaen)]

[combat-trainer: message: Major Physical Protection  (11 roisaen)]

[combat-trainer: message: Manifest Force  (24 roisaen)]

[combat-trainer: message: Sserinth removes a cambrinth armband made of interlocking wildling spiders from his upper arm.]

[combat-trainer: message: Static electricity from the eddy around Sserinth discharges through a silver-backed bear, but it seems unaffected.]

[combat-trainer: message: The air around Sserinth crackles with more static electricity causing more random discharges!]

[combat-trainer: message: A silver-backed bear slumps wearily.]

[combat-trainer: message: Sserinth appears to be aiming at a silver-backed bear with his competition shortbow.]

[combat-trainer: message: A silver-backed bear rots away into nothingness.]

[combat-trainer: message: The loud roaring of a raging inferno emanates from a tiny fiery fissure.]

[combat-trainer: message: Sserinth loads his competition shortbow with a boar-tusk arrow.]

[combat-trainer: message: Xanhand begins to advance on a silver-backed bear.]

**[combat-trainer: message: You turn to face a silver-backed bear.]**

[combat-trainer: message: You feel fully rested.]

**[combat-trainer: checked against [/Wouldn't it be better if you used a melee weapon?/i, /Face What?/i, /Roundtime/i, /You aren't close enough to attack/i, /It would help if you were closer/i, /There is nothing else to face!/i, /You must be hidden/i, /flying too high for you to attack/i, /Bumbling, you slip/i]]**

**[combat-trainer: for command gouge]**

**Comment by KatoakDR** [comment]
Thanks for the detailed report, I'll take a look

**Comment by TegCross** [comment]
@KatoakDR @rpherbig I don't think I thanked you both for the last fix, so... Thank you! Thank you!
