### ISSUE TITLE
mining-manager retreat

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#465]
[go2: move: no recognized response in 30 seconds.  giving up.]
[go2: restarting script...]
[go2]>combatant
Please rephrase that command.
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You evade.  
[You're solidly balanced and opponent has slight advantage.]
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You evade.  
[You're solidly balanced with no advantage.]
>
A beisswurm slowly slithers toward you!
* A beisswurm slices wide at you.  You dodge.  
[You're solidly balanced with no advantage.]
>comb
You must be holding both substances to combine them.  For more information, see HELP VERB COMBINE.
>
A beisswurm slowly slithers toward you!
* A beisswurm slices wide at you.  You evade.  
[You're solidly balanced and in better position.]
>combat
Other characters' combat messages now turned OFF.
>
--- Lich: 'go2' has been stopped by mining-buddy.
--- Lich: go2 has exited.

**Comment by rcuhljr** [comment]
Do you have the log of the 30 seconds before? that's the part that broke leading to this.

**Comment by xtremenerdrage** [comment]
[go2]>northeast
The beisswurm begins to advance on you!
The beisswurm advances from nearby and is closing steadily.
>
You can't do that while engaged!
>
[go2: move: failed]
[go2: restarting script...]
[go2: ETA: 0:00:25 (28 rooms to move through)]
[go2]>northeast
You can't do that while engaged!
>
[go2: move: failed]
[go2: restarting script...]
[go2]>combatant
Please rephrase that command.
>

**Comment by xtremenerdrage** [comment]
[go2]>north
You go north.
[Abandoned Mine, Tunnel - 7266]
Poised to attack stands a dwarf frozen in all of his glory.  You also see a beisswurm, a beisswurm and a beisswurm.
Obvious exits: north, northeast, south.
>
[go2]>northeast
The beisswurm begins to advance on you!
The beisswurm advances from nearby and is closing steadily.
>
You can't do that while engaged!
>
[go2: move: failed]
[go2: restarting script...]
[go2: ETA: 0:00:25 (28 rooms to move through)]
[go2]>northeast
You can't do that while engaged!
>
[go2: move: failed]
[go2: restarting script...]
[go2]>combatant
Please rephrase that command.
>
The beisswurm begins to advance on you!
The beisswurm advances from nearby and is closing steadily.
>
Dread Dreaderic just arrived.
>
Dread Dreaderic drifts south.
>
The beisswurm closes to melee range on you!
>
The beisswurm closes to melee range on you!
>
The beisswurm begins to advance on you!
The beisswurm advances from nearby and is closing steadily.
>
The beisswurm closes to melee range on you!
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You evade.  
[You're solidly balanced and in better position.]
>
A beisswurm slowly slithers toward you!
* A beisswurm claws at you.  You evade.  
[You're solidly balanced and in good position.]
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You evade.  
[You're solidly balanced and have slight advantage.]
>
A beisswurm slithers in.
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You dodge.  
[You're solidly balanced and in better position.]
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You dodge.  
[You're solidly balanced and in good position.]
>
A beisswurm slowly slithers toward you!
* A beisswurm claws at you.  You dodge.  
[You're solidly balanced and in strong position.]
>
The beisswurm begins to advance on you!
The beisswurm advances from nearby and is closing steadily.
>
A beisswurm slowly slithers toward you!
* A beisswurm claws at you.  You counter nearly all the claw with a blued-steel parry stick detailed with prowling black foxes.  
[You're solidly balanced and have slight advantage.]
>
The beisswurm closes to melee range on you!
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You beat off nearly all the teeth with a blued-steel parry stick detailed with prowling black foxes.  
[You're solidly balanced and in strong position.]
>
A beisswurm slowly slithers toward you!
* A beisswurm slices wide at you.  You deflect nearly all the claw with a blued-steel parry stick detailed with prowling black foxes.  
[You're solidly balanced and in better position.]
>
A beisswurm slowly slithers toward you!
* A beisswurm claws at you.  You fend off nearly all the claw with a blued-steel parry stick detailed with prowling black foxes.  
[You're solidly balanced and have slight advantage.]
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You counter nearly all the teeth with a blued-steel parry stick detailed with prowling black foxes.  
[You're solidly balanced and in better position.]
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You dodge.  
[You're solidly balanced and in excellent position.]
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You turn aside nearly all the teeth with a blued-steel parry stick detailed with prowling black foxes.  
[You're solidly balanced with opponent in better position.]
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You slap away nearly all the teeth with a blued-steel parry stick detailed with prowling black foxes.  
[You're solidly balanced and in strong position.]
>
Dread Dreaderic just arrived.
>
Dread Dreaderic drifts northeast.
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You dodge.  
[You're solidly balanced and in very strong position.]
>
Uncurling slowly from around your wrist, your onyx-eyed viper winds its way slowly up your arm and across your shoulder.  It pauses briefly, flicking its tongue to gain its bearings.  Blinking its jewel-like eyes it slithers over to your neck where it loops itself in graceful coils before returning to its sleeping state.
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You evade.  
[You're solidly balanced and in strong position.]
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You dodge.  
[You're solidly balanced with opponent in better position.]
>
A beisswurm slowly slithers toward you!
* A beisswurm claws at you.  You slap away nearly all the claw with a blued-steel parry stick detailed with prowling black foxes.  
[You're solidly balanced and have slight advantage.]
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You fend off nearly all the teeth with a blued-steel parry stick detailed with prowling black foxes.  
[You're solidly balanced and in superior position.]
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You dodge.  
[You're solidly balanced and in good position.]
>
A beisswurm slowly slithers toward you!
* A beisswurm claws at you.  You evade.  
[You're solidly balanced and in better position.]
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You counter nearly all the teeth with a blued-steel parry stick detailed with prowling black foxes.  
[You're solidly balanced and opponent has slight advantage.]
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You deflect nearly all the teeth with a blued-steel parry stick detailed with prowling black foxes.  
[You're solidly balanced and in good position.]
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You evade.  
[You're solidly balanced and in strong position.]
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You evade.  
[You're solidly balanced and opponent has slight advantage.]
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You evade.  
[You're solidly balanced and in better position.]
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You turn aside nearly all the teeth with a blued-steel parry stick detailed with prowling black foxes.  
[You're solidly balanced and have slight advantage.]
>
A beisswurm slowly slithers toward you!
* A beisswurm bites at you.  You evade.  
[You're solidly balanced and in very strong position.]

**Comment by rcuhljr** [comment]
Resolved. (lich auto update turned off.)
