### ISSUE TITLE
mining-manager doesn't mine

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#466]
--- Lich: error: nil can't be coerced into Fixnum
	mine:20:in `*'
	mine:20:in `initialize'
--- Lich: mine has exited.

**Comment by xtremenerdrage** [comment]
[mine]>prospect
You see evidence of mineral deposits and are certain a substantial quantity (4/5) remains to be found.
This area is composed of sedimentary rock layers.
Studying the geology, you are certain that continued mining will be quite safe.
You are certain that sandstone can be mined here.
You are certain that oravir can be mined here.
Miners stand ready to trade resources in for deeds.  Just PUSH any mined up stone or metal, and they'll take care of the rest.
Roundtime: 8 sec.
>
--- Lich: error: nil can't be coerced into Fixnum
	mine:20:in `*'
	mine:20:in `initialize'
--- Lich: mine has exited.
>

**Comment by rcuhljr** [comment]
Still not fixed apparently, need to test how the regex capture works with escapes stuff I think.

**Comment by rcuhljr** [comment]
Hopefully fixed, apparently I didn't push my mine changes.

**Comment by rpherbig** [comment]
4c378cafad1955ded62c1969b1adb73343492c2d
