### ISSUE TITLE
Pick does not recognize thief trap save from khri safe

### ISSUE THREAD

**Issue by LuckyThiefDR** [rpherbig/dr-scripts#4662]
With Khri Safe active, a thief can make a kind of saving throw when a trap is blown. However, the trap is not disarmed, it simply does not activate.

Pick does not recognize the text and instead assumes the trap is disarmed and moves on to picking, which immediately activates the trap.

Here is a sample:
---
[pick]>disarm my ironwood caddy identify
>
The hinges of the ironwood caddy are covered with a thin metal circle that has been lacquered with a shade of bright crimson.
The ironwood caddy's trap is a trivially constructed gadget which you can take down any time. (3/17)
Roundtime: 2 sec.
>
[pick]>disarm my ironwood caddy quick
You quickly work at disarming the caddy.
Thanks to an instinct provided by your sense of security, you barely avoid detonating the trap due to your fumbling efforts.  You doubt you'll be this lucky every time.
Roundtime: 2 sec.
>
[pick]>pick my ironwood caddy ident
The lock is a trivially constructed piece of junk barely worth your time. (3/17)
However, a cracked ironwood caddy is not fully disarmed, making any chance of picking it unlikely.
Roundtime: 2 sec.
>
[pick]>pick my ironwood caddy quick
You realize very quickly that this was a very bad idea...

**Comment by KatoakDR** [comment]
Taking a look, thanks for the log
