### ISSUE TITLE
FOC empath support

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#467]
FOC in combat for empath

**Comment by rcuhljr** [comment]
Heal seems like a much safer option to use in combat, FoC costs fatigue (which lowers defense) vitality (which makes hits do much more actual damage) and can possibly stun. Heal provides the same functionality without the huge costs other than needing to be cast a little more frequently.

**Comment by xtremenerdrage** [comment]
I think timers would also fix this can just add heal or foc on a timer. 
Or perhaps combat healing that calls another ;healme then goes back to combat

**Comment by Aurayn** [comment]
I also would like to be able to pop a FOC in combat.

**Comment by rcuhljr** [comment]
recast timers are now supported for spells, so this is bumped down on the priority ladder but I'll revisit it later.

**Comment by rcuhljr** [comment]
Done
