### ISSUE TITLE
Combat-Trainer and dealings with lodged crossbow bolts

### ISSUE THREAD

**Issue by Bmoney420** [rpherbig/dr-scripts#4711]
I was playing in Dragon Priest Assassins and combat trainer had an issue with bolts that were lodged in me. Here is the error messaging. I can retrieve a log if necessary. Many thanks to all the Developers!

[combat-trainer: message: That crossbow bolt needs to be tended to be removed.]
[combat-trainer: checked against [/You pick up/i, /You put your/i, /Stow what/i]]
[combat-trainer: for command stow my bolt]

**Comment by KatoakDR** [comment]
@Bmoney420 Thanks, investigating

**Comment by KatoakDR** [comment]
@Bmoney420 What were you hoping to happen in this scenario? That the script tried to tend you to remove the lodged bolt or skip picking up the bolt that may be on the ground?

If skipping picking up ammo then you may run out, but at least the script wouldn't hang and could move on to other weapons if necessary.

Do your logs show that combat-trainer eventually tended your wounds to dislodge the bolts?

**Comment by Bmoney420** [comment]
honestly, i was hoping that the script would simply stow bolts laying on the ground, ignore lodged bolts and swap to the next weapon. mostly just because i figured that would be the easiest fix.

the script never actually tended the lodged bolts, but i also didn't give it enough time to attempt to do it. as soon as i saw it was hanging up, i canceled the hunt and left the assassin area lol

**Comment by KatoakDR** [comment]
I agree the simplest approach for now is just ignore the message when ammo is lodged in you and move on with the script.

You may end up out of ammo with it all on the ground, but at least the script won't be hung up and you potentially die from inaction.
