### ISSUE TITLE
adding recipes to base-recipes

### ISSUE THREAD

**Issue by GreyhallowDR** [rpherbig/dr-scripts#4721]
I get adding 1 might be a very low priority but  the belaying pin is a fairly common item these days. I'll look out for others that would be worth adding and list them here.

- name: a metal belaying pin
  noun: pin
  volume: 8
  type: weaponsmithing
  work_order: false
  chapter: 4

**Comment by Dartellum** [comment]
I have a PR in for chapter 8 weapons. I can go through and make one for chapter 4 - complete the missing ones.

**Comment by Dartellum** [comment]
I have all weaponsmithing, armorsmithing, blacksmithing, carving, and shaping recipes in base-recipes now and confirmed. No duplicates. I have not made a PR for it yet as I am working through the other recipes in the file and adding tinkering.

**Comment by Dartellum** [comment]
I am still working through the list. See the PR4778 for what is already completed.

**Comment by MahtraDR** [comment]
This was added in https://github.com/rpherbig/dr-scripts/pull/4778 and can be closed. @rpherbig
