### ISSUE TITLE
Combat-trainer stop casting on lock option

### ISSUE THREAD

**Issue by skinnybb** [rpherbig/dr-scripts#475]
Could an option be added to combat-trainer to stop using TM spell once TM locks? Same with Debilitation spells.

**Comment by rpherbig** [comment]
Currently `combat-trainer` attempts to use whichever spell's skill has the
lowest field exp. It will use no spell if all skills are mindlocked and
your mana is under 70%.

**Comment by rcuhljr** [comment]
We can do multiple birds with one stone by making our two mana thresholds options.

**Comment by rpherbig** [comment]
@rcuhljr What "two mana threshold options"?

**Comment by rcuhljr** [comment]
Added
