### ISSUE TITLE
;outdoorsmanship not releasing symbiosis

### ISSUE THREAD

**Issue by Breubor** [rpherbig/dr-scripts#4785]
I've been getting a lot of backfires lately on an alt and I've tracked it down to ;outdoorsmanship.

During ;outdoorsmanship the script will train magics using crafting_training_spells:, and if the script ends in the middle of the prep it will release the spell prep, release harnessed mana... but not release prep symbiosis.

If your next script in ;t2 is, lets say, ;buff, where you are buffing without using symbiosis (and therefore at higher mana preps), it will consistently backfire because symbiosis is still prepped from earlier.

My band-aid fix is I added ;multi 1,rel symb at the end of my ;outdoorsmanship section, but that might be something to add to the ;outdoorsmanship script itself

**Comment by Sarvatt** [comment]
The outdoorsmanship script is called multiple times in quick succession from other scripts, it would need some kind of state tracking between scripts or else you will release twice and lose your symb completely

**Comment by Breubor** [comment]
Yes I apologize.  I just looked closer at the outdoormanship script and noticed this issue alert at the bottom (https://github.com/rpherbig/dr-scripts/issues/3141).  I'm going to close this issue out, because it is working as intended.
