### ISSUE TITLE
Dirge bank not tracked by ;banks in drinfomon

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#483]
who the hell has a bank account in dirge? anyway... if the goal is to replace bank books, lets add this bank!

>go bank
[Dirge, Traveller's Bank - 16655]
A last glimmer of more prosperous times, the bank retains some remnants of the town's faded glory.  A marble counter for the tellers stands solidly to one side, though now there is but one clerk left.  Several large windows have been hastily boarded up and reinforced with stout bars.  A few other patrons lounge about waiting for the teller.  One or two of them look you over casually but with a wariness in their cold eyes.  You also see the exchange rate board and a faded wooden sign.
Obvious exits: out.
>depo all
The clerk slides a small metal box across the counter into which you drop all your Kronars.  She counts them carefully and records the deposit in her ledger.
>
[drinfomon]>balance
The clerk pages through her ledger.  "Bellman-Ford, Dijkstra," she says to herself.  "Here we are.  Your current balance is 6 gold, 1 bronze, and 5 copper Kronars."
>;banks

                  Crossings:      143,140 or 14 platinum, 3 gold, 1 silver, 4 bronze
                Leth Deriel:        8,336 or 8 gold, 3 silver, 3 bronze, 6 copper
                      ------------------------------------------------------------------------------------------
                     Kronar Total:      151,476 or 15 platinum, 1 gold, 4 silver, 7 bronze, 6 copper
                     Lirum Total:            0 or 
                     Dokora Total:            0 or

**Comment by rpherbig** [comment]
Love the character name, by the way :)

**Comment by rpherbig** [comment]
@jandersson I *think* I fixed this, but I can't get to Dirge. Can you try this again?

**Comment by rpherbig** [comment]
Closing after in-game confirmation

**Comment by jandersson** [comment]
yea that was me :+1: 
thanks!
