### ISSUE TITLE
enchant - Imbue charges/harnesses twice the expected amount

### ISSUE THREAD

**Issue by ubiquitous42** [rpherbig/dr-scripts#4843]
With the following setup, `enchant` preps at 15, charges with 45, then harnesses 45:
```  imbue: &imbue
    Imbue:
      mana: 15
      cambrinth:
      - 45
```
 I believe this may be due to find_charge_invoke_stow being called inside of crafting_cast_spell, so it's overall called twice.

**Comment by KatoakDR** [comment]
@ubiquitous42 I think you've found a bug 🐞 

In `enchant.lic`, if you remove line 127 where it calls `find_charge_invoke_stow` does that resolve your problem?

**Comment by ubiquitous42** [comment]
Yep, without that line it only does it once.
