### ISSUE TITLE
More stealing tweaks

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#486]
Add a keep_stealing flag to not stop on mindlock and do a full run for recording purposes.

Change grab selection to Hi/Low acceptable range split.

Add in rough estimate data for problem items or find a better way to not jump too far above an acceptable range item.
` id=13 wreath, id=14 potion, and id=40 lockpick ring. `

**Comment by rcuhljr** [comment]
In place, needs tested more.

**Comment by rpherbig** [comment]
@rcuhljr What's the status of this?
