### ISSUE TITLE
[script] [combat-trainer] Does not recover weapon that's dropped due to loss of arm/hand

### ISSUE THREAD

**Issue by KatoakDR** [rpherbig/dr-scripts#4864]
### Background
* Reported by [oflimiteduse](https://discord.com/channels/745675889622384681/745675890242879671/828608083701137439) in the Lich discord
* Character is not picking back up their weapon after dropping it due to losing a arm/hand due to sorcerous backlash.
* In this case, the character is an empath who stays in combat because can self-heal but combat-trainer continues to try to attack (e.g., feint, feint, feint) but repeatedly gets the error "Wouldn't it be better if you used a melee weapon?"

### Expected Result
* combat-trainer picks up and/or stows the item that fell to the ground
* If weapon cannot be found then alert user and switch to next weapon

### Actual Result
* Combat log, https://pastebin.com/KVbatSU6

### Solution Ideas
* Weapon/shield recovery logic exists in combat-trainer for critters that steal items from the character. That code might be able to be reused or at least inspire a solution here.

**Comment by wstampley** [comment]
I'm really curious why the logic in combat trainer isn't stashing the weapon for sorcery automatically. It looks coded to do it.
```
  def spell_is_sorcery?(spell_data)
    return true  if spell_data['sorcery']
    return false unless spell_data['mana_type']
    return false if DRStats.native_mana.casecmp(spell_data['mana_type']).zero?
    return false if spell_data['mana_type'].casecmp('ap').zero?
    true
  end
  
  ....... <all the other stuff>
  
    if game_state.casting_sorcery
      @equipment_manager.stow_weapon(game_state.weapon_name)
    end
  
  .... <cast>
  
    if game_state.casting_sorcery
      game_state.casting_sorcery = false
      @equipment_manager.wield_weapon(game_state.weapon_name, game_state.weapon_skill)
    end
```
