### ISSUE TITLE
[script] [combat-trainer] Not hiding before attempting to backstab

### ISSUE THREAD

**Issue by KatoakDR** [rpherbig/dr-scripts#4865]
### Background
* Reported by [Skinz](https://discord.com/channels/745675889622384681/745676367663988948/828762002586337320) in the Lich discord
* Player is using StormFront with Lich
* Character is attempting to backstab when they are not hidden and getting error "You must be hidden to blindside."

### Expected Result
* combat-trainer hides before attempting to backstab
* combat-trainer re-attempts one time to hide when encounter "You must be hidden to blindside." before moving on

### Actual Result
* combat-trainer repeatedly tries and fails to backstab, never trying to hide

```
>
[combat-trainer]>backstab
>
You must be hidden to blindside.
>
[combat-trainer]>backstab
You must be hidden to blindside.
```

### Solution Ideas
* When attack and fail due to "You must be hidden" then retry one time to hide and attack. If fail the second attempt then move on to next action.

**Comment by rcuhljr** [comment]
It's probably useful to get the users yaml for situations like this where they've misconfigured something, this seems very likely to be them setting an attack override to backstab instead of use_stealth_attacks.
