### ISSUE TITLE
Bescort ways - A rare message can stall ;bescort when attempting to leave the first room upon entering the Ways

### ISSUE THREAD

**Issue by Nyctus** [rpherbig/dr-scripts#4867]
Repro:

1. Use ;bescort to enter the Ways toward any valid destination
2. Observe the script as it exits the first room after being pulled through the unstable moongate

Results:
Very occasionally a failed skill check results in the message "You end up walking in circles" and bescort will stall.

Expected:
When "You end up walking in circles" appears upon leaving the first room of the Ways, bescort will re-attempt the first 'pow'/move.

Example when entering via Taniendar and attempting to move toward the Microcosm:
`[bescort]>northeast
You move across the unreal landscape, navigating by the streams of Lunar energy.
You end up walking in circles.`

Related lines 1497 to 1500 of bescort:
`direction_to_pattern = {
      'center' => /the microcosm is to the (?<direction>.*)\.$/,
      'exit' => /You believe the end of the conduit lies (?<direction>.*)\.$|^You are already at the end of the conduit\.$/
    }`

**Comment by KatoakDR** [comment]
Add link to discord conversation, https://discord.com/channels/745675889622384681/745676101392793651/828436928629047296
