### ISSUE TITLE
[script] [combat-trainer] Sometimes misidentifies what ammo was shot and fails to pick it up

### ISSUE THREAD

**Issue by KatoakDR** [rpherbig/dr-scripts#4877]
### Background
* We had to revert https://github.com/rpherbig/dr-scripts/pull/4870 which resolved https://github.com/rpherbig/dr-scripts/issues/4868, so opening issue again. Try try try again 😬 
* Reported by [MulletByNature](https://discord.com/channels/745675889622384681/745678330933805157/829184672805290034) in the Lich discord

```
[combat-trainer]>shoot
< Moving with amazing force and guile, you fire a Sunderstone shard at a storm bull.  A storm bull attempts to dodge, taking the full blow.  The shard lands a spine-rattling strike that rips the right arm clean off at the shoulder.
The Sunderstone shard falls to the ground!
A storm bull expires with a bellow and a crackle of electricity.
The shimmering ethereal shield fades from around a storm bull.
[You're nimbly balanced]
[Roundtime 1 sec.]
>
[combat-trainer]>stow my spine
```

### Expected Result
* combat-trainer pick up the Sunderstone `shard` that was shot

### Actual Result
* combat-trainer tries to pick up `spine`, which the regex matched from `spine-rattling strike`

![image](https://user-images.githubusercontent.com/68095633/113811444-d654b780-9731-11eb-8b1b-4339c5d098e5.png)

![image](https://user-images.githubusercontent.com/68095633/114126800-bef70500-98be-11eb-9da6-be0fb6995a83.png)

### Implementation Notes
* Any changes to the shoot / ammo regex logic must be thoroughly tested, then tested again, then, reconsider what you're doing, test some more, maybe.. just maybe.. we might implement a change :)

**Comment by wstampley** [comment]
Does adding a whitespace after the ammo matcher fix this for most cases?

```
you (fire|poach|snipe) an? (?:.*\s)?(arrows?|bolt|shard|rock|sphere|clump|coral|fist|holder|lump|patella|pellet|pulzone|quadrello|quarrel|quill|stone|stopper|verretto|blowgun dart|crumb|spine|mantrap spike|tiny dragon|icicle|fang|scale|grey-black spike|bacon strip|page|naga|thorn|fragment) .* at
```

That causes it to ignore 'spine-rattling'. not sure about any other complications, but most ammo nouns should be followed by a space in normal usage.

**Comment by rcuhljr** [comment]
You could also just exclude periods from the allowed characters in the `(?:.*\s)?` using negation, `[^\.]*` or something similar. A similar approach would be to split the message on period before doing the regex match and only matching against the first sentence in the result.

**Comment by wstampley** [comment]
I really like the negation idea to get it to stop the greedy grab in the first sentence. Totally escaped me as I was poking at it earlier. 

It also seems like we really need a unit test style framework in place for these super sensitive regexs with a collection of the 'weird' cases people know about. Not sure if lich unit testing is a thing I don't know about, or if it's been tried before, etc.

**Comment by rcuhljr** [comment]
We have some [tests in place](https://github.com/rpherbig/dr-scripts/tree/master/test) but there's a lot of room for improvement. You've got two reasonable approaches that aren't massive undertakings.

1. Extract regexes to a common or data file, have scripts pull them from there and write unit tests around known problematic strings for each regex.
2. Move class AttackProcess to it's own script file, test it via loading the script and dummying out the path to reach the regex in question. Fair amount of effort here.

**Comment by KatoakDR** [comment]
Thanks for the link to the tests -- I'll definitely use those to help validate the regex changes since they're critical.

I've been tinkering with the regular expression at https://regex101.com/r/lByakC/1/

**Comment by rcuhljr** [comment]
`Driving in with exacting precision, you fire a bacon strip at a ship's rat.  A ship's rat attempts to dodge, leaning wrong and blundering into the blow.` Glad to see the game is keeping it serious :P

**Comment by wstampley** [comment]
> We have some [tests in place](https://github.com/rpherbig/dr-scripts/tree/master/test) but there's a lot of room for improvement. You've got two reasonable approaches that aren't massive undertakings.
> 
> 1. Extract regexes to a common or data file, have scripts pull them from there and write unit tests around known problematic strings for each regex.
> 2. Move class AttackProcess to it's own script file, test it via loading the script and dummying out the path to reach the regex in question. Fair amount of effort here.

Uh oh @KatoakDR - https://github.com/rpherbig/dr-scripts/blob/master/test/test_check_health.rb!
