### ISSUE TITLE
Researching causes combat-trainer to hang when casting buffs

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#490]
```
[combat-trainer]>pre moonblade 16

Are you sure you want to do that?  You'll interrupt your research!
[Enter your command again if you want to.]
You continue to study Augmentation magic.

[combat-trainer: *** No match was found after 15 seconds, dumping info]

[combat-trainer: messages seen length: 5]

[combat-trainer: message: Are you sure you want to do that?  You'll interrupt your research!]

[combat-trainer: message: [Enter your command again if you want to.]]

[combat-trainer: message: Gauge Flow  (54 roisaen)]

[combat-trainer: message: You continue to study Augmentation magic.]

[combat-trainer: message: Gauge Flow  (53 roisaen)]

[combat-trainer: checked against [/Your eyes darken to black as a starless/i, /Icy blue frost crackles up your arms/i, /Tiny tendrils of lightning jolt between your/i, /Turning your focus solemnly inward/i, /You begin chanting a psalm/i, /With (calm|meditative|rigid|tense) movements you/i, /You raise your head skyward/i, /With (tense|calm) movements/i, /You trace (an|a) (.*) sigil in the air/i, /Slow, rich tones form/i, /You begin chanting( a)? (catechisms|mantra|prayer|psalm)/i, /You raise (your|an) (arm|arms|head|palms) skyward/i, /With a sharp cut to your voice/i, /With a resounding "POP"/i, /Your skin briefly withers and tightens, becoming gaunt as the energies of/i, /The first gentle notes of Blessing of the Fae/i, /You begin to hum the/i, /The wailing of lost souls accompanies your preparation/i, /You briskly utter a few sharp words/i, /You are already preparing/i]]

[combat-trainer]>charge my cambrinth armband 10

Distracted by your devices, you forget what you were researching.
You harness a small amount of energy and attempt to channel it into your cambrinth armband.
You are able to channel all the energy into the armband.
The cambrinth armband absorbs all of the energy.
Roundtime: 3 sec.
```

**Comment by rpherbig** [comment]
Were you using training-manager? If so, it should always wait for research
to finish before going out hunting.

Or were you researching and then ran combat-trainer manually?

**Comment by jandersson** [comment]
I was running training manager

**Comment by jandersson** [comment]
You stroll north.
[Northeast Wilds, Grimsage Way - 984]
An enormous tower of grey marble rises imposingly from the ground, its stones fitted so closely that it appears to be one seamless spear of earth.  The top of the tower gleams brightly, the light reflecting from the panes of a skylight set into the roof.  A set of gleaming ebonwood doors inlaid with gold lead into the tower.  You also see a pile of rocks, a pile of grass, a steel pin, a capillary tube and a firewood bin.
Also here: Mistrya, Eracer, Hunter Jezzail who is shrouded in ghostly flames and Stellarest who is surrounded by a shimmering shield.
Obvious paths: south.

[go2: travel time: 0:00:19]

--- Lich: go2 has exited.

[crossing-training: ***Attempting to train Perception***]

[crossing-training]>collect rock

You move slightly to the left, hoping to find a better foraging spot.
You manage to collect a pile of rocks.
Roundtime: 15 sec.
You make definite progress in your project about Augmentation Patterns Research and decide to take a break.  However, there is still more to learn before you arrive at a breakthrough.

[crossing-training]>kick rocks

Jezzail begins a quiet rumba on his copper zills with only the slightest hint of difficulty.
You take a step back and run up to the pile of rocks.  Bringing your foot smashing down onto the pile, you send bits and pieces of debris scattering in every direction.  Looking around for the now defunct mountain of glory, you fail to find any signs of its presence.

[crossing-training]>research AUGMENTATION 300

You realize that your project about Augmentation Patterns Research only requires 241 more seconds of research, so you adjust your plans accordingly.
You confidently begin to bend the mana streams around and through you, testing the limits of your ability to weave augmentation spells into the flesh.

[crossing-training: ***Attempting to train Perception***]

[crossing-training]>collect rock

You manage to collect a pile of rocks.
Roundtime: 15 sec.
Eracer continues to play a quiet ballad on his copper zills, pausing only a little through a difficult section.

[crossing-training]>kick rocks

You take a step back and run up to the pile of rocks.  Bringing your foot smashing down onto the pile, you send bits and pieces of debris scattering in every direction.  Looking around for the now defunct mountain of glory, you fail to find any signs of its presence.

[crossing-training]>assess teach

You assess the teaching environment...

No one seems to be teaching.
Roundtime:  5 seconds.

[crossing-training: ***Attempting to train Perception***]

[crossing-training]>collect rock

You manage to collect a pile of rocks.
Roundtime: 15 sec.
You continue to study Augmentation magic.
Mistrya goes south.
Jezzail stumbles only slightly as he continues to play a rumba on his copper zills.
Noting that your research is progressing nicely, you continue to focus on it.
Jezzail stops playing his song.
Jezzail begins a quiet rumba on his copper zills with only the slightest hint of difficulty.
Jezzail gets a simple black compendium from inside his canvas pack.

[crossing-training]>kick rocks

You take a step back and run up to the pile of rocks.  Bringing your foot smashing down onto the pile, you send bits and pieces of debris scattering in every direction.  Looking around for the now defunct mountain of glory, you fail to find any signs of its presence.

--- Lich: crossing-training has exited.

--- Lich: hunting-buddy active.

--- Lich: go2 active.

[go2: ETA: 0:00:15 (77 rooms to move through)]

[go2]>south

**Comment by jandersson** [comment]
Seems like strange behaviour, maybe its a one-off. I'll see if it still does it after some time

**Comment by rcuhljr** [comment]
No, it totally looks like research doesn't stop crossing training from ending. I'll fix this.

**Comment by rpherbig** [comment]
f142966e143d4781e0f588bb7b66ef8572a43d21
