### ISSUE TITLE
Request Combat-trainer KEEPSAKE box compatability

### ISSUE THREAD

**Issue by Ghostthief** [rpherbig/dr-scripts#4924]
Keepsake/jewelery boxes seem to be usable at melee so a quick single use on a timer of less than 120 seconds should exibit some alternative to the OLD pets boxes

**Comment by KatoakDR** [comment]
Link to discord conversation, https://discord.com/channels/745675889622384681/745675890242879671/836443866814742539

**Comment by MahtraDR** [comment]
@Kiriawen Do you have a sample of what the actions are here? I can add, or we can close. Show me a log with a full cycle of a keepsake box and I'll add it.
