### ISSUE TITLE
Choose which spells to use in combat

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#493]
Request to be able to choose which spells are cast in combat offensively. 

Spells to rotate through an assigned cycle, SPELL 1, SPELL 2, SPELL 3 independent of current learning rate or skill level. 

So we can customize our battles

**Comment by rcuhljr** [comment]
`offensive_spell_cycle:` will accept a list of offensive spell names and try to cast them in that order. If you have expire messages on those spells it will still respect them and skip the spell.
