### ISSUE TITLE
Make harmless the default state for debilitation spells

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#494]
treat all debil spells as harmless for now, leave flag in for TM.

**Comment by rpherbig** [comment]
Could you elaborate on the reason for changing this?

**Comment by rcuhljr** [comment]
No debilitation spells that I can think of cause harm? why should every one need the flag set?

**Comment by rpherbig** [comment]
Is 'harmless' still useful for any non-Debilitation spells?

**Comment by rcuhljr** [comment]
Paralysis for TM.

**Comment by skyleronken** [comment]
Wouldn't this just be a change to base-spells.yaml? any programmatic setting of this would likely override user defined settings.

Or, would we rather assume all spells are harmless except for TM spells unless explicitly defined?

**Comment by rpherbig** [comment]
This has been mostly overtaken by the recent change to base spells. We
could add harmless: true or false to each spell in there.
