### ISSUE TITLE
bescort ice-skate error handling

### ISSUE THREAD

**Issue by wstampley** [rpherbig/dr-scripts#4948]
There are some unhandled edge cases in bescort for the ice road -

in this case, there was a YAML issue parsing the footwear property, so it didn't take my boots off, got an error message trying to put the skates on, and then never noticed the failure messages / falling over to switch to slow mode.

At least catching that you can't put on the skates seems like it would be an easy fix.

--- Lich: bescort active.
[bescort]>tap my skates
You tap a pair of white ice skates with fine brass buckles inside your traveler's pack.
>
[dependency: *** ERROR PARSING YAML FILE ***]
[dependency: (./scripts/profiles/Corgar-setup.yaml): did not find expected key while parsing a block mapping at line 825 column 3]
>
[dependency: *** ERROR PARSING YAML FILE ***]
[dependency: (./scripts/profiles/Corgar-setup.yaml): did not find expected key while parsing a block mapping at line 825 column 3]
[bescort]>get skates
You get a pair of white ice skates with fine brass buckles from inside your traveler's pack.
>
[bescort]>wear skates
>
You can't wear any more items like that.
>
[bescort]>se
You run southeast.
[Himineldar Shel, Mountain Road]
As night descends upon this mountainous region, falling temperatures increase the wind's bitter fury.  Blinding clouds of snow race across the slopes, disappearing into the darkness of the night.  The awesome power of nature unleashed against the mountain's solid stone is spellbinding.  Shadowy peaks, barely visible in the dark, are a reminder of the endless procession of mountains.
Obvious paths: east, northwest.
Roundtime: 2 seconds.
Room Number: 4367
>
[bescort]>e
...wait 1 seconds.
>
[bescort]>e
You had better slow down! The ice is far too treacherous for you to move as quickly as you are.
You go east.
[Himineldar Shel, Mountain Road]
Creeping across the mountains, the deepening shadows slowly engulf the trail in darkness.  Fractured rocks, the shattered bones of the mountain, tell the tale of a recent slide and lie scattered about the path.  Howling winds, strengthened by nightfall and plunging temperatures, rush down from the highest peaks with a banshee-like shrieking.  Along the horizon rise the shadowy images of majestic snowcapped mountains, standing in silent judgment in the darkness.
Obvious paths: east, west.
Roundtime: 2 seconds.
Room Number: 4419
>
[bescort]>e
>
Your excessive speed causes you to lose your footing.
 
Falling down you slide east.
[Himineldar Shel, Mountain Road]
Plunged into darkness and assaulted by brutal winds, the narrow trail slowly wends it way through the pass.  Sheer rock walls, rising to either side of the path, do nothing but increase the fury of nature.  The raging winds frequently dislodge large boulders from the cliffs above.  In the darkness, these missiles, with little warning, shatter violently on impact with the bottom of the pass and shower the trail and snow drifts with debris.
Obvious paths: northeast, west.
Some ice has hurt your right leg in the fall.
Room Number: 4420
>
[bescort]>ne
You can't do that while lying down.
>
[bescort]>stand
Your wounds are making standing more difficult.
You stand back up.

**Comment by Kaesken** [comment]
Do you have "footwear:" set?

**Comment by Hiinky** [comment]
Long as you do the fix within bescort and not on the mapdb, should be. No touching the map!

**Comment by wstampley** [comment]
I did have footwear: in my YAML, but I had a typo elsewhere that prevented the settings from loading correctly. That's why I was thinking bescort could at least recognize the failure to put skates on and act accordingly.

**Comment by Kaesken** [comment]
Yeah, would be nice for an error to trigger at "You can't wear any more items like that." to state that the skates were unable to be worn then go to collecting rocks while walking the mountain instead of running it as if you had skates on.
While talking about bescort, would also be a nice suggestion to give for when a person starts go2 in the middle of the ice path that it checks whether or not you're wearing skates and continue instead of just assuming you're not wearing skates and collects rocks as it finishes out the path.
