### ISSUE TITLE
Deprecated ostruct method in use in dependency.lic

### ISSUE THREAD

**Issue by vtcifer** [rpherbig/dr-scripts#4958]
As of 2.4.0 (ruby/ruby@7c89ca5) an internal OpenStruct method (`modifiable`) made private, but that commit also aliased the old method the new public method. 
Those aliases were removed in 2.7.0 (ruby/ruby@dbcc224)

This breaks this line of code:
https://github.com/rpherbig/dr-scripts/blob/56d3afd732fa8390057f14e4054a370b8adf30bc/dependency.lic#L140

Most people should be on a higher version than 2.3.0 (2.5.5 is current version with the all-in-one), but we should update to be within spec / future compatibility. 

This fixes in my test, and works on both 2.5.5, and 2.7.3 
```diff
+140      if !respond_to?(:modifiable?, true) # for backwards compatibility <2.3
-140      modifiable[new_ostruct_member(mname)] = args[0]
+141        modifiable[new_ostruct_member(mname)] = args[0]
+142      else                                # new >=2.3 method
+143        modifiable?[new_ostruct_member(mname)] = args[0]
+144      end
```

I have no pre-2.3 version to test, and no environment to commit for the PR at this time.

**Comment by rcuhljr** [comment]
Seems like a reasonable fix, surprised this risk never manifested sooner with us doing hackery like reworking ostruct. If we don't find a tester in a few days running a ruby version that old I'm of the inclination to ship it and wait to hear if problems arise.

**Comment by rcuhljr** [comment]
Alternate fix, are people even using this functionality any more? I think this may have just been me being too clever and maybe it should be up to scripts consuming the settings to use something more idiomatic like `settings.money_on_hand || 100`. You'd lose the warning unless you added it manually, but we could also just monkey patch in a clean method to ostruct `def fetch(setting, default)` that contains this behavior.

**Comment by vtcifer** [comment]
> Alternate fix, are people even using this functionality any more? I think this may have just been me being too clever and maybe it should be up to scripts consuming the settings to use something more idiomatic like `settings.money_on_hand || 100`. You'd lose the warning unless you added it manually, but we could also just monkey patch in a clean method to ostruct `def fetch(setting, default)` that contains this behavior.

It impacts flex_args, which is used a lot in combat-trainer / hunting-buddy.  I really  don't have enough ruby knowledge to know what all the downstream impact of reworking that code to get rid of ostruct.

**Comment by rcuhljr** [comment]
Sorry, not removing ostruct, just removing our custom override here that allows you attempt to retrieve a field from ostruct while providing it a default value to fallback on if it doesn't exist. This override of member_missing is all in support of 

```
 elsif len == 1
      echo("Failed to find yaml setting #{mid}, using default:#{args[0]}")
      args[0]
```
Where we allow you to call `settings.some_value(a_default_to_return_if_not_found)`

**Comment by vtcifer** [comment]
Yeah, way beyond my ruby knowledge/expertise, I'd really defer to someone with more experience.
