### ISSUE TITLE
Non stow behavior for listed gems

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#496]
Give people a way to flag gems to not get stowed into a gem pouch by combat trainer, things like kyanite stones, pearls, etc. etc.

**Comment by rpherbig** [comment]
Is this a user need or just documenting an idea?

**Comment by rcuhljr** [comment]
I'd like to be able to collect enchanting usable gems for my moon mage.

**Comment by rcuhljr** [comment]
In place.
