### ISSUE TITLE
Adding Juggernauts to base-hunting

### ISSUE THREAD

**Issue by MrQuosig** [rpherbig/dr-scripts#4985]
Add these to the shard part of base-hunting. They map fine, only have 4 rooms and might blow you up, but hey maybe they are interesting.

#https://elanthipedia.play.net/Dragon_Priest_juggernaut 
# CAUTION: Must periodically disarm orb or the special attack kills you. Add disarm orb: 60 (or less) to buff_nonspells:
juggernauts:
 - 4548
 - 4552
 - 4551
 - 4550

**Comment by MahtraDR** [comment]
Is this still valid? I can add them in if so.

**Comment by rpherbig** [comment]
@MrQuosig

**Comment by MahtraDR** [comment]
@rpherbig Close? or wait another week? Not quite as old as the other request for a zone, but nobody else has asked either, and @MrQuosig hasn't responded... I figure it doesn't make sense to add yet another zone for us to maintain. As in the other instance, I would be happy to add for an active request, note.

**Comment by MrQuosig** [comment]
Request still active, I just lost track of it after the 6th month wait.
