### ISSUE TITLE
Cage of Light in Combat

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#499]
Request to have Cage of Light available when in combat. Special CAST. Must CAST MOON to activate spell.

**Comment by rpherbig** [comment]
There is a custom cast option. Take a look at how Torgro does Ethereal
Fissure and see if that works.

**Comment by rcuhljr** [comment]
Cage of light already works, see [here](https://github.com/rpherbig/dr-scripts/blob/master/profiles/Mooselurk-setup.yaml#L162-L170)
