### ISSUE TITLE
Add sniping

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#5]
https://elanthipedia.play.net/mediawiki/index.php/Snipe

This ability is restricted to Survival-prime guilds (Ranger, Thief and Necromancer) of at least 40th circle.

**Comment by rpherbig** [comment]
@rcuhljr How useful is this?

**Comment by ericmeek** [comment]
Could a setting be created where we could choose to use either poach or snipe as stealth ranged attack? Currently I manually change poach to snipe in combat-trainer.

**Comment by rcuhljr** [comment]
Yeah it's been kind of a low priority for me because there where a lot of claims going around that poach boosted OF more than snipe and I don't use snipe personally since I need the defense training for not being hidden. I can add it back on the radar.
