### ISSUE TITLE
Train should get money and check tdps first

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#50]
use `tdp` and `tdp project` to determine if you can even train, if so get enough money. (one training is 6 copper per starting stat. 21->22 = 126 copper.)

**Comment by rpherbig** [comment]
Interesting, I didn't know about that command and the cost calculation. Thanks!

Do you think training should be all-or-nothing? That is, if the script calculates it can't train everything, should it abort or train as much as it can?

**Comment by rcuhljr** [comment]
No preference really.

**Comment by rpherbig** [comment]
I think I'll go with all-or-nothing. That will make calculations easier as well as sidestepping things like "does the order of arguments matter?" (and therefore minimize travel).
