### ISSUE TITLE
safe-room does not release rf before lying down to heal

### ISSUE THREAD

**Issue by Donntae** [rpherbig/dr-scripts#5012]
In some instances, safe-room does not release refractive field before lying down for the autoempath.

Log: [https://pastebin.com/F9fA41PG](https://pastebin.com/F9fA41PG)

**Comment by KatoakDR** [comment]
Thanks for the log.

Do you know if you had `spellmonitor` script running at the time? The `safe-room` script only releases invisibility spells that it detects that are active, and we rely on `spellmonitor` for that info. Based on what I saw in the code and your log, my guess is that maybe `spellmonitor` wasn't running?

For good measure, you might try adding it as an autostart: `;e autostart('spellmonitor')` to ensure it's always running.

**Comment by asechrest** [comment]
@rpherbig Suggest closing. No response from OP, no further issues, and @KatoakDR 's hunch looks to be the most likely scenario. 

Also verified RF [has the invisibility property defined](https://github.com/rpherbig/dr-scripts/blob/58fd89eddba32da3a4a4b79bb1b02139f46eec8f/data/base-spells.yaml#L2287).
