### ISSUE TITLE
War Stomp addition to training-manager

### ISSUE THREAD

**Issue by RyanEOD** [rpherbig/dr-scripts#5032]
Now that War Stomp is available to all 100+ Barbs, any thoughts to allowing it to be used in training manager via a yaml setting possibly? I search around and I don't see if it is already useable, or any settings that apply, so I'm sorry if it is already available. 

Thank you!

- https://elanthipedia.play.net/War_stomp

**Comment by KatoakDR** [comment]
In your `buff_nonspells` you can periodically perform any action you'd like. If, for example, to perform stomp is `stomp` command, then you could have:

```yaml
buff_nonspells:
  stomp: 180 # war stomp every 180 seconds
```

**Comment by MahtraDR** [comment]
@rpherbig We can close this. Katoak's answer above is very good.
