### ISSUE TITLE
Equipmanager does not use proper item verb

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#505]
In-game log: http://pastebin.com/d0kFnweU

Character YAML: http://pastebin.com/CENRPgZE

Note that the battle crossbow is tied in the YAML. However, combat-trainer calls `wear_equipment_set?` which calls `wear_item?`, which attempts to `get my #{item.short_name}` rather than remove if it is tied.

**Comment by rcuhljr** [comment]
The real problem is the crossbow is listed in the gearset when it doesn't show up in inventory combat I believe.

**Comment by rpherbig** [comment]
Good catch
