### ISSUE TITLE
Soul Attrition breaks Lich

### ISSUE THREAD

**Issue by KillashandreaDR** [rpherbig/dr-scripts#5061]
Casting of Soul Attrition by any means (via a script, or just simply manually) seems to break Lich from being able to see ANY game inputs whatsoever.

I have seen this behavior happen on ANY script the moment I cast the spell.  Almanac, Pick, Sanowret, go2, listen, jail-buddy, even some custom/personal ones I created myself.  I first noticed it obviously in combat, but I did testing outside of combat on several of the other "non-combat" scripts.  The result is all the same.  I don't know when this behavior started, as I only recently added SA to my hunting routine.  It could be a recent change to something, or it could have been a change a long time ago.

Example: I cast Soul Attrition and wait for Almanac to trigger.  Almanac will trigger after the standard pause between studying, and will get the almanac out of my backpack.  But then it freezes, because it couldn't "read" the game to determine that I successfully got the almanac.  Then after the 30 seconds or whatever, the BPUT times out and dumps the error.  It then moves on to studying the almanac, and again doesn't register that it was successful, and again BPUT times out, and moves on to the stowing of the almanac, and again have to wait for BPUT to time out yet again.

It appears Lich is not able to see RTs or CastRTs either.  If a script has waitrt or waitcastrt (without the "?"), then that script will just freeze forever.  Basically, any input given by the game to Lich seems to not get registered by Lich "indefinitely".  Also, if a script (some of my personal older ones use this that I haven't updated in a while) use an fput/waitfor type combination instead of bput, then those scripts too will get stuck forever.

The only way to "fix" the behavior is to quit the game and re-login.

**Comment by rpherbig** [comment]
@KatoakDR @vtcifer @Dartellum would one of you have a minute to look into this?

**Comment by vtcifer** [comment]
If I had to guess with no logs, most likely cause is FUBAR combat window XML, and something that GMs would probably need to fix.  I'm not sure logxml would even help here if it's a problem caused in core lich.  Possibly would need a raw packet capture to diagnose.

**Comment by KatoakDR** [comment]
I don’t have a Cleric to test with. @wstampley may be able to help test, too. 

@KillashandreaDR Would you please run the `echo` script then cast Soul Attrition spell to reproduce the issue? The `echo` script will create a file in your Lich folder named `echo_log_room.txt`. Please attach that file in a follow up comment here. 

To VTCifer’s point, if core Lich is borking then the log capture may not show us anything meaningful. But it’s an easy test to try and give us some extra info. 

Thanks

**Comment by Dartellum** [comment]
This goes back to the combat window implementation. I game the spell and it is working for me. 

<details>
<summary>:floppy_disk: Log of successful Soul Attrition</summary>
```
>pre sa
Since you're not feeding enough power into the spell pattern to make it coherent, you quickly work your way to the minimum required.
You begin chanting catechisms to invoke the Soul Attrition spell.
The guard searches the area with a wary eye.
You feel fully prepared to cast your spell.
>per
You reach out with your senses and see lambent streams of golden Holy mana radiating through the area.
Letting your senses extend further, you feel there is flickering mana to the south.
You sense your Osrel Meraud spell linking you to a brilliant orb of rippling cerulean light, which should last until you release it.
You sense the Centering spell upon you, which will last for about nineteen roisaen.
You sense the Protection from Evil spell upon you, which will last for about four roisaen.
You sense the Murrula's Flames spell upon you, which is linked to your Osrel Meraud orb.
You sense the Major Physical Protection spell upon you, which is linked to your Osrel Meraud orb.
You sense the Bless spell upon you, which is linked to your Osrel Meraud orb.
You sense the Shield of Light spell upon you, which is linked to your Osrel Meraud orb.
You sense the Persistence of Mana spell upon you, which is linked to your Osrel Meraud orb.
You have fully prepared the Soul Attrition spell at six mana.
Roundtime: 3 sec.
>hunt
You take note of all the tracks in the area, so that you can hunt anything nearby down.
You were unable to locate any followable tracks.
Roundtime: 8 sec.
A rat just arrived!
The ship's rat begins to advance on you!
The ship's rat is still a distance away from you and is closing steadily.
>cast rat
You gesture at a ship's rat.
You sense the arrival of a dark presence.
Roundtime: 2 sec.
Your spirit lashes out at a ship's rat!
The essence shatters through the ship's rat's aura, tearing mercilessly at its spirit as it crumples under the force of your onslaught.
You are barely harmed by the clash.
A ship's rat grows deathly pale!
The ship's rat falls to the ground and lies still.
You feel fully rested.
You feel fully attuned to the mana streams again.
Water drips steadily from your copper zills.
>;l
--- Lich: dependency, narost-glass, failsafe, drinfomon, spellmonitor, sanowret-crystal, smartlisten, afk, jail-buddy, events, convomon, roomnumbers, textsubs, rshell, status-monitor, loot-logger, buff-watcher, footwatch, tarantula
Your body is still soaked.
You feel fully attuned to the mana streams again.
>per
You reach out with your senses and see luminous streams of golden Holy mana radiating through the area.
Letting your senses extend further, you feel there is luminous mana to the southwest, radiant mana to the southeast, and radiant mana to the north.
You sense your Osrel Meraud spell linking you to a brilliant orb of rippling cerulean light, which should last until you release it.
You sense the Centering spell upon you, which will last for about nineteen roisaen.
You sense the Protection from Evil spell upon you, which will last for about three roisaen.
You sense the Murrula's Flames spell upon you, which is linked to your Osrel Meraud orb.
You sense the Major Physical Protection spell upon you, which is linked to your Osrel Meraud orb.
You sense the Bless spell upon you, which is linked to your Osrel Meraud orb.
You sense the Shield of Light spell upon you, which is linked to your Osrel Meraud orb.
You sense the Persistence of Mana spell upon you, which is linked to your Osrel Meraud orb.
You sense the Soul Attrition spell upon you, which will last until you fail to provide 6 mana for it.
Roundtime: 3 sec.
You feel fully attuned to the mana streams again.
A rat just arrived!
The ship's rat begins to advance on you!
The ship's rat is still a distance away from you and is closing steadily.
>hunt
You take note of all the tracks in the area, so that you can hunt anything nearby down.
To the southeast:
  1)   a ship's rat
To the southeast, southwest:
  2)   a ship's rat
To the southeast, southwest, southeast:
  3)   a ship's rat
  4)   a ship's rat
Roundtime: 8 sec.
Your spirit lashes out at a ship's rat!
The essence collides, tearing through the ship's rat's spirit and sending it reeling in horror.
You are barely harmed by the clash.
The ship's rat is stunned!
A ship's rat decays away.
You feel fully attuned to the mana streams again.
You feel fully prepared to cast your spell.
The ship's rat begins to advance on you!
The ship's rat is still a distance away from you and is closing steadily.
The ship's rat closes to pole weapon range on you!
>cast rat
You gesture at a ship's rat.
Maintaining two cyclic spells at once is beyond your mental comprehension, and the pattern dissipates.
The ship's rat closes to melee range on you!
Your spirit lashes out at a ship's rat!
The essence shatters through the ship's rat's aura, tearing mercilessly at its spirit as it crumples under the force of your onslaught.
You are barely harmed by the clash.
A ship's rat grows deathly pale!
The ship's rat falls to the ground and lies still.
You feel fully attuned to the mana streams again.
>per
You reach out with your senses and see luminous streams of golden Holy mana radiating through the area.
Letting your senses extend further, you feel there is luminous mana to the southwest, radiant mana to the southeast, and radiant mana to the north.
You sense your Osrel Meraud spell linking you to a brilliant orb of rippling cerulean light, which should last until you release it.
You sense the Centering spell upon you, which will last for about eighteen roisaen.
You sense the Protection from Evil spell upon you, which will last for about two roisaen.
You sense the Murrula's Flames spell upon you, which is linked to your Osrel Meraud orb.
You sense the Major Physical Protection spell upon you, which is linked to your Osrel Meraud orb.
You sense the Bless spell upon you, which is linked to your Osrel Meraud orb.
You sense the Shield of Light spell upon you, which is linked to your Osrel Meraud orb.
You sense the Persistence of Mana spell upon you, which is linked to your Osrel Meraud orb.
You sense the Soul Attrition spell upon you, which will last until you fail to provide 6 mana for it.
Roundtime: 3 sec.
```
</details>

;tldr - Game window works for me. @KillashandreaDR do you know if you updated to the latest version of lich? Are you on the DR fork?

**Comment by KillashandreaDR** [comment]
Ok, I'll do the tests you mentioned and post the file here.

I haven't updated Lich in awhile, so I will try that FIRST before anything else..  I'll also try that.  And sorry, but I don't know what DR Fork is.

**Comment by KillashandreaDR** [comment]
ok, actually it appears I was up to date on Lich.

So I did the echo test.  In this one I cast SA, then started up Sanowret.  It tapped my crystal, but then determined it couldn't find it when BPUT timed out.
[echo_log_room.txt](https://github.com/rpherbig/dr-scripts/files/6762187/echo_log_room.txt)

**Comment by Dartellum** [comment]
`;e use_lich_fork` at the comand line. `;e echo LICH_VERSION` for the version of lich. You should have 4.13.4f.

**Comment by KillashandreaDR** [comment]
Ok, that appears to have fixed it.  Switching to fork, and now the scripts operate after casting SA.

Thank you all for the support.
