### ISSUE TITLE
Suggestion - Craft Script (Enchanting) - Check for ingredients before purchasing

### ISSUE THREAD

**Issue by KillashandreaDR** [rpherbig/dr-scripts#5071]
I was wondering if we could get the craft script rewritten to check for enchanting ingredients in the designated storage container before purchasing new ones.

I don't know how many times I have had to abort the craft script after it buys one or more ingredients but before it starts the enchanting process, and then I get stuck with a whole bunch of sigils stored in my backpack.  In order to clear them out, I then have to manually buy any partial missing ingredients and then manually run the enchanting script outside of craft.

So it would be good for craft to maybe tap the sigil it is about to buy first.  If it can't find it, then it purchases.  If it finds it then moves on to the next ingredient without purchasing.

**Comment by rpherbig** [comment]
@Dartellum - interested in doing this?

**Comment by Dartellum** [comment]
> @Dartellum - interested in doing this?

I can add to my list. I still need to finish the base-recipe fix and restock fix.

**Comment by Dartellum** [comment]
See PR https://github.com/rpherbig/dr-scripts/pull/5115.

**Comment by Dartellum** [comment]
@rpherbig This is resolved by the PR already merged.

**Comment by rpherbig** [comment]
Closed in #5115
