### ISSUE TITLE
Khris hanging in common-arcana

### ISSUE THREAD

**Issue by nro2** [rpherbig/dr-scripts#5072]
Been seeing this issue since 7-9.  Possibly related to #5025 

--- Lich: buff active.

[buff]>Khri Avoidance Steady Prowess Sagacity Elusion

Drawing upon the intense training of your dedicated mind, you take hold of a myriad of meditative states at once.  Each builds upon the last, augmenting your abilities to new heights.

Taking a deep breath, you focus on making your mind and body one, your mental discipline trained on quickly noticing, analyzing, and dodging approaching threats.
Willing your body to meet the heightened functionality of your mind, you feel your motions steady considerably.
Remembering the mantra of mind over matter, you let your dedicated focus seep into your muscles.  The sensation of believing that your enemies will tremble at the mere thought of you translates from your every movement.
You carefully relax your mind through your expert training, allowing you to focus on your survival even under the most dire threats.
Purging yourself of all distractions and extraneous thoughts, you allow your mind and body to become one, becoming preternaturally aware of threats around you and the best ways to defend yourself.
Roundtime: 8 sec.

R> 
--- Lich: error: wrong number of arguments (given 1, expected 0)
	common-arcana:84:in `none?'
	common-arcana:84:in `activate_khri?'

--- Lich: buff has exited.

**Comment by rpherbig** [comment]
@wstampley can you take a look at this?

**Comment by wstampley** [comment]
It's almost certainly that the version of Ruby being used is too old. There should be a warning from dependency each week to that effect.

To verify, you can run `;e echo Gem::Version.new(RUBY_VERSION)`.

If that is older than 2.5.5, instructions for updating are found here: https://discord.com/channels/745675889622384681/745683568231055471/863130628760666142

**Comment by wstampley** [comment]
The same issue was found by another player on 2.0.0 yesterday, https://discord.com/channels/745675889622384681/745678330933805157/863112796236808252

**Comment by wstampley** [comment]
More info can be found here: https://apidock.com/ruby/v2_5_5/Enumerable/none%3F

It looked like `.none?` was always available, but the specific overload that this is calling `.none?(pattern)` was added in 2.5.5.

**Comment by bastionwt** [comment]
Is there a reason a Ruby version upgrade is being forced on players? That runs counter to previous development trends on Lich.

**Comment by nro2** [comment]
;e echo Gem::Version.new(RUBY_VERSION)

--- Lich: exec1 active.

[exec1: 2.4.5]

Could very well be it.  I will update and report back.  Thanks for the replies!

**Comment by nro2** [comment]
Yeah updating ruby fixed it.  Thanks everyone!

**Comment by wstampley** [comment]
> Is there a reason a Ruby version upgrade is being forced on players? That runs counter to previous development trends on Lich.

There was a public discussion amongst the active developers in discord that there needed to be some established (and moveable) minimum version in order to make it maintainable over time. That minimum was set at the current all-in-one installer's version of 2.5.5.

Testing scripts (for issues like the one above) becomes nearly impossible if we support "all" versions of Ruby.

I don't expect that it will be a regular occurrence, but also Ruby 2.0.0 (which apparently a decent chunk of people were using) released in 2013, and EOL'd in 2016.

**Comment by vtcifer** [comment]
> > Is there a reason a Ruby version upgrade is being forced on players? That runs counter to previous development trends on Lich.
> 
> There was a public discussion amongst the active developers in discord that there needed to be some established (and moveable) minimum version in order to make it maintainable over time. That minimum was set at the current all-in-one installer's version of 2.5.5.
> 
> Testing scripts (for issues like the one above) becomes nearly impossible if we support "all" versions of Ruby.
> 
> I don't expect that it will be a regular occurrence, but also Ruby 2.0.0 (which apparently a decent chunk of people were using) released in 2013, and EOL'd in 2016.
> 
> Side note - 2.5.5 is already EOL and no longer getting security patches or performance/support updates.

The same dependency update that institutes the warning also fixes a known dr-scripts incompatibility with ruby >=2.7.  I'm tempted to update the `help_me` method to call out in a highly visible manner the lower supported version, and lower the spam threshold from 7 days to 1 day as users seem to be ignoring the warning already.

I think we probably ought to move to >=2.7.x, but I also think that until we have an all-in-one, that's not a position we could reasonably take, and it should probably handle just upgrading ruby + gems and not touching anything else. 

Additionally, AFAIK the core lich (GS) side is looking at transitioning onto Ruby 3.0, so even though we maintain our own fork, we may need to eventually go to 3.0.x as well.
