### ISSUE TITLE
dual-load should check for a dual-loadable weapon

### ISSUE THREAD

**Issue by ericmeek** [rpherbig/dr-scripts#508]
The line:

1094: if @dual_load && DRSpells.active_spells['See the Wind']

Should also check if weapon is dual loadable (it sends "load arrows" when my crossbow is out). I modified to check for my bow but a comprehensive check for all dual loadable names should be added.

**Comment by rpherbig** [comment]
Are bows the only weapon that can be dual loaded?

**Comment by ericmeek** [comment]
From what I can find, yes. The nouns should be:
bow
shortbow
longbow
