### ISSUE TITLE
Sorter Error

### ISSUE THREAD

**Issue by cfrisby77** [rpherbig/dr-scripts#5087]
I got the error below from sorter when using pick.lic. 

> >;pick
> --- Lich: pick active.
> [pick]>open my backpack
> That is already open.
> 
> [pick]>rummage /B my backpack
> 
> [pick]>inv combat
> --- Lich: error: undefined method `join' for "Crossing":String
> 	sorter:88:in `block (2 levels) in _script'
> 	sorter:84:in `each'
> --- Lich: sorter has exited.

**Comment by cfrisby77** [comment]
NM, this was on a new character with no sorter settings in the yaml

**Comment by rpherbig** [comment]
We should probably make pick/sorter handle that a little better. What settings were you missing?

**Comment by cfrisby77** [comment]
No settings for sorter were in that characters yaml. so what ever is in
base, if anything.

Sorter was is in my global autostart.
