### ISSUE TITLE
Add mark results to textsubs

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#509]
https://elanthipedia.play.net/mediawiki/index.php/Mark

**Comment by rpherbig** [comment]
c5f5de91600bd46c0849731e76b62bc8d14f6c8c

But I need someone to test since my Thief can't mark. @rcuhljr ?

**Comment by rpherbig** [comment]
@rcuhljr Is it ok to close this?

**Comment by rcuhljr** [comment]
I mean I'm not planning on testing it specifically. just close it and if users report errors we can fix them.
