### ISSUE TITLE
Add cautious mode

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#51]
Inverse of dance mode, switched to ranged weaponry and retreat when over # of enemies.

**Comment by rpherbig** [comment]
I like this idea a lot

**Comment by rcuhljr** [comment]
Mostly done in 0185f206d4009573f47d006990e3d4fffc45a861

Still need a good transition out of ranged combat, it's going to finish however many attacks or exp it had left on the ranged weapon the mode ends.

**Comment by rcuhljr** [comment]
47d565863b945d197bae2b35cd4d4a8c0b7f9b65
