### ISSUE TITLE
Errors running healme

### ISSUE THREAD

**Issue by classicfail** [rpherbig/dr-scripts#5107]
I keep getting this when I run healme.

```
--- Lich: error: undefined method `delete_suffix' for "wound":String
	healme:485:in `build_composite_key_for_wound_details'
	healme:492:in `build_composite_key_for_wound'
--- Lich: healme has exited.
```

**Comment by vtcifer** [comment]
Update your ruby version to the minimum supported version (2.5.5 at this time), as dependency should be warning you that you are on an unsupported version once a week on login.

**Comment by classicfail** [comment]
Oh.  Thank you; I hadn't updated because all my other scripts were working and I didn't want to break anything.
