### ISSUE TITLE
outfitting with techs

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#511]
Potentially adding more acceptable outfitting items for people with tailoring techs.

**Comment by rpherbig** [comment]
Can you list some items you saw as options but that the script did not find acceptable?

**Comment by xtremenerdrage** [comment]
Ill have to research on this, I have techs for tailoring, do you just need a list of the ones its offering?

**Comment by rpherbig** [comment]
It seems to me like we should review the items that `workorders` is rejecting and see if any of them are good candidates and should be added to `base-crafting.yaml`. Does that seem reasonable, @rcuhljr ?

**Comment by rcuhljr** [comment]
Outfitting work orders only submits knitting currently. All knitting recipes should be added to the base-crafting file, but in order to accept work orders for non knitting things we'd need to overhaul workorders.lic
