### ISSUE TITLE
head-splitters wrong app

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#512]
[combat-trainer]>app splitter quick
You cannot appraise that when you are in combat!
>
[combat-trainer]>load arrows
You reach into your pack to load the battle longbow with some ice-adder arrows.
Roundtime 8 sec.
>
* A zombie head-splitter looms menacingly and swings at you.  You evade.  
[You're solidly balanced with opponent in better position.]

**Comment by rpherbig** [comment]
Does "app head-splitter" work?

**Comment by xtremenerdrage** [comment]
yea app head-splitter works

>app head-split
You are certain that the zombie head-splitter is healthy.
You are certain that it is about as strong as you are.
You are certain that it is not quite as agile as you are.
You are certain that it is rather less disciplined than you are.
You are certain that it is somewhat less quick to react than you are.
You are certain that it is about as conditioned as you are.

**Comment by rcuhljr** [comment]
We'll need to fix this in drinfomon's npc name location logic.

**Comment by rcuhljr** [comment]
Should be fixed, please make a new issue if it's still broken.
