### ISSUE TITLE
Add urn to supported trash bins

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#513]
It would be nice to use the urn here, outside the mm guild.

R>l
[Middens, Crossbow Bend - 19162]
Before you stands the Observatory of the Southern Crossbow.  It is a three-story edifice, its sixteen-sided walls capped with a crystal dome.  The top floor is also the nerve center of the Moon Mages' Guild, a most powerful and revered arcane circle throughout Elanthia.  All in all a rather quirky structure, it manages to inspire awe and curiosity at the same time.  A carved ivory door leads inside.  You also see a pile of rocks, a broken rune, a tiny hammer, an ivory urn and an ornate silver gateway.
Also here: Jonas.
Obvious paths: west.

**Comment by rcuhljr** [comment]
Should be done.
