### ISSUE TITLE
Swappable katana issues in combat-trainer

### ISSUE THREAD

**Issue by Khalikryst** [rpherbig/dr-scripts#5146]
[combat-trainer: message: You shift your tempered katana so you can use it one-handed.]
[combat-trainer: checked against [/ heavy edged /i, /\bkatana\b.*(light edged|medium edged|heavy edged|two-handed edged|light blunt|medium blunt|heavy blunt|two-handed blunt|light thrown|heavy thrown|short staff|quarter staff|halberd|pike)/, /You must have two free hands/i, /You have nothing to swap/, /Your (left|right) hand is too injured/, /Will alone cannot conquer the paralysis that has wracked your body/, /^You move a .* to your (left|right) hand/]]
[combat-trainer: for command swap my katana]

[combat-trainer: message: You shift the tempered katana so you can use it two-handed.]
[combat-trainer: checked against [/ heavy edged /i, /\bkatana\b.*(light edged|medium edged|heavy edged|two-handed edged|light blunt|medium blunt|heavy blunt|two-handed blunt|light thrown|heavy thrown|short staff|quarter staff|halberd|pike)/, /You must have two free hands/i, /You have nothing to swap/, /Your (left|right) hand is too injured/, /Will alone cannot conquer the paralysis that has wracked your body/, /^You move a .* to your (left|right) hand/]]
[combat-trainer: for command swap my katana]

I believe it just needs to have one-handed and two-handed added to the list.

**Comment by Kaesken** [comment]
The only thing I hadn't noticed in the code is when it wants to use your two-handed part of the katana, it doesn't have just "two-handed" under the check list.  It only has "two-handed edged" and "two-handed blunt".

**Comment by MahtraDR** [comment]
@KatoakDR What do you think on this one? Worth adding support specifically for katanas. I don't have one to test, alas.

**Comment by asechrest** [comment]
I glanced at this a while back. It will definitely take some changes to the way combat trainer understands what weapon skill has been swapped to. And what's unfortunate is that this katana seems like the only weapon that has this issue. I don't have this katana to test, so I don't feel comfortable making code changes without the ability to test.

**Comment by MahtraDR** [comment]
@Khalikryst are you willing to loan your katana out to one of us to test this out? None of us have katanas so this will not be implemented if we can't test it...

**Comment by MahtraDR** [comment]
@rpherbig Close this? We can't do anything without the item to test.
