### ISSUE TITLE
combat trainer giving following error

### ISSUE THREAD

**Issue by aruthas** [rpherbig/dr-scripts#5156]
--- Lich: error: no implicit conversion of Symbol into Integer
    combat-trainer:3165:in shoot_aimed'
    combat-trainer:3190:in attack_aimed'
--- Lich: combat-trainer has exited.

has something to do with

if Flags['ct-ranged-ammo']
      ammo = Flags['ct-ranged-ammo'][:ammo].to_s
      @firing_check = 0
      quantity = game_state.dual_load? ? 2 : 1
      stow_ammo(ammo, quantity)
      Flags.reset('ct-ranged-ammo')
end

**Comment by rpherbig** [comment]
@aruthas what version of Ruby do you have?

@KatoakDR it looks like those lines were last touched in #4890 - is this related to that PR?

**Comment by aruthas** [comment]
2.5.5 is the version I have.  I updated the commons and combat-trainer, as well as events.  I know its something on my end.  Having something to with Flags

**Comment by rcuhljr** [comment]
Either events.lic isn't updated properly or combat-trainer isn't. Verify what flag is being set for ct-ranged-ammo and the status of events.lic, named group matching has been in place since ruby 1.9.2

**Comment by KatoakDR** [comment]
> --- Lich: error: no implicit conversion of Symbol into Integer
> combat-trainer:3165:in shoot_aimed'
> combat-trainer:3190:in attack_aimed'
> --- Lich: combat-trainer has exited.

@aruthas Do you have the log of the "You fire...." message right before that error happened? Are you still having this error come up or was it a one time fluke?

Also, sorry for the late follow up, I was out of the game for a few months and not monitoring things.

**Comment by MahtraDR** [comment]
@aruthas Is this still an issue? Do you have the log referenced above?

**Comment by MahtraDR** [comment]
@rpherbig I think we can close this, since there's no followup.
