### ISSUE TITLE
crossing-training match on khri already in use

### ISSUE THREAD

**Issue by cpryor6** [rpherbig/dr-scripts#518]
thank you for taking a look!  here is the log:

[crossing-training]>stow right
You put your compendium in your hitman's backpack.
>
[crossing-training]>Khri Focus Plunder
You're already using the Focus meditation.
You're already using the Plunder meditation.
>
[crossing-training: *** No match was found after 15 seconds, dumping info]
[crossing-training: messages seen length: 10]
[crossing-training: message: You're already using the Focus meditation.]
[crossing-training: message: You're already using the Plunder meditation.]
[crossing-training: message:  Khri Plunder  (11 roisaen)]
[crossing-training: message:  Khri Focus  (14 roisaen)]
[crossing-training: message:  Khri Dampen  (10 roisaen)]
[crossing-training: message:  Khri Hasten  (14 roisaen)]
[crossing-training: message:  Khri Plunder  (11 roisaen)]
[crossing-training: message:  Khri Focus  (14 roisaen)]
[crossing-training: message:  Khri Dampen  (10 roisaen)]
[crossing-training: message:  Khri Hasten  (13 roisaen)]
[crossing-training: checked against [/With deep breaths/i, /Centering your mind/i, /Focusing your mind/i, /Remembering the mantra of/i, /Turning inwards, you find the/i, /Darkness is no bar to a/i, /Taking a deep breath/i, /Placing all of your thoughts/i, /Your hand twitches slightly/i, /With but a quick thought/i, /You calm your body and mind/i, /Letting your thoughts fall into/i, /You calm yourself with a deep breath/i, /Tapping into the well of mental power within/i, /Knowing that a dose of paranoia is healthy/i, /Willing your body to meet the heightened/i, /Purging yourself of all distractions/i, /Your dedicated training lends you grace/i, /You carefully relax your mind through/i, /Honing your mind and body to a single purpose/i, /Nothing happens/i, /Your body is willing/i, /You have not recovered/i]]
[crossing-training]>Khri Hasten Dampen
You're already using the Hasten meditation.
You're already using the Dampen meditation.
>
[crossing-training: *** No match was found after 15 seconds, dumping info]
[crossing-training: messages seen length: 11]
[crossing-training: message: You're already using the Hasten meditation.]
[crossing-training: message: You're already using the Dampen meditation.]
[crossing-training: message:  Khri Plunder  (11 roisaen)]
[crossing-training: message:  Khri Focus  (14 roisaen)]
[crossing-training: message:  Khri Dampen  (10 roisaen)]
[crossing-training: message:  Khri Hasten  (13 roisaen)]
[crossing-training: message: [DRPrime]-DR:Etreu: "Apparently the hotel is empty this week because my normal upgraded room got me into this 4 room 'room' hot tub, and screened in porch."]
[crossing-training: message:  Khri Plunder  (11 roisaen)]
[crossing-training: message:  Khri Focus  (14 roisaen)]
[crossing-training: message:  Khri Dampen  (10 roisaen)]
[crossing-training: message:  Khri Hasten  (13 roisaen)]
[crossing-training: checked against [/With deep breaths/i, /Centering your mind/i, /Focusing your mind/i, /Remembering the mantra of/i, /Turning inwards, you find the/i, /Darkness is no bar to a/i, /Taking a deep breath/i, /Placing all of your thoughts/i, /Your hand twitches slightly/i, /With but a quick thought/i, /You calm your body and mind/i, /Letting your thoughts fall into/i, /You calm yourself with a deep breath/i, /Tapping into the well of mental power within/i, /Knowing that a dose of paranoia is healthy/i, /Willing your body to meet the heightened/i, /Purging yourself of all distractions/i, /Your dedicated training lends you grace/i, /You carefully relax your mind through/i, /Honing your mind and body to a single purpose/i, /Nothing happens/i, /Your body is willing/i, /You have not recovered/i]]
[crossing-training]>collect rock
>
Hawkishly you spot your target and begin to forage.
You manage to collect a pile of rocks.
Roundtime: 15 sec.
>
[crossing-training]>kick rocks
You take a step back and run up to the pile of rocks.  Bringing your foot smashing down onto the pile, you send bits and pieces of debris scattering in every direction.  Looking around for the now defunct mountain of glory, you fail to find any signs of its presence.
>
[crossing-training]>collect rock
You manage to collect a pile of rocks.
Roundtime: 15 sec.

**Comment by rcuhljr** [comment]
Should be fixed.
