### ISSUE TITLE
craft.lic buys wrong enchanting supplies

### ISSUE THREAD

**Issue by Donntae** [rpherbig/dr-scripts#5216]
craft.lic is buying induction and abolition sigil-scrolls, but enchant is trying to use abolition and congruence to make a holy ritual focus. craft.lic is being called by t2 for general training.

Log is here:
https://pastebin.com/w676WUHD

**Comment by rpherbig** [comment]
@Dartellum

**Comment by BinuDR** [comment]
I'm working on it.

**Comment by BinuDR** [comment]
@Donntae I've submitted a fix.  In the meantime you can edit craft.lic and change line 347 from ordering 1 to 3 as follows:

`      DRCT.order_item(crafting_data['artificing'][@hometown]['stock-room'], 3) unless DRCI.exists?("induction sigil-scroll")`
