### ISSUE TITLE
transfer-items

### ISSUE THREAD

**Issue by simmish** [rpherbig/dr-scripts#5224]
Please add transferring of items from a worn/held container into another container not on oneself.  For instance, transferring from a backpack to a donation shelf or trashcan.  would be amazing!

**Comment by asechrest** [comment]
I'm pretty green but I'll give this a whirl. No timeframe. On Discord there was a suggestion to make this a separate script from transfer-items, which is primarily designed to safely transfer items between things on your own person. Transferring off your person would be inherently unsafe, thus the suggestion to make it separate. I'm thinking "offload-items" or something similarly named.

**Comment by simmish** [comment]
Hey no timeframe needed!  I tried to figure it out but my eyes cross with ruby and dr stuff.  Probably doesn't help I'm a novice at it.

Makes sense for a separate script for sure.  Just for the backlash people would post if they weren't paying attention or made a typo

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by asechrest** [comment]
@rpherbig  This can be closed via #5232
