### ISSUE TITLE
Tactics manuevers fail if not standing, missing 'You should stand up first'

### ISSUE THREAD

**Issue by Chewmatca** [rpherbig/dr-scripts#5242]
"You should stand up first" is not included in combat-trainer.lic
can search for instances of: 'You must be standing'
Lines 2464 and Line 2742 look to need to have this added, or your dude just stands there gettin whacked while prone.

Others also advised it could be same in issue for combat manuevers:

Zin — Today at 11:11 AM
re: the standing thing, the same issue exists for combat manuevers
If you fall before the command goes through and get a failure for not standing

**Comment by Chewmatca** [comment]
Full log, expect the script to stand when it did not, due to not catching "You must be standing" after being knocked to the ground.

An ice archon raises its massive icy foot and brings it downward!
The massive impact shakes the ground!
You fall over as the world shakes beneath you!
[You're mighty, very badly balanced with opponent overwhelming you.]


The ice archon moves into a position to parry.
P> 
An ice archon backs away from combat, sending a shower of ice shards from its body as it does so.
An ice archon moves ponderously northwest, dragging its feet and leaving huge snowy scratches behind it.

P> 
[combat-trainer]>analyze

True Bard Natarian just arrived.

P> 
True Bard Natarian goes southeast.

P> 
You should stand up first.
P> 
P> 
Jobber Sall just arrived.

P> 

The ice archon begins to advance on Sall.
P> 
Jobber Sall strolls southeast.

P> 
Your silver glow flares.
The air around you solidifies into a blinding yellow luminescence, collapsing under the force of the attack in a silent cascade of glassy fragments that vanish before reaching the ground.

Your silver glow flares.

You feel fully attuned to the mana streams again.
P> 
Your silver glow flares.

Your silver glow flares.

Your silver glow flares.


| ***STATUS*** stopping due to bleeding

An ice archon backs away from combat, sending a shower of ice shards from its body as it does so.
An ice archon moves ponderously northeast, dragging its feet and leaving huge snowy scratches behind it.

!SP> 
Your silver glow flares.

!SP> 
!P> 
Your silver glow flares.

!P> 
Your silver glow flares.

!P> 
[combat-trainer: *** No match was found after 15 seconds, dumping info]

[combat-trainer: messages seen length: 69]

[combat-trainer: message: [You're very badly hurt, mighty, very badly balanced with opponent overwhelming you.]]

[combat-trainer: message: * An ice archon sweeps low at you.  You attempt to dodge.  The sword lands a heavy strike that tears a painful cut across the knuckle of the left thumb.]

[combat-trainer: message: Your silver glow flares.]

[combat-trainer: message: [You're badly hurt, mighty, extremely imbalanced with opponent overwhelming you.]]

[combat-trainer: message: * An ice archon sweeps low at you.  You evade.  ]

[combat-trainer: message: [You're badly hurt, mighty, extremely imbalanced with opponent overwhelming you.]]

[combat-trainer: message: * An ice archon sweeps low at you.  You attempt to evade.  The sword lands a strong hit that painfully mashes several toes of the left foot.]

[combat-trainer: message: Your silver glow flares.]

[combat-trainer: message: Hydra Hex  (Indefinite)]

[combat-trainer: message: Major Physical Protection  (OM)]

[combat-trainer: message: Minor Physical Protection  (OM)]

[combat-trainer: message: Auspice  (OM)]

[combat-trainer: message: Shield of Light  (OM)]

[combat-trainer: message: Benediction  (OM)]

[combat-trainer: message: Centering  (OM)]

[combat-trainer: message: Glythtide's Gift  (OM)]

[combat-trainer: message: Persistence of Mana  (OM)]

[combat-trainer: message: Soul Shield  (36 roisaen)]

[combat-trainer: message: Divine Radiance  (38 roisaen)]

[combat-trainer: message: Osrel Meraud  (100%)]

[combat-trainer: message: [You're very beat up, mighty, extremely imbalanced with opponent overwhelming you.]]

[combat-trainer: message: * An ice archon sweeps low at you.  You attempt to dodge.  The sword lands a hard hit that tears the skin over the left elbow.]

[combat-trainer: message: Your silver glow flares.]

[combat-trainer: message: An ice archon moves ponderously northeast, dragging its feet and leaving huge snowy scratches behind it.]

[combat-trainer: message: An ice archon backs away from combat, sending a shower of ice shards from its body as it does so.]

[combat-trainer: message: [You're beat up, mighty, extremely imbalanced with opponent overwhelming you.]]

[combat-trainer: message: * An ice archon chops wide at you.  You barely fail to block with small shield.  The sword lands a solid hit that tears the skin over the left elbow, lightly stunning you.]

[combat-trainer: message: Your silver glow flares.]

[combat-trainer: message: [You're battered, mighty, very badly balanced with opponent overwhelming you.]]

[combat-trainer: message: * An ice archon chops wide at you.  You attempt to evade.  The sword lands a strong hit that nicks your left forearm.]

[combat-trainer: message: Your silver glow flares.]

[combat-trainer: message: [You're hurt, mighty, very badly balanced with opponent overwhelming you.]]

[combat-trainer: message: * An ice archon slices wide at you.  You barely fail to block with small shield.  The sword lands a strong hit to your left arm.]

[combat-trainer: message: Your silver glow flares.]

[combat-trainer: message: You feel fully attuned to the mana streams again.]

[combat-trainer: message: [You're bruised, mighty, very badly balanced with opponent overwhelming you.]]

[combat-trainer: message: * An ice archon chops wide at you.  You attempt to dodge.  The sword lands a strong hit to your back.]

[combat-trainer: message: Your silver glow flares.]

[combat-trainer: message: A cage of shadowy tendrils coalesces around an ice archon.]

[combat-trainer: message: A cage of shadowy tendrils coalesces around an ice archon.]

[combat-trainer: message: A cage of shadowy tendrils coalesces around an ice archon.]

[combat-trainer: message: A cage of shadowy tendrils coalesces around an ice archon.]

[combat-trainer: message: [You're mighty, very badly balanced with opponent overwhelming you.]]

[combat-trainer: message: * An ice archon feints low at you.  You attempt to dodge.  The sword lands a grazing strike to your left arm.]

[combat-trainer: message: The air around you solidifies into a blinding yellow luminescence, collapsing under the force of the attack in a silent cascade of glassy fragments that vanish before reaching the ground.]

[combat-trainer: message: Your silver glow flares.]

[combat-trainer: message: Jobber Sall strolls southeast.]

[combat-trainer: message: The ice archon begins to advance on Sall.]

[combat-trainer: message: [You're mighty, very badly balanced with opponent overwhelming you.]]

[combat-trainer: message: * An ice archon feints high at you.  You barely block with a small shield.  ]

[combat-trainer: message: [You're mighty, very badly balanced with opponent overwhelming you.]]

[combat-trainer: message: * An ice archon feints high at you.  You evade.  ]

[combat-trainer: message: Hydra Hex  (Indefinite)]

[combat-trainer: message: Major Physical Protection  (OM)]

[combat-trainer: message: Minor Physical Protection  (OM)]

[combat-trainer: message: Auspice  (OM)]

[combat-trainer: message: Shield of Light  (OM)]

[combat-trainer: message: Benediction  (OM)]

[combat-trainer: message: Centering  (OM)]

[combat-trainer: message: Glythtide's Gift  (OM)]

[combat-trainer: message: Persistence of Mana  (OM)]

[combat-trainer: message: Soul Shield  (37 roisaen)]

[combat-trainer: message: Divine Radiance  (38 roisaen)]

[combat-trainer: message: Manifest Force  (35 roisaen)]

[combat-trainer: message: Osrel Meraud  (100%)]

[combat-trainer: message: Jobber Sall just arrived.]

[combat-trainer: message: You should stand up first.]

[combat-trainer: message: True Bard Natarian goes southeast.]

[combat-trainer: message: True Bard Natarian just arrived.]

[combat-trainer: checked against [/roundtime/i, /Analyze what/i, /Your analysis reveals a massive opening/i, /You reveal an? .* (?:weakness|opening)/, /Your analysis reveals an? .* (?:weakness|opening)/, /You fail to find any holes/i, /There is nothing else/i, /Face what/i, /You must be closer/i, /You must be standing/i, /Strangely, you don't feel like fighting right now/i, /flying too high for you to attack/i, /Bumbling, you slip/i]]

[combat-trainer: for command analyze]

**Comment by asechrest** [comment]
Another hangup in the maneuver section per Zin on Discord:

```
The massive impact shakes the ground!
You fall over as the world shakes beneath you!
[You're winded, extremely imbalanced with opponent dominating.]

[combat-trainer]>maneuver doublestrike

You must be standing to perform that maneuver.
```

**Comment by asechrest** [comment]
@Chewmatca this should now be fixed.

@rpherbig We can close this via #5247
