### ISSUE TITLE
Add Capability for Crossing-Training to Steal From Beggar/Veteran/Minstrel During Thievery Session

### ISSUE THREAD

**Issue by cpryor6** [rpherbig/dr-scripts#525]
This is similar to what the old progressive stealing script did:  during a given run, if one came across the beggar/veteran/minstrel, the script would stop, hide, stalk, and steal.  I figure one grab for the lowbies, a few grabs for 150+ and five grabs for 300+ would be a great bump to learning during a run.  Thank you for considering this!

**Comment by rpherbig** [comment]
It wouldn't be hard for us to generalize `find-beggar` into `find` (or `find-npc`? or...) which gets us most of the way there.
