### ISSUE TITLE
Make train for multiple stats follow in game nomenclature

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#53]
add support for goal args.

;train reflex 20

trains reflex up to 20.

;train ref 20 str 15 int

trains reflex to 20, strength to 15, and int to +1.

**Comment by rpherbig** [comment]
I wonder if it's better to deviate from the game's syntax in this case.

;train reflex 5 => +5 makes a lot more sense to me

Alternatively, we could check the number against their current stat. If it is higher, assume it is a goal. If lower, assume it is an increment. Do you think that's too complicated or unintuitive?

**Comment by rcuhljr** [comment]
I'd rather just move entirely one way or the other. I'm fine with +5 interpretation, I don't mind a little more math. On the other hand if we went with goals I think it could make it more natural to be able to set goals with train, and just run train periodically which works toward your goals.

so ;train goals ref 40 cha 15 agi 45

then in the future I can hit ;train and it will train whatever it can towards those goals cheapest first.

**Comment by rpherbig** [comment]
That's an interesting idea.

The logic would be more complicated, since right now the script knows nothing of *incremental* TDP cost, only the *total* to reach a target/goal.

I'd added a check that it trains all-or-nothing. Are you now in favor of it training whatever it can?

**Comment by rpherbig** [comment]
After some LNet discussion, the consensus seems to be to go with syntax like ";train reflex 3" to train reflex 3 times (from N to N+3).

There is also a desire to remove the TDP check and therefore train as many times as possible.

**Comment by rcuhljr** [comment]
Settled on train r d 3 a I 5 syntax. No number means train 1.
