### ISSUE TITLE
Dependency in mainline lich repo is out of date

### ISSUE THREAD

**Issue by MahtraDR** [rpherbig/dr-scripts#5329]
@jayRyan24 i think Etreu is yours, and he's listed as the owner of the version of dependency uploaded to the mainline lich repo (with ;repos) would you mind pulling that and I or @KatoakDR can upload and maintain an up to date version? 

This impacts new users who have to manually download an up to date version from discord or GitHub and causes some pain with support. 

Thanks!

@rpherbig do you know if anyones ever tried to get our dependency bundled into the main lich repo by default? https://github.com/matt-lowe/Lich

**Comment by rcuhljr** [comment]
Etreu is mine and that account has been inactive for like 2-3 years. If tillmen is active you can have him remove it or change ownership in repository.

**Comment by MahtraDR** [comment]
Thank you for replying. I haven't tried Tillman yet. Can do next. 

If it's been inactive for that long, you can get a free month of premium using https://www.play.net/dr/promo/reactivate/home.asp?offerCode=DRBACKAFTER6

Would you be willing to do that? You can cancel right after.

**Comment by rcuhljr** [comment]
I'll be home again in ~4 days, I can look into it if Tillmen isn't tracked down yet.

**Comment by MahtraDR** [comment]
Following up, I've written to Tillmen just now. I asked that he delete the file from the repo, and referenced this thread.

I've also asked him to blacklist the filename from the repo, if possible. That prevents this issue in the future, and lets us manage new-installs our own way, without depending on the main lich repo. Katoak or I could maintain the file, but it's just as plausible one of us ends up leaving the game as anyone else has.

**Comment by rcuhljr** [comment]
I mean if we're moving the boot strapping file somewhere else it doesn't _super_ matter if it's still in `;repo`, just update the docs to all reference the new file location and the repo copy should drift off into the forgotten past.

**Comment by MahtraDR** [comment]
> I mean if we're moving the boot strapping file somewhere else it doesn't _super_ matter if it's still in `;repo`, just update the docs to all reference the new file location and the repo copy should drift off into the forgotten past.

The problem with the ;repo version is that it causes newbies problems. We get a lot of people coming to discord with half-installed lich, and it often comes from them having used the out of date dependency in ;repos.

My thinking is actually to remove your copy, and replace it not with the current up to date version, but with a placeholder script which references this repo, and the discord instead. That way even if I stop playing, or whoever else uploads this, stops playing, we don't end up in the same position as we are today...

Note Tillmen hasn't replied at all. :(

**Comment by vtcifer** [comment]
> The problem with the ;repo version is that it causes newbies problems. We get a lot of people coming to discord with half-installed lich, and it often comes from them having used the out of date dependency in ;repos.

If none of our instructions don't reference it anymore, and people still do it: 🤷‍♂️

**Comment by MahtraDR** [comment]
@rcuhljr Any chance you could look into this again? Nothing from Tillmen, and this would make a big difference to our support experience. :)

**Comment by MahtraDR** [comment]
@rcuhljr Any chance you can look into this? 

If you sign up with the code/link above, you get a free month. We just need you to pull that one file, and you can cancel again. 

Thanks!

**Comment by rcuhljr** [comment]
@MahtraDR 
```
[repository: deleting dependency.lic in 5 seconds... (;k repository to cancel)]
[repository: password saved for author Etreu]
[repository: done]
```

**Comment by MahtraDR** [comment]
> @MahtraDR
> 
> ```
> [repository: deleting dependency.lic in 5 seconds... (;k repository to cancel)]
> [repository: password saved for author Etreu]
> [repository: done]
> ```

Thank you! I've uploaded a meta script to replace it, giving instructions to come to github, or discord.
