### ISSUE TITLE
Add Stop on Mindlock to Locksmithing during Crossing-Training

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#535]
Currently the Locksmithing crossing-training doesn't stop until it reaches a new step in the process.  For example, the character will begin picking the box but will not stop until it is open, even if he/she becomes mindlocked.  If it would check for mindlocked every so often it would allow for the effective use of Pet Boxes.  Otherwise, it seems as though you'll try lockpicking until you run out of lockpicks.  I've noticed other crossing-training skills such as First Aid stop randomly in mid training, so it would be nice if locksmithing was modified to do the same somehow.

**Comment by rpherbig** [comment]
This looks like an extension of #17.

**Comment by wscherer420** [comment]
Is the Pick Script the same as the training that is done through Crossing-Training with you activate "-Locksmithing"?  If so, then yes that would seem to take care of it.

**Comment by wscherer420** [comment]
Right now I get a Pet Box, i have someone else disarm it because i can't. The only thing left for the box is to pick it. In locksmithing it wont stop when I'm mindlocked because I never progress past picking the box, i'm not able to open it at this skill level. So it doesn't stop until all the lockpicks are gone.

**Comment by rpherbig** [comment]
@rcuhljr Does the pet box logic not already do this?

**Comment by wscherer420** [comment]
hmmm...not sure what Pet Box Logic is.  To me a pet box is just a box i above my capability.  Is there a pet box script or command i should be using?

**Comment by rpherbig** [comment]
In #529 (04ffd0fed7df6a441c3769696ea022d1d69a97ad and 38fcc7a61c35b1cd43235ea0792255e4c9522e56) @rcuhljr implemented support for a pet box (matching your definition).

If you have no boxes in your `picking_box_source` container, it'll then check your `picking_pet_box_source` container for boxes. If it finds one, it'll disarm and then pick blind until mindlocked. Can you try setting `picking_pet_box_source` and see if that does what you want?

**Comment by rcuhljr** [comment]
This setting is NOT for boxes that aren't disarmed really, that's just a safety measure in case you put a non disarmed box into the pet box bag. It's going to disarm with armor on.

**Comment by wscherer420** [comment]
Would my regular picking container need to be different than the pet box container?


Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone
-------- Original message --------From: Robert Herbig <notifications@github.com> Date: 7/18/16  8:14 PM  (GMT-08:00) To: rpherbig/dr-scripts <dr-scripts@noreply.github.com> Cc: wscherer420 <alex@attismanagement.com>, Author <author@noreply.github.com> Subject: Re: [rpherbig/dr-scripts] Add Stop on Mindlock to Locksmithing during
  Crossing-Training (#535) 
In #529 (04ffd0f and 38fcc7a) @rcuhljr implemented support for a pet box (matching your definition).

If you have no boxes in your picking_box_source container, it'll then check your picking_pet_box_source container for boxes. If it finds one, it'll disarm and then pick blind until mindlocked. Can you try setting picking_pet_box_source and see if that does what you want?

**Comment by rcuhljr** [comment]
Yes. The only way it knows what the box type is is based on what container it comes from.

**Comment by wscherer420** [comment]
This was taken care of for me, i hadn't known about the petbox setting.  I am no longer running into the issue of locksmithing not stopping.
