### ISSUE TITLE
stand true/false for Pick.lic

### ISSUE THREAD

**Issue by Bmoney420** [rpherbig/dr-scripts#5363]
would like it if there was a feature to allow to sit/stand while picking

**Comment by MahtraDR** [comment]
Weird, but doable. I'll look into this tonight. 😀

**Comment by asechrest** [comment]
I have an edit saved. Will test shortly.

**Comment by MahtraDR** [comment]
@rpherbig this is resolved by https://github.com/rpherbig/dr-scripts/pull/5364
