### ISSUE TITLE
Sell-Loot - Issue selling certain gems.

### ISSUE THREAD

**Issue by SekmehtDR** [rpherbig/dr-scripts#5370]
```
[sell-loot]>rummage /G my gem pouch

You rummage through a suede gem pouch looking for gems and see a tiny mint green tsavorite, a medium chunk of coral, 
a tiny cinnamon chunk of coral, a medium chunk of coral, a medium chunk of coral, a large chunk of coral, 
a small chunk of coral, a medium chunk of coral, a small chunk of coral, a tiny cinnamon chunk of coral, 
a tiny cinnamon chunk of coral, a small chunk of coral, a medium chunk of coral, a medium chunk of coral, 
a tiny cinnamon chunk of coral, a large chunk of coral, a small chunk of coral, a small chunk of coral, 
a tiny cinnamon chunk of coral, a small chunk of coral, a small chunk of coral, a medium chunk of coral, 
a small chunk of coral and a large chunk of coral.
> 

[sell-loot]>get my chunk from my gem pouch

What were you referring to?
> 
[sell-loot]>sell my chunk to Anthelorm
```
Regex seems to only be passing "chunk" instead of "coral", is there an easy fix for this to adjust the regex or something else? Figured i'd report it if any other players have issues with it.

**Comment by rpherbig** [comment]
@KatoakDR is this related to #5351?

**Comment by rpherbig** [comment]
@asechrest is this related to #5339 ?

**Comment by KatoakDR** [comment]
> @KatoakDR is this related to #5351?

Yes in that I need to submit another PR like 5351 that handles "chunk of" and "hunk of" like we previously added support for "piece/set/pair of"

**Comment by asechrest** [comment]
> @asechrest is this related to #5339 ?

Interestingly, this uses a different rummage method. The selling of _gems_ within `sell-loot` uses `DRC.get_gems` => `DRC.rummage` => `DRC.list_to_nouns' => `DRC.get_noun` => `DRC.remove_flavor_text`. That last one is the one that @KatoakDR is working on (thankfully!) and the regex processing in that thing is an absolute bear.

The PR I worked on involved the selling of metals and stones within `sell-loot`, and that uses `DRCI.get_item_list` => `DRCI.rummage_container`.

I actually think my PR to the `DRCI.rummage_container` method would work for this issue, but it would need a tweak (I think) to rummage with the `/G` flag. There may be an opportunity for consolidation of methods here. Not sure.
