### ISSUE TITLE
Equipment manager support for inventory items that transform into weapons

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#539]
There are some weapons which are transformed to worn items. These would need some special wielding and sheathing logic to use properly. Here is an example

```
>remove tailband
You remove a polished steel tailband with serrated edges from your tail.
>turn tailband
With a flick of your thumb, you spin your steel tailband into the air.  As it starts its downward spiral toward you, the steel tailband suddenly explodes into a fine mist, expanding into a polished steel katavdar with serrated edges as it settles into your palm.
>turn katavdar
With a flick of your thumb and a turn of your wrist, the katavdar trembles then shrinks, settling into your palm as a polished steel tailband with serrated edges.
>wear tailband
You attach a polished steel tailband with serrated edges to your tail.
```

**Comment by jandersson** [comment]
I wouldn't mind working on this myself, seeing as your plates are probably full. 

Would the recommended course of action be to add a new attribute to gear items? 
`gear:
- :name: tailband
  :adjective: polished
  :is_worn: true
  :transforms_to: katavdar
  :transform_verb: turn
- :name: katavdar
  :is_worn: false
  :transforms_to: polished tailband
  :transform_verb: turn`

Then use this to wield, sheath the item/weapon in equipment manager?

**Comment by rpherbig** [comment]
Adding a new attribute seems like a natural way to go, but I think it's going to be a bit awkward no matter what. You have an item that may or may not exist at any given time and that's ok.

`get_item_helper` is almost what you want, but there are really two steps (remove then turn).

**Comment by rpherbig** [comment]
@rcuhljr Any thoughts on this one?
