### ISSUE TITLE
Faulty Stealing Logic

### ISSUE THREAD

**Issue by pradmer** [rpherbig/dr-scripts#540]
Crossing-Training doesn't stick to stealing items in the acceptable range as expected. Pastebin examples below.

http://pastebin.com/K8yrPuwn

**Comment by rpherbig** [comment]
I'm not familiar with the stealing logic. What did you expect to happen (as opposed to what you saw, logged in the pastebin)?

**Comment by pradmer** [comment]
I've been working on this off and and with Etreu. The way I understand it, the script should always be targeting items that fall in the "acceptable" teaching range. When it cross references base-stealing.yaml it should see that my current skill level is +1 from the acceptable_max of the item I was stealing on my previous rank and attempt to keep working on that item. Instead for a select number of shops in the pastebin it targets items that are either known to be above or below the acceptable range.
