### ISSUE TITLE
[script][circlecheck] - Doesn't pull yaml setting

### ISSUE THREAD

**Issue by asechrest** [rpherbig/dr-scripts#5419]
[Reported by penguin23](https://discordapp.com/channels/745675889622384681/745676101392793651/929472340222418945) in Discord.

For those who have the pretty_print yaml option set to show the updated format of `;circlecheck`, the script occasionally doesn't pull the yaml setting properly and the script shows the old format. The problem is rare.

It's not currently clear why this happens.

**Comment by asechrest** [comment]
There was a suggestion that this was some sort of race condition. Unfortunately I don't know the back-end of the functioning of the code enough to understand whether that could be the case. I also don't know why _this_ script would have trouble sometimes pulling a yaml setting, but others don't.

I don't really want to put a pause in this script to try to overcome the race condition, if that's what we're dealing with. Welcome any ideas.

PS - I did have one additional report that this happened once for another user. It's rare, but it happens.

**Comment by MahtraDR** [comment]
@asechrest Shall we close this? We know it's the other issue now.

**Comment by asechrest** [comment]
> @asechrest Shall we close this? We know it's the other issue now.

Fine with me. Either way, I'll tag it once new dependency merges.

**Comment by asechrest** [comment]
Issue now known. Closing as a duplicate of #5451
