### ISSUE TITLE
Additions to cast_messages:

### ISSUE THREAD

**Issue by ericmeek** [rpherbig/dr-scripts#545]
These currently timeout waiting:

[combat-trainer]>cast
You turn to face a red bear orc scout.
You breathe deeply, centering your energies before turning to a red bear orc scout.
Your cambrinth ring emits a loud *snap* as it discharges all its power to aid your spell.
Small globes of blue and orange light appear and dart upward like fireflies.
Creating an ominous shadow, a small scrub-oak limb falls from above!
The limb slams heavily into a red bear orc scout, knocking it completely out!

Shattered in the strike, the limb is absorbed back into the earth.
Roundtime: 2 sec.

[combat-trainer]>cast
You breathe deeply, centering your energies before turning to a red bear orc scout.
You strain, but are too mentally fatigued to finish the pattern, and it slips away.
>

**Comment by rcuhljr** [comment]
Added 'You breathe deeply, centering your energies' which should trigger both of these, I'm not sure if we want the too mentally fatigued message added as well. @rpherbig ?

**Comment by rpherbig** [comment]
I don't think it is necessary.
