### ISSUE TITLE
Possible race condition/collision causing semi-frequent get_settings or get_data failures

### ISSUE THREAD

**Issue by asechrest** [rpherbig/dr-scripts#5451]
We've had a number of reports, or personal experiences, with failures to `get_settings` or `get_data` within scripts. Examples:

- penguin23 on Discord reports that occasionally, my optional pretty formatting of the `;circlecheck` script output appears to fail to pull the yaml setting `circlecheck_prettyprint`. (Issue #5419 )
- @MahtraDR reports that his updates to allow releasing only certain cyclics sometimes fails to pull the yaml list of cyclics not to release.
- @KatoakDR reports that his autostarted `;buff-watcher` occasionally exits at starting because it finds no waggle sets.
- In script code [there exists some workarounds](https://github.com/rpherbig/dr-scripts/blob/8e38c9623a51893c389fc2724fd537d47c5ceb42/common-travel.lic#L330) for when this collision or race condition rears its head.

I wrote a script to see if I could cause the condition to happen on a regular basis and was successful. Granted, this was a stress test.

![image](https://user-images.githubusercontent.com/6467969/150596664-0d58cdd9-ccb7-487f-80c5-745e89cba4c0.png)

The frequency of the failure seems to be related to a lot going on, and a possible collision _between_ `get_data` and `get_settings`.

I was able to cause the most frequent failures during busy times (combat), with a number of scripts already running, and by making adjacent `get_data` and `get_settings` calls in my stress test script.

I don't have the background at the moment to really fix this issue, but I know @KatoakDR and @MahtraDR are taking a look at it. The hunch at the moment is, again, the possible collision between between the two methods and how they do what they do.

I'll let those two expound on the hunch if desired.

**Comment by KatoakDR** [comment]
Thanks for the write-up @asechrest 

I'm working on adding synchronization to the SetupFiles class in dependency, and other code cleanup, to remove the race condition.

**Comment by MahtraDR** [comment]
@asechrest writes the best bug reports. :)

**Comment by rpherbig** [comment]
> @asechrest writes the best bug reports. :)

This +1 ! ❤️
