### ISSUE TITLE
[meta] Can I get permissions to assign labels to issues?

### ISSUE THREAD

**Issue by MahtraDR** [rpherbig/dr-scripts#5513]
Hi @rpherbig I see this kind of thing happened back in 2017, where JayRyan had perms for this.

Would it be possible to do that today? It'd be a lot easier to track down issues if we could group them by script. I'm happy to do it once, and for the perms to be removed again if you'd prefer.

**Comment by KatoakDR** [comment]
Probably a good motivator for us to do https://github.com/rpherbig/dr-scripts/issues/4888 so that once we're part of an organization then it should be easier to assign people roles/teams

**Comment by rpherbig** [comment]
@MahtraDR I've invited you to be a collaborator on the repo. As far as I can tell, there's not much granularity with permissions so you're getting a _bunch_ of others, too. https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-user-account-settings/permission-levels-for-a-user-account-repository#collaborator-access-for-a-repository-owned-by-a-user-account

Also, feel free to close any Issues you think should be closed - you no longer need to ping me to close them.

Please be careful :)
