### ISSUE TITLE
Identifying method calls that aren't defined in the script

### ISSUE THREAD

**Issue by asechrest** [rpherbig/dr-scripts#5537]
Not really an issue with DR Lich, just putting it here for some visibility with devs.

As we go through old scripts and remove includes in favor of the common prefixes, one of the challenges is making sure we've actually identified all the methods that need a prefix. And testing the script can sometimes fool you into thinking you've captured them all when you've actually missed one and the `-common` is just already running in the background.

It occurred to me that there may exist an IDE that will identify visually those method calls wherein the method is not defined within that script file. Or some other visual solution that would help us ensure that we haven't missed a prefix, because if we have, it's nearly always a script-breaking bug.

Thoughts?

@rpherbig @MahtraDR @KatoakDR

**Comment by rpherbig** [comment]
I'm not aware of any such IDE.

> And testing the script can sometimes fool you into thinking you've captured them all when you've actually missed one and the -common is just already running in the background.

This would only happen if the script still has the `include` in it, right? If so, I kind of feel like the best way to do this is just to pick one common file, maybe one function, and fix it everywhere. Once all functions in a common file have been moved over, we can remove all includes of that common file.

Done all at once, I think it's mostly a find/replace problem and shouldn't take too much actual dev time. And once we're done, we can flag all includes in reviews as a problem.

**Comment by MahtraDR** [comment]
After some googling last night, It looks like Robucop would do this. Or other linters. I'll play with this today. I'm just struggling to stop using vim as my editor. :)

**Comment by asechrest** [comment]
This is now SOLVED. I found a `sed` script to pull all method names from a Ruby file. @MahtraDR took that and ran with it, building out a full Visual Studio Code-based solution to highlight all methods for each common file.
