### ISSUE TITLE
Dual Axe Repair Bug

### ISSUE THREAD

**Issue by jayRyan24** [rpherbig/dr-scripts#555]
While trying to get my stuff repaired, I ran into an issue with using a hand axe and a battle axe. The Battle Axe glanced, but the script kept trying to stow hand.axe. Both of them are located in my item list. 

Here's my YAML:
http://pastebin.com/LERt1Ex7

Here's the LOG:
http://pastebin.com/pmx71MaQ

**Comment by rpherbig** [comment]
I don't see anything obvious that would cause this. Has it happened to you again since filing this issue?

@rcuhljr Any thoughts?

**Comment by rpherbig** [comment]
We've been poking around at `equipmanager`, so it wouldn't hurt to try again.
