### ISSUE TITLE
common-items - add messaging for plate armor goggles

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#5557]
**remove my goggles
You carefully remove your metal-framed goggles from your eyes.
wear my goggles
You carefully arrange a pair of metal-framed goggles on your eyes so that it accents your features.**

app goggles quick
The metal-framed goggles are plate armor.

The goggles look like they offer protection for the following areas:

    right eye
    left eye

You feel certain that a pair of metal-framed goggles appear to impose trivial (2/15) maneuvering hindrance and insignificant (1/15) stealth hindrance, offering:
    high (7/15) protection and very great (12/17) damage absorption for puncture attacks.
    very high (8/15) protection and very great (12/17) damage absorption for slice attacks.
    good (5/15) protection and very great (12/17) damage absorption for impact attacks.
    very good (6/15) protection and good (7/17) damage absorption for fire attacks.
    moderate (4/15) protection and good (7/17) damage absorption for cold attacks.
    low (2/15) protection and fair (5/17) damage absorption for electrical attacks.

If you were only wearing a pair of metal-framed goggles, your maneuvering would be barely hindered (1/14), and your stealth would be barely hindered (1/14).
But considering all the armor and shields you are wearing or carrying, you are currently somewhat hindered (6/14), and your stealth is fairly hindered (5/14).

You are certain that the metal-framed goggles are rather reinforced against damage (11/18) and is practically in mint condition (91-99%).

The metal-framed goggles are made with metal.
You are certain that the metal-framed goggles weighs exactly 35 stones.
You are certain that the metal-framed goggles are worth exactly 2772 Kronars.
Roundtime: 5 seconds.

**Comment by asechrest** [comment]
I got this one. Discussed in Discord.
