### ISSUE TITLE
Ranger-Companion not unpausing scripts when out of milk

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#5563]
**Ranger-Companion fails to restart all scripts if it can't find milk in your inventory**

A baby wolf begins to whimper.
--- Lich: t2 paused.
--- Lich: sanowret-crystal paused.
--- Lich: hunting-buddy paused.
--- Lich: combat-trainer paused.
The onyx gargoyle begins to advance on you!
The onyx gargoyle is still a distance away from you and is closing steadily.
You've gained a new rank in your ability to parry.
You flourish your cutlass about in a butterfly pattern to test its balance.
The onyx gargoyle closes to pole weapon range on you! 
[ranger-companion]>stow left
Stow what?  Type 'STOW HELP' for details.
[ranger-companion]>get my milk
What were you referring to?
[ranger-companion]>signal companion to sleep
You signal to your baby wolf.
The baby wolf wanders off to find a quiet place to sleep.
[ranger-companion]>signal companion to sleep
Your companion is not here.
[ranger-companion]>signal companion to hunt
Your companion is not here.

--- Lich: ranger-companion has exited.

**Comment by mwest152** [comment]
In the odd chance someone else runs into this, restock seems to work for milk from Arthe Dale.

restock:
  super_cool_milk:
     name: milk
     room: 19240
     price: 18
     size: 1
     stackable: false
     quantity: 3

**Comment by asechrest** [comment]
I see the issue with the script and can offer a fix perhaps this evening.

**Comment by mwest152** [comment]
Nice!  It seem like it wasn't too much to change, but i didn't want to risk it.  I break scripts looking at the wrong.
