### ISSUE TITLE
Autostart script adding sometimes not persistent

### ISSUE THREAD

**Issue by asechrest** [rpherbig/dr-scripts#5603]
While testing #5601 and relogging multiple times with `;tdps` and `;drinfodump` (my custom testing script for version checks and DRStats dump) _recently_ added to autostart, I noticed that these two scripts were being removed from my autostarts. I have recreated the issue 5 times now by simply logging out and back in multiple times. Sometimes both scripts are removed from autostart after a single relog. Sometimes it takes 6 relogs. I've recreated the issue on both the PR versions of bootstrap/dependency/drinfomon and on the current versions, so it's confirmed unrelated to the #5601.

Interestingly, it only seems to remove one or both of these two recently added autostart scripts. It never removes the ones that have been there for a long time, like textsubs, roomnumbers, etc.

Per @BinuDR, folks have seen this before in the past. Example:

Adding `;tdps` to autostart.
```
>;e autostart('tdps')
--- Lich: exec1 active.
--- Lich: tdps active.
--- Lich: exec1 has exited.
Total Ranks Gained: 15976
TDPs Gained from Ranks: 14062
TDPs Gained from Circling: 11702
Total TDPs Gained: 25764
Total TDPs spent: 25491
TDPs remaining: 273

TDPs spent per stat
     Strength : 2907             Reflex : 4272
      Agility : 3696           Charisma : 312
   Discipline : 4179             Wisdom : 4485
 Intelligence : 3540            Stamina : 2100
--- Lich: tdps has exited.
>;e echo(list_autostarts)
--- Lich: exec1 active.
[exec1: ["drinfomon", "textsubs", "roomnumbers", "log", "spellmonitor", "tdps"]]
--- Lich: exec1 has exited.
```

Six relogs later:
```
>;e echo(list_autostarts)
--- Lich: exec1 active.
[exec1: ["drinfomon", "textsubs", "roomnumbers", "log", "spellmonitor"]]
--- Lich: exec1 has exited.
>
```

**Comment by asechrest** [comment]
@MahtraDR This may be cleared up with Lich5? I haven't experienced it since converting. You?

**Comment by MahtraDR** [comment]
Now you mention it. I have never noticed a failure to write in lich5. I'll test aggressively later.

**Comment by MahtraDR** [comment]
@asechrest Still have never seen an issue with lich5. 

Close?
