### ISSUE TITLE
Create script to set up a new character

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#562]
Some ideas:

- [x] ;go2 tobb to buy a skinning knife
- [x] Get bundling rope from Falken
- [x] Get gem pouch from appraiser
- [x] Buy lockpick ring and fill it with lockpicks (note, very expensive, so an advanced user kind of thing)
- [x] Buy an apprentice blacksmithing book for Scholarship training
- [x] Cambrinth ring (since circle 1 can't charge the default armband)
- [x] Crafting tools if they are selected? Logbook (and rub it), deeds, ...?
- [x] Buy quiver and arrows/bolts
- [x] Buys armor, weapons
- [x] Theurgy supplies
- [x] Get a runestone if Sorcery is going to be trained (or at least message that the user needs to find one)
- [x] Toggle expbrief
- [x] Set spell stance (115 115 70?)
- [x] Spell recognition
- [x] Adjust items to be in the right slot (e.g. shield, bundle)
- [x] Zills? (and chamois cloth for cleaning)
- [x] Join a guild?
- [x] Learn spells?
- [x] Spend your initial 600 TDPs

What else?

**Comment by rpherbig** [comment]
Join a guild?

Learn spells?

**Comment by jandersson** [comment]
Maybe learn some outdoorsmanship? A base amount is needed to train other things like theurgy (with the script) and mech lore

**Comment by jandersson** [comment]
Spend your 600 TDP's

**Comment by rpherbig** [comment]
Get gem pouch

**Comment by rpherbig** [comment]
Buy lockpick ring

**Comment by rpherbig** [comment]
Buy an apprentice blacksmithing book for Scholarship training.

Crafting tools if they are selected?

**Comment by rpherbig** [comment]
Also fa2a3678df69f44b5f6f4b8b0ce42d9b8fb716ee and e6df211d42009bc23c6b457427187229e285d1ed
