### ISSUE TITLE
Combat Trainer missing weather messaging

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#5649]
I'm pretty sure this is missing messaging.  This happened hunting in Cabalists.
---------------------------------
[combat-trainer]>weather

You glance outside.
It is completely overcast.

[combat-trainer: message: It is completely overcast.]

[combat-trainer: message: You glance outside.]

[combat-trainer: checked against [/inside/i, /You glance up at the sky./i]]

[combat-trainer: for command weather]

**Comment by asechrest** [comment]
Easy fix for later this evening when I'm home. Thanks for the report.

**Comment by asechrest** [comment]
Closed via #5652

**Comment by asechrest** [comment]
Closed via #5652
