### ISSUE TITLE
Steal Script Crossing locksmith bug/general stealing bugs

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#5651]
When stealing from the Crossing Locksmith, slim lockpicks can be stolen as "SLIM lockpick" but once you have it, there is no longer a "slim" adjective, and the script is unable to handle getting rid of it and it ends up piling up in your bags.  

[Ragge's Locksmithing, Salesroom]
Through the mingled gloom of shadows and tobacco smoke, you can barely make out the vague outlines of some rather sinister looking figures as they skulk in and out of a room to the east.  On the heavily scarred counter, a single oil burning lamp provides the only pool of light in the room, which radiates only a few feet outward before being swallowed by the shadows.
You also see the locksmith Ragge, a bookstand with a catalog on it, a large barrel and a heavily scarred counter.
Obvious exits: out.

Room Number: 19125

Mapped exits: go shadows
[go2: travel time: 0:00:01]

--- Lich: go2 has exited.

[steal]>hide

You melt into the background, convinced that your attempt to hide went unobserved.
Roundtime: 5 sec.

[steal]>steal slim lock 

Moving stealthily, you manage to grab a slim lockpick right from underneath the locksmith Ragge's very nose.
You learned acceptably from this theft.
Roundtime: 5 sec.

Your feet are dripping with water.  Pools of it are forming all around you.

HR> 
[steal]>put my slim lock in barrel

You come out of hiding.
What were you referring to?

[steal]>drop my slim lock

What were you referring to?

> 
[steal]>stow right

You put your lockpick in your backpack.

- - - -

glance
You glance down to see a slim lockpick in your right hand and nothing in your left hand.

> 
tap my slim lockpick
I could not find what you were referring to.

> 
tap my lockpick
You tap a slim lockpick that you are holding.

**Comment by drlichdependency** [comment]
Thanks for the report. Do any of other lockpick types exhibit the same behavior? Or is it just slim lockpicks that lose the ability to reference by the adjective?

**Comment by asechrest** [comment]
Thanks for the report. Is this only on slim lockpicks? Do any others lose the referenceable adjective?

**Comment by mwest152** [comment]
> Thanks for the report. Is this only on slim lockpicks? Do any others lose the referenceable adjective?

I'll investigate and get back to you.

**Comment by mwest152** [comment]
Adjectives dont stick on the ordinary or stout either.   Looks like maybe the adjective space was left open so you could buy the color ones.   I looked at base-stealing and the lockpick ring and the slim lockpick are the only items on it. 

read cat
You take a few moments to glance through the catalog, which lists Ragge's inventory.  Included in his catalog are the following:

Page 1 - Lockpicks and Lockpick Rings
Page 2 - Color List

A short note at the bottom advises you to read the individual pages before placing an order.

read page 1
read page 2
You open the book up to page 1 and notice

Lockpicks and Lockpick Rings:
Custom colors available.  See page 2 for colors.

 Ordinary Lockpick
 Stout Lockpick
 Slim Lockpick
 Lockpick Ring

You open the book up to page 2 and notice

Color List:

  Tarnished                       Black
  Grey                         Metallic
  Dull

order ordinary lockpick
Ragge sighs.  "Despite the rarity of this lockpick, I'm prepared to offer it to you for 125 kronars."

> 
off 125
Ragge hands over your lockpick.

tap my lock
You tap an ordinary lockpick that you are holding.

> 
tap my ordinary lock
I could not find what you were referring to.


tap my dull lock
You tap a stout dull lockpick that you are holding.

**Comment by asechrest** [comment]
Ok, I've got an idea for this I'll try to work on that isn't a hack and may help as a last resort failsafe if the DR parser confounds Lich's attempts to reference an item.

**Comment by mwest152** [comment]
Similar issue in the general store with small sacks

[Berolt's Dry Goods, Showroom]
Rough walls and floors covered with a gritty layer of dirt attest to the constant traffic in what must be one of the more popular establishments in town.  Shelves and counters crowd together, displaying all manner of equipment for a rugged lifestyle in an orderly, if dustridden manner.  Berolt, the proprietor, keeps a close eye on business, but still manages a quick, hearty laugh at a rather bawdy joke from a coarse-looking character who is obviously a regular visitor here.
You also see a cylindrical iron tinderbox, a coin purse, a coin purse, a coin purse, a coin purse, a coin purse, a coin purse, a coin purse, a coin purse, a rough-hewn table with a catalog on it, a scarred doorway and the merchant Berolt.
Obvious exits: out.

Room Number: 8265

Room Exits: go doorway

Mapped exits: go scarred doorway
[go2: travel time: 0:00:01]

--- Lich: go2 has exited.

[steal]>hide

You melt into the background, convinced that your attempt to hide went unobserved.
Roundtime: 4 sec.

[steal]>steal small sack in catalog

Moving stealthily, you manage to grab a small sack right from underneath the merchant Berolt's very nose.
You learned acceptably from this theft.
Roundtime: 5 sec.

[steal]>drop my small sack

You come out of hiding.
What were you referring to?

[steal]>stow right

You put your sack in your backpack.

> 
tap small sack
I could not find what you were referring to.

> 
tap my sack
You tap a small sack that you are holding.

>

**Comment by mwest152** [comment]
I know with the release of burgle this script has kind of fallen out of popularity, but i still use it to train stealth and thievery on my f2ps with long timers.  Figure I can keep adding issues as I find them.  I started logging so i can start posting details, but here are the items that I've built up so far with issues, some similar to the locksmith issues.

  - get2 764
  - multi 6,get my lockpick,put my lockpick in urn
  - multi 6,get my potion,put my potion in urn
  - multi 6,get my charm,put my wreath in urn
  - multi 6,get my wreath,put my wreath in urn
  - multi 6, get my sack,put my sack in urn
  - multi 6, get my cigar,put my cigar in urn
  - multi 6, get my strings,put my strings in urn
  - multi 6, get my lockpick ring from my back,put my lockpick ring in urn
  - multi 5, get my flute case,put my flute case in urn
  - multi 5, get my engagement ring,put my engagement ring in urn

**Comment by mwest152** [comment]
[The True Bard D'Or, Fine Instruments]
This is THE shop for Bards.  Famed far and wide for its range of instruments and things bardic, customers travel far just to shop here and to exchange tunes and to hear the latest gossip.  The walls are covered with dozens of music-making devices and glass counters hold strings and reeds and straps.  Rows of pigeonholes hold sheet music from a hundred cultures and more.  A backroom serves as a performance hall and a place for traveling bards to meet and catch up on goings-on.
You also see the apprentice, a polished lunat counter with a catalog on it and a dark curtain.
Obvious exits: out.

Room Number: 19078

Room Exits: go dark curtain

> 
Mapped exits: go backroom, go dark curtain

> 
[go2: travel time: 0:00:02]

--- Lich: go2 has exited.

[steal]>hide

You melt into the background, convinced that your attempt to hide went unobserved.
Roundtime: 3 sec.

HR> 
[steal]>steal case of silver in catalog

...wait 1 seconds.
HR> 
[steal]>steal case of silver in catalog

Moving stealthily, you manage to grab a silver flute case right from underneath the apprentice's very nose.
You learned acceptably from this theft.
Roundtime: 5 sec.

HR> 
Gained: Thievery(+1), Stealth(+1)

HR> 
[steal]>drop my case of silver

You come out of hiding.
What were you referring to?

> 
--- Lich: go2 active.

[go2: ETA: 0:00:01 (5 rooms to move through)]

[go2]>out

You go out.

[The Crossing, Asemath Walk]
You stand before a sign in the shape of a giant lute, painted in red and gilt and inlaid with ivory and jet, with florid script proclaiming the virtues of the True Bard d'Or, the Crossing's finest purveyor of high-quality instruments for bards, aesthetes and amateurs alike.  Dashing, gaily-clad figures stream in and out of the shop, lutes slung over shoulders or pipes clasped under arms.  A haunting tune, at once both exhilarating and melancholic, emanates from the doorway.  
Obvious paths: north, east, south, west.

Room Number: 783

Room Exits: go shop

> 
Mapped exits: go bards shop

[go2]>south

You go south.

[The Crossing, Asemath Walk]
The crowd here is boisterous, composed of students, teachers, and seekers of all kinds.  Some head south to the famed taproom of the Half Pint Inn, others appear to have already enjoyed the libations there to the dregs and are heading back for study.  The inn to the south and the visitors to the High Temple to the southeast contribute to the brisk flow of people to and from the Academy.  
Obvious paths: north, south.

Room Number: 784

> 
[go2]>south

You go south.

[The Crossing, Asemath Walk]
Clerics, academics and carousers all are apparent here, headed throughout town on different courses.  The windows and terraces from the back of the two-storied Half Pint Inn face the street from the south, while to the east is the side of the cleric's shop.  Smooth paving stones, pale grey with dark grey borders, have been laid to coordinate with the approaches to the High Temple.  
Obvious paths: north, east, west.

Room Number: 735

> 
[go2]>east

You go east.

[The Crossing, Alamhif Trace]
A constant stream of townsfolk and outlanders file past you but the mix is not your usual pastiche of rag-tag traders, bare-chested barbarians, indolent bards and assorted laborers.  Here most people speak in serene tones or peer at you benevolently from behind cowls of the cleric's calling.  Many cluster around Brother Durantine's Cleric Shop, which hugs the north side of the road.  A monk pauses in the shadows cast by the High Temple tower to the southwest before continuing his journey.
You also see Forest Warden Hengwild.
Obvious paths: east, south, west.

Room Number: 734

Room Exits: go shop

> 
Mapped exits: go cleric shop

[go2]>go shop

[Brother Durantine's Shop]
In this small adjunct to a local order of monks, Brother Durantine offers a variety of holy items and related things.  An assortment of holy symbols may be had as well as blessed waters, candles and ritual vestments for any who wish to serve their own religious needs.  Cool stone walls decorated with scenes from the life of the founder of the order doing various good deeds provide inspiration to all who see them.
You also see a dimly-lit storeroom, a plain counter with several things on it and a private room.
Obvious exits: out.

Room Number: 19073

Room Exits: go room, go store

> 
Mapped exits: go private room, go dimly-lit storeroom

[go2: travel time: 0:00:01]

--- Lich: go2 has exited.

[steal]>stow right

You put your case in your backpack.

**Comment by MahtraDR** [comment]
I'm inclined to close this. This script is old, and not much used anymore. burgling is just such an effective way to train... @mwest152 @asechrest ?

**Comment by mwest152** [comment]
I was using stealing to pick up slack on my f2ps with longer timers, but I haven't even really done that in a while.  This was a pretty awesome script though.
