### ISSUE TITLE
Meraud Commune in Combat-Trainer

### ISSUE THREAD

**Issue by drboldwin** [rpherbig/dr-scripts#569]
**Add to @skill_map:**
'Meraud' => 'Theurgy'

**Add to execute(game_state):**
when 'Commune Meraud'
      if DRSkill.getrank('Theurgy') >= 300 || game_state.npcs.empty?
        pause 1
        fput "stow #{GameObj.right_hand.noun}" if GameObj.right_hand.name != 'Empty'
        fput "stow #{GameObj.left_hand.noun}" if GameObj.left_hand.name != 'Empty'
        fput "get #{$settings.water_holder}"
        fput "sprinkle #{$settings.water_holder} on #{checkname}"
        fput "stow #{$settings.water_holder}"
        fput "get #{$settings.flint_lighter}", 'You get a', 'You are already'
        fput 'get incense', 'You get', 'You are already'
        fput 'light my incense with flint' # get messaging
        waitrt?
        fput "wave incense at #{checkname}"
        fput 'snuff incense'
        fput 'stow incense'
        fput "stow #{$settings.flint_lighter}", 'You put your', 'Stow what'
        pause 1
        bput('commune meraud', 'Nothing happens.', 'you have attempted a commune too recently', 'You close your eyes and concentrate, letting your mind still and feeling your breathing grow shallow')
        fix_standing
        EquipmentManager.instance.wield_weapon(game_state.weapon_name, game_state.weapon_skill)
	  end

**FOR YAML ONLY:**
Can now add in training_abilities:
  Commune Meraud:
    :check: Theurgy
    :cooldown: 1800

**Comment by drboldwin** [comment]
Can go through and change fput's to bput's before push if needed just need to gather all possible messages. - Runs as is.

**Comment by drboldwin** [comment]
There is one thing I wasn't sure on how to do so if you could add perhaps a stance setting before hand that does evasion/shield (since you will be weaponless during the process) and then goes back to whatever stance would have been active when it's over.

**Comment by rcuhljr** [comment]
I'll just make it so you get your weapon back out, then commune.

**Comment by drboldwin** [comment]
even better

**Comment by rpherbig** [comment]
@rcuhljr Are you still working on this?

**Comment by rcuhljr** [comment]
I forgot about .

**Comment by rcuhljr** [comment]
In place, needs tested.
