### ISSUE TITLE
safari rooms 2

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#572]
safari rooms with right numbers
9211
9212
9213
9214
9236

9215
9216
9217
9218
9219
9220

9223
9224

9230
9231
9232
9233
9234
9235

**Comment by rpherbig** [comment]
@xtremenerdrage Are these in addition to the existing rooms, or replacing them?

**Comment by rcuhljr** [comment]
replacing, I'll fix it.
