### ISSUE TITLE
Higher level climbing

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#573]
Go up and down the wall of undergondola, kill 60 seconds, repeat?

**Comment by UFTimmy** [comment]
FWIW, even at 900+ ranks of athletics, I found it worth it to do a circuit of many of the rooms in the undergondola. They taught an appreciable amount, and you're waiting 60 seconds anyway.

I have a Genie script with TF room numbers, so it won't help much, but from this map:

https://elanthipedia.play.net/mediawiki/index.php/RanikMap65

The climb pit room teaches the best, but I'd always do the embankment climb from by gargs, undergondola climb, climb the pit, go down to blade spiders, climb there, swim up the river, wait by the entrance to Gargs, and collect until a minute has passed, and then repeat.

**Comment by rcuhljr** [comment]
Add some of the extra rooms.
