### ISSUE TITLE
[script] [combat trainer] Error looting scrolls

### ISSUE THREAD

**Issue by MahtraDR** [rpherbig/dr-scripts#5754]
```
[combat-trainer]>stow \b([\w\'\"\-]+) (scroll|vellum|bark|tablet|parchment|roll|papyrus)\b

Stow what?  Type 'STOW HELP' for details.
> 
[combat-trainer]>stow \b([\w\'\"\-]+) (scroll|vellum|bark|tablet|parchment|roll|papyrus)\b
```

Obviously the scroll_nouns regex line from https://github.com/rpherbig/dr-scripts/pull/5747

but there is no `get_data('items').scroll_nouns` in CT, so I don't know how it gets there. I'm just heading to bed, will look more tomorrow.

@asechrest :)

**Comment by asechrest** [comment]
Closed via #5755
