### ISSUE TITLE
Correct empty mine messages

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#576]
This is not an empty mine

>prospect
You feel fully rested.
>
You see evidence of mineral deposits and are certain a scattering of resources (0/5) remains to be found.
This area is composed of alluvial rock layers.
Studying the geology, you are certain that continued mining will be quite safe.
You are certain that dolomite can be mined here.
You are certain that lumium can be mined here.
A diagram on the wall shows the location of additional resources still available for mining.
Miners stand ready to trade resources in for deeds.  Just PUSH any mined up stone or metal, and they'll take care of the rest.
Roundtime: 8 sec.

This is an empty mine

>prospect
You see evidence of mineral deposits and are certain a scattering of resources (0/5) remains to be found.
This area is composed of alluvial rock layers.
Roundtime: 8 sec.

**Comment by xtremenerdrage** [comment]
This is also NOT an empty mine

[mine]>prospect careful
You carefully scan the area and look for ways to excavate additional material.  Your analysis has revealed no additional resources to be unearthed here.

**Comment by xtremenerdrage** [comment]
this is the prospect careful of an empty mine

>prospect mine careful
You come out of hiding.
You see evidence of mineral deposits and are certain a scattering of resources (0/5) remains to be found.
This area is composed of alluvial rock layers.
Roundtime: 8 sec.

**Comment by rcuhljr** [comment]
Should be fixed.
