### ISSUE TITLE
traveling from orc_warcats to crossing

### ISSUE THREAD

**Issue by Kekahunadr** [rpherbig/dr-scripts#579]
every time i try it i get stuck in haven west road, no idea why or what and maybe even my fault??

**Comment by rpherbig** [comment]
@rcuhljr Any thoughts? I don't think I can investigate this one as F2P.

**Comment by Kekahunadr** [comment]
I am not f2p lol

**Comment by rcuhljr** [comment]
@rpherbig is F2P though.

**Comment by jandersson** [comment]
Riverhaven ring road west?

**Comment by wscherer420** [comment]
This issue i believe was new night descriptions for several rooms along that road in Riverhaven.  I believe its been taken care of though.  I'm not having that issue anymore.

**Comment by Kekahunadr** [comment]
It seems to be fixed now thank you

**Comment by jandersson** [comment]
I remapped some of the rooms in Haven a few days ago on ring road west. There is still a few rooms by the west gate that map to completely different rooms based on day/night (and their wayto's are pointing to one or the other).
