### ISSUE TITLE
Not untying tool from Belt.

### ISSUE THREAD

**Issue by jayRyan24** [rpherbig/dr-scripts#580]
Unsure why it works sometimes and sometimes it doesn't, but here's an example of it not working. 

Log:
http://pastebin.com/tW9aPg9u

YAML:
http://pastebin.com/ByDeSENA

**Comment by rpherbig** [comment]
Is mining the only time it fails to tie/untie?

Has mining ever tied/untied for you in the past?

**Comment by jayRyan24** [comment]
It seems to always tie/untie during mining. It will check if it's stowed, if not, it defaults to the tie option and then remembers. I believe this is an issue with go2, it seems to have STOWed left before climbing. So, I believe Mining/Mining Buddy, whichever supports this, needs to be sure to put the shovel away before attempting to go to another place. When I get home from work, I'll double check the log and see how it pulled it off to begin with and repost that here.

**Comment by rcuhljr** [comment]
Mining buddy should retie a tool at the end of all mining if it untied to begin with, regardless of where the tool was stored in the interim (due to go2 emptying hands).

**Comment by rpherbig** [comment]
Mine.lic also attempts to get the implement, but does not obey tied/worn.

**Comment by rcuhljr** [comment]
Yeah, mine assumes mining-buddy or the player has already gotten the tool into an accessible state.

**Comment by rpherbig** [comment]
I would expect getting the tool to be a responsibility of `mine` (i.e. in case you wanted to use a shovel for some things and pickaxe for others). What if your implement doesn't fit in the stow location (because it is tied)?

**Comment by rcuhljr** [comment]
Stow fails and everything works fine because you still have the tool in hand.

**Comment by rpherbig** [comment]
I don't feel confident a failed stow will always be without consequence. It may also lead to problems like in #589, I believe some ropes you need both hands free to climb?

**Comment by rcuhljr** [comment]
I haven't run into any climbs you can't do with things in hand. The other issue seems to be caused by either something going wrong with the retie logic, which is unrelated to stowing, or stopping mining manually instead of letting mining buddy finish and not putting away the shovel on the tie strap.
