### ISSUE TITLE
Using Rucksacks for Tied Weapons in Combat

### ISSUE THREAD

**Issue by jayRyan24** [rpherbig/dr-scripts#581]
Combat-Trainer needs to support the use of Tied weapons to Rucksacks. Rucksacks can tie up to two weapons/items. The downside to Rucksacks is that they require you to be out of engagement to tie and untie.

**Comment by rpherbig** [comment]
Is the only problem that you need to retreat first? Or are there multiple things that need to change?

**Comment by jayRyan24** [comment]
Yeah, you just need to retreat. The logs tell you that you "swing your rucksack around to the front and tie/untie item", so that's the issue. It's how/where it removes the item. It just requires that you aren't in melee (not sure about pole), I can check this.

**Comment by rpherbig** [comment]
Can you get us the messaging for a failed tie/untie? It'll be easy enough to add a check for that and retreat if needed.

**Comment by rpherbig** [comment]
tie axe to ruck
You are a little too busy to be worrying about doing that!

untie
same message

**Comment by rpherbig** [comment]
Out of combat:
- tie - `Swinging your oilcloth rucksack over one arm and moving it around to the front of your body, you tie your light spear to it with the use of the straps.  When you finish, the rucksack swings back into place upon your back.`
- untie - `Swinging your oilcloth rucksack over one arm and moving it around to the front of your body, you untie your light spear from it.  When you finish, the rucksack swings back into place upon your back.`

**Comment by rpherbig** [comment]
@rcuhljr Any thoughts on how to do this for untie?

**Comment by jayRyan24** [comment]
Hm? I think retreat out of range and use the "your body, you untie your" and "your body, you tie your" to determine if successful.

**Comment by rpherbig** [comment]
I meant in the code (sorry for the confusion). There is `stow_helper` for tie, to which it is easy to add another special case. But untie is a bit more complicated.

**Comment by rpherbig** [comment]
Closing - this can cover tieing, and #637 can cover untieing.
