### ISSUE TITLE
Ignoring certain items from base-stealing.

### ISSUE THREAD

**Issue by jayRyan24** [rpherbig/dr-scripts#582]
There are some items, such as cauldrons, that are a bit cumbersome to steal. They don't always fit in bags, or fill them up so quickly that you run around doing nothing with hands full. Possibly there needs to be a way to either ignore certain items on the list, or to not bag certain items on the list. I know you can not stow while stealing, but sometimes you want some items and sometimes you don't.

**Comment by rpherbig** [comment]
The 'id' field seems to be the best (unique) way to reference items. Do you have any objections to a list of IDs as the override list? cc @rcuhljr

**Comment by jayRyan24** [comment]
I don't personally, whatever is the easiest. Honestly, this was an issue with Kenahuna that we solved by removing it from the list. I haven't really given it a whole lot of thought outside of "we should be able to not steal something".

**Comment by rcuhljr** [comment]
I'd just do a list of things to ignore from stealing, id is appropriate.

**Comment by Kekahunadr** [comment]
Kekahuna here, its still stealin the cauldron :( for now i have a script to drop it when it dont fit but when i ferget to start script it really jams me up lol

**Comment by rcuhljr** [comment]
`dont_steal_list:` added, list of ids.

**Comment by Kekahunadr** [comment]
Thanks

**Comment by Kekahunadr** [comment]
Now where do I find the list of ID's lol

**Comment by rcuhljr** [comment]
`base-stealing.yaml`

**Comment by Kekahunadr** [comment]
Thanks again
