### ISSUE TITLE
workorders: alchemy bug 

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#5832]
I honestly don't really know a solution to this one, but I walked away for a bit and might have been doing this for too long.

You lightly tap Redxi on the shoulder.

> 
[workorders]>get my red flower

What were you referring to?

> 
[workorders]>tap my red flower 

You lightly tap Redxi on the shoulder.

> 
[workorders]>get my red flower

What were you referring to?

> 
[workorders]>tap my red flower 

You lightly tap Redxi on the shoulder.

**Comment by MahtraDR** [comment]
This looks like a parser bug to me. Assuming you actually have red flowers in your inventory anyway.

**Comment by mwest152** [comment]
Did not actually have any red flowers on my person.

**Comment by rpherbig** [comment]
There's a bunch of comments related specifically to flowers in `workorders.lic` - https://github.com/rpherbig/dr-scripts/blob/master/workorders.lic#L503
