### ISSUE TITLE
[script][crossing-training] - Using research to train does not work

### ISSUE THREAD

**Issue by asechrest** [rpherbig/dr-scripts#5838]
Reported by RalthasDR in Discord.

When using `crossing-training`, with yaml setting `use_research: true`, the script calls Gauge Flow with 0 mana, which fails. This is because it hard-codes the spell cast and feeds in an incomplete hash that doesn't have the mana specified:

```ruby
until DRSpells.active_spells['Gauge Flow'] > 20
      cast_spell({ 'abbrev' => 'GAF' }, nil)
      check_nerves
      pause 2
    end
```

**Comment by Raykyn55** [comment]
until DRCA.cast_spell?(get_data('spells').spell_data['Gauge Flow'], @settings)
 end

**Comment by asechrest** [comment]
> until DRCA.cast_spell?(get_data('spells').spell_data['Gauge Flow'], @settings) end

I just wonder if pulling a base setting, as opposed to a specified setting, is the right approach. Seems logical that some of the details should be able to be specified by the user, so that if nothing else, the user can specify simple things like the mana to use, instead of accepting the 5 mana base minimum.

**Comment by Raykyn55** [comment]
Could run buff gaf, or buff research, instead of cast_spell. Think theres something in base talks about a research waggle.

**Comment by Raykyn55** [comment]
until DRSpells.active_spells['Gauge Flow'] > 20
      unless @settings.waggle_sets['research']
        DRCA.cast_spell?(get_data('spells').spell_data['Gauge Flow'], @settings)
      else
        wait_for_script_to_complete('buff', ['research'])
      end
      check_nerves
      pause 2
    end

**Comment by MahtraDR** [comment]
This looks like a good first issue for someone. The code suggestion in https://github.com/rpherbig/dr-scripts/issues/5838#issuecomment-1159586164 probably works as is. Just needs a bit of testing.

**Comment by vtcifer** [comment]
100% on the good first issue, several options for improvement.

Another mitigation is to add `gaf` with a long enough `recast:` in `town-training` waggle `crossing-training` uses.

**Comment by MahtraDR** [comment]
Closing as stale. Nobody's stepped up.
