### ISSUE TITLE
Turn off looting

### ISSUE THREAD

**Issue by xtremenerdrage** [rpherbig/dr-scripts#585]
Would it be possible to make an syntax to turn off looting?

Only time I come across this issue is when hunting in big groups ie invasions etc. Seems rude to loot everything in a huge group

**Comment by rpherbig** [comment]
One option is simply to have a true/false for whether or not to loot.

We could also have a `loot` setting (with a default of `goods`) so the user can specify the type of looting they want (see https://elanthipedia.play.net/mediawiki/index.php/Loot_command). What do you think?

**Comment by xtremenerdrage** [comment]
I think both options would be nice. Im mainly concerned about hunting in large groups ie invasions or events. But I can see where the loot setting would also be useful for different characters or splitting loot

**Comment by rpherbig** [comment]
Would you expect this loot setting to also override whether or not you skin?

**Comment by xtremenerdrage** [comment]
I think you can already turn off skinning with the skinning syntax.

**Comment by rpherbig** [comment]
Sorry, let me clarify. The most straightforward way to implement this is to turn off all looting logic, which would include skinning. That is, if you turn off looting, it would also turn off skinning, regardless of the skinning-specific settings.

Is that acceptable, or would you prefer something more fine-grained?

**Comment by rpherbig** [comment]
Another question: it looks like looting and stowing of loot are two separate operations. Which are you expecting to be toggleable (or both)?
