### ISSUE TITLE
crafting_training_spells:

### ISSUE THREAD

**Issue by SaphiaFae** [rpherbig/dr-scripts#5858]
New trader here. My various waggle sets ignore starlight spells if there isn't sufficient starlight to cast them. Unfortunately crafting_training_spells: doesn't do this and repeatedly attempts to cast the same failed spell over and over. I only have one warding spell (TRC) so I have to # it out of my setup to craft.

**Comment by MahtraDR** [comment]
Hi, so... `starlight_threshold` is only for combat trainer. That functionality doesn't exist anywhere else at the moment. In light of this, you would be better off using MAF for Warding training perhaps? 

I don't think any of the folks currently actively developing play traders, alas...

**Comment by SaphiaFae** [comment]
Ok thanks. I'm waiting to get a spell slot.

**Comment by MahtraDR** [comment]
I just glanced at the trader spell charts. If you're just starting out, you get MAF for free until level 10. I'd use that to start, then switch to using NON when you have the spell slots.
