### ISSUE TITLE
Hunting Buddy Always Goes to TGSE

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#586]
When hunting buddy detects that your hunting session is over, it walks you over to TGSE. Is it possible to have this walk to our safe room instead? I think this would also help decouple hunting-buddy from the Crossing area, making it usable anywhere zones and safe rooms are defined

**Comment by kamarcum** [comment]
I'm in favor of that. I created #587 for @rcuhljr or @rpherbig to make if they agree.

**Comment by rpherbig** [comment]
Fixed in 652fd9fa43bc94fc5e27248c492aaa0af5c67fb1
