### ISSUE TITLE
combat-trainer - Multiple Enemy deaths

### ISSUE THREAD

**Issue by drboldwin** [rpherbig/dr-scripts#591]
Currently combat-trainer does not account for the raw power of a Cleric and multiple enemy deaths in the same action (or before a loot).  Could this be adjusted for as it will allow for better functionality with AoE spells.

**Comment by rpherbig** [comment]
The culprit is LootProcess - when combat-trainer loots, it waits for the dead_npcs array to clear. See https://github.com/rpherbig/dr-scripts/blob/master/combat-trainer.lic#L261

**Comment by drboldwin** [comment]
What about doing something like:

  def dispose_body(game_state)
    return if DRRoom.dead_npcs.empty?
	dead_count = DRRoom.dead_npcs.size
	while dead_count > 0
      game_state.mob_died = true
      arrange_mob(DRRoom.dead_npcs.first, game_state)
      if @necro
        if @ritual_type == 'harvest'
          check_thanatology(DRRoom.dead_npcs.first, 'preserve', game_state)
        end
        check_thanatology(DRRoom.dead_npcs.first, @ritual_type, game_state)
        check_skinning(DRRoom.dead_npcs.first, game_state) if ['preserve'].include?(@ritual_type)
      elsif @skin
        check_skinning(DRRoom.dead_npcs.first, game_state)
      end
      while 'and get ready to search it' == bput('loot', 'You search', 'I could not find what you were referring to', 'and get ready to search it')
        pause
        waitrt?
		dead_count --
      end
    pause 0.2 until DRRoom.dead_npcs.empty?
  end

**Comment by drboldwin** [comment]
Obviously this isn't completed but what about setting dead_count like is done in other areas of combat-trainer

**dead_count = DRRoom.dead_npcs.size**

and putting that whole loot process in a while loop

**while dead_count > 0**

decrement dead_count with each pass

**dead_count --** (not sure if thats how ruby does it but you get the idea)

and then just keep that line outside the loop to wait for the room to be empty

**pause 0.2 until DRRoom.dead_npcs.empty?**
