### ISSUE TITLE
typo in base-stealing for monocle

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#5912]
- exceptionally_max: 335
  exceptionally_min: 335
  id: '638'
  **item: steal monocle   <--------------------------------**
  item_in: in catalog
  pawnable: false
  room: 11781
  town: Arthe Dale

HR> [steal]>steal steal monocle in catalog

...wait 1 seconds.
HR> [steal]>steal steal monocle in catalog

Moving stealthily, you manage to grab a steel-rimmed monocle right from underneath the merchant Rufus's very nose.
You learned acceptably from this theft.
Roundtime: 5 sec.

HR> Gained: Thievery(+2), Stealth(+1)

HR> [steal]>drop my steal monocle

You come out of hiding.
What were you referring to?

**Comment by MahtraDR** [comment]
Thanks for the report. It'll get fixed imminently.
