### ISSUE TITLE
scroll search script

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#598]
Request for a script that will search a container and provide an on screen view-able list as well as being able to grab the scroll or scrolls you want and store them in a secondary container.

**Comment by ohbeanz** [comment]
Working on this one... should have a first pass in a day or so.

**Comment by rpherbig** [comment]
I'm really looking forward to it. I'd love to integrate this into lichbot so the 'inventory' command doesn't show 10 copies of 'a yellowed scroll' or such.

**Comment by rcuhljr** [comment]
Developing currently.
