### ISSUE TITLE
Pick.lic: missing messaging

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#5987]
You get a rotting mahogany chest from inside your tapestry carpetbag.
s!> 
[pick]>glance my mahogany chest

It looks like there is 1 trap left on the chest.
Looking more closely you see...
Whoever the alchemist was that made this trap deserves to be gutted.  The clay and vial can only mean this is the infamous shockwave trap!

It looks like there is 1 lock left on the chest.
Looking more closely you see...
A sturdy block of metal, the hole for the key is very wide.  This big lock obviously is meant for a correspondingly large key.
s!> 
[pick]>disarm my mahogany chest identify

**You're in no shape to be disarming anything!**

[pick: *** No match was found after 15 seconds, dumping info]

[pick: messages seen length: 16]

**[pick: message: You're in no shape to be disarming anything!]**

[pick: checked against [/Thanks to an instinct provided by your sense of security/i, /You'll need to have the item in your hands or placed on the ground./i, /lock springs out and stabs you painfully in the finger/i, /An acrid stream of sulfurous air hisses quietly/i, /A stream of corrosive acid sprays out from the/i, /With a sinister swishing noise, a deadly sharp scythe blade whips out the front of the/i, /There is a sudden flash of greenish light, and a huge electrical charge sends you flying/i, /A stoppered vial opens with a pop and cloud of thick green vapor begins to pour out of the/i, /A glass sphere on the seal begins to glow with an eerie black light/i, /Just as your ears register the sound of a sharp snap/i, /Looking at the needle, you notice with horror the rust colored coating on the tip/i, /You barely have time to register a faint click before a blinding flash explodes around you/i, /Moving with the grace of a pregnant goat, you carelessly flick at the piece of metal causing/i, /With a cautious hand, you attempt to undo the string tying the bladder to the locking mechanism/i, /Almost casually, you press on the tiny hammer set to break the tube. The hammer slips from its locked/i, /Nothing happened. Maybe it was a dud./i, /You get a feeling that something isn't right. Before you have time to think what it might be you find.../i, /and emits a sound like tormented souls being freed, then fades away suddenly/i, /has gotten much bigger/i, /and clumsily shred the fatty bladder behind it in the process./i, /liquid shadows/i, /You wiggle the milky-white tube back and forth for a few moments in an attempt to remove it from/i, /With a nasty look and a liberal amount of hurled, unladylike epithets, she wiggles back inside and slams/i, /Not sure where to start, you begin by prying off the body of the crusty scarab, hoping to break it free/i, /You feel like you've done a good job of blocking up the pinholes, until you peer closely to examine/i, /oversized, red, ant-like insects emerge and begin to race across your hands, quickly crawling all over your body/i, /As the stinging winds die down, they leave in their place several very angry vykathi reapers standing right beside you/i, /The liquid contents of the bladder empty, spraying you completely/i, /You experience a great wrenching in your gut and everything goes utterly black/i, /The dart flies through your fingers and plants itself/i, /You just begin to move it when a slight/i, /and sends tiny projectiles slamming into you/i, /fails to reveal to you what type of trap protects it/i, /something to shift/i, /An aged grandmother could defeat this trap in her sleep/i, /This trap is a laughable matter/i, /trivially constructed gadget which you can take down any time/i, /will be a simple matter for you to disarm/i, /should not take long with your skills/i, /with only minor troubles/i, /You think this trap is precisely at your skill level/i, /trap has the edge on you, but you've got a good shot at disarming/i, /odds are against you/i, /You have some chance of being able to disarm/i, /would be a longshot/i, /Prayer would be a good start for any/i, /You have an amazingly minimal chance/i, /You really don't have any chance/i, /You probably have the same shot as a snowball/i, /You could just jump off a cliff and save/i, /A pitiful snowball encased in the Flames/i, /stuffed with dirt rendering the trap harmless/i, /separated harmlessly from their charge/i, /You see a pin and shaft lodged into the frame/i, /been pulled away and whatever was inside, removed/i, /have been bent in such a way that they no longer will function/i, /You see a glowing rune pushed deep within the chest/i, /the dart has been moved too far out of position for the mechanism to function/i, /animal bladder and a disconnected string/i, /indicating the trap is no longer a danger/i, /have been bent away from each other/i, /It seems far enough away from the lock to be harmless/i, /You deem it quite safe/i, /seems a small portion of the trap has been removed/i, /The seal has been pried away from the lid/i, /metallic visage rests a small deflated bladder/i, /indicating a liquid was drained out/i, /as if something had been poured out the hole/i, /A bent needle sticks harmlessly out/i, /Someone has unhooked the stopper, rendering it harmless/i, /was picked apart and removed from the/i, /It is no longer attached to a razor-sharp scythe blade/i, /It seems harmless/i, /whatever it was has been pried out/i, /and the remnants of some type of powder/i, /sealed with dirt, blocking whatever/i, /has been peeled away from the hinges/i]]

[pick: for command disarm my mahogany chest identify]

**Comment by mwest152** [comment]
[pick]>pick my brass caddy blind

[pick]>pick my brass caddy ident

It's not even locked, why bother?
s> 
It's not even locked, why bother?
s> 
[pick]>open my brass caddy

**You open your** brass caddy.
s> 
[pick: *** No match was found after 15 seconds, dumping info]

[pick: messages seen length: 19]

[pick: message: You open your brass caddy.]

[pick: checked against [/^In the .* you see .*\./, /That is already open/i, /It is locked/i]]

[pick: for command open my brass caddy]

**Comment by mwest152** [comment]
The bearskin glove recent incidentals probably has issues with other scripts as well, but I noticed it with pick.  Here is the wear/remove messaging for some hiro bearskin gloves interlaced with strips of ice-veined leather:

**> rem gloves
A brisk chill leaves you as you remove some hiro bearskin gloves interlaced with strips of ice-veined leather.
> wear gloves
A brisk chill rushes through you as you wear some hiro bearskin gloves interlaced with strips of ice-veined leather.
>** 

[pick]>get my bear.gloves

As you touch some hiro bearskin gloves interlaced with strips of ice-veined leather, a light chill spreads up your arm and you shiver at the sudden cold.
You get some hiro bearskin gloves interlaced with strips of ice-veined leather from inside your haversack.
> 
[pick]>wear my bear.gloves

A brisk chill rushes through you as you wear some hiro bearskin gloves interlaced with strips of ice-veined leather.
> 
[pick: *** No match was found after 15 seconds, dumping info]

[pick: messages seen length: 11]

[pick: message: A brisk chill rushes through you as you wear some hiro bearskin gloves interlaced with strips of ice-veined leather.]

[pick: checked against [/^You put/, /^You pull/, /^You sling/, /^You attach/, /^You strap/, /^You slide/, /^You spin/, /^You slip/, /^You place/, /^You hang/, /^You tug/, /^You struggle/, /^You squeeze/, /^You manage/, /^You gently place/, /^You toss one strap/, /^You carefully loop/, /^You work your way into/, /^You are already wearing/, /^Gritting your teeth, you grip/, /slide effortlessly onto your/, /^You carefully arrange/, /^You drape/, /^You can't wear/, /^You (need to|should) unload/, /close the fan/, /^You don't seem to be able to move/, /^Wear what/, /^I could not/, /^What were you/]]

[pick: for command wear my bear.gloves]

**Comment by MahtraDR** [comment]
These are two separate issues.

One is in pick.lic relating to handling one being too injured to disarm.

Two is the messaging for wearing them bearskin gloves is unusual, and we don't have a match for it. I've fixed the common-items issue for this. I'll look into pick.lic next.
