### ISSUE TITLE
room 1412 exit conflicting with parser

### ISSUE THREAD

**Issue by cynesis** [rpherbig/dr-scripts#600]
Apparently, I would prefer to go stonebow rather than stones when issuing the command 'go stone'. Suggest changing the map exit to "go stones" instead of "go stone".
--
[go2]>go arch
[Siergelde, Ruins - 1412]
A carpet of thick rolling grasses is punctuated by tiny lavender flowers in what looks to be the foyer of the building.  A great monolith of speckled granite towers above you, its midsection etched with images.  Sparse tufts of juriweed skirt the point where the monolith has been driven into the ground by a power greater than any you can imagine.  You also see a pile of deliberately arranged stones at the center of the ruins, an aged statue, a massive archway and an oleander bush with a low, flat rock under it.
Obvious paths: southeast.
>
[go2]>go stone
You can't do that.
>
[go2: move: failed]
[go2: restarting script...]
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>go stone
You can't do that.
>
>tap stone
>
You tap a bamboo stonebow inside your backpack.
>close backpack
You close your backpack.
>go stones
[Siergelde, Stone Grotto - 1420]
Some of the building stones from the ruins that surround you have been fashioned into a shallow grotto at the very top of this hill.  Within the grotto, four rounded stones of descending size are set one upon the other in the manner of a crude altar.  At the foot of this altar, you find fruits and flowers in various stages of decay, the remnants of offerings to whatever power pervades this quietly sacred site.  You also see a tiny bubbling pool under some mintberry bushes.
Obvious paths: east, west.
>;k go2
--- Lich: go2 has exited.
[favor]>pray

**Comment by rcuhljr** [comment]
Fixed.
