### ISSUE TITLE
enchant.lic - getting an augmenting loop when crafting an augmenting loop

### ISSUE THREAD

**Issue by Tirost** [rpherbig/dr-scripts#6014]
Requesting that enchant.lic attempt to get an augmenting loop from the player's craft bag. Currently it uses the command `get my augmenting loop` which tries to get the unfinished augmenting loop from the brazier when crafting one.

I think the modification can be made to line 198 of enchant.lic at the `get_item(@loop)` section.

Log: https://pastebin.com/AuMyxVjY

**Comment by MahtraDR** [comment]
Resolved by https://github.com/rpherbig/dr-scripts/pull/6390

Please reopen if there are any more issues.
