### ISSUE TITLE
forge.lic missing messaging

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#6024]
**Used forge.lic to temper a weapon.  Happen to be holding the weapon and tongs at the same time.**

> ,forge temper club

--- Lich: forge active.

--- Lich: buff active.

No waggle set found for name: forge

--- Lich: buff has exited.

> 
[forge]>get my oil from my duffel bag

You need a free hand to pick that up.
> 
You feel fully attuned to the mana streams again.
> 
[forge: *** No match was found after 15 seconds, dumping info]

[forge: messages seen length: 4]

[forge: checked against [/You get/i, /What were/i]]

[forge: for command get my oil from my duffel bag]

--- Lich: go2 active.

[go2: ETA: 0:00:00 (1 rooms to move through)]

[go2]>south

You hobble south.

[Crossing Forging Society, Tool Store]
Masters and journeyman of the forging craft find a home in this room purchasing tools and ingredients.  Loud thumps and groaning accompany the loading and unloading of goods from storage.
You also see Forging Society Mistress Yalda, a clerk, a sturdy low counter with a small placard on it, a large sign and a steel crate.
Obvious exits: north, south, west.

Room Number: 8776

> 
[go2: travel time: 0:00:00]

--- Lich: go2 has exited.

> 
[forge]>order 6

The attendant says, "You can purchase a flask of oil for 1,000 Kronars.  Just order it again and we'll see it done!"
> 
[forge]>order 6

You realize your hands are full, and stop.
> 
[forge: *** No match was found after 15 seconds, dumping info]

[forge: messages seen length: 2]

[forge: checked against [/takes some coins from you/i]]

[forge: for command order 6]

[forge]>put my oil in my duffel bag

What were you referring to?
> 
--- Lich: go2 active.

[go2: ETA: 0:00:00 (1 rooms to move through)]

[go2]>north

You hobble north.

[Crossing Forging Society, Forge]
Several large grindstones on wooden frames stand in the middle of the workroom.  From time to time, a Dwarven apprentice scatters sand over the floor, both for more secure footing and as a safeguard against fire from the sparks cascading off the grindstones.  A high-pitched keening and the smell of hot metal rise from those in use and from others to the south.
You also see a glowing forge, an iron anvil, a pile of fuel, a slack tub filled with water and a large waste bucket.
Obvious exits: south.

Room Number: 8778

> 
[go2: travel time: 0:00:00]

--- Lich: go2 has exited.
> 
[forge]>release mana

You aren't harnessing any mana.
> 
[forge]>prepare symbiosis

But you've already prepared the Spring symbiosis!
> 
[forge]>prepare tksh 92

That won't affect your current attunement very much.

You raise your head skyward, chanting the equation of the Telekinetic Shield spell.
> 
[forge]>put my club on the forge

You glance down at the hot coals of the forge, and reconsider if you wish to do that.

[Putting a weapon or piece of armor on the forge begins the tempering process.  This process can make an item more durable, but failing can cause damage to it as well.  Put your item onto the forge again in the next 30 seconds, to proceed.  You've been warned!]
> 
[forge]>put my club on the forge

You carefully disassemble the club, apply a thin coat of clay to the metal and then place it on the forge.
Roundtime: 13 sec.

**Comment by MahtraDR** [comment]
Forge.lic has been rewritten since this. Does this still happen?
