### ISSUE TITLE
enchant.lic missing messaging

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#6036]
When done enchanting a gweth script doesn't end.

[enchant]>wave imbuement rod at gweth on brazier

The spell is channeled through the fount hanging above, and down into the gwethdesuan.  Not a single stream avoids your cautious analysis as you conduct them into arrangements.
Roundtime: 8 sec.
You collect the gwethdesuan and place it at your feet.
You collect the fount and place it at your feet.

[enchant]>put my imbuement rod in my duffel bag

You put your rod in your duffel bag.
> 
[enchant]>get my burin

You get a fey-bone burin wrapped within a lattice of steelsilk knotwork from inside your duffel bag.
> 
[enchant]>scribe gweth on brazier with my burin

Scribe what?
> 
> 
[enchant: *** No match was found after 15 seconds, dumping info]

[enchant: messages seen length: 13]

[enchant: checked against [/Roundtime/i]]

[enchant: for command scribe gweth on brazier with my burin]

[enchant]>scribe gweth on brazier with my burin

Scribe what?

**Comment by MahtraDR** [comment]
Resolved by #6089
