### ISSUE TITLE
ranger-companion update incorrectly pauses other scripts

### ISSUE THREAD

**Issue by SaphiaFae** [rpherbig/dr-scripts#6077]
The most recent update of ranger-companion doesn't function correctly. It pauses all other scripts as soon as you run it (instead of only pausing them when your companion needs feeding), then doesn't unpause them (frustrating since it's intended to be used as a "during" when hunting) and eventually closes itself citing an error regarding unpaused scripts. 

It runs fine, if I manually "unpause all" right after I start it, although it still doesn't pause to feed (not really a problem).

**Comment by MahtraDR** [comment]
Thanks for that. I'll look into this today.

**Comment by SaphiaFae** [comment]
Thanks. Here's the error I just got, if it helps. This occurred right after feeding my wolf and closed the script.

--- Lich: error: undefined local variable or method `scripts_to_unpause' for #<Companion:0x0c803790>
	ranger-companion:23:in `end_script'
	ranger-companion:74:in `initialize'
[ranger-companion]>signal companion to sleep
[ranger-companion]>signal companion to hunt
--- Lich: ranger-companion has exited.

**Comment by MahtraDR** [comment]
Please try now?

**Comment by SaphiaFae** [comment]
Thank you. It's almost working. The problem is, it closes itself after feeding my companion.- scripts starts- wolf whimpers to trigger feed loop- other scripts paused- wolf is fed- other scripts unpaused- script closes itself I can't copy and paste because I'm not on my computer. Thanks, Rose/SaphiaFae On 24/8/22, 14:19 Mahtra ***@***.***> wrote:

   
  Please try now?

**Comment by MahtraDR** [comment]
I've reopened the issue for now. When you can paste some logs, that'll help immensely.

**Comment by SaphiaFae** [comment]
--- Lich: ranger-companion active.
--- Lich: sc2 paused.
[ranger-companion: Pausing ["sc2"] to run ranger-companion]
[ranger-companion]>whistle for companion
You whistle loudly for your companion.
[Roundtime: 15 seconds]
A baby wolf scrambles in.
>
A baby wolf begins to whimper.
>
[ranger-companion]>stow left
Stow what?  Type 'STOW HELP' for details.
>
[ranger-companion]>get my milk
>
You get a bottle of fresh milk from inside your wolfskin backpack.
>
[ranger-companion]>feed my milk to wolf
The baby wolf greedily drinks a bottle of fresh milk.
>
[ranger-companion]>stow my milk
You put your milk in your wolfskin backpack.
>
[ranger-companion: Unpausing ["sc2"], ranger-companion has finished.]
--- Lich: sc2 unpaused.
[ranger-companion]>signal companion to sleep
You signal to your baby wolf.

The baby wolf wanders off to find a quiet place to sleep.
>
[ranger-companion]>signal companion to hunt
>
Your companion is not here.
>
--- Lich: ranger-companion has exited.

**Comment by SaphiaFae** [comment]
It's still pausing other scripts right at the start and the closing itself when they unpause. Previously it would only pause scripts in order to feed the companion and continue on after unpausing them.

I think Genie users probably have triggers set up and don't need this script. I use Wrayth. The script simplifies 4 actions:
- summons a companion
- feeds it when it whimpers
- pets it when it paces
- dismisses it (by sending to sleep if young, or to hunt if older) when you manually end the script.
It doesn't need to pause any scripts unless it's feeding or petting, and even then, it's not strictly necessary, but useful just in case, because the companion will permanently leave if you miss the cues. It definitely shouldn't exit after unpausing the scripts.

**Comment by MahtraDR** [comment]
Sorry about the hassle...

I see what i did there. Could you please test the version from https://github.com/rpherbig/dr-scripts/pull/6091 ?

Grab the file, and put it in your `scripts/custom` folder. If that version is good, we'll merge it.

Thanks!

**Comment by MahtraDR** [comment]
Closing this as we resolved the issue in the current version of ranger companion.
