### ISSUE TITLE
workorders.lic [carving] omitting material type

### ISSUE THREAD

**Issue by SaphiaFae** [rpherbig/dr-scripts#6093]
Workorders (carving) orders "wolf bones" but refers to them as "wolf". Neither the game, nor carve.lic recognises "wolf" on it's own. Carve.lic needs the material (wolf) and type (bone). 

###copy n paste with fluff cut out###

[workorders]>order 8
The attendant says, "You can purchase a stack of 10 wolf bones for 200 Kronars.  Just order it again and we'll see it done!"
>
[workorders]>order 8
The attendant takes some coins from you and hands you a stack of 10 wolf bones.
>
[workorders]>tap my deed
I could not find what you were referring to.
>
[workorders]>stow left
You put your stack in your zila rugursora.
>
[workorders]>get wolf 
What were you referring to?

--- Lich: carve active.
[carve: ***INVALID ARGUMENTS DON'T MATCH ANY PATTERN***]
Provided Arguments: '4 "a stone toe ring" wolf  ring'

 SCRIPT CALL FORMAT AND ARG DESCRIPTIONS (arguments in brackets are optional):
  ;carve <chapter> <recipe name> <material> <type> <noun>
   chapter      Chapter containing the item. 
   recipe name  Name of the recipe, wrap in double quotes if this is multiple words. 
   material     Type of stone/bone to use. 
   type         What material noun you are using. [stack, rock, stone, pebble, boulder, deed]
   noun          

 SCRIPT CALL FORMAT AND ARG DESCRIPTIONS (arguments in brackets are optional):
  ;carve resume <type> <noun>
   resume        
   type         Which material type the item is. [bone, stone]
   noun         Noun of item to resume. 

 YAML SETTINGS USED:
   crafting_container: Noun for base container for storing crafting related items. Gets and stows carving items from here. [Ex: backpack]
   crafting_items_in_container: List of items that are stored in your specific crafting_container. Get these carve tools from crafting_container. [Ex: - oil, - shaper]
   crafting_training_spells: Basic, no harness/cambrinth spells that are prepared in between crafting RT.  [Ex: https://tinyurl.com/4w56txzf]
   engineering_belt: Specify engineering belt name and list of tools. Use and stow carve tools from here. [Ex: https://github.com/rpherbig/dr-scripts/wiki/Crafting-Setup#tools (see Toolbelts section)]
   mark_crafted_goods: Specify whether to mark your crafted goods. Marks items you carve with your stamp. [Ex: true/false]

--- Lich: carve has exited.
[workorders]>get my engineering logbook
You get an engineering work order logbook from inside your zila rugursora.
>
[workorders]>bundle my ring with my logbook
You need to be holding the ring to do that.

[If the item is too heavy, you should first deed it by PUSHing it with a Deed Packet.]
>
[workorders: *** No match was found after 15 seconds, dumping info]
[workorders: message: [If the item is too heavy, you should first deed it by PUSHing it with a Deed Packet.]]
[workorders: message: You need to be holding the ring to do that.]
[workorders: checked against [/You notate the/i, /This work order has expired/i, /The work order requires items of a higher quality/i, /That's not going to work/i]]
[workorders: for command bundle my ring with my logbook]
[workorders]>stow right
You put your logbook in your zila rugursora.
>
[workorders]>get wolf 
What were you referring to?
>
--- Lich: carve active.
[carve: ***INVALID ARGUMENTS DON'T MATCH ANY PATTERN***]
Provided Arguments: '4 "a stone toe ring" wolf  ring'

 SCRIPT CALL FORMAT AND ARG DESCRIPTIONS (arguments in brackets are optional):
  ;carve <chapter> <recipe name> <material> <type> <noun>
   chapter      Chapter containing the item. 
   recipe name  Name of the recipe, wrap in double quotes if this is multiple words. 
   material     Type of stone/bone to use. 
   type         What material noun you are using. [stack, rock, stone, pebble, boulder, deed]
   noun          

 SCRIPT CALL FORMAT AND ARG DESCRIPTIONS (arguments in brackets are optional):
  ;carve resume <type> <noun>
   resume        
   type         Which material type the item is. [bone, stone]
   noun         Noun of item to resume. 

 YAML SETTINGS USED:
   crafting_container: Noun for base container for storing crafting related items. Gets and stows carving items from here. [Ex: backpack]
   crafting_items_in_container: List of items that are stored in your specific crafting_container. Get these carve tools from crafting_container. [Ex: - oil, - shaper]
   crafting_training_spells: Basic, no harness/cambrinth spells that are prepared in between crafting RT.  [Ex: https://tinyurl.com/4w56txzf]
   engineering_belt: Specify engineering belt name and list of tools. Use and stow carve tools from here. [Ex: https://github.com/rpherbig/dr-scripts/wiki/Crafting-Setup#tools (see Toolbelts section)]
   mark_crafted_goods: Specify whether to mark your crafted goods. Marks items you carve with your stamp. [Ex: true/false]

--- Lich: carve has exited.
>
[workorders]>get my engineering logbook
You get an engineering work order logbook from inside your zila rugursora.
>
[workorders]>bundle my ring with my logbook
You need to be holding the ring to do that.

[If the item is too heavy, you should first deed it by PUSHing it with a Deed Packet.]

>;ka

**Comment by SaphiaFae** [comment]
Incidentally....

>look in rug
>
In the zila rugursoora:
wolf-bone stack
>get wolf-bone
What were you referring to?
>get stack
You get a wolf-bone stack from inside your zila rugursora.

**Comment by Raykyn55** [comment]
```
Provided Arguments: '4 "a stone toe ring" wolf ring'
```
Looks like it thinks it's doing a stone order

**Comment by MahtraDR** [comment]
Tried to reproduce today and couldn't. If it's still an issue please re-open and we can re-look at it.
