### ISSUE TITLE
Can "stow <name of gem>" be changed to "stow gem"  ?  (Combat-Trainer)

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#610]
Because I wear  an "emerald-scaled cambrinth pivuh attached to a wide wristcuff" it seems to interfere when an emerald drops for loot.  (see below)

Is it possible to just have the script "stow gem" ?

You search the dusky-scaled basilisk.
The basilisk was carrying a tiny faceted mint green emerald!

[combat-trainer]>stow emerald

But that is already in your inventory.
A lesser dusky-scaled basilisk bursts open along its grievous wounds, flooding the area with a thick red sludge.  The body crumbles apart into the ooze, producing a thick, acrid smoke that grates harshly upon your eyes and throat.
* A lesser dusky-scaled basilisk bites ravenously at you.  You knock aside little of the fangs with a steel hhr'ata.  
[You're bruised, nimbly balanced with opponent in better position.]
* A lesser dusky-scaled basilisk whips its thick, spined tail at you.  You dodge.  
[You're bruised, nimbly balanced and in strong position.]
Your formation of a targeting pattern around a lesser dusky-scaled basilisk has completed.
* A lesser dusky-scaled basilisk whips its thick, spined tail at you.  You barely block with a damite targe.  
[You're bruised, nimbly balanced with opponent in better position.]
You feel fully attuned to the mana streams again.
* A lesser dusky-scaled basilisk swipes a massive claw at you.  You partially block with a damite targe.  
[You're bruised, nimbly balanced and in very strong position.]
* A lesser dusky-scaled basilisk swipes a massive claw at you.  You partially block with a damite targe.  
[You're bruised, nimbly balanced and opponent has slight advantage.]

[combat-trainer: *** No match was found after 15 seconds, dumping info]

[combat-trainer: messages seen length: 36]

[combat-trainer: message: But that is already in your inventory.]

[combat-trainer: message: Protection from Evil  (2 roisaen)]

[combat-trainer: message: Osrel Meraud  (97%)]

[combat-trainer: message: Benediction  (27 roisaen)]

[combat-trainer: message: Centering  (4 roisaen)]

[combat-trainer: message: Major Physical Protection  (3 roisaen)]

[combat-trainer: message: Hydra Hex  (Indefinite)]

[combat-trainer: message: Righteous Wrath  (9 roisaen)]

[combat-trainer: message: Murrula's Flames  (OM)]

[combat-trainer: message: Glythtide's Gift  (OM)]

[combat-trainer: message: Persistence of Mana  (OM)]

[combat-trainer: message: Bless  (4 roisaen)]

[combat-trainer: message: A lesser dusky-scaled basilisk bursts open along its grievous wounds, flooding the area with a thick red sludge.  The body crumbles apart into the ooze, producing a thick, acrid smoke that grates harshly upon your eyes and throat.]

[combat-trainer: message: * A lesser dusky-scaled basilisk bites ravenously at you.  You knock aside little of the fangs with a steel hhr'ata.  ]

[combat-trainer: message: [You're bruised, nimbly balanced with opponent in better position.]]

[combat-trainer: message: * A lesser dusky-scaled basilisk whips its thick, spined tail at you.  You dodge.  ]

[combat-trainer: message: [You're bruised, nimbly balanced and in strong position.]]

[combat-trainer: message: Your formation of a targeting pattern around a lesser dusky-scaled basilisk has completed.]

[combat-trainer: message: * A lesser dusky-scaled basilisk whips its thick, spined tail at you.  You barely block with a damite targe.  ]

[combat-trainer: message: [You're bruised, nimbly balanced with opponent in better position.]]

[combat-trainer: message: Protection from Evil  (2 roisaen)]

[combat-trainer: message: Osrel Meraud  (97%)]

[combat-trainer: message: Benediction  (27 roisaen)]

[combat-trainer: message: Centering  (4 roisaen)]

[combat-trainer: message: Major Physical Protection  (3 roisaen)]

[combat-trainer: message: Hydra Hex  (Indefinite)]

[combat-trainer: message: Righteous Wrath  (9 roisaen)]

[combat-trainer: message: Murrula's Flames  (OM)]

[combat-trainer: message: Glythtide's Gift  (OM)]

[combat-trainer: message: Persistence of Mana  (OM)]

[combat-trainer: message: Bless  (4 roisaen)]

[combat-trainer: message: You feel fully attuned to the mana streams again.]

[combat-trainer: message: * A lesser dusky-scaled basilisk swipes a massive claw at you.  You partially block with a damite targe.  ]

[combat-trainer: message: [You're bruised, nimbly balanced and in very strong position.]]

[combat-trainer: message: * A lesser dusky-scaled basilisk swipes a massive claw at you.  You partially block with a damite targe.  ]

[combat-trainer: message: [You're bruised, nimbly balanced and opponent has slight advantage.]]

[combat-trainer: checked against [/You pick up/i, /You get/i, /You need a free hand/i, /You just can't/i, /push you over the item limit/i, /You stop as you realize the .* is not yours/i, /Stow what/i]]

[combat-trainer]>weave

You weave back and forth in a dance-like motion, drawing your opponent's attention away from the fight.
[You're winded, nimbly balanced and in strong position.]
Roundtime: 4 sec.
A lesser dusky-scaled basilisk suddenly grows still, growling deeply as delicate coils of smoke rise from its nostrils.

[combat-trainer]>lob

< You lob a steel hhr'ata at a lesser dusky-scaled basilisk.  A lesser dusky-scaled basilisk dodges.  
The hhr'ata hits a wall and falls to the floor!
[You're winded, nimbly balanced and in strong position.]
[Roundtime 2 sec.]
You feel fully attuned to the mana streams again.

[combat-trainer]>get my hhr'ata

You pick up the hhr'ata lying at your feet.

[combat-trainer]>cast

You gesture at a lesser dusky-scaled basilisk.
With a ghastly wail, a pearlescent stream of grey light floods out of the dusky-scaled basilisk's mouth to illuminate the area briefly!
Roundtime: 1 sec.
A lesser dusky-scaled basilisk pounds into view, raking its spiked tail harshly across the ground!
The dusky-scaled basilisk begins to advance on you!
The dusky-scaled basilisk advances from nearby and is closing steadily.

[combat-trainer]>stow emerald

* A lesser dusky-scaled basilisk whips its thick, spined tail at you.  You dodge.  
[You're nimbly balanced and in good position.]
But that is already in your inventory.
You feel fully attuned to the mana streams again.
A lesser dusky-scaled basilisk stomps about, flame spouting angrily from its nostrils!
The swirling confines of malevolent darkness wane from about a lesser dusky-scaled basilisk.
The swirling confines of malevolent darkness wane from about a lesser dusky-scaled basilisk.

[DRPrime]-DR:Deatly: "k thanks"
The dusky-scaled basilisk closes to melee range on you!
* A lesser dusky-scaled basilisk pounds forward, clawing at you.  You dodge.  
[You're nimbly balanced and in very strong position.]
A cage of shadowy tendrils coalesces around a lesser dusky-scaled basilisk.
A cage of shadowy tendrils coalesces around a lesser dusky-scaled basilisk.
A cage of shadowy tendrils coalesces around a lesser dusky-scaled basilisk.
You feel fully attuned to the mana streams again.

[hunting-buddy: ***STATUS*** 180 minutes of hunting remaining or waiting on Large Edged, Staves, Tactics, Heavy Thrown, Brawling]

A lesser dusky-scaled basilisk appears less distracted.
* A lesser dusky-scaled basilisk bellows with rage as it lunges its powerful jaws at you.  You evade.  
[You're nimbly balanced with no advantage.]
* A lesser dusky-scaled basilisk whips its thick, spined tail at you.  You dodge.  
[You're nimbly balanced and in very strong position.]
A lesser dusky-scaled basilisk stomps about, flame spouting angrily from its nostrils!
You feel fully rested.

[combat-trainer: *** No match was found after 15 seconds, dumping info]

[combat-trainer: messages seen length: 35]

[combat-trainer: message: * A lesser dusky-scaled basilisk whips its thick, spined tail at you.  You dodge.  ]

[combat-trainer: message: [You're nimbly balanced and in good position.]]

[combat-trainer: message: But that is already in your inventory.]

[combat-trainer: message: You feel fully attuned to the mana streams again.]

[combat-trainer: message: A lesser dusky-scaled basilisk stomps about, flame spouting angrily from its nostrils!]

[combat-trainer: message: The swirling confines of malevolent darkness wane from about a lesser dusky-scaled basilisk.]

[combat-trainer: message: The swirling confines of malevolent darkness wane from about a lesser dusky-scaled basilisk.]

[combat-trainer: message: [DRPrime]-DR:Deatly: "k thanks"]

[combat-trainer: message: The dusky-scaled basilisk closes to melee range on you!]

[combat-trainer: message: * A lesser dusky-scaled basilisk pounds forward, clawing at you.  You dodge.  ]

[combat-trainer: message: [You're nimbly balanced and in very strong position.]]

[combat-trainer: message: Protection from Evil  (1 roisan)]

[combat-trainer: message: Osrel Meraud  (96%)]

[combat-trainer: message: Benediction  (27 roisaen)]

[combat-trainer: message: Centering  (3 roisaen)]

[combat-trainer: message: Major Physical Protection  (2 roisaen)]

[combat-trainer: message: Hydra Hex  (Indefinite)]

[combat-trainer: message: Righteous Wrath  (9 roisaen)]

[combat-trainer: message: Murrula's Flames  (OM)]

[combat-trainer: message: Glythtide's Gift  (OM)]

[combat-trainer: message: Persistence of Mana  (OM)]

[combat-trainer: message: Bless  (4 roisaen)]

[combat-trainer: message: A cage of shadowy tendrils coalesces around a lesser dusky-scaled basilisk.]

[combat-trainer: message: A cage of shadowy tendrils coalesces around a lesser dusky-scaled basilisk.]

[combat-trainer: message: A cage of shadowy tendrils coalesces around a lesser dusky-scaled basilisk.]

[combat-trainer: message: You feel fully attuned to the mana streams again.]

[combat-trainer: message: A lesser dusky-scaled basilisk appears less distracted.]

[combat-trainer: message: * A lesser dusky-scaled basilisk bellows with rage as it lunges its powerful jaws at you.  You evade.  ]

[combat-trainer: message: [You're nimbly balanced with no advantage.]]

[combat-trainer: message:  * Sensible Gragnathmor joins the adventure.]

[combat-trainer: message: * A lesser dusky-scaled basilisk whips its thick, spined tail at you.  You dodge.  ]

[combat-trainer: message: [You're nimbly balanced and in very strong position.]]

[combat-trainer: message: A lesser dusky-scaled basilisk stomps about, flame spouting angrily from its nostrils!]

[combat-trainer: message:  * Genneron Camanast just sauntered into the adventure with an annoying tune on his lips.]

[combat-trainer: message: You feel fully rested.]

[combat-trainer: checked against [/You pick up/i, /You get/i, /You need a free hand/i, /You just can't/i, /push you over the item limit/i, /You stop as you realize the .* is not yours/i, /Stow what/i]]

* A lesser dusky-scaled basilisk bites ravenously at you.  You dodge.  
[You're nimbly balanced and have slight advantage.]

[combat-trainer]>weave

You weave back and forth in a dance-like motion, drawing your opponent's attention away from the fight.
[You're winded, nimbly balanced and in superior position.]
Roundtime: 4 sec.
* A lesser dusky-scaled basilisk bites ravenously at you.  You evade.  
[You're winded, nimbly balanced and in excellent position.]

[combat-trainer]>lob

< You lob a steel hhr'ata at a lesser dusky-scaled basilisk.  A lesser dusky-scaled basilisk dodges.  
The hhr'ata hits a wall and falls to the floor!
[You're nimbly balanced and in superior position.]
[Roundtime 2 sec.]
A cage of shadowy tendrils coalesces around a lesser dusky-scaled basilisk.
* A lesser dusky-scaled basilisk slices wide at you.  You dodge.  
[You're nimbly balanced with no advantage.]
* A lesser dusky-scaled basilisk pounds forward, clawing at you.  You dodge.  
[You're nimbly balanced with opponent in better position.]

[combat-trainer]>get my hhr'ata

You pick up the hhr'ata lying at your feet.

[combat-trainer]>stow my hhr'ata

* A lesser dusky-scaled basilisk pounds forward, clawing at you.  You evade.  
[You're nimbly balanced and in very strong position.]
You put your hhr'ata in your haversack.

[combat-trainer]>get my nightstick

You get a steel nightstick from inside your kidskin baldric.

[combat-trainer]>pre pfe 20

That won't affect your current attunement very much.
You begin chanting a prayer to invoke the Protection from Evil spell.

[combat-trainer]>charge my armband 25

You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
* A lesser dusky-scaled basilisk pounds forward, clawing at you.  You evade.  
[You're nimbly balanced and have slight advantage.]
A lesser dusky-scaled basilisk bellows a deep, bass roar!

[combat-trainer]>charge my armband 25

You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
* A lesser dusky-scaled basilisk swipes a massive claw at you.  You evade.  
[You're nimbly balanced and in superior position.]
You feel fully rested.

[combat-trainer]>stow emerald

But that is already in your inventory.
* A lesser dusky-scaled basilisk swipes a massive claw at you.  You evade.  
[You're nimbly balanced with no advantage.]
A lesser dusky-scaled basilisk appears less distracted.
* A lesser dusky-scaled basilisk pounds forward, clawing at you.  You evade.  
[You're nimbly balanced and in better position.]
* A lesser dusky-scaled basilisk bites ravenously at you.  You counter little of the fangs with a steel nightstick.  
[You're nimbly balanced and have slight advantage.]
* A lesser dusky-scaled basilisk swipes a massive claw at you.  You barely block with a damite targe.  
[You're nimbly balanced with opponent in better position.]
* A lesser dusky-scaled basilisk swipes a massive claw at you.  You dodge.  
[You're nimbly balanced and in good position.]
You feel fully attuned to the mana streams again.
* A lesser dusky-scaled basilisk swipes a massive claw at you.  You barely block with a damite targe.  
[You're nimbly balanced and have slight advantage.]
The swirling confines of malevolent darkness wane from about a lesser dusky-scaled basilisk.
You feel fully prepared to cast your spell.

[combat-trainer: *** No match was found after 15 seconds, dumping info]

* A lesser dusky-scaled basilisk bellows with rage as it lunges its powerful jaws at you.  You evade.  

[combat-trainer: messages seen length: 39]

[You're nimbly balanced with no advantage.]

[combat-trainer: message: But that is already in your inventory.]

[combat-trainer: message: * A lesser dusky-scaled basilisk swipes a massive claw at you.  You evade.  ]

[combat-trainer: message: [You're nimbly balanced with no advantage.]]

[combat-trainer: message: A lesser dusky-scaled basilisk appears less distracted.]

[combat-trainer: message: * A lesser dusky-scaled basilisk pounds forward, clawing at you.  You evade.  ]

[combat-trainer: message: [You're nimbly balanced and in better position.]]

[combat-trainer: message: Protection from Evil  (1 roisan)]

[combat-trainer: message: Osrel Meraud  (96%)]

[combat-trainer: message: Benediction  (26 roisaen)]

[combat-trainer: message: Centering  (3 roisaen)]

[combat-trainer: message: Major Physical Protection  (2 roisaen)]

[combat-trainer: message: Hydra Hex  (Indefinite)]

[combat-trainer: message: Righteous Wrath  (8 roisaen)]

[combat-trainer: message: Murrula's Flames  (OM)]

[combat-trainer: message: Glythtide's Gift  (OM)]

[combat-trainer: message: Persistence of Mana  (OM)]

[combat-trainer: message: Bless  (3 roisaen)]

[combat-trainer: message: * A lesser dusky-scaled basilisk bites ravenously at you.  You counter little of the fangs with a steel nightstick.  ]

[combat-trainer: message: [You're nimbly balanced and have slight advantage.]]

[combat-trainer: message: * A lesser dusky-scaled basilisk swipes a massive claw at you.  You barely block with a damite targe.  ]

[combat-trainer: message: [You're nimbly balanced with opponent in better position.]]

[combat-trainer: message: * A lesser dusky-scaled basilisk swipes a massive claw at you.  You dodge.  ]

[combat-trainer: message: [You're nimbly balanced and in good position.]]

[combat-trainer: message: You feel fully attuned to the mana streams again.]

[combat-trainer: message: * A lesser dusky-scaled basilisk swipes a massive claw at you.  You barely block with a damite targe.  ]

[combat-trainer: message: [You're nimbly balanced and have slight advantage.]]

[combat-trainer: message: The swirling confines of malevolent darkness wane from about a lesser dusky-scaled basilisk.]

[combat-trainer: message: Protection from Evil  (1 roisan)]

[combat-trainer: message: Osrel Meraud  (95%)]

[combat-trainer: message: Benediction  (26 roisaen)]

[combat-trainer: message: Centering  (3 roisaen)]

[combat-trainer: message: Major Physical Protection  (1 roisan)]

[combat-trainer: message: Hydra Hex  (Indefinite)]

[combat-trainer: message: Righteous Wrath  (8 roisaen)]

[combat-trainer: message: Murrula's Flames  (OM)]

[combat-trainer: message: Glythtide's Gift  (OM)]

[combat-trainer: message: Persistence of Mana  (OM)]

[combat-trainer: message: Bless  (3 roisaen)]

[combat-trainer: message: You feel fully prepared to cast your spell.]

[combat-trainer: checked against [/You pick up/i, /You get/i, /You need a free hand/i, /You just can't/i, /push you over the item limit/i, /You stop as you realize the .* is not yours/i, /Stow what/i]]

[combat-trainer]>circle

You step badly, circling at the wrong moment as a lesser dusky-scaled basilisk steps easily into a better position and leaving you in worse off.
[You're solidly balanced with opponent in better position.]
Roundtime: 4 sec.
A cage of shadowy tendrils coalesces around a lesser dusky-scaled basilisk.
A cage of shadowy tendrils coalesces around a lesser dusky-scaled basilisk.
You feel fully attuned to the mana streams again.
* A lesser dusky-scaled basilisk swipes a massive claw at you.  You dodge.  
[You're nimbly balanced and in good position.]
Fitful sparks brighten and dim deep within the sky blue svelae on your forehead, swirling in a restless dance around its intaglio pale purple prairie violet.

[combat-trainer]>attack

* A lesser dusky-scaled basilisk swipes a massive claw at you.  You partially block with a damite targe.  
[You're nimbly balanced and in better position.]
< You feint a steel nightstick at a lesser dusky-scaled basilisk.  A lesser dusky-scaled basilisk evades.  
[You're nimbly balanced and in strong position.]
[Roundtime 1 sec.]
You feel fully rested.
* A lesser dusky-scaled basilisk whips its thick, spined tail at you.  You counter little of the tail with a steel nightstick.  
[You're nimbly balanced with no advantage.]
A lesser dusky-scaled basilisk suddenly grows still, growling deeply as delicate coils of smoke rise from its nostrils.

[combat-trainer]>invoke my armband

The armband pulses with Holy energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.
Roundtime: 1 sec.

[combat-trainer]>cast

You gesture.
Your armband emits a loud *snap* as it discharges all its power to aid your spell.
You are bathed in a soft white glow for a moment.

[combat-trainer]>stow emerald

But that is already in your inventory.
The swirling confines of malevolent darkness wane from about a lesser dusky-scaled basilisk.
* A lesser dusky-scaled basilisk swipes a massive claw at you.  You partially block with a damite targe.  
[You're nimbly balanced and in strong position.]
You feel fully rested.
A cage of shadowy tendrils coalesces around a lesser dusky-scaled basilisk.
* A lesser dusky-scaled basilisk whips its thick, spined tail at you.  You dodge.  
[You're nimbly balanced with no advantage.]
* A lesser dusky-scaled basilisk bites ravenously at you.  You barely block with a damite targe.  
[You're nimbly balanced with opponent in better position.]
A lesser dusky-scaled basilisk stomps about, flame spouting angrily from its nostrils!
You feel fully attuned to the mana streams again.

[hunting-buddy: ***STATUS*** 179 minutes of hunting remaining or waiting on Large Edged, Staves, Tactics, Heavy Thrown, Brawling]

* A lesser dusky-scaled basilisk whips its thick, spined tail at you.  You fend off little of the tail with a steel nightstick.  
[You're nimbly balanced with no advantage.]
* A lesser dusky-scaled basilisk bellows in rage as it claws at you.  You evade.  
[You're nimbly balanced with opponent in good position.]

[combat-trainer: *** No match was found after 15 seconds, dumping info]

[combat-trainer: messages seen length: 39]

[combat-trainer: message: Protection from Evil  (32 roisaen)]

[combat-trainer: message: Osrel Meraud  (95%)]

[combat-trainer: message: Benediction  (26 roisaen)]

[combat-trainer: message: Centering  (2 roisaen)]

[combat-trainer: message: Major Physical Protection  (1 roisan)]

[combat-trainer: message: Hydra Hex  (Indefinite)]

[combat-trainer: message: Righteous Wrath  (8 roisaen)]

[combat-trainer: message: Murrula's Flames  (OM)]

[combat-trainer: message: Glythtide's Gift  (OM)]

[combat-trainer: message: Persistence of Mana  (OM)]

[combat-trainer: message: Bless  (3 roisaen)]

[combat-trainer: message: But that is already in your inventory.]

[combat-trainer: message: The swirling confines of malevolent darkness wane from about a lesser dusky-scaled basilisk.]

[combat-trainer: message: * A lesser dusky-scaled basilisk swipes a massive claw at you.  You partially block with a damite targe.  ]

[combat-trainer: message: [You're nimbly balanced and in strong position.]]

[combat-trainer: message: You feel fully rested.]

[combat-trainer: message: A cage of shadowy tendrils coalesces around a lesser dusky-scaled basilisk.]

[combat-trainer: message: * A lesser dusky-scaled basilisk whips its thick, spined tail at you.  You dodge.  ]

[combat-trainer: message: [You're nimbly balanced with no advantage.]]

[combat-trainer: message: * A lesser dusky-scaled basilisk bites ravenously at you.  You barely block with a damite targe.  ]

[combat-trainer: message: [You're nimbly balanced with opponent in better position.]]

[combat-trainer: message: A lesser dusky-scaled basilisk stomps about, flame spouting angrily from its nostrils!]

[combat-trainer: message:  * After waking from a long catnap, Tigoti once again prowls the lands.]

[combat-trainer: message: Protection from Evil  (32 roisaen)]

[combat-trainer: message: Osrel Meraud  (95%)]

[combat-trainer: message: Benediction  (26 roisaen)]

[combat-trainer: message: Centering  (2 roisaen)]

[combat-trainer: message: Major Physical Protection  (1 roisan)]

[combat-trainer: message: Hydra Hex  (Indefinite)]

[combat-trainer: message: Righteous Wrath  (8 roisaen)]

[combat-trainer: message: Murrula's Flames  (OM)]

[combat-trainer: message: Glythtide's Gift  (OM)]

[combat-trainer: message: Persistence of Mana  (OM)]

[combat-trainer: message: Bless  (3 roisaen)]

[combat-trainer: message: You feel fully attuned to the mana streams again.]

[combat-trainer: message: * A lesser dusky-scaled basilisk whips its thick, spined tail at you.  You fend off little of the tail with a steel nightstick.  ]

[combat-trainer: message: [You're nimbly balanced with no advantage.]]

[combat-trainer: message: * A lesser dusky-scaled basilisk bellows in rage as it claws at you.  You evade.  ]

[combat-trainer: message: [You're nimbly balanced with opponent in good position.]]

[combat-trainer: checked against [/You pick up/i, /You get/i, /You need a free hand/i, /You just can't/i, /push you over the item limit/i, /You stop as you realize the .* is not yours/i, /Stow what/i]]

[combat-trainer]>circle

You fake a lesser dusky-scaled basilisk, first moving one way and then another, leaving it off balance.
[You're nimbly balanced with no advantage.]
Roundtime: 3 sec.
* A lesser dusky-scaled basilisk bellows in rage as it claws at you.  You fend off little of the claws with a steel nightstick.  
[You're nimbly balanced and in good position.]
A lesser dusky-scaled basilisk stomps about, flame spouting angrily from its nostrils!
A cage of shadowy tendrils coalesces around a lesser dusky-scaled basilisk.

[combat-trainer]>attack

* A lesser dusky-scaled basilisk pounds forward, clawing at you.  You partially block with a damite targe.  
[You're nimbly balanced and have slight advantage.]
< You jab a steel nightstick at a lesser dusky-scaled basilisk.  A lesser dusky-scaled basilisk evades.  
[You're adeptly balanced and in better position.]
[Roundtime 1 sec.]
You feel fully rested.
You feel fully attuned to the mana streams again.

[combat-trainer]>pre MAPP 20

That won't affect your current attunement very much.
You begin chanting a prayer to invoke the Major Physical Protection spell.

[combat-trainer]>charge my armband 25

You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
* A lesser dusky-scaled basilisk swipes a massive claw at you.  You dodge.  
[You're adeptly balanced and in strong position.]
* A lesser dusky-scaled basilisk swipes a massive claw at you.  You dodge.  
[You're adeptly balanced and in good position.]

[combat-trainer]>charge my armband 25

You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
A lesser dusky-scaled basilisk suddenly grows still, growling deeply as delicate coils of smoke rise from its nostrils.
The swirling confines of malevolent darkness wane from about a lesser dusky-scaled basilisk.
A white glow flares around you.
* A lesser dusky-scaled basilisk pounds forward, clawing at you.  You fail to evade.  The claws lands a harmless (0/23) blow to your left arm.
[You're nimbly balanced with no advantage.]

[combat-trainer]>stow emerald

But that is already in your inventory.
* A lesser dusky-scaled basilisk slices wide at you.  You fend off little of the claws with a steel nightstick.  
[You're nimbly balanced and have slight advantage.]
A cage of shadowy tendrils coalesces around a lesser dusky-scaled basilisk.
A cage of shadowy tendrils coalesces around a lesser dusky-scaled basilisk.
* A lesser dusky-scaled basilisk pounds forward, clawing at you.  You evade.  
[You're nimbly balanced and have slight advantage.]
* A lesser dusky-scaled basilisk pounds forward, clawing at you.  You evade.  
[You're nimbly balanced and have slight advantage.]
A lesser dusky-scaled basilisk stomps about, flame spouting angrily from its nostrils!
* A lesser dusky-scaled basilisk pounds forward, clawing at you.  You evade.  
[You're nimbly balanced with no advantage.]
A lesser dusky-scaled basilisk grows rigidly still like a statue for a moment, ceasing even its heavy, rhythmic breathing.
You feel fully prepared to cast your spell.
You feel fully attuned to the mana streams again.

[combat-trainer: *** No match was found after 15 seconds, dumping info]

[combat-trainer: messages seen length: 26]

[combat-trainer: message: But that is already in your inventory.]

[combat-trainer: message: * A lesser dusky-scaled basilisk slices wide at you.  You fend off little of the claws with a steel nightstick.  ]

[combat-trainer: message: [You're nimbly balanced and have slight advantage.]]

[combat-trainer: message: A cage of shadowy tendrils coalesces around a lesser dusky-scaled basilisk.]

[combat-trainer: message: A cage of shadowy tendrils coalesces around a lesser dusky-scaled basilisk.]

[combat-trainer: message: * A lesser dusky-scaled basilisk pounds forward, clawing at you.  You evade.  ]

[combat-trainer: message: [You're nimbly balanced and have slight advantage.]]

[combat-trainer: message: * A lesser dusky-scaled basilisk pounds forward, clawing at you.  You evade.  ]

[combat-trainer: message: [You're nimbly balanced and have slight advantage.]]

[combat-trainer: message: A lesser dusky-scaled basilisk stomps about, flame spouting angrily from its nostrils!]

[combat-trainer: message: Protection from Evil  (32 roisaen)]

[combat-trainer: message: Osrel Meraud  (95%)]

[combat-trainer: message: Benediction  (25 roisaen)]

[combat-trainer: message: Centering  (2 roisaen)]

[combat-trainer: message: Major Physical Protection  (1 roisan)]

[combat-trainer: message: Hydra Hex  (Indefinite)]

[combat-trainer: message: Righteous Wrath  (7 roisaen)]

[combat-trainer: message: Murrula's Flames  (OM)]

[combat-trainer: message: Glythtide's Gift  (OM)]

[combat-trainer: message: Persistence of Mana  (OM)]

[combat-trainer: message: Bless  (2 roisaen)]

[combat-trainer: message: * A lesser dusky-scaled basilisk pounds forward, clawing at you.  You evade.  ]

[combat-trainer: message: [You're nimbly balanced with no advantage.]]

[combat-trainer: message: A lesser dusky-scaled basilisk grows rigidly still like a statue for a moment, ceasing even its heavy, rhythmic breathing.]

[combat-trainer: message: You feel fully prepared to cast your spell.]

[combat-trainer: message: You feel fully attuned to the mana streams again.]

[combat-trainer: checked against [/You pick up/i, /You get/i, /You need a free hand/i, /You just can't/i, /push you over the item limit/i, /You stop as you realize the .* is not yours/i, /Stow what/i]]

[combat-trainer]>bob

You bob suddenly, lowering yourself into a smaller target.
[You're nimbly balanced and in strong position.]
Roundtime: 4 sec.
The dusky-scaled basilisk retreats from you.
A lesser dusky-scaled basilisk stomps about, flame spouting angrily from its nostrils!
You feel fully attuned to the mana streams again.

[combat-trainer]>attack

< You swing a steel nightstick at a lesser dusky-scaled basilisk.  A lesser dusky-scaled basilisk attempts to evade.  The nightstick flashes with a brilliant silver light and lands a good strike (3/23) to the basilisk's right leg.
[You're nimbly balanced and in good position.]
[Roundtime 3 sec.]
* A lesser dusky-scaled basilisk bellows with rage as it lunges its powerful jaws at you.  You barely block with a damite targe.  
[You're nimbly balanced and in good position.]

[combat-trainer]>invoke my armband

The armband pulses with Holy energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.
Roundtime: 1 sec.
The swirling confines of malevolent darkness wane from about a lesser dusky-scaled basilisk.
You feel fully rested.

[combat-trainer]>cast

* A lesser dusky-scaled basilisk pounds forward, clawing at you.  You dodge.  
[You're nimbly balanced and have slight advantage.]
You gesture.
Your armband emits a loud *snap* as it discharges all its power to aid your spell.
A bright silver nimbus roars up around you as streaks of steel-blue light descend in a convex field.
A sense of calm focus takes hold as the luminous pattern washes over you.  You feel moderately more able to avoid attacks with your energized joints.

[combat-trainer]>stow emerald

But that is already in your inventory.

**Comment by rpherbig** [comment]
Have you tested `stow gem` to see if it works on emeralds?

**Comment by rpherbig** [comment]
If `stow gem` doesn't work (hmm, maybe even if it does...), we may need to add ordinal logic. On a message of `But that is already in your inventory.`, we try to `stow second emerald`.

Heaven help us if you have a weapon that responds to emerald and everything breaks...

**Comment by drgabellia** [comment]
Yes.  Stow gem works for emeralds.

**Comment by rcuhljr** [comment]
Should be fixed
