### ISSUE TITLE
Hunting-Buddy Stop_On

### ISSUE THREAD

**Issue by drboldwin** [rpherbig/dr-scripts#612]
Not sure if this issue is elsewhere so disregard/delete if it is.  But my YAML is set to run to a back-train location and stop_on stealth skill.  Then run to my main hunting area.  But if my stealth skill is already locked (a stealth teacher in crossing can cause this) then it goes to the backtrain location but immediately toggles to main hunt.  So main hunt is occurring in the wrong hunting grounds.

**Comment by rcuhljr** [comment]
Fixed.
