### ISSUE TITLE
forge.lic failing to craft weapon recipe 'a spiked ball and chain'

### ISSUE THREAD

**Issue by mikejcook** [rpherbig/dr-scripts#6123]
There seems to be an issue with crafting the weapon recipe 'a spiked ball and chain' with forge

here's the snippet where it fails:
The ball and chain now appears ready for grinding and polishing on a grinding wheel.
Roundtime: 32 sec.

You need another finished wooden haft to continue crafting an unfinished spiked steel ball and chain.  You believe you can assemble the two ingredients together once you acquire them.

[Ingredients can be added by using ASSEMBLE Ingredient1 WITH Ingredient2]
>
[forge]>get ball from anvil
You get an unfinished spiked steel ball and chain from atop an iron anvil.
>
MISSING ball, Please find it and restart.

so I tried this little script:
    x = 'ball'
    echo DRCI.in_right_hand?(x)
    echo DRC.left_hand
    echo DRC.right_hand

--- Lich: test active.
[test: ]
[test: oak haft]
[test: spiked chain]
--- Lich: test has exited.

>tap my chain
>
I could not find what you were referring to.
>
>tap my ball
You tap an unfinished spiked steel ball and chain that you are holding.

Lich seems to think that the item is a spiked chain, but it's a spiked ball and chain.

**Comment by MahtraDR** [comment]
This is a known issue. The game reports it as a "ball and chain" but it's a "ball"

I've linked an open lich PR which resolves this issue.

**Comment by mikejcook** [comment]
> This is a known issue. The game reports it as a "ball and chain" but it's a "ball"
> 
> I've linked an open lich PR which resolves this issue.

@MahtraDR The PR doesn't seem to fix the issue for me. I believe I made the proper change and I'm still seeing the issue. Details below.

I made the following change to by lich.rbw:

         def initialize(id, noun, name, before=nil, after=nil)
            @id = id
            @noun = noun
            @noun = 'lapis' if @noun == 'lapis lazuli'
            @noun = 'hammer' if @noun == "Hammer of Kai"
            **@noun = 'ball' if @noun == "ball and chain" # DR item 'ball and chain' doesn't work.**
            @noun = 'mother-of-pearl' if (@noun == 'pearl') and (@name =~ /mother\-of\-pearl/)
            @name = name
            @before_name = before
            @after_name = after
         end


But I am still seeing the following error when forging:

The ball and chain now appears ready for grinding and polishing on a grinding wheel.
Roundtime: 25 sec.

You need another finished wooden haft to continue crafting an unfinished double-sided steel ball and chain.  You believe you can assemble the two ingredients together once you acquire them.

[Ingredients can be added by using ASSEMBLE Ingredient1 WITH Ingredient2]
>
[forge]>get ball from anvil
You get an unfinished double-sided steel ball and chain from atop an iron anvil.
>
MISSING ball, Please find it and restart.

--

>tap my ball
You tap an unfinished double-sided steel ball and chain that you are holding.
>;test2
--- Lich: test2 active.
[test2: ]
[test2: ]
[test2: double-sided chain]
--- Lich: test2 has exited.
>tap my ball and chain
I could not find what you were referring to.
