### ISSUE TITLE
tarantula.lic - specific fail scenario

### ISSUE THREAD

**Issue by GreyhallowDR** [rpherbig/dr-scripts#6129]
I  think this is just related to the script timer triggering while climbing Asketi's mount. Can we add a pattern to the bput to recognize `You need to concentrate on your climbing, not that.`?

It results in getting stuck mid-climb (travel is paused) and then the infinite loop of "cannot pause"

> Mapped exits: climb granite cliff
> [go2]>climb cliff
> You work your way down the cliff about 12 feet.
> [Asketi's Mount, Treacherous Cliff]
> Dense clouds obscure the view below, while an incredibly steep cliff soars out of sight into the icy mists overhead.  At eye level are slippery mountain walls, marred with craggy holes left by pitons and gouges left by ice axes.  Whistling winds rush down from the summit, trailing plumes of frost crystals that threaten to freeze the breath in one's lungs.  
> Obvious paths: none.
> Roundtime: 10 seconds.
> Room Number: 27558
> R> 
> Mapped exits: script autoclimbdown, script autoclimbup
> R> 
> --- Lich: bescort active.
> > 
> [bescort]>climb down
> You work your way about 14 feet down the cliff.
> Roundtime: 10 seconds.
> R> 
> [bescort]>climb down
> ...wait 1 seconds.
> R> 
> [bescort]>climb down
> You work your way about 15 feet down the cliff.
> Roundtime: 10 seconds.
> R> 
> --- Lich: sanowret-crystal paused.
> --- Lich: t2 paused.
> --- Lich: hunting-buddy paused.
> --- Lich: go2 paused.
> --- Lich: bescort paused.
> [tarantula: Pausing ["sanowret-crystal", "t2", "hunting-buddy", "go2", "bescort"] to run tarantula]
> R> 
> [tarantula]>turn my harvest spider to Tactics
> ...wait 2 seconds.
> R> 
> [tarantula]>turn my harvest spider to Tactics
> You need to concentrate on your climbing, not that.
> > 
> [tarantula: *** No match was found after 15 seconds, dumping info]
> [tarantula: messages seen length: 2]
> [tarantula: message: You need to concentrate on your climbing, not that.]
> [tarantula: message: ...wait 2 seconds.]
> [tarantula: checked against [/your changes snap into place/, /You need to vary which skillset/, /You should stop practicing your Athletics/, /You don't seem to be able to move to do that/]]
> [tarantula: for command turn my harvest spider to Tactics]
> > 
> [tarantula: Cannot pause, trying again in 5 seconds.]
> > 
> [tarantula: Cannot pause, trying again in 5 seconds.]
> > 
>

**Comment by asechrest** [comment]
@MahtraDR
