### ISSUE TITLE
combat-trainer - cleaner response to spell prep failure

### ISSUE THREAD

**Issue by drboldwin** [rpherbig/dr-scripts#614]
[combat-trainer]>tar ae 15
But you're already preparing a spell!

Perhaps add a call to release spell when you hit a situation like this?  Normally occurs during TM when target dies before casting.  An example log of this happening is [here](http://pastebin.com/kYVDig3N).

It should be noted you do see it eventually release the spell at the very bottom - but my then concentration has slipped and the spell was gone.

**Comment by rcuhljr** [comment]
Did you change your cast messages list or are you using something weird to cast that spell? Combat trainer releases the spell anytime it sees `You can't cast that at yourself!` which occurred in your log, but no release spell was sent.

**Comment by drboldwin** [comment]
http://pastebin.com/K992ES8f - base yaml
http://pastebin.com/skJT8Rpc - backtrain

**Comment by rcuhljr** [comment]
You have `cast_messages: ` which wipes out all cast messages in your setup for some reason. That's messing it up.
