### ISSUE TITLE
Create Script to Find Settings Info for Scripts

### ISSUE THREAD

**Issue by bwfisher82** [rpherbig/dr-scripts#6142]
# Purpose

I am creating a utility Ruby script that will parse *.lic Lich scripts for settings utilized.

# Requirements

## MVP

- Script location: ./util/
- Locate usages of get_settings (variables used).
- Locate usages of said variables (settings used).
- Include variable scope (skinning['skin'] and etc, instead of skinning).
- Output each setting, and each line number and line where said setting is used.

## Add Feature for Command Line Option Functionality (_--[option]_)

- Add command line options via OptionParser built-in Class for:
  - Finding all settings in a script. (MVP operation.)
  - Specifying full path or script name only, with or without extension.
  - Specifying lich script directory in case of not specifying full path.
  - Include a lich script directory default of relative path "../" (from ./util/ where new script will reside).
  - Include ability to specify a different default via a configuration file at ./util/options.json.

## Add Feature to Find Single Setting in Given Script

- Add option to command line options to specify a setting.
- Add logic to look for that specific setting.

## Add Feature to Find Single Setting in All Scripts

- Utilize lich script directory setting.
- Output each script name, and each line number and line where said setting is used.

## Add Feature to Find All Settings in All Scripts

- Utilize lich script directory setting.
- Output each script name, each setting name, and each line number and line where said setting is used.

## Support Custom Scripts

- Support, by default, reading custom scripts when certain options are used to scan scripts for settings.

## Add Feature to Toggle Output to YAML for a Non-Interactive Mode

- Output in YAML ref spec 1.1.
- Data structure format is TBD.
- Inquiry: Descriptions? Read from static file?
- Inquiry: Help/Example? Read from static file for now? Standard link format to wiki settings page in future?
- Inquiry: Script-specific usage descriptions? Read from static file?
- This relates to base-help.yaml; can the data format be altered? (Yes, the code that makes _;script help_ work would need altered as well.)

## (Maybe) Alter Help Data Structure / ";script help"

- Depending on above feature, may update base-help.yaml data structures.
- If so, also update the code that makes _;script help_ work.

## Add Ability to Generate base-help.yaml

- Add option when using yaml output to overwrite base-help.yaml with contents.

## Auto-Generate base-help.yaml

- Update dependency.lic so that upon connection base-help.yaml is auto-generated.
  - This should execute after script update checks.
  - This would use the non-interactive mode option with YAML based output.
- Reason: this should mean that base-help.yaml is updated for users without manual intervention if settings usage in any given scripts change.
- Note: This is not intended to cover custom scripts. I trust users know what settings they are using and what they do in their own scripts.

**Comment by asechrest** [comment]
Closed via #6143
