### ISSUE TITLE
bastard sword weapon swap (buffed ranger)

### ISSUE THREAD

**Issue by Butain** [rpherbig/dr-scripts#6158]
equipment manager is unable to detect weapon swap when ranger buffs are up.

`Poised like a cougar preparing to pounce, you swiftly grip your sword so it can be used as a two-handed edged weapon and stand ready.`

`Your hands seem to glide upon the surrounding air as you agilely adjust your grip on your sword so it can be used as a two-handed edged weapon.`

https://pastebin.com/9nRSanva

**Comment by Raykyn55** [comment]
Believe this is a local yaml issue. replied on discord.
