### ISSUE TITLE
Create sample YAML for Necromancer

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#617]
See #423

**Comment by wscherer420** [comment]
Awesome! Any ETA on this?  When you work on skinning, not sure how to balance it with preserve.  But perhaps a stop on mindlock for skinning, then preserve starts, or vice versa.  Even better would be a stagnated experience gain such as is done with weapons.

**Comment by rpherbig** [comment]
No ETA, it requires someone with a paid account. Anyone with a paid account could do it. Literally anyone. cough @rcuhljr cough.

If you want to submit a PR, the existing samples should be a pretty good starting point. My suggested format is circle requirements at the top and use as few settings as possible to get a circle 1 Necromancer introduced to the YAML system and make it to circle 2.
