### ISSUE TITLE
combat-trainer trying to remove an Item lying at feet 

### ISSUE THREAD

**Issue by GreyhallowDR** [rpherbig/dr-scripts#6175]
Not sure how I got myself into this scenario. Definitely involved a manual input and/or me having a full container.  This may be an opportunity to make the script more robust for this particular, albeit rare, situation.

[combat-trainer]>inv combat
All of your combat equipment:

  some tel'athi-spiked knuckles set with Heke'mhhg lazuli gemstones
  an insulated hood of zenganne lined with a pattern of triangles in silver thread
  a small demonscale shield pyrographed with a map of the Blasted Plains
  a scrimshawed demonbone parry stick
  some black moonsilk pants cuffed with pale blue zenganne
  some tel'athi-spiked footwraps bound with strips of Velakan linen
Lying at your feet is a steel stiletto with a diamondwood handle.

[Use INVENTORY HELP for more options.]
> 
[combat-trainer]>remove my steel.stiletto
You aren't wearing that.

**Comment by MahtraDR** [comment]
Do you have the stiletto in your `gear` entry showing as worn?

**Comment by MahtraDR** [comment]
@GreyhallowDR Any update here? Close as user error? :)

**Comment by Kiriawen** [comment]
Should be closeable due to lack of input from the originator and no other reported incidents from other users.

**Comment by MahtraDR** [comment]
Closing as stale.
