### ISSUE TITLE
base.yaml has skillset max thresholds that override global max threshold.

### ISSUE THREAD

**Issue by Smaptastic** [rpherbig/dr-scripts#6180]
As explained to me on discord, base.yaml has the following settings:
armor_exp_training_max_threshold: 32
weapon_exp_training_max_threshold: 32
magic_exp_training_max_threshold: 32
survival_exp_training_max_threshold: 32
lore_exp_training_max_threshold: 32

These seem to override stop_on_high_threshold if they have a value, making hunting-buddy not honor stop_on_high_threshold  unless the skillset thresholds are blanked in the -setup yaml.

**Comment by MahtraDR** [comment]
https://discord.com/channels/745675889622384681/745678330933805157/1030314984653201429

**Comment by Kiriawen** [comment]
This looks like it was resolved via the PR and appropriate settings.  Can we get this issue closed out please?

**Comment by MahtraDR** [comment]
Fixed by https://github.com/rpherbig/dr-scripts/pull/6682
