### ISSUE TITLE
Hunting zones that should probably have a warning about updating ignored_npcs

### ISSUE THREAD

**Issue by vtcifer** [rpherbig/dr-scripts#6181]
https://github.com/rpherbig/dr-scripts/blob/e3317fda8688c5de0b2b68ec6d8768977513e72d/data/base-hunting.yaml#L648-L662

https://github.com/rpherbig/dr-scripts/blob/e3317fda8688c5de0b2b68ec6d8768977513e72d/data/base-hunting.yaml#L1577-L1583

https://github.com/rpherbig/dr-scripts/blob/e3317fda8688c5de0b2b68ec6d8768977513e72d/data/base-hunting.yaml#L2969-L2974

**Comment by MahtraDR** [comment]
Resolved by https://github.com/rpherbig/dr-scripts/issues/6181
