### ISSUE TITLE
[common.lic] DRC.set_stance should support stance points > 200 for shield / parry

### ISSUE THREAD

**Issue by vtcifer** [rpherbig/dr-scripts#6192]
https://github.com/rpherbig/dr-scripts/blob/503cdc2cca54f9a16a788d154f9d7bf44d8174e2/common.lic#L810-L822

Should be an easy fix I'd think:

```ruby
 when 'parry' 
   "100 #{secondary} #{tertiary}" 
 when 'shield' 
   "100 #{tertiary} #{secondary}" 
```

**Comment by MahtraDR** [comment]
This looks simple enough. I have the fix running, and will submit in a day or two.

**Comment by MahtraDR** [comment]
Suggested fix works.
