### ISSUE TITLE
tarantula.lic and safe pausing infinite loop

### ISSUE THREAD

**Issue by mikejcook** [rpherbig/dr-scripts#6226]
tarantula.lic, if it somehow runs into an issue where it chooses the last selected skillset again, has an issue where it will get stuck in an infinite loop. I'm not positive how it ran into the issue, but the script is designed to handle it. However, with the new pause functionality, it looks like that's been broken.

When the script tries to turn the spider, if it gets the message about [You need to vary which skillset, it will try to turn the spider again. Here's where our issue comes up. Upon getting back to turn_tarantula, DRC.safe_pause_list never returns a valid pause situation.

You can reproduce this by running combat-trainer somewhere safe-ish and then using the below script. Log of the actual incident at the bottom.

class ZzzTest

  def initialize

    testPause

    pause 5

    testPause

  end

  def testPause
     until @scripts_to_unpause = DRC.safe_pause_list
      echo("Cannot pause, trying again in 5 seconds.")
      pause 5
    end   
  end
end

ZzzTest.new

--- Lich: sanowret-crystal paused.
--- Lich: t2 paused.
--- Lich: hunting-buddy paused.
--- Lich: combat-trainer paused.
[tarantula: Pausing ["sanowret-crystal", "t2", "hunting-buddy", "combat-trainer"] to run tarantula]
[tarantula]>turn my harvester spider to Missile Mastery
You fiddle with the tiny levers and dials of the spider's mechanical abdomen.  The process is complex, but you feel an intuitive grasp of the mechanism from the moment you touch it.
However, your changes fail to lock into place.
[You need to vary which skillset you select with every use.  Weapons was your last used skillset.]
[tarantula]>study harvester spider
As you examine the harvester spider, intuitive knowledge of its function and mechanics spring into your short-term memory.  You are unable to capture the great majority of the information, but are able to concentrate on the broad strokes.
The harvester spider is imbued with an unknown psychic power that is concentrated in its venom and can be adjusted by TURNing the various dials and levers along its mechanical abdomen.  RUBing the spider will aggitate it to strike, injecting yourself with its psychic venom.  The exact nature of the venom and its physiological effects are vastly too complex for this transfer of knowledge to encompass, but it will do something to your mind to consume a portion of your memories and transform it into artifical memories that can be applied more broadly to like-skills.
In addition to this, you can tell that the spider can indulge in metallophagia.  If SHAKEn with forging metal in the other hand, the spider will consume it and somehow change its mechanical components to mirror its meal.
The spider is currently set to consume Melee Mastery experience and when last used gave unbidden knowledge of Weapons techniques.
Roundtime: 5 sec.
[tarantula: Cannot pause, trying again in 5 seconds.]

It then just gets stuck with this message repeating:
[tarantula: Cannot pause, trying again in 5 seconds.]

**Comment by BinuDR** [comment]
Try commenting out line 93 (`use_tarantula` ) and see if that fixes your problem.  I think that should take care of it, but it will make you wait an additional 20 seconds before the tarantula eats a skill.

Let me know if it works.  You can reach me on discord at Binu#1114 or @ me in the lich discord server.

If not, I have another solution as well.

**Comment by BinuDR** [comment]
Here's a PR for it, please test.

https://github.com/rpherbig/dr-scripts/pull/6231

**Comment by MahtraDR** [comment]
Resolved by https://github.com/rpherbig/dr-scripts/pull/6231
