### ISSUE TITLE
swapping a thin-bladed fan

### ISSUE THREAD

**Issue by Setvers** [rpherbig/dr-scripts#626]
so i skinned a monster, and it had a 'fang'  so when i tried to close it my weapon, it didn't.  needs an adjective like in the stow line.

You can't close that!
>
You'll need to close the fan before you put it away.
>
[combat-trainer]>close my fan
You can't close that!
>
[combat-trainer]>stow my thin-bladed.fan
You'll need to close the fan before you put it away.
>
[combat-trainer]>close my fan
You can't close that!

**Comment by rcuhljr** [comment]
Should be fixed, let us know if it's not closing fans properly.
