### ISSUE TITLE
Ignore Copper/Bronze again

### ISSUE THREAD

**Issue by Traik404** [rpherbig/dr-scripts#627]
Combat-train used to just pick up silver/gold/plat, now it picks up copper/bronze as well and after a few hours the weight really adds up. Can we ignore just those without ignoring all coins? Sure there's an easy way.

**Comment by rcuhljr** [comment]
It always picked up all coins other than an old bug where it would only pick up singular coin, which silver gold plat were rarely ever going to be more then that. You can use the loot_subtraction and additions keys in your yaml to remove `coin` and `coins`, and add in `silver coin`, `silver coins`, `gold coin`, `gold coins`...
