### ISSUE TITLE
combat-trainer: issue looting "crystal" into full pouch

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#6270]
[combat-trainer]>loot
> 
You search the Xala'shar conjurer.
The conjurer was carrying a huge clear crystal and a large indigo tanzanite!
> 
[combat-trainer]>stow crystal
But that is already in your inventory.
> 
[combat-trainer]>stow gem
You pick up a large indigo tanzanite.
You think the fuzzy gem pouch is too full to fit another gem into.
> 
[combat-trainer]>drop my crystal
But you aren't holding that.
> 
[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 27]
[combat-trainer: message: But you aren't holding that.]
[combat-trainer: checked against [/You drop/i, /What were/i]]
[combat-trainer: for command drop my crystal]

[combat-trainer]>remove my fuzzy pouch
You need a free hand for that.
>
[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 40]
[combat-trainer: message: You need a free hand for that.]
[combat-trainer: checked against [/You remove/i]]
[combat-trainer: for command remove my fuzzy pouch]

[combat-trainer]>put my fuzzy pouch in my backpack
Perhaps you should be holding that first.

**Comment by Kiriawen** [comment]
that's an issue with you having a crystal on your person some place.

I'd suggest removing whatever "crystal" you have most likely worn and stowing it while hunting.

**Comment by mwest152** [comment]
It's a sanowret crystal

**Comment by Kiriawen** [comment]
doesn't invalidate my statement.  You currently have two options.  Remove the crystal from your body (just putting it into a bag would work) or add the crystal loot to loot_subtractions:

**Comment by Kiriawen** [comment]
we are not going to micro code for _every_ possibility.  Sometimes the scripts don't do what you want.  Adjust.

**Comment by mwest152** [comment]
All good, I was just trying to share my experience.  I don't know how to code personally, and don't know the difficulty of accounting for this particular scenario.  If I find something, I try to let the smarter people know about it.
