### ISSUE TITLE
tinker.lic couple little things

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#6287]
resume function doesn't seem to work

> ,tinker resume pelletbow
--- Lich: tinker active.

--- Lich: buff active.
--- Lich: buff has exited.

--- Lich: error: undefined method `work' for #<Tinker:0x0691d430>
	tinker:72:in `initialize'
	tinker:294:in `new'
--- Lich: tinker has exited.

------------
Not a big deal, but always tries to stow feet at end, but not putting away wood stain and hands are full if you use the "hold" arg.

**Comment by asechrest** [comment]
@Raykyn55 

The method `work` doesn't seem to be defined in this script. Unsure if it's a common method you're trying to lean on?

**Comment by Raykyn55** [comment]
This was resolved with #6293

**Comment by asechrest** [comment]
Per Raykyn55, closed as completed.
