### ISSUE TITLE
combat-trainer and wand-watcher conflict with held cambrinth

### ISSUE THREAD

**Issue by mikejcook** [rpherbig/dr-scripts#6297]
It looks like I ran into an issue where when wand-watcher paused combat-trainer, it somehow caused combat-trainer to skip over wearing my cambrinth armband, which ultimately caused the script to freeze up and die.

Here is the log as a pastebin: https://pastebin.com/dBxg3gXa

Line 7: CT invokes the armband as expected

Line 15-48: wand-watcher pauses the script and activates the wand. It lowers the armband and then retrieves it, all before unpausing.

From there, CT doesn't wear the armband. It just keeps it in my left hand.

Line 321: The end of the error message for trying to get my cutlass for off-hand attacks. After this, it just sits there and never executes another command.

It seems like the scripts did everything right, except that for some reason combat-trainer didn't think it needed to clean up my armband. Weird race condition or something? I'm not clear on how the safe pause stuff works, is there maybe a need to make CT flag itself as unsafe during the invoke method?

**Comment by MahtraDR** [comment]
Hey mate, I can't reproduce this. I'm going to guess this is happening at relatively low levels of arcana, since armbands usually hold 32 mana. So you wouldn't see this problem when having more than 164 Arcana, since it won't have to take the cambrinth off to charge.
