### ISSUE TITLE
Skinning not working for me in Combat-Trainer

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#631]
Greetings, 

I'm having an issue with skinning in combat trainer.  Below you can see my log.  It appears that if it is a critter i am not capable of skinning that i'll run into the issue.  Upon killing the first critter of the hunt, it will attempt to arrange, i fail miserably, cannot skin, and then on the following critter it doesn't attempt to arrange or skin.  Thoughts?

http://pastebin.com/3uhnp56a

**Comment by rpherbig** [comment]
Do you get Skinning exp for the first arrange? What about the failed second arrange?

The obvious fix is to try and arrange/skin on the next mob.

However, an option would be to instead cap your arranges to whatever # we just failed on and keep skinning. What do you think?

**Comment by wscherer420** [comment]
It can be hard to try and arrange on the second mob because the loot action happens so quickly.  I could cap the arrange to 1, but then it seems like the issue would occur if i fail miserably on the first try.  Which may be likely considering my skinning is much lower than what i'm hunting.  

I do get some skinning exp on that first arrange, not sure about the 2nd, i'll try to double check next time.

**Comment by rpherbig** [comment]
In your log, the first arrange ruins the corpse. The second arrange results in a message that indicates it can't be skinned, so combat-trainer stops trying.

I pushed a change that prevents that second arrange (i.e. the one after a failure). I'm not sure of the exact messaging of what will happen after this, so if you could test and report back, I'd appreciate it.

**Comment by wscherer420** [comment]
So i think that fixed it.  My guys seems to keep trying to skin on each kill regardless of success.  Thank you!
