### ISSUE TITLE
Combat-trainer clutter management

### ISSUE THREAD

**Issue by drboldwin** [rpherbig/dr-scripts#632]
Been playing with DUMP JUNK and seeing how we can use it to keep rooms clean (since enough clutter messes with DRRooms.npc and other such things.

It seems thrown items (items at your feet are safe and items that have hit the ground within maybe 30 seconds (from a loot/arrows or whatnot) are safe also.  With the current loot process it should stand to reason there is minimal risk involved in using dump junk.  Although I would suggest making it something that you toggle on in your yaml - dump_junk: true

For testing purposes I made it into a training ability and have been using it - this is not how it should be implemented but to give an idea:

----------------------------------------------------------------
when 'Dump Junk'
  dump_junk(game_state)
end

def dump_junk(game_state)
  if DRRoom.room_objs.size <= 12
  reset_ability(game_state, 'dump_junk')
  return
  end
  fput "dump junk"
end

-------------------------------------------------------------------

I would have done it somewhere else but didn't know the best way to keep it from spamming the ability (since it takes 300 seconds between the command and the janitor) perhaps some use of dump_junk.time but I haven't dealt with those attributes yet.  (still learning!)

**Comment by drboldwin** [comment]
------------------------------------------------------------

  def initialize(settings)
    echo('New LootProcess') if $debug_mode_ct
    skinning = settings.skinning({})

    @skin = skinning['skin'] || false
    echo("  @skin: #{@skin}") if $debug_mode_ct

    @arrange_all = skinning['arrange_all'] || false
    echo("  @arrange_all: #{@arrange_all}") if $debug_mode_ct

    @arrange_count = skinning['arrange_count'] || 0
    echo("  @arrange_count: #{@arrange_count}") if $debug_mode_ct

    @tie_bundle = skinning['tie_bundle'] || false
    echo("  @tie_bundle: #{@tie_bundle}") if $debug_mode_ct

    @arrange_types = skinning['arrange_types'] || {}
    echo("  @arrange_types: #{@arrange_types}") if $debug_mode_ct

    @lootables = settings.lootables([])
    echo("  @lootables: #{@lootables}") if $debug_mode_ct

    thanatology = settings.thanatology({})
    @ritual_type = thanatology['ritual_type'] || {}
    echo("  @ritual_type: #{@ritual_type}") if $debug_mode_ct

    @necro = thanatology['necro'] || false
    echo("  @necro: #{@necro}") if $debug_mode_ct

    @spare_gem_pouch_container = settings.spare_gem_pouch_container
    echo("  @spare_gem_pouch_container: #{@spare_gem_pouch_container}") if $debug_mode_ct

    @gem_pouch_adjective = settings.gem_pouch_adjective
    echo("  @gem_pouch_adjective: #{@gem_pouch_adjective}") if $debug_mode_ct

    @loot_delay = 5 # in seconds
    @loot_timer = Time.now - @loot_delay
    echo("  @loot_timer: #{@loot_timer}") if $debug_mode_ct

    @loot_bodies = settings.loot_bodies
    echo("  @loot_bodies: #{@loot_bodies}") if $debug_mode_ct

    @loot_specials = settings.loot_specials
    echo("  @loot_specials: #{@loot_specials}") if $debug_mode_ct
	
    **@dump_delay = 300
    @dump_timer = Time.now - @dump_delay**
  end

  def execute(game_state)
    game_state.mob_died = false
    dispose_body(game_state)
    stow_lootables(game_state)
    if (game_state.mob_died || game_state.npcs.empty?) && game_state.finish_killing?
      echo('LootProcess::clean_up') if $debug_mode_ct
      game_state.next_clean_up_step
    end
    **if (DRRooms.room_objs >= 13 && Time.now - @dump_timer < @dump_delay)
      fput DUMP JUNK
    end**
    return true if game_state.finish_spell_casting? || game_state.stowing?
    false
  end

----------------------------------------------------------

Something like that maybe?

**Comment by drboldwin** [comment]
The key parts being at the very bottom:
```
  if (Time.now - @dump_timer < @dump_delay) && dump_junk
    if DRRoom.room_objs.count >= 13
      fput DUMP JUNK
      @dump_timer = Time.now
    end
  end
```

and in the first part def initialize(settings)

```
    @dump_junk = settings.dump_junk
    @dump_delay = 300 # in seconds
    @dump_timer = Time.now - @dump_delay
```

**Comment by drboldwin** [comment]
I've tried and tried and can't get this damn timer to work.  As I have it right now it is just this:

```
    @dump_junk = settings.dump_junk
  end

  def execute(game_state)
    if @dump_junk
      if DRRoom.room_objs.count >= 13
        fput "DUMP JUNK"
      end
    end
```

The first bit being at the bottom of def initialize(settings) function and the second bit being at the very top of   def execute(game_state) function.

this does purge the room after 13 or more items with a DUMP JUNK
but it continues to send that command until the room is paused whenever it swings through def execute(game_state) (average 15-25 seconds or so)

The game sends back the # of time left before janitor comes with these inquiries so it isn't super problematic but not as clean as I would like.

This is set so you need to toggle it on in your YAML.

Also I don't know that this is the best place to put the check.  But I wasn't sure where would be and I knew at least here it would get executed at a fairly respectable rate.

**Comment by rpherbig** [comment]
I think your timer code was pretty close to what you wanted. Where you have `if (Time.now - @dump_timer < @dump_delay)`, you actually want `>`.

**Comment by rpherbig** [comment]
Also, the second part of that `if` was `dump_junk`, when you really want `@dump_junk` (if I'm reading the code right).

**Comment by drboldwin** [comment]
```
    @dump_junk = settings.dump_junk
    @dump_delay = 300 # in seconds
    @dump_timer = Time.now - @dump_delay
  end

  def execute(game_state)
    echo("  @dump_timer: #{@dump_timer}")
    if (Time.now - @dump_timer < @dump_delay) && dump_junk
      if DRRoom.room_objs.count >= 13
        fput "DUMP JUNK"
        @dump_timer = Time.now
      end
    end
```

**Comment by drboldwin** [comment]
I have dump_timer echoing out as you can see but it never changes...  Always returns

[combat-trainer:   @dump_timer: 2016-08-19 21:49:45 -0400]

The timer should be changing shouldn't it?

**Comment by rpherbig** [comment]
It won't change for 5 minutes.

**Comment by rpherbig** [comment]
To elaborate, `@dump_timer` is set when `dump junk` is sent. It will remain the same until it is set again, which requires `@dump_delay` seconds (5 minutes) to elapse.

**Comment by rpherbig** [comment]
By the way, the `-0400` is your time zone offset, which won't change even when `@dump_timer` is set.

**Comment by drboldwin** [comment]
This seems to be working now.  Will pull after a little more testing (probably tonight)

**Comment by drboldwin** [comment]
Final code is here:

```
    @dump_junk = settings.dump_junk
    @dump_delay = 300 # in seconds
    @dump_timer = Time.now - @dump_delay
  end

  def execute(game_state)
    if (Time.now - @dump_timer > @dump_delay) && @dump_junk
      if DRRoom.room_objs.count >= 13
        fput "DUMP JUNK"
        @dump_timer = Time.now
      end
    end
```

**Comment by rpherbig** [comment]
fea5c5791e6f3a299a34fbbcef2d43016143f6e6
