### ISSUE TITLE
Hunt training_ability check

### ISSUE THREAD

**Issue by skinnybb** [rpherbig/dr-scripts#635]
Is it possible to make the Hunt training_ability in combat-trainer check Scouting for a Ranger? Or make it configurable which skill it checks? When I lock perception in combat, this won't fire and I don't train Scouting.

**Comment by rpherbig** [comment]
Is it too hacky to make a new ability 'Scout' which checks 'Scouting'? You'd hunt twice occasionally, until one or both gets locked.

**Comment by rcuhljr** [comment]
I'd probably rather just expand our logic a bit to map `training -> [skills]`

**Comment by rpherbig** [comment]
That won't quite get is there since the scouting check has to be
conditional on if you are a ranger or not
