### ISSUE TITLE
Items at feet

### ISSUE THREAD

**Issue by Raykyn55** [rpherbig/dr-scripts#6359]
Like to add a few lines to global_defs, but don't see a way through the repo:
```ruby

    elsif line =~ /^You notice.* at your feet, and do not wish to leave it behind/
      fput "lift"
      fput "stow"
      sleep 1
      put_dir.call
```
inside move method.
```
>;go2 pond
--- Lich: go2 active.
[go2: ETA: 0:00:02 (12 rooms to move through)]
[go2]>south
You notice some ojhenik potion at your feet, and do not wish to leave it behind.
>
[go2]>lift
You pick up the potion lying at your feet.
>
[go2]>stow
You put your potion in your entangling brambles.
>
[go2]>south
You notice some sufil sap at your feet, and do not wish to leave it behind.
>
[go2]>lift
You pick up the sap lying at your feet.
>
[go2]>stow
You put your sap in your entangling brambles.
>
[go2]>south
```
With the new lift verb, this doesn't require anything special wrt commands or methods, and will sort most (if not all) issues of moving with items at your feet.

**Comment by Raykyn55** [comment]
lines 606 to 610, but probably anywhere is fine.

**Comment by vtcifer** [comment]
global_defs are in the lich5 repo
https://github.com/elanthia-online/lich-5

**Comment by Raykyn55** [comment]
> global_defs are in the lich5 repo:
> 
> https://github.com/elanthia-online/lich-5/blob/staging/lib/global_defs.rb
> 
> *edit - more specific link

Thank you, submitted there.
