### ISSUE TITLE
Drinfomon should run exp and info commands.

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#64]

**Comment by rpherbig** [comment]
Audit our scripts for places wee run those two in set up

**Comment by rpherbig** [comment]
And circlecheck, but we don't have a label for that

**Comment by rcuhljr** [comment]
22494456e0ab1e7ada2c0cf454a6c97e3b61548a 839811d038928f9e5731b5584e429fd71b2aad62
