### ISSUE TITLE
Have ;afk send a message to ;chat when ;tendme is activated

### ISSUE THREAD

**Issue by Traik404** [rpherbig/dr-scripts#640]
A simple 'CharacterX has sprung a leak in room 1234' that could be turned on/off in yaml.

This would serve the dual purpose of both giving empaths a heads up for easy Empathy training and ;combat-trainers the ability to significantly lower the risk of long sessions.

Thoughts?

**Comment by drboldwin** [comment]
What about setting up a special channel for this?  Perhaps a way of automating joining that channel if that is toggled on?

**Comment by Kekahunadr** [comment]
ooh thats sounds interesting would like to be a part of that
