### ISSUE TITLE
exo weapon support

### ISSUE THREAD

**Issue by Traik404** [rpherbig/dr-scripts#641]
If anyone gets bored enough to write in support for exo weapons:

The Grey Raven ring would be nice to cycle all the weapon types, but I don't own one yet.

**Axe: Small Edge/Light Thrown**
**SHAKE**: You shake your exoskeletal axe, causing it to break apart into thousands of live spiders. The swarm of arachnids scuttles quickly up your arm, nestling themselves on your person until they finally melt and coagulate into a thick armband formed by joined segments of blackened carapace.
**TAP**: Your armband breaks apart explosively into thousands of swarming spiders, which scuttle down your arm in a frenzy! The arachnid wave flows as one, moving with an apparent collective consciousness. Your hand is covered with twisting and writhing legs, but only briefly as the spiders resolidify into a deep ebony exoskeletal axe.

**Claymore: 2HE**
**SHAKE**: You shake your exoskeletal claymore, causing it to break apart into thousands of live spiders. The swarm of arachnids scuttle quickly up your arm, nestling themselves on your person until they finally melt and coagulate into a polished deep ebony ring carved to resemble a curled millipede.
**TAP**: Your ring breaks apart explosively into thousands of swarming spiders, which scuttle down your arm in a frenzy! The arachnid wave flows as one, moving with an apparent collective consciousness. Your hand is covered with twisting and writhing legs, but only briefly as the spiders resolidify into a deep ebony exoskeletal claymore.

**Katar: Small Edge**
**SHAKE**: You shake your exoskeletal katar, causing it to break apart into thousands of live spiders. The swarm of arachnids scuttle quickly up your arm, nestling themselves on your person until they finally melt and coagulate into a deep ebony scarab amulet inset with emerald eyes.
**TAP**: Your amulet breaks apart explosively into thousands of swarming spiders, which scuttle down your arm in a frenzy! The arachnid wave flows as one, moving with an apparent collective consciousness. Your hand is covered with twisting and writhing legs, but only briefly as the spiders resolidify into a deep ebony exoskeletal katar.

**Comment by rpherbig** [comment]
Does the `transform` attribute do what you need? See https://github.com/rpherbig/dr-scripts/blob/70ab9400368aa68acda7a41630a8cd89a09fa1bb/profiles/Masah-setup.yaml#L25-L27 for an example

**Comment by Traik404** [comment]
It's close, couple minor things: It removes the item before doing the transformation verb, and tries to wear it again after transforming it back (it auto-wears the item when you shake the weapons).
