### ISSUE TITLE
smoke.lic Error running

### ISSUE THREAD

**Issue by Sanzia** [rpherbig/dr-scripts#6420]
Ran into two problems running the updated smoke.lic.  

First, is...

> --- Lich: error: smoke:143: syntax error, unexpected end, expecting end-of-input
C:/Ruby4Lich5/Lich5/lich.rbw:802:in 'eval'
C:/Ruby4Lich5/Lich5/lich.rbw:802:in 'block (2 levels) in <class:Script>'
--- Lich: smoke has exited.

The solution I applied to def get_cig? and appears to work is...

Change Line 65 to lower case unless.
Remove Line 69 between end and true. 

Second, is...

>--- Lich: error: undefined method `lower_ground' for DRCI:Module
	smoke:103:in `light_cig?'
	smoke:59:in `initialize'
--- Lich: smoke has exited.

When I checked against DRCI, the call for lower_ground incorrect and should be lower_item?  I think the solution is;

Change 
DRCI.lower_ground(@cigar) 
to
DRCI.lower_item?(@cigar)

With these two changes, I'm puffing away to my heart's content.   I plan to explore and get more familiar with GitHub and read up on this process.

**Comment by MahtraDR** [comment]
Would you mind testing out the version in https://github.com/rpherbig/dr-scripts/issues/6420  for me? 

Thanks!

**Comment by Sanzia** [comment]
On it....Will report back in a few.

**Comment by MahtraDR** [comment]
I've never used this script. What do I need to use it to test it?

**Comment by Sanzia** [comment]
Um..If you want to test in game, I can met you and give you stuff.  Basically flint, blade and cigar.  I think it may have to do with the changes in the arg definitions in the beginning.

**Comment by Sanzia** [comment]
Also need to add some yaml settings.
####################################
# SMOKE SETTINGS
####################################
smoke:
  cigar_container: cigar.case
  smoke_image:
  lighter:
    type: flint
    container: cigar.case
    blade: haralun broadsword

**Comment by Sanzia** [comment]
But give me some more time...I may be able to solve it.  Haven't given up yet.  Let me try a few more things.

**Comment by Sanzia** [comment]
I hate to admit this...but it's working.  I was working on the wrong file.  You are good to go on this from my perspective.  No issues.  Thanks for the update and sorry for the confusion.  I will get better with my file management.

**Comment by MahtraDR** [comment]
Hah. Whoops. I bought a cigar. I can't get this thing to go at all. :D

**Comment by Sanzia** [comment]
Give me a room number and I'll meet you if you want.

**Comment by Sanzia** [comment]
I'm at the cemetery outside the east gate.  Rm 1742

**Comment by MahtraDR** [comment]
I got it! I was trying to light the cigar in the shop, and that wasn't working well... 
```
2023-02-24 15:19:45 NZDT: [smoke]>light cigar with my flint
2023-02-24 15:19:45 NZDT: You strike a piece of black flint with a kertig pasabas while holding it over a thin Purple Lion cigarillo causing sparks to fly.  Some of the sparks land on the Purple Lion cigarillo and with a few quick breaths
 in the right place you manage to get a flame going.
2023-02-24 15:19:45 NZDT: "Burning something as valuable as this might not be a good idea," you worry,  but the flames turn out to be merely a piece of the black flint which broke off and it quickly goes out.
2023-02-24 15:19:45 NZDT: [smoke]>sheath my pasabas
```

Left that room and it works now. :)

**Comment by Sanzia** [comment]
Nice....way to add another vice to your life.
