### ISSUE TITLE
Specific Target for spells

### ISSUE THREAD

**Issue by drboldwin** [rpherbig/dr-scripts#643]
Alright this was requested so I threw together something that works but would like input if there is a better way to implement this:

I set it up so you add target_enemy: <enemy> to your yaml, ex:  target_enemy: reaver
and then on line 740 I added:

`.select { |spell| spell['target_enemy'] ? game_state.npcs.first == spell ['target_enemy'] : true }`

issues with this:
it is checking npc.first which isn't always the npc you are facing and so if a reaver walks in while I am facing a wind hound for example.  it will trigger the spell but cast at my current target.  is there a way to pull current target?

**Comment by drboldwin** [comment]
so can potentially check entire array with something like:

`.select { |spell| spell['target_enemy'] ? DRRoom.npcs.include?(spell['target_enemy']) : true }`

and then maybe in def prepare_spell we could add something along the lines of
`fput {('face', @target_enemy)} if @target_enemy`
although that doesn't quite work but I'm just spitballing

**Comment by rpherbig** [comment]
718bae3bbc4e8728676d2cbbe0b1f65d7ac72a61
