### ISSUE TITLE
No paypal donation link

### ISSUE THREAD

**Issue by Traik404** [rpherbig/dr-scripts#647]
Anywhere.

This is a much better tool than Genie, let us contribute to a beer fund or something.

**Comment by rpherbig** [comment]
Code for a badge:

```
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=PUT ID HERE)
```

**Comment by rcuhljr** [comment]
I set up a paypal.me link, we should just be able to use this as our link anywhere and none of the charity related stuff. www.paypal.me/rcuhljr

**Comment by rpherbig** [comment]
Added to README
