### ISSUE TITLE
Commonize item scripts

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#65]
Also consider etreu.lic

**Comment by rpherbig** [comment]
And crossing-repair, but we don't have a label for that

**Comment by rcuhljr** [comment]
Use e2d9228557a40f8fe7ff5fd3669c5d634e04b5bc to update pick and others.

**Comment by rpherbig** [comment]
Pick: d9fb92eb775cb89aaa364bcba3a08d860c2320c6
Crossing-repair: c139299b25a327577036dbe5795f751b21c252c1
Forge: 8aa19b40e3bf186408d480e9e622e7cfe63d5fa0
Combat-trainer: 0afced76c205ada2623a3dc10d652ee41ab9d600
Crossing-training: 0afced76c205ada2623a3dc10d652ee41ab9d600
