### ISSUE TITLE
stow "second" emerald not working

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#651]
Suggest stow "gem" or maybe stow "other" emerald?

*********************************************

[combat-trainer]>stow first emerald

But that is already in your inventory.

[combat-trainer]>stow second emerald

Stow what?  Type 'STOW HELP' for details.

[combat-trainer]>circle

* A lesser dusky-scaled basilisk swipes a massive claw at you.  You dodge.  
[You're nimbly balanced and in better position.]
You fake a lesser dusky-scaled basilisk, first moving one way and then another, leaving it off balance.
[You're adeptly balanced and overwhelming opponent.]
Roundtime: 4 sec.

The swirling confines of malevolent darkness wane from about a lesser dusky-scaled basilisk.
You feel fully attuned to the mana streams again.
>stow gem
...wait 2 seconds.
* A lesser dusky-scaled basilisk swipes a massive claw at you.  You evade.  
[You're nimbly balanced and in better position.]
>stow gem

[combat-trainer]>attack

You pick up a tiny mint green emerald.
You open your pouch and put the mint green emerald inside, closing it once more.

**Comment by rcuhljr** [comment]
damn I hate DRs parser.

**Comment by rcuhljr** [comment]
Ok, trying other and seeing if it works better.
