### ISSUE TITLE
Zaulfang Swamp Claw - Death can be prevented if..........

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#653]
Would it be possible to have AFK kick in.....or even try to "escape" soon as claw grabs you?

******************************

A giant skeletal claw rises rapidly from the mire, lurching outward to grasp at you!  Your feet stick fast in the mire, and you can't manage to get out of the way fast enough.  The claw wraps its bony fingers around you and pulls you into its fist.
[Skeletal Claw]
A massive claw of bleached bone discolored with swamp sludge cradles you in its palm, jutting up from the marshy ground beneath it.  It's a wonder what beast this remnant once belonged to, or if it is in fact the remains of a natural creature at all.  The bony fingers are creeping slowly inward, and are close to trapping you inside.  You also see a pile of muddy sludge.
Obvious paths: out.
>
...wait 6 seconds.
>
[go2]>stand
You stand back up.
>
[go2]>southwest
You can't go there.
>
[go2: move: failed]
[go2: restarting script...]
[go2: error: your current room was not found in the map database]
--- Lich: go2 has exited.
[hunting-buddy: Failed to navigate to room 19435, attempting again]
[hunting-buddy: In an unknown room, manually attempting to navigate to 19435]
[hunting-buddy: failed to find a matching room]
--- Lich: combat-trainer active.
[combat-trainer]>stance set 100 40 40
Setting your Evasion stance to 100%, your Parry stance to 40%, and your Shield stance to 40%.  You have 5 stance points left.
>
[combat-trainer]>tap Glythtide orb
The orb is delicate.  Tapping it is not advised.
>
[combat-trainer]>open my hitman's backpack
That is already open.
>
[combat-trainer]>open my haversack
That is already open.
>
[combat-trainer]>open my baldric
That is already open.
>
[combat-trainer]>inv combat
All of your combat:

  a platinum parry stick inlaid with bands of jade
  a damite ring cap
  some damite ring greaves
  a damite ring mantle
  a damite ring tasset
  some insulated heavy burlap sleeves
  a damite targe
  a damite ring mask
  some blued steel elbow spikes shaped like sharp vulpine fangs
  some spiked knuckles
  some knee spikes
  some steel-toed footwraps
[Type INVENTORY HELP for more options]
>
[hunting-buddy: ***STATUS*** 240 minutes of hunting remaining or waiting on Large Edged, Staves, Tactics, Heavy Thrown, Brawling, Light Armor]
A runt-sized farm pig trots into the room.
>
[combat-trainer]>stance set 62 61 62
Setting your Evasion stance to 62%, your Parry stance to 61%, and your Shield stance to 62%.  You have 0 stance points left.
>
[combat-trainer]>infuse om 20
You tap into the mana from twenty of the surrounding streams and attempt to keep it channeling in a stream around you.
Roundtime: 1 sec.
You concentrate intently, attempting to infuse a generous amount of your harnessed mana into your active Osrel Meraud spell pattern.
Roundtime: 1 sec.
You sense that you were able to channel about two-thirds of your infusion's power into a brilliant orb of rippling cerulean light.  A faint tugging sensation emanates from the orb, as if it hungers for more.
>
[combat-trainer]>infuse om 20
You tap into the mana from twenty of the surrounding streams and attempt to keep it channeling in a stream around you.
Roundtime: 1 sec.
You concentrate intently, attempting to infuse a generous amount of your harnessed mana into your active Osrel Meraud spell pattern.
Roundtime: 1 sec.
You sense that you were able to channel about two-thirds of your infusion's power into a brilliant orb of rippling cerulean light.  A faint tingle washes through you as some of the energy is diffused, the orb having reached its full capacity.
>
Your body is dripping with water.  Pools of it are forming all around you.
>
[combat-trainer]>pre benediction 20
You feel fully rested.
>
That won't affect your current attunement very much.
You begin chanting a prayer to invoke the Benediction spell.
>
[combat-trainer]>charge my armband 25
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
Fitful sparks brighten and dim deep within the sky blue svelae on your forehead, swirling in a restless dance around its intaglio dark gold chrysanthemum.
>
The skeletal claw's bony fingers creep slowly inward.  You realize that it is now too late to slip out of the claw!
>
[combat-trainer]>charge my armband 25
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
[combat-trainer]>pray meraud
You glance heavenward and murmur to yourself, "Meraud, strengthen my magic that it not fail me in my time of need!"

You sense that you are as pure of spirit as you can be, and you are ready for whatever rituals might face you.

You feel that your gods have smiled upon you for your attempts to please them.
[Praying for 6 sec.]
>
[combat-trainer]>invoke my armband
The armband pulses with Holy energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.
Roundtime: 1 sec.
>
You feel fully attuned to the mana streams again.
>
[combat-trainer]>hunt
You find yourself unable to hunt in this area.
>
[combat-trainer]>perc
You reach out with your senses and see brilliant (17/21) streams of golden Holy mana radiating through the area.
You sense the Bless spell upon you, which will last for about three roisaen.
You sense the Murrula's Flames spell upon you, which is linked to your Osrel Meraud orb.
You sense the Glythtide's Gift spell upon you, which is linked to your Osrel Meraud orb.
You sense your Osrel Meraud spell linking you to a brilliant orb of rippling cerulean light, which should last until you release it.
You sense the Centering spell upon you, which will last for about three roisaen.
You sense the Persistence of Mana spell upon you, which is linked to your Osrel Meraud orb.
You are preparing the Benediction spell at twenty mana.
Roundtime: 3 sec.
>
The skeletal claw's bony fingers creep slowly inward.
>
You feel fully prepared to cast your spell.
>
[combat-trainer]>cast
You make a holy gesture and intone reverently, "Glythtide, hear my plea!"

Your armband emits a loud *snap* as it discharges all its power to aid your spell.
You suddenly feel more limber, your reflexes charged with a strong energy.
Suddenly your muscles flood with energy, singing with a strong vigor.
A surge of strong energy tingles through every nerve in your body, leaving you feeling more dexterous.
>
[combat-trainer]>rub my Glythtide orb
As you rub the Glythtide orb, it glows slightly more intensely and you feel a strange tugging, as if something has been moved from you to the orb.  You sense, though, that your sacrifice is not yet fully prepared.
>
[combat-trainer]>pre MAPP 20
That won't affect your current attunement very much.
You begin chanting a prayer to invoke the Major Physical Protection spell.
>
[combat-trainer]>charge my armband 25
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
You feel fully rested.
>
[combat-trainer]>charge my armband 25
>
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
[combat-trainer]>invoke my armband
The armband pulses with Holy energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.
Roundtime: 1 sec.
>
The skeletal claw's bony fingers creep slowly inward.
>
You feel fully attuned to the mana streams again.
>
You feel fully prepared to cast your spell.
>
[combat-trainer]>cast
You gesture.
Your armband emits a loud *snap* as it discharges all its power to aid your spell.
A bright silver nimbus roars up around you as streaks of steel-blue light descend in a convex field.
A sense of calm focus takes hold as the luminous pattern washes over you.  You feel moderately more able to avoid attacks with your energized joints.
>
[hunting-buddy: ***STATUS*** 239 minutes of hunting remaining or waiting on Large Edged, Staves, Tactics, Heavy Thrown, Brawling, Light Armor]
[combat-trainer]>pre pfe 20
That won't affect your current attunement very much.
You begin chanting a prayer to invoke the Protection from Evil spell.
>
[combat-trainer]>charge my armband 25
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
You feel fully rested.
>
[combat-trainer]>charge my armband 25
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
Your body is continuing to drip water everywhere.
>
[combat-trainer]>invoke my armband
>
The skeletal claw's bony fingers creep slowly inward.
>
The armband pulses with Holy energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.
Roundtime: 1 sec.
>
You feel fully attuned to the mana streams again.
>
You feel fully prepared to cast your spell.
>
[combat-trainer]>cast
You gesture.
Your armband emits a loud *snap* as it discharges all its power to aid your spell.
You are bathed in a soft white glow for a moment.
>
[combat-trainer]>pre rw 25
That won't affect your current attunement very much.
You begin chanting a prayer to invoke the Righteous Wrath spell.
>
[combat-trainer]>charge my armband 25
You feel fully rested.
>
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
The skeletal claw's bony fingers creep slowly inward.
>
[combat-trainer]>charge my armband 25
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
[combat-trainer]>invoke my armband
>
The armband pulses with Holy energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.
Roundtime: 1 sec.
>
Soft plumes of golden light blossom deep within the sky blue svelae on your forehead, playing off the skin around your eyes.
>
You feel fully attuned to the mana streams again.
>
[combat-trainer]>hunt
You feel fully prepared to cast your spell.
>
You find yourself unable to hunt in this area.
>
[combat-trainer]>cast
You gesture.
Your armband emits a loud *snap* as it discharges all its power to aid your spell.
Your blood begins to boil and with a mighty shout you allow the rage within to flow outward for all to see.
>
You feel fully rested.
>
The skeletal claw's bony fingers creep slowly inward.
>
[combat-trainer]>pre Centering 20
That won't affect your current attunement very much.
You begin chanting a prayer to invoke the Centering spell.
>
[combat-trainer]>charge my armband 25
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
[combat-trainer]>charge my armband 25
>
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
[hunting-buddy: ***STATUS*** 238 minutes of hunting remaining or waiting on Large Edged, Staves, Tactics, Heavy Thrown, Brawling, Light Armor]
[combat-trainer]>invoke my armband
>
The armband pulses with Holy energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.
Roundtime: 1 sec.
>
Your body is still soaked.
>
You feel fully attuned to the mana streams again.
>
The skeletal claw's bony fingers creep slowly inward.
>
You feel fully prepared to cast your spell.
>
[combat-trainer]>cast
You gesture.
Your armband emits a loud *snap* as it discharges all its power to aid your spell.
The tingling sensation leaves you.
An odd tingling sensation spreads upward from your feet through your entire body.
>
[combat-trainer]>pre Bless 20
>
That won't affect your current attunement very much.
You begin chanting a prayer to invoke the Bless spell.
>
[combat-trainer]>charge my armband 25
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
You feel fully rested.
>
[combat-trainer]>charge my armband 25
You harness a moderate amount of energy and attempt to channel it into your armband.
You are able to channel all the energy into the armband.
The armband absorbs all of the energy.
Roundtime: 4 sec.
>
[combat-trainer]>invoke my armband
>
The armband pulses with Holy energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.
Roundtime: 1 sec.
>
[combat-trainer]>perc
You reach out with your senses and see brilliant (17/21) streams of golden Holy mana radiating through the area.
You sense the Benediction spell upon you, which will last for about thirty roisaen.
You sense the Bless spell upon you, which will last for about one roisan.
You sense the Murrula's Flames spell upon you, which is linked to your Osrel Meraud orb.
You sense the Glythtide's Gift spell upon you, which is linked to your Osrel Meraud orb.
You sense your Osrel Meraud spell linking you to a brilliant orb of rippling cerulean light, which should last until you release it.
You sense the Major Physical Protection spell upon you, which will last for about thirty-one roisaen.
You sense the Centering spell upon you, which will last for about thirty-three roisaen.
You sense the Protection from Evil spell upon you, which will last for about thirty-one roisaen.
You sense the Persistence of Mana spell upon you, which is linked to your Osrel Meraud orb.
You sense the Righteous Wrath spell upon you, which will last for about thirty-three roisaen.
You are preparing the Bless spell at twenty mana.
Roundtime: 3 sec.
>
The skeletal claw's bony fingers creep slowly inward.
>
You feel fully attuned to the mana streams again.
>
You feel fully prepared to cast your spell.
>
[combat-trainer]>cast self
You gesture.
Your armband emits a loud *snap* as it discharges all its power to aid your spell.
Your body tingles as the brilliant silver glow fades from around you.
A brilliant silver glow enwreathes your body.
>
You feel fully rested.
>
You feel fully attuned to the mana streams again.
>
The skeletal claw's bony fingers creep slowly inward.
>
A gentle sound mimicking the patter of a summer shower meets your ears as the a brilliant orb of rippling cerulean light floating near you shears apart in luminous waves, reforming seconds later into a more solid sphere.
>
[hunting-buddy: ***STATUS*** 237 minutes of hunting remaining or waiting on Large Edged, Staves, Tactics, Heavy Thrown, Brawling, Light Armor]
>
[combat-trainer]>hunt
You find yourself unable to hunt in this area.
>
Gilded plumes of light fall in glittering showers within your sky blue svelae, fading into oblivion just before they would reach the skin of your forehead.
>
The skeletal claw's bony fingers creep slowly inward.
>
The skeletal claw's bony fingers creep slowly inward.  Death approaches swiftly.

**Comment by rcuhljr** [comment]
Yeah, I'll map the hand room too so it's possible to escape.

**Comment by rcuhljr** [comment]
Ok, I tried mapping this room in the DB (9610) and giving it an out direction back to the swamp, as well as setting up afk to try and flee if it sees you in this room.
