### ISSUE TITLE
Still having issues with stowing emerald

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#654]
Stow other emerald not working.  Stow gem works.

***********************

[combat-trainer]>stow emerald

But that is already in your inventory.

[combat-trainer]>stow other emerald

Stow what?  Type 'STOW HELP' for details.
You feel fully rested.
You feel fully attuned to the mana streams again.
The spiritual weight lifts off of a lesser dusky-scaled basilisk.

[combat-trainer]>weave

You weave back and forth in a dance-like motion, drawing your opponent's attention away from the fight.
[You're winded, adeptly balanced and overwhelming opponent.]
Roundtime: 3 sec.

[hunting-buddy: ***STATUS*** 123 minutes of hunting remaining or waiting on Large Edged, Staves, Tactics, Heavy Thrown, Brawling]

You feel fully prepared to cast your spell.

[combat-trainer]>attack

>stow gem
< You slice a steel broadsword at a lesser dusky-scaled basilisk.  A lesser dusky-scaled basilisk fails to dodge.  The broadsword flashes with a brilliant silver light and lands a heavy strike (7/23) that scratches the basilisk's right arm.
[You're winded, adeptly balanced and overwhelming opponent.]
[Roundtime 4 sec.]
...wait 4 seconds.
The dusky-scaled basilisk stands back up.
* A lesser dusky-scaled basilisk pounds forward, clawing at you.  You evade.  
[You're winded, adeptly balanced and in superior position.]
* A lesser dusky-scaled basilisk pounds forward, clawing at you.  You block with a damite targe.  
[You're adeptly balanced and overwhelming your opponent.]

[combat-trainer]>stow my broadsword

>stow gem
You put your broadsword in your kidskin baldric.

[combat-trainer]>get my hhr'ata

You pick up a tiny mint green emerald.
You open your pouch and put the mint green emerald inside, closing it once more.

**Comment by rcuhljr** [comment]
Trying again.
