### ISSUE TITLE
pick.lic custom source arg 

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#6561]
Not a huge deal, but I know some people are working on this script so figured I'd throw this out there.  The custom source argument doesn't seem to work.

**Comment by vtcifer** [comment]
A quick glance at the code on my side, and I'm not sure why it wouldn't be.  Can you run with debug ( `;pick debug` + whatever other arguments you use)?

**Comment by vtcifer** [comment]
You have the syntax wrong
`pick source=lootpouch`
https://elanthipedia.play.net/Lich_script_repository#pick

**Comment by mwest152** [comment]
This is how I have i

```pick:
  picking_box_sources:
  - portal
  - carryall
  - carpetbag
  - haversack
  - imperial handbag
  - lootpouch
  # - backpack
  tend_own_wounds: true
  trap_blacklist:
  trap_greylist:
  - teleport
  - reaper
  - concussion
  - shrapnel
  blacklist_container: backpack
  too_hard_container: backpack
  trash_empty_boxes: false```

**Comment by vtcifer** [comment]
> This is how I have it
> 
> 
> 
> ```
> 
> pick:
> 
>   picking_box_sources:
> 
>   - portal
> 
>   - carryall
> 
>   - carpetbag
> 
>   - haversack
> 
>   - imperial handbag
> 
>   - lootpouch
> 
>   # - backpack
> 
>   tend_own_wounds: true
> 
>   trap_blacklist:
> 
>   trap_greylist:
> 
>   - teleport
> 
>   - reaper
> 
>   - concussion
> 
>   - shrapnel
> 
>   blacklist_container: backpack
> 
>   too_hard_container: backpack
> 
>   trash_empty_boxes: false
> 
> ```

Ok? Your yaml isn't important here. You're using the wrong syntax when you start the script. Read the link I pasted.

**Comment by mwest152** [comment]
Ah ok, I've never had to call an argument that way before, but that works.
