### ISSUE TITLE
Stop method does not retrieve thrown weapon

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#66]
[training-manager: 0 minutes of hunting remaining]

You feel fully attuned to the mana streams again.

[combat-setup]>loot

You search the ship's rat.
You find nothing of interest.

[combat-setup: check ability: Hunt {:check=>"Perception", :cooldown=>80}]

[combat-setup: check ability: Perc {:check=>"Attunement", :cooldown=>120}]

[combat-setup]>attack

There is nothing else to face!
What are you trying to attack?

[combat-setup: checking weapons as Large Blunt!=Large Edged]

[combat-setup]>wield sword

A ship's rat decays away.
You draw out your bastard sword from the weapon harness, gripping it firmly in your right hand.

[combat-setup]>retreat

You are already as far away as you can get!

[combat-setup]>stow right

You put your sword in your weapon harness.

--- Lich: combat-setup has exited.

[training-manager]>retreat

You are already as far away as you can get!

[training-manager]>retreat

You are already as far away as you can get!

--- Lich: go2 active.

[go2: ETA: 0:00:02 (10 rooms to move through)]

[go2]>northwest

You notice a steel throwing hammer at your feet, and do not wish to leave it behind.

**Comment by rcuhljr** [comment]
How did it end up on the ground? thrown can't exit without you picking up the weapon in a bput.

**Comment by rpherbig** [comment]
I suspect either something happened that caused me to not pick it up while training, or I manually restarted combat-setup with the hammer on the ground.

I haven't seen this behavior since, so I'll close this out and just keep my eyes open for it to happen again.
