### ISSUE TITLE
Astrology buffs

### ISSUE THREAD

**Issue by Setvers** [rpherbig/dr-scripts#660]
Astrology buffs don't seem to check to see if the buffs are up, it will recast them no matter what.

> conc
> Katamba is dominant, Xibar is strong, while Yavash's influence is weak.
> Moonlight Manipulation and Enlightened Geometry spells are favored.
> You sense the Clear Vision spell upon you, which will last for about fourteen roisaen.
> You sense the Aura Sight spell upon you, which will last for about nine roisaen.
> Roundtime: 6 sec.
> ;astrology
> --- Lich: astrology active.
> [astrology]>pre cv 1
> You raise your palms skyward, chanting the equation of the Clear Vision spell.

**Comment by rcuhljr** [comment]
Not really a bug, we don't know if the previous casting was low power or a symbiosis or something else. It seemed better to always refresh the spell at the specified power for scripts that are run infrequently, Pick, Stealing, and Astrology.

**Comment by rcuhljr** [comment]
That said, not against changing this behavior for Astrology, the downsides are less relevant than stealing or pick.

**Comment by rpherbig** [comment]
@Setvers How strongly do you feel about this change?

**Comment by rpherbig** [comment]
See discussion over in #1063
