### ISSUE TITLE
Steal script stopping because of night

### ISSUE THREAD

**Issue by drgabellia** [rpherbig/dr-scripts#661]
[Arthe Dale, Glaysker Lane - 1080]
As you pause for a moment on the cobblestoned lane, your eye is caught by the entrance to a squat stone building with a blue awning.  A dazzling silver sword has been securely mounted to the arched entryway above a small engraved plaque.  
Obvious paths: northeast, southwest.

> [go2]>go shop
> [Assuming you mean an arched entryway.]

The door is locked up tightly for the night.

> --- Lich: 'go2' has been stopped by steal.
> [steal]>open door
> --- Lich: go2 has exited.
> What were you referring to?

**Comment by rcuhljr** [comment]
Did the script actually stop? it should move onto the next store, or stop if that was the last one.

**Comment by drgabellia** [comment]
It was the first stop.  Script exited.

[go2]>go shop

[Assuming you mean an arched entryway.]

The door is locked up tightly for the night.

--- Lich: 'go2' has been stopped by steal.

[steal]>open door

--- Lich: go2 has exited.

What were you referring to?

[steal]>inv combat

All of your combat:

  a platinum parry stick inlaid with bands of jade
[Type INVENTORY HELP for more options]

[steal]>get my targe

You get a damite targe from inside your hitman's backpack.

[steal]>wear my targe

You slide your left arm through the straps on your targe and flex, gaining a feel for the targe's weight.

[steal]>get my ring.cap

You get a damite ring cap from inside your hitman's backpack.

[steal]>wear my ring.cap

You put a damite ring cap on your head.

[steal]>get my ring.mask

You get a damite ring mask from inside your hitman's backpack.

[steal]>wear my ring.mask

You attach a damite ring mask to your nose.

[steal]>get my ring.tasset

You get a damite ring tasset from inside your hitman's backpack.

[steal]>wear my ring.tasset

You put a damite ring tasset around your waist.

[steal]>get my ring.mantle

You get a damite ring mantle from inside your hitman's backpack.

[steal]>wear my ring.mantle

A runt-sized farm pig trots into the room.

[steal]>get my ring.greaves

You work your way into a damite ring mantle.
You get some damite ring greaves from inside your hitman's backpack.

[steal]>wear my ring.greaves

You attach some damite ring greaves to your legs.

[steal]>get my insulated.sleeves

You get some insulated heavy burlap sleeves from inside your hitman's backpack.

[steal]>wear my insulated.sleeves

You slip some insulated heavy burlap sleeves onto your hands.

[steal]>get my spiked.knuckles

You get some spiked knuckles from inside your kidskin baldric.
Commando Nideaya just arrived.

[steal]>wear my spiked.knuckles

You slide some spiked knuckles onto your hands and clench your fists to secure the fit.

[steal]>get my knee.spikes

Commando Nideaya sprints northeast.
You get some knee spikes from inside your kidskin baldric.

[steal]>wear my knee.spikes

You strap some knee spikes over your knees, doing a quick dip to check your mobility.

[steal]>get my steel-toed.footwraps

You get some steel-toed footwraps from inside your haversack.

[steal]>wear my steel-toed.footwraps

You slide some steel-toed footwraps on your feet and kick the ground to finish the fit.

[steal]>get my elbow.spikes

You get some blued steel elbow spikes shaped like sharp vulpine fangs from inside your kidskin baldric.

[steal]>wear my elbow.spikes

You place some blued steel elbow spikes shaped like sharp vulpine fangs onto your elbows and tighten the straps.  With a quick adjustment, you position the elbow spikes for maximum efficiency.

--- Lich: steal has exited.

**Comment by rcuhljr** [comment]
Were you capped on exp or had you recently stolen? I can't see anything that would lead to this, other than at night it would try every ten minutes to steal from the night stores.

**Comment by drgabellia** [comment]
had 0 in exp at the time, had not recently stolen.  I went thru my logs and saw other times when the script continued on when that particular store was closed.  If it happens again, I'll let you know.  Thanks for looking into it, appreciated.  :)
