### ISSUE TITLE
Spells Prepping and Targeting but not casting in combat-trainer

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#662]
My newbie necro is having trouble with combat-trainer.  Offensive spells are prepping and targeting, but not casting.  My character eventually releases to spell if it doesn't lapse on its own.

http://pastebin.com/9SdPLMku

**Comment by rcuhljr** [comment]
Can you provide a log of the behavior? It sounds like we're missing your targeting complete message.

**Comment by wscherer420** [comment]
http://pastebin.com/NpETLFit

**Comment by wscherer420** [comment]
The debilitation spell isn't casting either, it preps but doesn't cast.
