### ISSUE TITLE
bescort failure and exit in Gate of Souls

### ISSUE THREAD

**Issue by Donntae** [rpherbig/dr-scripts#6639]
bescort fails when leaving the Gate of Souls area after hunting.  The messaging is around line 314 of the log:
```
--- Lich: error: coerce must return [x, y]
	bescort:33:in `+'
	bescort:33:in `update_coords'
--- Lich: bescort has exited.
```
Log: https://pastebin.com/H98096jd

**Comment by Donntae** [comment]
```
R> ,e echo LICH_VERSION
--- Lich: exec1 active.
[exec1: 5.6.2]
--- Lich: exec1 has exited.
,e echo RUBY_VERSION
--- Lich: exec1 active.
[exec1: 2.6.6]
--- Lich: exec1 has exited.
```
The error in bescort occurs frequently enough to make me think it's not an extreme edge case, but not every hunting cycle. Thanks for looking into it.

**Comment by Donntae** [comment]
After taking a second look at the log around line 281, I think the problem is that even after moving, the room desc is exactly the same and bescort doesn't recognize that the character's moved. I'm not sure how bescort currently recognizes movement.

**Comment by Kiriawen** [comment]
There's really not much we can do to fix that area due to it being a shifting maze and having duplicate rooms.  Unless Simu changes the area this is likely as good as it's gonna get.

**Comment by Donntae** [comment]
Would it be possible to attempt a fail-safe restart of bescort instead of an exit under the condition that bescort times out due to lack of movement?

**Comment by MahtraDR** [comment]
Honestly, I'm inclined to not change bescort on this. Our support for mazes, and shifting rooms is very spotty at best. When @vtcifer said this was an edge case, I picture him meaning this isn't an area that is well used, or that people go to very often... I'm open to having someone else fix bescort for this use case, but there aren't a lot of people coding for lich right now, and of the ones here, I'm not sure any of us wants to dive into this. Sorry.

**Comment by Donntae** [comment]
No worries. I'll close it out. Thanks for giving it some consideration.

**Comment by MahtraDR** [comment]
Sorry on this one. The notion of having bescort navigate in and out of mazes is pretty awesome though, so we'll come back to this eventually (not this specifically, just this concept) Eventually... :)
