### ISSUE TITLE
Astrology set to "peer telescope" instead of "peer my telescope"

### ISSUE THREAD

**Issue by phenomstar** [rpherbig/dr-scripts#6645]
When astrology calls DRCMM.peer_telescope, it will send the command "peer telescope" instead of "peer my telescope". If you're in a room with telescopes, this will cause astrology to loop and not exit/move on as it will aim your telescope, but peer in a telescope that isn't aimed.

ETA: It does also send the command "aim telescope" vs. "aim my telescope", but it appears the game so far defaults to the telescope in hand for aiming, but not peering.

*walkingastro appears to have the same calls, but mooniefill specifies "my telescope"

**Comment by Kiriawen** [comment]
The easy answer is...

Don't train in a room with a standing Telescope.

**Comment by Kiriawen** [comment]
Buuuump. 

Note:  I have not seen any other reports of incidents on discord.  Is this still an issue?
