### ISSUE TITLE
Not tying Shovel back to Belt. 

### ISSUE THREAD

**Issue by jayRyan24** [rpherbig/dr-scripts#665]
Causes endless look in forge after mining occurs and doesn't retie the shovel to the belt, instead it is stowing it and then forge can't find it. 

Long but detailed.

http://pastebin.com/pvfTc2i4

**Comment by rpherbig** [comment]
Possibly related to #580 and/or #589 ?

**Comment by rcuhljr** [comment]
```>;k mining-buddy```

You killed mining buddy with your shovel out, so regular stow logic put it in your bag, since the next time mining-manager ran it found your shovel in your bag it put it back away in your bag.
