### ISSUE TITLE
inventory-manager.lic not saving vault items correctly?

### ISSUE THREAD

**Issue by mwest152** [rpherbig/dr-scripts#6655]
Only able to test with a standard vault, but can't search for items I've placed in my vault or on the shelf. (vault_regular)

**Comment by mwest152** [comment]
I also have an outdated version that does shadow servants as well.

**Comment by MahtraDR** [comment]
Can you paste some logs? Describe the issue a bit better?

**Comment by mwest152** [comment]
fixed common-items with Scrounger support.
