### ISSUE TITLE
[drinfomon.lic ] Commoners hang drinfomon due to empty skill list check.

### ISSUE THREAD

**Issue by vtcifer** [rpherbig/dr-scripts#6660]
https://github.com/rpherbig/dr-scripts/blob/529b1457173c94c6ce7f0942c9ff016f2b4aa0e7/drinfomon.lic#L1355

For commoners, the above check causes drinfomon to hang because it will never be filled.  This is caused by how the exp list is populated:

https://github.com/rpherbig/dr-scripts/blob/529b1457173c94c6ce7f0942c9ff016f2b4aa0e7/drinfomon.lic#L1316
The output of this command will only be skills which actually have ranks.  Commoners don't have ranks.

A better output is probably `exp 0`, but I'm not 100% sure on the impact of having skills with 0 rank in that list.  Some testing is going to be needed, as that's boundary case.

**Comment by MahtraDR** [comment]
Have you tested how this works for commoners? We can send `exp 0` only for commoners too.

**Comment by MahtraDR** [comment]
Did you get a chance to test? I'm inclined to just change to `exp 0` but it'd be nice to have someone test.
