### ISSUE TITLE
Refactor LootProcess.dispose_body with respect to Necromancer Rituals

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#667]
While working on #657 I found that `dispose_body` is handling necromancer rituals. I think if necromancer rituals are given their own handler then `dispose_body` becomes more readable. The method `check_thanatology` is performing rituals, so I would propose using `check_thanatology` to act as a handler for rituals, and a new method `do_ritual` for performing them.

**Comment by rpherbig** [comment]
@jandersson Are you working on this?

**Comment by jandersson** [comment]
Yes, I'll get started on this
