### ISSUE TITLE
Braiding grass not stopping for injury

### ISSUE THREAD

**Issue by hennii** [rpherbig/dr-scripts#671]
In crossing-training, in the braid_to_fail method, there's no handling for nerves too damaged to braid. Here's the messaging:
```
[crossing-training]>braid my grass
You are in no condition to do that!

....

[crossing-training: *** No match was found after 15 seconds, dumping info]
[crossing-training: messages seen length: 25]
...
[crossing-training: checked against [/You Need to have more/i, /Roundtime/i, /You need both hands to do that/i, /You can't braid the .* into your braided/i]]
[crossing-training]>forage grass
``

**Comment by rpherbig** [comment]
Should we call safe-room, or just abort braiding?

**Comment by jandersson** [comment]
Sort of related, but astrology suffers from the same problem. You can be too injured to use a telescope.

**Comment by hennii** [comment]
Abort would be my suggestion -- with damaged nerves you can still do other crossing-training activities.

**Comment by rcuhljr** [comment]
I'd vote for getting healed, spell casting with damage nerves leads to a spiral as well.

**Comment by rpherbig** [comment]
The casting with nerve damage spiral has caused us major problems in the
past.

We have a few examples somewhere of snap shotting your current room,
healing, then resuming. We may look at commonizing that.

**Comment by rpherbig** [comment]
This one happened to my Thief last night. I came back to 50 pieces of grass in my pack since the failure case stows it.
