### ISSUE TITLE
Updated Discord Link for Wiki?

### ISSUE THREAD

**Issue by fix-little-things** [rpherbig/dr-scripts#6718]
Hi,

The discord link on the wiki is outdated or invalid, could a new one be posted?

Thanks!

**Comment by Hiinky** [comment]
https://discord.gg/qy5k5Qy9Cu

**Comment by MahtraDR** [comment]
> The discord link on the wiki is outdated or invalid, could a new one be posted?

Link the Wiki page with the bad link? Thanks!

**Comment by MahtraDR** [comment]
This one won't expire. https://discord.gg/qz4VYnXtNp

I've updated the wiki. Thanks!
