### ISSUE TITLE
Crossing-repair commands sent out of order

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#673]
From @rcuhljr :

```
[crossing-repair]>remove my elbow.spikes

You slide some brass knuckles onto your hands and clench your fists to secure the fit.
You loosen the straps securing your elbow spikes and remove them.

[crossing-repair]>wear my spikes

[crossing-repair]>give my elbow.spikes to Catrox
```

**Comment by rpherbig** [comment]
I see bputs in `crossing-repair` (around lines 31-32) and `equipmanager` (`get_item?` and `get_item_helper`) which should prevent these sorts of issues.

I'm not seeing anything obvious that would have caused this, unless maybe the remove bput saw "You slide" (from the brass knuckles) and moved on. Maybe a short `pause 0.5` between each item in `crossing-repair`?

**Comment by rcuhljr** [comment]
We could add the noun into the regex for removal/wearing success.
