### ISSUE TITLE
Hunting buddies is broken for non-bescort zones

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#675]
Weeks reported that `hunting_buddies` isn't working in gryphons.

As far as I can tell, the lambda in `hunting-buddy` is never getting checked because `common-travel::find_empty_room` checks that `DRRoom.pcs.empty?` before calling the predicate.

It is still working for my guys, who are in geni, a bescort zone. This is because bescort uses its own logic in maze zones. That led to me noticing that the `hunting_buddies` logic was changed in de5bdd3a43ed1b3aec1a05eb85178e22fccfea12, but not in bescort. Should that also be changed?

**Comment by drboldwin** [comment]
for the time being I set common-travel's statement to:

```
  def find_empty_room(search_rooms, idle_room, predicate = proc { true })
    loop do
      search_rooms.each do |room_id|
        walk_to(room_id)
		
        return true if predicate.call
      end
```

which fixed the issue - but likely will raise more, I think with my setup as it is I may not run into any for the time being.

**Comment by rcuhljr** [comment]
Should have resolved the issues, thanks for noticing that find_empty_room was the real culprit.

**Comment by drboldwin** [comment]
This is now working properly
