### ISSUE TITLE
Updating Room 8775 for DRX (DR Plat)

### ISSUE THREAD

**Issue by TheRealSckank** [rpherbig/dr-scripts#6770]
Looking at the map json room 8775 is missing an obvious exit and this is causing the room to not be identified (which then causes workorders and smith scripts to fail).
EXISTING: ["Obvious exits: north."]
UPDATE: ["Obvious exits: north, south."]

Full Room Copy/Paste from DRX right now:
[Crossing Forging Society, Supplies]
A chamber with stone walls and a lofty, vaulted ceiling links the rooms of the forge.  Its high arches help to subdue the clangor, letting it rise and echo in the space overhead.  Waves of heat and flickering reddish light from the foundries to the west strive with the scream of the grindstones to the east and the pounding din of metal on metal from the smithies to the south.
You also see a large sign, a central arch, a western arch, an eastern arch and some broad stone doors.
Obvious exits: north, south.

**Comment by MahtraDR** [comment]
Hi there, the map is only ever for Prime on the server. For Plat/Fallen you have to manually download the map, and then do local edits to it. I don't have a Plat account, alas. If you pop over to Discord and DM me, I can walk you through this.
