### ISSUE TITLE
Weaponsmithing crafting for hatchet is mistakenly trying to use hilt instead of haft

### ISSUE THREAD

**Issue by TegCross** [rpherbig/dr-scripts#6821]
- name: a metal hatchet
  noun: hatchet
  volume: 7
  type: weaponsmithing
  work_order: true
  chapter: 1
  part:
  - hilt

should be - haft

**Comment by BinuDR** [comment]
Put in a fix for this.
https://github.com/rpherbig/dr-scripts/pull/6822

We'll close this issue as soon as that gets merged.

**Comment by TegCross** [comment]
Thanks!

**Comment by MahtraDR** [comment]
Thanks @BinuDR !
