### ISSUE TITLE
Alchemy & Remedies, I'm guessing

### ISSUE THREAD

**Issue by Kaesken** [rpherbig/dr-scripts#6837]
```
[alchemy]>forage belradi moss 
You manage to find some belradi moss.
Roundtime: 4 sec.
R> [alchemy]>put my belradi moss in my 
Please rephrase that command.
[alchemy]>forage belradi moss 
You really need to have at least one hand free to forage properly.
[alchemy: WARNING: hands not emptied properly. Stowing...]
[alchemy]>stow right
You put your moss in your wyvern skull.

Later.....

[remedy]>tap belradi in shadows
I could not find what you were referring to.
[remedy]>get my belradi
What were you referring to?
[remedy: ]
[remedy: You seem to be missing: belradi]
```

```
> l in skull
In the wyvern skull you see a sturdy textbook, a savage flamewood riste, a hhr'ata, a nightstick, a cast-iron frying pan, an omnibus almanac, a khor'vela medicine bowl, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss, some belradi moss and a lot of other stuff.
```

Totally missing belradi apparently.  I only have `craft Alchemy` set so I'm not sure where to go from here.  I found it funny but wasn't sure if I should post this or not, xD

**Comment by mikejcook** [comment]
Could you show me how you're calling remedy? I think you're doing it manually, not from workorders, right? I think you might need to specify "belradi moss" in quotes, rather than just belradi.

**Comment by Kaesken** [comment]
```
  start: 5
  scripts:
    - safe-room
    - get2 1052
    - buff regen
    #- craft alchemy
```

I have it commented out now because all it does.  I've not changed my yaml settings in over a year because it always worked.
Then all of a sudden a few days ago, it'll run the `alchemy` script and forage belradi grass, attempt to put it in a container I never have set which Mahtra stated was the `alchemy_herb_storage`.  So I set that up.  Which fixed the belradi grass of infinity collection.
Now despite me having mortar and pestle set in the alchemy tools section, goes to the Alchemy Station to use the grinder to turn the belradi moss into crushed belradi then attempt to put the belradi into [it comes up an empty space] and it gets stuck, error code (I'll have to check my logs to get it), stows it instead then repeats the belradi moss in the grinder and repeats indefinitely.

**Comment by Kaesken** [comment]
Here you go.  I manually called it as how I have it set in my YAML so I can get a log for you:

https://pastebin.com/SUd0Mmnm

It's never done this before up until 3 days ago after I chose Remedies for a career and added more techs.
Don't know if that makes any difference but that's the only thing I've changed and it was not yaml settings.

**Comment by Kaesken** [comment]
And here is the log from the time prior to Mahtra telling me about the `alchemy_herb_storage` of what it was doing before I added that into my yaml:

https://pastebin.com/AFWhdeLQ

**Comment by mikejcook** [comment]
When it's checking for the crushed herb, it's looking at a YAML setting herb_container. So you will want to set that to the container you want to put the crushed moss into (example below):

```
herb_container: shadows
```

It looks like the alchemy script (that craft calls) will always use a grinder or press, it doesn't use your mortar and pestle.

So, if you can set the herb_container: setting, that should fix the issue with getting stuck dealing with the crushed moss. And then hopefully that's all! If you see another issue, let me know.

**Comment by Kaesken** [comment]
Okies.  It just confused me because it's never done this before so I didn't know about the extra settings.  I'll add that and try it out again later.  

Thank you so much!
