### ISSUE TITLE
Combat-trainer fails to default back to ambush under various situations when training multiple weapons with the backstab:true flag set in YAML 

### ISSUE THREAD

**Issue by drsuik** [rpherbig/dr-scripts#687]
Combat-trainer fails to default back to ambush under various situations when training multiple weapons with the backstab:true flag set in YAML 

With a weaponless brawling (Brawling: '') entry in weapon_training: and the backstab: true flag set. The result was a hangup. Missing 'With your bare hands?'

With an unsuitable weapon (Large Edged) the result was a hangup. Missing 'This type of weapon is entirely unsuitable for backstabbing.' 

With a blunt weapon the message is 'It's called a backSTAB for a reason.  Get a weapon that can puncture something.'

I solved these by adding

@line 1226 in combat-trainer
if reget(5, 'With your bare hands?', 'This type of weapon is entirely unsuitable for backstabbing.')
	fput('attack back')
else
     game_state.action_taken
end
@line 1232 in combat-trainer
if reget(5, 'backSTAB')
	fput('attack back')
else
     game_state.action_taken
end

These additions allow combat-trainer to default to ambush on several weapons even with the backstab:true flag set.

**Comment by drsuik** [comment]
E gave me a solution to use the YAML flag backstab: <weapon> instead of backstab: true 

this works completely and requires no edit to combat-trainer.

The reason I set backstab: true was because of [https://elanthipedia.play.net/Lich_script_repository#combat-trainer](url)
which shows that :
backstab: true to use backstab to train backstabbing skill, defaults to ambush if the mob can't be backstabbed.

**Comment by rpherbig** [comment]
Fixed the wiki, thanks for catching that!
