### ISSUE TITLE
Mining Error

### ISSUE THREAD

**Issue by Sagadin** [rpherbig/dr-scripts#693]
There was a previous error E fixed in connection with this script along the mine_use_packet: false logic line.  As often as this script gets used (but not on that logic line) this one may be there too.

Essentially after searching a room for minerals and finding none, it errors out, apparently due to not seeing a roundtime come up.

[mine: *** No match was found after 15 seconds, dumping info]
[mine: messages seen length: 17]
[mine: message: You carefully scan the area and look for ways to excavate additional material.  Your analysis has revealed no additional resources to be unearthed here.]
[mine: message: A beisswurm slowly slithers toward you!]
[mine: message: * With pathetic timing, a beisswurm slices wide at you.  You evade.  ]
[mine: message: [You're solidly balanced and in better position.]]
[mine: message: A beisswurm slowly slithers toward you!]
[mine: message: * Looking as if this were a bad idea, a beisswurm bites at you.  You dodge.  ]
[mine: message: [You're solidly balanced and in strong position.]]
[mine: message: Wolf Scent  (5 roisaen)]
[mine: message: A beisswurm slowly slithers toward you!]
[mine: message: * As if fumbling muscle flab were natural, a beisswurm slices wide at you.  You block solidly with a gargoyle-hide targe with a reinforced design.  ]
[mine: message: [You're solidly balanced and in dominating position.]]
[mine: message: A beisswurm slowly slithers toward you!]
[mine: message: * Apparently without direction or thought, a beisswurm bites at you.  You block solidly with a gargoyle-hide targe with a reinforced design.  ]
[mine: message: [You're solidly balanced and opponent has slight advantage.]]
[mine: message: A beisswurm slowly slithers toward you!]
[mine: message: * Moving in like a timid schoolboy, a beisswurm bites at you.  You dodge.  ]
[mine: message: [You're solidly balanced and have slight advantage.]]
[mine: checked against [/roundtime/i]]
--- Lich: mine has exited.

**Comment by rcuhljr** [comment]
pushed a fix.
