### ISSUE TITLE
[script] [validate.lic] updates

### ISSUE THREAD

**Issue by Kiriawen** [rpherbig/dr-scripts#6939]
Updates for Validate.

check for deprecated or invalid settings in gear:

check for orphaned aliases.

https://discord.com/channels/745675889622384681/745675890242879671/1296690702742192129 various updates discussed here.

**Comment by MahtraDR** [comment]
Orphaned aliases and to an extent deprecated/invalid settings that are set to `false` we can't test for. We can test for settings set to `true` easily enough, like this
```
[validate: WARNING:< Gear entry {:adjective=>nil, :name=>"leathers", :is_worn=>false, :is_leather=>true} has deprecated is_leather setting.  >]
[validate: ERROR:< Gear entry {:adjective=>nil, :name=>"leathers", :worn=>true, :is_leather=>true} has incorrect worn setting. The correct setting name is is_worn.  >]
```
How much prettier do we need it than this?

**Comment by Kiriawen** [comment]
I don't particularly mind what the output looks like as long as it's able to get the information across
