### ISSUE TITLE
Put Forging on cooldown if all rooms are full

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#72]
They seem to stay full for minutes, not seconds

**Comment by rpherbig** [comment]
This might be generalized to the need for a "temporary" cooldown system. This is one example of where it would be useful; another would be forging (keep the skill marked as trainable, but until we support skill > 50 it won't do anything). Are there others?

**Comment by rpherbig** [comment]
FA can't be trained if Scholarship is < 40

Sorcery can't be trained if Sorcery is > 70

Grep for 'return if DRSkill' and that should help find others.

**Comment by rpherbig** [comment]
None of the magic skills train while < 40% mana. We could train something else while mana regens instead of sitting idle.

**Comment by rcuhljr** [comment]
6bd6643e241905e2f4662a7fb080e1a3ce70d5c8
