### ISSUE TITLE
Crossing-Training/Memorized Scrolls

### ISSUE THREAD

**Issue by Traik404** [rpherbig/dr-scripts#727]
Can't discern memorized scrolls, tries to prep at 0 mana, fails out crossing-train.

Need a way for it to check, or players to flag spells as memorized.

Also, would love to have a 'memorized spell list' so if you died and lost it, it'll go rebuy the ones from the crossing-scroll shop and re-memorize (for gauge, maf, etc common ones).

Thanks!

**Comment by rpherbig** [comment]
Can you get us a log of what you saw?

**Comment by Traik404** [comment]
(excerpt from spells) You have temporarily memorized the Manifest Force [maf] spell.

prep maf 0

You have no idea how to cast that spell.

**Comment by Traik404** [comment]
prep maf 1 works fine
