### ISSUE TITLE
Strip location specific data out of trainer

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#73]
This doesn't need to be crossing trainer, it can be N trainer where you provide a safe room, climbing objects, bank, etc.

**Comment by rpherbig** [comment]
Where 'N' would be, for example, theury_trainer.lic and such?

**Comment by kamarcum** [comment]
https://github.com/rpherbig/dr-scripts/issues/586 is relevant. It looks like `pick` is also pretty crossing specific.

**Comment by rpherbig** [comment]
See 8c7479fb0e54ee9401436246af6339d53bc7ed47
