### ISSUE TITLE
Warmage aether

### ISSUE THREAD

**Issue by Kekahunadr** [rpherbig/dr-scripts#736]
might there be a way tio implement a way to fill warmage aether somewhere in crossing trainer? by using summon admit? i made a crappy script (stormfront) to admit till full then summon weapon till locked maybe that can help?
[summon.txt](https://github.com/rpherbig/dr-scripts/files/454207/summon.txt)

**Comment by rpherbig** [comment]
What is your goal with this change?

Training Summoning is currently supported - `crossing-training` will attempt to summon a weapon, using admittance if you need more elemental charge.

**Comment by Kekahunadr** [comment]
I can train summoning but my aether is always empty, I never have enough to
summon my familiar

**Comment by Kekahunadr** [comment]
I don't quite know how to explain it but my pathway alignment never gets
filled when using trainer, it trains summon but not pathways si if
alignment is low It can't summon nothing

**Comment by rpherbig** [comment]
Maybe you could describe what you would prefer to happen?

**Comment by Kekahunadr** [comment]
Well maybe somewhere in the crossing trainer there can be soon summon
admit, since it has to sit to do it

**Comment by rpherbig** [comment]
It will summon admittance if it tries to do something but does not have
enough charge

**Comment by Kekahunadr** [comment]
i have i think all the things it says in order to fill it up, it only takes
about 5 or 6 roundtimes

**Comment by Kekahunadr** [comment]
so it dosent fill the pool just enough do do whats needed, cuz everytime i
run trainer when im done i cant summon a familiar cuz pools are empty lol

**Comment by rpherbig** [comment]
Crossing training actually intentionally empties your charge each time it
trains summoning.  because that directly translates into more experience
gain.

**Comment by Kekahunadr** [comment]
ooh ok so we can cancel my issues then :) sorry for the misunderstanding
i like more exp lol

**Comment by Kekahunadr** [comment]
mabe there can be a way to align to a pathway durring combat?? like pathway
damage or one of them.... there might be one aready i just havent found it

**Comment by rpherbig** [comment]
Use buff_nonspells. Check Torgro YAML.
