### ISSUE TITLE
combat-trainer dropped weapon while swapping

### ISSUE THREAD

**Issue by arkrail** [rpherbig/dr-scripts#741]
Mid hunt, combat-trainer dropped my bastard sword while attempting to switch it.  The janitor ended up getting it.

```
[combat-trainer]>stow my bastard.sword

* Looking as if this were a bad idea, an Endrus serpent slices wide at you.  You dodge, leaning just out of harm's reach.  
[You're solidly balanced with no advantage.]
You put your sword in your patched gearbag.

[combat-trainer]>get bundling rope

You get some bundling rope from inside your patched gearbag.

[combat-trainer]>bundle

You bundle up your wooden fang with your bundling rope.

[combat-trainer]>wear bundle

You sling a lumpy bundle over your shoulder.

[combat-trainer]>tie bundle

Once you've tied off your bundle, you can not unbundle.  If you're sure, TIE the bundle again.

[combat-trainer]>tie bundle

Using the length of the rope, you tie the bundle, forming it into a much tighter package.

[combat-trainer]>adjust bundle

You adjust your tight bundle so that you can more easily and more quickly fit in additional skins.

[combat-trainer]>get my bastard.sword

You get a steel bastard sword from inside your patched gearbag.

[combat-trainer]>swap my sword

* In a weak and directionless display of aggression, an Endrus serpent bites at you.  You dodge, moving out of the way.  
[You're solidly balanced with opponent in better position.]
You switch your sword so that you can use it as a two-handed edged weapon.

[combat-trainer]>swap my sword

You switch your sword so that you can use it as a heavy edged weapon.

[combat-trainer]>drop my sword

You drop a steel bastard sword.

[combat-trainer]>loot

The Endrus serpent closes to pole weapon range on you!
You search the Endrus serpent.
The serpent was carrying a tiny faceted sea-green andalusite!

[combat-trainer]>stow andalusite

You pick up a tiny faceted sea-green andalusite.
You open your pouch and put the sea-green andalusite inside, closing it once more.
An Endrus serpent crumbles into dust, which is quickly scattered by an errant breeze.

[combat-trainer]>hide

You melt into the background, convinced that your attempt to hide went unobserved.
Roundtime: 5 sec.
Appearing to have lost sight of its target, an Endrus serpent stops advancing.
The serpent tastes the air with a tongue of flickering vines, wagging its head to and fro.
An Endrus serpent has spotted you!
An Endrus serpent bares its teeth in a thorny grin as it finds your hiding place!
The Endrus serpent discovers you, ruining your hiding place!
* Moving inexpertly, an Endrus serpent bites at you.  You barely block with a reinforced cougar-hide targe.  
[You're solidly balanced with opponent in very strong position.]

[combat-trainer]>hide
```

**Comment by rcuhljr** [comment]
Let me know and I'll make you a new sword. Do you have a little more of the preceding log, preferably from about where the mob died?

**Comment by arkrail** [comment]
I found this error immediately proceeding the problem, the script glanced twice at my throwing hammer, but never stowed it.

[combat-trainer]>lob

< Moving fluidly, you lob a steel throwing hammer at an Endrus serpent.  An Endrus serpent attempts to dodge, receiving a glancing blow.  The hammer lands a hard hit (5/23) that bruises the chest with a blow to the ribcage.
The throwing hammer falls to the ground!
An Endrus serpent jackknifes a few times, then grows still, its body rapidly settling until it is little more than a pile of wood and vine.
[You're solidly balanced]
[Roundtime 2 sec.]
* Awkwardly, an Endrus serpent bites at you.  You partially block with a reinforced cougar-hide targe.  
[You're winded, solidly balanced with no advantage.]

[combat-trainer]>get my throwing hammer

You pick up the hammer lying at your feet.

[combat-trainer]>glance

You glance down to see a steel throwing hammer in your right hand and nothing in your left hand.

[combat-trainer]>glance

You glance down to see a steel throwing hammer in your right hand and nothing in your left hand.

[combat-trainer]>get my bastard.sword

You get a steel bastard sword from inside your patched gearbag.

[combat-trainer]>get my bastard.sword

You are already holding that.

[combat-trainer]>swap my sword

You must have two free hands to use the bastard sword two-handed.
The Endrus serpent begins to advance on you!
The Endrus serpent is still a distance away from you and is closing steadily.
* As if fumbling muscle flab were natural, an Endrus serpent bites at you.  You dodge, managing to get out of the way with a minimum of effort.  
[You're solidly balanced and opponent has slight advantage.]
* Looking as if this were a bad idea, an Endrus serpent bites at you.  You evade, jumping to one side.  
[You're solidly balanced and opponent has slight advantage.]
The Endrus serpent closes to pole weapon range on you!
The Endrus serpent closes to melee range on you!
* Ineptly, an Endrus serpent bites at you.  You partially block with a reinforced cougar-hide targe.  
[You're solidly balanced with opponent in good position.]
* Awkwardly, an Endrus serpent bites at you.  You partially block with a reinforced cougar-hide targe.  
[You're solidly balanced and have slight advantage.]

[combat-trainer: *** No match was found after 15 seconds, dumping info]

[combat-trainer: messages seen length: 14]

[combat-trainer: message: You must have two free hands to use the bastard sword two-handed.]

[combat-trainer: message: The Endrus serpent begins to advance on you!]

[combat-trainer: message: The Endrus serpent is still a distance away from you and is closing steadily.]

[combat-trainer: message: * As if fumbling muscle flab were natural, an Endrus serpent bites at you.  You dodge, managing to get out of the way with a minimum of effort.  ]

[combat-trainer: message: [You're solidly balanced and opponent has slight advantage.]]

[combat-trainer: message: * Looking as if this were a bad idea, an Endrus serpent bites at you.  You evade, jumping to one side.  ]

[combat-trainer: message: [You're solidly balanced and opponent has slight advantage.]]

[combat-trainer: message: The Endrus serpent closes to pole weapon range on you!]

[combat-trainer: message: The Endrus serpent closes to melee range on you!]

[combat-trainer: message: * Ineptly, an Endrus serpent bites at you.  You partially block with a reinforced cougar-hide targe.  ]

[combat-trainer: message: [You're solidly balanced with opponent in good position.]]

[combat-trainer: message: * Awkwardly, an Endrus serpent bites at you.  You partially block with a reinforced cougar-hide targe.  ]

[combat-trainer: message: [You're solidly balanced and have slight advantage.]]

[combat-trainer: message: [DRPrime]-DR:Keldakin: "I'll just not anchor to end of line and it should be resolved."]

[combat-trainer: checked against [/ heavy edged /i, /\bsword\b.*(heavy edged|two-handed edged|heavy blunt|light edged|medium edged|light blunt|medium blunt|light thrown|short staff)/i]]

[combat-trainer]>stow right

You put your hammer in your patched gearbag.

[combat-trainer]>swap my sword

You switch your sword so that you can use it as a two-handed edged weapon.

[combat-trainer]>swap my sword

You switch your sword so that you can use it as a heavy edged weapon.

[combat-trainer]>stance set 100 0 81

Setting your Evasion stance to 100%, your Parry stance to 0%, and your Shield stance to 81%.  You have 0 stance points left.

[combat-trainer]>arrange for skin

That creature cannot produce skins.

[combat-trainer]>arrange

You begin to arrange the serpent's corpse in a manner that, while making the process of obtaining a part more difficult, guarantees a greater reward.
Roundtime: 2 sec.
* Moving in like a timid schoolboy, an Endrus serpent bites at you.  You partially block with a reinforced cougar-hide targe.  
[You're solidly balanced with opponent in better position.]
* With pathetic timing, an Endrus serpent bites at you.  You partially block with a reinforced cougar-hide targe.  
[You're solidly balanced with opponent in good position.]

[combat-trainer]>arrange

You continue arranging the serpent's corpse in a manner that, while making the process of obtaining a part more difficult, guarantees a greater reward.
Roundtime: 2 sec.
You feel fully rested.

[combat-trainer]>arrange

You continue arranging the serpent's corpse in a manner that, while making the process of obtaining a part more difficult, guarantees a greater reward.
Roundtime: 2 sec.

[combat-trainer]>arrange

* Ineptly, an Endrus serpent bites at you.  You partially block with a reinforced cougar-hide targe.  
[You're solidly balanced with opponent in good position.]
You continue arranging the serpent's corpse in a manner that, while making the process of obtaining a part more difficult, guarantees a greater reward.
Roundtime: 2 sec.
* Tentatively, an Endrus serpent bites at you.  You dodge, leaning to one side.  
[You're solidly balanced and opponent has slight advantage.]

[combat-trainer]>arrange

You complete arranging the serpent's corpse in a manner that, while making the process of obtaining a part more difficult, guarantees a greater reward.
Roundtime: 2 sec.

[combat-trainer]>tap my bundle

I could not find what you were referring to.

[combat-trainer]>skin


Moving with impressive skill and grace, you effortlessly retrieve a perfect fang from the Endrus serpent.
Roundtime: 2 sec.
* As if fumbling muscle flab were natural, an Endrus serpent bites at you.  You evade, managing to get out of the way with a minimum of effort.  
[You're solidly balanced with opponent in better position.]
Some nearby vegetation rustles, heralding the arrival of an Endrus serpent.
The Endrus serpent begins to advance on you!
The Endrus serpent is still a distance away from you and is closing steadily.

[combat-trainer]>stow my bastard.sword

* Looking as if this were a bad idea, an Endrus serpent slices wide at you.  You dodge, leaning just out of harm's reach.  
[You're solidly balanced with no advantage.]
You put your sword in your patched gearbag.

[combat-trainer]>get bundling rope

You get some bundling rope from inside your patched gearbag.

[combat-trainer]>bundle

You bundle up your wooden fang with your bundling rope.

[combat-trainer]>wear bundle

You sling a lumpy bundle over your shoulder.

[combat-trainer]>tie bundle

Once you've tied off your bundle, you can not unbundle.  If you're sure, TIE the bundle again.

[combat-trainer]>tie bundle

Using the length of the rope, you tie the bundle, forming it into a much tighter package.

[combat-trainer]>adjust bundle

You adjust your tight bundle so that you can more easily and more quickly fit in additional skins.

[combat-trainer]>get my bastard.sword

You get a steel bastard sword from inside your patched gearbag.

[combat-trainer]>swap my sword

* In a weak and directionless display of aggression, an Endrus serpent bites at you.  You dodge, moving out of the way.  
[You're solidly balanced with opponent in better position.]
You switch your sword so that you can use it as a two-handed edged weapon.

[combat-trainer]>swap my sword

You switch your sword so that you can use it as a heavy edged weapon.

[combat-trainer]>drop my sword

You drop a steel bastard sword.

**Comment by rcuhljr** [comment]
thanks, that helps a ton, and could you list your yaml gear settings for the throwing hammer?

**Comment by arkrail** [comment]
erm, I had it mixed between the adjective and name.  Entirely my fault.  Closing the issue.  Sorry boss!

**Comment by rcuhljr** [comment]
I'll still toss in the free sword if you yell at me in game (Etreu). We should probably try and guard against this in the future regardless.
