### ISSUE TITLE
Astrology spams room with missing constellation

### ISSUE THREAD

**Issue by cynesis** [rpherbig/dr-scripts#744]
Suspect rotation of skybox hides a constellation. Re-observation suggested.

[astrology]>observe Weasel in sky

You scan the skies for a few moments.
You focus your enhanced sight, through some of the cloud cover, upon the Weasel.
All but the smallest bit of the Weasel is obscured by clouds.
You struggle to make your observation through the clouds.
The Weasel is the symbol of Huldah the trickster, and is found scampering across the early-morning southern horizon of the winter skies.
You see nothing regarding the future.
Roundtime: 20 sec.

[astrology]>observe Weasel in sky

You scan the skies for a few moments.
Your search for the constellation of the Weasel turns up fruitless.

**Comment by rcuhljr** [comment]
Probably fixed?
