### ISSUE TITLE
Better setup file creation

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#75]
simple version, use send and respond to construct their settings for them
complex version build a gui

**Comment by rcuhljr** [comment]
Do we still think this is the right way to go?

**Comment by rpherbig** [comment]
Is this ;edityaml ?

**Comment by rcuhljr** [comment]
Yeah.

**Comment by rpherbig** [comment]
I haven't used it myself. I also haven't observed it being updated as
settings change.

Have we had a new user try it?

**Comment by rpherbig** [comment]
Good enough. Further changes can be tracked in new issues.
