### ISSUE TITLE
Enable prep sym for use in combat-trainer

### ISSUE THREAD

**Issue by BastionWT** [rpherbig/dr-scripts#758]
Allowing the use of prep sym in the combat trainer buff spells would go a long way to dramatically speeding up magic training, while not capping casters out on their mana. Single command, used just before you would normally cast would do the trick.

**Comment by rcuhljr** [comment]
Probably also consider running cyclics for training on a ~5 minute cycle.

**Comment by BastionWT** [comment]
Cyclics on a 5 minute cycle would also make me so happy. Would help my Bard train again...as that's how he used to train in combat using SF scripts.
