### ISSUE TITLE
Combat-Trainer doesn't recognize being Calmed

### ISSUE THREAD

**Issue by Sagadin** [rpherbig/dr-scripts#766]
After being calmed by a warcat, combat-training doesn't know what to do for aiming or prepping combat spells. 

http://pastebin.com/9biWX1bg
http://pastebin.com/LCfYk2Yh

**Comment by rpherbig** [comment]
I added the messaging so you won't see the long wait times. However, we still need to decide what the right action to take is when those messages are seen...

**Comment by Sagadin** [comment]
I would propose repeating whatever the failed action was, though that could also get you into a loop if there are too many warcats that you're effectively action locked.  That would really though mean your trying to hunt outside your effective level, in which case combat-trainer isn't going to save you in any other case either.
