### ISSUE TITLE
Dependency crash

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#768]
```
--- Lich: error: undefined method `each' for "filters":String
	dependency:645:in `load_settings'
	dependency:588:in `run_queue'
```

**Comment by rcuhljr** [comment]
Can you reproduce this? It looks like an out of date status-monitor.

**Comment by rpherbig** [comment]
I was in a hurry so I deleted my `seen_messages_*.dat` which seems to have fixed it.

I think the root cause is `@extras` being a string, not an array. There's a check for this on line 626, but line 645 assumes it is always an array.

**Comment by rcuhljr** [comment]
it should always be an array, or at least that was the original intent, status-monitor is just calling it wrong.

**Comment by rpherbig** [comment]
I think there's another bug. On line 628 the iteration variable is called `_extra`, but line 629 uses `@extra`.
