### ISSUE TITLE
Zombie-Manager Script

### ISSUE THREAD

**Issue by ohbeanz** [rpherbig/dr-scripts#772]
**New Script Idea**:
- Handles the process of creating a zombie during/at the start combat
- Specify whether a zombie should be used in combat via ("use_zombie") option

**Comment by ohbeanz** [comment]
Probably will start working on this myself...

**Comment by jandersson** [comment]
Should I add messaging for the raise ritual to #767  ? Or do you think this should be completely decoupled from the rituals done in LootProcess?

**Comment by rpherbig** [comment]
In general I'm a fan of decoupling things as much as possible. That said, I don't know much about the specifics of zombies.

**Comment by ohbeanz** [comment]
Hmm, yeah maybe they should be be completely decoupled -- since the necro isn't really "looting" the body any more. :)

**Comment by jandersson** [comment]
But you will need to kill something and then keep it around, yes?

**Comment by ohbeanz** [comment]
Yes. I planned on putting some sort of override there so that bodies aren't looted before the script gets a chance to raise it.
