### ISSUE TITLE
More Calm Stuff (combat-trainer)

### ISSUE THREAD

**Issue by Sagadin** [rpherbig/dr-scripts#784]
Combat trainer still doesn't correctly recognize tactic movement (bob, weave, circle) - I would propose just skipping those responses and moving along with whatever was planned next.

Combat trainer also doesn't correctly handle being calmed early in the AIM process, as it will cause the player to drop focus on the target, leaving a response message of: "That weapon must be in your right hand to fire!" after finally not being calmed instead of firing.

When this happens I would suggest either immediately refiring (which would be a snapshot, and have a fair chance of missing depending on skill) or re-aiming (which could cause a long loop if there are many creatures that cast Calm).  I would think the snapshot would be the most preferable of those options in the long run.

**Comment by rpherbig** [comment]
Could you post a log of some of these events?

**Comment by Sagadin** [comment]
[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 32]
[combat-trainer: message: * As if fumbling muscle flab were natural, a vicious warcat rips with its curving sabre-like teeth at you.  You fend off some of the teeth with a haralun adze.  ]
[combat-trainer: message: [You're nimbly balanced and in better position.]]
[combat-trainer: message: Strangely, you don't feel like fighting right now.]
[combat-trainer: message: Senses of the Tiger  (8 roisaen)]
[combat-trainer: message: Skein of Shadows  (7 roisaen)]
[combat-trainer: message: Hands of Lirisa  (9 roisaen)]
[combat-trainer: message: See the Wind  (13 roisaen)]
[combat-trainer: message: Instinct  (7 roisaen)]
[combat-trainer: message: Manifest Force  (13 roisaen)]
[combat-trainer: message: Calm  (Fading)]
[combat-trainer: message: You feel fully rested.]
[combat-trainer: message: * Attacking poorly, a red bear orc scout claws at you.  You deflect little of the claw with a haralun adze.  ]
[combat-trainer: message: [You're nimbly balanced with opponent in strong position.]]
[combat-trainer: message: You suddenly feel considerably less calm than you have been.]
[combat-trainer: message: * With weak timing, a red bear orc scout bites at you.  You dodge, leaning to one side with no room to spare.  ]
[combat-trainer: message: [You're nimbly balanced with opponent in superior position.]]
[combat-trainer: message: * Trying weakly, a vicious warcat rips with its curving sabre-like teeth at you.  You dodge, just managing to get out of a tight spot.  ]
[combat-trainer: message: [You're nimbly balanced with opponent in better position.]]
[combat-trainer: message: * Moving poorly, a red bear orc scout claws at you.  You evade, just managing to get out of a tight spot.  ]
[combat-trainer: message: [You're solidly balanced with opponent in very strong position.]]
[combat-trainer: message: * Moving weakly, a red bear orc scout claws at you.  You evade, just stepping out of harm's way.  ]
[combat-trainer: message: [You're solidly balanced with opponent in very strong position.]]
[combat-trainer: message: Senses of the Tiger  (8 roisaen)]
[combat-trainer: message: Skein of Shadows  (7 roisaen)]
[combat-trainer: message: Hands of Lirisa  (9 roisaen)]
[combat-trainer: message: See the Wind  (13 roisaen)]
[combat-trainer: message: Instinct  (6 roisaen)]
[combat-trainer: message: Manifest Force  (13 roisaen)]
[combat-trainer: message: * Trying weakly, a vicious warcat rips with its curving sabre-like teeth at you.  You counter little of the teeth with a haralun adze.  ]
[combat-trainer: message: [You're solidly balanced with opponent in good position.]]
[combat-trainer: message: * Moving poorly, a red bear orc scout claws at you.  You dodge, barely stepping to one side.  ]
[combat-trainer: message: [You're solidly balanced with opponent in very strong position.]]
[combat-trainer: checked against [/roundtime/i, /There is nothing else/i, /You must be closer/i, /You must be standing/i]]
[combat-trainer]>attack

**Comment by Sagadin** [comment]
[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 47]
[combat-trainer: message: Strangely, you don't feel like fighting right now.]
[combat-trainer: message: You feel fully rested.]
[combat-trainer: message: * Moving poorly, a red bear orc scout claws at you.  You turn aside little of the claw with a haralun adze.  ]
[combat-trainer: message: [You're solidly balanced with opponent in very strong position.]]
[combat-trainer: message: * A red bear orc scout claws at you.  You repulse little of the claw with a haralun adze.  ]
[combat-trainer: message: [You're solidly balanced with opponent in very strong position.]]
[combat-trainer: message: * With poor timing, a vicious warcat lashes out with large, velvet-padded claws extended at you.  You repulse little of the claw with a haralun adze.  ]
[combat-trainer: message: [You're solidly balanced with opponent in good position.]]
[combat-trainer: message: * Moving weakly, a red bear orc scout claws at you.  You knock aside little of the claw with a haralun adze.  ]
[combat-trainer: message: [You're solidly balanced with opponent in strong position.]]
[combat-trainer: message: Circle: 52]
[combat-trainer: message: Showing all skills with field experience.]
[combat-trainer: message:           SKILL: Rank/Percent towards next rank/Amount learning/Mindstate Fraction]
[combat-trainer: message:     Shield Usage:    176 66% mind lock     (34/34)     Chain Armor:     53 33% mind lock     (34/34)]
[combat-trainer: message:        Defending:    176 90% mind lock     (34/34)   Parry Ability:    169 56% very rapt     (31/34)]
[combat-trainer: message:      Small Edged:    191 53% understanding (14/34)             Bow:    168 55% scrutinizing  (17/34)]
[combat-trainer: message:     Light Thrown:     20 74% thoughtful     (4/34)   Melee Mastery:    171 28% thoughtful     (4/34)]
[combat-trainer: message:  Missile Mastery:    154 03% examining     (13/34)      Life Magic:    197 81% mind lock     (34/34)]
[combat-trainer: message:       Attunement:    127 00% interested    (12/34)          Arcana:    161 52% very riveted  (29/34)]
[combat-trainer: message:     Augmentation:    179 62% considering    (6/34)    Debilitation:    109 89% nearly locked (33/34)]
[combat-trainer: message:          Utility:     77 39% thoughtful     (4/34)         Warding:     29 92% understanding (14/34)]
[combat-trainer: message:          Evasion:    201 23% mind lock     (34/34)      Perception:    310 07% very focused  (21/34)]
[combat-trainer: message:     Locksmithing:    151 02% thinking       (5/34)        Skinning:    199 14% mind lock     (34/34)]
[combat-trainer: message:         Scouting:    224 47% pondering      (7/34)     Engineering:    199 01% perusing       (2/34)]
[combat-trainer: message:      Scholarship:    205 44% thinking       (5/34) Mechanical Lore:    189 69% perusing       (2/34)]
[combat-trainer: message:        Appraisal:    217 73% perusing       (2/34)         Tactics:    119 26% studious      (19/34)]
[combat-trainer: message: Total Ranks Displayed: 4171]
[combat-trainer: message: Time Development Points: 287  Favors: 27  Deaths: 3  Departs: 0]
[combat-trainer: message: Overall state of mind: clear]
[combat-trainer: message: EXP HELP for more information]
[combat-trainer: message: Senses of the Tiger  (8 roisaen)]
[combat-trainer: message: Skein of Shadows  (7 roisaen)]
[combat-trainer: message: Hands of Lirisa  (9 roisaen)]
[combat-trainer: message: See the Wind  (13 roisaen)]
[combat-trainer: message: Calm  (Fading)]
[combat-trainer: message: Instinct  (7 roisaen)]
[combat-trainer: message: Manifest Force  (14 roisaen)]
[combat-trainer: message: You feel fully attuned to the mana streams again.]
[combat-trainer: message: * Attacking poorly, a red bear orc scout claws at you.  You dodge, barely twisting out of a tight spot.  ]
[combat-trainer: message: [You're solidly balanced with opponent in excellent position.]]
[combat-trainer: message: * A red bear orc scout claws at you.  You evade, barely leaning out of harm's reach.  ]
[combat-trainer: message: [You're solidly balanced with opponent in very strong position.]]
[combat-trainer: message: The orc scout looks down with a faintly surprised expression before collapsing upon the ground.]
[combat-trainer: message: * Trying weakly, a vicious warcat lashes out with large, velvet-padded claws extended at you.  You evade, stepping aside in the nick of time.  ]
[combat-trainer: message: [You're solidly balanced and opponent has slight advantage.]]
[combat-trainer: message: The scrub-oak limb rapidly decays away.]
[combat-trainer: message: You suddenly feel considerably less calm than you have been.]
[combat-trainer: checked against [/roundtime/i, /There is nothing else/i, /You must be closer/i, /You must be standing/i]]
[combat-trainer]>attack

**Comment by Sagadin** [comment]
Having problems finding a copy of a "That weapon must be in your right hand to fire!" happening, but that's the exact game return after "shoot" when aim has been interrupted by Calm.

**Comment by Sagadin** [comment]
This is the messaging.  In this case the warcat in question died in between aiming and being fired at, but the new warcat in the room drew the same message.

[combat-trainer: *** No match was found after 15 seconds, dumping info]
[combat-trainer: messages seen length: 31]
[combat-trainer: message: You notice a vicious warcat as it stealthily closes to pole weapon range on you.]
[combat-trainer: message: You point at a vicious warcat, ruining its attempt to advance unnoticed.]
[combat-trainer: message: You turn to face a vicious warcat.]
[combat-trainer: message: That weapon must be in your right hand to fire!]
[combat-trainer: message: Kintryn searches around for a moment.]
[combat-trainer: message: Manifest Force  (10 roisaen)]
[combat-trainer: message: See the Wind  (5 roisaen)]
[combat-trainer: message: Senses of the Tiger  (2 roisaen)]
[combat-trainer: message: Skein of Shadows  (11 roisaen)]
[combat-trainer: message: Instinct  (1 roisan)]
[combat-trainer: message: Hands of Lirisa  (3 roisaen)]
[combat-trainer: message: Kintryn crosses her arms and points in opposite directions.]
[combat-trainer: message: The vicious warcat closes to melee range on you!]
[combat-trainer: message: The orc scout lopes in with her smooth rocks raised.  Crouching down as she stops, she twists warily, surveying the area.]
[combat-trainer: message: A vicious warcat gestures at you.]
[combat-trainer: message: Vibrant orange flames seem to flicker in the vicious warcat's yellow eyes, capturing your attention with a mesmerising stare.]
[combat-trainer: message: You feel a wave of incredibly overpowering calmness wash over you and are unable to think angry thoughts long enough to act on them.]
[combat-trainer: message: The vicious warcat stalks into the area.]
[combat-trainer: message: You feel fully rested.]
[combat-trainer: message: You feel fully prepared to cast your spell.]
[combat-trainer: message: You suddenly feel considerably less calm than you have been.]
[combat-trainer: message: Raising its head, a vicious warcat emits a piercing yowl!]
[combat-trainer: message: A vicious warcat decays away, leaving behind not even a scrap of fur.]
[combat-trainer: message: Kintryn begins to advance on a vicious warcat.]
[combat-trainer: message: Manifest Force  (10 roisaen)]
[combat-trainer: message: See the Wind  (5 roisaen)]
[combat-trainer: message: Senses of the Tiger  (2 roisaen)]
[combat-trainer: message: Skein of Shadows  (11 roisaen)]
[combat-trainer: message: Instinct  (1 roisan)]
[combat-trainer: message: Hands of Lirisa  (3 roisaen)]
[combat-trainer: message: Kintryn closes to pole weapon range on a vicious warcat.]
[combat-trainer: checked against [/isn't loaded/i, /There is nothing/i, /But your/i, /you fire/i, /you poach/i, /I could not find/i, /with no effect and falls to the ground/i, /Face what/i, /How can you poach if you are not hidden/i, /your moving to fire went unobserved/i, /notices your attempt to remain hidden/i, /you don't feel like fighting right now/i]]
[combat-trainer]>cast

**Comment by Sagadin** [comment]
Another log with it on the same cat:

>
A vicious warcat gestures at you.
Vibrant orange flames seem to flicker in the vicious warcat's yellow eyes, capturing your attention with a mesmerising stare.
You feel a wave of incredibly overpowering calmness wash over you and are unable to think angry thoughts long enough to act on them.
>
[combat-trainer]>shoot
Strangely, you don't feel like fighting right now.
>
You feel fully prepared to cast your spell.
>
Kintryn closes to pole weapon range on a vicious warcat.
>
* With inexpert timing, a vicious warcat rips with its curving sabre-like teeth at you.  You dodge, ducking in the nick of time.  
[You're bruised, solidly balanced with no advantage.]
>
* Moving weakly, a red bear orc scout claws at you.  You evade, leaning to one side with no room to spare.  
[You're bruised, solidly balanced with opponent in strong position.]
>
[combat-trainer]>shoot
Strangely, you don't feel like fighting right now.
>
[combat-trainer]>shoot
Strangely, you don't feel like fighting right now.
>
[combat-trainer]>shoot
Strangely, you don't feel like fighting right now.
>
Kintryn closes to melee range on a vicious warcat.
>
[combat-trainer]>shoot
Strangely, you don't feel like fighting right now.
>
[combat-trainer]>shoot
Strangely, you don't feel like fighting right now.
>
* With inept movements, a vicious warcat rips with its curving sabre-like teeth at you.  You dodge, barely leaning out of harm's reach.  
[You're bruised, solidly balanced with no advantage.]
>
[combat-trainer]>shoot
Strangely, you don't feel like fighting right now.
>
[combat-trainer]>shoot
* Trying weakly, a red bear orc scout claws at you.  You barely block with a gargoyle-hide targe with a reinforced design.  
[You're bruised, solidly balanced with opponent in strong position.]
>
Strangely, you don't feel like fighting right now.
>
Kintryn feints a pattern-welded haralun pugio with a carved bloodwood handle at a vicious warcat.  The pugio lands a good strike (3/23) to its back!  
>
[combat-trainer]>shoot
Strangely, you don't feel like fighting right now.
>
You suddenly feel considerably less calm than you have been.
