### ISSUE TITLE
Add Shard Walls to Athletics Training

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#791]
I'd like to add the Shard walls to the athletics training portion of crossing-training by basically translating this https://elanthipedia.play.net/Climb_Shard_(script) to base-athletics

I notice the Crossing walls data is pulled from base-athletics. Any thoughts on how to add the Shard walls data to this and use it in `train_athletics`? I was thinking of making a new list on the same level as athletics_options, but named shard_options or shard_walls, then doing one of two things..
1. a shortest path calc to the first target in both athletics_options and shard_walls and use whichever list has shortest path to the first target.
2. if the person has `hometown: Shard` in their settings then pull the shard_walls list, else use athletics_options

The first would seem to work no matter what 'hometown' you have, the second one seems much easier to implement

**Comment by rpherbig** [comment]
I think I'd be in favor of making `base-athletics` follow `base-town` and the like: have a list for Crossing, a list for Shard, etc. and pick based on your hometown.

**Comment by rcuhljr** [comment]
I don't think the simple list of places is the correct looking term solution. Climbing should be outta own script and room lists may not even be in the tank since they are highly variable based on skill ranges, and we train climbing at least three different ways.

**Comment by jandersson** [comment]
Just spitballing here:

What about storing the data in a database (a relational one), querying it, the resulting query contains a 'recipe' so to speak. The script just follows the recipe. This could allow feedback from the script. I think you're doing something similar with steal.lic

**Comment by jandersson** [comment]
So just wanted to mess around with this on paper.. but heres a potential schema/query

rooms(id, province)
has_action(room_id, action_id)
actions(id, action, target, min_skill, max_skill)

```
select rooms.id, actions.action
from rooms
join has_action
on rooms.id = room_id
join actions
on actions.id = action_id
where rooms.province = 'zoluren'
and actions.max_skill < 100
and actions.min_skill > 50
```

**Comment by rpherbig** [comment]
I think step one of any approach is to break athletics training into its own script.

**Comment by jandersson** [comment]
I started by copying out the methods in crossing-trainer to an athletics script and just running that, the same way astrology is done. Noticing that there are some method calls in athletics that play zills, train outdoorsmanship, check research, and one called `check_osrel`. How should these be handled? 

Are these methods all candidates for common code or becoming their own scripts?
