### ISSUE TITLE
Attacked another player through trainer

### ISSUE THREAD

**Issue by Endraig** [rpherbig/dr-scripts#798]
Attacked warchyld during my goblin hunt about 7/8ths through this document, not sure what happened.

[Wallet(6) (1).txt](https://github.com/rpherbig/dr-scripts/files/473193/Wallet.6.1.txt)

**Comment by rpherbig** [comment]
This really makes no sense to me. On line 29604:
```
[combat-trainer]>aim

You begin to target a scavenger goblin.
```

Then a few bobs, then on line 29641:
```
[combat-trainer]>shoot

Your attempt is slightly hindered by your target shield.
< As if fumbling muscle flab were natural, you fire a boar-tusk arrow at Warchyld.  Warchyld dodges.  
The boar-tusk arrow lands nearby!
[You're adeptly balanced and in dominating position.]
[Roundtime 1 sec.]
```

Why would shoot be at a different target than the one at which you aimed?

**Comment by rcuhljr** [comment]
Looks like DR broke, maybe that's what they restarted the servers for?
