### ISSUE TITLE
Make stance syntax more flexible

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#8]
Make stance syntax (in the setup file) flexible enough that I could say "Weapon" => ["shield"] and it would determine the second defensive skill dynamically

**Comment by rcuhljr** [comment]
What's the use case on this guy? If I "Bow" =>["shield"] it could still decide to try and parry with the other skill.

**Comment by rpherbig** [comment]
I wanted this when I was having trouble in my hunting zone. My vision was that I could use this to force my best defense as my primary and then let the script dynamically figure out the second defense.

**Comment by rcuhljr** [comment]
I'd also like if it didn't switch to an improper stance until the weapons were ready, aka don't take out a bow while still in parry etc etc.

**Comment by rcuhljr** [comment]
I'm calling this closed with the addition of `priority_defense`.
