### ISSUE TITLE
Cast harmless spells while dancing

### ISSUE THREAD

**Issue by rcuhljr** [rpherbig/dr-scripts#81]
Continue to train debilitation when dancing, and use and TM spells flagged as harmless. (paralysis)

**Comment by rpherbig** [comment]
376bbbc82d6480fe2a4f8e4b2603695d9acce76d - close?

**Comment by rpherbig** [comment]
Note that this results in preparing harmless spells even while no mobs are in the room. The cast fails of course. This seems related to #70 .

**Comment by rpherbig** [comment]
@rcuhljr Can we close this? I'm not too worried about the prep/cast on empty room issue.

**Comment by rcuhljr** [comment]
I fixed it already.
