### ISSUE TITLE
A more fluid way of dealing with multiple cyclics (crossing-training)

### ISSUE THREAD

**Issue by drboldwin** [rpherbig/dr-scripts#820]
Currently multiple cyclics are not handled well under training_spells, I imagine this is because it casts a cyclic spell - then cancels it to cast the other one before training is actually gained.  So in order to make all the bards of the world happier I came up with a quick and easy fix idea that I think should work.

something along the lines of:

```
    while DRSpells.prep_spell
      data['before'].each { |action| bput(action['message'], action['matches']) }
      cast(data['cast'])
      data['after'].each { |action| bput(action['message'], action['matches']) }
      if data['cyclic']
        if @settings.training_spells['Warding']['cyclic']
          UserVars.crossing_timers['Warding'] = Time.now
        end
        if @settings.training_spells['Utility']['cyclic']
          UserVars.crossing_timers['Utility'] = Time.now
        end
        if @settings.training_spells['Augmentation']['cyclic']
          UserVars.crossing_timers['Augmentation'] = Time.now
        end
      end
    end
```

Then instruct people to add exp_timers for whatever spells they are using as cyclic.  

```
exp_timers:
  Warding: 300
  Utility: 300
```
So in theory I think this would - after the cast if the spell was cyclic it will check for other cyclic spells and reset their timers back to 0.  so no other cyclic spells will now be called for another 300 seconds, then whenever crossing-training hits that spell again (I imagine this wouldn't take long as it's exp would be low) it will swap cyclics and reset all their timers again.

**Comment by rcuhljr** [comment]
Actually know that we know what spells are cyclic due to spell data we should just stop requiring exp timers for cyclics and set them manually in training.

**Comment by drboldwin** [comment]
Aye - that works.  I find 300 seconds is a good amount of time for a cyclic spell to run before being released when training with it.

**Comment by rcuhljr** [comment]
Should work now, and you no longer need to set exp timers for cyclics.
