### ISSUE TITLE
moonwatch window not functioning in glitch

### ISSUE THREAD

**Issue by cynesis** [rpherbig/dr-scripts#824]
Neither auto-created "Moons" window nor user-created "moonWatch" window function with the moonwatch 'window' argument. Appears in Game window, instead.

Raw data:
<output class="mono"/>
--- Lich: moonwatch has exited.
<output class=""/>
<output class="mono"/>
--- Lich: moonwatch active.
<output class=""/>
<streamWindow id='moonWindow' title='Moons' location='center' save='true' />
<exposeStream id='moonWindow'/>
<clearStream id="moonWindow"/>
<pushStream id="moonWindow"/> [k]-(103) [y]+(100) [x]-(2)<popStream/>

**Comment by rcuhljr** [comment]
Could you test this? I tried a potential change.

**Comment by cynesis** [comment]
Still not behaving as expected. I can't see why, though. The XML stream looks well formed. Perhaps FE issue?

Three windows for testing; Moons, moonWatch, moonWindow
All three remain empty.

**Game window:**
,moonwatch window
--- Lich: moonwatch active.
\> 
\n
 [k]-(160) [y]+(140) [x]+(30)\n
\> 
\n
 [k]-(159) [y]+(139) [x]+(29)\n
\> 

**Raw data window:**
\<output class="mono"/\>
--- Lich: moonwatch active.
\<output class=""/\>
\<streamWindow id='moonWindow' title='Moons' location='center' save='true' /\>
\<exposeStream id='moonWindow'/\>
\<clearStream id="moonWindow"/\>\n
\<pushStream id="moonWindow"/\> [k]-(160) [y]+(140) [x]+(30)\<popStream/\>\n
\<clearStream id="moonWindow"/\>\n
\<pushStream id="moonWindow"/\> [k]-(159) [y]+(139) [x]+(29)\<popStream/\>\n
