### ISSUE TITLE
Need more lumber during carving.

### ISSUE THREAD

**Issue by jayRyan24** [rpherbig/dr-scripts#834]
Lumber goes to feet, I stow it, I retrieve it but need more. 

http://pastebin.com/AZftcf4T

**Comment by rcuhljr** [comment]
Did someone enable a crafting recipe with the wrong volume recorded?

**Comment by rpherbig** [comment]
According to the epedia page (https://elanthipedia.play.net/Weapon:Crook_(crafted)), it uses 5 volumes, which is what `base-crafting` has.
