### ISSUE TITLE
Hunting failed due to Combat-Trainer startup.

### ISSUE THREAD

**Issue by jayRyan24** [rpherbig/dr-scripts#846]
It appears that Combat-Trainer was trying to start a new one before closing the previous. 

http://pastebin.com/H2dgHyR3

After 
```
 
--- Lich: combat-trainer is already running (use ;force [scriptname] if desired).
 
--- Lich: combat-trainer has exited.
 
```

I didn't perform any other action, I just stood there.

**Comment by rcuhljr** [comment]
Should be fixed.
