### ISSUE TITLE
Path to endrus_serpents is broken right when you GO PATH to enter

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#847]
[go2: move: failed]
[go2: restarting script...]
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>go pa
You can't do that.
>
[go2: move: failed]
[go2: restarting script...]
>ctap pa
Please rephrase that command.
>
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>go pa
>tap pa
You can't do that.
>
[go2: move: failed]
[go2: changing Room[1923].timeto['9527'] to nil]
[go2: restarting script...]
You tap a broad-bladed parang with a ghostly white hilt inside your journey pack.
>
[go2: error: failed to find a path between your current room (1923) and destination room (9527)]
[go2: reverting Room[1923].timeto['9527'] back to 0.2]
--- Lich: go2 has exited.
Remedi's blighted gold bracelet flares with radiant light, and he looks more at ease than before.
>
[hunting-buddy: Failed to navigate to room 9527, attempting again]
--- Lich: go2 active.
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>**go pa**
You can't do that.
>
[go2: move: failed]
[go2: restarting script...]
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>**go pa**
You can't do that.

**Comment by rcuhljr** [comment]
fixed.
