### ISSUE TITLE
Add support for Barbarian Dual Load with bows.

### ISSUE THREAD

**Issue by jayRyan24** [rpherbig/dr-scripts#852]
I added support for Barbarians to use Dual Load with the bow. With how their buffs work, this is how I can see we must do it at this time. We just basically try to Dual Load if it's set to do so. If we can't, we just Load. If they are without Form Eagle, it is a bit spammy, but when the buff comes back up, it will remove it. Also, with Dual-Load, you'll only need 1-2 loads to gain the basic 3 mind levels to move onto your next weapon (if training many). 

Here is a combat-trainer example: http://pastebin.com/wVbZJzJg

Combat-Trainer, combat logic: 
```
    else
      if game_state.dual_load? && DRSpells.active_spells['See the Wind']
        pause 0.5 until bput('load arrows', 'You reach into', 'already loaded', 'Such a feat would be impossible without the winds to guide')
      elsif game_state.barb_dual_load?
        pause 1
		case bput('load arrows', 'You reach into', 'already loaded', 'but are unable to draw upon its majesty')
          when 'You reach into' 
		  when 'already loaded' 
          when 'but are unable to draw upon its majesty'
            pause 0.5 until bput('load', 'You reach into', 'You carefully load', 'already loaded')
		end
	  else
        pause 0.5 until bput('load', 'You reach into', 'You carefully load', 'already loaded')
      end
```
Combat-Trainer, boolean:
```
  def barb_dual_load?
    @barb_dual_load && weapon_skill == 'Bow' && DRSkill.getxp('Bows') < 200 && DRStats.barbarian?
  end
```
Combat-Trainer, initialize:
```
	@barb_dual_load = settings.barb_dual_load
    echo("  @barb_dual_load: #{@barb_dual_load}") if $debug_mode_ct
```

Validate: 
```
   def assert_that_analyze_combo_is_valid(settings)
    return unless settings.barb_dual_load

    unless DRSkill.getxp('Bows') < 200 && DRStats.barbarian?
      error("You must be a Barbarian with over 200 skill in Bows to use barb_dual_load. Please set it to false in your yaml.")
    end
  end
```

Base YAML Setting:  `barb_dual_load: false`

Use Setting: `barb_dual_load: true`

**Comment by rpherbig** [comment]
Why did you use a new setting instead of the existing `dual_load`?

**Comment by jayRyan24** [comment]
The problem I'm trying to circumvent, and I could do it with dual_load and set a member variable too, is that the logic is checking for the Ranger spell being active to use Dual Load. This doesn't really work with Barbarians, so there needs to be a separate scenario for them. I'm definitely up to recommendations on how to fix it. Also also am checking some fail safes. The way it works now is that if they have Dual Load set, it just sets it and as long as they have the buff going, it works for them, but with Barbarians, there is no buff to readily check against, so I am checking that they are at minimum a barbarian and have at least 200 in Bows. Otherwise the logic will always spam Load Arrows first, regardless of whether or not they can use it.

**Comment by jayRyan24** [comment]
I can just do something like:

`  def dual_load?
    if DRStats.ranger?
	  @dual_load && weapon_skill == 'Bow'	
    elsif DRStats.barbarian?
      @barb_dual_load = @dual_load && weapon_skill == 'Bow' && DRSkill.getxp('Bows') < 200 && DRStats.barbarian?
	else
	  return false
  end
  
  def barb_dual_load?
    @barb_dual_load
  end`

```
#	@barb_dual_load = settings.barb_dual_load
#    echo("  @barb_dual_load: #{@barb_dual_load}") if $debug_mode_ct
```
    `@barb_dual_load = false`

**Comment by rpherbig** [comment]
I think you can use the existing `dual_load?` method and not need to introduce a barb-specific one.

There's probably a way to make this prettier, but the gist of it would be:
`@dual_load && weapon_skill == 'Bow' && (DRSpells.active_spells['See the Wind'] || (DRStats.barbarian? && DRSkill.getxp('Bows') > 200))`

**Comment by jayRyan24** [comment]
Yeah, didn't see that, lol. Pretty obvious too.

**Comment by jayRyan24** [comment]
Updated logic:

```
      if game_state.dual_load? && (DRSpells.active_spells['See the Wind'] || (DRStats.barbarian? && DRSkill.getrank('Bow') > 200))
        pause 0.5 until loadReturn = bput('load arrows', 'You reach into', 'already loaded', 'Such a feat would be impossible without the winds to guide', 'but are unable to draw upon its majesty')
		if loadReturn == 'but are unable to draw upon its majesty' || 'Such a feat would be impossible without the winds to guide'
		  pause 0.5 until bput('load', 'You reach into', 'You carefully load', 'already loaded')
		end
	  else
        pause 0.5 until bput('load', 'You reach into', 'You carefully load', 'already loaded')
      end
```

This is the only change in the entire file for combat-trainer.

**Comment by rpherbig** [comment]
I suggest moving all of the logic in that first `if` into `GameState::dual_load?`. I'm not sure if there's a clean way to avoid defining the 'load' bput twice.
