### ISSUE TITLE
Add 3-swap weapons to combat-training

### ISSUE THREAD

**Issue by hwoo79** [rpherbig/dr-scripts#87]
Riste (LE,LB,2HB) and half-handled riste (ME,MB,2HB), maybe others.

Riste messaging:

>wield riste
You draw out your riste from the leather pack, gripping it firmly in your right hand and balancing with your left.
>swap riste
You switch your riste so that you can use it as a heavy blunt weapon.
>swap riste
You switch your riste so that you can use it as a heavy edged weapon.
>swap riste
You switch your riste so that you can use it as a two-handed blunt weapon.

**Comment by rcuhljr** [comment]
e2d9228557a40f8fe7ff5fd3669c5d634e04b5bc
