### ISSUE TITLE
Theurgy - tap my incense in my backpack

### ISSUE THREAD

**Issue by Brachius** [rpherbig/dr-scripts#882]
**PROBLEM:** 
When theurgy does 'tap my incense in my backpack' AND you have no incense in your backpack, it taps Inoo when he's in the room. I heard Inoo was also asking that we fix this.

**POSSIBLE SOLUTION:** 
Change it to 'look my incense in my backpack'. The look verb also does not have issues with names starting with My who happen to be in the same room.

**MESSAGING:**
**Incense is present:** You see nothing unusual (Tested with Inoo and Mycena in the same room)
**Incense is not present:** I could not find what you were referring to.

**Comment by rpherbig** [comment]
Unfortunately, `look` has a very large number of responses, so we may have to go with only checking the negative case.

**Comment by Brachius** [comment]
Sounds good to me. He gets tapped a lot cause he sits at that safe zone a lot of people use.
