### ISSUE TITLE
Patch Notes via Dependency

### ISSUE THREAD

**Issue by ohbeanz** [rpherbig/dr-scripts#892]
Have it so patch notes are echoed in the client window after dependency is updated.

**Comment by rpherbig** [comment]
Would it be useful enough if the notes were a list of commit messages?

**Comment by ohbeanz** [comment]
Unfortunately, that's not always... helpful.  _goes and takes a screenshot of your and E's commit messages at 3:00am_

However, it could be a start if want it to be fully automated. Or, contributors get in the habit of adding notes to a common patchnotes/changelog file.

**Comment by rpherbig** [comment]
It might force contributors to make better commit messages :)

**Comment by drboldwin** [comment]
haha instead of the ever vague update-<script>?

**Comment by rpherbig** [comment]
We release a milestone maybe every month, which feels too late to me. But if there's real interest in this, I think it's more important we try something and then fine-tune it :)

**Comment by drboldwin** [comment]
I do think patch notes are nifty.  Though I tend to just look over yesterdays commits every morning to get an idea of things that changed, I have the added benefit of being able to look at the code if a proper summary wasn't written while others may not feel comfortable enough to do that.
