### ISSUE TITLE
Theurgy - flag delete

### ISSUE THREAD

**Issue by drboldwin** [rpherbig/dr-scripts#899]
```
--- Lich: error: wrong number of arguments (0 for 1)
    events:32:in `delete'
    theurgy:42:in `comm_tamsine'
--- Lich: theurgy has exited.
--- Lich: go2 active.

```
Believe this is an issue with this line:
`Flags.delete['theurgy-tamsine']`

Not sure why - I'm fairly certain .delete is able to be used with Flags...
does it need to be Flags['theurgy-tamsine'].delete instead?

**Comment by rpherbig** [comment]
Is delete a method that needs () ?

**Comment by rpherbig** [comment]
@rcuhljr reported this too: http://pastebin.com/M099ME40

I can't reproduce it, but I'm 99% sure from some ad hoc testing that the parentheses are the problem. I'll push that and see if it fixes it.
