### ISSUE TITLE
Add further Barb Analyze Combo support.

### ISSUE THREAD

**Issue by jayRyan24** [rpherbig/dr-scripts#902]
Due to suggestions from Everics, I plan to expand on the Analyze Flame support to include Analyze Damage and Analyze Accuracy. 

These buffs are on a 6-7 minute timer, I will add it so that they are reused on a 7.5 minute cycle with Flame filling in the gaps. The analyze_combo_type will be changes from a string input to a boolean value, use_barb_combos. 

The logic has been implemented, going through testing now.

**Comment by jayRyan24** [comment]
Here is the logic so far. Testing has been proven successful. If for some reason you try and Analyze Damage or Accuracy before the in-game cooldown has expired, it will handle it. Please look through and help me with cleaning the logic. I tried to use the code that is already established, and I couldn't figure out a way to do the if else more cleanly, maybe you guys can. This is pretty much all the code change. 

  ```
def update_analyze_array
    timer = cooldown_timers["accuracy"]
    if (!timer || (Time.now - timer).to_i > 450 && DRSkill.getrank('Expertise') >= 50)
      result = bput("analyze accuracy", 'cannot repeat it so soon', 'Analyze what\?', 'by landing a .*')
      waitrt?
      case result
      when 'cannot repeat it so soon'
        cooldown_timers["accuracy"] = Time.now
        return
      when 'Analyze what?'
        fput('face next')
        return []
      end
      text = result.match(/by landing a (.*)\.$/).to_a[1]
      @analyze_combo_array = list_to_nouns(text)
      cooldown_timers["accuracy"] = Time.now
      return
    end 
    
    timer = cooldown_timers["damage"]
    if (!timer || (Time.now - timer).to_i > 450 && DRSkill.getrank('Expertise') >= 125)
      result = bput("analyze damage", 'cannot repeat it so soon', 'Analyze what\?', 'by landing a .*')
      waitrt?
      case result
      when 'cannot repeat it so soon'
        cooldown_timers["damage"] = Time.now
        return
      when 'Analyze what?'
        fput('face next')
        return []
      end
      text = result.match(/by landing a (.*)\.$/).to_a[1]
      @analyze_combo_array = list_to_nouns(text)
      cooldown_timers["damage"] = Time.now
      return
    end 

    result = bput("analyze #{@analyze_combo_type}", 'Analyze what\?', 'by landing a .*')
    waitrt?

    case result
    when 'Analyze what?'
      fput('face next')
      return []
    end

    text = result.match(/by landing a (.*)\.$/).to_a[1]
    @analyze_combo_array = list_to_nouns(text)
  end
```

I did also try and follow convention and changed the array shifting to this:

 ```
 def next_combo_action
    @analyze_combo_array.shift
  end
```
```
def melee_attack_verb
    if use_weak_attacks?
      brawling? ? 'punch' : 'jab'
    elsif !@analyze_combo_type.nil? && !offhand? && !brawling?
      update_analyze_array if @analyze_combo_array.empty?
      next_combo_action
    else
      'attack'
    end
  end
```

**Comment by jayRyan24** [comment]
Here is a substantial logfile from combat. It's about 2000 lines. It has from start, renewal of buff, and then manually restarting the trainer. 

http://pastebin.com/atsBzZcy

**Comment by jayRyan24** [comment]
This might also be something we can handle with Flags, though I'm not terribly sure if this would work fully. 

```
  def initialize
    echo('New ComboProcess') if $debug_mode_ct
    Flags.add('ct-accuracy', 'You sense your ability to land deadly blows decrease')
    Flags.add('ct-damage', 'You sense your combat accuracy decrease')
  end
```

Just a thought. We also know it's pretty much exactly 7 minutes and once the first buff wears off I get another 2-3 combos off before it renews, giving it a nice padding for error, but this can probably be done with Flags.

**Comment by rpherbig** [comment]
A few thoughts:

- Do you feel that a barb using analyze flame would always want to also use damage and accuracy? Maybe an array would be better?

- If you are going to deprecate a setting (analyze_combo_type in this case), I highly recommend you write a validator that outputs a warning saying they should change to the new format. Check out validate.lic for some examples.

- Related to the validator, barbs are going to 'suddenly' stop seeing analyze flame stop working (until they move to the new setting). You might consider leaving the old code in, based on the old setting, and output a message saying to move to the new format. We can remove the old code after a week.

- There is a lot of repeated code between the accuracy and damage blocks. How about a helper method? I think the two inputs would be expertise rank and combo type.

- Why do you return from `update_analyze_array` when you see 'cannot repeat'? Why not instead fall through to the next analyze type?

**Comment by jayRyan24** [comment]
**Do you feel that a barb using analyze flame would always want to also use damage and accuracy? Maybe an array would be better?**

I thought about the array:

 barb_combos:
   - flame
   - accuracy
   - damage

My thoughts were to do this first, but then I figured if I'm using flame, I'm not worried about killing to quickly. I think accuracy will always be something people would want to use, damage would be something that would be the maybe, but if I'm running combos, I'm probably not worried about killing to fast. 

**If you are going to deprecate a setting (analyze_combo_type in this case), I highly recommend you write a validator that outputs a warning saying they should change to the new format. Check out validate.lic for some examples.**

**Related to the validator, barbs are going to 'suddenly' stop seeing analyze flame stop working (until they move to the new setting). You might consider leaving the old code in, based on the old setting, and output a message saying to move to the new format. We can remove the old code after a week.**

This is fine, I haven't worried about any of the validator stuff yet. 

**There is a lot of repeated code between the accuracy and damage blocks. How about a helper method? I think the two inputs would be expertise rank and combo type.**

Thought about this too, I definitely need to break it out, and go to an if-else thing.

**Why do you return from update_analyze_array when you see 'cannot repeat'? Why not instead fall through to the next analyze type?**

I tried to figure this out in Ruby and the only two I could find were break and next, which didn't work for me. This is almost why I asked for you to look it over and help with the logic, I couldn't find this exact thing to do in Ruby.

**Comment by jayRyan24** [comment]
Something like this?:

```
  def setup_combo_array(combo_type)
    result = bput("analyze #{combo_type}", 'cannot repeat', 'Analyze what\?', 'by landing a .*')
    waitrt?
    case result
    when 'cannot repeat'
      cooldown_timers[combo_type] = Time.now
      return
    when 'Analyze what?'
      fput('face next')
      return []
    end
    text = result.match(/by landing a (.*)\.$/).to_a[1]
    @analyze_combo_array = list_to_nouns(text)
    return
  end
```


```
  def update_analyze_array
    accuracy_timer = cooldown_timers["accuracy"]
    damage_timer = cooldown_timers["damage"]
    if (!accuracy_timer || (Time.now - accuracy_timer).to_i > 450 && DRSkill.getrank('Expertise') >= 50)
      setup_combo_array("accuracy")
      return 
    elsif (!damage_timer || (Time.now - damage_timer).to_i > 450 && DRSkill.getrank('Expertise') >= 125)
      setup_combo_array("damage")
      return
    else 
      setup_combo_array("flame")
  end
```

**Comment by rpherbig** [comment]
That's a step in the right direction, but I still see a fair bit of 'duplicated' code (not in the strictest sense, but code that could be extracted to lend clarity). Specifically, the timer and expertise checks.

I think the concern about not checking multiple analyze types still remains. That is, with the if/else structure, if 'accuracy' is attempted and fails, you do not try the next one in the list. To solve that, I think setup_combo_array needs to return a bool that indicates whether or not we should try the next combo. If it returns false, we retry.

Let me know what you think of this:

```
  def perform_analyze?(combo_type, expertise_requirement)
    return false if @cooldown_timers[combo_type] && @cooldown_timers[combo_type] > 450
    return false if DRSkill.getrank('Expertise') < expertise_requirement

    result = bput("analyze #{combo_type}", 'cannot repeat', 'Analyze what\?', 'by landing a .*')
    waitrt?
    case result
    when 'cannot repeat'
      cooldown_timers[combo_type] = Time.now
      return false
    when 'Analyze what?'
      fput('face next')
      return true
    end
    text = result.match(/by landing a (.*)\.$/).to_a[1]
    @analyze_combo_array = list_to_nouns(text)

    true
  end
```


```
  def update_analyze_array
    { 'accuracy' => 50, 'damage' => 125, 'flame' => 0).each do |type, expertise|
        break if perform_analyze?(type, expertise)
    end
```

**Comment by jayRyan24** [comment]
That's a really good fix for that, but I want to see about moving down the road of setting a flag for them to use instead of a timer.

**Comment by jayRyan24** [comment]
Let me get this working first, then I'll look into going to your update. For now though, how do I set a flag to initialize to true? I cannot find any info on Flags for Ruby. Point me in the right direction? 

```
  def update_analyze_array
    if (Flags['ct-accuracy'] && DRSkill.getrank('Expertise') >= 50)
      setup_combo_array("accuracy")
      Flags.reset('ct-accuracy')
      return 
    elsif (Flags['ct-damage'] && DRSkill.getrank('Expertise') >= 125)
      setup_combo_array("damage")
      Flags.reset('ct-damage')
      return
    else 
      setup_combo_array("flame")
    end
  end
```

**Comment by rpherbig** [comment]
Flags are a custom construct, defined in `events.lic`. To initialize one to true, you simply set it to true after adding it:

```
Flags.add("ct-Foo", message)
Flags["ct-Foo"] = true
```

Flags would also be easy to use in my example, just replace the timer line. Since Flag names are just string, you can interpolate the name of a Flag pretty easily: `if Flags["ct-#{combo_type}"]`.

**Comment by jayRyan24** [comment]
I figured they weren't since Flags get highlighted in Sublime, lol. I'm like going crazy, didn't find it in Common. My brain!

**Comment by jayRyan24** [comment]
OK, I got it working without timers now. Flags are set and reset. This also works when combat-trainer is restarted during combat. So, if you hunt the same target more than once and just switch YAMLs like I do, it will support that. I will add in the changes you made.

**Comment by jayRyan24** [comment]
All done, I'll had the validation stuff when I get back later. Currently running it with the changes you suggested.

**Comment by jayRyan24** [comment]
OK, have tested this and all the transitions I can think of. Let me know what needs to be fixed. 

combat-trainer.lic:  http://pastebin.com/tVwx7yxE
validate.lic:  http://pastebin.com/sZbhu3ff

**Comment by rpherbig** [comment]
Can you submit a pull request? That would make it a lot easier to review.
