### ISSUE TITLE
Please add configurable casting thresholds to combat-trainer

### ISSUE THREAD

**Issue by mithgrek** [rpherbig/dr-scripts#908]
With recent attunement changes, maintaining a lower attunement level is no longer required to optimize regen.  The default levels cause issues, especially with magic tertiaries, where it will fail to complete buffs.

Also, since charging cambrinth is not smart enough to detect when item is already full, it will fail repeatedly as it will never have enough mana to complete.

Please change the current mana thresholds in check_training, check_buffs, and check_offensive to configurable items in yaml.  Defaults can be whatever you feel is best, although IMHO increasing these makes sense with attunement changes.

**Comment by rpherbig** [comment]
Would you want to see each threshold configured individually? Or would one setting work?

**Comment by mithgrek** [comment]
I think each of the three thresholds is the cleanest.  If you just pick one, then you're assuming that everyone else would want the same priority.  It's only 3 settings that I noticed

**Comment by rpherbig** [comment]
I'll add offensive_spell_mana_threshold, training_spell_mana_threshold, and buff_spell_mana_threshold tonight.
