### ISSUE TITLE
Please enhance cambrinth charging to stop charging if full

### ISSUE THREAD

**Issue by mithgrek** [rpherbig/dr-scripts#910]
Should be staightforward, right?  Instead of blind charging 16,16,16 (or whatever), stop if cambrinth is full for some reason, and stop wasting attunement and roundtime.

This exacerbates the low mana issue prompting the issue in combat-trainer, but useful for common functions.

**Comment by rpherbig** [comment]
The helper is in common-arcana, just need to roll it out everywhere in a few days.

**Comment by mithgrek** [comment]
Awesome, thank you.
