### ISSUE TITLE
Crossing-trainer should only stop cyclics if they are a) hazardous in-town, or b) another cyclic will be trained by crossing-training

### ISSUE THREAD

**Issue by mithgrek** [rpherbig/dr-scripts#911]
Title says it all.  There's no need to stop a cyclic that character may have running for other reasons.

**Comment by jandersson** [comment]
It would be nice to have RoG always running in combat and during training on a necromancer as it hides their transcendental buffs among other things

**Comment by drboldwin** [comment]
I'm fairly certain Hunting-buddy is going to stop your cyclic before crossing-training get's to it if you are running training-manager.  If you are running crossing-training standalone this applies though.

That being said, I don't really understand why you want this to run constantly instead of being refreshed and getting extra learning from that.

Either way I'll try to think of the best way we could address this and we can try to go from there.

**Comment by jandersson** [comment]
The issue with RoG is that it protects the necromancer from outing themselves, so releasing it and then doing sell-loot could be considered harmful

**Comment by mithgrek** [comment]
I often stop and refresh it.   It's annoying when I refresh it, but then have crossing-trainer stop it again.  I never noticed hunting-buddy stopping it, but I use hunting-buddy far less often on my paladin, which is the only character with a cyclic I keep up.

**Comment by arkrail** [comment]
I have a young bard who has issues with this, GJ is one of his crossing training cyclics, and if it leaves this spell up when he goes hunting, then he cannot cast his own TM spell, which causes him to repeatedly cast BoS, and never gets to use his debilitation cyclic.

**Comment by mithgrek** [comment]
Do you have an issue with the cyclics as they currently are, or my request
for crossing-trainer (and only crossing-trainer) to stop running cyclics
only if they are hazardous or another cyclic will be trained.

Current behavior, *when crossing-trainer starts* is to stop all cyclics,
etc.  I don't think crossing-train stops cyclics when it stops... maybe
training-manager does, too, but I haven't checked.

**Comment by arkrail** [comment]
As they currently are.  Sorry was linked to this when I was speaking on lnet about this issue, didn't mean to combine two issues.
