### ISSUE TITLE
Room in Orc_Bandits does not work

### ISSUE THREAD

**Issue by Sagadin** [rpherbig/dr-scripts#917]
Room 8736 returns as unreachable.  Please remove it from base-hunting.

Mistwood Forest, Deer Trail - 8649]
The forest crowds up against the base of a tall cliff to the east.  Angling out to loom over the huddled forest below, the sandstone surface looks almost impossible to climb.  High overhead, a raptor circles as it hunts.  
Obvious paths: north, southwest, west, northwest.
>
[go2: travel time: 0:00:00]
--- Lich: go2 has exited.
Out of the corner of your eye, you notice a long-fanged warcat trying to sneak east.
You notice a long-fanged warcat trying to edge quietly past you.
[hunting-buddy: Failed to navigate to room 8736, attempting again]
>
--- Lich: go2 active.
[go2: ETA: 0:00:00 (2 rooms to move through)]
[go2]>northwest
You go northwest.
[Mistwood Forest, Deer Trail - 8641]
Past years' leaves lie crumpled and brown beneath the sheltering branches of the mistwood trees.  Every footstep and shift in position evokes a dry crackling noise as the fragile remains crumple underfoot.  
Obvious paths: north, east, southeast, southwest, northwest.
>
[go2]>southeast
You go southeast.
[Mistwood Forest, Deer Trail - 8649]
The forest crowds up against the base of a tall cliff to the east.  Angling out to loom over the huddled forest below, the sandstone surface looks almost impossible to climb.  High overhead, a raptor circles as it hunts.    a long-fanged warcat that is trying to remain hidden.
Obvious paths: north, southwest, west, northwest.
>
[go2: travel time: 0:00:00]
--- Lich: go2 has exited.
[hunting-buddy: Failed to navigate to room 8736, attempting again]
--- Lich: go2 active.
[go2: ETA: 0:00:00 (2 rooms to move through)]
[go2]>northwest
You go northwest.

**Comment by rpherbig** [comment]
Does that room not exist? Or does it exist and the map/pathing is messed up?

**Comment by Sagadin** [comment]
It appears to be out of range for this hunting area.  If it does exist, it doesn't seem to be around here.  There is a room 8637, but that is the room that crosses over the ravine, so it probably is not a room we would want to include in the hunting rooms as it sees a fair amount of traffic and use.
