### ISSUE TITLE
Find nearest tannery, gemshop, npc_healer, rather than using hometown setting

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#919]
Since we have a file with room id's for these services, it might be useful to find the nearest shop rather than basing everything off of a hometown setting. I think the only thing useful to have set is a bank, since I think many people want to do banking in a specific location. We could possibly have a setting 'use nearest bank' for people who just want to run their errands as quick as possible

**Comment by drboldwin** [comment]
the only trouble with using find nearest I encountered is that go2 for example, on the leth side of the ferry, thinks the crossing bank is closer then the leth bank because it's less rooms away, but not all rooms are =

**Comment by rcuhljr** [comment]
It should be sorting by travel time, I'll check it out.

**Comment by jandersson** [comment]
I think the .timeto in rooms calling the a ferry script should be the length of time it takes to cross. If thats correct then the distance calculation should choose the leth bank.

The big benefit of this is that I could call ;safe-room and get healed by a local NPC empath instead of running halfway around the world to dokt if I'm in shard with a hometown of Crossing. Ideally this would remove the need to even declare a hometown (perhaps we might want to declare a home bank though, but i personally would prefer to just use the closest bank)
