### ISSUE TITLE
Missing ritual failure messaging

### ISSUE THREAD

**Issue by cynesis** [rpherbig/dr-scripts#921]
You cannot harvest useful material from the corpse unless it is preserved first.

Occurs if the prior preserve has failed.

**Comment by rpherbig** [comment]
Does that mean the preserve can be retried? If so, if you provide the messaging we can have combat-trainer retry preserve.

**Comment by rpherbig** [comment]
The easier way to fix this would be to retry the preserve when it fails, rather than wait until trying a different ritual fails. Does preserve have a failure message?

**Comment by cynesis** [comment]
> perf pres on gryph
You bend over the gryphon's corpse, but are unable to discern where to direct your thanatological expertise in order to properly preserve the corpse.
Roundtime: 4 sec.
R> 
You are still rather wet, but drying off nicely.
> perf harv on gryph
You cannot harvest useful material from the corpse unless it is preserved first.
> 
The hiss of bile-green droplets drowns out nearly all other sound as acidic showers erupting from around you soak everything in sizzling wetness!
> perf diss on gryph
You realize after a few seconds that you don't have enough thanatological expertise to trace the lines of this corpse's former life force.
Roundtime: 10 sec.
