### ISSUE TITLE
Common-arcana: Commonize casting using data from discern

### ISSUE THREAD

**Issue by jandersson** [rpherbig/dr-scripts#928]
It would be nice to have this accessible to script writers who want the user to leave the prep amount unspecified and default to using discern data. 

Anecdotally, I've been drafting up a script to locate another player and then also grab the room ID. When I cast locate I always want to max prep so that failure to locate due to casting strength is never an issue. If discern casting was available like it is in crossing-trainer, then I could specify the locate spell data, and leave out the mana values, defaulting to discern. I would like to do this with my combat buffs as well, so that I know that my duration and spell strength is always at maximum. Its laziness really, but I would prefer this over updating my spell mana values every so often.

**Comment by rpherbig** [comment]
I think it is reasonable to always treat the 'no mana given' case as meaning 'go ahead and use the discern value'.

**Comment by jandersson** [comment]
As a user I think this would be a convenient addition. It is a reasonable default in my opinion, because I typically want my spells to be as effective as possible. There will be the case that we overprepare (casting with 100 mana) but I think the user should establish their preferences.

**Comment by drboldwin** [comment]
I think the discern routine splits the mana between 3 cambrinth charges.  People may not always want to spend that much time in combat prepping their cambrinth.  I don't think this is a reason to not do this I just mention it so maybe we could do something like
mana: discern
camb-x: ##

The ## being how many times you want to charge the camb (for discern to calculate with)

Though this may just be getting overly complicated at this point.
