### ISSUE TITLE
Pick should save harvested parts

### ISSUE THREAD

**Issue by korinthyn** [rpherbig/dr-scripts#929]
It would be nice to have an option to saved harvested parts from boxes.

**Comment by rpherbig** [comment]
Out of curiosity, what can you do with harvested parts? Epedia doesn't have any info...

**Comment by jandersson** [comment]
Thieves used to be able to store them in a special gempouch-like container and sell them at pawn shops. I don't know if this is still a thing

**Comment by Tarhish** [comment]
An old issue, but ;pick does store these now.  Technically anyone can sell the parts you harvest, but it only seems at all worthwhile for thieves.  My thief seems to get a lot more for them than anyone else?  I suppose that's a info theory concern, where seeing someone harvesting traps doesn't automatically out them.

Anyway, I think we can close this.
