### ISSUE TITLE
Item that cannot be stowed causes loop

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#93]
To simplify the logic, the current process is "turn in ticket, stow item, repeat" until all tickets are gone, and only then get/wear worn items. This breaks in the case of an item that cannot be stowed (i.e. a large worn weapon).

Instead we should wear or stow when an item is retrieved. This means that we now have to figure out which item the ticket was for, which we could ignore before. Can the equipment manager help with this?

`
>
[crossing-repair]>get my ticket
You get a Catrox repair ticket from inside your backpack.
>
[crossing-repair]>give my ticket to Catrox
You hand Catrox your ticket and are handed back a steel bardiche.
>
[crossing-repair]>stow right
The bardiche is too long to fit in the harness.
>
[crossing-repair]>stow right
The bardiche is too long to fit in the harness.
>
[crossing-repair]>stow right
The bardiche is too long to fit in the harness.
`

**Comment by rcuhljr** [comment]
Use `stow_weapon` in the equipment manager to avoid this. If you want to be fancy develop a snapshot gear in equipment manager and use that to determine which pieces get worn and which get stowed.

**Comment by rpherbig** [comment]
I think this will require #65 and/or #74 to be done first.

**Comment by rpherbig** [comment]
Fixed in c139299b25a327577036dbe5795f751b21c252c1
