### ISSUE TITLE
Make escort stow armor before swimming the rivers, and rewear it after crossing.

### ISSUE THREAD

**Issue by arkrail** [rpherbig/dr-scripts#940]
A few of us are having issues with escort choosing to swim over the barges/ferries.  Our athletics meet the bare minimum, but our armors cause too much hindrance to reliably get across.  This causes go2 to timeout and makes travel more complicated.  If escort could be tweaked to remove armor, such as perhaps creating a swimming/climbing gearset, and having equipment-manager called similar to how stealing is done, it would alleviate allot of this issue.

**Comment by rcuhljr** [comment]
https://github.com/rpherbig/dr-scripts/issues/548

**Comment by Sagadin** [comment]
We should be sure to make this optional, as there are many who could be just as, if not more hindered by the increased encumbrance from removing armor than the hindrance from wearing it.

**Comment by rcuhljr** [comment]
Encumbrance from removing armor has less effect than wearing it to swim everytime I've tested.
