### ISSUE TITLE
Infinite Climb Practice with Crossing-Trainer

### ISSUE THREAD

**Issue by ohbeanz** [rpherbig/dr-scripts#942]
My alt just keeps climbing, and climbing, and climbing. DRinfomon is not trusted. Dependency is running. Skill recorder is running.. and yet, continuous climbing. It seems as though DRSkill is returning false information:

http://pastebin.com/VGS3FRMV

**Comment by rcuhljr** [comment]
Do you run pretty exp or something else that messes with your exp messages?

**Comment by ohbeanz** [comment]
>;listall
--- Lich: teach, empathy, events, skill-recorder, roomnumbers, dependency, keepalive, tending, listen, drinfomon, spellmonitor, textsubs, afk, training-manager, hunting-buddy, combat-trainer, lnet

**Comment by rcuhljr** [comment]
well pretty-exp is something doesn't show up in list, it runs once and screws everything up.

**Comment by ohbeanz** [comment]
Pretty-exp was most likely the culprit! Thanks a lot, E! Closing.
