### ISSUE TITLE
Crossing_Training:  Scholarship

### ISSUE THREAD

**Issue by FeltzerDR** [rpherbig/dr-scripts#949]
Would it be possible to have a setting to select using Raven's Court to learn Scholarship instead of Studying my Book?  I seem to lock mine with one pass-through (long RT though) easier than using the book.  It might be my low levels.

Also, can play zills while studying the items inside there.

**Comment by rpherbig** [comment]
Are you referring to studying the art there? I didn't realize that taught Scholarship, neat.

Studying the art has long RTs, are you sure it's more time efficient than reading a book?

**Comment by FeltzerDR** [comment]
It seems so for me, I'll try to test it.

**Comment by rcuhljr** [comment]
Not having to buy a crafting book is a not insignificant boost.

**Comment by wscherer420** [comment]
I uploaded the Raven's Court Stormfront Script to the Lich Repository under "raven".  password is 1234 in case you want to use it and update it.  It doesn't run until mindlocked, it runs until the character has gone through the court appraising and studying art.  Which only gets you partially to mindlocked.  But it does also trains appraisal the same.  I agree it trains faster than the book.  I have scholarship currently around 300 and it still trains well.

**Comment by rcuhljr** [comment]
Should be working now if you're not a necro and training in the crossing.
