### ISSUE TITLE
Issue purchasing yarn when hometown set to Riverhaven

### ISSUE THREAD

**Issue by ghost** [rpherbig/dr-scripts#951]
Running a knitting workorder when the hometown is set to Haven has an intermittent bug.  The script checks for lirums to determine if I have enough money to buy yarn, but runs to Crossing to purchase the materials, even though I may not have enough kronar to buy the yarn

**Comment by adamgoerdt** [comment]
Just noticed that this issue occurs with mining buddy attempting to purchase deed packets as well

**Comment by rpherbig** [comment]
The deed packet part was just fixed in PR #1583.
