### ISSUE TITLE
;dependency install failed

### ISSUE THREAD

**Issue by nadams1073** [rpherbig/dr-scripts#953]
Followed startup guide... downloaded ... trusted then...

>;dependency install
[dependency: Installing rest-firebase gem, this may take a few minutes.]
>
--- Lich: error: Could not find a valid gem 'rest-firebase' (~> 1.1.0) locally or in a repository
	C:/Ruby200/lib/ruby/2.0.0/rubygems/dependency_installer.rb:308:in `find_spec_by_name_and_version'
	C:/Ruby200/lib/ruby/2.0.0/rubygems/dependency_installer.rb:109:in `available_set_for'

Any help would be appreciated, thanks

**Comment by rcuhljr** [comment]
There's a known issue with the ruby environment currently, sorry about that but you can fix it with these instructions here. https://github.com/rpherbig/dr-scripts/wiki/Solving-RubyGems-Error

**Comment by nadams1073** [comment]
Thanks, that led me in the right direction. Only one thing seemed off. When following the above fix, it told me to put the certificate into C:\Ruby200\lib\ruby\site_ruby\2.0.0\rubygems\ssl_certs folder, but that didn't exist. The path I used was C:\Ruby200\lib\ruby\2.0.0\rubygems\ssl_certs. Restarted Lich and everything worked out. Thanks again.
