### ISSUE TITLE
Cannot Offhand Throw

### ISSUE THREAD

**Issue by Tinen** [rpherbig/dr-scripts#955]
I recently switched to using Combat Trainer and it is excellent. The one feature I find it lacking is the ability to perform offhand throwing. 

I think this could possibly easily be accomplished by giving Offhand a modifier that allows it to access the throw training, only it would check Offhand Weapon skill, and need to have Off added to the attack verb.

**Comment by rcuhljr** [comment]
Added, look at my yaml for an example [here](https://github.com/rpherbig/dr-scripts/blob/5b884d256e9c79e06917c3fdca9d151d7e30dd89/profiles/Etreu-back.yaml#L32-L37) Note that I set bola for the offhand weapon and Light Thrown as the offhand_thrown value.

**Comment by Tinen** [comment]
Thanks! Awesome work!
