### ISSUE TITLE
Track how long each item will take instead of glancing at tickets every 30 seconds

### ISSUE THREAD

**Issue by rpherbig** [rpherbig/dr-scripts#96]

**Comment by rpherbig** [comment]
This would also require us to determine which ticket belongs to which item.

**Comment by rpherbig** [comment]
Now that #92 is fixed, I don't know if I care too much about doing this. The overall repair process is still limited by the item with the longest repair time.

@rcuhljr Do you care? You were the originator of this idea.

**Comment by rcuhljr** [comment]
It still seems like a nice improvement, but may not be worth the effort.

**Comment by rpherbig** [comment]
We have higher priority things to work on.
