### ISSUE TITLE
combat-trainer crashes with error

### ISSUE THREAD

**Issue by reithir** [rpherbig/dr-scripts#965]
Was working on a bunch of back training weapons with combat-trainer, when after killing a critter (mountain giant), got this error:

```
--- Lich: error: no implicit conversion of Array into String
	equipmanager:71:in `=~'
	equipmanager:71:in `block in item_by_desc'
```

Reproduced several times, it works fine a few cycles through all the weapons and then crash. I'm not sure what you need to track down this error, let me know and glad to provide you any details or data needed.

**Comment by rpherbig** [comment]
Were there any more lines to that error?

Can you link us to a pastebin of your YAML file?

**Comment by reithir** [comment]
http://pastebin.com/f6FSHJQk
http://pastebin.com/WePFRRJX

These are my two yamls files, the error occurred when I called the 'backtrain' file (second link). I actually changed these up a bit this evening (fewer weapons), let me try it out now and see if it still spits the error. Thanks for investigating, ;validate returned no problems with my setup at the time.

**Comment by rpherbig** [comment]
In your back file's weapon_training, Brawling should be '', not [].

**Comment by reithir** [comment]
when I did that, validate spit an error at me about the gear listings; what does my "brawling gear" entry need to look like? this could cause my error, but my character definitely brawled successfully at one point

**Comment by rpherbig** [comment]
What's the error from validate?

All of my characters use '' for Brawling and validate does not report an error for any of them.

**Comment by reithir** [comment]
It's two single quotes right, not a double quotation mark? Here's the error:

[validate: Validating settings for 2 settings files]
[validate: Checking 29 different potential errors in file Reithir-setup.yaml]
[validate: Checking 29 different potential errors in file Reithir-backtrain.yaml]
[validate: ERROR:< Item in weapon_training could not be found in gear listings. 'Brawling: â€™â€™'  >]
[validate: All done!]

**Comment by rpherbig** [comment]
Two single quotes.

That validator should filter out empty strings. That output indicates you have some odd characters instead of single quotes (even if they appear to be single quotes in the text editor).

**Comment by reithir** [comment]
Got it working, all set; for some reason the "single quote" I was using was some weird doppelgänger single quote, I copied/pasted yours and fixed it. I'm all set, thank you!!

**Comment by rpherbig** [comment]
Excellent!
