### ISSUE TITLE
Workorders still not matching correctly with offered jobs

### ISSUE THREAD

**Issue by reithir** [rpherbig/dr-scripts#966]
Same problem as yesterday, even though the patterns I submitted are part of base-crafting.yaml, the work orders script still does not match up with shaping patterns I'm offered; does a match table in the script need to be updated? I'm about 500 in engineering, being offered pretty high skill bows of all three varieties. Let me know what other info you need or if I can help, thanks.

**Comment by rpherbig** [comment]
@reithir Are you still seeing this?

**Comment by reithir** [comment]
Just fired up ;crossing-training to check this out, and it looks like it's working great. Thanks! Sorry, got sidetracked onto another character and haven't checked on this lately. Thank you! Ready to close this one.
