### ISSUE TITLE
Update ;pick with lockpick cases (the kind that are basically big lockpick rings)

### ISSUE THREAD

**Issue by reithir** [rpherbig/dr-scripts#969]
This is the "lockpick case" that I currently have, it functions exactly like a lockpick ring but holds 50 picks instead of 25, otherwise it's totally the same:

https://elanthipedia.play.net/Item:Darkly_painted_lockpick_case_depicting_a_pair_of_emerald-eyed_panthers

Can the pick script be updated to check for "lockpick case" as well? Otherwise I think it will work fine!

**Comment by rpherbig** [comment]
As I do not have a lockpick case, can you give `pick` a run and help us identify where it does not work for a case?

**Comment by reithir** [comment]
Sure thing, running ;pick, first thing that pops up (not sure if this is related) is in the command to rummage through the box container, I get that as "rummage /B my duffel bag", not sure what the /B is. But it doesn't cause any problems.

From there everything goes well, it disarms and picks everything like it should, until the end when it tries to "app my lockpick ring" and doesn't get a recognized response and quits from there.

On a final note, what lockpick types does it know about and know how to stock? I use the "stout iron lockpicks" from the Shard pick shop, I like them. They might be no better than regular stouts though, haha

**Comment by rpherbig** [comment]
/B is the rummage flag to only look for boxes. That should be independent of case or ring.

Does `app my lockpick case` use the same messaging as appraising a ring?

**Comment by reithir** [comment]
Ooh I gotcha, I did not know that. Agree, it's not related and clearly working fine.

Yes, lockpick case appraisal looks much like that of the ring. Here is the output from my case right now:

The lockpick case looks to be holding 28 lockpicks and it might hold an additional 22.
It appears that the lockpick case can be worn attached to a belt.
You are certain that the lockpick case weighs exactly 10 stones.
You are certain that the lockpick case is worth exactly 7718 Kronars.
Roundtime: 8 seconds.

**Comment by rpherbig** [comment]
@reithir Since I don't have a lockpick case, I can't test this myself. Can you help me test this?

1. Make sure your case is missing at least 1 lockpick
2. Restart dependency,
3. Run `;common-items`
4. Run `;e DRCI.refill_lockpick_container(get_settings.lockpick_type, get_settings.hometown, 'case')`

**Comment by reithir** [comment]
Can do. I'll have to wait until tonight or tomorrow morning to do this, I just got to Toronto for the weekend, about to go to a cousin's wedding for who knows how many hours. I will ping you again when I can test it out per your instructions. thanks!

**Comment by reithir** [comment]
I just followed the steps you said, restarted dependency, ran ;common-items and this is what I got when I ran the final line:

>;e DRCI.refill_lockpick_container(get_settings.lockpick_type, get_settings.hometown, 'case')
--- Lich: exec1 active.
--- Exception: uninitialized constant DRCI
exec1:1:in `_script'
--- Lich: exec1 has exited.

Help?

**Comment by rpherbig** [comment]
I think you'll need to use `;en` instead of `;e`, so `;en DRCI.refill_lockpick_container(get_settings.lockpick_type, get_settings.hometown, 'case')`

**Comment by reithir** [comment]
that didn't work, said it couldn't find the script 'en'.

**Comment by rpherbig** [comment]
Ok, we'll have to do this the easy way. Add the new setting to your YAML, restart dependency, and run the `pick` script. I've pushed the change which shouldn't affect anyone but you. :)

**Comment by reithir** [comment]
Haha, got it. Wait what setting do I add to my yaml? You just gave me code to run, not a new setting; do I use something other than use_lockpick_ring?

**Comment by rpherbig** [comment]
Keep `use_lockpick_ring: true` and add `lockpick_container: case`.

**Comment by reithir** [comment]
Got it. Test complete, looks like it's working well! I think we can consider this closed, if any other errors crop up I'll open a new issue but I think we're done!
