### ISSUE TITLE
SHARD : Dor'na'torna for Hibarnhvidar missing from ;bescort ways travel

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#972]
Sorry if I am missing something but I didn't see it as an option? 

[The Spire, Chamber of Contemplation - 3777]
Four sheep-skin rugs are laid across the cold floor at the cardinal points of the room, providing places to sit with minimal discomfort.  Pale white streaks mar the otherwise pristine silvery-blue crystalline walls, clustered predominately on the northern wall.  You also see a white-streaked crystalline archway and the silvery-white shard Dor'na'torna.
Obvious exits: none.

**Comment by rpherbig** [comment]
I believe the input you want is `steppes`.

**Comment by Aurayn** [comment]
ah yes it was added.... much rejoicing ensues
