### ISSUE TITLE
Support for prioritizing which classes to listen to

### ISSUE THREAD

**Issue by reithir** [rpherbig/dr-scripts#979]
Just like the subject says, have a rank order list of classes you want such that crossing-trainer will select the highest priority class among multiple classes being offered.

**Comment by rpherbig** [comment]
Currently it sorts by lowest field experience, then lowest rank. In what order would we check for priority?

**Comment by rpherbig** [comment]
Note: `listen_skills` could serve this purpose, but is only used in smartlisten. It also does not include guild-specific skills (which `smartlisten` then manually adds in based on your guild). We should figure out how to handle those.

**Comment by reithir** [comment]
Right. That's not a bad way to sort but for me it usually just grabs onto a random weapon I'm not really working instead of like FA (way more skill in FA than backtrain weapons, but I don't work FA much, but I could use it to circle). We could leave it the way it is UNLESS it's overriden by either listen_skills or a new field like listen_priorities where you could define and rank some number of skills you would always prefer to listen to. I'm not familiar with smartlisten yet so I don't know what to say there. ;)
