### ISSUE TITLE
Combat-Trainer Failure - Can't identify Cause

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#980]
YAML File: http://pastebin.com/bcqCXh3P
Combat Log: http://pastebin.com/iJQA9X5P
;validate response: http://pastebin.com/P4WRYjVB

So all of a sudden i'm having issues with combat-trainer.  It doesn't appear like my weapons are being recognized. Went through my YAML with a fine tooth comb and nothing seems off.  Any ideas for me?

**Comment by rcuhljr** [comment]
Well throw dagger doesn't match throwing dagger in your gear list, make them use the same adjective.

You also have a space in front of `gear:` so it's treating your entire gear list like it's part of `hunting_info:`

**Comment by wscherer420** [comment]
pssshhh, awesome.  Yeah the spaces in front of the gear were it.  Appreciate the help.
