### ISSUE TITLE
Suggestion: Create Invasion/PvP version of Combat-Trainer

### ISSUE THREAD

**Issue by wscherer420** [rpherbig/dr-scripts#981]
It would be really cool if there was a version of combat-trainer that strictly utilized the buff spells, offensive magic, and attacks.  While removing the appraising, perceiving, and so forth that is also trained in combat trainer.  

I could see it used in PVP, Invasions, or against creatures you can barely manage to hunt where you can't spare a moment checking "hunt" and so forth.  Just an idea.

**Comment by rcuhljr** [comment]
Could this not just be accomplished by a yaml file that turns those off?

**Comment by wscherer420** [comment]
oh didn't realize they could be turned off.  Just reviewed the YAML file and i think i see where to make the adjustments.  Thanks!
