### ISSUE TITLE
Weaponsmithing recipes not working for workorder

### ISSUE THREAD

**Issue by reithir** [rpherbig/dr-scripts#991]
I'll need to paste in a log in a few minutes as soon as I try again, but it looks like workorder is breaking for weaponsmithing projects which are above the amount of volume in one store-bought bronze ingot (10 volume I think). It tries to start the work with just the one ingot and when it cannot, it goes pretty berserk. Will paste a log in momentarily...

**Comment by rcuhljr** [comment]
Weaponsmithing isn't supported without using custom ingots.

**Comment by reithir** [comment]
Ahh, oops. My only option to train forging is blacksmithing then? And by custom ingots you mean I have to already have a correct ingot ready and then I should just use ;forge?
